### ISSUE TITLE
the last-session field in the backend is not always updated

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#10]
This is an entry for a bug met a few months ago during a test, that could not be reproduced.

## Output of `haproxy -vv` and `uname -a`

```
haproxy-1.9-dev earlier than 1.9-dev10, no exact version known.
Linux, don't remember what exact version, should be irrelevant here.
```

## What's the configuration?

```
I don't have it anymore unfortunately. It was a test config so very basic, with a stats page, and did have a low "maxconn" setting on the servers (1 or 2 servers only).
```

## Steps to reproduce the behavior

1. inject enough HTTP traffic that the servers reach their maxconn value and that the backend always has some pending connections in the queue
2. open the stats page.

## Actual behavior

When the problem appears, the "last session" field for the servers and/or the backend doesn't evolve anymore, as if when picking a connection directly from the queue didn't update this field. This behavior is misleading because it can make one think that a server failed to process traffic for a while when this is not true, and result in unneeded troubleshooting.

## Expected behavior

The last session field should continue to reflect the fact that the servers and the backend continue to process connections.

## Do you have any idea what may have caused this?

No and I couldn't reproduce it outside of this environment when tested again later on 1.9-dev10.

## Do you have an idea how to solve the issue?

I think a code review should reveal a location where a last_sess update is missing when a connection is assigned to a server, and this will tell us in what exact situation the problem happens.

**Comment by TimWolla** [comment]
@wtarreau This one is only tagged 1.9 and nothing else. As 1.9 is going to receive the last release today maybe have a look whether this can / should / needs to be closed.

**Comment by wtarreau** [comment]
Closing now since 1.9 reached EOL.
