### ISSUE TITLE
Add a replace-uri http action

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#100]
In order to remove reqrep/rsprep etc, Tim figured that URI rewriting is still not trivial. We need to have a replace-uri action working exactly like replace-header, but on the URI instead of a header field. I'm willing to take this one for 2.0, and in any case I want to start to emit warnings with the reqXXX/rspXXX rulesets so that we can kill them in 2.1.

**Comment by git001** [comment]
It should be also respect the statement from Tim about backreferences in `regsub(...)` 
https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#7.3.1-regsub

Cite from https://www.mail-archive.com/haproxy@formilux.org/msg33780.html
```
The obvious `http-request set-path %[path,regsub(...)]` as suggested in
the docs for `http-request set-query` does *NOT* work, because the
`regsub` parameters cannot contain the closing parenthesis required for
capture groups.
```

Is it possible to use backreferences in  `regsub(...)` ?

**Comment by wtarreau** [comment]
now done in 2.0, closing.

**Comment by git001** [comment]
Is there any chance to add `http-response replace-uri ` also as there is a `res*`  in the current version also.

**Comment by TimWolla** [comment]
> Is there any chance to add `http-response replace-uri ` also as there is a `res*` in the current version also.

What would that do? There's no URI in the response.

**Comment by wtarreau** [comment]
On Wed, Jun 12, 2019 at 11:50:03AM -0700, Aleks wrote:
> Is there any chance to add `http-response replace-uri ` also as there is a `res*`  in the current version also.

There is no URI in a response, there's a status code instead :-)

Willy

**Comment by git001** [comment]
:thinking: Yes you both are right. sorry for the noise :man_facepalming:
