### ISSUE TITLE
Add a way to run health checks on websocket servers in haproxy 2.2+

### ISSUE THREAD

**Issue by brenc** [haproxy/haproxy#1009]
## What should haproxy do differently? Which functionality do you think we should add?

haproxy 2.2 deprecated sending headers at the end of an `option httpchk`:

```
[WARNING] 350/205429 (6405) : parsing [/etc/haproxy/haproxy.cfg:791]: 'option httpchk' : hiding headers or body at the end of the version string is deprecated. Please, consider to use 'http-check send' directive instead.
```

This was handy for monitoring websocket servers like so:

```
option httpchk GET /ws?healthcheck=true HTTP/1.1\r\nHost:\ foobar.net\r\nConnection:\ Upgrade\r\nUpgrade:\ websocket\r\nSec-WebSocket-Key:\ x3JJHMbDL1EzLkh9GBhXDw==\r\nSec-WebSocket-Version:\ 13
http-check expect status 101
```

There doesn't appear to be a non-deprecated way to do this in 2.2+. Doing this doesn't work:

```
option httpchk GET /ws?healthcheck=true HTTP/1.1
http-check send hdr Host foobar.net hdr Connection Upgrade hdr Upgrade websocket hdr Sec-WebSocket-Key x3JJHMbDL1EzLkh9GBhXDw== hdr Sec-WebSocket-Version 13
http-check expect status 101
```

`http-check send` overwrites the `Connection` header and sets it to `close` (per the docs). These are the headers my app receives when using this method:

```
{
  host: 'foobar.net',
  upgrade: 'websocket',
  'sec-websocket-key': 'x3JJHMbDL1EzLkh9GBhXDw==',
  'sec-websocket-version': '13',
  'content-length': '0',
  connection: 'close'
}
```

## What are you trying to do?

Run health checks on websocket servers.

## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.2.6-3709bd4 2020/11/30 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.6.html
Running on: Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unus
ed-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-fie
ld-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Ws
hift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=
1 USE_ZLIB=1 USE_NS=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL
 -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +
TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA
 +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATL
AS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw
-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_F
REEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app


# uname -a
Linux staging-proxy02 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```

**Comment by a-denoyelle** [comment]
Maybe a way to fix it would be to only replace a keep-alive value in the Connection header, and in this case allow to send 'Connection: Upgrade, close'.
However, I'm not sure about the behavior of the various websocket implementation with this specific value.

**Comment by a-denoyelle** [comment]
FYI, a commit was recently merged on master which permit to specify the Connection header on the http-check send directives. You should be able to use it for a websocket handshake check.

**Comment by wtarreau** [comment]
Bruno, is this solution sufficient at this point or is anything else needed ? I'd like to know if we can close the issue in fact :-)

**Comment by lfarkas** [comment]
i've got exactly the same problem. is there any way to fix it?
anyway what is the currently right way to define health check? since i write the get into the 2nd line in this way:
```
option httpchk
http-check send meth GET uri /ws ver HTTP/1.1 hdr Host server:15674 hdr Authorization Basic\ bW9uOnZpZHV4bW9uOTc2NDMx hdr Connection Upgrade hdr Upgrade websocket hdr Sec-WebSocket-Key haproxy hdr Sec-WebSocket-Version 13 hdr Sec-WebSocket-Protocol v12.stomp
http-check expect status 101
```
or should i write the method and the url to the option line?
anyway none of this solution works.

**Comment by brenc** [comment]
@wtarreau were you talking to me? If so, then I'd say that in theory this seems sufficient. Has this been added to 2.2? If so then I can test it to know for sure. I can't seem to find any mention of it being added to 2.2 anywhere.

**Comment by wtarreau** [comment]
@lfarkas @brenc I thought this was backported but it was not, as it was an improvement not a fix, and not explicitly marked for backporting, sorry. I'm attaching a backport of the 2.4 patch here, could you please test it ? If it's OK for you I'm fine with merging it.

@brenc sorry I confused you with a coworker who has almost exactly the same alias :-)

[0001-MINOR-check-do-not-ignore-a-connection-header-for-ht.patch.txt](https://github.com/haproxy/haproxy/files/5941924/0001-MINOR-check-do-not-ignore-a-connection-header-for-ht.patch.txt)

**Comment by brenc** [comment]
@wtarreau no prob! I applied the patch, recompiled, updated the config, and pushed everything out. Tested a few different scenarios. Checked the headers on the ws connection. Everything appears to be working as expected. Thanks!

@lfarkas see my original post in this ticket for the right config to use. I posted both the old way and new way of doing this check. You'll have to use the old config until they merge this patch and issue a new release (unless you merge the patch yourself and recompile of course).

**Comment by wtarreau** [comment]
Perfect, then we'll backport it. Thanks!

**Comment by wtarreau** [comment]
Now merged in both 2.3 and 2.2. I'm closing as solved since there's not much more we can do at this point.

Thanks for the report and the tests!

**Comment by pratikbin** [comment]
>```
> option httpchk
> http-check send meth GET uri /ws ver HTTP/1.1 hdr Host server:15674 hdr Authorization Basic\ bW9uOnZpZHV4bW9uOTc2NDMx hdr Connection Upgrade hdr Upgrade websocket hdr Sec-WebSocket-Key haproxy hdr Sec-WebSocket-Version 13 hdr Sec-WebSocket-Protocol v12.stomp
> http-check expect status 101
> ```
>


ser @brenc , did it worked?

**Comment by brenc** [comment]
@pratikbin I don't understand. What are you asking me?
