### ISSUE TITLE
"TARGET=" is required by make

### ISSUE THREAD

**Issue by TheDavidFactor** [haproxy/haproxy#1016]
I'm trying to build HAProxy with Ansible using the community.general.make plugin and I get the error:

gmake: *** No rule to make target `linux-glibc'.  Stop.

Upon further investigation, I discovered that the plugin is calling "/bin/gmake linux-glibc ..." while "/bin/gmake TARGET=linux-glibc ..." works just fine.

Before I open an issue with the community.general.make project, I wanted to confirm that requiring TARGET= is valid make behavior.

**Comment by lukastribus** [comment]
Correct, `make linux-glibc` is invalid, it needs to be `make TARGET=linux-glibc`, also see `INSTALL`.
