### ISSUE TITLE
src/mworker-prog.c: identical inner condition

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1017]
src/mworker-prog.c:310:27: warning: Identical inner 'if' condition is always true. [identicalInnerCondition]

**Comment by wtarreau** [comment]
This one is valid, the construction is wrong, and there is a similar unneeded "if" 5 lines below that needs to be removed as well.

**Comment by wtarreau** [comment]
No done, thanks for your patience Ilya :-)
