### ISSUE TITLE
src/pool.c: identical condition

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1018]
src/pool.c:121:7: warning: Identical inner 'if' condition is always true. [identicalInnerCondition]

**Comment by wtarreau** [comment]
This one is wrong, it ignores the #ifdef that is just above and which makes this not always true.

**Comment by chipitsine** [comment]
maybe we should move `#endif` 3 lines lower ?

**Comment by wtarreau** [comment]
No we must not, that would render the code confusing. Ifdefs were never made to make code analysis tools happy anyway :-)

**Comment by chipitsine** [comment]
placing check outside `#ifdef` looks tautological. but I will recheck

**Comment by wtarreau** [comment]
Ilya, could we close this one ?
