### ISSUE TITLE
Haproxy-Ingress with NLB

### ISSUE THREAD

**Issue by sharma-rajendra** [haproxy/haproxy#1019]
After deploying the haproxy-ingress with AWS NLB getting error on controller pod:
cp: can't preserve ownership of '/etc/haproxy/lua/auth-request.lua': Operation not permitted
cp: can't preserve ownership of '/etc/haproxy/lua/send-response.lua': Operation not permitted
cp: can't preserve ownership of '/etc/haproxy/lua/services.lua': Operation not permitted
cp: can't preserve ownership of '/etc/haproxy/lua': Operation not permitted

**Comment by lukastribus** [comment]
This is `haproxy`, not `haproxy-ingress`.
