### ISSUE TITLE
Incorrect error handling of memory allocation error in strdup() in __sink_new (sink.c:65-66)

### ISSUE THREAD

**Issue by cve-reporting** [haproxy/haproxy#1023]
## Detailed description of the problem

Incorrect handling of the valued returned by strdup() usages in case of an allocation error will lead to NULL pointer dereference and segmentation fault error in case of restrictive memory protection or near NULL pointer overread in case of no memory restrictions (e.g. in embedded environments).

Vulnerable code (src/sink.c:65-76):

	65:	sink->name = strdup(name);
	66:	sink->desc = strdup(desc);
	67:	sink->fmt  = fmt;
	68:	sink->type = SINK_TYPE_NEW;
	69:	sink->maxlen = BUFSIZE;
	70:	/* address will be filled by the caller if needed */
	71:	sink->ctx.fd = -1;
	72:	sink->ctx.dropped = 0;
	73:	HA_RWLOCK_INIT(&sink->ctx.lock);
	74:	LIST_ADDQ(&sink_list, &sink->sink_list);
 	75: end:
	76:	return sink;

Crashing code (usage of sink->name without check for NULL):

	34:	struct list sink_list = LIST_HEAD_INIT(sink_list);

	38:	struct sink *sink_find(const char *name)
	39:	{
	40:		struct sink *sink;
	41:	
	42:		list_for_each_entry(sink, &sink_list, sink_list)
	43:			if (strcmp(sink->name, name) == 0)           // <- strcmp(NULL, name) causes read from NULL address
	44:				return sink;
	45:		return NULL;
	46:	}

## Expected behavior

haproxy should handle strdup() failure and display appropriate message. 

## Steps to reproduce the behavior

0. Install gdb

1. Download and unpack code of ErrorSanitizer (https://github.com/Samsung/ErrorSanitizer)

2. Remove hooks/hooks_memory.c file from the ErrorSanitizer directory or comment out the whole contents of this file to disable hooks for: malloc, calloc and realloc.

	rm hooks/hooks_memory.c

3. Continue with compilation of ErrorSanitizer according to the manual (https://github.com/Samsung/ErrorSanitizer#compilation)

	make

4. Set ESAN to the path of ErrorSanitizer directory

	export ESAN=/opt/...

5. Download and unzip attached map temp_1.cur_input
[temp_1.cur_input.zip](https://github.com/haproxy/haproxy/files/5761914/temp_1.cur_input.zip)

6. Download, unzip and compile haproxy-2.3.0

7. Run haproxy with ErrorSanitizer in gdb using:
	
	gdb -batch -ex='run' -ex='backtrace' --args env LD_PRELOAD=$ESAN/error_sanitizer_preload.so ./haproxy-2.3.0/haproxy -v temp_1.cur_input

You should receive similar output:
```
	process 14589 is executing new program: haproxy-2.3.0/haproxy
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
	[New Thread 0x7ffff6f57700 (LWP 14602)]
	[Thread 0x7ffff6f57700 (LWP 14602) exited]

	Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
	__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
	31	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
	#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
	#1  0x0000555555698c54 in sink_find (name=name@entry=0x555555723502 "stderr") at src/sink.c:43
	#2  0x00005555556990fa in __sink_new (fmt=7, desc=0x555555722646 "standard output (fd#2)", name=0x555555723502 "stderr") at src/sink.c:57
	#3  sink_new_fd (name=name@entry=0x555555723502 "stderr", desc=desc@entry=0x555555722646 "standard output (fd#2)", fmt=fmt@entry=LOG_FORMAT_RAW, fd=fd@entry=2) at src/sink.c:87
	#4  0x000055555569925e in sink_init () at src/sink.c:1023
	#5  0x0000555555588776 in main (argc=3, argv=0x7fffffffde28) at src/haproxy.c:3083
```
## Do you have any idea what may have caused this?

Incorrect handling of strdup() failure when returned value is NULL.
See following recommendations for details (especially the calloc example):
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

## Do you have an idea how to solve the issue?

Issues should be fixed by adding check for NULL after both strdup() in src/sink.c:65 and src/sink.c:66.

## What is your configuration?

N/A

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3.0-1c0a722a8 2020/11/05 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.0.html
Running on: Linux 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

```
Linux ABC 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
Segmentation fault (core dumped)
```

**Comment by chipitsine** [comment]
@cve-reporting , you only ran "haproxy -v"

can you run reg-tests with that lib preloaded ?

an example how to invoke reg-tests:
https://github.com/haproxy/haproxy/blob/master/.cirrus.yml#L9-L14

or:
https://github.com/haproxy/haproxy/blob/master/.travis.yml#L89


it might uncover other error handling issues

**Comment by chipitsine** [comment]
also, your haproxy version is 2.3: `2.3.0-1c0a722a8 2020/11/05`
can you try against master branch?

**Comment by chipitsine** [comment]
please ignore my suggestion to run reg-tests. it will be a mess of numerous reports in single issue.

we should report issues separately

**Comment by TimWolla** [comment]
I sent a patch: https://www.mail-archive.com/haproxy@formilux.org/msg39307.html
