### ISSUE TITLE
Incorrect error handling of memory allocation error of strdup() in cfg_parse_listen (cfgparse-listen.c:1512)

### ISSUE THREAD

**Issue by cve-reporting** [haproxy/haproxy#1024]
## Detailed description of the problem

Incorrect handling of the valued returned by strdup() usage in case of an allocation error will lead to NULL pointer dereference and segmentation fault error in case of restrictive memory protection or near NULL pointer overread in case of no memory restrictions (e.g. in embedded environments).
It may lead to arbitrary memory read or write in particular conditions (only partially met in this case).

Vulnerable code (cfgparse-listen.c:1512):

	1511:		rule->cond = cond;
	1512:		rule->be.name = strdup(args[1]);
	1513:		rule->line = linenum;
	1514:		rule->file = strdup(file);
	1515:		if (!rule->file) {
	1516:			ha_alert("Out of memory error.\n");
	1517:			goto out;
	1518:		}
	1519:		LIST_INIT(&rule->list);
	1520:		LIST_ADDQ(&curproxy->switching_rules, &rule->list);

Crashing code (usage of sink->name without check for NULL) - (log.c:563):

	563:		sp = str = backfmt = strdup(fmt);

## Expected behavior

haproxy should handle strdup() failure and display appropriate message. 

## Steps to reproduce the behavior

0. Install gdb

1. Download and unpack code of ErrorSanitizer (https://gitlab.com/ErrorSanitizer/ErrorSanitizer)

2. Remove hooks/hooks_memory.c file from the ErrorSanitizer directory or comment out the whole contents of this file to disable hooks for: malloc, calloc and realloc.

	rm hooks/hooks_memory.c

3. Continue with compilation of ErrorSanitizer according to the manual (https://gitlab.com/ErrorSanitizer/ErrorSanitizer#compilation)

	make

4. Set ESAN to the path of ErrorSanitizer directory

	export ESAN=/opt/...

5. Download and unzip attached map temp_30.cur_input
[temp_30.cur_input.zip](https://github.com/haproxy/haproxy/files/5762298/temp_30.cur_input.zip)

6. Download, unzip and compile haproxy (master branch at the moment of reporting)

7. Run haproxy with ErrorSanitizer in gdb using:
	
	gdb -batch -ex='run' -ex='backtrace' --args env LD_PRELOAD=$ESAN/error_sanitizer_preload.so ./haproxy-master/haproxy -v temp_30.cur_input

You should receive similar output:
```
	process 21393 is executing new program: haproxy-master/haproxy
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
	[New Thread 0x7ffff6f57700 (LWP 21904)]
	[Thread 0x7ffff6f57700 (LWP 21904) exited]
	[WARNING] 002/215343 (21393) : parsing [temp_30.esn_input:5] : HTTP log/header format not usable with frontend 'fe_main' (needs 'mode http').

	Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
	__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
	62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
	#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
	#1  0x00007ffff6ff5a1e in __GI___strdup (s=0x0) at strdup.c:41
	#2  0x00007ffff7baeb40 in real_strdup () from error_sanitizer_preload.so
	#3  0x00007ffff7baec0e in strdup () from error_sanitizer_preload.so
	#4  0x0000555555635dcc in parse_logformat_string (fmt=fmt@entry=0x0, curproxy=curproxy@entry=0x555555a6f4f0, list_format=list_format@entry=0x555555a64490, options=<optimized out>, options@entry=0, cap=cap@entry=8, err=err@entry=0x7fffffffd908) at src/log.c:563
	#5  0x00005555556315e4 in check_config_validity () at src/cfgparse.c:2552
	#6  0x0000555555678bc1 in init (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:1957
	#7  0x0000555555589d07 in main (argc=4, argv=0x7fffffffde58) at src/haproxy.c:3088

```
## Do you have any idea what may have caused this?

Incorrect handling of strdup() failure when returned value is NULL.
See following recommendations for details (especially the calloc example):
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

## Do you have an idea how to solve the issue?

Issues should be fixed by adding check for NULL after strdup() in cfgparse-listen.c:1512.

## What is your configuration?

haproxy (master branch)

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.4-dev4-23cc52-55 2020/12/31 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = 
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```

```
Linux ABC 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
Segmentation fault (core dumped)
```

**Comment by TimWolla** [comment]
Sent a patch for this: https://www.mail-archive.com/haproxy@formilux.org/msg39314.html
