### ISSUE TITLE
improve prometheus gauge state usage

### ISSUE THREAD

**Issue by wdauchy** [haproxy/haproxy#1029]
current status metrics are as follow:

```
haproxy_frontend_status{proxy="foo"} 1
haproxy_backend_status{proxy="foo"} 1
haproxy_server_status{proxy="foo",server="bar"} 1
```

where the value represents the state as a gauge, i.e. frontend: 0=STOP, 1=UP, 2=FULL - backend: 0=DOWN, 1=UP - server: 0=DOWN, 1=UP, 2=MAINT, 3=DRAIN, 4=NOLB)

I believe it would be easier to use if we had something like:

```
haproxy_frontend_status{proxy="foo",state="UP"} 1
haproxy_backend_status{proxy="foo",state="UP"} 1
haproxy_server_status{proxy="foo",server="bar",state="MAINT"} 1
```

where the state is a label value. I also think this could be closer to prometheus best practices.
A typical example is to be able to group by labels state, without having to hardcode somewhere the definition of each gauge value.

WDYT?

**Comment by wdauchy** [comment]
cc @capflam

**Comment by capflam** [comment]
@wdauchy, honestly, I have no opinion on it. I'm not a Prometheus expert and I thought the labels had to be more or less static. If you say it is closer to Prometheus best practices, I blindly trust you. Just remembered that each k/v label pair induces a separate time series for a given metric. So, for a given server, you would have 5 series for the metric `haproxy_server_status`. And only one would be reported at a time. If it is not a problem, or better, if it is the expected behaviour, it is of course a good idea.

On the HAproxy side, it means we must update the prometheus exporter to deal with dynamic labels. Or at least extend the way the labels are set to handle an enum. We may think to rely on a callback function.

**Comment by capflam** [comment]
@wdauchy, reading https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics makes me think we should always export all states, with the value 0 for unmatching ones. But I don't know if it is applicable to labels. For instance : 

```
haproxy_server_status{proxy="foo",server="bar",state="DOWN"} 0
haproxy_server_status{proxy="foo",server="bar",state="UP"} 0
haproxy_server_status{proxy="foo",server="bar",state="MAINT"} 1
haproxy_server_status{proxy="foo",server="bar",state="DRAIN"} 0
haproxy_server_status{proxy="foo",server="bar",state="NOLB"} 0
```

**Comment by wdauchy** [comment]
my original report was oriented to the observation that it is not straightforward to do a sum by value when you want to count the number of servers with a given status. On the other hand, using labels makes it possible to produce a sum(foo) by (state) very easily.
It is ok to use a label as long as the label values are a finite list to avoid exploding the cardinality over the time. It would also avoid a user to have to read the definition to understand each value.
All those problems comes from the fact we have more than two states possible. Without this constraint most system export something like `foo_running 0/1`. If we also look at the upstream prometheus exporter they even decided to reduce the different states to a binary one 0/1 see https://github.com/prometheus/haproxy_exporter/blob/master/haproxy_exporter.go#L480. I however found some complaints about people asking to have the true state.

On the missing metrics subject it is indeed important to always export all metrics. Regarding the labels, it however could be a bit tempered. The big difference here is that the value would be a 1 or 0 (or null if non existing). So in a sum usecase, it would not be an issue. My own use cases are mostly about counting the number of servers in a given state, but I fear other people would like to do some average operations. In that case it would be mandatory to have all states available all the time.
My conclusion is a bit puzzle as for my own usecase it will make sense to only export the current label, but to address all needs, exporting all states will increase the number of exported metrics. In terms of sizing this will become an issue for some users.

**Comment by pierrecdn** [comment]
I +1 this, to favor explicit over implicit (such as constants) via labels in prometheus.
As an example, we had to do such weird things to aggregate at a backend level for health_check statuses:
```
<aggregator_function> by(proxy, check_status) (count_values by(proxy, instance) ("check_status", haproxy_server_check_status))
```
And then I need reconciliate on the other end to make it readable for the end-user (ie. 15 = "Checks passing" etc.).

Doing it from the start would be way more convenient, but the clear downside I'm seeing as you @wdauchy is that the output it will produce will yet again eat more memory since the enumeration of states will have to be performed for each of these metrics.

**Comment by wtarreau** [comment]
Just thinking about something regarding the output size, as it's downloaded over HTTP it should be possible and extremely efficient to compress the output just like we can do for stats. That doesn't alleviate the need for parsing on the consumer side, but parsing a few chars versus a few digits is not what will dramatically change the cost, I guess that lookups of field names and the formating are more expensive. 10 years ago haproxy logs were parsable and indexable at 1 GB/s, and I think the prometheus formating is not harder to deal with :-)

**Comment by wdauchy** [comment]
Thanks @pierrecdn for the confirmation.

> Just thinking about something regarding the output size, as it's downloaded over HTTP it should be possible and extremely efficient to compress the output just like we can do for stats. That doesn't alleviate the need for parsing on the consumer side, but parsing a few chars versus a few digits is not what will dramatically change the cost, I guess that lookups of field names and the formating are more expensive. 10 years ago haproxy logs were parsable and indexable at 1 GB/s, and I think the prometheus formating is not harder to deal with :-)

the scrapping is one thing we can most likely improve through compression indeed; the real issue is more on the prometheus side as all metrics will be in memory. For another improvement we should think about a more granular way to filter out some metrics at the source level: it would avoid to scrap them from the beginning but also later the need to filter them on prometheus side. For now it is only at frontend/backend/server level. The main issue is often at server level where a few metrics are effectively used among potentially thousands of servers.

**Comment by capflam** [comment]
@wdauchy , can we close this feature request ?

**Comment by wdauchy** [comment]
yes lets close it for now. I was about to ask @pierrecdn whether he could test the next dev version to have feedbacks from a large infra.

thanks for your support @capflam on this one!
