### ISSUE TITLE
src/xprt_quic.c: null pointer dereference suspected by cppcheck

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1032]
```
src/xprt_quic.c:1882:10: warning: Either the condition '!frm' is redundant or there is possible null pointer dereference: frm. [nullPointerRedundantCheck]
  memset(frm, 0, sizeof *frm);
```

**Comment by wtarreau** [comment]
The test on `frm` is indeed too late and should be moved up a few lines. CCing @haproxyFred

**Comment by haproxyFred** [comment]
I have replied to the mail I have received for this issue with a patch as attachment, but I am not sure this may work!

**Comment by wtarreau** [comment]
Ah you're right, I also got trapped a few times by this. Just send it to me and I'll merge it. Thanks!

**Comment by TimWolla** [comment]
> I have replied to the mail I have received for this issue with a patch as attachment, but I am not sure this may work!

Unfortunately attachments don't appear to be supported for “reply by email” on GitHub issues.

**Comment by wtarreau** [comment]
Now merged, thanks all!
