### ISSUE TITLE
src/xprt_quic.c: null pointer dereference suspected by cppcheck

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1033]
```
src/xprt_quic.c:2689:34: warning: Either the condition 'if(conn_ctx)' is redundant or there is possible null pointer dereference: ctx. [nullPointerRedundantCheck]
 TRACE_ENTER(QUIC_EV_CONN_TRMHP, ctx->conn);
                                 ^
```

**Comment by wtarreau** [comment]
This one was not easy. The `if (conn_ctx)` test is in the caller, `qc_srv_pkt_rcv()`, and this `conn_ctx` becomes the `ctx` argument of `qc_try_rm_hp()`. The arg must then be turned to `ctx ? ctx->conn : NULL`. CC @haproxyFred

**Comment by wtarreau** [comment]
Actually no, I'm wrong. The function uses ctx everywhere. I guess it's the caller that should avoid to call the function if `conn_ctx` is null. But I'll let Fred judge by himself.

**Comment by haproxyFred** [comment]
Hmm, for haproxy server (QUIC clients) the connection context is initialized before receiving any packet running ->init() xprt callback with&conn->xprt_ctx as second argument. If the context initialization has failed, I agree there is an issue. But if this initialization has failed we must stop receiving any UDP datagram. The haproxy server dgram parser (qc_srv_pkt_rcv()) would not be called. This part is not finalized.

For me cppcheck is wrong.

The test below is also useless
    /* Wake the tasklet of the QUIC connection packet handler. */
    if (conn_ctx)
        tasklet_wakeup(conn_ctx->wait_event.tasklet);

**Comment by chipitsine** [comment]
closing issue. will re-run cppcheck
