### ISSUE TITLE
src/queue.c: null pointer dereference suspected by cppcheck

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1036]
```
src/queue.c:291:31: warning: Either the condition 'pp' is redundant or there is possible null pointer dereference: pp. [nullPointerRedundantCheck]
 if (KEY_CLASS(p->node.key) < KEY_CLASS(pp->node.key))
                              ^
src/queue.c:288:6: note: Assuming that condition 'pp' is not redundant
 if (pp && !p)
     ^
src/queue.c:291:31: note: Null pointer dereference
 if (KEY_CLASS(p->node.key) < KEY_CLASS(pp->node.key))
                              ^
```

**Comment by chipitsine** [comment]
`pp` is always true in 288. we can remove that check

**Comment by haproxyFred** [comment]
There is the same issue for 'p' variable which is dereferenced before being tested.

**Comment by wtarreau** [comment]
Yes we can remove the test on `pp`, it was just for readability (i.e. have the 4 combinations of p/pp). It can be replaced by a comment above the test saying "now pp is non-null". However Fred, I can't find where p is dereferenced before being tested, are you sure you were not mistaken ?

For me, !pp&&!p return 0, !pp&&p go to use_p, pp&&!p go to use_pp which doesn't use p, and we're left with pp&&p here.

**Comment by haproxyFred** [comment]
I remember having read if (!pp et !p) or if (pp && p) (the same test on pp and p)  and concluded they was logically the same issue both on p and pp variable without even opening the source file.

**Comment by capflam** [comment]
Should be fixed now.
