### ISSUE TITLE
strict-limits is not enforced with master-worker 

### ISSUE THREAD

**Issue by NickMRamirez** [haproxy/haproxy#1042]
## Detailed description of the problem

The documentation defines the global directive `strict-limits` this way:

> Makes process fail at startup when a setrlimit fails. Haproxy is tries to set
the best setrlimit according to what has been calculated. If it fails, it
will emit a warning. **Use this option if you want an explicit failure of
haproxy when those limits fail.** This option is disabled by default. If it has
been enabled, it may still be forcibly disabled by prefixing it with the "no"
keyword.

I observed that HAProxy 2.2.4 and 2.2.7 on Ubuntu Bionic (18.04) starts successfully when I set `strict-limits` in the `global` section and set `maxconn` to a very high number. HAProxy does give an alert that the file descriptors could not be set, but otherwise continues to start.

The output of `systemctl status`:

```
systemd[1]: Starting HAProxy Load Balancer...
haproxy[16853]: [NOTICE] 010/184533 (16853) : haproxy version is 2.2.7-1ppa1~bionic
haproxy[16853]: [NOTICE] 010/184533 (16853) : path to executable is /usr/sbin/haproxy
haproxy[16853]: [ALERT] 010/184533 (16853) : [/usr/sbin/haproxy.main()] Cannot raise FD limit to 4000044, limit is 1024.
haproxy[16853]: Proxy stats started.
haproxy[16853]: Proxy www started.
lb1 haproxy[16853]: Proxy webservers started.
haproxy[16853]: [ALERT] 010/184533 (16853) : [/usr/sbin/haproxy.main()] FD limit (1024) too low for maxconn=2000000/maxsock=4000044. Please raise 'ulimit-n' to 4000044 or more to avoid any trouble.
haproxy[16853]: [NOTICE] 010/184533 (16853) : New worker #1 (16873) forked
systemd[1]: Started HAProxy Load Balancer.
```

## Expected behavior

When `strict-limits` is set in the `global` section, HAProxy should fail to start when it cannot increase the file descriptors to accomodate the desired `maxconn` setting. However, the behavior observed is that HAProxy does start anyway.

## Steps to reproduce the behavior

1. Add a `maxconn` that is very high, such as 2-million, and add `strict-limits`:

```
global
    maxconn 2000000
    strict-limits
```

2. Restart HAProxy.
3. The process starts successfully, although it should not.
4. Check `systemctl status` to see that you got an alert that says: *FD limit (1024) too low for maxconn=2000000/maxsock=4000044. Please raise 'ulimit-n' to 4000044 or more to avoid any trouble.*

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

No, but the relevant code was introduced in this patch: https://github.com/haproxy/haproxy/commit/0fec3ab7bf

## What is your configuration?

```
global
    log /dev/log local0 debug
    stats socket /var/run/haproxy.sock user haproxy group haproxy mode 660 level admin
    master-worker
    maxconn 2000000
    strict-limits

defaults
    log global
    mode http
    option httplog
    timeout connect 10s
    timeout client 30s
    timeout server 30s
    timeout http-request 30s

frontend www
    bind :80
    default_backend webservers

backend webservers
    default-server maxconn 30  check 
    server server1 127.0.0.1:8080 check
    server server2 127.0.0.1:8081 check
    server server3 127.0.0.1:8082 check
```

## Output of `haproxy -vv` and `uname -a`

**haproxy -vv**:

```
HA-Proxy version 2.2.7-1ppa1~bionic 2021/01/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.7.html
Running on: Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-12MIrN/haproxy-2.2.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

**uname -a**:

```
Linux lb1 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

HAProxy did not crash.

## Additional information (if helpful)

I am using the HAProxy distribution for Ubuntu 18.04 from https://haproxy.debian.net/

**Comment by jmagnin** [comment]
@wdauchy is strict-limits not supposed to apply when master-worker is used or was https://github.com/haproxy/haproxy/blob/master/src/haproxy.c#L3114 mistakenly copied from https://github.com/haproxy/haproxy/blob/master/src/haproxy.c#L3164 ? (also wondering about lines 3138 and 3150).

**Comment by wdauchy** [comment]
> @wdauchy is strict-limits not supposed to apply when master-worker is used or was https://github.com/haproxy/haproxy/blob/master/src/haproxy.c#L3114 mistakenly copied from https://github.com/haproxy/haproxy/blob/master/src/haproxy.c#L3164 ? (also wondering about lines 3138 and 3150).

I must say I had a hard time remembering why I wrote it that way but now I remember; I wanted to have a scenario such as:
- we have a working process
- we update the ulimit
- we reload, haproxy is unable to set the new limit, the reload fails, without breaking the working process

but I agree it is adding some confusion for the initial start and not aligned with what it is stated in the documentation. So it is probably better to remove those conditions to make it clearer that even the master worker will exit in a case of a reload scenario. I will send a patch later today if you don't.

**Comment by jmagnin** [comment]
I'll send a patch. Thanks

**Comment by wdauchy** [comment]
> I'll send a patch. Thanks

thanks. please make sure to add the above context I mentioned in the commit message so we better understand later the history of it.

**Comment by wlallemand** [comment]
The behavior could be enhanced by checking the HAPROXY_MWORKER_REEXEC environment variable, so it could still exits during the first start but not during a reload.

**Comment by wdauchy** [comment]
ah good point, I missed that `HAPROXY_MWORKER_REEXEC` when I had a quick look this morning.
just to make it clear if we use it:
- exit at first start when limits cannot be set
- exit new worker during a reload to fail the reload

both approach are ok to me at the end, if we either exit everything or just the new worker.

**Comment by wlallemand** [comment]
Well, in fact I forgot something, with the master-worker, if you do an exit() during a reload, the atexit() callback is called and the master process reexecute itself in wait mode, which is the normal behavior when a configuration is invalid and it does not kill the previous processes. So you don't have to check if you are in master mode or not if you do an exit() during the parsing.

**Comment by wdauchy** [comment]
ok, that's clear indeed
