### ISSUE TITLE
HAProxy 2.2.0+ segfault when frontend has server lines defined

### ISSUE THREAD

**Issue by brhenc** [haproxy/haproxy#1043]
## Detailed description of the problem

A frontend containing server lines that passes a configuration check with warnings (no alerts) using haproxy -c -f /etc/haproxy/haproxy.cfg fails when started with haproxy -f (or as a systemd service) with a segmentation fault.

Freak copy-pasting accident of haproxy config from Slack revealed the issue.

## Expected behavior

The behavior in HAProxy 1.5 (or until about commit 0a3dd74c to be a bit more precise) was to disallow server lines in a frontend.
In any case, a segmentation fault shouldn't happen - either it should exit
cleanly or work with the rather mangled configuration.

## Steps to reproduce the behavior

1. define a frontend with server lines
2. use haproxy versions after commit d7e639661a49a77f4d49222a0761ec19ab33f843 (or the specific commit)
3. Run a configuration check against the haproxy configuration - it should pass with warnings: `haproxy -c -f /etc/haproxy/haproxy.cfg`
4. Start HAProxy either as a systemd service or manually with `haproxy -f /etc/haproxy/haproxy.cfg`

## Do you have any idea what may have caused this?
Git bisecting between v2.1.0 and v2.2.0 reveals that commits after https://github.com/haproxy/haproxy/commit/d7e639661a49a77f4d49222a0761ec19ab33f843
experience the segmentation fault.

## Do you have an idea how to solve the issue?
Not at the moment.

## What is your configuration?

```
global
    log /dev/log local0 debug
    maxconn 2000

defaults
    log global
    mode http
    option httplog
    timeout connect 10s
    timeout client 30s
    timeout server 30s
    timeout http-request 30s

frontend www
    bind :80
    server server1 127.0.0.1:8080 check
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.7-1~bpo10+1 2021/01/10 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.7.html
Running on: Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.2.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

```
Linux debian-10 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
HAProxy crashes before it can log to syslog:
haproxy -f /etc/haproxy/haproxy.cfg
[WARNING] 010/172606 (1383) : parsing [/etc/haproxy/haproxy.cfg:16] : 'server' ignored because frontend 'www' has no backend capability.
Segmentation fault
```
Full backtrace attached for vbernat - build HAProxy
[haproxy-vbernat-backtrace.txt](https://github.com/haproxy/haproxy/files/5799021/haproxy-vbernat-backtrace.txt)
Full backtrace for latest master commit
[haproxy-master-backtrace.txt](https://github.com/haproxy/haproxy/files/5799020/haproxy-master-backtrace.txt)

## Additional information (if helpful)

Core dump attached (Debian 10, vbernat 2.2.7 HAProxy)
[core-haproxy-vbernat-11-0-0-2442-1610405451.gz](https://github.com/haproxy/haproxy/files/5799033/core-haproxy-vbernat-11-0-0-2442-1610405451.gz)
Core dump attached (Debian 10, master commit, same build options as vbernat )
[core-haproxy-latest-master-commit-11-0-0-2413-1610405415.gz](https://github.com/haproxy/haproxy/files/5799032/core-haproxy-latest-master-commit-11-0-0-2413-1610405415.gz)
Reproducible with latest 2.2 branch commit
Reproducible with 2.3.0
Reproducible with 2.4-dev5
Reproducible with latest master version ( at the time of writing, this is
commit 76603f2552fafc23871a914600a18c3616959693 )

**Comment by capflam** [comment]
Thanks @brhenc. It should be fixed in the 2.4.

**Comment by TimWolla** [comment]
> [WARNING] 010/172606 (1383) : parsing [/etc/haproxy/haproxy.cfg:16] : 'server' ignored because frontend 'www' has no backend capability.

I wonder why this is a warning only. Would it make sense to turn this into a hard error? Is there any case where having a `server` in a `frontend` section is not a mistake?

**Comment by wtarreau** [comment]
Just checked and this check dates v1.3.4 in 2006, commit 977b8e41  ("[MAJOR] distinguish between frontend, backend, ruleset and listen") to be precise. Historically we wanted not to break existing configs, and most warnings are emitted with some settings that are useless and have no effect (e.g maxqueue etc), hence the introduction of the function "warnifnotcap()". But apparently we never added a "failifnotcap()", and I agree that a few statements like "server" would definitely need to fail.

I'm usually against adding new errors before LTS versions, but for this one, I don't see any valid point in keeping it as a warning since I don't see when a user would like to temporarily turn a "listen" statement to a frontend and hope their server will be silently ignored. The only case was likely when the frontend keyword was new and users needed time to transform their config. 15 years later if that was not done, it will never be!

So I'm OK with turning this into a hard error.

**Comment by capflam** [comment]
Ok, I'll emit an fatal error instead of a warning. It may be backported as far as 2.2 too I guess (maybe as far as 2.0).

**Comment by wtarreau** [comment]
closing since the fix was backported.
