### ISSUE TITLE
src/cli.c: unused variable suspected by Coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1048]
```
2116        if ((end - 1) == (payload + strlen(PAYLOAD_PATTERN))) {
2117                /* if the payload pattern is at the end */
2118                s->pcli_flags |= PCLI_F_PAYLOAD;
    CID 1399833 (#1 of 1): Unused value (UNUSED_VALUE)assigned_value: Assigning value from reql to ret here, but that stored value is overwritten before it can be used.
2119                ret = reql;
2120        }
```

**Comment by wdauchy** [comment]
this was introduced by commit 3301f3e5cdecf2439762a678c1c2e9846a41e0f6 ("BUG/MEDIUM: cli: handle correctly prefix and payload").
So it's true that looking at the current code, ret will be overridden anyway, so we could remove this `ret = reql;` statement. But maybe this was added on purpose as a generic way. Any thoughts @wlallemand?

**Comment by chipitsine** [comment]
let us remove it

**Comment by capflam** [comment]
Now fixed, thanks @chipitsine
