### ISSUE TITLE
Runtime API: manage CAs via socket

### ISSUE THREAD

**Issue by thomas-kaltenbach** [haproxy/haproxy#1057]
## What should haproxy do differently? Which functionality do you think we should add?
We need following functionalities to update all our certificates dynamically:

```
show  ssl ca
new ssl ca
set  ssl ca
commit ssl ca
```

## What are you trying to do?
With [Dynamic SSL Certificate Storage](https://www.haproxy.com/de/blog/dynamic-ssl-certificate-storage-in-haproxy/#:~:text=The%20new%20Dynamic%20SSL%20Certificate,to%20commit%20or%20cancel%20them.) we can add/update dynamically certificates without reloading haproxy. That is very good.

We planed to switch to manage our certificates with the runtime api, but unfortunately our blocker is that currently it is not possible to manage the CAs via socket.

## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.2.7-f10629d 2021/01/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.7.html
Running on: Linux 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=6).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

```
# uname -a
Linux 4087cab6ec46 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 GNU/Linux
```

**Comment by domdom82** [comment]
bump. we would really like to see this implemented. else certificates via the socket api (without having to reload) is incomplete for us. our main goal is to replace the `crt-list` feature of the config with matching socket api commands and eventually not having to reload at all.

**Comment by rlebreton** [comment]
I'm currently working on this feature. I focused on the set/commit/abort triad first since it seemed like it would answer to most use cases. The ability to add new CA files should follow, as well as a "show ca" that would still need to be defined. If you have some data that you would particularly like to see in the output of a show ca command, don't hesitate to mention it here.

**Comment by wlallemand** [comment]
I think we should maybe consider an other name than "ca" for the CLI, maybe "ca-file" like the configuration directive. I fear that it become confusing at some point, because what we want to update is the "ca-file" which could contains multiple CAs, not just a CA.

Regarding the "show ca-file" command, it should display the information of each CA in the ca-file, because they are separated entities, so it is basically a "show cert" command which iterates on each CA in my opinion.

I don't know if it is relevant right now, be we might want to be able to add an individual CA to the ca-file, or to remove one, instead of having to set the entire file  later. We'll stick to the set feature for the moment but it could evolve to that once it is stable.

**Comment by domdom82** [comment]
what about "ca-cert"?

**Comment by domdom82** [comment]
agree with @wlallemand. Moreover, I think there should be two different commands for the ca-file (shows a list of cas) and a single ca.
Analogous to `show ssl crt-list` which displays a list of certificates in the crt-list but `show ssl cert` shows details about a single certificate.

**Comment by wlallemand** [comment]
HAProxy does not handle a specific entity for a single CA, it's always a ca-file which can contain one or more CAs. It is important to keep a consistency between the CLI and the configuration file. So we could probably keep the same command but with an index, like it's done for the crt-list.

For example `show ssl ca-file foobar.crt:2` will display the 2nd CA.

**Comment by domdom82** [comment]
ok I see. so `show ssl ca-file foobar.crt` would then show a list of all CAs in that particular ca-file. Adding an individual CA like you mentioned can be a follow-up feature. We also don't need that at the moment as we get a full ca-file from our customers. (as per the `ca-file` ssl bindconf)

**Comment by thomas-kaltenbach** [comment]
Hey, thank you for providing this new feature!
Only one question, will this be part of 2.4?

**Comment by wlallemand** [comment]
Unfortunately no, it was not planned for 2.4 so it was merged after its release. It was too late in the release cycle to be considered mergeable when 2.4 was freezed, and 2.4 was released last week.

**Comment by domdom82** [comment]
@wlallemand does this change also include the management of `crl-file` entries in the crt-list by chance? I think this would also be needed for dynamically changing revocation lists.

**Comment by wlallemand** [comment]
@domdom82 yes, please see this commit: https://github.com/haproxy/haproxy/commit/3c222bd99c537d5c680f00abeb02d8a40eae3929

**Comment by wlallemand** [comment]
I'm closing the ticket since the feature is now merged in master.

**Comment by domdom82** [comment]
@wlallemand thanks!
