### ISSUE TITLE
multiple monitor-uri not work, the last monitor-uri  overide the other one !

### ISSUE THREAD

**Issue by mcarbonneaux** [haproxy/haproxy#1059]
## Detailed description of the problem

In the HAProxy docs (i've tryed haproxy from 1.8 to 2.1.11), I don’t see it explicitly stated that multiple monitor-uri statements cannot be used in a single frontend. 

When i try to add multiple monitor-uri in frontend (each uri are used by different frontend lb) the behavior seems to be that the last monitor-uri in the frontend overrides the others. 

## Expected behavior

That all monitor-uri reponse ok for the frontend.

**Comment by wtarreau** [comment]
Yes absolutely. There's exactly one such URI defined in a frontend. Maybe the doc is not clear on this subject indeed.

If you really need multiple monitor-uris you could actually implement them using the return directive instead nowadays. E.g.
```
   http-request return status 200 content-type text/plain string "OK" if { url /my/monitor/uri }
```

Do you want to propose a different wording for the doc or an addition that would have made this point more obvious to you when you checked there ?

**Comment by mcarbonneaux** [comment]
Thank's for response!

but i think is be more simple to make possible to use multiple monitor-uri than this type of generic response (that work fine so!), and more readable in the configuration file.

**Comment by Warren-D-Johnson** [comment]
> 
> 
> Thank's for response!
> 
> but i think is be more simple to make possible to use multiple monitor-uri than this type of generic response (that work fine so!), and more readable in the configuration file.

mcarbonneaux

A work around is to setup an additional frontend with its own separate monitoring URL that references whatever backend you want to keep track of.  For example:

frontend port950
  bind :950
  mode http
  acl servers_are_down nbsrv(some_backend) lt 1
  monitor-uri /haproxy?monitor_some_backend
  monitor fail if servers_are_down

You'll need to open port 950 through your firewall (remembering to lock it down to whatever is doing the health check).  Your monitor healthcheck URL would be something similiar to

http://www.domain.com:950/haproxy?monitor_some_backend

**Comment by wtarreau** [comment]
The doc was now updated, we can close now! Thanks for the report and sorry for having forgotten about it!
