### ISSUE TITLE
src/stats.c: uninitialized variable suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1063]
@wdauchy , is it related to prometheus refactoring ?

```
1789                        default:
1790                                /* should never fall here unless non implemented */
1791                                return 0;
1792                }
    CID 1444669 (#1 of 1): Uninitialized scalar variable (UNINIT)7. uninit_use: Using uninitialized value metric. Field metric.type is uninitialized.
1793                stats[current_field] = metric;
1794                if (selected_field != NULL)
1795                        break;
1796        }
1797        return 1;
```

**Comment by wdauchy** [comment]
Ah yes I will handle this one. Thanks

**Comment by TimWolla** [comment]
Just fixed the title of the issue to be accurate. This is about an uninitialized variable, not an unused one.

**Comment by capflam** [comment]
It is a false positive. The variable is set in the switch statement inside the while loop. At each iteration, the variable is set and used to fill the stats array. For unused/unimplemented metrics, the variable is not used. So it is safe.

**Comment by wdauchy** [comment]
@capflam yes you are right. yesterday I did not looked much in the details of the report. We can close this issue.

**Comment by capflam** [comment]
Contrary to what I said, It is a valid report. Now fixed. Sorry for the wrong analysis.
