### ISSUE TITLE
freebsd-11 reg-tests are broken

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#108]
build log:

https://cirrus-ci.com/task/4769353875062784

**Comment by wtarreau** [comment]
Ilya, look closer, it's not haproxy, it's vtest which fails. For whatever reason it cannot create a socket. Maybe Cirrus runs in a jail preventing it from accessing the network, then regtests need to be disabled there. We need to keep in mind that the goal is not to achieve best results on CI but to achieve best quality on haproxy thanks to CI.  Thus let's not fall into the trap consisting in wasting valuable development time fixing erroneous CI issues that CI created!
```
---- h1    0.0 Create listen socket failed: hostname nor servname provided, or not known
---- h1    0.0 Assert error in haproxy_wait(), src/vtc_haproxy.c line 697:  Condition(h->pid > 0) not true.  Errno=0 No error: 0
```
