### ISSUE TITLE
src/mux_h2.c uninitialized variable suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1084]
```
5308                struct ist n = list[hdr].n;
    CID 1403563 (#1 of 1): Uninitialized scalar variable (UNINIT)55. uninit_use: Using uninitialized value list[hdr].v.
5309                struct ist v = list[hdr].v;
```

**Comment by TimWolla** [comment]
`.v` is uninitialized exactly when `.n` is an empty string. The assignment to the local variable technically uses an initialized value, but that uninitialized value is not used except in the initial assignment.

So this is a false positive, but it might or might not be possible to slightly rearrange the code to not even perform the assignment.
