### ISSUE TITLE
2.2.8 Lua core.get_info() does not work anymore

### ISSUE THREAD

**Issue by SkeletonRocky** [haproxy/haproxy#1090]
Lua function core.get_info() returns "nil" at 2.2.8 version, its working with 2.2.6 with the same configuration.

> root@haproxy-dani-build:~# /opt/haproxy-2.2.8/sbin/haproxy -f /etc/haproxy/haproxy.cfg
> [info] 028/083156 (10298) : SIGSCI_INIT sigsci-module-haproxy 1.2.0 on /var/run/sigsci.sock
> [NOTICE] 028/083156 (10298) : haproxy version is 2.2.8-7bf78d7
> [NOTICE] 028/083156 (10298) : path to executable is /opt/haproxy-2.2.8/sbin/haproxy
> [ALERT] 028/083156 (10298) : lua init: runtime error: table index is nil from [C] field 'get_info', /usr/local/lib/lua/5.3/sigsci/SignalSciences.lua:546 C function line 537.

> root@haproxy-dani-build:~# /opt/haproxy-2.2.6/sbin/haproxy -f /etc/haproxy/haproxy.cfg
> [info] 028/083237 (10306) : SIGSCI_INIT sigsci-module-haproxy 1.2.0 on /var/run/sigsci.sock

haproxy.cfg global section:

> lua-load /usr/local/lib/lua/5.3/sigsci/SignalSciences.lua

lua script line 546:

>   local infos = core.get_info()

**Comment by capflam** [comment]
Thanks. This bug is already fixed but after the 2.2.8. See 3ddec3ee7d. It will be included in the 2.2.9.

**Comment by SkeletonRocky** [comment]
Also the same issue in v2.3.4

**Comment by capflam** [comment]
And the same is true for the 2.3.4. The fix will be included in the 2.3.5 :)
