### ISSUE TITLE
Backend use-server condition sometimes will go not working normally

### ISSUE THREAD

**Issue by TerrySunTW** [haproxy/haproxy#1094]
## Detailed description of the problem
use-server condition sometimes will go wrong server

I am using Haproxy to separate https with different domain setting, but sometimes it will go to wrong server with same url, but when I wrote test python script to send https request 100 times per second, It couldn't reproduce the wrong situation. Any ideas?

Test URL:

https://web1.abc.com:8080 (sometimes a few request will go web2)

https://web2.abc.com:8080 (sometimes a few request will go web1)

## Expected behavior
All of requests should go correct server by url

## Steps to reproduce the behavior
Still don't know how to reproduce the situation.

## Do you have any idea what may have caused this?
Would it caused by my internal port forward?

## Do you have an idea how to solve the issue?
No

## What is your configuration?

```
frontend http_https_8080
  mode tcp
  bind *:8080
  tcp-request inspect-delay 30s
  tcp-request content accept if HTTP

  use_backend http_server if HTTP
  default_backend local_https_server

backend http_server
  mode tcp
  tcp-request content accept if { req_ssl_hello_type 1 }
  tcp-request inspect-delay 30s

#domain agent
  use-server web1 if { hdr_dom(Host) -i web1.abc.com }
  use-server web2 if { hdr_dom(Host) -i web2.abc.com }
  server web1 10.10.10.10:8080
  server web2 10.10.10.11:8083


frontend local_https_9443
  mode tcp
  bind  *:9443 ssl crt /etc/haproxy.pem
  default_backend http_server

backend local_https_server
  mode tcp
  option ssl-hello-chk
  server localhttps localhost:9443
```

## Output of `haproxy -vv` and `uname -a`

Im using container to create haproxy service ( haproxy:2.3.4)

**Comment by capflam** [comment]
You are using TCP proxies. Thus the routing is only performed on the first request. If your are using "keep-alive" connections, the other requests sent on a given connection are not analyzed and routed to the same server.  Note also that  you are not waiting for the HTTP headers of the request for SSL connections. Thus it is possible to select the server without the "Host" header. In this case, your 2 `use-server` rules don't match and a classical roundrobin is applied to choose  a server.

So, at first glance, it is not a bug but a configuration issue. The issue tracker is reserved to track the bugs and the feature requests. Use the forum or the mailing list if you need more help on this subject.

The forum is at: https://discourse.haproxy.org/

The mailing list (no need to subscribe) is: haproxy@formilux.org
Subscribe to the list: haproxy+subscribe@formilux.org
Unsubscribe from the list: haproxy+unsubscribe@formilux.org
