### ISSUE TITLE
Truncated responses when using abortonclose + shutr

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#11]
This is a summary of several old reports indicating that haproxy would truncate some responses in 1.8 and 1.7 if option abortonclose is set and the client closes. It could be related to comparable reports causing truncated compressed objects. It was reported that 1.7.0 didn't have the problem and it looked related to the long chain the stream processing fixes that went into 1.7 to address unkillable connections.

It is uncertain whether current versions are now safe from this, nor even if the issue was fixed in 1.7 and 1.8 as a byproduct of another fix. This entry was added not to forget it and to add other potential victims report it with extra information. Barring any new info on it, maybe we can close it and we'll reopen it when we get more info?

**Comment by capflam** [comment]
I'm closing this issue. No other report since almost 3 years....
