### ISSUE TITLE
http-error status with lf-file expects HTTP head which is then printed in HTTP body

### ISSUE THREAD

**Issue by bjacke** [haproxy/haproxy#1135]
## Detailed description of the problem
I want to configure a customized error page via:

http-error status 403 content-type "text/html; charset=utf-8" lf-file /etc/haproxy/errors/403-plus-id.http

if the 403-plus-id.http file contains no http header lines, then haproxy complains:

[ALERT] 045/131653 (15133) : parsing [/etc/haproxy/haproxy.cfg:224] : errorfile : '/etc/haproxy/errors/403-plus-id.http': unabled to parse headers (error offset: 4)

If I add the http header (just like in the default errorfiles), then haproxy generates the HTTP header by itself and print the HTTP header lined from the 403-plus-id.http file into the HTTP body (as user visible text).

## Steps to reproduce the behavior
set
http-error status 403 content-type "text/html; charset=utf-8" lf-file /etc/haproxy/errors/403-plus-id.http
and access a page which is 403 forbidden, in my case it's forbidden through a "http-request tarpit deny_status 403" directive in the frontend.
## What is your configuration?

```
fronend test
....
 http-error status 403 content-type "text/html; charset=utf-8" lf-file /etc/haproxy/errors/403-plus-id.http
 http-request tarpit deny_status 403
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.9-1~bpo10+1 2021/02/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
Running on: Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.2.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

**Comment by capflam** [comment]
I'm unable to reproduce the bug, with the 2.2.9 and the last 2.4-dev. For me, everything works as expected. So it may be caused by something else in your config. Could you provide a minimal but complete config to reproduce the bug please ?

**Comment by bjacke** [comment]
just put these two lines into a random frontend:

    http-error status 500 content-type "text/html; charset=utf-8" lf-file /etc/haproxy/errors/500.http
    http-request tarpit deny_status 500 if { path /haproxy-issue-1135 }

see for example now https://www.samba.org/haproxy-issue-1135

wthouth the HTTP header in the 500.http file, haproxy will refuse the configuration.

**Comment by bjacke** [comment]
arrg, sorry, I had from previous testing also a errorfile declaration, which of course expects the HTTP header to be there! Sorry for the noise :-/

**Comment by capflam** [comment]
no problem :)
