### ISSUE TITLE
Limitation on the size of the URL

### ISSUE THREAD

**Issue by jlmontes1697** [haproxy/haproxy#115]
## Output of `haproxy -vv` and `uname -a`

```
(paste your output here)
```

## What's the configuration?

```
(paste your output here)
```

## Steps to reproduce the behavior

1. 
2. 
3. 

## Actual behavior
I need to make very large requests to a WEB server through the Balancer HAPROXY. When the size is very large it does not redirect to any backend, if the size is small it works correctly.
Is there any limit to the size of the URL?

**Comment by lukastribus** [comment]
Yes and can you can tune those parameters for example `tune.bufsize`, `tune.http.cookielen` or `tune.http.maxhdr` as per the documentation.

However, this is not a bug and the issue tracker on github is not a support forum. Please consider using the support channels (discourse, mailing list) for further questions, as per the issue template.
