### ISSUE TITLE
undefined reference to `quic_transport_params_init'

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#1153]
## Detailed description of the problem

When I try to build the current git version with USE_QUIC are this error and waring message shown.

```
.
.
.
src/proxy.c: In function 'proxy_preset_defaults':
src/proxy.c:1110:2: warning: implicit declaration of function 'quic_transport_params_init'; did you mean 'SSL_set_quic_transport_params'? [-Wimplicit-function-declaration]
  quic_transport_params_init(&defproxy->defsrv.quic_params, 0);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
  SSL_set_quic_transport_params
.
.
.

  LD      haproxy
/usr/bin/ld: src/proxy.o: in function `proxy_preset_defaults':
/usr/src/haproxy/src/proxy.c:1110: undefined reference to `quic_transport_params_init'
collect2: error: ld returned 1 exit status
```
## Expected behavior

Sucessfull build.

## Steps to reproduce the behavior

1. git clone https://gitlab.com/aleks001/haproxy24-boringssl
2. cd haproxy24-boringssl
3. `buildah bud --rm --layers --tag hap-24-bor . `
4.   or `docker build --rm --tag hap-24-bor . `

The base image is debian:latest
gcc compiler version 8.3.0

## Do you have any idea what may have caused this?

No

## Do you have an idea how to solve the issue?

No

**Comment by haproxyFred** [comment]
A fix should be merged soon.
