### ISSUE TITLE
map not existing/working/created/set when only having http-request set-map in config

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxy/haproxy#1156]
this does not do anything on its own
`http-request set-map(/etc/haproxy/maps/test.map) %[url] %[str(value)]`

It starts to work when you have something like added
` use_backend %[req.hdr(host),lower,word(1,:),map(/etc/haproxy/maps/test.map,testb)]`

Looks to me like unexpected/unwanted behaviour.

HAProxy version 2.2.8-7bf78d7, released 2021/01/13

**Comment by TimWolla** [comment]
https://github.com/haproxy/haproxy/issues/1051#issuecomment-759640991
