### ISSUE TITLE
src/peers.c: known condition suspected by cppcheck

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1165]
```
src/peers.c:431:8: style: Condition 'peer' is always true [knownConditionTrueFalse]
src/peers.c:444:8: style: Condition 'peer' is always true [knownConditionTrueFalse]
```

**Comment by EmericBr** [comment]
The commit/version to know on which sources those lines # applies would be appreciate with such report

**Comment by chipitsine** [comment]
I ran cppcheck on master branch

**Comment by TimWolla** [comment]
https://github.com/haproxy/haproxy/blob/7bbc6c9ac3511dd54bcd575d8c6404af2731576b/src/peers.c#L431

`peer` must be truthy here, because it is initialized using `a2` which was just checked a few lines earlier.

**Comment by EmericBr** [comment]
> I ran cppcheck on master branch

Yep but master is evolving, It would be a great asset it your report notes at least the last commit on which ccpcheck is runned.

**Comment by chipitsine** [comment]
I ran on 7bbc6c9ac3511dd54bcd575d8c6404af2731576b

**Comment by EmericBr** [comment]
Thanks

**Comment by capflam** [comment]
Fixed. Thanks !
