### ISSUE TITLE
 if Access-Control-Allow-Headers has to much entries haproxy acts strange

### ISSUE THREAD

**Issue by cccdemon** [haproxy/haproxy#1166]
## Detailed description of the problem

We`ve added all the x-amz/aws headers to our haproxy configuration, after this our s3/haproxy setup was in 3 ot 10 tests not able to fullfill a get request (without haproxy it worked like a charm) : 

## Steps to reproduce the behavior

1. add these headers to your config
```rspadd Access-Control-Allow-Headers:\ Origin,\ X-Requested-With,\ Content-Type,\ Accept,\ X-Amz-Date,\ X-Amz-User-Agent,\ Authorization,\ x-amz-acl,\ X-Amz-Content-Sha256,\ ETag,\ amz-sdk-invocation-id,\ amz-sdk-request,\ x-amz-content-sha256,\Cache-Control,\ Content-Disposition,\ Content-Encoding,\ Content-Language,\ Content-Length,\ Content-MD5,\ Content-Range,\ Expires,\ If-Match,\ If-Modified-Since,\ If-None-Match,\ If-Unmodified-Since,\ Last-Modified,\ Location,\ Range,\ accept-ranges,\ x-amz-abort-date,\ x-amz-abort-rule-id,\ x-amz-acl,\ x-amz-archive-status,\ x-amz-bucket-object-lock-enabled,\ x-amz-bucket-object-lock-token,\ x-amz-bypass-governance-retention,\ x-amz-confirm-remove-self-bucket-access,\ x-amz-content-sha256,\ x-amz-copy-source,\ x-amz-copy-source-if-match,\ x-amz-copy-source-if-modified-since,\ x-amz-copy-source-if-none-match,\ x-amz-copy-source-if-unmodified-since,\ x-amz-copy-source-range,\ x-amz-copy-source-server-side-encryption-customer-algorithm,\ x-amz-copy-source-server-side-encryption-customer-key,\ x-amz-copy-source-server-side-encryption-customer-key-MD5,\ x-amz-copy-source-version-id,\ x-amz-delete-marker,\ x-amz-expected-bucket-owner,\ x-amz-expiration,\ x-amz-grant-full-control,\ x-amz-grant-read,\ x-amz-grant-read-acp,\ x-amz-grant-write,\ x-amz-grant-write-acp,\ x-amz-metadata-directive,\ x-amz-mfa,\ x-amz-missing-meta,\ x-amz-mp-parts-count,\ x-amz-object-lock-legal-hold,\ x-amz-object-lock-mode,\ x-amz-object-lock-retain-until-date,\ x-amz-replication-status,\ x-amz-request-charged,\ x-amz-request-payer,\ x-amz-restore,\ x-amz-restore-output-path,\ x-amz-server-side-encryption,\ x-amz-server-side-encryption-aws-kms-key-id,\ x-amz-server-side-encryption-bucket-key-enabled,\ x-amz-server-side-encryption-context,\ x-amz-server-side-encryption-customer-algorithm,\ x-amz-server-side-encryption-customer-key,\ x-amz-server-side-encryption-customer-key-MD5,\ x-amz-source-expected-bucket-owner,\ x-amz-storage-class,\ x-amz-tagging,\ x-amz-tagging-count,\ x-amz-tagging-directive,\ x-amz-version-id,\ x-amz-website-redirect-location```

Leads to an 503, somethimes to an 206 or 204 reponse. 
As Backend we are using ceph rgw. (which works without the haproxy config like a charme) 

## Do you have any idea what may have caused this?

Max Header Size reached?

## Do you have an idea how to solve the issue?

Make max header size configurable

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.7.5-2 2017/05/17
HA-Proxy version 2.0.13-2ubuntu0.1 2020/09/08 - https://haproxy.org/
Ubuntu 20.04 and Debian 9

```

**Comment by capflam** [comment]
It is not a bug. It works as designed. Your header is too big ( ~2090 bytes). You must increase `tune.maxrewrite` value to be sure to have enough space to add it.

> tune.maxrewrite <number>
>
> Sets the reserved buffer space to this size in bytes. The reserved space is
> used for header rewriting or appending. The first reads on sockets will never
> fill more than bufsize-maxrewrite. Historically it has defaulted to half of
> bufsize, though that does not make much sense since there are rarely large
> numbers of headers to add. Setting it too high prevents processing of large
> requests or responses. Setting it too low prevents addition of new headers
> to already large requests or to POST requests. It is generally wise to set it
> to about 1024. It is automatically readjusted to half of bufsize if it is
> larger than that. This means you don't have to worry about it when changing
> bufsize.


For more info, use the forum or the mailing list.

The forum is at: https://discourse.haproxy.org/

The mailing list (no need to subscribe) is: haproxy@formilux.org
Subscribe to the list: haproxy+subscribe@formilux.org
Unsubscribe from the list: haproxy+unsubscribe@formilux.org
