### ISSUE TITLE
agent-check marked as ready,up causes failed servers to be marked as UP

### ISSUE THREAD

**Issue by aaronbbrown** [haproxy/haproxy#1176]
👋🏻  Greetings from GitHub :octocat:.  We have discovered what appears to be a regression in the behavior of agent-check and L4 health checks which it would be ❤️ to get some help with addressing.

## Detailed description of the problem

In haproxy all released versions of 2.2, when a health `check` is failed due to a L4 timeout **and** `agent-check` returns `ready.up`, the `server` continues to be marked as `UP`. This appears to have been introduced in 2.2-dev7. Prior to 2.2-dev7, the `server` would be marked `DOWN` in this same situation.

## Expected behavior

When a `server` is `DOWN` via health `check`, that should take precedence over the `agent-check` response. I can't think of a scenario where forcing (via `agent-check`) a backend to be artificially healthy in the face of a L4 timeout would yield a successful request.

## Steps to reproduce the behavior

I created a demonstration w/ docker and docker-compose in https://github.com/aaronbbrown/haproxy-agent-checker-bug. This example:

- starts up an haproxy 2.1 and an haproxy 2.2.10 container with an nginx pod as a `server`
- a netcat-based implementation of agent-check that always returns `ready,up`
- prints the CSV output from the stats page of each showing the server as UP for both 2.1 and 2.2
- stops the nginx container
- prints the CSV output from the stats page of each showing that haproxy 2.1 sees the backend as `DOWN` and haproxy 2.2 sees it as `UP`

1. Clone this repo https://github.com/aaronbbrown/haproxy-agent-checker-bug
2. install docker and docker-compose
3. run `./breakit.sh`
4. observe that haproxy 2.2 marks the backend as UP after the nginx container has been stopped

## Do you have any idea what may have caused this?

The issue first appears in 2.2-dev7, which seems to have a lot of work on checks. 2.2-dev6 behaves as expected.

## What is your configuration?

The configuration is all in https://github.com/aaronbbrown/haproxy-agent-checker-bug/blob/main/haproxy.cfg, but copied here:

```
global
  stats socket /var/run/haproxy.sock mode 666 level admin
  stats timeout 30s

defaults
  mode    http
  option  httplog
  option  dontlognull
  timeout connect 5000
  timeout client  50000
  timeout server  50000

listen fe
  bind 0.0.0.0:80
  option tcp-check
  balance roundrobin

  server server1 nginx:80 addr nginx check port 80 agent-check agent-addr agentchecker agent-port 3333 agent-inter 1s inter 1s

listen stats
  bind 0.0.0.0:1936
  stats enable
  stats uri /
```

## Output of `haproxy -vv` and `uname -a`

```console
$ uname -a
Linux bc7bbc908ad6 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux

$ haproxy -vv
HA-Proxy version 2.2.10-6a09215 2021/03/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.10.html
Running on: Linux 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=6).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

## Additional information (if helpful)

Thanks for your help with this!

**Comment by capflam** [comment]
Thanks, there is indeed a bug. It is pretty easy to fix. I'll push a fix soon. Instead of updating `.health` threshold of the agent-check, the one of the health-check is updated.

**Comment by capflam** [comment]
Fixed and backported now. Thanks !

**Comment by aaronbbrown** [comment]
@capflam 🥇 Thank you!
