### ISSUE TITLE
Perf improvement

### ISSUE THREAD

**Issue by sebastienros** [haproxy/haproxy#1177]
You will probably dislike it to be filed as an issue, but I didn't want to create an account on the forum. On the positive side, as part of the ASP.NET team, I benchmark diverse proxies including HA. Though the perf had declined in the past year, a very recent change which I haven't identified has increased the perf very significantly. So I just wanted to let you know in case you didn't have continuous benchmarks reports. Congrats! 👏 

The following charts exposes RPS and mean latency with diverse payload sizes on proxying a simple GET on http-http.

![image](https://user-images.githubusercontent.com/1165805/110730449-50e2f380-81d5-11eb-9353-e050df91595c.png)

Another note, I always found weird that the 10KB requests are faster than the 1KB ones. Maybe some specific memory management after a threshold size.

**Comment by sebastienros** [comment]
Note that we run out of docker hub latest tag. So most probably released with 2.4-dev11.

**Comment by chipitsine** [comment]
are those tests performed regularly ?
are results public available ?

**Comment by sebastienros** [comment]
Everyday, available here: https://aka.ms/aspnet/benchmarks
There is a menu at the bottom, look for Proxies. Then there are some filters for the protocols, where you can also compare to other proxies, and types of traffic. I need to check why we don't seem to run anything else than http for HA, it's surprising.

**Comment by TimWolla** [comment]
> Note that we run out of docker hub latest tag. So most probably released with 2.4-dev11.

`:latest` is a 2.3.6 as of now: https://github.com/docker-library/official-images/blob/a7157926de2c88d72390adadba25c85d1ef4e259/library/haproxy#L17

**Comment by chipitsine** [comment]
continuous benchmarking is ... awesome.
I would add a link to it (if it supposed to stay for a long time)

**Comment by wtarreau** [comment]
Yep, the recent updates are encouraging. We've been working on some bottlenecks observed in highly threaded environments and this is starting to pay off. A few of them have even been backported to 2.3 as they addressed possible crashes that were met in certain environments.

Thanks for your nice feedback, I didn't imagine that this would have been noticed by anyone in that short a time :-)

**Comment by hloeung** [comment]
Seems to line up with this commit:

https://github.com/docker-library/official-images/commit/5d09476d456ec5ad253b4753a5a39fdd98b79514#diff-9635fd86b43f6939891ed4a03d3e4772860c1291792af4a300d8c690b9e99904

So updating from 2.3.5 to 2.3.6. I'm going through the 2.3.6 changelogs on http://www.haproxy.org/download/2.3/src/CHANGELOG but can't seem to make out specifically which commits would be responsible for the performance improvements shown in the benchmark.

**Comment by wtarreau** [comment]
I'm seeing sevreal locking changes between 2.3.5 and 2.3.6, one by which we were abusively taking the server lock in health_adjust() that's called on each and every valid response (!) and another one related to the thread-safe lists where a misplaced check could possibly cause excess attempts. These are the two I'm noticing at first glance.

**Comment by capflam** [comment]
I guess we can close this issue now. Thanks !
