### ISSUE TITLE
Weird CR session terminations after enabling HTTP/2

### ISSUE THREAD

**Issue by ghorio** [haproxy/haproxy#1186]
## Detailed description of the problem
Hi all,
So basically I had a haproxy version 1.7.5 running for a long time but we needed to enable HTTP/2, so as its not supported on v1.7.5 I proceeded with upgrade to v1.8.28 and after adding alpn h2,http/1.1 as per documentation I run in an issue with 400 Bad Request on all my requests (later on with help from HAproxy community I found out that it was probably due to option httpclose in my backend configs). I then upgraded straight to v2.0.20 and my HAproxy config started to work (I did not make any changes since v1.7 config except for alpn)

After some time I noticed that there are weird CR errors coming in haproxy log. My haproxy serves like 300 requests per second and those CR requests pop out like 2-3 per 5 seconds or sometimes even less. They look like this

```
Mar 12 15:20:56 boost-2 haproxy[1147]: 195.122.4.119:63621 [12/Mar/2021:15:20:56.011] front-http~ backend/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 1632/577/17/0/3 0/0 "GET /t/2021/02/27/32890/470x275.jpg HTTP/2.0"
Mar 12 15:20:56 boost-2 haproxy[1147]: 195.122.4.119:63621 [12/Mar/2021:15:20:56.038] front-http~ backend/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 1637/578/18/0/3 0/0 "GET /t/2016/11/08/6/110x110.jpg HTTP/2.0"
Mar 12 15:20:56 boost-2 haproxy[1147]: 195.122.4.119:63621 [12/Mar/2021:15:20:56.051] front-http~ backend/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 1639/578/17/0/3 0/0 "GET /t/2016/11/08/28/110x110.jpg HTTP/2.0"
Mar 12 15:21:05 boost-2 haproxy[1147]: 81.198.64.171:52737 [12/Mar/2021:15:21:05.364] front-http~ backend/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 1689/579/3/0/3 0/0 "GET /v5/img/icons/app-store-badge.svg HTTP/2.0"
```

This happens only on frontends where alpn h2,http/1.1 is enabled.
I have tried to set also no option http-use-htx as per recommendation on HAproxy community, but then CR started to log with HTTP/1.1 at the end instead of HTTP/2.0

```
Mar 16 10:30:23 boost-2 haproxy[17832]: 85.234.170.149:53029 [16/Mar/2021:10:30:23.607] frontend-http~ backend-domain-com/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 805/716/2/0/3 0/0 "POST /loadHeader.php HTTP/1.1"
Mar 16 10:30:23 boost-2 haproxy[17832]: 85.234.170.149:53029 [16/Mar/2021:10:30:23.607] frontend-http~ backend-domain-com/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 805/716/3/0/3 0/0 "GET /ajax/remoteArticles?portal=exx HTTP/1.1"
Mar 16 10:30:32 boost-2 haproxy[17832]: 159.148.112.49:50788 [16/Mar/2021:10:30:32.714] frontend-http~ backend-domain-com/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 774/684/0/0/3 0/0 "GET /export/1/ HTTP/1.1"
Mar 16 10:32:03 boost-2 haproxy[17832]: 89.254.142.215:50751 [16/Mar/2021:10:32:03.368] frontend-http~ backend-img-domain-com/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 790/716/1/0/3 0/0 "GET /upload2/articles/90/906548/quiz/qu_60422.jpg HTTP/1.1"
Mar 16 10:32:03 boost-2 haproxy[17832]: 89.254.142.215:50751 [16/Mar/2021:10:32:03.369] frontend-http~ backend-img-domain-com/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 790/716/1/0/3 0/0 "GET /upload2/articles/90/906548/quiz/qu_60423.jpg HTTP/1.1"
Mar 16 10:32:03 boost-2 haproxy[17832]: 89.254.142.215:50751 [16/Mar/2021:10:32:03.376] frontend-http~ backend-img-domain-com/<NOSRV> 0/-1/-1/-1/0 -1 0 - - CR-- 790/716/1/0/3 0/0 "GET /upload2/articles/90/906548/quiz/qu_60426.jpg HTTP/1.1"
```
I have not received any user complains for web page (haproxy frontend) where h2 is enabled currently but there was an issue where specific URL path is forwarded from different HAproxy/nginx/varnish chain to my haproxy which then forwards to nodejs app on my end and I got complains that there were times during the day where this specific URL path would hung up for a minute or so and would return 5xx errors on their side while in my haproxy logs I would see like 50-100 or more CR errors with NOSRV in a row all logged at the same timestamp and once h2 was disabled there have not been any complains, so I would say that this impacts application as well. This specific URL path is being requested a lot per second, basically on all the requests when browsing page as its used for cookie consent purposes. Quite weird actually why it would hung for such a long time, like hiccup.

## Expected behavior
Previously on v1.7.5 I did not see any errors related to CR, but then again there was no http/2 enabled.
I would probably expect no CR terminations and no hiccups on my nodejs app.

## Steps to reproduce the behavior

Not sure if this is reproducable somehow, but steps I took were -
1. Have v1.7.5 running
2. Upgrade to v1.8.28, add alpn h2,http/1.1 to frontend, see 400 Bad Request
3. Upgrade to v2.0.20, see everything running fine with alpn h2,http/1.1 enabled
4. Get complains that NodeJS app is not accessible for a few seconds to minute during some periods of day
5. Start to notice CR errors in log on frontends where h2 is enabled

## Do you have any idea what may have caused this?
To be honest I have no idea, for now seems like somethign related to HTTP/2
## Do you have an idea how to solve the issue?
Unfortunately not at the moment
## What is your configuration?
I tried to trim my config as much as possible to exclude unnecessary ACL rules and backends as most of them are similar to the ones I have here in example. IP addresses and domains have been changed for example ones.

```
global
    maxconn 10000
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3
    ssl-dh-param-file /etc/haproxy/ssl/dhparams.pem

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        option http-ignore-probes
        no option http-use-htx
        timeout connect 5000
        timeout client  50000
        timeout server  300000
        timeout tunnel 70000ms
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend frontend-http
  bind 11.11.11.22:80
  bind 11.11.11.33:80
  bind 11.11.11.22:443 ssl crt /etc/haproxy/ssl/certs/domain.com.pem alpn h2,http/1.1
  bind 11.11.11.33:443 ssl crt /etc/haproxy/ssl/certs/domain.com.pem alpn h2,http/1.1

  option accept-invalid-http-request

  reqadd X-Forwarded-Proto:\ https if { ssl_fc }
  reqadd X-Forwarded-Port:\ 443 if { ssl_fc }
  reqadd X-Forwarded-Proto:\ http if !{ ssl_fc }
  reqadd X-Forwarded-Port:\ 80 if !{ ssl_fc }

  rspidel Server
  http-request set-header X-GW-Client-IP %[src]
  acl hdr_connection_upgrade hdr(Connection)  -i upgrade
  acl hdr_upgrade_websocket  hdr(Upgrade)     -i websocket

  acl host-domain-com hdr_dom(host) -i -m reg ^(domain\.com)(:[0-9]+)?$
  acl host-img-domain-com hdr_dom(host) -i -m reg ^(img)([0-9])?\.(domain\.com)(:[0-9]+)?$

  use_backend backend-domain-com if host-domain-lv
  use_backend backend-img-domain-com if host-img-domain-com

backend Abuse
  stick-table type ip size 1m expire 30m store conn_rate(3s),conn_cur,gpc0,http_req_rate(10s),http_err_rate(20s)

backend per-src-path
  stick-table type binary len 20 size 1k expire 10m store http_req_rate(10s)

backend Logger
  stick-table type ip size 100k expire 30m store conn_rate(3s),gpc0,conn_cur,http_req_rate(10s),http_err_rate(10s)

backend backend-img-domain-com
  option httpclose
  option forwardfor
  balance roundrobin
  option httpchk HEAD / HTTP/1.1\r\nHost:img.domain.com
  server 177 1.1.1.177:6081 check
  server 100 1.1.1.100:8080 backup

backend backend-domain-com
  option httpclose
  option forwardfor
  balance roundrobin
  option httpchk HEAD / HTTP/1.1\r\nHost:domain.com
  acl abuse src_http_req_rate(Logger) ge 100
  acl flag_abuser src_inc_gpc0(Logger) ge 0
  tcp-request content reject if abuse flag_abuser
  server domain-rancher 1.1.1.21:80 check
  server 100 1.1.1.100:8080 backup
```

## Output of `haproxy -vv` and `uname -a`

```
root@boost-2:~# haproxy -vv
HA-Proxy version 2.0.20-1~bpo9+1 2021/01/12 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.0.20=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.0l  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.0j  20 Nov 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.22 2016-07-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

```
root@boost-2:~# uname -a
Linux boost-2 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```

## Additional information (if helpful)
I raised this question on HAproxy community with more details there, the Post can be found here if anyone is interested - https://discourse.haproxy.org/t/400-bad-request-when-enabling-http-2/6338

**Comment by wtarreau** [comment]
Could you try to comment out the "tcp-request content reject" rule ? I'm wondering if it could be that one request triggers it from time to time, and causes the whole connection to be killed, bringing with it all pending requests. That's one of the "fun" part of multiplexed connections.

**Comment by ghorio** [comment]
> Could you try to comment out the "tcp-request content reject" rule ? I'm wondering if it could be that one request triggers it from time to time, and causes the whole connection to be killed, bringing with it all pending requests. That's one of the "fun" part of multiplexed connections.

Hi. I removed `tcp-request content reject if abuse flag_abuser` from backend config and at first it seemed like it was fine but after some time it still started to throw same CR errors in log file although it looks like they are coming in less than before, maybe its because traffic is not so large currently though.
Would this rule also impact other backends? Because I have this rule only for this one specific backend.

**Comment by wtarreau** [comment]
Yes it will impact other backends because its goal is to destroy a front connection. And given that H2 is multiplexed, a front connection will bring up to 100 requests at once that can be routed to different backends depending on your rules, and when one causes the destruction, all other ones will die with it.

**Comment by wtarreau** [comment]
And actually the problem with this rule when using H2 is that given that you can get 100 requests at the same time from a single TCP segment, you really get them in the same millisecond so the "rate ge 100" rule will definitely match quite a lot. One possible approach would be to significantly increase the threshold (e.g. to 500 or so). Abusers will generally hit whatever limit you set anyway.

**Comment by ghorio** [comment]
> Yes it will impact other backends because its goal is to destroy a front connection. And given that H2 is multiplexed, a front connection will bring up to 100 requests at once that can be routed to different backends depending on your rules, and when one causes the destruction, all other ones will die with it.

Ok that would make sense for this frontend, but lets say I have a different frontend configured on different IP together with this one, would it still impact the other frontend which had this specific consent URL path hanging up?
And what about those CRs still coming in after removing the tcp reject rule, does it mean client side is sending aborted HTTP requests etc.?

EDIT: Also what I notice is that those CRs happen mostly on .jpg, .png, .svg, .gif files

**Comment by wtarreau** [comment]
If they happen on images it could very well match clients aborting on heavily loaded pages. I'm personally used to press Escape all the time when a site takes time to load, and I'm pretty sure I'm not the only one :-)

**Comment by wtarreau** [comment]
Is there anything more we can do on this issue or should we consider it resolved ?

**Comment by capflam** [comment]
I'm closing the issue, feel free to re-open it if it is not solved from your point of view.
