### ISSUE TITLE
server/cli_add_server.vtc appears to be flaky

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1188]
see: https://github.com/haproxy/haproxy/runs/2150160074 and https://github.com/haproxy/haproxy/runs/2149878874

**Comment by a-denoyelle** [comment]
Indeed it is. It might be just a synchronization problem but I would like to be sure before starting to push fixes.

**Comment by a-denoyelle** [comment]
I pushed a commit, let's hope it will help to stabilize the reg-test.

**Comment by capflam** [comment]
It seems to be fixed now. I'm closing this issue.
