### ISSUE TITLE
2.2.11 possible regression in http-response track-sc* behavior 

### ISSUE THREAD

**Issue by anitgandhi** [haproxy/haproxy#1193]
## Detailed description of the problem

I recently attempted upgrading from HAProxy 2.2.6 to 2.2.11, and noticed that behavior related to `http-response track-scX myKey table myTable` has changed. Specifically, some counters are not updating at all anymore. 

## Expected behavior

Expected to see the counters continue to be populated. 

Especially when the 2 separate `http-response` directives reference 2 different `track-sc` counters (i.e. 1 vs 2), I would have thought both would be populated. 

## Steps to reproduce the behavior

1. config as below
2. send traffic to HAProxy and view tables: `echo "show table st_frontend_ssl_protocol_stats; show table st_frontend_ssl_cipher_stats; show table st_backend_ssl_protocol_stats; show table st_backend_ssl_cipher_stats" | socat - /var/run/haproxy.sock`

## Do you have any idea what may have caused this?

I saw [this mailing list thread](https://www.mail-archive.com/haproxy@formilux.org/msg40013.html) and figured it might be related. 

[This commit](https://github.com/haproxy/haproxy/commit/362d25e50708adf2b273bf9ee04f6566f113815e) seems very relevant as well. 

Perhaps both issues are at play. 

## Do you have an idea how to solve the issue?

I can't seem to figure out a functioning configuration that works around the issue. See below for attempts. 

## What is your configuration?

Here's the original config that works with 2.2.6 and no longer works with 2.2.11.

```
...

peers mypeers 
  peer my-hostname 127.0.0.1:5000 # local peer

frontend https_443 
  mode http
  bind ...
  tcp-request session track-sc0 ssl_fc_protocol table st_frontend_ssl_protocol_stats
  tcp-request session track-sc1 ssl_fc_cipher table st_frontend_ssl_cipher_stats
  default_backend https_443_backend

backend https_443_backend 
  mode http
  default-server ssl
  http-response track-sc1 ssl_bc_protocol table st_backend_ssl_protocol_stats
  http-response track-sc1 ssl_bc_cipher table st_backend_ssl_cipher_stats
  server ...

backend st_backend_ssl_cipher_stats 
  stick-table type string len 128 size 100 expire 1d peers mypeers store http_req_cnt

backend st_backend_ssl_protocol_stats 
  stick-table type string len 16 size 5 expire 1d peers mypeers store http_req_cnt

backend st_frontend_ssl_cipher_stats 
  stick-table type string len 128 size 100 expire 1d peers mypeers store sess_cnt

backend st_frontend_ssl_protocol_stats 
  stick-table type string len 16 size 5 expire 1d peers mypeers store sess_cnt
```

Here's how the stick tables are populated on 2.2.11 after sending a few HTTP requests - note how both backend tables are empty:

```
# table: st_frontend_ssl_protocol_stats, type: string, size:5, used:1
0x55f06cb9f308: key=TLSv1.3 use=0 exp=86398576 sess_cnt=57

# table: st_frontend_ssl_cipher_stats, type: string, size:100, used:1
0x55f06cb42c58: key=TLS_AES_128_GCM_SHA256 use=0 exp=86398576 sess_cnt=57

# table: st_backend_ssl_protocol_stats, type: string, size:5, used:0

# table: st_backend_ssl_cipher_stats, type: string, size:100, used:0
```

If I simply change 1 line in the above config to `http-response track-sc2 ssl_bc_protocol table st_backend_ssl_protocol_stats` (that is, to use sticky counter 2), then:
```
# table: st_frontend_ssl_protocol_stats, type: string, size:5, used:1
0x556d4b5d7088: key=TLSv1.3 use=51 exp=86399984 sess_cnt=51

# table: st_frontend_ssl_cipher_stats, type: string, size:100, used:1
0x556d4b66dc48: key=TLS_AES_128_GCM_SHA256 use=51 exp=86399984 sess_cnt=51

# table: st_backend_ssl_protocol_stats, type: string, size:5, used:1
0x556d4b683448: key=TLSv1.3 use=0 exp=86399986 http_req_cnt=4452

# table: st_backend_ssl_cipher_stats, type: string, size:100, used:0
```

If I instead change the other line to `http-response track-sc2 ssl_bc_cipher table st_backend_ssl_cipher_stats`, then:
```
# table: st_frontend_ssl_protocol_stats, type: string, size:5, used:1
0x560eae425c18: key=TLSv1.3 use=0 exp=86397516 sess_cnt=51

# table: st_frontend_ssl_cipher_stats, type: string, size:100, used:1
0x560eae3c11c8: key=TLS_AES_128_GCM_SHA256 use=0 exp=86397516 sess_cnt=51

# table: st_backend_ssl_protocol_stats, type: string, size:5, used:0

# table: st_backend_ssl_cipher_stats, type: string, size:100, used:1
0x560eae43fda8: key=TLS_AES_256_GCM_SHA384 use=0 exp=86397467 http_req_cnt=200
```

If I change both lines to use SC2, then:
```
# table: st_frontend_ssl_protocol_stats, type: string, size:5, used:1
0x7fe7f4173a08: key=TLSv1.3 use=0 exp=86397931 sess_cnt=52

# table: st_frontend_ssl_cipher_stats, type: string, size:100, used:1
0x7fe7f4110d48: key=TLS_AES_128_GCM_SHA256 use=0 exp=86397931 sess_cnt=52

# table: st_backend_ssl_protocol_stats, type: string, size:5, used:1
0x7fe7f4129468: key=TLSv1.3 use=0 exp=86397899 http_req_cnt=200

# table: st_backend_ssl_cipher_stats, type: string, size:100, used:0
```

This last one seems to make sense, based on the explanation in [this commit](https://github.com/haproxy/haproxy/commit/362d25e50708adf2b273bf9ee04f6566f113815e), that only the first registered entry will be populated. 

## Output of `haproxy -vv` and `uname -a`

```
root@my-hostname:~# haproxy -vv
HA-Proxy version 2.2.11-1ppa1~focal 2021/03/18 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.11.html
Running on: Linux 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-V7sSWX/haproxy-2.2.11=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

root@my-hostname:~# uname -a
Linux my-hostname 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Additional information (if helpful)

For some context: we use this configuration to gather TLS protocol and cipher stats for both incoming frontend and backend server connections, but aggregated across multiple frontends and backends (only 1 frontend/backend pair is seen above, but in practice there could be multiple). 

The frontend configuration continues to work well. 

side note: we to use `tcp-request session track-scX` for the backend configuration, with `sess_cnt` as the stick-table data type as opposed to `http_req_cnt`, as that would a more appropriate measurement. However, neither was accepted as valid configuration by HAProxy, so we had to work around it. For our specific use case, we didn't really care about absolute numbers, so this was fine for us. 

I can't seem to find a configuration where this goes back to working.

Any suggestions are certainly welcome. Thanks in advance!

**Comment by wtarreau** [comment]
Hi,

there is very likely a bug in your configuration, you have the same track counter used in two rules:
```
  http-response track-sc1 ssl_bc_protocol table st_backend_ssl_protocol_stats
  http-response track-sc1 ssl_bc_cipher table st_backend_ssl_cipher_stats
```
As indicated in the doc: `The first "track-sc1" rule executed enables tracking of the counters of the specified table as the second set` so if your goal is to try to track the protocol and if it fails, to fall back on the cipher, it's valid, but very likely it's not at all what you intended to do since you're tracking two completely different things.

The (rare) use case of having the same track-sc referenced multiple times is when you're trying to extract the same data from multiple sources. For example:
```
   http-request track-sc1 hdr(x-forwarded-for)
   http-request track-sc1 src   # if xff not found above
```

Otherwise for parallel tracking you absolutely need different trackers (each of them is one reference in a table so you cannot have the same reference in multiple tables).

**Comment by anitgandhi** [comment]
Hi, thanks for the response and explanation. I see now how the configuration was incorrect. 

I guess prior to 2.2.11 it was working inadvertently, and with the bug fix commit, it fixed that incorrect behavior. 

That said, I'm still a bit confused why the following configuration does not work in 2.2.11 either (note the 2 separate trackers, 2 separate tables):

```
backend https_443_backend 
  mode http
  default-server ssl
  http-response track-sc1 ssl_bc_protocol table st_backend_ssl_protocol_stats
  http-response track-sc2 ssl_bc_cipher table st_backend_ssl_cipher_stats
  server ...
```

```
# table: st_frontend_ssl_protocol_stats, type: string, size:5, used:1
0x564eee7e2f38: key=TLSv1.3 use=0 exp=86395662 sess_cnt=55

# table: st_frontend_ssl_cipher_stats, type: string, size:100, used:1
0x564eee7c2938: key=TLS_AES_128_GCM_SHA256 use=0 exp=86395662 sess_cnt=55

# table: st_backend_ssl_protocol_stats, type: string, size:5, used:1
0x564eee84df38: key=TLSv1.3 use=0 exp=86395629 http_req_cnt=200

# table: st_backend_ssl_cipher_stats, type: string, size:100, used:0
```

Also note that this modified config works as expected on 2.2.6

**Comment by wtarreau** [comment]
For now I cannot reproduce it with a simpler config, so I'm trying to set up a reproducer. Could you please switch the two rules and see if only the first track-sc works for example ?

**Comment by wtarreau** [comment]
Also, are you certain you were not already using track-sc2 in the frontend for example ? The trackers are per-transaction so what you set at the beginning of the request remains active till the end of the response. Maybe you're just having some overlap ? Because when I'm setting 3 http-response track-sc{0,1,2} rules on 3 different tables, I'm well seeing the 3 being updated.

**Comment by anitgandhi** [comment]
> Also, are you certain you were not already using track-sc2 in the frontend for example ? The trackers are per-transaction so what you set at the beginning of the request remains active till the end of the response. Maybe you're just having some overlap ? Because when I'm setting 3 http-response track-sc{0,1,2} rules on 3 different tables, I'm well seeing the 3 being updated.

I was worried about possible overlap with the frontend as well, but I just re-checked our config and we only ever use the following config for frontends:

```
frontend https_443 
  mode http
  bind ...
  tcp-request session track-sc0 ssl_fc_protocol table st_frontend_ssl_protocol_stats
  tcp-request session track-sc1 ssl_fc_cipher table st_frontend_ssl_cipher_stats
  default_backend https_443_backend
```

Note that we use `tcp-request session` here instead of `http-response track`; this is because for the data we need, which is TLS session stats, it's more appropriate (in my opinion) to track the session layer.

**Comment by anitgandhi** [comment]
> Could you please switch the two rules and see if only the first track-sc works for example ?

I just tried the following:
```
backend https_443_backend 
  mode http
  default-server ssl
  http-response track-sc2 ssl_bc_cipher table st_backend_ssl_cipher_stats
  http-response track-sc1 ssl_bc_protocol table st_backend_ssl_protocol_stats
  server ...
```

And now everything works as before!

**Comment by anitgandhi** [comment]
> Could you please switch the two rules and see if only the first track-sc works for example ?

So with this config on 2.2.11:

```
backend https_443_backend
  mode http
  default-server ssl
  http-response track-sc2 ssl_bc_cipher table st_backend_ssl_cipher_stats
  http-response track-sc1 ssl_bc_protocol table st_backend_ssl_protocol_stats
  server ...
```

The cipher stats are populated, but not protocol: 

```
# table: st_backend_ssl_protocol_stats, type: string, size:5, used:0

# table: st_backend_ssl_cipher_stats, type: string, size:100, used:1
0x55626a85a628: key=TLS_AES_256_GCM_SHA384 use=0 exp=86398530 http_req_cnt=500
```

(perhaps I misinterpreted the request w.r.t switching the 2 directives; if this was incorrect, please let me know, I'm happy to try any combination of configuration!)

**Comment by wtarreau** [comment]
Great, so this proves that the issue is with the rules ordering and not with the samples nor the tracker number. Thanks for the test. Your point about the session rules is interesting, I didn't notice first time, I'll need to take that into consideration. And you're perfectly right that it's more appropriate.

However there's still overlap of sc1 which is used at two places. I don't understand why sometimes it's reused and sometimes ignored in your case, but it's very possible that the test that was missing to detect the conflict triggers this, or that it's not sufficient to cover this case. Normally your http-request track-sc1 rule should never work because sc1 is already used at the session level. But regardless I want to see a deterministic behavior which is not what I'm observing here.

By the way if you really want to have more trackers you can recompile haproxy and change the number by setting `MAX_SESS_STKCTR` (max 10 for 0..9).

The way you use them is interesting because in fact you don't really want to track and keep the tracker, you seem to want to just update a few fields for an entry here, and that's well reflected in your initial config where the same tracker was mistakenly reused. I'm wondering if we couldn't have a "touch-sc" action which would do something hybrid, consisting in enabling and disabling the tracking in one operation.
It wouldn't track all events that appear after the tracking but it could likely be sufficient for use cases like yours, and allow to track more info than the 3 default trackers.

**Comment by anitgandhi** [comment]
Apologies for an earlier comment that I have since deleted - in it, I noted that switching the order of the 2 `http-response track-scX` directives succeeded; turns out I accidentally tested that on 2.2.6 hence it was "working". 

The comment I have kept above is indeed with 2.2.11; based on what I could gather there, changing the order does not seem to matter - whichever directive that uses `sc2` is the one whose table entry gets populated. This aligns with what you said above:

> However there's still overlap of sc1 which is used at two places... Normally your http-request track-sc1 rule should never work because sc1 is already used at the session level...

When changing both to use `sc2`, the first table is the only one populated - this behavior completely aligns with the change outlined in 362d25e50708adf2b273bf9ee04f6566f113815e . 

I think my original misunderstanding was that since our environment uses 4 separate tables for frontend/backend * protocol/cipher , and the frontends+backends were both in `mode http`, that no counters would be "shared" across sessions. In particular, I incorrectly assumed that an https frontend and http(s) backend would be "disconnected" with respect to sessions. 

> By the way if you really want to have more trackers you can recompile haproxy and change the number by setting MAX_SESS_STKCTR (max 10 for 0..9).

Yes I've considered this, unfortunately we're currently in an environment where we are not compiling ourselves, but I will keep this in mind if/when we're able to do this. 

> The way you use them is interesting because in fact you don't really want to track and keep the tracker, you seem to want to just update a few fields for an entry here...

Yeah for us, in both the the frontend and backend cases, what I suppose we really want to do is extract 2 keys (protocol+cipher) from 1 session/request, into separate tables; but I recognize that as things stand today, that is not directly possible. 

Just to provide some more context for how we use these numbers - we use the runtime api to extract the table values and transform them into custom Prometheus counters, after which it's aggregated like any other Prometheus data.

**Comment by anitgandhi** [comment]
Anyway, thank you for all the help with this! We were clearly relying on incorrect behavior, and I do believe 2.2.11 is behaving more consistently than previous versions, so I'm going to close this.

**Comment by wtarreau** [comment]
OK thanks for the details, it's useful to know a bit more about the use cases! And yes I was about to suggest combining the two entries into a single table but it can be more cumbersome to extract them as pure stats.

**Comment by anitgandhi** [comment]
Ah thanks for that suggestion about combining, I got it to work with this config below. The custom concatenation using a known delimiter (`|`) works well enough for our use case, and we can use 1 less SC now :) 

```
global
  ...
  ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
  ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:@SECLEVEL=1
  ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
  ssl-default-server-options ssl-min-ver TLSv1.2 no-tls-tickets
  ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA
  ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
  ...

frontend https_443
  mode http
  bind ...
  tcp-request session set-var(sess.fc_cipher) ssl_fc_cipher
  tcp-request session track-sc0 ssl_fc_protocol,concat(|,sess.fc_cipher) table st_frontend_ssl_stats
  default_backend https_443_backend

backend st_frontend_ssl_stats
  # 2 allowed protocol versions * 29 allowed ciphers(uites) = only 58 possible combinations for entries,
  # but using 100 just for a round number and extra capacity in case
  # 100 (50+128) = 17.8KB max usage 
  stick-table type string len 128 size 100 expire 1d peers mypeers store sess_cnt

backend https_443_backend
  mode http
  default-server ssl
  http-response set-var(sess.bc_cipher) ssl_bc_cipher
  http-response track-sc1 ssl_bc_protocol,concat(|,sess.bc_cipher) table st_backend_ssl_stats
  server ...

backend st_backend_ssl_stats
  # same calculation as above, since our frontend and backend protocol/cipher limitations are identical
  stick-table type string len 128 size 100 expire 1d peers mypeers store http_req_cnt

```

**Comment by wtarreau** [comment]
Yep, that was the idea. I'm using concatenation at various places as well (e.g. source+cookie etc). Glad it worked for you!
