### ISSUE TITLE
stick table counter regression 1.8.29, 2.0.21, 2.1.12, 2.2.11

### ISSUE THREAD

**Issue by lukastribus** [haproxy/haproxy#1196]
This is a **tracking issue only** for a bug that is already fixed in all supported, affected trees.

## Detailed description of the problem

From the fix 8cc586c73fefd96f4be1f7820e38a1263f6252ca

> In commit a1ecbca0a ("BUG/MINOR: freq_ctr/threads: make use of the last
> updated global time"), for period-based counters, the millisecond part
> of the global_now variable was used as the date for the new period. But
> it's wrong, it only works with sub-second periods as it wraps every
> second, and for other periods the counters never rotate anymore.

First reported:
https://www.mail-archive.com/haproxy@formilux.org/msg40013.html

Second report:
https://discourse.haproxy.org/t/counter-issues-on-1-8-29/6381

## Expected behavior

Counters decrement over time as per configuration.

## Steps to reproduce the behavior

1. Use stick table counters
2. Notice counters fail to decrement over time

## Do you have any idea what may have caused this?

Commit a1ecbca0a

## Do you have an idea how to solve the issue?

Commit 8cc586c73fefd96f4be1f7820e38a1263f6252ca (requires 6064b34be0e761de881a5bfca287d01f69122602)

## What is your configuration?

From:
https://www.mail-archive.com/haproxy@formilux.org/msg40014.html

```
fe-test
  http-request track-sc0 src table be-test

be-test
  stick-table type ipv6 size 1m expire 24h store http_req_rate(2s)

```

## Affected releases

* 1.8.29
* 2.0.21
* _2.1.12 (unmaintained)_
* 2.2.11
* 2.3.8 (incomplete bugfix)

**Comment by schferbe** [comment]
Is there a plan when this fix will be released on the 2.2 LTS line?

**Comment by lukastribus** [comment]
It was planned for the beginning of this week, however there's a chance that the fix is not fully addressing the problem, which is why additional diagnosis will be required at this point:

https://www.mail-archive.com/haproxy@formilux.org/msg40095.html

**Comment by lukastribus** [comment]
2.3.8 is affected by the additional bug I just mentioned, 2.3.9 has been released which fixes everything.

2.2.12 will be released shortly with the fixes for both of the issues.

**Comment by lukastribus** [comment]
@schferbe 2.2.12 was released.

**Comment by schferbe** [comment]
Thank you for notifying me. The release seems to resolve our problem.

**Comment by wtarreau** [comment]
Thank you for the nice feedback :-)
