### ISSUE TITLE
cache: do not list entries with negative expiration date

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#12]
This is another old report with little context information. It was noticed right after 1.8 was released that issuing "show cache" on the CLI would show entries with negative expiration date. It should still be true on 1.9 and above though it was not verified.

What happens is that expired objects are not actively removed, they're just not matched anymore, but since they are the oldest, their blocks will be reused so this is not a problem. However the output looks a bit dirty and it would be better to find a solution not to list them, at the very least by not showing them in the dump, and preferably by periodically scanning outdated entries to evict them. This would also help report more accurate statistics on the suitable cache size.

**Comment by TimWolla** [comment]
> It was noticed right after 1.8 was released that issuing "show cache" on the CLI would show entries with negative expiration date. It should still be true on 1.9 and above though it was not verified.

This is still true even for 2.4.x.

**Comment by wtarreau** [comment]
Now fixed, will have to be backported
