### ISSUE TITLE
Configuring crl-file breaks valid certificates

### ISSUE THREAD

**Issue by tomaszszlek** [haproxy/haproxy#1201]
## Detailed description of the problem

I have problem with using CRL in HaProxy. In short, if I have two certificates and will add CRL file with one of them to HaProxy configuration then the other one (which wasn't revoked) is considered invalid by HaProxy.

## Expected behavior

After adding CRL file to HaProxy configuration, requests from not revoked client certificates shouldn't be rejected.

## Steps to reproduce the behavior

I have following certificate chaing : RootCA → Intermediate → (leaf certificate A, leaf certificate B).
In ca.pem I have my Intermediate certificate which is used for mTLS. In crl.pem I have leaf certificate B.
My assumption was that I should still be able to authorize using certificate A since only B is revoked.
Unfortunately it doesn’t work like that, I have executed following tests:

In first scenario I am adding `crl-file /tmp/crl.pem` into `crl.list` file, here are the results:

```
Test with valid certificate A - getting 403
Test with revoked certificate B - getting 403
Test with invalid certificate C - getting 403
```

Then I have executed the same test but without CRL. I simply removed `crl-file /tmp/crl.pem` from the config. The results were as follows:

```
Test with valid certificate A - getting OK response
Test with revoked certificate B - getting OK response (its because I haven’t declared crl-file of course)
Test with invalid certificate C - getting 403
```

As I could clearly see adding CRL breaks valid certificate for some reason.
Test was executed using docker `haproxy:2.2.10-alpine`.

## Do you have any idea what may have caused this?
No

## Do you have an idea how to solve the issue?
No

## What is your configuration?

My HaProxy config:

```
defaults
  timeout server 1m
  timeout client 1m
  timeout connect 5s
listen l
  bind :443 ssl crt-list /tmp/crt.list  ca-ignore-err all crt-ignore-err all
  mode http
  http-request deny if { ssl_c_verify gt 0 }
  http-request return content-type "text/plain" string "ok\n"
```

and `crt.list` content :

`tmp/crt.pem [ca-file /tmp/ca.pem verify optional crl-file /tmp/crl.pem] !*`

## Output of `haproxy -vv` and `uname -a`

```
/ # haproxy -vv
HA-Proxy version 2.2.10-6a09215 2021/03/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.10.html
Running on: Linux 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=6).
Built with OpenSSL version : OpenSSL 1.1.1j  16 Feb 2021
Running on OpenSSL version : OpenSSL 1.1.1j  16 Feb 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20201203
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

```
/ # uname -a
Linux mypc 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 Linux

```

## Additional information (if helpful)

I have started discussing it in [HaProxy forum](https://discourse.haproxy.org/t/configuring-crl-file-breaks-valid-certificates/6354/2) however there were no answers. It seems to me like a bug so I decided to post it here.

**Comment by wtarreau** [comment]
You're in areas where way less people are skilled, that's certainly why you got no response. Adding @EmericBr, @wlallemand, @rlebreton who are more likely to judge whether that's expected or not.

**Comment by rlebreton** [comment]
Hello @tomaszszlek, thanks for the report, I'll look into it. 
Just to be sure, when you say that you put certificateB into the crl file, did you create an actual CRL file (with a BEGIN/END X509 CRL section) or did you copy certificateB?

**Comment by tomaszszlek** [comment]
Hello @rlebreton, thank you! By creating CRL file I am creating actual CRL file:

`
-----BEGIN X509 CRL-----
...
-----END X509 CRL-----
`

**Comment by rlebreton** [comment]
I ran some tests on my side, and the only time when I came across a behavior like the one you described (where adding a crl file prevents any client from connecting) was when some of my certificates were badly constructed (with empty CN fields for instance).

@tomaszszlek could you please check that all of your certificates pass an "openssl verify" test please ? The following command should work in your case :
openssl verify -CAfile RootCA.pem -untrusted IntermediateCA.pem certificateA.pem

**Comment by tomaszszlek** [comment]
Hi @rlebreton, thanks for looking at it, the above command gives "ok":
`
➜  openssl verify -CAfile certs/RootCA/ca.crt -untrusted certs/Intermediate/ca.crt certs/Intermediate/issued/valid.crt
certs/Intermediate/issued/valid.crt: OK
`

I created fake PKI that you could use to reproduce my issue, if you will test it then you will see that even using "valid" certificate HaProxy returns 403 while when removing crl section from crl-list file it starts working.
The repo can be found here : https://github.com/tomaszszlek/haproxy-crl-demo.
The password to client cert files is "secret".

**Comment by rlebreton** [comment]
Thanks @tomaszszlek , I managed to reproduce the bug with your certificates, I'll keep looking into it and hopefully find out why this bug happens.

**Comment by rlebreton** [comment]
@tomaszszlek I now have a better understanding of what is happening. I could not reproduce your bug at first because to simplify things I performed all my tests with a single CA, no root/intermediate pair. The error code raised by the ssl_c_verify when you specify a crl-list has the value 3 which means that we were "unable to get certificate CRL" (see https://www.openssl.org/docs/man1.0.2/man1/verify.html). This happens because the way we implemented the CRL in HAProxy is by requiring that when you give a CRL file, there should be one CRL section per CA in your certificate chain. You could try to run your tests again after adding an "empty" CRL file for your root CA below the intermediateCA's CRL in your crl.pem file. This worked for me.

Now considering that I did not find anything in the documentation about this need for as many CRLs as CA certificates, we could need either a DOC patch or a C patch depending on if we want to keep this behaviour or not (which is pretty likely).

@wlallemand @EmericBr In our CRL implementation, when setting the CRL-related flags in the X509_STORE, we set the flags X509_V_FLAG_CRL_CHECK and X509_V_FLAG_CRL_CHECK_ALL, the latter being the one that forces the user to build as many CRL sections as there are certificates in the CA chain (see https://www.openssl.org/docs/man1.1.0/man3/X509_VERIFY_PARAM_set_flags.html). Is this something we do want to enforce ?

**Comment by tomaszszlek** [comment]
Thank you @rlebreton for looking into this so quickly and finding a solution !
My two cents regarding `X509_V_FLAG_CRL_CHECK_ALL`, in my opinion the most flexible solution would be if HaProxy would still be able to check entire chain (including all CA's) against CRL.pem however do not enforce CA (even empty) for each CA.

**Comment by wlallemand** [comment]
I'm surprised it does not work in your use case since this a common scenario and not much changed since the implementation of the crl-file in haproxy 1.5.

I tested with your github repository without changing anything and I can make it work correctly, so I'm kind of confused.

That's how I made my test:
```
/tmp/haproxy-crl-demo$ docker run --net host --rm -v ${PWD}:/crl_test haproxy:2.2.10-alpine -f /crl_test/h.cfg
```

```
/tmp/haproxy-crl-demo$ curl --cacert certs/RootCA/ca.crt --cert certs/Intermediate/issued/valid.crt:secret --key certs/Intermediate/private/valid.key --resolve domain.com:443:127.0.0.1 https://domain.com
ok
```

Did I miss something?

**Comment by wlallemand** [comment]
Looks like you commited the Root CRL in the intermediate CA today, I missed that.

@rlebreton You are right, it looks like it's not documented in haproxy, I suppose this could be a problem if the intermediate certificate become revoked. That's a big change to remove this flag in my opinion, we should probably make it an option. Maybe we could do a patch for the documentation and backport it, and make a new option which allows this behavior in future versions of haproxy.

**Comment by tomaszszlek** [comment]
Indeed, yesterday I have updated my repo with working crl file (attached empty RootCA CRL to Intermediate CRL) so anyone who will look at my repo will find working example instead of broken one. Sorry for causing confusion !

**Comment by wlallemand** [comment]
The documentation was updated.
