### ISSUE TITLE
silent-drop not working with IPv6 connections

### ISSUE THREAD

**Issue by bjacke** [haproxy/haproxy#1203]
## Detailed description of the problem
silent-drop on tcp frontends does not work with IPv6 connections, the server sends a TCP RST after the tcp-request inspect-delay. With IPv4 connections the connects are properly dropped silently.

## Expected behavior
als IPv6 connections should be dropped silently, same like IPv4 connections

## Steps to reproduce the behavior
use sample config, then "telnet -4 ip 4673" (works, dropped silently after timeout), then "telnet -6 ip 4673" (fails, dropped with TCP RST after timeout)

## What is your configuration?

```
frontend ft_sample
        bind :::4673
        mode tcp
        tcp-request inspect-delay 2s
        tcp-request content silent-drop if !{ req_len gt 0 }
        use_backend bk_sample

```

## Output of `haproxy -vv` and `uname -a`

haproxy -vv
HA-Proxy version 2.2.8-1~bpo10+1 2021/01/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.8.html
Running on: Linux 4.9.237-vs2.3.9.8 #1 SMP Mon Sep 28 14:06:51 CEST 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-Dyw9cm/haproxy-2.2.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

**Comment by a-denoyelle** [comment]
I have tried to reproduce the issue with your configuration sample without success. For me, I see no TCP RST for both ipv4 and ipv6. Beware that it requires haproxy admin privilege to properly set the TCP_REPAIR socket option.
By the way, you are using an outdated version. If you can, do not hesitate to update at least to the latest version of the 2.2 which is currently the 2.2.11. Maybe this will fix your problem.

**Comment by bjacke** [comment]
admin privileges should not be an issue there. But it seems like the silent-drop feature is really quite picky. Also running it on the same host where haproxy runs, the telnet on IPv4 also gets a TCP RST even though remote connections don't get a TCP RST. I also don't see AF_INET[6] dependencies in the code. Maybe it's also just a OS problem.

**Comment by a-denoyelle** [comment]
In case TCP_REPAIR is not supported, the implementation sets the TTL for future RST packet to 1, which can explained why you see it nevertheless on the local host but not on a distant machine.

**Comment by lukastribus** [comment]
Which OS, libc, kernel is this and how did you get the executable (compiled locally; remotely, installed from repositories)? At least glibc-2.18 is required for `TCP_REPAIR` to be defined.

Add the define manually during compilation if the libc does not provide it (but the kernel does):

    make clean; make [...] DEFINE="-DTCP_REPAIR=19"


Run haproxy through `strace -tt` and check the calls and returns to make sure what happens.

**Comment by bjacke** [comment]
also just checked more systems, I see the described effect with v6 not silently dropped on:
Ubuntu glibc 2.31, kernel 5.4, Ubuntu 20.04 haproxy build 2.0.13
Debian Buster with glibc 2.28, kernel 4.19,  current haproxy.debian.net buster-backports-2.2 (haproxy 2.2.11)

**Comment by bjacke** [comment]
TCP_REPAIR fails, probably because the process runs as haproxy and not as root?
[pid 20603] 13:39:55.464009 setsockopt(22, SOL_TCP, TCP_REPAIR, [1], 4) = -1 EPERM (Operation not permitted)
But it's quite usual, that haproxy forks with different user than root. So the TCP_REPAIR failure is unavoidable here then?

**Comment by bjacke** [comment]
in the TTL fallback method I see for both v4 and v6:

[pid 20604] 13:45:29.310115 setsockopt(22, SOL_IP, IP_TTL, [1], 4) = 0

but for v6 this does not seem to work, still the TCP RST reaches the client.

**Comment by bjacke** [comment]
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_71/apis/ssocko.htm mentions for IP_TTL:  This option is only supported for sockets with an address family AF_INET.

**Comment by bjacke** [comment]
IPV6_UNICAST_HOPS seems to the the equivalent for AF_INET6, or?

**Comment by a-denoyelle** [comment]
You are right, ttl is an header of an ipv4 datagram, it was renamed to hop-limit for ipv6. Therefore we should probably set the corresponding options depending on the socket family here.

**Comment by lukastribus** [comment]
> TCP_REPAIR fails, probably because the process runs as haproxy and not as root?

We need the rest of the configuration, so we can shed some light on it. You are probably dropping privileges ("user", "group" settings).

I agree the workaround for TCP_REPAIR would have to be conditioned, based on the AF (`if AF_INET6: then IPPROTO_IPV6 -> IPV6_UNICAST_HOPS = 1`)

**Comment by bjacke** [comment]
> We need the rest of the configuration, so we can shed some light on it. You are probably dropping privileges ("user", "group" settings).

yes, the config has "user haproxy" in global section. I was just wondering (and assumed that first) if haproxy can regain root privileges for TCP_REPAIR maybe. No problem if not as the TTL/HOP issue is identified now, too :-)

**Comment by lukastribus** [comment]
No, we can't regain privileges, that's the point of dropping them in the first place :)

You could not drop privileges at all by removing the user/group settings, or assign `CAP_NET_ADMIN` capability to the executable. This way, you make TCP_REPAIR work.

For the TCP_REPAIR workaround we need to implement the proper syscall.

**Comment by wtarreau** [comment]
I definitely agree here!

Does something like this work for you ?
```
diff --git a/src/tcp_act.c b/src/tcp_act.c
index b3993f7de..da5878465 100644
--- a/src/tcp_act.c
+++ b/src/tcp_act.c
@@ -207,7 +207,12 @@ static enum act_return tcp_exec_action_silent_drop(struct act_rule *rule, struct
         * network and has no effect on local net.
         */
 #ifdef IP_TTL
-       setsockopt(conn->handle.fd, SOL_IP, IP_TTL, &one, sizeof(one));
+       if (conn->src->ss_family == AF_INET)
+               setsockopt(conn->handle.fd, SOL_IP, IP_TTL, &one, sizeof(one));
+#endif
+#ifdef IPV6_UNICAST_HOPS
+       if (conn->src->ss_family == AF_INET6)
+		setsockopt(conn->handle.fd, SOL_IPV6, IPV6_UNICAST_HOPS, &one, sizeof(one));
#endif
  out:
        /* kill the stream if any */
```
[note: edited above to fix the wrong option]

**Comment by bjacke** [comment]
yes, thank you, that makes IPv6 connections also get dropped without TCP RST.

**Comment by wtarreau** [comment]
OK now merged and scheduled for backporting. Thank you!

**Comment by lukastribus** [comment]
FreeBSD and MacOS builds fail:

```
src/tcp_act.c:215:31: error: use of undeclared identifier 'SOL_IPV6'
                setsockopt(conn->handle.fd, SOL_IPV6, IPV6_UNICAST_HOPS, &one, sizeof(one));
                                            ^
1 error generated.
make: *** [src/tcp_act.o] Error 1
```


I assume we need:

    -#ifdef IPV6_UNICAST_HOPS
    +#if defined(IPV6_UNICAST_HOPS) && defined(SOL_IPV6)

**Comment by wtarreau** [comment]
Oh that reminds me something. I'll have a look, I'm pretty sure FreeBSD uses something like IPPROTO_V6 or similar instead of SOL_IPV6. We already have this for one setsockopt, though I don't remember which one. I'll search for SOL_IPV6 and should find it :-)

**Comment by wtarreau** [comment]
Now backported everywhere, closing.
