### ISSUE TITLE
Haproxy stop working on FreeBSD

### ISSUE THREAD

**Issue by djadk84** [haproxy/haproxy#1206]
All Haproxy service on 10 servers stop sending traffics to their respectives backend.
A quick look into haproxy stats shows all the backend down and no traffic was going 
to them.

## Expected behavior

1. 
2. 
3. 

## Do you have any idea what may have caused this?
I'm unable to reproduce this behavior, since I didn't clearly understand how it come to happen.

## Do you have an idea how to solve the issue?
I restart the service and work for now
## What is your configuration?

```
(paste your output here)
```

## Output of `haproxy -vv` and `uname -a`

```
% haproxy -vv
HA-Proxy version 2.3.7-2d39ce3 2021/03/16 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.7.html
Running on: FreeBSD 12.2-RELEASE-p1 FreeBSD 12.2-RELEASE-p1 GENERIC amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = clang
  CFLAGS  = -O2 -I/usr/pkg/include
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1
  DEBUG   = 

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H +GETADDRINFO +OPENSSL -LUA -FUTEX +ACCEPT4 +CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with clang compiler version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace


% uname -a
FreeBSD workingdead 12.2-RELEASE-p1 FreeBSD 12.2-RELEASE-p1 GENERIC  amd64
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

**Comment by chipitsine** [comment]
2.3.7 is not the latest.
can you try to update to 2.3.9 ?

**Comment by wtarreau** [comment]
Also there is no config information here and some config mistakes could explain this. For example if you're running with huge timeouts (or even none at all) and your servers disappear and re-apper, you could end up with no connections left (just an example of course). Knowing if haproxy still responds to clients is important as well. Maybe the process is deadlocking on a bug with all threads stuck at 100% CPU. And as Ilya said, 2.3.7 isn't the one with all known fixes applied.

**Comment by djadk84** [comment]
global
    daemon
    log         127.0.0.1 local2
    chroot      /var/chroot/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     30010
    user        haproxy
    group       haproxy
    ulimit-n    100000
    h1-case-adjust date Date
    h1-case-adjust server Server
    h1-case-adjust location Location
    h1-case-adjust set-cookie Set-Cookie
    h1-case-adjust connection Connection
    h1-case-adjust content-type Content-Type
    h1-case-adjust cache-control Cache-Control
    h1-case-adjust content-length Content-Length
    h1-case-adjust content-encoding Content-Encoding
    h1-case-adjust transfer-encoding Transfer-Encoding
    h1-case-adjust access-control-allow-origin Access-Control-Allow-Origin

    # stats unix socket
    stats socket /var/chroot/haproxy/stats level admin uid haproxy gid haproxy

#---------------------------------------------------------------------
# Defaults settings
#---------------------------------------------------------------------
defaults
    timeout connect         5s
    timeout client          2m
    timeout server          2m

#---------------------------------------------------------------------
# Backend & Listen blocks settings
#---------------------------------------------------------------------
backend web_http_out
    mode        http
    option      httpclose
    option      forwardfor
    balance     roundrobin
    option      httpchk
    http-check send meth HEAD uri /status ver HTTP/1.1 hdr host web.server.com
    cookie      BACKEND insert indirect nocache maxidle 30m maxlife 8h
    server      server1 192.168.20.10:80 cookie M check inter 3s fall 3 weight 10
    server      server2 192.168.20.11:80 cookie B check inter 3s fall 3 weight 10


listen web_http_in
    maxconn     10000
    bind        192.168.20.15:80
    mode        http
    log         global
    option      httplog
    option      dontlog-normal
    option      http-ignore-probes
    option      h1-case-adjust-bogus-client
    acl         too_long hdr_val(Content-Length) gt 196608
    stick-table type ip size 500k expire 60m store conn_cur,gpc0,conn_rate(60s)
    http-request track-sc0 src table dbc_http_in
    http-response sc-inc-gpc0(0) if { status 403 }
    http-request deny if { sc_get_gpc0(0) gt 5 }
    http-request deny if too_long
    errorfile 403 /var/chroot/haproxy/403error.html
    default_backend web_http_out

backend tcp_skt_out
    mode            tcp
    option      tcp-check
    tcp-check   send-binary 7b22636d64223a2270696e67227d #{"cmd":"ping"}
    tcp-check   expect binary 7b22737461747573223a20302c2022706f6e67223a20747275657d #{"status": 0, "pong": true}
    acl login_fail res.payload(0,41) -m sub "not-logged-in"
    tcp-response inspect-delay 150ms
    tcp-response content sc-inc-gpc0(0) if login_fail
    balance         roundrobin
    server      server1-9091 192.168.20.10:9091 check inter 3s fall 3 weight 1
    server      server2-9091 192.168.20.11:9091 check inter 3s fall 3 weight 1
    

listen tcp_skt_in
    log         global
    option      tcplog
    option      dontlog-normal
    mode        tcp
    maxconn     10000
    bind        192.168.20.15:9091
    balance     roundrobin
    stick on src table tcp_skt_in
    stick-table type ip size 500k expire 60m store conn_cur,gpc0,conn_rate(60s)
    tcp-request connection track-sc0 src
    tcp-request connection reject if { src_get_gpc0 gt 10 }
    default_backend tcp_skt_out

backend tcp_socket_out
    mode            tcp
    balance     roundrobin
    server      server1-8081 192.168.20.10:8081 check inter 3s fall 3 weight 1
    server      server1-8082 192.168.20.10:8082 check inter 3s fall 3 weight 1
    server      server2-8081 192.168.20.11:8081 check inter 3s fall 3 weight 1
    server      server1-8082 192.168.20.10:8082 check inter 3s fall 3 weight 1

listen tcp_socket_in
    maxconn             10000
    bind                192.168.10.15:8081,192.168.10.15:8082
    balance     roundrobin
    default_backend     tcp_socket_out

listen stats
    bind 192.168.10.15:8080
    maxconn 100
    mode http
    stats enable
    stats uri /haproxy
    stats hide-version
    stats show-node Rproxy
    stats realm Statistics
    stats auth username:password

**Comment by wtarreau** [comment]
Just guessing, but are you certain that the servers you test with this tcp-check:
```
option tcp-check
tcp-check send-binary 7b22636d64223a2270696e67227d #{"cmd":"ping"}
tcp-check expect binary 7b22737461747573223a20302c2022706f6e67223a20747275657d #{"status": 0, "pong": true}
acl login_fail res.payload(0,41) -m sub "not-logged-in"
```
have not entered a protection mode where they refuse to respond after too many attempts ? In the past there was something like this with the mysql checks where a counter limit had to be reset in the base.

The single fact that all your LBs stopped and sees the servers down really makes me think it's something very similar. With a bit of luck you'll find some info in your servers' logs.

**Comment by djadk84** [comment]
I recall we had a similar issue with haproxy back then but this was cause due some changes in the compiler behavior.
https://www.mail-archive.com/haproxy@formilux.org/msg25795.html
Do you have more info about that bug you mention?

**Comment by capflam** [comment]
Any news on this issue ?

**Comment by capflam** [comment]
I'm closing this issue now. Feel free to reopen it if necessary.
