### ISSUE TITLE
applet:receive() Lua function hangs with certain requests

### ISSUE THREAD

**Issue by mmirold** [haproxy/haproxy#1207]
## Detailed description of the problem

We use Lua actions and services to implement an API gateway. For certain requests, the Lua logic retrieves configuration data from backend servers to route requests to the correct backend. Our implementation uses the AppletHttp class to extract information from the client request, e.g. a parameter from a form-url-encoded POST body.

Our QA team has reported problems with requests coming from IE11. For those requests, haproxy does never send back a response. The log file doesn't show any problems. The Lua service just indefinitely hangs in a in a call to `applet:receive()`.

On other browsers, the problem does not occur.

## Expected behavior

`applet:receive()` should not hang.

## Steps to reproduce the behavior

Please come back to me for a minimal reproduction if the description below is not sufficient.

## Do you have any idea what may have caused this?

On first sight, pcap traces from IE11 and e.g Firefox don't seem to show significant differences, i.e. the User-Agent header differs slightly but otherwise nothing special. One thing that *is* different, however, is that the IE sends the POST requests as two different TCP segments (headers + body) whereas Firefox sends the request completely in one segment. So, I suppose that this difference somehow confuses the haproxy applet:receive logic.

## Do you have an idea how to solve the issue?

I have sprinkled `hlua_applet_http_recv_yield()` with print statements and it seems that the function does never consider the htx request being finished. This is although the `count` variable equals the content-length of the request (after one yield resumption) in our example. I am not too familiar with haproxy internals or the HTX architecture, but what makes me suspicious it that

* By default, i.e. when someone calls `applet:receive` without parameters, `hlua_applet_http_recv_yield()` is called with a `len` value of -1. 
* As I understand the code, the only code path that makes this function return properly with len == -1 is when HTX signals a trailer or an end-of-trailer marker. According to the documentation, both are optional.

So, I think that the combination of `applet:receive` without max length and a HTX request without trailer should always trigger this behavior. That is doesn't seem to do so (or does it?) may indicate that my undestanding is flawed. However, the following patch makes the problem disappear in our case (not sure if this breaks something else, however)

```
diff --git a/src/hlua.c b/src/hlua.c
index a61809e49..7b97e13e9 100644
--- a/src/hlua.c
+++ b/src/hlua.c
@@ -4494,6 +4494,10 @@ __LJMP static int hlua_applet_http_recv_yield(lua_State *L, int status, lua_KCon
                                break;
                }

+               if (htx->flags & HTX_FL_EOM) {
+                       len = 0;
+               }
+
                co_set_data(req, co_data(req) - vlen);
                count -= vlen;
                if (len > 0)
```

## What is your configuration?

Here, how the lua code is included:
```
global
    lua-prepend-path /etc/haproxy/apigateway-http/lib/?.lua
    lua-load /etc/haproxy/apigateway-http/region-finder.lua
```
Here, how the service is triggered in a frontend section

```
    acl is-get-auth-token-endpoint path_beg /api/v1/auth/token
    http-request use-service lua.get_auth_token  if is-get-auth-token-endpoint { method POST }
```

Here, the relevant part of the Lua code
```
local function get_auth_token(applet)
	local request = http.request.parse(applet)
	local email = request.data:match(".*username=([^&]+).*")
...

core.register_service("get_auth_token",  "http", get_auth_token)
```

Edit: the `http.request.parse`comes from the https://github.com/haproxytech/haproxy-lua-http library. Here the relevant part of its code:

```
function M.request.parse(applet)
    local self = setmetatable({}, M.request)
    self.method = applet.method

    if (applet.method == "POST" or applet.method == "PUT") and
            applet.length > 0 then
        self.data = applet:receive()
        if self.data == "" then self.data = nil end
    end
```

Please let me know if you need more information.

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.4-dev14-e1b9e1-29 2021/04/01 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_SYSTEMD=1 USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER +SYSTEMD +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

```
uname -a
Linux <redacted> 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
## Additional information (if helpful)

If you need pcap traces, please let me know.

**Comment by capflam** [comment]
Thanks for the detailed report, I confirm there is a bug. I haven't perform any test yet, but by reading the code it is clear a test on `HTX_FL_EOM` flag is missing. Your patch is not that far from what should be done. I'll do some test to validate the fix, but you may tests this patch:

```diff
diff --git a/src/hlua.c b/src/hlua.c
index a61809e49..988872d50 100644
--- a/src/hlua.c
+++ b/src/hlua.c
@@ -4506,6 +4506,12 @@ __LJMP static int hlua_applet_http_recv_yield(lua_State *L, int status, lua_KCon
                }
        }
 
+       /* The message was fully consumed and no more data are expected
+        * (EOM flag set).
+        */
+       if (htx_is_empty(htx) && (htx->flags & HTX_FL_EOM))
+               len = 0;
+
        htx_to_buf(htx, &req->buf);
 
        /* If we are no other data available, yield waiting for new data. */
```

**Comment by mmirold** [comment]
Thanks :-) I can confirm that the patch works for me.

**Comment by capflam** [comment]
The fix was merged. Thanks !
