### ISSUE TITLE
"missing connect rule" error while parsing "http-check send" 

### ISSUE THREAD

**Issue by leolux** [haproxy/haproxy#1212]
Tested on HAProxy version 2.3.9-1~bpo10+1, released 2021/03/30

```
backend httptest
  option httpchk  
  http-check send hdr host foo.bar meth GET uri / 
  http-check expect status 200
```

Results in the following parsing error: 
```
'http-check send' : unable to add http-check send rule at step 2 (missing connect rule)..
```

**Comment by TimWolla** [comment]
> Results in the following parsing error:

So? Why do you believe this to be incorrect? Also: Please fill in the issue template when filing bug reports.

**Comment by leolux** [comment]
I thnk this is a bug because the following complete haproxy.conf works fine:

```
frontend reproducer
    mode http
    bind *:80    

backend reproducer_backend
	mode http
	balance roundrobin		
	option httpchk
    http-check expect string ok       		
	#http-check send hdr host foo.bar meth GET uri / 
	
	server s1 mydomain.com:10001 check
	server s2 mydomain.com:10002 check
```

But if you uncomment the line with "http-check send" I get the parsing error. I got the line from the following https://github.com/haproxy/haproxy/issues/683#issuecomment-643588803 which has two likes and the issue is marked as solved which indicates that this line is correct.

**Comment by jmagnin** [comment]
I think you are supposed to set the 'send' before the 'expect'.

**Comment by leolux** [comment]
Thanks jmagnin, you saved my day!
