### ISSUE TITLE
haproxy 2.4-dev15 opentracing crash haproxy

### ISSUE THREAD

**Issue by bandrea83** [haproxy/haproxy#1213]
## Detailed description of the problem

configuring haproxy in daemon mode and trying to read request uri or header let haproxy crash

## Expected behavior

as without daemon mode configuration span must be able to read request headers/uri or some other info about the request/response packet

## Steps to reproduce the behavior

1. enable daemon mode in global section
2. configure ot for send span with url or req.hdr("something") as tag
3. start haproxy and do a request

## What is your configuration?

```
<haproxy.cfg>

global
#   nbthread 1
    maxconn 5000
    hard-stop-after 10s
#   log localhost:514 local7 debug
#   debug
    stats socket /tmp/haproxy-fe.sock mode 666 level admin
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  httpclose
    retries 3
    maxconn 4000
    timeout connect 5000
    timeout client  50000
    timeout server  50000

listen stats
    mode http
    bind *:8001
    stats uri /
    stats admin if TRUE
    stats refresh 10s

frontend ot-test-fe-frontend
    bind *:10080
    mode http
    default_backend servers-backend

    filter opentracing id ot-test-fe config fe/ot.cfg

backend servers-backend
    mode http
    server server-1 127.0.0.1:11080

<ot.cfg>

[ot-test-fe]
    ot-tracer ot-test-tracer
        config fe/cfg-zipkin.json
        plugin libzipkin.so
#       log localhost:514 local7 debug
        option dontlog-normal
        option hard-errors
        no option disabled
        rate-limit 100.0

        scopes client_session_start
        scopes frontend_tcp_request
        scopes frontend_http_request
        scopes backend_tcp_request
        scopes backend_http_request
        scopes client_session_end

        scopes server_session_start
        scopes tcp_response
        scopes http_response
        scopes server_session_end

    ot-scope client_session_start
        span "HAProxy session" root
            baggage "haproxy_id" var(sess.ot.uuid)
        span "Client session" child-of "HAProxy session"
        event on-client-session-start

    ot-scope frontend_tcp_request
        span "Frontend TCP request" child-of "Client session"
        event on-frontend-tcp-request

    ot-scope frontend_http_request
        span "Frontend HTTP request" follows-from "Frontend TCP request"
            tag "http.method" method
            tag "http.url" url
            tag "http.version" str("HTTP/") req.ver
        finish "Frontend TCP request"
        event on-frontend-http-request

    ot-scope backend_tcp_request
        span "Backend TCP request" follows-from "Frontend HTTP request"
        finish "Frontend HTTP request"
        event on-backend-tcp-request

    ot-scope backend_http_request
        span "Backend HTTP request" follows-from "Backend TCP request"
        finish "Backend TCP request"
        span "HAProxy session"
            inject "ot-ctx" use-headers
        event on-backend-http-request

    ot-scope client_session_end
        finish "Client session"
        event on-client-session-end

    ot-scope server_session_start
        span "Server session" child-of "HAProxy session"
        finish "Backend HTTP request"
        event on-server-session-start

    ot-scope tcp_response
        span "TCP response" child-of "Server session"
        event on-tcp-response

    ot-scope http_response
        span "HTTP response" follows-from "TCP response"
            tag "http.status_code" status
        finish "TCP response"
        event on-http-response

    ot-scope server_session_end
        finish *
        event on-server-session-end

<cfg-zipkin.json>

{
    "service_name": "haproxy_test",
    "collector_host": "zipkin-ep.devapps.test.it",
    "collector_port": 80
}

```

## Output of `haproxy -vv` and `uname -a`

```
haproxy -vv
HA-Proxy version 2.4-dev15-cd430b9b7 2021/04/03 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 3.10.0-1160.21.1.el7.x86_64 #1 SMP Mon Feb 22 18:03:13 EST 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_EPOLL=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_DL=1 USE_OT=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS +OT -QUIC -PROMEX

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with OpenTracing support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [  OT] opentracing
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace

 uname -a
Linux 84ff471a608d 3.10.0-1160.21.1.el7.x86_64 #1 SMP Mon Feb 22 18:03:13 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

```

## If HAProxy crashed: Last outputs and backtraces

```
cat _log-run-fe-1617689839
[WARNING] 095/061719 (299) : config : log format ignored for proxy 'stats' since it has no log address.
[WARNING] 095/061719 (299) : config : log format ignored for frontend 'ot-test-fe-frontend' since it has no log address.

full log with ot_debug enabled in attachment

```
[haproxy-crash-full-log.txt](https://github.com/haproxy/haproxy/files/6262707/haproxy-crash-full-log.txt)

## Additional information (if helpful)

if you remove, in ot.cfg file, the tag that read req/res headers/info it work as expected

**Comment by bandrea83** [comment]
in attachment the core dump file
[core.zip](https://github.com/haproxy/haproxy/files/6264616/core.zip)

**Comment by bandrea83** [comment]
can be the problem is related to zipkin plugin, the tags are correctly readed

(gdb) frame 4
#4  0x000000000047208d in ot_span_init (tracer=0x7f71a802f090, operation_name=0x5658d90 "Frontend HTTP request", ts_steady=ts_steady@entry=0x7ffeebfb1fb0, ts_system=ts_system@entry=0x0, ref_type=2, ref_ctx_idx=<optimized out>, ref_span=0x5757b20,
    tags=tags@entry=0x7ffeebfb1d70, num_tags=3, err=err@entry=0x7ffeebfb2038) at addons/ot/src/opentracing.c:268
268             retptr = tracer->start_span_with_options(tracer, operation_name, &options);
(gdb) info local
options = {start_time_steady = {value = {tv_sec = 469945, tv_nsec = 479173649}}, start_time_system = {value = {tv_sec = 0, tv_nsec = 0}}, references = 0x7ffeebfb1ba0, num_references = 1, tags = 0x7ffeebfb1d70, num_tags = 3}
context = {idx = -1, span = 0x5757b20, destroy = 0x0}
references = {type = otc_span_reference_follows_from, referenced_context = 0x7ffeebfb1bb0}
retptr = 0x0
__func__ = "ot_span_init"

(gdb) frame 6
#6  flt_ot_scope_run (s=s@entry=0x5756e50, f=f@entry=0x5757410, chn=chn@entry=0x5756e60, conf_scope=conf_scope@entry=0x5658c30, ts=ts@entry=0x7ffeebfb1fb0, dir=dir@entry=0, err=err@entry=0x7ffeebfb2038) at addons/ot/src/event.c:247
247                             if (flt_ot_scope_run_span(s, f, chn, dir, span, &data, conf_span, ts, err) == FLT_OT_RET_ERROR)
(gdb) info local
data = {tags = {{key = 0x5658e50 "http.method", value = {type = otc_value_string, value = {bool_value = (unknown: 91674592), double_value = 4.5293266503712774e-316, int64_value = 91674592, uint64_value = 91674592, string_value = 0x576d7e0 "GET"}}}, {
      key = 0x5658f70 "http.url", value = {type = otc_value_string, value = {bool_value = (unknown: 91691008), double_value = 4.5301377085354904e-316, int64_value = 91691008, uint64_value = 91691008, string_value = 0x5771800 "/"}}}, {key = 0x5659090 "http.version", value = {
        type = otc_value_string, value = {bool_value = (unknown: 91707424), double_value = 4.5309487666997034e-316, int64_value = 91707424, uint64_value = 91707424, string_value = 0x5775820 "HTTP/1.1"}}}, {key = 0x0, value = {type = otc_value_bool, value = {
          bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0,
      value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0,
          uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}}, num_tags = 3, baggage = 0x0, log_fields = {{key = 0x0, value = {
        type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0,
          string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false,
          double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {
        type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0,
          string_value = 0x0}}}, {key = 0x0, value = {type = otc_value_bool, value = {bool_value = otc_false, double_value = 0, int64_value = 0, uint64_value = 0, string_value = 0x0}}}}, num_log_fields = 0}
span = 0x5758360
sample = <optimized out>
conf = <optimized out>
conf_ctx = <optimized out>
conf_span = <optimized out>
finish = <optimized out>
ts_now = {tv_sec = 65280, tv_nsec = 0}
retval = 1
__func__ = "flt_ot_scope_run"

**Comment by zaga00** [comment]
Hello @bandrea83,

thanks for reporting the bug.  I can't reproduce the bug on my own. I use docker Zipkin tracer and API library from the following url: https://github.com/rnburn/zipkin-cpp-opentracing/releases/download/v0.5.2/linux-amd64-libzipkin_opentracing_plugin.so.gz

Zipkin tracer is installed and running as follows:

docker pull openzipkin/zipkin-slim
docker run -d -p 9411:9411 openzipkin/zipkin-slim

Which version of Zipkin API library do you use?

Here is a screenshot of the display where you can see that all the tags are set correctly (here I added an additional tag defined like this: 'tag "http.host" req.hdr("Host")').

![image](https://user-images.githubusercontent.com/11427034/113851723-16508480-979c-11eb-95e9-0c27cb9f2507.png)

**Comment by zaga00** [comment]
Does the haproxy process crash every time you send the data to the Zipkin tracer or after a while?

**Comment by bandrea83** [comment]
Hi @zaga00, 

it only happens with daemon global option configured in haproxy. i'm using zipkin library version 0.5.2, precompiled (the one you linked) or building it make no difference

it crash immediately after the first request (i'm simply doing a curl on the listen port)

**Comment by zaga00** [comment]
Hello @bandrea83,

I have tried an example fe/be with the 'daemon' option enabled and it works for me as I wrote.

**Comment by zaga00** [comment]
Maybe if you try to turn off stdout/stderr redirection to /dev/null, the log files will be more complete.  It does haproxy if it runs in daemon mode.  The next patch excludes it:

----
diff --git a/src/haproxy.c b/src/haproxy.c
index e7d30b01f..41828f5cf 100644
--- a/src/haproxy.c
+++ b/src/haproxy.c
@@ -763,6 +763,8 @@ static void dump(struct sig_handler *sh)
  */
 static void stdio_quiet(int fd)
 {
+       return;
+
        if (fd < 0)
                fd = open("/dev/null", O_RDWR, 0);
 
----

**Comment by zaga00** [comment]
Maybe if you try to turn off stdout/stderr redirection to /dev/null, the log files will be more complete. It does haproxy if it runs in daemon mode. The next patch excludes it:

[enable-output.txt](https://github.com/haproxy/haproxy/files/6271302/enable-output.txt)

**Comment by bandrea83** [comment]
thank you, i've tried to rebuilt my container with the path you attached here but i have the same problem

here the log
[_log-run-fe-1617797439.txt](https://github.com/haproxy/haproxy/files/6271472/_log-run-fe-1617797439.txt)

i'm also using the fe-be test and here the test i'm doing:

```
curl localhost:10080 -vvv
* About to connect() to localhost port 10080 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 10080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:10080
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

i'm building haproxy using:
openssl 1.1.1k
lua 5.3.5
opentracing-cpp 1.5.0
opentracing-c-wrapper (master branch)

here the make options for haproxy:
```
    make -j4 TARGET=linux-glibc \
    USE_EPOLL=1 \
    USE_LINUX_TPROXY=1 \
    USE_REGPARM=1 \
    USE_DL=1 \
    USE_ZLIB=1 \
    USE_PCRE=1 \
    USE_PCRE_JIT=1 \
    USE_OPENSSL=1 \
    SSL_LIB=/usr/local/openssl/lib \
    SSL_INC=/usr/local/openssl/include \
    USE_LUA=1 \
    LUA_LIB=/usr/local/lua/lib \
    LUA_INC=/usr/local/lua/include \
    USE_THREAD=1 \
    USE_OT=1 \
    OT_INC=/usr/local/include \
    OT_LIB=/usr/local/lib \
    OT_RUNPATH=1 \
    OT_DEBUG=1 \
    DEFINE="-DTCP_USER_TIMEOUT=18" \
    CFLAGS="-O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label" && \
    make PREFIX=/usr install
```

everything is build from rhel7:7.9 image

**Comment by zaga00** [comment]
Hello @bandrea83,

my question may seem strange ... but it seems to me that a mix of 32-bit and 64-bit pointers appears in your log.  By any chance do you use x32 ABI when compiling some libraries or haproxy?  Let’s say we look at this function call:

`ot_span_init(0x57550b0, "Frontend HTTP request", 0x7ffd58c6d1e0, (nil), 2, -1, 0x5772cc0, 0x7ffd58c6cfa0, 3, 0x7ffd58c6d268:(nil))`

**Comment by wtarreau** [comment]
Hi @zaga00 

it's unrelated, it's just (annoyingly) always the case nowadays. Usually you have the code, bss, heap etc at low pointers and suddenly all mmaps arrive at high addresses. This makes dumps pretty much unreadable but we have to deal with that. Just for fun, have a look at `cat /proc/self/maps`.

@bandrea83 just to be sure, did you use a previous version that worked and then faced the crash after an upgrade or did you always face crashes ? (and if so since which version, sometimes it may help).

**Comment by wtarreau** [comment]
Also @bandrea83 could you please issue `bt full` in your gdb session so that we can see the full backtrace ? It will give us more info about what exact lines, states etc were used at the exact moment of the crash.

**Comment by bandrea83** [comment]
hi @wtarreau, 
daemon option works only in branch dev15, so it is not an update of version. It always crash after the first curl call (if i remove global daemon option in haproxy.cfg it work as expected)

i've tried to build master branch but the build fail on ot/src/parser.c compilation

here the bt full output
[full-bt.txt](https://github.com/haproxy/haproxy/files/6276406/full-bt.txt)

**Comment by zaga00** [comment]
On CentOS 7.9 haproxy crashes as in the example above, regardless of whether Jaeger or Zipkin API library is used.  So the bug has been confirmed and I can now investigate what the problem is.

**Comment by bandrea83** [comment]
seem that if i build the zipkin library from master source code it work as expected, so can be something related to prebuild libzipkin 1.5.0

**Comment by wtarreau** [comment]
@bandrea83 not sure what you meant about "deamon option works only in dev15", given that this keyword has been there for 20 years now since 1.0. Or maybe you're speaking about sometihng else ?

If you face build issues, please report them! Here you're just saying "build fails on ot/src/parser.c" but we have no chance to fix this on your platform if you don't indicate the error :-(

At least @zaga00 says he can reproduce the bug now so let's wait for his findings.

**Comment by bandrea83** [comment]
you're right @wtarreau, i will explain better
ot only work with daemon option from dev15 tag (issue https://github.com/haproxy/haproxy/issues/1204)

as already said, buildin zipkin-cpp from source seem to solve the issue (also using 1.5.0 tag), it send the span correctly

about master building here the error:

```
  CC      src/ev_poll.o
  CC      src/ev_epoll.o
  CC      src/ssl_sample.o
  CC      src/ssl_sock.o
  CC      src/ssl_crtlist.o
  CC      src/ssl_ckch.o
  CC      src/ssl_utils.o
  CC      src/cfgparse-ssl.o
  CC      src/hlua.o
  CC      src/hlua_fcn.o
  CC      src/namespace.o
  CC      addons/ot/src/cli.o
  CC      addons/ot/src/conf.o
  CC      addons/ot/src/event.o
  CC      addons/ot/src/filter.o
  CC      addons/ot/src/group.o
  CC      addons/ot/src/http.o
  CC      addons/ot/src/opentracing.o
  CC      addons/ot/src/parser.o
  CC      addons/ot/src/pool.o
addons/ot/src/parser.c: In function 'flt_ot_parse_cfg_tracer':
addons/ot/src/parser.c:493:3: warning: passing argument 4 of 'parse_logsrv' from incompatible pointer type [enabled by default]
   if (parse_logsrv(args, &(flt_ot_current_tracer->proxy_log.logsrvs), kw_mod == KWM_NO, &err_log) == 0) {
   ^
In file included from addons/ot/include/include.h:33:0,
                 from addons/ot/src/parser.c:20:
include/haproxy/log.h:89:5: note: expected 'const char *' but argument is of type 'char **'
 int parse_logsrv(char **args, struct list *logsrvs, int do_del, const char *file, int linenum, char **err);
     ^
addons/ot/src/parser.c:493:3: error: too few arguments to function 'parse_logsrv'
   if (parse_logsrv(args, &(flt_ot_current_tracer->proxy_log.logsrvs), kw_mod == KWM_NO, &err_log) == 0) {
   ^
In file included from addons/ot/include/include.h:33:0,
                 from addons/ot/src/parser.c:20:
include/haproxy/log.h:89:5: note: declared here
 int parse_logsrv(char **args, struct list *logsrvs, int do_del, const char *file, int linenum, char **err);
     ^
make: *** [addons/ot/src/parser.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by zaga00** [comment]
Hello all,

@wtarreau '[PATCH] MINOR: opentracing: register config file and line number on log servers' on the haproxy mailing list solves this compilation error.

@bandrea83 I can confirm: if zipkin-cpp is compiled locally, everything works ok with this API library.

Using tags crashes haproxy if original (precompiled) Zipkin (or Jaeger) OpenTracing API library is used.  Probably something is not compatible with these precompiled libraries and the old redhat linux system.

**Comment by bandrea83** [comment]
thank you all so much. i think it can be closed

**Comment by wtarreau** [comment]
OK, thank you!
