### ISSUE TITLE
Peers protocol dissector inconsistent parsing

### ISSUE THREAD

**Issue by phemmer** [haproxy/haproxy#1221]
## Detailed description of the problem

When using the peers protocol dissector, packed are parsed differently based on the order they are viewed.

## Expected behavior

Packets should be parsed consistently, no matter the order viewed.

## Steps to reproduce the behavior

1. Open packet capture
2. Click frame 225
3. Click frame 226
4. Click frame 227
5. Click frame 226

Observe that on steps 3 and 5, the message is parsed differently.

![Screenshot_2021-04-12_10-21-40](https://user-images.githubusercontent.com/1826947/114410643-89317500-9b79-11eb-9db5-08f9b94bf18f.png)
![Screenshot_2021-04-12_10-22-08](https://user-images.githubusercontent.com/1826947/114410182-2809a180-9b79-11eb-9137-e6f0397e7829.png)

## Do you have any idea what may have caused this?

Smells like some internal state used by the dissector is being incorrectly reused/not-cleared when changing the selected frame.

## Do you have an idea how to solve the issue?

No

## Additional information (if helpful)

Dissector built with commit 7b1425a

I can provide the packet capture, but contains private information. So will need an email, or other private communication channel to share.

**Comment by haproxyFred** [comment]
This is a well known bug I have decided not to fix. To parse a stick table update message we must know the previous definition message which has been received: all the update messages following this definition message depend on it. There is no information in the update message which tell us which stick-table it is referring to. This is the clicking action which triggers the parsing in Wireshark in addition to the one which is sequentially done when receiving TCP segments.

I did not take the time to fix this issue. I am not sure I will do.

Indeed, I never use wireshark anymore to analyze peers protocol traces. It is too heavy to use, too slow. tshark (mode text application) is highly better for that. It sequentially parses all the TCP segments and that's it.
