### ISSUE TITLE
Option for TLS compression?

### ISSUE THREAD

**Issue by mzealey** [haproxy/haproxy#1223]
## What should haproxy do differently? Which functionality do you think we should add?

An option to enable TLS compression (rfc3749)

## What are you trying to do?

I would like to use haproxy to sit between a non ssl service and an ssl client. But as it is a tcp stream rather than http I would like to have the option to enable tls compression in the stream I send to the client (frontend), where client supports it.

I believe `SSL_CONF_cmd(ctx, "Options", "Compression")` should enable this

There are many sites talking about tls compression vulnerabilities however I understand that these have all been fixed in tls1.3

## Output of `haproxy -vv` and `uname -a`

2.3 does not seem to have this functionality

**Comment by lukastribus** [comment]
And what is this TCP application specifically, that benefits from compression at the TLS layer?


> There are many sites talking about tls compression vulnerabilities however I understand that these have all been fixed in tls1.3

Wrong, compression has been removed from TLSv1.3.

There is no place for TLS compression across untrusted networks (which is the point of TLS).

**Comment by mzealey** [comment]
ah yes i see I got that wrong. if it's not in the standard going forwards then no point implementing it i guess.
