### ISSUE TITLE
HAProxy running but refuse connection from port 5000 of postgresql

### ISSUE THREAD

**Issue by thuybt** [haproxy/haproxy#1227]
## Detailed description of the problem

I have running HAproxy successfully 
![image](https://user-images.githubusercontent.com/59462501/115369298-2895de00-a1f2-11eb-911a-5504101eda63.png)
But unable to connect to my database throught port 5000
![image](https://user-images.githubusercontent.com/59462501/115369505-5f6bf400-a1f2-11eb-8a6d-24a39cb00df8.png)

![image](https://user-images.githubusercontent.com/59462501/115369586-7a3e6880-a1f2-11eb-80f3-291381e289b0.png)
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
## Steps to reproduce the behavior

1. systemctl start haproxy
2. systemctl status haproxy
3. 

## What is your configuration?

```
global
    maxconn 100

defaults
    log global
    mode tcp
    retries 2
    timeout client 30m
    timeout connect 4s
    timeout server 30m
    timeout check 5s

listen stats
    mode http
    bind *:8009
    stats enable
    stats uri /

listen postgres
    bind *:5000
    option httpchk
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server postgresql_10.128.0.10_5432 10.128.0.10:5432 maxconn 100 check port 8008
    server postgresql_10.128.0.11_5432 10.128.0.11:5432 maxconn 100 check port 8008
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.5.18 2016/05/10
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 8192, maxpollevents = 200

Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.7
Compression algorithms supported : identity, deflate, gzip
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
Built with PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
```
```
Linux postgre02 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

## Additional information (if helpful)

- HAProxy is installed with patroni and etcd to ensure the high availability of the Postgresql system

**Comment by lukastribus** [comment]
Please do not ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org

**Comment by curtis18** [comment]
@thuybt Did you resolve the issue? I have the same situation as yours.
