### ISSUE TITLE
Do not report HTTP 5xx in logs for termination code 'CC'

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1266]
## What should haproxy do differently? Which functionality do you think we should add?

If the client disconnects before the server connection could be established then a status code in the 5xx range in combination with termination code `CC` is logged. HTTP 5xx shows up in log analyzers as a server error, despite the server being unable to do anything about this situation.

The HAProxy log should either contain a 4xx code or something clearly invalid, such as `0` or `-1`, to indicate that the request could not be completed due to the client's behavior.

See this mailing list thread: https://www.mail-archive.com/haproxy@formilux.org/msg40556.html

## What are you trying to do?

I don't want any false positives indicating possible server / backend issues.

## Output of `haproxy -vv` and `uname -a`

```
HAProxy version 2.4.0-1~bpo10+1 2021/05/21 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.0.html
Running on: Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by NicolasCARPi** [comment]
nginx introduced error 499 - Client Closed Request which is appropriate but non standard. At least the advantage is that someone looking through the logs will be able to search for that error code and immediatly understand what happened. Whereas a 0 or -1 doesn't convey what happened. So I suggest using error 499, because the client will never get it anyway so it's okay if it's not standard IMHO, what's important is to have a clear(er) error for the sysadmin.

**Comment by wtarreau** [comment]
-1 has always been used for about 20 years to report such situations here in fact, so this one doesn't come out of nowhere, and it's already handled where relevant. The problem I'm having with valid codes (like 499) is that you cannot tell the difference between a server returning it and haproxy forcing it. And actually on an abort, since haproxy passes it to the server, chances are high that the server (if nginx) will return that one, without you having a chance to tell whether the response was delivered to the client or not.

**Comment by capflam** [comment]
@TimWolla, Here is a patch to report -1 status in logs for 'CC' and 'CQ' termination states. Does it meet your expectations ?

[0001-MINOR-http-ana-Use-1-status-for-client-aborts-during.patch.txt](https://github.com/haproxy/haproxy/files/6584611/0001-MINOR-http-ana-Use-1-status-for-client-aborts-during.patch.txt)

**Comment by TimWolla** [comment]
@capflam It's hard for me to test this, because I don't know how to clearly reproduce the issue (locally) and we generally try to consume the Debian packages in our production instances.

However based off the commit message and the diff it looks like it indeed meets my expectations.

I can try to build a testing environment to check, but this probably will not happen soon.

**Comment by capflam** [comment]
Thanks, don't bother with testing. You answered to my question. I'll merge the patch soon.
