### ISSUE TITLE
haproxy 2.0.0 and problems with http/2 connections and cookies?

### ISSUE THREAD

**Issue by darix** [haproxy/haproxy#127]
## Output of `haproxy -vv` and `uname -a`

```
haproxy -vv ; uname -a
HA-Proxy version 2.0.0 2019/06/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = x86_64
  CC      = gcc
  CFLAGS  = -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_PTHREAD_PSHARED=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_PIE=1 USE_STACKPROTECTOR=1 USE_RELRO_NOW=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD +PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.0i-fips  14 Aug 2018
Running on OpenSSL version : OpenSSL 1.1.0i-fips  14 Aug 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.4
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.41 2017-07-05
Running on PCRE version : 8.41 2017-07-05
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

Linux tengu 5.1.6-2.g2e484d7-default #1 SMP Mon Jun 3 05:27:42 UTC 2019 (2e484d7) x86_64 x86_64 x86_64 GNU/Linux

```

## What's the configuration?

```
  bind 0.0.0.0:443   tfo ssl crt-list /etc/haproxy/certlist.cfg alpn h2,http/1.1 npn h2,http/1.1 strict-sni ca-file /etc/haproxy/ca.pem
  bind :::443 v6only tfo ssl crt-list /etc/haproxy/certlist.cfg alpn h2,http/1.1 npn h2,http/1.1 strict-sni ca-file /etc/haproxy/ca.pem

```

## Steps to reproduce the behavior

on vhosts where I don't have any sessions or so I can connect just fine with the ```h2,``` bit in the configuration. on vhosts where I had a session from before the ugprade the connection just hangs. removing the ```h2,``` bit makes it work. backend is an nginx.

**Comment by lukastribus** [comment]
I think this may be because after a H2 -> H1 conversation in HTX, we lowercase all the headers, as explained here:

https://discourse.haproxy.org/t/haproxy-2-0-0-header/3930/4

Can you confirm this works with `no option http-use-htx` ?

**Comment by darix** [comment]
That seems to work.

**Comment by lukastribus** [comment]
Can you confirm your backend does not consider HTTP header names to be case-insensitive?

**Comment by wtarreau** [comment]
Christopher found a bug in the way H2 cookies are split and reassembled in HTX. This was fixed in latest 2.0-git (I have to check why the snapshots were not produced last night). It would be interesting to give this a try.

**Comment by wtarreau** [comment]
Snapshots now available (symlink was missing to the generation script).

**Comment by capflam** [comment]
In fact, bug about cookies was really fixed only this morning. So checkout the git repo or wait tomorrow for the next snapshot.

**Comment by lukastribus** [comment]
So for the record we are talking about bb0efcdd and 3e2638ee here?

**Comment by capflam** [comment]
@lukastribus, yes.

**Comment by darix** [comment]
updated to and the problem seems to be fixed 2.0.0~git6.41dc8432

**Comment by lukastribus** [comment]
Thanks.

@capflam any reason why 1.9 with htx enabled would not be affected?

**Comment by wtarreau** [comment]
On Tue, Jun 18, 2019 at 05:08:48AM -0700, Lukas Tribus wrote:
> @capflam any reason why 1.9 with htx enabled would not be affected?

I could be wrong but it's possible that the sequence of blocks in
the buffer in 1.9 resulted in the old HTX block ending up being
emptied and dropped without the size being an issue, and that in
2.0 where some small changes were made (end of headers, data, etc)
could have slightly changed this.

**Comment by capflam** [comment]
@lukastribus, sorry I missed your question. In fact, a first patch (0c6de00d) was pushed to fix the bug. It was also backported in 1.9. For the 1.9, this only patch was enough to fix the bug. But for the 2.0, the problem was  more complex because of some internal changes in the HTX.

it seems to work now in 2.0, thanks to @darix feedback. So I will close the issue.
