### ISSUE TITLE
travis-ci failure

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1272]
I will leave it for the record
https://travis-ci.com/github/haproxy/haproxy/builds/227359875

**Comment by chipitsine** [comment]
it still happens. I'm trying to bisect ...

**Comment by chipitsine** [comment]
this is breaking change: https://github.com/haproxy/haproxy/commit/7a835f3

**Comment by chipitsine** [comment]
@capflam , please have a look once you have time

**Comment by capflam** [comment]
Thanks @chipitsine, I'm on it.

**Comment by capflam** [comment]
It should be fixed now. Thanks !

**Comment by chipitsine** [comment]
I'll test tomorrow

**Comment by chipitsine** [comment]
I verified. All green
