### ISSUE TITLE
Installing HAProxy failed due to ssl-default-bind-ciphersuites

### ISSUE THREAD

**Issue by AlexeiKlimenko** [haproxy/haproxy#1273]
This bug is still active on Debian GNU/Linux 9.13 (stretch)
Last available package 2.2.14 doesn't solve this issue. What is the best way to goal it?

**Comment by wlallemand** [comment]
I'm not sure what you are talking about.
If you are talking about bug #1096 please open an issue on your distribution bug tracker.

If that's not the case, explain what your problem is by filling correctly the issue template.

**Comment by lukastribus** [comment]
>  Last available package 2.2.14 doesn't solve this issue. What is the best way to goal it?

Just remove this keyword from the configuration. Your base OS (or more precisely the openssl library) doesn't support TLSv1.3 and this is a default that doesn't belong in this configuration.

Or better yet, upgrade to Debian stable.
