### ISSUE TITLE
support for openssl 3.0.0

### ISSUE THREAD

**Issue by satya-rajesh** [haproxy/haproxy#1276]
While compiling with openssl-3.0.0 alpha17, haproxy does not compile.

In file included from include/haproxy/openssl-compat.h:7,
                 from include/haproxy/listener-t.h:37,
                 from include/haproxy/connection-t.h:34,
                 from include/haproxy/check-t.h:22,
                 from include/haproxy/server-t.h:32,
                 from include/haproxy/lb_map-t.h:26,
                 from include/haproxy/backend-t.h:30,
                 from include/haproxy/proxy-t.h:35,
                 from include/haproxy/applet-t.h:31,
                 from include/haproxy/action-t.h:25,
                 from include/haproxy/stream.h:25,
                 from include/haproxy/channel.h:30,
                 from src/ssl_sock.c:51:
src/ssl_sock.c: In function 'ctx_set_TLSv13_func':
src/ssl_sock.c:2219:5: error: missing binary operator before token "1"
 2219 | #if SSL_OP_NO_TLSv1_3
      |     ^~~~~~~~~~~~~~~~~
src/ssl_sock.c: In function 'ssl_set_TLSv13_func':
src/ssl_sock.c:2225:5: error: missing binary operator before token "1"
 2225 | #if SSL_OP_NO_TLSv1_3
      |     ^~~~~~~~~~~~~~~~~
make: *** [Makefile:906: src/ssl_sock.o] Error 1
make: *** Waiting for unfinished jobs....
error: Bad exit status from /var/tmp/rpm-tmp.r8ltyZ (%build)

**Comment by chipitsine** [comment]
what is "rpm-tmp" path ? is it some official rpm ? like Fedora ? or homegrown ?

**Comment by chipitsine** [comment]
the question is "how stable openssl-3.0 api ?" if it is frozen it makes sense to invest now. if it will be changed it would better to wait

**Comment by satya-rajesh** [comment]
> what is "rpm-tmp" path ? is it some official rpm ? like Fedora ? or homegrown ?

It is for photo OS: https://github.com/vmware/photon/

**Comment by satya-rajesh** [comment]
> the question is "how stable openssl-3.0 api ?" if it is frozen it makes sense to invest now. if it will be changed it would better to wait

beta release of openssl 3.0.0 is planned to be on June 30, 2021. it would be helpful to prioritize it.
https://github.com/openssl/openssl/milestone/17

**Comment by chipitsine** [comment]
What exactly "beta" or "alpha" means? Which one is frozen?

**Comment by wlallemand** [comment]
Support for OpenSSL 3.0.0 is planned, however the engine API is deprecated and could cause problems for some usecases.

**Comment by satya-rajesh** [comment]
> What exactly "beta" or "alpha" means? Which one is frozen?

alpha is still in development phase - haproxy can experiment with this openssl release, though no official release is expected.
beta release is when openssl team completes their features - haproxy can support from this release.

Some of the packages started their work on openssl 3.0.0:
https://github.com/dotnet/runtime/issues/46526
https://github.com/sfackler/rust-openssl/issues/1263
so on..

**Comment by wlallemand** [comment]
@chipitsine do you think you can create a CI job which builds with openssl 3.0.0 ? that could be a huge help for us.
We already tested the 3.0.0 during the 2.4 development but the API probably changed since the latest test. A CI job could be a great thing for tracking their API changes.

**Comment by chipitsine** [comment]
I will send patch

**Comment by chipitsine** [comment]
@satya-rajesh , how do you build openssl ?

I see a lot of deprecated errors https://github.com/chipitsine/haproxy/runs/2726928681


generally, I doubt whether we should rebuild OpenSSL with enabling deprecated functions or make haproxy work in hard mode (when all deprecated is disabled)

**Comment by wlallemand** [comment]
They are supposed to be enabled with the default openssl config, you can either disable them with -Wno-deprecated-declarations or just stop building with -Werror. (I prefer the last option since you still seeing them as warning).

**Comment by satya-rajesh** [comment]
> @satya-rajesh , how do you build openssl ?
> 
> I see a lot of deprecated errors https://github.com/chipitsine/haproxy/runs/2726928681
> 
> generally, I doubt whether we should rebuild OpenSSL with enabling deprecated functions or make haproxy work in hard mode (when all deprecated is disabled)

I tried this config for openssl 3.0.0, haproxy build was working till alpha16. But from alpha17, seems some changes for SSL_OP_NO_TLSv1_3 in openssl due to which build was failing as mentioned in comment 1.

./config \
    --prefix=%{_prefix} \
    --libdir=%{_libdir} \
    --openssldir=/%{_sysconfdir}/ssl \
    --api=1.1.1 \
    --shared \
    --with-rand-seed=os,egd \
    enable-egd \
    enable-deprecated \

**Comment by TimWolla** [comment]
> you can either disable them with -Wno-deprecated-declarations or just stop building with -Werror. (I prefer the last option since you still seeing them as warning).

I consider it important that the CI builds HAProxy using `ERR=1`, because if the build is green no one is ever going to look into the logs and thus not seeing the warning either.

**Comment by wlallemand** [comment]
We could just build with -Wno-deprecated-declaration then, but we won't see these warnings anymore, I don't know which is preferable.

**Comment by wlallemand** [comment]
I fixed the compilation issue for 3.0.0-alpha17, however we still have to convert the code to get ride of the deprecated API, but that is unlikely to happen before the 3.0.0 release.

**Comment by satya-rajesh** [comment]
Tried the patch: https://github.com/haproxy/haproxy/commit/f22b032956bc492dcf47b2a909f91a6fb2c6e49b
It seems to have fixed the build.

**Comment by chipitsine** [comment]
@wlallemand , what do you think if will check for

```
#ifdef SSL_OP_NO_TLSv1_3
```

instead of 

```
#if SSL_OP_NO_TLSv1_3
```

**Comment by wlallemand** [comment]
I thought about it first but it can't work because we are redefining it in openssl-compat.h, so basically it will never match.
The alternative would be to replace the "#if" by a "if", but honestly we encounter the problem only with this one, it's fine this way imho.

**Comment by chipitsine** [comment]
is this issue resolved ?

**Comment by wlallemand** [comment]
It does compile but there is still a lot of deprecated functions used, it need to be cleaned up, and the API could probably change before the final 3.0.0 release. So I prefer we let this ticket open until it's properly ported to the 3.0.0 API.

**Comment by wlallemand** [comment]
3.0.0-beta1 was released today, I took the opportunity to test it on a github action CI but it looks like something broke: https://github.com/wlallemand/haproxy/runs/2849708480. It needs to be investigated before being merged in the master.

**Comment by chipitsine** [comment]
3.0.0-beta2 released few days ago

**Comment by chipitsine** [comment]
07-Sep-2021 | Final version of OpenSSL 3.0.0 is now available: please download and upgrade!


:)

**Comment by satya-rajesh** [comment]
> 3.0.0-beta1 was released today, I took the opportunity to test it on a github action CI but it looks like something broke: https://github.com/wlallemand/haproxy/runs/2849708480. It needs to be investigated before being merged in the master.

Could you please confirm the haproxy release with openssl 3.0.0 support as openssl 3.0.0 is now released.

**Comment by wlallemand** [comment]
No OpenSSL 3.0.0 support made it in a release yet, only build with the deprecated API is supported, but at least one reg-test is failing.

**Comment by chipitsine** [comment]
interesting corner case for openssl-3.0

https://sourceforge.net/p/openvpn/mailman/message/37360686/

**Comment by vincentbernat** [comment]
Ubuntu is applying f22b032956bc492dcf47b2a909f91a6fb2c6e49b on top of 2.4 to get OpenSSL 3 support. I am being asked to do the same for Debian. Is the patch safe? If yes, could it be put in the next 2.4?

**Comment by wlallemand** [comment]
@vincentbernat That is safe to build with it. We actually never built ha2.4 with openssl3 though. I just test it and it looks like the tests are working flawlessly, so I'll probably backport this patch as well as the CI for the next 2.4 releases. I thing that is a reasonable idea to support openssl3 on 2.4 since it's the latest LTS released.

The current status for OpenSSL 3.0:
- 2.4 + OpenSSL 3 deprecated API  + https://github.com/haproxy/haproxy/commit/f22b032956bc492dcf47b2a909f91a6fb2c6e49b: OK
- 2.5 + OpenSSL 3 deprecated API: OK
- 2.6-dev + OpenSSL3 deprecated API: OK
- 2.6-dev + OpenSSL3 native API: In progress, still some work on the engine support

**Comment by wlallemand** [comment]
Current status:

**Comment by wlallemand** [comment]
Update of the status for OpenSSL 3.0:

    2.4 + OpenSSL 3 deprecated API : OK
    2.5 + OpenSSL 3 deprecated API: OK
    2.6 + OpenSSL 3 native API: OK

The support for the engines was disabled by default in 2.6 in order to achieve a default build without the deprecated API. To enable it again you need to use USE_ENGINE=1 on the make line.

The support for OpenSSL 3.0 is now considered complete, I'm closing the issue.
