### ISSUE TITLE
Rate limiting seems not work when high request

### ISSUE THREAD

**Issue by yi-guo-546** [haproxy/haproxy#1277]
# Detailed description of the problem
I use rate limit to backend url。When client request low, the rate limit work as we think. But when client request high, the rate limit seems not work.
I set 100 request in every 30s . I use hey client to request. 
When the conconnection is low, such as 4, and run 40s, i can get 202 responses which is 200.
```
hey -z 40s -c 4 http://stress-test-0.com:80/test

Summary:
  Total:	40.0004 secs
  Slowest:	0.4834 secs
  Fastest:	0.0001 secs
  Average:	0.0002 secs
  Requests/sec:	18359.0313

  Total data:	35974183 bytes
  Size/request:	48 bytes

...

Status code distribution:
  [200]	202 responses
  [429]	734167 responses
```
When the conconnection is high, such as 5 or higher, and run 40s, i can only get 101 responses which is 200.
```
hey -z 40s -c 5 http://stress-test-0.com:80/test

Summary:
  Total:	40.0004 secs
  Slowest:	0.1214 secs
  Fastest:	0.0001 secs
  Average:	0.0002 secs
  Requests/sec:	23993.5142

  Total data:	47022801 bytes
  Size/request:	48 bytes

...

Status code distribution:
  [200]	101 responses
  [429]	959649 responses
```

# Haproxy Configuration

```
Name: HAProxy
Version: 2.2.2
Release_date: 2020/07/31
```

```
frontend https
    bind *:80 

    use_backend stress-test  if { hdr_dom(host)  stress-test-0.com }  { path_beg / }

backend stress-test
    stick-table type string size 100 expire 30s store http_req_rate(30s),gpc1
    acl rate_open path,table_gpc1 gt 0
    http-request return status 429 content-type text/plain string "too frequent request for backend stress-test" if rate_open
    http-request track-sc0 path
    http-request set-var(res.req_rate) sc_http_req_rate(0)
    acl req_too_fast sc_http_req_rate(0)  gt 100
    http-request sc-inc-gpc1(0) if req_too_fast

    server-template server 100 127.0.0.1:1234 disabled check
```

# Expected behavior
In every 30s, there has about 100 request to pass.

**Comment by TimWolla** [comment]
> Version: 2.2.2

The version you are using is almost one year old and missing out on 293 bugfixes: https://www.haproxy.org/bugs/bugs-2.2.2.html.

Please upgrade and check whether you are still seeing the issue.

**Comment by yi-guo-546** [comment]
> > Version: 2.2.2
> 
> The version you are using is almost one year old and missing out on 293 bugfixes: https://www.haproxy.org/bugs/bugs-2.2.2.html.
> 
> Please upgrade and check whether you are still seeing the issue.

i use the same request in 2.2.13 version, it still has the same problem.

**Comment by capflam** [comment]
I'm unable to reproduce the issue. Except if `hey` commands are consecutively launched with no delay. And in this case, it is expected. It is more or less the same as running one test for 80s. If I wait at least 30s between two runs (regardless the number of workers), it works as expected.

**Comment by wtarreau** [comment]
There is something I don't quite understand here, the conclusion and the config contradict the title and expectation.

In the title and description it is said that the limit does *not* work when the rate is "high", and here in the tests, the "low" one had 202 responses instead of the expected ~100, while the "high" one had 101, so it looked OK.

Actually I'm surprised by the 202 responses (but as Tim said, it could be caused by one of the 193 bugs since fixed). Because normally you shouldn't see more than the maximum you configured, plus the number of threads (since the test is made before blocking and several threads can see the lower value before all deciding to block). With 4 connections that wouldn't be over 4 so that should be 104, not 202.

Please can you check that in 2.2.13 you're still seeing 202 at low connection counts ? Because clearly for me /this/ is the problem.

**Comment by capflam** [comment]
There are more than ~100 requests, because the test is performed on 40s and the 429 error is returned before incrementing the stick table counter. So, after the first 30s, the counter drops to 0 for the last 10s of the test and another bunch or requests is sent to the server.

I may have wrong, but for me there is no problem here. And I'm unable to reproduce @yi-guo-546 results if I wait more than 30s between 2 consecutive tests. However, if the second test is immediately performed after the first one, the rate limitation is still enabled and only ~100 requests are sent to the server on the last 20s.

**Comment by wtarreau** [comment]
Ah you're right indeed there's no tracking before the return so the entry should eventually disappear.

However I'm not sure why you're speaking about waiting 30s between two tests, maybe something's wrong when the table's entry is continously fetched from, so we need to let the test run continously to check the same conditions.

**Comment by wtarreau** [comment]
However by running continuously I cannot reproduce the problem. I've changed the expire and measure to 10s on the last test because 30s is unbearably long, and used a reject instead of return to make it more visible.

```
$ h1load  -c 5 http://127.0.0.1:8001/
#     time conns tot_conn  tot_req      tot_bytes    err  cps  rps  bps   ttfb
         1     4    38738    38835          21614  38734 38k7 38k8 172k 35.36u 
         2     4    76547    76644          21614  76543 37k7 37k7 0.00    -   
         3     4   114681   114778          21614 114677 38k0 38k0 0.00    -   
         4     3   152496   152594          21614 152493 37k7 37k7 0.00    -   
         5     3   190579   190677          21614 190576 38k0 38k0 0.00    -   
         6     4   228632   228729          21614 228628 38k0 38k0 0.00    -   
         7     3   266491   266589          21614 266488 37k8 37k8 0.00    -   
         8     5   304290   304387          21614 304286 37k7 37k7 0.00    -   
         9     3   342253   342351          21614 342250 37k9 37k9 0.00    -   
        10     4   380369   380568          43228 380366 38k0 38k1 172k 25.69u 
        11     3   418452   418652          43228 418450 38k0 38k0 0.00    -   
        12     2   456193   456393          43228 456191 37k7 37k7 0.00    -   
        13     3   494063   494262          43228 494060 37k8 37k8 0.00    -   
```

As we can see, we have a difference of 101 requests between tot and err on the first second, and 202 on the 10th second, all other ones are properly intercepted, but everything looks as if it's working correctly.

@yi-guo-546 please make really sure you properly upgraded your executable, you might have accidently let the old one running, or upgraded the wrong one etc. All common mistakes in a test environment, that could explain why you're the only one seeing this.

**Comment by gaulzhw** [comment]
```
backend stress-test
    stick-table type string size 100 expire 30s store http_req_rate(30s),gpc1
    acl rate_open path,table_gpc1 gt 0
    http-request return status 429 content-type text/plain string "too frequent request for backend stress-test" if rate_open
    http-request track-sc0 path
    http-request set-var(res.req_rate) sc_http_req_rate(0)
    acl req_too_fast sc_http_req_rate(0)  gt 100
    http-request sc-inc-gpc1(0) if req_too_fast
```

From the config, it limits request rate to 100 every 30s, which means every 30s it can only serve 100 request.

The expire time is 30s, when request is continuous, it never expires.

The hey tests lasts 40s, which is longer than expire time 30s. The purpose is in every 30s, only 100 requests should server, other request should be 429.

40s means have 2 window, want 200 requests server.

**Comment by wtarreau** [comment]
Yes I agree, I initially didn't notice that the track wasn't set before the return so I thought it was continously refreshed (which is often used when dealing with DDoS for example). But for me it works perfectly:
```
Status code distribution:
  [429] 771758 responses
  [503] 202 responses
```

**Comment by gaulzhw** [comment]
> Yes I agree, I initially didn't notice that the track wasn't set before the return so I thought it was continously refreshed (which is often used when dealing with DDoS for example). But for me it works perfectly:
> 
> ```
> Status code distribution:
>   [429] 771758 responses
>   [503] 202 responses
> ```

In @yi-guo-546 comments, it errors when client request rate large.
You can try if scale up rate limit.

Requests/sec:	23993.5142  compared with Requests/sec:	18359.0313

**Comment by yi-guo-546** [comment]
> Yes I agree, I initially didn't notice that the track wasn't set before the return so I thought it was continously refreshed (which is often used when dealing with DDoS for example). But for me it works perfectly:
> 
> ```
> Status code distribution:
>   [429] 771758 responses
>   [503] 202 responses
> ```

with 15s and client connection 5, the performance is right. but if you increase test time and client connection, the result will not as we performaned.
This is the latest test result by hey client.
```
hey -z 15s -c 5 http://stress-test-0.shopee.io:30641/test

Status code distribution:
  [200]	202 responses
  [429]	263165 responses
```

when I increase test time and client connection, the 200 response number do not increase as expected
```
hey -z 55s -c 10 http://stress-test-0.shopee.io:30641/test

Status code distribution:
  [200]	303 responses
  [429]	999697 responses
```

**Comment by yi-guo-546** [comment]
> Yes I agree, I initially didn't notice that the track wasn't set before the return so I thought it was continously refreshed (which is often used when dealing with DDoS for example). But for me it works perfectly:
> 
> ```
> Status code distribution:
>   [429] 771758 responses
>   [503] 202 responses
> ```

with 15s and client connection 5, the performance is right. but if you increase test time and client connection, the result will not as we performaned.
This is the latest test result by hey client.
```
hey -z 15s -c 5 http://stress-test-0.com:80/test

Status code distribution:
  [200]	202 responses
  [429]	263165 responses
  ```
when I increase test time and client connection, the 200 response number do not increase as expected
```
hey -z 55s -c 10 http://stress-test-0.com:80/test

Status code distribution:
  [200]	303 responses
  [429]	999697 responses
  ```

**Comment by wtarreau** [comment]
I get the same results with 55s, which is shocking because the tool stops at *exactly* one million requests, so that it doesn't get past the second or third period in fact. Could you please test with a more serious client, i.e. one that *does* show progress being made ? This one remains in the dark for one minute, and what I'm suspecting now is that you're only observing the client stopping the test from the beginning. As you can see below the results are total garbage, 55 seconds times 60758 req/s have never made one millon. So the client is broken!

```
$ hey -z 55s  -c 10 http://127.0.0.1:8001/

Summary:
  Total:        55.0053 secs
  Slowest:      0.0175 secs
  Fastest:      0.0001 secs
  Average:      0.0005 secs
  Requests/sec: 60758.1894
  
  Total data:   147087253 bytes
  Size/request: 147 bytes
...
Status code distribution:
  [429] 999798 responses
  [503] 202 responses
```

**Comment by yi-guo-546** [comment]
I use wrk2 client to test. The result is ok. thanks @wtarreau.

**Comment by wtarreau** [comment]
Great. FWIW if you're interested, I've added status code reporting to h1load, that gives this:

```
$ h1load -d 55 -c 10 -S http://127.0.0.1:8001/ 
#     time conns tot_conn  tot_req      tot_bytes    err  cps  rps  bps   ttfb 1xx 2xx 3xx 4xx 5xx
         1    10       10   268914       33354640      0 10.0 268k 266M 36.79u   0   0   0 268812 102 
         2    10       10   546715       67801840      0 0.00 277k 275M 36.00u   0   0   0 277801   0 
         3    10       10   820184      101711996      0 0.00 273k 271M 36.57u   0   0   0 273469   0 
         4    10       10  1091464      135350716      0 0.00 271k 268M 36.86u   0   0   0 271280   0 
         5    10       10  1367808      169617372      0 0.00 276k 273M 36.19u   0   0   0 276344   0 
         6    10       10  1640864      203476316      0 0.00 272k 270M 36.63u   0   0   0 273056   0 
         7    10       10  1913325      237261480      0 0.00 272k 270M 36.71u   0   0   0 272461   0 
         8    10       10  2190541      271636264      0 0.00 276k 274M 36.08u   0   0   0 277216   0 
         9    10       10  2462650      305377780      0 0.00 271k 269M 36.75u   0   0   0 272109   0 
        10    10       10  2737243      339427312      0 0.00 274k 272M 36.42u   0   0   0 274593   0 
        11    10       10  3013554      373698966      0 0.00 276k 273M 36.19u   0   0   0 276210 101 
        12    10       10  3288716      407819178      0 0.00 274k 272M 36.35u   0   0   0 275163   0 
        13    10       10  3565172      442099598      0 0.00 276k 273M 36.17u   0   0   0 276455   0 
        14    10       10  3837859      475912786      0 0.00 272k 270M 36.67u   0   0   0 272687   0 
        15    10       10  4113786      510127858      0 0.00 275k 273M 36.21u   0   0   0 275927   0 
        16    10       10  4390269      544411626      0 0.00 276k 273M 36.17u   0   0   0 276483   0 
        17    10       10  4665123      578493522      0 0.00 274k 272M 36.39u   0   0   0 274854   0 
        18    10       10  4943126      612965894      0 0.00 277k 275M 35.97u   0   0   0 278003   0 
        19    10       10  5212651      646386994      0 0.00 269k 267M 37.11u   0   0   0 269525   0 
        20    10       10  5489677      680738342      0 0.00 276k 274M 36.10u   0   0   0 277026   0 
        21    10       10  5763482      714699128      0 0.00 273k 271M 36.53u   0   0   0 273704 101 
        22    10       10  6034633      748321852      0 0.00 270k 268M 36.88u   0   0   0 271151   0 
        23    10       10  6305990      781970120      0 0.00 271k 268M 36.85u   0   0   0 271357   0 
```
etc. This allows you to precisely monitor when your rules match and when they don't.

**Comment by yi-guo-546** [comment]
I will use h1load to test for my work. Thanks for your great work.
