### ISSUE TITLE
HAproxy 2.0.0 build fails on RHEL/CentOS 6

### ISSUE THREAD

**Issue by DBezemer** [haproxy/haproxy#128]
## Output of `haproxy -vv` and `uname -a`
```
haproxy v2.0.0
no output from haproxy -vv as it cannot be built
```

```
Linux centos6.lcl 2.6.32-754.14.2.el6.x86_64 #1 SMP Tue May 14 19:35:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
n/a, default Makefile
```

## Steps to reproduce the behavior

1. Download source of HAproxy v2.0.0 on RHEL6/CentOS6
2. Extract source 
3. Execute:
```
/usr/bin/make -j1 CPU=generic TARGET=linux-glibc USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_REGPARM=1 'ADDINC=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' USE_LINUX_TPROXY=1 USE_THREAD=1 USE_TFO=1 ADDLIB=-Wl,-z,relro
```
4. Make fails with error:
```
src/namespace.o: In function `my_socketat':
/opt/rpm-haproxy/rpmbuild/BUILD/haproxy-2.0.0/src/namespace.c:102: undefined reference to `setns'
/opt/rpm-haproxy/rpmbuild/BUILD/haproxy-2.0.0/src/namespace.c:97: undefined reference to `setns'
collect2: ld returned 1 exit status
make[1]: *** [haproxy] Error 1
```

## Actual behavior

Make fails with error:
```
src/namespace.o: In function `my_socketat':
/opt/rpm-haproxy/rpmbuild/BUILD/haproxy-2.0.0/src/namespace.c:102: undefined reference to `setns'
/opt/rpm-haproxy/rpmbuild/BUILD/haproxy-2.0.0/src/namespace.c:97: undefined reference to `setns'
collect2: ld returned 1 exit status
make[1]: *** [haproxy] Error 1
```

## Expected behavior

Make succeeds

## Do you have any idea what may have caused this?
Incorrect assumption that setns will be available on supported distro, GlibC < 2.14 will not include this call and would require a raw syscall implementation

## Do you have an idea how to solve the issue?
Implement a raw syscall if glibc < 2.14

**Comment by lukastribus** [comment]
A raw syscall is useless, setns() is only supported in linux >= 3.0.

Either we drop namespace support from the linux-glibc target, or we require those running such old releases to disable namespace support (make TARGET=linux-glibc USE_NS=).

CentOS 6 is only supported for another 18 months. I'm not sure if it makes sense to continue to work around those old platforms especially in the those new trains.

CCing @wtarreau

**Comment by DBezemer** [comment]
@lukastribus compiling with USE_NS=0 does not resolve the issue as the portion in namespace.c is not behind that flag. setns is supported in kernel 2.6.15 and onwards and 2.6.32 is present on CentOS/RHEL after 6.6 but the glibc version present (2.12) does not provide the function.

Similar issues can be seen on other projects, where the typical approach is to mock/implement setns yourself using something like (copied from keepalived's implementation)
```
#ifndef HAVE_SETNS
#include <unistd.h>
#ifndef SYS_setns
#define SYS_setns __NR_setns
#endif

#include <sys/syscall.h>

/* For some reason Centos 6.5 doesn't define SYS_setns */
#ifndef SYS_setns
#define SYS_setns __NR_setns
#endif

#ifndef MS_SLAVE	/* Since glibc 2.12, but Linux since 2.6.15 */
#include <linux/fs.h>
#endif
static int
setns(int fd, int nstype)
{
	return (int)syscall(SYS_setns, fd, nstype);
}
#endif
```

**Comment by chipitsine** [comment]
@DBezemer , which openssl do you run on centos 6 ? default is 1.0.1, haproxy is tested against 1.0.2 and higher

**Comment by DBezemer** [comment]
@chipitsine openssl 1.0.1e as is default on CentOS 6. That is unrelated to this issue tho, setns is not part of openssl.

**Comment by chipitsine** [comment]
I know. I meant that haproxy is not tested against openssl-1.0.1

**Comment by wtarreau** [comment]
On Tue, Jun 18, 2019 at 10:09:25AM -0700, David Bezemer wrote:
> @lukastribus compiling with USE_NS=0 does not resolve the issue as the
> portion in namespace.c is not behind that flag. setns is supported in kernel
> 2.6.15 and onwards and 2.6.32 is present on CentOS/RHEL after 6.6 but the
> glibc version present (2.12) does not provide the function.

Note it's not "USE_NS=0" but "USE_NS=" (no value = empty variable).

> Similar issues can be seen on other projects, where the typical approach is
> to mock/implement setns yourself using something like (copied from
> keepalived's implementation)

We already have something like this, and in fact I'm absolutely certain
we can build without NS support as I could build it for my old firewall's
kernel 2.4 with glibc-2.2.5! So if you use "USE_NS=" with nothing, it
will *not* try to use namespaces.

**Comment by DBezemer** [comment]
@wtarreau the namespace support is not the issue, the kernel has namespace support. The issue is that the available glibc does not implement the setns function. USE_NS= does indeed skip the code relying on this.

**Comment by lukastribus** [comment]
So this is not about a build issue then, but it is about you requiring namespace support on a 2.6.32 kernel, is that what you are saying then?

It's a feature request then.

setns() is supported since linux kernel 3.0, see https://github.com/torvalds/linux/commit/0663c6f8fa37d777ede74ff991a0cba3a42fcbd7 and http://man7.org/linux/man-pages/man2/setns.2.html

**Comment by wtarreau** [comment]
On Tue, Jun 18, 2019 at 11:53:27AM -0700, David Bezemer wrote:
> The issue is that the available glibc does not implement the setns
> function.

That's what I understood. When I'm saying I got it run on glibc-2.2.5,
mind you it's about 15 years older than yours :-)

> USE_NS= does indeed skip the code relying on this.

Great, thanks for confirming. When I decided to enable it by default,
I checked all supported systems and didn't know the libc on this
distro was missing it.

Willy

**Comment by DBezemer** [comment]
@lukastribus odd that the kernel documentation is incorrect on the matter as namespace support was added in kernel 2.6.15 and user namespaces were added in 2.6.23. You can see a full history here: https://lwn.net/Articles/531114/.

@wtarreau For dealing with glibc not implementing setns() would it make sense to implement a check for this functions existence and set USE_NS= if it's not available?

**Comment by wtarreau** [comment]
On Tue, Jun 18, 2019 at 12:20:04PM -0700, David Bezemer wrote:
> For dealing with glibc not implementing setns() would it make sense to
> implement a check for this functions existence and set USE_NS= if it's not
> available?

In fact we're back to my initial intent to have a target per distro,
it's just that when starting to think about it it derived to adding
automatic support for extra features but my main concern was initially
the kernel+libc combination.

Willy

**Comment by chipitsine** [comment]
target per distro are not very useful if we do not cover them with CI

question is "are we going to treat CentOS 6 as first class citizen and add to CI"

**Comment by lukastribus** [comment]
I would just introduce `linux-glibc-legacy`, and enable everything that `linux2628` had - and nothing else.

Then we only have to maintain 2 targets, instead of twenty, and we don't need disable options, to build in older CentOs releases.

**Comment by wtarreau** [comment]
On Wed, Jun 26, 2019 at 12:24:35PM -0700, Lukas Tribus wrote:
> I would just introduce `linux-glibc-legacy`, and enable everything that
> `linux2628` - and nothing else.
> 
> Then we only have to maintain 2 targets, instead of twenty, and we don't need
> disable options, to build in older CentOs releases.

That could definitely be a good idea.

Initially I wanted to introduce distro aliases exactly for the kernel+libc
combinations in fact, and derived to other default options (which is where
I was wrong), but I think I'll reload the discussion about this soon,
because in practice even if we end up with 20 targets they don't require
any maintenance effort as history has shown since linux2628 :-)

**Comment by liurui2014** [comment]
Is there any update on this issue?

**Comment by wtarreau** [comment]
Not really, and it turned into a feature request since it's mostly about easing the configuration. It's just waiting for someone to propose a patch for the makefile to add this new linux-glibc-legacy target in fact.

**Comment by chipitsine** [comment]
I added those to `include/common/namespace.h`

https://gitlab.com/chipitsine/haproxy/commit/884c78adf73d67a587f4ead8cfc9b7e7734aed61

if nobody minds, I'll send patch to list.

also, I created very basic CI for CentOS 6.x: https://gitlab.com/chipitsine/haproxy/-/jobs/283657123

**Comment by chipitsine** [comment]
oops

https://travis-ci.com/chipitsine/haproxy/jobs/229433701

**Comment by lukastribus** [comment]
I'd suggest we don't add additional band-aid to support namespaces in CentOS, and rather implement that `linux-glibc-legacy` target instead.

I can send a patch for such a target in the next few days.

**Comment by wtarreau** [comment]
Hi Ilya,

Thanks for this. If it works fine for you, then better place this
into compat.h which is made purposely to map compatibility between
systems.

Willy

**Comment by wtarreau** [comment]
On Thu, Aug 29, 2019 at 03:24:14PM -0700, Lukas Tribus wrote:
> I'd suggest we don't add additional band-aid to support namespaces in CentOS,

I don't really mind adding a few hooks *iff* we know it adds some value,
as we've already done it a few times (see compat.h).

> and rather implement that `linux-glibc-legacy` target instead.

I agree that this one will be useful over the long term anyway so it
will be good to have it.

> I can send a patch for such a target in the next few days.

Great, thank you!

Willy

**Comment by chipitsine** [comment]
@lukastribus , I'm fine with your approach. Ok, let us wait for a patch from you.

what I'm interested is CentOS 6 CI. I'll send my patch right after you.

**Comment by chipitsine** [comment]
@DBezemer , we are very close to closing this issue.

https://cirrus-ci.com/task/5189284203593728

minor thing left is "what to do with ALPN reg test"
I do not have an elegant solution (I think we can delete that particular reg test within CentOS 6 build)

**Comment by DBezemer** [comment]
@chipitsine thanks for the update, the library on CentOS 6 does as stated not support ALPN so there is no other option than to remove the test on CentOS 6. Great to know it's now covered in CI :)

**Comment by chipitsine** [comment]
We have repaired CI
I suggest to close this issue

**Comment by wtarreau** [comment]
Let's backport the fixes to 2.0 before closing :-)

**Comment by chipitsine** [comment]
was it backported to 2.0 ?

**Comment by wtarreau** [comment]
It was forgotten, but I've done it now, thanks for the reminder. I'm now closing this issue.
