### ISSUE TITLE
2.4.0: pcre2 10.37 no longer provides posix API/ABI

### ISSUE THREAD

**Issue by kloczek** [haproxy/haproxy#1280]
https://vcs.pcre.org/pcre2/code/trunk/NEWS?revision=1310&view=markup

It would be good to move away from pcre2 posix API/ABI.

**Comment by wlallemand** [comment]
Did you had problem compiling with pcre2 10.37? The regex.h POSIX API is supposed to be used only when haproxy is not compiled with PCRE/PCRE2.

**Comment by wtarreau** [comment]
Agreed, I think we should be safe. By the way I don't find that it's a wise move from pcre inside a same major branch to remove support for a legacy API :-/  Chances that this will further maintain the old pcre in field.

**Comment by kloczek** [comment]
Still that change in pcre2  meand s that whole USE_PCRE code can be removed.

**Comment by wlallemand** [comment]
I'm not sure what you mean by that, how would you build with pcre1?

**Comment by kloczek** [comment]
Correction.
I'm only tryint to tell that with introduction of latest pcre2 USE_PCRE2 could be removed as pcre2 o longer provides posix like API/ABI.

**Comment by wtarreau** [comment]
Hmmm no. I just had a look at the code and there are still some internal API differences in option names or type names. Probably these could be automatically determined by checking another macro from the pcre lib itself, but I'm not sure it will provide a big value given that it looks like users still have to decide which ones to install for plenty of projects.

**Comment by wlallemand** [comment]
The USE_PCRE2 flag and define enable the usage of the PCRE2 lib and API. However, there are other cases where you want to build with PCRE 1, or where you don't want to build with PCRE at all but use the regex.h POSIX API  provided by your libc. I don't think we have anything to do since we are supporting 3 regex libraries here.
