### ISSUE TITLE
Haproxy 2.4.0 compilation notification

### ISSUE THREAD

**Issue by zurikus** [haproxy/haproxy#1283]
## Detailed description of the problem

Compilation of haproxy 2.4.0 on Centos 8.2 with build in prometheus metrics endpoint ( [as described here](https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/) ) is not starting and throw out notification: 

```
$ make TARGET=linux-glibc USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_REGPARM=1 USE_LUA=1 USE_OPENSSL=1 USE_PCRE=1 USE_ZLIB=1 USE_SYSTEMD=1 EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"
make: *** No rule to make target 'contrib/prometheus-exporter/service-prometheus.o', needed by 'haproxy'.  Stop.
```

## Expected behavior

make command is executing fine on top of haproxy 2.2.0 and 2.3.0 version of haproxy

## Steps to reproduce the behavior

Download haproxy source from 2.4.0 tag and execute make command provided on top of Centos 8.2 

Can you please provide some feedback, why it is happening?

**Comment by capflam** [comment]
Prometheus exporter compilation has changed in HAproxy 2.4. You should use `USE_PROMEX=1` option. In doubt, `make help` command is a good way to have the list of options.

**Comment by zurikus** [comment]
Thank you for such fast response and for right directions.

Command : 

`make TARGET=linux-glibc USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_REGPARM=1 USE_LUA=1 USE_OPENSSL=1 USE_PCRE=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1`

Worked like a charm. 

Closing.
