### ISSUE TITLE
SERVER_SOFTWARE missing from the default FCGI parameters

### ISSUE THREAD

**Issue by ziegenberg** [haproxy/haproxy#1285]
## Detailed description of the problem

I'm using the in HAProxy 2.1 newly added FastCGI protocol to relay requests directly from HAProxy to a running PHP-FPM service. The script requires the `SERVER_SOFTWARE` to be set but it's not.

## Expected behavior

According to [section 10.2 in the configuration manual](http://cbonte.github.io/haproxy-dconv/2.3/configuration.html#10.2) the CGI/1.1 specification (RFC3875) requires several variables to be passed to the script. HAProxy claims it sets them and some others commonly used by FastCGI applications.

The `SERVER_SOFTWARE` meta-variable is missing although the [RFC3875 (section 4.1.17)](https://datatracker.ietf.org/doc/html/rfc3875#section-4.1.17) claims it MUST be set _"to the name and version of the information server software making the CGI request"_.

## Steps to reproduce the behavior

1. Install & configure HAProxy with backend using `use-fcgi-app`
2. Try to access FCGI parameter `SERVER_SOFTWARE` in the script in the PHP-FPM server behind HAProxy

## Do you have any idea what may have caused this?

The `SERVER_SOFTWARE` meta-variable is not set.

## Do you have an idea how to solve the issue?

Set the `SERVER_SOFTWARE` meta-variable by default to the name and version of HAProxy running at the moment.

## What is your configuration?

I used a slightly altered version of the example configuration from [section 10.1.3 in the configuration manual](http://cbonte.github.io/haproxy-dconv/2.3/configuration.html#10.1.3)

```
frontend front-http
    mode http
    bind *:80
    bind *:

    default_backend back-moodle

backend back-moodle
    mode http
    use-fcgi-app php-fpm
    server php-fpm /run/php/moodle.sock proto fcgi

fcgi-app php-fpm
    log-stderr global
    option keep-conn

    docroot /var/www/moodle
    index index.php
    path-info ^(/.+\.php)(/.*)?$

```

## Output of `haproxy -vv` and `uname -a`

```
$ haproxy -vv
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1c FIPS  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.4
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.1 20191121 (Red Hat 8.3.1-5)
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```
```
$ uname -a
Linux moodle-web-01.xxx.xxx.xxxxx.xxx.xx 4.18.0-240.22.1.el8_3.x86_64 #1 SMP Thu Apr 8 19:01:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

It did not.

## Additional information (if helpful)

None.

**Comment by git001** [comment]
Indeed this header is not in the default_param function  
http://git.haproxy.org/?p=haproxy.git;a=blob;f=src/mux_fcgi.c;h=7be9755319131561dfc2d495ba776d469cdc8221;hb=HEAD#l1422

Maybe you can set it with http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#10.1.1-set-param

```
set-param SERVER_SOFTWARE "HAProxy version 2.2.2"
```

**Comment by capflam** [comment]
That's true, this param is missing. I'll try to add it as soon as possible. In the mean time, as @git001 said, you can set it by hand using the `set-param` directive. It is not really handy but it does the trick. Thanks !

**Comment by capflam** [comment]
It should be fixed in 2.5-dev. The patch will be backported soon. Thanks !

**Comment by ziegenberg** [comment]
Wow! That was quick. Thx a lot!

**Comment by capflam** [comment]
Now backported as far as 2.2.
