### ISSUE TITLE
Can't change the body of the HTTP request through Lua. 

### ISSUE THREAD

**Issue by greenx** [haproxy/haproxy#1287]
I needed to change the body of the HTTP request using Lua. The documentation says that this can be done using the channel class.
https://www.arpalert.org/src/haproxy-lua-api/2.2/index.html#channel-class
I tried for several days to get this to work, until I found a message on the mailing list that it was banned for the HTTP regime.
http://git.haproxy.org/?p=haproxy-1.9.git;a=commit;h=3f829a4b7
But there is not a word about this in the documentation. 
Judging by the source code, only in version 2.5 there will be nominal messages stating that this is prohibited. There is no normal message in version 2.2. 
```
...Lua function 'modify-request': runtime error: 0 from [C] method 'send',...
```

**Comment by capflam** [comment]
Indeed, the error message was introduce in the 2.3-dev4 (77016daabe). I guess we can backport it as far as 2.0. And I was pretty sure to have added a warning in the documentation, but obviously not. I'll fix that. Thanks
