### ISSUE TITLE
ACL base on TCP destination's ip address ranges

### ISSUE THREAD

**Issue by 20NE** [haproxy/haproxy#1296]
## What should haproxy do differently? Which functionality do you think we should add?

when haproxy  work on TCP mode, ACL blacklist base on destination's ip address list.

## What are you trying to do?

When HAProxy doesn't act as a reverse proxy, but instead as a "normal" forwarding proxy, I hope ACL can block tcp request when the destination is in the ip address ranges, i.e. 223.223.176.0/20 223.223.192.0/20 223.252.128.0/17

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3.10-4764f0e 2021/04/23 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.10.html
Running on: Linux 5.10.34-1-lts #1 SMP Sun, 02 May 2021 12:41:09 +0000 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -march=x86-64 -mtune=generic -O2 -pipe -fno-plt
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.3
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```

**Comment by TimWolla** [comment]
I guess giving your current configuration to use HAProxy as a forward proxy would be helpful here.

**Comment by 20NE** [comment]
Yes, as long as ACL dst support ip address rangs.
I put ip address rangs in file
my ACL config example:
``tcp-request connection reject if { dst -f ip_rangs_file }``

with error output:
```
223.223.176.0/20 223.223.192.0/20 223.252.128.0/17 is not a valid IPv4 or IPv6 address at line 1 of file "ip_rangs_file"
```

**Comment by TimWolla** [comment]
> `223.223.176.0/20 223.223.192.0/20 223.252.128.0/17 is not a valid IPv4 or IPv6 address at line 1 of file "ip_rangs_file"`

This looks like you did not separate the IP addresses by newlines, but by a space instead.

**Comment by 20NE** [comment]
Yes, no error output now, thank you.
But ACL doesn't work as expected, tcp sesstion with destinion in ip adress rangs through haproxy anyway. My config:
```
frontend socks-in
        bind 127.0.0.1:1080
    tcp-request content reject if { dst -f /path/to/ip_rangs_file }
    use_backend socks-out
```

**Comment by TimWolla** [comment]
At this point it's likely that it's not a missing feature in HAProxy, but that instead you need help with your configuration. This issue tracker isn't the right place for that. Please use the mailing list or the forum:

The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org

Please make sure to provide the *full* configuration, not just excerpts. Also explain how you make requests to HAProxy.

**Comment by 20NE** [comment]
All right, thanks for your patience.
Love haproxy, great job.
Nice day.
