### ISSUE TITLE
Unsupported Transfer-Encoding values forwarded

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [haproxy/haproxy#1301]
## Detailed description of the problem

When HAProxy receives a request with unsupported values in the Transfer-Encoding header, they are forwarded. If for example the following is sent to HAProxy:

```
GET / HTTP/1.1
Host: localhost:8080
Transfer-Encoding: JUNK, chunked

5
hello
0

```

Then HAProxy will forward the Transfer-Encoding header as-is.

## Expected behavior

According to RFC 7230 (last paragraph of https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.1):

>A server that receives a request message with a transfer coding it
>does not understand SHOULD respond with 501 (Not Implemented).

So the expected behavior is for HAProxy to respond with 501 Not Implemented.

## Steps to reproduce the behavior

1. Start Haproxy with the config below: `haproxy -f config.cfg`
2. Start a listener on port 5000: `nc -lvnp 5000`
3. Send a request with an unsupported Transfer-Encoding value to port 8080: `echo -en "GET / HTTP/1.1\r\nHost: localhost:8080\r\nTransfer-Encoding: JUNK, chunked\r\n\r\n5\r\nhello\r\n0\r\n\r\n" | nc localhost 8080`

You can see that the request turns up in stdout of the listener. Haproxy didn't reject the request.

## Do you have any idea what may have caused this?

Nope.

## Do you have an idea how to solve the issue?

Reject all requests with unsupported Transfer-Encoding values.

## What is your configuration?

```
# https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#2.5
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

listen http-in
    bind *:8080
    server server1 localhost:5000 maxconn 32
```

## Output of `haproxy -vv` and `uname -a`

`haproxy -vv`:
```
HAProxy version 2.4.1-1ce7d49 2021/06/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.1.html
Running on: Linux 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

`uname -a`:
```
Linux hostname 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

(Found by Mattias Grenfeldt and Asta Olofsson)

**Comment by wtarreau** [comment]
Indeed, but I think it's okay as we're not a server but a gateway. So as long as chunked encoding is last, we can delimit the message and pass it as-is to the server, which will decide. However, *if* we had to do any processing on the body, then we would indeed need to reject it, and I don't think we currently do, e.g. when dechunking.

Hmmm thinking about it a bit more, now since HTX we always dechunk, and I think we lose the inner encoding in this case. If that's the case, then we'd indeed have to reject it. We'll discuss this tomorrow I think. Good catch anyway!

**Comment by capflam** [comment]
This was addressed. First the `TE` header is now sanitized to only send `trailers` to the server. So no unknown encoding should be received from the server. This part will be backported.
On 2.5-DEV only, messages with an unknown encoding (so everything except `chunked`) are now rejected. A 422-Unprocessable-Content is returned to the client during the request parsing. A 502-Bad-Gateway is returned if the error occurred during the response parsing. This part will not be backported because no problem was never reported on this point and it is always a bit annoying to change the behavior of stable versions.
