### ISSUE TITLE
Support set-log-level at tcp-request content level

### ISSUE THREAD

**Issue by bedis** [haproxy/haproxy#1306]
Hi there,

I'd like to get support of `set-log-level` action at tcp-request content level. It is only supported at HTTP request and response time for now.

The use case is simple. In a LB dealing with a large amount of traffic, I'd like to quickly collect the log lines for traffic being blocked (hence I block at the `tco-request content` level). That said, these log lines are emitted with the "info" syslog severity. Which means they are "lost" in the middle of so many other log lines. If I could change these log line level to "notice" (or something else), I could forward them in a specific file and then faster discover which IPs have been blocked.

NOTE: as a workaround, for now, I use a small lua script which can itself change the log level when the threshold is passed.

**Comment by capflam** [comment]
My pleasure :)
