### ISSUE TITLE
After reload: Old process does not output stats any more

### ISSUE THREAD

**Issue by hujiko** [haproxy/haproxy#1307]
### Detailed Description of the Problem

After reloading HAProxy, the old HAProxy-Process, that still holds connection, does not report any statistics any more.
This is problematic, as there is no way of figuring out, how many connections this process is still handling.

I am trying to fetch the stats by sending `@!<old-process-id> show stat` to the haproxy-master.sock

### Expected Behavior

I would expect, that sending a "show stat" to the old process ID through the haproxy-master.sock would still show the statistics as long as the process is running

### Steps to Reproduce the Behavior

1.) Spawn up an HAProxy with any kind of frontend
2.) Create a session to it and keep the session open
3.) Perform an HAProxy reload to spawn a new process.
The old process will still hold the connection.
4.) send "show proc" to the haproxy-master.sock in order to get the old process ID.
5.) send "@!<PID> show stat" to the haproxy-master.sock
6.) You will get the following output.

```
# pxname,svname,qcur,qmax,scur,smax,slim,stot,bin,bout,dreq,dresp,ereq,econ,eresp,wretr,wredis,status,weight,act,bck,chkfail,chkdown,lastchg,downtime,qlimit,pid,iid,sid,throttle,lbtot,tracked,type,rate,rate_lim,rate_max,check_status,check_code,check_duration,hrsp_1xx,hrsp_2xx,hrsp_3xx,hrsp_4xx,hrsp_5xx,hrsp_other,hanafail,req_rate,req_rate_max,req_tot,cli_abrt,srv_abrt,comp_in,comp_out,comp_byp,comp_rsp,lastsess,last_chk,last_agt,qtime,ctime,rtime,ttime,agent_status,agent_code,agent_duration,check_desc,agent_desc,check_rise,check_fall,check_health,agent_rise,agent_fall,agent_health,addr,cookie,mode,algo,conn_rate,conn_rate_max,conn_tot,intercepted,dcon,dses,wrew,connect,reuse,cache_lookups,cache_hits,srv_icur,src_ilim,qtime_max,ctime_max,rtime_max,ttime_max,eint,idle_conn_cur,safe_conn_cur,used_conn_cur,need_conn_est,uweight,-,ssl_sess,ssl_reused_sess,ssl_failed_handshake,h2_headers_rcvd,h2_data_rcvd,h2_settings_rcvd,h2_rst_stream_rcvd,h2_goaway_rcvd,h2_detected_conn_protocol_errors,h2_detected_strm_protocol_errors,h2_rst_stream_resp,h2_goaway_resp,h2_open_connections,h2_backend_open_streams,h2_total_connections,h2_backend_total_streams,
```

### What is your configuration?

```haproxy
global
  master-worker
  log /dev/log  local0
  log /dev/log  local1 notice
  chroot /var/lib/haproxy
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s
  user haproxy
  group haproxy
  daemon
nbproc 2

  # Default SSL material locations
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private

  # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
  log global
  mode  http
  option  httplog
  option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

frontend stats
    bind *:8404
    stats enable
    stats uri /stats
    stats refresh 10s
    stats admin if TRUE

listen testbackend
    mode http
    bind :9001
    balance roundrobin
    server s1 8.8.8.8
    server s2 8.8.8.8
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.0-1ppa1~bionic 2021/05/21 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.0.html
Running on: Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-PxmLVF/haproxy-2.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Additional Information

- No local patches
- Installed HAproxy from ppa, but was also able to reproduce it with `2.0.13-2ubuntu0.1, released 2020/09/08` that comes by default with Ubuntu 20.
- Running on Ubuntu 20 and Ubuntu 18, both OS show the issue

**Comment by wtarreau** [comment]
This is something known that can be confusing. Actually what's happening is that proxies marked "disabled" in the config are purposely not dumped by the stats output, and during a soft-stop, they are also being disabled, hence they are not dumped. It should not be terribly difficult to change this, but given that it didn't appear to annoy anyone for more than a decade, it has remained of very low priority. But I'm not opposed to changing this behavior if there's a good reason for this.

**Comment by hujiko** [comment]
Thanks a lot for the reply.
It actually is confusing, at least for me.

Maybe I can give some background why I intend to use this feature at all:

We plan to use HAProxy to load balance long running TCP-Sessions, that are open for multiple days.
We then gather statistics of all HAProxy-Processes, in order to monitor how many current connections we have.
We use this not only for debugging possibly load related issues, but also to get an overview if the overall system status is healthy.
With "disabled" proxies not reporting statistics any more, after a reload the stats would indicate, that all of those connections are gone and would (falsely) lead to the suspicion, that something is broken.

I personally would expect, that when I explicitly ask a disabled process for it stats, that it then answers them. (or at least that I get an error telling me, that I am trying to fetch stats from a disabled proxy)
Not having them included in some potential "overall stats" feature, would be understandable for me.

If you are not opposed to the idea and especially if that is not a difficult change, I would really appreciate, if this change finds its way into a (near) future version of HAProxy.

**Comment by wtarreau** [comment]
Rest assured that your request definitely makes sense. I'm used to seeing this effect because whenever I upgrade haproxy I check the stats immediately before and immediately after, and the second request then goes to the old process, showing an almost empty page. I found it disturbing initially but got used to it.

I'm going to turn this issue into a feature request so that we don't forget about it.

Note that if you're interested in having a look at haproxy's internals, you're welcome to check how it works and to try to change it yourself. We can guide you through that if needed.

**Comment by hujiko** [comment]
I don't really have a clue about C, but I would love to try.

I had a look at stats.c and might have found the respective line:

```diff
diff --git a/src/stats.c b/src/stats.c
index 3458924b7..a976ee95b 100644
--- a/src/stats.c
+++ b/src/stats.c
@@ -3575,8 +3575,8 @@ static int stats_dump_proxies(struct stream_interface *si,
                }

                px = appctx->ctx.stats.obj1;
-               /* skip the disabled proxies, global frontend and non-networked ones */
-               if (!px->disabled && px->uuid > 0 && (px->cap & (PR_CAP_FE | PR_CAP_BE))) {
+               /* skip the global frontend proxies and non-networked ones */
+               if (px->uuid > 0 && (px->cap & (PR_CAP_FE | PR_CAP_BE))) {
                        if (stats_dump_proxy_to_buffer(si, htx, px, uri) == 0)
                                return 0;
                }
```

I compiled HAProxy with this patch myself and can verify, that this change will cause stats to be reported also for "disabled" proxies.

I ran `make reg-tests` with my binary and also that seemed to be successful:
```
########################## Starting vtest ##########################
Testing with haproxy version: 2.5-dev0-47ee44-266
0 tests failed, 9 tests skipped, 134 tests passed
```

How shall I proceed here?
Can I just send the two-line change to the mailing list, or was it already sufficient to ping you in this issue?

**Comment by wtarreau** [comment]
Great, thanks for testing. Could you please add a frontend and a backend in your config with the "disabled" keyword and see if they appear there ? This is my main concern. If they do, we'll face trouble and will need to distinguish the two types of "disabled". If they don't, I guess your patch above should be safe enough.

Regarding how to proceed, since this is a behaviour change, I prefer that we discuss it on the mailing list (others might have concerns or complementary suggestions).
Thanks!

**Comment by hujiko** [comment]
I tried that.

Disabled frontends work fine.
Disabled backends sadly cause the process to crash completely.

I don't really know why, as from what I saw in the code, the frontend and backend structs have their own "disabled" flag.

I also observed, that when not filtering out disabled proxies, the master process shows up, having the worker processes as "backends". :/
Also suddenly a new "MASTER" frontend was appearing, with all the workers as backend nodes. Very interesting and maybe also a nice feature, but totally out of this scope ;) 

So I came up with a different approach:

```diff
diff --git a/src/stats.c b/src/stats.c
index 3458924b7..a976ee95b 100644
--- a/src/stats.c
+++ b/src/stats.c
 src/stats.c | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/src/stats.c b/src/stats.c
index 3458924b7..e01cbcef5 100644
--- a/src/stats.c
+++ b/src/stats.c
@@ -3575,8 +3575,11 @@ static int stats_dump_proxies(struct stream_interface *si,
 		}

 		px = appctx->ctx.stats.obj1;
-		/* skip the disabled proxies, global frontend and non-networked ones */
-		if (!px->disabled && px->uuid > 0 && (px->cap & (PR_CAP_FE | PR_CAP_BE))) {
+		/* skip the global frontend proxies and non-networked ones
+		 * also skip disabled proxies unless they are still holding active sessions.
+		* This change allows retrieving stats from "old" proxies after a reload.
+		*/
+		if ((!px->disabled || (px->disabled && px->served > 0)) && px->uuid > 0 && (px->cap & (PR_CAP_FE | PR_CAP_BE))) {
 			if (stats_dump_proxy_to_buffer(si, htx, px, uri) == 0)
 				return 0;
 		}
```

So what this code does is:
- Filter out disabled proxies, UNLESS they still have `> 0` active sessions => actively serving requests.

I think that condition in code is more clear, why some disabled proxies are still included.
I am not really happy with the code in the `if()` condition, because it might be hard to read (lots of brackets, complicated condition)

But to write beautiful C-Code, my knowledge is not big enough.

I would say: Once you are happy with the code & implementation, I will contact the mailing list and then get feedback about the feature and the way this is implemented :)

EDIT:
Just to state it explicitly:
With that patch:

- after a reload I can still access old stats through the master-sock
- disabled frontends and disabled backends are still hidden in stats
- the unexpected MASTER config is also not shown any more

**Comment by wtarreau** [comment]
I'm not that much surprised for the crash (though I don't know where it happens), it's possible that some fields are not initialized and are being dereferenced. I think your idea of checking for existing connections is pretty interesting. It might not be sufficient for your use case, of course, but at least it won't hide anymore the proxies on which live connections are still present, and I think it's already an improvement.

By the way in your patch you can simplify the condition:

  `(!px->disabled || (px->disabled && px->served > 0))`

is strictly equivalent to:

  `(!px->disabled || px->served > 0)`

One approach you could be interested in experimenting with is the following: instead of having a single boolean for both disabled and stopped, we'd need two. Right now the "disabled" field is a "char" and only holds two values (0 or 1) and is always tested against 0 or non-zero. The idea would be to change in proxy.c the two occurrences of `proxy->disabled = 1` to `proxy->disabled |= 2`, and in the stats code you modified above, instead of testing
`px->disabled` you could test `!(px->disabled & 1)`.

Thus we'd have 1 for disabled, 2 for stopped. The stats would still skip the disabled ones and you'd have the stopped ones listed. This is hypothetical, I have not tested it. And this can be done in addition to your patch which I like anyway.

**Comment by hujiko** [comment]
> Instead of having a single boolean for both disabled and stopped, we'd need two

before I came up with the idea of checking the `served` attribute of the proc, I had a similar idea.
I was looking, through the proc, if there would be a way to identify, that is was shut down.
I was thinking about converting the `char` to an ENUM for `disabled` and store the reason for disabling in there.

I decided against that just because I am new to that codebase and not too skilled in C. I have the fear, that I break something without noticing. (especially as for consistency reasons I would also need to adjust the `disabled` attribute of frontends & backends)

I tried your approach of setting `disabled` to `2` when a proxy is shut down and update the condition in `stats.c` to `!(px->disabled & 1)`.

It showed the same behavior as with `px->served > 0`, with one difference:

it looks like the `mworker_proxy` gets `->disabled = 1` somewhere.
Therefore, it then is also included in the stats output, which I would call an unexpected behavior change.

If you could live with me trying to keep the change as small as possible and would be fine with this patch, then I would take the next step and inform the mailing list to make them aware and get additional feedback.

```diff
diff --git a/src/stats.c b/src/stats.c
index 3458924b7..e01cbcef5 100644
--- a/src/stats.c
+++ b/src/stats.c
@@ -3575,8 +3575,11 @@ static int stats_dump_proxies(struct stream_interface *si,
 		}

 		px = appctx->ctx.stats.obj1;
-		/* skip the disabled proxies, global frontend and non-networked ones */
-		if (!px->disabled && px->uuid > 0 && (px->cap & (PR_CAP_FE | PR_CAP_BE))) {
+		/* skip the global frontend proxies and non-networked ones
+		* also skip disabled proxies unless they are still holding active sessions.
+		* This change allows retrieving stats from "old" proxies after a reload.
+		*/
+		if ((!px->disabled || px->served > 0) && px->uuid > 0 && (px->cap & (PR_CAP_FE | PR_CAP_BE))) {
 			if (stats_dump_proxy_to_buffer(si, htx, px, uri) == 0)
 				return 0;
 		}
```

**Comment by wtarreau** [comment]
I guess you meant mworker sets disabled to 2, and that's probably when it releases its socket. However I don't understand what it's listed at this moment and not the rest of the time. It's very likely that you've stumbled upon a bug here.

But yeah, feel free to suggest your current patch on the ML and explain the small difference, I think most users will be fine with it as-is. I'm personally fine with it.

**Comment by hujiko** [comment]
> I guess you meant mworker sets disabled to 2
Yes, my fault.

Let me add a screenshot of the "new" stats table that appears when implementing the `!(px->disabled & 1)` idea:

![haproxy-master](https://user-images.githubusercontent.com/946442/123597696-f1e0d300-d7f3-11eb-99d5-bfc3d3ebfa2c.png)

This is not any frontend/listen section that I defined in the HAproxy-config.
And when reloading / having multiple worker processes running, they will all show up there. (like backend servers).

BTW: I sent the patch to the mailing list now.

**Comment by wlallemand** [comment]
Hi,
I just dig into the master code, and what's going on, is that we are doing a mworker_cli_stop() into the child in order to stop the MASTER proxy which is only supposed to be used in the master.

So what I've done is that I added the "PR_CAP_INT" capability to the mworker proxy, and I excluded this from the output stats so we could use whatever method we want.  I tested it with the `disabled |= 2` method suggest by @wtarreau and it seems to work, so if we want to use this method, we could.

https://github.com/haproxy/haproxy/commit/e7f74623e4fc7d582145b38a60c6911acc7da41d
https://github.com/haproxy/haproxy/commit/d11c5728b4b3af115b07db63f2d965bd1338affa

**Comment by wtarreau** [comment]
That's indeed a clean approach. I'd also be in favor for duplicating the current `stop_proxy()` into itself and `disable_proxy()` so that the former sets the stopped bit and the latter the disabled bit which could be used separately. It would then make sense to consider that the stopped state corresponds to the state resulting from a soft-stop (when the process is in "stopping" state), and that "disabled" is when the proxy ought not to appear anywhere (= "disabled" in the config)

**Comment by wlallemand** [comment]
I pushed a patch that implements it, stopped proxies are shown (even without connections) , but disabled one are not. the disable_proxy() function was not implemented since only the PR_DISABLED bit set during the configuration parsing was needed.
