### ISSUE TITLE
unable to load certificate chain from file error

### ISSUE THREAD

**Issue by k-nuhdim** [haproxy/haproxy#1308]
Issue - Haproxy config test is failing with below error 
         unable to load certificate chain from file '/etc/haproxy/certs/mapersite2-vs/209037_mapersite2_default_mysite.pem'.
         
Haproxy Version - haproxy version is 2.2.9-a947cc2 & tried 2.2.10-6a09215 also.

Troubleshooting details 
- Validated the SSL certificate & CA Chain - Validation is passing & No issue found on chain also. 
- Created new file with certificate content and tried - No luck.
- No other security issue like selinux context and all.
- Tried to reproduce the issue from diffrent haproxy with the same certificate - No luck, it's throwing an error there also.

Note: Its working fine on older Haproxy v1.8

**Comment by TimWolla** [comment]
If you want to report a bug then please use the 'Bug Report' issue form and fill in all the requested fields carefully.

If you don't think this is a bug and you want help fixing your configuration then the correct place is either the forum or the mailing list.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
