### ISSUE TITLE
Better error message when HTTP request is too large

### ISSUE THREAD

**Issue by peterellisjones** [haproxy/haproxy#1309]
### Your Feature Request

Hi folks, when sending a request with very large headers where the total header payload is close to or greater in size than `tune.bufsize - tune.maxrewrite`, the user gets a generic 400 error which looks like this:

```
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
``` 

It is not very clear to users that this error has occurred due to HAProxy buffer size limits -- would it be possible to improve the error to suggest that the headers might be too large?

### What are you trying to do?

Run a platform-as-a-service supporting users who tend to create all kinds of unusual HTTP requests, and who may get stuck if they receive generic rather than a specific error message caused by -- in this example -- HTTP headers that are too large.

A clearer message could be something like:
```
<html><body><h1>400 Bad request</h1>
HTTP request too large, maximum allowed size is X bytes. You may need to reduce the total size of headers in the request.
</body></html>
``` 

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.14-a07ac36 2021/04/29 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.14.html
Running on: Linux 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=yes USE_STATIC_PCRE2=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE +STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.1
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : no (libpcre2 build without JIT?)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

**Comment by wtarreau** [comment]
We envisoned using 414 or 431 for this some time ago, but I think it simply never drew enough interest so that someone started to work on it. These could allow you to tailor it to your needs and mention in details what the problem is in a custom message for example.

Is this something you could be interested in working on, with some guidance ? It should not be very hard, as I think there are very few places detecting this specific condition in the parser right now.

**Comment by plowin** [comment]
Just stumbled across this and am wondering why there seems to be such a low demand for this? End-users should benefit a lot from such an enhancement or is this a rare HAProxy config?

**Comment by wtarreau** [comment]
It seems very few users are interested. This request probably happened less than 3-4 times in 20 years. We're currently busy cleaning up the last parts before 2.7 release next week. But if you're interested in trying to work on this, do not hesitate to have a look and even propose a patch. I'm willing to help you get it merged if needed. It's not that difficult :-)

**Comment by capflam** [comment]
414 or 431 error responses are now returned by the H1 multiplexer when appropriate. Thanks !

**Comment by maxmoehl** [comment]
This change has now hit our BOSH release of HAProxy and as expected the [test that checks for a 400](https://github.com/cloudfoundry/haproxy-boshrelease/blob/dd88c257319902bf3a971e1fde4435dd9269b6bb/acceptance-tests/buffer_size_test.go#L49-L56) is now failing. However, it reports that the status code is 414 even though we are pushing the headers, not the URI:

```
  [FAILED] Expected
      <int>: 414
  to equal
      <int>: 400
```

Looking at the change I think there might be a bug:

https://github.com/haproxy/haproxy/blob/06821dc1897c48555dc9047ca534060cfa99440d/src/h1_htx.c#L398-L401

This checks `h1m->err_state` which is not yet set at this point and will be set after we `goto error`. If we change this to check against `h1m->state` (which is what `err_state` will be set to) it should work as intended.

I'll spend a few minutes today to see if this is indeed the issue and submit a fix if it is.

Edit: seems like this is indeed a bug, I've submitted `[PATCH] BUG/MEDIUM: mux-h1: fix 414 / 431 status code reporting` to the mailing list.

**Comment by capflam** [comment]
It seems you're right. good catch !
