### ISSUE TITLE
promex: perform backend-level aggregations for some server metrics

### ISSUE THREAD

**Issue by pierrecdn** [haproxy/haproxy#1312]
### Your Feature Request

I'm continuing here a discussion that was started here a while ago: https://www.mail-archive.com/haproxy@formilux.org/msg35369.html

As we expected during the change (hi @wdauchy :smile: ), the `haproxy_server_check_status` metric was already complex to operate at scale prior to 2.4, but now that it's using the new label-based representation, it becomes a bit more complex to store it in a TSDB at scale with decent retention levels and aggregation capabilities.

As an example, for a 50 haproxy load-balancers setup, using 50 backends, with ~10 to 1000 servers each. Now that we're using a value encoded on 16 `state` labels, it generate cardinalities representing millions of instant data points.

Scrape duration is perfectly fine (even under these conditions fetching a few tens of MBs is perfectly doable and fast when using:
```
  params:
    no-maint:
    - empty
```
Regarding metric storage, a good hint to avoid storing everything is to perform some kind of opt-in in prometheus:
```
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: haproxy_(process_|frontend_|backend_|server_check_status).*
    replacement: $1
    action: keep
```
:arrow_up: here I'm keeping process/frontend/backend metric, and I only keep servers check_status.

But still, it's a bit too much to have decent numbers regarding evaluation time when you operate these metrics to create a backend-level representation, for ex. using:
```
record:haproxy_backend_check_status
expr:sum without(server) (haproxy_server_check_status)
```

I was wondering what do you think to create the metric directly at the exporter level so that some people :smirk: could avoid storing server_metrics without any accuracy issue (this one and maybe others that might make sense such as `haproxy_server_status`).

For these `sum` aggregations, instead of a boolean, the metric number would represent the number of servers under a given state.
Example: this "be_foo-bar" backend has 100 servers, 98 of them in the L7OK state. 
```
haproxy_backend_check_status{proxy="be_foo-bar",state="HANA"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="SOCKERR"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L4OK"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L4TOUT"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L4CON"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L6OK"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L6TOUT"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L6RSP"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L7TOUT"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L7RSP"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L7OK"} 98
haproxy_backend_check_status{proxy="be_foo-bar",state="L7OKC"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="L7STS"} 2
haproxy_backend_check_status{proxy="be_foo-bar",state="PROCERR"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="PROCTOUT"} 0
haproxy_backend_check_status{proxy="be_foo-bar",state="PROCOK"} 0
```

### What are you trying to do?

I'm trying to reduce the memory allocated to prometheus and the time to compute relatively simple aggregations... by a lot.

Without loosing visibility on these metrics (actually, it's awesome to be able to produce such visualizations for my users:
![image](https://user-images.githubusercontent.com/4225738/123852380-87778200-d91c-11eb-86d0-d50072b0b127.png)
)

### Output of `haproxy -vv`

```plain
I'm using 2.4.1.
```

**Comment by wdauchy** [comment]
Thank you for this complete feedback. The aggregation was indeed something more or less mandatory short term because of the reasons you mentioned above. The implementation will be somehow a challenge to avoid creating a new problem while trying to generate that on haproxy side (meaning, we aggregate the server values, in a backend side, which is currently not done). I however agree this will be more convenient for the user.
nitpick for naming I am a bit puzzle with `haproxy_backend_check_status` as the value will have a different meaning than the server equivalent, but I do not have a better proposition yet.

**Comment by pierrecdn** [comment]
> nitpick for naming I am a bit puzzle with haproxy_backend_check_status as the value will have a different meaning than the server equivalent, but I do not have a better proposition yet.

That's not nitpicking, I agree it could be something different indeed to differentiate from a "native" backend metric. But at trying `haproxy_backend_server_check_status` or `haproxy_server_backend_check_status` I was not really satisfied :slightly_smiling_face:

**Comment by pierrecdn** [comment]
@wdauchy anybody else to mention who could provide a feedback on this? Is there any chance for it to be accepted?

**Comment by wdauchy** [comment]
I haven't look into the details but the main change will be around calling the collection of a given metric of all the servers from a backend context. In fact we already do that for some fields such as UWEIGHT (see `fill_be_stats_computesrv`), so I don't see how this could be an issue, apart from adding more overhead to output a given metric.

@capflam will probably be the one to validate the technical part. I however can look into the implementation if you are not already on it.

**Comment by capflam** [comment]
It is doable. However, I don't know if we should aggregate all status in a loop on the server list or if we should instead work on the exporter to have a true internal state and increment the right counter when the check status of each server is dumped. My concerns is about consistency between the servers metric and the aggregated one. In addition, having an internal state for the exporter instead of hijacking the stats applet state may be a good way to add filters on metrics.

About the overhead, I guess it could be nice to have an option to enable/disable the aggregated metric. Maybe we can choose to dump aggregated metric or the per-server metric but not both in same time. It is a good way to avoid consistency issues. About then naming, what do you think about `haproxy_backend_aggregated_server_check_status` or `haproxy_backend_agg_server_check_status` ?

**Comment by pierrecdn** [comment]
> I however can look into the implementation if you are not already on it.

Unfortunately, I'm not :watch:

> However, I don't know if we should aggregate all status in a loop on the server list or if we should instead work on the exporter to have a true internal state and increment the right counter when the check status of each server is dumped.

Can't this create performance issues during access to the endpoint?
Update: from what i see it would be quite minor since we loop over the servers anyway. It should be a matter of creating multiple temporary variables [in the loop](https://github.com/haproxy/haproxy/blob/master/addons/promex/service-prometheus.c#L942)?

> In addition, having an internal state for the exporter instead of hijacking the stats applet state may be a good way to add filters on metrics.

I :+1: this, it'd be even more powerful than passing `?no-maint`

> About the naming, what do you think about haproxy_backend_aggregated_server_check_status or haproxy_backend_agg_server_check_status ?

I'd be more in favor of `agg` on my side (more concise, less chance to collide with something else in the future?).

**Comment by capflam** [comment]
Now implemented and backported to 2.4. Thanks @wdauchy !

**Comment by pierrecdn** [comment]
Hi @capflam @wdauchy,
At trying to use these metrics instead of my old home-made aggregations I discovered something .. bad.
The `haproxy_backend_agg_server_check_status` is in fact producing an aggregation of `haproxy_server_status` instead of `haproxy_server_check_status` :confused: .
So, now that they may be active users, should we rename right now this to `haproxy_backend_agg_server_status`?
What about the "real" `haproxy_backend_agg_server_check_status` metric?

**Comment by wdauchy** [comment]
> Hi @capflam @wdauchy, At trying to use these metrics instead of my old home-made aggregations I discovered something .. bad. The `haproxy_backend_agg_server_check_status` is in fact producing an aggregation of `haproxy_server_status` instead of `haproxy_server_check_status` 😕 . So, now that they may be active users, should we rename right now this to `haproxy_backend_agg_server_status`? What about the "real" `haproxy_backend_agg_server_check_status` metric?

good point. it's true that I only had server status in mind at that moment.
I am not really confortable with a rename though as it might break some usages. But I agree this will however clarify the future.

**Comment by cpaillet** [comment]
@wdauchy I try a fix here https://www.mail-archive.com/haproxy@formilux.org/msg42905.html, renaming the value you created, and create a new one for `haproxy_backend_agg_server_check_status`
