### ISSUE TITLE
Format string documentation improvements requested

### ISSUE THREAD

**Issue by mzealey** [haproxy/haproxy#1317]
### Detailed Description of the Problem

The configuration manual (both for 1.8 and 2.4) lists %Ta as being available in all modes. However haproxy doesn't start when trying to use this in tcp mode. https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#8.2.4

### Expected Behavior

Docs should probably be updated with a H in the table

### Steps to Reproduce the Behavior

Start haproxy in tcp mode with logstring containing %Ta

### What is your configuration?

```haproxy
n/a
```

### Output of `haproxy -vv`

```plain
1.8 and 2.4 affected
```

**Comment by capflam** [comment]
Documentation updated. Thanks !
