### ISSUE TITLE
2.4.2: missing git tag

### ISSUE THREAD

**Issue by kloczek** [haproxy/haproxy#1318]
### Detailed Description of the Problem

Looks like there is no in git repo git tag for 2.4.2.

### Expected Behavior

N/A

### Steps to Reproduce the Behavior

N/A

### Do you have any idea what may have caused this?

N/A

### Do you have an idea how to solve the issue?

N/A

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
N/A
```

### Last Outputs and Backtraces

```plain
N/A
```

### Additional Information

N/A

**Comment by TimWolla** [comment]
The HAProxy repository on GitHub contains the development branch. Once a release is created this development branch is forked into the respective release branch with any fixes cherry picked into the release branch.

Thus you can only find tags for development versions within this repository. Use the repositories on haproxy.org to find the release tags. In your case this is: https://git.haproxy.org/?p=haproxy-2.4.git

**Comment by kloczek** [comment]
> The answer [here](https://github.com/haproxy/haproxy/issues/49#issuecomment-467222505) show a valid option to recognize new versions. Why isn't that an option for you to get informed about new versions?

Because as I'm working on whole OS distribution signing to yet another mailing list and add processing some hand written remails to obtain action trigger that new version has been released is not an option.

Creating new copy of the git repo instead just BRANCH is really UNIQUE approach.
Why git is used that very lobotomised way?  🤔 

As you see I'm not the only person which is asking the same question and I'm sure that I'll be not last one.

**Comment by lukastribus** [comment]
You mean, why are we not using Github for absolutely everything, just because it happens to make your workflow easier?

Github is not the center of the world, and it's certainly not the center of open source software.

Haproxy stable trees with bugfix tags are openly accessible with any git client. If that is not enough for you, than I'm afraid we can't help you.
