### ISSUE TITLE
`-m` might be broken in current dev

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1319]
see https://github.com/haproxy/haproxy/commit/6fd0450b47ce81dacc53057e5e05d1c2920fdf82#commitcomment-53491847

and:

https://github.com/haproxy/haproxy/commit/6fd0450b47ce81dacc53057e5e05d1c2920fdf82#diff-91a87d0577ca56659f3b8bc2814349b0462397368b4d966681564750a99cc786L2001-L2015

**Comment by wtarreau** [comment]
I'm sorry but I don't understand the question nor comment. I feel like I've done something wrong that the reporter spotted but I can't figure what was actually noticed nor what the question focuses on at first glance. Cc @nafets227.

**Comment by TimWolla** [comment]
@wtarreau In that commit 6fd0450b47ce81dacc53057e5e05d1c2920fdf82 you removed the

```
	/* recompute the amount of per-process memory depending on
	 * the shared SSL cache size
	 */
```

part from haproxy.c which looked not intentional to the reporter. If that `if (global.rlimit_memmax_all) {` condition was intentionally removed you can simply close this issue. Otherwise you should revert that change.

**Comment by TimWolla** [comment]
Or more specifically you also removed the `global.rlimit_memmax = global.rlimit_memmax_all;` part in the `#else` of the preprocessor condition.

**Comment by wtarreau** [comment]
Ah got it now. You're right, that looks suspicious. I suspect I didn't notice the difference between rlimit_memmax_all and rlimit_memmax. I'll have to review that change. I'm not releasing yet then. Thank you!

**Comment by wtarreau** [comment]
Now fixed, thank you!

**Comment by nafets227** [comment]
Thank you @TimWolla for explaining and @wtarreau for fixing, while I was in delay answering. You exactly hit the point I detected when analyzing an issue in my setup.
