### ISSUE TITLE
Can't build with OpenTracing support with library installed in /usr/lib

### ISSUE THREAD

**Issue by ssgelm** [haproxy/haproxy#1323]
### Detailed Description of the Problem

I am packaging opentracing-cpp and opentracing-c-wrapper for Debian in order to enable OpenTracing to the haproxy Debian package. As a result, the opentracing libraries are installed into `/usr/lib`, not to a different location like `/opt`. This means that the `pkg-config` cflags for opentracing-c-wrapper end up being empty, because `/usr/lib` is already in the include path. For example (debug flag added so you can see what it's doing):
```
$ pkg-config --cflags opentracing-c-wrapper --debug
Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Looking for package 'opentracing-c-wrapper'
Looking for package 'opentracing-c-wrapper-uninstalled'
Reading 'opentracing-c-wrapper' from file '/usr/lib/x86_64-linux-gnu/pkgconfig/opentracing-c-wrapper.pc'
Parsing package file '/usr/lib/x86_64-linux-gnu/pkgconfig/opentracing-c-wrapper.pc'
  line>prefix=/usr
 Variable declaration, 'prefix' has value '/usr'
  line>exec_prefix=${prefix}
 Variable declaration, 'exec_prefix' has value '/usr'
  line>libdir=${prefix}/lib/x86_64-linux-gnu
 Variable declaration, 'libdir' has value '/usr/lib/x86_64-linux-gnu'
  line>includedir=${prefix}/include
 Variable declaration, 'includedir' has value '/usr/include'
  line>
  line>Name: opentracing-c-wrapper
  line>Description: The OpenTracing C wrapper library.
  line>Version: 1.1.0
  line>
  line>Requires:
  line>Libs: -L${libdir} -Wl,--rpath,${libdir} -lopentracing-c-wrapper
  line>Cflags: -I${includedir}
Path position of 'opentracing-c-wrapper' is 4
Adding 'opentracing-c-wrapper' to list of known packages
Package opentracing-c-wrapper has -I/usr/include in Cflags
Removing -I/usr/include from cflags for opentracing-c-wrapper
Package opentracing-c-wrapper has -L /usr/lib/x86_64-linux-gnu in Libs
Removing -L /usr/lib/x86_64-linux-gnu from libs for opentracing-c-wrapper
 post-recurse: opentracing-c-wrapper
adding CFLAGS_OTHER string ""
 post-recurse: opentracing-c-wrapper
 original: opentracing-c-wrapper
   sorted: opentracing-c-wrapper
adding CFLAGS_I string ""
returning flags string ""
```
Therefore, when I try to build haproxy with `USE_OT` it fails with the error:
```
make[2]: Entering directory '/build/haproxy-2.4.2'
addons/ot/Makefile:27: *** OpenTracing C wrapper : can't find headers.  Stop.
make[2]: Leaving directory '/build/haproxy-2.4.2'
```

### Expected Behavior

I expect haproxy to build properly and not fail with an error.

### Steps to Reproduce the Behavior

1. Install `opentracing-cpp` and `opentracing-c-wrapper` with a prefix of `/usr`
2. Attempt to build haproxy with `USE_OT=1`
3. The `make` should fail.

### Do you have any idea what may have caused this?

When pkg-config gets the cflags for a library it does not add a `-I` flag for libraries already in the include path. Since `/usr/lib` is already in the include path the cflags are empty. This breaks the assertion in the Makefile that assumes that an empty list of cflags means the library isn't installed. It's obviously not the correct fix, but the following patch works around the issue and allows me to compile:
```patch
--- a/addons/ot/Makefile
+++ b/addons/ot/Makefile
@@ -23,9 +23,9 @@
 endif
 endif

-ifeq ($(OT_CFLAGS),)
-$(error OpenTracing C wrapper : can't find headers)
-endif
+# ifeq ($(OT_CFLAGS),)
+# $(error OpenTracing C wrapper : can't find headers)
+# endif

 ifeq ($(OT_LIB),)
 OT_LDFLAGS = $(shell pkg-config --silence-errors --libs $(OTC_WRAPPER)$(OT_DEBUG_EXT))
```

### What is your configuration?

```haproxy
I don't think much configuration is helpful here, but I am building on a Debian unstable host using the Debian packaging tooling for haproxy. The opentracing libraries are installed via deb packages to /usr/lib
```

### Output of `haproxy -vv`

```plain
N/A, since I can't actually build haproxy.
```

**Comment by chipitsine** [comment]
we specify USE_OT, OT_LIB, OT_INC, OT_RUNPATH for opentracing ci

OT_RUNPATH=1 is responsible for using rpath (not sure why it is not enabled automatically)

https://github.com/haproxy/haproxy/blob/master/.github/matrix.py#L76-L79


I can try to get those options for debian packaging

**Comment by ssgelm** [comment]
I think you are misunderstanding my problem. First of all, the Makefile errors out before `OT_RUNPATH` is even accessed (L27 vs L35). Second, I believe i could work around this by setting `OT_INC` but I shouldn't need to because pkg-config is installed and working properly.

**Comment by chipitsine** [comment]
I understand what you are going to do. I suggested some fast fix))

**Comment by ssgelm** [comment]
Oh, got it! 😄 Thanks for the suggestion.

**Comment by chipitsine** [comment]
ok, I'll refactor OT_RUNPATH=1 as well ....

**Comment by ssgelm** [comment]
I'm pretty sure rpath doesn't need to be set here since the lib is in /usr/lib, no?

**Comment by wtarreau** [comment]
In fact these are the limits of external tools like pkgconfig. They provide *some* hints to help detect certain dependencies and usually it's considered that the output can be used as-is, but as you figured it's not always the case. The rpath is legitimate when the lib is in a non-standard directory and does indeed not make much sense for /usr/lib, but here again it should not be on the consumer program to have to decide on this but on pkgconfig itself. Since that's not done, better keep it as it doesn't break for those in /usr/lib, and remains necessary for other ones.

**Comment by chipitsine** [comment]
I mean "automatic" rpath if lib is specified explicitly. Currently we have to specify both.

You do not have for Debian, because you use standard lib path

**Comment by zaga00** [comment]
Hello all,

perhaps this can be solved by setting the env variable PKG_CONFIG_ALLOW_SYSTEM_CFLAGS when running pkg-config so that pkg-config does not throw system include from the CFLAGS settings.

`OT_CFLAGS = $(shell PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --silence-errors --cflags $(OTC_WRAPPER)$(OT_DEBUG_EXT))`

This system include should not get in the way, as it is unnecessary anyway.

Or, two checks are made, one with the env variable set and the other without and then the other is used for CFLAGS and the first to check.  :)

**Comment by ssgelm** [comment]
Thinking about this more: `pkg-config` should exit non-zero if the package isn't found. Maybe you could instead use that to determine its success rather than whether the variable is set?

**Comment by zaga00** [comment]
This is not a problem if pkg-config does not find the configuration, but it is a problem if it finds and does not set OT_CFLAGS.  Also, pkg-config is used only if OT_INC or OT_LIB has not been set before.  It’s a bit of an unfortunate solution, but so far it has worked.

**Comment by zaga00** [comment]
In this patch, a check has been added to see if there is an installed package, and if pkg-config finds it, the contents of the ot_cflags variable are irrelevant:

```
diff --git a/addons/ot/Makefile b/addons/ot/Makefile
index 9d9b1bfee..ef48ce49d 100644
--- a/addons/ot/Makefile
+++ b/addons/ot/Makefile
@@ -8,6 +8,7 @@ OT_DEFINE    =
 OT_CFLAGS    =
 OT_LDFLAGS   =
 OT_DEBUG_EXT =
+OT_PKGSTAT   =
 OTC_WRAPPER  = opentracing-c-wrapper
 
 ifneq ($(OT_DEBUG),)
@@ -16,6 +17,7 @@ OT_DEFINE    = -DDEBUG_OT
 endif
 
 ifeq ($(OT_INC),)
+OT_PKGSTAT = $(shell pkg-config --exists $(OTC_WRAPPER)$(OT_DEBUG_EXT); echo $$?)
 OT_CFLAGS = $(shell pkg-config --silence-errors --cflags $(OTC_WRAPPER)$(OT_DEBUG_EXT))
 else
 ifneq ($(wildcard $(OT_INC)/$(OTC_WRAPPER)/.*),)
@@ -23,9 +25,15 @@ OT_CFLAGS = -I$(OT_INC) $(if $(OT_DEBUG),-DOTC_DBG_MEM)
 endif
 endif
 
+ifeq ($(OT_PKGSTAT),)
 ifeq ($(OT_CFLAGS),)
 $(error OpenTracing C wrapper : can't find headers)
 endif
+else
+ifneq ($(OT_PKGSTAT),0)
+$(error OpenTracing C wrapper : can't find package)
+endif
+endif
 
 ifeq ($(OT_LIB),)
 OT_LDFLAGS = $(shell pkg-config --silence-errors --libs $(OTC_WRAPPER)$(OT_DEBUG_EXT))
```

**Comment by zaga00** [comment]
Hello @ssgelm,

does the patch posted here meet the requirements or does something need to change?

**Comment by ssgelm** [comment]
Oh, sorry, I missed the earlier post! I just tested and that fixes my issue.

**Comment by zaga00** [comment]
Can this issue be closed?

**Comment by ssgelm** [comment]
Yes!

**Comment by zaga00** [comment]
All right, I'm just asking.  I don't have the authority to close the issue at this repository, it has to be someone else to do it.  :)

**Comment by wtarreau** [comment]
OK closing now, thank you both!
