### ISSUE TITLE
segmentation fault when checking cfg file and reloading haproxy, in program script

### ISSUE THREAD

**Issue by bluebrown** [haproxy/haproxy#1324]
### Detailed Description of the Problem

Hi I have found a weird situation. I have managed to narrow things down.

### Dockerfile

```dockerfile
FROM haproxy:alpine

USER root
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-S", "/run/haproxy-master.sock"]

WORKDIR /usr/local/etc/haproxy/

COPY haproxy.cfg /usr/local/etc/haproxy/
COPY loop.sh  /usr/local/bin/
```

### haproxy.cfg

The haproxy.cfg is very simple and just defines a program, which is a script that runs a loop.

```ini
program loop
    command loop.sh

global
    log          fd@2 local2
```

### loop.sh

The loop script is the important part.

```shell
#!/bin/sh

set -ex

while :
do
    sleep 10
    # HAProxy is throwing segmetion fault on the second iteration.
    # When commmenting the config check out, it doesnt throw the error.
     haproxy -W -c -f haproxy.cfg
    break
done

kill -s SIGUSR2 1

return 0
```

### Output

```c
[NOTICE]   (1) : New program 'loop' (8) forked
[NOTICE]   (1) : New worker #1 (9) forked
+ :
+ sleep 10
+ haproxy -W -c -f haproxy.cfg
Configuration file is valid
+ break
+ kill -s SIGUSR2 1
+ return 0
[WARNING]  (1) : Reexecuting Master process
[WARNING]  (9) : Stopping frontend GLOBAL in 0 ms.
[NOTICE]   (1) : New program 'loop' (15) forked
[NOTICE]   (1) : New worker #1 (16) forked
[WARNING]  (1) : Former program 'loop' (8) exited with code 0 (Exit)
+ :
+ sleep 10
[WARNING]  (1) : Former worker #1 (9) exited with code 0 (Exit)
+ haproxy -W -c -f haproxy.cfg
Configuration file is valid
[WARNING]  (19) : Reexecuting Master process in waitpid mode
Segmentation fault (core dumped)
[NOTICE]   (1) : haproxy version is 2.4.2-553dee3
[ALERT]    (1) : Current program 'loop' (15) exited with code 139 (Segmentation fault)
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[ALERT]    (1) : Current worker #1 (16) exited with code 143 (Terminated)
[WARNING]  (1) : All workers exited. Exiting... (139)
```

#### First Iteration

```c
PID   USER     TIME  COMMAND
    1 root      0:00 haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg -S /run/haproxy-master.sock
    8 root      0:00 {loop.sh} /bin/sh /usr/local/bin/loop.sh
    9 root      0:00 haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg -S /run/haproxy-master.sock
   10 root      0:00 sleep 1
````

#### Second Iteration(before crash)

```c
PID   USER     TIME  COMMAND
    1 root      0:00 haproxy -sf 8 9 -W -db -f /usr/local/etc/haproxy/haproxy.cfg -S /run/haproxy-master.sock
   22 root      0:00 {loop.sh} /bin/sh /usr/local/bin/loop.sh
   23 root      0:00 haproxy -sf 8 9 -W -db -f /usr/local/etc/haproxy/haproxy.cfg -S /run/haproxy-master.sock
   24 root      0:00 sleep 10
   26 root      0:00 ps
```

### Expected Behavior

I expect to be able to reload the worker without error.

### Steps to Reproduce the Behavior

Create the docker image and run it as described above.

### Do you have any idea what may have caused this?

I dont know why but it is strictly related to the config check. If I remove the following like it doesnt throw the error.

```
haproxy -W -c -f haproxy.cfg
```

### What is your configuration?

```haproxy
program loop
    command loop.sh

global
    log          fd@2 local2
```

### Output of `haproxy -vv`

```plain
$ docker run haproxy:alpine -vv
HAProxy version 2.4.2-553dee3 2021/07/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.2.html
Running on: Linux 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.3.1 20210424

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment]
I must confess I'm having a hard time understanding what is being tested here. I'm seeing an haproxy config that executes a program which itself executes haproxy. It seems to me that if you run this without "-c", it will simply start an infinite number of processes. I'm not sure what I'm missing here.

Sure it's not clean to see a segfault but given that it complains in the forked process, I'm wondering if it's not even the started sub-process that fails on out of memory. 

What did you initially try to do ?

**Comment by bluebrown** [comment]
Hi,

this is supposed to do a "hitless reload" on the workers in order to pick up changes in the config file, if its valid.

Based on the comment in the official [docker-entrypoint.sh](https://github.com/docker-library/haproxy/blob/master/2.5-rc/docker-entrypoint.sh) I am sending `SIGUSR2`  to HAProxy in master worker mode.

>   -W  -- "master-worker mode" (similar to the old "haproxy-systemd-wrapper"; allows for reload via "SIGUSR2")

I have a project where I want to update the config and reload HAProxy dynamically. https://github.com/bluebrown/swarm-haproxy-ingress. 

The current [entrypoint](https://github.com/bluebrown/swarm-haproxy-ingress/blob/main/loadbalancer/entrypoint.sh) works OK, but is causing issues when trying to terminate the container completely. 

<details>
 <summary>Scrape Function</summary>

```shell
fetch_config()
{
    # fetch config
    if ! curl -s -f "$1" > new.cfg;
    then
        return 1
    fi
    # compare checksums
    if [ "$(md5sum haproxy.cfg | cut -d ' ' -f 1)" = "$(md5sum new.cfg | cut -d ' ' -f 1)" ]
    then 
        return 2
    fi
    # validate
    if ! haproxy -c -f new.cfg;
    then
        return 3
    fi
    # use valid file once all checks are passed
    cp new.cfg haproxy.cfg
    return 0
}

scrape_config()
{
    while :
    do
        # sleep until next iteration
        sleep "$2"
        if fetch_config "$1";
        then
           # reload worker
            kill -s SIGUSR2 1
        fi
    done
}
```

</details>

So my idea is to move the scrape function from this entrypoint to a HAProxy program. Once I did this, I noticed the SEG fault and narrowed it down to the point where I can see it's throwing the error when having a config check there, while its not throwing the error if I only  reload the workers.

**Comment by wtarreau** [comment]
OK so in fact the program doesn't start haproxy, it just sends it the signal.

Hmmm just thinking, the master process does set a number of environment variables for its next instantiation. It's possible that these are exported and are visible to the "haproxy -W -c" that you're calling.

Could you please try to add `env | grep HAPROXY >>/tmp/log` to your script to see if such variables are visible, and in this case unset them ? If it solves the issue, then we'll know what needs to be addressed inside haproxy (i.e. unset such variables in workers and programs).

**Comment by wtarreau** [comment]
I could reproduce it now and it's the `HAPROXY_MASTER_REEXEC` variable that causes this. You can work around the problem for now by unsetting it in your script.

Or even better, just add this to your global section:
```
global
     unsetenv HAPROXY_MWORKER_REEXEC
```

It fixes it for me. That's ugly but now at least we know what to look for.

Thanks for your report!

**Comment by wtarreau** [comment]
Now fixed in mainline, it will flow down to older versions soon.

**Comment by bluebrown** [comment]
WOW, your a beast.

**Comment by wtarreau** [comment]
Please don't close, we're keeping it open to track the required backports. It will automatically be closed once all branches are fixed.

**Comment by wlallemand** [comment]
@bluebrown thanks for your report. I understand what you are trying to do but in my opinion this is not the job of HAProxy and it's really hackish, you should consider using a init system in your container instead.
