### ISSUE TITLE
Connection is not properly closed

### ISSUE THREAD

**Issue by geniqtech** [haproxy/haproxy#1325]
### Detailed Description of the Problem

We are using HAProxy as a TCP proxy between a SMPP client and a SMPP server. SMPP protocol is TCP socket based and requires a persistent connection between the client and server.

HAProxy is configured as SSL Passthrough mode. Whenever the backend is down, the SMPP client is able to detect this and tries to trigger a reconnection. However the reconnection seems to be  "stucked" and will not timeout. Restarting the SMPP client application does not help too.

This issue only happens on RHEL 7.X and does not occur on RHEL 8.X

Interestingly if we remove the option "check inter 5s" in the configuration, the SMPP reconnection will work.

### Expected Behavior

Whenever the backend server is down, the frontend connection should not be "stucked" so that the SMPP client is able to attempt reconnection indefinitely.

### Steps to Reproduce the Behavior

1. Setup a SMPP client to connect through HAProxy via TCP mode with SSL passthrough to a SMPP server
2. Stop the SMPP server
3. Both HAProxy and SMPP client is able to detect the disconnection but SMPP client reconnection will be "stucked"

### Do you have any idea what may have caused this?

Not very sure what could be the reason but on RHEL 7.x, we already tried to update all software components to the latest version and the issue is still happening. It is strange that the exact setup works on RHEL 8.x.

Also removing "check inter 5s" from the backend configuration will work too.

### What is your configuration?

```haproxy
# IP addresses have been masked

global
   log 127.0.0.1 local0 notice
   chroot /var/lib/haproxy
   user haproxy
   group haproxy
   daemon

defaults
   log global
   mode tcp
   option tcplog
   option dontlognull
   retries 3   
   timeout connect 3000
   timeout client 50000
   timeout server 50000

frontend front.aggregator.a
    bind 1.1.1.1:4000
    default_backend back.aggregator.a

backend back.aggregator.a
     server aggregator.a 2.2.2.2:2776 check inter 5s
```

### Output of `haproxy -vv`

```plain
haproxy -vv
HAProxy version 2.4.1-1ce7d49 2021/06/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.1.html
Running on: Linux 3.10.0-1160.31.1.el7.x86_64 #1 SMP Wed May 26 20:18:08 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace

uname -a
Linux ip-172-31-27-52.ap-southeast-1.compute.internal 3.10.0-1160.31.1.el7.x86_64 #1 SMP Wed May 26 20:18:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wtarreau** [comment]
Hi,

Not exactly sure what you mean by *'HAProxy and SMPP client is able to detect the disconnection but SMPP client reconnection will be "stucked"'*. Do you mean that haproxy receives the disconnection, forwards it to the client which also disconnects, then tries to reconnect and fails to ?

If so, I'm wondering, given that you have checks enabled, and depending how fast the client reconnects, it's possible that it connects to haproxy with no available servers, that haproxy immediately closes, and that the client doesn't deal well with this situation.

I must say the exact sequence you're observing is not entirely clear. Would it be possible to share some of your logs ? The timings and termination flags there are useful. Feel free to replace your addresses or server names with "XXX" if you want.

**Comment by geniqtech** [comment]
Hi,

Thanks for your response.

Please refer below for the application logs:


Without "check inter 5s" in haproxy configuration
================================
2021-07-17 19:22:20,523 [SmppAdapter] WARN  - fireUnknownThrowable(): Unknown throwable received, but it was a ClosedChannelException, executing reconnect...
2021-07-17 19:22:20,523 [DefaultSmppSession] DEBUG - Caller waiting on request [1], cancelling it with a channel closed exception
2021-07-17 19:22:20,523 [DefaultSmppSession] DEBUG - Unbind/close was requested, ignoring channelClosed event
...
2021-07-17 19:22:28,544 [SmppAdapter] WARN  - fireUnknownThrowable(): Unknown throwable received, but it was a ClosedChannelException, executing reconnect...
2021-07-17 19:22:28,544 [DefaultSmppSession] DEBUG - Caller waiting on request [1], cancelling it with a channel closed exception
2021-07-17 19:22:28,544 [DefaultSmppSession] DEBUG - Unbind/close was requested, ignoring channelClosed event
...
2021-07-17 19:22:36,565 [SmppAdapter] WARN  - fireUnknownThrowable(): Unknown throwable received, but it was a ClosedChannelException, executing reconnect...
2021-07-17 19:22:36,565 [DefaultSmppSession] DEBUG - Caller waiting on request [1], cancelling it with a channel closed exception
2021-07-17 19:22:36,565 [DefaultSmppSession] DEBUG - Unbind/close was requested, ignoring channelClosed event

Remarks: The application was able to keep retrying to reconnect


With "check inter 5s" in haproxy configuration
==============================
2021-07-17 19:27:42,494 [SmppAdapter] WARN  - fireUnknownThrowable(): Unknown throwable received, but it was a ClosedChannelException, executing reconnect...

The logs will just stop at the line above

**Comment by wtarreau** [comment]
Sorry, I meant the haproxy logs, as I won't have much use of the application logs.

**Comment by capflam** [comment]
@geniqtech  Any news on this issue ?

**Comment by capflam** [comment]
I'm closing this issue now. Feel free to reopen it if necessary.
