### ISSUE TITLE
Two potential errors due to the unreleased lock &init_mutex before program exit

### ISSUE THREAD

**Issue by jenny-cheung** [haproxy/haproxy#1326]
Dear developers:
First, thank you for your checking! The lock pthread_mutex_lock(&init_mutex); is not released if the relevant branch conditions satisfy.  The fix is to insert` pthread_mutex_unlock(&init_mutex);` before `exit(1)`.

https://github.com/haproxy/haproxy/blob/6a510907807b7fb901654b4f5e5100aa91868fb7/src/haproxy.c#L2716

```
static void *run_thread_poll_loop(void *data)
{
	...;
	
#ifdef USE_THREAD
	pthread_mutex_lock(&init_mutex);
#endif
	/* The first thread must set the number of threads left */
	if (!init_left)
		init_left = global.nbthread;
	init_left--;

	tv_init_thread_date();

	list_for_each_entry(ptaf, &per_thread_alloc_list, list) {
		if (!ptaf->fct()) {
			ha_alert("failed to allocate resources for thread %u.\n", tid);
			exit(1); // exit with unreleased lock
		}
	}

	list_for_each_entry(ptif, &per_thread_init_list, list) {
		if (!ptif->fct()) {
			ha_alert("failed to initialize thread %u.\n", tid);
			exit(1); // exit with unreleased lock
		}
	}

	if (init_left == 0)
		protocol_enable_all();

#ifdef USE_THREAD
	pthread_cond_broadcast(&init_cond);
	pthread_mutex_unlock(&init_mutex);

	...;
}
```

Best,

**Comment by wtarreau** [comment]
This is true indeed, however this is totally harmless, since exit() will cause the whole process to exit, not just the current thread to terminate, thus all other threads will die. I do think that at the very least a comment is deserved here to mention "let's kill the whole process" before the exit() so as to clarify the intent.

Feel free to propose a patch for this (and I'm fine with adding an unlock if you prefer to make the code clearer or better pass through various static code analysers).

Thank you!

**Comment by jenny-cheung** [comment]
Thank you for your detailed reply. I will send a pull request for this issue soon.

**Comment by wtarreau** [comment]
Please don"t forget to read CONTRIBUTING before making your patch. I'm suggesting this because usually when people start to speak about pull requests, they do it "the github way" (i.e. the most atrocious way ever invented :-)). Thanks!

**Comment by wtarreau** [comment]
Not sure you saw my message, the patch is exactly what I feared, with broken indent and no commit message :-(

**Comment by jenny-cheung** [comment]
@wtarreau Sorry for that. I will resend a new pull request soon.

**Comment by wtarreau** [comment]
Closing since now merged. Thank you!

**Comment by jenny-cheung** [comment]
Thank you!
