### ISSUE TITLE
allow negation of ciphers in specfic ssl listen ports (via bind ... ciphers ...) 

### ISSUE THREAD

**Issue by devZer0** [haproxy/haproxy#1339]
### Your Feature Request

Apparently, in bind ciphers param i can set ciphers, but negation does not work like in ssl-default-bind-ciphers, 

### What are you trying to do?

if i do default hardening via  

ssl-default-bind-ciphers ALL:!aNULL:!RC4:!IDEA:!SEED:!3DES

and then try to add specific ciphers to be denied for listen port 1111 like this:

bind :1111 ssl crt /etc/ssl/private/cert.pem no-tlsv10 no-tlsv11 ciphers !AES128-SHA

i'm getting

Jul 30 13:58:15 rproxy haproxy[1650]: [ALERT]    (1650) : Proxy 'fe-https-chat': unable to set SSL cipher list to '!AES128-SHA' for bind ':1111' at [/etc/haproxy/haproxy.cfg:122].
Jul 30 13:58:15 rproxy haproxy[1650]: Proxy 'fe-https-chat': unable to set SSL cipher list to '!AES128-SHA' for bind ':1111' at [/etc/haproxy/haproxy.cfg:122].
Jul 30 13:58:15 rproxy haproxy[1650]: [ALERT]    (1650) : Fatal errors found in configuration.
Jul 30 13:58:15 rproxy systemd[1]: haproxy.service: Control process exited, code=exited, status=1/FAILURE

whereas the non-denied variant is working.

I would expect that i can use cipher list at "ciphers" param the same as with ssl-default-bind-ciphers param

### Output of `haproxy -vv`

```plain
haproxy -vv
HAProxy version 2.4.2-1~bpo10+1 2021/07/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.2.html
Running on: Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.4.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by jmagnin** [comment]
Hello,

when you use `ssl-default-bind-ciphers` in global and set `ciphers` on a bind line, you effectively tell haproxy not to care about the global setting and use the ciphers string you set for that bind line. Perhaps the documentation should make this clearer, but with most things you set in `default` or `global`, when you redefine them in a proxy you override the default value.

Setting a ciphers string with only a negated cipher does not make sense, and that's why you get the error. It's the same as if you used `openssl ciphers '!AES128-SHA'`, you'd get an error as it does not make sense. You have to set some ciphers you want before you negate others, just like in your `ssl-default-bind-ciphers` statement.

if this were to be a feature, we would need an additional keyword, as a lot of users expect `ciphers` to behave as it does today.

**Comment by devZer0** [comment]
ahh, thank you for explanation, that wasn't clear to me. sorry for the noise
