### ISSUE TITLE
SPOP: Errors with lots of concurrent requests

### ISSUE THREAD

**Issue by cortex93** [haproxy/haproxy#1340]
### Detailed Description of the Problem

I'm doing some benchmarking and encounter lots of error when increasing workload.

I have test with and without pipelining. Without, there is less issues.
From what I can see with a SPOA server trace is that HAProxy Disconnect with code-status = 0 and message = normal without reading the agent ack frame the server sent in reply to notify on the same the connection. Some times, it send a disconnect right after receiving the agent hello (haproxy hello is not a healthcheck).
In haproxy logs, the message has st=256.
It happens a lot when concurrent request is higher than maxconn

If testing one request at a time, it seems applets are created up to nbthread (regardless maxconn) and then get reused. When stressing, a lot of applets are created and the number of idle applets is zero.

```
SPOE: [my-agent] <EVENT:on-frontend-http-request> sid=2091 st=256 0/31/10/-1/41 0/337 21/1 486/1590
SPOE: [my-agent] <EVENT:on-frontend-http-request> sid=2113 st=256 0/23/10/-1/34 0/337 21/1 487/1591
```

### Expected Behavior

HAProxy SPOE should handle heavy load and no error should occured.
When using SPOE for traffic filtering, it is very easy to create a denial of service.

### Steps to Reproduce the Behavior

1. Use the spoa-mirror example at https://github.com/haproxytech/spoa-mirror
2. Run it with or without pipelining enabled.
3. Use the given config
4. `ab -c 100 -n 1000 http://localhost:80/

### Do you have any idea what may have caused this?

Maybe related to https://github.com/haproxy/haproxy/issues/705

### Do you have an idea how to solve the issue?

no

### What is your configuration?

```haproxy
global
  log stdout format raw local1 debug debug
  nbthread 64
  maxconn 5000

defaults
  log global
  mode http
  option httplog
  option dontlognull
  option http-buffer-request
  timeout connect 5000
  timeout client  50000
  timeout server  50000

frontend web
   bind :80
   filter spoe engine my-spoa config /usr/local/etc//haproxy/spoa.conf
   http-request set-header "ip_score" %[var(sess.myspoe.ip_score)]
   default_backend servers

backend servers
   balance roundrobin
   server web1 web:8080 check

backend be_agents
   mode tcp
   balance roundrobin
   timeout connect 15s # greater than hello timeout
   timeout server  35s # greater than idle timeout
   option spop-check
   server agent1 agent:12345 maxconn 20 #check inter 3s
```

```
[my-spoa]
spoe-agent my-agent
   messages           my-message-name
   option var-prefix  myspoe
   option send-frag-payload
   log                global
   use-backend        be_agents
   timeout hello      10s
   timeout idle       30s
   timeout processing 30s

spoe-message my-message-name
   args ip=src anotherarg=str(abc) body=req.body
   event on-frontend-http-request if { path / }
```
```


### Output of `haproxy -vv`

```plain
HAProxy version 2.4.2-553dee3 2021/07/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.2.html
Running on: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace

Linux 07e2d96e134e 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux
```

**Comment by capflam** [comment]
You're right, the patch provided to fix #705 contains a bug. I'm working an a fix. Thanks !

**Comment by capflam** [comment]
Here are 3 patches that should fix this issue. You can apply them on top of the 2.4.2 or 2.4-HEAD. It could be good to confirm it fixes the issue on your side. I'm unable to reproduce it with these patches but a confirmation is never useless :)

[0001-MINOR-spoe-Add-a-pointer-on-the-filter-config-in-the.patch.txt](https://github.com/haproxy/haproxy/files/6921537/0001-MINOR-spoe-Add-a-pointer-on-the-filter-config-in-the.patch.txt)
[0002-BUG-MEDIUM-spoe-Create-a-SPOE-applet-if-necessary-wh.patch.txt](https://github.com/haproxy/haproxy/files/6921540/0002-BUG-MEDIUM-spoe-Create-a-SPOE-applet-if-necessary-wh.patch.txt)
[0003-BUG-MEDIUM-spoe-Fix-policy-to-close-applets-when-SPO.patch.txt](https://github.com/haproxy/haproxy/files/6921542/0003-BUG-MEDIUM-spoe-Fix-policy-to-close-applets-when-SPO.patch.txt)

**Comment by cortex93** [comment]
I'm not sure which branch or tag to checkout. None is named 2.4.2 or 2.4-HEAD ?

**Comment by jmagnin** [comment]
@cortex93 haproxy-2.4 git repo is available at http://git.haproxy.org/git/haproxy-2.4.git/ 
github.com/haproxy/haproxy only has the development branch.

**Comment by cortex93** [comment]
Seems good for me. No errors so far. Thanks for the quick fix.

**Comment by capflam** [comment]
Thanks, I will push the fix and backport it.
