### ISSUE TITLE
Haproxy 2.4.2 csv export show empty data after reload

### ISSUE THREAD

**Issue by prescolt** [haproxy/haproxy#1345]
### Detailed Description of the Problem

After i add new listen block configuration and reload haproxy service 
some listen frontend can not show data in csv export, with blank pages. 
example empty parameter with no csv data :  /haproxy_stats;csv;norefresh and haproxy_stats;csv;norefresh?scope=vocongt1
![image](https://user-images.githubusercontent.com/27767144/129033269-eeac47ed-b398-4444-a209-1cdeee00e0f5.png)
stat and json pages is okay
![image](https://user-images.githubusercontent.com/27767144/129033487-c2fdbd29-8ea0-4440-b373-cc6d2f3f3ba1.png)
![image](https://user-images.githubusercontent.com/27767144/129033572-66a36e4c-66dc-4f59-9b89-009c21cfc8a0.png)

### Expected Behavior

Csv data must show same as json after reload haproxy as other version.

### Steps to Reproduce the Behavior

1 : Add new listen configuration
2 : reload haproxy
3 : view csv export

### Do you have any idea what may have caused this?

I check log and no error. I do know what cause this issue
Updated
After half day. I have been recheck csv export, and it work correcly. So I think this function may be routing to old thread (wating for terminate ) or old thread have been wating for expire session.

### Do you have an idea how to solve the issue?
I think this function should be routing to new active thread after reload.
_No response_

### What is your configuration?

```haproxy
global
        master-worker
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 666 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
        hard-stop-after 4d
        #nbproc          2
        cpu-map 1/all 0-7
        maxconn           80000
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        ssl-default-bind-options no-sslv3
        server-state-base /etc/haproxy/states
        server-state-file server_states
        #debug

defaults
        log     global
        option tcpka
        option tcplog
        option  dontlognull
        timeout connect 5s
        timeout client  50s
        timeout server  5s
        #log-format "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq"
        log-format "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc"
        #https://cdn.haproxy.com/wp-content/uploads/2019/02/image4.png
        load-server-state-from-file global
      


listen stats # Define a listen section called "stats"
  bind :xxxx# Listen on localhost:xxxx
  mode http
  stats enable  # Enable stats page
  stats hide-version  # Hide HAProxy version
  stats realm Haproxy\ Statistics  # Title text for popup window
  stats uri /haproxy_stats  # Stats URI
  #http-request use-service prometheus-exporter if { path /metrics }
  stats refresh 10s

#########################################

##############################################
        listen vocongt1-xxx.xxx.xxx-5622
        bind xxx.xxx.xxxx:5622 tfo
        mode tcp
        log global
        retries 2
        timeout connect 5s
        option redispatch
        timeout client 100000
        timeout server 100000
        option tcplog
        balance leastconn
        maxconn 4000
        rate-limit sessions 150
        timeout queue 10s
        ### comment no config:        table used to store behaviour of source IPs
        stick-table type ip size 999k expire 300s store gpc0,conn_rate(10s),conn_cur
        tcp-request connection track-sc1 src
        ### comment no config: IPs that have gpc0 > 0 are blocked until the go away for at least 5 minutes
        ### comment no config: refuses a new connection from an abuser
        acl source_is_abuser src_get_gpc0 gt 0
        ### comment no config: connection rate abuses get blocked
        acl conn_rate_abuse  sc1_conn_rate gt 10
        acl mark_as_abuser   sc1_inc_gpc0  gt 0
        ### comment no config: tcp connection delay
        tcp-request inspect-delay 3s
        tcp-request connection reject if  source_is_abuser
        tcp-request connection reject if { src_conn_cur ge 10 }
        tcp-request connection reject if   conn_rate_abuse mark_as_abuser
        #tcp-request content accept if WAIT_END
        timeout check 5s
        server xx.xxx.xx xx.xxx.xxx:5622 check port 5622 inter 10s maxconn 999
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.2-553dee3 2021/07/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.2.html
Running on: Linux 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = cc
  CFLAGS  = -O2 -march=native -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=20).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by prescolt** [comment]
Additional Infomation
Ubuntu 18.04
Kernel 5.4

**Comment by prescolt** [comment]
Hi
After half day. I have been recheck csv export, and it work correcly. So I think this function may be routing to old thread (wating for terminate ) or old thread have been wating for expire session.

**Comment by wtarreau** [comment]
Yes I think so as well. As you're changing the URL in the URL bar, the browser might be using a different connection and doesn't get to the right place. In 2.5-dev we've had some improvements so that the old stats can continue to be delivered while stopping (this will make the problem less visible but you'll get the old process' stats instead of nothing).

**Comment by keivanshahin** [comment]
We have the same problem, as we use active/passive, the passive aka slave wont get csv status until we switch from master since it does not get any traffic when being passive, which is kinda annoying as we use opsview to monitor backends on the servers with help of csv, so for now we have added a "test" frontend which we connect to each time we reload the configuration on the slave.

I also notice its also due to how many backends you have, if i remove 2 from my config, doesn't matter where it keeps on working but if i have all my backends server in the config i have to do a connection to generate data to haproxy.

**Comment by wtarreau** [comment]
I'm sorry, but I don't understand the issue(s) you're describing. You seem to be mixing two problems, one related to switching an address between a master and a slave devices, which I suspect is performed via a virtual address being migrated between machines, and that an updated request from the browser is sent over a TCP connection that's blocked by the machine's firewall rules, preventing it from responding, and a second issue where something not clear happens in your stats page depending on the number of backends in your conf. Note that even the one you use to consult the stats page does make data move, so you'll need to precise your trouble here I think.

**Comment by prescolt** [comment]
> Yes I think so as well. As you're changing the URL in the URL bar, the browser might be using a different connection and doesn't get to the right place. In 2.5-dev we've had some improvements so that the old stats can continue to be delivered while stopping (this will make the problem less visible but you'll get the old process' stats instead of nothing).

HI
After rollback to version 2.2. Problem have been resolved. The new stat of new process alway  return instead empty data.

**Comment by capflam** [comment]
What is the status of this issue ?

**Comment by wtarreau** [comment]
I have no idea, I think the problem description remained confusing. In addition, in 2.5 there were improvements so that the stats of stopped proxies remain displayed during reloads. This might or might not resolve the issue here if it was in relation to this. It's worth testing, at least to clarify the issue.

**Comment by prescolt** [comment]
Hi, i am testing on 2.4.8 and i will feedback soon. I need proxy running on high load and  reload haproxy for re-simulate this case.
Thank
