### ISSUE TITLE
2.5: Default User-Agent of HTTP Client not valid according to RFC 7231#5.5.3

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1354]
### Detailed Description of the Problem

The user agent (`HAProxy HTTP client`) of the HTTP client does not follow the grammar defined in [RFC 7231#5.5.3](https://httpwg.org/specs/rfc7231.html#header.user-agent).

### Expected Behavior

The user agent should be valid according to the RFC.

### Steps to Reproduce the Behavior

Look at the source code: https://httpwg.org/specs/rfc7231.html#header.user-agent

### Do you have an idea how to solve the issue?

The user agent should simply read `HAProxy`, without any spaces. Possibly `HAProxy/x.y` with `x.y` being the branch.

### What is your configuration?

```haproxy
n/a
```

### Output of `haproxy -vv`

```plain
n/a
```

**Comment by wlallemand** [comment]
Thanks for the report. Just to be clear about this feature, it will probably still evolve a lot so I'm still open to suggestions, there are already some parts that I'm fixing. The CLI client itself will probably be only accessible in expert mode, if not disabled by default at compilation time. It's currently just a small demo of the API.

I'll change the name as suggested.
