### ISSUE TITLE
Infinity loop while logging after reload.

### ISSUE THREAD

**Issue by tekuchev** [haproxy/haproxy#1356]
### Detailed Description of the Problem

Sometimes, after reload, the process which must be stopped, is starting to send a huge count of syslog messages  with internal error in session state at disconnect:

```
Aug 20 00:46:09: 61.19.35.42:60965 [20/Aug/2021:00:45:44.612] f_name -/- 0/0/-1/-1/-1/-1/-1/-1/24779 400 0 - - CR-- 1245/38/0/0/0 0/0 - - <BADREQ> <BADREQ> "<BADREQ>" "<BADREQ>"  
Aug 20 00:46:09: 61.19.35.42:60965 [20/Aug/2021:00:45:44.612] f_name -/- 0/0/-1/-1/-1/-1/-1/-1/24779 500 0 - - IR-- 1245/38/0/0/0 0/0 - - <BADREQ> <BADREQ> "<BADREQ>" "<BADREQ>"  
```

The first request seems like usual tcp flood, nothing interesting except large time total.
The second record repeats infinity times.

The process, which send this messages, use 100% of one CPU core, send about 200 kpps UDP Syslog messages described above and use about 400 Mbit/sec network.

At the same time the new haproxy process normally works.
Sometime, after further reload, may start new bogus process, which will send the same count of messages.
To stop this, we make full stop/start haproxy.

### Expected Behavior

Haproxy mustn't send unwanted log records.

### Steps to Reproduce the Behavior

I don't know :-(
The problem occurs once per day or two days while reload haproxy. 
Usually we automatically reload haproxy 2-3 times per hour.

### What is your configuration?

```haproxy
global
        
        log log1.example.com local6
        tune.ssl.default-dh-param 2048
        tune.bufsize 65536
        ssl-default-bind-options ssl-min-ver TLSv1.2
        ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
        
        daemon
        cpu-map 1/all 0-64
        stats socket 10.0.200.163:1200
        maxconn 40000
        ulimit-n 200000 
        pidfile /var/run/haproxy.pid
        h1-case-adjust location Location

defaults
        log-format %ci:%cp\ [%t]\ %ft\ %si/%sp\ %Th/%Ti/%Tq/%TR/%Tw/%Tc/%Tr/%Td/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %sslv\ %sslc\ %HV\ %HM\ %{+Q}HP\ %{+Q}HQ
        log global
        timeout connect 4000
        timeout client-fin 9000
        timeout http-keep-alive 200
        timeout client 120000
        timeout server 240000
        errorfile 503 /etc/haproxy/503.html
        option h1-case-adjust-bogus-client

resolvers hts_dns
     nameserver dns1 192.168.0.1:53
     nameserver dns2 192.168.0.2:53

# We use about 100 frontends with same config:

frontend f_name
        mode http
        bind 192.168.10.10:80 transparent
        bind 192.168.10.10:443 transparent alpn h2,http/1.1,http/1.0 ssl crt-list lists/fe_name_certs.list
        http-request replace-value Host (.*):.* \1
        http-request set-var(req.backend) hdr(host),lower,map(lists/fe_name_domains.map,error_503)
        acl no_domain_in_map var(req.backend) error_503
        http-request set-var(req.backend) hdr(host),lower,map_reg(lists/fe_name_wcard_domains.map,error_503) if no_domain_in_map
        http-request add-header X-BACKEND %[var(req.backend)]
        http-request set-header X-FULLURL %[req.hdr(host),lower]%[url]
        capture request header Host len 256
        capture response header X-Powered-By len 20        
        acl blocked_url req.fhdr(X-FULLURL) -m reg -f lists/blocked_urls.list
        acl bad_host var(req.backend) error_503
        acl https_domain hdr(host) -i -f lists/fe_name_https_domains.list
        acl https_wildcard hdr_reg(host) -i -f lists/fe_name_https_wcard_domains.list
        acl cert_verification path_beg /.well-known/acme-challenge/
        acl static_content url_reg ^/.*\.[a-zA-Z0-9]{1,5}$
        acl dynamic_content path_end .php
        acl cache_available nbsrv(b_cache) ge 1
        acl method_post method POST
        use_backend b_blocked_url if blocked_url
        use_backend b_error_503 if bad_host
        use_backend b_http_redirect if { ssl_fc } !https_domain !https_wildcard
        use_backend b_certmanager if cert_verification
        use_backend b_cache if cache_available static_content !dynamic_content !method_post
        use_backend b_%[var(req.backend)]
```

### Output of `haproxy -vv`

```plain
# haproxy -vv
HAProxy version 2.4.3-4dd5a5a 2021/08/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.3.html
Running on: Linux 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_SLZ=1 USE_TFO=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

# uname -a
Linux example.com 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
```


### Last Outputs and Backtraces

_No response_

### Additional Information

_No response_

**Comment by wtarreau** [comment]
I'm wondering if this could be in anyway related to the transparent mode. For example, can you confirm that none of the configured servers will have an IP:port that matches the frontend's address ? This could create a connect loop for example. It's unclear to me where such an internal error may be produced though, it looks totally crazy.

Is this something that started to happen recently after an upgrade ?

**Comment by tekuchev** [comment]
> For example, can you confirm that none of the configured servers will have an IP:port that matches the frontend's address ?

We use about 40 pairs IP:80 on frontend proxied to the same ip using iptables rules. But exactly this frontend IP use different backend IP.

> Is this something that started to happen recently after an upgrade ?

Yes, I try to upgrade haproxy from 2.0 to 2.4.3.

So, I try to downgrade from 2.4.3 to 2.2.15. Valid configuration for 2.4.3 was failed for 2.2.15 on this `cpu-map` directive:
~~~
cpu-map 1/all 0-64
~~~

I changed directive according documentation to:
~~~
cpu-map 1/all 0-63
~~~

With this config, haproxy-2.2.15 works normally. 
Now I try this config on 2.4.3: haproxy runs about 30 hours without the issue, so this is may be a root of the problem.
There is some other differences in configuration which valid for 2.4.3, but not valid for 2.2.15, but they related to `http-check` backend options, so I think they doesn't concern with the issue.
 
I'll wait  for some days and talk about results.

**Comment by wtarreau** [comment]
OK thank you. There's nothing that could explain this abnormal behavior for now.

**Comment by tekuchev** [comment]
The problem was repeated again on haporxy-2.4.3 after 3 days of working without problems.
This is a packets-per-second image of the problem:
<img width="600" alt="Screenshot 2021-08-30 at 11 12 40" src="https://user-images.githubusercontent.com/32452428/131313435-30eee858-3929-4b84-9134-a159957b9113.png">

Now  I remove `cpu-map` directive.

**Comment by wtarreau** [comment]
How should this graph be read ? There's no scale. Why are only two curves going through the roof and not the other ones ? In addition, can you confirm that what you're graphing are your syslog messages and not the production traffic ?

**Comment by tekuchev** [comment]
> How should this graph be read ?

Before 11:10 we have our usual production payload which is about 20k pps. 
At 11:10 something happens and haproxy start to send about 200 k pps of syslog messages as described above. 
Haproxy was reloaded by schedule at 10:48. There was more then 50 reloads  since full restart.
The haproxy was stopped and started at 22:40. There is no other problems with services in this period (except our log process system, which was not very happy :-) )

> Why are only two curves going through the roof and not the other ones ?

We have several vlan interfaces on physical network card. Curves, which  goes to the roof:
- vlan to our backend servers, which include log server (Yellow line)
- total out traffic on the interface (Blue line)

Incoming traffic from Internet (red line) is not changed significantly.
Green curve is a total incoming on the interface - also nothing stranges.

In attach -  strace dump of the bogus haproxy process while it send syslog messages.
[process_strace.gz](https://github.com/haproxy/haproxy/files/7076518/process_strace.gz)

**Comment by capflam** [comment]
I need more time to investigate but I managed to reproduce this kind of loop with the H1 mux. I will try to understand what really happens, but I'm on it.

**Comment by capflam** [comment]
I pushed a fix that should solve this bug. It will be backported soon.
