### ISSUE TITLE
haproxy=2.4.3: Websockets do not work on http/2 capable backends

### ISSUE THREAD

**Issue by DCkQ6** [haproxy/haproxy#1364]
### Detailed Description of the Problem

When haproxy backend is configured with [alpn](http://cbonte.github.io/haproxy-dconv/2.4/configuration.html#5.2-alpn):
```
  server apache backend:443 check ssl verify none alpn h2,http/1.1
```
**and** pointed server is capable to use http/2 connection
**and** one of available path on pointed server use websocket protocol.

Than mentioned websocket path do not work. I was able only to find relevant log on pointed server - apache 2.4 - named `backend_1`:
```
haproxy_1     | <134>Aug 24 23:34:44 haproxy[10]: Connect from 172.20.0.1:41582 to 172.20.0.4:8443 (_front_fails/HTTP)
backend_1     | [Tue Aug 24 23:34:44.829050 2021] [http2:debug] [pid 10:tid 140018503931648] h2_stream.c(543): [client 172.20.0.4:44400] AH03082: h2_stream(67-3,IDLE): created
backend_1     | [Tue Aug 24 23:34:44.829067 2021] [http2:debug] [pid 10:tid 140018503931648] h2_session.c(1700): [client 172.20.0.4:44400] AH03078: h2_session(67,BUSY,1): transit [IDLE] -- stream change --> [BUSY]
backend_1     | [Tue Aug 24 23:34:44.829082 2021] [http2:debug] [pid 10:tid 140018503931648] h2_session.c(221): [client 172.20.0.4:44400] AH03063: h2_session(67,BUSY,1): recv invalid FRAME[HEADERS[length=814, hend=1, stream=3, eos=0]], frames=4/5 (r/s)
backend_1     | [Tue Aug 24 23:34:44.829107 2021] [http2:debug] [pid 10:tid 140018503931648] h2_session.c(595): [client 172.20.0.4:44400] AH03068: h2_session(67,BUSY,1): sent FRAME[RST_STREAM[length=4, flags=0, stream=3]], frames=4/6 (r/s)
backend_1     | [Tue Aug 24 23:34:44.829119 2021] [http2:debug] [pid 10:tid 140018503931648] h2_session.c(267): [client 172.20.0.4:44400] AH03065: h2_stream(67-3,CLOSED): closing with err=1 protocol error
```

It is worth adding that if apache is not able to handle h2 connection it works flawlessly.

### Expected Behavior

I would expect that configuration of the backend with both http/2 and websocket protocols should be no-brainer, or at least fail with noticeable messages.

### Steps to Reproduce the Behavior

I prepared simple dev environment that shows exactly this issue with minimum configuration - [reproduce-haproxy-websocket-issue](https://github.com/DCkQ6/reproduce-haproxy-websocket-issue) 
1. `git clone https://github.com/DCkQ6/reproduce-haproxy-websocket-issue.git`
2. `docker-compose up --build`
3. Visit https://localhost:8443/test.html to observe failure and https://localhost:8444/test.html for working configuration (without `alpn` directive)

### What is your configuration?

```haproxy
global
  default-path config
  log         stdout local0 debug

defaults
  mode                    http
  log                     global

frontend _front_works
  bind  *:8444     ssl crt /usr/local/etc/haproxy/certificate alpn h2,http/1.1
  default_backend _back_works

frontend _front_fails
  bind  *:8443    ssl crt /usr/local/etc/haproxy/certificate alpn h2,http/1.1
  default_backend _back_fails


backend _back_works
  server apache backend:443 check ssl verify none

backend _back_fails
  server apache backend:443 check ssl verify none alpn h2,http/1.1
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.3-4dd5a5a 2021/08/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.3.html
Running on: Linux 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by wtarreau** [comment]
I believe it's expected to work but I honestly don't remember :-/  CCing @a-denoyelle who knows best.

**Comment by a-denoyelle** [comment]
I cannot reproduce simply the issue on my side, I will look into your reproducer to investigate this.

**Comment by a-denoyelle** [comment]
The problem is that apache seems to not support the rfc 8441, and so it is not possible to use a h2 connection with websockets to it. There is no way to make it work with alpn h2 configured on the server line.

As a side note, there is however one mistake in the haproxy implementation. The Extended CONNECT should not be used as the server side did not advertize it, so the request error could be reported more quickly on the haproxy side.

**Comment by wtarreau** [comment]
I'm starting to wonder if we'll need to provide a way to configure this. It's problematic that we can first try to negotiate H2 when we know we'll need WS, and that we don't even know if the connection will support RFC8441. But this would also involve rethinking a little bit the idle connections' organization to determine RFC8441-capable vs non-capable ones. It's not an easy problem at all.

**Comment by capflam** [comment]
FYI, this issue should be fixed now. The 2.4.9 was released with the appropriate patches.

**Comment by MangalaKavi** [comment]
Hi, websocket with http2 doesnt seem to be working, below is my setup:

client ->loadbalancer->haproxy->websocket_service
http1.1_websocket->http2_websocket->haproxy(h2 to h1)->http1_1_websocket service

So my loadbalancer sent a http2 request to haproxy, i expected haproxy to properly convert websocket request in http2 to http1.1 format, ie, adding upgrade,connection and sec-websocket-key, however, pls find the below packet that haproxy is sending it is not adding the above mentioned header, also the method should be GET but not connect

connect / HTTP/1.1
host: 10.1.1.1:8081
sec-websocket-version: 13
sec-websocket-extensions: permessage-deflate; client_max_window_bits
transfer-encoding: chunked

haproxy version that i have configured

HAProxy version 2.5.7-1ppa1~bionic 2022/05/14 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.7.html
Running on: Linux 4.15.0-180-generic #189-Ubuntu SMP Wed May 18 14:13:57 UTC 2022 x86_64

**Comment by wtarreau** [comment]
Hello,

first it's better not to reuse a closed thread that ended in "fixed" as it definitely implies that the problem you're facing has a different cause.

Second, did you type the request by hand or it this what your server received ? I'm asking because HTTP methods are case-sensitive, and `connect` is not `CONNECT` and what you're showing here definitely looks like a `connect` method sent over H2 and forwarded to H1. And that's definitely not websocket, of course. What's your client ?
