### ISSUE TITLE
Undefined preprocessor defines

### ISSUE THREAD

**Issue by ezequielgarcia** [haproxy/haproxy#1369]
### Tool Name and Version

-Wundef

### Code Report

```plain
Enabling -Wundef and then doing a regular build such as `make TARGET=linux-glibc`, shows a couple undefined stuff.


include/import/eb64tree.h:556:5: warning: "BITS_PER_LONG" is not defined, evaluates to 0 [-Wundef]
  556 | #if BITS_PER_LONG >= 64
include/haproxy/defaults.h:287:5: warning: "MAXHOSTNAMELEN" is not defined, evaluates to 0 [-Wundef]
  287 | #if MAXHOSTNAMELEN
include/haproxy/regex-t.h:39:7: warning: "USE_PCRE2" is not defined, evaluates to 0 [-Wundef]
   39 | #elif USE_PCRE2
```

In particular it looks like `ebtree` BITS_PER_LONG should be either defined a-la-qemu or __BITS_PER_LONG?
```


### Additional Information

_No response_

### Output of `haproxy -vv`

```plain
I'm using today's git HEAD
```

**Comment by wtarreau** [comment]
Hi Ezequiel,

I never noticed these ones, thanks for the report. While I'm used to using `#if` with a macro being 0 if undefined, some of them can indeed be changed and I agree that there's an issue with BITS_PER_LONG making the code select a less optimal version. I'll have a look at it, thank you!

**Comment by wtarreau** [comment]
I fixed all those I could reproduce here. I'm now thinking that we might benefit in enabling it by default. Anyway, since that looks OK now, I'm closing. Thanks for reporting!

**Comment by ezequielgarcia** [comment]
@wtarreau happy to help! I think enabling Wundef makes sense, e.g. weston uses it: https://gitlab.freedesktop.org/wayland/weston/-/commit/cde58fd20a6e0a3f83ad3dafde2a0e89994c6e29.

**Comment by wtarreau** [comment]
I'm sure we still have a few leftovers of them that could pop up in various configuration options, because it used to be very convenient to rely on just #if. But as you reported, it can also occasionally hide a bug, so that's a very little convenience that's not necessarily worth keeping. I'll push a test branch through the CI just to see if other ones pop up.

**Comment by wtarreau** [comment]
So by playing with the CI and "git grep" a little bit, I found a handful of other ones but now there's no more issue, everything's OK, thus I enforced it. If it causes unexpected harm in less commonly built code, it's easy to revert. Thanks for your insights!

**Comment by ezequielgarcia** [comment]
@wtarreau Using the commits here as inspiration, I did some changes to ebtree itself. https://github.com/wtarreau/ebtree/pull/2. Thanks!
