### ISSUE TITLE
Suspicious implementation of thread_has_tasks()

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1370]
### Tool Name and Version

CodeQL

### Code Report

```plain
static inline int thread_has_tasks(void)
{
	return (!!(global_tasks_mask & tid_bit) |
		!eb_is_empty(&sched->rqueue) |
	        !!sched->tl_class_mask |
		!MT_LIST_ISEMPTY(&sched->shared_tasklet_list));
>>>  Usage of a logical not (!) expression as a bitwise operator. 
}
```

### Additional Information

Should the function use `||` instead?

### Output of `haproxy -vv`

```plain
2.5-dev5
```

**Comment by wtarreau** [comment]
That was intended here and at a few other places in the critical path where it produces better code. That's the reason for the "!!" on the first one. All values are turned to pure 0 or 1 which can be arranged more efficiently using logical OR than with compare and cond jumps.
