### ISSUE TITLE
Add warning ssl_fc_sni must *never* be used for routing to the documentation

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1373]
… and possibly to the config parser if it is possible to detect this case?

**Comment by wtarreau** [comment]
I would not say "never" but I'd say that it's very unlikely to match what the users think they want to do, particularly in HTTP. And we must really explain why and remind users that using anything but Host in HTTP can easily lead to vulnerabilities by routing the traffic to the wrong location.

**Comment by lukastribus** [comment]
I agree.

We also give the dangerous advice about this in the [sni](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#5.2-sni) server keyword documentation.

> A typical use case is to send the SNI received from the client in
> a bridged HTTPS scenario, using the "ssl_fc_sni" sample fetch for the
> expression, though alternatives such as req.hdr(host) can also make sense.

**Comment by wtarreau** [comment]
Finally done!
