### ISSUE TITLE
The variable meth_sl is used before being assigned

### ISSUE THREAD

**Issue by CHHJIA** [haproxy/haproxy#1375]
### Detailed Description of the Problem

The variable _meth_sl_ is not assigned in a branch at line 239 in _src/h2.c/h2_prepare_htx_reqline_. However, its value is used after.

### Expected Behavior

The variable _meth_sl_ should be assigned to  _phdr[H2_PHDR_IDX_METH]_

### Steps to Reproduce the Behavior

None

### What is your configuration?

```haproxy
None
```

### Output of `haproxy -vv`

```plain
None
```

**Comment by wtarreau** [comment]
No, please look closer, all conditions result in leaving via `fail`. So it will not be used.
