### ISSUE TITLE
16 out of 48 threads start using 100% CPU

### ISSUE THREAD

**Issue by jaroslawr** [haproxy/haproxy#1383]
### Detailed Description of the Problem

As traffic increases, but way before the sever is saturated, 16 threads out of a total of 48 will start using 100% CPU. It's always a set of 16 threads and its either the first 16 threads or the last 16 threads (I reproduced it 5 times and it never hit the middle 16 threads). 

In `show threads` those threads show large run queue size (`rqsz`): [show_threads2.txt](https://github.com/haproxy/haproxy/files/7116204/show_threads2.txt)

`show tasks` output: [show_tasks.txt](https://github.com/haproxy/haproxy/files/7116158/show_tasks.txt)

### Expected Behavior

Threads don't saturate prematurely.

### Steps to Reproduce the Behavior

It just happens as traffic increases, but while the server still has a lot of free resources hardware-wise. Maybe a race condition triggered by increased concurrency?

### What is your configuration?

```haproxy
global
        user haproxy
        group haproxy

        nbthread 48
        cpu-map auto:1/1-48 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94

        maxconn 120000
        hard-stop-after 10s

        tune.bufsize 32768
        tune.ssl.default-dh-param 2048
        tune.ssl.cachesize 10000000
        tune.ssl.lifetime 3600

        log /dev/log local0 info

defaults
        mode http

        log global
        option httplog

        option forwardfor
        option http-buffer-request

        maxconn 110000

        retries 0
        no option redispatch

        timeout client 30000
        timeout server 500
        timeout connect 25
        timeout queue 25

frontend http
        bind *:80

        default_backend xyz

frontend https
        bind *:443 ssl crt /etc/haproxy/abcd.pem alpn h2,http/1.1

        default_backend xyz

backend xyz
        balance leastconn
        option httpchk
        http-check send meth HEAD uri /healthcheck
        default-server check inter 1000 maxqueue 1

        server xyz_101.net_1234 xyz_101.net:1234 weight 10 maxconn 10
        ...
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.3-4dd5a5a 2021/08/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.3.html
Running on: Linux 5.10.0-1026-oem #27-Ubuntu SMP Thu May 6 07:19:13 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by jaroslawr** [comment]
I attach a flamegraph from just one of the busy threads (zipped because github won't let me attach a .svg file). It seems to spend a lot more time than usual in fwlc_get_next_server and fwlc_srv_reposition.
[haproxy_stuck_thread.zip](https://github.com/haproxy/haproxy/files/7116643/haproxy_stuck_thread.zip)

**Comment by wtarreau** [comment]
Could you please also send the output of `lscpu -e` ? I'm wondering if the CPUs corresponding to the threads in question wouldn't be spread over two distinct L3 caches, making their interactions way slower. Or do you have certain frontends bound to some of these threads only maybe ?

**Comment by jaroslawr** [comment]
@wtarreau  The CPU is an EPYC 7702P, it has 16MB of L3 per each 4 physical cores. In the setup described above we bind HAProxy threads to only one thread (logical core) from each physical core, so HAProxy threads also share L3 cache in groups of 4.

**Comment by wtarreau** [comment]
OK thanks. So that definitely validates the problem I'm talking about, that communication is OK within a group but terrible between groups. This is exactly the reason the work on thread-groups was started on 2.5. The leastconn algo precisely is one example that causes massive inter-thread synchronization and where I would like to see one head per thread-group. It would significantly reduce contention while still producing very good results under load.

I suspect that you're occasionally facing the rare case you were facing more often in the past where most servers are saturated or about to be saturated in the leastconn tree and the lookup to find a free one is quite long.

Do all your servers use the same maxconn value ? Do you have some slowstart on some servers ? I'm just trying to figure what situations could occasionally inflate the lookup/update cost.

**Comment by jaroslawr** [comment]
@wtarreau Based on the stats page the servers seem to have scur far from maxconn, and I repeated the tests with server maxconn removed with the same effect. Why are groups of 8 physical cores affected if only groups of 4 share the cache?

**Comment by wtarreau** [comment]
Most likely because some of these two groups are working together and one group often wins and the other one often loses for example. Note that haproxy has no idea of cores in use nor cache, so this really shows that the low-level behavior in the hardware is very uneven. Depending on what we spot, we may figure some adjustments to help it though.

Could you please try to run "perf top" when this happens, then zoom in the top-most function and scroll until you spot two-digit percents and copy-paste the output ? This will indicate us exactly the atomic ops that are involved and could be of significant help.

**Comment by jaroslawr** [comment]
@wtarreau Here it is:

![ha_perf_top](https://user-images.githubusercontent.com/26233/132710065-18534cbb-f12c-47a8-a8a6-6d9284764dd5.png)
![ha_perf_top_fwlc_get_next_server](https://user-images.githubusercontent.com/26233/132710056-0f370b46-209c-46e4-9244-c8e9db60c9de.png)
![ha_perf_top_fwlc_srv_reposition](https://user-images.githubusercontent.com/26233/132710059-587bff80-e5f5-48cc-927f-34546001be43.png)

**Comment by wtarreau** [comment]
Thanks! It's the lbprm lock. It's not even trying to obtain it, it's trying to load the cache line into the local CPU that takes so much time! It indicates that once the cache line is in another L3 part, it tends to stick there for a while. This is even partially visible by the fact that the initial read took 8 times longer than the atomic read-modify-write that followed, which indicates that once the line is there, it can be instantly updated. Maybe this CPU tries to optimize the success of CMPXCHG instructions by delaying the relinquish of just written entries, but as can be seen here it can have a very bad effect :-/  This further motivates me to continue my researches on forcing CPUs to become more fair to each others regarding atomics.

**Comment by wtarreau** [comment]
Hey @jaroslawr I'm wondering if you've given 2.7 a try.  It integrates exponential back-off on threads that was carefully tuned to work fairly on AMD (I could double the performance and completely flattern the last percentile of latency with it). In such a case we could close this issue then.

**Comment by capflam** [comment]
@jaroslawr, is this issue is still relevant ? did you get a change to test a newer release ?

**Comment by jaroslawr** [comment]
@capflam @wtarreau In general we use 2.7.x without issues but not exactly in the setup described in this issue and I did not repeat and probably will not quickly repeat stress tests of the kind I reported here, when reporting this I was experimenting with different ways to pin HAProxy instances and network card queues to CPU cores. Since I did not find any better way than our "default" way, we returned to the "default" way of using two HAProxy instances on a 128-logical-core server, one instance pinned to 64 cores. We still have to migrate this setup to use the new thread groups. So from my POV this definitely can be closed.

**Comment by jaroslawr** [comment]
(In the "default" setup and while the physical cores are < 100% utilized we do not observe any stability issues or unfairness with respect to cores, both at the time this was originally reported and now, the tests were taking things to their limit...)

**Comment by capflam** [comment]
Thanks @jaroslawr, I'm closing now.
