### ISSUE TITLE
future of BoringSSL support

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1386]
### Detailed Description of the Problem

starting in https://boringssl.googlesource.com/boringssl/+/dddb60eb9700110835ff6e2b429de40a17006429
X509_OBJECT is not exportable from BoringSSL anymore

```
[ilia@fedora haproxy]$ grep -r X509_OBJECT .
./include/haproxy/openssl-compat.h:static inline X509_CRL *X509_OBJECT_get0_X509_CRL(const X509_OBJECT *a)
./include/haproxy/openssl-compat.h:static inline STACK_OF(X509_OBJECT) *X509_STORE_get0_objects(X509_STORE *st)
./include/haproxy/openssl-compat.h:static inline int X509_OBJECT_get_type(const X509_OBJECT *a)
./include/haproxy/openssl-compat.h:static inline X509 *X509_OBJECT_get0_X509(const X509_OBJECT *a)
./include/haproxy/openssl-compat.h:static inline X509_CRL *X509_OBJECT_get0_X509_CRL(const X509_OBJECT *a)
./src/ssl_ckch.c:	STACK_OF(X509_OBJECT) *objs;
./src/ssl_ckch.c:	for (i = 0; i < sk_X509_OBJECT_num(objs); i++) {
./src/ssl_ckch.c:		cert = X509_OBJECT_get0_X509(sk_X509_OBJECT_value(objs, i));
./src/ssl_ckch.c:	STACK_OF(X509_OBJECT) *objs;
./src/ssl_ckch.c:			cert_count = sk_X509_OBJECT_num(objs);
./src/ssl_ckch.c:	STACK_OF(X509_OBJECT) *objs;
./src/ssl_ckch.c:	for (i = 0; i < sk_X509_OBJECT_num(objs); i++) {
./src/ssl_ckch.c:		crl = X509_OBJECT_get0_X509_CRL(sk_X509_OBJECT_value(objs, i));
./src/ssl_sock.c:		X509_OBJECT *obj;
./src/ssl_sock.c:		STACK_OF(X509_OBJECT) *objs = X509_STORE_get0_objects(store);
./src/ssl_sock.c:		for (i = 0; i < sk_X509_OBJECT_num(objs); i++) {
./src/ssl_sock.c:			obj = sk_X509_OBJECT_value(objs, i);
./src/ssl_sock.c:			switch (X509_OBJECT_get_type(obj)) {
./src/ssl_sock.c:				X509_STORE_add_cert(store_ctx, X509_OBJECT_get0_X509(obj));
./src/ssl_sock.c:				X509_STORE_add_crl(store_ctx, X509_OBJECT_get0_X509_CRL(obj));
./src/ssl_sock.c:		STACK_OF(X509_OBJECT) *objs;
./src/ssl_sock.c:		for (i = 0; i < sk_X509_OBJECT_num(objs); i++) {
./src/ssl_sock.c:			x = X509_OBJECT_get0_X509(sk_X509_OBJECT_value(objs, i));
[ilia@fedora haproxy]$ 

```

### Expected Behavior

preserving backward compatibility in BoringSSL side (nothing we can guarantee)

### Steps to Reproduce the Behavior

https://github.com/haproxy/haproxy/runs/3497255293

### Do you have any idea what may have caused this?

Google unawareness of compatibility

### What is your configuration?

```haproxy
no
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by chipitsine** [comment]
partially fixed by https://github.com/chipitsine/haproxy/commit/5c88436683aa81a7105e6a690ba15cf56278b4d0

(but still a lot of thing to fix)

**Comment by wlallemand** [comment]
It's heavily related to #1276, lot of changes are to be done to remove the deprecated API. We planned to have someone at the company to do it.

**Comment by chipitsine** [comment]
I checked latest activity in OpenSSL, `X509_OBJECT` is still exportable for dev branch. Despite of `aligning with OpenSSL` I do not see such an activity in OpenSSL itself (but I might be wrong on that)

**Comment by sooslaca** [comment]
hi @chipitsine , not sure how to properly send a PR or a commit for your repo. 
Along with your fix above, I copied the X509_OBJECT definition from https://boringssl.googlesource.com/boringssl/+/refs/heads/2924/include/openssl/x509_vfy.h#120 
to 
https://github.com/haproxy/haproxy/blob/master/include/haproxy/openssl-compat.h#L180

and it's working.
It compiles again with boringssl (commit: 3a667d10e94186fd503966f5638e134fe9fb4080 latest stable as of today: https://boringssl.googlesource.com/boringssl/+/chromium-stable)

What do you think should it be safe to add this back in 2.4.12?

**Comment by sooslaca** [comment]
Figured, sent a PR for your branch: https://github.com/chipitsine/haproxy/pull/11

**Comment by chipitsine** [comment]
That was not supposed to happen (you could create your own fork), but that's legitimate approach. I'll have a look, thanks!

**Comment by chipitsine** [comment]
@sooslaca , I've merged your PR and enabled BoringSSL: https://github.com/chipitsine/haproxy/runs/4747418259?check_suite_focus=true

however, you can do the same in your own fork. I' fine with such PRs, but it looks like non needed step

**Comment by chipitsine** [comment]
@sooslaca , I'm going to send my patch to the list soon. your patch is appropriate. are you going to send it yourself ? or I can do it as well

**Comment by sooslaca** [comment]
I don’t know what list you think of so please go ahead and do it @chipitsine . Thanks

**Comment by chipitsine** [comment]
@sooslaca , here's guide how to contribute: https://github.com/haproxy/haproxy/blob/master/CONTRIBUTING

**Comment by chipitsine** [comment]
patches sent to the list for discussion

https://www.mail-archive.com/haproxy@formilux.org/msg41781.html

**Comment by wlallemand** [comment]
I'm updating the ticket with what I sent on the mailing list:


> But when checking the commits they didn't make anything deprecated in                                                                             
> fact, they just made it opaque.                                                                                                                   
>                                                                                                                                                   
> https://boringssl.googlesource.com/boringssl/+/dddb60eb9700110835ff6e2b429de40a17006429                                                           
>                                                                                                                                                   
> In this commit they pretend aligning with OpenSSL, which might be the                                                                             
> case, if you take a look at openssl/x509.h, they still define:                                                                                    
>                                                                                                                                                   
> - DEFINE_STACK_OF(X509_OBJECT)                                                                                                                    
> - OPENSSL_EXPORT STACK_OF(X509_OBJECT) *X509_STORE_get0_objects(X509_STORE *st);                                                                  
>                                                                                                                                                   
> So either there is an export problem of the X509_OBJECT or we are                                                                                 
> missing a include or something else is wrongly done.                                                                                              
>                                                                                                                                                   
> I'll made some test to check what's going on.

> I just tried to build with the latest boringSSL version, the problem is
> on our side:
> 
> We are defining X509_OBJECT_get0_X509_CRL() because it does not exist in
> boringSSL, and inside it we are accessing the members of the X509_OBJECT
> and it can't work since it's opaque.
> 
> We need to use the accessors instead, or find an alternative API.


> So, basically, we need to extract some X509_CRL from an X509_STORE which
> could be done in OpenSSL  with the X509_OBJECT API by using
> X509_OBJECT_get0_X509_CRL() which is not available in boringSSL
> 
> We are kind of stuck there because this is supposed to be the low
> level API, now everything is opaque and we can't do much.
> 
> The alternative would be to stop using the X509_STORE for storing the
> CRL, and use a STACK_OF(X509_CRL)... But we use the store because it
> could be either a X509_CRL or a X509... so it would be kind of
> redefining a X509_STORE API... and I honestly don't want to do that.
> 
> In my opinion there is a problem in their API because there is no
> accessor for the X509_CRL in a X509_OBJECT. Which is kind of weird
> because they have a X509_OBJECT_get0_X509() accessor, they probably just
> missed it.

**Comment by wlallemand** [comment]
I'm closing the issue, problem is not on our side.
