### ISSUE TITLE
gRPC proxy performance and timeout errors in HAProxy 1.9.8 and 2.0.1

### ISSUE THREAD

**Issue by danf0rth** [haproxy/haproxy#139]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.1-1ppa1~bionic 2019/06/27 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-O7_wB6/haproxy-2.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

```

```
uname -a
Linux grpc-balancer 5.1.9-050109-generic #201906111132 SMP Tue Jun 11 11:35:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Also tried 4.15.0-50 kernel

## What's the configuration?

```
global
    log stdout local0
    maxconn 100000
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options ssl-min-ver TLSv1.1
    tune.ssl.default-dh-param 2048
    tune.h2.max-concurrent-streams 100000 # 65535 # 65535 # 8096
    #nbproc 4
    nbthread 4
    cpu-map 1- 0-
	
defaults
    log global
    mode http
    timeout connect 5s
    timeout client 30s
    timeout server 30s
    option httplog
    # option logasap
    option http-use-htx
    http-reuse always
    maxconn 100000      

frontend grpc-proxy
    bind :9000  ssl crt /etc/ssl/private/grpc-balancer.pem alpn h2
    default_backend grpc-feeds

backend grpc-feeds
    balance roundrobin

    server grpc-feeds-01    1.2.3.4:9000    ssl verify none alpn h2 check weight 10
    server grpc-feeds-02    5.6.7.8:9000    ssl verify none alpn h2 check weight 6 
```

## Steps to reproduce the behavior

1. Create two gRPC servers with single directional streaming
2. Put HAProxy as balancer in front of  them
3. Start benchmark

## Actual behavior
Performance through balancer less than direct connect to single node. When i benchmark directly to the single node, i get about 2k rps and no errors. When i benchmark through HAProxy with two servers in backend, i get about 1600 rps and a lot of errors on client side, such as:

```
13 - server closed the stream without sending trailers (rpc error: code = Internal desc = server closed the stream without sending trailers)
```

```
14 - stream terminated by RST_STREAM with error code: REFUSED_STREAM (rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: REFUSED_STREAM)
```

## Expected behavior
Performance should be higher with HAProxy and two servers in backend than direct connect to single server.

## Do you have any idea what may have caused this?
To explain my idea why this could happen, first i want to explain how my application works. There are gRPC client and server written on Golang with this [lib](https://github.com/grpc/grpc-go).

This is algorithm how my applications works:
1. gRPC client perform request to gRPC server with timeout (1s500ms)
2. gRPC server receive request and start making another requests to external resources, starting streaming responses responses as soon as it get them.
3. If it is fast enough to get all responses and stream them to client, it's ok and nothing to do.
4. If client see that 1s500ms passed, but the stream is still not closed, client cancel the context (see golang context), that should be propagated to the gRPC server. What it means? It means that when client canceled context, the server notified about this and server stops all expensive jobs associated with this request. We will not do any job if client not waiting for response anymore.

My opinion when client closes context (i don't know how this really happened on low level), HAProxy still keeping connect opened and my backend servers still doing expensive jobs.

## Do you have an idea how to solve the issue?
If my guess is correct, HAProxy should also notify the backend servers when client is not waiting for response anymore, so they should stop their expensive work. 

## More
Please, see this topic on official HAProxy forum, i discussed this problem but no success: https://discourse.haproxy.org/t/haproxy-performance-issue-when-proxying-to-grpc/3927

Sorry for my ugly english, hope you understand me.

**Comment by wtarreau** [comment]
The behaviour you describe is normal and expected as by default, haproxy lets a server finish a job that was started (it is because in HTTP/1 there is no visible difference between a client which stops and a client which simply shuts down the send channel). You can however make haproxy forward the close to the server using "option abortonclose". Then the server will receive the close notification and will decide whether to continue or to stop.

**Comment by wtarreau** [comment]
Given that it matches the documented behaviour I'm adjusting the tags.

**Comment by danf0rth** [comment]
My idea was based on the fact that HAProxy is slower in rps under benchmark that when i perform benchmark directly to single node. I thought that if HAProxy did not closing connection, my backends became a bottleneck due to a lot of work that nobody needs anymore. 

Anyway, i just added `option abortonclose` to backend block, and make one more benchmark:

1. Direct connect to single node
2. Connect to HAProxy with the same node in backend (only one node)

Results:

1. I run benchmark 14m and did not get any errors, result is:
```
./grpc-client -addr ip-of-direct-node:9000 -workers 4096
^C2019/07/01 12:22:46 3187449 requests, 3186808 responses, 3186808 filled, 0 empty
2019/07/01 12:22:46 3790.84 rps (14m0.660693566s)
```
2. 1 minute and i started to receive errors. This is not all errors, but the latest one that i could copy from my ssh terminal. There are also was errors from my first post from __Actual behavior__ section.

```
... a lot of errors, i hit Ctrl^C
2019/07/01 12:51:50 unknown error: 14 - stream terminated by RST_STREAM with error code: REFUSED_STREAM (rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: REFUSED_STREAM)
2019/07/01 12:51:50 unknown error: 14 - stream terminated by RST_STREAM with error code: REFUSED_STREAM (rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: REFUSED_STREAM)
2019/07/01 12:51:50 unknown error: 14 - stream terminated by RST_STREAM with error code: REFUSED_STREAM (rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: REFUSED_STREAM)
^C2019/07/01 12:51:54 236850 requests, 232754 responses, 232754 filled, 0 empty
2019/07/01 12:51:54 3815.99 rps (1m0.994364049s)

```

I believe that i missed some configuration option or something else, because i am new to HAProxy.

What option can cause such behavior and how to make HAProxy perform more reliable when proxying to gRPC servers?

**Comment by wtarreau** [comment]
The REFUSED_STREAM code is sent when the server side closed with no response. This typically happens when forwarding to an HTTP/1 server over a keep-alive connection which closes at the time we're trying to use it, or similarly if a GOAWAY was received after the request was sent. In this case the request is lost and REFUSED_STREAM invites the client to try again. Maybe in some cases your server fails to respond to some requests or rejects some of them for whatever reason. Maybe some requests are sent before the server emits a GOAWAY to limit the number of streams over a connection and are lost. I can suggest you two things:
1. update to 2.0.2 which fixed a significant number of issues related to message forwarding and closing, as this could very well be a side effect of such a bug.
2. try to enable L7 retries to let haproxy retry in the case the server closes the connection.

**Comment by capflam** [comment]
Flagged to work as designed and inactive since a while. May be closed now.
