### ISSUE TITLE
Client certificate request interaction with GO's http.Client

### ISSUE THREAD

**Issue by gkatev** [haproxy/haproxy#1399]
### Detailed Description of the Problem

Hi, 
I've come across a problem/bug with client certification between a GO language application and Haproxy. The problem is that no client certificate is presented to the server (proxy), either because it is not requested properly, or because it is not offered by the client.

However, I cannot pinpoint the fault to either the client's or the server's side, and as far as I can tell, with my limited understanding, the problem lies in the combination of the two. Testing with a different server or a different client, the problem goes away.

- GO client with HAProxy server: Errors, no certificate present, `SSL handshake failure` in server, `remote error: tls: certificate required` in client.
- Curl client with HAProxy server: No errors.
- GO client with openssl s_server: No errors, client certificate visible in server log.
- openssl s_client with HAProxy server: No errors visible, can see list of client certificate CA names in client log.

If you believe that the problem lies on the side of Go's library, please let me know, along with some relevant information so that I can properly raise the issue there.

If you need additional information please instruct me how I could go about obtaining it. (wireshark? additional logging in proxy?) Any form of guidance appreciated.

### Expected Behavior

When the `verify optional` or `verify required` keyword is set, the proxy properly requests a client certificate, and the client responds with one.

### Steps to Reproduce the Behavior

Load the attached HAProxy configuration, and use the below commands/code to replicate the 4 scenarios outlined in the problem description.

Minimal GO TLS Client (`$ go run <client.go>`)
```go
package main

import "log"
import "net/http"
import "net/url"
import "crypto/tls"

func main() {
	cert, err := tls.LoadX509KeyPair("client_cert.pem", "client_key.pem")
	
	if err != nil {
		log.Fatalf("Error creating x509 keypair")
	}
	
	client := &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
				Certificates: []tls.Certificate{cert},
			},
		},
	}
	
	// _, err = client.PostForm("https://localhost:22400", url.Values {});
	_, err = client.PostForm("https://localhost:443", url.Values {});
	
	if err != nil {
		log.Fatalf("POST error", err)
	}
}
```
OpenSSL client
```
$ openssl s_client -connect localhost:443 -cert <client_cert.pem> -key <client_key.pem>
```
OpenSSL server
```
$ openssl s_server -accept 22400 -Verify 1 -cert <server_cert.pem> -key <server_key.pem>
```
cURL client
```
$ curl -X POST --key <client_key.pem> --cert <client_cert.pem> --insecure https://localhost:443 
```

### What is your configuration?

```haproxy
global
    maxconn 20000
    log /dev/log local0 info
    user haproxy
    pidfile /run/haproxy.pid
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    option forwardfor
    maxconn 8000
    timeout connect 5s
    timeout client 30s
    timeout server 30s

frontend main
    bind :::443 ssl crt /etc/haproxy/ssl/ verify required ca-file /etc/ca-certificates/extracted/ca-bundle.trust.crt crt-ignore-err all
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.4-acb1d0b 2021/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.4.html
Running on: Linux 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fwrapv
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.1.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by wtarreau** [comment]
Thanks for this detailed report, this is very interesting. Out of curiosity, could you please try on a very old version (1.6, 1.7 or so) so that we can try to figure if it's a change of behavior in haproxy (and if so which one) ? It's also very possible that we do not set a certain option on the SSL stack that is mandatory for this client.

CCing @EmericBr and @wlallemand who know these areas much better than me.

**Comment by gkatev** [comment]
@wtarreau Indeed, I tried version 1.9.0 and it worked. No errors and printing the certificate in the console it looks correct. Furthermore, it seems that the error appeared in version 2.2.0.

- 2.1.7-2: working correctly
- 2.2.0-1: not working correctly

**Comment by wtarreau** [comment]
Extremely useful, thank you!

**Comment by capflam** [comment]
@EmericBr, @wlallemand, what is the status of this issue ?

**Comment by wlallemand** [comment]
No progress on this, should still be tested.

**Comment by Darlelet** [comment]
> OpenSSL server
$ openssl s_server -accept 22400 -Verify 1 -cert <server_cert.pem> -key <server_key.pem>

I ran some tests with 2.7 and 2.6 using self signed ca+certificates, here are my observations:

Adding `-CAfile <ca_file.pem>` to openssl s_server command:
```bash
openssl s_server -accept 22400 -Verify 1 -cert <server_cert.pem> -key <server_key.pem> -CAfile <ca_file.pem>
```
 
results in s_server behaving like haproxy with the provided bind line:
```conf
bind :::443 ssl crt server_cert_key.pem verify required ca-file ca_file.pem crt-ignore-err all
```

That is: go client failing with `"remote error: tls: unknown certificate authority"`

----------

Conversely, if we replace `ca_file.pem` with `@system-ca` in haproxy bind line:
```conf
bind :::443 ssl crt server_cert_key.pem verify required ca-file @system-ca crt-ignore-err all
```

haproxy's behavior now seems to match the original openssl s_server command (without CAfile):
```bash
openssl s_server -accept 22400 -Verify 1 -cert <server_cert.pem> -key <server_key.pem>
```

(go client is able to complete the TLS handshake and does not report any errors)

Please note that `@system-ca` ca-file argument support has been added in 2.6 (See: c6b1763dcdb645472cb02760ac91278c5c3e7d4f).

**Comment by glorpen** [comment]
I've wrestled with very similar or even the same (depending if OP was here from Syncthing forum ) problem - no cert from Syncthing client written in GO.

So, after some research, Go http library by default filters out certs with incompatible hashes and CA's - when HAProxy is configured with `ca-file <pem>`, it sends required CA's to Client and then Go client removes certs not from those CA's.
For Syncthing it goes more extreme as server/CA certs and clients certs often are not related at all, and in that cases Go client filter will always result in empty list of certs.

For now I've fixed it by making HAProxy use ca-certs from dir without certs eg. `ca-file /empty` - now Go client gets empty list of CA's and so does not remove any certs.

**Comment by capflam** [comment]
what is the status of this issue ? Is it still relevant ? What can we do ?

**Comment by wlallemand** [comment]
@glorpen from what you are explaining it looks to me that you need to use `ca-verify-file` http://docs.haproxy.org/3.0/configuration.html#ca-verify-file instead of `ca-file`, so HAProxy won't send the certificates in the CA names during the server hello.

I'm closing this ticket as the issue does not seem to be within HAProxy. feel free to reopen.
