### ISSUE TITLE
ub64enc, ub64dec backport for 2.2.x and more sample fetch 

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#1400]
### Your Feature Request

1. ub64enc/dec samples are already supported in 2.4.x 
Do you have a plan to backport in 2.2.x??

2. we want to more sample fetches ( tcp_info on tcp_sample.c and tls extension info in ssl_sample.c )

## tcp_info in tcp_sample.c  
-- already support 
rtt 
rttvar
-- need fetches 
tcp_options
snd_cwnd
rcv_space
snd_ssthresh
advmss
snd_wscale
rcv_wscale

## get tls extension info in ssl_sample.c, ssl_sock.c ( client hello )
session_id == ssl_fc_session_id
session_id_len
ec_point_formats_len
supported_versions_len
tls_record_ver
ciphers
signature_algo
supported_groups
session_ticket_len
record_size_limit_len
ciphers_len
grease_value
extslen
renegotiation_info
renegotiation_info_len
signature_algo_len

### What are you trying to do?

We want to classify a client from NAT IP.

ex) mobile user use samp ip from telco.

 

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.4 2021/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.4.html
Running on: Linux 5.11.0-1.el7.elrepo.x86_64 #1 SMP Sun Feb 14 18:10:38 EST 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = cc
  CFLAGS  = -O2 -march=native -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DTLS_TICKETS_NO=4
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS
-51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1l  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1l  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with Naver SSL Client Hello request capture. version: xxx
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-16)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment]
Well, I'm fine with occasionally backporting two trivial converters like above, but not a large series of sample fetches, particularly when some of them might even rely on subtle changes down the stack. The simple fact that you need so many to be available is a strong indication that you need to consider upgrading to 2.4. Major versions are made and maintained precisely to provide new features.

**Comment by zino7825** [comment]
@wtarreau I agree with you, but I have to check so many things for upgrading because of side effects.

**Comment by wtarreau** [comment]
For sure, but it you have so many things to check to upgrade, you can imagine the trouble it could be on the developers side to make sure not to break the code for *anyone* by attempting these backports, and worse, how to deal with breakage later once some might bee relying on stuff that ought never to have been backported and that cannot be reverted anymore!

**Comment by wtarreau** [comment]
By the way, keep in mind that many of us install several versions side by side. You could for example keep 2.2 for your main applications and install a 2.4 one for the only application that requires this for now, and progressively migrate your older configs there as you get more confidence into it.

**Comment by TimWolla** [comment]
@wtarreau I guess this one is not happening for the reasons you outlined. Shall we close this?

**Comment by wtarreau** [comment]
Yes Tim, I think we'd rather close indeed. 2.5 is already out, we'd have to backport that to 2.3 and 2.2 while 2.3 dies in a few months, so that's a good indication that 2.2 should be offered quite some rest and avoid non-100% necessary backports.

**Comment by zino7825** [comment]
@wtarreau @TimWolla 
I'm currently using 2.8.x, but there's still no significant added fetch on the tcp_info side.

I think it would be good to add the information below, what do you think?
```
tcpi_options
tcpi_snd_cwnd
tcpi_rcv_space
tcpi_snd_ssthresh
tcpi_advmss
tcpi_snd_wscale
tcpi_rcv_wscale
```

https://github.com/haproxy/haproxy/blob/4b5f55728352976e6fe39d92d5b365e8e60a7316/src/tcp_sample.c#L352-L359
