### ISSUE TITLE
Ha proxy not tagging FIX packets

### ISSUE THREAD

**Issue by ghost** [haproxy/haproxy#1401]
### Detailed Description of the Problem

Using the documentation from haproxy to configure basic fix tagging.
Here is my config

global

log 127.0.0.1:514 local2

chroot /var/lib/haproxy

pidfile /var/run/haproxy.pid

maxconn 4000

user haproxy

group haproxy

daemon

ca-base /etc/ssl/certs

crt-base /etc/ssl/private

stats socket /var/lib/haproxy/stats

setenv TCP_LOG "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq"

defaults

mode tcp

log global

timeout connect 3s

timeout client 2000ms

timeout server 2000ms

maxconn 500

frontend fix_listener

log 127.0.0.1:514 local2 debug

mode tcp

bind InternalIP:8444

log-format "${TCP_LOG} %[var(txn.sendercompid)] %[var(txn.targetcompid)]"

tcp-request content set-var(txn.sendercompid) req.payload(0,0),fix_tag_value(SenderCompID)

tcp-request content set-var(txn.targetcompid) req.payload(0,0),fix_tag_value(TargetCompID)

use_backend fixloadgen_tord if { var(txn.SenderCompID) -m str FIXLOADGEN_TORD }

backend fixloadgen_tord

mode tcp

server uatapp IP:15185

What I get as a result is I can see FIX logon message via dump but haproxy immediately send reset packet. When I remove the tagging and send straight through it works fine. Here is what my log looks like . I see an entry where the logon occurs

Sep 28 12:47:58 localhost haproxy[10650]: IP:62870 [28/Sep/2021:12:47:58.652] fix_listener fix_listener/<NOSRV> -1/-1/0 0 SC 1/1/0

/0/0 0/0 FIXLOADGEN_TORD TARGETCOMP_foo

Then I also see these messages 

Sep 27 14:29:48 localhost haproxy[7391]: externalIP:53720 [27/Sep/2021:14:29:04.530] fix_listener fixloadgen_tord/uatapp 1/0/43867 1106 CD

1/1/0/0/0 0/0 - - (these last two dashes should be loggin sendercompid and target) 

I sometimes will see it tag but most of the time it doesn't. Most importantly it doesn't detect it on the initial FIX login. 

### Expected Behavior

Redirect to specific backend based on sendercompid

### Steps to Reproduce the Behavior

Used standard configuration from haproxy's blog to setup tagging. Traffic does not get passed to backed server. It does work if I remove tagging and logic and send straight tcp. 

### Do you have any idea what may have caused this?

no

### What is your configuration?

```haproxy
Here is my config



global

log 127.0.0.1:514 local2

chroot /var/lib/haproxy

pidfile /var/run/haproxy.pid

maxconn 4000

user haproxy

group haproxy

daemon

# tune.ssl.default-dh-param 2048

ca-base /etc/ssl/certs

crt-base /etc/ssl/private

# turn on stats unix socket

stats socket /var/lib/haproxy/stats

setenv TCP_LOG "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq"



defaults

mode tcp

log global

# option tcplog

# option http-server-close

# option forwardfor except 127.0.0.0/8

# retries 3

# timeout http-request 10s

# timeout queue 1m

timeout connect 3s

timeout client 2000ms

timeout server 2000ms

# timeout http-keep-alive 10s

# timeout check 10s

maxconn 500





frontend fix_listener

log 127.0.0.1:514 local2 debug

mode tcp

# tcp-request inspect-delay 1s

bind InternalIP:8444

# option tcplog

# retries 3

log-format "${TCP_LOG} %[var(txn.sendercompid)] %[var(txn.targetcompid)]"

# tcp-request content reject unless { req.payload(0,0),fix_is_valid }

tcp-request content set-var(txn.sendercompid) req.payload(0,0),fix_tag_value(SenderCompID)

tcp-request content set-var(txn.targetcompid) req.payload(0,0),fix_tag_value(TargetCompID)

use_backend fixloadgen_tord if { var(txn.SenderCompID) -m str FIXLOADGEN_TORD }

# default_backend fixloadgen_tord







backend fixloadgen_tord

mode tcp

server uatapp IP:15185



What I get as a result is I can see FIX logon message via dump but haproxy immediately send reset packet. When I remove the tagging and send straight through it works fine. Here is what my log looks like . I see an entry where the logon occurs

Sep 28 12:47:58 localhost haproxy[10650]: IP:62870 [28/Sep/2021:12:47:58.652] fix_listener fix_listener/<NOSRV> -1/-1/0 0 SC 1/1/0

/0/0 0/0 FIXLOADGEN_TORD TARGETCOMP_foo

Then I also see these messages Sep 27 14:29:48 localhost haproxy[7391]: externalIP:53720 [27/Sep/2021:14:29:04.530] fix_listener fixloadgen_tord/uatapp 1/0/43867 1106 CD

1/1/0/0/0 0/0 - -
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.4-acb1d0b 2021/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.4.html
Running on: Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-39)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment]
For `tcp-request content` to wait for contents, you need to have a `tcp-request inspect-delay` statement which indicates how long to wait for the incoming data before taking a final verdict.

**Comment by wtarreau** [comment]
By the way once you have this you'll be able to uncomment the `reject` rule to make sure to only let analysed traffic pass through. Please try with a delay equivalent to your timeout client first, that should be enough, and let us know how it goes.

**Comment by ghost** [comment]
I tried adding tcp-request inspect-delay  before with various lengths all the way up to 60s. Still doesn't pass traffic.

**Comment by bedis** [comment]
Hi @gcbosonic 
Can you enable checks on the server:

    server uatapp IP:15185 check

What FIX protocol version are you using?
Would you be able to take a packet capture and send it to my email address of both working / non working situations?

**Comment by ghost** [comment]
We are using FIX 4.4. I'll send you packet captures yes.

**Comment by ghost** [comment]
I don't have your email but sent you a message on the public haproxy slack workspace.

**Comment by bedis** [comment]
I think I got it: the variable name is case sensitive in HAProxy and you're have typos in your config:

First, you capture and log the SenderCompID with a lowercase variable name:

    log-format "${TCP_LOG} %[var(txn.sendercompid)] %[var(txn.targetcompid)]"
    tcp-request content set-var(txn.sendercompid) req.payload(0,0),fix_tag_value(SenderCompID)

But when taking the routing decision, you inserted some uppercase letters:

    use_backend fixloadgen_tord if { var(txn.SenderCompID) -m str FIXLOADGEN_TORD }

Just replace the variable name in the `use_backend` directive by the one  you set with the `tcp-request content` directive and it should work.

**Comment by bedis** [comment]
It was hard to spot in your very first message cause the formatting is all broken....

**Comment by ghost** [comment]
that isn't the problem. Here is the current config and still doesn't detect it. 
`` frontend fix_listener
   log 127.0.0.1:514 local2 debug
   mode tcp
   bind IP:8444 #ssl  crt /etc/ssl/certs/star_otcxn.pem  ssl-min-ver TLSv1.2
   tcp-request inspect-delay 100000 

   retries                 3 
   log-format "${TCP_LOG} %[var(txn.sendercompID)] %[var(txn.targetcompid)] %[var(txn.errormessage)]"

   tcp-request content set-var(txn.sendercompid) req.payload(0,0),fix_tag_value(SenderCompID)
req.payload(0,0),fix_tag_value(TargetCompID)
   tcp-request content set-var(txn.errormessage) str("Sendercompid does not match  FIXLOADGEN_TORD") if !{ var(txn.sendercompid) -m str "FIXLOADGEN_TORD" }
   use_backend fixloadgen_tord if { var(txn.sendercompid) -m str FIXLOADGEN_TORD }



``

**Comment by ghost** [comment]
Here is my log entry. 
Oct  5 10:14:00 localhost haproxy[17992]: IP:34440 [05/Oct/2021:10:14:00.100] fix_listener fix_listener/<NOSRV> -1/-1/0 0 SC 1/1/0/0/0 0/0 - - Sendercompid does not match  FIXLOADGEN_TORD

**Comment by capflam** [comment]
@gcbosonic, please try to properly format your comments. Otherwise, it is pretty hard to diagnose errors. You still have case issue on `txn.sendercompid` variable in your log format. In addition, it is highly recommended to check the message validity first using `fix_is_valid` converter in an acl. It is a good way to validate the message was received. Otherwise, you must add an ACL condition to wait for the message to perform your  `set-var` action. Otherwise, the action will always be performed on the first evaluation regardless something was received or not. For instance:
```
tcp-request content set-var(txn.sendercompid) req.payload(0,0),fix_tag_value(SenderCompID) if { req.len gt 0 }
```

Note that this only waits for any content. If the message is fragmented, the `set-var` action can still fail. The best is to use an ACL to validate the message validity. For instance:
```
tcp-request content reject unless { req.payload(0,0),fix_is_valid }
tcp-request content set-var(txn.sendercompid) req.payload(0,0),fix_tag_value(SenderCompID)
```

**Comment by ghost** [comment]
It appears to be working now that I added FIX validator. (which I tested in the past but wasn't working). Problem fixed. thank you.
