### ISSUE TITLE
http-request set-method

### ISSUE THREAD

**Issue by sbuerg** [haproxy/haproxy#1403]
### Detailed Description of the Problem

I'm using haproxy 2.4.4. (compiled on SLES12 SP4) with OpenSSL 1.1.1l.

the problem:
http-request set-method POST doesnt work in the frontend  in mode http

here my attempt: (you see the request starts with a POST method):

SOAP::Transport::HTTP::Client::send_receive: HTTP::Request=HASH(0x3c6bff0)
SOAP::Transport::HTTP::Client::send_receive: POST https://server1.my.domain:7443/oscare/oma/ws/document/v3 HTTP/1.1
Accept: text/xml
Accept: multipart/*
Accept: application/soap
Content-Length: 1688
Content-Type: text/xml; charset=utf-8
SOAPAction: createDocument

the soap response of the server shows:  (the server receives a GET method)

SOAP::Transport::HTTP::Client::send_receive: HTTP::Response=HASH(0x4044730)
SOAP::Transport::HTTP::Client::send_receive: HTTP/1.1 405 Method Not Allowed
Connection: keep-alive
Date: Fri, 01 Oct 2021 16:25:26 GMT
Server: WildFly/10
Content-Length: 22
Content-Type: text/plain
Client-Date: Fri, 01 Oct 2021 16:25:26 GMT
Client-Peer: 10.115.52.222:8443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=DE/O=ITSCare/OU=PKI/CN=ITSCare Issuing CA 01
Client-SSL-Cert-Subject: /C=DE/O=ITSCare/OU=Infrastructure/OU=Manual/CN=server1.my.domain
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
Client-SSL-Version: TLSv1_2
Client-SSL-Warning: Peer certificate not verified
X-Powered-By: Undertow/1

HTTP GET not supported
--------------------------

the problem is that the http-request set-method not works.  you see it in my configuration

### Expected Behavior

i need the http-request set-method to change the method from GET to POST in the frontend before the haproxy sends the data to the backend.

### Steps to Reproduce the Behavior

no comment

### Do you have any idea what may have caused this?

http-request set-method not working. 
the backend receives a GET method.

### Do you have an idea how to solve the issue?

fix it in the source-code.

### What is your configuration?

```haproxy
listen ssl
   bind 0.0.0.0:7443 tfo ssl no-sslv3 crt /server/cert.pem
   option tcp-smart-connect
   server http 127.0.0.1:7084 send-proxy-v2

frontend http
   mode http
   http-request set-method POST
   bind 127.0.0.1:7084 tfo accept-proxy
   acl is_ssl fc_rcvd_proxy
   default_backend default

backend default
   cookie SERVERID insert indirect nocache
   server server1 server1.my.domain:8443 ssl verify none maxconn 1000 check inter 2s cookie server1
   server server2 server1.my.domain:8443 ssl verify none maxconn 1000 check inter 2s cookie server2
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.4-acb1d0b 2021/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.4.html
Running on: Linux 4.12.14-122.60-default #1 SMP Mon Feb 1 20:52:25 UTC 2021 (cb56da1) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = cc
  CFLAGS  = -O2 -march=native -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.37 2021-05-26
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
[WARNING]  (99222) : config : log format ignored for proxy 'ssl' since it has no log address.
[WARNING]  (99222) : config : log format ignored for frontend 'http' since it has no log address.
[WARNING]  (99222) : config : log format ignored for proxy 'stats' since it has no log address.
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
Using epoll() as the polling mechanism.
00000000:ssl.accept(0004)=0066 from [10.114.13.78:56976] ALPN=<none>
00000000:ssl.clireq[0066:ffffffff]: POST /document/v3 HTTP/1.1
00000000:ssl.clihdr[0066:ffffffff]: te: deflate,gzip;q=0.3
00000000:ssl.clihdr[0066:ffffffff]: connection: TE
00000000:ssl.clihdr[0066:ffffffff]: accept: text/xml
00000000:ssl.clihdr[0066:ffffffff]: accept: multipart/*
00000000:ssl.clihdr[0066:ffffffff]: accept: application/soap
00000000:ssl.clihdr[0066:ffffffff]: host: server1.my.domain:7443
00000000:ssl.clihdr[0066:ffffffff]: user-agent: SOAP::Lite/Perl/1.27
00000000:ssl.clihdr[0066:ffffffff]: content-length: 1688
00000000:ssl.clihdr[0066:ffffffff]: content-type: text/xml; charset=utf-8
00000000:ssl.clihdr[0066:ffffffff]: soapaction: createDocument
00000001:http.accept(0005)=0068 from [10.114.13.78:56976] ALPN=<none>
00000001:http.clireq[0068:ffffffff]: POST /document/v3 HTTP/1.1
00000001:http.clihdr[0068:ffffffff]: te: deflate,gzip;q=0.3
00000001:http.clihdr[0068:ffffffff]: connection: TE
00000001:http.clihdr[0068:ffffffff]: accept: text/xml
00000001:http.clihdr[0068:ffffffff]: accept: multipart/*
00000001:http.clihdr[0068:ffffffff]: accept: application/soap
00000001:http.clihdr[0068:ffffffff]: host: server1.my.domain:7443
00000001:http.clihdr[0068:ffffffff]: user-agent: SOAP::Lite/Perl/1.27
00000001:http.clihdr[0068:ffffffff]: content-length: 1688
00000001:http.clihdr[0068:ffffffff]: content-type: text/xml; charset=utf-8
00000001:http.clihdr[0068:ffffffff]: soapaction: createDocument
00000001:default.srvrep[0068:0069]: HTTP/1.1 302 Found
00000001:default.srvhdr[0068:0069]: x-powered-by: Undertow/1
00000001:default.srvhdr[0068:0069]: location: https://server1.my.domain:8443/document/v3
00000001:default.srvhdr[0068:0069]: content-length: 0
00000001:default.srvhdr[0068:0069]: date: Fri, 01 Oct 2021 16:25:26 GMT
00000001:default.srvcls[0068:0069]
00000001:default.clicls[0068:0069]
00000001:default.closed[0068:0069]
00000000:ssl.srvrep[0066:0067]: HTTP/1.1 302 Found
00000000:ssl.srvhdr[0066:0067]: x-powered-by: Undertow/1
00000000:ssl.srvhdr[0066:0067]: location: https://server1.my.domain:8443/document/v3
00000000:ssl.srvhdr[0066:0067]: content-length: 0
00000000:ssl.srvhdr[0066:0067]: date: Fri, 01 Oct 2021 16:25:26 GMT
00000000:ssl.srvhdr[0066:0067]: set-cookie: SERVERID=server1; path=/
00000000:ssl.srvcls[0066:0067]
00000000:ssl.clicls[0066:0067]
00000000:ssl.closed[0066:0067]
```

### Additional Information

no comment

**Comment by capflam** [comment]
I don't understand. In the HAProxy's debug messages, there is a POST request and a 302-Found response. not a 405-Method-Not-Allowed. Thus it is confusing. In addition, if the client sends a POST request, there is no reason to force the method to POST and the server will receive a POST. However, because there is a redirect URL pointing on your application server, it may be that your client is attempting to follow the redirect with a GET request directly on the application server, by-passing HAProxy.

**Comment by roidelapluie** [comment]
When you are redirected for a POST, most client generally wil do a GET of the 302 found response.  This is expected. See curl's example: https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

**Comment by sbuerg** [comment]
Our Webservices is using SOAP over HTTP (with a POST Method). 
My SOAP Request does it right, but the haproxy changed the request into GET Method. The Webservice answered with a 302 http Code not with a SOAP Response. if i use my request without haproxy, then it goes without problems.

Here is the definition ... you see it in example 3 (section 6.4)
[https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383527](url)

In documentation of haproxy i have found http-request set-method for the frontend section. i thought i could solve my problem, but i doesnt. how can i solve it?

**Comment by git001** [comment]
Well the server sends the 302 not haproxy.

```
00000001:default.srvrep[0068:0069]: HTTP/1.1 302 Found
00000001:default.srvhdr[0068:0069]: x-powered-by: Undertow/1
00000001:default.srvhdr[0068:0069]: location: https://server1.my.domain:8443/document/v3
00000001:default.srvhdr[0068:0069]: content-length: 0
00000001:default.srvhdr[0068:0069]: date: Fri, 01 Oct 2021 16:25:26 GMT
```

What's in the logs of undertow at that time?

**Comment by sb9x** [comment]
is the 302 a redirect of haproxy? if yes, how can i prevent haproxy to do that?

**Comment by sbuerg** [comment]
i think the problem is one of my webserver, because the first one produces the 302 found error. as i had performed my tests with the haproxy, i hadnt do more than 1 attempts. now i have done several requests and i have noticed, that the first server produces the 302 http code - the attempts with the second they worked.  thanks for your support.

**Comment by sbuerg** [comment]
the haproxy is running on the server2. 
my attempts works, if haproxy routes the requests to server2, but if the request changes to server1, then the Wildfly says that HTTP GET not supported (it cames from the web-applikation, because they need a POST method). any ideas?

**Comment by capflam** [comment]
It is out of HAProxy scope. So I'm closing the issue. But, if I correctly understand your issue, it seems your client follows the redirect link. It first sends a POST request to your app server (server1) via HAProxy, then a GET request directly to your app server because of the link in the 302-Found response. But I don't know why it works when the client try to reach the server2.
