### ISSUE TITLE
Race condition on socket timeout/closure

### ISSUE THREAD

**Issue by laurence-pawling** [haproxy/haproxy#1423]
### Detailed Description of the Problem

There appears to be some kind of race condition or lack of guard if a request arrives just as a connection is being torn down due to timeout. We have noticed this with internal connections between backends and frontends on the same haproxy instance (see config below - we use frontends listening on UNIX sockets to provide blue/green routes).
It would probably be true of a backend talking to a remote server that has an idle timeout as well - however the "loopback" scenario is easier to reproduce.

If a request is sent from a backend to another frontend *as the timeout client timer expires*, the request will be dropped with no response to the client, and "termination state: SD" will be logged for the request.

The bug seems to exist in recent versions of v1.8 and v1.9 (tested 1.8.27 on CentOS 7, and 1.8.28 and 1.9.16 on FreeBSD 11.4). However, it DOES NOT seem to exist in v1.8.24

### Expected Behavior

When a request is received by the backend, if the existing connection has been timed out by the end server (or child frontend) that it is being forwarded to, I would expect haproxy to create a new connection and use that, rather than trying to use a connection which is currently in the process of being torn down (or just abandoning the request) which seems to be what is happening

### Steps to Reproduce the Behavior

1. Vanilla haproxy server install running v1.8.27 or greater, or v1.9.16. Apparently OS-independent, we have verified on CentOS 7 and FreeBSD 11.4
2. Config as below (this is simplified from our normal blue/green config but demonstrates the issue)
3. An HTTP client that can submit a request every n seconds, where n is the value set in `timeout client` on the blue/green frontend. I have been using Locust with a single user (see Locustfile below)

I have tested this with different settings for timeout client and the result is always the same - a failure rate of up to around 40%. Changing the gap between requests by +/- 0.1 seconds prevents the problem occurring. However, we do see this on our production systems on occasion.

### Do you have any idea what may have caused this?

It seems to be some kind of race condition or lack of guard, where the haproxy backend tries to use a connection even though teardown has begun from the server end, or abandons the request because its chosen outbound connection is being torn down, rather than creating a new connection for that request.

### Do you have an idea how to solve the issue?

We have reduced the impact of the issue by using `http-reuse always`, which means a smaller pool of connections are then hit more frequently, preventing timeouts, but the issue still appears on occasion, for instance as demand drops after peak periods and the connection pool reduces naturally.

### What is your configuration?

```haproxy
# The following haproxy config file can be used to recreate the issue
# For simplicity I have been using a default install of nginx as the final backend, but anything will do.
# Multiple values of timeout client have been tested, and the failure occurs if the time between requests ~= timeout client.

global
    log         /var/run/log local2
    pidfile     /var/run/haproxy.pid
    daemon

frontend test
    bind 192.168.33.33:8080
    mode http
    default_backend bluegreen_selector

backend bluegreen_selector
    mode http
    http-reuse always
    server blue unix@/var/run/blue.sock

frontend blue
    bind /var/run/blue.sock user root mode 600
    timeout client 6s
    mode http
    default_backend local_nginx

backend local_nginx
    mode http
    server nginx 127.0.0.1:80



################
# locustfile.py
################
# Instantiate with something like:
# locust --headless --locustfile locustfile.py --users 1 --spawn-rate 1 --host http://192.168.33.33:8080
# However, any similar test should have the same effect - I've done the same with requests and sleep()

from locust import HttpUser, task, constant

class TestUser(HttpUser):

    @task
    def send_request(self):
        response = self.client.get('/',name='GET Request')
        response.close()

    wait_time = constant(6)
```

### Output of `haproxy -vv`

```plain
Centos:
[vagrant@hostname ~]$ uname -a
Linux hostname.test.lcy.globalsign.network 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

HA-Proxy version 1.8.27-493ce0b 2020/11/06
Copyright 2000-2020 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace




FreeBSD test VM:
root@hostname:/usr/home/vagrant # uname -a
FreeBSD hostname.test.lcy.globalsign.network 11.4-RELEASE FreeBSD 11.4-RELEASE #0 r362094: Fri Jun 12 18:27:15 UTC 2020     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

HA-Proxy version 1.9.16 2020/07/31 - https://haproxy.org/
No more fixes for branch 1.9 past this version, please upgrade to branch 2.0!
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-ignored-qualifiers -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wtype-limits -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_ACCEPT4=1 USE_REGPARM=1 USE_OPENSSL=1 USE_STATIC_PCRE=1 USE_PCRE_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2u-freebsd  20 Dec 2019
Running on OpenSSL version : OpenSSL 1.0.2u-freebsd  20 Dec 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE
              h2 : mode=HTX        side=FE|BE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

**Comment by laurence-pawling** [comment]
Note - forgot to mention above - the same problem occurs whether a UNIX socket or a TCP port is used for the "blue" frontend.

**Comment by jmagnin** [comment]
Hello @laurence-pawling and thank you for reporting this. Can you reproduce with more recent versions ?
1.8 only receives critical fixes, and 1.9 is no longer maintained.

**Comment by wtarreau** [comment]
Note, this is not a bug and is a documented and expected behavior of HTTP. The principle of reusing a connection implies that there is a time race between the moment the server decides to close and the moment the client decides to reuse the connection, so some data will *always* be dropped in flight when this happens.

HAProxy deals with this two ways:
  - the first (and original) one is that according to HTTP spec, only requests from the same client or idempotent requests are sent over reused connections by default. This guarantees that haproxy does not take more risks than the client does, so when this condition happens, we proceed the same way on the other side and the client can retry if it wants. In this case haproxy will close to the client without sending any response, in order to replicate the server's behavior (just as if the client was talking directly to the server, so that the client knows it's safe to retry). It seems to be what you're observing.
  - since 2.0 or so, we've implemented layer7 retries. They are configurable and allow to reconnect and send the same request over a new connection when facing a certain number of errors. It is *very important* to read the doc about these, because users tend not to understand the impact of retrying a request without the client's permission. Uusally retrying on failed connections is safe, but there's always a window of uncertainty (e.g. the request causes the server to crash, which cannot be distinguished from the server closing with a request in flight), and normally it ought to be the client's decision to retry.

I tend to recommend to only keep the first behavior, unless you know that your requests are idempotent and you want to hide occasional failures to your clients, knowing that the clients will not see them in browsers but only when using clients that do not retry on such standard failures, and that they would face exactly the same if they were connecting directly to the server. Layer7 retries are really made to hide internal problems such as servers crashing or being taken out of a farm and abruptly stopped.

**Comment by wtarreau** [comment]
By the way, here are the up-to-date specs on retries and idempotent requests:
  - https://www.ietf.org/archive/id/draft-ietf-httpbis-messaging-19.html#name-persistence
  - https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-idempotent-methods
