### ISSUE TITLE
Lua filters: HTTPMessage.body() erratic behaviour in filters when analysing some responses

### ISSUE THREAD

**Issue by vishnu-prasad-r** [haproxy/haproxy#1426]
### Detailed Description of the Problem

When `HTTPMessage.body()`  is called from  `FILTER.http_payload()` inside a **Lua filter**, the following erratic behaviour is observed

1.  When called with value of offset value as 0, i.e  `http_msg:body(0)
`, the returned value is an object of **userdata** type **LUABOX** is returned, instead of string or nil .

2.  When called with a positive value for length parameter, i.e `http_msg:body(0,100) `, the returned value is a **number**.  The returned number is in fact the _length_ parameter.
3.  When called with a negative value for offset parameters, ie `http_msg:body(-1) ` , **nil** is returned even though underlaying buffer contains valid response body. It is still possible to prepend a string to the http_msg using HTTPMessage.prepend() method.

### Expected Behavior

As per documentation HTTPMessage.body()  must either return a string or nil or raise an error.

Returning a number , or userdata object of type LUABOX is an unexpected behaviour.

Also, the method should return a string instead of nil if there is data in the buffers.

### Steps to Reproduce the Behavior

This bug is observed only for certain HTTP responses. It is observed when applying Lua filter to a dynamically generated HTTP response coming from a Ruby on Rails server.

The issue is not observed when static files are being served.

The issue is not observed on dynamic HTTP responses with large body. The issue is not observed when a small (992 byte long) static HTML page is served.

The issue is observed for several dynamic HTTP response of sizes of the order 8.3 KB, 9.5 KB,  10.6 KB , etc.

When same response bodies are served as static files, the issue is not observed. It appears like the issue has something to do with the speed and chuck sizes of response received from back-end server.

The issue is not observed when the response body is in fact empty (like when HTTP response code is 3XX) .

I was able to reproduce the issue consistently for certain pages on by dynamic website. But not with any random test blobs. 

### Do you have any idea what may have caused this?

Detailed debugging showed that whenever this issue is observed:

1. `FILTER.http_payload() `is called only once
2. `HTTPMessage.eom(http_msg) `is returning **true**

Observed the following from code tracing:
1. Even when the erratic behaviour is observed, all parameter validations and checks in method `__LJMP static int hlua_http_msg_get_body(lua_State *L)`  in hlua.c are passing successfully.

Execution is reaching here 
https://github.com/haproxy/haproxy/blob/b4d0cd02c14d4db1cf54b0bd8ee328fb198553f3/src/hlua.c#L6527 .

Hence the issue bug is in method `static int _hlua_http_msg_dup(struct http_msg *msg, lua_State *L, size_t offset, size_t len)` in hlua.c 
https://github.com/haproxy/haproxy/blob/b4d0cd02c14d4db1cf54b0bd8ee328fb198553f3/src/hlua.c#L6312

I found some logical error in the control flow. While iterating through HTX Blocks, if the first HTX block is a DATA block and later a non-DATA HTX is encountered, the method will return without pushing anything into the Lua stack. It would neither push the buffer , nor it will push a nil value. Since nothing is pushed to the stack, the Lua code will see last argument to the function as the return value (which will be the **offset** parameter, when supplied) .

### Do you have an idea how to solve the issue?

Rewriting the method by adding an else case for condition check on https://github.com/haproxy/haproxy/blob/b4d0cd02c14d4db1cf54b0bd8ee328fb198553f3/src/hlua.c#L6341

and pushing the buffer to the stack , fixes the issue partially. 

```
static int _hlua_http_msg_dup(struct http_msg *msg, lua_State *L, size_t offset, size_t len)
{
	struct htx *htx = htxbuf(&msg->chn->buf);
	struct htx_blk *blk;
	struct htx_ret htxret;
	luaL_Buffer b;
	int ret = 0;

	luaL_buffinit(L, &b);
	htxret = htx_find_offset(htx, offset);
	for (blk = htxret.blk, offset = htxret.ret; blk && len; blk = htx_get_next_blk(htx, blk)) {
		enum htx_blk_type type = htx_get_blk_type(blk);
		struct ist v;

		switch (type) {
			case HTX_BLK_UNUSED:
				break;

			case HTX_BLK_DATA:
				v = htx_get_blk_value(htx, blk);
				v = istadv(v, offset);
				if (v.len > len)
					v.len = len;

				luaL_addlstring(&b, v.ptr, v.len);
				ret += v.len;
				break;

			default:
				if (!ret) {
					/* Remove the empty string and push nil on the stack */
					lua_pop(L, 1);
					lua_pushnil(L);
				}
                                else {
                                        luaL_pushresult(&b); 
                                }
				goto end;
		}
		offset = 0;
	}

	luaL_pushresult(&b);

end:
	return ret;
}
```

### What is your configuration?

```haproxy
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
        

        lua-load /media/vishnu/Data/Work2/auth-gateway/haproxy.lua

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http



frontend gateway
  mode http
  bind 127.0.0.1:83
  filter lua.twofaassistant
  http-request lua.check_2fa_cookie
  http-request use-service lua.redirect_to_auth_server if { var(req.two_fa_invalid) -m bool }
  http-response lua.insert_2fa_cookie
  use_backend http_service_a

backend http_service_a
   mode http
   server s1 127.0.0.1:3000
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.5-dev10-f2b1b4d 2021/10/16 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Additional Information

1. HAProxy was built with Lua 5.3 on Ubuntu 20.04
2. When the issue is observed `FILTER.http_payload() `is called only once . But if I return a value 0 from `FILTER.http_payload()` , it will be called once again but same erratic behaviour will be observed on `HTTPMessage.body()` . Whenever this issue is observed `HTTPMessage.eom(http_msg) `is returning **true** .
3. If the return value of `HTTPMessage.body()` is a number, then it is always the last argument passed to `HTTPMessage.body()`
4.  Even when the issue is observed `HTTPMessage.prepend()` and `HTTPMessage.set()` are succeeding. I am able to view the prepended string on the browser. But `HTTPMessage.body()` will still manifest erratic behaviour even if called after calling  `HTTPMessage.set(string)`

**Comment by vishnu-prasad-r** [comment]
I found that when these errors occurred, there were exactly two HTX blocks in the HTX-BLOCKS buffer of the response channel.

First block was of type `HTX_BLK_DATA` and the second block was of type `HTX_BLK_EOT` .

When these errors don't occur, all blocks are of type `HTX_BLK_DATA` .

**Comment by capflam** [comment]
Indeed, you're right, there is an issue here and your patch only partially fixes it. When there is no payload, `nil` must be returned. For now, an empty string is returned. Here is a patch to fix both issues:
```diff
diff --git a/src/hlua.c b/src/hlua.c
index 6d9205938..fe22d6bb0 100644
--- a/src/hlua.c
+++ b/src/hlua.c
@@ -6338,20 +6338,24 @@ static int _hlua_http_msg_dup(struct http_msg *msg, lua_State *L, size_t offset,
                                break;
 
                        default:
-                               if (!ret) {
-                                       /* Remove the empty string and push nil on the stack */
-                                       lua_pop(L, 1);
-                                       lua_pushnil(L);
-                               }
+                               if (!ret)
+                                       goto no_data;
                                goto end;
                }
                offset = 0;
        }
 
-       luaL_pushresult(&b);
-
 end:
+       if (!ret && (htx->flags & HTX_FL_EOM))
+               goto no_data;
+       luaL_pushresult(&b);
        return ret;
+
+  no_data:
+       /* Remove the empty string and push nil on the stack */
+       lua_pop(L, 1);
+       lua_pushnil(L);
+       return 0;
 }
 
 /* Copies the string <str> to the HTTP message <msg> at the offset
```

If you agree, I can amend your patch.

**Comment by vishnu-prasad-r** [comment]
@capflam 
I agree with your observation. Please amend the patch.

**Comment by capflam** [comment]
Merged now. I forgot to link the issue in the commit (0af4bd7be).
