### ISSUE TITLE
SPOE async mode and threads

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#143]
Currently, "option async" in SPOE leads to a warning being emitted when threads are enabled. The reason is that this allows the other side to send the response on any connection, ignoring thread affinity. Now that threads are enabled by default, it would be nice to address this once for all.

There are 3 ways to do this:
   1) generating a distinct engine_id for each thread. Currently the engine_id is generated on startup so that it will differ between the old and new processes, but not between multiple processes of the same instance nor between threads of the same process. Simply having a per-thread array would work fine. Alternately the last bits of the uuid could be dedicated to the process number and thread number.
   2) implement a shared Rx queue per connection so that all messages are linked together there, and using a bit mask it's possible to indicate what thead IDs are still represented. Once each thread has consumed its messages, the Rx queue is released. It should not be very difficult to implement and could be useful to design well for other inter-stream communications (e.g. having compute threads pick the work from others, like for compression).
  3) implement a dispatch queue very similar to the accept queue so that incoming messages are queued into each destination's queue. While it requires less locking and lookups (only one lookup to match and deliver), and significantly reduces head-of-line bocking, it also requires per-destination buffering which may be a bit more painful to deal with. Or such buffers should be allocated by the sender but they will result in lots of cache lines bouncing around if it picks its own buffers for the target. Also it must absolutely be bounded so that a flood (or bug) in one stream doesn't cause tons of allocations to be performed.

For the short term, solution 1 above seems needed, at least to address the limitation when it comes to processes. Solution 2 could be nice to avoid memory copies hence sounds suitable to compression or any offloading in general. Solution 3 sounds better for small, low-latency messages for which a copy is always preferable over making others wait on a shared resource. SPOE async messages might fall into this category but should then be documented as such. Note that once solution 1 considers threads, solutions 2 and 3 will not be used. So some analysis must be done to determinee if there is more value in sending lots of small responses over a single connection which will locally dispatch or if it's better to send  them over multiple connections.

**Comment by capflam** [comment]
Just to mention that the solution 1 was implemented few months ago (commit b1bb1afa).

**Comment by capflam** [comment]
The SPOE was refactored in 3.1 and the async mode was removed. I'm closing.
