### ISSUE TITLE
Haproxy Globalization

### ISSUE THREAD

**Issue by lzb-libra** [haproxy/haproxy#1431]
### Your Feature Request

Can the haproxy dashboard be configured for internationalization, or how should i modify it.

### What are you trying to do?

Increase the nationalization function of haproxy`s dashboard page

### Output of `haproxy -vv`

```plain
haproxy -1.5.18
```

**Comment by wtarreau** [comment]
Not sure what dashboard page you're talking about, and in addition it's about an antique, unmaintained version.

**Comment by lzb-libra** [comment]
I used the yum package manager to download and install Haproxy. I can only install 1.5.18. The Dashboard page I said is as shown in the figure below. I found this code in the 2.4.7 source code. You output an HTML page to the browser. Yes, it is probably in line 3358 of the stats.c file. The number of lines is not necessarily accurate. The file I found by searching the "Statistics Report" globally looks like the code of the front page.[](url
![QQ截图20211027093210](https://user-images.githubusercontent.com/63389341/138985251-fb0c0485-b202-4e88-8820-0485e427acdb.png)
)

**Comment by wtarreau** [comment]
Ah, got it, that's what we call the "stats page". However it's now unclear to me what you want to see changed there for "internationalization".

Regarding 1.5.18, then I'm assuming you're probably running on a CentOS distro. But even on CentOS, version 1.8 is provided, so it might just be a matter of configuring yum to use up-to-date packages (I don't know how that's done, but I guess you can understand that the maintenance of a version emitted 7.5 years ago has come to an end).

**Comment by TimWolla** [comment]
> However it's now unclear to me what you want to see changed there for "internationalization".

I would assume that they want to have other languages available for the stats page (possibly selected based on the `accept-language` header).

**Comment by wtarreau** [comment]
I suspected this but this sounds fairly limited to me, which is why I was asking. I don't see us translating "frontend", "backend" nor "server" which are also config keywords. Quite a number of column title are already short or even abbreviated to avoid having too large a table. Health check status is a plain copy of the report sent to the logs and must not be translated. What is there left ? The legends ? We could imagine optionally preloading the header part from an external file, but that still feels quite limited to me.

**Comment by lzb-libra** [comment]
Okay, I get it. What you mean is that the internationalization you develop is a dispensable function for you and it is still a relatively difficult function to achieve. Then I have thought about it a lot, then am I? Can I realize multi-language support by myself by modifying the source code?

**Comment by wtarreau** [comment]
But we did not develop any internationalization! If you want to try something, sure, feel free to experiment by changing the code and see where you can go. But I aleady predict that it might be worse than today, as very often when certain terms are translated out of context.

**Comment by lzb-libra** [comment]
Okay, I get it. Thank you very much.
