### ISSUE TITLE
cirrus-ci builds are broken

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1437]
### Detailed Description of the Problem

https://github.com/vtest/VTest/issues/29

### Expected Behavior

let us wait couple of days, if not fixed, we'll stick to certain vtest commit

### Steps to Reproduce the Behavior

cirrus-ci builds

### What is your configuration?

```haproxy
no
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by TimWolla** [comment]
This is not a build failure in VTest, this is in HAProxy itself.

**Comment by chipitsine** [comment]
fixed in https://github.com/haproxy/haproxy/commit/5592c7b455dc89584e1241f3952ca5e5c9fbf687
