### ISSUE TITLE
Regarding the use of Haproxy for load balancing of Memcached

### ISSUE THREAD

**Issue by lzb-libra** [haproxy/haproxy#1440]
### Detailed Description of the Problem

Hello, developers, because our company's project uses Memcached as a back-end cache. Two servers are used to build a Memcached cache that is the master and slave. We use com.dango.Memcached as the client. For linking, a problem with this client is that if one of the servers is down, it will not mark or remove the down server, causing each request to request the down server, which will cause our service to change Slow, so I thought of using load balancing, so I used the Haproxy software. After using this software, it did solve the problems I encountered, but I encountered other problems during the test. First, I use the client to directly connect to memcached. There is no problem when I get the value, but when I use Haproxy as a load balancer, there will be a problem when I get the value. If the key currently obtained does not exist in Memcached, the connection is normal. There will be no errors on the client side, but when you use Haproxy to obtain it, there will be a question. This client has a problem with java.nio.BufferUnderflowException. Do you know the reason for this?

### Expected Behavior

There should be no abnormal information like the client is directly connected to Memcached

### Steps to Reproduce the Behavior

1. Use com.dango.memcached as the client linking memcached.

2. Get the value of a key that does not exist in the cache.

3. The client directly configures the address of memcached, and obtains the value through the key, the program will not be abnormal, and the key does not exist in the cache.

4. The client configures the port that haproxy listens to, uses haproxy to perform load balancing, and then obtains the value through the key, the program is abnormal, and the key does not exist in the cache.

### What is your configuration?

```haproxy
global
    log         127.0.0.1 local0 info

    chroot      varb/haproxy
    pidfile     ar/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket arb/haproxy/stats

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option                  http-server-close
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

listen Memcached_simGroup_22813
    bind *:22813
    mode tcp
    option tcplog
    balance roundrobin
    server cache1 ***.***.***.***:11813 check inter 2000 rise 2 fall 3
    server cache2 ***.***.***.***:11813 check inter 2000 rise 2 fall 3

listen Dashboard
    stats enable
    bind *:18080
    mode http
    option httplog
    log global
    maxconn 10
    stats refresh 20s
    stats uri /admin
    stats realm haproxy
    stats auth admin:admin
    stats hide-version
    stats admin if TRUE
```

### Output of `haproxy -vv`

```plain
haproxy -2.5
```

**Comment by lukastribus** [comment]
This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.
 
Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
