### ISSUE TITLE
QUIC code reports

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1445]
### Tool Name and Version

gcc 11

### Code Report

```plain
src/quic_sock.c: In function ‘quic_sock_fd_iocb’:
src/quic_sock.c:181:50: warning: potential null pointer dereference [-Wnull-dereference]
  181 |         struct quic_transport_params *params = &l->bind_conf->quic_params;
      |                                                 ~^~~~~~~~~~~
In file included from include/haproxy/connection.h:28,
                 from src/quic_sock.c:18:
include/haproxy/buf.h:64:17: warning: potential null pointer dereference [-Wnull-dereference]
   64 |         return b->size;
      |                ~^~~~~~
include/haproxy/buf.h:78:17: warning: potential null pointer dereference [-Wnull-dereference]
   78 |         return b->data;
      |                ~^~~~~~
include/haproxy/buf.h:160:17: warning: potential null pointer dereference [-Wnull-dereference]
  160 |         return b->head;
      |                ~^~~~~~
...



src/mux_quic.c: In function ‘qc_io_cb’:
src/mux_quic.c:1350:13: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
 1350 |         int ret = 0;
      |             ^~~

....

src/h3.c: In function ‘h3_decode_qcs’:
src/h3.c:145:25: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  145 |                         struct buffer htx_buf = BUF_NULL;
      |                         ^~~~~~
src/h3.c:138:36: warning: variable ‘scheme’ set but not used [-Wunused-but-set-variable]
  138 |                         struct ist scheme = IST_NULL, authority = IST_NULL;
      |                                    ^~~~~~
src/h3.c:173:35: warning: potential null pointer dereference [-Wnull-dereference]
  173 |                         sl->flags |= HTX_SL_F_BODYLESS;
      |                                   ^~
src/h3.c:173:35: warning: potential null pointer dereference [-Wnull-dereference]
  173 |                         sl->flags |= HTX_SL_F_BODYLESS;
src/h3.c:174:43: warning: potential null pointer dereference [-Wnull-dereference]
  174 |                         sl->info.req.meth = find_http_meth(meth.ptr, meth.len);
      |                         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...


src/qpack-enc.c: In function ‘qpack_encode_field_section_line’:
src/qpack-enc.c:126:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  126 |         char qpack_field_section[] = {
      |         ^~~~

...

```
```


### Additional Information

_No response_

### Output of `haproxy -vv`

```plain
no
```

**Comment by a-denoyelle** [comment]
Thanks for the report. Fred and I will look into it. In any case, it could be useful now to have a build with USE_QUIC=1 on the github CI.

**Comment by chipitsine** [comment]
CI build is something that I'll send patches today or tomorrow (depending on how busy am I).

I also noticed couple of tests are not stable on qiictls. That may require more investigation

**Comment by TimWolla** [comment]
@a-denoyelle FYI: The `__maybe_unused` macro maybe would have allowed for a slightly cleaner fix here, as it does not require commenting out some code.

**Comment by a-denoyelle** [comment]
> @a-denoyelle FYI: The `__maybe_unused` macro maybe would have allowed for a slightly cleaner fix here, as it does not require commenting out some code.

You're right. This code is under heavy change, so that's why I allow myself a dirty fix, as the return value will be reused later.

**Comment by a-denoyelle** [comment]
@chipitsine we should have cover everything now.

**Comment by ghost** [comment]
> ### Tool Name and Version
> gcc 11
> 
> ### Code Report
> ```
> src/quic_sock.c: In function ‘quic_sock_fd_iocb’:
> src/quic_sock.c:181:50: warning: potential null pointer dereference [-Wnull-dereference]
>   181 |         struct quic_transport_params *params = &l->bind_conf->quic_params;
>       |                                                 ~^~~~~~~~~~~
> In file included from include/haproxy/connection.h:28,
>                  from src/quic_sock.c:18:
> include/haproxy/buf.h:64:17: warning: potential null pointer dereference [-Wnull-dereference]
>    64 |         return b->size;
>       |                ~^~~~~~
> include/haproxy/buf.h:78:17: warning: potential null pointer dereference [-Wnull-dereference]
>    78 |         return b->data;
>       |                ~^~~~~~
> include/haproxy/buf.h:160:17: warning: potential null pointer dereference [-Wnull-dereference]
>   160 |         return b->head;
>       |                ~^~~~~~
> ...
> 
> 
> 
> src/mux_quic.c: In function ‘qc_io_cb’:
> src/mux_quic.c:1350:13: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
>  1350 |         int ret = 0;
>       |             ^~~
> 
> ....
> 
> src/h3.c: In function ‘h3_decode_qcs’:
> src/h3.c:145:25: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
>   145 |                         struct buffer htx_buf = BUF_NULL;
>       |                         ^~~~~~
> src/h3.c:138:36: warning: variable ‘scheme’ set but not used [-Wunused-but-set-variable]
>   138 |                         struct ist scheme = IST_NULL, authority = IST_NULL;
>       |                                    ^~~~~~
> src/h3.c:173:35: warning: potential null pointer dereference [-Wnull-dereference]
>   173 |                         sl->flags |= HTX_SL_F_BODYLESS;
>       |                                   ^~
> src/h3.c:173:35: warning: potential null pointer dereference [-Wnull-dereference]
>   173 |                         sl->flags |= HTX_SL_F_BODYLESS;
> src/h3.c:174:43: warning: potential null pointer dereference [-Wnull-dereference]
>   174 |                         sl->info.req.meth = find_http_meth(meth.ptr, meth.len);
>       |                         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ...
> 
> 
> src/qpack-enc.c: In function ‘qpack_encode_field_section_line’:
> src/qpack-enc.c:126:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
>   126 |         char qpack_field_section[] = {
>       |         ^~~~
> 
> ...
> ```
> 
> ```
> 
> 
> ### Additional Information
> 
> _No response_
> 
> ### Output of `haproxy -vv`
> 
> ```plain
> no
> ```

How to test the Haproxy http3 protocol, I have successfully compiled haproxy 2.5 and 2.6-dev1 through quictls/openssl, but found that I will not configure the use of quic, and there is no UDP port development for background port monitoring.
```
COMMAND   PID    USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
haproxy 12409 haproxy    3u  IPv4 15459889      0t0  TCP *:https (LISTEN)
haproxy 12409 haproxy    5u  IPv4 15459891      0t0  TCP *:https (LISTEN)
```

```
HAProxy version 2.5.0 2021/11/23 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
Running on: Linux 4.14.129-bbrplus #1 SMP Mon Jun 24 16:51:05 UTC 2019 x86_64
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_STATIC_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_QUIC=1
  DEBUG   = 

Feature list : -EPOLL -KQUEUE -NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -THREAD -BACKTRACE +STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL -LUA -ACCEPT4 -CLOSEFROM +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -PROCCTL -THREAD_DUMP -EVPORTS -OT +QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 3.0.1+quic 14 Dec 2021
Running on OpenSSL version : OpenSSL 3.0.1+quic 14 Dec 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built without multi-threading support (USE_THREAD not set).
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): no
Built with gcc compiler version 6.3.0 20170516

Available polling systems :
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 2 (2 usable), will use poll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            quic : mode=HTTP       side=FE|BE     mux=QUIC     flags=HTX|CLEAN_ABRT|HOL_RISK
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```
