### ISSUE TITLE
add new output for map_* to provide the matching key

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#1446]
_Originally posted by @jaroslawr in https://github.com/haproxy/haproxy/issues/1408#issuecomment-935522997_

The goal would be to have a set of `map_*_key` converters that return the key itself instead of a value. It can be convenient when matching prefixes, suffixes, sub-strings, or network addresses for example. Right now one has to write a map with the two columns identical for this. More info in the thread above including a design proposal.

**Comment by Darlelet** [comment]
The above solution has been implemented and is now available starting with 3.0, I guess we can close the issue

**Comment by zino7825** [comment]
@Darlelet Wow!! I didn't know that. thx!!
Please make backport to 2.8.x too!!
