### ISSUE TITLE
HAProxy returns 500. whenever txn:done has txn:reply body size greater than 15589. With core.register_action http-res

### ISSUE THREAD

**Issue by adnanmomin** [haproxy/haproxy#1447]
### Detailed Description of the Problem

I want HAProxy to follow redirects returned by backend servers instead of returning them to client.
For this I had registered an action on http-response like `http-response lua.handle_redirect if { status eq 301 302 }`.

Lua code looks as below
> local function process(txn)
> >--     Logic to follow backend redirects and get final response in a variable `r` goes here. Then below code runs.
> > 
> >     local reply = txn:reply()
> >     reply:set_status(r.status_code, r.reason)
> >     for k, v in pairs(r.headers) do
> >         reply:add_header(k, v)
> >     end
> >     reply:set_body(""..r.content)
> >     txn:done(reply)
> end
> 
> core.register_action("handle_redirect", {"http-res"}, process)

From the above code 

> if `string.len(r.content)` is less than or equal to `15589`, `txn.done(reply)` works correctly and HAProxy returns the correct response.

> If `string.len(r.content)` greater than `15589`, `txn.done(reply)` breaks(doesn't works correctly) and HAProxy returns 500 response status to client.

### Expected Behavior

Expected behavior
`txn.done(reply)` should work correctly even if `string.len(r.content)` greater than `15589` and HAProxy should return correct response.

### Steps to Reproduce the Behavior

The response body size of the redirect followed must be grater than 15589 characters.

### Do you have any idea what may have caused this?

No

### Do you have an idea how to solve the issue?

No

### What is your configuration?

```haproxy
global
        maxconn 30000
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
        lua-load /etc/haproxy/lua/handle_redirect.lua

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 900000ms
        timeout client  900000ms
        timeout server  900000ms
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

listen redirect_handler
        bind *:7425

        mode http

        http-request replace-uri /(.*) /\1
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
        http-request set-header Host some.host.name

        http-response lua.handle_redirect if { status eq 301 302 }

        server api-gateway some.host.name:443 ssl verify none sni str(some.host.name)
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.4-1ppa1~focal 2021/09/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.4.html
Running on: Linux 5.11.0-1020-aws #21~20.04.2-Ubuntu SMP Fri Oct 1 13:03:59 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-t3psiR/haproxy-2.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
From /var/log/haproxy.log
Nov  8 10:05:16 ip-172-31-8-218 haproxy[1796]: Following backend redirect
Nov  8 10:05:26 ip-172-31-8-218 haproxy[1796]: BODY LEN :: 42032
Nov  8 10:05:26 ip-172-31-8-218 haproxy[1796]: my.public.i.p:2877 [08/Nov/2021:10:05:15.874] redirect_handler redirect_handler/backend-server 0/0/5/-1/10494 500 740 - - PH-- 1/1/0/0/0 0/0 "GET /dev/return/redirect-status HTTP/1.1"

From journalctl -xe
Nov 08 10:08:06 ip-172-31-8-218 haproxy[2006]: [info] 311/100806 (2006) : Following backend redirect
Nov 08 10:08:11 ip-172-31-8-218 haproxy[2006]: [info] 311/100811 (2006) : BODY LEN :: 42032
```

### Additional Information

OS Details:

> NAME="Ubuntu"
> VERSION="20.04.2 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian

Lua Details:
> Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio

**Comment by capflam** [comment]
Well, I must admit it is not mentioned in the lua-api documentation. Thus you cannot make it up. But the reply size is limited to one internal buffer. Size of these buffers is set to 16k by default and may be tuned via `tune.bufsize`. Note that there is also an overhead because of the internal HTTP representation. Unfortunately, for now there is no trivial way to be sure the reply will fit in a buffer.

I'm tagging it as "work as designed" but I'm not closing the issue as a reminder. I must update the lua-api documentation.

**Comment by adnanmomin** [comment]
@capflam thanks for the explanation.
Please suggest how to get this done.
First approach coming to my mind is, I'll need to stream response from Lua to HAProxy.

**Comment by capflam** [comment]
It is not possible to stream data from a Lua action. It is a design limitation. The same than for error files.  The response is forged, returned to the client and the connection is closed. Only lua services are able to stream data. But it is not a suitable solution in your case. It is possible to write a lua filter. However, this feature was introduced in the 2.5 and is still experimental.

**Comment by adnanmomin** [comment]
@capflam thanks.

**Comment by adnanmomin** [comment]
@capflam any help on how to achieve this [Unable to implement HAProxy as Forward Proxy for HTTPS](https://stackoverflow.com/q/68321275) using HAProxy.

I think you have already done something like it.
Seen you portfolio on [https://capflam.org/](https://capflam.org/).

**Comment by lukastribus** [comment]
Haproxy is not a proper forward proxy server and it likely never will be. You are trying to use the wrong tool for the job, and you will implement fix after fix and will probably never be done, as bandaid solution tend to break with changes/upgrades (both on the haproxy as well as on the browser and server side).

You may want to get back to the drawing board.

**Comment by adnanmomin** [comment]
@lukastribus thanks for your comment.
I'll review my approach.
