### ISSUE TITLE
Documentation typo (ssl_fc_unique_id)

### ISSUE THREAD

**Issue by joellimberg** [haproxy/haproxy#1449]
### Detailed Description of the Problem

In `doc/configuration.txt`, the description for `ssl_fc_unique_id` includes this:

> The unique id can be encoded to base64 using the converter: "**ssl_bc_unique_id**,base64".

It should be `ssl_fc_unique_id,base64` instead.

**Comment by capflam** [comment]
Fixed. Thanks !
