### ISSUE TITLE
[Help]How to run all of the test function?

### ISSUE THREAD

**Issue by GuardianRain** [haproxy/haproxy#1459]
### Tool Name and Version

haproxy 2.0.24

### Code Report

```plain
Hello,I want to run all of the test function, but I have no C knowledge, would you like to give me a guidance about how to do this? Thank you vary much.
```

### Output of `haproxy -vv`

```plain
haproxy 2.0.24
```

**Comment by TimWolla** [comment]
Running the reg-tests is explained in the README within the reg-tests directory: https://github.com/haproxy/haproxy/tree/master/reg-tests. You can also take a look at the VTest workflow in GitHub Actions: https://github.com/haproxy/haproxy/blob/master/.github/workflows/vtest.yml

However: This issue tracker is meant for tracking bugs and features, not to seek help. Please use the forum or the mailing list if you have a follow-up question. I recommend using the mailing list for this type of technical question.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org

**Comment by GuardianRain** [comment]
> Running the reg-tests is explained in the README within the reg-tests directory: https://github.com/haproxy/haproxy/tree/master/reg-tests. You can also take a look at the VTest workflow in GitHub Actions: https://github.com/haproxy/haproxy/blob/master/.github/workflows/vtest.yml
> 
> However: This issue tracker is meant for tracking bugs and features, not to seek help. Please use the forum or the mailing list if you have a follow-up question. I recommend using the mailing list for this type of technical question.
> 
> The forum is at: https://discourse.haproxy.org/
> 
> * The mailing list (no need to subscribe) is: [haproxy@formilux.org](mailto:haproxy@formilux.org)
> * Subscribe to the list: [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)
> * Unsubscribe from the list: [haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)

Okay, thanks a lot, I will use the mailing list to seek help next time. Sorry about this time of trouble!
