### ISSUE TITLE
Zero chunk appended to HEAD response

### ISSUE THREAD

**Issue by minh-wdc** [haproxy/haproxy#146]
## Output of `haproxy -vv` and `uname -a`

I am using HAProxy 2.0.1 via the docker
https://github.com/docker-library/haproxy/blob/8e656d4403154a7086fb63bd92382c9f8d32af9b/2.0/Dockerfile

## What's the configuration?

```
defaults
    log     global
    mode    http
    option  httplog

frontend haproxynode
    bind *:8080
    mode http
    default_backend backendnodes

backend backendnodes
    server node1 127.0.0.1:8000 check

```

## Steps to reproduce the behavior

1. Run the python http server
```
python simple_server.py
```

simple_server.py
```
import time
import BaseHTTPServer


HOST_NAME = ""
PORT_NUMBER = 8000


class MyHandler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_HEAD(s):
        s.protocol_version = "HTTP/1.1"
        s.send_response(200)
        s.send_header("transfer-encoding", "chunked")
        s.end_headers()
        return

if __name__ == '__main__':
    server_class = BaseHTTPServer.HTTPServer
    httpd = server_class((HOST_NAME, PORT_NUMBER), MyHandler)
    print time.asctime(), "Server Starts - %s:%s" % (HOST_NAME, PORT_NUMBER)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()
    print time.asctime(), "Server Stops - %s:%s" % (HOST_NAME, PORT_NUMBER)

```

2. Start a docker container using the config file
```
docker run -d --network="host" --name my-running-haproxy -v ~/haproxy:/usr/local/etc/haproxy:ro haproxy:2.0.1
```
3. use netcat to send a HEAD request to the server

```
$ nc localhost 8080
HEAD / HTTP/1.1
<enter>
<enter>
```

## Actual behavior

HAProxy forwards the response, but adds a zero chunk to the message body.

```
HTTP/1.1 200 OK
server: BaseHTTP/0.3 Python/2.7.12
date: Mon, 01 Jul 2019 13:25:47 GMT
transfer-encoding: chunked

0
```

## Expected behavior

The response should not contain a message body as per https://tools.ietf.org/html/rfc2616#section-9.4.

```
HTTP/1.1 200 OK
server: BaseHTTP/0.3 Python/2.7.12
date: Mon, 01 Jul 2019 13:25:47 GMT
transfer-encoding: chunked

```

This behaviour was correct in HAProxy 1.9.8
```
docker run -d --network="host" --name my-running-haproxy-1.9.8 -v ~/haproxy:/usr/local/etc/haproxy:ro haproxy:1.9.8
```

## Do you have any idea what may have caused this?
No, I am not familiar with the codebase.

## Do you have an idea how to solve the issue?
No, I am not familiar with the codebase.

**Comment by capflam** [comment]
I confirm the bug. In fact, it also affect HAProxy 1.9 when the HTX mode is enabled. I pushed a fix. Thanks.

**Comment by capflam** [comment]
Pushed now to 2.0 and 1.9.

**Comment by minh-wdc** [comment]
Thanks!
