### ISSUE TITLE
Stats Page Dark Mode not fully styled

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1461]
### Detailed Description of the Problem

Not all colors on the stats page appear to be properly adjusted for dark mode. Making parts of it unreadable:

![scrot_2021_11_23_17_36_12](https://user-images.githubusercontent.com/209270/143065705-e0ab15be-b4d0-4b5f-921a-f2d41fcab86e.png)

### Expected Behavior

I expect that I am able to read everything.

### Steps to Reproduce the Behavior

1. Open https://stats.haproxy.org/ with dark mode enabled.

### What is your configuration?

```haproxy
n/a
```

### Output of `haproxy -vv`

```plain
2.6-dev0-27f88a-1 on haproxy.org
```

**Comment by wtarreau** [comment]
That's ugly indeed. I think these are only the unchecked ones, probably that the gray should be turned to dark gray, but I don't know much, I'm really not used to such dark themes nor to what styles people expect in such environments.

**Comment by hujiko** [comment]
I so far did not work with sockets and stats before, but from my naive thinking, I would expect a socket row to look similar to a server that is enabled, but does not have a health check defined.

Based on that idea, I generated this patch.

I don't have a strong opinion on the color to be used and I am open for changes.
But I would definetely say, that my patch would make it a lot better than it currently is.

Therefore I would suggest to merge this patch until someone comes around with a better idea.

[0001-MINOR-stats-Add-dark-mode-support-for-socket-rows.patch.txt](https://github.com/haproxy/haproxy/files/8206424/0001-MINOR-stats-Add-dark-mode-support-for-socket-rows.patch.txt)

Stats about sockets would then look like this:
![HAproxy stats page](https://user-images.githubusercontent.com/946442/157242499-0769bbf4-59cb-4828-ae4b-b35afce6c44c.png)

**Comment by cipriancraciun** [comment]
I think it looks OK.

It would be nice to have it backported to 2.5.x.

----

BTW, @hujiko, when you test the layout / theme, do you have a config file (or equivalent) that generates all kinds of situations?

(If I were to take a stab at the CSS, it would be nice to have something to practice on.)

**Comment by hujiko** [comment]
> BTW, @hujiko, when you test the layout / theme, do you have a config file (or equivalent) that generates all kinds of situations?

Actually no.
What I did:
I saved the HTML from https://stats.haproxy.org into a local file.
Then I was investigating the CSS and checked for the attributed assigned to the socket row.
As this is `.socket`, it seems quite explicit and unique to me.

I then checked the CSS block in the `<head>` and saw, that for `.socket` there is no dark-mode overwrite in the CSS.
I added that locally and then opened the HTML page in my browser to see how it looks.

You don't even need a running HAProxy instance for that, as once the stats HTML is generated, no server connection is needed any more. (No JS, CSS, images, API dependencies)

**Comment by cipriancraciun** [comment]
> I saved the HTML from https://stats.haproxy.org/ into a local file.

I thought about a similar trick, however that doesn't "exercise" various states a particular server might be in.  I hoped there is a way to generate "fake" HTML dashboards for the purpose of styling, etc.

**Comment by wtarreau** [comment]
This is perfect, I've just merged it, thank you both! I'll backport it to 2.5 soon.
Regarding the way to "fake" an HTML output, the best way is to declare a stats socket in an empty (or existing) config. It remains limited of course but that's better than nothing. If you enable "stats admin if TRUE" you can change some servers states and that might help. But some states are very hard to reproduce and observe, namely the transition from down to up for example.

**Comment by wtarreau** [comment]
For the record it's commit a690b73fb in 2.6.

**Comment by wtarreau** [comment]
It's in 2.5 as well now, so we can close this issue. Thanks everyone!
