### ISSUE TITLE
building haproxy 2.5.0 fails with event ports backend

### ISSUE THREAD

**Issue by hadfl** [haproxy/haproxy#1467]
### Detailed Description of the Problem

```
src/ev_evports.c:254:28: error: 'FD_UPDT_DEAD' undeclared (first use in this function); did you mean 'FD_UPDT_DONE'?
  254 |                 if (ret == FD_UPDT_DEAD)
      |                            ^~~~~~~~~~~~
```

### Expected Behavior

`haproxy` to build successfully

### Steps to Reproduce the Behavior

build `haproxy` on an illumos/Solaris based OS.

### Do you have any idea what may have caused this?

https://github.com/haproxy/haproxy/commit/b1f29bc6252ffa6b43e2e210c4852dd9c3a1b1eb removed the `dead_fd` counter and therefore the `FD_UPDT_DEAD` flag.

it's been originally introduced w/ https://github.com/haproxy/haproxy/commit/200bd50b73f8e0e3f27e83361dc456a69747a2b8

### What is your configuration?

```haproxy
`SunOS nemesis 5.11 omnios-master-72433da6283 i86pc i386 i86pc`
```

### Output of `haproxy -vv`

```plain
build issue
```

**Comment by wtarreau** [comment]
Hmm sorry for this one. Could you please try to delete these 2 lines (the 'if' condition and the 'continue' statement) ? Such FDs ought to be caught by the FD_UPDT_MIGRATED condition. Not sure how I missed evports here :-/

**Comment by hadfl** [comment]
thanks for your feedback and clarification. it's indeed how we fixed the build locally. however i was unsure whether it's the correct approach or if the `dead_fd` counter needs to be re-introduced.

are you going to get the fix in or do you want me to open a PR?

**Comment by wtarreau** [comment]
I'll fix it, thank you very much for confirming!

**Comment by hadfl** [comment]
Thank you!

**Comment by wtarreau** [comment]
Now fixed in mainline, thank you!
