### ISSUE TITLE
error-log-format: ssl_fc_sni always empty

### ISSUE THREAD

**Issue by lukastribus** [haproxy/haproxy#1484]
### Detailed Description of the Problem

When using error-log-format with %[ssl_fc_sni], we never actually return a SNI value.

### Expected Behavior

Return SNI value.

### Steps to Reproduce the Behavior

1. use error-log-format with ssl_fc_sni (as per the documentation)
2. trigger a SSL handshake failure (for example with mismatching SSL versions, ciphers or SNI with strict-sni)

### Do you have any idea what may have caused this?

Maybe when triggering an handshake error the SNI value is already destroyed or not properly initialized.

### Do you have an idea how to solve the issue?

If this is fixable in the code: OK; if not, we should document this limitation and remove `ssl_fc_sni` from the `error-log-format` example.

### What is your configuration?

```haproxy
global
  maxconn 100
  log 10.0.0.4 syslog debug
  chroot /tmp/

defaults
  mode http
  timeout connect 10s
  timeout client 60s
  timeout server 60s
  timeout http-request 5s
  timeout http-keep-alive 2s
  timeout tunnel 10s
  option httplog
  log global
  log-format %[ssl_fc_sni]

frontend my-https-frontend
  bind :443 ssl ssl-min-ver SSLv3 ssl-max-ver TLSv1.0 crt /mycert.pem
  error-log-format "%ci:%cp [%tr] %ft %ac/%fc %[fc_err] %[ssl_fc_err,hex]/%[ssl_c_err]/%[ssl_c_ca_err]/%[ssl_fc_is_resumed] %[ssl_fc_sni]/%sslv/%sslc"
  option httpslog
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.0-26f4e1-16 2021/12/03 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
Running on: Linux 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

### Additional Information

Initially reported at https://discourse.haproxy.org/t/logging-server-name-on-failed-ssl-handshakes/7180/5

**Comment by wtarreau** [comment]
Hi Lukas,

does this only happen with SSL errors or also with other errors (e.g. bad request) ? What I'm suspecting is that if it happens on SSL error, once the SSL context is in error we cannot use it anymore to retrieve anything, including the SNI. In this case maybe the only reasonable option left could indeed be to put a warning in the doc indicating that the various SSL sample fetches are only available when the SSL handshake completes.

**Comment by rlebreton** [comment]
I had a look at that too and I think I found an explanation to why this fetch does not work in some cases. For the short explanation, this fetch does not seem to work when the handshake failure is actually a ClientHello error (as in not a verify error but an error related to other parts of the client hello).

The ssl_fc_sni sample fetch uses OpenSSL's SSL_get_servername function which basically returns the 'hostname' part of the ssl_ssession structure. This hostname field if filled after the servername extension is processed through a 'user' defined callback (ssl_sock_switchctx_err_cbk in our case). But this servername callback will only be called after the clienthello callback is called (ssl_sock_switchctx_cbk in haproxy) (see 'man SSL_get_servername' for more info).
In our case the actual servername processing is done directly in the clienthello callback so in case of sni mismatch the clienthello callback raises an error which prevents the servername callback from being called (and the hostname field of the OpenSSL structure from being filled).

The only solution I see to this problem is to store ourselves the servername when we find it but we probably don't want to do this by default and it would require some new capture-like option.

**Comment by wtarreau** [comment]
Thanks for the analysis. I'm not convinced either by the benefits of capturing this at this point because this would only cover for issues that happen late in the client hello processing, but not those which happen earlier (before openssl extracts it). But if there's an elegant way to do this and it's considered useful, why not.

**Comment by lukastribus** [comment]
The use case of the user on discourse is to monitor SNI's of failed handshakes to understand missing certificates in a strict-sni configuration. I could also see how this would be useful in cipher/TLS version mismatches.

**Comment by wtarreau** [comment]
Yes indeed this makes sense to figure which line of a crtlist is causing the trouble. @rlebreton I'm wondering if we couldn't retrieve the info from the clienthello callback and re-inject it into openssl using SSL_set_servername() or something like this, and hope that it will be pre-filled even if the handshake doesn't complete.

**Comment by wtarreau** [comment]
Oh I forgot to say, yes, that's ugly.

**Comment by rlebreton** [comment]
There's no proper way to set the servername/hostname of the client in the SSL context from the server-side. The only APIs that exist either operate on the SSL_SESSION only (SSL_SESSION_set1_hostname) which would never work for TLSv1.3 seeing how SSL_get_servername is implemented, or are highly discouraged by the documentation as well as comments in the OpenSSL code (SSL_set_tlsext_host_name that should only be called from the client side).

I chose to use the ex_data mechanism instead, which enables to store user data in a SSL structure. A patch in currently being reviewed. It consists in storing the SNI ourselves when we know that the handshake will not succeed and to fallback to using this ex_data stored data in the ssl_fc_sni implementation.
