### ISSUE TITLE
double free issue when using crt directive with default-server

### ISSUE THREAD

**Issue by Mo3m3n** [haproxy/haproxy#1488]
### Detailed Description of the Problem

A double free issue happens when validating (haproxy -c ) the provided configuration file
```
 $ haproxy -c -f haproxy.cfg
Configuration file is valid           
free(): double free detected in tcache 2
[1]    49389 abort (core dumped)  haproxy -c -f haproxy.cfg

```

### Expected Behavior
configuration valid with 0 exit code (success)

### Steps to Reproduce the Behavior

1. haproxy -c -f haproxy.cfg

### Do you have any idea what may have caused this?

The problem disappears when reducing backend servers to a single server.

### What is your configuration?

```haproxy
defaults
  mode http
  timeout connect 5000
  timeout client 70000
  timeout server 50000

frontend http
  bind 127.0.0.2:80
  default_backend test

backend test
  default-server ssl crt /tmp/cert.pem verify none
  server SRV_1 10.244.1.4:443
  server SRV_2 10.244.1.5:443
```

### Output of `haproxy -vv`

```plain
haproxy -vv
HAProxy version 2.4.7-b5e51a5 2021/10/04 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.7.html
Running on: Linux 5.10.75-1-lts #1 SMP Wed, 20 Oct 2021 11:02:09 +0000 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fwrapv
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =
```

### Additional Information

This also happens with current master(7ceae1189) on 2.4

**Comment by capflam** [comment]
Confirmed. The regression was introduced by the commit 0498fa40. @rlebreton any idea ?

**Comment by rlebreton** [comment]
Not yet but it does not seem too mean. I'll look into it asap.

**Comment by rlebreton** [comment]
It actually turns out that the commit that introduced the bug does not even work properly since a config like the following would not work :
backend test
  default-server ssl crt cert.pem verify none
  balance roundrobin
  server SRV_1 :12345 ssl verify required ca-file ca.crt
  server SRV_2 :12345

Since the two backends use the same SSL_CTX and not duplicates of the default SSL context, any new SSL configuration specified by each server will be applied to the same context, meaning that the second server's parameters will overwrite the first's.

The fastest way of solving the current issue would be to revert the buggy commit until a proper fix is ready.

**Comment by wlallemand** [comment]
@rlebreton I don't think that's a good idea to revert this since the commit is already a fix for another problem, it's better to fix the issue.

**Comment by rlebreton** [comment]
Fixing the issue would require to rework on the previous bug fix because currently the default-server mechanism does not work properly. It was all introduced a while back when ckch instances where adopted on the backend side.
In the short term I could prevent the double free from happening with a patch like the following one but the underlying bug would still be here :

```
diff --git a/src/server.c b/src/server.c
index 4f75dff5a..0a508a632 100644
--- a/src/server.c
+++ b/src/server.c
@@ -46,6 +46,7 @@
 #include <haproxy/time.h>
 #include <haproxy/tools.h>
 #include <haproxy/xxhash.h>
+#include <haproxy/openssl-compat.h>
 
 
 static void srv_update_status(struct server *s);
@@ -2060,6 +2061,8 @@ static void srv_ssl_settings_cpy(struct server *srv, struct server *src)
 
        srv->ssl_ctx.verify = src->ssl_ctx.verify;
 
+       if (src->ssl_ctx.ctx)
+               SSL_CTX_up_ref(src->ssl_ctx.ctx);
        srv->ssl_ctx.ctx = src->ssl_ctx.ctx;
 
        if (src->ssl_ctx.verify_host != NULL)
```

@wlallemand If you prefer this option I can give you a proper patch that prevents the crash and work on the bug later.

**Comment by wlallemand** [comment]
@rlebreton In my opinion both of the options are bad, since they are just hiding the problem, we must prioritize a real fix instead. So, yes, it's better to rework the previous bug fix.

**Comment by Mo3m3n** [comment]
server-ca is also impacted by this issue. I guess it was expected but I am mentioning it here since we have received a different bug [report](https://github.com/haproxytech/kubernetes-ingress/issues/409) about this one.

**Comment by wlallemand** [comment]
@Mo3m3n I fixed the issue in master, it must behave correctly now.

**Comment by Mo3m3n** [comment]
Thanks @wlallemand, tests with master are successful
Ingress Controller will be updated as soon as the fix will backported to 2.4

**Comment by wtarreau** [comment]
And backported to 2.4. Now closing, thank you both!

**Comment by wdauchy** [comment]
@wlallemand could you remind me what is supported with the runtime API? in haproxy 2.4 I think the following was working before:

```
    default-server verify none
    option httpchk
    http-check connect default
    http-check send meth GET uri /health ver HTTP/1.1 hdr host foo

    server srv3 10.112.51.139:8443 weight 1 ssl
    server srv0 10.112.48.9:8443 weight 1 ssl
    server srv2 10.112.58.82:8443 weight 1 ssl
    server srv1 10.112.54.206:8443 weight 1 ssl
    server-template srv 4-14 0.0.0.0:0 check disabled
```

When I try to enable a server from the server template list (out of maintenance, setting IP/port + `set server ssl on`), the health check traffic is in plain text, while the output of the `set server ssl` command says `server ssl setting updated`

I also tried with an existing server: `set server ssl off` for srv0 and then `on`, the health check traffic comes back in plain text.
I also tried to set it by default in default-server.

I will probably continue the investigation as I am almost sure this was working before.
