### ISSUE TITLE
Haproxy 2.2.19 is having issues returning objects from a remove CDN (2.2.18 works fine)

### ISSUE THREAD

**Issue by doradojl** [haproxy/haproxy#1489]
### Detailed Description of the Problem

After updating the HAProxy to version 2.2.19 we are experimenting issues download images and HAPRoxy is returning this error:
`jldorado.aveng.net/:1 GET https://jldorado.aveng.net/fonts/proximanova-regular-webfont.woff2 net::ERR_HTTP2_SERVER_REFUSED_STREAM
/img/icon-message-center.svg:1 GET https://jldorado.aveng.net/img/icon-message-center.svg net::ERR_HTTP2_SERVER_REFUSED_STREAM
Image (async)
attr @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
access @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
attr @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
$set @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
forEach @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$set @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
interpolateFnWatchAction @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
interpolateFnWatcher @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
watchGroupAction @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$digest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$apply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
done @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
completeRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
requestLoaded @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
load (async)
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
sendReq @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
serverRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
processQueue @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$digest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$apply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
done @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
completeRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
requestLoaded @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
load (async)
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
sendReq @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
serverRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
processQueue @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$digest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$apply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
bootstrapApply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
invoke @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
doBootstrap @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
bootstrap @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
angularInit @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
mightThrow @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
process @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
setTimeout (async)
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fire @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fireWith @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fire @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fire @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fireWith @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
ready @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
completed @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
/img/icon-star.png:1 GET https://jldorado.aveng.net/img/icon-star.png net::ERR_HTTP2_SERVER_REFUSED_STREAM
Image (async)
attr @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
access @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
attr @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
$set @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
forEach @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$set @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
interpolateFnWatchAction @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
interpolateFnWatcher @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
watchGroupAction @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$digest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$apply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
done @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
completeRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
requestLoaded @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
load (async)
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
sendReq @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
serverRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
processQueue @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$digest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$apply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
done @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
completeRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
requestLoaded @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
load (async)
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
sendReq @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
serverRequest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
processQueue @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$digest @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
$apply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
bootstrapApply @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
invoke @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
doBootstrap @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
bootstrap @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
angularInit @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:59
mightThrow @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
process @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
setTimeout (async)
(anonymous) @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fire @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fireWith @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fire @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fire @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
fireWith @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
ready @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
completed @ libs.a0a73ee066b1436220aa.js?a0a73ee066b1436220aa:54
/img/user-gray.svg:1 GET https://jldorado.aveng.net/img/user-gray.svg net::ERR_HTTP2_SERVER_REFUSED_STREAM`

If we reverted to version 2.2.18 it works fine again. 

### Expected Behavior

Have the same behavior than 2.2.18

### Steps to Reproduce the Behavior

1. We have an angular web ui with static assets in a CloudFront CDN in AWS
2. HAproxy is redirecting to the CDN depending on the path and the result of a map file. 
3. Also depending on the map it's redirecting to a backend API. 

### Do you have any idea what may have caused this?

It should be a change in the latest version related to h2. Even if we disable h2 in the CloudFront we are seeing the same behavior using HTTP 1.1

### Do you have an idea how to solve the issue?

Right now, not using the latest version. I tried to upgrade to 2.4 but we had the same strange behavior so probably something we have in the rest of the versions.

### What is your configuration?

```haproxy
global
  daemon
  master-worker
  nbproc 1
  nbthread 4
  cpu-map auto:1/1-4 0-3
  maxconn 100000
  stats socket /run/haproxy/admin.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
  stats timeout 30s
  ssl-dh-param-file /etc/haproxy/dhparam.pem
  ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  hard-stop-after 30s
  log /dev/log  local0 notice

resolvers mydns
  parse-resolv-conf
  resolve_retries       30
  timeout retry         4s
  hold valid           60s
  hold nx              10s

defaults
  option dontlognull
  log global
  option httplog
  log-format %ci\ -\ %{+Q}r\ %ST\ %U\ %{+Q}[capture.req.hdr(0)]\ %{+Q}[capture.req.hdr(1)]\ %{+Q}b\ %{+Q}s
  timeout connect 10s
  timeout client 5m
  timeout server 5m
  option http-keep-alive
  option persist
  option http-ignore-probes
  option clitcpka
  option srvtcpka
  option tcpka
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

frontend health-check
  mode http
  bind :5151
  http-request deny deny_status 200 if { path_beg /ping }

frontend http-requests
  mode http
  bind :80
  bind :443 ssl crt  /etc/haproxy/certs/star-av-ssl.pem alpn h2,http/1.1
  option forwardfor
  capture request header Referer len 200
  capture request header User-Agent len 200
  http-request redirect scheme https code 301 if !{ ssl_fc }

  acl agent_kinesis hdr(Host) -i us-east-1-agent-entrypoint.xxxx.xxxxx

  acl url_backend  path_beg     /mssp /api /login /saml2 /core

  use_backend kinesis-kinesis if agent_kinesis
  use_backend %[base,lower,regsub(\..*,,g)]-http if url_backend
  use_backend %[base,lower,regsub(\..*,,g),map_beg(/etc/haproxy/maps/cdn-domain2backend.map)]-http

frontend sensors
  mode tcp
  option tcplog
  log-format client_ip=\"%ci:%cp\"\ backend_name=\"%b\"\ server_ip=\"%si\"\ termination_state=\"%ts\"
  log /dev/log  local0 info
  option logasap
  bind :7100
  tcp-request inspect-delay 5s
  tcp-request content capture req.ssl_sni len 128
  use_backend %[req.ssl_sni,lower,regsub(\..*,,g)]-tcp

frontend stats
  bind :9000
  mode http
  stats enable
  stats hide-version
  stats uri /stats

backend kinesis-kinesis
  mode http
  option httpchk GET /
  default-server inter 10s fall 10 rise 1
  balance roundrobin
  server-template kinesis 3 kinesis.us-east-1.amazonaws.com ssl verify required ca-file /etc/ssl/certs/Amazon_Root_CA_1.pem sni str(kinesis.us-east-1.amazonaws.com) resolvers mydns init-addr none resolve-prefer ipv4

backend meta-http
  mode http
  http-request set-header Host usma-dev.xxxx.xxxxx.xxxxxx
  http-request set-path /usma-meta%[path]
  http-request set-path /usma-meta/index.html if { path_end -i / }
  balance roundrobin
  server-template meta 5 usma-dev.xxxx.xxxxx.xxxxxx ssl verify required ca-file /etc/ssl/certs/Amazon_Root_CA_1.pem sni str(usma-dev.xxxx.xxxxx.xxxxxx) resolvers mydns init-addr none resolve-prefer ipv4

backend legacy-http
  mode http
  http-request set-header Host usma-dev.xxxx.xxxxx.xxxxxx
  http-request set-path /usma-legacy%[path]
  http-request set-path /usma-legacy/index.html if { path_end -i / }
  balance roundrobin
  server-template legacy 5 usma-dev.xxxx.xxxxx.xxxxxx ssl verify required ca-file /etc/ssl/certs/Amazon_Root_CA_1.pem sni str(usma-dev.xxxx.xxxxx.xxxxxx) resolvers mydns init-addr none resolve-prefer ipv4

backend usmc-legacy-http
  mode http
  http-request set-header Host usma-dev.xxxx.xxxxx.xxxxxx
  http-request set-path /usmc-legacy%[path]
  http-request set-path /usmc-legacy/index.html if { path_end -i / }
  balance roundrobin
  server-template usmc-legacy 5 usma-dev.xxxx.xxxxx.xxxxxx ssl verify required ca-file /etc/ssl/certs/Amazon_Root_CA_1.pem sni str(usma-dev.xxxx.xxxxx.xxxxxx) resolvers mydns init-addr none resolve-prefer ipv4

backend usmc-meta-http
  mode http
  http-request set-header Host usma-dev.xxxx.xxxxx.xxxxxx
  http-request set-path /usmc-meta%[path]
  http-request set-path /usmc-meta/index.html if { path_end -i / }
  balance roundrobin
  server-template usmc-meta 5 usma-dev.xxxx.xxxxx.xxxxxx ssl verify required ca-file /etc/ssl/certs/Amazon_Root_CA_1.pem sni str(usma-dev.xxxx.xxxxx.xxxxxx) resolvers mydns init-addr none resolve-prefer ipv4

backend maintenance_ui-http
  mode http
  http-request set-header Host usma-dev.xxxx.xxxxx.xxxxxx
  http-request set-path /usma-meta/maintenance.css if { path_end -i .css }
  http-request set-path /usma-meta/assets/img/wrench.svg if { path_end -i .svg }
  http-request set-path /usma-meta/maintenance.html if { path_end -i / }
  balance roundrobin
  server-template maintenance 5 usma-dev.xxxx.xxxxx.xxxxxx ssl verify required ca-file /etc/ssl/certs/Amazon_Root_CA_1.pem sni str(usma-dev.xxxx.xxxxx.xxxxxx) resolvers mydns init-addr none resolve-prefer ipv4

backend backend1-tcp
    mode tcp
    server backend1-tcp 10.1.45.106

backend backend1-http
    mode http
    server backend1-http 10.1.45.106:443 ssl verify none
```

### Output of `haproxy -vv`

```plain
-Proxy version 2.2.19-1ppa1~bionic 2021/11/29 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.19.html
Running on: Linux 5.4.0-1059-aws #62~18.04.1-Ubuntu SMP Fri Oct 22 21:51:38 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-KqNtHw/haproxy-2.2.19=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

### Last Outputs and Backtraces

```plain
No crash
```

### Additional Information

a

**Comment by wtarreau** [comment]
This is interesting because there are only two commits in this range for H2:
- 697d12da1 BUG/MEDIUM: mux-h2: always process a pending shut read
- 5c6249f7a MINOR: mux-h2: perform a full cycle shutdown+drain on close

Do you think you could try to revert them to confirm it fixes the issue for you ? I can attach the patches if needed.

**Comment by doradojl** [comment]
Yes, of course, if you don't mind attaching the patches I can test them in our development environment.

**Comment by wtarreau** [comment]
Cool, here they are. They're theoretically independent on each other. Since they are the original patches from the tree, you have to apply them in reverse (`patch -Rp1 < 0001-....`). If you need to have them reversed because you integrate them to packages, and are not sure how to do that, just let me know and I'll reverse them for you.

[0002-MINOR-mux-h2-perform-a-full-cycle-shutdown-drain-on-.patch.txt](https://github.com/haproxy/haproxy/files/7761961/0002-MINOR-mux-h2-perform-a-full-cycle-shutdown-drain-on-.patch.txt)
[0001-BUG-MEDIUM-mux-h2-always-process-a-pending-shut-read.patch.txt](https://github.com/haproxy/haproxy/files/7761962/0001-BUG-MEDIUM-mux-h2-always-process-a-pending-shut-read.patch.txt)

**Comment by doradojl** [comment]
It should be something I'm doing wrong.

- I downloaded the repo
- I checkout to branch `gco v2.2.0`
- I reverted the 002 without any issue

But I cannot find the code for https://github.com/haproxy/haproxy/commit/697d12da1290ffb0fedc11cc8fd1be91ca8f748d

It could be possible I'm not in the correct branch?

**Comment by wtarreau** [comment]
You're just not at the correct tag (2.2.0). Please take the 2.2.19 tarball from http://www.haproxy.org/download/2.2/src/ and revert the two patches on top of it. If you prefer the git version, you can clone it from here: http://git.haproxy.org/git/haproxy-2.2.git/ and you'll be in the right branch with the latest maintenance fixes.

**Comment by doradojl** [comment]
I compiled the binary with these options
```
USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1  make TARGET=linux-glibc
```
to simulate the environment we have using Ubuntu 18.04 and after replacing the binary **we have exactly the same issue**

Reverting the binary to 2.2.18 start working well again.

**Comment by doradojl** [comment]
https://*****/fonts/proximanova-regular-webfont.woff2 net::ERR_HTTP2_SERVER_REFUSED_STREAM

**Comment by wtarreau** [comment]
OK then we're on the wrong track and it's the same issue Tim is facing with 2.4.9 on the backend side with the SNI in #1495, that is being propagated to the frontend. I cannot trivially backport the existing fixes from 2.4 to 2.2 right now, Instead please try to revert the attached patch (using patch -Rp1 on the tree), it was meant to fix SSL connection reuse when dealing with SNI under TLS 1.3, and it should do the trick.
[0003-BUG-MEDIUM-ssl-backend-TLS-resumption-with-sni-and-T.patch.txt](https://github.com/haproxy/haproxy/files/7769230/0003-BUG-MEDIUM-ssl-backend-TLS-resumption-with-sni-and-T.patch.txt)

**Comment by wtarreau** [comment]
@doradojl if you want I could backport the SNI-related patches to 2.2. If you build from Git you can pull it any time. If you prefer a tarball, please use the next nightly snapshot tomorrow.

**Comment by doradojl** [comment]
@wtarreau Sorry for the late response, I reverted the code and as you said the issue was fixed. So it looks like that change it's impacting the 2.2.19.

**Comment by wtarreau** [comment]
No problem, don't be sorry :-)  Thanks for your response, it indeed confirms it's the same issue. I have backported the missing fixes a week ago, if you want to give it a try, it's available here: http://www.haproxy.org/download/2.2/src/snapshot/
This could help us confirm that it's worth releasing 2.2.20 as-is.

**Comment by doradojl** [comment]
Tested, and it works smoothly. Thanks!!!

**Comment by wtarreau** [comment]
Excellent, many thanks! I feel more confident releasing with this. We'll first do a 2.4 and a 2.3, and likely a 2.2 the week after.

**Comment by doradojl** [comment]
Do we revert this in 2.4 too? We tried to migrate from 2.2. to 2.4 and we go back to 2.2 because we triplicate the number of RST sent by HAProxy to the NLB we have. Not sure if could be related to this issue.

**Comment by wtarreau** [comment]
The latest 2.4 snapshot also contains the fix. There's no theoretical reason a number of RST could be related, but if haproxy used to abort client connections while they were uploading, that could provoke RSTs to be sent. So you may want to give it a try (same URL as above, with 2.4 instead of 2.2).

**Comment by doradojl** [comment]
Thanks for the info. Really appreciate it :D

**Comment by wtarreau** [comment]
@doradojl for your info 2.2.20 was just released with that fix backported. I'm closing the issue now to keep the list clear, but do not hesitate to open a new one if you still face a problem.

**Comment by doradojl** [comment]
Thanks for your support!!
