### ISSUE TITLE
Fedora Rawhide: 'server be4/srv4' : could not resolve address 'localhost'.

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1500]
### Detailed Description of the Problem

https://gitlab.com/chipitsine/haproxy-ci-playground/-/jobs/1918868202

`'server be4/srv4' : could not resolve address 'localhost'.`

while we can replace 'localhost' with 127.0.0.1, I'm not sure that is appropriate fix here.
maybe someone will come with better fix

### Expected Behavior

to work

### Steps to Reproduce the Behavior

run VTest suite on Fedora Rawgide

https://gitlab.com/chipitsine/haproxy-ci-playground/-/jobs/1918868202

### What is your configuration?

```haproxy
no config
```

### Output of `haproxy -vv`

```plain
haproxy master built for VTest
```

**Comment by wtarreau** [comment]
Ilya, please always post the reproducer config in the issue itself. Linking to other ones or even other sites makes them 1) extremely painful to follow and comment on, and 2) impossible to track once these other links vanish. I didn't seem to have noticed anything wrong in your capture but maybe I'm missing something. Or probably they decided to break something as critical as local name resolution in fedora but then most services will have quite some trouble...

**Comment by chipitsine** [comment]
I've got your point on vanished links to external sources. thanks

**Comment by chipitsine** [comment]
Fedora Rawhide is green again: https://gitlab.com/chipitsine/haproxy-ci-playground/-/pipelines/439065085

(no visible reason)
