### ISSUE TITLE
Feature request: AWS gwlb support

### ISSUE THREAD

**Issue by JackSlateur** [haproxy/haproxy#1503]
### Your Feature Request

A while ago, amazon released a product called [Gateway Load balancer](https://aws.amazon.com/elasticloadbalancing/gateway-load-balancer/)
It is a special kind of load balancer that allows customer to send L3 traffic to a pool of instances, where further filtering or processing can happen

Many proprietary software like [F5](https://devcentral.f5.com/s/articles/BIGIP-integration-with-AWS-Gateway-Load-Balancer-Overview), [checkpoint](https://sc1.checkpoint.com/documents/IaaS/WebAdminGuides/EN/CP_CloudGuard_Network_for_AWS_Centralized_Gateway_Load_Balancer/Content/Topics-AWS-GWLB-VPC-DG/Introduction.htm) etc have some support for this

Under the hood, packets from the client are encapsulated inside [GENEVE](https://en.wikipedia.org/wiki/Generic_Network_Virtualization_Encapsulation), with specific per-packet TLVs to identify the source tenant, so per-packet tracking must be done

A dummy example that does filtering exists [here](https://www.sentiatechblog.com/geneveproxy-an-aws-gateway-load-balancer-reference-application), written in Python

### What are you trying to do?

I would like to use Haproxy as a TCP reverse proxy, behind an AWS GWLB setup

Could this feature be part of Haproxy's roadmap ?

Best regards,

**Comment by wtarreau** [comment]
Thanks for notifying us about this feature, I didn't know that AWS supported GENEVE.

Please note, however, that this is a packet-level tunnel, it has nothing to do with a proxy which deals with connections. The packets are processed by the operating system which reassembles them into connections. There is some doc here explaining how to configure GENEVE on Linux: https://darjchen.medium.com/setting-up-geneve-tunnel-with-linux-tc-571f891618a9

If you give it a try, please share your successes and setups here as it could possibly interest other people.

**Comment by JackSlateur** [comment]
Hi @wtarreau 
Thank you for the feedback, I understand that there is no plan for user-space tcp stack that would be required to support this setup
Unless another piece of software supports dynamic GENEVE tunnels: as far as I know, iproute2 etc requires static data, and cannot use dynamic per-flow TLV

I will dig further and in other ways and put feedbacks if I find something

Have a nice day
