### ISSUE TITLE
Number of current sessions increasing for stats frontend with enabled prometheus-exporter

### ISSUE THREAD

**Issue by cgoeller** [haproxy/haproxy#151]
## Output of `haproxy -vv` and `uname -a`

```
[user@lb01 ~]$ haproxy -vv
HA-Proxy version 2.0.1 2019/06/26 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with PCRE2 version : 10.23 2017-02-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

[user@lb01 ~]$ uname -a
Linux lb01 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Running on RHEL 7.6 with keepalived and virtual ip address
Prometheus is running in version 2.7.1

## What's the configuration?

```
global
    maxconn 4096

defaults
    timeout client              30s
    timeout server              30s
    timeout connect             30s

frontend lb_web
    bind 172.17.51.124:80
    mode tcp
    default_backend swarm_traefik

backend swarm_traefik
    mode tcp
    balance roundrobin
    server srv1 172.17.51.10:80 check
    server srv2 172.17.51.11:80 check
    server srv3 172.17.51.12:80 check

frontend stats
    bind *:8404
    mode http
    http-request use-service prometheus-exporter if { path /metrics }
    stats enable
    stats uri /stats
    stats refresh 10s
```

## Prometheus config

```
  # HAProxy
  - job_name: haproxy
    scrape_interval: 1s
    static_configs:
      - targets:
          - lb01.site:8404
          - lb02.site:8404
```
The scrape interval in production is not that high by the way.

## Steps to reproduce the behavior

1. Start HAproxy with enabled prometheus service
2. Add scrape config in prometheus and start it

## Actual behavior

The number of current sessions for the "stats" frontend increases until it reaches the maximum. Then haproxy is completely unresponsive.

The other frontend is not affected.

![haproxy_stats](https://user-images.githubusercontent.com/1073092/60594981-679d3a00-9da6-11e9-88f5-1fda7ba30bcc.png)

## Expected behavior

The number of current sessions for the stats frontend does not increase over time and haproxy stays responsive.

## Do you have any idea what may have caused this?

When disabling the scrape job in prometheus or disabling the prometheus-service in haproxy, the number of connections is fine. So it looks like an issue in the prometheus-service module.

## Do you have an idea how to solve the issue?

No.

**Comment by capflam** [comment]
I confirm the bug. I'll fix it soon. Thanks !

**Comment by capflam** [comment]
I pushed a fix. It was also backported to 2.0. Feel free to test it.

**Comment by Alex1602** [comment]
Has the docker version been fixed already?

**Comment by TimWolla** [comment]
@Alex1602 The Docker images are based on released HAProxy versions. As this issue has been fixed 7 days ago and no release happened since then the Docker image still is affected.

**Comment by Alex1602** [comment]
Ah oke Ik already tried to build a Dev version but it was not in there. Do you know when this release would normally happen? Even if only in a Dev version?

**Comment by git001** [comment]
@Alex1602 
> Has the docker version been fixed already?

You can use in the meantime my image until 2.0.2 is released. I have build it with snapshot ss-20190706 5 days ago.

https://hub.docker.com/r/me2digital/haproxy20-centos

The run command is described in this blog post https://www.me2digital.com/blog/2019/05/haproxy-sni-routing/#run just replace `me2digital/haproxy19` with `me2digital/haproxy20-centos`
