### ISSUE TITLE
HAProxy 2.4.11 incomplete responses

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#1511]
### Detailed Description of the Problem

It looks like only 2.4.11 is affected. In some cases, we noticed some partial responses for example via curl:
`* transfer closed with 14389 bytes remaining to read`

It indeed got only part of the response.

HAProxy logs an internal proxy error:
`somefrontend~ somebackend/someserver 0/0/1/0/3 200 117289 - - ID-- 91/11/2/2/0 0/0 {somehost|curl/7.29.0|||} "GET /de HTTP/1.1"
`

"I" is described as:
        _I : an internal error was identified by the proxy during a self-check.
            This should NEVER happen, and you are encouraged to report any log
            containing this, because this would almost certainly be a bug. It
            would be wise to preventively restart the process after such an
            event too, in case it would be caused by memory corruption._

According to the logs it also doesn't seem to just affect curl but others as well.
It also affected several frontends/backends, not just specific ones.

### Expected Behavior

Transfer shouldn't be partial

### Steps to Reproduce the Behavior

Well, there is no good way yet to reproduce it. I have one CenOS Host, running 7.9.2009 and using their curl https://vault.centos.org/7.9.2009/os/Source/SPackages/curl-7.29.0-59.el7.src.rpm
I wasn't able to reproduce it on other hosts though. Even when using the same curl binary or building the same from source.

### Do you have any idea what may have caused this?

Something between 2.4.10 and 2.4.11 it seems

### What is your configuration?

```haproxy
non yet, due to containing sensitive details
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.11-1e183b8 2022/01/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.11.html
Running on: Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE= USE_PCRE_JIT= USE_PCRE2=1 USE_PCRE2_JIT= USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB= USE_SLZ=1 USE_NS= USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO -NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
somefrontend~ somebackend/someserver 0/0/1/0/3 200 117289 - - ID-- 91/11/2/2/0 0/0 {somehost|curl/7.29.0|||} "GET /de HTTP/1.1"
```

**Comment by capflam** [comment]
Thanks, It is probably related to #1510. I'm investigating.

**Comment by capflam** [comment]
@idl0r, Here is a patch that should fix this issue:

[0001-BUG-MAJOR-mux-h1-Don-t-decrement-.curr_len-for-unsen.patch.txt](https://github.com/haproxy/haproxy/files/7840414/0001-BUG-MAJOR-mux-h1-Don-t-decrement-.curr_len-for-unsen.patch.txt)

**Comment by capflam** [comment]
I'm closing this one because it is a duplicate of #1510.
