### ISSUE TITLE
Request for property ssl_c_r_dn: Client certificate root CA DN

### ISSUE THREAD

**Issue by domdom82** [haproxy/haproxy#1514]
### Your Feature Request

HAproxy should provide an additional property called `ssl_c_r_dn` similar to the existing ones `ssl_c_i_dn` and `ssl_c_s_dn`. The property should provide the full distinguished name of the root ca that was used when completing the chain of trust during client certificate validation by HAproxy.
 

### What are you trying to do?

The existing properties show the DN of the issuer and the subject of a client certificate. However, in some cases the issuer is not sufficient because it is an intermediate on an arbitrarily long chain of intermediates. To some clients behind HAproxy, the issuer is meaningless as they only know the DN of the root CA, so they cannot decide if the client certificate can be trusted just by looking at the (intermediate) issuer. 

In our specific case, there is also a longer list of accepted root CAs for a given (shared) domain. Some clients running on that domain may want to trust certificates by one of those root CAs but not others. So the client needs to know the CA that was ultimately used at the end of the chain.

Technically, HAproxy should have that information as it is used to form a complete chain of trust during the mTLS handshake.

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.0-f2e0833 2021/11/23 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
Running on: Linux 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```
```

**Comment by domdom82** [comment]
@wlallemand Do you think this could be done with reasonable effort?

**Comment by wlallemand** [comment]
I think it's doable, there is a function SSL_get0_verified_chain() provided by OpenSSL which can return the verified chain of the client, I never used it, but I think that could be the way to do it.

If you want to experiment with this, you could try a copy of the smp_fetch_ssl_x_chain_der() (ssl_c_chain_der sample) function in src/ssl_sample.c, and replace SSL_get_peer_certificate() with SSL_get0_verified_chain(), this should return the entire verified chain in binary.

**Comment by andyast** [comment]
@domdom82 did you ever make any progress on this?

**Comment by domdom82** [comment]
@andyast I have it in my backlog but haven't gotten around to do it yet. We might prioritize if there is higher demand for such a feature.

**Comment by andyast** [comment]
Only reason I asked is that I was going to take a crack at implementing it and submit a PR but didn't want to duplicate work.  Thanks for the info.

**Comment by domdom82** [comment]
@andyast hi, just checking. did you have any success in writing the PR?

**Comment by shadyabhi** [comment]
This issue caught my attention as it felt like a good hello-world PR attempt. 

[MINOR: ssl: add new sample ssl_c_r_dn](https://gist.github.com/shadyabhi/4014fc6e7acd1afc3e15c823d2565d49)

@wlallemand Would you have a moment to review this? My comfort is in writing Go/Python, however, I'm using this as an opportunity to remind myself of C. 

To the reviewer, I used `smp_fetch_ssl_x_notafter` as reference.

* Removed the condition for client/server, as we only needed `client certificate` in this case. 
* I verified that `SSL_get0_verified_chain` doesn't increase the ref count, so `X509_free` was not needed.

Guidance is appreciated, thanks!

**Comment by wlallemand** [comment]
Hi @shadyabhi, thanks for your proposal, there are minor issues but nothing difficult to fix!

Your ssl_sock_get_verified_chain_root() function is not doing things right in my opinion, in a STACK_OF(X509) the order is not guaranteed. You could iterate on the whole stack and return the first which is self-issued with X509_check_issued(cert, cert).

The documentation  is kind of confusing, I think you should mention that it comes from the chain once completed with the "ca-file" and verified, if it wasn't verified it is not suppose to return anything.

Also we are using a regression test for these sample fetches, it is  available in `reg-tests/ssl/ssl_client_samples.vtc`, it would be great if you can update it with this sample!

Thanks!

**Comment by wlallemand** [comment]
@shadyabhi any update on this? do you need help?

**Comment by shadyabhi** [comment]
Updated: [0001-MINOR-ssl-add-new-sample-ssl_c_r_dn.patch](https://gist.github.com/shadyabhi/c7095e6f416de2f98155d49d35836860)

@wlallemand I appreciate the review, updated patch linked above. 

>Your ssl_sock_get_verified_chain_root() function is not doing things right in my opinion, in a STACK_OF(X509) the order is not guaranteed.

I see, thanks. I also checked the API doc, it didn't provide any order guarantee. I've updated the code so we now loop through the chain and check for `X509_check_issued(crt, crt) == X509_V_OK` condition to find the `root CA cert`.

>The documentation is kind of confusing, I think you should mention that it comes from the chain once completed with the "ca-file" and verified, if it wasn't verified it is not suppose to return anything.

Sure, I've revised the documentation in latest patch. 

>Also we are using a regression test for these sample fetches, it is available in reg-tests/ssl/ssl_client_samples.vtc, it would be great if you can update it with this sample!

I've added the test as well. However, I don't like how it is written. For the cert `client1.pem` in the test `reg-tests/ssl/ssl_client_samples.vtc`, it looks like, the sample value for `ssl_c_i_dn` will be same as `ssl_c_i_dn`.

**Comment by wlallemand** [comment]
Thank you, I pushed the patch to master.

> I've added the test as well. However, I don't like how it is written. For the cert `client1.pem` in the test `reg-tests/ssl/ssl_client_samples.vtc`, it looks like, the sample value for `ssl_c_i_dn` will be same as `ssl_c_i_dn`.

Indeed, since we don't have a chain with intermediate certificates it's difficult to understand the difference with ssl_c_i_dn ... but that shouldn't be a problem, if Openssl is breaking X509_check_issued() there will be a bigger issue :-)  I'll try to introduce a more complex certificate chain to have more accurate tests.

**Comment by shadyabhi** [comment]
@wlallemand Great, happy to contribute. I'll keep looking for opportunities around the next one. :)  I see there were two follow-up `BUILD related` commits due to the `SSL_get0_verified_chain` being introduced  and some library compatibilities. 

I'm not sure how I can check these issues in advance, anyway, thank you for fixing that as follow-ups. It would be nice, if I could do a `CI test` with a patch before publishing.

>I'll try to introduce a more complex certificate chain to have more accurate tests.

That's definitely a good idea. I didn't want to introduce too many changes and wanted your opinion first.

**Comment by wlallemand** [comment]
> @wlallemand Great, happy to contribute. I'll keep looking for opportunities around the next one. :)

Thanks! We are always happy to have external contribution, HAProxy wouldn't be that powerful without the users! :-)

> I see there were two follow-up `BUILD related` commits due to the `SSL_get0_verified_chain` being introduced and some library compatibilities.
> 
> I'm not sure how I can check these issues in advance, anyway, thank you for fixing that as follow-ups. It would be nice, if I could do a `CI test` with a patch before publishing.

This part is always complicated, it's a mess to support correctly all openssl versions and forks. If you want to test it yourself you could run your own github fork with github actions activated, it will run all the build we are supporting.

**Comment by hmilkovi** [comment]
Hi everyone is there a chance I can help or contribute to get ssl_c_r_chain_der variable that would do same
as ssl_c_chain_der but get verified chain?

Wanted double check before I go into  coding.

Why?
DN can be spoofed, CA are going to be dynamic user controlled so DN can't be 100% trusted. If I can get der format I can do sha256 or sha1 from it and be 100% sure it is specific CA.
