### ISSUE TITLE
Feature: http-check disable-on XXX

### ISSUE THREAD

**Issue by mrhackcz** [haproxy/haproxy#152]
Hello haproxy devs !
Im looking for something how to disable backend server when status code is XXX. I think 404 is not the best code for turning off servers and I would prefer e.g. 503. Is possible to add option to http-check disable-on ? Third argument could be status code which if haproxy recieve it, haproxy will mark server as MAINT.
Thank you !

**Comment by lukastribus** [comment]
Are you talking about health checks or regular transactions?

**Comment by mrhackcz** [comment]
Im talking about same thing as "disable-on-404" httpcheck, but for arbitrary status code. In that case I need to do health check and when status code will be the code that I set in haproxy option, server will be marked as MAINT.

> Are you talking about health checks or regular transactions?

**Comment by lukastribus** [comment]
503 is a temporary server issue that in my opinion is supposed to set the status to down, not MAINT.

Usually you'd use the admin socket or the stats interface to change a servers state to MAINT or DRAIN, but this feature allows to do it on the backend, by adding and removing a file on the backend server.

I don't see the use-case and disagree that we should over-complicate features such as this one.

**Comment by mrhackcz** [comment]
Ok, thank you for this describe.
