### ISSUE TITLE
Timeouts during expect rule evaluation

### ISSUE THREAD

**Issue by alexsrb** [haproxy/haproxy#1523]
### Detailed Description of the Problem

An application (Graylog) exposes an API (without authentication) for integrating with load balancers, as described  [here](https://docs.graylog.org/docs/load-balancers).
In a nutshell, "The status knows three different states, ALIVE, THROTTLED and DEAD, which is also the text/plain response".

In order to perform multiple checks, tcp-check has to be used also for this API (multiple "option tcp-check" stanzas).

Testing setup: 3 identically configured application nodes + 1 HAProxy.
Application node 1 in state ALIVE, node 2 in state THROTTLED, node 3 in state DEAD (manual state overrides for failure simulation).

![image](https://user-images.githubusercontent.com/4201994/150801932-072510f2-f11a-4963-b17e-8d5950a4b424.png)
![image](https://user-images.githubusercontent.com/4201994/150801952-7d558117-c5a9-41e9-a529-0e75dca72881.png)
![image](https://user-images.githubusercontent.com/4201994/150801980-9b397231-de56-40e1-a673-f5fb9b164963.png)
![image](https://user-images.githubusercontent.com/4201994/150802001-83262251-dac5-4f9d-a7f5-0d5ecc7da38f.png)

The "tcp-check expect" behaves in an improper way:

a) "tcp-check expect string ALIVE" wrongfully marks node 2 (THROTTLED) as timed-out (L7TOUT) with the message "Layer7 timeout: at step 6 of tcp-check (expect string 'ALIVE')", instead of invalid response (L7RSP) as it does with node 3 (DEAD).
![image](https://user-images.githubusercontent.com/4201994/150802862-23c0c747-7a85-4353-b34e-64c91d827fd8.png)

b) "tcp-check expect string ALIVEE" wrongfully marks both node 1 (ALIVE) and node 2 (THROTTLED) as timed-out (L7TOUT) with the message "Layer7 timeout: at step 6 of tcp-check (expect string 'ALIVEE')", instead of invalid response (L7RSP) as it does with node 3 (DEAD).
![image](https://user-images.githubusercontent.com/4201994/150804097-918f343f-7ab2-4938-81e1-906bebc31ea5.png)

c) "tcp-check expect error-status L7OKC ! string THROTTLED" wrongfully marks node 1 (ALIVE) as timed-out (L7TOUT) with the message "Layer7 timeout: at step 6 of tcp-check (expect string 'THROTTLED')", instead of check passed (L7OK) as it does with node 3 (DEAD).
![image](https://user-images.githubusercontent.com/4201994/150806673-57f43d3f-6197-438e-9e17-6424d228501a.png)

d) "tcp-check expect ! string DEAD" wrongfully marks both node 1 (ALIVE) and node 2 (THROTTLED) as timed-out (L7TOUT) with the message "Layer7 timeout: at step 6 of tcp-check (expect string 'DEAD')", instead of invalid response (L7RSP) as it does with node 3 (DEAD).
![image](https://user-images.githubusercontent.com/4201994/150804548-2b046c78-a18b-44b1-9811-0babec636c75.png)

The same incorrect behaviour is observed when using rstring+equivalent regex.

### Expected Behavior

As per above (see "instead of..." statements).

### Steps to Reproduce the Behavior

-

### Do you have any idea what may have caused this?

Maybe the underlying logic does take the status codes into account, even if it should NOT do so (one uses "tcp-check expect" exactly for a very granular and MANUAL control of the decision logic)?

### What is your configuration?

```haproxy
global
        log /dev/log    len 65535       format rfc5424  local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256

        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets


defaults
        mode tcp
        log global
        option tcplog
        option dontlognull
        timeout client 30s
        timeout client-fin 1s
        option clitcpka
        timeout server 30s
        timeout server-fin 1s
        timeout connect 5s
        timeout queue 5s
        option srvtcpka

backend <redacted>
        # Check every second
        default-server check inter 1s

        option tcp-check
        tcp-check connect port 9000
        tcp-check send GET\ /api/system/lbstatus\ HTTP/1.1\r\n
        tcp-check send Host:\ localhost:9000\r\n
        tcp-check send \r\n
        # Three different possible states, ALIVE, THROTTLED and DEAD, which is also the text/plain response.
        tcp-check expect string ALIVE
#        tcp-check expect string ALIVEE
#        tcp-check expect ! string DEAD

        server <redacted:1> <redacted IP>:514 check log-proto octet-count
        server <redacted:2> <redacted IP>:514 check log-proto octet-count
        server <redacted:3> <redacted IP>:514 check log-proto octet-count
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.7-1~bpo11+1 2021/10/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.7.html
Running on: Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -ffile-prefix-map=/build/haproxy-2.4.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by capflam** [comment]
First, it is probably a good idea to use `http-check` directives instead of `tcp-check`.

Then, the first two servers are returning HTTP/1.1 response without `connection: close` header. And you don't set it in your request. Thus, the connections are kept alive on these servers. If the string is matched, the server is marked as UP. However, if the string is not found, HAProxy waits till the timeout or the connection close. On the second server, because the connection is not closed after the response, a timeout is reported. On the third server, the connection is closed, thus an invalid response is reported.

The same is true for all other scenario.

To fix your issue, add `connection: close` header in your request. And to be safe, you may also add it in all graylog responses.

**Comment by alexsrb** [comment]
@capflam thank you very much for the quick feedback!
Adding the Connection: close header in the tcp-check send requests did solve the issue, thanks!

@ "it is probably a good idea to use http-check directives instead of tcp-check.":
Can one use "option tcp-check" and "option httpchk" together?
I am asking because a dual check is needed (TCP connection check on port 514 = Syslog listener running AND API check on port 9000 = processing ready), and when trying to use httpchk for the latter, killing the service listening on TCP 514 did not change the status of that node.

In other words, closing port TCP 514 does NOT trigger the tcp check in:
        option tcp-check
        tcp-check connect port 514
        option httpchk
        http-check connect port 9000
        http-check send meth HEAD uri /api/system/lbstatus ver HTTP/1.1 hdr host localhost:9000
        http-check expect status 200,429
        http-check expect error-status L7OKC ! status 429

whereas in here it does:
        option tcp-check
        tcp-check connect port 514
        option tcp-check
        tcp-check connect port 9000 #ssl
        tcp-check send GET\ /api/system/lbstatus\ HTTP/1.1\r\n
        tcp-check send Host:\ localhost:9000\r\n
        tcp-check send Connection:\ close\r\n
        tcp-check send \r\n
        tcp-check expect string ALIVE
        tcp-check expect error-status L7OKC ! string THROTTLED

**Comment by capflam** [comment]
You cannot mix http and tcp health-checks. Only one kind of health-check is supported. And for now, a `connect` rule without any `expect` rule is not really supported with http health-checks. It is designed to send an HTTP request and test the response. So in this case, you must indeed use a tcp-check.

Note that one `option tcp-check` line is enough. The second one overrides the first one.

**Comment by alexsrb** [comment]
Alright, thanks for the confirmation w.r.t. the inability to mix tcp and http health checks.
And for the other tip as well!
