### ISSUE TITLE
src/mux_h2.c: checked return is suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1527]
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1469118:  Error handling issues  (CHECKED_RETURN)
/src/mux_h2.c: 6370 in h2_rcv_buf()
6364     
6365            /* <buf> is empty and the message is small enough, swap the
6366             * buffers. */
6367            if (htx_is_empty(buf_htx) && htx_used_space(h2s_htx) <= count) {
6368                    htx_to_buf(buf_htx, buf);
6369                    htx_to_buf(h2s_htx, &h2s->rxbuf);
>>>     CID 1469118:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "b_xfer" without checking return value (as is done elsewhere 4 out of 5 times).
6370                    b_xfer(buf, &h2s->rxbuf, b_data(&h2s->rxbuf));
6371                    goto end;
6372            }
6373     
6374            htx_xfer_blks(buf_htx, h2s_htx, count, HTX_BLK_UNUSED);
6375
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
This one is not needed because the condition to succeed is guaranteed by the surrounding "if" (destination is empty hence a swap will always happen).

**Comment by TimWolla** [comment]
@wtarreau If Coverity is to be trusted then in all cases except that one the return value is checked. This can also be confusing to a human reader.

For uri_normalizer.c I've attempted write the code as clear as possible and did the following:

https://github.com/haproxy/haproxy/blob/74904a479251539606f83c1ecef76d9a10fdb7d5/src/uri_normalizer.c#L445-L450

Ignoring the return value felt wrong, so I opted to explain this to the human reader with the comment and used `my_unreachable()` to explain this to the compiler as well. My understanding is that this should cause the compiler to not emit additional code for the unreachable case.

**Comment by wtarreau** [comment]
Sometimes it makes sense, but here not only it's in the hot path and we're certainly not going to make the compiler emit code that serves no purpose, but in addition there is a clear comment before the if explaining why this can be done. Thus writing the code that does the opposite would be even more confusing. We used to have places in the past where we tried hard to handle impossible cases but that made that code unmaintainable just because of the absurdity of conflicting impossible cases at some point.

**Comment by TimWolla** [comment]
> we're certainly not going to make the compiler emit code that serves no purpose

Interesting. Does the compiler not strip the branch? It's clearly marked unreachable.

> Thus writing the code that does the opposite would be even more confusing.

But that's fair :smiley:

**Comment by wtarreau** [comment]
On a simple test like this one, it may strip it. But sometimes the condition can be more complex (e.g. you have to call another function to validate a size or something) and then the compiler cannot know that it's without side effects and has to call it before giving up.

**Comment by chipitsine** [comment]
well, Coverity accept "modeling" 

https://scan.coverity.com/tune#what-is-model

**Comment by chipitsine** [comment]
for short term, I'll mark this finding as false positive
