### ISSUE TITLE
Maxlength of a line in a statefile

### ISSUE THREAD

**Issue by VigneshSP94** [haproxy/haproxy#1530]
### Your Feature Request

We’re using service discovery with haproxy, and use statefile to revive states during reloads. Sometimes loading from the statefile is failing with error corrupted global server state file 'path/to/statefile' at line somenumber

Upon debugging, we learnt that maximum allowed characters in a state_line is 512

https://github.com/haproxy/haproxy/blob/21ea8c519816314e88f65199c8f1d9c1a226f8b1/include/haproxy/server-t.h#L135

the fqdn of the real server and srv records are very big in size in our environment which easily exceeds defined 512 length.

Is there any reason it is contained within 512 chars? can we change it? Any recommendations to work this around will be very helpful.

### What are you trying to do?

-

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.10-bedf277 2021/12/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.10.html
Running on: Linux 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1h  22 Sep 2020
Running on OpenSSL version : OpenSSL 1.1.1h  22 Sep 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by VigneshSP94** [comment]
@lukastribus sorry to rush, any comments on this will be very helpful.

**Comment by lukastribus** [comment]
I didn't write that code, but in 41472f4d98d165465bc9aa9bc399911b7bc3c50e the comment says:

`an arbitrary state-file max line length`

So I don't think there are particular problems raising this. What would be a value that satisfies your use-case (with some margin)?

CCing @bedis

**Comment by VigneshSP94** [comment]
For our use and commonly, we believe a length of 1024 will be fine.

**Comment by wtarreau** [comment]
I too think it can easily be changed. The reason for the original size was that initially there were few fields and most of them are short. With long FQDN names and possibly many fields with large values, that can become a mess. I had a quick check and it's only allocated in the stack at a few places. We can even increase it to 2 kB without problem if we want to stay on the safe side. I'm keeping the entry open so as not to forget. By the way, I'll retag this as a bug because it should not fail with valid contents.

**Comment by VigneshSP94** [comment]
@wtarreau can I submit a fix? I think its fairly easy. `SRV_STATE_LINE_MAXLEN` is used in 5 places, all calling the same value with no alterations.

**Comment by wtarreau** [comment]
Sure, you're welcome! Thank you! Please see CONTRIBUTING to make sure you properly format your commit message and subject line mentioning a bug, and do not forget to mention in the commit message that it should be backported to stable branches since you faced it in 2.4. That will naturally flow to other versions.

**Comment by wtarreau** [comment]
@VigneshSP94 any news on this ?

**Comment by VigneshSP94** [comment]
@wtarreau sorry, I will submit a commit this week !

**Comment by VigneshSP94** [comment]
@wtarreau I've submitted a commit last night and sent to the mailing list.

**Comment by wtarreau** [comment]
Yes I noticed, thank you @VigneshSP94, I'll take it ASAP, it's just that I'm busy on low-level stuff for now :-)

**Comment by wtarreau** [comment]
Now merged, let's keep it open for the backports. Thanks @VigneshSP94 !

**Comment by capflam** [comment]
It was backported to all versions. Thanks !
