### ISSUE TITLE
Cannot validate configuration using jwt_verify

### ISSUE THREAD

**Issue by piir** [haproxy/haproxy#1533]
### Detailed Description of the Problem

when running haproxy to validate a configuration file, it exits with a code 139 and the folowing output:
```
Configuration file is valid
free(): double free detected in tcache 2
```

### Expected Behavior

return code is 0, and no message about a double free

### Steps to Reproduce the Behavior

1. generate a valide rsa key
```
openssl genrsa -out private.pem 2048
openssl rsa -in private.pem -pubout > public.pem
```
2. set a minimal configuration
```
cat <<EOF >haproxy.cfg
defaults
   mode http

frontend public_web_servers
   bind *:80
   timeout client 5000
   default_backend public_web_servers


backend public_web_servers
   acl token_verify urlp(token),jwt_verify(txn.jwt_alg,"/usr/local/etc/haproxy/public.pem") 1
EOF
```
3. run a docker with the associated configuration
`docker run -it --rm  -p 8080:80 -v $(pwd)/public.pem:/usr/local/etc/haproxy/public.pem:ro  -v $(pwd)/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro  --name haproxy-syntax-check haproxy:2.5 haproxy -f /usr/local/etc/haproxy/haproxy.cfg -c`

### Do you have any idea what may have caused this?

The pointer used in jwt_deinit to iterate over the allocated entry is not reset after a delete resulting in a double free. To cause the error the public.pem must be a valid file otherwise jwt_tree_load_cert won't allocate an entry in jwt_cert_tree.

### Do you have an idea how to solve the issue?

```
diff --git a/src/jwt.c b/src/jwt.c
index 8c4537542..e5f1d990a 100644
--- a/src/jwt.c
+++ b/src/jwt.c
@@ -364,7 +364,7 @@ static void jwt_deinit(void)
        while (node) {
                entry = ebmb_entry(node, struct jwt_cert_tree_entry, node);
                ha_free(&entry);
-               node = ebmb_first(&jwt_cert_tree);
+               node = ebmb_next(node);
        }
 }
 REGISTER_POST_DEINIT(jwt_deinit);
```

### What is your configuration?

```haproxy
running on docker with image id: 645e4ef01d91
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.1-86b093a 2022/01/11 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.1.html
Running on: Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by rlebreton** [comment]
The deinit was indeed broken, I found a few other bugs than this one as well.
The following three patches should make it cleaner (only the first one concerns this specific issue though)

[0001-BUG-MINOR-jwt-Double-free-in-deinit-function.txt](https://github.com/haproxy/haproxy/files/8003551/0001-BUG-MINOR-jwt-Double-free-in-deinit-function.txt)
[0002-BUG-MINOR-jwt-Missing-pkey-free-during-cleanup.txt](https://github.com/haproxy/haproxy/files/8003552/0002-BUG-MINOR-jwt-Missing-pkey-free-during-cleanup.txt)
[0003-BUG-MINOR-jwt-Memory-leak-if-same-key-is-used-in-mul.txt](https://github.com/haproxy/haproxy/files/8003553/0003-BUG-MINOR-jwt-Memory-leak-if-same-key-is-used-in-mul.txt)

**Comment by piir** [comment]
Thanks, i was hoping to see those patches integrated in the current and previous version, i'm using the 2.5. Do you have any ideas on how to make this happen ?

**Comment by rlebreton** [comment]
Sorry for the delay, I had a talk with @wlallemand and he suggested some changes for the third patch. Here are the new patches that should fix the issue :

[0001-BUG-MINOR-jwt-Double-free-in-deinit-function.patch.txt](https://github.com/haproxy/haproxy/files/8070464/0001-BUG-MINOR-jwt-Double-free-in-deinit-function.patch.txt)
[0002-BUG-MINOR-jwt-Missing-pkey-free-during-cleanup.patch.txt](https://github.com/haproxy/haproxy/files/8070466/0002-BUG-MINOR-jwt-Missing-pkey-free-during-cleanup.patch.txt)
[0003-BUG-MINOR-jwt-Memory-leak-if-same-key-is-used-in-mul.patch.txt](https://github.com/haproxy/haproxy/files/8070468/0003-BUG-MINOR-jwt-Memory-leak-if-same-key-is-used-in-mul.patch.txt)

**Comment by wlallemand** [comment]
Thanks, this was merged in master and will be backported for the next 2.5 release.
