### ISSUE TITLE
Support a variable name as an offset to the date fetch

### ISSUE THREAD

**Issue by bedis** [haproxy/haproxy#1534]
### Your Feature Request

Currently, the `date` fetch supports an offset as the form of an integer.
Would be great to be able to pass a variable name which contains an integer to be consumed by the fetch, something like that:
```
http-response set-var(txn.myoffset) int(2400)
http-response set-header expire date(txn.myoffset)
```

NOTE: might be related to #1535 

### What are you trying to do?

I want to have a more dynamic date

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.0-6bba47-41 2021/12/30 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
Running on: Linux 5.10.0-1052-oem #54-Ubuntu SMP Tue Nov 23 09:06:13 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.2
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by Darlelet** [comment]
Here is my attempt to address this feature request.
[0001-DEV-sample-adding-date_var-smp_fetch.patch.txt](https://github.com/haproxy/haproxy/files/9566587/0001-DEV-sample-adding-date_var-smp_fetch.patch.txt)


I purposely chose not to modify existing date() sample fetch but instead provide a new sample fetch called date_var() that will perform variable lookups as you requested.
I was afraid that changing date() could induce some performance issues or could lead to confusion as the behavior would then be "type" dependent.

#### Here is a working example:

```
http-response set-var(txn.myoffset) int(2400)
http-response set-header expire %[date_var(txn.myoffset)]
``` 
Will behave the same as:
```
http-response set-header expire %[date(2400)]
```

**Comment by capflam** [comment]
Just my 2 cents, it may be implemented as a converter. For instance:

```
var(txn.myoffset),date(<unit>)
```

This way, it will not be limited to variable. It will work for all sample fetches returning a integer.

**Comment by Darlelet** [comment]
@capflam You're right, it is much more versatile this way. Thank you for the suggestion!

Here is a working implementation using converters instead:
[0001-DEV-http_conv-adding-date-converter.patch.txt](https://github.com/haproxy/haproxy/files/9567640/0001-DEV-http_conv-adding-date-converter.patch.txt)

Depending on the usage, maybe it could be worth considering both implementations as they are not conflicting.
(one is simpler to use, the other has more potential)

**Comment by Darlelet** [comment]
Also while playing with converters I noticed that converters validating functions are called even if no arguments are provided to a converter taking optional arguments. In this case arg[0] contains a NULL-BYTE.

That behavior differs from sample fetches: validating function for a sample fetch taking optional arguments won't be called at all if no arguments are provided.

This explains the extra check needed in [0001-DEV-http_conv-adding-date-converter.patch.txt](https://github.com/haproxy/haproxy/files/9567640/0001-DEV-http_conv-adding-date-converter.patch.txt) before calling **smp_check_date_unit** (sample.c) from **_smp_check_date_unit** (http_conv.c):
 
```
        /* specific check needed: validating arg funcs are always called
         * for converters even when no argument are provided whereas
         * they are not called for sample_fetch if no arguments are provided
         */
        if (args[0].data.str.area[0] == '\0')
                _args[1].type = ARGT_STOP;
```

**Comment by TimWolla** [comment]
> `var(txn.myoffset),date(<unit>)`

Isn't that exactly equivalent to `date(<unit>),add(txn.myoffset)`?

With this config:

```
listen foo
	bind *:8080
	mode http

	http-request set-var(txn.offset) req.hdr(offset)
	http-after-response set-header time %[date(),add(txn.offset),http_date]
	server example example.com:80
```

I can just do:

```
$ http localhost:8080 'offset: 9999999'                                                                                                                                                         
time: Sun, 08 Jan 2023 09:28:23 GMT
```

and it does what is expected. I think this feature request is completely unnecessary then. Users can be expected to use the `,add()` converter if they need variables.

**Comment by capflam** [comment]
@TimWolla, indeed, you"re right ! I totally forgot that `add()` converter may be used with a variable.

**Comment by TimWolla** [comment]
@capflam So, should we close this request then?

**Comment by capflam** [comment]
Of course :)
