### ISSUE TITLE
Ability to use the "expire" information from the stick table

### ISSUE THREAD

**Issue by bedis** [haproxy/haproxy#1535]
### Your Feature Request

When a data is stored in a stick table and data expiration is enabled, HAProxy maintain an "expire" counter. This expiration counter is not accessible from the HAProxy configuration.
Given the following table:
`stick-table type ip size 10k expire 1h peers cluster store http_req_rate(10s)`

And the output of the stick table:
```
# table: fe_main, type: ip, size:10240, used:1
0x56416d945cb0: key=127.0.0.1 use=0 exp=3597444 http_req_rate(10000)=5
```
This is the "exp" counter. I'd like to get a fetch and a converter to get access to this value.

NOTE: might be related to #1534

### What are you trying to do?

I'd like to use the `exp` value in case of "API gateway" pattern to return a date to the client who abused a service:
* this date can be the moment when current quota will expire
* this date can be the moment when an abuser could re-use the service again

* Example of headers returned by github API: [https://docs.github.com/en/rest/overview/resources-in-the-rest-api#checking-your-rate-limit-status](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#checking-your-rate-limit-status) (check the X-RateLimit-Reset header)
* Send a `retry-after` header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

Configuration could look like this:
* with a converter:
```
fe_main
 [...]
 stick-table type ip size 10k expire 1h peers cluster store http_req_rate(10s)
 http-request set-var(txn.exp) src,table_exp(fe_main)
 http-request return status 429 hdr x-ratelimit-reset %[date,add(txn.exp)]  if { src,table_http_req_rate(fe_main) gt 100 }
```
* with a fetch:
```
fe_main
 [...]
 stick-table type ip size 10k expire 1h peers cluster store http_req_rate(10s)
 http-request track-sc0 src
 http-response set-var(txn.exp) sc0_exp
 http-response set-header hdr x-ratelimit-reset %[date,add(txn.exp)] if { sc0_http_req_rate lt 100 }
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.0-6bba47-41 2021/12/30 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
Running on: Linux 5.10.0-1052-oem #54-Ubuntu SMP Tue Nov 23 09:06:13 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.2
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```
```

**Comment by vchirikov** [comment]
Yep, it will be very helpful for `RateLimit-Reset` header
draft: https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html

**Comment by walkeran** [comment]
I would find this useful as well, for a `Retry-After` header, but I would also find it useful to be able to **set** the expiration time on a per-entry basis.

My use-case is is:
- I have a table I use for blocking bad clients. Right now it has a couple hour expiration
- There are multiple ways that a client can be deemed bad, and those ways would ideally have different "penalties"
- When a user is blocked, their identifier is tracked in the ban table. I'd like to also be able to set the TTL in that request, causing their ban to last the intended length of time.

This seemed like a bit of an odd ask, but when I saw the request in this issue, I thought it might not actually be too farfetched.

Thanks!

**Comment by wtarreau** [comment]
Note that this is now addressed in 2.7-dev and was backported to 2.6.3 (`table_expire()` and `table_idle()`).

**Comment by wtarreau** [comment]
I'm thus closing as fixed.

**Comment by walkeran** [comment]
You rock, @wtarreau -- thanks a bunch!!
