### ISSUE TITLE
Lua api documentations links on web site www.haproxy.org dead...

### ISSUE THREAD

**Issue by mcarbonneaux** [haproxy/haproxy#1543]
### Detailed Description of the Problem

the links on web site www.haproxy.org are dead for recent version of lua api documentation...
![image](https://user-images.githubusercontent.com/8479023/152550530-f3a828df-4e33-4569-8826-8fb20ed3772e.png)

and on old nginx !!!

### Steps to Reproduce the Behavior

go to the web site www.haproxy.org and clic on lua api html documentation on dev, 2.5 and 2.4 version....

### Do you have any idea what may have caused this?

for 2.4 i think the link have not been updated... because the link http://www.arpalert.org/src/haproxy-lua-api/2.4/index.html work...
and the latest one i think has not been generated....

**Comment by wtarreau** [comment]
Ah thank you Mathieu, now fixed! I'll check with Thierry because I think he should not use a "dev" suffix in his URIs to change it later.
