### ISSUE TITLE
Memory leak/growth in HAProxy 2.5.1 ? 

### ISSUE THREAD

**Issue by lserranov** [haproxy/haproxy#1548]
### Detailed Description of the Problem

I have HAProxy 2.5.1 in SSL termination config running in a container of a Kubernetes POD, the backend is an Scala App that runs in another container of same POD.

I placed 3 times 500K connections in the system as follows:
1) Put 500K connections 
2) Wait 5-10 mins once all the connections are in place
3) Stop the traffic for 15 minutes
4) Repeat 1-3 above 3 times

In a graph the traffic was as below:

![image](https://user-images.githubusercontent.com/7193096/154101888-2b0d5ecf-4f1f-44bb-a488-8e12105ca7a9.png)

When looking at RSS chart for HAProxy, memory usage was as below, you can see that the first time I put the traffic RSS hit 18GB, the second time it hit 28GB and the third time I was not able to finish the test as the Max Memory allowed in my container  is 30GB and Kubernetes killed the Container :
![image](https://user-images.githubusercontent.com/7193096/154102641-af22c671-d426-4e47-99d2-621ade0bcddd.png)

### Expected Behavior

Expected behavior is:

I expect that memory should have stayed around 20GB for all the test provided that the traffic was the same.

BTW, is surprising to see that memory usage is 20GB for 400K connections, i.e 50KB per connection.  

### Steps to Reproduce the Behavior

1. Configure the client and HAProxy to do persistent connections
2. Monitor RSS Memory usage for HAProxy  
2. Put 400K persistent connections in the setup
3. Leave the traffic 5-10 mins
4. Remove the traffic
5. Repeat 2-4 above 3 times  
6. Check Memory RSS usage over time

### Do you have any idea what may have caused this?

No

### Do you have an idea how to solve the issue?

No

### What is your configuration?

```haproxy
10 Client Machines, 64K connections each
1 Single HAProxy Server
8 Backend Servers

global
  log stdout    local0 info
  log stdout    local1 info
  stats timeout 30s
  user haproxy
  group haproxy
  daemon
  maxconn 500000

  nbthread 4


  # Default SSL material locations
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private

  
  ssl-default-bind-options no-sslv3

  ssl-default-bind-options “some settings” 
  ssl-default-bind-ciphers “some settings”

  ssl-default-server-options “some settings”
  ssl-default-server-ciphers “some settings”

  tune.ssl.default-dh-param 2048

listen stats
  bind *:9391
  mode http
  http-request use-service stats-exporter if { path /metrics }
  stats enable
  stats uri /stats
  stats refresh 10s

frontend my-server-config
  bind *:5455 ssl accept-proxy transparent crt server.pem ca-file CA.pem verify required
  mode tcp
  maxconn 500000
  option clitcpka
  option tcplog
  timeout client      100s
  default_backend nginx-server

backend nginx-server
  mode tcp
  fullconn 500000
  balance leastconn
  option srvtcpka
  timeout connect     100s
  timeout server      100s
  server nginx-1 server1:80 send-proxy check port 80
  server nginx-2 server2:80 send-proxy check port 80
  server nginx-3 server3:80 send-proxy check port 80
  server nginx-4 server4:80 send-proxy check port 80
  server nginx-5 server5:80 send-proxy check port 80
  server nginx-6 server6:80 send-proxy check port 80
  server nginx-7 server7:80 send-proxy check port 80
  server nginx-8 server8:80 send-proxy check port 80
```

### Output of `haproxy -vv`

```plain
$ haproxy -vv
HAProxy version 2.5.1-86b093a 2022/01/11 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.1.html
Running on: Linux 5.4.0-1041-aws #43-Ubuntu SMP Fri Mar 19 22:06:16 UTC 2021 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=36).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.3.1 20211027

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

/ $ 
/ $ uname -a
Linux 4dfps  5.4.0-1041-aws #43-Ubuntu SMP Fri Mar 19 22:06:16 UTC 2021 x86_64 Linux
/ $
```

**Comment by wtarreau** [comment]
Could you please rebuild with USE_MEMORY_PROFILING=1 ? Then place `profilng.memory on` in your global section.
On the CLI you can then enter `show profiling memory` between tests, it will show call places that allocate/release memory and may help spot where this is. Also, please be aware that for large memory usage we've already had reports of extremely inefficient memory management with some versions of glibc that made us think about a leak while in the end it was not the case, with tens of GB used and not easily released. Switching to jemalloc completely fixed the issue because it was able to punch holes in smaller areas.

You can also try to issue a SIGQUIT to the process, it will flush all of its memory pools. If the allocator cannot easily punch small holes, it may be constrainted to keep large areas allocated until the last byte is released.

By the way, ~50kB per connection sounds high but not excessive for SSL depending on whether there is traffic or not. There's ~2kB per end-to-end connection for haproxy, plus ~16kB per direction for the SSL stack, plus possibly ~16kB per direction with pending data for haproxy buffers. An interesting test would be to decrease `bufsize` to 8192 (half of the current value) and see by how much it shrinks, if at all. You can also issue `show pools` on the CLI to see how memory is allocated.

**Comment by lserranov** [comment]
Hi @wtarreau , 

Following your advise, we moved from linux-musl into  linux-glibc and that helped with the problem:

![image](https://user-images.githubusercontent.com/7193096/154773366-92ae4346-1a10-4811-b732-404342799382.png)

Thanks a lot for helping and guiding.

**Comment by wtarreau** [comment]
Ah, impressive difference, indeed! That's not that much surprising if you were on musl, it's optimised for low resource usage, and you cannot optimize both for low resource usage and high resource usage. However, given your planned load, I really encourage you to give a try to jemalloc. It would likely result in a significant reduction, as it is *really* optimized for such loads and can aggressively release unused areas.

**Comment by wtarreau** [comment]
So I guess we can close then.
