### ISSUE TITLE
src/h3.c: variable are set, but not used

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1549]
### Tool Name and Version

clang13

### Code Report

```plain
CC      src/cfgparse-quic.o
src/h3.c:206:9: error: variable 'htx_sent' set but not used [-Werror,-Wunused-but-set-variable]
        size_t htx_sent;
               ^
src/h3.c:207:6: error: variable 'htx_space' set but not used [-Werror,-Wunused-but-set-variable]
        int htx_space;
            ^
src/h3.c:234:6: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int ret;
            ^
3 errors generated.
```

### Additional Information

caught on Fedora Rawhide (comes with clang13)

### Output of `haproxy -vv`

```plain
no
```

**Comment by a-denoyelle** [comment]
It is only reproducible when building without DEBUG_STRICT as these variables are used for BUG_ON statements. However, this is only a temporary solution until a proper error handling of these cases is implemented, which should remove these compiler warnings as well.
