### ISSUE TITLE
Lingering worker processes consuming RAM

### ISSUE THREAD

**Issue by krzysztof-bronk** [haproxy/haproxy#155]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.20 2019/04/25
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_SYSTEMD=1 USE_PCRE=1 USE_PCRE_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
```
```
Linux (...) 4.14.55-68.37.amzn2.x86_64 #1 SMP Fri Jul 20 00:55:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
[Service]
Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid"

ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE

ExecReload=/usr/sbin/haproxy -f $CONFIG -c -q -x /run/haproxy_admin.sock
ExecReload=/bin/kill -USR2 $MAINPID

KillMode=mixed
Restart=always
Type=notify
```

## What's the configuration?

```
1 core, 1 thread

defaults
  log             global
  mode            http
  balance         roundrobin
  option          httplog
  option          dontlognull
  retries         3

  timeout connect         10s
  timeout client          5m
  timeout server          5m
  timeout http-request    10s
  timeout queue           1m
  timeout http-keep-alive 20s
  timeout check           20s

  option          redispatch
  option          contstats
  option          forwardfor

HUNDREDS of listeners binding ports 30000+
Example:
bind :32114 ssl crt /etc/ssl/private/pki.pem
    server X Y:Z check port 32114 ssl
    server X Y:Z check port 32114 ssl 
    server X Y:Z check port 32114 ssl
    (...) x30

As you can imagine, the stats page barely loads... but I digress
```

## Steps to reproduce the behavior

service haproxy reload * many days

## Actual behavior

Over time, with enough reloads, haproxy will have forever lingering worker processes (not many, but a couple)
Example:
```
haproxy    6263  4.8 11.2 608784 448312 ?       Ss   Jul02 207:09 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 68609 220944 118972 50137 -x /run/haproxy_admin.sock
haproxy   50137  0.5  8.1 480012 327880 ?       Ss   Jun03 255:49 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 164239 118972 4573 -x /run/haproxy_admin.sock
haproxy   68609  4.3 11.5 631240 462036 ?       Ss   Jun27 487:48 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 65076 63020 50137 182459 220944 118972 -x /run/haproxy_admin.sock
haproxy   87125  6.6  9.3 536564 375816 ?       Ss   Jul04  90:37 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 6263 68609 220944 118972 50137 -x /run/haproxy_admin.sock
root     118970  0.0  4.9 268836 196416 ?       Ss   May24   0:13 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 6263 68609 220944 118972 50137 -x /run/haproxy_admin.sock
haproxy  118972  0.9  5.7 366756 231540 ?       Ss   May24 563:27 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid
root     127656  0.0  0.0 119464   948 pts/0    R+   12:22   0:00 grep --color=auto haproxy
haproxy  220944  2.3 10.6 588332 426732 ?       Ss   Jun19 532:02 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -sf 126079 50137 118972 -x /run/haproxy_admin.sock
```
The instance eventually runs out of RAM (?).
Restarting haproxy service fixes the issue immediately.

## Expected behavior

For worker processes not to linger on forever and consume RAM

## Do you have any idea what may have caused this?

Nope

## Do you have an idea how to solve the issue?

service haproxy restart

Thank you for the support!

I have a bonus question - in the article about truly seamless reloads, it's stated "The implementation is limited to passing 253 listeners at the most, but this is a limitation of the SCM_RIGHTS API combined with the fact that we don’t want to poll at this moment, and it is more than enough to support even multi-process reloads."
What does that mean exactly? If I bind 300 ports, only 253 can have the seamless reload? Or is that something else?

**Comment by dward** [comment]
I'm experiencing the same issue with 1.8.20. We reload haproxy several times during the day to update SSL certificates. At some points, we'll get stale worker processes that never die.

We ended up adding the following to the config as a workaround:
```
hard-stop-after 3600s
```
An lsof of the stale processes would show something similar to:
```
haproxy 22241 nobody  642u     sock       0,7      0t0 927261462 protocol: TCP
```
With no details on the TCP connection. So, it's like the kernel has closed the socket, but it's not closed within the process.

**Comment by lukastribus** [comment]
Did you guys use a different release prior to this, that did not have this problem? If yes, which one?

**Comment by dward** [comment]
We didn't see the issue until we went from version 1.8.14 to 1.8.19. Though, at the same time we enabled http2.

**Comment by lukastribus** [comment]
@krzysztof-bronk you have high timeout values, for example client and server are set to 5 minutes. Without `hard-stop-after` any client can easily block process exit by holding the connection. Are you using H2? Because that means any H2 connection with activity less than "timeout client" (5 minutes) will block the old process from exiting.

@dward can you share your configuration as well please? You confirmed you are using H2, what are your timeouts?

**Comment by dward** [comment]
Here's the config including the timeouts.
The stale workers would live on forever in our case without hard-stop-after.

```
global
        maxconn 2000000
        user nobody
        group nobody
        nbproc 10
        tune.bufsize 32768
        tune.ssl.default-dh-param 2048
        hard-stop-after 3600s

        ssl-mode-async
        ssl-default-bind-options ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.2
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!DES-CBC3-SHA
        ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!DES-CBC3-SHA
        ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11

defaults
        retries 3
        option redispatch
        option log-separate-errors
        option tcp-smart-connect
        option tcp-check
        maxconn 2000000
        log 127.0.0.1:601 user warning
        log-tag haproxy
        timeout connect 1s
        timeout client 60s
        timeout server 60s
        timeout client-fin 60s
        timeout server-fin 60s
        timeout check 1s
        default-server inter 10s downinter 5s rise 3 fall 2

frontend varnish-ssl
        bind 0.0.0.0:443 ssl crt /etc/varnish/maps/site-certs/ tfo alpn h2,http/1.1
        mode http
        default_backend varnish-ssl-backend

backend varnish-ssl-backend
        mode http
        balance roundrobin
        option httpchk GET /_health_ping "HTTP/1.0\r\nHost: www.domain.com"
        http-check expect status 418
        server http1 127.0.0.1:6080 check send-proxy-v2
        server http2 127.0.0.2:6080 check send-proxy-v2
        server http3 127.0.0.3:6080 check send-proxy-v2
        server http4 127.0.0.4:6080 check send-proxy-v2
```

**Comment by krzysztof-bronk** [comment]
I'll definitely give "hard-stop-after" a go. 
We do not use H2 at the moment, but we're stuck with the high timeouts for better or worse.
I understand your explanation, though I also observe this issue on environments with VERY low service RPS. And as far as I've noticed, those worker processes simply never die.

I could verify it though - by cutting off all traffic. If the old process does not exit, then it shouldn't be due to clients. The unfortunate issue here is that those old processes hold on to a lot of RAM, eventually choking the instance.

**Comment by lukastribus** [comment]
Well, this is really what `hard-stop-after` is about indeed.

Now in both your cases there is the possibility that this is about a bug in haproxy (and not necessarily the same); however it is also true that without any bugs and without hard-stop-after, an attacker can easily and with low costs keep your obsolete processes up and running for a very long time, starving your instances to dead anyway.

So yes, I would strongly suggest using `hard-stop-after` in every case.

Regarding the issue, there are a number of issues fixed after 1.8.20, so running more uptodate code would probably be a good idea. You could get a 1.8 snapshot tarball, clone from 1.8 git or wait for the 1.8.21 release, which I assume is happening soon.

**Comment by wtarreau** [comment]
By the way regarding hard-stop-after, in 2.0 with master-worker there is a nice new feature called "mworker-max-reloads" which indicates how many reloads a child will resist to. It's even better because it can guarantee that you'll never have more than X concurrent processes regardless of your reload frequency.

I've looked at post-1.8.20 changes and found this fix which addresses an issue affecting H2 which could occasionally result in dead connections lying forever, and thus possibly prevent the old process from leaving:
   e7c30a336 ("BUG/MEDIUM: mux-h2: make sure the connection timeout is always set")

For other ones I don't see how they could have any such impact. We'll try to issue 1.9 and 1.8 soon with a reasonable definition of "soon".

**Comment by krzysztof-bronk** [comment]
Thank you for the response :) I'm trying hard-stop-after at the moment, and it seems to work as advertised, RAM is kept in check!
