### ISSUE TITLE
TCP Connection reset during traffic to frontend when backend connection is closed and complete

### ISSUE THREAD

**Issue by sjursky** [haproxy/haproxy#157]
## Output of `haproxy -vv` and `uname -a`

```
docker exec -it haproxy_reverse-proxy_1 haproxy -vv
HA-Proxy version 1.8.20 2019/04/25
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE2=1 USE_PCRE2_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.0j  20 Nov 2018
Running on OpenSSL version : OpenSSL 1.1.0j  20 Nov 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE2 version : 10.22 2016-07-29
PCRE2 library supports JIT : yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace 

docker exec -it haproxy_reverse-proxy_1 uname -a   
Linux a917858e64ee 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 GNU/Linux
```

## What's the configuration?

```
haproxy.cfg

global
        log 127.0.0.1:514 local0 debug  # IP in pcap 172.18.0.2
        daemon
        user root
        group root
        maxconn 4096
defaults
        log global
        mode http
        option httplog
        option dontlognull
        option redispatch
        option nolinger
        timeout connect 5000
        timeout check 5000
        timeout http-keep-alive 10s
        timeout client 200000
        timeout server 200000

frontend main
    bind *:80
    acl url_nasp path_beg /nasp/app/ui
    use_backend         apache  if url_nasp
    default_backend     generate_404

backend apache
    mode http
    balance roundrobin
    server apache foo.bar:80  # IP in pcap 192.168.143.92
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    option forwardfor
    option httpchk HEAD / HTTP/1.0

backend generate_404
    errorfile 503 /usr/local/etc/haproxy/generate_404.http
```

## Steps to reproduce the behavior

1. Have a backend server serving a big file over HTTP. In our case it was Apache server and file with size over 80kB.
2. Have a remote client on same LAN but not on same host as HAProxy. Network "fast" localhost clients on HAProxy machine are OK and not affected by this.
3. Call a GET request on a big file over HAProxy and include `Connection: close` in request headers. This is a MUST, it will not happen with `Connection: keep-alive` as it will not close the TCP connection after the request is complete.

## Actual behavior

When calling that big file, on response, the TCP connection is reset in traffic.

Numbers in [brackets] represents actual packet No. in pcap capture (see attached bellow)
When response from backend is complete [9] and that TCP connection between backend and HAProxy is properly closed (FIN+ACK, ACK, [91,93]), HAProxy will reset connection to client (RST+ACK [94]) during traffic and client will receive incomplete response from HAProxy with last data packet [92].

Wireshark filters:
tcp.stream eq 2  -----> Client vs. HAProxy   (192.168.136.221 vs. 172.18.0.2)
tcp.stream eq 3  -----> HAProxy  vs. Apache backend (172.18.0.2 vs. 192.168.143.92)

## Expected behavior

HAProxy should send all the data packets before it RST+ACK the connection to client.

Localhost clients on HAProxy machine are fine. Transfer is fast enough so all data packets arrive before RST,ACK conneciton from HAProxy.
Wireshark filters for local client:
tcp.stream eq 0  -----> Client vs. HAProxy   (192.168.130.46 vs. 172.18.0.2)
tcp.stream eq 1  -----> HAProxy  vs. Apache backend (172.18.0.2 vs. 192.168.143.92)

## Do you have an idea how to solve the issue?

This behavior was also reproduced on HAProxy 2.0.1.
However it can't be reproduced on Nginx 1.16.

## Attachments (packet capture)

tcpdump:
[naspdump-hap-1820.zip](https://github.com/haproxy/haproxy/files/3367107/naspdump-hap-1820.zip)

**Comment by lukastribus** [comment]
Don't use `option nolinger`, the documentation specifically warns against this:

https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#4-option%20nolinger

**Comment by sjursky** [comment]
@lukastribus Yes, that will do it. Not using this direction will work. But documentation states:
> When clients or servers abort connections in a dirty way (e.g. they are
physically disconnected)

There was no dirty way from backend in capture. See packet No. [89-93] you can see normal 3way handshake with FIN, FIN+ACK, ACK flags.

**Comment by capflam** [comment]
This part is just an explanation about the accumulation of connections in FIN_WAIT1 state because of dirty aborts. 

When the option `nolinger` is set, all connections are quickly closed. we speak about hard close in this case. It means the connections are closed with a reset. So all pending data are lost. It is the expected behaviour here.

**Comment by sjursky** [comment]
@capflam thank you for better explanation, closing this as expected behavior (one does not simply use nolinger :)
