### ISSUE TITLE
probable leak in src/session.c

### ISSUE THREAD

**Issue by asuffield** [haproxy/haproxy#1596]
https://github.com/haproxy/haproxy/blob/5bcfd33063a460ed6efafa840e354e383d4252c0/src/session.c#L191

I'm pretty sure this should be out_free_sess. It was moved in https://github.com/haproxy/haproxy/commit/1b3c931bffbac8ffb3efb1b489f7572be219e6e8 and now comes after the new_session call.

**Comment by wtarreau** [comment]
I agree, good catch! Also quic_sock needs to be rechecked in 2.5 as it was changed with that code as well, but in latest -dev it was fixed.

**Comment by wtarreau** [comment]
Now fixed, thank you! In the end (and purely by chance) the bug cannot be triggered because none of the two available transport layers is able to return <0 here. Regardless I've marked it for backport for long-term reliability.
