### ISSUE TITLE
No support of mqtt_is_valid and mqtt_field_value for proxy-protocol connection

### ISSUE THREAD

**Issue by dhruvjain99** [haproxy/haproxy#1598]
### Detailed Description of the Problem

In the following mqtt connection flow, mqtt_is_valid and mqtt_field_value is not working as intended.

Client -> Google Load Balancer(proxy-protocol enabled) -> HAProxy

Currently the connection is rejected if the ACL rule(https://pastebin.mozilla.org/TESFMj1b#L57) is mentioned in the frontend config. Also, if this rule is omitted then mqtt_field_value does not work due to which there is no entry in the stick table. Logs of the HAProxy config mentioned in the pastebin can be found [here](https://pastebin.mozilla.org/8q0dUseO).

I have tried adding accept-proxy(https://pastebin.mozilla.org/GeC047TW#L53) but it still doesn't work. 
Also, if I strip the actual source(client) ip using accept-proxy, then enabling proxy-protocol on the google load balancer won't be of any use. 

### Expected Behavior

`tcp-request content reject unless { req.payload(0,0),mqtt_is_valid }` should not reject a valid mqtt request via proxy-protocol enabled google load balancer. There should be an entry in the stick table with the key as client_identifier.

### Steps to Reproduce the Behavior

1. Add `tcp-request content reject unless { req.payload(0,0),mqtt_is_valid }` rule in frontend.
2. Add 
```
  # Create a stick table for session persistence
  stick-table type string len 200 size 1m expire 24h
  # Use ClientID / client_identifier as persistence key
  stick on req.payload(0,0),mqtt_field_value(connect,client_identifier)
```
in the backend for sticky-sessions.
3. Route traffic to HAProxy via google load balancer (any proxy) with proxy-protocol enabled.
4. Try with/without accept-proxy.

### What is your configuration?

```haproxy
global
  maxconn 524000
  log /dev/log local0
  log /dev/log local1 notice
  chroot /var/lib/haproxy
  stats socket /run/haproxy/admin.sock mode 660 level admin
  stats socket ipv4@127.0.0.1:9999 level admin
  stats timeout 30s
  user haproxy
  group haproxy
  daemon
​
# Default SSL material locations
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private
  ssl-default-bind-options no-sslv3
  ssl-default-bind-ciphers ALL:!ADH:!EXP:!LOW:!RC2:!3DES:!SEED:!kEDH:!aNULL:!RC4:+HIGH:+MEDIUM
  tune.ssl.default-dh-param 2048
​
defaults
  log global
  mode tcp
  balance roundrobin
  option tcplog
  option dontlognull
  option dontlog-normal
  option http-server-close
  timeout connect 20s
  timeout client 60s
  timeout server 50s
  timeout http-request 50s
  timeout tunnel 3600s
  timeout http-keep-alive 20s
  timeout queue 2s
  timeout tarpit 60s
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http
​
listen haproxy-status
  mode http
  bind ip:1936
  stats enable
  stats uri /stats
  stats refresh 15s
  stats show-node
​
frontend vernemq_frontend
  bind :8000
  maxconn 520000
  option tcplog
  log global
  tcp-request content reject unless { req.payload(0,0),mqtt_is_valid }
  tcp-request inspect-delay 2s
  tcp-request content reject if HTTP
  acl fmoi_cidr_range src x.x.x.x/y.y.y.y/z
  use_backend vernemq_send_proxy if fmoi_cidr_range
  default_backend vernemq
​
frontend vernemq_http_frontend
  bind :80
  maxconn 5000
  default_backend vernemq_http
​
backend vernemq
  mode tcp
  maxconn 520000
  option httpchk GET /health
  # Create a stick table for session persistence
  stick-table type string len 200 size 1m expire 24h
  # Use ClientID / client_identifier as persistence key
  stick on req.payload(0,0),mqtt_field_value(connect,client_identifier)
  server verne-0-0 ip:1883 maxconn 90000 check port 8888
  server verne-0-1 ip:1884 maxconn 90000 check port 8888
​
backend vernemq_send_proxy
  mode tcp
  maxconn 520000
  option httpchk GET /health
  # Create a stick table for session persistence
  stick-table type string len 2000 size 1m expire 24h
  # Use ClientID / client_identifier as persistence key
  stick on req.payload(0,0),mqtt_field_value(connect,client_identifier)
  server verne-0-0 ip:1883 maxconn 90000 check port 8888 send-proxy
  server verne-0-1 ip:1884 maxconn 90000 check port 8888 send-proxy
​
backend vernemq_http
  mode http
  option httpchk GET /health
  server verne-0 ip:8888 check port 8888
​
backend bad_backend
  mode http
  errorfile 403 /etc/haproxy/errors/403.http
```
```


### Output of `haproxy -vv`

```plain
`haproxy -vv`:

HAProxy version 2.4.2-1ppa1~focal 2021/07/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.2.html
Running on: Linux 5.8.0-1038-gcp #40~20.04.1-Ubuntu SMP Thu Jul 15 11:55:03 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-IXRjPg/haproxy-2.4.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

`uname -a`: `Linux VM_NAME 5.8.0-1038-gcp #40~20.04.1-Ubuntu SMP Thu Jul 15 11:55:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
```


### Last Outputs and Backtraces

_No response_

### Additional Information

_No response_

**Comment by capflam** [comment]
Without `accpet-proxy` keyword, this cannot work. However, It is not clear for me if the behavior is still the same with `accpt-proxy` keyword on the bind line. I've performed some tests with HAProxy only, with a pure-TCP frontend redirecting the traffic on an internal MQTT proxy using the PROXY protocol to finally send everything to a MQTT server and it works as expected. The ACLs and the stickiness.

Could you provide HAProxy logs with the `accpet-proxy` protocol ? Note that, at this stage, you should also consider to get a network capture to understand the problem.

**Comment by capflam** [comment]
There is also something strange in your backends config. Servers on one backend use the PROXY protocol while servers of the other don't. Are you sure you are not sending traffic without the PROXY protocol to servers that expect to receive it ?

**Comment by dhruvjain99** [comment]
The backend without send-proxy serves all the connections coming from
Google load balancer with proxy-protocol enabled and SSL. There is an
update in the findings that when I disabled proxy-protocol on the google
load balancer, still the mqtt_is_valid rule rejected the connection. We
need to check if disabling SSL would help.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/07/22,
03:22:59 PM

**Comment by TimWolla** [comment]
As a reference, there's also a mailing list thread here: https://www.mail-archive.com/haproxy@formilux.org/msg41915.html

**Comment by capflam** [comment]
There is no SSL configured on your frontends. So this cannot work. You cannot expect to analyze MQTT messages if the traffic is encrypted. In addition, if your servers expect to receive a PROXY protocol header, you must add one of `send-proxy` keywords, depending on your config.

**Comment by capflam** [comment]
In addition, if the server traffic is encrypted too, you must configure SSL on your server lines. At this stage, I think it is more an issue with your configuration than a bug. Or I missed something.

**Comment by dhruvjain99** [comment]
I meant by disabling SSL on Google load balancer which is public internet
facing even though we had terminated SSL before relaying the request from
Google load balancer to HAProxy in the earlier cases which is the reason
why SSL is not configured on HAProxy. On further investigation, we found
that HAProxy mqtt_is_valid and mqtt_field_value does not support mqtt v3.1
. Since we were using mqtt v3.1, it was not working as expected.
We found this by taking tcpdump on HAProxy and analysing the packets for
working and non-working clients. We found that the protocol name and level
in the CONNECT control packet payload header was different.
So, mqtt_is_valid and mqtt_field_value parses only v3.1.1 and v5.0
correctly.

Thank you so much for coordinating on this issue. Really appreciate the
HAProxy team.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/08/22,
11:03:26 AM

**Comment by dhruvjain99** [comment]
Ref:
https://github.com/haproxy/haproxy/blob/5bcfd33063a460ed6efafa840e354e383d4252c0/src/mqtt.c#L697-L708



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/08/22,
11:06:17 AM

**Comment by dhruvjain99** [comment]
Closing this issue in lieu of #1600
