### ISSUE TITLE
Support of mqtt_is_valid and mqtt_field_value for mqtt v3.1

### ISSUE THREAD

**Issue by dhruvjain99** [haproxy/haproxy#1600]
### Your Feature Request

HAproxy mqtt_is_valid and mqtt_field_value should support mqtt v3.1. Adding this support would prevent mqtt v3.1 connections getting dropped due to `tcp-request content reject unless { req.payload(0,0),mqtt_is_valid }` and help these connections stick to backend using mqtt_field_value.

Currently, the support is only for v3.1.1 and v5.0. Ref: https://github.com/haproxy/haproxy/blob/5bcfd33063a460ed6efafa840e354e383d4252c0/src/mqtt.c#L697-L708

### What are you trying to do?

Since our app is currently on mqtt v3.1, moving it HAProxy 2.4 with `tcp-request content reject unless { req.payload(0,0),mqtt_is_valid }` and sticky-sessions won't support the clients with v3.1. Adding support for v3.1 would add backward compatibility to sticky-sessions feature.

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.2-1ppa1~focal 2021/07/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.2.html
Running on: Linux 5.8.0-1038-gcp #40~20.04.1-Ubuntu SMP Thu Jul 15 11:55:03 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-IXRjPg/haproxy-2.4.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by git001** [comment]
From my point of view is this part which checks the Version.

https://github.com/haproxy/haproxy/blob/5bcfd33063a460ed6efafa840e354e383d4252c0/src/mqtt.c#L724-L730

Maybe you can send a patch to the list after you have read the https://github.com/haproxy/haproxy/blob/master/CONTRIBUTING

**Comment by dhruvjain99** [comment]
Sure, I'll soon raise a patch for it.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/08/22,
02:29:46 PM

**Comment by capflam** [comment]
Indeed, it could be done quite easily. Note the protocol name is also not the same. Anyway, contribution are welcome !

**Comment by dhruvjain99** [comment]
I have sent a patch. Ref: https://www.mail-archive.com/haproxy@formilux.org/msg41995.html

**Comment by capflam** [comment]
It was pushed. I performed very naive test and it works. Thanks ! It will be backported soon, with other patches in the pipe.
I will update the documentation,I just realized it was not updated...

**Comment by dhruvjain99** [comment]
Great! Thank you so much for the acknowledgment.

**Comment by dhruvjain99** [comment]
@capflam I see that the fix is part of [[RELEASE] Released version 2.6-dev4](https://git.haproxy.org/?p=haproxy.git;a=commit;h=0541c2b978c51f8ac3f262988b658b23eeed1842). Just wanted to know if we have any timeline/approximate idea in what time will it be backported to the stable 2.4 branch. Maybe if you can redirect me to the documentation which mentions it.

This would help us plan our releases accordingly. 
Thanks.

**Comment by capflam** [comment]
I'm on the backports. Thus it will be available soon in stable versions. However, for now, next releases are not planned. We'll see once all fixes will be backported.

**Comment by capflam** [comment]
FYI, It was backported to 2.5 and 2.4

**Comment by dhruvjain99** [comment]
Thank you so much for the updates. Really appreciate it. 👍

**Comment by dhruvjain99** [comment]
@capflam Do we have any updates on the next stable release dates of v2.4 and v2.5?

**Comment by capflam** [comment]
It was backported to the 2.5 and I'm on the release. It will be emitted today. The next 2.4 will be emitted soon, probably the end of the week.
