### ISSUE TITLE
Haproxy sometimes stop working

### ISSUE THREAD

**Issue by xiddjp** [haproxy/haproxy#1601]
### Detailed Description of the Problem

Haproxy sometimes stop working

### Expected Behavior

working fine

### Steps to Reproduce the Behavior

run haproxy 

### Do you have any idea what may have caused this?

no

### Do you have an idea how to solve the issue?

restart haproxy

### What is your configuration?

```haproxy
#HA Proxy Config
global
 ulimit-n 500000
 maxconn 99999
 maxpipes 99999
 tune.maxaccept 500

 log 127.0.0.1 local0
 log 127.0.0.1 local1 notice

 ca-base /etc/ssl/certs
 crt-base /etc/ssl/private

 ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
 ssl-default-bind-options no-sslv3

defaults

 log global

 mode http

 timeout connect 5000ms
 timeout client 50000ms
 timeout server 50000ms
 timeout tunnel  1h    # timeout to use with WebSocket and CONNECT

 default-server init-addr none
```

### Output of `haproxy -vv`

```plain
uname -a output:
Linux david 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

how to run 'haproxy -vv' in docker mode?
```

### Last Outputs and Backtraces

```plain
2022-03-08 11:14:24,918 INFO supervisord started with pid 1
2022-03-08 11:14:25,921 INFO spawned: 'crond' with pid 22
2022-03-08 11:14:25,924 INFO spawned: 'haproxy' with pid 23
2022-03-08 11:14:25,960 INFO success: haproxy entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-08 11:14:25,960 INFO exited: haproxy (exit status 0; expected)
2022-03-08 11:14:26,961 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-09 05:29:29,223 INFO reaped unknown pid 175 (terminated by SIGABRT (core dumped))
```

**Comment by git001** [comment]
> how to run 'haproxy -vv' in docker mode?

You can try to run one of these command.

```
docker run -it --rm --entrypoint /usr/local/sbin/haproxy haproxy -vv
# or
podman run -it --rm --entrypoint /usr/local/sbin/haproxy haproxy -vv
```

**Comment by xiddjp** [comment]
> > how to run 'haproxy -vv' in docker mode?
> 
> You can try to run one of these command.
> 
> ```
> docker run -it --rm --entrypoint /usr/local/sbin/haproxy haproxy -vv
> # or
> podman run -it --rm --entrypoint /usr/local/sbin/haproxy haproxy -vv
> ```

Now the haproxy is working, waiting for stop working status, current output is:

HA-Proxy version 2.2.12-a723e77 2021/03/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.12.html
Running on: Linux 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.35 2020-05-09
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app

**Comment by xiddjp** [comment]
> > how to run 'haproxy -vv' in docker mode?
> 
> You can try to run one of these command.
> 
> ```
> docker run -it --rm --entrypoint /usr/local/sbin/haproxy haproxy -vv
> # or
> podman run -it --rm --entrypoint /usr/local/sbin/haproxy haproxy -vv
> ```
Hi, reproduced this issue, this is docker logs and haproxy -vv output log:

$
sysuser@template2004 ~/lm/gw-docker$ sudo docker logs 406476bbfc76
Adding qdisc plug dev lo id 40: parent 1:4
  refcnt 0no options
Adding qdisc plug dev lo id 40: parent 1:4
  refcnt 0no options
2022-03-07 14:07:55,011 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-03-07 14:07:55,016 INFO supervisord started with pid 1
2022-03-07 14:07:56,025 INFO spawned: 'crond' with pid 33
2022-03-07 14:07:56,027 INFO spawned: 'haproxy' with pid 34
2022-03-07 14:07:56,033 INFO success: haproxy entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-07 14:07:57,098 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-07 14:07:57,099 INFO exited: haproxy (exit status 0; expected)
2022-03-08 00:02:34,478 INFO reaped unknown pid 37 (exit status 0)
2022-03-08 12:31:54,647 INFO reaped unknown pid 55 (exit status 0)
2022-03-09 00:53:23,230 INFO reaped unknown pid 74 (exit status 0)
2022-03-09 12:49:16,255 INFO reaped unknown pid 93 (exit status 0)
2022-03-10 00:38:39,245 INFO reaped unknown pid 112 (exit status 0)
sysuser@template2004 ~/lm/gw-docker$
sysuser@template2004 ~/lm/gw-docker$
sysuser@template2004 ~/lm/gw-docker$
sysuser@template2004 ~/lm/gw-docker$
sysuser@template2004 ~/lm/gw-docker$ sudo docker exec -it 406476bbfc76 /usr/local/sbin/haproxy -vv
HA-Proxy version 2.2.12-a723e77 2021/03/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.12.html
Running on: Linux 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.35 2020-05-09
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app

**Comment by TimWolla** [comment]
> Known bugs: http://www.haproxy.org/bugs/bugs-2.2.12.html

Upgrade, please. HAProxy 2.2.12 is affected by a 3-digit number of bugs, as you can see at that link. The current version is 2.2.21.

**Comment by git001** [comment]
This is not a docker hub image.

> sysuser@template2004 ~/lm/gw-docker$ sudo docker logs 406476bbfc76
> Adding qdisc plug dev lo id 40: parent 1:4
> refcnt 0no options
> Adding qdisc plug dev lo id 40: parent 1:4
> refcnt 0no options
> 2022-03-07 14:07:55,011 CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
> 2022-03-07 14:07:55,016 INFO supervisord started with pid 1
> 2022-03-07 14:07:56,025 INFO spawned: 'crond' with pid 33
> 2022-03-07 14:07:56,027 INFO spawned: 'haproxy' with pid 34
> 2022-03-07 14:07:56,033 INFO success: haproxy entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
> 2022-03-07 14:07:57,099 INFO exited: haproxy (exit status 0; expected)

What's your modification of the image?
How do you start haproxy from supervisord?

Please also not that we use this issue tracker for bug reports and feature request, not generic support.

I suggest the mailing list for development related discussions.

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org

thanks @lukastribus for the text :smile:

**Comment by capflam** [comment]
In addition, if you really think there is a bug, it could be good to share the full config. There is no frontend/backend config. Note also that, AFAIK, supervisord expects to run program in foreground. Thus don't demonize HAProxy.

**Comment by capflam** [comment]
I'm closing this issue, because it seems to be outside HAProxy. At least we need more info to investigate. Thanks !
