### ISSUE TITLE
H2: configure the per-stream initial window size independently on each side

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#1607]
### Your Feature Request

`tune.h2.initial-window-size` allows to configure the H2 initial window size, which is the window size each stream will use. Setting it too low on high latency links will limit upload bandwidths. Setting it too high on low bandwidth links will cause head-of-line blocking.

Given that servers are usually very close to haproxy with high bandwidth (hence can experience small windows) and clients are far away with a low bandwidth (hence not only suffer from small windows, but also limit the ability to drain a server's response), it would make a lot of sense to configure the frontend stream window to a high value (256-512kB maybe), since multiple clients are almost never coalesced over a single connection on the front side, and conversely use a small window on the backend side (one buffer size) so that coalesced clients over that connections do not hinder each other.

The current parameter acts on both sides and it would be nice to be able to tune it per side. It would make sense to make it configurable per-server and per-bind, but frontend/backend would also work fine, and in this case keeping the current setting as a default one for the whole stack remains OK.

Being able to express the value as a ratio of the buffer size could have some interest as well (e.g. store it negative for ratios or positive for absolute).

### What are you trying to do?

Increase POST upload speed without causing head-of-line blocking on downloads (or conversely).

### Output of `haproxy -vv`

```plain
2.6-dev3, but was planned for 2.4.
```

**Comment by wtarreau** [comment]
See also related developers' note #352.

**Comment by maxmoehl** [comment]
> The current parameter acts on both sides and it would be nice to be able to tune it per side. It would make sense to make it configurable per-server and per-bind, but frontend/backend would also work fine, and in this case keeping the current setting as a default one for the whole stack remains OK.

Seems like this is implemented via `tune.h2.fe.initial-window-size` and `tune.h2.be.initial-window-size`, or am I missing something?

**Comment by wtarreau** [comment]
You're right, I didn't remember there was an issue for that one, now closing.
