### ISSUE TITLE
Simplify retries counter calculation

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#1608]
The current method used to count retries is dated and has experienced many changes over time without being reworked, resulting in something error-prone when trying to add new code, as well as something difficult to debug.

We currently store the number of retries left, and all calculations of redispatch or reporting of number of retries experienced are made using subtracts from the configured retries, which is complicated and doesn't bring any benefit.

We should just change that to store the counter of retries and compare it to the configured one when taking decisions. The rest will be greatly simplified.

**Comment by capflam** [comment]
It was finally addressed.
