### ISSUE TITLE
Allow Bandwith limitations based on throughput

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#1618]
### Your Feature Request

HAProxy should be able to limit the connections based on bandwidth consumption based on *bps.

### What are you trying to do?

It would be nice to have the capability to limit the bandwidth on specific parts

  * Hosts (SNI, HTTP)
  * URL (Path, query, ...)
  * SPOE vars
  * Client

Currentrly is a limitation possible with connections and sessions but not based on consumed bandwidth 

### Output of `haproxy -vv`

```plain
Future version
```

**Comment by git001** [comment]
Looks like with this commit https://github.com/haproxy/haproxy/commit/2b6777021d5586fbe02a07f9930a7274f5a400e7 can this issue be closed

**Comment by TimWolla** [comment]
Thanks, added the Fixed label.
