### ISSUE TITLE
clang 14 syntax errors

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1638]
### Tool Name and Version

clang 14

### Code Report

```plain
CC      src/ssl_sock.o
In file included from In file included from src/ev_epoll.c:24:
include/haproxy/task.h:190:10: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        return (!!(global_tasks_mask & tid_bit) |
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                ||
include/haproxy/task.h:190:10: note: cast one or both operands to int to silence this warning
src/ev_poll.c:25:
include/haproxy/task.h:190:10: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        return (!!(global_tasks_mask & tid_bit) |
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                ||
include/haproxy/task.h:190:10: note: cast one or both operands to int to silence this warning
1 error generated.
make: *** [Makefile:991: src/ev_poll.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [Makefile:991: src/ev_epoll.o] Error 1
In file included from src/ssl_sample.c:28:
In file included from include/haproxy/conn_stream.h:26:
In file included from include/haproxy/applet.h:31:
include/haproxy/task.h:190:10: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        return (!!(global_tasks_mask & tid_bit) |
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                ||
include/haproxy/task.h:190:10: note: cast one or both operands to int to silence this warning
1 error generated.
make: *** [Makefile:991: src/ssl_sample.o] Error 1
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
Compilers are really becoming pathetic... Most often you end up with cond jumps with || and with binary ops with |. Maybe they've become a bit smarter nowadays but in the past this used to make huge differences on critical paths. We'll check if placing parenthesis around works around it.

**Comment by wtarreau** [comment]
I can't make it complain with clang-14 on godbolt, I don't know what to think about it, but I'm embarrassed to try to work around it. I tried this, in case you'd want to try with your local version:
```
int testme(int *a, int *b, int *c, int *d)
{
    return !(*a) | !!(*b & 1) | !(*c & 2) | !(*d);
}
```
However it's obvious that it produces much better code than with the `||` that emits no less than 3 cond jumps.

**Comment by chipitsine** [comment]
my "local" is Fedora Rawhide. I'll try soon

**Comment by chipitsine** [comment]
I've created dedicated repo: https://gitlab.com/chipitsine/clang14-rawhide

it contains [sample code](https://gitlab.com/chipitsine/clang14-rawhide/-/blob/main/test.c) above
and [clang14 pipeline](https://gitlab.com/chipitsine/clang14-rawhide/-/blob/main/.gitlab-ci.yml)


it [runs](https://gitlab.com/chipitsine/clang14-rawhide/-/jobs/2333016511) without errors

**Comment by chipitsine** [comment]
however, haproxy [still fails](https://gitlab.com/chipitsine/haproxy-ci-playground/-/jobs/2332214534) on Fedora Rawhide

**Comment by wtarreau** [comment]
You'll need to pass the optims and warnings flags. Could you please try again with the following ones to match what we're using by default:
```
-O2 -Wall -Wextra -Werror -Wbitwise-instead-of-logical -Wundef -Wdeclaration-after-statement -Wtype-limits -Wshift-negative-value   -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
```

**Comment by wtarreau** [comment]
I also tried with some equality tests but no issue for now: https://godbolt.org/z/odeMqexnW
I don't know what criterion it triggers on, thus, but I disagree with the approach since it suggests to change the code to do something different and may result in introducing serious bugs when one expects that all members of the expression are evaluated, because replacing '|' with '||' will only evaluate the first ones till one is true, which is absolutely not the same!

**Comment by wtarreau** [comment]
Just in case, could you please check if casting each expression to `int` works around it ?
```
--- a/include/haproxy/task.h
+++ b/include/haproxy/task.h
@@ -185,12 +185,12 @@ static inline int task_in_wq(struct task *t)
 }
 
 /* returns true if the current thread has some work to do */
static inline int thread_has_tasks(void)
 {
-       return (!!(global_tasks_mask & tid_bit) |
-               !eb_is_empty(&th_ctx->rqueue) |
-               !!th_ctx->tl_class_mask |
-               !MT_LIST_ISEMPTY(&th_ctx->shared_tasklet_list));
+       return ((int)!!(global_tasks_mask & tid_bit) |
+               (int)!eb_is_empty(&th_ctx->rqueue) |
+               (int)!!th_ctx->tl_class_mask |
+               (int)!MT_LIST_ISEMPTY(&th_ctx->shared_tasklet_list));
 }
 
```

**Comment by chipitsine** [comment]
> You'll need to pass the optims and warnings flags. Could you please try again with the following ones to match what we're using by default:
> 
> ```
> -O2 -Wall -Wextra -Werror -Wbitwise-instead-of-logical -Wundef -Wdeclaration-after-statement -Wtype-limits -Wshift-negative-value   -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
> ```

it is [still green](https://gitlab.com/chipitsine/clang14-rawhide/-/jobs/2336273717#L1584)


I tested your patch (locally), it fixes clang errors

**Comment by wtarreau** [comment]
OK thank you Ilya. We still don't know what crazy heuristic they invented just to annoy us but at least there is a solution that doesn't deteriorate the code too much.

**Comment by wtarreau** [comment]
Workaround now applied, it should be OK now. Thanks!
