### ISSUE TITLE
Error 400 on HTTP/1.1 Websocket Connection Upgrade v2.4+

### ISSUE THREAD

**Issue by etfloyd** [haproxy/haproxy#1642]
### Detailed Description of the Problem

HTTP/1.1  request with "Connection: Upgrade" and "Upgrade: websocket" headers fails with error 400 <BADREQ> on HAProxy v2.4.0 and above

### Expected Behavior

HAProxy should handle the request rather than reject it with 400 <BADREQ>. The same request is properly handled on HAProxy v2.3.19. Eliminating either header allows the request to be properly handled on HAProxy v2.4.15.

### Steps to Reproduce the Behavior

1. On a Linux machine with Docker, create this `haproxy.cfg`:
```
global
  log stdout format raw local0

defaults
  log global
  option httplog clf
  option dontlognull
  mode http
  timeout client 60s
  timeout connect 60s
  timeout server 60s
  errorfile 503 /usr/local/etc/haproxy/error503.http

frontend incoming
  bind 0.0.0.0:8080
  default_backend none
  
backend none
```
and this http errorfile named `error503.http`:
```
HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <title>Error 503</title>
    </head>
    <body>
        <div>
            <h1>Made it to backend!</h1>
        </div>
    </body>
</html>
```
in the current directory.

2. Start haproxy like this:
```
docker run -d --name haproxy -v$(pwd):/usr/local/etc/haproxy --net host haproxy:2.3.19-alpine
```

3. Run this curl command:
```
curl -v -i -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" http://localhost:8080/
```

4. Note the output and haproxy logs 
```
docker logs haproxy
```

5. Stop haproxy and rerun version 2.4.15:
```
docker rm -f haproxy
docker run -d --name haproxy -v$(pwd):/usr/local/etc/haproxy --net host haproxy:2.4.15-alpine
```

6. Repeat step 3 and 4.

7. Remove one of the headers from the curl command:
```
curl -v -i -H "Connection: Upgrade" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" http://localhost:8080/
```
8. Repeat steps 3 and 4.

### What is your configuration?

```haproxy
See Steps to Reproduce
```

### Output of `haproxy -vv`

```plain
N/A
```

### Additional Information

The Steps to Reproduce above are contrived to demonstrate with minimal configuration that when those two headers are present, the request never reaches the backend on HAProxy v2.4.15. We don't actually upgrade the connection in either demo scenario above. The `none` backend has no servers, so throws a 503 if the request actually reaches it, which triggers the errorfile. In the logs, you can see that the request reaches the `none` backend every time on HAProxy v2.3.19. It does not reach the backend on HAProxy v2.4.15 with the two headers. 

In the real-world application, there are additional websocket-related headers: Host, Origin, Sec-WebSocket-Version, Sec-WebSocket-Key. Those headers do not trigger the problem. It all works fine when we bypass HAProxy and go directly to the application pod - upgrades the connection and leaves it open, as expected. It all works fine through HAProxy as long as we use v2.3.19 or below.

**Comment by capflam** [comment]
There is no websocket key. You must add it via the `Sec-WebSocket-Key` header. It is mandatory. On 2.3 and prior, this header is not checked because there is no explicit support for websocket. Since the 2.4, WebSockets over H2 is supported. It requires some processing on messages, especially to support H2 to H1 communications, or the opposite. Thus, the key is now mandatory.

**Comment by etfloyd** [comment]
As noted in Additional Information, in our real-world use case, `Sec-WebSocket-Key` header is present. It still fails on v2.4.15 but not on v2.3.19. Try it:
```
curl -v -i -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" http://localhost:8080/
```
For the demo, for _your_ convenience, I pared it down to the minimum that can reproduce the problem. H2 is not involved. I've added the `Sec-WebSocket-Key` header to the steps above. Feel free to add whatever additional headers you want. The result is still the same. Seriously, if it were that easy, I wouldn't have filed a bug report. This has cost us many hours, potentially delayed a production implementation, and caused us to have to regress a major component of our infrastructure.

Can you reopen this bug report or do I need to file a new one?

**Comment by capflam** [comment]
Your key is invalid. It must be a random 16-bytes string encoded in base64. Thus the encoded key must have 24 characters. Your encoded key contains only 20 characters.

**Comment by capflam** [comment]
Note that there is no key for H2 WebSocket. This explains why it works.

**Comment by etfloyd** [comment]
Ha! That did it. Will report this to the app testers. Apologies for your trouble.
