### ISSUE TITLE
shctx_lock() limits the cache's scalability to around 1.

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#1651]
### Detailed Description of the Problem

When testing the cache with small non-cacheable objects (10kB) the performance appears seriously limited and whatever the number of threads, the CPUs are often heavily used. `perf top` shows that `shctx_lock()` takes all the CPU with 32 threads:
- with cache hits, 55% at 550k RPS = 1 µs per call
- with cache misses of empty objects (store headers only), 76% at 140k RPS = 5.5 µs per call
- with cache misses of 10kB objects, 84% at 100k RPS = 8.4 µs per call
- with misses of 100kB objects, 73% at 23k RPS = 31.7µs per call

The lock could be turned to an upgradable RW lock but it would probably not change much since plenty of operations require to move the blocks between the hot and the avail lists and these operations are currently locked. Probably that switching to MT lists would become a significant improvement but this has not been studied yet.

The main problem isn't as much the lock itself as what's done under the lock. Functions `shctx_row_inc_hot()` and `shctx_row_dec_hot()` move the blocks between the lists by iterating over them, thus the larger the object, the more numerous they are. There is a `last_append` field in the first block that indicates the last one of the list, so it should theoretically be possible to detach a sub-list at once and re-insert it into the other list, all in O(1), bringing the cost back to the misses of empty objects. However that field is not always initialized nor valid, and while that ought to be done in `shctx_row_reserve_hot()`, that function is horrendous and has been known for breaking several times in the past (which is the reason why nobody touches it). adding `if (!ret->last_append) ret->last_append=ret` and pre-setting `ret->last_append` to NULL when ret is first assigned *seems* to do the job but it's hard to tell if it's always right. It might even be possible that last_reserved has to be used instead.

It's not critical, the pref remains acceptably good and this can be addressed after 2.6 but it's important to address this because this code is old, brittle and inefficient and it cannot be worked on late in the development cycle due to the risk of breaking something odd.

### Expected Behavior

The cache should scale better, its perf degrades quickly above 6-8 threads if it needs to store a lot (i.e. high miss rate). At 6 threads, downloading 10kB without caching results in 280k req/s at 25 Gbps and 4.3 CPUs used, while storing into the cache slows down to 167k req/s and 13 Gbps at 6 CPUs used. At 48 threads that's down to 100k rps and 8 Gbps for 48 CPUs used and 84% CPU in the lock.

### Steps to Reproduce the Behavior

Request random objects being store into the cache.

### Do you have any idea what may have caused this?

The list manipulation under the lock.

### Do you have an idea how to solve the issue?

- 1st step, rewrite `shctx_row_reserve_hot()` and make sure the last_* pointers are always valid and that it doesn't leak any block in case insufficient blocks are found (it seems to be the case right now)
- 2nd step, move lists in O(1) to reduce the cost of the lock
- 3rd step, change `shctx_row_data_append()` to drop `from` and use `first->last_append` instead
- 4th step, change `shctx_row_inc_hot()` and `shctx_row_dec_hot()` to move lists at once instead of looping from the first block
- 5th step, study if some list operations can be turned to mt_lists in order to drop the lock at certain steps
- 6th step, see if it can be useful to turn the lock into an R/W lock (it seems the SSL cache lookup could benefit from this at least). That might also be useful for cache hits if the switch from hot to avail can be made atomic so that there's no more need to take an exclusive lock there.

### What is your configuration?

```haproxy
(... plenty of debugging junk ...)

listen l1
        bind :9000
        http-request set-query "s=%[rand,mod(20000)]/dummy=%[rand(1000)]"  if { path_beg /rands }
        http-request cache-use c1
        server s1 198.18.0.32:8000
        http-response set-header etag blah
        http-response cache-store c1

cache c1
        max-age 3
        total-max-size 40
        max-object-size 262144
```

The server is httpterm and the client does this:
```
$ h1load -t 16 -c 512  http://198.18.0.135:9000/rands
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6-dev5-f1de1b-40 2022/04/13 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=48).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

The lock's cost is way more observable under `perf top` when applying this patch to uninline it:
```
--- a/include/haproxy/shctx.h
+++ b/include/haproxy/shctx.h
@@ -37,8 +37,19 @@ int shctx_row_data_get(struct shared_context *shctx, struct shared_block *first,
 
 extern int use_shared_mem;
 
-#define shctx_lock(shctx)   if (use_shared_mem) HA_SPIN_LOCK(SHCTX_LOCK, &shctx->lock)
-#define shctx_unlock(shctx) if (use_shared_mem) HA_SPIN_UNLOCK(SHCTX_LOCK, &shctx->lock)
+__attribute__((noinline))
+static void shctx_lock(struct shared_context *shctx)
+{
+       if (use_shared_mem)
+               HA_SPIN_LOCK(SHCTX_LOCK, &shctx->lock);
+}
+
+__attribute__((noinline))
+static void shctx_unlock(struct shared_context *shctx)
+{
+       if (use_shared_mem)
+               HA_SPIN_UNLOCK(SHCTX_LOCK, &shctx->lock);
+}
```

**Comment by capflam** [comment]
It was addressed in recent versions, I'm closing
