### ISSUE TITLE
Fast closing frontend connection creates not properly closed connection to backend with a tproxy setup

### ISSUE THREAD

**Issue by xschlef** [haproxy/haproxy#1672]
### Detailed Description of the Problem

We have a tproxy based setup for balancing several slapd (running on debian bullseye) read only mirrors.

Some applications, that are usually tested against active directory that is usually not loadbalanced, use some tricks to check for availability of the ldap service.

Here is a php snippet from php.net
```
function serviceping($host, $port=389, $timeout=1)
{
        $op = fsockopen($host, $port, $errno, $errstr, $timeout);
        if (!$op) return 0; //DC is N/A
    else {
    fclose($opanak); //explicitly close open socket connection
    return 1; //DC is up & running, we can safely connect with ldap_connect
    }
}
```

This basically creates and closes a tcp connection in sub-milliseconds between client and haproxy.

haproxy somehow does not warrant that this connection is closed and will create a connection to the backend servers even after the original connection to the client is closed.

This creates a syn packet with the client ip as source to one of the backends.
haproxy will now discard this backend connection without sending an RST packet to the backend.

This creates a lot of dangling tcp connections in the backend in SYN_RECV state. The backend will try to send syn,ack packets which are ignored by haproxy as they are no longer belonging to any connection.

Some applications, in this case our slapd servers, are DoSed by this behavior and will stop responding, effectively taking the service down.

### Expected Behavior

haproxy should send an RST packet for a connection that was discarded internally in a tproxy setup so backends will close the connection or close the connection properly.

### Steps to Reproduce the Behavior

1. make a lot of connections with the provided snippet to a tproxy based service
2. watch the open sockets on a backend pile up in state SYN_RECV

### Do you have any idea what may have caused this?

I guess that there is a timing issue so the connection to the backend will be created despite the fact that the frontend connection is already closed and that this will not happen in setups with higher latency.

### What is your configuration?

```haproxy
global
        daemon
        stats socket /run/haproxy/admin_10.10.142.62.sock mode 660 level admin
        stats timeout 30s
        master-worker
        pidfile /run/haproxy-10.10.142.62.pid
        maxconn 2000000
        ulimit-n 8388608
        ssl-server-verify none #for checks
        tune.ssl.default-dh-param 2048
        tune.bufsize 32768
        log /dev/log local0 notice
        chroot /var/lib/haproxy
        cpu-map 1- 0-
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        ssl-default-bind-options no-sslv3
        maxconnrate 2000000
        maxsslconn  2000000
        maxsslrate  2000000

defaults
        mode tcp
        log global
        timeout connect 15s
        timeout check 10s
        timeout client 50s
        timeout server 50s
        option dontlognull
        option contstats
        no option allbackups #use only first backup server if one is down
        option redispatch #enable session redistribution in case of connection failure
        retries 3
        maxconn 2000000
        backlog 2000000 #Give hints to the system about the approximate listen backlog desired size


peers IMTLBPeers
        peer lb-01  10.10.8.169:1024
        peer lb-02  10.10.8.170:1024


frontend fe_3329529148385281_636
        bind 10.10.142.62:636
        log /dev/log local0 info
        mode tcp
        no option http-server-close
        option tcpka
        option contstats
        log-format '{"pid":%pid,"haproxy_frontend_type":"tcp","haproxy_process_concurrent_connections":%ac,"haproxy_frontend_concurrent_connections":%fc,"haproxy_backend_concurrent_connections":%bc,"haproxy_server_concurrent_connections":%sc,"haproxy_backend_queue":%bq,"haproxy_server_queue":%sq,"haproxy_queue_wait_time":%Tw,"haproxy_server_wait_time":%Tc,"response_time":%Td,"session_duration":%Tt,"request_termination_state":"%tsc","haproxy_server_connection_retries":%rc,"remote_addr":"%ci","remote_port":%cp,"frontend_addr":"%fi","frontend_port":%fp,"frontend_ssl_version":"%sslv","frontend_ssl_ciphers":"%sslc","haproxy_frontend_name":"%f","haproxy_backend_name":"%b","haproxy_server_name":"%s","response_size":%B,"request_size":%U}'
        timeout client 10m
        default_backend be_3329529148385281_Default_636

backend be_3329529148385281_Default_636
        source 0.0.0.0 usesrc clientip
        log /dev/log local0 info
        mode tcp
        no option http-server-close
        option tcpka
        option log-health-checks
        # Custom Options
        timeout server 10m
        # /Custom Options
        fullconn 65535
        balance roundrobin
        default-server inter 10s rise 2 fall 3
        server first   10.10.189.141:636  check-ssl
        server second  10.10.189.142:636  check-ssl
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.22-1~bpo10+1 2022/03/15 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.22.html
Running on: Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.2.22=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=56).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

### Additional Information

I can provide packet captures, if they are needed.

**Comment by wtarreau** [comment]
I think there are two parts here:
  - the fact that you'd like to be able to abort the connections ASAP
  - the problem with response SYN-ACKs not being matched

The first point could be (at least) partially solved by appending "option abortonclose" in your config, which will result in a client abort being passed ASAP to the other side, including aborting a pending connection.

I think that in your case you could improve the configuration so that empty connections are not forwarded. There's a way to do this with "tcp-request inspect-delay". Since you're using LDAP and the client speaks first, it could be as simple as rejecting incoming connections without client data, and it should look like this:
```
   tcp-request inspect-delay 5s
   tcp-request content reject if { req.len eq 0 }
```

For the second point, if the return SYN-ACK is not matched against a connection, there's definitely a problem with your netfilter rules. It sounds like you are silently dropping packets that do not match any known connection, am I wrong ? You should always use a reset for unknown connections (e.g. `-j REJECT --reject-with tcp-reset`). The DROP action is fine for SYN packets though. I don't know your ruleset but the usual thing would look roughly like this:
```
-A INPUT -m conntrack --ct-state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -m conntrack --ct-state NEW -p tcp --syn -j chain-with-tcp-rules
-A INPUT -m conntrack --ct-state INVALID -p tcp -j REJECT --reject-with tcp-reset
-A INPUT -j DROP
```
If for any reason you've enabled the `tcp_be_liberal` sysctl, you may need to match `NEW,INVALID` on the last rule instead of just `INVALID` since any non-SYN packet could also create a new connection (even a SYN-ACK).

**Comment by xschlef** [comment]
Thank you for your fast and thorough answer. We will add this to our setup. We had some issues with --ct-state INVALID rejects in the past with other services running over the same haproxy, but the tcp-request inspect-delay will be added for sure. I am closing this for now, as it seems to be a problem with our netfilter setup (we are running nftables).
