### ISSUE TITLE
Duplicate DNS requests leading to incorrect routing of requests

### ISSUE THREAD

**Issue by tamimkh** [haproxy/haproxy#1688]
### Detailed Description of the Problem

When haproxy 2.0/2.2/2.3 is configured with a `resolvers` and a `server-template` that uses these `resolvers` if the DNS server used by the resolver goes down for "enough" time (ie: longer then the `timeout resolve` configuration) then haproxy will start to make duplicate DNS requests to the configured DNS server. This is not a big problem in itself but the duplicate DNS requests have the same DNS "transaction id" and the [eb32 tree](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=015d9be435db2291f5f256ddaae5912831ad5d8b;hb=8aa30fbc7d63af568eab1d81e52600a9d61a33ae#l352) containing currently used "transaction ids" is [cleared](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=015d9be435db2291f5f256ddaae5912831ad5d8b;hb=8aa30fbc7d63af568eab1d81e52600a9d61a33ae#l395) on receiving the [response](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=015d9be435db2291f5f256ddaae5912831ad5d8b;hb=8aa30fbc7d63af568eab1d81e52600a9d61a33ae#l1746) of the first DNS request. This makes it possible to reuse a "transaction id" that is currently in flight and get a response from the DNS server that was actually intended for another query. The end result is a `server-template` containing an incorrect server and as a result haproxy routing requests to this incorrect server.

### Expected Behavior

Availability issues with DNS servers used by `resolvers` blocks should not cause the reuse of DNS "transaction ids" for requests that are currently in flight.

### Steps to Reproduce the Behavior

1. Startup an haproxy 2.0/2.2/2.3 instance with a `resolvers` block with a configured `timeout resolve` and `server-template` that uses the resolver
1. Stop the DNS server that the `resolvers` block points to for atleast 2x `timeout resolve`
1. Start the DNS server again
1. Run tcpdump and observe that haproxy is sometimes making 2x the DNS requests required and that the extra requests have an identical DNS "transaction id" to another request

### Do you have any idea what may have caused this?

This issue seems to have been introduced by https://git.haproxy.org/?p=haproxy-2.0.git;a=commitdiff;h=8aa30fbc7d63af568eab1d81e52600a9d61a33ae. In this patch `dgram->t.sock.fd` is set to `-1` on connection errors so that it can be re-created. The issue here is that this causes [`dns_send_query`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=015d9be435db2291f5f256ddaae5912831ad5d8b;hb=8aa30fbc7d63af568eab1d81e52600a9d61a33ae#l295) to increment `nb_nameservers`s when the `fd` is re-created even though there has been no change in the number of nameservers. That then prevents duplicate request sending code in [`dns_resolve_send`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=015d9be435db2291f5f256ddaae5912831ad5d8b;hb=8aa30fbc7d63af568eab1d81e52600a9d61a33ae#l1782) from functioning correctly leading to the duplicate requests to happen in some cases.

### Do you have an idea how to solve the issue?

I think the easy fix for this issue would be to decrement the the value on `nb_nameservers` after doing `dgram->t.sock.fd = -1` in `dns_resolve_send`. It seems like `nb_namservers` could also potentially be set when the haproxy config is parsed and not setup after a connection succeeds to the DNS server. However, I do not have enough familiarity with with code base to know if this is actually possible and won't cause other issues.

I am happy to attempt to come up with a patch once people with more experience with the codebase determine the best way to fix this issue.

### What is your configuration?

```haproxy
global
  maxconn 32000
  nbthread 1
  pidfile /var/run/haproxy.pid
  daemon
  stats socket /var/run/haproxy.sock mode 600 level admin
  stats timeout 2m

defaults
  log global
  retries 3
  option redispatch
  balance roundrobin
  option tcplog
  maxconn 5000
  timeout connect 3s
  timeout server 86400s
  timeout client 86400s
  timeout server-fin 60s
  timeout client-fin 60s
  default-server init-addr last,none
  mode tcp

listen status
  bind 127.0.0.1:8880
  mode http
  option httpclose
  option httplog
  stats enable
  stats uri /

resolvers dns
  nameserver           dns localhost:8600
  accepted_payload_size  8192
  resolve_retries           1
  # If a resolution request fails retry in 1 second
  timeout retry            1s
  # Make resolution requests every 5 seconds
  timeout resolve          5s
  # If resolution returns anything other then success hold the current values for up to a day
  hold timeout         86400s
  hold refused         86400s
  hold other           86400s
  # Hold valid values for 5 seconds and remove old values immediately
  hold valid               5s
  hold obsolete            0s
  hold nx                  0s

listen web
  bind *:8080
  server-template web 64 _web._tcp.service check resolvers dns inter 5s on-marked-down shutdown-sessions

listen web2
  bind *:8081
  server-template web 64 _web2._tcp.service check resolvers dns inter 5s on-marked-down shutdown-sessions

listen web3
  bind *:8082
  server-template web 64 _web3._tcp.service check resolvers dns inter 5s on-marked-down shutdown-sessions
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.0.28-1ppa1~xenial 2022/03/15 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=6).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.21 2016-01-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

**Comment by EmericBr** [comment]
The dns code is full of such issues on v < 2.4.

**Comment by EmericBr** [comment]
Analysing the code, the Transaction ID is a randomly generated with a 65k period. So even if a delayed response is coming, this should not collide with  an old response. Even if it collide, a check on resolved name is done and response is ignored if not corresponding.

But there is clearly multiple bugs in the code. The error cases or invalid responses are clearly sadly handled, this results in re-sending the queries multiple time to evey servers each time an error occurs with only one server because there is no "re-starting" point and the full resolution is restarted. 

A bug re-work of this part has been started in 2.4 and people using advanced dns features are encouraged to move on v > 2.4

**Comment by tamimkh** [comment]
> Analysing the code, the Transaction ID is a randomly generated with a 65k period. So even if a delayed response is coming, this should not collide with an old response.

Just to clarify, there is no collision in the "transaction id" since the `eb32` tree is preventing that. However, we are sending multiple requests with the same "transaction id" while [removing](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l395) an entry from the `eb32` tree on the first response. This makes it possible to create a new request entry with an identical id in the `eb32` tree while a response for an old request still has not been received. When this response is eventually received we [retrieve](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1634) the `dns_response` for **new** request for which we have received no response even though the response is for the **old** request.

>  Even if it collide, a check on resolved name is done and response is ignored if not corresponding.

If you are referring to the code to compare [here](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1723) then I think by that point its too late. This is due to us calling [`dns_validate_response`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1644) which goes through the previously stored [`answer_list`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l946) and [compares](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l966) them to the old invalid DNS results that were just retrieved. This fails since the DNS SRV response is for an old request and contains a completely different server leading the `last_seen` timestamp to [not be updated](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l983) on the current valid server entry and for the invalid server to be added to the [`answer_list`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l988) for the `dns_resolution`. This leads the call to [`dns_check_dns_response`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l994) which is [iterating over the `answer_list`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l505) for the `dns_resolution` to [remove](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l522) the old entry since our `hold obsolete` is 0 and this [comparision](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l508) fails. This function also later on sets up [resolving](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l597) of the new server returned by the old invalid SRV request since it is included in the `answer_list` it is iterating over. When this server resolves its IP after `timeout resolve` elapses we start to route requests to an incorrect server.

> A bug re-work of this part has been started in 2.4 and people using advanced dns features are encouraged to move on v > 2.4

That is good to hear since we are currently in the process of moving to 2.4 since our testing showed that it was not impacted by this issue. The main reason we wanted to report this bug was to raise awareness and potentially have it fixed in the older supported releases since it seemed like it would not be too hard to fix.

**Comment by wtarreau** [comment]
Just to confirm, I still don't see how you can see an old response with the same ID arrive late, because the ID's period being 65535 means that you'd have to send 65535 new requests before reusing that same ID. If a response remains in flight for that long, it's becoming an issue, and that's a limit imposed by the DNS protocol itself. That's why I'm asking if you're certain you're seeing the same ID being reused; because that could in fact be the consequence of a bug elsewhere in that code.

**Comment by tamimkh** [comment]
> Just to confirm, I still don't see how you can see an old response with the same ID arrive late, because the ID's period being 65535 means that you'd have to send 65535 new requests before reusing that same ID.

I think this is due to [`dns_resolve_send`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1771) looping only over `resolvers->resolutions.curr` and incrementing [`nb_queries` on success](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1833), not removing `dns_resolution`s (that only happens on a [response](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1763)) and only not sending requests when [`res->nb_queries == resolvers->nb_nameservers`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1798). This means if `nb_nameservers` does not represent the actual number of DNS servers you will be sending requests with duplicate DNS ids since [`dns_build_query`](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l235) does not reset the transaction id used on the DNS request. The DNS transaction id only seems to be [reset](https://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/dns.c;h=694f840666c2f17059226fbc7493dc94446b021c;hb=e7e6b2445b3792dc3502a81aeadd1c61fb799e08#l1761) only when the response is received from the server.

> If a response remains in flight for that long, it's becoming an issue, and that's a limit imposed by the DNS protocol itself. That's why I'm asking if you're certain you're seeing the same ID being reused; because that could in fact be the consequence of a bug elsewhere in that code.

Yup, I am definitely seeing an id being reused. It is also being reused milliseconds after the first use. Here is a [pcap file](https://github.com/haproxy/haproxy/files/8768700/dump.pcap.zip) demonstrating this behaviour (the colliding id can be found by searching for `dns.id == 0xcaab`). You should also be able to reproduce the behaviour with the haproxy 2.0.29 using the following [`haproxy.cfg`](https://github.com/haproxy/haproxy/files/8768710/haproxy.txt) (run with `/usr/sbin/haproxy -Ws -f haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock`) and dnsmasq with the following [`dnsmasq.conf`](https://github.com/haproxy/haproxy/files/8768717/dnsmasq.txt) (run with `dnsmasq -d -k -C dnsmasq.conf`). All it takes to cause the duplicate transaction id DNS requests is starting haproxy and dnsmasq and letting haproxy detect the `Server`s being `UP`, turning off dnsmasq for a minute or so and then starting it up again. At that point, a `tcpdump -i lo port 8600` should show DNS SRV requests with the duplicate ids happening milliseconds after the first request.

**Comment by capflam** [comment]
I checked the code of HAProxy-2.2. And `nb_nameservers` is indeed never decremented as you said. It must reflect the number of active nameservers for a resolver. When a connection error is detected and the current FD is deleted, the counter must be decremented. Your analysis seems valid. I must check more carefully of course because the code is far to be clear. For instance, I'm annoyed about the comparison between `nb_responses` and `nb_nameservers` because there are some code paths where the query is not sent.

**Comment by wtarreau** [comment]
I remember Emeric explaining this thing to me when narrating about the horrors he discovered there. I think you should ask Emeric whether he remembers a way to address this specific case, if at all fixable. I'm wondering if we should emit warnings in all pre-2.4 versions whenever a `resolvers` section is declared, saying basically "_DNS in versions prior to 2.4 is known to suffer from a lot of breakage and is not fixable, use at your own risk_".

**Comment by capflam** [comment]
I tried hard to fix this bug. Unfortunately, it could only be a partial fix. The current design cannot be fixed. The main reason is that counters are used to track number of queries and responses, but there is no way to know on which nameservers a query was sent. It is pretty annoying. We will add a warning in the documentation for all versions prior the 2.4. There are too many corner cases and unfixable bugs without a huge refactoring.

However, I tried to mitigate the issue by fixing, as far as possible, the counters. Here is the patch. It must be tested first because I'm unable to reproduce the issue. It is a theoretical patch.

[0001-BUG-MEDIUM-dns-Keep-the-right-count-of-active-namese.patch.txt](https://github.com/haproxy/haproxy/files/8888664/0001-BUG-MEDIUM-dns-Keep-the-right-count-of-active-namese.patch.txt)

**Comment by tamimkh** [comment]
It looks like this patch fixes the issue. I am no longer seeing the duplicate requests for at least the failure mode described in the bug report. Here is a [pcap](https://github.com/haproxy/haproxy/files/8892684/fixed.haproxy22.pcap.txt) file showing the patch applied to `haproxy-2.2@c8d619949fe601e247b5baf780330ce88eb834b5` without any duplicate DNS SRV requests. Thank you for taking the time to come up with a patch for this even though I fully understand that the DNS code pre haproxy 2.4 is flawed and likely has several other bugs like this.

In case you want to try to reproduce yourself, I was able to do it by running `haproxy-2.2@c8d619949fe601e247b5baf780330ce88eb834b5` using `/usr/local/sbin/haproxy -Ws -f haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock` with the following
[haproxy.cfg](https://github.com/haproxy/haproxy/files/8892579/haproxy.cfg.txt) and `dnsmasq` `2.75-1ubuntu0.16.04.10` using `dnsmasq -d -k -C dnsmasq.conf` with the following [dnsmasq.conf](https://github.com/haproxy/haproxy/files/8892586/dnsmasq.conf.txt). The reproduction steps I used were:

* Turn on haproxy and dnsmasq
* Wait 30 seconds for stuff to stabalize
* Turn off dnsmasq
* Wait 5 minutes (You can probably wait a shorter period of time but I just wanted to be certain)
* Turn on dnsmasq
* Run tcpdump (`tcpdump -i lo port 8600 -w dump.pcap`) for ~1 minute 
* Observe duplicate DNS SRV requests (ie: `dns.query.type == 33`) upon opening in wireshark
 
Here is the [pcap](https://github.com/haproxy/haproxy/files/8892632/reproduce.haproxy22.pcap.txt) file that shows the issue happening on `haproxy-2.2@c8d619949fe601e247b5baf780330ce88eb834b5`. You can look for `dns.id == 0x0008` if you want to see an example.

**Comment by wtarreau** [comment]
Many thanks for the description, detailed reproducers are always much appreciated!

**Comment by capflam** [comment]
Thanks for the feedback. I finally pushed the fix. I really hope it will not introduce some regressions.
