### ISSUE TITLE
LB complex algorithms combination and anonymity issues

### ISSUE THREAD

**Issue by hashbulla** [haproxy/haproxy#1693]
### Detailed Description of the Problem

Shot out to the HaProxy team and maintainers, keep up the good work guys !

I am in the situation of managing a complex proxy architecture composed of multiple chained load balancers each of them implementing diffent load balancing algorithms and routing request in the final stage to a specific pool of proxies.

I am encoutering 3 different issues which neither the official nor unofficial documentations are adressing completely. 

**1.** I want to route my requests according to its final destination regarding both the dns of the endpoint targeted or/and some part of the url path. I have not found satisfying results using the following config :

I have tried `path_beg, path_end,  path_sub`  with the following config :

```frontend default
        bind *:8080
        mode http
        acl admin_url path_sub admin

        use_backend srvs_app1 if admin_url

backend srvs_app1
        balance leastconn
        server host1 HOST1_IP:PORT1 check
        server host2 HOST2_IP:PORT2 check
```

**2** I use to spoof some requests parameters using a Squid and an Elite configuration according to this article https://www.metahackers.pro/setup-high-anonymous-elite-proxy/. Although, I wish not to use Elite Squid nodes as a spoofing layer in my infrastructure anymore, hence I was curious to know if such an Anonymous/Elite configuration exists on HaProxy. Any help on this point would be appriciated.

**3** Some of my load balancers have to implement a _Least Time_ type algorithms and some other need to use a combination of a _Power of two random choices_ type algorithm with a _Least Time_ one after the random selection of two nodes have been done. I have found 2 relevant articles refering to such a set up, one for HaProxy (https://www.haproxy.com/blog/power-of-two-load-balancing/) and one for NGINX (https://www.nginx.com/blog/nginx-power-of-two-choices-load-balancing-algorithm/). 

In HaProxy official documentation, I have yet not found any reference to a _Least Time_ or any combination of _Power of two random choices_ and _Least Time_ algorithms : https://devdocs.io/haproxy~2.4/configuration#chapter-4.2

This 3rd point critical, I really wish you guys will provide me with a clear answer on this one !

Cheers 

### Expected Behavior

**1** Being able to route my requests to different nodes according to the request endpoint url informations (DNS, Path) with `path_sub` and a combination of conditions (peferably with Regular Expressions). 

**2** Provide my HaProxy configurations with Elite/Anonymous settings.

**3** Implement _Least Time_ algorithms alone but as well combined with _Power of two random choices_ type algorithms (_Random Two_ and _Least Time_ on the random choice resulting nodes)

The infra should look as so : 

https://image.noelshack.com/fichiers/2022/19/3/1652284155-loadbalancing-15.png

### Steps to Reproduce the Behavior

No can do easely !

### What is your configuration?

```haproxy
Many configurations have been unsuccessfully tried.
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.0.13-2ubuntu0.5 2022/03/02 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-qHmAxE/haproxy-2.0.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=3).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

**Comment by capflam** [comment]
It is not a bug report. I don't really understand what you want to achieve. But it is not the right place to gather this kind of info. It may eventually be transformed to a feature request but first try to get some help on the forum or the mailing list. Thanks.

The forum is at: https://discourse.haproxy.org/
* The mailing list (no need to subscribe) is: [haproxy@formilux.org](mailto:haproxy@formilux.org)
* Subscribe to the list: [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)
* Unsubscribe from the list: [haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)
