### ISSUE TITLE
quiet Option dont suppress WARNINGS after HUP

### ISSUE THREAD

**Issue by matheuscaselani** [haproxy/haproxy#1698]
### Detailed Description of the Problem

I'm running haproxy under docker, and after startup and any HUP to the container, it keeps throwing WARNINGS and NOTICES like this: 

> [NOTICE] 132/222944 (1) : New program 'api' (8) forked.
> [NOTICE] 132/222944 (1) : New worker #1 (9) forked.
> [WARNING] 132/223531 (9) : Proxy XXXXXXX stopped (cumulated conns: FE: 0, BE: 0).
> [WARNING] 132/223531 (9) : Proxy XXXXXXX stopped (cumulated conns: FE: 0, BE: 0).
> [WARNING] 132/223531 (9) : Proxy XXXXXXX stopped (cumulated conns: FE: 0, BE: 0).
> [WARNING] 132/223532 (9) : Stopping frontend GLOBAL in 0 ms.
> [WARNING] 132/223532 (9) : Stopping backend XXXXXXX in 0 ms.
> [WARNING] 132/223532 (9) : Stopping backend XXXXXXX in 0 ms.
> [WARNING] 132/223532 (9) : Stopping backend XXXXXXX in 0 ms.
>[WARNING] 132/223536 (1) : Former worker #1 (9) exited with code 0 (Exit)

I'm also using -W -db on startup ( default config over docker entry point )

### Expected Behavior

The quiet flag should disable all NOTICE and WARNINGS level output

### Steps to Reproduce the Behavior

Use my haproxy config options : 

> global
>   cpu-map 1 1
>   cpu-map 2 2
>   maxconn 200000
>   stats socket /var/run/haproxy.sock mode 600 level admin
>   stats timeout 2m
>   tune.ssl.default-dh-param 4096
>   ssl-server-verify none
>   quiet
> 
> defaults
>   log global
>   option redispatch
>   option dontlognull
>   option dontlog-normal
>   option contstats
>   timeout connect 5s
>   timeout client 1200s
>   timeout queue 30s
>   timeout server 1200s
>   retries 3
>   timeout tarpit 1m
>   backlog 10000000

### Do you have any idea what may have caused this?

I think send_log() function doesnt have a "if" clause to avoid sending these warnings like h_warning() does.

[h_warning Function LINK](https://imgur.com/E1Rq9oh)

[send_log Function LINK](https://imgur.com/dA8uVHq)

[send_log Function LINK 2](https://imgur.com/wFmKrrE)

### What is your configuration?

```haproxy
> global
>   cpu-map 1 1
>   cpu-map 2 2
>   maxconn 200000
>   stats socket /var/run/haproxy.sock mode 600 level admin
>   stats timeout 2m
>   tune.ssl.default-dh-param 4096
>   ssl-server-verify none
>   quiet
> 
> defaults
>   log global
>   option redispatch
>   option dontlognull
>   option dontlog-normal
>   option contstats
>   timeout connect 5s
>   timeout client 1200s
>   timeout queue 30s
>   timeout server 1200s
>   retries 3
>   timeout tarpit 1m
>   backlog 10000000
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.3.9-53945bf 2021/03/30 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.9.html
Running on: Linux 4.15.0-1113-azure #126~16.04.1-Ubuntu SMP Tue Apr 13 16:55:24 UTC 2021 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=6).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.35 2020-05-09
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

### Additional Information

I've also tried to send all log output to rsyslog server and still get the same error.

Adding log 127.0.0.1 local0 err to global section

**Comment by wtarreau** [comment]
It doesn't seem unreasonable, indeed. Historically foreground was used only for debugging so it needed to have precedence over quiet. Nowadays nobody uses quiet so there's no real need for this precedence anymore. We could possibly switch the two. In addition nowadays we have a STARTING flag that didn't exist a long time ago, so we can preserve these warnings during the startup.

**Comment by mfcaselani** [comment]
Sounds good to me @wtarreau . There is anything else to be reviewed in this post or i can help with ? thanks for your time ^^

**Comment by wtarreau** [comment]
I've had a look and it will be more difficult than anticipated, because the `quiet` flag gets removed when `-db` is passed, and it's then tested at plenty of places.

However the `-q` passed to the CLI has precedence and is not removed. Could you please try just adding `-q` to your command line ? I think it will do exactly what you want.

**Comment by mfcaselani** [comment]
Hey @wtarreau thank you for your reply! It indeed worked like a charm. Again, thank you so much.
