### ISSUE TITLE
SSL - haproxy exposes certificate with different dates

### ISSUE THREAD

**Issue by jakubvojacek** [haproxy/haproxy#1700]
### Detailed Description of the Problem

We have had 4 cases when the SSL certificate, in a PEM file, had expiration till July but haproxy was exposing a certificate that was till May only. I confirmed the duration of the PEM file with openssl command 

```
openssl x509 -enddate -noout -in portal.oxmantv.com.pem 
notAfter=Jul 18 23:59:59 2022 GMT
```

But according to webbrower, the was about to expire certificate expired May 19th (I was notified about the expiration thanks to the prometheus blackbox_exporter). 

<img width="859" alt="Screenshot 2022-05-16 at 10 25 46" src="https://user-images.githubusercontent.com/3463456/168550912-aacebd90-840d-436d-b93a-fd2ce15a7603.png">

I confirmed the expiration via browser as well as sslabs.com - the certifcate was looking like expiring but in fact, was not. 

This couldn't have been caused by different certificate loaded. The site was new and first certificates were generated in april and were not yet renewed. The PEM was valid from Aprill till July, sslabs.com was showing the SSL from February to May - which is impossible, we werent using this server/haproxy in February.

I managed to fix this just by restarting haproxy service. After the restart, the SSL certificate expiration was showing fine in browsers

### Expected Behavior

The certificate expiration should be same as in the PEM file. 

### Steps to Reproduce the Behavior

Unfortunately, I dont know how to reproduce it. I restarted haproxy on the 4 servers that we had this issue as we couldn't afford for the SSL to expire. 

### Do you have any idea what may have caused this?

All 4 servers/haproxies had in common that they were installed within a day time. Perhaps zerossl was issuing some "corrupted" certificates at that time? Because we have hundreds of other sites and we didnt see this issue before.

### Do you have an idea how to solve the issue?

Restarting haproxy (reload was not enough I believe, since we applied some changes recently and reloaded the services).

But that isnt really solution, thats more like dirty quickfix.

### What is your configuration?

On the affected servers, we were using `HAProxy version 2.5.5-1~bpo11+1 2022/03/14` - I know that there is a newer haproxy avaialble, I am waiting for next 2.5 release as it will contain fixes related to FPM/gzip and I didnt want to update the containers twice. (EDIT: just noticed that the version was released three days ago)

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.5-1~bpo11+1 2022/03/14 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.5.html
Running on: Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=56).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Additional Information

I dont know whether its an issue with haproxy or with the PEM file or something entirely else. But perhaps you guys encountered this before and will know what might have caused this.

Thanks a lot

**Comment by wlallemand** [comment]
That's unlikely to happen, HAProxy exposes the certificate you give it, it does not modify anything and you can't modify a certificate since a certificate is signed.

You probably loaded the wrong certificate, or multiple certificates for the same domain by accident (which happens often when using directory loading).

Reloading or restarting will load the certificates on the filesystem, what probably happen is that the certificates changed on the filesystem before you reloaded.

You can check the state of the certificate in HAProxy using the "[show ssl cert](https://cbonte.github.io/haproxy-dconv/2.5/management.html#show%20ssl%20cert)" command on the CLI

And you can check directly the certificate outputed on your domain with `openssl s_client -showcerts -connect portal.oxmantv.com:443`

**Comment by jakubvojacek** [comment]
The server was installed in April, I couldnt have generated zerossl certificate that starts from February in April. 

Thanks anyway

**Comment by wlallemand** [comment]
No idea how zerossl works, but are you sure the machine that generated the certificate had the right date?

**Comment by lukastribus** [comment]
> The server was installed in April, I couldnt have generated zerossl certificate that starts from February in April.

There is a certificate of `portal.oxmantv.com` that has been created on February 18th with serial nr `9b:48:4f:99:bf:24:69:2a:08:40:c3:e4:3d:49:dc:ae` and this is confirmed both by your screenshot and from public CT logs:

https://crt.sh/?id=6200923692

Somehow you pointed haproxy to this old certificate. Haproxy cannot turn back the time from April to February and create that certificate.

I understand you are not sure how this happened, but this has nothing to do with haproxy.

**Comment by jakubvojacek** [comment]
Ok thank you again, I hope this will no re-ocurr, in case it does, I will do some more debugging based on the commands above, once again, thank you for getting back to me
