### ISSUE TITLE
Request body truncated on ~0.2% of POST requests after upgrade to haproxy 2.0.1

### ISSUE THREAD

**Issue by alexf101** [haproxy/haproxy#171]
## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.0.1 2019/06/26 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

# uname -a
Linux slb-i-0cd585125c3eea175.au.s522.net 4.14.97-74.72.amzn1.x86_64 #1 SMP Tue Feb 5 20:59:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

I've extracted the relevant sections of our config for brevity. It also serves a bunch of other micro-services, but at very low request rates.
```
frontend secure {
    # Add header so the web client can identify when a proxy in the middle
    # has answered a request instead of us.
    rspadd X-Stile:\ 1

    # Capture request and response headers related to rate-limiting for logging.
    capture request header X-Stile-Session len 64

    # Echo the X-Stile-Echo header back to the client. The web-client uses this to detect broken HTTP
    # clients, like iOS 9.
    capture request header X-Stile-Echo len 8
    http-response add-header X-Stile-Echo %[capture.req.hdr(1)]

    # Use default HTTP log format with few extra fields on the end related to rate-limiting.
    # Repeat the abuse streak at the end so we can easily filter by this in rsyslog by ignoring
    # any log messages that don't include a non-zero streak.
    log global
    log-format {%[sc2_get_gpc0]}\ {60|350|%[sc2_http_req_rate]}\ %ci:%cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ SSL:{%sslv|%sslc}\ REQ_HEADERS:%hr\ %{+Q}r

    bind *:443 ssl no-sslv3 no-tls-tickets crt /var/run/slb/ssl_certs/<redacted>
    bind *:81
    option forwardfor

    maxconn 40000

    # Set HSTS header
    http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"

    #
    # Health Check Ping
    #
    # NOTE: MUST BE BEFORE MAINTENANCE.
    # Otherwise Route 53 will remove all members when we go into Maintenance Mode.
    #
    monitor-uri /ping

    #
    # Stile API
    #
    acl url_api path_beg -i /api/au

    # Set up stick table for tracking HTTP request rate to the API by user session.
    # Our session IDs don't appear to be this long in practice, but we allow for
    # strings of up to 64 characters in the sessions table.
    stick-table type string len 64 size 100k expire 120s store gpc0,http_req_rate(60s)

    # We must explicitly set a maximum inspection delay to make HAProxy wait until
    # it has received enough data to properly evaluate the 'HTTP' ACL below.
    # Otherwise it will immediately evaluate to false without waiting at all.
    tcp-request inspect-delay 1s

    # Track all requests associated with a session and decide if request rate is abusive.
    acl sessionless req.hdr_cnt(X-Stile-Session) eq 0
    tcp-request content track-sc2 hdr(X-Stile-Session) if HTTP !sessionless
    acl req_rate_abuse sc2_http_req_rate gt 350

    # Track number of contiguous requests made once considered abusive.
    # This may be useful for diagnosing ongoing/malicious abuse, but is currently primarily
    # used to filter logs to only record 'streaks' of at least one abusive request.
    # NOTE: 'accept' and 'gt 0' are effectively placeholders; this is a hack to cause side effects
    # (which seems to be blessed by the HAProxy author).
    acl inc_abuse_streak   sc2_inc_gpc0 gt 0
    acl clear_abuse_streak sc2_clr_gpc0 gt 0
    # NOTE: if any of these passes it will stop evaluation of any subsequent http-request rules.
    http-request allow if HTTP req_rate_abuse inc_abuse_streak
    http-request allow if HTTP !req_rate_abuse clear_abuse_streak

    # Set response headers so a conscientious client can correct its behaviour.
    http-response add-header X-Stile-Req-Window 60
    http-response add-header X-Stile-Req-Allowed 350
    http-response add-header X-Stile-Req-Actual %[sc2_http_req_rate]
    http-response add-header X-Stile-Req-Abuse-Streak %[sc2_get_gpc0] if req_rate_abuse

    use_backend api if url_api
}

backend api
    fullconn 16000

    # Provide timing information to public-api2 (see log.rb)
    http-request set-header X-SLB-Accepted-At "%t UTC"
    http-request set-header X-SLB-Handshake "%Th"
    http-request set-header X-SLB-Idle "%Ti"

    # strip /api/../ from request
    reqrep ^([^\ :]*)\ /api/au/(.*)     \1\ /\2

    log global

    option httpchk GET /ping

    balance roundrobin

    server <name> <ip>:<port> check inter 2s maxconn 25
    server <name> <ip>:<port> check inter 2s maxconn 25
    server <name> <ip>:<port> check inter 2s maxconn 25
    # ... And so on! There are 56 servers there at the moment on 14 IP addresses.
}
```

## Steps to reproduce the behavior

I'm not yet at the point where I can reproduce this issue with artificial traffic.

1. We rolled out an upgrade from 1.8.12-8a200c7 to 2.0.1.
2. We observed an error rate of ~0.2% of actual user POST requests (which we initially thought was unrelated noise). These POST requests appeared to our backend to have empty bodies, when they should've had valid JSON.
3. We rolled back haproxy to 1.8.12 a few days later, and the errors immediately ceased.

## Actual behavior

Requests seem to be getting truncated occasionally.

## Expected behavior

No difference to 1.8.12, i.e. requests are passed through to backend api.

## Do you have any idea what may have caused this?

Not a strong idea.

Error logs for individual users on the same device show a mixture of successes and failures, rather than a consistent pattern.

Most errors seem to be from users on Chrome 75 on Windows 10.

We were handling ~500 requests per second today, split amongst three haproxy instances - our haproxy boxes can usually handle that without breaking a sweat. During the last week, we had very few users online due to local school holidays, and also observed the issue then, so... it doesn't appear to be load related.

## Do you have an idea how to solve the issue?

Well, it was definitively solved by rolling back to version 1.8, so something in the version two changes will be causing it. I have no idea what though.

**Comment by alexf101** [comment]
Our current theory is that this was caused by changes to chunked-encoding. Still investigating...

**Comment by alexf101** [comment]
Ok, we now believe that what's going on is:

1. The new version of haproxy passes through chunked-encoding to the backend server, but the old version consumed the entire request before passing it through.

2. A [bug in Puma](https://github.com/puma/puma/issues/1839) that hitherto didn't affect us means that it completely fails to load the request if it's chunked.

3. Since chunked encoding can happen pretty much at the browser's discretion, this explains the intermittency of the problems we were seeing.

So, not a bug in haproxy. However, an important change in behaviour that may affect a lot of people, especially if they run puma servers.

**Comment by wtarreau** [comment]
Note, haproxy will not unilaterally decide to use chunked encoding. It
will do so if it receives chunked encoding. What is possible however is
that the chunking slightly differs between before and after the upgrade
and that you were lucky in the past for whatever reason (e.g. numerous
very small chunks emitted by the browser and passed as-is) and that now
the chunks are larger for whatever reason and that the server chokes on
them.

Please also note that we've fixed a number of non-critical bugs between
2.0.1 and 2.0.2 so you may be interested in trying again with that last
one just in case you'd have witnessed a corner case split between haproxy
and Puma.

**Comment by alexf101** [comment]
Thanks for the info!

Looks like puma itself was actually ok, and we had some old custom middleware that was expecting the Content-Length to always be present. However, according to the http spec, that header isn't included when using Transfer-Encoding: chunked.

The main mystery remaining to me is why this worked at all with haproxy 1.8.

> What is possible however is
that the chunking slightly differs between before and after the upgrade
and that you were lucky in the past for whatever reason (e.g. numerous
very small chunks emitted by the browser and passed as-is) and that now
the chunks are larger for whatever reason and that the server chokes on
them.

Yes, something like that.

This bug definitely falls squarely on our own shoulders though. I suppose the one thing I can suggest is that anyone considering an update should be sure to test that chunked-encoding is working with their existing stack, as something about 1.8 seems to hide issues with it.

**Comment by jamrok** [comment]
To help anyone who runs into a similar problem, `option http-use-htx` is what's enabled by default [since the Haproxy 2.0-dev3 according to the docs]( https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#option%20http-use-htx ).
This new behavior is affecting how `transfer-encoding: chunked` responses are being handled. 

Turning it off reverts back to the pre-Haproxy 2.0 behavior where Haproxy seemingly buffers the complete request before sending it along.

Alternatively, for my situation** I [enabled compression]( https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-compression%20algo ) for the backend that was problematic and I didn't have to disable HTX.

> **My situation:
> - Upgraded from Haproxy 1.8 to 2.0.4, therefore HTX is enabled by default
> - HTTP/2 is NOT being used for a particular backend (`server: Apache-Coyote/1.1`) in Chrome only (Version 76.0.3809.100), but it works fine for Firefox (68.0.2) and Safari
> - Random blank pages in Chrome only with `net::ERR_INVALID_CHUNKED_ENCODING 200` in the Chrome Console. 
>    - It's blank (Status: (failed) in `Network` tab in Developer Tools) because Chrome is prematurely closing the connection after waiting a bit (about 350ms)
>    - The total response size was >= 2MB (`content-length` header isn't set due to `transfer-encoding: chunked`...this is fine)

@wtarreau Just to close the loop on this, when time allows, can you please double check that the way HTX is affecting `transfer-encoding: chunked` for large responses (eg 3MB) isn't breaking something in Chrome? Maybe what's delivered isn't what Chrome expects, hence the `net::ERR_INVALID_CHUNKED_ENCODING 200` message. I think that would be the proper "fix".

Thanks
