### ISSUE TITLE
"option httpchk <method> <uri> HTTP/1.1" healthchecks using a HTTP/2 when server proto is h2

### ISSUE THREAD

**Issue by 180254** [haproxy/haproxy#1711]
### Detailed Description of the Problem

I have the backend section defined as follows:
```
backend myservers
  option httpchk GET /healthcheck HTTP/1.1\r\nHost:\ www
  server server1 127.0.0.1:18080 proto h2 check inter 5s rise 1 fall 2
```
```
backend myservers
  option httpchk GET /healthcheck HTTP/1.1
  http-check send hdr host www
  server server1 127.0.0.1:18080 proto h2 check inter 5s rise 1 fall 2
```

server1 is health checked using the HTTP/2 protocol, instead of HTTP/1.1.

### Expected Behavior

HTTP version string is set to HTTP/1.1.
server1 should be health checked using the HTTP/1 protocol.

### Steps to Reproduce the Behavior

1. Clone the demo repo: `git clone https://github.com/180254/haproxy-issue-1711`.
2. Start demo server (spring boot + jetty + h2c + accesslog): `./server.sh`.

3. Start haproxy server server with configuration 1: `./haproxy1.sh`.
4. See demo server logs, server is healthchecked using http2 .
> 127.0.0.1 - - [21/May/2022:12:21:20 +0000] "GET /healthcheck HTTP/2.0" 200 3

4. Start haproxy server server with configuration 2: `./haproxy2.sh`.
5. See demo server logs, server is healthchecked using http2 .
> 127.0.0.1 - - [21/May/2022:12:21:40 +0000] "GET /healthcheck HTTP/2.0" 200 3

6. Use the script `./cleanup.sh` to remove the docker images created for the test.

### What is your configuration?

```haproxy
defaults
  mode http
  timeout client 10s
  timeout connect 5s
  timeout server 10s
  timeout http-request 10s

frontend myfrontend
  bind 127.0.0.1:28080
  default_backend myservers

backend myservers
  option httpchk GET /healthcheck HTTP/1.1\r\nHost:\ www
  server server1 127.0.0.1:18080 proto h2 check inter 5s rise 1 fall 2
```

```haproxy
defaults
  mode http
  timeout client 10s
  timeout connect 5s
  timeout server 10s
  timeout http-request 10s

frontend myfrontend
  bind 127.0.0.1:28080
  default_backend myservers

backend myservers
  option httpchk GET /healthcheck HTTP/1.1
  http-check send hdr host www
  server server1 127.0.0.1:18080 proto h2 check inter 5s rise 1 fall 2
```

### Output of `haproxy -vv`
I checked the following docker images:
```plain
- haproxy:2.4.17
- haproxy:2.5.7
- haproxy:2.6-dev10
```

### Additional Information

1. After removing "proto h2" healthcheck works fine.

2. The following configuration works as expected:
```
backend myservers
  option httpchk
  http-check connect
  http-check send meth GET uri /healthcheck ver HTTP/1.1 hdr host www
  http-check expect status 200
  server server1 127.0.0.1:18080 proto h2 check inter 5s rise 1 fall 2
```

1. Clone the demo repo: `git clone https://github.com/180254/haproxy-issue-1711`.
4. Start demo server (spring boot + jetty + h2c + accesslog): `./server.sh`.
5. Start haproxy server server with configuration 3: `./haproxy3.sh`.
6. See demo server logs, server is healthchecked using http1.1 .
> 127.0.0.1 - - [21/May/2022:12:13:26 +0000] "GET /healthcheck HTTP/1.1" 200 3

However, configuration 1 and 2 should also work.

**Comment by capflam** [comment]
Here everything works as expected and documented. You've explicitly specified the H2 protocol on the server line and by default, the health-checks use the server configuration. So the HTTP/1.1 request is translated to a H2 request when it is sent to the server. It is exactly the same mechanism than the one used for normal HTTP clients. Looking at your configuration, clients are sending HTTP/1.1 requests and the server are receiving H2 requests.

If you want to perform HTTP/1.1 health-checks you must use a `http-check connect` rule:
```
option httpchk GET /healthcheck HTTP/1.1
http-check connect default proto h1
http-check send hdr host www
```
