### ISSUE TITLE
the custom logformat conflict with option httplog

### ISSUE THREAD

**Issue by ljhmily** [haproxy/haproxy#1715]
### Detailed Description of the Problem

haproxy -v
HAProxy version 2.4.16-9d532c4 2022/04/29 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.16.html
Running on: Linux 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64

I configured haProxy Frontend to use option Httplog and then set log format to reset the log format, but the output result is still the default Httplog format. when I disable option Httplog entries, the output log format is a custom one

### Expected Behavior

In the official document, http://docs.haproxy.org/2.4/configuration.html#8.2.3, when it is used, it will cover the option httplog, TCPLOG and other entries, but the actual results are opposite.The priority is higher than the LOG-Format

### Steps to Reproduce the Behavior

1、Install or compile a haproxy2.4.x version with minimal configuration, write option Httplog log-format, and configure log output
global
  daemon
  chroot /var/empty
  user haproxy
  group haproxy
  maxconn 10000
  pidfile /var/run/haproxy.pid
  stats socket /var/run/haproxy.stat mode 600 level admin
  stats timeout 5000ms
  log 127.0.0.1:514 local1

# The public 'www' address in the DMZ
frontend public
  mode http
  maxconn 8000
  bind *:80 name clear
  log-format %T\ %t\ Some\ Text
  log global
  option dontlognull
  option httplog
  timeout client 30s
  stats uri /admin/stats
  default_backend static

# The static backend backend for 'Host: img', /img and /css.
backend static
  mode http
  balance roundrobin
  option redispatch
  timeout server 5s
  timeout connect 5s
  server statsrv1 10.23.10.205:50081 inter 1000
  retries 2
  option prefer-last-server

listen stats
  bind *:50081
  stats enable
  stats uri /stats
  stats realm HAProxy-04\ Statistics
  stats auth stat:statspassw0rd
  stats admin if TRUE
2、start haproxy
3、request
curl http://a.midea.com:80
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
Haproxy log output, 100% matches the default format of the official document httplog
May 25 15:37:31 localhost haproxy[29797]: 10.23.10.205:44540 [25/May/2022:15:37:31.973] public static/statsrv1 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
3、Disable option Httplog in Frontend and request again
curl http://a.midea.com:80
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
haproxy log output，matches log-format %T\ %t\ Some\ Text
May 25 15:39:15 localhost haproxy[30262]: 25/May/2022:07:39:15 +0000 25/May/2022:15:39:15.263 Some Text

### Do you have any idea what may have caused this?

Conflict or priority issues

### Do you have an idea how to solve the issue?

Temporary solution: Disable Option Httplog in Frontend

### What is your configuration?

```haproxy
global
  daemon
  chroot /var/empty
  user haproxy
  group haproxy
  maxconn 10000
  pidfile /var/run/haproxy.pid
  stats socket /var/run/haproxy.stat mode 600 level admin
  stats timeout 5000ms
  log 127.0.0.1:514 local1

# The public 'www' address in the DMZ
frontend public
  mode http
  maxconn 8000
  bind *:80 name clear
  log-format %T\ %t\ Some\ Text
  log global
  option dontlognull
  option httplog
  timeout client 30s
  stats uri /admin/stats
  default_backend static

# The static backend backend for 'Host: img', /img and /css.
backend static
  mode http
  balance roundrobin
  option redispatch
  timeout server 5s
  timeout connect 5s
  server statsrv1 10.23.10.205:50081 inter 1000
  retries 2
  option prefer-last-server

listen stats
  bind *:50081
  stats enable
  stats uri /stats
  stats realm HAProxy-04\ Statistics
  stats auth stat:statspassw0rd
  stats admin if TRUE
```

### Output of `haproxy -vv`

```plain
compile version
HAProxy version 2.4.16-9d532c4 2022/04/29 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.16.html
Running on: Linux 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_LINUX_TPROXY=1 USE_LIBCRYPT=1 USE_CRYPT_H=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DEBUG_FULL

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

rpm version
/usr/sbin/haproxy -vv
HAProxy version 2.4.0-6cbbecf 2021/05/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.0.html
Running on: Linux 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by capflam** [comment]
It is expected and documented:

> "[option httplog](http://docs.haproxy.org/dev/configuration.html#option%20httplog)" overrides any previous "[log-format](http://docs.haproxy.org/dev/configuration.html#log-format)" directive.

> "[log-format](http://docs.haproxy.org/dev/configuration.html#log-format)" directive overrides previous "[option tcplog](http://docs.haproxy.org/dev/configuration.html#option%20tcplog)", "[log-format](http://docs.haproxy.org/dev/configuration.html#log-format)",
"[option httplog](http://docs.haproxy.org/dev/configuration.html#option%20httplog)" and "[option httpslog](http://docs.haproxy.org/dev/configuration.html#option%20httpslog)" directives.

`option httplog` is only a shortcut to avoid a tedious `log-format` definition

**Comment by ljhmily** [comment]
> 

yes，But it has a higher priority. Do I use the wrong place？

**Comment by capflam** [comment]
There is no priority just a definition order.

**Comment by ljhmily** [comment]
> There is no priority just a definition order.

？So is there a solution, other than unmasking

**Comment by capflam** [comment]
First, I don't know what you want to achieve. You must choose your log format. the HTTP one or the custom one. There is no reason to set the both directives in the same section. Because the second one will always override the first one.

**Comment by ljhmily** [comment]
> First, I don't know what you want to achieve. You must choose your log format. the HTTP one or the custom one. There is no reason to set the both directives in the same section. Because the second one will always override the first one.

you said，the custom one will always override the first one？But in my test, the former will override the latter，and that's my question, it's a bug

**Comment by capflam** [comment]
Sorry `first` and `second` were not related to my first comment but the position of your directives in your configuration. The documentation is pretty clear.  When a directive defining a log format (`log-format`, `option httplog`, `option tcplog`...) is parsed in a proxy section, any previous log format for this proxy  is replaced by the new one. You are defining 2 log formats in your `public` frontend. The first one with a `log-format` directive. The second one with `option httplog`. So, as documented, your custom log format is replaced by the HTTP one. There is no issue. It is not possible to have several log formats in same time on the same proxy.

**Comment by ljhmily** [comment]
> Sorry `first` and `second` were not related to my first comment but the position of your directives in your configuration. The documentation is pretty clear. When a directive defining a log format (`log-format`, `option httplog`, `option tcplog`...) is parsed in a proxy section, any previous log format for this proxy is replaced by the new one. You are defining 2 log formats in your `public` frontend. The first one with a `log-format` directive. The second one with `option httplog`. So, as documented, your custom log format is replaced by the HTTP one. There is no issue. It is not possible to have several log formats in same time on the same proxy.

I see, combined with your description, this is a problem with the dataplane API, which forces option httplog to be placed after log-format
