### ISSUE TITLE
haproxy X-Frame-Options problem

### ISSUE THREAD

**Issue by Omidmoradi1365** [haproxy/haproxy#173]
Hi
I am trying to configure my haproxy 1.8.16 to stop rendering my site from another sites by using iframe. but I have some exceptions, I want some sites can do it.
I have searched a lot but the solutions did not work at all.
Can somebody help me about this issue????!!!!

I tried the below way, not work for me:

capture request header host len 128
http-response add-header X-Frame-Options:\ ALLOW-FROM %[capture.req.hdr(0)]
if { capture.req.hdr(0) -m found } { capture.req.hdr(0) -i load.example.com
}

**Comment by wtarreau** [comment]
I don't know if you realize that your message absolutely contains zero information about what you're trying to do. You're just copy-pasting some random config excerpts but it's impossible to guess what you need. So please start by describing what you are trying to do and maybe someone can then help you. Likely you will also need to describe how your application expects to use this header field as well.

**Comment by capflam** [comment]
Hum... it seems to be a question about the configuration of HAProxy and not a bug. The issue tracker on Github is not the right place to ask such questions. It is not a support forum. You'll find more help on [discourse](https://discourse.haproxy.org/) or on [the mailing list](http://www.haproxy.org/#tact).

However, if you really think there is a bug, please try to use the "Bug Report" template. It really helps us to sort the issues and figure out what's going on.
