### ISSUE TITLE
No Http response with no logs increased on upgrade to haproxy 2.4

### ISSUE THREAD

**Issue by tmccombs** [haproxy/haproxy#1735]
### Detailed Description of the Problem

After upgrading from haproxy 2.2 to 2.4 we saw an increase in NoHttpResponseExceptions from an apache http client connecting to haproxy. After rolling back to 2.2 we stopped getting so many of these errors. From what I can tell, this happens when the request is successfully sent, but the server never returns a response.

Interestingly, these request don't show up in the haproxy logs at all. 

### Expected Behavior

Haproxy 2.4 should not increase amount of missing http responses

### Steps to Reproduce the Behavior

I can't reliably reproduce this. It regularly happens with the full config under load, but I haven't been able to reproduce in a more minimal environment, or find a pattern in the types of requests that encounter this.

### Do you have any idea what may have caused this?

Something that changed between haproxy 2.2 and 2.4. 

### Do you have an idea how to solve the issue?

No

### What is your configuration?

```haproxy
# note: this is just a small portion of the full configuration
global
  log-tag "dlb-preprod"
  log               localhost:514 len 65535 local2 info
  tune.bufsize      65536
  tune.maxrewrite   2048
  maxconn           65000
  user              haproxy
  group             haproxy
  server-state-file /tmp/haproxy-server-state
  stats socket      /tmp/haproxy-stats expose-fd listeners
  log-send-hostname
  quiet
  daemon
  hard-stop-after 45m
  
  nbthread          2

  tune.pattern.cache-size 0

defaults 
  load-server-state-from-file global
  mode             http
  retries          3
  maxconn          65000
  timeout connect  5000
  timeout client   30000
  timeout client-fin  5000
  timeout http-keep-alive 90000
  timeout server   300000
  option           allbackups
  option           dontlognull
  option            http-server-close
  option           log-health-checks
  option           redispatch
  logformat  'redacted'

resolvers systemdns
  parse-resolv-conf
  accepted_payload_size 8192

frontend my_fe
  bind :27003 accept-proxy
  bind :27600

  log global
  # a bunch of acls, and http-request and http-response rules that can't be included
  use_backend my_be

backend my_be
    balance leastconn
  default-server inter 3s fall 2 rise 2
  option httpchk GET /health
  http-check disable-on-404

  server-template service-name 4 service.example.com:80 check resolvers systemdns init-addr none
```

### Output of `haproxy -vv`

```plain
thayne@dlb-10-6-0-110_preprod:~$ haproxy -vv
HAProxy version 2.4.16-9d532c4 2022/04/29 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.16.html
Running on: Linux 5.11.0-1020-aws #21~20.04.2-Ubuntu SMP Fri Oct 1 13:03:59 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2_JIT=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
No relevant logs, as mentioned
```

**Comment by capflam** [comment]
What is the 2.2 version ? For now, I have no idea. You may try with the 2.4.17. It is strange there is no log. You may try `show fd` and `show sess all` commands when the problems happens.

**Comment by tmccombs** [comment]
2.2 version output:

```
HA-Proxy version 2.2.17-dd94a25 2021/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.17.html
Running on: Linux 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2_JIT=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
	```

**Comment by capflam** [comment]
Thanks. So your 2.2 version is outdated (it matches the 2.4.4 on the release timeline). It is hard to know if it is a regression of the 2.4 or if it is common to the 2.4 and the 2.2. `show fd` and `show sess all` outputs remain required to know if there are stalled sessions.

**Comment by capflam** [comment]
Thanks. So your 2.2 version is outdated (it matches the 2.4.4 on the release timeline). It is hard to know if it is a regression of the 2.4 or if it is common to the 2.4 and the 2.2. `show fd` and `show sess all` outputs remain required to know if there are stalled sessions.

**Comment by tmccombs** [comment]
Sorry it has taken me so long to respond, I've been really busy with other stuff.

> You may try `show fd` and `show sess all` commands when the problems happens

this is unfortunately rather difficult to do. While it does happen sometimes in a testing environment, it is relatively rare. Out of over 30,000 requests  in a 30-minute window, this happened 5 times. 

I was able to run these commands within a few minutes of it happening.  The redacted output is [here](https://gist.github.com/tmccombs/7d7dd0702fb1a9189e4e3415e6782980).  I'm not sure if that will be any help though since it wasn't immediately when it happened.

**Comment by tmccombs** [comment]
Looking into this some more, the errors I was seeing in the preproduction environment were actually probably a client problem. And were happening with haproxy 2.2 as well. 

However, I just tested upgrading a single load balancer in the production environment to haproxy 2.4.18, and the number of  these NoHttpResponseExceptions  dramatically increased. So it hasn't been fixed by any patches since the last time I tried. 

This is preventing me from upgrading haproxy past 2.2 in production. And I can only reproduce it in production.  I wonder if maybe something changed around keepalive behavior, and haproxy is closing connections while http requests are in flight more often now. For some additional context the client is using a connection pool to reuse connections between the client and the haproxy load balancers.

**Comment by tmccombs** [comment]
The timeouts I have configured are:

```
  timeout connect  5000
  timeout client   30000
  timeout client-fin  5000
  timeout http-keep-alive 90000
  timeout server   300000
  ```
  
  I also have `option http-server-close`

**Comment by capflam** [comment]
Sorry for the delay. I'm back from holidays :). Well, there was no real change about keepalive on client side between 2.2 and 2.4. But you must try with a recent 2.2 to be sure. Are you using H2 connections on client side ?

However, it is indeed possible that your client fails to detect connection shutdowns and is reusing an already closed connection. In this case it explains why there is no log message. There is no keepavlie on server side, thus this eliminates the reuse of a closed connection on server side. But when this happens, your client must retry.

I cannot explain why this happens more frequently on the 2.4, but you may try to increase or reduce  `http-keep-alive` timeout to check if that changes anything.

**Comment by tmccombs** [comment]
Sorry for the delay on my end,  I've been gone for a while.

> Are you using H2 connections on client side ?

No. I'll try it with a recent 2.2 and longer http-keep-alive timeout sometime in the next couple of weeks.

**Comment by tmccombs** [comment]
Ok, I tried with 2.2.25, and don't see this issue. 

I've also tried increasing the `http-keep-alive` timeout to 5 minutes and to 10 minutes. That doesn't seem to help much. I still get much higher levels of these NoHttpResponseExceptions when using haproxy 2.4 than with 2.2. 

I also tried changing `timeout http-keep-alive` to 50ms, and that made the problem worse.

**Comment by capflam** [comment]
When you set `timeout http-keep-alive` to 50ms, did you observed any change on the 2.2 ? But if the problem still persist with pretty high value, it means there is something else. I'm digging...

**Comment by capflam** [comment]
I read again your issue description. When the problem occurs, you say the request is sent but the response never comes. How long does it take between sending the request and the error ? Is it possible that your client fails to correctly detect a stale connection and does not retry ? I'm asking because with a very low `timeout http-keep-alive` value, the probability to reuse a closed connection on the client side is very high. If the problem is worse in this case, it means your client is unable to retry the request.

**Comment by tmccombs** [comment]
> How long does it take between sending the request and the error ?

I'm not sure. Let me get back to you on that. 

>  Is it possible that your client fails to correctly detect a stale connection and does not retry ?

Possibly. I'm not actually sure how the apache http client determines if a connection is stale. I'm not really surprised this happens sometimes, there is likely a race condition between checking if the connection is stale, sending the request and the connection actually being closed.  What I am concerned about is that it happens significantly more often after upgrading to haproxy 2.4, and I don't know why. 

> it means your client is unable to retry the request

my client does retry for some kinds of http requests (like GET and HEAD), however, if it is a non-idempotent request (ex POST), then it won't retry because it doesn't know if the server actually started processing the request yet. And it is these POST requests that are specifically a problem for me (although having to retry more often for idempotent requests does have an impact on performance).

**Comment by capflam** [comment]
> What I am concerned about is that it happens significantly more often after upgrading to haproxy 2.4, and I don't know why.

I'm still trying to figure out why it happens more frequently on 2.4. I'm  probably missing something obvious but for now, I've no explanation. On 2.2, the K/A timeout is handle by the HTTP request analyzer, at the highest  level. On the 2.4, it is handled by the mux. So, close to the connection level. But, it is should behave the same way. And it is still possible my analysis is wrong ...

**Comment by tmccombs** [comment]
Another interesting piece to this is that I am setting the `Keep-Alive` header to 60 seconds, which is shorter than the keep alive timeout. So the apache connection pool should be marking connections as stale before they expire (although should and does aren't necessarily the same thing).

**Comment by capflam** [comment]
The `http-keep-alive` timeout (the HAProxy one) is only used for client connections. `Keep-Alive` header is not used by HAProxy. And on the server side, you have disabled  the connection keep-alive because `http-server-close` option is enabled.

**Comment by tmccombs** [comment]
Sorry, that probably wasn't clear enough. haproxy is sending the `keep-alive` header to the client. And the client desgined to use the value of the `keep-alive` header to determine how long to keep connections in the connection ppol.

**Comment by sriraamas** [comment]
Hey folks! I have a reproducible case setup with docker. I was able to see the issue in 2.4.20 but the issue didn't happen with haproxy 2.2.26

I used apache http client to reproduce this. The http-client lives here.. https://github.com/sriraamas/http-client-scala-app/blob/master/src/main/scala/example/Hello.scala. The http client can be run easily by downloading: https://github.com/sriraamas/http-client-scala-app/releases/download/0.3/http-client-deploy.jar and running 
`java -jar http-client-deploy.jar`

I used the docker commands like: 

```
sudo docker network create --driver=bridge mynetwork

sudo docker run -d  --name web1 --net mynetwork inanimate/echo-server:latest
sudo docker run -d  --name web2 --net mynetwork inanimate/echo-server:latest
sudo docker run -d  --name web3 --net mynetwork inanimate/echo-server:latest

mkdir run
chmod 0777 run

sudo docker run  \
   --name haproxy24 \
   --net mynetwork \
    --sysctl net.ipv4.ip_unprivileged_port_start=0 \
   -v $(pwd):/usr/local/etc/haproxy:ro \
   -v $(pwd)/run:/var/run \
   -p 8099:8099 \
   -p 8404:8404 \
   haproxy:2.4.20
```

with haproxy.cfg created in current working directory
```
global
  stats socket /var/run/stats.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
  log stdout format raw local0 debug

defaults
  mode http
  timeout client 10s
  timeout client-fin 5s
  timeout connect 5s
  timeout server 5m
  timeout http-keep-alive 90s
  log global
  option http-server-close

frontend stats
  bind *:8404
  stats enable
  stats uri /
  stats refresh 10s

frontend myfrontend
  bind :8099
  default_backend webservers

backend webservers
  server s1 web1:8080 check
  server s2 web2:8080 check
  server s3 web3:8080 check
```


The issue is seen if we run:

```
for x in {1..100}; do sudo docker kill -s HUP haproxy24; sleep 0.4; done
```
and 

running the scala app simultaneously. (which basically does http-requests continuously)
```
java -jar http-client-deploy.jar
```

**Comment by capflam** [comment]
I don't think it is the same  issue because @tmccombs does not report the issue during reloads but on running instance. @tmccombs, do you confirm ?

@sriraamas, in your case it is an expected change of the 2.4. On reload idle HTTP connections are simply closed. No response is sent and no log is emitted. Of course the client must be aware of this and retry a connect to send the request. An idle connection on haproxy side may be a usable connection on client side, it is just a matter of timing. But it is totally valid for a server to close the connection with no response. For the client, it is a warranty it can safely retry. All decent HTTP clients must do that.

You don't observe this behavior on 2.2 because it changed in 2.4. On 2.2, on reload, idle HTTP connections remain  open and haproxy waits a timeout or a last request to close them. It was discussed in #1506. It is possible to make the 2.4 or higher work like the 2.2 by using `option  idle-close-on-response`.

**Comment by tmccombs** [comment]
Actually, I think it is the same thing I observed (@sriraamas is my coworker). In the environment where I saw this happening we are currently reloading the configuration for haproxy about once a minute, due to some legacy code that changes the configuration regularly. That change in behavior actually makes a lot of sense for why this was happening. It also explains why I couldn't reproduce in other environments, because those environments don't reload as often. 

Now that I know what is causing this, I have some direction on how to address it. I can probably just make some changes so we don't have to reload as often, and I think there are some changes we can make to the client to make it better at detecting closed connections. 

Thank you so much @capflam, you have been very helpful. 

p.s. 

> For the client, it is a warranty it can safely retry. All decent HTTP clients must do that.

For idempotent requests, yes. However, for non-idempotent requests (for example a POST request), it can't safely retry, because it is possible that the server received the request, and started processing it before the connection closed.

**Comment by capflam** [comment]
Thanks for the update ! And indeed, retry on close is only valid for idempotent requests. I'm adding "works as design" label.

**Comment by Lonzak** [comment]
Sorry for digging up this ticket but we recently started using haproxy and in our loadtest we experience the exact same problem.

>Now that I know what is causing this, I have some direction on how to address it. I can probably just make some changes so we don't have to reload as often, and I think there are some changes we can make to the client to make it better at detecting closed connections.


@tmccombs  May I ask what you changed in the end to make it work? Increase the configuration load interval?

**Comment by git001** [comment]
@Lonzak please open a new issue with the required information's.
