### ISSUE TITLE
[question/bug] Default tune.bufsize does not seem to fit largest SSL buffer (2^14+some)

### ISSUE THREAD

**Issue by wdoekes** [haproxy/haproxy#1743]
### Detailed Description of the Problem

_(So, this isn't quite a bug report. But I'm sure the most technical answers can be expected here. Diving in.)_

We've had someone doing large POST data requests on our haproxy. They got a 500 response, with `<NOSRV>` for backend and `PR--` for the `termination_state`.

With log-format `%ci:%cp %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq` the HTTP logs would look like this:
```
IP:PORT https-in~ https-in/<NOSRV> -1/-1/-1/-1/0 500 5253 - - PR-- 2/2/0/0/0 0/0
```

**After debugging a while, it turned out that it was the SSL buffer that did not fit in the `tune.bufsize` buffer.**

When trying to reproduce, I used `openssl s_client`, but that has a read (and thus write) buffer of 8192:
https://github.com/openssl/openssl/blob/926c698c6f0a197e0322d4617db0ecd0d40f6e06/apps/s_client.c#L57
I adjusted that to 32K. After that, I could consistently reproduce the issue.

### Expected Behavior

My expectation was that regular http clients should be able to POST data. Apparently we need larger buffers for certain uncommon TLS/HTTP clients.

### Steps to Reproduce the Behavior

1. Create a `mode http` haproxy config
2. `bind` with `ssl`
3. Do backend selection based on some HTTP value (`use_backend x if METH_GET`); this backend does not respond, a 500 vs. 503 will show what's going on.
4. Lower `tune.bufsize` to `8192`
5. Send a large (hard-to-compress) POST with a HTTPS client that uses 8K or larger buffers (like openssl s_client).
6. Observe how you get a 500 response, and `<NOSRV>` as backend and either a `PR--` or `IR--` termination state.
(Increase the `tune.buffer` to `10112` and we'll get a 503/404/200-whatever response from the backend.)

### Do you have any idea what may have caused this?

Normally we don't want to lower the `tune.bufsize` to below 16K. This was just a demonstration. For a problem with the default 16K buffer, we can alter `openssl s_client` to send 16K instead of 8K.

If we replace `#define BUFSIZZ 1024*8` with `#define BUFSIZZ 1024*32` we're sure that we'll make the most out of the `SSL_write` calls:
https://github.com/openssl/openssl/blob/926c698c6f0a197e0322d4617db0ecd0d40f6e06/apps/s_client.c#L57

`openssl s_client` will send (for TLSv1.2) TLS segments with octet size 16413. That is composed of: 5 bytes contenttype(1)+version(2)+length(2) and 16408 bytes ciphertext. This decodes to 16384 (16K) plaintext.

At this point we'll need to increase the `tune.bufsize` to `18304`. For lower values, we'll get this 500 response. For 18304 and above, we can safely POST data and a backend gets selected.

And in fact, while testing for the exact limits, I saw both `PR--` and `IR--` when receiving a 500 error.

The docs have this to say:
>         P : the session was prematurely aborted by the proxy, because of a
>            connection limit enforcement, because a DENY filter was matched,
>            because of a security check which detected and blocked a dangerous
>            error in server response which might have caused information leak
>            (e.g. cacheable cookie).
and:
>        I : an internal error was identified by the proxy during a self-check.
>            This should NEVER happen, and you are encouraged to report any log
>            containing this, because this would almost certainly be a bug. It
>            would be wise to preventively restart the process after such an
>            event too, in case it would be caused by memory corruption.

I looks like that when it does not fit at all, we get a `P`, but when we're close, we get a `I`. Which should be reported. Here? :angel: 

### Do you have an idea how to solve the issue?

Well. I'm mostly interested in The Right Value :tm: 

According to the documentation, `tune.bufsize` gets subtracted by `tune.maxrewrite`. However, I could not deduce how those values were used exactly.

For **8K** TLS segments, I needed these minimal values:
```
    tune.bufsize 10112	  # <- 0x2780: lower this by 16 to 10096 (0x2770), and we get a 500 immediately
    tune.maxrewrite 1024  # keep default
```
Or, alternatively, when tweaking `tune.maxrewrite`:
```
    tune.bufsize 8192
    tune.maxrewrite 1818  # <- 0x71A: lower this to 1817, and we get a 500 immediately
```
For **16K** TLS segments, I needed these:
```
    tune.bufsize 18304    # <- 0x4780: lower this by 16 to 18288 (0x4770), and we get a 500 immediately
    tune.maxrewrite 1024  # keep default
```
According to the TLS specs, we should not see larger plaintext than 2^14 (16K):
https://datatracker.ietf.org/doc/html/rfc5246#section-6.2.1
>    length
>      The length (in bytes) of the following TLSPlaintext.fragment.  The
>      length MUST NOT exceed 2^14.

And https://datatracker.ietf.org/doc/html/rfc5246#section-6.2.3 max 2^14+2048 (18K) for the MACed ciphertext (again + 5 bytes).
And according to https://datatracker.ietf.org/doc/html/rfc5246#section-7.2.2 there is even a specific error for an overflow:
>   record_overflow
>      A TLSCiphertext record was received that had a length more than
>      2^14+2048 bytes, or a record decrypted to a TLSCompressed record
>      with more than 2^14+1024 bytes.  This message is always fatal and
>      should never be observed in communication between proper
>      implementations (except when messages were corrupted in the
>      network).

So, to be able to accept 16384 bytes of plaintext, I need a `tune.bufsize` of 18304.

**What value would I need to accept the most ridiculously large TLS segment?**

18304+2K, something just under 20K? And how would altering `tune.maxrewrite` influence that value?

### What is your configuration?

```haproxy
I know, this is a slighlty older haproxy version: 2.2.22

However, because I could find so little on the internet about this particular issue, I have a strong feeling this is not limited to this version.

And I'm especially interested in how the `tune.*` values interact, insomuch that I need 18K to be able to read just above 16K of ciphertext.
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.22-0osso0~ubu18.04 2022/03/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.22.html
Running on: Linux 4.15.0-173-generic #182-Ubuntu SMP Fri Mar 18 15:53:46 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-Vf8W02/haproxy-2.2.22=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_NS=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=20).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

### Additional Information

NOTE: I did not check whether `Expect: 100-continue` made any difference. This should probably also be checked.

It could be that clients using `Expect: 100-continue` will get a proper backend selected and then their data can be forwarded. It could also be that the backend gets selected, but then the data doesn't get through because the buffer is too small.

Sorry for the long post. Thanks for reading!

Cheers,
Walter Doekes
OSSO B.V.

**Comment by wtarreau** [comment]
Thanks a lot Walter for the very detailed analysis. I think I understand what could be happening internally and there are likely two thresholds as you've seen, one that would prevent a full record from being buffered before being deciphered, and another limit where this one can be buffered but there's not enough room in the output to store it. This might indeed require to slightly increase `tune.bufsize` because I'm not particularly fond of alternatives consisting in doing some double-buffering or stuff like this. I'm puzzled as to why it's only reported now, though. Plenty of other applications ought to have faced it, including haproxy chained onto itself. That's very weird.

**Comment by wdoekes** [comment]
One thing I forgot to mention, that might (?) affect the size of the buffers needed:
- we're using optional client certs (which I supplied during my tests);
  ```
  bind IP:443 ssl crt CERT no-sslv3 ca-file CA verify optional
  ```
- the cert would be placed in a header in pem format:
  ```
  http-request set-header X-Ssl-Client-Cert -----BEGIN\ CERTIFICATE-----\ %[ssl_c_der,base64]\ -----END\ CERTIFICATE-----\  if { ssl_c_used }
  ```

> I'm puzzled as to why it's only reported now, though. Plenty of other applications ought to have faced it, including haproxy chained onto itself. That's very weird.

You're not the only one. We've been using haproxy for years and years, so this was a strange find for us too.

My best guess so far is that applications commonly use 2^13 (8K) sized TLS records.

**Comment by wdoekes** [comment]
Okay. _So it was user error after all_ :grin: 

The buffers are only reached because of the `set-header` above.

## Reproducing

I took a random other host config and amended the `bind` with:
```
bind ... ca-file CAFILE verify optional
```
and added the extra header:
```
http-request set-header X-Ssl-Client-Cert -----BEGIN\ CERTIFICATE-----\ %[ssl_c_der,base64]\ -----END\ CERTIFICATE-----\  if { ssl_c_used }
```
Then I ran this against that host config, using `pysclient.py`[1] (using urandom to make sure we do not get compression):
```shell
dd bs=16000 count=1 if=/dev/urandom status=none |
  ./pysclient.py -connect HOST:443 -cert clientcert.crt -key clientcert.key
```
And indeed, at around `14420..14460` bytes of data we'll see 500-errors with `IR--` popping up, and above that, it changes to `PR--`.

## The fix

Because the certificate in base64/pem-format is about 1700 bytes, setting `tune.maxrewrite` to something is more sufficient:
```conf
tune.maxrewrite 1760
```
When the header_key+value fits, the problem disappears like snow, and we can enlarge the POST data to infinity without getting unexpected 500s.

## Answers

Sorry for the noise! :cry:  I think I have my answer concerning the buffers I need:

- no need to touch `tune.bufsize` beyond the default 16K
- make sure `tune.maxrewrite` is large enough to fix all our added headers

That only leaves the question of the `IR--` as reported. Not sure if you want that followed up here though.

---

[1] `pysclient.py`:
```python3
#!/usr/bin/env python3
import argparse
import socket
import ssl
import sys


def main():
    parser = argparse.ArgumentParser(description='PYthon openssl S_CLIENT')
    conn_arg = parser.add_argument('-connect', metavar='HOSTPORT', help=(
        'Connect to HOST:PORT'))
    #parser.add_argument('--tls1_v2')
    parser.add_argument('-cert', metavar='FILE', help=(
        'Client certificate filename'))
    parser.add_argument('-key', metavar='FILE', help=(
        'Client key filename'))

    args = parser.parse_args()
    if not args.connect:
        parser.error('-connect is mandatory')
    if bool(args.cert) ^ bool(args.key):
        parser.error('when specifying client cert, you need both -cert/-key')
    host, port = args.connect.split(':')
    port = int(port)

    if args.cert:
        context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
        context.load_cert_chain(certfile=args.cert, keyfile=args.key)
    else:
        context = ssl.create_default_context()

    # Load up data from stdin.
    data = sys.stdin.buffer.read()

    conn = context.wrap_socket(
        socket.socket(socket.AF_INET), server_hostname=host)
    conn.connect((host, port))

    # Write data
    header = (
        f'POST / HTTP/1.1\r\n'
        f'Host: {host}\r\n'
        f'Content-Length: {len(data)}\r\n'
        f'\r\n')
    print('WRITING:')
    print(header, end='')
    print('<data>')
    print()
    conn.write(header.encode('ascii') + data)

    # Receive data
    print('READING:')
    data = conn.read(32 * 1024)
    conn.close()
    print(data)


if __name__ == '__main__':
    main()
```

**Comment by wtarreau** [comment]
Ah cool, many many thanks for this update, it's quite a relief! I was really concerned about that area that I had no idea how to attack!

Regarding the `IR` flags, I'm almost sure they can happen when we fail to add a large header. IR indicates an internal error during request processing so that can match. It just seems to me that depending on where exactly we fail, it's possible to get different errors. Maybe we should add some doc about it to shorten the troubleshooting time in case someone else faces this case in the future.

**Comment by wdoekes** [comment]
I'm again sorry for causing alarm. Glad there is no bug.

As for the documentation, something like the following perhaps. I'm not too fond of my `I` text edits though, because the _"this should NEVER happen"_ contradicts with the _"this happens when the buffer is too small."_

```diff
diff --git a/doc/configuration.txt b/doc/configuration.txt
index 183710c35..27c95fb5f 100644
--- a/doc/configuration.txt
+++ b/doc/configuration.txt
@@ -2710,9 +2710,12 @@ tune.bufsize <number>
   addition, use of HTTP/2 mandates that this value must be 16384 or more. If an
   HTTP request is larger than (tune.bufsize - tune.maxrewrite), HAProxy will
   return HTTP 400 (Bad Request) error. Similarly if an HTTP response is larger
-  than this size, HAProxy will return HTTP 502 (Bad Gateway). Note that the
-  value set using this parameter will automatically be rounded up to the next
-  multiple of 8 on 32-bit machines and 16 on 64-bit machines.
+  than this size, HAProxy will return HTTP 502 (Bad Gateway). If the bufsize is
+  smaller than 16384 when reading large TLS records or if the maxrewrite is too
+  small to fit your extra headers, HAProxy will return HTTP 500 (Internal
+  Server Error). Note that the value set using this parameter will
+  automatically be rounded up to the next multiple of 8 on 32-bit machines and
+  16 on 64-bit machines.
 
 tune.comp.maxlevel <number>
   Sets the maximum compression level. The compression level affects CPU
@@ -2892,10 +2895,10 @@ tune.maxrewrite <number>
   bufsize, though that does not make much sense since there are rarely large
   numbers of headers to add. Setting it too high prevents processing of large
   requests or responses. Setting it too low prevents addition of new headers
-  to already large requests or to POST requests. It is generally wise to set it
-  to about 1024. It is automatically readjusted to half of bufsize if it is
-  larger than that. This means you don't have to worry about it when changing
-  bufsize.
+  to already large requests or to POST requests, causing a 500 (Internal Server
+  Error) to be generated. It is generally wise to set it to about 1024. It is
+  automatically readjusted to half of bufsize if it is larger than that. This
+  means you don't have to worry about it when changing bufsize.
 
 tune.pattern.cache-size <number>
   Sets the size of the pattern lookup cache to <number> entries. This is an LRU
@@ -22325,7 +22328,12 @@ each of which has a special meaning :
             connection limit enforcement, because a DENY filter was matched,
             because of a security check which detected and blocked a dangerous
             error in server response which might have caused information leak
-            (e.g. cacheable cookie).
+            (e.g. cacheable cookie). If this happens before a backend has been
+            selected, you will see "<NOSRV>" as server_name. If the buffers are
+            insufficient to decode TLS records or to add extra http headers
+            this event is also triggered. When using TLS it is recommended to
+            keep "tune.bufsize" at 16384 and enlarge "tune.maxrewrite" as
+            needed.
 
         L : the session was locally processed by HAProxy and was not passed to
             a server. This is what happens for stats and redirects.
@@ -22340,7 +22348,8 @@ each of which has a special meaning :
             This should NEVER happen, and you are encouraged to report any log
             containing this, because this would almost certainly be a bug. It
             would be wise to preventively restart the process after such an
-            event too, in case it would be caused by memory corruption.
+            event too, in case it would be caused by memory corruption. (This
+            event can also be seen when buffers are just slightly too small.)
 
         D : the session was killed by HAProxy because the server was detected
             as down and was configured to kill all connections when going down.
```

**Comment by wtarreau** [comment]
Don't worry, the usual way to deal with PEBKAC is to disappear, which wastes everyone's time. Here there's no time wasted and we have something to look at. Your remark regarding "should never happen" is particularly interesting. I think we should keep the internal error for what it really is, and add a new flag for failures (e.g. 'F'). That's something that didn't exist prior to the strict-mode so we didn't figure that an extra flag would have been welcome. I'm finding at least some that return the 'P' letter, but we really need to recheck everything now.

**Comment by capflam** [comment]
About this issue. Since a while, a `PR`/`PH` + `500-Internal-error` errors are reported for rewrite failures. And the configuration manual was updated accordingly. So I guess we can consider the issue as fixed.
