### ISSUE TITLE
How to obtain the ARM version of haproxy? 

### ISSUE THREAD

**Issue by fantastic2085** [haproxy/haproxy#1746]
### Your Feature Request

https://hub.docker.com/_/haproxy?tab=tags  Does the image obtained from this link support ARM?

### What are you trying to do?

Could you please tell me where I can get haProxy that supports ARM?

### Output of `haproxy -vv`

```plain
none
```

**Comment by chipitsine** [comment]
yes

![image](https://user-images.githubusercontent.com/2217296/173278580-a5dae37e-560d-42e7-ad60-ecb667424ca1.png)

**Comment by fantastic2085** [comment]
https://hub.docker.com/_/haproxy?tab=tags  Will the docker image downloaded by this link automatically adapt?

**Comment by TimWolla** [comment]
That Docker image is not maintained by the HAProxy team, this issue tracker is the wrong place to ask.

For questions specific to the image, this repository is appropriate: https://github.com/docker-library/haproxy/. For general questions about Docker's behavior ("Will the docker image downloaded by this link automatically adapt?") a Docker support channel should be used.

**Comment by fantastic2085** [comment]
Thank you for your patience

**Comment by TimWolla** [comment]
See docker-library/haproxy#187 for the upstream question.
