### ISSUE TITLE
QUIC overtime HAProxy memory consumption increase

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#1749]
### Detailed Description of the Problem

When servicing requests via QUIC, HAProxy's resident memory consumption endlessly rises.

After first discussing it in passing [here](https://github.com/haproxy/haproxy/issues/1738#issuecomment-1152930400), @a-denoyelle suggested it was not unexpected at the moment and [there](https://github.com/haproxy/haproxy/issues/1747#issuecomment-1155136760) that a generic issue was a good place to discuss it and share information

### Expected Behavior

That HAProxy's usual excellent memory characteristics be upheld with QUIC

### Steps to Reproduce the Behavior

1. Use a QUIC binding to serve requests

### What is your configuration?

N/A (related to the protocol impl at the time of writing)

### Output of `haproxy -vv`

Generic to the protocol impl but was observed on at least 2.7-dev (https://github.com/haproxy/haproxy/commit/040955fb39f8df183adda6fa19761a1ede36f624) with both QuicTLS 1.1.1o and 3.0.3

**Comment by Tristan971** [comment]
Quoting myself in #1738:
> One thing I noted before seeing the content was that it took a sensible amount of time to copy the coredump around... And indeed, it was a 1.9GB coredump, which is very uncharacteristic for us.
> HAProxy typically sits more in the range of 250MB of RAM on our average load-balancer (the guinea pig ones I'm using for these tests are also by far the least used).

Unfortunately I don't have much more detailed observations to share, nor am I aware of how we can help as users to investigate the matter; presumably looking at the rough content of a coredump after a few hours?

**Comment by haproxyFred** [comment]
Hello @Tristan971, you should try to link haproxy against libasan, then send a SIGUSR1 signal to haproxy after you suspect it has consumed too much memory. libasan would dump useful information about the memory leaks (see https://github.com/google/sanitizers).

On my side, something seems broken on my system:
==3636143==LeakSanitizer has encountered a fatal error.
==3636143==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==3636143==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)

**Comment by Tristan971** [comment]
I can try doing that, sure; any compilation/linking/runtime flags twiddling you'd recommend on libasan/haproxy side or just the defaults? (seeing the LSAN_OPTIONS bit in your example above)

**Comment by haproxyFred** [comment]
LASAN_OPTIONS dumped above was to enable the debug mode I guess, to fix the crash ;)
Give a try to these options, but may depend on your toolchain:
-fsanitize=leak as compilation option, -lasan as linking option.

**Comment by Tristan971** [comment]
just fwiw im likely not going to be able to test it for a few more days

**Comment by haproxyFred** [comment]
Ok.

**Comment by a-denoyelle** [comment]
I just pushed two fixes (I referenced the wrong issue number). For the record here they are.
https://github.com/haproxy/haproxy/commit/2c31e1293661cd44b71457b8fd0567b08ef95b0b
https://github.com/haproxy/haproxy/commit/23f908ccd62b1123e0fe1ed73743dcd8390890e1

This should improve the situation but there may be other leaks left.

**Comment by Tristan971** [comment]
Just deployed those (or rather 2.7's 1bad7db).

Will give it a couple of hours and see what things looks like and deploy an ASAN-linked build as per fred's recommendation to get some stats then (ran out of time for today already alas)

**Comment by Tristan971** [comment]
Alas the memleak is still there, and I can't reliably get the rate of growth as I don't have per-process memory metrics, only node-wide ones. And those are useless for this as the colocated varnish makes too much noise as it grows and shrinks.

Will make an ASAN build tmr and measure that

**Comment by wtarreau** [comment]
Thanks. That's sad, but ultimately we'll tackle it.

**Comment by wtarreau** [comment]
@Tristan971 in your other issue #1759, your "show pools" output looks quite high to me:
   - Pool quic_dgram (216 bytes) : 1236349 allocated (267051384 bytes), 1236349 used (~11 by thread caches), needed_avg 1236345, 0 failures, 5 users, @0x55fdb0722080 [SHARED]

Unless your amount of QUIC trafic is extreme, seeing 1.2 million quic dgrams in flight looks pretty high, so I htink that the memory leak is there. In addition, I'm noting that your number of lost sent packets is ~140000, maybe there's a relation and that can help us spot where the problem is.

**Comment by wtarreau** [comment]
Hmmm actually I'm seeing that it could also be any other pool of similar size since they're shared. Could you please pass -dMno-merge on the command line so that pools are all separate ? The show pools output will be much larger but we'll know exactly which entry is leaking.

**Comment by Tristan971** [comment]
> That's sad, but ultimately we'll tackle it.

Never doubted that! :-)

> Unless your amount of QUIC trafic is extreme, seeing 1.2 million quic dgrams in flight looks pretty high, so I htink that the memory leak is there.

I'm not certain what qualifies as "extreme" and I suspect that's not the case on that one lone LB, but at least I can quantify the traffic across it. 

<details>
<summary>Traffic statistics</summary>

At the time I ran the command in #1759, here were the last hour of traffic stats for the LB I ran `show pools` against:

HTTP reqs
<img width="702" alt="http request rate" src="https://user-images.githubusercontent.com/875533/175246948-9678789f-b707-4674-9908-180a6237f056.png">

Frontend throughput bps
<img width="702" alt="frontend throughput bps" src="https://user-images.githubusercontent.com/875533/175247115-84ed6734-ac70-4675-9a0f-9b67f2662895.png">

HTTP version spread across the same timerange, so about 16% of traffic over QUIC/HTTP3 (note it's not quite a perfect correlation, as the API was excluded from H3, while it represents a lower % of throughput per req, but oh well)

<img width="839" alt="http version spread" src="https://user-images.githubusercontent.com/875533/175248657-ca40eeff-551f-4d38-8baa-8aaea073600f.png">

</details>

> Could you please pass -dMno-merge on the command line so that pools are all separate

Will do in a short bit, just need to figure out the correct systemd-overrides-fu to add that somewhat cleanly

**Comment by Tristan971** [comment]
Another perhaps relevant bit (just guessing), is the # of frontend sessions (as per `haproxy_frontend_current_sessions` to be precise) grows quite a bit when using QUIC, as visible on the chart below

<img width="697" alt="Screenshot 2022-06-23 at 10 16 31" src="https://user-images.githubusercontent.com/875533/175251113-4fa37f10-2e8f-4a85-a433-861a345f1d92.png">

**Comment by haproxyFred** [comment]
About libASAN issue, before waiting for hours, you should try to send a USR1 signal to haproxy to check you have not the same problem than me with libASAN. You should see such traces:

==678233==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 64 byte(s) in 2 object(s) allocated from:
    0 0x7ff46861edb0 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
    1 0x7ff4683a81c9 in CRYPTO_zalloc (/home/flecaille/src/haproxy/../openssl/build/lib/libcrypto.so.81.1.1+0x1801c9)

If this is the case, as told by Willy "insecure-fork-wanted" global option fixes the libASAN issue on my side.

**Comment by Tristan971** [comment]
Ah thanks, would likely not have guessed that alone 👍

**Comment by haproxyFred** [comment]
@Willy: as discussed, I have just pushed two fixes in https://github.com/haproxytech/quic-dev/commits/fle-quic-bugs.

**Comment by haproxyFred** [comment]
@wtarreau: there is a remaining compilation error to fix.

**Comment by Tristan971** [comment]
Fwiw I've tried to get the leak sanitizer going but somewhat couldn't figure it out it seems...

ended up with CC/LD both set to clang and `CFLAGS  = -fsanitize=leak -static-libsan` but it does... nothing, as far as I can tell. SIGUSR1 kills don't cause any san-related logs ([here](https://gitlab.com/mangadex-pub/haproxy/-/jobs/2632137169) is the compilation step)

Note that before that I tried gcc + CFLAG'd -fsanitize=leak + ADDLIB'd -lasan and ran into the same problem as https://github.com/google/sanitizers/issues/796 where they suggested to the author that `-lasan` was pretty much the devil, hence why I tried the clang builtin sanitizer route 😓 

In the meantime I added in the non-shared pool flags and am waiting on the test instance to grow to export the result

**Comment by wtarreau** [comment]
@haproxyFred thanks I'll have a look.
@Tristan971 don't worry, we finally managed to reproduce it with Fred and his pending fixes address will it. I'll just have to pick them and merge them (possibly after checking the build error Fred mentioned). Stay tuned :-)

**Comment by Tristan971** [comment]
Oh, very nice! :-)

**Comment by haproxyFred** [comment]
@wtarreau build error fixed!
@Tristan971 Note that there may be remaining memleak issues.

**Comment by wtarreau** [comment]
OK I'll pick them. Thanks Fred!

**Comment by wtarreau** [comment]
Just pushed now! And I confirm that for me the issue is gone as well on my machine. Thank you Fred!
@Tristan971 I'm leaving it to you to recheck now, but feel free to close if it's OK for you.

**Comment by Tristan971** [comment]
Nice, I'll have a go at it sometime tomorrow then 👍

**Comment by haproxyFred** [comment]
In fact the bug was partially fixed :smile:
See my last commit in the same fle-quic-bugs branch.

**Comment by wtarreau** [comment]
Ah yes, good catch, I remembered that one. Now merged as well, thank you Fred :-)

**Comment by Tristan971** [comment]
Well I ended up giving it a try right now, and here are the results...

Memory usage before with pre/post QUIC enabling

<img width="1406" alt="Screenshot 2022-06-23 at 23 36 09" src="https://user-images.githubusercontent.com/875533/175406618-baccf638-6c52-42cc-8dc6-974d4c068d89.png">

Memory usage after with pre/post QUIC enabling

<img width="1403" alt="Screenshot 2022-06-23 at 23 36 36" src="https://user-images.githubusercontent.com/875533/175406649-dbac92bd-69be-4053-ac7b-f4595f0fac29.png">

I will now close it :-) Thanks a lot to both!

**Comment by wtarreau** [comment]
Thanks for the quick feedback! However I'm reopening, I forgot that now we need to backport QUIC fixes to 2.6 :-)
