### ISSUE TITLE
TCP Fast Open doesn't work to backend server

### ISSUE THREAD

**Issue by Exocomp** [haproxy/haproxy#175]
## Output of `haproxy -vv` and `uname -a`

```
uname -a

Linux box1 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
haproxy -vv

HA-Proxy version 2.0.2 2019/07/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.38 2015-11-23
Running on PCRE version : 8.38 2015-11-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

## What's the configuration?

```
global
        user haproxy
        group haproxy
        daemon
        nbproc 1

defaults
        timeout connect 5s
        timeout client 5s
        timeout server 20s

frontend myfrontend
        bind 192.168.1.10:80
        mode http
        use_backend mybackend

backend mybackend
        mode http
        retry-on conn-failure empty-response response-timeout
        server box2 192.168.1.20:5003 tfo
```

## Steps to reproduce the behavior

1.  Use tcpdump or what ever means to collection network traffic on the HAProxy box
2.  From a client make an HTTP call to HAProxy (without TCP Fast Open)
3.  View the tcpdump

## Actual behavior

The HTTP call from HAProxy to Backend server does not use TCP Fast Open.

## Expected behavior

The HTTP call from HAProxy to Backend server should use TCP Fast Open.

## My thoughts

I'm starting to use TCP Fast Open with my setup and I thought I'd start implementing it when I saw that HAProxy supports TCP Fast Open with backend servers.  I'm using the latest build of HAProxy 2.0.2 but I'm not able to get it to work.

My initial HTTP call (client) to HAProxy is not using TCP Fast Open, however, I have added the "tfo" parameter on the server line and my understanding is that HAProxy should use TCP Fast Open with the backend server.

I've enabled TCP Fast Open at the OS level:

```
cat /proc/sys/net/ipv4/tcp_fastopen
3
```
Here is the SYN packet from HAProxy to the Backend server, it doesn't show the TCP Fast Open Cookie Request which I expected to see:

![image](https://user-images.githubusercontent.com/25571083/61392033-970e7500-a883-11e9-8510-6c7da9e2a244.png)

If I'm misunderstanding how it is supposed to work my apologies.

**Comment by wtarreau** [comment]
Are you sure your server supports TFO ? I'm asking because I remember
when I first experimented with TFO a few years ago, I noticed that
after some repeated errors, the client would stop using TFO for a
given destination or maybe globally. Thus I suspect there's a negative
cache somewhere in the system to temporarily disable TFO towards a
misbehaving server.

Please run your test through strace so that we can see how the outgoing
socket is configured and how connect() is done.

**Comment by Exocomp** [comment]
@wtarreau 

> Are you sure your server supports TFO ?

I believe so, however this is my first time working with TFO so bear with me.  When using the "tfo" parameter on bind in the frontend section the server generates a TFO cookie. So at least that part is working for sure.

Is it possible that TFO is working (on the server) on the receiving end (listening socket) but not for outgoing connections? Since `cat /proc/sys/net/ipv4/tcp_fastopen` returns 3 that _should_ enable both as far as the docs I'm reading.

> Please run your test through strace so that we can see how the outgoing socket is configured and how connect() is done

Let me read up on that and give that a shot.

By the way I've been using HAProxy for a couple of years so wanted to take the chance to thank you for your relentless effort and a great product!

**Comment by Exocomp** [comment]
@wtarreau 

Thanks for recommending strace.  I see that it is making a call to:

`setsockopt(13, SOL_TCP, 0x1e /* TCP_??? */, [1], 4) `

0x1e = TCP_FASTOPEN_CONNECT

So if what I'm reading is correct looks like TCP_FASTOPEN_CONNECT was added in kernal 4.11, I'm running 4.4. So that's my issue.

What tripped me up was that TFO is supported prior to 4.4 however not the new "TCP_FASTOPEN_CONNECT" option.

I see your documentation it does state the version 4.11 requirement so I think you guys are fine.

Let me upgrade and try again and I'll post an update.

**Comment by Exocomp** [comment]
@wtarreau 

```
uname -msr
Linux 4.11.2-041102-generic x86_64
```

Works now :)

Thanks again for your help!

**Comment by wtarreau** [comment]
Thanks for your tests and feedback. Indeed it all completely makes sense.
The older API was a mess and not really implementable. There's not much
we can do when the new one has no effect, as even a warning or anything
could cause trouble in pretty valid cases while everything works fine,
but less optimally.
