### ISSUE TITLE
arm64 graviton2 build fails on travis-ci

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1755]
### Tool Name and Version

gcc-9.3

### Code Report

```plain
src/ssl_ckch.c: In function ‘cli_io_handler_commit_cafile_crlfile’:

src/ssl_ckch.c:2720:5: error: ‘path’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

 2720 |     chunk_printf(&trash, "Committing %s", path);

      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated due to -Wfatal-errors.
```

3 failures:

https://app.travis-ci.com/github/haproxy/haproxy/jobs/573980804
https://app.travis-ci.com/github/haproxy/haproxy/jobs/573238983
https://app.travis-ci.com/github/haproxy/haproxy/jobs/572446622
```


### Additional Information

_No response_

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
Thanks, I could reproduce it on an ubuntu 20.04 on ARM64. with gcc-9.4. At first I thought the compiler was stupid, but in fact the construct is too complex for it to spot that this cannot happen: in case of incorrect cafile_type, path is not set, we jump to label "error" that's still inside the loop and the compiler cannot verify that the chaining of state changes only leads to the end. Presetting the path to NULL fixes it. I'll write a patch.

**Comment by wtarreau** [comment]
It's OK for me now.

**Comment by chipitsine** [comment]
thanks, I'll keep an eye on travis-ci
