### ISSUE TITLE
QUIC occasional stalled requests

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#1759]
### Detailed Description of the Problem

Alluded to it first in #1737 [here](https://github.com/haproxy/haproxy/issues/1737#issuecomment-1151642072) and recommended to raise it separately by @haproxyFred so here I am.

Every now and then a (QUIC) request is stalled according to the browser, like so:
![](https://user-images.githubusercontent.com/875533/172947710-76c91714-c797-4978-bd17-bfdbcdfb454f.png).

ie the browser doesn't seem to ever end up aware of the response being complete (or the response is indeed not complete and something breaks on the way back).

### Expected Behavior

Responses are complete and browsers are aware of them being complete

### Steps to Reproduce the Behavior

1. Run HAProxy (up to 2.7's current master, 1bad7db) with a QUIC-enabled frontend
2. Fire a QUIC request (at least with a Chromium based browser, including and especially Firefox)
3. Observe the request never finishing

### What is your configuration?

N/A. Same as other issues, ie straightforward QUIC+L7->L7 proxying. You can find a(n annoyingly noisy) snippet in #1738

### Output of `haproxy -vv`

Note: happens on 2.6.0, 2.6.1 and 2.7-dev, with both QuicTLS 1.1.1o and 3.0.3

---

```plain
HAProxy version 2.7-dev0-1bad7db+mangadex-10d88f2 2022-06-22T15:09+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.4.143-1-pve #1 SMP PVE 5.4.143-1 (Tue, 28 Sep 2021 09:10:37 +0200) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=5
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_STATIC_PCRE2=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE +STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT +QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 3.0.3+quic-mangadex-10d88f2 22 Jun 2022
Running on OpenSSL version : OpenSSL 3.0.3+quic-mangadex-10d88f2 22 Jun 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

I unfortunately don't have that much reliable metrics for this but a few things I observed:

Our API is much more impacted than our frontend (static JS+HTML) or static images. As example of HTTP calls (you do need SNI and Host header match however, if you make some sort of local proxy) here follows (all non-authenticated GETs):
- API: https://api.mangadex.org/list/1f43956d-9fe6-478e-9805-aa75ec0ac45e?includes[]=user
- Frontend/static: https://mangadex.org/flags/gb.svg

For our users' sake this is obviously not globally enabled etc, so you likely will need to force QUIC usage on your browser/client side, but it should be available worldwide nonetheless.

For how differently they are backend-wise:
- API is proxied by a local varnish instance
- Frontend is proxied by a local varnish instance
- This example static image is proxied by a local nginx cache

They should also overall have similar timings, due to all being locally cached on the edge node, and the HAProxy<>{nginx, varnish} being plain HTTP.

I suspect this might be useful so here are the pools on one node:
```
$ echo "show pools" | socat unix-connect:/run/haproxy/admin.sock stdio
Dumping pools usage. Use SIGQUIT to flush them.
  - Pool quic_tls_iv (24 bytes) : 3207 allocated (76968 bytes), 3207 used (~30 by thread caches), needed_avg 3212, 0 failures, 10 users, @0x55fdb07263c0 [SHARED]
  - Pool quic_arng_p (56 bytes) : 7231 allocated (404936 bytes), 7231 used (~208 by thread caches), needed_avg 7227, 0 failures, 34 users, @0x55fdb071cc80 [SHARED]
  - Pool quic_rx_cry (88 bytes) : 2296 allocated (202048 bytes), 2296 used (~188 by thread caches), needed_avg 2301, 0 failures, 13 users, @0x55fdb071ff00 [SHARED]
  - Pool comp_ctx (120 bytes) : 105 allocated (12600 bytes), 105 used (~33 by thread caches), needed_avg 103, 0 failures, 2 users, @0x55fdb072fb00 [SHARED]
  - Pool ssl_sock_ct (152 bytes) : 14992 allocated (2278784 bytes), 14992 used (~137 by thread caches), needed_avg 14992, 0 failures, 12 users, @0x55fdb071aac0 [SHARED]
  - Pool quic_frame_ (184 bytes) : 10404 allocated (1914336 bytes), 10404 used (~201 by thread caches), needed_avg 10400, 0 failures, 13 users, @0x55fdb071dd40 [SHARED]
  - Pool quic_dgram (216 bytes) : 1236349 allocated (267051384 bytes), 1236349 used (~11 by thread caches), needed_avg 1236345, 0 failures, 5 users, @0x55fdb0722080 [SHARED]
  - Pool session (248 bytes) : 255 allocated (63240 bytes), 255 used (~8 by thread caches), needed_avg 251, 0 failures, 1 users, @0x55fdb072ea40 [SHARED]
  - Pool ssl_sock_cl (280 bytes) : 773 allocated (216440 bytes), 773 used (~20 by thread caches), needed_avg 773, 0 failures, 6 users, @0x55fdb0719a00 [SHARED]
  - Pool spoe_ctx (312 bytes) : 0 allocated (0 bytes), 0 used (~0 by thread caches), needed_avg 0, 0 failures, 1 users, @0x55fdb072b7c0 [SHARED]
  - Pool quic_rx_pac (408 bytes) : 1097 allocated (447576 bytes), 1097 used (~40 by thread caches), needed_avg 1093, 0 failures, 1 users, @0x55fdb0720fc0 [SHARED]
  - Pool qcc (472 bytes) : 136 allocated (64192 bytes), 136 used (~3 by thread caches), needed_avg 139, 0 failures, 2 users, @0x55fdb0727480 [SHARED]
  - Pool resolv_answ (600 bytes) : 0 allocated (0 bytes), 0 used (~0 by thread caches), needed_avg 0, 0 failures, 1 users, @0x55fdb072c8c0 [SHARED]
  - Pool stream (1016 bytes) : 146 allocated (148336 bytes), 146 used (~44 by thread caches), needed_avg 144, 0 failures, 1 users, @0x55fdb072a700 [SHARED]
  - Pool quic_crypto (1048 bytes) : 1648 allocated (1727104 bytes), 1648 used (~47 by thread caches), needed_avg 1646, 0 failures, 2 users, @0x55fdb071ee00 [SHARED]
  - Pool fcgi_conn (1240 bytes) : 0 allocated (0 bytes), 0 used (~0 by thread caches), needed_avg 0, 0 failures, 1 users, @0x55fdb0729640 [SHARED]
  - Pool h2c (1304 bytes) : 100 allocated (130400 bytes), 100 used (~8 by thread caches), needed_avg 97, 0 failures, 1 users, @0x55fdb0728580 [SHARED]
  - Pool quic_conn (3864 bytes) : 253 allocated (977592 bytes), 253 used (~2 by thread caches), needed_avg 254, 0 failures, 1 users, @0x55fdb0723140 [SHARED]
  - Pool hpack_tbl (4096 bytes) : 100 allocated (409600 bytes), 100 used (~8 by thread caches), needed_avg 97, 0 failures, 1 users, @0x55fdb0a10600 [SHARED]
  - Pool quic_tx_rin (4120 bytes) : 66 allocated (271920 bytes), 66 used (~2 by thread caches), needed_avg 65, 0 failures, 2 users, @0x55fdb0725300 [SHARED]
  - Pool buffer (16384 bytes) : 1851 allocated (30326784 bytes), 1851 used (~149 by thread caches), needed_avg 1847, 0 failures, 1 users, @0x55fdb0a06d80 [SHARED]
  - Pool quic_conn_r (16408 bytes) : 252 allocated (4134816 bytes), 252 used (~1 by thread caches), needed_avg 252, 0 failures, 1 users, @0x55fdb0724240 [SHARED]
  - Pool trash (16416 bytes) : 8 allocated (131328 bytes), 8 used (~7 by thread caches), needed_avg 7, 0 failures, 1 users, @0x55fdb0730c00
  - Pool dns_msg_buf (65560 bytes) : 0 allocated (0 bytes), 0 used (~0 by thread caches), needed_avg 0, 0 failures, 1 users, @0x55fdb072d980 [SHARED]
  - Pool quic_rxbuf_ (262168 bytes) : 64 allocated (16778752 bytes), 64 used (~0 by thread caches), needed_avg 60, 0 failures, 1 users, @0x55fdb071bbc0 [SHARED]
Total: 25 pools, 327769136 bytes allocated, 327769136 used (~2844040 by thread caches).
```

As usual, happy to try patches or extra config/compile options to get more useful info if necessary.

**Comment by Tristan971** [comment]
Additionally, the result of adding `stats show-modules` on the stats frontend. Not sure if it dupes the admin socket output there or how to export it in a nicer way so here's a screenshot in the meantime.

QUIC:
<img width="420" alt="Screenshot 2022-06-22 at 18 32 21" src="https://user-images.githubusercontent.com/875533/175088555-711da4d4-5e49-469d-9d3f-127d7495438b.png">

H3:
<img width="421" alt="Screenshot 2022-06-22 at 18 35 53" src="https://user-images.githubusercontent.com/875533/175089486-0e7ea52a-82cd-40da-9d3c-f6f67961afd7.png">

(And for comparison sake if relevant) H2
<img width="342" alt="Screenshot 2022-06-22 at 18 35 15" src="https://user-images.githubusercontent.com/875533/175089242-a7b8454e-a261-4f12-870f-e9a2b8f9b751.png">

**Comment by a-denoyelle** [comment]
I can reproduce easily this if I stop doing requests for a time longer than the configured `timeout client`. This is because our management of connection closing is incomplete for the moment. When the timeout expires, the upper-layer of our QUIC stack dies without notify the client which will continue to use the partially dead connection.

To fix this issue we have to emit a H3 GOAWAY and a CONNECTION_CLOSE when the timeout expires. However it's not completely clear for us how we should proceed on this. In the meantime, you can raise the `timeout client` to be bigger than `tune.quic.frontend.max-idle-timeout` (by default 30s). Please tell us if you encounter still or not the issue after.

**Comment by Tristan971** [comment]
Trying that with `timeout client 32s` and the default for quic max idle timemout.

After a quic(k🙂) check, it seems to fix parts of the issue, specifically the frontend flakiness on some browsers and particularly Firefox, so that's very nice (also, in looking up how to not let that open us up to slowloris-type attacks I found out about how `timeout http-request` works, so that's nice).

However I kept the API on h2 as its requests still get stalled with those timeouts (I don't have a specific %-age but enough that no nontrivial page loads entirely successfully), so there's probably a second problem in there somewhere

**Comment by Tristan971** [comment]
Here are a couple of maybe-relevant observations (if they're entirely unrelated, I'll raise it as a separate issue once the others are fixed, in case they happen to fix it) to this one and/or #1737. Either way, I observe a very significant increase in active sessions and total request times when serving things via QUIC.

Sessions (`haproxy_frontend_current_sessions`):
![2022-06-28 15_11_28-HAProxy 2 Full - Grafana and 10 more pages - Personal - Microsoft​ Edge Beta](https://user-images.githubusercontent.com/875533/176200923-383f80e3-74de-45b5-8070-a3f23bbebd5a.png)

Times (`haproxy_backend_total_time_average_seconds` and `haproxy_backend_response_time_average_seconds`) respectively:
![2022-06-28 15_09_58-HAProxy 2 Full - Grafana and 10 more pages - Personal - Microsoft​ Edge Beta](https://user-images.githubusercontent.com/875533/176201532-b83a95c3-7654-4fa6-9e91-aa192054158d.png)

I mention that since I wonder if it's because of something else also meant to "end" requests never triggering (and thus keeping them alive longer and "inflating" metrics)

**Comment by Tristan971** [comment]
Just passing by to say that I've reenabled advertisement of QUIC to a portion of users hitting a build of 53bfac8c632dd77a199194f70062bfd86270d400 and it seems that the recent quic fixes caught that one as I can't reproduce it anymore so far! 🎉 

From a glance at the recent commit messages, it sounds like it could be e53b489826ba9760a527b461095402ca05d2b6be that delivered this gift

Will keep an eye out over the next few days, but this certainly looks promising :-)

**Comment by Tristan971** [comment]
A few more observations. It used to be intermittent with our frontend and 100% reproducible with our API. Both are now looking fixed (esp the latter is relevant, as merely 1-2 homepage refreshes were enough to trigger it).

As for my TTFB/TX time observations from above, they are still the same. But frankly I'm starting to doubt the metric itself rather than the QUIC mux.
The scale of TX times claimed is simply too unreasonably high to be justified by anything but "many users hitting multi-seconds timeouts consistently bringing the average up".

That said, I'll just keep collecting data and see if any pattern emerges from it. If everything looks good and users don't complain, I will probably enable it in at least all of Europe when 2.6.3 is out.

**Comment by Tristan971** [comment]
I believe this issue is fixed, now that 2.6.5 is emitted. Never had any other occurence of it on my end either over the past few weeks of 2.7-dev.

**Comment by haproxyFred** [comment]
Indeed there are chances this commit fixed this issue:
```
commit 0937ad2b864c8dfb96ab0435a7420dcc2d13f624
Author: Frédéric Lécaille <flecaille@haproxy.com>
Date:   Wed Aug 24 17:57:09 2022 +0200

    BUG/MINOR: quic: Stalled connections (missing I/O handler wakeup)
```

**Comment by Tristan971** [comment]
Shall I close it then? I would have but my understanding is it is usually maintainers that do so

**Comment by haproxyFred** [comment]
No, you do not have to close it.

**Comment by a-denoyelle** [comment]
Closed with backport done.
