### ISSUE TITLE
abortonclose regression

### ISSUE THREAD

**Issue by pem3v78** [haproxy/haproxy#1762]
### Detailed Description of the Problem

We recently upgraded from 2.0.20 to 2.0.29 and seen new timeouts. The example status line:

27/Jun/2022:18:59:22.144 10.0.0.14:41570 http-in backend1/server1 0/0/0/-1/5005 400 211 - - CH-- 614/614/4/4/0 0/0 "POST /my_uri HTTP/1.1"

The timeout of 5 seconds is set on client. Seems HAProxy is stuck processing some requests. This is consistent on every environment. Only HTTP 1.1 is used by client and in backends. On version 2.0.20 there are no request with termination state of CH-- in our envs.

### Expected Behavior

No timeouts in 2.0.29 just as in 2.0.20.

### Steps to Reproduce the Behavior

I don't have an isolated test case for it. I run a suite of tests (running for ten minutes) and about four requests fail with termination status of CH--.

> 

### Do you have any idea what may have caused this?

I bisected the code and it shows:

366312a56fe04e9fc1a684f69752ad381dd7e7e7 is the first bad commit
commit [366312a56fe04e9fc1a684f69752ad381dd7e7e7](http://git.haproxy.org/?p=haproxy-2.0.git;a=commit;h=366312a56fe04e9fc1a684f69752ad381dd7e7e7)
Author: Christopher Faulet <cfaulet@haproxy.com>
Date:   Thu Apr 8 18:34:30 2021 +0200

    MEDIUM: mux-h1: Don't block reads when waiting for the other side

    When we are waiting for the other side to read more data, or to read the
    next request, we must only stop the processing of input data and not the
    data receipt. This patch don't change anything on the subscribes for
    reads. So it should not change anything. The only difference is that the H1
    connection will try to read data if it is woken up for an I/O event and if
    it was subscribed for reads.

    This patch is required to fix abortonclose option for H1 client connections.

    (cherry picked from commit ec4207cb68b1d7d50e06d35aaa73586e2c7d46b0)
    [Cf: H1C_F_IN_BUSY flag is used instead of H1C_F_WAIT_OUTPUT]
    Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>
    (cherry picked from commit 655205413a779da086def0365d7a567cf37c2642)
    Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>
    (cherry picked from commit a325112ff883e306ff115a8dff4ef7070e990791)
    [Cf: commits 44410b03a ("MINOR: conn-stream: Force mux to wait for read events
         if abortonclose is set") and c4f8ce7c3 ("BUG/MEDIUM: mux-h1: Properly
         report client close if abortonclose option is set") are ignored because
         mux-h1 wakeups and subscribes are now handled the same way. This one is
         enough to fix abortonclose option.]
    Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>

:040000 040000 1b7d3cbe2bb09be04666f2ed174ecd9e3b3fe71d 435ca64caba6d99e99f3a41eb1d0f4c0afc55dc2 M      src

### Do you have an idea how to solve the issue?

Workaround is to remove abortonclose from configuration but would like to see real fix in code.

### What is your configuration?

```haproxy
global
    log 127.0.0.1   local0
    log 127.0.0.1   local1 notice
    maxconn 8192
    chroot /usr/share/haproxy
    uid 99
    gid 99
    daemon
    stats socket /run/haproxy.sock mode 770 expose-fd listeners

defaults
    log global
    mode http
    retries 3
    timeout connect 5s
    timeout client  10m
    timeout server  10m
    balance roundrobin

    option dontlognull
    option redispatch
    option forwardfor
    option abortonclose
    option http-server-close
    option http-pretend-keepalive

    default-server fall 2 check weight 20 slowstart 1m
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.0.29-5e15b0f 2022/05/13 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -m64 -march=x86-64 -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_SLZ=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -MY_ACCEPT4 -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

**Comment by capflam** [comment]
`CH--` means the client aborted while HAproxy was waiting for the server response. I guess your client has a timeout of 5s. It is the purpose of the `abortonclose` option. I remember this option was broken, but I don't know if the 2.0.20 was concerned.

Here, at first glance, everything works as expected. The bug seems to be on the 2.0.20 in your case. If you don't want to abort when the client closes the connection, you must indeed remove `abortonclose` option.

**Comment by capflam** [comment]
I performed a quick test on the 2.0.20, and indeed the `abortonclose` is not working on this version. So, it is not a regression but a fix :)

**Comment by pem3v78** [comment]
You are right. I wish the abortonclose had never been broken. I introduced the option to our config six years ago and all was well back then. In the mean time the option stopped working in some version and we failed to spot it. After the option was fixed we noticed increased number of CH-- requests because the clients behavior changed. Indeed logs on 2.0.20 show there are requests with total time much bigger than 5 seconds and they end in http status 200. Since we are not able to influence the clients, we have removed abortonclose from config and upgraded to 2.0.29 and all is well. Please close this issue and edit the labels as "work as intended". This is indeed a fix and not a bug. Thanks for clarification.
