### ISSUE TITLE
log directive's 'minlevel' is not capping log events

### ISSUE THREAD

**Issue by NickMRamirez** [haproxy/haproxy#1764]
### Detailed Description of the Problem

The log directive accepts a `minlevel` parameter, which should:

```
An optional minimum level can be specified. If it
is set, logs emitted with a more severe level than this one will
 be capped to this level. This is used to avoid sending "emerg"
messages on all terminals on some default syslog configurations
```

I set a minlevel so that it should capture only info level traffic, which is only TCP and HTTP requests. Not up/down server status. The docs say, "Level "notice" will be used to indicate a server going up," 

```
log   127.0.0.1 local0 info info
```

But my logs are still showing up/down server status.

```
Jun 29 17:11:37 localhost hapee-lb[15594]: 192.168.56.1:62927 [29/Jun/2022:17:11:37.528] fe_main webservers/s1 0/0/0/1/1 200 483 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
Jun 29 17:11:38 localhost hapee-lb[15594]: 192.168.56.1:62927 [29/Jun/2022:17:11:38.301] fe_main webservers/s2 0/0/0/3/3 200 483 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
Jun 29 17:12:50 localhost hapee-lb[15594]: Server webservers/s2 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Jun 29 17:12:51 localhost hapee-lb[15594]: Server webservers/s1 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
Jun 29 17:12:51 localhost hapee-lb[15594]: backend webservers has no server available!
Jun 29 17:13:22 localhost hapee-lb[15594]: Server webservers/s2 is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
Jun 29 17:13:23 localhost hapee-lb[15594]: Server webservers/s1 is UP, reason: Layer4 check passed, check duration: 0ms. 2 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
```

### Expected Behavior

The `minlevel` parameter should cap log events at the given level. In other words, I should be able to collect only info level events, and not more severe events.

### Steps to Reproduce the Behavior

1. Set the minlevel, such as:

```
log                127.0.0.1 local0 info info
```

2. Stop and start backend servers.
3. Check whether the logs show the server up/down events.

### What is your configuration?

```haproxy
global
    maxconn            75000
    log                127.0.0.1 local0 info info
    log                127.0.0.1 local1 notice
    user               hapee-lb
    group              hapee
    chroot             /var/empty
    pidfile            /var/run/hapee-2.5/hapee-lb.pid
    stats socket       /var/run/hapee-2.5/hapee-lb.sock user hapee-lb group hapee mode 660 level admin expose-fd listeners
    stats socket       /var/run/hapee-extras/hapee-lb.sock user hapee-lb group hapee mode 660
    stats socket       ipv4@127.0.0.1:9999 level admin  expose-fd listeners
    stats timeout      10m
    setenv HTTP_LOG    "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
    module-path        /opt/hapee-2.5/modules
    # module-load    hapee-lb-modsecurity.so
    # modsecurity-deny-blocking-io
    # module-load        hapee-lb-update.so

# dynamic-update
#   update id /etc/hapee-2.5/mymap.map  url http://192.168.50.25:80/  delay 10s  log map

defaults
    mode               http
    log                global
    option             httplog
    option             dontlognull
    option             forwardfor except 127.0.0.0/8
    option             redispatch
    retries            3
    timeout connect    10s
    timeout client     30s
    timeout client-fin 30s
    timeout server     30s
    
frontend fe_main
  bind :80
  # filter modsecurity owasp_crs rules-file /etc/hapee-2.5/modsec.rules.d/lb-modsecurity.conf
  default_backend webservers

backend webservers
  balance roundrobin
  server s1 127.0.0.1:8080 check weight 100 maxconn 30
  server s2 127.0.0.1:8081 check weight 100 maxconn 30

listen stats 
  bind :8404
  stats enable
  stats uri /
  stats refresh 10s
  no log
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.0-1.0.0-275.350 2022/06/03 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around November 2023.
Known bugs: https://www.haproxy.com/documentation/hapee/2-5r1/onepage/changelog/#2.5.0
Running on: Linux 4.15.0-176-generic #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -Werror -DMAX_SESS_STKCTR=12 -DSTKTABLE_EXTRA_DATA_TYPES=10
  OPTIONS = USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_CPU_AFFINITY=1 USE_NS=1 USE_SYSTEMD=1 USE_OT=1 USE_MEMORY_PROFILING=1 USE_MODULES=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS +OT -QUIC -PROMEX +MEMORY_PROFILING +MODULES

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with the Prometheus exporter as a service
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with OpenTracing support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
        [  OT] opentracing
```

**Comment by capflam** [comment]
As states in the documentation, the `minlevel` will cap the messages severity. It means a messages with a higher severity will be logged with the `minlevel` one. For instance, in your case, messages with the NOTICE level will be logged with  the INFO level instead.

**Comment by NickMRamirez** [comment]
Thanks @capflam, I'm still not understanding. Maybe I'll understand it if I go through some scenarios:

Severity levels are:

- emerg
- alert
- crit
- err
- warning
- notice
- info
- debug

## Scenario 1: Only the `level`

```
log   127.0.0.1 local0 info
```

In this case, I've set `level` to *info*, and I will get *info* through *emerg* events. Everything except *debug*.

## Scenario 2: level + minlevel

```
log   127.0.0.1 local0 info info
```

The first parameter gives me *info* through *emerg* events. The second parameter converts *notice* through *emerg* to *info*. Like Scenario 1, I get the same events logged, but now some of those events are labelled as *info*.

## questions
I can't tell. What is the difference, functionally between these two scenarios? Converting *notice* through *emerg* to *info* has what effect? It seems like setting events to *info*, when I am already capturing them, serves a purpose I can't identify.

## What I would like it to do

I'd like to capture *info* level events only.

**Comment by capflam** [comment]
The min level is only used to not flood all consoles. Some loggers send by default `alert` and `emerg` messages to all consoles. On some shared environment, it is not possible to change the logger settings and it may be pretty annoying.

Unfortunately, you cannot get messages from a level without those at higher ones, except by configuring your logger.

**Comment by NickMRamirez** [comment]
By consoles, I guess you mean multiple users connecting over serial cables? I don't have experience with that. Does SSH replace this typically, since SSH gives multiple users access to a server? In any case, you've given me enough info to go on, and this ticket can be closed.

Thanks again!

**Comment by capflam** [comment]
SSH sessions are also concerned indeed.

**Comment by CoolCold** [comment]
> As states in the documentation, the `minlevel` will cap the messages severity. It means a messages with a higher severity will be logged with the `minlevel` one. For instance, in your case, messages with the NOTICE level will be logged with the INFO level instead.

This is much cleaner that haproxy 2.8 docs ( https://docs.haproxy.org/2.8/configuration.html#3.1-log ) - at least for non native speaker. My reading was on "capped" , in 
> If it is set, logs emitted with a more severe level than this one will be capped to this level.

to mean: oh, it won't emit at all then!

Correct reading (to my understanding): normalized and transformed to not exceed the CAP value, downgraded to less critical level

reverse translation (Eng -> Ru -> Eng):

> An optional level can be specified to filter outgoing messages. By default, all messages are sent. If a maximum level is specified, only messages with a severity level equal to or greater than that level will be sent. An optional minimum level can be specified. If specified, messages sent with a higher severity level will be limited to that level. This is used to prevent "emerg" messages from being sent to all terminals in some default syslog configurations.


If you wonder where Haproxy 2.8 yet used - Ubuntu 24.04 LTS .

UPDATE: I can probably create the PR for rewording here https://github.com/haproxy/haproxy/blob/master/doc/configuration.txt , @capflam .
