### ISSUE TITLE
src/tools.c: resource leak suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1789]
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1490698:  Resource leaks  (RESOURCE_LEAK)
/src/tools.c: 4935 in check_if_dlopen_usable()
4929      */
4930     void check_if_dlopen_usable()
4931     {
4932            /* dlopen(NULL) returns a handle to the main program or NULL
4933             * on static builds.
4934             */
>>>     CID 1490698:  Resource leaks  (RESOURCE_LEAK)
>>>     Failing to save or free storage allocated by "dlopen(NULL, 1)" leaks it.
4935            dlopen_usable = dlopen(NULL, RTLD_LAZY) ? 1 : 0;
4936     }
4937     
4938     INITCALL0(STG_PREPARE, check_if_dlopen_usable);
4939     
4940     /* Tries to retrieve the address of the first occurrence symbol <name>.
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
Hehe, I was about to say "pfff there's no dlclose" but actually yes there is one! Anyway I'm currently replacing this function as it a little bit too greedy and catches cases where it ought not report an issue. I've found a more reliable method using dladdr() that for now seems to work on all the machines where that was failing. So we can consider that code removed already.

Thanks!

**Comment by chipitsine** [comment]
let's close it.
I'll reopen if will be still an issue tomorrow
