### ISSUE TITLE
keep-alive should be disabled when a frontend is full

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#18]
## Output of `haproxy -vv` and `uname -a`

```
all versions since at least 1.6
```

## What's the configuration?

No particular configuration. HTTP with client-side keep-alive is needed.

## Steps to reproduce the behavior

Establish enough HTTP connections to a frontend to reach its maxconn. Send one request and keep the connection alive.

## Actual behavior

The frontend will not accept extra connections since it's saturated.

## Expected behavior

The responses should be turned to close mode when coming from a saturated frontend to release slots as fast as possible.

## Do you have any idea what may have caused this?

The main problem is that frontends don't reach the FULL state anymore. This was apparently caused by the per-listener maxconn limitations.

## Do you have an idea how to solve the issue?

We need to make sure a frontend can reach the FULL state again when it cannot accept new connections anymore and that this state leaves once a connection is released. Then it will be easy to disable keep-alive when the frontend is full.

**Comment by capflam** [comment]
I remove 1.6, 1.7 and 1.9 labels. 1.9 is EOL and I doubt the fix will be backported to 1.6 and 1.7 that should now receives only critical fixes.

**Comment by wtarreau** [comment]
I looked again at this one. There could be one solution consisting in directly checking the listener's and frontend's `nbconn` vs `maxconn`. However there remains two caveats:
- without configuring a margin, only one connection will see its close enforced, so this will not release that much accept() bandwidth and may force the proxy to oscillate between full and not full, eating CPU around listener_accept() Maybe allowing at least N-2N threads to connect would be better, but shoulds this be made tunable ?
- nothing will be done for existing idle connections and we're back to the recent discussions about releasing connections on stopping and how to configure all that for what use case

I don't remember having seen anyone complain about this and I suspect that those running with fairly low frontend maxconn counts already use short `timeout keep-alive` settings anyway. Thus I'm in favor of closing as wontfix. Yes it's a design limitation but definitely not one whose workarounds will significantly improve the situation, and maybe even make it worse sometimes (e.g. SSL reconnection cost).
