### ISSUE TITLE
Authentication - users in file

### ISSUE THREAD

**Issue by imclint21** [haproxy/haproxy#180]
Hi,

Is it possible to have users in a single file like /etc/haproxy/htpasswd ?

Best regards

**Comment by capflam** [comment]
HAproxy can load several configuration files. You may have on file with the definition of your [userlists](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#3.4), for instance `/etc/haproxy/htpasswd`, and another one with your proxy configuration. You can then use the samples [http_auth](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#7.3.6-http_auth) or [http_auth_group](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#7.3.6-http_auth_group) to check users authentication.

BTW, it is not a feature request but just a question about the configuration of HAProxy. The issue tracker on Github is not the right  place to ask such questions. It is not a support forum. You'll find more  help on [discourse](https://discourse.haproxy.org/) or on the [mailing list](http://www.haproxy.org/#tact).

**Comment by imclint21** [comment]
OK merci, je posterais sur le forum, enfaite je ne trouvais pas de solution pour ça que j'ai créer une issue ^^

Cordialement
