### ISSUE TITLE
Add official package repository

### ISSUE THREAD

**Issue by darius-m** [haproxy/haproxy#1800]
### Your Feature Request

Please add an official package repository (or bring back the one that was available until December 2021 on https://www.haproxy.com/download/haproxy/, that some users have found despite not being well documented, as also mentioned by someone in [this forum post](https://discourse.haproxy.org/t/repository-gone/7397)). Official package repositories usually provide a higher level of trust for users when a distribution's package repositories do not provide the latest versions of an application (e.g., a newer version is required when using some features that were added later).

Additionally, please publish a list of present and old GPG keys used to sign the packages (I could find the fingerprint of the key that was used for the repository mentioned above since it was saved by the package manager, but I could not find a list of known / trusted fingerprints to verify it after the repository was removed).

On a personal note, it feels like the work that was done to create the scripts that handle package creation has been wasted by removing the repository.

### What are you trying to do?

Install a newer version of HAProxy than the one that is provided in the distribution's package repository. An official repository could provide a means to install the package without locally recompiling the code (which is more error prone when managing multiple servers) or relying on lesser known (an with a lower level of trust) package repositories.

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by wlallemand** [comment]
I have no idea where this repository was found but HAProxy Technologies (haproxy.com) never officially provided packages for the community version. I don't recall this link being mentioned anywhere public so this look like a mistake to me :-(

If you need packages for the community version, you can take a look at this page https://github.com/haproxy/wiki/wiki/Packages which list the packages available for the community version.
