### ISSUE TITLE
Failed to get the sockets from the old process!

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1803]
### Detailed Description of the Problem

When reloading HAProxy 2.6.2 I'm seeing the following message in the log:

```
Jul 25 09:46:23 *snip* haproxy[1652444]: [WARNING]  (1652444) : Failed to get the number of sockets to be transferred !
Jul 25 09:46:23 *snip* haproxy[1652444]: [ALERT]    (1652444) : Failed to get the sockets from the old process!
```

### Expected Behavior

Not seeing the error message.

### Steps to Reproduce the Behavior

1. `systemctl reload haproxy`
2. Look in the logs.

### What is your configuration?

```haproxy
global
	log stdout format short daemon
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
	set-dumpable
	expose-experimental-directives

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/haproxy/ssl

	tune.ssl.default-dh-param 2048

	# TLS 1.2-
	ssl-default-bind-ciphers      ECDHE+CHACHA20:ECDHE+AES128:ECDHE+AES256:!MD5
	# TLS 1.3+
	ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
	# Require TLS 1.2 or higher
	ssl-default-bind-options      ssl-min-ver TLSv1.2 prefer-client-ciphers

	maxconn 10000

defaults
	timeout connect 5s
	timeout client  50s
	timeout server  130s
	timeout http-request 5s
	timeout check 1s

	unique-id-format %{+X}o\ %[hostname,field(1,.),upper]-%Ts%rt
```

systemd config:
```
# /lib/systemd/system/haproxy.service
[Unit]
Description=HAProxy Load Balancer
Documentation=man:haproxy(1)
Documentation=file:/usr/share/doc/haproxy/configuration.txt.gz
After=network-online.target rsyslog.service
Wants=network-online.target

[Service]
EnvironmentFile=-/etc/default/haproxy
EnvironmentFile=-/etc/sysconfig/haproxy
BindReadOnlyPaths=/dev/log:/var/lib/haproxy/dev/log
Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid" "EXTRAOPTS=-S /run/haproxy-master.sock"
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS
ExecReload=/usr/sbin/haproxy -Ws -f $CONFIG -c -q $EXTRAOPTS
ExecReload=/bin/kill -USR2 $MAINPID
KillMode=mixed
Restart=always
SuccessExitStatus=143
Type=notify

# The following lines leverage SystemD's sandboxing options to provide
# defense in depth protection at the expense of restricting some flexibility
# in your setup (e.g. placement of your configuration files) or possibly
# reduced performance. See systemd.service(5) and systemd.exec(5) for further
# information.

# NoNewPrivileges=true
# ProtectHome=true
# If you want to use 'ProtectSystem=strict' you should whitelist the PIDFILE,
# any state files and any other files written using 'ReadWritePaths' or
# 'RuntimeDirectory'.
# ProtectSystem=true
# ProtectKernelTunables=true
# ProtectKernelModules=true
# ProtectControlGroups=true
# If your SystemD version supports them, you can add: @reboot, @swap, @sync
# SystemCallFilter=~@cpu-emulation @keyring @module @obsolete @raw-io

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/haproxy.service.d/haproxy-journald.conf
#
# Ansible managed
#

[Service]
LogRateLimitIntervalSec=0
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.2-1~bpo11+1 2022/07/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.2.html
Running on: Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=12).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wlallemand** [comment]
I couldn't reproduce this issue. Do you reproduce this problem for each reload?

Since 2.6, the seamless reload use the mworker socketpairs to get the old sockets, so "expose-fd listeners" is not needed anymore. Could check with ps that you are seeing something like `./haproxy -sf 5677 -x sockpair@3`?

**Comment by TimWolla** [comment]
> Do you reproduce this problem for each reload?

No, only for some:

```
Jul 25 13:11:07 *snip* systemd[1]: Reloading HAProxy Load Balancer.
Jul 25 13:11:07 *snip* haproxy[1652444]: [NOTICE]   (1652444) : Reloading HAProxy
Jul 25 13:11:07 *snip* haproxy[1839818]: [WARNING]  (1839818) : Proxy http stopped (cumulated conns: FE: 2352, BE: 6).
Jul 25 13:11:07 *snip* haproxy[1839818]: Proxy http stopped (cumulated conns: FE: 2352, BE: 6).
Jul 25 13:11:07 *snip* haproxy[1839818]: [WARNING]  (1839818) : Proxy https stopped (cumulated conns: FE: 25408, BE: 0).
Jul 25 13:11:07 *snip* haproxy[1839818]: Proxy https stopped (cumulated conns: FE: 25408, BE: 0).
Jul 25 13:11:07 *snip* haproxy[1652444]: [NOTICE]   (1652444) : New worker (2573118) forked
Jul 25 13:11:07 *snip* haproxy[1652444]: [NOTICE]   (1652444) : Loading success.
Jul 25 13:11:07 *snip* systemd[1]: Reloaded HAProxy Load Balancer.

[…]

Jul 25 13:11:51 *snip* haproxy[1652444]: [NOTICE]   (1652444) : Reloading HAProxy
Jul 25 13:11:51 *snip* haproxy[1652444]: [NOTICE]   (1652444) : haproxy version is 2.6.2-1~bpo11+1
Jul 25 13:11:51 *snip* haproxy[1652444]: [NOTICE]   (1652444) : path to executable is /usr/sbin/haproxy
Jul 25 13:11:51 *snip* haproxy[1652444]: [WARNING]  (1652444) : Failed to get the number of sockets to be transferred !
Jul 25 13:11:51 *snip* haproxy[1652444]: [ALERT]    (1652444) : Failed to get the sockets from the old process!
Jul 25 13:11:51 *snip* haproxy[2573118]: [WARNING]  (2573118) : Proxy http stopped (cumulated conns: FE: 4, BE: 0).
Jul 25 13:11:51 *snip* haproxy[2573118]: Proxy http stopped (cumulated conns: FE: 4, BE: 0).
Jul 25 13:11:51 *snip* haproxy[2573118]: [WARNING]  (2573118) : Proxy https stopped (cumulated conns: FE: 88, BE: 0).
Jul 25 13:11:51 *snip* haproxy[2573118]: Proxy https stopped (cumulated conns: FE: 88, BE: 0).
Jul 25 13:11:51 *snip* haproxy[1652444]: [NOTICE]   (1652444) : New worker (2574220) forked
Jul 25 13:11:51 *snip* haproxy[1652444]: [NOTICE]   (1652444) : Loading success.
Jul 25 13:11:51 *snip* systemd[1]: Reloaded HAProxy Load Balancer.
```

```
$ ps aux |grep haproxy
root     1652444  0.0  0.0  93184  9452 ?        Ss   Jul13   0:07 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
haproxy  1839818  1.6  0.2 2182484 175584 ?      Sl   09:46   3:30 /usr/sbin/haproxy -sf 1825224 1211767 3695250 1667241 -x sockpair@4 -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
haproxy  2573118  0.7  0.0 2181168 21964 ?       Sl   13:11   0:00 /usr/sbin/haproxy -sf 1839818 -x sockpair@6 -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
haproxy  2574220  1.4  0.0 2181248 20648 ?       Sl   13:11   0:01 /usr/sbin/haproxy -sf 2573118 1839818 -x sockpair@6 -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
root     2575657  0.0  0.0   6180   548 pts/0    S+   13:13   0:00 grep haproxy
```

**Comment by wlallemand** [comment]
I caught an old problem in the sockpair protocol, it looks like the wrong error code was returned when the connexion failed, I fixed it in commit f67e8fb. At least it should return the right error if the "connect" is not achieved correctly.

So what's possible is that the new process couldn't connect to the previous one, the error you are seeing are emitted when trying to do a send() or a recvmsg() with the sockpair.

**Comment by TimWolla** [comment]
> So what's possible is that the new process couldn't connect to the previous one, the error you are seeing are emitted when trying to do a send() or a recvmsg() with the sockpair.

Is there any way to get additional information here? Should I wait for the commit to be released?

**Comment by hont512** [comment]
I have same issue with latest master (#https://github.com/haproxy/haproxy/commit/f67e8fb92c795808f60b2406ae395ebc0ca180c5 included) 

I've checked a little in /src/cli.c -> _getsocks() 
After line "tot_fd_nb += !!(fdtab[cur_fd].state & FD_EXPORTED);" - usually tot_fd_nb == 7 (on almost load-free server with nbthread=4), but sometimes it become zero and same reload-error appear

**Comment by hont512** [comment]
Also
- Removing "expose fd-listeners" changes nothing

- I have reloads almost each minute + reloads take a lot of time (large LUA, thousands backends and certs) 

It looks like, the less interval between reloads, the more chances to get fail (I have error in 3-7 minutes at average, but can make it faster manually)
As just a guess - maybe the reason is related to reloads that happen before all old process die

* Happens only on production server, while it's OK on dev. Still didn't find the reason. Production has a lot of IPs. but it shouldn't  be related.

**Comment by wlallemand** [comment]
I got what the problem is, when having remaining processes, an old process could be chosen to get the sockets, but the there is no socket anymore in this one, that's why you are seeing "tot_fd_nb == 0".

I'm working on a fix.

**Comment by geofffranks** [comment]
@wlallemand @capflam  hey! I'm running into a problem on haproxy that looks very similar to this. Do you happen to know if it affects v2.5.4 of haproxy as well?

**Comment by capflam** [comment]
At first glance, no. But @wlallemand is the best placed to answer. However, you are running a quite old version. You should try to upgrade first. The 2.5.9 was released few days ago.

**Comment by wlallemand** [comment]
@geofffranks HAProxy 2.5 is not able to use the internal socketpairs to retrieve the bind of the listeners, so that's not the same issue. Please update to the latest HAProxy 2.5 version and open another ticket if your problem persist.

**Comment by geofffranks** [comment]
Thanks @wlallemand @capflam! I'm able to get a reproduction now against both 2.5.4 + 2.6.6. Will open another ticket.

**Comment by pmanno** [comment]
Hi. I'm seeing this in 2.4.22
`Apr 05 01:02:44 sslb00 haproxy[14438]: [NOTICE]   (14438) : haproxy version is 2.4.22-1~bpo11+1
Apr 05 01:02:44 sslb00 haproxy[14438]: [NOTICE]   (14438) : path to executable is /usr/sbin/haproxy
Apr 05 01:02:44 sslb00 haproxy[14438]: [ALERT]    (14438) : Failed to get the sockets from the old process!
Apr 05 01:02:44 sslb00 haproxy[48789]: [WARNING]  (48789) : Proxy stats stopped (cumulated conns: FE: 74, BE: 0).
Apr 05 01:02:44 sslb00 haproxy[48789]: [WARNING]  (48789) : Proxy default stopped (cumulated conns: FE: 0, BE: 0).
Apr 05 01:02:44 sslb00 haproxy[48789]: Proxy stats stopped (cumulated conns: FE: 74, BE: 0).`

**Comment by frobware** [comment]
I've seen similar errors in 2.2.24 and can reproduce the issue when the machine haproxy is running on is very significantly loaded and when there are very frequent reloads (e.g., every 5 seconds). 

My patch retried the getsocks call on failure which mitigated the issue, albeit unsatisfactorily. I was unable to reproduce using 2.6. I didn't pursue this any further than the following patch[1] as the respective associated customer case was closed. 

[1] https://gist.github.com/frobware/5b9ef50bbabb61e215ce2001635c8916

**Comment by clauderobi** [comment]
I am seeing the same this with  haproxy version is 2.8.3-86e043a via pfsense.

NOTICE] (41784) : config : config: Empty global server state file '/tmp/haproxy_server_state'.
[NOTICE] (41784) : haproxy version is 2.8.3-86e043a
[NOTICE] (41784) : path to executable is /usr/local/sbin/haproxy
[WARNING] (41784) : Failed to connect to the old process socket '/tmp/haproxy.socket'
[ALERT] (41784) : Failed to get the sockets from the old process! 

After numerous attempt AND after taking the time to write this post, something cleared up because starting worked.

**Comment by wlallemand** [comment]
Please open another issue, this ticket is about an issue on the socketpair@ internal stats socket, the error message you're having is not related at all, and can have multiple causes, like the configuration or the way you are starting haproxy. (also messages on closed ticket are often ignored because it's not in the list of tickets)
