### ISSUE TITLE
Real Host header for httpchk/http-check send directive

### ISSUE THREAD

**Issue by yagza** [haproxy/haproxy#1819]
### Your Feature Request

Adding real or defined by variable Host header for httpchk/http-check send directive

### What are you trying to do?

According to the https://stackoverflow.com/questions/52616960/send-real-host-header-for-httpchk-in-haproxy : 
```you can not change it in per-server way. The header will be same for all servers in the backend pool. I asked that in HAproxy community and they confirmed it is impossible now.```  - but I found no feature request or bug about it.

I found no way to realize the following configuration (especially the "hdr Host $REAL_HOST" part):

```
backend SOME_BACKEND
...
    option httpchk
    http-check connect port 80
    http-check send meth GET /some_uri ver HTTP/1.1 hdr Host $REAL_HOST
    http-check expect status 200
...
    server NODE_1 $EXAMPLE1:443 check
    server NODE_2 $EXAMPLE2:443 check
```

I found no way to define hdr Host $REAL_HOST depending on server NODE_* (per server) for http checking needs.
I want to define hdr Host using lua or basing on server host, but it looks like it is impossible to set variable in this directive.

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.2-1ppa1~focal 2022/07/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.2.html
Running on: Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-ZVPsuh/haproxy-2.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by git001** [comment]
Your request is to add something similar like [check-sni](https://docs.haproxy.org/2.6/configuration.html#5.2-check-sni), right.
How about to create a patch for that feature request?  
When you're about to produce a patch, please have a look at the CONTRIBUTING file which explains how to properly format a commit message. Thanks!

**Comment by yagza** [comment]
Nope, SNI involves SSL, which is excluded in my http check (not ssl port). The problem is between haproxy and service - there is a istio sidecar container which routes traffic by Host header...

**Comment by Tristan971** [comment]
While check-sni isn't quite that, it is still similar to the `sni <sni>` option of `http-check connect`.

That said I ran into a similar limitation with regards to the http-check connect port and thankfully it accepted expressions. According to https://docs.haproxy.org/2.6/configuration.html#4.2-http-check%20send hdr also accepts format strings, so should support constructs like so

```
http-check send meth GET uri /healthz hdr Host "%[server_name]"
```
(or more likely "%s"; I'm not certain if the fetch and the log-format are interchangeable here)

At least it passes the config validation here (though I didn't try and see if it works as expected)

**Comment by yagza** [comment]
> While check-sni isn't quite that, it is still similar to the `sni <sni>` option of `http-check connect`.
> 
> That said I ran into a similar limitation with regards to the http-check connect port and thankfully it accepted expressions. According to https://docs.haproxy.org/2.6/configuration.html#4.2-http-check%20send hdr also accepts format strings, so should support constructs like so
> 
> ```
> http-check send meth GET uri /healthz hdr Host "%[server_name]"
> ```
> 
> (or more likely "%s"; I'm not certain if the fetch and the log-format are interchangeable here)
> 
> At least it passes the config validation here (though I didn't try and see if it works as expected)

Thank you for the reply.
Well I've tried few things before create this request. I captured via tcpdump how headers looks like and every time it was literally variable:

```
GET /some_uri HTTP/1.1
host: ${EXAMPLE1}
content-length: 0
connection: close
```
 and

```
GET /some_uri HTTP/1.1
host: $EXAMPLE1
content-length: 0
connection: close
```


But I never tried your way. I'll check it.

**Comment by yagza** [comment]
"%s" indeed!! (with the "%[server_name]" I've got an error: 'http-check send' : failed to parse sample expression <server_name]> : unknown fetch method 'server_name'.)

for server 1:
```
GET /some_uri HTTP/1.1
host: NODE_1
content-length: 0
connection: close
```

for server 2:
```
GET /some_uri HTTP/1.1
host: NODE_2
content-length: 0
connection: close
```

Using "%s" for the hdr Host allows me to use backend "server name" for each server, but I see no way to define them as an environment variables (or some variables) in this case:
```
character '$' is not permitted in server name"
```

But this is definitely different case.
Thanks for the help!

**Comment by capflam** [comment]
I guess we can close this feature request. FYI, `server_name` sample fetch does not exist but `srv_name` does and is equivalent to  `%s`.  Note also environment variables are replaced during the configuration parsing. Thus, it will not work in your case.
