### ISSUE TITLE
Exchange MAPI connectivity failing with new patches and IIS Extended Protection enabled

### ISSUE THREAD

**Issue by mamama1** [haproxy/haproxy#1828]
### Detailed Description of the Problem

After installing the latest updates for MS Exchange 2016 and(!) enabling "Extended Protection" (see https://techcommunity.microsoft.com/t5/exchange-team-blog/released-august-2022-exchange-server-security-updates/ba-p/3593862 and https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/), connections from my Outlook clients using MAPI stopped working. This has been observed with Outlook 2010, 2013 and 2016 on latest patch levels.

Things like h1-case-adjust for all the headers were in place all the time because of us still supporting Outlook 2010 anyway and "no option http-use-htx" on the frontend and all corresponding backends has been tried as well.

Rolling back the Extended Protection on the Exchange servers resolved the issue.

During logon attempts, security event log entries with NTLM error code 0xC000035B are ovserved which seem to be channel binding errors. This disappears, if we publish the exchange server directly to the internet, without haproxy in between or if Extended Protection is disabled on the Exchange servers.

This is the debug output of haproxy -d

> 00000000:fe_ex2013.accept(0006)=000d from [1.2.3.4:62508] ALPN=<none>
> 00000000:fe_ex2013.clireq[000d:ffffffff]: POST /mapi/emsmdb/?MailboxId=1c29e5c5-60c2-412c-84ef-785923afbe21@mydomain.net HTTP/1.1
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: cache-control: no-cache
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: pragma: no-cache
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: content-type: application/mapi-http
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: accept: application/mapi-http
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: user-agent: Microsoft Office/15.0 (Windows NT 10.0; Microsoft Outlook 15.0.5423; Pro)
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: client-request-id: {DBA2AB27-AC63-4C85-BE60-0BD69D72CF6E}
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: x-clientapplication: Outlook/15.0.5475.1000
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: x-clientinfo: {1DCDD398-9989-4EE8-83BE-FEAC75E4F14E}:21
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: x-user-identity: first.last@mydomain.net
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: x-requestid: {9429E800-6CAF-4F16-AF1C-E07A4EBE7B32}:2
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: x-requesttype: Connect
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: content-length: 0
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: host: mail.mydomain.net
> 00000000:fe_ex2013.clihdr[000d:ffffffff]: authorization: Negotiate some short encoded string
> 00000000:be_ex2013_mapi.srvrep[000d:0010]: HTTP/1.1 401 Unauthorized
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: server: Microsoft-IIS/10.0
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: request-id: bc278b96-0416-45b3-9c7e-c251b765d612
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: www-authenticate: Negotiate some long encoded string
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: x-owa-version: 15.1.2507.12
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: www-authenticate: NTLM
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: x-powered-by: ASP.NET
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: x-feserver: exchsrvrname
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: date: Tue, 16 Aug 2022 15:38:24 GMT
> 00000000:be_ex2013_mapi.srvhdr[000d:0010]: content-length: 0
> 00000000:be_ex2013_mapi.srvcls[000d:0010]
> 00000000:be_ex2013_mapi.clicls[000d:0010]
> 00000000:be_ex2013_mapi.closed[000d:0010]
> 00000001:fe_ex2013.accept(0006)=000d from [1.2.3.4:62508] ALPN=<none>
> 00000001:fe_ex2013.clireq[000d:ffffffff]: POST /mapi/emsmdb/?MailboxId=1c29e5c5-60c2-412c-84ef-785923afbe21@mydomain.net HTTP/1.1
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: cache-control: no-cache
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: pragma: no-cache
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: content-type: application/mapi-http
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: accept: application/mapi-http
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: user-agent: Microsoft Office/15.0 (Windows NT 10.0; Microsoft Outlook 15.0.5423; Pro)
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: client-request-id: {DBA2AB27-AC63-4C85-BE60-0BD69D72CF6E}
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: x-clientapplication: Outlook/15.0.5475.1000
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: x-clientinfo: {1DCDD398-9989-4EE8-83BE-FEAC75E4F14E}:21
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: x-user-identity: first.last@mydomain.net
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: x-requestid: {9429E800-6CAF-4F16-AF1C-E07A4EBE7B32}:2
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: x-requesttype: Connect
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: content-length: 300
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: host: mail.mydomain.net
> 00000001:fe_ex2013.clihdr[000d:ffffffff]: authorization: Negotiate some even longer encoded string
> 00000001:be_ex2013_mapi.srvrep[000d:0010]: HTTP/1.1 401 Unauthorized
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: server: Microsoft-IIS/10.0
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: request-id: 58cc617f-bd90-47e3-ac2c-7b6409eb93e5
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: x-owa-version: 15.1.2507.12
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: www-authenticate: Negotiate
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: www-authenticate: NTLM
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: x-powered-by: ASP.NET
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: x-feserver: exchsrvrname
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: date: Tue, 16 Aug 2022 15:38:24 GMT
> 00000001:be_ex2013_mapi.srvhdr[000d:0010]: content-length: 0
> 00000001:be_ex2013_mapi.srvcls[000d:0010]
> 00000001:be_ex2013_mapi.clicls[000d:0010]
> 00000001:be_ex2013_mapi.closed[000d:0010]

in the regular haproxy.log I see 401 errors when the outlook client is trying to login:
Aug 16 17:16:29 myhostname haproxy[79874]: 1.2.3.4:62441 [16/Aug/2022:17:16:29.760] fe_ex2013~ be_ex2013_ews/exchange1 0/0/2/5/7 401 547 - - ---- 7/7/0/0/0 0/0 "POST /EWS/Exchange.asmx HTTP/1.1"

This is what the MS Remote Connectivity analyzer throws at me:

> ###### REQUEST [2022-08-16T15:19:37.8849270Z] [ResolvedIPs: 2.3.4.5] ######
> 
> POST /mapi/nspi/?mailboxId=7446d92d-0f37-4550-8f7b-0010ebd0e13e@mydomain.net HTTP/1.1
> Content-Type: application/octet-stream
> User-Agent: MapiHttpClient
> X-RequestId: 5660e832-fe68-4b47-96ab-39631f28eb31:1
> X-ClientInfo: b0d196d3-72dd-4a62-80b6-4a74278b914b:1
> client-request-id: ea007628-35ae-4c1b-b4f0-35ed46c0ac7d
> X-ClientApplication: MapiHttpClient/15.20.5504.0
> X-RequestType: Bind
> Authorization: Negotiate [truncated]
> Host: mail.mydomain.net
> Content-Length: 45
> 
> --- REQUEST BODY [+0.281] ---
> ..[BODY SIZE: 45]
> 
> --- REQUEST SENT [+0.281] ---
> 
> ###### RESPONSE [+0.985] ######
> 
> HTTP/1.1 401 Unauthorized
> request-id: 872dadd1-1ccf-4b3b-a261-c285fd88b2bf
> x-owa-version: 15.1.2507.12
> x-failurecontext: FrontEnd;401;VW5hdXRob3JpemVk;;;;
> Server: Microsoft-IIS/10.0
> WWW-Authenticate: Negotiate,NTLM
> X-Powered-By: ASP.NET
> X-FEServer: exchsrvname
> Date: Tue, 16 Aug 2022 15:19:38 GMT
> Content-Length: 0
> x-frame-options: SAMEORIGIN
> X-Content-Type-Options: nosniff
> 
> --- RESPONSE BODY [+0.985] ---
> 
> --- RESPONSE DONE [+0.985] ---
> 
> ###### EXCEPTION THROWN [+0.985] ######
> 
> 
> HTTP Response Headers:
> request-id: 872dadd1-1ccf-4b3b-a261-c285fd88b2bf
> x-owa-version: 15.1.2507.12
> x-failurecontext: FrontEnd;401;VW5hdXRob3JpemVk;;;;
> Server: Microsoft-IIS/10.0
> WWW-Authenticate: Negotiate,NTLM
> X-Powered-By: ASP.NET
> X-FEServer: exchsrvname
> Date: Tue, 16 Aug 2022 15:19:38 GMT
> Content-Length: 0
> x-frame-options: SAMEORIGIN
> X-Content-Type-Options: nosniff
> 
> HTTP Status Code: 401 Unauthorized

### Expected Behavior

Authentication should still be working ;)

### Steps to Reproduce the Behavior

Have an Exchange 2016 Server on current patch level with Extended Protection enabled and my haproxy configuration in front of that and try to connect from the outside via MAPI with Outlook 2010, 2013 or 2016

### Do you have any idea what may have caused this?

I guess haproxy somehow is messing with the packets which Extended Protection isn't liking.

### What is your configuration?

```haproxy
#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------

global
    log         /dev/log local0
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/run/haproxy.stat


    ######## Outlook 2010 fix ######################################################
    h1-case-adjust accept Accept
    h1-case-adjust authorization Authorization
    h1-case-adjust authrequired AuthRequired
    h1-case-adjust cache-control Cache-Control
    h1-case-adjust client-request-id Client-Request-Id
    h1-case-adjust connection Connection
    h1-case-adjust content-length Content-Length
    h1-case-adjust content-type Content-Type
    h1-case-adjust cookie Cookie
    h1-case-adjust date Date
    h1-case-adjust host Host
    h1-case-adjust persistent-auth Persistent-Auth
    h1-case-adjust pragma Pragma
    h1-case-adjust request-header Request-Header
    h1-case-adjust response-header Response-Header
    h1-case-adjust server Server
    h1-case-adjust set-cookie Set-Cookie
    h1-case-adjust status-code Status-Code
    h1-case-adjust transfer-encoding Transfer-Encoding
    h1-case-adjust user-agent User-Agent
    h1-case-adjust www-authenticate WWW-Authenticate
    h1-case-adjust x-anchormailbox X-AnchorMailbox
    h1-case-adjust x-clientapplication X-ClientApplication
    h1-case-adjust x-clientInfo X-ClientInfo
    h1-case-adjust x-content-type-options X-Content-Type-Options
    h1-case-adjust x-deviceinfo X-DeviceInfo
    h1-case-adjust x-elapsedtime X-ElapsedTime
    h1-case-adjust x-expirationinfo X-ExpirationInfo
    h1-case-adjust x-feserver X-FEServer
    h1-case-adjust x-mapihttpcapability X-MapiHttpCapability
    h1-case-adjust x-pendingperiod X-PendingPeriod
    h1-case-adjust x-powered-by X-Powered-By
    h1-case-adjust x-requestid X-RequestId
    h1-case-adjust x-requesttype X-RequestType
    h1-case-adjust x-responsecode X-ResponseCode
    h1-case-adjust x-serverapplication X-ServerApplication
    h1-case-adjust x-starttime X-StartTime
    h1-case-adjust x-user-identity X-User-Identity
    ################################################################################


#--------------------------
# SSL tuning / hardening
#--------------------------
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

    ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

    ssl-dh-param-file /etc/haproxy/dhparam

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------

# Regarding timeout client and timeout server:
# https://discourse.haproxy.org/t/high-number-of-connection-resets-during-transfers-exchange-2013/1158/4

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option                  forwardfor       except 127.0.0.0/8
    option                  redispatch
#   option                  contstats
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          15m # this value should be rather high with Exchange
    timeout server          15m # this value should be rather high with Exchange
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 100000
option h1-case-adjust-bogus-client

#-------------------------------------------------------
# Stats section
#-------------------------------------------------------

listen stats
        bind 192.168.77.10:444 # VIP
        stats enable
        stats refresh 300s
        stats show-node
        stats auth admin:hidden
        stats hide-version
        stats uri  /stats


#---------------------------------------------------------------------
# Main front-end which proxies to the back-ends
#---------------------------------------------------------------------

frontend fe_ex2013
  # Domain ACLs
  acl acl_mail.mydomain.net hdr(host) -i mail.mydomain.net
  acl acl_www.mydomain2.at hdr(host) -i www.mydomain2.at
  acl acl_mydomain4.at hdr(host) -i mydomain4.at
  acl acl_old.mydomain3.at hdr(host) -i old.mydomain3.at

  http-response set-header X-Frame-Options SAMEORIGIN
  http-response set-header X-Content-Type-Options nosniff

  mode http
  bind *:80
  bind *:443 ssl crt /etc/letsencrypt/live/mail.mydomain.net/fullchain.pem

  # force HTTP or HTTPS
  redirect scheme https code 301 if !{ ssl_fc } acl_mail.mydomain.net   # redirect 80 -> 443 (for owa)
  redirect scheme http code 301 if { ssl_fc } !acl_mail.mydomain.net    # redirect 443 -> 80 for non-ssl sites



  ########################
  ##      Exchange      ##
  ########################

  # OWA domain redirects
  acl acl_owa-redirects hdr(host) -i mail.mydomain5.at mail.mydomain6.at mail.mydomain7.at mail.mydomain8.at mail.mydomain3.at mail.mydomain9.at mail.mydomain2.at mail.mydomain10.at
  http-request redirect location https://mail.mydomain.net/owa if acl_owa-redirects

  # redirect to /owa subfolder if / is requested
  acl p_root path -i /
  http-request set-path /owa if p_root acl_mail.mydomain.net

  # exchange virtual directories
  acl autodiscover url_beg /Autodiscover
  acl autodiscover url_beg /autodiscover
  acl mapi url_beg /mapi
  acl rpc url_beg /rpc
  acl owa url_beg /owa
  acl owa url_beg /OWA
  acl eas url_beg /Microsoft-Server-ActiveSync
  acl ews url_beg /EWS
  acl ews url_beg /ews
  acl oab url_beg /OAB
  acl oab url_beg /oab

  # exchange backends
  use_backend be_ex2013_autodiscover if autodiscover acl_mail.mydomain.net
  use_backend be_ex2013_mapi if mapi acl_mail.mydomain.net
  use_backend be_ex2013_rpc if rpc acl_mail.mydomain.net
  use_backend be_ex2013_owa if owa acl_mail.mydomain.net
  use_backend be_ex2013_eas if eas acl_mail.mydomain.net
  use_backend be_ex2013_ews if ews acl_mail.mydomain.net
  use_backend be_ex2013_oab if oab acl_mail.mydomain.net

#------------------------------
# Back-end section
#------------------------------

backend be_ex2013_autodiscover
  mode http
  balance roundrobin
  option httpchk GET /autodiscover/healthcheck.htm
  option log-health-checks
  http-check expect status 200
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none

backend be_ex2013_mapi
  mode http
  balance roundrobin
  option httpchk GET /mapi/healthcheck.htm
  option log-health-checks
  http-check expect status 200
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none

backend be_ex2013_rpc
  mode http
  balance roundrobin
  option httpchk GET /rpc/healthcheck.htm
  option log-health-checks
  http-check expect status 200
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none

backend be_ex2013_owa
  mode http
  balance roundrobin
  option httpchk GET /owa/healthcheck.htm
  option log-health-checks
  http-check expect status 200
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none

backend be_ex2013_eas
  mode http
  balance roundrobin
  option httpchk GET /microsoft-server-activesync/healthcheck.htm
  option log-health-checks
  http-check expect status 200
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none

backend be_ex2013_ews
  mode http
  balance roundrobin
  option httpchk GET /ews/healthcheck.htm
  option log-health-checks
  http-check expect status 200
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none

backend be_ex2013_oab
  mode http
  balance roundrobin
  option httpchk GET /oab/healthcheck.htm
  option log-health-checks
  http-check expect status 200
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none

backend be_ex2013
  mode http
  balance roundrobin
  server exchange1 192.168.0.6:443 check ssl inter 15s verify none
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.18-1~bpo11+1 2022/07/27 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.18.html
Running on: Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by git001** [comment]
When you try to use [http-reuse never](https://docs.haproxy.org/2.6/configuration.html#4.2-http-reuse) and see if it fixes the issue?
HAProxy try to make the connection private https://github.com/haproxy/haproxy/blob/master/src/http_ana.c#L1706 but maybe this "Extended Protection" do something "more".

Btw: do you know the directive [h1-case-adjust-file](https://docs.haproxy.org/2.6/configuration.html#h1-case-adjust-file)?

**Comment by shipitsin-ilia** [comment]
as @git001 already mentioned, NTLM (and Negotiate) are very specific beasts, authentication happens once per keepalive session, and entire keepalive session is supposed to be terminated exactly within single tcp session.

haproxy tries to deal with that by marking connection "private", i.e. it is not reusable by other users.

I do not have Exchange 2016 right now, can you please compare headers of very first http request (haproxy debug is fine for that) for two cases

1) extended protection enabled
2) not enabled

headers difference should explain haproxy behaviour and next steps

**Comment by shipitsin-ilia** [comment]
I was wrong. It is not related to headers.

extended protection is based on ssl channel binding.
current Exchange implementation is not compatible with any ssl termination.

quote from docs "SSL Offloading scenarios are not supported"

**Comment by shipitsin-ilia** [comment]
![image](https://user-images.githubusercontent.com/108898059/184957593-66f07bc0-6014-4813-ab91-0c3cb0c0e852.png)

**Comment by mamama1** [comment]
to be perfectly honest, i did not identify my configuration as a ssl offloading scenario. so that's what it essentially is, what i'm doing?

**Comment by shipitsin-ilia** [comment]
as long as you run haproxy in "http" mode with "ssl" on haproxy side, it is offloading scenario

**Comment by mamama1** [comment]
ok thanks, I'm screwed, then xD

**Comment by TimWolla** [comment]
Closing as everything is working as intended: The channel binding detects that an intermediary decrypts the connection.

**Comment by seanzhang422** [comment]
What mamama1 is doing is SSL bridging but not SSL offloading. SSL bridging is supported. [reference](https://microsoft.github.io/CSS-Exchange/Security/Extended-Protection/#ssl-bridging-supported-scenarios)

The missing piece here is that the reverse proxy must use the exact same certificate-key pair as the backend for the Extended Protection to work (explained in the refence link above). As of the latest Exchange 2016 CU, the MAPI over HTTP does not require session affiliation, so you don't need to set up any affiliation in the haproxy setting.
