### ISSUE TITLE
Include config settings.

### ISSUE THREAD

**Issue by fuka307** [haproxy/haproxy#183]
add support for the include config parameter like apahce or nginx.

**Comment by wtarreau** [comment]
No, it was already explained to great lengths multiple times. This would cause far more trouble than it would solve. Instead you can already load multiple files or even a set of directories.

**Comment by sebma** [comment]
@wtarreau Hi, you wrote : 
> Instead you can already load multiple files or even a set of directories.

So if I have multiple `-f`, I need to override `ExecStart=` command line of the SystemD `haproxy.service`, right ?

And what shall I write in those files, each backend parts ?
