### ISSUE TITLE
Client/Server using HTTP/2 and bidirectional gRPC fails with HTTP2: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by systemmonkey42** [haproxy/haproxy#1830]
### Detailed Description of the Problem

Using the backup application "kopia" (https://github.com/kopia/kopia) I wanted to expose the repository server via HAPROXY to restrict external access via ACLs

Even without ACL's or any special configuration, the server side starts reporting
```
http: connection error: PROTOCOL_ERROR
```
Within seconds of the client connection. 

When use directly, or with NGINX as a proxy, there is no problem.

I am unsure how to diagnose the problem to any detailed level.  I use haproxy for various reasons and converting to NGINX is a significant amount of work.

### Expected Behavior

Operation as normal via HTTP2

### Steps to Reproduce the Behavior

Create a frontend supporting http/2 (alpn h2,http/1.1)

Create a backend which directs traffic to kopia server
```
backend reposerver
    server repo1 192.168.1.20:51515 alpn h2 ssl verify none
```

Direct client to connect via haproxy instead of direct.
(ssl certificates are managed via letsencrypt on haproxy.   kopia server is using self signed)

### Do you have any idea what may have caused this?

I can only assume an incompatibility between HAPROXY http/2 handling, and that of GOLANG (tested with 1.17.2 and 1.18.3)

I started to instrument go's net/http modules to trace the exact packet which triggered the error, but my skills with go are not up to the task.

### Do you have an idea how to solve the issue?

Identify the exact packet which GO HTTP/2 server is complaining about, and identify if or how it was generated by haproxy.

### What is your configuration?

```haproxy
# Generic configuration
global
    log 127.0.0.1   local0 debug

    stats socket /run/haproxy.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    #debug
    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/haproxy/certs

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GC    M-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA    -AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE    -RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNUL    L:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
    ssl-default-bind-options no-sslv3
    tune.ssl.default-dh-param 2048

defaults
    log     global
    mode    http
    maxconn 256

    option  httplog
    option  forwardfor
    option  dontlognull
    option  http-no-delay
    #option  http-server-close
    #option  log-health-checks

    # Configure default compression
    compression algo raw-deflate
    compression type application/javascript text/html text/css

    timeout connect 15000ms
    timeout client  1h
    timeout server  1h
    timeout tunnel  1h

frontend http-ssl
        bind *:443 ssl crt-list /etc/haproxy/certs.txt crt-list /etc/letsencrypt/haproxy/certs.txt alpn h2,http/1.1

        # Preferred backend is the "Host" header value in lowercase.
        http-request set-var(req.preferred) hdr(Host),field(1,":/"),lower
        use_backend %[var(req.preferred)] if { var(req.preferred),nbsrv() gt 0 }
        default_backend reject

backend reject
        http-request deny # redirect prefix http://www.google.com/?q= code 302

backend <domain>
    no option abortonclose
    server srv1 <internal_ip>:51515 alpn h2 ssl verify none
```

### Output of `haproxy -vv`

```plain
Tested with 2.2, 2.6.2, and git master

HAProxy version 2.6.2-16a3646 2022/07/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.2.html
Running on: Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
Running on OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.2.1 20220219

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
    [CACHE] cache
    [COMP] compression
    [FCGI] fcgi-app
    [SPOE] spoe
    [TRACE] trace
```

### Last Outputs and Backtraces

```plain
No crash.  Logs show 'SD--' due to server disconnected after it detected the protocol error.
```

### Additional Information

Workload is light.  Environments tested - haproxy in docker contain, haproxy under ubuntu vm, haproxy on ubuntu physical server.

**Comment by systemmonkey42** [comment]
Example run without haproxy
```
# kopia snapshot create /etc
Snapshotting root@<hostname>:/etc ...
 * 0 hashing, 0 hashed (0 B), 2456 cached (8 MB), uploaded 0 B, estimating...
Created snapshot with root kc7760d344aed99586354d868b3a7743b and ID c8766adb8e75b7f19fa2fc7bf677710c in 0s
#
```
Server logs
```
# kopia --log-level=debug server start  --server-password=redacted --config-file=server.config --address=0.0.0.0:51515 --tls-cert-file=fullchain.pem --tls-key-file=privkey.pem

Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.

DEBUG generated random auth cookie signing key: aeb5d46e-ef93-46d6-a4cc-430ffc9c2676
SERVER ADDRESS: https://[::]:51515
Open the address above in a web browser to use the UI.
starting session for user "root@<hostname>" from 192.168.1.20:44990
starting session for user "root@<hostname>" from 192.168.1.20:44990
session ended for user "root@<hostname>" from 192.168.1.20:44990
session ended for user "root@<hostname>" from 192.168.1.20:44990

```

Same again, pointing to haproxy instead of direct
```
# kopia snapshot create /etc
Snapshotting root@<hostname>:/etc ...
ERROR unable to parse snapshot manifest 34f18b6ed3611b038042bae923aa5d47: unable to find manifest entries: rpc error: code = Internal desc = server closed the stream without sending trailers: EOF
ERROR unable to parse snapshot manifest 1126ccbdbb0628f9d98e4d2e80f6867b: unable to find manifest entries: rpc error: code = Internal desc = server closed the stream without sending trailers: EOF
ERROR unable to parse snapshot manifest 9c91f73528e17a9daa7d7969cd696114: unable to find manifest entries: rpc error: code = Internal desc = server closed the stream without sending trailers: EOF
ERROR flush error: EOF: EOF
#
```
The client errors simply indicate the server didnt respond

Server logs
```
# kopia --log-level=debug server start  --server-password=redacted --config-file=server.config --address=0.0.0.0:51515 --tls-cert-file=fullchain.pem --tls-key-file=privkey.pem

Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.

DEBUG generated random auth cookie signing key: aeb5d46e-ef93-46d6-a4cc-430ffc9c2676
SERVER ADDRESS: https://[::]:51515
Open the address above in a web browser to use the UI.
starting session for user "root@<hostname>" from <proxyip>:52498
starting session for user "root@<hostname>" from <proxyip>:52506
2022/08/17 18:46:01 http2: server connection error from <proxyip>:52506: connection error: PROTOCOL_ERROR
session ended for user "root@<hostname>" from <proxyip>:52506
session ended for user "root@<hostname>" from <proxyip>:52498
```

Server drops the connection at the point it detected a protocol error

```
router_1    | 2022-08-17T08:46:02.412035409Z 2022-08-17T08:46:02+00:00 localhost haproxy[19]: <clientip>:60802 [17/Aug/2022:08:46:01.283] http-ssl~ <fqdn>/srv1 0/0/0/125/1129 200 10470 - - SD-- 1/1/1/1/0 0/0 "POST https://<fqdn>/kopia_repository.KopiaRepository/Session HTTP/2.0"
router_1    | 2022-08-17T08:46:02.413230247Z 2022-08-17T08:46:02+00:00 localhost haproxy[19]: <clientip>:60802 [17/Aug/2022:08:46:01.124] http-ssl~ <fqdn>/srv1 0/0/2/156/1289 200 211 - - CD-- 1/1/0/0/0 0/0 "POST https://<fqdn>/kopia_repository.KopiaRepository/Session HTTP/2.0"
```
As far as haproxy is concerned, the kopia server simple disconnected unexpectedly.

**Comment by git001** [comment]
Please can you also run haporxy in debug mode `haproxy -d ...` to see which headers are send from kopia

**Comment by systemmonkey42** [comment]
Headers attached.  These are all the connections the client makes before failing
<details><summary>Debug logs</summary><pre>0000003c:http-ssl.accept(0006)=001b from [<clientip>:47520] ALPN=h2
0000003c:http-ssl.clireq[001b:ffffffff]: POST https://<fqdn>/kopia_repository.KopiaRepository/Session HTTP/2.0
0000003c:http-ssl.clihdr[001b:ffffffff]: host: <fqdn>
0000003c:http-ssl.clihdr[001b:ffffffff]: content-type: application/grpc
0000003c:http-ssl.clihdr[001b:ffffffff]: user-agent: grpc-go/1.47.0
0000003c:http-ssl.clihdr[001b:ffffffff]: te: trailers
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-hostname: redacted
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-username: redacted
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-password: redacted
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-version: 0.11.3
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-build-info: 317cc36892707ab9bdc5f6e4dea567d1e638a070
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-repo: kopia/kopia
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-os: linux
0000003c:http-ssl.clihdr[001b:ffffffff]: kopia-arch: amd64
0000003c:<backend>.srvrep[001b:0016]: HTTP/2.0 200
0000003c:<backend>.srvhdr[001b:0016]: content-type: application/grpc
0000003c:<backend>.srvhdr[001b:0016]: trailer: Grpc-Status
0000003c:<backend>.srvhdr[001b:0016]: trailer: Grpc-Message
0000003c:<backend>.srvhdr[001b:0016]: trailer: Grpc-Status-Details-Bin
0000003d:http-ssl.accept(0006)=001b from [<clientip>:47520] ALPN=h2
0000003d:http-ssl.clireq[001b:ffffffff]: POST https://<fqdn>/kopia_repository.KopiaRepository/Session HTTP/2.0
0000003d:http-ssl.clihdr[001b:ffffffff]: host: <fqdn>
0000003d:http-ssl.clihdr[001b:ffffffff]: content-type: application/grpc
0000003d:http-ssl.clihdr[001b:ffffffff]: user-agent: grpc-go/1.47.0
0000003d:http-ssl.clihdr[001b:ffffffff]: te: trailers
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-arch: amd64
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-hostname: redacted
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-username: redacted
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-password: redacted
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-version: 0.11.3
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-build-info: 317cc36892707ab9bdc5f6e4dea567d1e638a070
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-repo: kopia/kopia
0000003d:http-ssl.clihdr[001b:ffffffff]: kopia-os: linux
0000003d:<backend>.srvrep[001b:0016]: HTTP/2.0 200
0000003d:<backend>.srvhdr[001b:0016]: content-type: application/grpc
0000003d:<backend>.srvhdr[001b:0016]: trailer: Grpc-Status
0000003d:<backend>.srvhdr[001b:0016]: trailer: Grpc-Message
0000003d:<backend>.srvhdr[001b:0016]: trailer: Grpc-Status-Details-Bin
0000003c:<backend>.srvcls[001b:0016]
0000003c:<backend>.clicls[001b:0016]
0000003c:<backend>.closed[001b:0016]
0000003d:<backend>.srvcls[001b:0016]
0000003d:<backend>.clicls[001b:0016]
0000003d:<backend>.closed[001b:0016]
</pre></details>

**Comment by git001** [comment]
A wild guess, the `trailer:` fields with uppercase values are not permitted by RFC 7540  
https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2

> However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2

which is implemented as such in HAProxy for HTTP/2
https://git.haproxy.org/?p=haproxy.git;a=blob;f=src/h2.c;hb=b29a1dc2f4a334c1c7fea76c59abb4097422c05c#l881

My suggestion is to fix this in grpc-go https://github.com/grpc/grpc-go/blob/master/internal/transport/handler_server.go#L250 as this clearly violates RFC 7540 or use HTTP/1 for that backend.

**Comment by wtarreau** [comment]
I don't think they're sent as upper case. What you're seeing in the `trailers` header are names of the headers to be considered and are case insensitive. I'm pretty sure they're properly passed lowercase otherwise the nginx would block the response as well.

You should enable traces so that we see what's happening inside the H2 stack:
```
$ (echo "trace h2 sink buf0; trace h2 level developer; trace h2 verbosity complete; trace h2 start now;show events buf0 -w -n" ; cat ) | socat - /run/haproxy.sock > h2-trace.txt
```

This will wait for events in the H2 layer and will show them, both for frontends and backends. If you press enter, the trace will stop being collected but not stop being generate. In order to disable traces, just send `trace 0` to the CLI socket:
```
$ socat - /run/haproxy.sock <<< "trace 0"
```
The trace will contain both sides but will have everything in it (including the GOAWAY that is sent about something apparently offending). Please have a close look at the trace before sharing it, as it may contain header field values that you may want to mask.

**Comment by systemmonkey42** [comment]
This morning, I was able to complete a few backups.  Failures were not 100%, which puts credibility into the idea the headers were not at issue.

The following was a working backup.  The backup volume was tiny. (Which may be why it succeeded part of the time this morning)

Successful backup: [trace1.txt](https://github.com/haproxy/haproxy/files/9366399/trace1.txt)

Failures outnumbers successes though..

Backup which failed: [trace6.txt](https://github.com/haproxy/haproxy/files/9366402/trace6.txt)

For completeness, this is the `haproxy -d` output for a successful backup...
<details>

<summary style="font-size:10px">Debug log</summary>

<pre>
00000003:http-ssl.accept(0006)=0018 from [[clientip]:43434] ALPN=h2
00000003:http-ssl.clireq[0018:ffffffff]: POST https://[fqdn]/kopia_repository.KopiaRepository/Session HTTP/2.0
00000003:http-ssl.clihdr[0018:ffffffff]: host: [fqdn]
00000003:http-ssl.clihdr[0018:ffffffff]: content-type: application/grpc
00000003:http-ssl.clihdr[0018:ffffffff]: user-agent: grpc-go/1.48.0
00000003:http-ssl.clihdr[0018:ffffffff]: te: trailers
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-repo:
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-os: linux
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-arch: amd64
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-hostname: [redacted]
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-username: [redacted]
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-password: [redacted]
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-version: v0-unofficial
00000003:http-ssl.clihdr[0018:ffffffff]: kopia-build-info: unknown
00000003:[kopia_backend].srvrep[0018:0016]: HTTP/2.0 200
00000003:[kopia_backend].srvhdr[0018:0016]: content-type: application/grpc
00000003:[kopia_backend].srvhdr[0018:0016]: trailer: Grpc-Status
00000003:[kopia_backend].srvhdr[0018:0016]: trailer: Grpc-Message
00000003:[kopia_backend].srvhdr[0018:0016]: trailer: Grpc-Status-Details-Bin
00000004:http-ssl.accept(0006)=0018 from [[clientip]:43434] ALPN=h2
00000004:http-ssl.clireq[0018:ffffffff]: POST https://[fqdn]/kopia_repository.KopiaRepository/Session HTTP/2.0
00000004:http-ssl.clihdr[0018:ffffffff]: host: [fqdn]
00000004:http-ssl.clihdr[0018:ffffffff]: content-type: application/grpc
00000004:http-ssl.clihdr[0018:ffffffff]: user-agent: grpc-go/1.48.0
00000004:http-ssl.clihdr[0018:ffffffff]: te: trailers
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-password: [redacted]
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-version: v0-unofficial
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-build-info: unknown
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-repo:
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-os: linux
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-arch: amd64
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-hostname: [redacted]
00000004:http-ssl.clihdr[0018:ffffffff]: kopia-username: [redacted]
00000004:[kopia_backend].srvrep[0018:0016]: HTTP/2.0 200
00000004:[kopia_backend].srvhdr[0018:0016]: content-type: application/grpc
00000004:[kopia_backend].srvhdr[0018:0016]: trailer: Grpc-Status
00000004:[kopia_backend].srvhdr[0018:0016]: trailer: Grpc-Message
00000004:[kopia_backend].srvhdr[0018:0016]: trailer: Grpc-Status-Details-Bin
00000003:[kopia_backend].srvcls[0018:0016]
00000003:[kopia_backend].clicls[0018:0016]
00000003:[kopia_backend].closed[0018:0016]
00000004:[kopia_backend].srvcls[0018:0016]
00000004:[kopia_backend].clicls[0018:0016]
00000004:[kopia_backend].closed[0018:0016]
</pre></details>

Many thanks for your time.

**Comment by systemmonkey42** [comment]
I'm sure it doesn't matter, but this is the equivalent 'NGINX' configuration.

```nginx
server {
    listen       51500 ssl http2;
    server_name  <fqdn>;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_certificate /etc/nginx/ssl/cert.pem;
    client_max_body_size 0;
    proxy_ssl_verify off;
    location /kopia_repository.KopiaRepository {
        grpc_pass grpcs://<serverip>:51515;
    }
    location / {
        proxy_pass https://<serverip>:51515;
    }
}
```

In NGINX I need to specify the use of gRPC for a specific path.  Do I need to specify this for HAProxy? Or does it auto-detect what it needs to do?

Thanks again

**Comment by systemmonkey42** [comment]
I learned enough GO to instrument the http/2 handling code, and built the server with the modified http/2 code.

The result was the error "http2ErrCodeProtocol" was always returned from the marked line below.

```go
func (sc *http2serverConn) processWindowUpdate(f *http2WindowUpdateFrame) error {
    sc.serveG.check()
    switch {
    case f.StreamID != 0: // stream-level flow control
        state, st := sc.state(f.StreamID)
        if state == http2stateIdle {
            // Section 5.1: "Receiving any frame other than HEADERS
            // or PRIORITY on a stream in this state MUST be
            // treated as a connection error (Section 5.4.1) of
            // type PROTOCOL_ERROR."
---->       return sc.countError("stream_idle", http2ConnectionError(http2ErrCodeProtocol))
        }
        if st == nil {
            // "WINDOW_UPDATE can be sent by a peer that has sent a
            // frame bearing the END_STREAM flag. This means that a
            // receiver could receive a WINDOW_UPDATE frame on a "half
            // closed (remote)" or "closed" stream. A receiver MUST
            // NOT treat this as an error, see Section 5.1."
            return nil
        }
        if !st.flow.add(int32(f.Increment)) {
            return sc.countError("bad_flow", http2streamError(f.StreamID, http2ErrCodeFlowControl))
        }
    default: // connection-level flow control
        if !sc.flow.add(int32(f.Increment)) {
            return http2goAwayFlowError{}
        }
    }
    sc.scheduleFrameWrite()
    return nil
}
```

It seems to be complaining it was sent the wrong type of frame while in an "idle" state.  I'll try an find at what point it became "idle" and what triggered it to do so.

Update:

It appears a stream packet is received with a streamID of 0x7fffffff, which is not a valid stream id, resulting in state change.

The same log without haproxy shows the streamid is 3,4 or 5.

**Comment by wtarreau** [comment]
Very useful, thanks a lot! And your trace6 confirms that the PROTOCOL_ERROR was indeed *received* not sent by haproxy:
```
<0>2022-08-17T22:12:25.035001+00:00 [03|h2|2|mux_h2.c:3601] receiving H2 GOAWAY frame : h2c=0x7ff3a1458a90(B,FRP) dsi=0 h2s=0x557c722474a0(0,CLO)
<0>2022-08-17T22:12:25.035002+00:00 [03|h2|5|mux_h2.c:2689] h2c_handle_goaway(): entering : h2c=0x7ff3a1458a90(B,FRP)
<0>2022-08-17T22:12:25.035004+00:00 [03|h2|5|mux_h2.c:2241] h2_wake_some_streams(): entering : h2c=0x7ff3a1458a90(B,FRP) err=PROTOCOL_ERROR/01
<0>2022-08-17T22:12:25.035005+00:00 [03|h2|5|mux_h2.c:2261] h2_wake_some_streams(): leaving : h2c=0x7ff3a1458a90(B,FRP) err=PROTOCOL_ERROR/01
<0>2022-08-17T22:12:25.035006+00:00 [03|h2|5|mux_h2.c:2702] h2c_handle_goaway(): leaving : h2c=0x7ff3a1458a90(B,FRP) err=PROTOCOL_ERROR/01
<0>2022-08-17T22:12:25.035009+00:00 [03|h2|5|mux_h2.c:3638] h2_process_demux(): skipping remaining frame payload : h2c=0x7ff3a1458a90(B,FRP) err=PROTOCOL_ERROR/01 dsi=0 h2s=0x557c722474a0(0,CLO)
<0>2022-08-17T22:12:25.035011+00:00 [03|h2|3|mux_h2.c:3643] switching to FRAME_H : h2c=0x7ff3a1458a90(B,FRP) err=PROTOCOL_ERROR/01 dft=GOAWAY/00 dfl=0
<0>2022-08-17T22:12:25.035013+00:00 [03|h2|5|mux_h2.c:3371] h2_process_demux(): no more Rx data : h2c=0x7ff3a1458a90(B,FRH) err=PROTOCOL_ERROR/01
<0>2022-08-17T22:12:25.035014+00:00 [03|h2|5|mux_h2.c:3687] h2_process_demux(): leaving : h2c=0x7ff3a1458a90(B,FRH) err=PROTOCOL_ERROR/01
```

Now regarding the use of this stream ID, the only way this would be possible would be by having sent **1 billion** requests on this connection, that sounds like a lot! I've rechecked the code to be sure, and we're always restarting from the highest known ID and they're properly incremented using only odd ones. Are you certain that the received stream ID matches this ? If you could find a way to get a capture of the faulty frame, that would immensely help. Another possibility would be something going wrong in the frame encoding, resulting in the byte stream being shifted and the stream being looked up at the wrong place, but I really don't believe in it now that most of the net's traffic is delivered over H2 and that it's been years without any reports that could suggest this.

I'm reading the trace in more details since it contains at least 3 connections, and I'm isolating the connection that experienced the problem (0x7ff3a1458a90).

**Comment by wtarreau** [comment]
So what I can find is one stream sent with ID=1 on that connection, with the following request:
```
<0>2022-08-17T22:12:24.891712+00:00 [03|h2|1|mux_h2.c:5765] sent H2 request   : h2c=0x7ff3a1458a90(B,FRH) h2s=0x7ff3a145a6a0(1,IDL) : [1] H2 REQ: POST https://[fqdn]/kopia_repository.KopiaRepository/Session HTTP/2.0
```
What I'm seeing is that data is being uploaded and downloaded in parallel, and that suddenly we're getting a GOAWAY. It's possible we've done something wrong, but I don't know. I suspect that the code you've inspected above uses stream ID 0x7ffffff to indicate that the stream was already in error or something like this. It would be useful to check the content-length header if any on the server side, so that we can verify that we didn't send too much. Neither side sent the end of stream, so data was still flowing and the window being updated in both directions.

**Comment by systemmonkey42** [comment]
Thanks for your time so far.  GO appears to support the following
```
export GODEBUG=http2debug=2
```
which produced the logs I've attached.  If it isn't enough, I'll try and provide more detail.

At line 2586, you see the "read frame" stream=2147483647  (0x7fffffff).  
```
2022/08/18 17:45:23 http2: server read frame WINDOW_UPDATE stream=2147483647 len=4 incr=806
```

Hopefully the go logs make some sense to you.

[kopia_http_trace.txt](https://github.com/haproxy/haproxy/files/9371579/kopia_http_trace.txt)

If I can figure out how, I'll try and get a raw hex-dump of the frames which are read from the socket. The log only appears to show a summary of the parsed frame.

**Comment by wtarreau** [comment]
Ah that's quite useful, thank you! So it's not a new stream (hence headers frame) but a window update frame that's seen for such a stream. I'm going back to inspect that code and the first trace.

**Comment by wtarreau** [comment]
So while I'm not finding anything equivalent in the trace, the interesting point is that it's not a matter of the stream being shifted, because the length is correct (4) and the increment as well (806, that's what's happening at the connection level as well). Thus it's very possible that we've sent crap, but I'm having a hard time imagining how this can happen given that these frames are used all the time.

**Comment by systemmonkey42** [comment]
That wasn't so hard. I'm almost starting to like go...

The log now contains
````
RAW FRAME HEADER:  00 00 04 08 00 ff ff ff ff
2022/08/18 18:09:53 http2: Framer 0xc0058d20e0: read WINDOW_UPDATE stream=2147483647 len=4 incr=806
2022/08/18 18:09:53 http2: server read frame WINDOW_UPDATE stream=2147483647 len=4 incr=806
````
Showing the frame containing 0xFFFFFFFF as the streamID was read from the wire.

The parsing code looks like
```
    return http2FrameHeader{
        Length:   (uint32(buf[0])<<16 | uint32(buf[1])<<8 | uint32(buf[2])),
        Type:     http2FrameType(buf[3]),
        Flags:    http2Flags(buf[4]),
        StreamID: binary.BigEndian.Uint32(buf[5:]) & (1<<31 - 1),
        valid:    true,
    }, nil
```
Which reads as `streamID` is bytes 5 onwards (starting from zero of course) & 0x7FFFFFFF, which results in what we see.

[kopia_http_trace2.txt](https://github.com/haproxy/haproxy/files/9371743/kopia_http_trace2.txt)

**Comment by systemmonkey42** [comment]
I'm happy to any apply patches you might think will help you to understand what is going on.  I'm pretty much set up with kopia and haproxy build environments at this point.

**Comment by wtarreau** [comment]
Ah very interesting! I'm currently looking at the code used to send the WU frame. I analysed that part a bit too much trying to find the fault there, to figure that the code there is good. However, going up shows me that we're sending a WU frame for the stream ID being demuxed, which can be set to -1 when no frame is being processed, and I was hoping to see an equivalent -1 in the trace. I'm reassured to see that you caught it on the wire, now it totally makes sense. I'm trying to figure exactly when this can happen and how to address this, but that helps a lot, many thanks!

**Comment by wtarreau** [comment]
I'm now seeing a way how this may happen, and the bidirectional transfer encourages this. Basically we get a buffer full condition on tx that prevents the frame from being sent immediately (due to our upload) and in parallel we get a partial frame header on rx (due to the input buffer being full with data before that frame header). In this case the new frame header will cause h2c->dsi to become -1, we break out of the loop by lack of the rest of the frame header, and once we can finally send that WU frame, we're using that wrong value. Obviously it's extremely timing dependent otherwise it wouldn't be fun. I'm now studying how to best address this.

**Comment by chipitsine** [comment]
Interesting. I'll try to run kopia auto tests with haproxy in front of kopia

**Comment by wtarreau** [comment]
I can now easily reproduce it (I've added a BUG_ON in the WU sending code to catch it). Uploading a POST via H2 to a second instance which returns a 503 makes it happen instantly. The difficulty is to estimate what to change in alternative for resetting h2c->dsi on that line of code that was only added to get non-confusing traces...

**Comment by wtarreau** [comment]
By the way David if you want to test something simple, please just try this (you will have to apply it by hand as I copy-pasted it; in short, just kill the `h2c->dsi=-1` line around line 3640):
```
diff --git a/src/mux_h2.c b/src/mux_h2.c
index 54f792b77..13fdea899 100644
--- a/src/mux_h2.c
+++ b/src/mux_h2.c
@@ -3640,7 +3642,7 @@ static void h2_process_demux(struct h2c *h2c)
                        b_del(&h2c->dbuf, ret);
                        h2c->dfl -= ret;
                        if (!h2c->dfl) {
                                TRACE_STATE("switching to FRAME_H", H2_EV_RX_FRAME|H2_EV_RX_FHDR, h2c->conn);
                                h2c->st0 = H2_CS_FRAME_H;
-                               h2c->dsi = -1;
+                               //h2c->dsi = -1;
                        }
```

With this it must work, I just need to figure what else to use for the traces to know the stream was back to idle. It might end up with a new flag in the worst case...

**Comment by systemmonkey42** [comment]
With that change, I have had no failures.  I have a backup running for a few minutes so far...

Backup of 31GB (1m files) completed in 5 min... 😄

**Comment by wtarreau** [comment]
Great, thank you very much for confirming. Now I'm trying to find the best long-term solution. Congrats for spotting a 3-year old bug :-)

**Comment by wtarreau** [comment]
@systemmonkey42 I've pushed the final fix as well as another tiny one in development branch 20220818-bug-h2-wu-3. I would be pleased if you could give it a try. If you can't try development branch for any reason, no problem, I can also backport them to 2.6 or post the individual patches here, just let me know. Thank you!

**Comment by systemmonkey42** [comment]
@wtarreau Always happy to test something new.
```
7d06b38dc31e:/etc/haproxy# haproxy -vv
HAProxy version 2.7-dev3 2022/08/07 - https://haproxy.org/
Status: development branch - not safe for use in production.
```

This is working well.   All my tests so far have completed successfully.

Many thanks for taking the time to sort this out!   Very much appreciated.

**Comment by wtarreau** [comment]
Ah great, thanks for the quick response! So I can merge this and will backport it to 2.6. With a bit of luck I can make 2.6.3 today.
