### ISSUE TITLE
Feature Request: Changing configuration file without restarting the proxy service

### ISSUE THREAD

**Issue by kylemanel** [haproxy/haproxy#1849]
### Your Feature Request

Having used HA-Proxy in production environments previously, I found it inconvenient to alter the configuration or files being utilized; Proxy configuration file, & certificates, as this required restarting the HAProxy service.
It would be valuable, instead to have the proxy service utilize the configuration file, once during startup, then retain it in memory, such that the configuration file could be altered on-the-fly, and then provide a command to reload the configuration from the file;

1] Start app,
2] App loads configuration into memory,
3] Acts on configuration,
CASE] User changes configuration AND issues configuration change command,
CASE.1] HAProxy app, identifies processes running with old configuration and completes them with the old configuration (in memory), while also;
CASE.2] HAProxy application, reloads the configuration file
CASE.3] Initiating new actions with new configuration, and maintaining prior actions with old configuration.
CASE.4] Once prior actions are completed, discard old configuration.

### What are you trying to do?

This would provide significant flexibility to the application, and enable it to be utilized where accessibility needs to be altered rapidly, or availability must be maintained 24x7.

### Output of `haproxy -vv`

```plain
1.8.X community
```

**Comment by git001** [comment]
This features are already available via runtime api [Dynamic Configuration with the HAProxy Runtime API](https://www.haproxy.com/blog/dynamic-configuration-haproxy-runtime-api/) or via [Dataplane API](https://www.haproxy.com/blog/announcing-haproxy-data-plane-api-2-6/)

My suggestion is to consider a update to the latest LTS Version (2.6) as the 1.8 only receives **critical fixes only** until this year see https://www.haproxy.org/

**Comment by TimWolla** [comment]
In addition to the runtime API you can just *reload* HAProxy for zero-downtime configuration updates. This will spawn new workers with the updated configuration and stop the old ones once they handled all active requests.

**Comment by TimWolla** [comment]
Closing, because this effectively is already available. If you are missing out on something specific that is not updateable live, then please create a feature request dedicated to feature.

**Comment by kylemanel** [comment]
Understood, and thank-you for this information, it makes HAProxy very attractive to me, once again.
