### ISSUE TITLE
src/cfgparse-listen.c: null pointer dereference suspected when "-fsanitize=thread" specified

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1869]
### Tool Name and Version

gcc9 + thread sanitizer

### Code Report

```plain
CC      src/haproxy.o
src/cfgparse-listen.c: In function ‘cfg_parse_listen’:
src/cfgparse-listen.c:305:5: error: potential null pointer dereference [-Werror=null-dereference]
  305 |     ha_alert("parsing [%s:%d] : ambiguous defaults section name '%s' referenced by %s '%s' exists at least at %s:%d and %s:%d.\n",
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  306 |       file, linenum, args[arg+1], proxy_cap_str(rc), name,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  307 |       curr_defproxy->conf.file, curr_defproxy->conf.line, px2->conf.file, px2->conf.line);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

### Additional Information

build command:

make  -j3 CC=gcc ERR=1 DEBUG_CFLAGS="-fsanitize=thread" LDFLAGS="-fsanitize=thread" TARGET=linux-glibc USE_OPENSSL=1

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment]
Thanks Ilya,

gcc complains about pointer deference in ha_alert statement, but in fact it got confused earlier by this:

```c
302:                        if (ebpt_next_dup(&curr_defproxy->conf.by_name)) {
303:                                struct proxy *px2 = container_of(ebpt_next_dup(&curr_defproxy->conf.by_name), struct proxy, conf.by_name);
```

Setting ebpt_next_dup result in tmp variable and using this variable to perform container_of() silences the warning.

Here is a proposed fix:
[0001-BUG-MINOR-cfgparse-listen-fix-ebpt_next_dup-pointer-.patch.txt](https://github.com/haproxy/haproxy/files/10058227/0001-BUG-MINOR-cfgparse-listen-fix-ebpt_next_dup-pointer-.patch.txt)

**Comment by capflam** [comment]
Thanks @Darlelet, now merged !

**Comment by capflam** [comment]
Close it now. Backport will be handled as usual. Thanks !
