### ISSUE TITLE
Stop health checks and DNS lookups when stopping

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1874]
### Your Feature Request

I'd like HAProxy to stop performing backend health checks and DNS lookups when stopping and no more new requests will be sent to a backend.

Care needs to be taken to correctly handle `idle-close-on-response` as indicated in this email: https://www.mail-archive.com/haproxy@formilux.org/msg42739.html

See this mailing list thread for more details: https://www.mail-archive.com/haproxy@formilux.org/msg42738.html

### What are you trying to do?

When HAProxy handles long-running responses, old workers will stick around to handle in-progress connections. The old workers will still perform health checks and DNS lookups, consuming CPU, even though they will not send any new requests to backend servers. I'd like to avoid wasting CPU power for this.

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.5-1~bpo10+1 2022/09/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.5.html
Running on: Linux 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.6.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by TimWolla** [comment]
This behavior is pretty painful for us. Would it be an option to add some additional (possibly protected by the experimental directives flag) option that effectively forces a `disable health` for all servers once the soft stop is started? To my understanding this should be safe in our case, because we don't use `idle-close-on-response`, so idle connections should be closed immediately and connections with live requests will not accept any other request.

**Comment by TimWolla** [comment]
This patch appears to do the trick:

```
diff --git i/src/proxy.c w/src/proxy.c
index a021224d63..313d676395 100644
--- i/src/proxy.c
+++ w/src/proxy.c
@@ -2222,6 +2222,19 @@ static void do_soft_stop_now()
        /* we isolate so that we have a chance of stopping listeners in other groups */
        thread_isolate();
 
+       struct proxy *p = proxies_list;
+
+       while (p) {
+               struct server *sv = p->srv;
+
+               while (sv) {
+                       sv->check.state &= ~CHK_ST_ENABLED;
+                       sv = sv->next;
+               }
+
+               p = p->next;
+       }
+
        /* stop all stoppable listeners */
        protocol_stop_now();
```

**Comment by capflam** [comment]
I'll try to work on this feature. But indeed, a global option is probably the only way to disable dns resolutions and servers health check during a soft-stop. Because otherwise there is no easy way to detect the right conditions to do it safely.

**Comment by capflam** [comment]
Good news. I finally had time to work on this issue. We've finally considered it is a bug. The default behavior is to stop the health checks and the DNS resolutions when HAProxy is stopping. In fact, it was the behavior for the health-checks in 2.2 and lower.

However, I must still add proxy options to change this behavior if anyone relies on health-checks or DNS resolution during soft-stop.

**Comment by TimWolla** [comment]
That's awesome news, thank you!

As the existing resolver change mentions that it may be backported to 2.7 and 2.6, but not earlier: For our use case backporting to 2.7 is sufficient. All affected HAProxy nodes are running 2.7.

**Comment by lukastribus** [comment]
> However, I must still add proxy options to change this behavior if anyone relies on health-checks or DNS resolution during soft-stop.

Do we really want this added complexity? What would be the use-case? Maybe I understand something wrong, but:

- when a in-flight H1 transaction is finished, connections are supposed to be closed, right?
- when a long running in-flight transaction is running against a server that is suddenly declared down by health-checks, this would not solve the problem for the in-flight transaction anyway
- in H2, we should send GOAWAY to all H2 connections as soon as we enter soft-stop mode, only completing in flight transactions?
- in TCP mode, marking a server down is even less useful for in-flight connections and new connections should never be accepted anyway

I really don't understand the use-case of health checking in soft-stop condition.

**Comment by capflam** [comment]
@TimWolla , good to know. I will backport it to 2.7 only on a first step. There is always a risk of breakage with resolvers.

@lukastribus, it may be useful in conjonction with `idle-close-on-response` option for instance to be able to choose a server still alive and with the right IP address. It is not a common use case, indeed. But, in the past, it has already been asked to still perform health-checks during a soft-stop.

**Comment by lukastribus** [comment]
Ok, thanks for clarifying.

**Comment by TimWolla** [comment]
Lukas' question makes me wonder, what happens in the following case:

1. A client connects to a frontend.
2. It begins sending the HTTP headers (e.g. the `GET / HTTP/1.0` line).
3. HAProxy is reloaded.
4. The client finishes sending the full request and only now can HAProxy decide where to send the request.

Will the health checks be stopped after step (3) or after step (4)?

**Comment by capflam** [comment]
Yes, It can happen. And it can be worst because on the step 4, you can have connection retries and redispatch. But we cannot detect these cases.

**Comment by wtarreau** [comment]
Note that it's not because health checks are stopped that it's the end of the world either. The same could be said without stopping actually. It just depends when the health check detecting a bad server happens. We're not killing servers just because we stop, they're still there, in the same state as they were previously.

**Comment by capflam** [comment]
Pushed to 2.7

**Comment by TimWolla** [comment]
I was on Vacation last week, but a co-worker performed the update to 2.7.5 last week. It's *much* better now: The number of of DNS queries per second is now pretty much constant and was reduced by approximately 90%. Thank you!

Old workers are still pretty busy with a large number of `madvise(?, ?, MADV_DONTNEED)` calls which looks wrong, but that's something for a different issue.

**Comment by capflam** [comment]
Thanks for your feedback !

**Comment by capflam** [comment]
No need to backport it to 2.4. I'm closing
