### ISSUE TITLE
haproxy 2.6.5 deb amd64  - segfault at 1 ip 0000648f5dfa3918 sp 000071e4b4cf33e0 error 6 in haproxy[XXXX+1e2000]

### ISSUE THREAD

**Issue by SLoeuillet** [haproxy/haproxy#1875]
### Detailed Description of the Problem

Packages from 
deb http://ppa.launchpad.net/vbernat/haproxy-2.4/ubuntu focal main
deb http://ppa.launchpad.net/vbernat/haproxy-2.6/ubuntu focal main

Random crashes on several hosts with 2.6.5-1ppa1~focal amd64 package

[Tue Sep 20 11:45:25 2022] haproxy[1118423]: segfault at 1 ip 0000579e1089f918 sp 0000778ab1f353e0 error 6 in haproxy[XXXXXX+1e2000]
[Tue Sep 20 11:45:25 2022] Code: e8 4d 70 17 00 e8 e8 67 17 00 c6 04 25 01 00 00 00 00 ba 03 00 00 00 48 8d 35 04 3c 20 00 31 ff e8 2d 70 17 00 e8 c8 67 17 00 <c6> 04 25 01 00 00 00 00 50 58 ba 03 00 00 00 48 8d 35 b2 5a 1e 00

Also have traces of another crash which could be the same in 2.4.18-1ppa1~focal amd64 :
[Tue Sep 13 17:07:00 2022] haproxy[305922]: segfault at 4 ip 0000565573809030 sp 00007ffd524b4960 error 4 in haproxy[XXXXXX+1cf000]
[Tue Sep 13 17:07:00 2022] Code: 01 e0 44 8b 48 04 44 89 ca c1 ea 1c 83 fa 03 75 99 4c 89 eb 4c 8b 64 24 10 4d 89 f5 4c 8b 74 24 18 66 0f 1f 84 00 00 00 00 00 <41> 0f b7 4f 04 41 8b 07 66 41 89 4c 24 26 a8 20 74 06 41 80 4c 24

### Expected Behavior

No crashes

### Steps to Reproduce the Behavior

Wait for the crash

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.5-1ppa1~focal 2022/09/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.5.html
Running on: Linux 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-mOXxkT/haproxy-2.6.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by chipitsine** [comment]
you have accidently (?) exposed password in `userlist backoffice_users`
not sure how sensitive it is

**Comment by SLoeuillet** [comment]
Thanks but that's my redacted version ;)

**Comment by rbogaert-scw** [comment]
I think it looks like the #1862 , it's using resolvers too. Too bad not having the stack trace to compare. 😕

**Comment by capflam** [comment]
FYI, I proposed a patch for #1862. It you have a way to try it, it could be very helpful.

**Comment by SLoeuillet** [comment]
> I think it looks like the #1862 , it's using resolvers too. Too bad not having the stack trace to compare. confused

If you have a deb with symbols so I could share you a trace, I'll take it and share you traces with pleasure at first crash

**Comment by TimWolla** [comment]
@SLoeuillet You can get debug symbols for the PPA by installing `haproxy-dbgsym`.

**Comment by SLoeuillet** [comment]
> @SLoeuillet You can get debug symbols for the PPA by installing `haproxy-dbgsym`.

I see the ddeb in the web folder :
http://ppa.launchpad.net/vbernat/haproxy-2.6/ubuntu/pool/main/h/haproxy/haproxy-dbgsym_2.6.5-1ppa1~focal_amd64.ddeb

But I can't install it from apt.
Downloaded and installed it manually

Waiting for the next crash to extract a meaningful stack trace, thanks

**Comment by SLoeuillet** [comment]
My fault, missing main/debug :
deb http://ppa.launchpad.net/vbernat/haproxy-2.6/ubuntu focal main main/debug

**Comment by capflam** [comment]
FYI, a fix in resolvers was pushed. It may fix your issue. The 2.6.6 was released and it ships the fix. Could you try it ?

**Comment by SLoeuillet** [comment]
Both nodes updated to 2.6.6
@capflam : are you sure fix is included in 2.6.6 ?

2.6.6 was released on 2022/09/21

Your fix did touch master on 2022/09/27
https://github.com/haproxy/haproxy/commit/eaabf060312f6aad1c0c195ad33e5ea612acc47a

As 2.6.6 is not tagged in github, I can't check (last release tagged was v2.6.0)

**Comment by capflam** [comment]
Damned, you're right the fix was not included in the 2.6.6. Sorry !

**Comment by bmailhe** [comment]
Any update on this ?

**Comment by capflam** [comment]
Well, the 2.6.7 should be release soon but there are still few open bugs we want to fix first. However, a resolvers fix was backported and is available in the 2.6 repo. It might fix this issue, but with no trace, it is hard to be categorical.

**Comment by capflam** [comment]
FYI, the 2.6.7 was finally released. Sorry for the delay !

**Comment by capflam** [comment]
Any news about this issue ? Does the 2.6.7 fix it ?

**Comment by capflam** [comment]
FYI, the 2.6.8 was released.

**Comment by capflam** [comment]
I'm closing because a potential fix was provided and no other report since a while. But If it still happens, feel free to reopen this issue with more info. Thanks. Labels are not changed to know it is not 100% fixed for sure.
