### ISSUE TITLE
metric description

### ISSUE THREAD

**Issue by zhangzhuzi** [haproxy/haproxy#1882]
hi! where can I find the detailed metric description of haproxy exporter,such as Globals metrics/Frontend metrics/Listener metrics/Backend metrics/Server metrics/Stick table metrics.

**Comment by Darlelet** [comment]
Hi,

Please take a look at: [`addons/promex/README`](https://github.com/haproxy/haproxy/tree/master/addons/promex), there is a section named "**Exported metrics**" that should help you.

A quick reminder though,  Github issues are meant for bugs, code reports or feature requests only!

Don't hesitate to use [discourse](https://discourse.haproxy.org) next time you're looking for help about something that is not related to haproxy's development.
