### ISSUE TITLE
HAProxy doesn't forward important TLV header by ProxyProtocol v2

### ISSUE THREAD

**Issue by adam-prohack** [haproxy/haproxy#1890]
### Detailed Description of the Problem

I have a problem with Proxy Protocol 2 and the HAProxies chain. In my solution architecture, I have connected in series some network proxies and load balancers. Incoming traffic is moved by AWS NLB in TCP mode (without TLS termination), to HAProxy where TLS is terminated and this proxy checks the Client Certificate (mTLS). Finally, traffic from this HAProxy is forwarded with proxy protocol v2 to another HAProxy instance and next to my application. First HAProxy instance set PP2_SUBTYPE_SSL_CN TLV record which is read by my application when it is connected directly to this proxy. Unfortunately, my application couldn't terminate TLS, and to ensure end-to-end encryption I need to have an additional HAProxy as a sidecar on the machine (container) where my application is run. Sidecar HAProxy doesn't forward PP2_SUBTYPE_SSL_CN TLV record received from source HAProxy to my application and I am not able to read source client certificate CN. In my opinion, it is a bug, because there is not possible to connect more than 1 HAProxies in a chain when I want to use mTLS authentication for my application. Maybe you have any idea how e.q. with LUA scripts can I achieve forwarding TLV records on HAProxy?

Architecture draft:
 AWS NLB(PP2 outcoming) -> HAProxy (PP2 incoming/outcoming, TLS, mTLS, TLV SSL CN set) ->HAProxy (PP2 incoming/outcoming, TLS, TLV SSL CN accidentally erased) -> Application (require TLV SSL CN)

### Expected Behavior

HAProxy should forward PP2_SUBTYPE_SSL_CN TLV record received from listener to backend when it wasn't changed in chain.

### Steps to Reproduce the Behavior

1. You need to install HAProxy with enabled proxy protocol v2 on backend. Configure TLS termination and mTLS authorization on this instance.
2. Install HAProxy with enabled proxy protocol v2 on listener and backend. Configure only TLS termination e.q. with self signed certificate
3. Set up first instance backend to forward traffic to second instance listener
4. Connect second instance backend to application which require PP2_SUBTYPE_SSL_CN TLV record like VerneMQ MQTT broker.

### Do you have any idea what may have caused this?

HAProxy only set PP2_SUBTYPE_SSL_CN TLV header when instance has client certificate validation enabled and loses this information when client certificate validation was enabled on the first HAProxy in HAProxies chain.

### What is your configuration?

```haproxy
frontend http_frontend
    mode            http
    bind            *:18888 ssl crt /ssl/haproxy.pem
    default_backend vernemq_http_backend
backend vernemq_http_backend
    mode            http
    server          localhost 127.0.0.1:8888 verify none check
frontend mqtt_frontend
    bind            *:11883 ssl crt /ssl/haproxy.pem accept-proxy
    default_backend vernemq_mqtt_backend
backend vernemq_mqtt_backend
    server          localhost 127.0.0.1:1883 check send-proxy-v2
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.6-274d1a4 2022/09/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.6.html
Running on: Linux 5.10.124-linuxkit #1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022 aarch64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by nsaeris** [comment]
I have a similar use case. There should be a way to pass the client certification CN through the chain of HAProxy proxies. This would be similar to how client source IP and ports are passed along the chain. Since each path in the chain may have different TLS auth and certs involved, it would be good to have a dedicated TLV for the initial client cert CN.

**Comment by capflam** [comment]
Sorry for the late reply. It seems to be more a feature request than a bug. Because the current behavior is expected, while it not feats your requirements.  I didn't check if it can solve your issue, but in 2.9, the `set-proxy-v2-tlv-fmt` option was added. It could be good to take a look. 

In the mean time, I'm closing the issue. Feel free to create a feature request if necessary. Thanks !
