### ISSUE TITLE
Build fails with the openssl-3.0.6+quic branch of quictls/openssl

### ISSUE THREAD

**Issue by elyograg** [haproxy/haproxy#1893]
### Detailed Description of the Problem

The openssl project released version 3.0.6.  Today quictls began preparations for their 3.0.6 release and created a new branch named openssl-3.0.6+quic.

After upgrading to this new branch, haproxy's master branch fails to build.  I do not know if the problem is in haproxy or quictls.  If the quictls project is intentionally changing their API in an incompatible way, then probably haproxy.

Build output:

```
Already up to date.
  CC      src/ev_poll.o
  CC      src/ev_epoll.o
  CC      src/cpuset.o
  CC      src/ssl_sample.o
  CC      src/ssl_sock.o
  CC      src/ssl_crtlist.o
  CC      src/ssl_ckch.o
  CC      src/ssl_utils.o
In file included from include/haproxy/quic_cc.h:33,
                 from include/haproxy/quic_conn.h:41,
                 from src/ssl_sock.c:68:
include/haproxy/quic_conn-t.h:514:37: error: field ‘level’ has incomplete type
  514 |         enum ssl_encryption_level_t level;
```

### Expected Behavior

I expected it to build without warnings or errors, as it does with openssl-3.0.5+quic.

### Steps to Reproduce the Behavior

1. Install newest quictls/openssl branch.
2. Build haproxy with that version of openssl.

### What is your configuration?

Build command for haproxy:

```make -j4 TARGET=linux-glibc \
      USE_PCRE2_JIT=1 \
      USE_OPENSSL=1 \
      USE_ZLIB=1 \
      USE_SYSTEMD=1 \
      CPU=native \
      USE_QUIC=1 \
      SSL_INC=/opt/quictls/include \
      SSL_LIB=$QUICTLS_LIB \
      LDFLAGS="-Wl,-rpath,/opt/quictls/lib64" \
      DEBUG=" "
```

### Output of `haproxy -vv`

It doesn't build, so I can't get this.  If I try to run the existing haproxy version with the new quictls, I get this because the new quictls uses different library filenames:

`haproxy: error while loading shared libraries: libssl.so.81.3: cannot open shared object file: No such file or directory`

**Comment by shipitsin-ilia** [comment]
`include/haproxy/quic_conn-t.h:514:37: error: field ‘level’ has incomplete type` usually happens when you try to enable QUIC on vanilla OpenSSL

is it possible that freshly created branch does not yet include quic patch ?

**Comment by elyograg** [comment]
That is very possible.  They only created it six hours ago.  I thought maybe I should have waited until they changed the default branch to 3.0.6, but I was a little excited about a new branch. :)

**Comment by elyograg** [comment]
Got the release announcement for 3.0.6+quic, updated my repos, and built again.  Worked this time.

**Comment by elyograg** [comment]
And now I see that openssl is withdrawing 3.0.6 and will soon release 3.0.7.  All kinds of fun.
