### ISSUE TITLE
Allow NOLB return from agent-check

### ISSUE THREAD

**Issue by jlecour** [haproxy/haproxy#1904]
### Your Feature Request

Currently, the agent-check allows for many status : up/down/failed/stopped and ready/maint/drain
But the useful NOLB status can't be set from the agent-check.

### What are you trying to do?

I'd like to mark a server as "out of load-balancing" without marking it as down or maint.

My use case is for read-only databases (like Redis) when they are in "replica" mode, but have the agent set themto UP and ready when they become "master".

I know thath for Redis it is generally advised to use a tcp-check and look for the replication role,but it sets the server in DOWN status when it is slave, which is notthe correct status. It is definitely UP but should not receive any request.

I've worked around this by setting the server to DRAIN, but semantically it's less expressive.

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.9-2+deb11u3 2022/03/10 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
Running on: Linux 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -ffile-prefix-map=/build/haproxy-UmgAPI/haproxy-2.2.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

**Comment by jlecour** [comment]
Here is the content of my agent-check :

```bash
#!/bin/sh

set -u

config_var() {
    variable=$1
    file=$2
    test -f "${file}" && grep -E "^${variable}\s+.+$" "${file}" | awk '{ print $2 }' | sed -e "s/^[\"']//" -e "s/[\"']$//"
}
get_role() {
    host=$(config_var "bind" "${conf_file}")
    port=$(config_var "port" "${conf_file}")
    pass=$(config_var "requirepass" "${conf_file}")

    if [ -n "${pass}" ]; then
        export REDISCLI_AUTH="${pass}"
    fi

    cmd="${redis_cli_bin} -h ${host} -p ${port} INFO REPLICATION"
    ${cmd} 2>/dev/null | grep -Eo "role:\w+" | cut -d ':' -f2
}
get_status() {
    systemctl is-active "${1}"
}

redis_cli_bin=$(command -v redis-cli)
if [ -z "${redis_cli_bin}" ]; then
    printf "%s\n" "down # missing redis"
    exit 1
fi
if [ $# -lt 1 ]; then
    service="redis-server.service"
    conf_file="/etc/redis/redis.conf"
else
    service="redis-server@${1}.service"
    conf_file="/etc/redis-${1}/redis.conf"
fi
if [ ! -r "${conf_file}" ]; then
    printf "%s\n" "down # missing config"
    exit 3
fi

status=$(get_status "${service}")

case "${status}" in
    active)
        printf "%s " "up"
        ;;
    inactive)
        printf "%s\n" "stopped # systemd:${status}"
        exit 1
        ;;
    failed)
        printf "%s\n" "fail # systemd:${status}"
        exit 1
        ;;
    *)
        printf "%s\n" "down # systemd:${status}"
        exit 1
        ;;
esac

role=$(get_role "${conf_file}")

case "${role}" in
    master)
        printf "%s" "ready # role:master"
        ;;
    slave)
        printf "%s" "maint # role:slave"
        ;;
    *)
        printf "%s" "maint # role:unknown"
        ;;
esac
printf "\n"

exit 0
```

The xinetd script to have the agent shell script accessible over TCP : 

```
service haproxy-agent-redis-role
{
        socket_type     = stream
        bind            = 172.19.3.200
        port            = 16379
        protocol        = tcp
        wait            = no
        type            = UNLISTED
        user            = root
        server          = /usr/share/scripts/haproxy-agent-redis-role.sh
        log_on_failure  += USERID
        disable         = no
        only_from       = 172.19.3.100 172.19.3.101 172.19.3.102
}
```

and the HAProxy config snippet :

```haproxy
frontend fe_redis
    mode tcp
    option tcplog

    bind 127.0.0.1:6379

    default_backend be_redis

backend be_redis
    mode tcp
    balance first

    default-server maxconn 1024 check agent-check agent-port 16379 agent-inter 1s

    server srv1 172.20.3.200:6379
    server srv2 172.20.3.201:6379
```

**Comment by wtarreau** [comment]
Unless I'm missing something, `NOLB` is the health equivalent of the administrative `DRAIN` state. It predates it because in older times we abused the health check so that the administrator could express a drain state there. But now that you can explicitly report `drain` in the agent status, are you still seeing any difference between the two for your use case ? The principle is the same, in both cases the weight will be set to zero so that only existing sessions reach the server but no new ones.

**Comment by jlecour** [comment]
Hi @wtarreau 

> NOLB is the health equivalent of the administrative DRAIN state

That is an interresting clarification ;)

I guess I could settle for a DRAIN state, if they are the same.

But, If I understand correctly, the DRAIN state won't close already open connections.

When we have long lived connections to a database, If the state changes, connections to the master would become connections to a slave/replica. I guess it could be problematic.

**Comment by wtarreau** [comment]
DRAIN will indeed not close any open connection, just like NOLB (both technically just set the server's weight to 0).

If you need to forcefully kill connections to a server, please have a look at the `observe layer4` statement combined with `on-marked-down ...` and `on-marked-up ...`. For example with databases what people often do is to kill all connectionn when the server is marked down and to kill all backup connections when an active server is marked up. That may or may not match your needs. In any case you'll need to terminate the DRAIN state with the server being marked down for this to happen, but I guess that's the intent since DRAIN/NOLB are only meant to be transient. And switching to maint should count as a down transition as well and result in killing connections as well.

**Comment by jlecour** [comment]
Thanks a lot for this.
It seems to imply that I need to have a phased change when a change of master/replica is happening.
I hoped that I could to it in just one step, with a very simple agent check.

I'm closing the issue for the moment, but will reopen it if needed.

Thanks again.

**Comment by wtarreau** [comment]
Indeed, if what you really want is 1) stop accepting new connections and 2) close existing ones after some time, it's necessarily a two-phase operation. If instead you just want to instantly kick all connections and prevent new ones from arriving, then you'd rather announce that the service is down, and this grouped with `on-marked-down` will result in all connections being instantly killed. The difficulty with TCP connections is always the same, find when it's best to kill remaining connections to be sure not to degrade the service. If the database itself is able to kill existing connections (or just to force them to quit after the end of the next operation) that could then provide the necessary cleanup without risking to kick them too fast.
