### ISSUE TITLE
No DNS resolution by healthcheck 

### ISSUE THREAD

**Issue by keyolk** [haproxy/haproxy#1906]
### Detailed Description of the Problem

With the below configuration
```
resolvers awsvpc
  nameserver awsvpc 169.254.169.253:53
  resolve_retries 3
  hold valid 3s
  timeout resolve 30s
  
listen rabbitmq1
  bind :5672
  option clitcpka
  server master myrabbitmq-master:5672 resolvers awsvpc check rise 2 fall 2 inter 1s on-marked-down shutdown-sessions on-marked-up shutdown-backup-sessions
  server slave myrabbitmq-slave:5672 resolvers awsvpc check rise 2 fall 2 inter 1s backup
```

I checked that DNS resolution is done every 30s.
And tried with DNS resolution by health check trigger.

I tried that blocking network with iptables

And checked the below line is run with gdb. Seems it is related.
https://github.com/haproxy/haproxy/blob/v2.4.0/src/resolvers.c#L453
```
(gdb) directory /usr/local/src/haproxy
Source directories searched: /usr/local/src/haproxy:$cdir:$cwd
(gdb) b src/resolvers.c:463
Breakpoint 1 at 0xaaaabd92acb0: file src/resolvers.c, line 463.
(gdb) b src/dns.c:104
Breakpoint 2 at 0xaaaabd96606c: file src/dns.c, line 104.
(gdb) c
Continuing.
[Switching to LWP 2505364]

Thread 1 "haproxy" hit Breakpoint 1, resolv_trigger_resolution (req=<optimized out>) at src/resolvers.c:463
463             if (resolvers->t && (res->status != RSLV_STATUS_VALID ||
(gdb) s
109             if (unlikely((timer - now) <= 0))
(gdb) s
465                     task_wakeup(resolvers->t, TASK_WOKEN_OTHER);
```

But when I see it with tcpdump there was no request until the regular DNS resolution.

### Expected Behavior

Having DNS resolution when the health check failed and triggers it.

### Steps to Reproduce the Behavior

Block the network after 10s of the last DNS resolution which is regular DNS resolution.

```
$ iptables -A OUTPUT -p tcp --dport 5672 -j DROP
```

### What is your configuration?

```haproxy
global
  log /dev/log local0 debug
  # daemon
  maxconn 50000

default RABBITMQ
  mode tcp
  timeout connect 4s
  timeout server 86400s
  timeout client 86400s
  timeout check 10s
  log /dev/log/local0 debug debug
  log-format ""%ci:%cp %si:%sp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq"
  option log-health-checks

resolvers awsvpc
  nameserver awsvpc 169.254.169.253:53
  resolve_retries 3
  hold valid 3s
  timeout resolve 30s
  
listen rabbitmq1
  bind :5672
  option clitcpka
  server master myrabbitmq-master:5672 resolvers awsvpc check rise 2 fall 2 inter 1s on-marked-down shutdown-sessions on-marked-up shutdown-backup-sessions
  server slave myrabbitmq-slave:5672 resolvers awsvpc check rise 2 fall 2 inter 1s backup
```
```


### Output of `haproxy -vv`

```plain
$ haproxy -vv
HAProxy version 2.4.19-ec55434 2022/09/28 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.19.html
Running on: Linux 5.13.0-1031-aws #35~20.04.1-Ubuntu SMP Mon Jun 13 22:33:23 UTC 2022 aarch64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
Running on OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.2.1 20220219

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

```
$ uname -a
Linux mymachine #35~20.04.1-Ubuntu SMP Mon Jun 13 22:33:23 UTC 2022 aarch64 Linux
```
```


### Last Outputs and Backtraces

_No response_

### Additional Information

We use 
- docker image haproxy:2.4.19-alpine
- on ubuntu focal
- with 5.13 kernel

**Comment by lukastribus** [comment]
> Expected Behavior
> Having DNS resolution when the health check failed and triggers it.

This is not expected behavior.

**Comment by capflam** [comment]
Sorry, I don't understand the issue. Healthchecks and DNS resolution are not related.

**Comment by keyolk** [comment]
@capflam, @lukastribus 
I read this from the document below.
And I thought it means it would trigger DNS resolution when the HC is failed.

https://docs.haproxy.org/2.4/configuration.html#5.3
> A few other events can trigger a name resolution at run time:
>  - when a server's health check ends up in a connection timeout: this may be
    because the server has a new IP address. So we need to trigger a name
    resolution to know this new IP.

**Comment by capflam** [comment]
Indeed, It seems you're right. I was not aware that DNS resolutions could be triggered from health-checks. I guess there is an issue here, because in the resolver code, the resolutions are performed periodically (configured via `timeout resolve` directive) and AFAIK, it cannot be speed up. I'll see with @bedis if it is expected or not.

To make thing a bit easier to review, the following patch should do the trick. However, I don't know if it is the best way to fix the issue.

```diff
diff --git a/src/resolvers.c b/src/resolvers.c
index 4bbc6e50b3..996f3c70eb 100644
--- a/src/resolvers.c
+++ b/src/resolvers.c
@@ -460,8 +460,11 @@ void resolv_trigger_resolution(struct resolv_requester *req)
         * valid */
        exp = tick_add(res->last_resolution, resolvers->hold.valid);
        if (resolvers->t && (res->status != RSLV_STATUS_VALID ||
-           !tick_isset(res->last_resolution) || tick_is_expired(exp, now_ms)))
+           !tick_isset(res->last_resolution) || tick_is_expired(exp, now_ms))) {
+               if (res->step == RSLV_STEP_NONE)
+                       res->last_resolution = TICK_ETERNITY;
                task_wakeup(resolvers->t, TASK_WOKEN_OTHER);
+       }
 
        leave_resolver_code();
 }
```

**Comment by lukastribus** [comment]
A bit of history for context:

A long time ago (haproxy 1.7 and older), DNS run time resolution was *only* triggered by health checks, there was no periodic DNS resolution, unless triggered by health checks.

See: https://docs.haproxy.org/1.7/configuration.html#5.3.1

In fact this is also where this text comes from (`when a server's health check ends up in a connection timeout ... we need to trigger a name resolution to know this new`).

I'm not sure whether this ever worked in 1.7 and older but a large change in 1.8 certainly was to implement DNS run time resolution independently from health checks. Also the sentence does not sound very "convincing". It is unclear what "We need to do X" means in the context of documentation: it is implemented this way or is it a developer note/todo item that would belong in a commit message?

Regarding this change in behavior which technically is a new feature: I would ask that we don't backport it, considering that health checks and DNS subsystems are fragile, and this is the first time this comes up in the 7 years we have this (commit 1fa666681df21935efec2005f9a67957d88ccf7a).

**Comment by keyolk** [comment]
@lukastribus Thanks for giving historical information!
I think what the document said is not about to-do items.
Cause there is related code already at https://github.com/haproxy/haproxy/blob/master/src/check.c#L921

**Comment by capflam** [comment]
I checked and it seems the "feature" was lost during the resolvers refactoring (67957bd5). I must found some time to investigate deeper. But it seems to be a very old regression. And I agree with @lukastribus, this part is pretty sensitive. Especially because this part is also used by `do-resolve` action.

**Comment by capflam** [comment]
I pushed a fix for this issue. The patch will probably be backported but not too far and slowly to be sure there is no regression. At first glance, it seems safe. But this part is tricky and the resolvers design makes it really hard to audit.

**Comment by capflam** [comment]
It will not backported to 2.2. I'm closing now.
