### ISSUE TITLE
Limit rate speed/bandwidth

### ISSUE THREAD

**Issue by sbh96** [haproxy/haproxy#1907]
### Your Feature Request

Hi, i want to limit bandwidth for my backend servers to prevent high speed connections around 50kb per secend 
I use haproxt to reverse proxy my websocket (v2ray sever)
And i want limit connection per user ip
I check rate limit documents i donw want to limit my request i want to something like `rate_limte` option in nginx but i think haproxy havent this feature

### What are you trying to do?

.

### Output of `haproxy -vv`

```plain
--
```

**Comment by git001** [comment]
The current development branch have the bandwith filter https://github.com/haproxy/haproxy/blob/master/src/flt_bwlim.c which is documented https://docs.haproxy.org/dev/configuration.html#9.7 maybe this filter fulfills your request

**Comment by capflam** [comment]
Indeed. This kind of limit already exists, but only on the 2.7-DEV.
