### ISSUE TITLE
cpu overconsumption

### ISSUE THREAD

**Issue by High-snoop** [haproxy/haproxy#1912]
### Detailed Description of the Problem

Hi,

After a year of using a simple haproxy, there was an overconsumption of cpu without explanation.

![image](https://user-images.githubusercontent.com/117070741/198961946-9b9e2b4c-f3a5-4cd7-a1b1-50b0df8570b7.png)
![image](https://user-images.githubusercontent.com/117070741/198962232-0d7505ee-2056-4f8b-9174-b6bb4f26ae48.png)

After restart only the haproxy, the situation is back to normal.

No other network activity detected
![image](https://user-images.githubusercontent.com/117070741/198964308-45d78d71-771c-43f6-b2cc-ba02d798316e.png)

No memory overactivity 
![image](https://user-images.githubusercontent.com/117070741/198964523-4980183a-daf2-49e6-bc6e-52e2639315c1.png)

And no IO disk too
![image](https://user-images.githubusercontent.com/117070741/198964069-d99f610d-525e-4ae0-83e6-247c50b54b48.png)

### Expected Behavior

N/A

### Steps to Reproduce the Behavior

unknown
It was the first time we had this type of problem with a haproxy

### Do you have any idea what may have caused this?

Good question :-)

### Do you have an idea how to solve the issue?

No Unfortunately

### What is your configuration?

```haproxy
#-----------------------------------------------------------------------------------------------------------------------
# Global settings
#-----------------------------------------------------------------------------------------------------------------------

global

    log 127.0.0.1 local2

    maxconn     5000
    user        "$APP_USER"
    daemon
    tune.ssl.default-dh-param 2048

    stats socket "$APP_DIR/haproxy/haproxy.sock" user "$APP_USER" group "${APP}${ENV}" mode 660 level admin
    stats timeout 2m

#-----------------------------------------------------------------------------------------------------------------------
# Default settings
#-----------------------------------------------------------------------------------------------------------------------

defaults

      mode                    http
      log                     global
      option                  tcplog
      option                  dontlognull
      option                  redispatch
      retries                 3
      timeout http-request    10s
      timeout queue           1m
      timeout connect         10s
      timeout client          1m
      timeout server          1m
      timeout http-keep-alive 10s
      timeout check           10s
      maxconn                 3000
      stats                    enable

#-----------------------------------------------------------------------------------------------------------------------
# Frontends & Backends settings
#-----------------------------------------------------------------------------------------------------------------------


frontend front_mcp_bddf
    bind *:8443
    mode tcp
    option tcplog
    default_backend back_dtp_bddf


backend back_dtp_bddf
  mode tcp
  server dtp_1 "$HAP_DTP_BDDF_1" check inter 60s
  server dtp_2 "$HAP_DTP_BDDF_2" check inter 60s
  server dtp_3 "$HAP_DTP_BDDF_3" check inter 60s
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.0-6cbbecf 2021/05/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.0.html
Running on: Linux 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_OPENSSL=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

### Additional Information

How can we debug more by viewing more than tcp or http logs to identify the root cause.
We didn't activate rsyslog logs on this server.
Thanks for your help

**Comment by lukastribus** [comment]
2.4.0 is not a good choice to run in production.

http://www.haproxy.org/bugs/bugs-2.4.0.html

403 bugs, 32 of them MAJOR and 154 of them MEDIUM, there are 19 subsequent bugfix releases available.


Please upgrade to the latest bugfix release as listed on http://www.haproxy.org/


It doesn't make a lot of sense to start an investigation when there are so many known bugs that you would hit sooner or later anyway.

**Comment by High-snoop** [comment]
I understand your remarks, we used this version on this projet since one year without issue,
So you recommend to used [2.4.19], [2.5.9] or [2.6.6].

**Comment by TimWolla** [comment]
> So you recommend to used [2.4.19], [2.5.9] or [2.6.6].

I recommend either 2.4.19 (and then staying up to date with all 2.4.x updates) or 2.6.x (and then also staying up to date). I recommend against 2.5.x, because that is not a LTS version and thus requires you to switch branches more often. It's targeted at experienced power-users.

**Comment by High-snoop** [comment]
Thanks for your quick feedback.
I will update to 2.4.19. (DEV -> HML -> PRD)
So what we have to configure to get more log as debug ?

**Comment by lukastribus** [comment]
If the process starts busy looping again, the first thing I'd do is attach strace to the process consuming all the CPU and see what happens on a syscall level:

`strace -tt -p <PID> -o strace-output.log`

This doesn't require any other preparation, it's just something you'd do before restarting haproxy while the process is still spinning.

**Comment by High-snoop** [comment]
Thanks your help.
I'll open another issue if the cpu overconsumption back again after update
