### ISSUE TITLE
Urgent help: need pricing for haproxy enterprise edition

### ISSUE THREAD

**Issue by sona0108** [haproxy/haproxy#1916]
### Detailed Description of the Problem

 haproxy we are using now is unlicensed free version, need pricing for haproxy enterprise edition
we need some estimate costs. if we move to the licensed version

we are using 4 HAproxy servers, can we have estimated costs?
you can give examples like other companies using 

### Expected Behavior

Urgent help: need pricing for haproxy enterprise edition

### Steps to Reproduce the Behavior

it is documented request 

### What is your configuration?

```haproxy
NA
```

### Output of `haproxy -vv`

```plain
currently we have HAProxy version 2.4.7
```

**Comment by capflam** [comment]
It is not the right place to get such info. Feel free to contact HAProxy Technologies company: https://www.haproxy.com/contact-us/
