### ISSUE TITLE
[PATCH] Better error reporting when command isn't found via socket runtime API

### ISSUE THREAD

**Issue by shadyabhi** [haproxy/haproxy#1937]
### Your Feature Request

Patch: [0001-MINOR-cli-print-parsed-command-when-not-found.patch](https://gist.github.com/shadyabhi/7c3c77a068fba7b58eb24463f62c6a50) 

`NOTE`: Apologize if its wrong to send it here, as opposed to what the `CONTROBUTING` says to send over mailing list, I felt that Github seems more popular looking at the activity and how the project is accepting patches as part of creating issues.

When no command matches in socket API, HAproxy should also return the `command that was parsed` before declaring that it didn't find a match. 

Previously:-
```
➤ echo -e "show version\nhelpp"| socat ./haproxy.sock - | head -n4
2.7-dev6

Unknown command, but maybe one of the following ones is a better match:
  add map [@<ver>] <map> <key> <val>      : add a map entry (payload supported instead of key/val)
```

Now:-
```
 ➤ echo -e "show version\nhelpp"| socat ./haproxy.sock - | head -n4
2.7-dev8-737bb7-156

Unknown command: 'helpp', but maybe one of the following ones is a better match:
  add
```

`Unknown command: "helpp"` exactly guides user what went wrong, just like `bash shell` does. 

### What are you trying to do?

Let's suppose a user is following official docs to upload a new cert in HAproxy, he might copy-paste the following command from [docs.](https://www.haproxy.com/documentation/hapee/latest/api/runtime-api/set-ssl-cert/)

```
echo -e "set ssl cert /etc/hapee-2.6/certs/site.pem <<\n$(cat ./new_certificate.pem)\n" | socat stdio tcp4-connect:127.0.0.1:9999
```

Since `./new_certificate.pem` is a PEM file, it is completely valid to have a `newline` in it. When HAproxy starts processing the `payload`, it'll stop processing the payload at `first occurrence of newline` and all the other lines in the next PEM block will result in a cryptic `Unknown Command` error, because `-----BEGIN` isn't a valid command as an example. 
Ideally, the error should tell what the user must do next. As someone new to HAproxy, it wasn't entirely obvious to me at first. Granted, after knowing what happened, the issue is pretty obvious :)  

### Output of `haproxy -vv`

```plain
➤ ./haproxy -vv | head
HAProxy version 2.7-dev8-737bb7-156 2022/11/17 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_STATIC_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
```
```

**Comment by wtarreau** [comment]
That's a very good reason for doing it, you're absolutely right, and I agree that it has already happened to me as well when chaining commands. However there's a tiny bug in your patch: as you can see, the condition to report the error depends on !args || !*args || !**args, yet you're trying to append *args. You need to take care of this situation by conditionning the second chunk_strcat() by `args && *args`, and then that's OK, I'll merge it.

Thank you!

**Comment by shadyabhi** [comment]
Hi @wtarreau, thank you for taking the time to review this request. As suggested, I've updated it with the check before using *args.

[0001-MINOR-cli-print-parsed-command-when-not-found.patch](https://gist.github.com/shadyabhi/7c3c77a068fba7b58eb24463f62c6a50)

**Comment by wtarreau** [comment]
OK thank you, now merged! I've just slightly re-indented the commit message because some lines were far too long, and commit messages don't use markdown formatting. I've also verified it didn't break reg-tests (just in case one of them would include the error message in a capture, but this wasn't the case).

Thanks!
