### ISSUE TITLE
http-request set-uri only sets path for HTTP/2 requests

### ISSUE THREAD

**Issue by bartbutler** [haproxy/haproxy#1938]
### Detailed Description of the Problem

We are trying to use `http-request set-uri` to control the URI sent in the request line to our backends. It works fine when the client uses HTTP/1.1 to connect to the front-end, but only sets the path of HTTP/2 is used. Using an intermediate loopback HTTP/1.1 frontend to "sanitize" the request works as a workaround.

Note that HTTP/2 requests typically contain the scheme and host in the request line and this is passed without modification to HTTP/1.1 backends, which works fine. We only see this path truncation behavior when using `http-request set-uri`.

### Expected Behavior

We expect `http-request set-uri` to set the entire URI of the request line regardless of whether the initial request was HTTP/2 or HTTP/1.1.

### Steps to Reproduce the Behavior

Below a sample backend configuration. It points to a Squid proxy. The health check works fine and has the entire URI. If it's connected to a front-end and the client requests using HTTP/1.1, it also works. If the client uses HTTP/2, the request is only GET %[pathq]. This can be verified with Wireshark or tcpdump.

backend proxy
  balance random(2)
  mode http
  http-check connect port 3128
  http-check send meth HEAD uri https://www.hcaptcha.com/ ver HTTP/1.1
  http-check expect status 200
  option httpchk
  option          redispatch 1
  retry-on        conn-failure empty-response junk-response response-timeout 0rtt-rejected 403 500 502 503 504

  http-request set-uri "https://www.hcaptcha.com%[pathq]"
  default-server  inter 20s fastinter 2s init-addr last,libc,none no-ssl proto h1
  server-template squid_ 2 squid.data.plabs.ch:3128 maxconn 500 weight 10

### Do you have any idea what may have caused this?

No, I looked at the code and didn't see anything obvious.

### Do you have an idea how to solve the issue?

No

### What is your configuration?

```haproxy
backend proxy
  balance random(2)
  mode http
  http-check connect port 3128
  http-check send meth HEAD uri https://www.hcaptcha.com/ ver HTTP/1.1
  http-check expect status 200
  option httpchk
  option          redispatch 1
  retry-on        conn-failure empty-response junk-response response-timeout 0rtt-rejected 403 500 502 503 504

  http-request set-uri "https://www.hcaptcha.com%[pathq]"
  default-server  inter 20s fastinter 2s init-addr last,libc,none no-ssl proto h1
  server-template squid_ 2 squid.data.plabs.ch:3128 maxconn 500 weight 10
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.19-ec55434 2022/09/28 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.19.html
Running on: Linux 5.7.4-1.el7.elrepo.x86_64 #1 SMP Thu Jun 18 10:06:20 EDT 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PTHREAD_PSHARED=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1 USE_OT=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD +PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS +OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
Running on OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[  OT] opentracing
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by wtarreau** [comment]
Hi Bart,

thanks for reporting this. I have not looked yet but what I'm suspecting is that set-uri sets the authority here but that there wasn't any in the initial request (host only) and as such it wasn't used on output. Or conversely, maybe it sets the host without affecting the authority and only the authority was used. We'll have to check this closer next week I think.

**Comment by bartbutler** [comment]
Thanks for looking into it!

**Comment by capflam** [comment]
It is because the URI was marked as normalized during the H2 parsing. In H2, `:authority`, `:scheme` and `:path` pseudo-header are converted into an absolute-URI to ease request processing between H1 and H2. When the request is forwarded to the server, the most common format is chosen. In H2, the URI is split in pseudo headers (`:authority`, `:scheme` and `:path`). In H1, because, the request URI was normalized, a relative URI is sent. This way, the most common and less surprising format is used in output, depending on the http version. However, an absolute URI received from a H1 client will be forwarded using the same format to a H1 server. 

Thus, I'm annoyed because, in your example, it seems natural to remove the info about the URI normalization, to be sure an absolute URI will be used in H1. But I don't know if someone is relying on the current behavior... 

The patch is trivial:

``` diff
diff --git a/src/http_htx.c b/src/http_htx.c
index 7a32c2156f..dbb9c966a4 100644
--- a/src/http_htx.c
+++ b/src/http_htx.c
@@ -389,6 +389,7 @@ int http_replace_req_uri(struct htx *htx, const struct ist uri)
                goto fail;
 
        sl = http_get_stline(htx);
+       sl->flags &= ~HTX_SL_F_NORMALIZED_URI;
        if (!http_update_host(htx, sl, uri))
                goto fail;
 
```

**Comment by bartbutler** [comment]
Thanks for the explanation! What's the procedure for figuring out whether anyone is relying on this (odd) behavior? Any chance we could get it in a 2.4 bugfix release (we'll use the patch for now, thanks).

**Comment by capflam** [comment]
Well, I've decided to push the proposed patch. It will backported as far as 2.4. However, for now, we are focusing on the 2.7 release. So other releases will be delayed a bit.

**Comment by bartbutler** [comment]
No worries, thank you so much for fixing it, we'll use the patch in our build for now.

**Comment by ballestr** [comment]
Thanks a lot again for the patch @capflam , we have rebuilt 2.4.19 with it and I can confirm that it does work as desired, the full URI gets propagated to the squid `server` independently of the protocol used by the client 👍
