### ISSUE TITLE
couple null pointer dereference suspected by cppcheck

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1940]
### Tool Name and Version

cppcheck

### Code Report

```plain
src/auth.c:273:34: warning: Either the condition 'ep' is redundant or there is possible null pointer dereference: ep. [nullPointerRedundantCheck]
src/pool.c:303:54: warning: Either the condition '!pool' is redundant or there is possible null pointer dereference: pool. [nullPointerRedundantCheck]
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment]
src/auth.c:

ep is always assigned, but crypt() and crypt_r() functions could return NULL on failure depending on libc implementation, so we better keep this way for portability reasons.

As for the possible pointer de-reference, I guess cppcheck refers to this:
```c
233:#ifdef DEBUG_AUTH
233:        fprintf(stderr, ", crypt=%s\n", ep);
233:#endif
```
Maybe we could add an extra check before the fprintf call, although in practice
it shouldn't be a big deal if ep is NULL: printf implementations often check for NULL string pointers when dealing with `"%s"` fmt.

src/pool.c:
```c
if (!pool) {
    /* ... */
    /* always provide an aligned pool */
    pool = (struct pool_head*)((((size_t)pool_addr) + __alignof__(*pool)) & -(size_t)__alignof__(*pool));
    /* ... */
}
pool->users++;
```

Could you please try to check if commenting out ```pool->users++;``` and running cppcheck again removes the warning?
If so, my guess is that cppcheck does not correctly track `pool` assignments and this is a false positive.

**Comment by chipitsine** [comment]
I did search on `Either the condition` (most useful cppcheck finding), so brief report contains only single line.

sure, there are detailed reports as well

auth.c:

```
Checking src/auth.c: DEBUG_AUTH...
src/auth.c:273:34: warning: Either the condition 'ep' is redundant or there is possible null pointer dereference: ep. [nullPointerRedundantCheck]
 fprintf(stderr, ", crypt=%s\n", ep);
                                 ^
src/auth.c:276:6: note: Assuming that condition 'ep' is not redundant
 if (ep && strcmp(ep, u->pass) == 0)
     ^
src/auth.c:273:34: note: Null pointer dereference
 fprintf(stderr, ", crypt=%s\n", ep);
                                 ^
```


pool.c:

```
src/pool.c:303:54: warning: Either the condition '!pool' is redundant or there is possible null pointer dereference: pool. [nullPointerRedundantCheck]
  pool_addr = calloc(1, sizeof(*pool) + __alignof__(*pool));
                                                     ^
src/pool.c:300:6: note: Assuming that condition '!pool' is not redundant
 if (!pool) {
     ^
src/pool.c:303:54: note: Null pointer dereference
  pool_addr = calloc(1, sizeof(*pool) + __alignof__(*pool));
                                                     ^
```


while cppcheck is somewhat naive compared to coverity, sometimes it catches real issues.
if you are interested in reviewing it's findings, I can share details how to run it:

```
cppcheck --force --enable=all .
```

**Comment by chipitsine** [comment]
I'll check whether commenting helps or not today

**Comment by Darlelet** [comment]
Thanks for the full report Ilya!

> I'll check whether commenting helps or not today

No need to, the last cppcheck output you provided is enough: pool report is also false positive.
Cppcheck complains about ```__alignof__(*pool)```
but it is fine here because `alignof`, like `sizeof`, is evaluated at compile time.

Only `src/auth.c` could be addressed with "ep" checked against null before calling printf(), but as I mentioned, printf should be fine with a NULL string pointer in most cases.

**Comment by chipitsine** [comment]
thanks for review, looks like it should be reported/fixed on cppcheck side.

**Comment by chipitsine** [comment]
I attached full cppcheck report (easy to get one by running `cppcheck --force --enable=all .`) just in case if there's something useful

https://gist.github.com/chipitsine/98cf507a5a4ceb62328dd3c9e5f7e82b

**Comment by Darlelet** [comment]
> I attached full cppcheck report (easy to get one by running cppcheck --force --enable=all .) just in case if there's something useful

Thanks, nothing caught my attention so far, but I didn't spend that much time analyzing it to be honest because it is quite dense.

> Only src/auth.c could be addressed with "ep" checked against null before calling printf(), but as I mentioned, printf should be fine with a NULL string pointer in most cases.

Here is a fix:
[0001-MINOR-auth-possible-null-dereference-in-check_user.patch.txt](https://github.com/haproxy/haproxy/files/10083151/0001-MINOR-auth-possible-null-dereference-in-check_user.patch.txt)

**Comment by chipitsine** [comment]
Yep, I'm planning to report auth.c to cppcheck soon

**Comment by wtarreau** [comment]
In fact we already have other cases where some printf("%s") are passed NULLs. This is generally not a big problem but it's at least ugly to see "(null)".

**Comment by wtarreau** [comment]
Aurélien, I'm going to take the patch right now, but I'll slightly adjust the commit message since there's no null deref, just a suspicion by the checker.

**Comment by Darlelet** [comment]
Yeah sure!

**Comment by wtarreau** [comment]
That's now merged. For the other one regarding the pool, I agree with Aurélien, the problem is the checker not being aware of alignof() and thinking that pool is being dereferenced while it's not the case at all, so this one can safely be ignored (just like any involving sizeof and alignof in general).

Thank you guys! Ilya feel free to close when you want.

**Comment by chipitsine** [comment]
I reported to cppcheck: https://trac.cppcheck.net/ticket/11401#ticket

as for null check, I think it might be better to check for null

**Comment by chipitsine** [comment]
alignof was fixed on cppcheck
https://trac.cppcheck.net/changeset/52264b9c2600163155f89683e0c0e289d55e6799/

@Darlelet , if you don't mind, I'll give cppcheck more spin to see what it finds and how to deal with findings.
maybe we'll add it to pipeline sometimes

**Comment by wtarreau** [comment]
Oh that's cool!

**Comment by Darlelet** [comment]
Nice!

@chipitsine Sure, go ahead!

**Comment by chipitsine** [comment]
I'll start with 'error:' findings on 'src' folder first
