### ISSUE TITLE
HAProxy 2.4.19: 502 Bad Gateway Exception for Websockets over h2 / http/1.1

### ISSUE THREAD

**Issue by mikeblum** [haproxy/haproxy#1944]
### Detailed Description of the Problem

After upgrading from `2.3.14-alpine` to `2.4.19-alpine` it appears our websocket backends are now throwing `502 Bad Gateway` exceptions. Downgrading back to `2.3` resolves the issue.

```
xx.xx.xxx.xx:1234 [22/Nov/2022:20:20:59.580] waf~ backend-websocket-test/srv3 0/0/2/-1/22 502 6369 - - PHNN 23/23/13/0/0 0/0 {example.com|curl/7.79.1|xxx.xx.xx.xx} "GET /websocket HTTP/1.1"
xx.xx.xxx.xx:1234 [22/Nov/2022:21:33:10.799] waf~ backend-websocket-test/srv1 0/0/0/-1/15 502 6098 - - PHNN 26/26/0/0/0 0/0 {example.com|curl/7.79.1|24.12.177.15} "GET /websocket HTTP/1.1"
```

### Expected Behavior

Specifying `alpn http/1.1 ws h1` should ignore `h2` websocket support and mimic the haproxy `2.3` behavior.

### Steps to Reproduce the Behavior

```
curl \
    -v -i \
    --http1.1 \
    --include \
    --no-buffer \
    --header "Connection: upgrade" \
    --header "Upgrade: websocket" \
    --header "Sec-WebSocket-Key: RpO/IPC3YMbl/1ditEzV7w==" \
    --header "Sec-WebSocket-Version: 13" \
    https://example.com/websocket
```

returns:

```
* ALPN, offering http/1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
HTTP/1.1 101
```

vs

```
curl \
    -v -i \
    --include \
    --no-buffer \
    --header "Connection: upgrade" \
    --header "Upgrade: websocket" \
    --header "Sec-WebSocket-Key: RpO/IPC3YMbl/1ditEzV7w==" \
    --header "Sec-WebSocket-Version: 13" \
    https://example.com/websocket
```

returns:

```
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
HTTP/2 400
Can "Upgrade" only to "WebSocket".*
```

Using the `2.3` backend below with HAProxy `2.4` exhibits the `502 Bad Gateway` behavior:

```
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 502
HTTP/2 502
< date: Tue, 22 Nov 2022 21:33:10 GMT
date: Tue, 22 Nov 2022 21:33:10 GMT
< content-type: text/html
content-type: text/html
< content-length: 107
content-length: 107
< cache-control: no-cache
cache-control: no-cache

<
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

Based on the error codes seems like it could be related to [tune.http.maxhdr](https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#3.2-tune.http.maxhdr) and why changing from `add-header` to `set-header` seems to have changed the exception from a `502 Bad Gateway` to a `400 Bad Request`.

### Do you have any idea what may have caused this?

Seems like this issue is related to https://github.com/haproxy/haproxy/issues/1364

### Do you have an idea how to solve the issue?

In an attempt to get back to the `2.3` behavior we added the following `global`:

`h2-workaround-bogus-websocket-clients`

and added `alpn http/1.1` to the websocket backend (also tried `alpn http/1.1,h2 ws h1`)

both of these features were backported to `2.4`:

https://www.haproxy.com/blog/announcing-haproxy-2-4/#http-2-websockets

https://www.haproxy.com/blog/announcing-haproxy-2-5/#disable-bootstrapping-websockets-with-http-2-for-newer-browsers

### What is your configuration?

```haproxy
global
    maxconn 50000
    crt-base /etc/ssl/certs
    log stdout format raw local0 debug
    ssl-default-bind-options ssl-min-ver TLSv1.2
    stats socket /var/run/haproxy/haproxy-24.sock mode 0660 level admin
    stats socket ipv4@0.0.0.0:9000 level admin
    stats timeout 30s
    tune.ssl.default-dh-param 2048
    h2-workaround-bogus-websocket-clients
    master-worker
    daemon

defaults
    balance         leastconn
    default-server  inter 2s fall 3 rise 2 maxconn 2000
    log             global
    mode            http
    option          httplog
    option          dontlognull
    option          idle-close-on-response 
    option          forwardfor
    option          redispatch
    retries         3

    timeout connect         10s
    timeout client           5m
    timeout server           5m

    timeout tunnel           1h
    timeout queue           30s
    timeout tarpit          60s

frontend waf
    bind *:8443 ssl crt /etc/ssl/certs/fullchain-private.pem

    # CORS support
    http-request set-header X-Forwarded-Proto https

    # XSS / Content headers
    http-response set-header X-Frame-Options SAMEORIGIN
    http-response set-header X-Content-Type-Options nosniff
    http-response set-header X-XSS-Protection "1; mode=block"
    http-response set-header Referrer-Policy no-referrer-when-downgrade
    http-response set-header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload;"

    http-request capture req.hdr(Host) len 100
    http-request capture req.hdr(User-Agent) len 150
    http-request capture req.hdr(X-Forwarded-For) len 15

    acl acl-websocket path_beg /websocket
    acl acl-connection-upgrade hdr(Connection)  -i upgrade
    acl acl-upgrade-websocket  hdr(Upgrade)     -i websocket

    use_backend %[req.hdr(Host),lower,map(/usr/local/etc/haproxy/websocket.map)] if acl-connection-upgrade acl-upgrade-websocket acl-websocket
    use_backend %[req.hdr(Host),lower,map(/usr/local/etc/haproxy/backend.map)]
```

## haproxy 2.3 websocket backend:

```
backend backend-websocket-test
    balance roundrobin

    cookie SRV insert indirect nocache maxidle 30m maxlife 8h dynamic
    dynamic-cookie-key test
    http-request add-header Upgrade websocket
    http-request add-header Connection upgrade
    server-template srv 1-3 _api._env=test.service.consul resolvers consul resolve-prefer ipv4 check init-addr none
```

## haproxy 2.4 websocket backend:

```
backend backend-websocket-test
    mode    http
    option  logasap
    balance roundrobin

    cookie SRV insert indirect nocache maxidle 30m maxlife 8h dynamic
    dynamic-cookie-key test
    http-request set-header Upgrade websocket
    http-request set-header Connection upgrade
    server-template srv 1-3 _api._env=test.service.consul resolvers consul resolve-prefer ipv4 check init-addr none alpn http/1.1 ws h1
```

we also tried adding the `alpn` to the :bind but didn't see any changes so we reverted:

```
frontend waf
-    bind *:8443 ssl crt /etc/ssl/certs/fullchain-private.pem
+    bind *:8443 ssl crt /etc/ssl/certs/fullchain-private.pem alpn h2,http/1.1
```

### Output of `haproxy -vv`

```
/ $ haproxy -vv
HAProxy version 2.4.19-ec55434 2022/09/28 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.19.html
Running on: Linux 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1s  1 Nov 2022
Running on OpenSSL version : OpenSSL 1.1.1s  1 Nov 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.2.1 20220219

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Additional Information

We use an AWS Application Load Balancer to front our HAProxy servers to the public internet

- http/2 is enabled and works for all of our non-websocket requests
- ALB sticky sessions are disabled in favor of a HAProxy-defined SRV cookie

```
http-request set-header Upgrade websocket
http-request set-header Connection upgrade
```

is needed because some of our clients' firewalls and network rules maim these headers.

**Comment by a-denoyelle** [comment]
> ```
> curl \
>     -v -i \
>     --include \
>     --no-buffer \
>     --header "Connection: upgrade" \
>     --header "Upgrade: websocket" \
>     --header "Sec-WebSocket-Key: RpO/IPC3YMbl/1ditEzV7w==" \
>     --header "Sec-WebSocket-Version: 13" \
>     https://example.com/websocket
> ```
> 
> returns:
> 
> ```
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
> * ALPN, server accepted to use h2
> HTTP/2 400
> Can "Upgrade" only to "WebSocket".*
> ```
> 

I'm not sure I fully understand the issue. At least, this curl output shows that HTTP/2 has been chosen so you should have an `alpn h2` on the bind line. However, connection-specific headers such as `connection` or `upgrade` are not allowed in HTTP/2. In fact, to open a websocket in HTTP/2, you have to use the Extended CONNECT method as specified in the dedicated RFC8441 https://datatracker.ietf.org/doc/html/rfc8441.

**Comment by mikeblum** [comment]
To clarify we're trying to force all websocket traffic to use `http/1.1` as it did in `haproxy 2.3`. The issue is even with adding:

```
global
    h2-workaround-bogus-websocket-clients
```

and `alpn http/1.1 ws h1` to the `server-template`:

`server-template srv 1-3 _api._env=test.service.consul resolvers consul resolve-prefer ipv4 check init-addr none alpn http/1.1 ws h1`

`curl`ing `/websocket` selects `h2` regardless.

https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#3.1-h2-workaround-bogus-websocket-clients says for websockets to downgrade to `http/1.1` the `alpn` should include `h2`?

> To allow clients to automatically downgrade to http/1.1 for the websocket tunnel, specify h2 support on the bind line using "[alpn](https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#)" without an explicit "[proto](https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#)" keyword.

I think the issue here is that specifying both `h2-workaround-bogus-websocket-clients` and `alpn http/1.1` doesn't alter what HAProxy is advertising.

i'll see if adding `proto h1` forces traffic to use `http/1.1`

**Comment by a-denoyelle** [comment]
I'll try to clarify the situation.

curl does not fully support websocket via its command-line tool. You can simulate it in HTTP/1.1 which should return a `101 Switching protocols` response. But curl has no idea that you want to use websocket, instead if just craft a request with the headers you specified. If your haproxy bind line advertises h2 via alpn, curl will try to use it even though `upgrade` and `connection` headers are invalid with it : this is not related to websocket.

I suggest you to test your web application with a browser such as firefox or chrome. `h2-workaround-bogus-websocket-clients` is useful in this context : this will allow the browser to use or not H2 for the websocket tunnel.

All of this concerns the frontend side of haproxy. Now, on your issue you seem to think that there is problem with the backend side. If you want to use HTTP/1.1, just declare a server without `proto` keyword and it should be enough. Also, on your config, I saw server lines with `alpn` but without SSL : this has no effect.

**Comment by mikeblum** [comment]
Agreed that `curl` is a dubious tool here for diagnosing websocket issues. From the replication steps specifying `--http1.1` returns the expected `HTTP/1.1 101`. Reviewing the load balancer logs all of our websocket traffic (and 99% of traffic in general) is over `http1.1`.

The new websocket h2 support in `haproxy 2.4` made me think that was the issue between `2.3` and `2.4`.

https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#3.2-tune.http.maxhdr seems like it might be the source of the `400 Bad Request` as well as `502 Bad Gateway` for this small subset of traffic trying to open websocket connections - they all have a `PHNN` error code and the latest user-agents / browser versions which led me to think `h2-workaround-bogus-websocket-clients` might be the issue as we don't see this situation using `haproxy 2.3`.

There seems to be a bad gateway issue only in `2.4` when I have:

```
    http-request set-header Upgrade websocket
    http-request set-header Connection upgrade
```

Should i raise `tune.http.maxhdr`?

**Comment by a-denoyelle** [comment]
> There seems to be a bad gateway issue only in `2.4` when I have:
> 
> ```
>     http-request set-header Upgrade websocket
>     http-request set-header Connection upgrade
> ```

Are you sure you need these statements ? Because if these headers are sent do a non-websocket endpoint, the HTTP server will probably close the connection which will result in a 502 response from haproxy.

**Comment by mikeblum** [comment]
We have separate backends for http vs websockets and add these headers for clients that strip these headers. Previously in `2.3` we had:

```
 http-request add-header Upgrade websocket
 http-request add-header Connection upgrade
```

**Comment by mikeblum** [comment]
Could the problem be that in `2.4` the `Sec-WebSocket-Key` header is now required? [ Error 400 on HTTP/1.1 Websocket Connection Upgrade v2.4+ #1642](https://github.com/haproxy/haproxy/issues/1642#issuecomment-1092499676) I've removed the `set-header` and see the same `400 Bad Request` errors now that we're no longer artificially fixing the websocket headers. 

I think in the `2.4` changelog

> MINOR: h1: reject websocket handshake if missing key

is the change?

**Comment by mikeblum** [comment]
closing this issue since this appears to be expected behavior in `2.4`

**Comment by netsupcloud** [comment]
its interesting how you can release this bug easy like that and it is there it means haproxy is useless? and there no accurate users for it ?

nginx will correctly reverse proxy websocket connections but haproxy will give 400 error:

```
/etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    option http-server-close
#    option h2-workaround-bogus-websocket-clients
#    option h1-case-adjust-bogus-client
#    option http-use-htx
    log global
    option httplog
    option logasap

    # Define ACLs for WebSocket requests (Upgrade: websocket header)
    acl is_websocket hdr(Upgrade) -i websocket
    acl is_upgrade hdr(Connection) -i upgrade

    # WebSocket path routing
    use_backend service_cgws if path_cgws is_websocket is_upgrade

backend service_cgws
    mode http
    log global
    server cgws 127.0.0.1:180
    timeout connect 5s
    timeout server 1m
    option http-server-close
    option forwardfor
    http-request set-header X-Forwarded-For %[src]

HAPROXY as reverse proxy result:
curl -v -H "Upgrade: websocket" -H "Connection: Upgrade" http://127.0.0.1:80/cgws
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /cgws HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.76.1
> Accept: */*
> Upgrade: websocket
> Connection: Upgrade
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad request
< Content-length: 90
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
<
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
* Closing connection 0


---------------------------------------------------------------------------------------------------
NGINX as reverse proxy result:
curl -v -H "Upgrade: websocket" -H "Connection: Upgrade" http://127.0.0.1:80/cgws
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /cgws HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.76.1
> Accept: */*
> Upgrade: websocket
> Connection: Upgrade
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 Switching Protocols
< Server: nginx
< Date: Sat, 22 Feb 2025 09:55:15 GMT
< Connection: upgrade
< Upgrade: websocket
<
^C
```

this default install dnf in haproxy -y on centos 9 stream version 2.4.22
also i tried manual instal from source 3.1.5 and result was same
