### ISSUE TITLE
Support arbitrary PROXY protocol v2 TLVs as samples

### ISSUE THREAD

**Issue by CrawX** [haproxy/haproxy#1947]
### Your Feature Request

Hi all,

We're currently using haproxy as the central ingress point for our traffic.
We are routing the traffic to specific applications instances via SNI. Optionally, we also IP allowlist on backend level.
This configuration looks something like this:
```
    acl network_allowed src -f "/etc/haproxy/allowlists/001"
    acl network_allowed src 0.0.0.0/0
    tcp-request content reject unless network_allowed
```

Since we want to integrate AWS PrivateLink and Azure Private Link, we're trying to replace this acl with one based on information available in PROXY protocol v2 TLVs. [AWS](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol) and [Azure](https://learn.microsoft.com/en-us/azure/private-link/private-link-service-overview#getting-connection-information-using-tcp-proxy-v2) (and likely others) support the PROXY protocol v2 in their load balancers and provide unique identifiers (VPC Endpoint ID (AWS) and Private Endpoint Link ID (Azure)) which could replace the IP in allowlisting.

haproxy seems to already support various PROXY protocol v2 TLVs as samples, eg [fc_pp_authority](https://docs.haproxy.org/2.6/configuration.html#7.3.3-fc_pp_authority). It understandably doesn't support the AWS or Azure-specific TLVs I mentioned above (or other TLVs in the CUSTOM range).

I've looked into how this could be integrated with haproxy and found that it could potentially be done similarly to how [capturing](http://docs.haproxy.org/2.6/configuration.html#4-capture%20request%20header) and [retrieving](http://docs.haproxy.org/2.6/configuration.html#capture.req.hdr) is done for HTTP headers: one capture that specifies which TLV type and (optionally) subtype to capture with what length and a fetch that allows to fetch the _n_-th capture.

I tried to implement this and went the following route:
I added some fields into the `proxy` struct (analogous to `nb_req_cap`, `req_cap` etc), parsed these directives in `cfg_parse_listen` (similar to `capture request header`), added an array of the captured values to the `connection` struct (analogous to `req_cap` in `stream`) and then looped over that configuration in the `default` case of the tlv-`switch` in `conn_recv_proxy`.  I matched the values and wrote the results into the array in the `connection` struct. A new fetch (similar to `smp_fetch_capture_req_hdr`) then retrieved the value from the `connection` struct.

I was then able to start server like this
```
defaults
    mode http

frontend echo
    bind "*:5443" accept-proxy
    # capture proxyprotocolv2 tlv <type> <subtype or -1> len <maximum length>
    capture proxyprotocolv2 tlv ea 1 len 25
    capture proxyprotocolv2 tlv ea 3 len 33
    capture proxyprotocolv2 tlv ef -1 len 29
    capture proxyprotocolv2 tlv ee 1 len 4
    http-after-response set-header echo1 %[capture.pp2.tlv(0)]
    http-after-response set-header echo2 %[capture.pp2.tlv(1)]
    http-after-response set-header echo3 %[capture.pp2.tlv(2)]
    http-after-response set-header echo4 %[capture.pp2.tlv(3)]
    http-request return status 200
```
which captured the values as expected and set them in the http response.

While it worked nicely, it is probably far from complete since I've never worked with the haproxy source so far.
My questions are the following:
* is this use case something that would make sense to be integrated into haproxy?
* what could an acceptable solution look like?
* could a possible solution look similar to what I outlined above?

Thanks!
@CrawX, @happytobi

### What are you trying to do?

Refer to information contained in custom PROXY protocol v2 TLVs in acls to allowlist based on these values.

### Output of `haproxy -vv`

```plain
HAProxy version 2.7-dev8-ba3228-14 2022/10/26 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
Usage : haproxy [-f <cfgfile|cfgdir>]* [ -vdVD ] [ -n <maxconn> ] [ -N <maxpconn> ]
        [ -p <pidfile> ] [ -m <max megs> ] [ -C <dir> ] [-- <cfgfile>*]
        -v displays version ; -vv shows known build options.
        -d enters debug mode ; -db only disables background mode.
        -dM[<byte>,help,...] debug memory (default: poison with <byte>/0x50)
        -V enters verbose mode (disables quiet mode)
        -D goes daemon ; -C changes to <dir> before loading files.
        -W master-worker mode.
        -q quiet mode : don't display messages
        -c check mode : only check config files and exit
        -cc check condition : evaluate a condition and exit
        -n sets the maximum total # of connections (uses ulimit -n)
        -m limits the usable amount of memory (in MB)
        -N sets the default, per-proxy maximum # of connections (0)
        -L set local peer name (default to hostname)
        -p writes pids of all children to this file
        -dC[[key],line] display the configuration file, if there is a key, the file will be anonymised
        -dk disables kqueue() usage even when available
        -dp disables poll() usage even when available
        -dG disables getaddrinfo() usage
        -dR disables SO_REUSEPORT usage
        -dK{class[,...]} dump registered keywords (use 'help' for list)
        -dr ignores server address resolution failures
        -dV disables SSL verify on servers side
        -dW fails if any warning is emitted
        -dD diagnostic mode : warn about suspicious configuration statements
        -sf/-st [pid ]* finishes/terminates old pids.
        -x <unix_socket> get listening sockets from a unix socket
        -S <bind>[,<bind options>...] new master CLI
```
```

**Comment by wtarreau** [comment]
Hello,

thanks to the work done by @alexanderstephan we now have this new ability in latest 2.9-dev if you want to give it a try.

**Comment by alexanderstephan** [comment]
@wtarreau Thanks for all your support! I guess this issue can be closed now?

**Comment by wtarreau** [comment]
Oh yes, absolutely! Thanks Alexander for your work!
