### ISSUE TITLE
keep default weight or custom weight if weight is not set in SRV records

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxy/haproxy#195]
Maybe it is good to apply the default weight also. When SRV records return 0?

This works
`server-template webchat 2 _webchat._tcp.marathon.mesos weight 100 resolve-opts allow-dup-ip`

This sets weight to 1
`server-template webchat 2 _webchat._tcp.marathon.mesos resolve-opts allow-dup-ip`

```
[@ mesos-cni]# dig +short @192.168.10.151 _webchat._tcp.marathon.mesos SRV
0 0 8181 webchat-jygxm-s1.marathon.mesos.
0 0 8181 webchat-h3q8o-s1.marathon.mesos.
```

haproxy 2

**Comment by wtarreau** [comment]
Could you please try to describe what you're trying to achieve first ? It may surprise you that I don't understand anything about your feature request, but that's the reality. Please keep in mind that if nobody is interested in deciphering it it will hardly make progress.

**Comment by f1-outsourcing** [comment]
> 
> 
> Could you please try to describe what you're trying to achieve first ? It may surprise you that I don't understand anything about your feature request, but that's the reality. Please keep in mind that if nobody is interested in deciphering it it will hardly make progress.

are you using haproxy? or are you some github robot?

**Comment by wtarreau** [comment]
That's the question I was thinking about you given that you can't seem to make sentences. No I have the confirmation.
