### ISSUE TITLE
(cppcheck)  src/debug.c: Comparing pointers that point to different objects

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1951]
### Tool Name and Version

cppcheck

### Code Report

```plain
this is review task to determine how to address the next cppcheck finding:


src/debug.c:1266:39: error: Comparing pointers that point to different objects [comparePointers]
   for (ptr = &__start_mem_stats; ptr < &__stop_mem_stats; ptr++) {
                                      ^
src/debug.c:1253:52: note: Variable declared here.
 extern __attribute__((__weak__)) struct mem_stats __start_mem_stats;
                                                   ^
src/debug.c:1266:15: note: Address of variable taken here.
   for (ptr = &__start_mem_stats; ptr < &__stop_mem_stats; ptr++) {
              ^
src/debug.c:1254:52: note: Variable declared here.
 extern __attribute__((__weak__)) struct mem_stats __stop_mem_stats;
                                                   ^
src/debug.c:1266:41: note: Address of variable taken here.
   for (ptr = &__start_mem_stats; ptr < &__stop_mem_stats; ptr++) {
                                        ^
src/debug.c:1266:39: note: Comparing pointers that point to different objects
   for (ptr = &__start_mem_stats; ptr < &__stop_mem_stats; ptr++) {
                                      ^
```

### Output of `haproxy -vv`

```plain
code only issue
```

**Comment by Darlelet** [comment]
```__start_*``` and ```__stop_*``` prefixes are used to access ELF sections at link time, this is some low-level stuff here and my guess is that cppcheck is not aware of it, but we can't blame it for that: this really is marginal use and hard to track down actually.

**Comment by chipitsine** [comment]
shall we open an issue on cppcheck for that ? generally, there's no good suppression mechanism for cppcheck

**Comment by Darlelet** [comment]
To add some context: `mem_stats` section is fed by bug.h macro replacements for memory-allocating functions (like malloc,strdup..) when haproxy is compiled with `DEBUG_MEM_STATS`.

This way "debug dev memstats" can produce ordered and meaningful memory usage dumps thanks to hints stored within the `mem_stats` section.

**Comment by chipitsine** [comment]
can be a good indicator to (for cppcheck) to ignore `extern` variables ?

**Comment by Darlelet** [comment]
> shall we open an issue on cppcheck for that ? generally, there's no good suppression mechanism for cppcheck

I guess it's always a good idea to let them know about it at least (even if they can't come up with a quick-fix)

Just out of curiosity, if I understand right, there's no way to tell cppcheck to ignore some code paths: ifdef guards are ignored?

**Comment by chipitsine** [comment]
if that makes sense, I'll open an issue on cppcheck.

you are right, we cannot teach cppcheck to ignore "extern" ourselves (unless we provide a patch)

**Comment by chipitsine** [comment]
from what I see in documentation, neither cppcheck, nor c compiler should take care of "extern" variables.
@Darlelet , do "extern" variables look as what should be ignored by analyzers ?

**Comment by Darlelet** [comment]
@chipitsine I'm not sure ignoring "extern" variables would be a good idea. While it should fix this warning, it would prevent cppcheck to perform well on any extern variable. The fact that it is extern or not should not be an issue for compilers/analyzers.

Here what's actually confusing for the analyzer is that `__start_XXX` and `__stop_XXX` symbols are dynamic: they are not resolved by the analyzer itself (cppcheck is a static code analyzer) nor by the compiler. Such resolution is expected to be performed by the linker. 

Perhaps cppcheck should ignore known linker-provided symbols instead, if that's something technically doable on their side..

**Comment by shipitsin-ilia** [comment]
excluding dynamic properties for static analyzers make sense (at least for me).
do we have some source of such dynamic properties ? at least those _start_xxx, __stop_xxx

**Comment by shipitsin-ilia** [comment]
I reported on cppcheck side https://trac.cppcheck.net/ticket/11419

however, when I google for those properties, I see only haproxy on search results. I'm curious where are them documented.

**Comment by Darlelet** [comment]
Thank you Ilya

Yes indeed with `__start_mem_stats` chances are high that you will only find haproxy related results.
(Because `mem_stats` part is custom name chosen by haproxy developers)

`__start_xxx`/`__stop_xxx` or "custom elf section" and  will give you more results.

This is really marginal use and unfortunately I'm not aware of an "official" documentation for this.

Source is mostly mailing lists, gcc/ld source code and linux kernel source code (ie: linux kernel initcalls, which seems to have inspired haproxy initcalls implementation that relies on this property as well, see: d13a9281bd45df2f25d64545ec6cc14298970818)

**Comment by Darlelet** [comment]
FYI: Here is an interesting write-up on this topic: https://mgalgs.io/2013/05/10/hacking-your-ELF-for-fun-and-profit.html

While it is not an official content, it helps understanding how this works under the hood.

Here are additional references:
- https://www.mail-archive.com/bug-binutils@gnu.org/msg05811.html
- https://gcc.gnu.org/legacy-ml/gcc-help/2014-04/msg00165.html
- https://reviews.llvm.org/D13760?id=37494
- GNU binutils/ld manual (search for `__start_SECNAME` and `__stop_SECNAME`)

**Comment by shipitsin-ilia** [comment]
there are comments from cppcheck developers

https://trac.cppcheck.net/ticket/11419#comment:3

**Comment by Darlelet** [comment]
It seems like we need to be more precise to make it less confusing:

From what I can tell, issue is not related to `__` prefix nor `extern` keyword, it is directly related to `__start_` and `__stop_` prefixed symbols that may indicate custom ELF section lookups (resolved at link time) for a section previously defined using the `__section__()` variable attribute under GNU gcc+ld/gold or llvm.

Excerpt from binutils/ld manual:

>If an output section’s name is the same as the input section’s name and is representable as a C identifier, then the linker will automatically PROVIDE two symbols: __start_SECNAME and __stop_SECNAME, where SECNAME is the name of the section. These indicate the start address and end address of the output section respectively. Note: most section names are not representable as C identifiers because they contain a ‘.’ character.

https://sourceware.org/binutils/docs-2.39/ld/Input-Section-Example.html

It might be worth noting the additional references mentioned in my previous comment as well to provide more context/examples.
Despite its marginal use, refs clearly indicate that this feature is intended and used in various projects.

**Comment by Darlelet** [comment]
Daniel asked for minimal code that allows to reproduce the issue.

Chrchr example was fine but I reduced it further:

```c
#include <stdio.h>

struct my_str {
    char *name;
};

#define REGISTER_STR(_name)				\
    static struct my_str _				\
    __attribute((__section__("my_section")))		\
    __attribute((__used__)) = {				\
	.name = _name,					\
    }

REGISTER_STR("Test");

extern struct my_str __start_my_section;
extern struct my_str __stop_my_section;

int main(int argc, char *argv[])
{
    struct my_str *iter;

    for (iter = &__start_my_section ; iter < &__stop_my_section; ++iter) {
	printf("STR from my section: %s\n", iter->name);
    }

    return 0;
}
```

With latest cppcheck (`--force --enable=all`):

```shell
./cppcheck --force --enable=all ./lab
Checking lab/test.c ...
lab/test.c:23:44: error: Comparing pointers that point to different objects [comparePointers]
    for (iter = &__start_my_section ; iter < &__stop_my_section; ++iter) {
                                           ^
lab/test.c:16:22: note: Variable declared here.
extern struct my_str __start_my_section;
                     ^
lab/test.c:23:17: note: Address of variable taken here.
    for (iter = &__start_my_section ; iter < &__stop_my_section; ++iter) {
                ^
lab/test.c:17:22: note: Variable declared here.
extern struct my_str __stop_my_section;
                     ^
lab/test.c:23:46: note: Address of variable taken here.
    for (iter = &__start_my_section ; iter < &__stop_my_section; ++iter) {
                                             ^
lab/test.c:23:44: note: Comparing pointers that point to different objects
    for (iter = &__start_my_section ; iter < &__stop_my_section; ++iter) {
                                           ^
nofile:0:0: information: Cppcheck cannot find all the include files (use --check-config for details) [missingIncludeSystem]
```

**Comment by capflam** [comment]
I'm closing now because it is not related to haproxy. Thanks guys !
