### ISSUE TITLE
Haproxy logs | severity level is not working 

### ISSUE THREAD

**Issue by dimakyriakov** [haproxy/haproxy#1961]
### Detailed Description of the Problem

Hello,
We are getting all logs from haproxy in /var/log/warn-haproxy.log log file. We set the severity level to "warning" in haproxy.cfg file:
`log localhost:514 local2 warning`
In rsyslog conf file we set next setting:
`local2.warning /var/log/warn-haproxy.log`

And we still getting all logs from haproxy:
![image](https://user-images.githubusercontent.com/96116626/207018111-046748ba-e7b9-4d40-a958-49516b28d2b8.png)

### Expected Behavior

Get logs with warning and above level

### Steps to Reproduce the Behavior

1. Set `log localhost:514 local2 warning` to haproxy.cfg file
2. Set `local2.warning /var/log/warn-haproxy.log` to rsyslog `49-haproxy.conf` file
3. restart rsyslog, reload haproxy.

### Do you have any idea what may have caused this?

I already tried different ways to achive expected result:
1. We tried to use `log /dev/log local0, log /dev/log local0 warning, log localhost:514 local2 warning, log localhost:514 local2` for haproxy
2. We tried to use `local2.warning /var/log/warn-haproxy.log, local2.* /var/log/warn-haproxy.log` and:
```
if $programname == "haproxy" then {
        /var/log/e-haproxy.log
        stop
}
```
Still getting all logs with all severity level

### Do you have an idea how to solve the issue?

No

### What is your configuration?

```haproxy
haproxy.cfg:

global
  daemon
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  master-worker
  nbproc 1
  nbthread 5
  cpu-map auto:1/1-5 0-4
  maxconn 5000
  pidfile /var/run/haproxy.pid
  stats socket /var/lib/haproxy/stats
  stats socket /var/lib/haproxy/haproxy.stats level admin
  stats socket *:1999 level admin
  stats socket /var/run/haproxy.sock mode 600 level admin
  stats socket /var/run/haproxy.sock user haproxy group haproxy mode 660 level admin
  stats timeout 30s
  tune.ssl.default-dh-param 2048
  log localhost:514 local2 warning
  #log /dev/log local0 warning
  #log /dev/log local1 notice
  #log stdout format raw local0 info
  #log stderr format raw local0 info
  ssl-server-verify none
  crt-base /etc/haproxy/certs
  tune.ssl.cachesize 1000000

defaults
  mode tcp
  maxconn 3000
  log global
  log-format "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq"
  option httplog
  option redispatch
  option dontlognull
  option log-separate-errors
  ...

49-haproxy.conf:

# Create an additional socket in haproxy's chroot in order to allow logging via
# /dev/log to chroot'ed HAProxy processes
$AddUnixListenSocket /var/lib/haproxy/dev/log
$ModLoad imudp
$UDPServerAddress 127.0.0.1
$UDPServerRun 514
# Send HAProxy messages to a dedicated logfile

#if $programname == "haproxy" then {
#        /var/log/e-haproxy.log
#        stop
#}

local2.warning /var/log/warn-haproxy.log

#local0.err /var/log/haproxy.log
#& stop


#local1.* /var/log/haproxy.log
#& stop
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.0.13-1ppa1~bionic 2020/02/15 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-ooLwkU/haproxy-2.0.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

**Comment by git001** [comment]
Please update to the latest version and see if the issue is already fixed.  
Your version shows 542 fixes https://www.haproxy.org/bugs/bugs-2.0.13.html  

Maybe you can consider to update to the latest LTS version of 2.6

**Comment by capflam** [comment]
From what I can see, you have only errors in your logs. Because you've enable `log-separate-errors` option, errors are logged with LOG_ERR level instead of LOG_INFO. So it is expected.

**Comment by dimakyriakov** [comment]
> From what I can see, you have only errors in your logs. Because you've enable `log-separate-errors` option, errors are logged with LOG_ERR level instead of LOG_INFO. So it is expected.

Deleted `log-separate-errors` option and got the same result. It reporting NOTICE and info logs as well. Example: 
![image](https://user-images.githubusercontent.com/96116626/207322868-c6a3a2e8-0ac6-4e20-ab61-53126d4b7d96.png)
Rsyslog: `local2.warning /var/log/haproxy.log`
Haproxy: `log localhost:514 local2 warning`

It means that only upgrade version might help?

**Comment by TimWolla** [comment]
> It means that only upgrade version might help?

I'm not aware of any fix related to the issue you are seeing. But I strongly recommend you to upgrade to HAProxy 2.0.30 (the latest 2.0.x) at the very least. HAProxy 2.0.13 that you are running is almost 3 years old and affected by a CRITICAL security issue. As you are using the PPA, upgrading should be as simple as `apt upgrade`.

**Comment by capflam** [comment]
@dimakyriakov, In your logs extract, there is no longer messages about your traffic. Thus it works for this part. For messages about servers state, some are sent with LOG_NOTICE level but some others are sent with LOG_ALERT level. It depends on the server state. When the server is set to DOWN, if it was not previously paused, an alert is sent.  When all backend servers are down a message with LOG_EMERG level is sent. So, everything seems to work as expected.

**Comment by capflam** [comment]
It seems there is no issue. Can we close it ?

**Comment by dimakyriakov** [comment]
Thank you guys, closing the issue
