### ISSUE TITLE
HAproxy does not log anything for denied H2 requests

### ISSUE THREAD

**Issue by domdom82** [haproxy/haproxy#1968]
### Detailed Description of the Problem

- We have some clients that send very large headers
- For this we use `tune.bufsize` and `tune.maxrewrite`
- When a client exceeds bufsize - maxrewrite on a H1 request they get a 400 and HAproxy logs a denied request
- When a client exceeds 64k (regardless of bufsize) on a H2 request they get a REFUSED_STREAM but HAprxy logs nothing

### Expected Behavior

1. `tune.bufsize` should also affect H2 requests, or it should be clearly documented that this option is H1 only
2. if `tune.bufsize` can't be used with H2 requests, an alternative should be present (maybe `tune.h2.header-table-size`? unclear)
3. in any case, HAproxy should write a log statement if H2 streams get aborted. Otherwise operators have no clue what happened and why.

### Steps to Reproduce the Behavior

1. Deploy HAproxy (no backend needed, see config below)
2. Configure `tune.bufsize` to > 64k
3. Issue a 64k H1 request:
```
curl -k --http1.1 https://localhost:9443/ -H "$(cat 64k-header.txt)"
OK%
```
4. Issue a 80k H1 request:
```
curl -k --http1.1 https://localhost:9443/ -H "$(cat 80k-header.txt)"
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```
5. Observe a nice log statement in HAproxy:
```
Dec 15 15:39:10 dfbd1e79cd81 localhost haproxy[8]: 172.17.0.1:62848 [15/Dec/2022:15:39:10.365] (-) myfrontend~ myfrontend/<NOSRV> 11/3/-1/-1/-1/-1/15 400 0 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>" TLS_AES_256_GCM_SHA384 TLSv1.3 1 0 0 0 "" "" "localhost"
```
6. Now try a 64k H2 request: (this should work based on tune.bufsize)
```
curl -vk --http2 https://localhost:9443/ -H "$(cat 64k-header.txt)"
(...)
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* REFUSED_STREAM, retrying a fresh connect
* Connection died, tried 5 times before giving up
* Closing connection 5
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (56) Connection died, tried 5 times before giving up
```
7. Check HAproxy logs. No entry.
8. Now try a 80k H2 request. Same result.

### Do you have any idea what may have caused this?

I know it's technically an H2 stream and no HTTP response has been sent to the client. This is probably the hook where log statements are written, thus no log appears because there is no response / status code to set.

### Do you have an idea how to solve the issue?

HAproxy should at least write a log statement about the denied H2 request. This is critical for observability and customer tickets.

### What is your configuration?

```haproxy
global
  log /dev/log len 4096 format rfc3164 syslog info
  stats socket /var/run/haproxy.sock mode 600 expose-fd listeners level admin
  nbthread 4
  tune.bufsize 71000
  tune.maxrewrite 4096

defaults
  log global
  mode http
  timeout connect 5s
  timeout client 1h
  timeout server 5s

frontend myfrontend
  bind :443 ssl crt /etc/cert/server.pem alpn h2,http/1.1
  log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %Th/%Ti/%TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslc %sslv %[ssl_fc_has_sni] %[ssl_c_used] %[ssl_fc_has_crt] %[ssl_c_err] %{+Q}[ssl_c_s_dn] %{+Q}[ssl_c_i_dn] %{+Q}[ssl_fc_sni]"

  capture request header Host len 256
  capture request header User-agent len 256

  http-request return status 200 content-type text/plain string OK

```
```


### Output of `haproxy -vv`

```plain
HAProxy version 2.6.5-987a4e2 2022/09/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.5.html
Running on: Linux 5.10.124-linuxkit #1 SMP Thu Jun 30 08:19:10 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```
```


### Last Outputs and Backtraces

_No response_

### Additional Information

**Comment by domdom82** [comment]
- Here is a [pcap file](https://paste.c-net.org/RumbleMadly) that shows network traffic of a client trying to push a 64k H2 header to HAproxy and getting denied
- Here is the [keylog file](https://paste.c-net.org/TrailingWines) to decrypt the pcap traffic in Wireshark

**Comment by wtarreau** [comment]
That's a proto error, so I guess you've hit this check in the code, and it's reported at the upper layer in one of the various places where we try to decode partial headers frames:
```
		if ((unsigned)hdr.len > (unsigned)global.tune.bufsize) {
			/* RFC7540#4.2: invalid frame length */
			TRACE_STATE("too large frame!", H2_EV_RX_FRAME|H2_EV_RX_FHDR|H2_EV_RX_HDR|H2_EV_RX_CONT|H2_EV_H2C_ERR|H2_EV_PROTO_ERR, h2c->conn);
			h2c_error(h2c, H2_ERR_FRAME_SIZE_ERROR);
			goto fail;
		}
```

The difficulty here in H2 is that when you cannot decode, there's very little to say because we have no stream and the logs are quite poor. I applied the attached patch and am now getting this with your config:
```
<134>Dec 22 09:05:03 haproxy[11456]: 127.0.0.1:62224 [22/Dec/2022:09:05:03.267] (-) myfrontend myfrontend/<NOSRV> 0/0/-1/-1/-1/-1/0 0 0 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>" - - 0 - - - "" "" ""
```
Do you think that would be helpful in your case ? I'm not necessarily opposed to merging it, it's just that we have to balance when to log at lower layers because some logs could be exclusively pollution with almost no info. Here I admit that such events shouldn't happen often, so maybe it can be useful. Just let me know.
[patch-log-h2-hdr-fail.diff.txt](https://github.com/haproxy/haproxy/files/10284953/patch-log-h2-hdr-fail.diff.txt)

**Comment by domdom82** [comment]
@wtarreau I get your points. To us it is most helpful to have the source IP and the timestamp when the error occurred because we can then tell the customer that their request has at least reach HAproxy (and was not stopped by other systems in front). I agree, the info on the logs is minimal, but I wanted to see at least *some* log entry to know that HAproxy actually was involved. 
With such a log statement, we could tell the customer to do a tcpdump from their end, which would reveal the H2 issue, so I'd be happy to see it merged.

Once more thing: In the code piece you shared, the reason is clearly defined ("invalid frame length"), however there is currently no means to log that using a fetch (similar to TLS errors, e.g. `ssl_fc_err_str`). Do you think it is possible to add similar fetches for h2? e.g. `h2_fc_err_str` that could contain more details on why the h2 request was denied.

**Comment by wtarreau** [comment]
> With such a log statement, we could tell the customer to do a tcpdump from their end, which would reveal the H2 issue, so I'd be happy to see it merged.

OK thanks, will try to refine it a little bit and will merge it.

> Once more thing: In the code piece you shared, the reason is clearly defined ("invalid frame length"), however there is currently no means to log that using a fetch (similar to TLS errors, e.g. ssl_fc_err_str). Do you think it is possible to add similar fetches for h2? e.g. h2_fc_err_str that could contain more details on why the h2 request was denied.

It's more complicated actually. We're logging at the lower layers and there's no stream yet, so most of the operations that are normally performed to extract some elements using sample fetches will just be ignored. We could say "just retrieve it at the session level" but then we'd only get the last info at the connection level and here it's just one stream that is causing trouble. We can't have a single field to collect elements for all possibly bogus streams, as anyone would log any other stream's last status. It's a bit like if we had to purposely create a dummy stream just for the time of the log (that's more or less what H1 does) but inside a multiplexed connection it's a hell lot more hackish.

We're still constantly improving the internal API to try to better align layers and enforce certain guarantees that could allow to extract such a thing. For example maybe at some point it would become reasonable to consider that pointer X in the connection has a certain validity duration and may be used as the last error for currently parsed stream. But I don't think that in the current state that's feasible, due to this stream failing without having ever existed.

**Comment by craig** [comment]
FYI: there is another way to trigger PROTOCOL_ERROR without haproxy logging anything:

```
echo "cookie: 1" > header
curl -v -k --http2 https://localhost/test -H "$(cat header)"
```

-> Works against 2.8-dev0

```
curl -v -k --http2 https://localhost/test -H "$(cat header header)"
*   Trying localhost:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=localhost
*  start date: Jun  7 16:32:15 2022 GMT
*  expire date: Jul  9 16:32:14 2023 GMT
*  issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55cc7dcd62c0)
> GET /test HTTP/2
> Host: localhost
> user-agent: curl/7.74.0
> accept: */*
> cookie: 1
> cookie: 1
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* stopped the pause stream!
* Connection #0 to host localhost left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

There are no logs. This is a bit mean when you're under DDoS as an attacker can cause load by doing handshakes, but it's hard to see what's happening. 

@wtarreau, unfortunately I don't have time to test if this is fixed by your patch; it would be great if this and possibly any other error during the connection lifetime would always cause a log entry.

**Comment by wtarreau** [comment]
@craig thanks for the report, I'll try it as well. I suspect it should be addressed but it's easy for me to check thanks to your repro.

**Comment by wtarreau** [comment]
Finally found the time to test it. With the patch, your example above does produce a log as well:
```
<134>Jan 19 23:20:52 haproxy[17573]: 127.0.0.1:52296 [19/Jan/2023:23:20:52.444] (-) myfrontend myfrontend/<NOSRV> 0/0/-1/-1/-1/-1/0 0 0 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>" - - 0 - - - "" "" ""
```
I'm going to merge this.

**Comment by wtarreau** [comment]
Keeping older versions on hold for a moment (at least one version). Not sure if we'll go as far as 2.0 though.

**Comment by capflam** [comment]
Not backported to 2.0 because it is not a critical fix. I'm closing now.

**Comment by capflam** [comment]
Hum it was not backported to 2.4 and 2.2, I missed it I guess

**Comment by capflam** [comment]
Ok it is marked to backport it "progressively"...

**Comment by wtarreau** [comment]
Yeah I noticed ;-)
