### ISSUE TITLE
(cppcheck) src/cache.c: null pointer dereference suspected

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1969]
### Tool Name and Version

cppcheck

### Code Report

```plain
this is review task to determine how to address the next cppcheck finding:

src/cache.c:428:61: error: Null pointer dereference: (struct shared_context*)NULL [nullPointer]
 return (struct shared_context *)((unsigned char *)cache - ((struct shared_context *)NULL)->data);
                                                            ^
```

### Output of `haproxy -vv`

```plain
code only issue
```

**Comment by Darlelet** [comment]
It seems it was already included in your full report gist from #1940 (https://gist.github.com/chipitsine/98cf507a5a4ceb62328dd3c9e5f7e82b#file-gistfile1-txt-L777), I remember spending some time on this one.

And if I remember good, there is no issue here: it is tricky but will remain safe as long as `data` member is a char array (changing it to a pointer would indeed lead to pointer dereference).
```c
struct shared_context {
        /* [...] */
        unsigned char data[VAR_ARRAY];
};
```

**Comment by Darlelet** [comment]
`((struct shared_context *)NULL)->data)` will translate into `data` positional offset within struct `shared_context`

**Comment by chipitsine** [comment]
full report purpose was to fix what worth to be fixed.

now we evaluate findings one by one to either rewrite code or report it as false positive to cppcheck in order to get clean report once (if that will happen, we'll add it to automation)

**Comment by chipitsine** [comment]
what can be an algorithm for cppcheck to recognize this pattern as safe ?

**Comment by Darlelet** [comment]
No problem, I included the link for reference, and because it helped me remembering about it. 

Actually you are right, adding an extra `&` before `((struct shared_context *)NULL)->data)` would make it even safer in the event `data` is being changed to a pointer some day.

Like this: `&((struct shared_context *)NULL)->data)`

And it might as well silence the warning?

**Comment by chipitsine** [comment]
np, I'll check

**Comment by TimWolla** [comment]
@Darlelet Would `offsetof()` work here?

**Comment by Darlelet** [comment]
Yes it does, thank you for mentioning it!
To be honest I don't know why it was not used in the first place, could be for portability reasons?

Now that haproxy implements its own portable offsetof macro (928fbfa8b71b7486ea1a53d59bcd5c42887d5f7b), portability issues should not be a concern anymore and offsetof should be preferred here, I guess.

May this be part of a bigger cleanup?
```
grep -rn 'NULL)->'             
                              
src/ssl_sock.c:4497:	return (struct shared_block *)((unsigned char *)sh_ssl_sess - ((struct shared_block *)NULL)->data);
src/cache.c:428:	return (struct shared_context *)((unsigned char *)cache - ((struct shared_context *)NULL)->data);
src/cache.c:433:	return (struct shared_block *)((unsigned char *)entry - ((struct shared_block *)NULL)->data);
include/haproxy/list.h:94:#define LIST_ELEM(lh, pt, el) ((pt)(((const char *)(lh)) - ((size_t)&((pt)NULL)->el)))
include/haproxy/list.h:616:#define MT_LIST_ELEM(lh, pt, el) ((pt)(((const char *)(lh)) - ((size_t)&((pt)NULL)->el)))
```

**Comment by chipitsine** [comment]
adding `&` muted the detection

**Comment by wtarreau** [comment]
Indeed at minima the '&' is needed there, and offsetof() could be used, but actually it's more generally the various call places that would need to use cleaner accessors than just doing pointer calculation like this.

**Comment by shipitsin-ilia** [comment]
some rule for coccinelle ? maybe there's such rule somewhere?

**Comment by shipitsin-ilia** [comment]
I found very similar [ruleset](https://github.com/coccinelle/coccinellery/tree/master/offset)

it might be adopted to our case

**Comment by chipitsine** [comment]
resolved in https://github.com/haproxy/haproxy/commit/2ca01589a01baac6228465829c409192a61a5ea3
