### ISSUE TITLE
There is a code error in the function b_slow_realign

### ISSUE THREAD

**Issue by wkdzzb** [haproxy/haproxy#1978]
### Detailed Description of the Problem
```C
static inline void b_slow_realign(struct buffer *b, char *swap, size_t output)
{
	size_t block1 = output;
	size_t block2 = 0;

	/* process output data in two steps to cover wrapping */
	if (block1 > b_size(b) - b_head_ofs(b)) {
		block2 = b_size(b) - b_head_ofs(b);
		block1 -= block2;
	}
	memcpy(swap + b_size(b) - output, b_head(b), block1);
	memcpy(swap + b_size(b) - block2, b_orig(b), block2);
.....
}
```
if (block1 > b_size(b) - b_head_ofs(b)) is true, block1 is the length of the [xxxx|  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ] and block2 is the length of the [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |xxxx].

### Expected Behavior

Can correctly calculate the length of block1 and block2.

### Steps to Reproduce the Behavior

I'm just reading the code。

### What is your configuration?

```haproxy
none
```

### Output of `haproxy -vv`

```plain
master
```

**Comment by Darlelet** [comment]
I'm afraid of missing something out, could you please be more specific?

Do you mean that wrapping is improperly handled in the function?

**Comment by capflam** [comment]
Indeed, you're right, there is a bug. It was introduced when the buffer API was refactored. Here is the patch, I'll push it soon:
```diff
diff --git a/include/haproxy/buf.h b/include/haproxy/buf.h
index f2f003c15..417ff9c8e 100644
--- a/include/haproxy/buf.h
+++ b/include/haproxy/buf.h
@@ -467,7 +467,7 @@ static inline void b_slow_realign(struct buffer *b, char *swap, size_t output)
 
        /* process output data in two steps to cover wrapping */
        if (block1 > b_size(b) - b_head_ofs(b)) {
-               block2 = b_size(b) - b_head_ofs(b);
+               block2 = b_peek_ofs(b, block1);
                block1 -= block2;
        }
        memcpy(swap + b_size(b) - output, b_head(b), block1);
```

All versions as far as 2.0 are affected.

**Comment by wtarreau** [comment]
Indeed, good catch!

**Comment by capflam** [comment]
I pushed the fix. Thanks @wkdzzb !
