### ISSUE TITLE
"show ssl ca-file" always shows "@system-ca" after HAproxy 2.5

### ISSUE THREAD

**Issue by domdom82** [haproxy/haproxy#1979]
### Detailed Description of the Problem

Ever since HAproxy 2.6 the socket command "show ssl ca-file" returns "@system-ca" in the list of trusted CAs for client certificates. This is dangerous as it implies that all system CAs are trusted for client certificates connecting to HAproxy.

This also applies if another CA file was set explicitly in the haproxy.config file.

### Expected Behavior

- HAproxy should only accept the CA files set by the configuration.
- If no `ca-file` entry was given, "@system-ca" should not be implied. Instead, an empty list of CA files should be returned by the "show ssl ca-file" command.

### Steps to Reproduce the Behavior

1. Run the attached config with HAproxy 2.5.10 (or any 2.5.x release)
2. `echo "show ssl ca-file" | socat - /var/run/haproxy.sock`
3. The response should be
```
# filename
/client_ca_test_file.ca.pem - 1 certificate(s)
```
4. If you remove the `ca-file` entry from haproxy.config, the return should be an empty list:
```
# echo "show ssl ca-file" | socat - /var/run/haproxy.sock
<empty>
```
5. Now run the attached config with HAproxy 2.6.5, 2.6.7 or HAproxy 2.7.1 (possibly other 2.6.x and 2.7.x affected, too)
6. `echo "show ssl ca-file" | socat - /var/run/haproxy.sock`
7. The response will be
```
# filename
/client_ca_test_file.ca.pem - 1 certificate(s)
@system-ca - 129 certificate(s)
```
8. If you remove the `ca-file` entry from haproxy.config, it still returns the "@system-ca" entry:
```
# echo "show ssl ca-file" | socat - /var/run/haproxy.sock
# filename
@system-ca - 129 certificate(s)
```

Tested with docker images of HAproxy versions.

### What is your configuration?

```haproxy
global
  log /dev/log len 4096 format rfc3164 syslog info
  stats socket /var/run/haproxy.sock mode 600 expose-fd listeners level admin
  nbthread 4

defaults
  log global
  mode http
  timeout connect 5s
  timeout client 1h
  timeout server 5s

frontend myfrontend
  bind :443 ssl crt /etc/cert/server.pem ca-file /client_ca_test_file.ca.pem verify optional crt-ignore-err all ca-ignore-err all
  log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %Th/%Ti/%TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslc %sslv %[ssl_fc_has_sni] %[ssl_c_used] %[ssl_fc_has_crt] %[ssl_c_err] %{+Q}[ssl_c_s_dn] %{+Q}[ssl_c_i_dn] %{+Q}[ssl_fc_sni]"

  capture request header Host len 256
  capture request header User-agent len 256

  http-request set-header X-SSL-Client-Err %[ssl_c_err]

  default_backend be

backend be
  server echo-headers localhost:8080 check
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.7.1-3e4af0e 2022/12/19 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2024.
Known bugs: http://www.haproxy.org/bugs/bugs-2.7.1.html
Running on: Linux 5.10.124-linuxkit #1 SMP Thu Jun 30 08:19:10 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -PTHREAD_EMULATION +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -OPENSSL_WOLFSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING +SHM_OPEN

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wlallemand** [comment]
" This is dangerous as it implies that all system CAs are trusted for client certificates connecting to HAproxy."

**Comment by wlallemand** [comment]
> Ever since HAproxy 2.6 the socket command "show ssl ca-file" returns "@system-ca" in the list of trusted CAs for client certificates. This is dangerous as it implies that all system CAs are trusted for client certificates connecting to HAproxy.

I think there is some confusion, having @system-ca in "show ssl ca-file" does not imply that it's loaded for your server lines. Since version 2.6, the @system-ca are loaded at startup because it's the only way to access these files, HAProxy does not access files during runtime so it needs to load them at startup.

The result of the "show ssl ca-file" command only shows the certificates that are available in HAProxy, it's not a list of currently used certificates. This is not applied by default on your server lines.

Only the httpclient uses this by default, but you can configure it to use something else.

**Comment by domdom82** [comment]
@wlallemand so it's only a "visual" thing? so what is the API to get the CA files that are actually used then? maybe the docs should be updated to emphasize that the CAs returned are not the ones that are used (which still confuses me tbh).

**Comment by wlallemand** [comment]
It's a certificate cache in HAProxy, there is even a status which give you the state "Used" or "Unused" ( https://docs.haproxy.org/2.7/management.html#show%20ssl%20ca-file ) it's the same with the "crt" command.

With the CLI you are able to create a new ca-file or a new crt, so they will appear in the list of ca-file and crt, but they won't be used until you insert them from the CLI in a crt-list entry, or a new server line.

Indeed the documentation could be changed, it can be confusing.

**Comment by domdom82** [comment]
@wlallemand thanks for the clarification!
