### ISSUE TITLE
Add 'final_status' sample fetch

### ISSUE THREAD

**Issue by CaptainDredge** [haproxy/haproxy#1980]
### Detailed Description of the Problem

If we use following acl to classify failed requests in a backend
```
acl failed_request status ge 400
```
Then `status` doesn't return a `5xx` status in cases where Haproxy itself throws 5xx i.e. in cases like `conn-failure`, `response-timeout` etc.

### Expected Behavior

It is expected that `status` fetch should return a `5xx` response code in cases where Haproxy throws it itself

### Steps to Reproduce the Behavior

1. Start Haproxy with attached configuration
2. Make few calls which fails due to connection errors or due to response timeout on server
3. see `path-beg-backend` stick table and you should see the counter for the failed api will not be incremented. `path-beg-backend` stick table is tracking count of 5xx per api

### What is your configuration?

```haproxy
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # Default ciphers to use on SSL-enabled listening sockets.
        # For more information, see ciphers(1SSL). This list is from:
        #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
        # An alternative list with additional directives can be obtained from
        #  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        ssl-default-bind-options no-sslv3

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 1000
        timeout client  1000
        timeout server  1000
        timeout http-keep-alive 300
        option http-server-close

        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend test-frontend
        bind 127.0.0.1:80
        mode http
        default_backend test-backend
        http-request set-var(req.path) path
        acl is_es var(req.path) -m beg /
        http-request set-var(req.url_beg) path,word(1,/) 
        http-request track-sc0 var(req.url_beg) table path-beg-backend if is_es

backend test-backend
        balance roundrobin
        server go-server 127.0.0.1:8000
        acl failed_request status ge 500
        http-response sc-inc-gpc0(0) if failed_request

backend path-beg-backend
        stick-table type string len 32 size 100k expire 1m store gpc0_rate(1m)


listen stats
bind 127.0.0.0:8001
mode http
option forwardfor
option httpclose
stats enable
stats show-legends
stats refresh 5s
stats uri /stats
stats realm Haproxy\ Statistics
stats auth hello:hello            #Login User and Password for the monitoring
stats admin if TRUE
default_backend test-backend
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 1.8.19-1+deb10u3 2020/08/01
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-OkbS59/haproxy-1.8.19=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
```

**Comment by Darlelet** [comment]
http status fetch relies on smp_prefetch_htx() to extract the response status code.
Unfortunately when haproxy responds itself on error, it bypasses standard processing and does not complete the http response analysis, leading to a response state that does not meet smp_prefetch_htx() prerequisites.

We could extract status code directly from the txn context without relying on htx (this is what we do for the %ST log fmt which properly reports 50x errors generated by haproxy), but it means that the status fetch would behave differently than other http fetches (that all rely on smp_prefetch_htx()).. Probably not a good idea.

**Comment by CaptainDredge** [comment]
From a user point of view if we're doing some operations like circuit breaking or rate-limiting or metric tracking through stick-tables etc. based on some logic that relies on response codes(from a client perspective) then fetching it through `status` gives an incomplete info.
Is there any way currently to get 5xx status that haproxy responds itself? I explored even the lua api and still couldn't find any way

**Comment by TimWolla** [comment]
If I understand this issue correctly, then the issue is not (just) the `status` fetch, but rather/also that `http-response` will not be executed at all for HAProxy-generated responses. `http-after-response` is required for that.

@CaptainDredge Unrelated to the issue at hand, you should upgrade your HAProxy. 1.8.x is effectively EOL and you're not even running the latest 1.8. The current LTS is HAProxy 2.6.x (2.6.7 currently).

**Comment by Darlelet** [comment]
@TimWolla You're right in this situation we could use `http-after-response`, but after-response is only implementing a limited set of actions, and it seems that `sc-inc-gpc0` is not (yet?) part of that list. This won't work here :(

**Comment by CaptainDredge** [comment]
@Darlelet Are there future plans to add more actions like `sc-inc-gpc0` in `http-after-response` ?

Also, if I `set-var` txn.status in `http-after-response`, is there a place where I can use it? I guess no because `http-after-response` is probably the last phase in transaction, and all other phases cannot evaluate something set in a later phase.

>@CaptainDredge Unrelated to the issue at hand, you should upgrade your HAProxy. 1.8.x is effectively EOL and you're not even running the latest 1.8. The current LTS is HAProxy 2.6.x (2.6.7 currently).

@TimWolla thanks I've updated it to `2.6.x`. Older version I got with apt out-of-the-box.

**Comment by Darlelet** [comment]
> Are there future plans to add more actions like sc-inc-gpc0 in http-after-response ?

While I don't see any technical difficulty to do so, I would wait for @capflam's advice here as he knows this part best.
He's on vacation and will be back next week.

> Also, if I set-var txn.status in http-after-response, is there a place where I can use it? I guess no because http-after-response is probably the last phase in transaction, and all other phases cannot evaluate something set in a later phase.

If by "using it" you ultimately mean reporting it to the stick table I'm short of ideas :/

**Comment by wtarreau** [comment]
Please note that all sample-fetch rules and ACLs that rely on them exclusively apply to the traffic *received* by haproxy. This makes sense as historically nothing could be done after a response was emitted. For example an error message may contain a content-type header field that will not be matched for the same reasons. Also, if you perform a "deny" on a response status code, it will by definition change the response sent to the user and possibly with it the returned status code. You wouldn't want to have to guess which one a rule applies to.

Of course with the introduction of `http-after-response` things changed a little bit because it is possible to see what is being delivered. I remember seeing a request not too long ago for being able to distinguish the received status from the delivered status (right now we only have the former). I seem to remember that the reason was that the user wanted to be able to place the two side-by-side in the logs.

Thus I guess that the discussion is more related to the desire to introduce such a separate final-status that differs from the received status ? If that's the case, we should turn that into a feature request.

**Comment by CaptainDredge** [comment]
Yes, @wtarreau I've two feature request
1. To introduce such final status
2. Support more operations like `sc_inc_gpc0` in `http-after-response`

Should I create separate issues for these two or you can track both of these under this issue?

**Comment by wtarreau** [comment]
I suspect that the second one will be the only user of the former, so both can remain the same request. In fact the simplest solution is to change this issue's status, and it will preserve the discussion history. We'll do it here. Thanks.

**Comment by capflam** [comment]
Well, at first glance, there is no reason to not support `sc_inc_gpc{0,1}` in `http-after-response` ruleset. In fact, reviewing all `http-response` actions, I guess we may add support of several actions: 

* `del-acl` and ` del-map`
*  `sc-inc-*` and `sc-set-*`
* `set-log-level`
* `set-map`

**Comment by wtarreau** [comment]
Thanks for checking. I generally agree, however I think track-sc has no use there. Its purpose is to set up a tracker to track *future* events, and here in an after-response rule, there's basically nothing more going to happen, we're microseconds before releasing all trackers. And it could encourage some users to use it for a wrong reason (and track-sc are not cheap in terms of setup). I'd rather add it only if there was a very compelling case of something that cannot be done differently.

**Comment by capflam** [comment]
Copy that !

**Comment by capflam** [comment]
I pushed a fix to add support of missing actions in `http-after-response` ruleset.

**Comment by CaptainDredge** [comment]
@capflam  will this fix be available in next new release or it will also be backported to till any older LTS version?

**Comment by capflam** [comment]
Indeed, it was not backported, most probably because it was not marked as  a bug :). But I guess we can safely backport it to 2.7 and 2.6. Is this commit is enough to fix your issue ?

**Comment by CaptainDredge** [comment]
I'm yet to test the fix on my system but do you think the `status` fetch method if now used in acl in conjuction with `http-response` will return the final status returned by haproxy i.e. when haproxy status differs from the one returned by server or when none is returned by server ?

**Comment by capflam** [comment]
No, there is no commit to get the final response status. Not yet at least. If a response was already received from the server, the `status` fetch method will return the server's one, even if it is changed by HAProxy. There is however an exception for 500-Internal-error. But it will be the final status if HAProxy sends its response before it receives the server's one. So, in your case,  you should be able to catch 50x errors returned by HAProxy on connection failures. And because you are not using any `http-response` rules that alters the status code, it should be enough.

**Comment by CaptainDredge** [comment]
Thanks! But is this exception of `status` fetch returning `50x` status code in case of network errors true only when this fetch is used in conjuction with `http-response` only or it it true for other http phases as well like `http-request`?
I believe it is the former since the last time I checked `status` used to return `null` i.e. any acl involving `fetch` will always be false in case of network error `50x` status codes thrown by haproxy before receiving any status from server.

**Comment by capflam** [comment]
In `http-response` rules, you will only be able to catch status code received from the server. If you also want to get the status code of responses returned by HAProxy, excluding those returned after the server response, you should use `http-after-response` rules.

**Comment by RamakrishnaChilaka** [comment]
Is it possible to add a fetch to get termination_state as well?

**Comment by CaptainDredge** [comment]
@capflam can we get this backported to `2.7` and `2.6` ?

**Comment by capflam** [comment]
I guess it is possible. The commit is quite simple.

**Comment by capflam** [comment]
Now backported to 2.7 and 2.6

**Comment by capflam** [comment]
FYI, I added `server_status` sample fetch to get the status code received from the server and `txn.status` to get the transaction status code, the one reported in logs (`%ST`). `status` remains unchanged, it returns the status code in the HTTP response itself, thus the one sent to the client. Most of time, this will be the same than `txn.status`.

The termination state is also exposed via `txn.sess_term_state` sample fetch. It is the same than `%ts` in logs.

**Comment by CaptainDredge** [comment]
@capflam till which haproxy version this `server_status` fix is backported?

**Comment by capflam** [comment]
Nothing was planned for now. Technically, it is feasible to backport it. We can evaluate to backport it to 2.8. But I doubt we will do so for 2.7 and lowers.

**Comment by CaptainDredge** [comment]
Thanks!! I'll be grateful if it can be backported to atleast 2.8(LTS) so we'll be able to upgrade our existing systems from 2.6
