### ISSUE TITLE
Ubuntu 22.04 aarch64 Cross Compile Fails on linking libcrypt

### ISSUE THREAD

**Issue by soxrok2212** [haproxy/haproxy#1986]
### Detailed Description of the Problem

Attempting to use aarch64-linux-gnu-gcc to cross compile for arm64 fails when linking libcrypt. Build system is x86_64 Ubuntu 22.04.

```
# make -j 1 CC=/usr/bin/aarch64-linux-gnu-gcc TARGET=linux-musl

...

  LD      haproxy
/usr/lib/gcc-cross/aarch64-linux-gnu/11/../../../../aarch64-linux-gnu/bin/ld: cannot find -lcrypt: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:963: haproxy] Error 1
make: *** Waiting for unfinished jobs....
```

```
$ sudo apt list installed libcrypt-dev
Listing... Done
libcrypt-dev/jammy,now 1:4.4.27-1 amd64 [installed]
```

### Expected Behavior

Build should succeed.

### Steps to Reproduce the Behavior

1. make -j 1 CC=/usr/bin/aarch64-linux-gnu-gcc TARGET=linux-musl

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by TimWolla** [comment]
> libcrypt-dev/jammy,now 1:4.4.27-1 amd64 [installed]

I'm not too familiar with that output, but are you positive that the library is installed for aarch64? It only lists amd64 there.

**Comment by wtarreau** [comment]
And what exact haproxy source version is this ?

**Comment by chipitsine** [comment]
it is known issue.
we set `USE_LIBCRYPT=` to disable it for cross builds

https://github.com/haproxy/haproxy/blob/master/.github/workflows/cross-zoo.yml#L109

**Comment by wtarreau** [comment]
@chipitsine indeed it's very likely because libcrypt is not present in the reporter's toolchain, but we have zero info here, no haproxy version, no toolchain version etc. All my toolchains build fine and include libcrypt, here I don't know where they come from. That's why I'd like to be sure that it's just that libcrypt is missing from the toolchain's sysroot and it's not another issue before closing the issue.

**Comment by soxrok2212** [comment]
Hi all, sorry. Yep libcrypt is missing from my toolchain. 

This is for v2.7.1.

**Comment by wtarreau** [comment]
Cool, I prefer that :-)  Ilya's solution is the simplest one in this case, as you generally don't need libcrypt for the vast majority of configs. I'm going to close now. Thanks for the quick response.
