### ISSUE TITLE
SSL Certificate SHA512

### ISSUE THREAD

**Issue by officebluesource** [haproxy/haproxy#1988]
### Detailed Description of the Problem

SSL certificate signed with SHA512 and a RSA public key length of 8192 bit is not working. 
haproxy is giving 503 service unavailable

### Expected Behavior

SSL Certificate works

### Steps to Reproduce the Behavior

1. implement a SSL Certificate with SHA512 and a RSA key length of 8192 bit

### What is your configuration?

```haproxy
Log output: Informational | haproxy | [04/Jan/2023:18:18:42.620] xxx_frontend_https/x.x.x.x:443: SSL handshake failure

haproxy version 2.4.17-9f97155
ssl.default-dh-param is set to 1024 (default)
```

### Output of `haproxy -vv`

```plain
no output
```

**Comment by lukastribus** [comment]
More information is needed:

- `haproxy -vv` output as requested by the template
- the configuration or at least part of it
- informations about the client if this is a frontend issue (for example output of `curl -vv https://...`)



> haproxy is giving 503 service unavailable

It is unclear from your description where this certificate is actually used.

Is it configured in the frontend of haproxy? If so, you would not be able to see a 503 service unavailable response in the client.

Is configured on a backend server that you are accessing through haproxy, so haproxy is the SSL client?

Is it configured as client certificate in the backend to authenticate against a backend SSL server?

**Comment by officebluesource** [comment]
* third party CA SSL is only configured on frontend of haproxy and SSL termination is performed on frontend side for an incoming client
* a self signed SSL connection (to a tomcat server) is configured on backend side
* both Certificates are simple Server Certificated (no Client Certificate or other mutual TLS stuff is performed)
* HAproxy frontend SSL Cert signed with SHA256 and a key length of 2048 bit is working fine in this setup

config (part of the specific service):

```
Frontend: SPE_PROD_frontend_https ()
frontend SPE_PROD_frontend_https
    bind x.x.x.x:443 name x.x.x.x:443 ssl no-tlsv10 no-tlsv11 no-sslv3 no-tls-tickets ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305  crt-list /tmp/haproxy/ssl/594cac7eaa3f16.22001480.certlist 
    mode http
    option http-keep-alive
    default_backend SPE_prod_backend
    option forwardfor
    # tuning options
    maxconn 100000
    timeout client 30s
    timeout http-request 5s`

# Backend: SPE_prod_backend ()
backend SPE_prod_backend
    # health check: health_mp_PROD
    option httpchk
    http-check send meth GET uri /status/core/f3c8b0acad31b56bef7cc4ca3889ed78 ver HTTP/1.1 hdr Host x.x.x.x
    http-check expect status 204
    mode http
    balance leastconn
    # stickiness
    stick-table type ip size 50k expire 30m  
    stick on src
    # tuning options
    timeout connect 5s
    timeout server 30s
    http-reuse never
    server x..x.x.x :8443 check inter 2s  ssl verify none
    server x.x.x.x:8543 check inter 2s  ssl verify none
    server x.x.x.x:8443 check inter 2s  ssl verify none
    server x.x.x.x:8543 check inter 2s  ssl verify none
```

curl output:

```
*   Trying x.x.x.:433
* Connected to x.x.x.x port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
> GET /status/core/f3c8b0acad31b56bef7cc4ca3889ed78 HTTP/1.1
> Host: x.x.x.x
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 107
< cache-control: no-cache
< content-type: text/html
<
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
* Connection #0 to host x.x.x.x left intact
```
haproxy -vv output:

```
HAProxy version 2.4.17-9f97155 2022/05/13 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.17.html
Running on: FreeBSD 13.1-RELEASE FreeBSD 13.1-RELEASE stable/22.7-n250212-a26d60                                                                                                                                                                                                                                             65f1f SMP amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextr                                                                                                                                                                                                                                             a -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unuse                                                                                                                                                                                                                                             d-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers                                                                                                                                                                                                                                              -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -Wtype-limits                                                                                                                                                                                                                                              -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_STATIC_PCRE=1 USE_GETADDRINFO=1 USE_OP                                                                                                                                                                                                                                             ENSSL=1 USE_LUA=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_PROMEX=1
  DEBUG   =

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL                                                                                                                                                                                                                                              -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE +STATIC_PCRE -STATIC_PCRE2 +                                                                                                                                                                                                                                             TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H +GETADDRINFO +OPENSSL +LUA                                                                                                                                                                                                                                              -FUTEX +ACCEPT4 +CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATL                                                                                                                                                                                                                                             AS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL +PROCCTL -THREAD_DUMP -EVP                                                                                                                                                                                                                                             ORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
Running on OpenSSL version : OpenSSL 1.1.1q  5 Jul 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.12
Running on zlib version : 1.2.12
Compression algorithms supported : identity("identity"), deflate("deflate"), raw                                                                                                                                                                                                                                             -deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 13.0.0 (git@github.com:llvm/llvm-project.git l                                                                                                                                                                                                                                             lvmorg-13.0.0-0-gd7b669b3a303)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_A                                                                                                                                                                                                                                             BRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RIS                                                                                                                                                                                                                                             K|NO_UPG
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by lukastribus** [comment]
The certificates on the Tomcat backend servers are always standard SHA2/2048 bit RSA certificates?
The SHA512 8192 bit certificates are in the frontend, correct?

This is unexpected, because as shown by your outputs, the frontend TLS connection (with SHA512/8192 bit cert) establishes perfectly fine, it even provides a full HTTP response (503 Service Unavailable), which indicates a failure in the backend, but doesn't make sense for a certificate replacement on the frontend.

Is there more complexity in the actual configuration like context switching based on SNI values, for example?

I suggest to enable `option httplog` in all affected sections (front and backend) and check that you are actually hitting the expected backend (SPE_prod_backend).

We need to see the log line that actually shows the reason for the `503 Service Unavailable` in httplog format.

**Comment by TimWolla** [comment]
I believe some web browsers reject certificates with RSA key sizes > 4096, so this might be the issue here.

**Comment by officebluesource** [comment]
We ended up to use a new SHA256 SSL certificate with 2048bit Key length.
IMHO there must be an issue in haproxy with 8192bit RSA Keys that breaks the health checks to the backend servers (I've no idea, why that happens, the backend servers are not in touch with the Certificate from the haproxy frontend). Also we observed a much slower processing time on the client side, maybe more CPU consumption from haproxy at the SSL handshake due to the long key?

`option httplog` does not indicate an error in SNI, all requests seem to go to the correct backend.
We observerd some strange errors on backend side: `05/Jan/2023:10:35:05 +0100] - - - - "-" 400 - **0**` coming from haproxy with the SHA512 Certificate in place.  Seems some kind of "malformed" request from haproxy to the backend resulting in `http 400 bad request`. 
`
option httpslog` is available from version 2.5, maybe we'll update to collect additional logs.

**Comment by lukastribus** [comment]
> Also we observed a much slower processing time on the client side, maybe more CPU consumption from haproxy at the SSL handshake due to the long key?

How did you measure slower processing when it doesn't work at all?

But yeah, absolutely, using a RSA certificate with more than 2048bit is a terrible idea.

A 4096-bit RSA certificate will require 6 times the CPU cycles on the SSL server (haproxy) per handshake, comparing to a 2048-bit certificate:

https://vincent.bernat.ch/en/blog/2011-ssl-dos-mitigation

I don't have any numbers for 8192-bit RSA certificates, but this is exponential.

For any production workload, if you for some reason must use RSA certificates, never increase beyond 2048-bit. But really EC certificates should be used at this point. And if you still need RSA for legacy stuff, you can use both so that only old clients waste your CPU cycles with RSA handshakes.

**Comment by officebluesource** [comment]
> How did you measure slower processing when it doesn't work at all?

The backend servers are not down at all, haproxy always bounces between up and down state in the health check leading to a "half" client functionality. But even it worked for a certain amount of time, it was really slow.

> For any production workload, if you for some reason must use RSA certificates, never increase beyond 2048-bit. But really EC certificates should be used at this point. And if you still need RSA for legacy stuff, you can use both so that only old clients waste your CPU cycles with RSA handshakes.

good point, thank you. I will consider and test it upon next certificate change

**Comment by wlallemand** [comment]
any update on this?

**Comment by capflam** [comment]
I'm closing because the issue seems inactive. If there are new info,  feel free to reopen it.
