### ISSUE TITLE
DNS resolver does not work after running a Lua action

### ISSUE THREAD

**Issue by Smackd0wn** [haproxy/haproxy#1993]
### Detailed Description of the Problem

Here is a minimal configuration that reproduces the bug: In a TCP mode proxy, there are two `tcp-request content` rules:

1. A Lua "action" that receives and sends some contents from/to the request Channel.
2. A DNS resolve (`do-resolve`) rule.

The problem is, most of the time (like 90% of requests), the second rule (DNS resolution) does not run -- no DNS packets are sent. If the order of the two rules are swapped, then DNS works every times.

### Expected Behavior

The DNS resolution should work every time.

### Steps to Reproduce the Behavior

1. Use the configuration and Lua script below
2. Watch for DNS requests with `tcpdump` (or log/use the resolved IP address in a later rule)
3. Make some requests, which should trigger DNS resolution every time, but the action is ignored most of the time

```lua
-- This Lua action simply waits for some content from the client, and appends a line of text to the response
local function foo(txn)
    repeat c = txn.req:line() until c:len()>0
    txn.res:send('This line is sent from Lua.\n')
end
core.register_action("foo", {'tcp-req'}, foo, 0)
```

### Do you have any idea what may have caused this?

No idea, sorry, but since it does not always occur, maybe a race condition?

### What is your configuration?

```haproxy
global
    maxconn 1000
    lua-load foo.lua

resolvers mydns
    nameserver google 8.8.8.8:53
    hold valid 0s

listen srv
    mode tcp
    bind *:8080
    tcp-request inspect-delay 5s
    tcp-request content lua.foo
    tcp-request content do-resolve(txn.myip,mydns) str(google.com)
    server srv 1.0.0.1:80
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.7.1-3e4af0e 2022/12/19 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2024.
Known bugs: http://www.haproxy.org/bugs/bugs-2.7.1.html
Running on: Linux 5.15.86-1-lts #1 SMP Sun, 01 Jan 2023 16:03:00 +0000 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/haproxy/src=/usr/src/debug/haproxy -flto=auto -fwrapv
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -PTHREAD_EMULATION +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -OPENSSL_WOLFSSL +LUA +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING +SHM_OPEN

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.0.7 1 Nov 2022
Running on OpenSSL version : OpenSSL 3.0.7 1 Nov 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace

Linux 5.15.86-1-lts #1 SMP Sun, 01 Jan 2023 16:03:00 +0000 x86_64 GNU/Linux
```

### Additional Information

This problem can be reproduced on 2.6, 2.7 and dev, but not on 2.4 (with `txn.req:line()` replaced with the old API `getline()`.

**Comment by capflam** [comment]
There is a bug in `Channel:line()` function. When no specific length is provided and no line is found, instead of waiting for more data, an empty string is returned. In your case, it means your script will loop in the `repeat .. until` block. If the inspect delay is reached waiting for a line from the client, the `do-resolve` will not be executed.

With the fixed version of the `Channel:line()` function, there is no reason to get the first line in loop, the function will wait for data. However, it may return `nil` if no data are received when the inspect delay is reached (or a client abort).

Note that `Channel:data()` is also affected.  

I will push a fix soon. Thanks !

**Comment by Smackd0wn** [comment]
> There is a bug in `Channel:line()` function. When no specific length is provided and no line is found, instead of waiting for more data, an empty string is returned. In your case, it means your script will loop in the `repeat .. until` block.

Yes, I have noticed this change since 2.5, but I was not sure it was a bug or a new design. In 2.4, I used `Channel.getline()` or `.get()` and it would always return some data (unless no data received during the inspect delay), but that changed since 2.5, with the new `line()` or `data()`, or even with the now deprecated `get()` and `getline()` API. That is why I used a repeat...until loop in 2.5, In the 2.5+ Lua docs, it says:
> By default, if no length is provided, all incoming data found, starting at the given offset, are returned.

So my understanding was that returning an empty string when no incoming data is in the buffer was the expected behavior, and the user is supposed to write a loop if they expect some data. But I think keeping the old behavior is more favorable.

---

> If the inspect delay is reached waiting for a line from the client, the `do-resolve` will not be executed.

I am afraid timeout is probably not the cause. I used `echo "GET / HTTP1.1\n\n" | nc 127.0.0.1 8080` during test, so that a line of string is guaranteed to hit haproxy via loopback interface within the specified inspect delay (which is generously 5 seconds), typically within 10 ms. Lua script can always get a line of data, if you try printing that out. Yet, the `do-resolve` still does not work _most of the time_, even when there is enough inspect delay left.

Fwiw, during my test, it seems that if the Lua script only tries to receive data (with repeat...until loop), but does _not_ send anything to the response Channel (i.e., commenting out `txn.res:send('This line is sent from Lua.\n')`), the `do-resolve` works reliably. Conversely, DNS seems also work fine if Lua only sends but not receives.

**Comment by Smackd0wn** [comment]
I ran some additional test: I added a counter to the `repeat...until` loop. It turns out that it either loops only 1 time (i.e., got some data at the first shot), or 346233 times. Note that the script can always successfully get the data after so many retries, usually within 1ms of wall clock time. Curiously, DNS packets were sent only when counter is 1, but not when it's 346233.

Curious still, when `res:send()` was commented out, no matter the loop counter was 1 or 346233, DNS packets were always sent.

I hadn't the foggiest idea what could possibly cause the bug.

**Comment by capflam** [comment]
Ok, thanks for these information. It is really useful. I guess I found the bug in the resolver code. It happens depending on the scheduling. The first call to `do_resolv` action triggers a new resolution. Concretely it wakes up the resolvers task. Most of time the resolvers task will be processed before the next call to `do_resolv` action. However, it is possible to return in the `do_resolv` action before the resolvers task has a chance to run.  This case is not properly handled.

I will fix this bug too...

**Comment by Smackd0wn** [comment]
Thanks a lot! I have tested your patches individually and both bugs should have been independently fixed now.

**Comment by capflam** [comment]
It was not backported to 2.0 because it is not a critical fix and the resolvers code is too sensitive in 2.0. I'm closing now.

**Comment by Smackd0wn** [comment]
@capflam It appears that the old `Channel.get` API (`hlua_channel_get()`), although deprecated, is still affected by the bug. If no arguments specified (i.e., `get()`), it might return an empty string instead of waiting for more data. So existing scripts, if not switching to the new `data()` + `remove()` API, could break when upgraded from 2.4 or earlier to 2.5+ and . Could that get fixed as well?

**Comment by capflam** [comment]
`Channel.get` works as documented. It the buffer is empty, an empty string is returned, except if no more data are expected. In this case, `nil` is returned. But it doesn't yield. It was never documented it should yield when the buffer is empty. On this point, the function was fixed. Unfortunately, it means existing scripts should be updated if they use this function. I can understand it is disappointing. This function was deprecated especially because it is ambiguous and errorprone.

**Comment by capflam** [comment]
`Channel.get` works as documented. It the buffer is empty, an empty string is returned, except if no more data are expected. In this case, `nil` is returned. But it doesn't yield. It was never documented it should yield when the buffer is empty. On this point, the function was fixed. Unfortunately, it means existing scripts should be updated if they use this function. I can understand it is disappointing. This function was deprecated especially because it is ambiguous and errorprone.

**Comment by Smackd0wn** [comment]
I see. Thanks a lot for the explanation!
