### ISSUE TITLE
Error building from source with Lua5.4.4

### ISSUE THREAD

**Issue by NicolasCARPi** [haproxy/haproxy#1999]
### Detailed Description of the Problem

While building haproxy from source, there is this error:

~~~
/usr/bin/ld: src/hlua.o: in function `hlua_httpclient_new':
/home/user/.dev/haproxybug/haproxy/src/hlua.c:7082: undefined reference to `lua_newuserdata'
/usr/bin/ld: src/hlua.o: in function `hlua_fetches_new':
/home/user/.dev/haproxybug/haproxy/src/hlua.c:4130: undefined reference to `lua_newuserdata'
/usr/bin/ld: src/hlua.o: in function `hlua_converters_new':
/home/user/.dev/haproxybug/haproxy/src/hlua.c:4252: undefined reference to `lua_newuserdata'
/usr/bin/ld: src/hlua.o: in function `hlua_txn_new':
/home/user/.dev/haproxybug/haproxy/src/hlua.c:7663: undefined reference to `lua_newuserdata'
/usr/bin/ld: src/hlua.o: in function `hlua_http_new':
/home/user/.dev/haproxybug/haproxy/src/hlua.c:5629: undefined reference to `lua_newuserdata'
/usr/bin/ld: src/hlua.o:/home/user/.dev/haproxybug/haproxy/src/hlua.c:4387: more undefined references to `lua_newuserdata' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:976: haproxy] Error 1
~~~

Lua is available on the system. The make command used just after cloning from master:

`make -j 16 TARGET=linux-glibc USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1 USE_SYSTEMD=1`

Note that using `USE_LUA=0` doesn't change a thing (same error). Simply specfying the TARGET will successfully build.

### Expected Behavior

The compilation is successful.

### Steps to Reproduce the Behavior

1. git clone from master
2. build from a system with lua5.4.4 (Archlinux will do that), use: `make TARGET=linux-glibc USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1 USE_SYSTEMD=1`

### Do you have any idea what may have caused this?

See: http://www.lua.org/manual/5.4/manual.html#8.3

### Do you have an idea how to solve the issue?

Replacing all occurences of `lua_newuserdata` with `lua_newuserdatauv` seems to fix the issue.

### What is your configuration?

```haproxy
Not applicable.
```

### Output of `haproxy -vv`

```plain
Building on Archlinux, x86
Linux <hostname> 6.1.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Jan 2023 15:10:07 +0000 x86_64 GNU/Linux
```

### Additional Information

[diff.txt](https://github.com/haproxy/haproxy/files/10406389/diff.txt)

**Comment by capflam** [comment]
As stated in the lua documentation, `lua_newuserdata` is still provided as a macro. So it should work.

**Comment by lukastribus** [comment]
> Note that using `USE_LUA=0` doesn't change a thing (same error). Simply specfying the TARGET will successfully build.

USE_ flags are about definition, not the content. `USE_LUA=0` is identical to `USE_LUA=1`.

To disable a USE_ flag previously set from other USE flags or TARGET, use `USE_LUA=`

**Comment by capflam** [comment]
The macro indeed exists in lua-5.4.4: https://github.com/lua/lua/blob/v5.4.4/lua.h#L412. So it is strange. However, I'm not against catching the deprecation.  But we must take care to still be compatible with previous version of lua.

**Comment by NicolasCARPi** [comment]
> As stated in the lua documentation, lua_newuserdata is still provided as a macro. So it should work.

Indeed, that was also my impression, so this is a bit surprising. I have the same file (/usr/include/lua.h line 412) on my system, but for some reason it doesn't work.

Thanks @lukastribus for the precisions about USE flags.

**Comment by Darlelet** [comment]
Hi,

>Indeed, that was also my impression, so this is a bit surprising. I have the same file (/usr/include/lua.h line 412) on my system, but for some reason it doesn't work.

Could you try manually specifying the path to the correct 5.4.4 header file parent directory using `LUA_INC` and see if the issue still persists?

```
make clean
make -j 16 TARGET=linux-glibc USE_OPENSSL=1 USE_LUA=1 LUA_INC=/path/to/lua5.4_header_file/parent/directory USE_PCRE=1 USE_SYSTEMD=1
```
I suspect that your system could be using lua 5.4.4 library when linking but with older 5.3 header files when compiling

**Comment by NicolasCARPi** [comment]
@Darlelet I confirm that adding `LUA_INC=/usr/include` fixes the issue.

**Comment by capflam** [comment]
What is the issue status ? can we close it ?

**Comment by NicolasCARPi** [comment]
@capflam Yes, I think this issue is now a good documentation on the error message, with a workaround. It can be revisited later if needed. It might very well be some sort of distribution related issue as @Darlelet hinted, though I don't really know how to verify this claim.
