### ISSUE TITLE
HAProxy not forwarding requests to nginx ingress

### ISSUE THREAD

**Issue by mohanss08** [haproxy/haproxy#2007]
I'm using `HA-Proxy (Independent server)` and `Kubernetes v1.24.9 cluster (One master and three workers)` bare metal based.

**HAProxy Environment:**
```
OS: Ubuntu 20.04.5 LTS
HAProxy version: 2.4.20-1ppa1~focal 2022/12/09
```
**My access workflow:-**

**Users** --> **HAproxy**(Front End --> Back End) --> **Kubernetes Cluster**(Nginx Ingress --> Service --> Jenkins POD)

I have deployed Jenkins application as a pod inside my cluster. When i access my Jenkins URL - `http://jenkins.company.com/jenkins` on browser i should see my Jenkins login page. But it always fails with `404 Not Found` error.

Master, Workers and HAProxy(LB) are running separately on VMs. In Master, Worker, LB and in my laptop i have added `jenkins.company.com` entry along with LB `IP address` in hosts file. 

Have found that our HAProxy is not forwarding request to our cluster nginx-ingress controller pod.

Based on the `nginx-ingress` logs it doesn't look like the Ingress Controller has not even processed the request. There should be a log line similar to this one:

```
160.5.5.7 - - [19/Jan/2023:09:35:18 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "http://jenkins.company.com/jenkins" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0" "-"
```
But in my case i can't see any logs.

My HAproxy `/etc/haproxy/haproxy.cfg` configurations as follows,

```
$ sudo cat /etc/haproxy/haproxy.cfg
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http
frontend user_local
    bind *:80
    mode http
    default_backend ks_backend

backend ks_backend
    mode http
    balance roundrobin
    server kserver1 160.20.21.12:80
```

```
$ sudo netstat -pnltu | grep 80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      7529/haproxy
```

```
$ sudo tail -n 10 /var/log/haproxy.log

Jan 19 16:21:41 LB haproxy[238044]: [NOTICE]   (238044) : path to executable is /usr/sbin/haproxy
Jan 19 16:21:41 LB haproxy[238044]: [ALERT]    (238044) : Current worker #1 (238046) exited with code 143 (Terminated)
Jan 19 16:21:41 LB haproxy[238044]: [WARNING]  (238044) : All workers exited. Exiting... (0)
Jan 19 17:07:14 LB haproxy[6863]: [WARNING]  (6863) : Exiting Master process...
Jan 19 17:07:14 LB haproxy[6863]: [NOTICE]   (6863) : haproxy version is 2.4.20-1ppa1~focal
Jan 19 17:07:14 LB haproxy[6863]: [NOTICE]   (6863) : path to executable is /usr/sbin/haproxy
Jan 19 17:07:14 LB haproxy[6863]: [ALERT]    (6863) : Current worker #1 (6879) exited with code 143 (Terminated)
Jan 19 17:07:14 LB haproxy[6863]: [WARNING]  (6863) : All workers exited. Exiting... (0)
Jan 19 17:07:14 LB haproxy[7527]: [NOTICE]   (7527) : New worker #1 (7529) forked
```
In the log shown `exited with code 143 (Terminated)` does it causing issue?

Any guidance to solve this issue would be helpful.

Thank you!

**Comment by Tristan971** [comment]
Just curious, how is your nginx-ingress service defined? Since you write:

> Have found that our HAProxy is not forwarding request to our cluster nginx-ingress controller pod.

HAProxy wouldn't be able to talk to a pod directly (in general), since k8s defaults to them only having an address internal to the cluster's overlay network.

It should instead talk to a service, and since you're saying you run on baremetal it should likely be a NodePort type service (unless you use something like MetalLB), and NodePort type services are on the 3XXXX-32XXX port range, not 80.

This HAProxy config would likely only work if nginx-ingress pods are setup to run on hostNetwork with a hostPort (not just a containerPort) of 80 🤔

The best way to check that your k8s side is fine is whether you can curl the server ip:port from the HAProxy VM in the first place (ie 160.20.21.12:80 in this case)

**Comment by mohanss08** [comment]
Hi @Tristan971 

I have installed `Nginx Ingress Controller` by using this link [https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests](https://github.com/nginxinc/kubernetes-ingress/issues/url) on my Kubernetes master.

It is runs as a daemon set,

```
$ kubectl get all -n nginx-ingress
NAME                      READY   STATUS    RESTARTS   AGE
pod/nginx-ingress-69z69   1/1     Running   0          26m
pod/nginx-ingress-l7z86   1/1     Running   0          26m
pod/nginx-ingress-wsjfv   1/1     Running   0          26m

NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/nginx-ingress   3         3         3       3            3           <none>          26m
```
I have deployed jenkins application and it is running as `ClusterIP` 
```
$ kubectl get svc  --all-namespaces
NAMESPACE     NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP                  3d1h
jenkins       jenkins-svc   ClusterIP   10.103.54.142   <none>        80/TCP                   3d1h
kube-system   kube-dns      ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   3d1h
```
```
$ kubectl get ingress --all-namespaces
NAMESPACE   NAME              CLASS    HOSTS                ADDRESS   PORTS   AGE
jenkins     jenkins-ingress   <none>   jenkins.company.com             80      19h
```
Curl result from my HAProxy VM to cluster
```
$ curl -D- http://160.20.21.12/jenkins -v
*   Trying 160.20.21.12:80...
* TCP_NODELAY set
* Connected to 160.20.21.12 (160.20.21.12) port 80 (#0)
> GET /jenkins HTTP/1.1
> Host: 160.20.21.12
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: nginx/1.23.3
Server: nginx/1.23.3
< Date: Fri, 20 Jan 2023 10:23:58 GMT
Date: Fri, 20 Jan 2023 10:23:58 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 153
Content-Length: 153
< Connection: keep-alive
Connection: keep-alive

<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.23.3</center>
</body>
</html>
* Connection #0 to host 160.20.21.12 left intact
```

**Comment by Tristan971** [comment]
Huh, then it presumably does run it as a hostNetwork pod indeed (that's a pretty sad default approach for it to take, but it's another topic I suppose). Unfortunately that doesn't help much with your problem if it works (but it's good to know).

To have logs with haproxy you'll want something like that (https://docs.haproxy.org/2.7/configuration.html#4.2-log is the relevant doc section):

```haproxy
global
    ...
    log stdout local0

defaults
    ...
    log global

frontend user_local
    ...
    option httplog
```

This should at least make haproxy send logs to its stdout (thus captured by journalctl if you run it with systemd) so you can see what it thinks it did

**Comment by mohanss08** [comment]
Have added my complete `/etc/haproxy/haproxy.cfg` file content in question section(Refer above). 

```
$ sudo haproxy -c -f /etc/haproxy/haproxy.cfg
Configuration file is valid
```
Also the below is my ` journalctl ` result.

```
$ sudo journalctl -u haproxy.service --since today --no-pager
-- Logs begin at Fri 2021-02-19 12:36:06 IST, end at Fri 2023-01-20 16:06:33 IST. --
Jan 20 14:18:56 LB haproxy[7527]: [WARNING]  (7527) : Exiting Master process...
Jan 20 14:18:56 LB systemd[1]: Stopping HAProxy Load Balancer...
Jan 20 14:18:56 LB haproxy[7527]: [NOTICE]   (7527) : haproxy version is 2.4.20-1ppa1~focal
Jan 20 14:18:56 LB haproxy[7527]: [NOTICE]   (7527) : path to executable is /usr/sbin/haproxy
Jan 20 14:18:56 LB haproxy[7527]: [ALERT]    (7527) : Current worker #1 (7529) exited with code 143 (Terminated)
Jan 20 14:18:56 LB haproxy[7527]: [WARNING]  (7527) : All workers exited. Exiting... (0)
Jan 20 14:18:56 LB systemd[1]: haproxy.service: Succeeded.
Jan 20 14:18:56 LB systemd[1]: Stopped HAProxy Load Balancer.
Jan 20 14:18:56 LB systemd[1]: Starting HAProxy Load Balancer...
Jan 20 14:18:56 LB haproxy[175050]: [NOTICE]   (175050) : New worker #1 (175052) forked
Jan 20 14:18:56 LB systemd[1]: Started HAProxy Load Balancer.
```

**Comment by Tristan971** [comment]
That's certainly odd. I'm unsure why you're not getting any logs; I take it this is the haproxy.debian.net PPA, so the log forwarding should work fine...

Guess I'm missing something here, hopefully someone else can chime in

**Comment by mohanss08** [comment]
Hi Tristan,

Indeed it was some issue with my `HAProxy VM` system side, So I had swapped the server and tried, its being working fine as expected.

Sorry for the inconvenience caused. Thanks a lot for your support.

**Comment by Tristan971** [comment]
No problem @mohanss08; if it's not confidential, it would be helpful to quickly summarise what was wrong so people running into this in the future can find the solution more easily as well

**Comment by mohanss08** [comment]
Sure Tristan, Here it is - In my previous `HAProy VM` server found that it was attached as Kubernetes node in another cluster master. So i suspect due to this it was unable to forward my project users request from HAProxy to my Kubernetes master.

Therefore i had installed HAprxoy in another(fresh VM) and configured the ` /etc/haproxy/haproxy.cfg` same as given above and in this able to communicate with my cluster application.

**Comment by Tristan971** [comment]
Hmmm, interesting. That's odd that it would result in no logs but thanks for noting it here 👍

**Comment by mohanss08** [comment]
Thank you!
