### ISSUE TITLE
Haproxy 2.7.1 fails to reload haproxy.cfg stored on glusterfs on HUP signal

### ISSUE THREAD

**Issue by aki-k** [haproxy/haproxy#2010]
### Detailed Description of the Problem

I'm using Haproxy 2.7.1 Docker image from Docker Hub. My haproxy.cfg configuration file resides on
Glusterfs storage.

I use a bind mount to mount the config file into the Docker container:

    volumes:
      - "/glusterfs_root/container_files/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:z"

This works ok but when sending the HUP signal to haproxy, I get the following error message:

[NOTICE]   (1) : Reloading HAProxy
[NOTICE]   (1) : haproxy version is 2.7.1-3e4af0e
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (1) : config : Cannot open configuration file/directory /usr/local/etc/haproxy/haproxy.cfg : Stale file handle
[WARNING]  (1) : Loading failure!

https://hub.docker.com/_/haproxy

> Reloading config
> 
> If you used a bind mount for the config and have edited your haproxy.cfg file, you can use HAProxy's graceful 
> reload feature by sending a SIGHUP to the container:
> 
> $ docker kill -s HUP my-running-haproxy
> 
> The entrypoint script in the image checks for running the command haproxy and replaces it with haproxy-systemd-wrapper
> from HAProxy upstream which takes care of signal handling to do the graceful reload. Under the hood this uses the -sf option
> of haproxy so "there are two small windows of a few milliseconds each where it is possible that a few connection failures will 
> be noticed during high loads" (see 
> [Stopping and restarting HAProxy](http://www.haproxy.org/download/2.3/doc/management.txt)).

### Expected Behavior

I'd like to reload the config with a minimum delay.

### Steps to Reproduce the Behavior

Here's my Docker compose file:

```
version: '3.7'

services:
  haproxy:
    image: haproxy:2.7.1
    environment:
      - container=docker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
    networks:
      - proxy
    ports:
      - "5235:5235"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0

    volumes:
      - "/glusterfs_root/container_files/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:z"

networks:
  proxy:
    name: proxy
    external: true
```

### Do you have any idea what may have caused this?

It's probably because of Glusterfs. I had the same thing happen with service config files for Traefik. 
Traefik wouldn't know how to live reload the service config files off Glusterfs.

### What is your configuration?

```haproxy
global
    log stdout format raw local0 debug
    log stdout format raw local1 debug
    tune.bufsize 16384

defaults
    log global
    option tcplog
    mode tcp
    timeout connect 30s
    timeout client 30s
    timeout server 7d
    timeout tunnel 7d
    option tcpka

frontend remote_ssh_5235
    mode tcp
    option clitcpka
    bind *:5235
    use_backend remote_ssh_5235_hosts
    log global

backend remote_ssh_5235_hosts
    mode tcp
    option srvtcpka
    server remote_5235 ip:5235
    log global
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.7.1-3e4af0e 2022/12/19 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2024.
Known bugs: http://www.haproxy.org/bugs/bugs-2.7.1.html
Running on: Linux 5.13.5-1.el7.elrepo.x86_64 #1 SMP Sat Jul 24 12:30:08 EDT 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -PTHREAD_EMULATION +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -OPENSSL_WOLFSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING +SHM_OPEN

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

The Docker nodes are CentOS 7. I have a three node Docker swarm cluster.

**Comment by Darlelet** [comment]
Hi,

"Cannot open configuration file/directory" error indicates that the `stat()` function call failed for a given path (could be a file or a directory, but in this case it is an absolute path to `/usr/local/etc/haproxy/haproxy.cfg`  according to the related haproxy Dockerfile).

Here it fails with "Stale file handle", which in this context (glusterfs or nfs), could mean that the "virtual" file
 `/usr/local/etc/haproxy/haproxy.cfg` (which is binded to your glusterfs node under the hood through docker) became unusable (for whatever reason)

Are you sure this is the correct way to combine glusterfs with docker? (I'm just wondering, I'm not a docker nor glusterfs expert)
At this point I don't think it has something to do with haproxy itself, but it could indicate some configuration or compatibility issues between docker and glusterfs.

I would suggest this test on the running container when you see that the reload fails:
```sudo docker exec -it my-running-haproxy stat /usr/local/etc/haproxy/haproxy.cfg```

If the stat call also fails from the docker-cli, then it means that the docker container is having trouble reliably using the upstream file from the glusterfs node.
(In which case, it would be interesting to see if binding the parent glusterfs directory instead of the full path to the file, ie: `/glusterfs_root/container_files/haproxy:/usr/local/etc/haproxy:z` helps somehow)

Anyway, if you need further assistance with that, feel free to open an issue on the docker/haproxy repository (https://github.com/docker-library/haproxy/issues) or glusterfs project since we're getting a bit off-topic here.

Thanks

**Comment by aki-k** [comment]
Thanks, changing the volume mount to

    volumes:
      - "/glusterfs_root/container_files/haproxy:/usr/local/etc/haproxy:z"

fixed it.
```
[NOTICE]   (1) : New worker (32) forked
[NOTICE]   (1) : Loading success.
[NOTICE]   (1) : haproxy version is 2.7.1-3e4af0e
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[WARNING]  (1) : Former worker (28) exited with code 0 (Exit)
```

**Comment by aki-k** [comment]
Fixed
