### ISSUE TITLE
2.0: "do-resolve" with IPV6 failed "set-dst"

### ISSUE THREAD

**Issue by pyhd** [haproxy/haproxy#202]
The bug is quite simple, so just keep it short:

```
frontend fe
    bind 10.0.0.1:80
    mode tcp
    tcp-request content do-resolve(txn.myip,mydns,ipv6) req.hdr(host),lower
    default_backend be

backend be
    mode tcp
    tcp-request content reject if { var(txn.myip) -m ip 127.0.0.0/8 10.0.0.0/8 }
    tcp-request content set-dst var(txn.myip)
    server clear 0.0.0.0:0
```

I read 2.0 post and tried "do-resolve" features as the example.  If `ipv6 `is prefered instead of `ipv4`, in backend 0.0.0.0:0 cannot handle this case. So I believe "set-dst" have not yet supported dual-stack, at least access from ipv4 to ipv6 cannot work.

**Comment by daniel-corbett** [comment]
I have found that the IPv6 equivalent of 0.0.0.0:0 to use would be :::0.  This works fine for me:

```
frontend fe
    bind :80
    mode http
    tcp-request content do-resolve(txn.myip,mydns,ipv6) req.hdr(host),lower
    default_backend be

backend be
    mode http
    option redispatch
    tcp-request content reject if { var(txn.myip) -m ip 127.0.0.0/8 10.0.0.0/8 }
    tcp-request content set-dst var(txn.myip)
    server clear1 :::0
```

If for some reason you want to have a backend with mixed ipv4 or ipv6 destinations I think something like the below work.  However, this may not be an ideal way of doing it.

```
backend be
    mode http
    option redispatch
    tcp-request content reject if { var(txn.myip) -m ip 127.0.0.0/8 10.0.0.0/8 }
    tcp-request content set-dst var(txn.myip)
    server clear1 :::0
    server clear2 0.0.0.0:0
```

**Comment by pyhd** [comment]
Thanks for your reference. The 2nd plan works for me a little, but not perfectly. Frequently "empty response" still came out from Chrome. Beforehand I just used NGINX in backend to handle this case(ipv4->ipv6/ipv4).

**Comment by kornaz** [comment]
Looks like this isn't fixed yet, not even in the latest stable 2.2.x. I've added a couple of use-server's to forward to the correct server by checking the address type. Works just fine, but I believe this shouldn't be necessary and should be fixed in Haproxy.

```
    use-server v4 unless { var(txn.dst_ip) -m sub ':' }
    use-server v6 if { var(txn.dst_ip) -m sub ':' }
    server v4 0.0.0.0:0
    server v6 :::0
```

**Comment by capflam** [comment]
Indeed, this should work natively. With this quick patch, it should work on the 2.0: 
```diff
diff --git a/src/backend.c b/src/backend.c
index dc13d3a3e..a95c2bdb6 100644
--- a/src/backend.c
+++ b/src/backend.c
@@ -897,8 +897,10 @@ int assign_server_address(struct stream *s, struct connection *srv_conn)
                        conn_get_to_addr(cli_conn);
 
                        if (cli_conn->addr.to.ss_family == AF_INET) {
+                               ((struct sockaddr_in *)&srv_conn->addr.to)->sin_family = AF_INET;
                                ((struct sockaddr_in *)&srv_conn->addr.to)->sin_addr = ((struct sockaddr_in *)&cli_conn->addr.to)->sin_addr;
                        } else if (cli_conn->addr.to.ss_family == AF_INET6) {
+                               ((struct sockaddr_in6 *)&srv_conn->addr.to)->sin6_family = AF_INET6;
                                ((struct sockaddr_in6 *)&srv_conn->addr.to)->sin6_addr = ((struct sockaddr_in6 *)&cli_conn->addr.to)->sin6_addr;
                        }
                }
```

But the same must be done on all versions. 

However in @pyhd snippet, in TCP mode, an inspect delay must be added to wait the HTTP request. But it is probably easier to use HTTP proxies and to rely on http-request rules instead.

**Comment by capflam** [comment]
It should be fixed now. Thanks for the reminder !
