### ISSUE TITLE
"Content-Length: 0" sent on HTTP health checks gives 400 Bad Request

### ISSUE THREAD

**Issue by jlecour** [haproxy/haproxy#2026]
### Detailed Description of the Problem

I've just moved from HAProxy 1.8 to 2.2 and with the same configuration I get health-check errors that I didn't get before.

I've found that an HTTP header `Content-Length: 0` is sent with the `HEAD`/`GET` check on HTTP.

When the upstream server is an AWS ELB, the request gets an `400 Bad request` error (reproductible with a simple `curl` command.

### Expected Behavior

I don't know if HAProxy is wrong to send ths header or if the AWS ELB proxy is wrong to reject the request, but there is definitely a chage in behaviour between 1.8 and 2.2.

[The workaround is](https://discourse.haproxy.org/t/bad-request-on-health-check-due-to-content-length-header/6588) to change to a TCP check that does the HTTP part manually :

```
option tcp-check
tcp-check comment send\ HTTP\ request
tcp-check send GET\ /status\ HTTP/1.0\r\n
tcp-check send User-Agent:\ Haproxy\ Health\ Check\r\n
tcp-check send \r\n
tcp-check expect rstring HTTP/1\..\ 200 comment check\ HTTP\ response
```

but this seems very strange to have to do this.

### Steps to Reproduce the Behavior

Create a backend with an http check

```
backend web
    balance roundrobin

    option httpchk HEAD /up
    server-template elb 2 elb-domain:80 check init-addr none resolvers mydns
```

### What is your configuration?

```haproxy
Debian 11 with official package.
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.9-2+deb11u3 2022/03/10 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
Running on: Linux 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -ffile-prefix-map=/build/haproxy-UmgAPI/haproxy-2.2.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```
```


### Last Outputs and Backtraces

_No response_

### Additional Information

_No response_

**Comment by capflam** [comment]
Indeed, it is not really elegant. The RFC says a client SHOULD NOT sends the content-length in this case.  It is not a MUST NOT. But it can easily be fixed. However, there is an issue with AWS ELB that must be reported too because there is nothing preventing a client to do the same.

**Comment by TimWolla** [comment]
> Debian 11 with official package.

Please note that with the official Debian package you will likely not receive the bugfix for this. I recommend using the haproxy.debian.net repositories. You will need to upgrade to 2.4 at least https://haproxy.debian.net/#distribution=Debian&release=bullseye&version=2.4 or even better to 2.6: https://haproxy.debian.net/#distribution=Debian&release=bullseye&version=2.6

**Comment by jlecour** [comment]
I'll keep my ugly tcp check for now.
I'll try to open an issue at AWS.

Thanks for the feedback.

**Comment by capflam** [comment]
Sorry for the delay. A fix was pushed. It will be backported when the pipe of pending fixes will be flushed. Thanks !

**Comment by edbighead** [comment]
@jlecour did you get answer from AWS? 

I found out that `Content-Length: 0` header requests does not comply with RFC 7230 and are classified as `Acceptable` in [docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#classification-reasons). When ELB has `Desync mitigation mode` set as `Strictest`, it blocks the `Acceptable` ones ([docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#desync-mitigation-mode))

**Comment by wtarreau** [comment]
I could understand that they classify a GET or HEAD with a body as "acceptable", since it's permitted but not universally handled, but considering that "content-length: 0" is "acceptable" (that I read as "suspicious") is strange IMHO, as it's perfectly valid, and even necessary when you need to send an empty POST for example.

**Comment by jlecour** [comment]
@edbighead As far as I can tell, I've never received a response from Amazon, or it got lost.
