### ISSUE TITLE
CPU consumption rises to double when updating

### ISSUE THREAD

**Issue by Josecbm90** [haproxy/haproxy#2028]
### Detailed Description of the Problem

I was using HAProxy version 1.8.31 on Ubuntu 14.04 (OpenSSL 1.0.1f), when trying to update HAProxy to version 2.6.8 I have detected how CPU consumption doubles.

I have tried different combinations, adapting the configuration, and it happens in all of them.

HAProxy 1.6.16 on Ubuntu 16.04 (OpenSSL 1.0.2g)
HAProxy 1.8.31 on Ubuntu 16.04 (OpenSSL 1.0.2g)
HAProxy 2.0.30 on Ubuntu 16.04 (OpenSSL 1.0.2g)
HAProxy 2.6.8 on Ubuntu 18.04 (OpenSSL 1.1.1)
HAProxy 2.6.8 on Ubuntu 20.04 (OpenSSL 1.1.1f) 
HAProxy 2.6.8 on Debian 11 (OpenSSL 1.1.1n)

### Expected Behavior

I expect that, if CPU consumption increases, at least not to double.

### Steps to Reproduce the Behavior

1. Two HAProxy ec2 behind AWS ELB
2. HTTPS load test (I used `vegeta` with `-rate=300`)
3. There is a big difference in CPU consumption 

### Do you have any idea what may have caused this?

It gives me the feeling that it may have to do with OpenSSL.

### Do you have an idea how to solve the issue?

No idea.

### What is your configuration?

```haproxy
global
    lua-load /usr/local/etc/haproxy/cors.lua
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon
    maxconn 60000

    # Logging
    log 127.0.0.1:5140 local0 # Fluentd agent
    log-send-hostname
    # log 127.0.0.1:514 local0 # Enable if logs are needed on syslog

    # SSL Labs A+ Rating Settings
    tune.ssl.default-dh-param 2048
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tls-tickets
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:RSA+AESGCM:!aNULL:!MD5:!DSS
    ssl-default-server-options no-sslv3 no-tlsv10 no-tls-tickets
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:RSA+AESGCM:!aNULL:!MD5:!DSS

    # Statistics
    stats socket /var/run/haproxy.sock mode 600 level admin
    stats timeout 2m

defaults
    log     global
    mode    http
    option  redispatch
    option  httpclose
    option  forwardfor
    option  dontlognull
    # option  httplog

    # log-format overrides previous 'option  httplog' and add X-Forwarded-For header capture
    log-format "%[capture.req.hdr(0)] %ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hs %[capture.req.hdr(1)] %{+Q}r"

    # Timeout settings
    # TODO: Review
    retries 3
    timeout connect 60s
    timeout client 90s
    timeout server 90s

    # Load Balancing algorithm.
    balance roundrobin

    # Error Files
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

    # Statistics
    stats enable
    stats uri /haproxy?stats
    stats realm Strictly\ Private
    stats auth xx:xx

userlist xx
    user xx insecure-password xx

resolvers awsvpc
    nameserver default xx.xx.xx.xx:xx
    resolve_retries       3
    timeout retry         1s
    hold valid           100ms

# Redirect all HTTP requests to HTTPS
frontend www-http
    bind 0.0.0.0:80
    redirect scheme https code 301 if !{ ssl_fc }

    # Capture IPs from header X-Forwarded-For
    capture request header X-Forwarded-For len 128
    # Capture header referer
    capture request header referer len 256

frontend www-https
    bind 0.0.0.0:443 ssl crt /etc/haproxy/certs/xxx.pem
    maxconn 60000
    default_backend xxx

    # Capture IPs from header X-Forwarded-For
    capture request header X-Forwarded-For len 128
    # Capture header referer
    capture request header referer len 256

    { ... multiples acls and redirects ... }

{ ... some backends config ... }
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.8-1ppa1~focal 2023/01/24 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.8.html
Running on: Linux 5.15.0-1028-aws #32~20.04.1-Ubuntu SMP Mon Jan 9 18:02:08 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-poansH/haproxy-2.6.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -QUIC +RT +SLZ -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

Left: HAProxy 1.8.31 on Ubuntu 14.04
Right: HAproxy 2.6.8 on Ubuntu 20.04

`htop` with the same load test

![image](https://user-images.githubusercontent.com/110654890/216382289-8b99b061-24fb-4956-af05-cf83f96dcd2d.png)

`perftop` with the same load test

![image](https://user-images.githubusercontent.com/110654890/216383938-44fe9406-0668-449e-9442-9737fe487102.png)

**Comment by wtarreau** [comment]
Hello,

sorry for the slow response, I wanted to respond last week but failed. I've spent some time looking at your captures, and strangely, "perf top" doesn't seem to indicate much time spent in haproxy, everything included. One could think that the crypto part counts a bit, but it's not easy to say either. We did notice a marginal CPU increase between 1.0.2 and 1.1.x caused by the switch of application-provided locks to pthread_rwlocks. If you have the ability to test it, it would be great to run the same test with 2.6.8 on 14.04. It's very possible that it would use a little bit more CPU but I would like to sort out the part that is caused by haproxy and the part caused by libssl or anything else.

**Comment by Josecbm90** [comment]
As is logical, you do not offer a version, or at least I cannot find it, of HAProxy 2.x for Ubuntu 14.04.

I'm trying to force that version by compiling it, but I can't, when compiling and installing I find all kinds of problems.

I don't know if there is any way for you to help me with this or if there is an easier way that I don't know about, in the meantime I'll keep trying to give you this feedback.

Thanks in advance

**Comment by wtarreau** [comment]
Please do not hesitate to share the problems you're facing when compiling and/or installing. What I would suggest, is to build using the same options as used on the recent distros' package:
```
$ make -j$(nproc) TARGET=linux-glibc CPU=generic USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
```
then you should be able to use the resulting "haproxy" binary as a replacement for the other one. I suggest not to install it and instead just to start it using the same options the existing process is currently using (e.g. check with `ps auxww|grep haproxy` and start `./haproxy -f ...` the same way after stopping the other one).

If you notice that it doesn't use as much CPU on this older distro, this could further confirm a relation with the performance degradatio caused by the locking changes in openssl 1.1. Then I could guide you on trying 2.7 on the newer distro and letting haproxy work around this by providing its own locks to it, and verify if this has any impact.

**Comment by Josecbm90** [comment]
Thanks for the tips, I managed to do that test, I copy the results below.

The performance has gotten even worse when using HAProxy 2.6.8 on Ubuntu 14.04 with OpenSSL 1.0.1f

Left: 2.6.8 on Ubuntu 14.04
Right: 2.6.8 on Ubuntu 20.04

`haproxy -vv`
![image](https://user-images.githubusercontent.com/110654890/217231977-152ae7ce-9ae8-4965-90d1-54e56eb6cd42.png)

`htop`
![image](https://user-images.githubusercontent.com/110654890/217230547-8aa79ee3-598a-4f1e-8a2e-5b807ba80c75.png)

`perf top`
![image](https://user-images.githubusercontent.com/110654890/217230967-b3ce1b09-c00f-4410-a624-e194bff2cc76.png)

**Comment by Josecbm90** [comment]
After the latest results, my brain really locked up because I was 99% sure it was related to OpenSSL.

That's when I fell into another change that I had overlooked, in the tests between different versions I was using a different certificate for the HTTPS frontend.

The first one, which gave good performance, was generated with Let's Encrypt and the second was a self-generated certificate with OpenSSL.

I don't know if this information is of any use to you, if it can be considered a bug or the behavior is normal, in my case the incident is over, I have recovered the performance of HAProxy.

For any other information I can give you, I'll keep an eye on the thread until you close it.

Thank you so much.

**Comment by wtarreau** [comment]
That's particularly weird. I'm not that familiar with the htop output, I would have thought that the two processes listed are two threads of the same process, except that one of them of the left is at 117%, meaning it cannot be a single thread. So I'm a bit confused about what we're observing. Also I still don't understand why perf top seems to show only functions exhibiting a very low CPU usage, all in the crypto stuff. There's something really odd there, we should be seeing CPU usage eaten somewhere else.

**Comment by Josecbm90** [comment]
We posted at the same time, I post again to ensure you see my last reply.

**Comment by wtarreau** [comment]
Ah we responded at the same time :-)

Your discovery is interesting. So you remember what parameters you used for that self-generated certificate ? Maybe it has a very large key that costs a lot in terms of crypto operations ?

**Comment by Josecbm90** [comment]
The differences I can see is that the length of the self signed private key is doubled and it is RSA while the other is not.

I don't know if this info will be enough, I was generating it with Ansible, the specific playbook part looks like this:

```
- name: Create an OpenSSL private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: /etc/haproxy/certs/xxx.key
    owner: xxx
    group: xxx
    mode: '644'

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: /etc/haproxy/certs/xxx.crt
    privatekey_path: /etc/haproxy/certs/xxx.key
    provider: selfsigned
    selfsigned_not_after: "+36500d"
    owner: xxx
    group: xxx
    mode: '644'
  
- name: combine certs
  shell: |
    cat /etc/haproxy/certs/xxx.crt /etc/haproxy/certs/xxx.key > /etc/haproxy/certs/xxx.pem
```

**Comment by wtarreau** [comment]
OK so RSA4096 can be quite CPU intensive already. Also, if the original one is not RSA, it is using ECDSA and is very light in terms of CPU usage, which can definitely explain that big a difference.

**Comment by Josecbm90** [comment]
Completely.

Nothing else on my part, I close the thread as completed.

Thank you for guiding me and helping me so quickly and efficiently.

**Comment by wtarreau** [comment]
You're welcome, I also prefer when issues end up requiring no fix like here ;-)
