### ISSUE TITLE
A way for HAproxy to send the client IP to Exchange in TCP mode

### ISSUE THREAD

**Issue by 02dag** [haproxy/haproxy#2029]
### Your Feature Request

I would like a possibility to send the client IP to Exchange when load balancing SMTP.

Send-proxy is not supported by Exchange

### What are you trying to do?

I am trying to load balance SMTP connections for Exchange through HAproxy. This works but HAproxy is sending its proper IP and not the client IP to Exchange. Send-proxy is not supported by Exchange.

Other options like forwardfor only works in http mode and that wont cut it for SMTP

### Output of `haproxy -vv`

```plain
HAProxy version 2.7.1-1ppa1~jammy 2022/12/19 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2024.
Known bugs: http://www.haproxy.org/bugs/bugs-2.7.1.html
Running on: Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_OT=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -PTHREAD_EMULATION +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -OPENSSL_WOLFSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS +OT -QUIC +PROMEX -MEMORY_PROFILING +SHM_OPEN

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[  OT] opentracing
	[SPOE] spoe
	[TRACE] trace
```

**Comment by git001** [comment]
Looks like you would like tho have the feature [XCLIENT](https://www.postfix.org/XCLIENT_README.html) for smtp protocol. This implies that HAProxy understand SMTP and add this to the SMTP Protocol, which is not yet implemented but patches are welcome  :smile: . It is also required that the SMTP client (Server , Mail Client, Library, ... ) understand the `250-XCLIENT NAME ADDR PROTO HELO` response from the server. I don't know it the Outlook Client or any other Client handle that response header properly.

Do MS Exchange support the XCLIENT feature?  
Have you asked Microsoft for a suggested solution for that Problem?

**Comment by 02dag** [comment]
No, I have not heard that MSExchange support this. I dont think they(MS) will plan for supporting this at all in the forseeable future, since they already have a client/server solution that works and uses mapi to communicate.

Why implement XCLIENT when noone else supports it?

**Comment by git001** [comment]
> I would like a possibility to send the client IP to Exchange when load balancing SMTP.

[MAPI](https://en.wikipedia.org/wiki/MAPI) is not SMTP, the original Question was about SMTP, not MAPI. The only way in SMTP to get original client is the [XCLIENT](https://www.postfix.org/XCLIENT_README.html) extention, afaik.

**Comment by 02dag** [comment]
Yes the question was about smtp and it still is ,but you start talking about something that noone is supporting anyway. And the suggestion that haproxy will someday support it wont help anyone.

**Comment by lukastribus** [comment]
You can put haproxy in transparent mode and use it as default-gateway. It's a complex setup, but possible.

There are no other options.
