### ISSUE TITLE
About BoringSSL to build HAProxy  problem

### ISSUE THREAD

**Issue by ghost** [haproxy/haproxy#203]
At present, the version of HAProxy I use is v2.1-dev1, but I find that there are some minor problems in the process of building HAProxy v2.1-dev1 through BoringSSL. Because I am a novice and know little about the code, I hope my friends can help solve the problem.

In order to demonstrate again where the problem was wrong, I listed the whole process.

First install the dependencies needed to build boringssl
```
$ apt-get install cmake golang software-properties-common ninja-build
```
Download BoringSSL v2.1-dev1 source code
```
$ git clone https://boringssl.googlesource.com/boringssl
```
Enter the boringssl source directory, create a build directory, and enter the build directory
```
$ cd ~/boringssl && mkdir build && cd build
```
Generating makefile by cmake
```
$ cmake -GNinja ..
```
Build with Ninja
```
$ ninja
```
Return to the boringssl source directory
```
$ cd ..
```
Create a boringssl directory in the `/opt` directory, as well as the `/optboringssl/lib` directory.
```
$ mkdir /opt/boringssl /opt/boringssl/lib
```
Copy the include and required Lib in the boringssl directory to the`opt/boringssl`directory
```
$ cp -r include /opt/boringssl
$ cp build/ssl/libssl.a build/crypto/libcrypto.a /opt/boringssl/lib
```

Execute the following statement for compilation
```
$ make -j $(nproc) TARGET=linux-glibc USE_OPENSSL=1 SSL_INC=/opt/boringssl/include SSL_LIB=/opt/boringssl/lib
```

The current mistake lies in
```
root@korea:~/haproxy-2.1-dev1# make -j $(nproc) TARGET=linux-glibc USE_OPENSSL=1 SSL_INC=/opt/boringssl/include SSL_LIB=/opt/boringssl/lib
  CC      src/ev_poll.o
In file included from include/types/listener.h:29:0,
                 from include/types/global.h:32,
                 from src/ev_poll.c:26:
include/common/openssl-compat.h:184:19: error: conflicting types for ‘EVP_PKEY_base_id’
 static inline int EVP_PKEY_base_id(EVP_PKEY *pkey)
                   ^~~~~~~~~~~~~~~~
In file included from /opt/boringssl/include/openssl/pem.h:64:0,
                 from /opt/boringssl/include/openssl/ssl.h:149,
                 from include/common/openssl-compat.h:7,
                 from include/types/listener.h:29,
                 from include/types/global.h:32,
                 from src/ev_poll.c:26:
/opt/boringssl/include/openssl/evp.h:928:20: note: previous declaration of ‘EVP_PKEY_base_id’ was here
 OPENSSL_EXPORT int EVP_PKEY_base_id(const EVP_PKEY *pkey);
                    ^~~~~~~~~~~~~~~~
Makefile:835: recipe for target 'src/ev_poll.o' failed
make: *** [src/ev_poll.o] Error 1
```

Since I don't know anything about code, I can only edit the openssl-compat.h file, remove the following code, save it and compile it again.
```
$ vim /include/common/openssl-compat.h +183

#ifdef OPENSSL_IS_BORINGSSL
/*   remove it
	static inline int EVP_PKEY_base_id(const EVP_PKEY *pkey)
	{
		return EVP_PKEY_type(pkey->type);
	} */
#endif
```

I compiled again and found that there was no prompt for the error, but I seem to have removed this section which seems to be a security hazard, but I don't know what to do.

Get more details about haproxy through `haproxy-vv'.
```
root@korea:~/haproxy-2.1-dev1# haproxy -vv
HA-Proxy version 2.1-dev1 2019/07/16 - https://haproxy.org/
...
Built with OpenSSL version : BoringSSL
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
...
```

I hope to know how to solve a friend can tell me how to deal with it, because I think the parameters I deleted may have hidden dangers to safety, I hope you can help me ~

**Comment by wtarreau** [comment]
Hello,

be careful with BoringSSL, it purposely has an unstable API and is known for regularly breaking application. The problem you reported appeared yesterday with a code change on their side (they adopted a new function already present in other SSL libs) and thus broke haproxy which redefined it for boringssl. It was already fixed this morning.

Thus given that you're using a git version of BoringSSL, you should use a git version of haproxy. If you pull the latest master, this problem is already solved.

**Comment by wdauchy** [comment]
Hello @bigman-rgb 
If you use the last HEAD from the git it should be fixed with http://git.haproxy.org/?p=haproxy.git;a=commit;h=f580d0f3918b31d2b3b3d99c99d120d46c712d2f

**Comment by ghost** [comment]
> Hello,
> 
> be careful with BoringSSL, it purposely has an unstable API and is known for regularly breaking application. The problem you reported appeared yesterday with a code change on their side (they adopted a new function already present in other SSL libs) and thus broke haproxy which redefined it for boringssl. It was already fixed this morning.
> 
> Thus given that you're using a git version of BoringSSL, you should use a git version of haproxy. If you pull the latest master, this problem is already solved.

Ok, I will try again.

**Comment by ghost** [comment]
> Hello,
> 
> be careful with BoringSSL, it purposely has an unstable API and is known for regularly breaking application. The problem you reported appeared yesterday with a code change on their side (they adopted a new function already present in other SSL libs) and thus broke haproxy which redefined it for boringssl. It was already fixed this morning.
> 
> Thus given that you're using a git version of BoringSSL, you should use a git version of haproxy. If you pull the latest master, this problem is already solved.

I have re-downloaded the source code via git, and I have successfully solved the problem. Thank you very much!

**Comment by wtarreau** [comment]
You're welcome, thanks for confirming!
