### ISSUE TITLE
HAProxy stop removing expired sessions in stick table at some time

### ISSUE THREAD

**Issue by alekseyp-amzn** [haproxy/haproxy#2034]
### Detailed Description of the Problem

HAProxy stop removing expired records in stick table. It happens regularly and depends on current time and date. 
For example, last issues were about 02/09/22 20:48 UTC,  22/10/22 13:51 UTC, 11/12/22 06:54 UTC and 29/01/23:56 UTC

![stick_table_bad_02_09_22_20_48](https://user-images.githubusercontent.com/124629497/217087762-025da9d6-a386-4fdd-81e4-6712bb0791b6.png)
![stick_table_bad_01_29_23_23_56](https://user-images.githubusercontent.com/124629497/217087828-e6223f4f-01f7-4a8d-af99-7a659a690ed6.png)

To fix this issue we need to clear stick table manually (however, it does not work if we have multiple HAProxy with stick table peering) or restart HAProxy. This issue does not depend on HAProxy start time, so it does not make sense to restart HAProxy before the issue.

### Expected Behavior

stick-table entries are removed when they expire

### Steps to Reproduce the Behavior

To reproduce this issue we need some set of unique conditions:
- exact date and time
- requests with random stick keys for the records, besides this, some keys have to be repeatable during stick table expiration time. It is not reproducible for monotonously increasing or decreasing stick record's keys.

HAProxy configuration file:
```
global
    maxconn         1000
    stats socket    /tmp/haproxy.stat mode 600 level admin
    log             /dev/log local0 info
    pidfile         /tmp/haproxy.pid
    daemon

defaults
    timeout connect 5s
    timeout server  30s
    timeout queue   30s
    timeout client  30s

frontend test
    mode            http
    bind            0.0.0.0:8081
    http-request return status 200 content-type "text/plain" string "Hi"

frontend f
    bind            *:8080
    mode            http
    log             global
    option          httplog

    default_backend b

backend b
    mode            http
    balance         roundrobin
    option httpchk  HEAD /

    stick-table type integer size 1m expire 600s srvkey addr
    stick on urlp_val(key) table b

    server          srv1 127.0.0.1:8081 check inter 1000
    server          srv2 127.0.0.2:8081 check inter 1000
    server          srv3 127.0.0.3:8081 check inter 1000
    server          srv4 127.0.0.4:8081 check inter 1000
```
Example of requests generating script:
```
#!/bin/env python3
 
import random
import time
import requests
 
def get_key():
    # it generates about 6000 (300 * 20) unique keys
    key = random.randrange(20000,300000000,1000000) + random.randrange(1, 21, 1)
 
    return key
 
while True:
    r = requests.get(url = "http://127.0.0.1:8080/", params = {'key': get_key()})
    print(r)
    time.sleep(0.5)
```
- change system date to 06:40:00 UTC 11/12/2022 :  `date -s "22-12-11 06:40:00"`
- start HAProxy
- start requests generation script
- monitor number of records in stick table: `echo "show table" | socat /tmp/haproxy.stat - `
- the issue will be observed in 15 minutes, about 06:55:00 UTC 11/12/2022 and continue until HAProxy is not restarted or stick table is not cleared
- the issue is also fixed in 10 minutes after stopping request generating script

### Do you have any idea what may have caused this?

As the one of condition for the problem is exact time and date, we need to analyze what are special in these moments. The issues were at 02/09/22 20:48 UTC,  22/10/22 13:51 UTC, 11/12/22 06:54 UTC.

Unix timestamp representation for these moments are:

02/09/22 20:48 UTC - 1662151680 seconds - 1662151680000 milliseconds - 0x182FFF5E000
22/10/22 13:51 UTC - 1666446660 seconds - 1666446660000 milliseconds - 0x183FFF611A0
11/12/22 06:54 UTC - 1670741640 seconds - 1670741640000 milliseconds - 0x184FFF64340

We can notice that in all these dates in the milliseconds timestamp representation last 32 bit value is close to 0xFFFFFFFF. Actually these dates lag behind 0xFFFFFFFF by around 600 seconds - the stick table expiration time.

Based on it, we can suppose the issue is related with integer overflow when 32 bit unsigned integer value pass from 0xFFFFFFFF to 0x00000000.

Further investigation shows that HAProxy uses ticks to simplify time calculation and comparison. Tick is a representation of a date relative to another one, and is measured in milliseconds. Ticks are stored in 32 bit signed integers and this is enough to handle dates that are between 24.85 days in the past and as much in the future.

HAProxy uses ticks to check stick session expiration time, and keeps stick session expiration timestamp in elastic binary tree to speed up the processing. Moreover, HAProxy uses expiration timestamp as a key for elastic binary tree. According the source code, elastic binary tree key is a 32 bit unsigned integer.

To work with ticks (addition, subtraction, comparison) set of functions are provided which use signed integers to avoid integer overflow. However, in function `process_table_expire` we have direct comparison for unsigned integers (https://git.haproxy.org/?p=haproxy-2.4.git;a=blob;f=src/stick_table.c;h=becca299aef448c432ade7d183602bfc387178e1;hb=HEAD#l608). 

According this code:
```
if (!eb || eb->key > ts->exp.key)
    eb = &ts->exp;
```
we can run into the situation when `eb->key` (next possibly expired record) can have value bigger than `ts->exp.key` (currently checked record) even if `eb->key` is expired before `ts->exp.key`. And as a result, we schedule the next task wake up to the time much later than the next record expiration time and stop processing all records with `eb->key` more than 0xFFF6D83F (4294967295 - 600000). Moreover, it also breaks the further record processing as we constantly have the keys between 0xFFF6D83F and 0xFFFFFFFF.

### Do you have an idea how to solve the issue?

To fix the issue, I suggest to:
- use ticks functions instead of direct keys comparison. 
- pay additional attention to edge condition when `eb` is NULL. in this case we have to revisit current record only if we reached the end of right part of EBT or it is the latest record in stick table.

Suggested patch:
```
From fe92d597ac04fd1635034adbccf2da4b69f081dc Mon Sep 17 00:00:00 2001
From: Aleksey Ponomaryov <alekseyp@amazon.com>
Date: Mon, 6 Feb 2023 22:58:55 +0000
Subject: [PATCH] BUG/MINOR: stick_table: expired stick table entries stop
 being removed

At some moments expired stick table records stop being removed.
It happens due to direct comparison between unsigned integers
and integer overflow when HAProxy checks expired records in stick table,
which in turn can lead to skipping expired records in stick table.

Change this by using ticks function tick_is_le to compare time values
to avoid processing the records that expire later than the current one.

Moreover, this change checks condition when we have to revisit
current record only if we reached the end of right part of EBT
or it is the latest record in stick table.

This should be backported up to 2.7.
---
 src/stick_table.c | 18 ++++++++++++++----
 1 file changed, 14 insertions(+), 4 deletions(-)

diff --git a/src/stick_table.c b/src/stick_table.c
index 09c7c7431..65b0c87e5 100644
--- a/src/stick_table.c
+++ b/src/stick_table.c
@@ -218,8 +218,9 @@ int __stktable_trash_oldest(struct stktable *t, int to_batch)
        int max_search = to_batch * 2; // no more than 50% misses
        int batched = 0;
        int looped = 0;
+        unsigned int look_back_ms = now_ms - TIMER_LOOK_BACK;

-       eb = eb32_lookup_ge(&t->exps, now_ms - TIMER_LOOK_BACK);
+       eb = eb32_lookup_ge(&t->exps, look_back_ms);

        while (batched < to_batch) {

@@ -257,8 +258,12 @@ int __stktable_trash_oldest(struct stktable *t, int to_batch)
                        ts->exp.key = ts->expire;
                        eb32_insert(&t->exps, &ts->exp);

-                       if (!eb || eb->key > ts->exp.key)
+                       if (!eb) {
+                               if (looped || ts->exp.key >= look_back_ms)
+                                       eb = &ts->exp;
+                       } else if (tick_is_le(ts->exp.key, eb->key)) {
                                eb = &ts->exp;
+                       }

                        continue;
                }
@@ -657,9 +662,10 @@ struct task *process_table_expire(struct task *task, void *context, unsigned int
        struct eb32_node *eb;
        int looped = 0;
        int exp_next;
+        unsigned int look_back_ms = now_ms - TIMER_LOOK_BACK;

        HA_RWLOCK_WRLOCK(STK_TABLE_LOCK, &t->lock);
-       eb = eb32_lookup_ge(&t->exps, now_ms - TIMER_LOOK_BACK);
+       eb = eb32_lookup_ge(&t->exps, look_back_ms);

        while (1) {
                if (unlikely(!eb)) {
@@ -699,8 +705,12 @@ struct task *process_table_expire(struct task *task, void *context, unsigned int
                        ts->exp.key = ts->expire;
                        eb32_insert(&t->exps, &ts->exp);

-                       if (!eb || eb->key > ts->exp.key)
+                       if (!eb) {
+                               if (looped || ts->exp.key >= look_back_ms)
+                                       eb = &ts->exp;
+                       } else if (tick_is_le(ts->exp.key, eb->key)) {
                                eb = &ts->exp;
+                       }
                        continue;
                }

--
```

### What is your configuration?

```haproxy
global
    daemon
    maxconn         10000
    hard-stop-after 600s
    server-state-file var/run/haproxy_server_state

defaults
    log global
    mode http
    option httplog
    option http-buffer-request
    load-server-state-from-file global

    timeout connect 1s
    timeout client 300s
    timeout server 2s

peers haproxy
    peer ip-10-0-42-245 10.0.42.245:18080
    peer ip-10-0-60-178 10.0.60.178:18080
    peer ip-10-0-62-59 10.0.62.59:18080
    peer ip-10-0-63-250 10.0.63.250:18080

frontend frontend
    bind 0.0.0.0:8443 ssl crt var/etc/tls.pem
    mode http
    default_backend backend

backend backend
    acl calls path_beg /calls
    acl active_call path_reg ^/test/\d+/active_call$
    acl message path_beg /message

    balance roundrobin
    mode http

    stick-table type integer size 10m expire 600s peers haproxy srvkey addr
    stick on req.body,json_query('$.id',"int") table backend if calls
    stick match capture.req.uri,field(4,/) table backend if active_call
    stick match req.body,json_query('$[0].message.id',"int") table backend if message

    option httpchk GET /live HTTP/1.1
    http-check send hdr Host localhost
    http-check expect rstatus ^200

    default-server inter 2s fall 3 rise 1 weight 100 init-addr last,libc,none
    server-template server 12000 localhost:8443 disabled ssl verify none check
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.20 2022/12/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.20.html
Running on: Linux 4.14.301-224.520.amzn2.x86_64 #1 SMP Fri Dec 9 09:57:03 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = x86_64-pc-linux-gnu-gcc
  CFLAGS  = -Wchar-subscripts -Wcomment -Wformat -Winit-self -Wmain -Wmissing-braces -Wno-pragmas -Wparentheses -Wreturn-type -Wsequence-point -Wstrict-aliasing -Wswitch -Wtrigraphs -Wuninitialized -Wunknown-pragmas -Wunused-label -Wunused-variable -Wunused-value -Wno-error=missing-include-dirs -Wno-error=narrowing -Wpointer-sign -Wimplicit -pthread -fdiagnostics-color=auto -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -msse -mfpmath=sse -march=core2 -g -fPIC -g-Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.0.2zf  21 Jun 2022
Running on OpenSSL version : OpenSSL 1.0.2zf  21 Jun 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.4.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

### Additional Information

This issue can be related to issues #2024 and #2025

**Comment by wtarreau** [comment]
Hi Aleksey,

nice analysis, thank you. When I saw the dates you reported, my first thought was "wow this looks dangerously close to 49.7 days between incidents" and indeed it was! I think we could further simplify the test on top of your patch, because I'm not thinking about a valid case for direct key comparison (though I don't have that code in mind and it could be related to the loop's construct; we should compare with wake_expired_tasks() that does it correctly).

One thing I wanted to do a few years ago when we faced the last time-wrap issue was to start the internal clock 5 seconds before rollover, hoping that it would expose such anomalies immediately. But nothing was ever done in this regard. Stick tables entries could probably take a bit more than 5 seconds to be created so maybe we should start at 30s or so, but I would really like to see that done anyway.

**Comment by wtarreau** [comment]
While I understand in which situation this problem may trigger (penultimate element in the tree having been updated and upshed to a lower exp value than the last one), the problem I'm having is that for the bug to trigger it seems that a forced purge needs to happen, and your graphs do not suggest that at all since you're getting full as a consequence of the bug and not as a starting condition for the bug to happen. And indeed, I couldn't trigger it at all in latest versions, even after forcing the time to wrap at boot a little bit after the first entries expire, because either we never go to trash_oldest or we look up the next entry to expire when entering the function, which will ultimately catch the skipped ones.

Did you actually check that with your fix the problem reliably disappeared ? If so, I suspect it's due to another one still sticking somewhere.

One thing I'm suspecting instead is that in 2.4 we're storing the exp_next into the table and using it to restart the purge task. And this exp_next is taken directly from eb->key which may be in the past, and I'm wondering if instead we're not failing to reschedule the purge task at some point.

**Comment by wtarreau** [comment]
In fact the test is not correct for another case: the entry being looked up is the last one and was refreshed to a wrapping date, while the next one is NULL. After updating the entry it will automatically be used for the subsequent lookup, ignoring all those before for the first turn. But again, subsequent calls will collect them thanks to the look back offset and the eb_first(). So I really think that it has something to do with the expiration task itself.

**Comment by wtarreau** [comment]
I finally understand what is exactly happening. It's a bit between both of our suggestions :-)

In fact the problem is that when picking the elements from the right side of the window, indeed we continue from the last picked one instead of the next one in the list ending up skipping the tail of the window. But it's not entirely lost, only *one* of them will be picked per wakeup period. What's horrible here is that the larger the table's expire, the rarer the wakeups and the more entries in the window. So if you have 10k elements in the last 15 minutes and your task wakes up every 15 minutes (due to the newly updated wakeup value), you'll end up needing 100 days to purge the tail. I did manage to reproduce this in 2.4 with a 15s table expiry and a date starting 20s in the past. I'm using two clients in parallel, one constantly refreshing the same entry and another one accessing random entries. I can see the same effect as you see, where when getting close to the end of the window, the table grows to its maximum cardinality.

I think the tick_is_expired() test is sufficient though, I don't see why the test on the "looped" element would be needed. I'll test with that in mind.

**Comment by wtarreau** [comment]
OK this one works for me and covers all cases we're interested in:
```
-                       if (!eb || eb->key > ts->exp.key)
+                       /* the update might have jumped beyond the next element,
+                        * possibly causing a wrapping. We need to check whether
+                        * the next element should be used instead. If the next
+                        * element doesn't exist it means we're on the right
+                        * side and have to check the first one then. If it
+                        * exists and is closer, we must use it otherwise, we
+                        * use the current one.
+                        */
+                       if (!eb)
+                               eb = eb32_first(&t->exps);
+
+                       if (!eb || tick_is_lt(ts->exp.key, eb->key))
                                eb = &ts->exp;
+
                        continue;
                }
```

Of course the same must be done in both functions. I'm going to reuse part of your commit message description since it's fairly complete and will possibly adjust a few elements based on the latest observations. Please just confirm me you're OK with me keeping you as the patch's author, @alekseyp-amzn .

**Comment by alekseyp-amzn** [comment]
Hi Willy,

thank you for checking it. I agree, your final patch is simpler and more straight forward. 
And yes, I do not mind to keeping me as patch's author :-)

**Comment by wtarreau** [comment]
Perfect, I'm going to do that, then, thanks!

**Comment by wtarreau** [comment]
Now pushed, we'll still have to backport it but for -dev it's fixed already!
