### ISSUE TITLE
Request for Precompiled Binaries

### ISSUE THREAD

**Issue by ghost** [haproxy/haproxy#2036]
### Your Feature Request

I'd like to see an easier installation process via the use of precompiled binaries which don't require third party utilities like make, etc.

This would make it easier for beginners to get involved with HAProxy as even for an advanced user like myself, the installation documents are off-putting.

### What are you trying to do?

//

### Output of `haproxy -vv`

```plain
//
```

**Comment by lukastribus** [comment]
See #1800 

https://github.com/haproxy/haproxy/issues/1800#issuecomment-1194451341

**Comment by wtarreau** [comment]
I think it's fine to close it since it's a duplicate, given that the responses in the linked thread perfectly match the request.

**Comment by lukastribus** [comment]
I thought I closed it, this new GH button always confuses me.

**Comment by wtarreau** [comment]
Ah I'm not surprised, I'm always extra careful not to click the wrong one!
