### ISSUE TITLE
agent-check should allow set backend weight and up/down in one response

### ISSUE THREAD

**Issue by taleintervenor** [haproxy/haproxy#2039]
### Your Feature Request

We have tested the latest version (1.5.18) of haproxy in CentOS stream repo. It seems agent-check not accpet agent response with both up/down notify and weight percent (for example "up\n" along with "50%\n"). And it also don't regard weight percent response as node up message. So, after a backend node was marked DOWN, we have to send UP response at first and then send the weight update reponse.
But the problem is, agent on backend don't know what its node's current state is in haproxy server's view. For example, the agent on NODE_A has sent an "up\n" response, but server not received it due to some network problem. So server still think NODE_A is DOWN while agent expect it had known this node's up. Then agent will move on to update its weight during following agent-check request, which all messed up.
Since agent cannot actively notify the haproxy server its node's state, nor can it get server's backend node state view, it should be necessarily to permit agent to send full description of its node state in one response.

### What are you trying to do?

Consider the case where agent is responsible for both updating backend node's weight and checking node's availability.
Haproxy server should accept reponse like "up\n50%\n", or respect "50%\n" response hint the node's up. So agent can correct the node state in server's view at any state, even if some check communication lost or not worked as expected.

### Output of `haproxy -vv`

```plain
HA-Proxy version 1.5.18 2016/05/10
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 8192, maxpollevents = 200

Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.7
Compression algorithms supported : identity, deflate, gzip
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
Built with PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
```

**Comment by capflam** [comment]
I already woks. It is possible but you should not use a `\n` as separator but a space a tab or a comma.
