### ISSUE TITLE
About OpenSSL 1.1.1c problems when building haproxy

### ISSUE THREAD

**Issue by ghost** [haproxy/haproxy#204]
The current build problem is that OpenSSL 1.1.1c compiles haproxy with the following error.
```
/opt/openssl-1.1.1c/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
Makefile:826: recipe for target 'haproxy' failed
make: *** [haproxy] Error 1
```

The process is as follows:
Compile opeenssl：
```
wget https://github.com/openssl/openssl/archive/OpenSSL_1_1_1c.tar.gz && tar xzvf OpenSSL_1_1_1c.tar.gz
cd ~/openssl-OpenSSL_1_1_1c
./config --prefix=/opt/openssl-1.1.1c no-shared
sudo make && sudo make install_sw
```
Compile haproxy：
```
git clone https://github.com/haproxy/haproxy.git
cd haproxy
make -j $(nproc) TARGET=linux-glibc \
    USE_OPENSSL=1 SSL_LIB=/opt/openssl-1.1.1c/lib SSL_INC=/opt/openssl-1.1.1c/include
```
But after compiling, I found the following error, how can I solve it?
```
/opt/openssl-1.1.1c/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
Makefile:826: recipe for target 'haproxy' failed
make: *** [haproxy] Error 1
```

**Comment by wtarreau** [comment]
I'm seeing that you build openssl with "no-shared", but haproxy 1.8 and above enable threads, so you need a thread-aware version of openssl. Please retry without "no-shared".

**Comment by ghost** [comment]
> I'm seeing that you build openssl with "no-shared", but haproxy 1.8 and above enable threads, so you need a thread-aware version of openssl. Please retry without "no-shared".

Currently, openssl1.1.1 only supports tls1.3. I tested the 1.1.0 version to compile normally, but I need tls1.3. How can I solve it?

**Comment by ghost** [comment]
> I'm seeing that you build openssl with "no-shared", but haproxy 1.8 and above enable threads, so you need a thread-aware version of openssl. Please retry without "no-shared".

I tried ./config --prefix=/opt/openssl-1.1.1c shared, but found that it compiles normally, but via haproxy -v it will prompt the lack of libssl.so.1.1 and libcrypto.so.1.1

Aug 01 08:53:12 korea.vps.com haproxy[23190]: /usr/sbin/haproxy: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (requi
Aug 01 08:53:12 korea.vps.com haproxy[23190]: /usr/sbin/haproxy: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (re

**Comment by ghost** [comment]
> I'm seeing that you build openssl with "no-shared", but haproxy 1.8 and above enable threads, so you need a thread-aware version of openssl. Please retry without "no-shared".

Forgot one thing is that my system is debian9

**Comment by ghost** [comment]
> I'm seeing that you build openssl with "no-shared", but haproxy 1.8 and above enable threads, so you need a thread-aware version of openssl. Please retry without "no-shared".

And I found that in my /usr/lib/x86_64-linux-gnu/ path, it does include libssl.so.1.1 and libcrypto.so.1.1, but the compiled haproxy can't find libssl.so.1.1 and libcrypto.so.1.1 under the /usr/lib/x86_64-linux-gnu/  path, so I replaced the two libssl.so.1.1 and libcrypto.so.1.1 of my compiled openssl-1.1.1c with /usr/lib/x86_64-linux-gnu/Two dynamic libraries under the path, the result haproxy can work normally, is the two dynamic libraries that come with the system too old? And must be replaced manually?

**Comment by lukastribus** [comment]
I don't think `no-shared` means that openssl won't be thread-aware, afaik it just means that only static files are build (`.a` instead of `.so`), so that openssl remains completely static. This is useful for testing and why we suggest this in INSTALL.

`ADDLIB=-lpthread` is needed to include `pthread` support which should fix this issue.

**Comment by wtarreau** [comment]
On Thu, Aug 01, 2019 at 07:31:27AM -0700, Lukas Tribus wrote:
> I don't think `no-shared` means that openssl won't be thread-aware, afaik it
> just means that only static files are build (`.a` instead of `.so`), so that
> openssl remains completely static. This is useful for testing and why we
> suggest this in INSTALL.

Oh indeed you're right Lukas, sorry about that.

> `ADDLIB=-lpthread` is needed to include `pthread` support which should fix this issue.

OK thanks.
Willy

**Comment by ghost** [comment]
> I don't think `no-shared` means that openssl won't be thread-aware, afaik it just means that only static files are build (`.a` instead of `.so`), so that openssl remains completely static. This is useful for testing and why we suggest this in INSTALL.
> 
> `ADDLIB=-lpthread` is needed to include `pthread` support which should fix this issue.

OK！it work！Thanks！
