### ISSUE TITLE
Haproxy mqtt connected around 32k，The system cpu suddenly increases

### ISSUE THREAD

**Issue by elysian-gc** [haproxy/haproxy#2050]
### Detailed Description of the Problem

I used emqx as the back end，and one of emqx，the number of connections exceeds 32K，The system cpu suddenly increases，

After adding source, as follows
    server emqx_node_1 xxxxxxxx:1883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5 source 10.51.4.xx
    server emqx_node_2 xxxxxxxx:1883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5 source 10.51.4.xx
    server emqx_node_3 xxxxxxxx:1883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5 source 10.51.4.xx
    server emqx_node_4 xxxxxxxx:1883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5 source 10.51.4.xx
can get more connections;

I think one clientip:clientport + serverip:serverport limit 65535, but only 32k connections, system cpu increase
I don't know why
please help me

### Expected Behavior

none

### Steps to Reproduce the Behavior

1. start emqx
2. start haproxy
3. emqtt_bench conn -c 60000 -h xxxxxx -S -p 18883 -k 120 -i 5

### What is your configuration?

```haproxy
global
    maxconn 520000
    log  127.0.0.1  local0 debug
    #log  127.0.0.1
    #log  loghost  local0  info 
    uid  988 
    gid  982 
    #daemon
    #cpu-map 1-4 0-3
    nbthread  4
    #tune.ssl.cachesize 2000000
    #debug
    #quiet
    chroot  /usr/local/haproxy
    stats  socket  /usr/local/haproxy/haproxy.sock
    profiling.tasks auto
    tune.runqueue-depth 2000

# These parameter can be used for frontend, backend and listen:
defaults
    log global
    mode   tcp
    retries 3
    maxconn 520000
    balance roundrobin
    balance    source
    balance    leastconn
    option clitcpka


frontend frontend_emqx_ssl
    bind *:18883 ssl crt /etc/haproxy/emqx.pem no-sslv3
    option tcplog
    timeout client 200s
    mode tcp
    default_backend backend_emqx_ssl
backend backend_emqx_ssl
    mode tcp
    timeout server 200s
    balance roundrobin
    server emqx_node_1 10.51.4.127:1883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5 source 10.51.4.212
    server emqx_node_2 10.51.4.4:1883 check-send-proxy send-proxy-v2 check inter 10s fall 2 rise 5 source 10.51.4.140
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.9-3a3700a 2023/02/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.9.html
Running on: Linux 5.10.165-143.735.amzn2.aarch64 #1 SMP Wed Jan 25 03:13:36 UTC 2023 aarch64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY -LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -QUIC +RT -SLZ -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.3.1 20180712 (Red Hat 7.3.1-15)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
[root@ip-10-51-4-38 ~]# strace -p 1610 -c
strace: Process 1610 attached
^Cstrace: Process 1610 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 93.93   13.707594       47595       288       288 connect
  2.54    0.370191          27     13677           sendto
  2.07    0.302790          10     28493      6989 recvfrom
  0.30    0.043875          50       874           epoll_pwait
  0.25    0.035887          35      1003           setsockopt
  0.25    0.035796          20      1772           clock_gettime
  0.20    0.028750          19      1468           epoll_ctl
  0.12    0.018202         122       149           accept4
  0.11    0.015669          18       865       282 getsockopt
  0.10    0.013928           9      1477           getpid
  0.08    0.012206          42       288           socket
  0.03    0.004831          16       285           getsockname
  0.02    0.002729           9       288           fcntl
  0.00    0.000165           6        24           timer_settime
  0.00    0.000098          14         7           close
  0.00    0.000046           1        24        13 rt_sigreturn
  0.00    0.000003           3         1           bind
  0.00    0.000002           1         2           futex
------ ----------- ----------- --------- --------- ----------------
100.00   14.592762                 50985      7572 total
```

**Comment by elysian-gc** [comment]
[root@ip-10-51-4-38 ~]# strace -p 1610 -e trace=connect
strace: Process 1610 attached
connect(228363, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228367, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228373, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228377, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228381, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228385, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228389, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228393, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228398, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228402, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228407, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228410, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228413, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228416, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228419, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228421, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228423, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x3, si_overrun=0, si_value={int=3, ptr=0x3}} ---
connect(228426, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228428, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228430, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=1, ptr=0x1}} ---
connect(228431, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228433, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228435, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228437, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228439, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228443, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228446, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228449, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228452, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228455, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228458, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228546, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x1, si_overrun=0, si_value={int=2, ptr=0x2}} ---
connect(228582, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228586, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228593, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228607, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228614, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228631, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228636, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x2, si_overrun=0, si_value={int=0, ptr=NULL}} ---
connect(228658, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228666, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228677, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228686, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228695, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228706, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228717, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228774, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228778, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228783, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228787, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228791, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228797, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228800, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x3, si_overrun=0, si_value={int=3, ptr=0x3}} ---
connect(228803, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228806, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=1, ptr=0x1}} ---
connect(228809, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228812, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228815, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228818, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228821, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228824, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228828, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228831, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228835, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228837, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228841, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228872, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(228907, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x1, si_overrun=0, si_value={int=2, ptr=0x2}} ---
connect(229013, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229054, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229058, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229061, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229064, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229066, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229072, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229076, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x2, si_overrun=0, si_value={int=0, ptr=NULL}} ---
connect(229081, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229084, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229094, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229098, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229102, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229104, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229106, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229108, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229111, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229113, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229118, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229121, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229128, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x3, si_overrun=0, si_value={int=3, ptr=0x3}} ---
connect(229133, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229137, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
--- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=1, ptr=0x1}} ---
connect(229141, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229145, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229149, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229152, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.3.161")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229157, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229162, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.4.4")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(229166, {sa_family=AF_INET, sin_port=htons(1883), sin_addr=inet_addr("10.51.5.182")}, 16) = -1 EINPROGRESS (Operation now in progress)

**Comment by elysian-gc** [comment]
![image](https://user-images.githubusercontent.com/44466800/221841390-ee39dd23-357e-4995-85aa-a560d5906003.png)

This means there is not enough port?

**Comment by capflam** [comment]
Indeed, here all the CPU is spent in the `connect()` syscall trying to find a source port for the outgoing connections. You may first check the range for local source port in your sysctls (`sysctl net.ipv4.ip_local_port_range`) and then you may try to increase it, for instance from 1024 to 65535 (`sysctl -w net.ipv4.ip_local_port_range="1024 65535"`) . In addition you may check if you have TIME_WAIT for outgoing connections (from haproxy to the server). It should not happen.

**Comment by elysian-gc** [comment]
thanks for your reply，I had check `net.ipv4.ip_local_port_range` .and that moment can increase connections.
I see a patch,which is https://patchwork.ozlabs.org/project/netdev/patch/1432504175.4060.155.camel@edumazet-glaptop2.roam.corp.google.com/.
by the test, start connect is odd ports, more than 32k, connect is even port,I don't know if that's the problem。

**Comment by capflam** [comment]
Sorry I don't understand, you already tried to increase the source port range ?

**Comment by elysian-gc** [comment]
Before I asked the question, I had already increased the port range, but the same phenomenon as described occurred. Now I have found that when I start to proxy emqx, the locally initiated connection to the server randomly chooses an odd-numbered port first, and only when it exceeds 32k, the port is even.

I'm sorry, my English is not good.

**Comment by lukastribus** [comment]
So the CPU usage increases only when even ports start to get assigned? That sounds more like a kernel issue to me.

I don't think it's a good idea to handle source port allocation in haproxy when we do multithreading, as the threads would compete for the same source port ranges, but I would try two things:

- try to see what happens with `nbthread 1`
- try to see what happens with `nbthread 1` + source with port allocation from within haproxy (for example `source 10.51.4.212:2049-60999`)

**Comment by elysian-gc** [comment]
@lukastribus  
So the CPU usage increases only when even ports start to get assigned? -- yes
`source 10.51.4.212:2049-60999` ,which can  perfectly solve my problem. Thank you very much.

**Comment by lukastribus** [comment]
This is really only a workaround, ideally the kernel problem should be fixed.

So based on your finding https://github.com/torvalds/linux/commit/07f4c90062f8fc7c8c26f8f95324cbe8fa3145a5 we can see that in https://github.com/torvalds/linux/commit/ed2dfd900992aa7b6b3d0abd8ec9a7e9d2c7f827

> it is advised to have an even number
> of ports described in /proc/sys/net/ipv4/ip_local_port_range
> 
> This means start/end values should have a different parity.

Can you confirm that when you did it with the kernel only, the start-end values had different parity?

There is a further improvement in https://github.com/torvalds/linux/commit/1580ab63fc9a03593072cc5656167a75c4f1d173 but all those improvements go way back, your kernel is much more modern than that.

**Comment by wtarreau** [comment]
What I suspect instead, since the config works in TCP mode, is that clients close first, making haproxy close first, and that ephemeral outgoing ports remain in TIME-WAIT on the haproxy side. That's the worst that can happen (and sadly people who don't understand how TCP works continue to design protocols so that clients close first). This can be verified by issuing `ss -an state time-wait` and checking that many of them have 10.51.4.xxx:1883 in the "Peer Address:Port" column.

I think that in this case adding "option nolinger" in the backend should help, by making haproxy close connections with a TCP RST, that will prevent the TIME-WAIT from being created. However it's possible that servers will log an error for each disconnection in this case. It might be worth trying though.

**Comment by elysian-gc** [comment]
@lukastribus @wtarreau thanks your help
I run `sysctl -w net.ipv4.ip_local_port_range="1024 61000"` or `sysctl -w net.ipv4.ip_local_port_range="1024 61001"` or  `sysctl -w net.ipv4.ip_local_port_range="1025 61001"` or `sysctl -w net.ipv4.ip_local_port_range="1025 61000"`,Same result
,
as follows 
![image](https://user-images.githubusercontent.com/44466800/222330917-be280ddc-5328-4715-96f9-791e7778c75c.png)
![image](https://user-images.githubusercontent.com/44466800/222330889-8d488afe-2a7c-446b-8467-8c0657976f5f.png)
as shown above, haproxy connections around 64k(connect emqx around 32k),the time-wait only 1, the system cpu go up.
the image is amazon linux2 arm,I have asked aws for help

**Comment by NullIsNot0** [comment]
Can you try setting some timeouts in defaults section and see if it helps reducing hanging connections?

```
defaults
    timeout connect 5s
    timeout client-fin 9s
    timeout server-fin 9s
    timeout queue 15s
    timeout tunnel 1h
```

**Comment by capflam** [comment]
Any news on this issue ?

**Comment by capflam** [comment]
For now, I'm closing the issue because it seems inactive. If there is still an issue, feel free to reopen it with more info. Thanks.
