### ISSUE TITLE
req.hdr_ip() should recognize IPv6 addresses in square brackets

### ISSUE THREAD

**Issue by otovalek** [haproxy/haproxy#2054]
### Detailed Description of the Problem

when req.hdr_ip() is used in an ACL, e.g.

`acl acl_numeric_ip_host req.hdr_ip(Host) -m found`

an IPv4 address, e.g. "192.158.1.38" is matched, but IPv6 address enclosed in square brackets, e.g. "[2001:0db8:85a3:0000:0000:8a2e:0370:7334]" is not matched.

### Expected Behavior

The ACL

`acl acl_numeric_ip_host req.hdr_ip(Host) -m found`

should match a HTTP request with

`Host: [2001:0db8:85a3:0000:0000:8a2e:0370:7334]`

Note that the [...] format of IPv6 address is both valid (see https://www.rfc-editor.org/rfc/rfc3986.html#section-3.2.2) and common (sent by web browsers in the Host header).

Haproxy documentation ( http://docs.haproxy.org/dev/configuration.html#7.3.6-req.hdr_ip ) refers to RFC7239 ( https://www.rfc-editor.org/rfc/rfc7239.html#section-6.1 ), which refers to the RFC3986 mentioned above. This means that haproxy does not behave according to its documentation.

### Steps to Reproduce the Behavior

1. in reg-tests/http-rules/converters_ipmask_concat_strcmp_field_word.vtc, replace
`Addr2: 2001:db8::bad:c0f:ffff`
with
`Addr2: [2001:db8::bad:c0f:ffff]`
3. make reg-tests
4. the tests fail

### Do you have any idea what may have caused this?

The smp_fetch_hdr_ip() function calls inet_pton() to recognize the IPv6 address.
However, inet_pton() does not support IPv6 addresses in brackets.

### Do you have an idea how to solve the issue?

The smp_fetch_hdr_ip() function can be modified to trim '[' and ']' before calling inet_pton()

### What is your configuration?

```haproxy
This behavior can be reproduced with make reg-tests on any platform as stated above.
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8-dev4-83540ed429ae 2023/02/24 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = 
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER -OPENSSL -OPENSSL_WOLFSSL -OT -PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ -SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wtarreau** [comment]
Hello,

originally when support for IPv6 started in haproxy in 2003, square brackets were not even used (rfc3986 was only emitted 2 years later), and we were used to dealing with plain IPv6 addresses, particularly in x-forwarded-for headers. Later we didn't want to change the behavior to make sure not to break existing deployments. As such, it's not technically a bug rather a design decision (or non-decision if you want :-)).

However I agree with you that as soon as we start to refer to 7239 as we did in 2.4, we should at least respect its format, especially since there's no mention of any exception in the doc. So I guess I'm fine with merging your proposed fix. There's just one thing, when updating the regtest you removed one test I want us to preserve, so that we're certain not to break existing deployments. Could you please have a look at this ? Thanks!

**Comment by otovalek** [comment]
I added some new testcases instead of modifying current ones.

**Comment by wtarreau** [comment]
Yeah, thank you for that. it's now merged.

**Comment by otovalek** [comment]
Fixed in commits d1773e6881caba229575fa7e0525846697dd4e21, fa0413f1c7e0eaff6fb061f53f8efaae9eccca32

**Comment by capflam** [comment]
@wtarreau, should it be backported or not ?

**Comment by wtarreau** [comment]
I don't think it's strictly needed since we don't have the rfc7239 stuff in 2.7. But if @otovalek needs it in 2.7 I'm fine with hvaing it there.

**Comment by otovalek** [comment]
That's not necessary. I have a quick & dirty workaround of
`req.hdr(Host) -m reg ^\[[0-9a-fA-F:]+\]$`

**Comment by capflam** [comment]
copy that. Thanks !

**Comment by Puliyo** [comment]
Mind checking here in this closed thread.
Will the fix also address ACL match pattern for ip?

Eg: when HOST is `[2001:db8:85a3:8d3:1319:8a2e:370:7348]:443` and ACL rule is `acl match_ipv6 req.hdr(host) -m ip ::/0`

As of v2.7.6-1, match_ipv6 will be False.

**Comment by otovalek** [comment]
No.

This would have to be likewise fixed at [buf2ip6()](https://github.com/haproxy/haproxy/blob/3b50e5c164b4dffec8b70787b0cc8cc998b72675/src/tools.c#L3063).
I think you should create a separate issue.

**Comment by Puliyo** [comment]
Thanks. I have raised one ^.
