### ISSUE TITLE
SSL pass-through with HTTP Tunnel/Proxy Support

### ISSUE THREAD

**Issue by eozturk1** [haproxy/haproxy#2056]
## HAProxy should support handling HTTP [CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) requests in TCP mode

Existing HTTP proxy/tunneling implementations (such as Java's [Proxy](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)) uses a HTTP CONNECT request that requires the proxy to open a TCP channel to the destination and respond with a HTTP 200 status. Then, for secure connections (HTTPS), TCP mode can be used to exchange the rest of the traffic -- i.e., SSL passthrough.

The existing HAProxy modes don't support this since they only forward the requests -- meaning a CONNECT request will end up at the destination server which might not know how to handle it.

### What are you trying to do?

SSL passthrough with HTTP tunneling

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by capflam** [comment]
What you are looking for is a forward proxy, like squid. HAProxy is reverse proxy.

**Comment by eozturk1** [comment]
Thanks for the reply @capflam! As I understand, there is no way to achieve this with HAProxy currently, correct?

Do you mean [Squid](https://github.com/squid-cache/squid)? Is it possible to achieve the same with NGINX and is there any advantage to using NGINX for it?

**Comment by eozturk1** [comment]
One more question, with Squid (or NGINX) is it possible to have the HTTP CONNECT request to be encrypted as well? The forward proxy should decrypt the CONNECT request and establish SSL pass-through to the destination server. (The goal is to hide the final destination of the CONNECT request.)The client should check the forward proxy certificate and the destination server certificates are both valid.

**Comment by git001** [comment]
> Thanks for the reply @capflam! As I understand, there is no way to achieve this with HAProxy currently, correct?
> 
> Do you mean [Squid](https://github.com/squid-cache/squid)? Is it possible to achieve the same with NGINX and is there any advantage to using NGINX for it?

No, this is not possible with vanilla nginx, maybe there are some plugins but nginx is also mainly a Webserver and reverse proxy

**Comment by capflam** [comment]
I'm closing the issue because HAProxy will most probably never be a forward proxy. It is possible to forward a request to a server based on the Host header value and a `do-resolve` action. But HAproxy will not handle HTTP Connect requests on its own. About Squid and Nginx, the best is to check documentation of both projects and eventually ask some support on the appropriate channels.
