### ISSUE TITLE
[ALERT] 213/135403 (26245) : Starting proxy socks5_speed_check: cannot bind socket [0.0.0.0:8889]

### ISSUE THREAD

**Issue by hongyi-zhao** [haproxy/haproxy#206]
Hi,

I use the latest git version of haproxy, and often I meet the following error while staring it:

[ALERT] 213/135403 (26245) : Starting proxy socks5_speed_check: cannot bind socket [0.0.0.0:8889]

The lsof and pgrep gives nothing on that port.

Any hints for this issue?

Regards

**Comment by lukastribus** [comment]
The issue tracker is for bugs and features request, not for generic support.

Please use the mailing list or the discourse forum instead.
