### ISSUE TITLE
Redispatch failed in gRPC proxy

### ISSUE THREAD

**Issue by AndreWanga** [haproxy/haproxy#2060]
### Detailed Description of the Problem

When I use haproxy to proxy gRPC requests, I found out redispatch function not doing well. When I kill one backend, the haproxy will NOT redispatch requests to the other one.

### Expected Behavior

When one of the backends goes down, the haproxy will redispatch the requests to the others.

### Steps to Reproduce the Behavior

1. use my config
2. kill one backend while doing a stress testing
3. check if you get wrong response

### What is your configuration?

```haproxy
frontend grpc_server
    mode http
    timeout client 500ms
    bind :8001 proto h2
    default_backend triton_grpc_servers
backend triton_grpc_servers
    mode http
    timeout connect 100ms
    timeout server 1s
    balance leastconn
    option redispatch 1
    retries 3
    retry-on all-retryable-errors
    server s1 triton_server1:8001 check observe layer7 error-limit 1 on-error mark-down rise 3 inter 10s proto h2
    server s2 triton_server2:8001 check observe layer7 error-limit 1 on-error mark-down rise 3 inter 10s proto h2
```

### Output of `haproxy -vv`

```plain
haproxy 2.5.0
```

**Comment by capflam** [comment]
HAProxy 2.5.0 is totally outdated. You must definitely upgrade. Note also the 2.5 will be EOL in a month or so. It is probably a good idea to switch to the 2.6.

**Comment by AndreWanga** [comment]
> HAProxy 2.5.0 is totally outdated. You must definitely upgrade. Note also the 2.5 will be EOL in a month or so. It is probably a good idea to switch to the 2.6.

If I upgrade to 2.6.9, will this promblem be dealt with?

**Comment by capflam** [comment]
I don't know. But the 2.5.0 is affected by a 363 known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html. So you must upgrade. We cannot investigate on a presumable bug on a so old version.

**Comment by AndreWanga** [comment]
> I don't know. But the 2.5.0 is affected by a 363 known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html. So you must upgrade. We cannot investigate on a presumable bug on a so old version.

Okay，I would do the test as you say. I'll tell you the result after I try. Thanks
