### ISSUE TITLE
Retry connection (redispatch) in a case of TCP reset

### ISSUE THREAD

**Issue by findmyname666** [haproxy/haproxy#2061]
### Your Feature Request

Add configuration option to retry a request, possibly to different backend server, when HAProxy receive TCP reset.

### What are you trying to do?

Hello all,

I was playing with HAProxy and testing the behaviour when HAProxy receive TCP RST from backend server or some intermediate L4 component in the network. I noticed that connection isn't retried even when there is an option **redispatch**.

I used following HAProxy configuration which is almost the same version as supplied in [the docker image tag 2.7.3](https://hub.docker.com/_/haproxy/):

```
#---------------------------------------------------------------------
# Example configuration for a possible web application.  See the
# full configuration options online.
#
#   https://www.haproxy.org/download/2.7/doc/configuration.txt
#   https://cbonte.github.io/haproxy-dconv/2.7/configuration.html
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #
	log stdout format raw local0

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    # daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    #option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# example how to define user and enable Data Plane API on tcp/5555
# more information: https://github.com/haproxytech/dataplaneapi and
#   https://www.haproxy.com/documentation/hapee/2-0r1/configuration/dataplaneapi/
#---------------------------------------------------------------------
# userlist haproxy-dataplaneapi
#     user admin insecure-password mypassword
#
# program api
#    command /usr/bin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --restart-cmd "kill -SIGUSR2 1" --reload-delay 5 --userlist hapee-dataplaneapi
#    no option start-on-reload

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend  main
    bind *:9000

    default_backend app

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend app
    balance     roundrobin
	retry-on    all-retryable-errors

    server rst1 127.0.0.1:9001
    server rst2 127.0.0.1:9002
```

My backend app is simple TCP server written in go which reset a connection once it receive some. I uploaded the code [here](https://github.com/findmyname666/tcp-rst-srv).

Testing procedure:
- I built HAProxy container with the above configuration. Upstream image: **haproxytech/haproxy-ubuntu:2.7.3**.
- I ran HAProxy container on localhost.
- I started two backend servers on port 9001 and 9002 (locahost as well).
- I sent requests with curl.
- Request reached backends.
- HAProxy logged 502 without any retry/redispatch:
```
127.0.0.1:55066 [28/Feb/2023:10:09:50.098] main app/rst1 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
127.0.0.1:49804 [28/Feb/2023:10:09:57.353] main app/rst2 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
```
- Client received `502` as well:
```
└──╼$ curl http://127.0.0.1:9000
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

I'm not sure if this doesn't work due to some reason or nobody was thinking about it. I will leave it up to you to decide if this make sense.

### Output of `haproxy -vv`

```plain
root@d6bf15a475c1:/# haproxy -vv
HAProxy version 2.7.3-1065b10 2023/02/14 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2024.
Known bugs: http://www.haproxy.org/bugs/bugs-2.7.3.html
Running on: Linux 6.1.11-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  9 19:20:24 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by findmyname666** [comment]
Out of curiosity I tested my test backend server also with these servers/loadbalancers:
- [Traefik](https://traefik.io/) - There is support for [the retries](https://doc.traefik.io/traefik/middlewares/http/retry/#retry) but I got the same result as with HAProxy e.g. no retries.
- [Caddy](https://caddyserver.com/) - Retries worked in the [reverse proxy mode](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy).

**Comment by capflam** [comment]
Thanks. It a bug. In this case, a retry must be performed because the retries policy include `empty-response`. The bug affects the 2.8-DEV and 2.7. I'll push a fix soon.

**Comment by capflam** [comment]
I pushed the fix in 2.8-DEV. Thanks !

**Comment by findmyname666** [comment]
@capflam thx a lot for quick action :)
I'm not sure what is HAProxy policy here but I encountered the same behaviour with versions 2.6.9 & 2.5.12.

**Comment by capflam** [comment]
Now I'm puzzled. Because on the 2.6 and 2.5, I'm unable to reproduce the issue. Are the Log messages similar on these versions ?

**Comment by findmyname666** [comment]
Interesting ... how do you test it ?
I used the same config as above and there are no retries.

Log from:
- 2.5

```
127.0.0.1:33362 [01/Mar/2023:08:09:27.267] main app/rst1 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET /zlo HTTP/1.1"
127.0.0.1:42824 [01/Mar/2023:08:09:56.565] main app/rst2 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET /zlo HTTP/1.1"
```

- 2.6

```
127.0.0.1:34088 [01/Mar/2023:08:12:49.760] main app/rst2 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/+1 0/0 "GET /zlo HTTP/1.1"
127.0.0.1:36126 [01/Mar/2023:08:12:52.277] main app/rst1 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET /zlo HTTP/1.1"
```

In meantime I also tested how does it handle [envoy](https://www.envoyproxy.io/). It does retries in my case with configuration option `retry_on: reset`.

**Comment by wtarreau** [comment]
I have not tested but what I'm suspecting is that you might possibly be facing truncated responses and that we'd offer no option for this specific one (I've seen junk-response for non-parsable contents which seem different).

**Comment by capflam** [comment]
It is indeed a good point. You said you want to retry on reset. For me it was in case the server has sent no data, not on a partial response. In this case, HAProxy will not retry because truncated responses are not considered as "junk" responses. In such case,  a connection error is reported and no retry is performed.

**Comment by wtarreau** [comment]
The thing is, as soon as we've started to send data to the client, it's not possible anymore to redispatch, as there's no way to tell a client "oh, sorry, ignore what already I sent you, take this one instead".

With that said, from the logs above it seems it was definitely an error while waiting for headers, so I don't know why it would not have worked.

**Comment by capflam** [comment]
Ok, so I'm able to reproduce the error and in fact it depends if the RESET is handled during the connect or after. On the first case, a retry is performed because it is detected as a connect error. But not on the second case because a read error is reported, it is not considered as an empty response, so there is no retry.

So now the question is to decide how to handle these errors when we are waiting for the response headers. I'm a bit surprised there is no retry in this case, but it was designed this way.

About truncated messages, it depends if it happens when we are waiting for the headers or not. Because on the first case, nothing is sent to the client. A retry is safe here and it can be considered as a junk response. Checking the 2.6, it seems it is handled this way. So it is a change on recent versions. I must fix that. But we are agree, if we start to forward data to the client, of course no retry is possible.

**Comment by wtarreau** [comment]
But if the reset happens while waiting for headers, we should at least match the empty response. I mean, no matter how it is implemented technically inside, and how we consider it wrt flags, what is received by the user is an empty response and that's what the option should protect against. Also that's surprising to me because the very first use case of empty-response precisely is the RST. It's made for the cases where sending a request over an existing persistent connection races with a close from the server, that causes an RST to appear. This was one of the very first use cases and I'm pretty certain it *has* worked at some point.

**Comment by findmyname666** [comment]
> It's made for the cases where sending a request over an existing persistent connection races with a close from the server, that causes an RST to appear.

This is actually 1 of the cases I like to test.

> This was one of the very first use cases and I'm pretty certain it has worked at some point.

Well you are right. I just tested it on docker image tag ver. 2.3 and retries works :)
e.g. I added 1 more backend into server pool to response with 200.

```
127.0.0.1:49510 [01/Mar/2023:10:29:05.006] main app/zlo1 0/0/0/1/1 200 117 - - ---- 1/1/0/0/+2 0/0 "GET /zlo HTTP/1.1"
127.0.0.1:35616 [01/Mar/2023:10:29:11.081] main app/zlo1 0/0/0/0/0 200 117 - - ---- 1/1/0/0/+2 0/0 "GET /zlo HTTP/1.1"
127.0.0.1:35620 [01/Mar/2023:10:29:16.756] main app/zlo1 0/0/0/0/0 200 117 - - ---- 1/1/0/0/+2 0/0 "GET /zlo HTTP/1.1"
```

Retries don't work on versions > 2.3 for this specific case.

**Comment by wtarreau** [comment]
I can indeed reproduce it this way, it broke between 2.5 and 2.6:
```
global
        set-dumpable
        stats socket /tmp/sock1 mode 666 level admin
        stats timeout 1h

defaults
        mode http
        timeout client 5s
        timeout server 5s
        timeout connect 5s

listen f
        bind :8001
        log stdout local0 info
        option httplog
        option dontlog-normal
        retry-on all-retryable-errors
        server next 127.0.0.1:8002

frontend b
        bind :8002
        timeout http-keep-alive 1  # one ms
        redirect location /
```

Then I inject with `h1load -c 1 -R 1000` so that the interval between two requests is very close to the keep-alive timeout. I get plenty of these in 2.6:
```
<134>Mar  1 11:34:46 haproxy[15880]: 127.0.0.1:54578 [01/Mar/2023:11:34:46.448] f f/next 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
<134>Mar  1 11:34:46 haproxy[15880]: 127.0.0.1:54592 [01/Mar/2023:11:34:46.454] f f/next 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
```

So now we have a repro and a rough range where the problem appeared, it's bisectable. However please be aware that the fix might not necessarily be easy, such areas are extremely tricky :-/

**Comment by wtarreau** [comment]
In 2.8 it's different, no more 502 but sometimes there are ~3s pauses. Not sure what these are.

**Comment by capflam** [comment]
I'm on it. Indeed there was a change at some point  in 2.4.

**Comment by wtarreau** [comment]
strange, for me 2.4 and 2.5 behave the same here. Maybe we've cumulated several changes there. We know how sensitive that area is...

**Comment by capflam** [comment]
I don't know. But I'm able to reproduce the issue with the 2.4 but not with the 2.2. For now, I'm trying to understand what introduced the change. Otherwise it will be hard to fix the issue :)

**Comment by wtarreau** [comment]
I could bisect it to this one backported to 2.6:
```
commit c99b463974656affab492c85776df2b8ee193c63
Author: Willy Tarreau <w@1wt.eu>
Date:   Thu Sep 1 19:58:58 2022 +0200

    MINOR: backend: always satisfy the first req reuse rule with l7 retries
    
    The "first req" rule consists in not delivering a connection's first
    request to a connection that's not known for being safe so that we
    don't deliver a broken page to a client if the server didn't intend to
    keep it alive. That's what's used by "http-reuse safe" particularly.
    
    But the reason this rule was created was precisely because haproxy was
    not able to re-emit the request to the server in case of connection
    breakage, which is precisely what l7 retries later brought. As such,
    there's no reason for enforcing this rule when l7 retries are properly
    enabled because such a blank page will trigger a retry and will not be
    delivered to the client.
```

And indeed, 2.6.0 doesn't have the problem but it logs 302 without retries as warnings... The patch above was backported to solve trouble with reuse. I don't remember about the details. Maybe there are several regions of breakage in other branches, which could explain why we're not observing the same ranges.

**Comment by capflam** [comment]
On my side, I'm testing with tcploop as server (`tcploop 127.0.0.1:8000 L A100 G P100 K`) and curl for the client. With or without `P100` option, on the 2.4, the result is not stable. Sometime there are some retries. 1, 2 or 3. it depends. But most of time there is no retry.

On the 2.2, there are always 3 retries. So there is at least an issue on the 2.4.

**Comment by wtarreau** [comment]
OK, good to know indeed!

**Comment by capflam** [comment]
I found the bug. It was introduced by the following commit:
```
commit 1a4449b0d0de49095aa8a1e1218e7c731d769f75
Author: Christopher Faulet <cfaulet@haproxy.com>
Date:   Mon May 31 11:45:24 2021 +0200

    CLEANUP: http-ana: Remove useless if statement about L7 retries
    
    Thanks to the commit 1f08bffe0 ("MINOR: http-ana: Perform L7 retries because
    of status codes in response analyser"), the L7 retries about the response
    status code is now fully handled in the HTTP response analyser.
    CF_READ_ERROR flag is no longer set on the response channel in this
    case. Thus it is useless to try to catch L7 retries when CF_READ_ERROR is
    set because it cannot happen.
    
    The above commit was backported to 2.4, thus this one should also be
    backported.
```

I removed a retry case on a wrong assumption.  By reverting it, it works as expected expect on the 2.8 because there is another bug on top of this one :/

@wtarreau, can you try the following patch on the 2.7/2.6 to be sure it works for you ? I'm unable to reproduce your result with your reproducer for an unknown reason. I've only some 302 with one retry, but not much.

```
diff --git a/src/http_ana.c b/src/http_ana.c
index d9f9201cad..ae6dcb0457 100644
--- a/src/http_ana.c
+++ b/src/http_ana.c
@@ -1359,6 +1359,13 @@ int http_wait_for_response(struct stream *s, struct channel *rep, int an_bit)
                if (rep->flags & CF_READ_ERROR) {
                        struct connection *conn = sc_conn(s->scb);
 
+                       if ((txn->flags & TX_L7_RETRY) &&
+                           (s->be->retry_type & PR_RE_DISCONNECTED) &&
+                           (!conn || conn->err_code != CO_ER_SSL_EARLY_FAILED)) {
+                               if (co_data(rep) || do_l7_retry(s, s->scb) == 0)
+                                       return 0;
+                       }
+
                        /* Perform a L7 retry because server refuses the early data. */
                        if ((txn->flags & TX_L7_RETRY) &&
                            (s->be->retry_type & PR_RE_EARLY_ERROR) &&
```

**Comment by wtarreau** [comment]
Indeed, good catch, now with this on top of 2.6, no more problem for me. I'm still having the long pauses on 2.8 but that's unrelated.

**Comment by capflam** [comment]
Ok thanks. About pauses, could it be the TAR delay ?

**Comment by wtarreau** [comment]
And this one is the one that is causing occasional delays to me:
```
commit ecb40b2c388dffcc9998a92df536ec7419ed8fed (refs/bisect/bad)
Author: Willy Tarreau <w@1wt.eu>
Date:   Thu Sep 1 19:58:58 2022 +0200

    MINOR: backend: always satisfy the first req reuse rule with l7 retries
    
    The "first req" rule consists in not delivering a connection's first
    request to a connection that's not known for being safe so that we
    don't deliver a broken page to a client if the server didn't intend to
    keep it alive. That's what's used by "http-reuse safe" particularly.
```

It makes sense in this scenario in that it's directly related to l7 retries. I just don't understand where the delay is coming from, the principle was to allow any request to reuse an existing connection in safe mode, not just the second one. Maybe we end up reusing broken connections and causing a retry but if that's the case it would be surprising that the broken connections are in the pool. What I'm seeing is that we're regularly waiting for a `timeout connect` there, probably indicating that the abnormal event of that connection happened before we were waiting for an event, hence before we reused it.

If I dmup the connection state after picking it in that "if" block, it's exactly the same as previous ones:
```
c=0x7fbbe019e5e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x7fbbe019e5e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x7fbbe019e5e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x7fbbe019e5e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x7fbbe019e5e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x7fbbe019e5e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x2c535e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x2c535e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x2c535e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x2c535e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x2c535e0 flg=0x300 mux=0x9d9840 xprt=0xbee480
c=0x2c535e0 flg=0x300 mux=0x9d9840 xprt=0xbee480  <<<--- here it hangs
```

Thus I suspect that instead we're passing the request down the mux and that the event is received at the wrong moment there. I think I should be able to emulate this using reuse always, I'll check.

**Comment by capflam** [comment]
hum it's strange indeed.

**Comment by findmyname666** [comment]
> What I'm seeing is that we're regularly waiting for a timeout connect there,

I'm not expert here and it can be obvious for you but based on [the retry documentation](http://docs.haproxy.org/2.7/configuration.html#4.2-retries) there is delay added:
```
In order to avoid immediate reconnections to a server which is restarting,
a turn-around timer of min(timeout connect, one second) is applied before
a retry occurs on the same server.
```

**Comment by wtarreau** [comment]
that seems to be related to the mux indeed: if instead I switch the server to h2, no more problems, and I'm seeing lots of matches of SE_FL_ERROR in http_ana.c:1231 before the test for TX_NOT_FIRST. I don't enter this block in H1 while I'm pretty sure we're getting such errors as well, so very likely a shutr on the connection happens at a moment we don't watch (e.g. after the connection is picked and before it's effectively used), and we don't see the event.

**Comment by wtarreau** [comment]
@findmyname666 yes that's the turn-around delay ("TAR" state) that Christopher was talking about. But here it's not this one, it really is a missed event. In short, we seem to be waiting for a server response (so likely we've sent the request) on a connection that looks dead without noticing it. I really suspect the error fell into a crack.

**Comment by capflam** [comment]
I'm unable to reproduce the error. If you enable h1 traces, is the problem still observable ?

**Comment by wtarreau** [comment]
As you guessed it's indeed extremely sensitive to timings. I can't make it fail with traces enabled. It doesn't fail if bound only on different CPUs than h1load, and doesn't fail if there are less than 2 threads. I'm running in background with "h1load -w 1000 -c 1 -r 1 -R 10000"  to see if it manages to catch one with traces enabled, and to stop.

**Comment by wtarreau** [comment]
I could manage to get one in "verbosity quiet". It's not awesome of course but it could give some hints. Here are the last 1k lines. As a reminder, single end-to-end connection, thus at most 3 parallel streams (1 from client->px, one px->server, one server). There's a timeout at the end. My timeout server is configured to 120s during this test so it cannot come from there. Still same conf as above with traces enabled and logs disabled.
[log.txt](https://github.com/haproxy/haproxy/files/10863288/log.txt)

**Comment by capflam** [comment]
Thanks, I'll take a look

**Comment by wtarreau** [comment]
And there's no way to trigger it with "-r 1" (ie client keep-alive). So there's really something related to this tx_not_first being cleared.

**Comment by wtarreau** [comment]
sorry, s/with/without above. More clearly, it *needs* -r1 to disable keepalive.

**Comment by capflam** [comment]
hehe. Now, with `-r 1` I'm able to reproduce it ! I'm still trying to demangle your log. But it is not easy in quiet mode :) With the reproducer it will be easier.

**Comment by wtarreau** [comment]
Cool, and sorry for the confusion.

**Comment by capflam** [comment]
I've collected the `show sess all` and `show fd` output when this happen:

```
0x7ffff78475e0: [01/Mar/2023:18:33:07.253883] id=11983 proto=tcpv4 source=127.0.0.1:36944
  flags=0x100c4a, conn_retries=0, conn_exp=<NEVER> conn_et=0x000 srv_conn=0xc088c0, pend_pos=(nil) waiting=0 epoch=0
  frontend=f (id=2 mode=http), listener=? (id=1) addr=127.0.0.1:8001
  backend=f (id=2 mode=http) addr=127.0.0.1:44992
  server=next (id=1) addr=127.0.0.1:8002
  task=0x7ffff7846f60 (state=0x00 nice=0 calls=1 rate=0 exp=8m17s tid=1(1/1) age=2s)
  txn=0x7ffff783bf20 flags=0x803000 meth=1 status=-1 req.st=MSG_DONE rsp.st=MSG_RPBEFORE req.f=0x4c rsp.f=0x00
  scf=0x7ffff7848fa0 flags=0x00000080 state=EST endp=CONN,0x7ffff7843f40,0x02804001 sub=1
      h1s=0x7ffff7843f40 h1s.flg=0x100040 .sd.flg=0x2804001 .req.state=MSG_DONE .res.state=MSG_RPBEFORE
      .meth=GET status=0 .sd.flg=0x02804001 .sc.flg=0x00000080 .sc.app=0x7ffff78475e0
      .subs=0x7ffff7848fb0(ev=1 tl=0x7ffff7845fc0 tl.calls=0 tl.ctx=0x7ffff7848fa0 tl.fct=sc_conn_io_cb)
      h1c=0x7ffff784df40 h1c.flg=0x0 .sub=0 .ibuf=0@(nil)+0/0 .obuf=0@(nil)+0/0 .task=0x7ffff7849f60 .exp=<NEVER>
      co0=0x7ffff784ef40 ctrl=tcpv4 xprt=RAW mux=H1 data=STRM target=LISTENER:0xc07df0
      flags=0x80000300 fd=31 fd.state=20 updt=0 fd.tmask=0x2
  scb=0x7ffff7844fa0 flags=0x00000011 state=EST endp=CONN,0x7ffff782df40,0x02800001 sub=1
      h1s=0x7ffff782df40 h1s.flg=0x4090 .sd.flg=0x2800001 .req.state=MSG_DONE .res.state=MSG_RPBEFORE
      .meth=GET status=0 .sd.flg=0x02800001 .sc.flg=0x00000011 .sc.app=0x7ffff78475e0
      .subs=0x7ffff7844fb0(ev=1 tl=0x7ffff782cfc0 tl.calls=1 tl.ctx=0x7ffff7844fa0 tl.fct=sc_conn_io_cb)
      h1c=0x7ffff782af40 h1c.flg=0x80000000 .sub=1 .ibuf=0@(nil)+0/0 .obuf=0@(nil)+0/0 .task=0x7ffff7830f60 .exp=<NEVER>
      co1=0x7ffff7833f40 ctrl=tcpv4 xprt=RAW mux=H1 data=STRM target=SERVER:0xc088c0
      flags=0x00000300 fd=32 fd.state=10121 updt=0 fd.tmask=0x2
  req=0x7ffff7847600 (f=0x49c40080 an=0x8000 pipe=0 tofwd=0 total=51)
      an_exp=<NEVER> rex=<NEVER> wex=<NEVER>
      buf=0x7ffff7847608 data=(nil) o=0 p=0 i=0 size=0
      htx=0x81d040 flags=0x0 size=0 data=0 used=0 wrap=NO extra=0
  res=0x7ffff7847660 (f=0x80400000 an=0x1400000 pipe=0 tofwd=0 total=0)
      an_exp=<NEVER> rex=8m17s wex=<NEVER>
      buf=0x7ffff7847668 data=(nil) o=0 p=0 i=0 size=0
      htx=0x81d040 flags=0x0 size=0 data=0 used=0 wrap=NO extra=0

     31 : st=0x000020(cl heopi W:sRa R:sra) ref=0 gid=1 tmask=0x2 umask=0x0 owner=0x7ffff784ef40 iocb=0x6b3155(sock_conn_iocb) back=0 cflg=0x80000300 fam=ipv4 lport=8001 rport=36944 fe=f mux=H1 ctx=0x7ffff784df40 h1c.flg=0x0 .sub=0 .ibuf=0@(nil)+0/0 .obuf=0@(nil)+0/0 .task=0x7ffff7849f60 .exp=<NEVER> h1s=0x7ffff7843f40 h1s.flg=0x100040 .sd.flg=0x2804001 .req.state=MSG_DONE .res.state=MSG_RPBEFORE .meth=GET status=0 .sd.flg=0x02804001 .sc.flg=0x00000080 .sc.app=0x7ffff78475e0 .subs=0x7ffff7848fb0(ev=1 tl=0x7ffff7845fc0 tl.calls=0 tl.ctx=0x7ffff7848fa0 tl.fct=sc_conn_io_cb) xprt=RAW
     32 : st=0x010121(cL heopI W:sRa R:srA) ref=0 gid=1 tmask=0x2 umask=0x2 owner=0x7ffff7833f40 iocb=0x6b3155(sock_conn_iocb) back=1 cflg=0x00000300 fam=ipv4 lport=44992 rport=8002 sv=f/next mux=H1 ctx=0x7ffff782af40 h1c.flg=0x80000000 .sub=1 .ibuf=0@(nil)+0/0 .obuf=0@(nil)+0/0 .task=0x7ffff7830f60 .exp=<NEVER> h1s=0x7ffff782df40 h1s.flg=0x4090 .sd.flg=0x2800001 .req.state=MSG_DONE .res.state=MSG_RPBEFORE .meth=GET status=0 .sd.flg=0x02800001 .sc.flg=0x00000011 .sc.app=0x7ffff78475e0 .subs=0x7ffff7844fb0(ev=1 tl=0x7ffff782cfc0 tl.calls=1 tl.ctx=0x7ffff7844fa0 tl.fct=sc_conn_io_cb) xprt=RAW
```

I'm investigating. But we have an "established" server connection on `next` without the corresponding client one on `b` frontend.

**Comment by capflam** [comment]
I merged the fix about this specific issue. Remain the Willy's issue, but it is not related. I'm marking this one as fixed.
