### ISSUE TITLE
Scheduling algorithm - first

### ISSUE THREAD

**Issue by chengsir520** [haproxy/haproxy#2062]
### Detailed Description of the Problem

The configuration uses the scheduling algorithm “first”, which defaults to 4095 connections. After the pressure test configuration, the request connection will not go up. Other scheduling algorithms are tested normally

### Expected Behavior

The problem may be the scheduling algorithm module, or the configuration is not suitable for this scenario

### Steps to Reproduce the Behavior

Configure and use the scheduling algorithm “first”, try to use large concurrency to test whether the number of connections can reach the limit

### What is your configuration?

```haproxy
backend servers
        mode http
        balance  first
```

### Output of `haproxy -vv`

```plain
[root@test-1 examples]# haproxy -vv
HA-Proxy version 1.8.0 2017/11/26
Copyright 2000-2017 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = 

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built without PCRE or PCRE2 support (using libc's regex instead)
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace

[root@test-1 examples]# uname -a
Linux test-1 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Darlelet** [comment]
It looks like you're using 1.8.0 version which is more than 5 years old.
Moreover 1.8 version is now EOL: it is recommended that you upgrade haproxy to a more up-to-date stable branch if possible.
 
Could you please try again with a more recent version (or at least update to the last 1.8.31 version) and come back to us if the issue still persists?

Thanks

**Comment by chengsir520** [comment]
Ok, thanks
