### ISSUE TITLE
maxconn affects /proc/$pid/limits in a strange way

### ISSUE THREAD

**Issue by fillest** [haproxy/haproxy#207]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.9.6-1ppa1~bionic 2019/03/30
Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
Linux somehost 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
	nbproc 16
	maxconn 0
defaults
	maxconn 100000
frontend some-front
	bind :80 process 1
	...
	bind :80 process 16
	bind :443 ssl crt .. 1
	...
	bind :443 ssl crt .. 16
backend some-back
	server server1 ip:80 check port 80 inter 1000ms fastinter 1000ms downinter 1000ms rise 2 fall 2 pool-max-conn -1 pool-purge-delay 99h
	...
	server server13 ip:80 check port 80 inter 1000ms fastinter 1000ms downinter 1000ms rise 2 fall 2 pool-max-conn -1 pool-purge-delay 99h
	option httpchk GET /some-url
```

## Steps to reproduce the behavior

1. `DefaultLimitNOFILE=1000000:1000000` is set in systemd globally 

## Actual behavior

```
$ cat /proc/4906/limits | grep 'open files'
Max open files            4388                 1000000              files    
```

## Expected behavior
Actually I'm failing to figure out what number to expect because the whole limiting system seems to be quite complex and it's hard to build a formula by reading `maxconn` docs. Honestly I expected it to be 1000000 because I of `global maxconn 0`.
I've started to dig into this because I've got some incident and want to try to increase the limit. Now I can't figure out how to do it with a controlled result. I've set _defaults_ `maxconn 200000` but the number in `cat ...limits` didn't change even after full restart. But - if I set _global_ `maxconn 500000` then
```
$ cat /proc/26543/limits | grep 'open files'
Max open files            1000388              1000388              files
```
Why? Also why does it show `1000388` hard limit now, how cant it be > 1000000?..

**Comment by wtarreau** [comment]
Just found this report that remained unresponded and was not noticed. 1.9 is dead but the question is general and I'll respond before closing.

The reason for your observation is that there isn't a 1:1 relation between FD and connections. Historically haproxy has always made sure to be able to sustain `maxconn` end-to-end connections from client to server. Some FDs are used by listeners, some by stats sockets (which must always be accessible), some by pipes, pollers, etc. This explains the complex calculation. Here what you found is that if you enforce 500k connections you need 1M FD just for these connections, plus roughly 388 FDs to cover for the other uses explained above. Thus there is nothing abnormal here, it's just that resources are secured to make sure they will be usable once needed.
