### ISSUE TITLE
Header value is static for http-check send

### ISSUE THREAD

**Issue by aj9411** [haproxy/haproxy#2075]
### Detailed Description of the Problem

Hey guys,

I am using haproxy and have this backend:

```
 backend backend_v
        mode http
        option httpchk GET /verifyonline
        http-check expect status 200
        server s01 {{ $.Values.hostname }}:{{ .backend_port }} check ssl verify none
        http-request set-header X-SSL-Client-DN             %{+Q}[ssl_c_s_dn]
        http-request set-header X-SSL-Client-CN             %{+Q}[ssl_c_s_dn(cn)]
        http-request set-header authorization "bearer %[str('bearertoken'),map(/certs/variables.map, NotSet)]"
        http-response del-header (Server|X-AspNet-Version|x-powered-by)
```

this backend sets a few headers on the http request, one of them being a bearer token. This bearer token is stored at `/certs/variables.map` and is refreshed when the token is near expiration by another process. You'll also see that we have an http check here calling `/verifyOnline`. Currently this is endpoint does not have an authorization requirement, which is not good even if it just returns a generic OK.

I saw that I could add headers to http checks as described here; https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#http-check%20send

So I changed the http check portion to:

```
option httpchk
http-check send meth GET uri /api/mqtt/verifyonline hdr authorization "bearer %[str('bearertoken'),map(/certs/variables.map, NotSet)]"
http-check expect status 200
```

and introduced an authorization requirement for the `/verifyOnline` API and this works, but sadly only for the first 24 hours after the service starts up. What I think is happening is:

1. Service starts up, gets bearer token and puts it on `/certs/variables.map`
2. backend http check grabs bearer token from `/certs/variables.map`
3. Things are good for 24 hours while the initial token is valid
4. After 24 hours, the token becomes invalid

So, it looks like the `http-check send` doesn't support 'dynamic' header values, which is a shame because it means I can't add that authorization requirement to my `/verifyOnline` API

Is there a way to make it work like ` http-request set-header`?

### Expected Behavior

I expected the `http-check send` to grab the current header value from local storage instead of keeping the initial header value forever.

### Steps to Reproduce the Behavior

Steps to repro: explained above

### What is your configuration?

```haproxy
Relevant backend config shared above.
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.9-3a3700a 2023/02/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.9.html
Running on: Linux 5.4.0-1100-azure #106~18.04.1-Ubuntu SMP Mon Dec 12 21:49:35 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -QUIC +RT +SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by capflam** [comment]
How are you updating the token ? If you just update the file content, this will not work. For the health checks but also for the regular requests. You must update the map content via the CLI ? The file is only read during HAProxy startup.

Please check  http://docs.haproxy.org/2.6/management.html#9.3 for more information about the CLI commands

**Comment by aj9411** [comment]
there's another process looping and checking for the current token's expiration. If it's time to get a new auth token, we get a new one and write it to the file. We haven't had problems with regular requests using the file (`http-request set-header authorization "bearer %[str('bearertoken'),map(/certs/variables.map, NotSet)]"`) for almost two years.

So, the proper thing to do would be to use the CLI to set and get a map entry corresponding to the token, getting the current token always?

**Comment by capflam** [comment]
If the other process only updates the file content, it cannot work. I don't know how the token is validated on your server, but the file content is only loaded during startup. There is no file access at runtime. To update a map dynamically, you should indeed use the CLI. It is the most obvious way to do. Of course, you must also still update the file to get the right value on reload/restart.

**Comment by aj9411** [comment]
Ok, I will use the map entries, thanks!

**Comment by aj9411** [comment]
Ok, sorry for rambling a bit here. I am re-opening in case it is a real bug now that I looked closed at the other process that refreshes the token. It actually sends a SIGUSR2 signal to the haproxy container, which is supposed to reload HAProxy as explained here: https://www.haproxy.com/documentation/hapee/latest/management/starting-stopping/#reload-the-configuration

So, I think that is why the regular http requests are working. For the case of the http check above, is it expected for a SIGUSR2 signal to reload the file content as well?

**Comment by capflam** [comment]
Indeed, SIGUSR2 signal triggers a reload if you are running in master/worker mode. Because it works for your requests, I guess it is your case. If a reload is really performed, it should indeed work.  I suspect your issue is not related to the sample evaluation in the health-checks. I performed some tests to be sure and this works as expected.

Have you any way to perform a test manually ? If yes, it could be good to get a network capture between HAProxy and your server to get the health-check requests before and after the token update. You can also explore the map content on the CLI using `show map #id` command before and after the reload.

**Comment by capflam** [comment]
gentle ping

**Comment by capflam** [comment]
Any news about this issue ? If you need more time to work on it, it is not a problem. I just want to be sure it is still alive. Thanks

**Comment by aj9411** [comment]
Sorry @capflam, change of priorities happened and I don't think I'll be working on this haproxy reload anymore. I'll close now as I don't have a way to gather evidence now. Thanks for the quick responses!

**Comment by aj9411** [comment]
closing as not planned
