### ISSUE TITLE
src/ssl_ocsp.c: dead code suspected by coverity

### ISSUE THREAD

**Issue by shipitsin-ilia** [haproxy/haproxy#2077]
### Tool Name and Version

coverity

### Code Report

```plain
/src/ssl_ocsp.c: 1410 in cli_parse_update_ocsp_response()


________________________________________________________________________________________________________
*** CID 1506560:  Control flow issues  (DEADCODE)
/src/ssl_ocsp.c: 1410 in cli_parse_update_ocsp_response()
1404            return 0;
1405     
1406     end:
1407            if (errcode & ERR_CODE) {
1408                    return cli_dynerr(appctx, memprintf(&err, "%sCan't send ocsp request for %s!\n", err ? err : "", args[3]));
1409            }
>>>     CID 1506560:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "return cli_dynmsg(appctx, 5...".
1410            return cli_dynmsg(appctx, LOG_NOTICE, err);
1411     }
1412     
1413     #endif  /* !defined OPENSSL_IS_BORINGSSL */
1414     
1415
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by rlebreton** [comment]
Thanks for the report, I simplified the function a bit to remove this dead code as well as a useless variable. Is also found a pretty unlikely leak that I fixed as well.
[0001-BUG-MINOR-ssl-Remove-dead-code-in-cli_parse_update_o.txt](https://github.com/haproxy/haproxy/files/11026959/0001-BUG-MINOR-ssl-Remove-dead-code-in-cli_parse_update_o.txt)
[0002-BUG-MINOR-ssl-Fix-potential-leak-in-cli_parse_update.txt](https://github.com/haproxy/haproxy/files/11026960/0002-BUG-MINOR-ssl-Fix-potential-leak-in-cli_parse_update.txt)

**Comment by capflam** [comment]
Both patches were merged. I guess we can close the issue now. Thanks !
