### ISSUE TITLE
TLS 1.3 Controlled Server Certificate using Signature Algorithms

### ISSUE THREAD

**Issue by madhanrajrm** [haproxy/haproxy#2081]
Hi Team ,

Certificate being returned by a server during TLS 1. 3 handshake.

We have an ssl bind(server) opened up on particular port . this particular bind “crt” has been loaded with both ECDSA and RSA based certificates .

For tls 1.2 handshake certificates being returned from server are based on Cipher Authentication Algorithm but for TLS 1.3 it is primarily controlled with help of Signature Algorithms.

Do we have any configuration in haproxy.conf to specify supported signature algorithms by server as well as to request client certificates based on this signature algorithms ?.

openSSL 1.1.1n.7.2.390 – version
FIPS mode: OFF

I need an control on certificates being offered by server back to client when haproxy uses them. As far as i researched through the ocde there are no calls being made from haproxy to SSL_CTX_set1_sigalgs() or SSL_set1_sigalgs() . 

Haproxy version:- 

[root@cucm-8 ~]# /usr/local/cm/bin/haproxy  -vvv
HA-Proxy version 2.0.27-dee3aad 2022/01/26 - https://haproxy.org/
Build options :
  TARGET  = custom
  CPU     = generic
  CC      = gcc
  CFLAGS  = -m64
  OPTIONS = USE_THREAD=1 USE_LINUX_SPLICE=1 USE_OPENSSL=1 USE_CPU_AFFINITY=1

Feature list : -EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE -NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 -TPROXY -LINUX_TPROXY +LINUX_SPLICE -LIBCRYPT -CRYPT_H -VSYSCALL -GETADDRINFO +OPENSSL -LUA -FUTEX -ACCEPT4 -CLOSEFROM -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : CiscoSSL 1.1.1n.7.2.390
Running on OpenSSL version : CiscoSSL 1.1.1n.7.2.390
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with transparent proxy support using: IP_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): no

Available polling systems :
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 2 (2 usable), will use poll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE        mux=H2
              h2 : mode=HTX        side=FE|BE     mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

[root@cucm-8 ~]# 

Thanks,
Madhan

**Comment by madhanrajrm** [comment]
Hi Team , Do anyone have any suggestions or pointers around this ?

**Comment by wlallemand** [comment]
Hello,

When having a RSA and ECDSA certificate for the same SNI, HAProxy will chose the right certificate based on what the client is supporting. The code is implemented here: https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L2453

I'm not sure to understand what you need, is the certificates not delivered correctly?

**Comment by madhanrajrm** [comment]
Hi @

> Hello,
> 
> When having a RSA and ECDSA certificate for the same SNI, HAProxy will chose the right certificate based on what the client is supporting. The code is implemented here: https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L2453
> 
> I'm not sure to understand what you need, is the certificates not delivered correctly?

Hi , Thanks for the response . 

Today I have a port opened in Haproxy which loads both ECDSA and RSA certs as well as it is mutual TLS port .

Lets say this is the port 8888 opened by Haproxy  to which my client ( which also supports both ECDSA and RSA certs) talks  with this port (8888) 

When server port(8888) opened by haproxy requests  for client certificate  it always prefers ecdsa based signature algorithms on top  so my client is always sending back ECDSA certificate during TLS 1.3 communication. 

So we need a way to instruct my port 8888 to control client cert signature algorithms offering.

**Comment by lukastribus** [comment]
So it's not about certificate the server sends to the client, but what the certificate the client sends to the server in a client ssl authentication configuration?

You still did not explain the use case or what problem you are trying to solve: why do you need to use the RSA certificate in a dual certificate configuration?

**Comment by madhanrajrm** [comment]
Our product is something which has evolved over years . So many of
customers still only sign their RSA certs because signing an ecdsa would be
costlier for them . So we are working a way to handle those old customers
as well as the new customers.

So by configuring the client signature algorithms  from server end we have
control on what client is going to offer back and trust flows from there .
We were able to achieve this in our other appl Code with help of these APIs
SSL_CTX_set1_sigalgs_list —> server end.

SSL_CTX_set1_client_sigalgs_list —> client end


Hence requesting haproxy also to provide this feature .

**Comment by lukastribus** [comment]
So the problem you are actually trying to solve is a compatibility issue with a SSL client that has RSA certificates only and you are implying that the handshake fails when the server has both EC/RSA certificates and TLSv1.3.

Is that correct?

If the client breaks when the client sigalgs list allows both EC and RSA but the client only has a RSA cert, that certainly sounds like a client bug, 

I don't see the equivalent options in nginx or Apache and I'm worried about feature creep in the SSL stack, especially because we are evaluating openssl alternatives.

I'd suggest you research putting those options in `openssl.cnf` machine-wide, so you can fix your problem today without any changes in upstream software.

On the haproxy side, this needs careful evaluation.

**Comment by madhanrajrm** [comment]
No thats not the exact problem , all our concerns are what   certificates
are being exchanged and how to force one particular certificate to get
exchanged though if client has both the certs.

Let me try to put it graphically here :-

Server (haproxy).     ————————> client
8888 port
Support both RSA                                 Supports both type of
certs
and ECDSA CERTS


I want to control the certs being offered by client based on servers
capabilities.

When i need client to send RSA  cert i would configure my server’s client
 sigalgs(SSL_CTX_set_client_sigalgs) only with RSA (or atleast i would be
prefering them on top) whereas if i need client ECDSA cert then i would
configure only with ecdsa algo’s.

This is how openssl recommends to have control the certs by having both the
type of certs being loaded in the CTX.
Reason why i need this because of cost of signing ecdsa is more.

So i am requesting for an haproxy config which would take these sigalgs as
an parameter (very similar to ciphers) in bind ssl options.

**Comment by lukastribus** [comment]
Yes, that is exactly what I said.

**Comment by wlallemand** [comment]
Thanks for explaining your problem. HAProxy has an SSL stack which is precisely configurable, and that kind of feature request is something that matches what we want to be able to configure.

We already had requests in the past to configure the Server Signature Algorithms for appliances that wasn't supporting the default ones but no patch made it to haproxy yet. Sometimes HAProxy is used to fixes the issues of others components so that totally makes sense. 

If I understand correctly your need, it only has to apply the SSL_CTX_set1_client_sigalgs_list on bind lines. IMHO this seems feasible and not that intrusive, If you are familiar with C you can even try to do the patch.

**Comment by wlallemand** [comment]
@madhanrajrm  The commit right above implements the "client-sigals" keyword which allows to configure the Signature Algorithm for Client Authentication for the bind lines, I also pushed the "sigals" keywords that does it for the Server Signature Algorithms.

**Comment by madhanrajrm** [comment]
Thanks  you @wlallemand  much appreciated !!!. Will pick this up . 

> @madhanrajrm The commit right above implements the "client-sigals" keyword which allows to configure the Signature Algorithm for Client Authentication for the bind lines, I also pushed the "sigals" keywords that does it for the Server Signature Algorithms.

**Comment by madhanrajrm** [comment]
one last query @wlallemand  , can i know when this code can get released officially in haproxy.org ?

**Comment by wlallemand** [comment]
@madhanrajrm It will be release with 2.8 in about 1 month.
