### ISSUE TITLE
Support IPV6 link scope addressing

### ISSUE THREAD

**Issue by clauderobi** [haproxy/haproxy#2097]
### Your Feature Request

Ability for HAProxy to support IPv6 link-scope addressing for backend definitopn, either directly or via mDNS name resolution. 

### What are you trying to do?

With this feature enabled, it becomes possible to use backend servers that have no IPv4 addresses and no IPv6 addresses other than the link-scope. Using this configuration helps in many ways:
- better security as the backend server can only be reached via the proxy.
- the backend servers can not reach out either so a compromised OS is limited in the harm it can cause. It can definitely no reach outside the L2 network. A firewall could achieve the same; but silent failures (misconfiguration, etc.) of the firewall"s rule can, and do, happen. 
- simplified management. As a way of an example, for certain scenario where the IP network is manged by another entity it is a challenge to find the IP address assigned to small devices. At the same time their MAC is available on the enclosure so this can be used instead. 

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.9-f8dcd9f 2021/11/24 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.9.html
Running on: FreeBSD 12.3-STABLE FreeBSD 12.3-STABLE RELENG_2_6_0-n226742-1285d6d205f pfSense amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-string-plus-int -Wtype-limits -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_STATIC_PCRE=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_PROMEX=1
  DEBUG   = 

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE +STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H +GETADDRINFO +OPENSSL +LUA -FUTEX +ACCEPT4 +CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL +PROCCTL -THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1l-freebsd  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l-freebsd  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
```

**Comment by lukastribus** [comment]
Also previously discussed in discourse:

https://discourse.haproxy.org/t/how-to-put-a-link-local-ipv6-address-in-server-of-a-backend/5592/

**Comment by wtarreau** [comment]
Interesting use case, thanks for reporting it (and thanks Lukas for the link). However, there's nowhere to store the interface name in the sockaddr_in6 struct, so I suspect that it's just an artificial representation that most programs have agreed upon over time. For example I remember that 15 years ago I needed to use "ping -I eth0 <lladdr>" on linux and "ping <lladdr>%eth0" on BSD. Thus I suspect the only difference is the interface binding.
Have you tried simply specifying "interface eth0" on your `bind` or `server` lines where you use that link-local addresses ? I suspect that would be all you'd need.

**Comment by clauderobi** [comment]
In fact, sockaddr_in6 does include the interface index. This is what sin6_scope_id is for. That field is only valid for a IPv6 link scope address and allows specifying the index. When using getAddrInfo(), with a correct IPv6 link scope address (i.e. with %interfacename), the returned sockadd_in6 is correct and directly suitable to use with connect(). 

I am using pfsense so I am a little limited in the tests I can do. At least, specifying an IPv6 link scope address is not supported when defining a backend. I assumed that this was because haproxy does not support this. May be I am wrong. But the link Lukas mentions indicates that someone else tried without success.

**Comment by wtarreau** [comment]
Ah I vaguely remember from last time I played with this ~20 years ago ;-)

I'm just confused by your last comment, you mean that even if we add explicit support for this in haproxy, it will not work because of pfsense ? Could you try on a regular OS (or just manually edit your config) ?  I think it's worth trying because if the socket is bound to the interface before connecting, I don't see why it wouldn't work.

**Comment by wtarreau** [comment]
Just tested here and it works! You need the `source` keyword on your `server` line because it's how the interface can be forced, we just omit the address and the port. I did it with this:
```
listen test
        bind :1234
        server ssh fe80::ea6a:1111:1111:1111:22 source ::: interface bond0
```
And when I'm connecting to port 1234 it properly passes the connection to the SSH server on the other machine.

**Comment by wtarreau** [comment]
I'm marking it as "works as designed", though I think that it could be worth adding some info in the doc to explain this.

**Comment by clauderobi** [comment]
Are you sure it works? Because for me it only works if the server is defined as follow:

server server1 [fe80::42:acff:fe13:3] source ::: interface eth0

Without the square bracket it **almost** works, except that the IPv6 address used is wrong (as seen with wireshark).

**Comment by wtarreau** [comment]
On Fri, Mar 31, 2023 at 10:21:20AM -0700, clauderobi wrote:
> Are you sure it works? Because for me it only works if the server is defined as follow:
> 
> server server1 [fe80::42:acff:fe13:3] source ::: interface eth0
> 
> Without the square bracket it **almost** works, except that the IPv6 address used is wrong (as seen with wireshark). 

Hehe :-) that's because a server always has a port, so whatever is after
the last colon is the port number. In my case the :22 was the SSH port ;-)
Above you're sending the traffic to port 3 of address fe80::42:acff:fe13
which thanks to IPv6 address compression is filled with zeroes between the
two colons.

This is the main reason why support for square brackets was recently
added. While some of us had no problem with that by being aware of the
format, lots of people were fooled by this.

Willy

**Comment by clauderobi** [comment]
Ok. I noticed the 22 but I assumed it was like 127.0.0.53 where you put the port as part of the actual IP address

The square brackets are the standard, like it or not...

Just for completeness, does the code use getAddrInfo? If so then if the DNS resolver supports IPv6 link scope (such as mdns / avahi) then resolving by name will work too.

**Comment by wtarreau** [comment]
> The square brackets are the standard, like it or not...

Actually they're standard for URLs only. Also that now common representation appeared after we started to support v6, and we still needed to support existing configs.

> Just for completeness, does the code use getAddrInfo

It does on operating systems which are known to have a working one. On half of those which provide one it's simply totally broken. But at least on the linux+glibc target it has been known to work for about a decade now and is enable by default.
