### ISSUE TITLE
just one certificate with "ca md too weak" in crt-list results with haproxy not starting

### ISSUE THREAD

**Issue by lukenowak** [haproxy/haproxy#2117]
### Detailed Description of the Problem

Haproxy fails to start with:

[ALERT]    (3712010) : config : parsing [haproxy.cfg:7] : 'bind 127.0.0.1:4443' in section 'frontend' : 'crt-list' : error processing line 1 in file 'crt-list.txt' : unable to load chain certificate into SSL Context 'cert.pem': ca md too weak. Make sure you are linking against Openssl >= 1.0.2.

### Expected Behavior

I expect haproxy to start with a warning and do not serve site with incorrect certificate.

### Steps to Reproduce the Behavior

Build haproxy with openssl-3.0.8-quic1.tar.gz, have certificate chain which leads to "ca md too weak" and use it with provided configuration.

### Do you have any idea what may have caused this?

Seems newer OpenSSL versions are stricter regarding certificate chains.

### Do you have an idea how to solve the issue?

I workarounded it by using OpenSSL_1_1_1s+quic1.tar.gz, then haproxy starts.

### What is your configuration?

```haproxy
$ cat haproxy.cfg 
global
  pidfile haproxy.pid
  master-worker

frontend https-frontend
  bind 127.0.0.1:4443 ssl crt-list crt-list.txt

$ cat crt-list.txt 
cert.pem somedomain.com
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8-dev7-28f2a5-17 2023/04/12 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :                                                            
  TARGET  = linux-glibc                                                    
  CPU     = generic                                                        
  CC      = cc                      
  CFLAGS  = -m64 -march=x86-64 -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-o
verflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clo
bbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_DL=1 USE_QUIC=1 USE_PCRE=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS                         
                                                                           
Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMI
C +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_
JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION +QUIC +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_D
UMP +TPROXY -WURFL +ZLIB                                                   

Default settings :       
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
                                     
Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.0.8+quic 7 Feb 2023
Running on OpenSSL version : OpenSSL 3.0.8+quic 7 Feb 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.3
Built with network namespace support. 
Built with zlib version : 1.2.12
Running on zlib version : 1.2.12
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

Note: haproxy will fail to start if I'll simply use the certificate with crt in the haproxy.cfg in case of openssl 3, but will simply run with openssl 1. Such behavior seems quite understandable for non massive hosting.

My context: I am using crt-list in massive hosting scenarios, and not starting haproxy results with problem for all sites, while being able to start and serve everything else is very good situation in such context.

**Comment by wlallemand** [comment]
This is the expected behavior, the certificates are considered part of the configuration, and you can't start HAProxy with a wrong configuration.

Your problem seems to be related to the configuration of openssl 3, you could probably fix the issue with SECLEVEL=0 in your openssl.cnf file.

Regarding the behavior you are expecting I have a suggestion:
You could start without any certificates loaded (using strict-sni keyword), then add some certificates and reload.
Or you could start without any certificates and add the certificates with "add ssl crt-list" on the CLI.

But in my opinion that doesn't make sense to start with a certificate which can't be loaded, because you wrote in your configuration to load this certificate, so the problem is the configuration.

**Comment by lukastribus** [comment]
I agree, when you upgrade your OS or libssl to a new major version, some changes and hard failures are expected. Hiding problems with a specific part of your configuration would be a lot worse in the majority of the cases.

**Comment by wtarreau** [comment]
Maybe the error message should be updated ? Right now it suggests to use OpenSSL >= 1.0.2, which is a bit outdated.

**Comment by lukenowak** [comment]
Thanks for the explanation, I got it. Also I'll do validation of certificates with minimal haproxy configuration, so I'll not end up with wrong configuration on live setup.

I am +1 for updating the error messages.

**Comment by wtarreau** [comment]
@wlallemand what about this ?
[ssl-improve-msg.diff.txt](https://github.com/haproxy/haproxy/files/11247141/ssl-improve-msg.diff.txt)

**Comment by wlallemand** [comment]
@wtarreau I don't think that's a good idea, you can have a lot of other errors here which are unrelated to SECLEVEL, and you could have an error related to SECLEVEL everywhere we try to load a certificate in the code. Since we now display the OpenSSL error I don't think there is something else to do, people just google the OpenSSL error.

I'll remove the OpenSSL 1.0.2 mention, which was introduced by 08ce6ab0c9fdad9cca599984b94cb58e63191116 with SSL_CTX containing several chains with different algorithm (ie bundle with ecdsa/rsa).

**Comment by wtarreau** [comment]
OK, thanks for the explanation, that works for me!
