### ISSUE TITLE
src/stream.c: copy paste suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2123]
* CID 1508826:  Incorrect expression  (COPY_PASTE_ERROR)
/src/stream.c: 2375 in process_stream()
2369                    sc_schedule_shutdown(scb);
2370            }
2371     
2372            /* shutdown(write) pending */
2373            if (unlikely((scb->flags & (SC_FL_SHUT_DONE|SC_FL_SHUT_WANTED)) == SC_FL_SHUT_WANTED &&
2374                         channel_is_empty(req))) {
>>>     CID 1508826:  Incorrect expression  (COPY_PASTE_ERROR)
>>>     "scf" in "scf->flags" looks like a copy-paste error.
2375                    if (scf->flags & SC_FL_ERROR)
2376                            scb->flags |= SC_FL_NOLINGER;
2377                    sc_shutdown(scb);
2378            }
2379     
2380            /* shutdown(write) done on server side, we must stop the client too */

**Comment by wtarreau** [comment]
Looks like Coverity is right on this one and I'm impressed. Actually I find such type of suggestions, that look more like a peer review, much more useful than the vast majority of gcc's absurd warnings. @capflam could you please check ?

**Comment by capflam** [comment]
There is no bug here. On the 2.7, we have this code:

```c
	/* shutdown(write) pending */
	if (unlikely((req->flags & (CF_SHUTW|CF_SHUTW_NOW)) == CF_SHUTW_NOW &&
		     channel_is_empty(req))) {
		if (req->flags & CF_READ_ERROR)
			scb->flags |= SC_FL_NOLINGER;
		sc_shutw(scb);
	}
```

So, if a shutdown for writes is pending for the request channel and this channel is empty, we can perform the shutdown. In addition, if there is a read error on this channel (the request one), `SC_FL_NOLINGER` flag is set on the back SC.

Translated in 2.8: If a shutdown is scheduled on the back SC and the request channel is empty, we can perform the shutdown. If a terminal error was encountered on the front SC, `SC_FL_NOLINGER` flag is set on the back SC.

**Comment by wtarreau** [comment]
Thank you for checking. Maybe such explanation would be useful to put there in a comment while it's still fresh in your mind :-)

**Comment by chipitsine** [comment]
I've marked as false positive
