### ISSUE TITLE
src/quic_conn.c: dead code suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2126]
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1508946:  Control flow issues  (DEADCODE)
/src/quic_conn.c: 8523 in qc_set_tid_affinity()
8517            return 0;
8518     
8519      err:
8520            task_destroy(t1);
8521            task_destroy(t2);
8522            if (t3)
>>>     CID 1508946:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach this statement: "tasklet_free(t3);".
8523                    tasklet_free(t3);
8524     
8525            TRACE_DEVEL("leaving on error", QUIC_EV_CONN_SET_AFFINITY, qc);
8526            return 1;
8527     }
8528
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by a-denoyelle** [comment]
Coverity is right indeed, but as we are on an error-path, I'm tented to ignore it as it's cleaner to free all resources there. If we later modify the code in this function and add new early return path it will be useful.

**Comment by chipitsine** [comment]
I've marked it as intentional

**Comment by TimWolla** [comment]
@a-denoyelle Commonly freeing functions are safe to be called with `NULL`, `tasklet_free()` currently isn't, but `task_destroy()` is. Would it make sense to add `if (!tl) return;` to `tasklet_free()` or is this too expensive? That check within `tasklet_free()` would avoid that every caller needs to check themselves.

**Comment by a-denoyelle** [comment]
I see no objection to add an extra check on NULL inside the function, unless @wtarreau has a good reason not to.

**Comment by wtarreau** [comment]
No, I think it's reasonable, for the sake of uniformity with other free* functions.

**Comment by TimWolla** [comment]
Okay, I'll reopen this and probably send a patch later.
