### ISSUE TITLE
need help on why https doesn't work 

### ISSUE THREAD

**Issue by ishallbethat** [haproxy/haproxy#213]
Hi I don't know why https doesn't work. Http works perfectly.
Here is my haproxy.cfg.  And my haproxy is version "HA-Proxy version 1.6.3 2015/12/25"
`global
        log 127.0.0.1:514  local0
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

resolvers dns
nameserver hk 210.177.255.186:53
hold valid 1s

frontend http_api
        bind *:80
        mode http
	acl network_allowed src  10.28.0.0/14 10.32.0.0/14 10.12.0.0/14 10.60.0.0/14
        acl google hdr_beg(host) -i www.google.com
        http-request deny if !network_allowed
	option forwardfor
	use_backend google_backend if google

frontend https_api
        bind *:443
        mode tcp
        acl network_allowed src  10.28.0.0/14 10.32.0.0/14 10.12.0.0/14 10.60.0.0/14
        acl misumi hdr_beg(host) -i xxx.xxx.xxx
        http-request deny if !network_allowed
        option forwardfor
        use_backend misumi_backend if misumi

backend google_backend
        mode http
	balance roundrobin
        server google www.google.com:80  check inter 1000 resolvers dns
	#server nginx 10.128.0.121:80

backend misumi_backend
        mode tcp
        balance roundrobin
        server misumi xxx.xxx.xxx:443  check inter 1000 resolvers dns
`

**Comment by lukastribus** [comment]
You flat out ignored the question template completely.

Closing without any further comments.
