### ISSUE TITLE
Hapoxy Rate limit performance issue during  sudden traffic surge 

### ISSUE THREAD

**Issue by nishantpratap1** [haproxy/haproxy#2134]
### Detailed Description of the Problem

backend st_user-profile
    stick-table type string size 100k expire 1s store http_req_rate(1s)

frontend user-web-fe
    bind *:443 ssl crt /etc/haproxy/secure.org.com.pem no-sslv3
    acl host_service_pt hdr(host) service-pt.org.com
    
    acl restricted_swagger_page url_beg /swagger-ui.html /v2/api-docs
    http-request deny if restricted_swagger_page
    
    acl user-profile url_beg /user/profile/meta/app/v4
    acl st_user-profile_limit str("/user/profile/meta/app/v4"),table_http_req_rate(st_user-profile) gt 1000
    http-request track-sc0 str("/user/profile/meta/app/v4") table st_user-profile if !st_user-profile_limit host_service_pt user-profile
    http-request deny deny_status 429 if st_user-profile_limit host_service_pt user-profile      capture request header True-Client-IP len 64
    
    reqadd X-Forwarded-Proto:\ https

    use_backend service-be-pt  if   host_service_pt

backend service-be-pt
    balance leastconn
    server service-t-1 127.0.0.1:31121 check
    server service-t-2 127.0.0.2:31121 check

This is my  haproxy config for a service that i am doing PT for  in my org , but i am seeing strange behaviour it's not working in case of traffic surge 
 what wrong i am  doing here ? 
 is there any major diff in terms of rate limiting in enterprise edition or community edition .
 
 
 Attaching graph here 
<img width="986" alt="image" src="https://user-images.githubusercontent.com/70062154/234015798-9f9d3b0d-a908-4b27-aabd-cd221750f29d.png">

 

### Expected Behavior

ideally it should have accepted 1000 request , but it's coming around 300-500 range , and total traffic is 2000 req per second , and if we further increase the load , the performance degrades gradually. 

### Steps to Reproduce the Behavior

1.  Use stick table of type string 
2.  Use tracksc0 counter of str type 
3. Increase load to 2x ,3x, 4x 

### Do you have any idea what may have caused this?

maybe stick table type we are using but not so sure 

### Do you have an idea how to solve the issue?

Tried various parameters till now , tried to tune the haproxy , but still no success , we want to implement exact  limit .

### What is your configuration?

```haproxy
backend st_user-profile
    stick-table type string size 100k expire 1s store http_req_rate(1s)

frontend user-web-fe
    bind *:443 ssl crt /etc/haproxy/secure.org.com.pem no-sslv3
    acl host_service_pt hdr(host) service-pt.org.com
    
    acl restricted_swagger_page url_beg /swagger-ui.html /v2/api-docs
    http-request deny if restricted_swagger_page
    
    acl user-profile url_beg /user/profile/meta/app/v4
    acl st_user-profile_limit str("/user/profile/meta/app/v4"),table_http_req_rate(st_user-profile) gt 1000
    http-request track-sc0 str("/user/profile/meta/app/v4") table st_user-profile if !st_user-profile_limit host_service_pt user-profile
    http-request deny deny_status 429 if st_user-profile_limit host_service_pt user-profile      capture request header True-Client-IP len 64
    
    reqadd X-Forwarded-Proto:\ https

    use_backend service-be-pt  if   host_service_pt





backend service-be-pt
    balance leastconn
    server service-t-1 127.0.0.1:31121 check
    server service-t-2 127.0.0.2:31121 check
```

### Output of `haproxy -vv`

```plain
haproxy -c -V -f /etc/haproxy/haproxy.cfg

Configuration file is valid


haproxy -vv
HA-Proxy version 1.8.20 2019/04/25
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.4
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace


```

**Comment by git001** [comment]
Please add the output of `haproxy -vv` to the issue

**Comment by nishantpratap1** [comment]
> Please add the output of `haproxy -vv` to the issue

haproxy -vv
HA-Proxy version 1.8.20 2019/04/25
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.4
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace

**Comment by git001** [comment]
Please can you use a more recent version of HAProxy as the 1.8 isn't anymore maintained since 2022-Q4.  
https://www.haproxy.org/

I would suggest to use latest 2.6

> is there any major diff in terms of rate limiting in enterprise edition or community edition

I would say no but I never used a enterprise edition so this question can be answered maybe better from a enterprise edition user :smile:

**Comment by shadyabhi** [comment]
@nishantpratap1 You should upgrade HAproxy soon, we've even had core dumps in production due to thread performance with stick tables in production. https://github.com/haproxy/haproxy/issues/1918

**Comment by nishantpratap1** [comment]
@shadyabhi  @git001   after upgrading to 2.2.24 ,  performance is still the same 

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/70062154/234238643-5fbc8857-e951-400d-b6c4-bd90f20ac221.png">


sharing haproxy --vv 
haproxy -vv 
HA-Proxy version 2.2.24-26b8015 2022/05/13 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.24.html
Running on: Linux 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DMAX_SESS_STKCTR=12
  OPTIONS = USE_PCRE2=1 USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.4
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.23 2017-02-14
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

**Comment by capflam** [comment]
The 2.2.24 is also outdated (1-year old).  It does not mean this will fix your issue. But we will not look for a bug on an outdated version. But at first glance, it is most probably a configuration issue. I suggest to ask some help on discourse (https://discourse.haproxy.org/)

**Comment by nishantpratap1** [comment]
@capflam  Thanks  , I was suspecting the same , that  only version upgrade  is not going to fix this , maybe I am not able to guess where I am going wrong in setting config .
I raised the topic as you mentioned , hoping to solve this soon

**Comment by capflam** [comment]
I'm closing. But feel free to reopen if it is finally an bug and not a configuration issue. Thanks !
