### ISSUE TITLE
HAProxy receiving TCP Reset from Load Balancer

### ISSUE THREAD

**Issue by infa-sanaik** [haproxy/haproxy#2135]
### Detailed Description of the Problem

Our setup is haproxy (https) sending traffic to Azure LB (in TCP mode) sending traffic to envoy ingress gateway.
http-reuse is set to default value i.e. safe
pool-max-conn is not set so it defaults to -1
pool-purge-delay is not set so it defaults to 5s
Periodically, HAProxy receives TCP reset from Azure LB after sending application data.
We do not see a TCP connection initiation sequence in that TCP stream which means HAProxy is sending data on an existing connection.
The reset is not sent by envoy proxy.
Only case Azure LB can send TCP reset is when connection idle.
Idle timeout of Azure LB is 15 minutes. #of resets increase a lot when it is set to 4 minutes.
TCP resets are not seen if http-reuse is set to never or Azure LB is bypassed and traffic is sent directly to envoy proxy

### Expected Behavior

HAProxy should not let connection remain idle for more than 15 mins.
We believe Azure LB is sending TCP reset after 15 mins but somehow HAProxy is not closing the connection.
Is there any parameter to control max-age of idle backend connections?

### Steps to Reproduce the Behavior

send traffic with some gaps/delays
issue is not seen when traffic is continuously flowing i.e. when backend connections remain active.

### What is your configuration?

```haproxy
http-reuse is set to default value i.e. safe
pool-max-conn is not set so it defaults to -1
pool-purge-delay is not set so it defaults to 5s
```

### Output of `haproxy -vv`

```plain
$ /usr/sbin/haproxy -vv
HAProxy version 2.4.17-9f97155 2022/05/13 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.17.html
Running on: Linux 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_LIBCRYPT=1 USE_CRYPT_H=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.4.2
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by lukastribus** [comment]
This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

* The forum is at: https://discourse.haproxy.org/
* The mailing list (no need to subscribe) is: [haproxy@formilux.org](mailto:haproxy@formilux.org)
* Subscribe to the list: [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)
 * Unsubscribe from the list: [haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)



Sounds like you want to configure TCP keepalives on the backend. Something like:

    backend abc
     option srvtcpka
     srvtcpka-idle 180
     srvtcpka-intvl 15
     srvtcpka-cnt 4


This will enable TCP keepalive in `backend abc`, triggering a keepalive message every 180 seconds when the TCP session was idle for at least that long and then tries every 15 seconds for 4 times to get a response before ultimately closing the socket.

Check the documentation (haproxy and kernel) for more informations about TCP keepalive. Use the aforementioned forums and mailing list for generic support.
