### ISSUE TITLE
Security issue with Mariadb Galera Cluster 

### ISSUE THREAD

**Issue by Nem-developing** [haproxy/haproxy#2137]
### Detailed Description of the Problem

# Introduction
Hello everyone. 

Today I found a security issue on Hapoxy with Galera Mariadb. 

When I try to connect to the FrontEnd side with **mycli**, It does not require a password with valid user (wich, of course, require a valid password), and even fake users like 'toto' or 'tata' (those users don't exist in my cluster) can connect to the cluster through haproxy. 

# My infrastructure :
| Name   |      PORT      |  Replication Port |
|----------|:-------------:|------:|
| HaProxy  |  3300 | 4567 |
| mysqld1  |  3301 | 4567 |
| mysqld2  |  3302 | 4568 |
| mysqld3  |  3303 | 4569 |
| mysqld4  |  3304 | 4570 |

## List of users :
```sql
MariaDB [(none)]> SELECT user, password, host FROM mysql.user;
+-------------+----------+----------------------------------+
| User        | Password | Host                             |
+-------------+----------+----------------------------------+
| mariadb.sys |          | localhost                        |
| root        | invalid  | localhost                        |
| mysql       | invalid  | localhost                        |
|             |          | localhost                        |
|             |          | barkia-nehemie-tp-multi-services |
| haproxy     |          | %                                |
+-------------+----------+----------------------------------+
```
Here we can see a list of all users created into my cluster.
 ## Example of the security issue
```sql
root@cloudshell:~$ mycli -u tata  -h 35.195.199.249 -P 3300
MariaDB 10.5.18
mycli 1.26.1
Home: http://mycli.net
Bug tracker: https://github.com/dbcli/mycli/issues
Thanks to the contributor - BuonOmo
MariaDB tata@35.195.199.249:(none)> select user(),current_user();
+----------------+----------------+
| user()         | current_user() |
+----------------+----------------+
| tata@localhost | @localhost     |
+----------------+----------------+

1 row in set
Time: 0.014s
```
We can see that I can be connect to the cluster without specifing a password and also with a "fake" user.
 ## Confirmation of the security issue
When I try the same command without using Haproxy :
```bash
root@cloudshell:~$ mycli -u tata  -h 35.195.199.249 -P 3301
Password:
(1045, "Access denied for user 'tata'@'34.77.55.129' (using password: YES)")
root@cloudshell:~$ mycli -u tata  -h 35.195.199.249 -P 3302
Password:
(1045, "Access denied for user 'tata'@'34.77.55.129' (using password: YES)")
root@cloudshell:~$ mycli -u tata  -h 35.195.199.249 -P 3303
Password:
(1045, "Access denied for user 'tata'@'34.77.55.129' (using password: YES)")
root@cloudshell:~$ mycli -u tata  -h 35.195.199.249 -P 3304
Password:
(1045, "Access denied for user 'tata'@'34.77.55.129' (using password: YES)")
```
I used the google cloud shell to be outside of my cluster to show you the security issue. And for information, I got rejected if I try with root. 

# Conclusion
Thank you to have read this issue. I hope that a solution will be found and the problem, recreated. 

### Expected Behavior

Request must be rejected.

### Steps to Reproduce the Behavior

Use one of those commands : 
- mycli -u admin  -h 35.195.199.249 -P 3300
- mycli -u tata  -h 35.195.199.249 -P 3300
- mycli -u toto  -h 35.195.199.249 -P 3300
- mycli -u " "  -h 35.195.199.249 -P 3300

My exact configuration can be recreated with this documentation (it's in french but you will be able to see every configuration that i made): https://files.nehemiebarkia.fr/ISSUE/installation_cluster_mariadb_galera_BARKIA_NEHEMIE.pdf

If you need more information, please contact me at **nehemiebarkia@gmail.com** I've saved somes history.

### Do you have any idea what may have caused this?

N/A

### Do you have an idea how to solve the issue?

N/A

### What is your configuration?
```haproxy
**Environement :** 
Host : Google Cloud VM

**Haproxy version :** 
HA-Proxy version 2.2.9-2+deb11u5 2023/04/10 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
Running on: Linux 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64

**Galera version :**
4.11(r7b59af73

**Mariadb version :**
mariadb  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Mycli version : **
Version: 1.26.1
```
**Specific Haproxy Configuration :** 
```haproxy
listen galera
    bind 0.0.0.0:3300
    balance roundrobin
    mode tcp
    option tcpka
    option mysql-check user haproxy
    server galera-mariadb-1 127.0.0.1:3301 check weight 1
    server galera-mariadb-2 127.0.0.1:3302 check weight 1
    server galera-mariadb-3 127.0.0.1:3303 check weight 1
    server galera-mariadb-4 127.0.0.1:3304 check weight 1
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.9-2+deb11u5 2023/04/10 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
Running on: Linux 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -ffile-prefix-map=/build/haproxy-6Gqgxt/haproxy-2.2.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

### Last Outputs and Backtraces

```plain
No error in Haproxy Logs. 

Apr 25 16:27:00 debian haproxy[421]: 34.77.55.129:57522 [25/Apr/2023:16:27:00.584] galera galera/galera-mariadb-2 1/0/124 811 -- 2/2/1/0/0 0/0
Apr 25 16:27:50 debian haproxy[421]: 34.77.55.129:57508 [25/Apr/2023:16:27:00.573] galera galera/galera-mariadb-1 1/0/50008 186 cD 1/1/0/0/0 0/0
Apr 25 16:28:16 debian haproxy[421]: 34.77.55.129:47880 [25/Apr/2023:16:28:16.811] galera galera/galera-mariadb-4 1/0/124 811 -- 2/2/1/0/0 0/0
Apr 25 16:28:18 debian haproxy[421]: 34.77.55.129:47878 [25/Apr/2023:16:28:16.804] galera galera/galera-mariadb-3 1/0/1215 186 -- 1/1/0/0/0 0/0
Apr 25 16:28:40 debian haproxy[421]: 34.77.55.129:46224 [25/Apr/2023:16:28:40.819] galera galera/galera-mariadb-2 1/0/118 811 -- 2/2/1/0/0 0/0
Apr 25 16:28:42 debian haproxy[421]: 34.77.55.129:46218 [25/Apr/2023:16:28:40.813] galera galera/galera-mariadb-1 1/0/1826 186 -- 1/1/0/0/0 0/0
Apr 25 16:43:02 debian haproxy[421]: 34.77.55.129:37134 [25/Apr/2023:16:43:02.474] galera galera/galera-mariadb-4 1/0/121 811 -- 2/2/1/0/0 0/0
Apr 25 16:43:35 debian haproxy[421]: 34.77.55.129:37128 [25/Apr/2023:16:43:02.467] galera galera/galera-mariadb-3 1/0/32983 186 -- 1/1/0/0/0 0/0
Apr 25 16:43:47 debian haproxy[421]: 34.77.55.129:43564 [25/Apr/2023:16:43:47.682] galera galera/galera-mariadb-2 1/0/123 811 -- 2/2/1/0/0 0/0
Apr 25 16:45:00 debian haproxy[421]: 34.77.55.129:43562 [25/Apr/2023:16:43:47.675] galera galera/galera-mariadb-1 1/0/73044 311 cD 1/1/0/0/0 0/0
```

### Additional Information

- I didn't made any mysql_secure_installation.
- In the MyCli command, I need to put two spaces between the username and the "-h".

**Comment by lukastribus** [comment]
This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

* The forum is at: https://discourse.haproxy.org/
* The mailing list (no need to subscribe) is: [haproxy@formilux.org](mailto:haproxy@formilux.org)
* Subscribe to the list: [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)
 * Unsubscribe from the list: [haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)

**Comment by Nem-developing** [comment]
Hello. 

How is it possible that you said that it's not an Haproxy security issue ? The problem comes only when we request the cluster through the Haproxy Frontend.

**Comment by capflam** [comment]
There is no SQL support in HAProxy. It just acts as a TCP proxy and does nothing else to pass data from a side to the other one. Thus, it must be a configuration issue with your cluster. You must check your credentials.

**Comment by lukastribus** [comment]
Haproxy connects one TCP socket with another in this configuration, that is all. There is nothing in haproxy that can make it bypass mysql authentication.

You can do the same with netcat.

You did not provide an analysis showing the security issue in haproxy, you just provided a problem looking for a solution, security related or otherwise, that is why your request does not belong in the bug tracker.

Also, when you have issue like this, I strongly suggest to switch to the official mysql client first, as opposed to some python reimplementation of the mysql protocol found on github.

**Comment by Nem-developing** [comment]
Hello. here is an example of the security issue with mysql : 

```sql
xxxx@debian-tower:~$ mysql -u ''  -h xxx.xxx.xx.87 -P 3300
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 298
Server version: 10.5.18-MariaDB-0+deb11u1 Debian 11

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select current_user;
+--------------+
| current_user |
+--------------+
| @localhost   |
+--------------+
1 row in set (0,030 sec)

MariaDB [(none)]> exit
Bye
xxxx@debian-tower:~$ mysql -u ' '  -h xxx.xxx.xx.87 -P 3300
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 298
Server version: 10.5.18-MariaDB-0+deb11u1 Debian 11

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> exit
Bye

xxxx@debian-tower:~$ mysql -u toto  -h xxx.xxx.xx.87 -P 3300
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 334
Server version: 10.5.18-MariaDB-0+deb11u1 Debian 11

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select current_user;
+--------------+
| current_user |
+--------------+
| @localhost   |
+--------------+
1 row in set (0,032 sec)

MariaDB [(none)]> exit
Bye
```
As you can see, it do not depend on the mysql tool used. The security issue depend on Haproxy. I've did the verification before texting you.
Néhémie Barkia.

**Comment by TimWolla** [comment]
The security issue is that your MySQL authentication config grants everyone access who connects from localhost. By putting HAProxy with the given configuration in front of MySQL everyone is connecting from localhost. If a reverse proxy is capable of disabling the authentication of the services behind them, the issue is in the service, not in the reverse proxy. If you are having issues with securely configuring your Galera cluster, please seek advice from an experienced Galera DBA.

**Comment by Nem-developing** [comment]
Mabe it's because my Haproxy is into the same server than my cluster ? 
But It's still weird that by default, everyone can login without anything.

**Comment by TimWolla** [comment]
Multiple developers told you in clear words that the issue is not in HAProxy and that HAProxy issue tracker is not the correct location to seek help with correctly configuring a Galera cluster. Please seek help with an experienced Galera DBA. I'm locking this issue at this point to avoid any more email notifications being sent to all the folks watching this repository for an unrelated issue (and I apologize for adding this last notification myself).
