### ISSUE TITLE
server ssl verify none not obayed 

### ISSUE THREAD

**Issue by dik23** [haproxy/haproxy#2142]
### Detailed Description of the Problem

I have a multi-server [crowdsec](https://www.crowdsec.net/) setup with haproxy in the front and the crowdsec LAPI host running behind and using letsencrypt certs.  The relevant haproxy config is described [here](https://www.crowdsec.net/blog/the-haproxy-bouncer-is-out) with the multi-server setup described [here](https://www.crowdsec.net/blog/multi-server-setup) and the https part described [here](https://www.linuxjournal.com/content/improve-crowdsec-multi-server-installation-https-between-agents)

The two machines are connected in crowdsec, I can see that the haproxy machine is registered with the LAPI host

My backends contains

`server crowdsec myserver.com:9090 check ssl verify none`

Restart haproxy and the haproxy bouncer fails to register on the LAPI host

`Apr 28 17:13:29 ip-10-0-0-178 haproxy[208509]: Stream Query with startup true
Apr 28 17:13:29 ip-10-0-0-178 haproxy[208509]: Start fetching decisions: startup=true
Apr 28 17:13:29 ip-10-0-0-178 haproxy[208509]: -:- [28/Apr/2023:17:13:29.157] <HTTPCLIENT> <HTTPCLIENT>/<HTTPSCLIENT> 2/0/-1/-1/3 503 217 - - SC-- 0/0/0/0/3 0/0 {} "GET https://10.0.0.245:9090/v1/decisions/stream?startup=true HTTP/1.1"
Apr 28 17:13:29 ip-10-0-0-178 haproxy[208509]: Got error fetching decisions from Crowdsec: 503 (<html><body><h1>503 Service Unavailable</h1>.No server is available to handle this request..</body></html>.)
Apr 28 17:13:29 ip-10-0-0-178 haproxy[208509]: Got error fetching decisions from Crowdsec: 503 (<html><body><h1>503 Service Unavailable</h1>.No server is available to handle this request..</body></html>.)
Apr 28 17:13:29 ip-10-0-0-178 haproxy[208509]: [alert] 117/171329 (208509) : Got error fetching decisions from Crowdsec: 503 (<html><body><h1>503 Service Unavailable</h1>.No server is available to handle this request..</body></html>.)
Apr 28 17:13:22 ip-10-0-0-178 haproxy[39433]: Got error fetching decisions from Crowdsec: 503 (<html><body><h1>503 Service Unavailable</h1>.No server is available to handle this request..</body></html>.)
`

If I add `httpclient.ssl.verify none` in global and restart haproxy it connects to the LAPI host straight away

`Apr 28 17:31:06 ip-10-0-0-178 haproxy[39433]: Stream Query with startup false
Apr 28 17:31:06 ip-10-0-0-178 haproxy[39433]: Start fetching decisions: startup=false
Apr 28 17:31:06 ip-10-0-0-178 haproxy[212764]: Stream Query with startup false
Apr 28 17:31:06 ip-10-0-0-178 haproxy[212764]: Start fetching decisions: startup=false
Apr 28 17:31:06 ip-10-0-0-178 haproxy[212764]: -:- [28/Apr/2023:17:31:06.064] <HTTPCLIENT> <HTTPCLIENT>/<HTTPSCLIENT> 2/0/0/51/51 200 153 - - ---- 0/0/0/0/0 0/0 {} "GET https://10.0.0.245:9090/v1/decisions/stream?startup=false HTTP/1.1"
Apr 28 17:31:06 ip-10-0-0-178 haproxy[212764]: Decisions fetched: startup=false
`

The [docs for 2.6](https://docs.haproxy.org/2.6/configuration.html#httpclient.ssl.verify) states

`Works the same way as the verify option on server lines. If specified to 'none',
servers certificates are not verified. Default option is "required".
`

It's clearly not working the same as the verify option on server lines

### Expected Behavior

`ssl verify none` works the same as `httpclient.ssl.verify none`

### Steps to Reproduce the Behavior

See above

### What is your configuration?

```haproxy
https://github.com/crowdsecurity/cs-haproxy-bouncer/blob/031e1e37fea48a97d9e102f660b47027510c5a9f/haproxy.cfg
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.12-1ppa1~jammy 2023/04/01 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.12.html
Running on: Linux 5.15.0-1035-aws #39-Ubuntu SMP Wed Apr 19 13:47:15 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_OT=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL +OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -QUIC +RT +SLZ -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[  OT] opentracing
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

Ubuntu 22.04.2 LTS
haproxy 2.6.12-1ppa1~jammy
crowdsec-haproxy-bouncer  0.0.5

[crowdsec.lua](https://github.com/crowdsecurity/cs-haproxy-bouncer/blob/031e1e37fea48a97d9e102f660b47027510c5a9f/lib/crowdsec.lua)

**Comment by lukastribus** [comment]
You will have to provide a configuration to reproduce the issue, referring to 3 different blog posts is not going to be enough.


> It's clearly not working the same as the verify option on server lines

"Works the same way" is does not mean the options are the same exact thing or that they are interchangeable. They are not.

The `verify` keyword on the server line is relevant for SSL certificate verification for backend servers.
`httpclient.ssl.verify` is relevant for the httpclient.

They work the same way, but apply to different features.

**Comment by capflam** [comment]
a gentle ping

**Comment by dik23** [comment]
I'm not longer using this so am unable to update
