### ISSUE TITLE
Dynamic loading of 'new' certificate reports sucess but not seems to resolve name from https request.

### ISSUE THREAD

**Issue by paradisaeidae** [haproxy/haproxy#2148]
### Detailed Description of the Problem

As described by: https://www.haproxy.com/blog/dynamic-ssl-certificate-storage-in-haproxy/
.. a new certificate should be dynamically loadable.
This is also suggested by: https://gist.github.com/haproxytechblog
Though it is not clear if a cert.list should be applied as well as a new ssl cert command.

### Expected Behavior

The https request should succeed for the new domain.

### Steps to Reproduce the Behavior

export allChains=/whereareyour_DIRs_of_pems
export subdir=hereareyoupems # beneath whereareyour_DIRs_of_pems
export newcert=anewcert.pem
export httpDom=thedomain.for.pem
ls -l $allChains/$subdir/$newcert
echo 'pause for ll'; read answer

mv $allChains/$subdir/$newcert $allChains/ # Hide the pem from haproxy
sudo killall -9 haproxy
sudo systemctl start haproxy
echo 'Now newcert is now disabled'
wget https://$httpDom
echo 'pause for test'; read answer

mv $allChains/$newcert $allChains/$subdir/ # pem now in dir nominated by config.

echo -e "new    ssl cert $allChains/$subdir/$newcert" | socat unix-connect:/var/run/haproxy.sock -
echo 'pause for new'; read answer
echo -e "set    ssl cert $allChains/$subdir/$newcert <<\n$(cat $allChains/$subdir/$newcert | grep . )\n" | socat unix-connect:/var/run/haproxy.sock -
echo 'pause for set'; read answer
echo -e "commit ssl cert $allChains/$subdir/$newcert" | socat unix-connect:/var/run/haproxy.sock -
#$ echo -e "add ssl  crt-list /etc/haproxy/cert-list.txt <<\n/etc/haproxy/certs/new_certificate.pem [alpn h2] mysite.local\n" | socat  unix-connect:/var/run/haproxy.sock -
#$ echo -e "show ssl crt-list /etc/haproxy/cert-list.txt <<\n/etc/haproxy/certs/new_certificate.pem [alpn h2] mysite.local\n" | socat  unix-connect:/var/run/haproxy.sock -
wget https://$httpDom

### Do you have any idea what may have caused this?

The new ssl cert, set ssl cert and the commit commands report success.
So there may be a seperate table needing the new domain added.
This may be the sni table?? 

### Do you have an idea how to solve the issue?

No idea, sorry.

### Last Outputs and Backtraces

```plain
Does not crash.
```

### Additional Information

This is a test environment, low stress.

**Comment by wlallemand** [comment]
If you want to update an existing certificate, you just need to do `set ssl cert`  then `commit ssl cert`. If you want to add new certificates dynamically, you need to have either a crt-list or a directory configured on your bind line.

**Comment by wlallemand** [comment]
If you want to update an existing certificate, you just need to do `set ssl cert`  then `commit ssl cert`. 

If you want to add new certificates dynamically, you need to have either a crt-list or a directory configured on your bind line. Then:
- `new ssl cert`
- `set ssl cert`
- `commit ssl cert`
These 3 commands will create the certificate storage, then you need to add it to your crt-list with: `add ssl crt-list`.

**Comment by wlallemand** [comment]
It looks like you are trying to use `add ssl crt-list` with a crt-list which does not exist in your configuration. use `show ssl crt-list` to show the list of available crt-list, I presume you want to use the directory `certsdir` which should be shown as a crt-list .

**Comment by paradisaeidae** [comment]
Thanks! Gotit!
Wonderful!
