### ISSUE TITLE
HAproxy 2.6.7 unable to load SSL certificate into SSL Context after upgrade from 2.0.22

### ISSUE THREAD

**Issue by janezhen08** [haproxy/haproxy#2152]
### Detailed Description of the Problem

Hello Team,

Recently we upgrade haproxy from v2.0.22 to v2.6.7, after upgrade, haproxy failed to read the configuration, error:

[ALERT]    (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:54] : 'bind *:443' in section 'frontend' : error processing line 0 in file '/xxx' : unable to load SSL certificate into SSL Context '/xxx/xx.crt'.

This cert is uploaded in 2019, and it was working fine previously before the upgrade.

But now it failed to load SSL certificate into SSL Context.

Could you take a look and advise what's the root cause?

thanks

Jane

### Expected Behavior

It should be able to load SSL certificate into SSL Context.

### Steps to Reproduce the Behavior

if we upload the cert and restart haproxy, it will load the cert and throw errors:

[ALERT]    (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:54] : 'bind *:443' in section 'frontend' : error processing line 0 in file '/xxx' : unable to load SSL certificate into SSL Context '/xxx/xx.crt'.

### Do you have any idea what may have caused this?

I think it may related to haproxy version upgrade.

### Do you have an idea how to solve the issue?

no

### What is your configuration?

```haproxy
Below is part of the configuration:

frontend xxxx
  # Port 83 handles SSL termination at Ext LB. Port 443 handles SSL termination at haproxy
  bind *:443 ssl no-sslv3 no-tlsv10 no-tlsv11 crt /certs/default.pem crt /xxxx
  bind *:83
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.7-c55bfdb 2022/12/02 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.7.html
Running on: Linux 4.12.14-122.147-default #1 SMP Tue Jan 17 11:42:48 UTC 2023 (f3fd84a) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_ZLIB=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -LUA +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021 SUSE release SUSE_OPENSSL_RELEASE
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021 SUSE release 150400.7.25.1
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
Thu 11 May 2023 04:44:40 AM UTC | Configuring Load Balancer
Thu 11 May 2023 04:44:40 AM UTC | Setting up vanity certificates...
Working with Cert directory: /certs/certs
Thu 11 May 2023 04:44:46 AM UTC | Starting rsyslogd...
Thu 11 May 2023 04:44:49 AM UTC | Starting dnsmasq...
Thu 11 May 2023 04:44:49 AM UTC | Starting HAProxy
[NOTICE]   (27) : haproxy version is 2.6.7-c55bfdb
[NOTICE]   (27) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:54] : 'bind *:443' in section 'frontend' : error processing line 0 in file '/xxx' : unable to load SSL certificate into SSL Context '/xxx/xxxx.crt'.
[WARNING]  (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:91]: 'option httpchk' : hiding headers or body at the end of the version string is deprecated. Please, consider to use 'http-check send' directive instead.
[WARNING]  (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:104]: 'option httpchk' : hiding headers or body at the end of the version string is deprecated. Please, consider to use 'http-check send' directive instead.
[WARNING]  (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:137] : backend 'xxx' : 'option tcplog' directive is ignored in backends.
[ALERT]    (27) : config : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
[ALERT]    (27) : config : Fatal errors found in configuration.
```

**Comment by wlallemand** [comment]
HAProxy was quite permissive with certificate loading in previous versions. What is possible is that your certificate contained some error from the beginning, Look for duplicate certificates in the file, or incorrect characters... I know this is quite difficult to debug, but we added a more verbose output in HAProxy 2.7 which is able to print a more precise error. So you could test with that.

**Comment by wlallemand** [comment]
I backported the commit 45fed2c7a6bb762d5a52b9355cedde15d6f7cd3b so you will be able to have these errors in the next 2.6 version. Also, the latest 2.6 version is 2.6.13, so please update your version or you will be affected by this list of bugs: https://www.haproxy.org/bugs/bugs-2.6.7.html

**Comment by janezhen08** [comment]
I have upgraded haproxy to v2.7.0 to debug, now error is that 

[ALERT]    (27) : config : parsing [/usr/local/etc/haproxy/haproxy.cfg:54] : 'bind *:443' in section 'frontend' : error processing line 0 in file '/xxx : unable to load SSL certificate into SSL Context '/xxx/xxxx.crt': ee key too small.

I checked the error crt, found the rsa key is 1024, not sure if this is the root cause?

Is there any doc which states that rsa key must 2048 and above?

Also I notice that openssl version may also cause such issue, i have verified in openssl v1.1.1d, it has no issue to parse the rsa 1024 certficate, but if i use openssl v1.1.1l, it will report the issue too.

Could you advise.

thanks

Jane

**Comment by wlallemand** [comment]
You should check your openssl.cnf configuration, most distribution forbid this kind of certificate with a SECLEVEL=2 (https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html) . That's possible they changed the security level during an update.
