### ISSUE TITLE
Bug: v2.7.8 config for stats maxconn

### ISSUE THREAD

**Issue by ryanlelek** [haproxy/haproxy#2155]
### Detailed Description of the Problem

Version: v2.7.8, latest release as of writing
Unable to set `stats maxconn` as currently described in manual:
http://docs.haproxy.org/2.7/configuration.html#3.1-stats%20maxconn

Providing `stats maxconn NUMBER` fails to start.

### Expected Behavior

Should respect provided config `stats maxconn NUMBER`

### Steps to Reproduce the Behavior

1. Using minimal configuration below, run `haproxy -f bug.cfg` - should work fine
2. Uncomment the `stats maxconn` line
3. `haproxy -f bug.cfg` - should fail with error

```
[NOTICE]   (22530) : haproxy version is 2.7.8-1~bpo11+1
[NOTICE]   (22530) : path to executable is /usr/sbin/haproxy
[ALERT]    (22530) : config : parsing [bug.cfg:17]: unknown stats parameter 'maxconn', expects 'admin', 'uri', 'realm', 'auth', 'scope', 'enable', 'hide-version', 'show-node', 'show-desc' or 'show-legends'.
[ALERT]    (22530) : config : Error(s) found in configuration file : bug.cfg
```

### Do you have any idea what may have caused this?

Probably [cfgparse-listen.c](https://github.com/haproxy/haproxy/blob/94df1b57ee0e2f3df97c0348f52ea7c74d98e12a/src/cfgparse-listen.c#L1688) missing the configuration

### Do you have an idea how to solve the issue?

There is probably a mis-match with the configuration or documentation.
The regular `maxconn` config was used alternatively but did not appear to work as intended.

Updating the code is one possible solution.
Updating the documentation is another solution, especially if this was an older config style mistakenly included in newer versions.

### What is your configuration?

```haproxy
global
	log     /dev/log syslog notice
	stats  socket /run/haproxy-stats.socket mode 660 level admin expose-fd listeners
	stats  timeout 2s

defaults
	log        global
	mode       http
	option     httplog
	timeout connect 5s
	timeout client  5s
	timeout server  5s

listen stats
	bind     :8444  alpn h2,http/1.1
	stats  enable
	#stats  maxconn  20
	stats  uri /stats
```
```


### Output of `haproxy -vv`

```plain
Note: This is installed from the repos at https://haproxy.debian.net/


# haproxy -vv
HAProxy version 2.7.8-1~bpo11+1 2023/05/06 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2024.
Known bugs: http://www.haproxy.org/bugs/bugs-2.7.8.html
Running on: Linux 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```
```


### Last Outputs and Backtraces

_No response_

### Additional Information

_No response_

**Comment by wtarreau** [comment]
I don't remember having removed it recently so either it's an old removal for a good reason and we failed to update the doc, or it's a bug. I'm going to have a look. Are you aware of an earlier version where this was still working ?

**Comment by wtarreau** [comment]
Ah, I had not noticed, your "stats maxconn" is in the frontend. It's only supported in the global section, because it sets the maxconn of the purposely created frontend that is dedicated to the stats CLI. In regular proxies for the stats page, the limits are per listener, not per url, so you'll need to set the "maxconn" parameter in the listen section itself:
```
listen stats
	bind     :8444  alpn h2,http/1.1
	maxconn  20
	stats  enable
	stats  uri /stats
```

Also, it's cleaner to declare them as "frontend" instead of "listen" when there are no servers in the section (though it's just a minor detail).

**Comment by ryanlelek** [comment]
Thank you Willy!

My mistake, I should have tried some other routes like the `global` section. Since some of the `stats` options were used in the listener/frontend, that had me thinking only that area.

What might help is updating the documentation for that keyword/command to have a matrix of what sections are allowed, similar to what's here:
http://docs.haproxy.org/2.7/configuration.html#4.2-acl

I could add an update to the docs if you prefer, but this docs location looks like it's generated output HTML from another repo with source files:
https://github.com/haproxy/docs

Otherwise, we can close the issue
