### ISSUE TITLE
src/check.c: unused value suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2158]
### Tool Name and Version

coverity

### Code Report

```plain
1244                                check->state &= ~CHK_ST_CLOSE_CONN;
    CID 1509243 (#1 of 1): Unused value (UNUSED_VALUE)assigned_pointer: Assigning value NULL to conn here, but that stored value is overwritten before it can be used.
1245                                conn = NULL;
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment]
This ambiguity first appeared in 2.6 with 177a0e60ee7ce172dae1970ed206a51ab615ee13

It seems that since the above commit `conn = NULL` is not relevant anymore, @capflam do you confirm?

**Comment by capflam** [comment]
Indeed, this statement is useless but harmless.

**Comment by capflam** [comment]
Harmless but fixed :) Thanks !
