### ISSUE TITLE
`h2s_make_data` comment has two `Returns` statements

### ISSUE THREAD

**Issue by jsoref** [haproxy/haproxy#2175]
I know this is a bit of an odd report. I'm sorry. I normally send other kinds of things to start, but I was reading in this file and ran across:

https://github.com/haproxy/haproxy/blob/ae0f8be0111b8ea128c6e35ee22451162eb98818/src/mux_h2.c#L5816-L5822

* Returns the number of bytes sent.
* Returns the number of data bytes consumed, or zero if nothing done. 

It's possible one of these is correct, it's possible one of these is incorrect. It's somewhat likely one of them is a copy+paste from another block.

The former is present for `h2s_snd_fhdrs`:
https://github.com/haproxy/haproxy/blob/ae0f8be0111b8ea128c6e35ee22451162eb98818/src/mux_h2.c#L5146-L5155

The latter is present for `h2s_skip_data`:
https://github.com/haproxy/haproxy/blob/ae0f8be0111b8ea128c6e35ee22451162eb98818/src/mux_h2.c#L6115-L6122

Naively, based on the name `make data`, I'd _guess_ that the latter is more likely than the former. But, even if I'm right, I'm not entirely certain how much of the block to change.

**Comment by capflam** [comment]
Finally fixed. Thanks !
