### ISSUE TITLE
Interaction between check, zero-warning, and server address resolution failures

### ISSUE THREAD

**Issue by ethanmdavidson** [haproxy/haproxy#2176]
### Detailed Description of the Problem

When running haproxy with `haproxy -c -dW -dr -f /usr/local/etc/haproxy/conf.d/`, check mode is failing due to server address resolution failures, despite `-dr` being set.

From the [haproxy manual](https://docs.haproxy.org/2.8/management.html#3):

> -c : only performs a check of the configuration files and exits before trying
    to bind. The exit status is zero if everything is OK, or non-zero if an
    error is encountered. Presence of warnings will be reported if any.

>  -dW : if set, haproxy will refuse to start if any warning was emitted while
   processing the configuration. This helps detect subtle mistakes and keep the
   configuration clean and portable across versions. It is recommended to set
   this option in service scripts when configurations are managed by humans,
   but it is recommended not to use it with generated configurations, which
   tend to emit more warnings. It may be combined with "-c" to cause warnings
   in checked configurations to fail. This is equivalent to global option
   "zero-warning".

> -dr : ignore server address resolution failures. It is very common when
    validating a configuration out of production not to have access to the same
    resolvers and to fail on server address resolution, making it difficult to
    test a configuration. This option simply appends the "none" method to the
    list of address resolution methods for all servers, ensuring that even if
    the libc fails to resolve an address, the startup sequence is not
    interrupted.

However, even with `-dr` set, the server address resolution failures are printed at `WARNING` level, causing check mode to fail, despite the fact that it is set to "ignore server address resolution failures"

example log message:
```
[WARNING]  (8) : config : [/usr/local/etc/haproxy/conf.d//api.cfg:42] : 'server example/example' : could not resolve address 'example.internal-domain', disabling server.
```

### Expected Behavior

I would expect that when `-dr` is set, server address resolution failures would not cause check mode to fail. 

### Steps to Reproduce the Behavior

1. Create a simple haproxy config with a backend server that can't be resolved
2. run haproxy in with `-c -dW -dr` flags

### Do you have an idea how to solve the issue?

Either don't print address resolution failures as WARNING when -dr is set, or continue printing them at WARNING but add a workaround in the check logic to ignore those specific warnings.

### What is your configuration?

```haproxy
global
	log stdout format raw daemon notice
	log stderr format raw daemon warning
	user haproxy
	group haproxy

defaults http_defaults
	mode http
	log global
	timeout connect 5s
	timeout client  10s
	timeout server  10s
	timeout http-request 10s
	option redispatch

resolvers docker
	parse-resolv-conf

defaults api_backend_defaults
	mode http
	log global
	timeout client 10s
	timeout server 10s
	timeout connect 5s
	timeout http-request 10s
	default-server init-addr last,libc,none
	default-server no-tls-tickets
	default-server resolvers docker
	default-server no-ssl
	option forwardfor

frontend api from http_defaults
	bind *:9001
	log stdout format raw daemon info
	option httplog

	use_backend example if { path_beg -i /example }

backend example from api_backend_defaults
	server example example.myinternaldomain:80
```
```


### Output of `haproxy -vv`

```plain
HAProxy version 2.8.0-fdd8154 2023/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.0.html
Running on: Linux 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=5).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace


```
```


### Last Outputs and Backtraces

```plain
#12 1.489 [NOTICE]   (8) : haproxy version is 2.8.0-fdd8154
#12 1.490 [NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
#12 1.490 [WARNING]  (8) : config : [/usr/local/etc/haproxy/conf.d//api.cfg:42] : 'server example/example' : could not resolve address 'example.myinternaldomain', disabling server.
#12 1.638 [ALERT]    (8) : config : Some warnings were found and 'zero-warning' is set. Aborting.
```
```


### Additional Information

_No response_

**Comment by capflam** [comment]
For me, in this case a notice message must be triggered instead of a warning. When `-dr` option is set but also when the last `init-addr` parameter is `none`. It is exactly what `-dr` option does. It is stated the process should start in case of resolution failure, it should be true with the `zero-warning` option.

**Comment by capflam** [comment]
It should be fixed now

**Comment by ethanmdavidson** [comment]
Thank you so much @capflam! Should I close this now, or wait until the next 2.8.x release?

**Comment by capflam** [comment]
backported. I'm closing now. Thanks !
