### ISSUE TITLE
Client does not support authentication protocol requested by server; consider upgrading MySQL client.

### ISSUE THREAD

**Issue by ly161110323** [haproxy/haproxy#2177]
### Detailed Description of the Problem

Version of old mysql is 5.7. My haproxy config is following: 
```
   listen  mysql
        bind 0.0.0.0:13306
        mode tcp
        option tcplog
        balance roundrobin
        option mysql-check user haproxy
        server node1 {IP1}:3306 check weight 1 maxconn 2000
        server node2 {IP2}:3306 check weight 1 maxconn 2000
        #使用keepalive检测死链
        option  tcpka
```
I create user `haproxy` in mysql and `haproxy` successfully works.

Currently, I upgrade mysql to 8.0.21. But `haproxy` shows that `has no mysql server available!`. In haproxy logs, I found that `Client does not support authentication protocol requested by server; consider upgrading MySQL client.`

What should I do? 
Could anyone help me please?

### Expected Behavior

haproxy successfully works.

### Steps to Reproduce the Behavior

None.

### Do you have any idea what may have caused this?

Maybe older version of `haproxy`.

### What is your configuration?

```haproxy
listen  mysql
        bind 0.0.0.0:13306
        mode tcp
        option tcplog
        balance roundrobin
        option mysql-check user haproxy
        server node1 {IP1}:3306 check weight 1 maxconn 2000
        server node2 {IP2}:3306 check weight 1 maxconn 2000
        #使用keepalive检测死链
        option  tcpka
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 1.8.12-8a200c7 2018/06/27
Copyright 2000-2018 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -fno-strict-overflow -Wno-unused-label -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_SYSTEMD=1 USE_PCRE=1 USE_PCRE_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
```

**Comment by Darlelet** [comment]
Seems related to #1970

**Comment by Darlelet** [comment]
Also please consider updating haproxy because 1.8.12 is more than 4 years old. (http://www.haproxy.org/bugs/bugs-1.8.12.html)

Moreover as 1.8 is now EOL it is recommended to upgrade to a newer LTS version (>= 2.2) to be eligible for upcoming bugfixes

**Comment by ly161110323** [comment]
Simply I remove mysql-check `option mysql-check user haproxy`. Then `haproxy` successfully works. Since haproxy can determine the status of mysql by status of port, is there any hidden danger in canceling `mysql-check`?

**Comment by Darlelet** [comment]
Yes it will work and still check that the server is reacheable, but it won't tell you if your mysql daemon is misbehaving.

If it's acceptable for you then it's ok, if not then your mysql configuration should be ajusted to allow haproxy to perform the auth test in plaintext, but mind the security issues that could come with it

**Comment by ly161110323** [comment]
Thanks for your answer!  Later I will try newer `haproxy`.

**Comment by capflam** [comment]
The MySQL check is pretty simple. But I honestly don't know if it could be improved to support other auth mechanism (or just a subset). There is no MySQL support in HAProxy and unfortunately, it could be hard to implement. For now, we must live with these limitations.  I'm closing now because it works as designed. But you can create a Feature Request if it is really a must have for you. But as said, I suspect it will be a bit hard.
