### ISSUE TITLE
SSL Handshake failure (error:00000000:lib(0):func(0):reason(0)) error message

### ISSUE THREAD

**Issue by okoriko** [haproxy/haproxy#2181]
### Detailed Description of the Problem

After upgrading our servers to from `2.7.5` to `2.8.0` we've seen the overall volume of reported errors increase. The new errors had the message:
```
SSL handshake failure (error:00000000:lib(0):func(0):reason(0))
```

Previously there were some errors with the message `SSL handshake failure` in `2.7.5` ~but with the new message these increased by roughly 3 times~ (see [below](https://github.com/haproxy/haproxy/issues/2181#issuecomment-1606682328)).
This seems to have been introduce with this [commit](https://github.com/haproxy/haproxy/commit/4adb4b99032b8f1a593cd48e856c0930f8523496).

After reverting to `2.7.5`, the error volume returned to its expected levels.

### Expected Behavior

While we normally see some SSL handshake failures, we suspect the new message might be due to a bug.

### Steps to Reproduce the Behavior

We weren't able to tie this to any specific request or conditions. At the moment the only repro steps would be:
1. upgrade from 2.7.5 to 2.8.0

### Do you have any idea what may have caused this?

No but it does seem strange that:
- the error is `00000000`, afaik OpenSSL doesn't define this error.
- also, it seems the function `ERR_error_string` is relying on an internal static buffer and the function isn't thread safe ([ref](https://github.com/openssl/openssl/blob/6181a333670199d20fb60028807edba44899e8d5/crypto/err/err.c#LL577C7-L577C23)).

### What is your configuration?

```haproxy
global
    log stdout format raw local0
    tune.ssl.capture-buffer-size 96
    ssl-default-bind-options ssl-min-ver TLSv1.0

defaults
    log global
    mode http
    option httplog
    option  dontlog-normal
    timeout connect 2000
    timeout server  5000
    timeout client  50000

frontend haproxy-main
    mode http
    bind *:80
    bind :443 ssl crt /usr/local/etc/haproxy/certs/ alpn http/1.1,h2
    http-request redirect scheme https unless { ssl_fc }
    default_backend <backend>

backend <backend>
    option httpchk
    option redispatch
    option http-keep-alive
    timeout http-keep-alive 10
    http-reuse always
    retry-on empty-response conn-failure response-timeout
    default-server inter 3s fall 3 rise 2
    balance source
    http-request set-header x-hap-proto-ver %[ssl_fc,iif(hs,h)],%[fc_http_major],%[req.ver]
    http-request set-var-fmt(req.ja3) %[ssl_fc_protocol_hello_id],%[ssl_fc_cipherlist_bin(1),be2dec(-,2)],%[ssl_fc_extlist_bin(1),be2dec(-,2)],%[ssl_fc_eclist_bin(1),be2dec(-,2)],%[ssl_fc_ecformats_bin,be2dec(-,1)]
    http-request set-header x-hap-ja3-md5 %[var(req.ja3),digest(md5),hex]
             server <server> <ip:port> check
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.0-fdd8154 2023/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.0.html
Running on: Linux 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS
Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB
Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
Available services : prometheus-exporter
Available filters :
    [BWLIM] bwlim-in
    [BWLIM] bwlim-out
    [CACHE] cache
    [COMP] compression
    [FCGI] fcgi-app
    [SPOE] spoe
    [TRACE] trace
```

**Comment by lukastribus** [comment]
> * the error is `00000000`, afaik OpenSSL doesn't define this error.
> 
> * also, it seems the function `ERR_error_string` is relying on an internal static buffer and the function isn't thread safe ([ref](https://github.com/openssl/openssl/blob/6181a333670199d20fb60028807edba44899e8d5/crypto/err/err.c#LL577C7-L577C23)).

Good bug report, thanks. CC @wlallemand

**Comment by wlallemand** [comment]
Thank you for your report, can you try the following patch ?

[0001-BUG-MINOR-ssl-log-message-non-thread-safe-in-SSL-Han.txt](https://github.com/haproxy/haproxy/files/11724715/0001-BUG-MINOR-ssl-log-message-non-thread-safe-in-SSL-Han.txt)

However I'm surprised you have more errors, it shouldn't be related to the error dump. Are you able to reproduce a case where the SSL code is 0 ?

**Comment by okoriko** [comment]
@wlallemand @lukastribus thank you for the follow up :pray: 

> Thank you for your report, can you try the following patch ?
> 
> [0001-BUG-MINOR-ssl-log-message-non-thread-safe-in-SSL-Han.txt](https://github.com/haproxy/haproxy/files/11724715/0001-BUG-MINOR-ssl-log-message-non-thread-safe-in-SSL-Han.txt)
> 
> However I'm surprised you have more errors, it shouldn't be related to the error dump. Are you able to reproduce a case where the SSL code is 0 ?

Thanks for the patch! I'm also surprised by the behavior because it would mean that, at least, we've got more `conn->err_code == CO_ER_SSL_HANDSHAKE` than before.  I'm wondering if this error message is maybe just a symptom of another problem.

We were running `2.8.0` against a portion of our live traffic for tests and I'm not really sure how to trace this any further. 
Do you have any recommendations on maybe some logging options we could turn on to better identify the context of these errors?

**Comment by wlallemand** [comment]
I never had this case before, it's quite strange, I'm not aware of any change that could make it happen. Did you update your SSL library or any other component?

You can try to use the [error-log-format](https://docs.haproxy.org/2.8/configuration.html#8.2.5) but for this kind of error I don't think it will provide you much more, Ideally a pcap would help, if you are able to isolate the errors.

**Comment by okoriko** [comment]
> Did you update your SSL library or any other component?

No, we're running the official docker [image](https://github.com/docker-library/haproxy/blob/2d7b121a1dda3f7844ae094f17346be7252e2ad6/2.8/Dockerfile) as-is :thinking:

**Comment by wlallemand** [comment]
I investigated the code a little bit and made tests with openssl 1.1.1. From what I can see:

- when leaving the client hello callback with an error, OpenSSL send the SSL_AD_UNRECOGNIZED_NAME to the client, I could confirm that the generated error log is `error:142090EA:SSL routines:tls_early_post_process_client_hello:callback failed`, so the problem shouldn't be in the SNI selection.

I'm seeing 2 cases where the SSL error could be 0, and the error set to CO_ER_SSL_HANDSHAKE:

- First one is when having SSL_ERROR_SYSCALL returned by SSL_do_handshake(), it's unclear to me what error you can get there, the documentation is stating that could get an error from the OpenSSL stack there, but it looks like you didn't get one.
- The second one is when having any other error which is not handled by haproxy, for example SSL_ERROR_SSL, which is an unrecoverable error. I could try to replace CO_ER_SSL_HANDSHAKE there by CO_ERR_SSL_FATAL.

At this point I couldn't reproduce the problem unfortunately.

**Comment by wlallemand** [comment]
After analysing some logs I could find some errors with an error-log-format which use the default example of the documentation: `error-log-format "%ci:%cp [%tr] %ft %ac/%fc %[fc_err]/%[ssl_fc_err,hex]/%[ssl_c_err]/%[ssl_c_ca_err]/%[ssl_fc_is_resumed] %[ssl_fc_sni]/%sslv/%sslc"`

The 34 error is the SSL Handshake failure error (See http://docs.haproxy.org/2.8/configuration.html#fc_err) and the 0s are the OpenSSL error code. 

Most logs does not have any SNI nor ciphers:

-  `34/0000000000000000/0/0/0 -/TLSv1.3/(NONE)`
-  `34/0000000000000000/0/0/0 domain1.com/TLSv1.3/TLS_AES_256_GCM_SHA384`
-  `34/0000000000000000/0/0/0 domain2.com/TLSv1.2/(NONE)`

I don't know exactly why they generated this error, but from the IPs I have in the logs they looks  like bots generating erroneous requests. So maybe some protocols error are there, I'll try to modify a little bit the code to be more verbose but OpenSSL does not seem to drop much info here.

I'm surprised that you have less error when reverting to 2.7 though, it could really be a coincidence!

**Comment by wlallemand** [comment]
I could find occurrences of these errors as far as 2.5, and we didn't had error-log-format before that, so it's difficult to know if it was there before. The machine use the -dev releases, I made some stats of the number of occurrences of the error per month but I didn't find any obvious correlation with a specific version

**Comment by okoriko** [comment]
@wlallemand thank you so much for all the additional information here :pray: 

> I'm surprised that you have less error when reverting to 2.7 though, it could really be a coincidence!

Definitely, and we do see lots of bots as well so it may have been some weird coincidence. 
I'll try to run another test tomorrow.

**Comment by okoriko** [comment]
@wlallemand just a quick update: we did run the tests again on a small portion of the traffic comparing `2.7.5` and `2.8.0` with the default error log options (same you mentioned).

This time we didn't observe any difference in volume of errors. We also observed mostly these two patterns:
- `34/0000000000000000/0/0/0 -/TLSv1.3/(NONE)`
- `34/0000000000000000/0/0/0 <domain>/TLSv1.3/TLS_AES_256_GCM_SHA384`

We running additional tests and I'll let you know if we notice anything that may be relevant on this issue. 
But for now I think it's safe to ignore the volume change statement from the original report.

**Comment by okoriko** [comment]
@wlallemand just a note that we've been running 2.8.0 in production side by side with 2.7.5 for the past week and didn't notice any significant change in error volumes happening. This was probably a coincidence, apologies for the initial misleading report on error volume change.

**Comment by wlallemand** [comment]
Thanks for giving us feedback on this, I spent some time digging this, and it seems like there is one case which is not correctly handled when receiving a close_notify alert during the handshake. So I believe this is our problem, I made a patch which change the error case in that specific case (https://github.com/haproxy/haproxy/commit/e8e5762389c56ba0d794ecc43d8a1b26667c9c56 and https://github.com/haproxy/haproxy/commit/3388b234659aecacfb949e4925ba9461f17916e4) . I won't backport it because it would change the behavior, but after this patch you would have an error 24 in fc_err_str ("Connection closed during SSL handshake" )

**Comment by Iatbzh** [comment]
Did you mean to fix it in version 2.8.0 or 2.9,

My production environment has been upgraded to 2.8 and there have been errors

**Comment by Iatbzh** [comment]
@wlallemand

**Comment by wlallemand** [comment]
@Iatbzh This patch https://github.com/haproxy/haproxy/commit/0c9ff0cde451db6fdd2f9f1159e622f1646d5eb1 was backported in 2.8, and will only hide the OpenSSL errror when the error is 0. No 2.8.1 version was released yet with it.

https://github.com/haproxy/haproxy/commit/3388b234659aecacfb949e4925ba9461f17916e4 this patch won't be backported and is 2.9 only, it changes the "SSL Handshake failure" message by a "Connection closed during SSL handshake" for this spectific problem.

But in any cases it's a problem from the client so you will have errors.

**Comment by Iatbzh** [comment]
Hello, it seems that testing version 2.8.1 did not solve this issue

@wlallemand

**Comment by wlallemand** [comment]
@Iatbzh which issue are your referring to? There is no real problem in this ticket, we only changed the way the handshake failure is reported. Are you excepting something specifically?

**Comment by Iatbzh** [comment]
I thought the SSL handshake failure (error: 000000: lib (0): func (0): reason (0)) in the log was a bug because I did not see this error in the log when using the container haproxy1.9. When I upgraded to 2.8 or 2.8.1, I kept reporting this error

**Comment by Iatbzh** [comment]
@wlallemand

**Comment by wlallemand** [comment]
@Iatbzh 2.8.1 will only shows "SSL handshake failure" instead of "SSL handshake failure (error: 000000: lib (0): func (0): reason (0)" when the error is 0. This kind of logs are problems from the client side, because the handshake could not be completed, it often happens with bots.
