### ISSUE TITLE
Broken proxying to SSL endpoints with http/2 (since 2.6)

### ISSUE THREAD

**Issue by dfateyev** [haproxy/haproxy#2183]
### Detailed Description of the Problem

We have been using HAProxy in Kubernetes as an [ingress controller](https://github.com/haproxytech/kubernetes-ingress). After a planned ingress controller version upgrade we found that the proxying to SSL-based endpoints, using http2, become broken. If we revert to an older ingress controller version, the normal proxying behavior is restored.

We have [discussed](https://github.com/haproxytech/kubernetes-ingress/issues/467) the issue with HAProxy controller devs (it's a lengthy thread on how to reproduce), and they [informed](https://github.com/haproxytech/kubernetes-ingress/issues/467#issuecomment-1582447416) that the problem is related to HAProxy 2.3 to 2.6 version change in the controller — and it's recommended to discuss with HAProxy upstream.

The short repro is mentioned in [comment-1416477169](https://github.com/haproxytech/kubernetes-ingress/issues/467#issuecomment-1416477169):

```
$ curl --http1.1 http://<haproxy-ip>/kubernetes-dashboard/
<valid content>

$ curl --http2 http://<haproxy-ip>/kubernetes-dashboard/
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

2023/02/03 20:52:27 http2: server connection error from 10.239.192.2:60814: connection error: PROTOCOL_ERROR
2023/02/03 20:54:20 http2: server connection error from 10.239.192.2:46358: connection error: PROTOCOL_ERROR
```
> If I revert to controller 1.6.9 (HAProxy 2.3), HTTP/2 is handled correctly:
```
$ curl --http1.1 http://<haproxy-ip>/kubernetes-dashboard/
<valid content>

$ curl --http2 http://<haproxy-ip>/kubernetes-dashboard/
<valid content>

upstream Nginx balancer with http/2 support + client browser:
<http/2.0 based valid content>
```

### Expected Behavior

HTTP/2 proxying to SSL-based endpoints supposedly doesn't work in newer versions

### Steps to Reproduce the Behavior

1. Install K8s HAProxy ingress controller, based on HAProxy 2.6 version;
2. Set an ingress resource, which uses path rewrite and SSL endpoints;
3. Try to access the resource, and check the error occurred.

### What is your configuration?

```haproxy
# _version=8
# HAProxy Technologies
# https://www.haproxy.com/
# this file is not meant to be changed directly
# it is under haproxy ingress controller management

global
  daemon
  localpeer local
  master-worker
  pidfile /var/run/haproxy.pid
  stats socket /var/run/haproxy-runtime-api.sock expose-fd listeners level admin
  stats timeout 36000
  tune.ssl.default-dh-param 2048
  ssl-default-bind-options no-sslv3 no-tls-tickets no-tlsv10
  ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
  hard-stop-after 1800000
  log 127.0.0.1 local0 notice
  default-path config

defaults
  log global
  log-format '%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs "%HM %[var(txn.base)] %HV"'
  option redispatch 0
  option dontlognull
  option http-keep-alive
  timeout http-request 5000
  timeout connect 5000
  timeout client 50000
  timeout queue 5000
  timeout server 50000
  timeout tunnel 3600000
  timeout http-keep-alive 60000

peers localinstance
  peer local 127.0.0.1:10000

frontend healthz
  mode http
  bind 0.0.0.0:1042 name v4
  bind :::1042 name v6 v4v6
  monitor-uri /healthz
  option dontlog-normal

frontend http
  mode http
  bind 0.0.0.0:80 name v4
  bind :::80 name v6
  http-request set-var(txn.base) base
  http-request set-var(txn.path) path
  http-request set-var(txn.host) req.hdr(Host),field(1,:),lower
  http-request set-var(txn.host_match) var(txn.host),map(/etc/haproxy/maps/host.map)
  http-request set-var(txn.host_match) var(txn.host),regsub(^[^.]*,,),map(/etc/haproxy/maps/host.map,'') if !{ var(txn.host_match) -m found }
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map(/etc/haproxy/maps/path-exact.map)
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map_beg(/etc/haproxy/maps/path-prefix.map) if !{ var(txn.path_match) -m found }
  http-request replace-path /kubernetes-dashboard(/|$)(.*) /\2 if { var(txn.path_match) -m dom 3c9d9f4fd27c5ae518111b33de8d9ca3 } 
  use_backend %[var(txn.path_match),field(1,.)]
  default_backend haproxy-controller_default-local-service_http

frontend https
  mode http
  bind 0.0.0.0:443 name v4
  bind :::443 name v6
  http-request set-var(txn.base) base
  http-request set-var(txn.path) path
  http-request set-var(txn.host) req.hdr(Host),field(1,:),lower
  http-request set-var(txn.host_match) var(txn.host),map(/etc/haproxy/maps/host.map)
  http-request set-var(txn.host_match) var(txn.host),regsub(^[^.]*,,),map(/etc/haproxy/maps/host.map,'') if !{ var(txn.host_match) -m found }
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map(/etc/haproxy/maps/path-exact.map)
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map_beg(/etc/haproxy/maps/path-prefix.map) if !{ var(txn.path_match) -m found }
  http-request set-header X-Forwarded-Proto https
  http-request replace-path /kubernetes-dashboard(/|$)(.*) /\2 if { var(txn.path_match) -m dom 3c9d9f4fd27c5ae518111b33de8d9ca3 } 
  use_backend %[var(txn.path_match),field(1,.)]
  default_backend haproxy-controller_default-local-service_http

frontend stats
  mode http
  bind *:1024 name stats
  bind :::1024 name v6
  stats enable
  stats uri /
  stats refresh 10s
  http-request set-var(txn.base) base
  http-request use-service prometheus-exporter if { path /metrics }

backend haproxy-controller_default-local-service_http
  mode http
  balance roundrobin
  option forwardfor
  no option abortonclose
  default-server check
  server SRV_1 127.0.0.1:6061 enabled
  server SRV_2 127.0.0.1:6061 disabled
  server SRV_3 127.0.0.1:6061 disabled
  server SRV_4 127.0.0.1:6061 disabled
  server SRV_5 127.0.0.1:6061 disabled
  server SRV_6 127.0.0.1:6061 disabled
  server SRV_7 127.0.0.1:6061 disabled
  server SRV_8 127.0.0.1:6061 disabled
  server SRV_9 127.0.0.1:6061 disabled
  server SRV_10 127.0.0.1:6061 disabled
  server SRV_11 127.0.0.1:6061 disabled
  server SRV_12 127.0.0.1:6061 disabled
  server SRV_13 127.0.0.1:6061 disabled
  server SRV_14 127.0.0.1:6061 disabled
  server SRV_15 127.0.0.1:6061 disabled
  server SRV_16 127.0.0.1:6061 disabled
  server SRV_17 127.0.0.1:6061 disabled
  server SRV_18 127.0.0.1:6061 disabled
  server SRV_19 127.0.0.1:6061 disabled
  server SRV_20 127.0.0.1:6061 disabled
  server SRV_21 127.0.0.1:6061 disabled
  server SRV_22 127.0.0.1:6061 disabled
  server SRV_23 127.0.0.1:6061 disabled
  server SRV_24 127.0.0.1:6061 disabled
  server SRV_25 127.0.0.1:6061 disabled
  server SRV_26 127.0.0.1:6061 disabled
  server SRV_27 127.0.0.1:6061 disabled
  server SRV_28 127.0.0.1:6061 disabled
  server SRV_29 127.0.0.1:6061 disabled
  server SRV_30 127.0.0.1:6061 disabled
  server SRV_31 127.0.0.1:6061 disabled
  server SRV_32 127.0.0.1:6061 disabled
  server SRV_33 127.0.0.1:6061 disabled
  server SRV_34 127.0.0.1:6061 disabled
  server SRV_35 127.0.0.1:6061 disabled
  server SRV_36 127.0.0.1:6061 disabled
  server SRV_37 127.0.0.1:6061 disabled
  server SRV_38 127.0.0.1:6061 disabled
  server SRV_39 127.0.0.1:6061 disabled
  server SRV_40 127.0.0.1:6061 disabled
  server SRV_41 127.0.0.1:6061 disabled
  server SRV_42 127.0.0.1:6061 disabled

backend kubernetes-dashboard_kubernetes-dashboard_443
  mode http
  balance roundrobin
  option forwardfor
  no option abortonclose
  default-server ssl alpn h2,http/1.1 verify none
  server SRV_1 10.239.96.4:8443 enabled
  server SRV_2 127.0.0.1:8443 disabled
  server SRV_3 127.0.0.1:8443 disabled
  server SRV_4 127.0.0.1:8443 disabled
  server SRV_5 127.0.0.1:8443 disabled
  server SRV_6 127.0.0.1:8443 disabled
  server SRV_7 127.0.0.1:8443 disabled
  server SRV_8 127.0.0.1:8443 disabled
  server SRV_9 127.0.0.1:8443 disabled
  server SRV_10 127.0.0.1:8443 disabled
  server SRV_11 127.0.0.1:8443 disabled
  server SRV_12 127.0.0.1:8443 disabled
  server SRV_13 127.0.0.1:8443 disabled
  server SRV_14 127.0.0.1:8443 disabled
  server SRV_15 127.0.0.1:8443 disabled
  server SRV_16 127.0.0.1:8443 disabled
  server SRV_17 127.0.0.1:8443 disabled
  server SRV_18 127.0.0.1:8443 disabled
  server SRV_19 127.0.0.1:8443 disabled
  server SRV_20 127.0.0.1:8443 disabled
  server SRV_21 127.0.0.1:8443 disabled
  server SRV_22 127.0.0.1:8443 disabled
  server SRV_23 127.0.0.1:8443 disabled
  server SRV_24 127.0.0.1:8443 disabled
  server SRV_25 127.0.0.1:8443 disabled
  server SRV_26 127.0.0.1:8443 disabled
  server SRV_27 127.0.0.1:8443 disabled
  server SRV_28 127.0.0.1:8443 disabled
  server SRV_29 127.0.0.1:8443 disabled
  server SRV_30 127.0.0.1:8443 disabled
  server SRV_31 127.0.0.1:8443 disabled
  server SRV_32 127.0.0.1:8443 disabled
  server SRV_33 127.0.0.1:8443 disabled
  server SRV_34 127.0.0.1:8443 disabled
  server SRV_35 127.0.0.1:8443 disabled
  server SRV_36 127.0.0.1:8443 disabled
  server SRV_37 127.0.0.1:8443 disabled
  server SRV_38 127.0.0.1:8443 disabled
  server SRV_39 127.0.0.1:8443 disabled
  server SRV_40 127.0.0.1:8443 disabled
  server SRV_41 127.0.0.1:8443 disabled
  server SRV_42 127.0.0.1:8443 disabled
```
```


### Output of `haproxy -vv`

```plain
HAProxy version 2.6.13-234aa6d 2023/05/02 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.13.html
Running on: Linux 3.10.0 #1 SMP Thu Dec 15 20:31:06 MSK 2022 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -QUIC +RT +SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 3.0.8 7 Feb 2023
Running on OpenSSL version : OpenSSL 3.0.8 7 Feb 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.1 20220924

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```
```


### Last Outputs and Backtraces

_No response_

### Additional Information

_No response_

**Comment by capflam** [comment]
Here the issue is that you try to perform a connection upgrade. Before the 2.4, nothing was performed, the request is translated to H2 and sent with no special transformation. It means a H2 GET request is sent to the server. Since the 2.4, to be able to support websockets in HTTP/2, the request is translated to a CONNECT h2 request. But it only works if the server supports the  Extended connect (RFC8441). Otherwise a protocol error is reported. And your server does not support it.

Now, I don't understand what you try to achieve by setting the `--http2` curl option.  HAProxy does not perform any connection upgrade. And you are already dealing with protocol negotiation in SSL via the alpn. Thus there is no reason to request a H2C upgrade.  Thus this option is useless.  You may use `--http2-prior-knowledge` option to init a clear H2 connection on the frontend side.

**Comment by dfateyev** [comment]
@capflam thanks for the prompt answer.

> Now, I don't understand what you try to achieve by setting the `--http2` curl option. HAProxy does not perform any connection upgrade. And you are already dealing with protocol negotiation in SSL via the alpn. Thus there is no reason to request a H2C upgrade. Thus this option is useless. You may use `--http2-prior-knowledge` option to init a clear H2 connection on the frontend side.

The problem is that HAProxy instance (which serves as ingress controller) is behind an upstream NGINX balancer. The NGINX instance handles an incoming client's connections and proxies it using HTTP/2 to HAProxy instance below — then we observe the error. I have reproduced the issue with `NGINX → HAProxy → application` chain accessing HAProxy with `curl --http2` option, I suppose it's similar what NGINX upstream server does.

**Comment by capflam** [comment]
in your reproducer, you don't perform an HTTP/2 request but an HTTP/1.1 request requesting an upgrade to HTTP/2 via the H2C protocol. To perform a clear HTTP/2 request from curl, you should use `http2-prior-knowledge` option.

It could be good to know if your upstream NGINX balancer is just forwarding the client request as is. In this case, it means your clients are requesting an HTTP/1.1 to HTTP/2 upgrade. Otherwise, it means your NGINX balancer is requesting this upgrade by itself. In both case, it could be good to know why. Because on the server side,  the HTTP version is negotiated via the ALPN and there is no upgrade and HAProxy will not handle it. Thus it seems totally useless to try to perform an H2C upgrade.

Anyway, as a workaround, you can remove `connection` and `upgrade` header, by adding following rules in your frontend section:
```
    http-request del-header connection
    http-request del-header upgrade
```

You may filter these rules on `h2c` protocol.

@a-denoyelle, there are options to configure how websockets upgrades are performed. Do you think it might be useful to disable the RFC8441 on the server side ?

**Comment by dfateyev** [comment]
> in your reproducer, you don't perform an HTTP/2 request but an HTTP/1.1 request requesting an upgrade to HTTP/2 via the H2C protocol. To perform a clear HTTP/2 request from curl, you should use `http2-prior-knowledge` option.

You are right: the curl connection works with `http2-prior-knowledge`, and broken with `http2`.

> It could be good to know if your upstream NGINX balancer is just forwarding the client request as is. In this case, it means your clients are requesting an HTTP/1.1 to HTTP/2 upgrade. Otherwise, it means your NGINX balancer is requesting this upgrade by itself. In both case, it could be good to know why. Because on the server side, the HTTP version is negotiated via the ALPN and there is no upgrade and HAProxy will not handle it. Thus it seems totally useless to try to perform an H2C upgrade.

Observing the load balancer configuration, I think it requests the upgrade unconditionally. In a server section:
```
	proxy_http_version		1.1;
	proxy_set_header		Host $host;
	proxy_set_header		X-Forwarded-Proto $scheme;
	proxy_set_header		X-Real-IP $remote_addr;
	proxy_set_header		X-Remote-Port $remote_port;
	proxy_set_header		X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header		X-Forwarded-Port $server_port;
	proxy_set_header		X-Host $host;
	proxy_set_header		Upgrade $http_upgrade;
	proxy_set_header		Connection "upgrade";
...
```
I think it was introduced for websocket support, and related to the [NGINX manual](http://nginx.org/en/docs/http/websocket.html).

> Anyway, as a workaround, you can remove `connection` and `upgrade` header, by adding following rules in your frontend section:
> 
> ```
>     http-request del-header connection
>     http-request del-header upgrade
> ```
> 
> You may filter these rules on `h2c` protocol.

I am not sure if I can do it in HAPRoxy ingress controller configuration (the HAProxy configuration is managed by ingress controller). I will ask the controller devs.

> @a-denoyelle, there are options to configure how websockets upgrades are performed. Do you think it might be useful to disable the RFC8441 on the server side ?

I think it can be a good idea, for these options to be provided further on ingress controller level, so we could emulate older HAPRoxy behavior, or similar.

**Comment by capflam** [comment]
> Observing the load balancer configuration, I think it requests the upgrade unconditionally. In a server section:
> 
> ```
> 	proxy_http_version		1.1;
> 	proxy_set_header		Host $host;
> 	proxy_set_header		X-Forwarded-Proto $scheme;
> 	proxy_set_header		X-Real-IP $remote_addr;
> 	proxy_set_header		X-Remote-Port $remote_port;
> 	proxy_set_header		X-Forwarded-For $proxy_add_x_forwarded_for;
> 	proxy_set_header		X-Forwarded-Port $server_port;
> 	proxy_set_header		X-Host $host;
> 	proxy_set_header		Upgrade $http_upgrade;
> 	proxy_set_header		Connection "upgrade";
> ...
> ```
> 
> I think it was introduced for websocket support, and related to the [NGINX manual](http://nginx.org/en/docs/http/websocket.html).

I'm not a NGINX expert, but it seems the upgrade is unconditional here. In the manual, the connection header must be set to `$connection_upgrade` to only pass what the client has requested. It may be the root cause of your issue. Because I'm surprised a client is requesting a h2c upgrade. 

However, about the websocket support, you must be aware that it will only works in http/2 if your server supports the extended connect. Otherwise, you should switch to http/1.1 to do so. And here, there is an option. check `ws` keyword on the server line and `h2-workaround-bogus-websocket-client` global option. But be sure your NGINX configuration is correct first. Because it is unusual to support websocket upgrade on any URLs.

So we may think to add options but at first glance, it is useless here. Updating the NGINX configuration to use `$connection_upgrade` instead of `upgrade` for the connection header should do the trick. And then, you should review the websocket support on your server to be sure it works as expected. For now, your HTTP/2 servers don't support it.

**Comment by dfateyev** [comment]
I have managed to get the expected behavior, using conditional NGINX connection upgrade, as described in the [article](http://nginx.org/en/docs/http/websocket.html) above, and some additional options (NGINX solution specific). @capflam thank you for the details and support.
I believe, the initial request can be closed now.
As for an option to emulate older HAProxy behavior, I leave it for your decision: if you feel that we don't need it, we can close the ticket.

**Comment by wtarreau** [comment]
OK thank you for your feedback!
