### ISSUE TITLE
Add HAProxy with QUIC to apt

### ISSUE THREAD

**Issue by PabloKowalczyk** [haproxy/haproxy#2185]
### Your Feature Request

Hello, there are three simple steps to [install HAProxy on Ubuntu/Debian](https://haproxy.debian.net/) using [ppa:vbernat/haproxy-2.8](https://launchpad.net/~vbernat/+ppa-packages), however there is no `haproxy-quic` version in this `ppa`.

Are there any change to add `haprox-quic` to [ppa:vbernat/haproxy-2.8](https://launchpad.net/~vbernat/+ppa-packages)?

Also, please note that there are special version of Docker images with QUIC, for example [Ubuntu](https://github.com/haproxytech/haproxy-docker-ubuntu-quic), so why not add special version in `ppa`?

### What are you trying to do?

Actually I would like to use HTTP/3 on Ubutnu 20.04 without building HAProxy from scratch, ideally using `apt`.

### Output of `haproxy -vv`

```plain
Not relevant
```

**Comment by a-denoyelle** [comment]
We do not manage packaging ourselves, instead we rely on the various distro maintainers for this. As you may know, QUIC is not compatible with OpenSSL library so that means that first a compatible SSL library must be available in the distro, which is most of the time not the case. Even if this requirement is met, this means that a maintainer would have to ship multiple haproxy packages targeting several SSL libraries which is a time-consuming process.

All this means that for now the straightforward approach is to recompile haproxy yourself for QUIC support. You can check the INSTALL file or read the following article for guidance : 
https://www.haproxy.com/blog/how-to-enable-quic-load-balancing-on-haproxy

**Comment by PabloKowalczyk** [comment]
I see, but I would like to not build it myself to ease maintenance, updating Docker version or self-built version means deactivating HAProxy for a while, `apt` version just work and updates smoothly.

**Comment by haproxyFred** [comment]
Perhaps this is what you are looking for: https://github.com/haproxytech/haproxy-docker-alpine-quic

**Comment by wtarreau** [comment]
We all understand the inconvenience, but this has to be explained to the OpenSSL team who decided to reject QUIC support after letting everyone hope for 3.5 years that it would be merged, or explained to the people in charge of packaging OpenSSL for your favorite distro to convince them to switch from OpenSSL to quicTLS. The mess  OpenSSL provoked here is exactly what you describe: their attitude **forces** end-users to rebuild themselves, leaving them with **no other choice**. We're sorry for this and rest assured we're among those trying to find alternate solutions to make the situation easier for users!

**Comment by PabloKowalczyk** [comment]
Is it possible to create something like `haproxy-quic`, that will depends on `quicTLS`, in [https://launchpad.net/~vbernat](https://launchpad.net/~vbernat)?

**Comment by wtarreau** [comment]
This would require that quicTLS be packaged by those distros, which is not the case, so there's no way a package can be emitted with a broken dependency on a non-existing package. That's the reason why some of us have been asking for this in the past.

**Comment by PabloKowalczyk** [comment]
It can't work even when `https://launchpad.net/~vbernat` adds `quicTLS` package?

**Comment by wtarreau** [comment]
But has Vincent expressed the intent to maintain this package ? Because engaging into maintaining a TLS stack for a distro is not something fun at all, and definitely not something a maintainer would do just to make it easier to workaround protocol limitations imposed by openssl.

**Comment by PabloKowalczyk** [comment]
Ok then, thanks for clarifying.

**Comment by dragoangel** [comment]
> I see, but I would like to not build it myself to ease maintenance, updating Docker version or self-built version means deactivating HAProxy for a while, `apt` version just work and updates smoothly.

maybe docker images could be a solution for you? For example https://github.com/iuridiniz/haproxy-quic-docker/blob/main/Dockerfile

Or you can take this repo as a base just to build it locally without docker.
