### ISSUE TITLE
HAProxy should not emit warning if server-state-file does not exist or is empty

### ISSUE THREAD

**Issue by markkrj** [haproxy/haproxy#2190]
### Detailed Description of the Problem

I'm building a new HAProxy instance and want to use `zero-warning`, as we do not intend to change the config dynamically (programmatically).
Problem is, we cannot start off using an empty/nonexistent `server-state-file` and dump states to the file later, as a warning is emitted.

### Expected Behavior

I think this should be a INFO instead.

### Steps to Reproduce the Behavior

```bash
cd `mktemp -d`
echo -e 'global\n zero-warning\n server-state-file test' >haproxy.cfg
docker run --rm -v $PWD/haproxy.cfg:/etc/haproxy/haproxy.cfg haproxytech/haproxy-debian
```

Output:
```
[NOTICE]   (1) : haproxy version is 2.8.0-fdd8154
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[WARNING]  (1) : config : config: Can't open global server state file 'test': No such file or directory
[ALERT]    (1) : config : Some warnings were found and 'zero-warning' is set. Aborting.
```

### Do you have an idea how to solve the issue?

I would like to use `server-state-file` so if users disable a server using the stats page, that would be kept in a reload. I'd be fine with either:
* A option to turn off warning for missing `server-state-file`.
* Turning it in an INFO message instead.

### What is your configuration?

```haproxy
global
 zero-warning
 server-state-file test
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.0-fdd8154 2023/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.0.html
Running on: Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64
```

**Comment by markkrj** [comment]
Thinking more about this, I came up to two ways of fixing it:
1. Replace `ha_warning` by `ha_alert` or `ha_notice`
2. Add argument to `zero-warning` keyword (something like `no-warn-state-files`) and check for that.

I want to send a patch, but wanted to know what you think about this before implementing. Option 1 would be breaking if people rely on it failing if file is missing and `zero-warning` is used. If a breaking change is OK in main branch (not backporting it), then I'd prefer that. If that's unacceptable, then I'd implement option 2, but wanted to know if that argument name fine, or you have a better suggestion.

**Comment by capflam** [comment]
For me, it seems raisonnable to emit a message via `ha_notice()` when the file is not found or is empty. Especially because it is the only way to start with `zeor-warning` option on a fresh install or a cold restart. A valid configuration must be started with the `zero-warning` option. Here it is not possible. Thus it is a bug for me and it should be fixed. 

I guess it could be good to check other messages to be sure there are no other abusive warnings. Thanks @markkrj, let me know if you need some help !

**Comment by markkrj** [comment]
@capflam sent two patches to the mailing list

**Comment by capflam** [comment]
Backported to 2.8. I'm closing now :). Thanks @markkrj
