### ISSUE TITLE
Report on which end a TLS alert was issued

### ISSUE THREAD

**Issue by maxmoehl** [haproxy/haproxy#2192]
### Your Feature Request

Currently I am not aware of any fetcher that provides an indication about whether a TLS alert was received over the connection or occurred locally. For most alerts this is not really relevant because they can only occur on either side. But especially with mTLS we observed some alerts on both sides and it becomes tricky to figure out who's at fault.

For example in GoLang every alert (or any error really) that is received over the connection is prefixed with `remote error:`.

### What are you trying to do?

Determine whether a TLS alert was received over the connection (via a TLS alert message) or occurred locally.

### Output of `haproxy -vv`

```plain
HAProxy version 2.7.7-feedf14 2023/04/27 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2024.
Known bugs: http://www.haproxy.org/bugs/bugs-2.7.7.html
Running on: Linux 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=yes USE_STATIC_PCRE2=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN -SLZ -STATIC_PCRE +STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wlallemand** [comment]
I understand the point. However it's unclear to me how you get TLS alerts ? With HAProxy 2.7 you will only have an "SSL Hanshake failure" in the logs, but you won't see any TLS alert. Can you detail a little bit your configuration and usecase? thanks

**Comment by maxmoehl** [comment]
We are using [`ssl_fc_err`](https://docs.haproxy.org/2.7/configuration.html#7.3.4-ssl_fc_err) to get more details about what exactly caused the issue. My assumption was that HAProxy prints some details about either the received alert or the error that occurred locally. We do indeed have occurrences where we only see `SSL Handshake Failure` without any details. Are you saying that HAProxy can only provide further details if the error occurred locally and that an empty `ssl_fc_err` indicates a TLS alert received from the peer?

The main use-case is better troubleshooting. We have a lot of clients that have very ... interesting implementations of the TLS specification. This causes all sorts of weird errors and any detail we can get from HAProxies logs helps.

**Comment by wlallemand** [comment]
Okay that makes sense, `ssl_fc_err` is indeed the right way to do this, but this is only the error code generated by the OpenSSL stack, it's not necessarily a "TLS alert". This value is filled when doing the handshake.

I don't know exhaustively all error codes, but from what I observed,  the "tlsv1 alert" errors are the alert received from the peer, if haproxy emitted an alert you won't see that but a "callback failed" error, a unsupported protocol or something else.

**Comment by wlallemand** [comment]
Also there is a case of hanshake failure without any openssl error which was discussed in https://github.com/haproxy/haproxy/issues/2181

**Comment by maxmoehl** [comment]
Okay from the linked issue I understand that the `SSL Handshake Error` together with an `ssl_fc_err` that is `0000000000000000` comes from the client sending a `close_notify`.

Do you still think that it would be possible to provide some clear indication of whether the openssl error occurred because the client sent a TLS alert or because some error occurred on HAProxy?

**Comment by wlallemand** [comment]
> Okay from the linked issue I understand that the `SSL Handshake Error` together with an `ssl_fc_err` that is `0000000000000000` comes from the client sending a `close_notify`.
> 

That's right.

> Do you still think that it would be possible to provide some clear indication of whether the openssl error occurred because the client sent a TLS alert or because some error occurred on HAProxy?

The error would be a TLS alert error if it's a TLS alert sent by a peer.

There are multiple fetches that you can use in case of mTLS, first of all I recommend you to setup an error-log-format https://docs.haproxy.org/2.7/configuration.html#8.2.5, this would give you more details.  `ssl_c_err`  as well as `ssl_c_ca_err` can give you error code about the verify error code in haproxy.

You can also use the `fc_err` which gives you some details too http://docs.haproxy.org/2.8/configuration.html#7.3.3-fc_err_str  .

`ssl_fc_err_str` error that are raised during the handshake by a TLS alert emitted by the peer will be prefixed by "tlsv1/sslv3 alert" in there description. Hexadecimal error codes depends on your openssl version.

I made an extract of the `ssl_fc_err` I have in my logs, converted with `openssl errstr`

```
error:1408A0C1:SSL routines:func(138):no shared cipher
error:1408A10B:SSL routines:func(138):wrong version number
error:1408F09B:SSL routines:ssl3_get_record:https proxy request
error:1408F09C:SSL routines:ssl3_get_record:http request
error:1408F10B:SSL routines:ssl3_get_record:wrong version number
error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
error:140940F4:SSL routines:ssl3_read_bytes:unexpected message
error:140940F5:SSL routines:ssl3_read_bytes:unexpected record
```
These are protocols errors, generated by haproxy or openssl.

```
error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
error:14094413:SSL routines:ssl3_read_bytes:sslv3 alert unsupported certificate
error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired
error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

These are SSLv3 and TLSv1 alert, so they were sent by the client.

```
error:1414F178:SSL routines:tls1_set_server_sigalgs:no shared signature algorithms
error:1416C095:SSL routines:tls_process_finished:digest check failed
error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher
error:141A20F4:SSL routines:ossl_statem_server_read_transition:unexpected message
error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share
error:141F7065:SSL routines:final_key_share:no suitable key share
error:141FA0FD:SSL routines:tls_psk_do_binder:binder does not verify
error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm
error:142090BB:SSL routines:tls_early_post_process_client_hello:no compression specified
error:142090C1:SSL routines:tls_early_post_process_client_hello:no shared cipher
error:142090FC:SSL routines:tls_early_post_process_client_hello:unknown protocol
error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol
error:14209175:SSL routines:tls_early_post_process_client_hello:inappropriate fallback
error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low
```

These one were generated by HAProxy or OpenSSL

**Comment by maxmoehl** [comment]
Thanks a lot for the details!

As you recommend we already have the error-log-format set up but were missing some details about how all of this interacts. The details you provided made the situation a lot clearer.

I will close this issue since I don't think there is anything to be changed.
