### ISSUE TITLE
Error in download link on https://www.haproxy.org/#down

### ISSUE THREAD

**Issue by larkly** [haproxy/haproxy#2194]
### Detailed Description of the Problem

When trying to download HAProxy 2.8 stable release from the download matrix on www.haproxy.org, the link points to https://www.haproxy.org/download/2.7/src/haproxy-2.8.0.tar.gz which gives a 404. The correct link is https://www.haproxy.org/download/2.8/src/haproxy-2.8.0.tar.gz.

### Expected Behavior

Package should download

### Steps to Reproduce the Behavior

N/A

### Do you have any idea what may have caused this?

Typo

### Do you have an idea how to solve the issue?

Fix the typo :)

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by capflam** [comment]
I checked and the links are correct.

**Comment by larkly** [comment]
Still giving me a 404

![image](https://github.com/haproxy/haproxy/assets/519380/e558f23b-4b57-47d1-8414-259ceddbfb7b)

**Comment by git001** [comment]
I can confirm that in the matrix http://www.haproxy.org/#down is the dir 2.7 but tar.gz 2.8

```shell
curl -Ss https://www.haproxy.org/|egrep -i -a4 'latest rel'
<td><a href="/download/1.1/src/snapshot/haproxy-ss-LATEST.tar.gz">tar.gz</a></td>
<td>-</td>
</tr>
<tr align=center>
<th>Latest release</th>
<td><a href="/download/2.9/src/devel/haproxy-2.9-dev0.tar.gz">tar.gz</a> / <a href="/download/2.9/src/CHANGELOG">Log</a></td>

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
<td><a href="/download/2.7/src/haproxy-2.8.0.tar.gz">tar.gz</a> / <a href="/download/2.8/src/CHANGELOG">Log</a></td>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

<td><a href="/download/2.7/src/haproxy-2.7.9.tar.gz">tar.gz</a> / <a href="/download/2.7/src/CHANGELOG">Log</a></td>
<td><a href="/download/2.6/src/haproxy-2.6.14.tar.gz">tar.gz</a> / <a href="/download/2.6/src/CHANGELOG">Log</a></td>
```

**Comment by wtarreau** [comment]
Indeed there was an error, now fixed, thanks for reporting this and sorry for the error (the page is still edited mostly by hand during major releases).
