### ISSUE TITLE
New compression algorithms zopfli

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#22]
## Output of `haproxy -vv` and `uname -a`

```
Future version
```

## What should haproxy do differently? Which functionality do you think we should add?

Haproxy could add a additional compression algorithm.

```
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
```

https://github.com/google/zopfli

ZopfliDeflate creates a valid deflate stream in memory, see:  
http://www.ietf.org/rfc/rfc1951.txt

ZopfliZlibCompress creates a valid zlib stream in memory, see:  
http://www.ietf.org/rfc/rfc1950.txt

ZopfliGzipCompress creates a valid gzip stream in memory, see:  
http://www.ietf.org/rfc/rfc1952.txt

**Comment by wtarreau** [comment]
In my opinion, Zopfli is not designed to be used for in-line compression but for off-line compression instead. It provides marginal gains over gzip/deflate (5-10% typically) at the expense of extreme compression time (50-100 times longer). This is well suited for recompressing often used images but not for being deployed to compress random objects flowing through a load balancer.

**Comment by git001** [comment]
Thanks for clarification
