### ISSUE TITLE
HTTP Version (%HV) is not properly logged on long paths (truncated or logged as HTTP/0.9)

### ISSUE THREAD

**Issue by amsnek** [haproxy/haproxy#2205]
### Detailed Description of the Problem

On long PATHs (starting from 1011-1018 chars) the contents of %HV become truncated resulting in partial logs. From 1019 chars onwards, the http method is logged as HTTP/0.9. 

examples: HTTP/2.0 GET request with "/this/is/a_very_long_path" will result in:

path length: =1011 -> %HV = HTTP/2.0
path length: =1012 -> %HV = HTTP/2.
path length: =1013 -> %HV = HTTP/2
path length: =1014 -> %HV = HTTP/
path length: =1015 -> %HV = HTTP
path length: =1016 -> %HV = HTT
path length: =1017 -> %HV = HT
path length: =1018 -> %HV = H
path length: >=1019 -> %HV = HTTP/0.9

### Expected Behavior

http method (%HV) always being logged as send by the client/browser. In the above example: HTTP/2.0

### Steps to Reproduce the Behavior

1) enable logging of %HV in default log format or custom log format
2) send a request (curl/browser/otherwise) with a path >= 1019 char length
3) %HV results in HTTP/0.9 (or truncated versions of the original HTTP version)

### Do you have any idea what may have caused this?

possibly buffer corruption

### What is your configuration?

```haproxy
Linux / RHEL8
locally compiled haproxy
also tested on haproxy 2.8.0 -> same results
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.14-5188364 2023/06/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.14.html
Running on: Linux 4.18.0-477.13.1.el8_8.x86_64 #1 SMP Thu May 18 10:27:05 EDT 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Werror=format-security
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_STATIC_PCRE2=1 USE_OPENSSL=1 USE_LUA=1 USE_TFO=1 USE_NS=1 USE_DEVICEATLAS=1 USE_SYSTEMD=1 USE_QUIC= USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H +DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -QUIC +RT +SLZ -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=3).
Built with OpenSSL version : OpenSSL 3.0.9 30 May 2023
Running on OpenSSL version : OpenSSL 3.0.9 30 May 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with DeviceAtlas support (dummy library only).
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-18)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by Darlelet** [comment]
The "limit" your reaching is probably related to syslog `<length>` defaulting to 1024: the message will automatically be truncated unless set to a larger value using `len` parameter from the `log` directive.

See: https://docs.haproxy.org/dev/configuration.html#4.2-log (search for `<length>`)

```
path length: =1011 -> %HV = HTTP/2.0
path length: =1012 -> %HV = HTTP/2.
path length: =1013 -> %HV = HTTP/2
path length: =1014 -> %HV = HTTP/
path length: =1015 -> %HV = HTTP
path length: =1016 -> %HV = HTT
path length: =1017 -> %HV = HT
path length: =1018 -> %HV = H
path length: >=1019 -> %HV = HTTP/0.9
```
But the fact that the %HV output differs based on message length (the last one) is strange indeed.

Could you share your relevant `log` and `log-format` directives please?

**Comment by Darlelet** [comment]
Ok, I'm able to reproduce using curl client.
It's completely unrelated to `<length>` / syslog truncation so you can safely ignore my previous message

**Comment by Darlelet** [comment]
You're probably reaching `tune.http.logurilen` limit instead

which defaults to:
`
include/haproxy/defaults.h:92:#define REQURI_LEN      1024
`

See: https://docs.haproxy.org/dev/configuration.html#tune.http.logurilen

**Comment by amsnek** [comment]
> You're probably reaching `tune.http.logurilen` limit instead
> 
> which defaults to: `include/haproxy/defaults.h:92:#define REQURI_LEN 1024`
> 
> See: https://docs.haproxy.org/dev/configuration.html#tune.http.logurilen

That is absolutely correct! 🙈 Should have found that setting, somehow I was thinking that the default urilength is much longer -> thanks a lot!
