### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING / malformed HTTP packet.

### ISSUE THREAD

**Issue by Mike-Benoit** [haproxy/haproxy#2207]
### Detailed Description of the Problem

We are experiencing an issue where a specific web application that uses large 99.5KB .CSS files causes a net::ERR_INCOMPLETE_CHUNKED_ENCODING error when accessed from a computer on a high latency network (across the Atlantic Ocean).

We are unable to replicate the problem with closer devices, however, multiple computers (and phones) using separate internet connections across the Atlantic consistently exhibit the same issue.

The problem persists over H2 and H1 protocols with SSL enabled, where we experience net::ERR_CONNECTION_RESET errors. We have managed to replicate the issue on H1 with SSL disabled to minimize variables.

The issue doesn't occur when we bypass HAProxy and use TCP port forwarding directly to the backend web server, suggesting that the issue lies with HAProxy. However, we cannot find any relevant errors in the logs.

**Additional Information:**

- Packet captures from both ends and config files can be found here: [packet_captures.tar.gz](https://github.com/haproxy/haproxy/files/11991360/packet_captures.tar.gz)

- Logs and developer trace can be found here: [haproxy_trace_failed_encoding.log](https://github.com/haproxy/haproxy/files/11991368/haproxy_trace_failed_encoding.log)

- When we disabled mod_deflate in Apache on the backend server, the issue resolved itself immediately.
- In Apache, setting DeflateBufferSize to 1000000 (JS file is about 363K), changes the error from a chunked error to ERR_CONTENT_LENGTH_MISMATCH.

- The backend server doesn't seem to matter, we moved a large .JS file to another server and the exact same issue occurred.

Issue was originally discussed with Willy Tarreau on the mailing list linked below, moving it here for easier tracking:
https://www.mail-archive.com/haproxy@formilux.org/msg43516.html

### Expected Behavior

The large .CSS files should load correctly without any errors.

### Steps to Reproduce the Behavior

**Steps to reproduce:**

Access the specific web application that uses large 99.5KB .CSS files from a computer on a high latency network (across the Atlantic Ocean).
Actual Result:

We are experiencing a net::ERR_INCOMPLETE_CHUNKED_ENCODING error when the large .CSS files are loaded.

### What is your configuration?

```haproxy
OS: Ubuntu 22.04
HAProxy version: 2.7.7
```

### Output of `haproxy -vv`

```plain
2.7.7
```

**Comment by capflam** [comment]
Thanks I will investigate

**Comment by capflam** [comment]
The trace file is truncated. It only shows the request on the frontend side.  Is it possible to have a full transaction, including exchange with the server ?
 
On the tcpdump, the response is indeed truncated. It could be good to also perform a capture between haproxy and the server. In addition, could you check "show errors" output on the CLI ?

**Comment by Mike-Benoit** [comment]
Apologies for the delayed response. Unfortunately its quite a process for us to replicate this issue, as it involves taking down critical infrastructure and coordinating between multiple people halfway across the globe. Due to this bug, we were forced to migrate all of our systems away from haproxy to nginx reverse proxy, which has also eliminated other nagging issues (random git communication errors and a handful of customers saying they can't access our site) we have been fighting with for many years, though we now suspect they were all caused by this bug too.

We would love to help fix this so we can migrate back to haproxy, but due to the difficulty and cost in replicating it, it would be helpful to have real-time communications with a haproxy developer during the process so we can ensure we collect any and all data required at one time and don't have to continue repeating the process to collect more and more data. 

I realize its a big ask, but would this be possible to arrange by chance?

**Comment by capflam** [comment]
Now its my turn to be sorry about the delay. Honestly, real-time debugging will not be possible. I totally understand your point of view of course. Debugging an issue on a production environnement is always a big deal. But on our side we cannot start to this kind of support. Otherwise, we risk heading down a slippery slope. I hope you understand.

Except by testing a new release, eventually the latest 2.8, I don't know how to help you. For now, there are not enough info to move forward. Let me know if you think your able to work on it or not. If not I will close the issue hoping to reopen it one day... or not if the issue gone by chance.

**Comment by capflam** [comment]
I'm gently closing the issue now, tagging it as "cannot reproduce".
