### ISSUE TITLE
Lua: Allow retrieving of "proc." scoped vars from core.

### ISSUE THREAD

**Issue by TheDJVG** [haproxy/haproxy#2212]
### Your Feature Request

Sometimes It's nice to be able to retrieve "proc." variables set in "global" to be retrieved in places where there's no TXN or Applet available (register_init or register_task).

For example a variable is set with information used by a task, like an instance name for haproxy or a hostname that's used by multiple lua files.

Having a method like `core.get_var()`  would allow us to get access to these proc. scoped variables.

### What are you trying to do?

In this specific case there's a LUA task that talks to an external system and information on how to talk to that system needs to be available.

Although the same can be achieved using `os.getenv()`  and have this information stored in environment variables it's nice to define things 1 time in the global config to be used in different places. Currently it's not possible for a task to retrieve a variable set in the "proc." scope.

### Output of `haproxy -vv`

```plain
HAProxy version 2.9-dev1-65f18d-34 2023/07/11 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 6.4.1-1.0 #1 SMP PREEMPT_DYNAMIC Sat Jul  1 21:38:12 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_LUA=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER -OPENSSL -OPENSSL_WOLFSSL -OT -PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ -SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.1.1 20230429

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by TheDJVG** [comment]
A possible implementation could look like this:

```patch
diff --git a/src/hlua.c b/src/hlua.c
index ae0d412a4..ea750b947 100644
--- a/src/hlua.c
+++ b/src/hlua.c
@@ -1965,6 +1965,33 @@ static int hlua_set_map(lua_State *L)
        return 0;
 }
 
+/* This function is an LUA binding. It provides a function
+ * for retrieving a var from the proc scope in core.
+ */
+ static int hlua_core_get_var(lua_State *L)
+{
+       const char *name;
+       size_t len;
+       struct sample smp;
+
+       MAY_LJMP(check_args(L, 1, "get_var"));
+
+       name = MAY_LJMP(luaL_checklstring(L, 1, &len));
+
+       /* We can only retrieve information from the proc. scope */
+       /* FIXME: I didn't want to expose vars_hash_name from vars.c */
+       if (len < 5 || strncmp(name, "proc.", 5) != 0)
+               WILL_LJMP(luaL_error(L, "'get_var': Only 'proc.' scope allowed to be retrieved in 'core.get_var()'."));
+
+       if (!vars_get_by_name(name, len, &smp, NULL)) {
+               lua_pushnil(L);
+               return 1;
+       }
+
+       return MAY_LJMP(hlua_smp2lua(L, &smp));
+       return 1;
+}
+
 /* This function disables the sending of email through the
  * legacy email sending function which is implemented using
  * checks.
@@ -13202,6 +13229,7 @@ lua_State *hlua_init_state(int thread_num)
        hlua_class_function(L, "del_acl", hlua_del_acl);
        hlua_class_function(L, "set_map", hlua_set_map);
        hlua_class_function(L, "del_map", hlua_del_map);
+       hlua_class_function(L, "get_var", hlua_core_get_var);
        hlua_class_function(L, "tcp", hlua_socket_new);
        hlua_class_function(L, "httpclient", hlua_httpclient_new);
        hlua_class_function(L, "event_sub", hlua_event_global_sub);
```

**Comment by wtarreau** [comment]
I thought we already had something like this, but I could have been mistaken. Isn't there anything either to get/set txn variables from Lua ? If so, I could be mistaken with this. I'm trying to make sure we implement something consistent and uniform.

**Comment by TheDJVG** [comment]
@wtarreau I've been reading through the [Lua docs](https://github.com/haproxy/haproxy/blob/master/doc/lua.txt) and I don't see a way to access the variables in a register_init or register_task as it does not have a TXN argument and the `core.` class does not have anything regarding reading a variable outside a TXN/AppletHTTP/AppletTCP.

If I'm not reading the docs correctly I'm sorry for opening this issue and it can be closed.

**Comment by wtarreau** [comment]
OK thanks for checking. Ah I think I understand, for other (txn) variables you're using the `var` sample-fetch function under `txn.sf`, that's it ? This is what I wasn't sure about, and then I agree that it's not even possible to make something barely consistent between the two, given that they work radically differently.

I tend to agree with your approach then, and maybe later we'll want to further expand it to `set_var()` as well as there's already `set_map()`. I'm CCing @thierry-f-78 in case he sees an alternate approach that we'd both be missing, but I tend to think yours looks good.

**Comment by TheDJVG** [comment]
I did look into adding `set_var()` but I wasn't sure if that is desirable as some part of the code seem to imply that this might not be allowed, but I might be looking in the wrong spot:

https://github.com/haproxy/haproxy/blob/65f18d65a3822acaa39418d8e919e9afe1f5e781/src/vars.c#L632-L633

**Comment by wtarreau** [comment]
Indeed, you're right. Anyway better avoid doing it until a real need arises. Setting global variables from a Lua script can do as much harm as good!

**Comment by thierry-f-78** [comment]
Hello, the variable code has evolved a lot since I wrote it, so I'm not sure my opinion was interesting :-)

In my memories, the variables are allocated while the configuration is parsed. I'm sure we cant set or modify variable from Lua code, But I'm not sure we can create variable from Lua code.

Anyway, init and task are executed after the haproxy configuration parsing, so manipulating vars in this section should not create problem.

Warning, "core" api is accessible from lua init (the main code of go file which is executed during the configuration parsing), and this could create probleme, so it would be better to check the execution context of the variable manipulation. In my memories, a flag indicates the haproxy runtime mode.

**Comment by wtarreau** [comment]
Thank you Thierry. But what could be the problem during init ? In the worst case, the variable doesn't exist and that's all, no ? The rest of the subsystems are already initialized anyway during the init code (i.e. vars lists are already initialized). The lua init code will only see a variable declared before the lua-load file though. But that's true for about anything in the global section anyway.

**Comment by thierry-f-78** [comment]
You're right, it's likely that I say anything. I admit that I did not read the code carefully before giving my opinion.

I had in mind that the variable names are resolved when reading the configuration in order to provide enough space in the session and in the core and to have indexed access to the variables. This is probably an erroneous memory, because it seems that the variables are resolved at the time of their use, and in this case, it is no problem to use them from anywhere.

I just came across this `vars_parse_cli_set_var()` function in `src/vars.c` which should serve as inspiration for writing the necessary in Lua.

**Comment by TheDJVG** [comment]
I used the `get_var` function from the Lua TXN class as an example writing the code and removed the part that sets the txn/sess information as that would not be available as the function is not used in that context.

**Comment by thierry-f-78** [comment]
Your `get_var` patch seems right.

It would be better to process the `set_var` as well.

> I did look into adding set_var() but I wasn't sure if that is desirable as some part of the code seem to imply that this might not be allowed, but I might be looking in the wrong spot:

The reason is explain here: 3a4bedccc60 the author is @wtarreau (and here 7055301934e39). I'm not sure to understand the reason de la limitation.

**Comment by wtarreau** [comment]
Ah indeed. I do remember that some users creating associative arrays using variables used to create insane amounts of names slowing everything down. At least with the txn, sess etc scopes, that was limited to a single element carrying them all, and all would vanish. However with `proc.` they will persist.

Thus I tend to think it's better to keep it as @TheDJVG did (i.e. only get_var) for now, and wait to see if someone *really* needs a set_var() and with what constraints if at all.

**Comment by thierry-f-78** [comment]
ok for the explanation.

Nice usage ! I never thing this usage when I wrote vars system. BTW Lua provides all the necessary for this kind of usage. It would be clever to write Lua code to store array (of course, centralized information will make HAProxy slower due to necessary lock).

**Comment by wtarreau** [comment]
Now merged, thank you. I found in the regtests that the applets are in fact already capable of getting/setting a variable: `applet.get_var()` and `applet.set_var()`. But clearly that's very limiting as you'd want to use this anywhere else. If could could adjust the set_var.lua and set_var.vtc test cases to cover your modification, that would be great, it could avoid that it breaks during a change in the future.
