### ISSUE TITLE
Add option to update status code during timeout queue in haproxy.cfg

### ISSUE THREAD

**Issue by ajaymovva** [haproxy/haproxy#2221]
### Your Feature Request

- Currently, HAProxy is throwing a `503` status code when the request is queue timeout on the HAProxy backend. As we have a `maxconn` setting for the server, if there are more connections than the `maxconn` setting, the request is waiting on the backend queue, and once the `timeout queue` duration is completed, the haproxy will send a `503` status code for these connections. Which is also the same status code if there is a `conn-failure` between HAProxy and the server.
- As a service, we want to differentiate connection failures/queue timeouts so that we can track the exact connection failures.
- We want to track the timeout queue cases and explicitly modify the status code `503` to `4xx(429)` based on our cases so that it won't contribute to the error rate.

### What are you trying to do?

- We are trying to use http-after-response` to track the 503 status code for the HAProxy backend if there is any timeout queue and modify the status code from 503 to 4xx(429).
- We are looking for an option to verify if there is a queue timeout and update status in `haproxy.cfg` using `http-after-response`.

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.14 2023/06/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.14.html
Running on: Linux 5.10.149-133.644.amzn2.x86_64 #1 SMP Tue Oct 18 16:52:42 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = x86_64-pc-linux-gnu-gcc
  CFLAGS  = -Wchar-subscripts -Wcomment -Wformat -Winit-self -Wmain -Wmissing-braces -Wno-pragmas -Wparentheses -Wreturn-type -Wsequence-point -Wstrict-aliasing -Wswitch -Wtrigraphs -Wuninitialized -Wunknown-pragmas -Wunused-label -Wunused-variable -Wunused-value -Wno-error=missing-include-dirs -Wno-error=narrowing -Wpointer-sign -Wimplicit -pthread -fdiagnostics-color=auto -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -msse -mfpmath=sse -march=core2 -g -fPIC -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -QUIC +RT +SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.0.2zg  7 Feb 2023
Running on OpenSSL version : OpenSSL 1.0.2zg  7 Feb 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.4.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by ajaymovva** [comment]
@capflam  Need your thoughts on this

**Comment by capflam** [comment]
Indeed, for now there is no way to retrieve the error type (queue timeout/error, connection timeout/error ...) It was useless is older versions but it could be useful now there are http-after-response rules.

However, we must address the feature  in the right way. It is not specific to the queue timeout. It is a specific case of a larger issue. We've planned to rework error management and that includes indirectly this feature. But it is a long term work. But at short-term, several sample fetches should be added to be able to retrieve all loggable information, to have a sample fetch for all `%...` . One of them is the termination state. It means, once added, you should be able to add an acl to match the `sQ`  termination state.

**Comment by ajaymovva** [comment]
>  One of them is the termination state. It means, once added, you should be able to add an acl to match the sQ termination state.

@capflam Do we have anyway today in any Haproxy version we can fetch termination state and match with acl. Also, if it is not available, a tentative timeline for when the short-term fix is available so that we can work with this short-term approach until the complete feature is available.

**Comment by capflam** [comment]
AFAIK, it is not possible for now. But as said, it is planned to add a sample fetch to get the termination state. It will be available for the 2.9. At short term, it will be the only solution to perform what you want to achieve. I will notify you when it will be available.

**Comment by capflam** [comment]
FYI, I pushed a `txn.sess_term_state` sample fetch. In the doc, there is an exemple to change the status code depending on its value, to set a 429 for `sQ`.

**Comment by ajaymovva** [comment]
Thanks!! 

@capflam  will be very helpful if it can backport these change to below versions atleast 2.6.x version.

**Comment by wtarreau** [comment]
Please no. We always say that minor backports to the latest LTS release can sometimes be considered when they're minor, but there's really zero reason to go further, and it goes against the principle of super stability that users expect by sticking to older releases. And the latest LTS is 2.8, so if that's backportable there I'm personally all for it if that helps, but not for 2.6.
