### ISSUE TITLE
req.payload not works correctly

### ISSUE THREAD

**Issue by vincenzocapasso7** [haproxy/haproxy#2229]
### Detailed Description of the Problem

I'm using Haproxy to inspect traffic in TCP mode and send parsed traffic to backend, I'm using req.payload() function to obtain TCP payload and search a string in it. The problem is that I can't reject TCP connection based on content because is esecuted all the time the default_backend. I've analyzed the packets that the client send and the payload is correct.

### Expected Behavior

Requests that contain string "USER" must be dropped.

### Steps to Reproduce the Behavior

You can reproduce the behavior in 2.6 and 2.8 version, I haven't tried in other versions. I've installed Haproxy with APT on Ubuntu 20.04.

### What is your configuration?

```haproxy
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd li>
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2>
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES12>
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_S>
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults        
        log     global
        mode    tcp
        option  tcplog
        timeout connect 5000
        timeout client  50000
        timeout server  50000
frontend ftp_frontend
        bind 10.10.11.2:21
        mode tcp
        tcp-request inspect-delay 2s
        tcp-request content capture req.payload(0,0) len 4
        tcp-request content reject if { req.payload(0,4) -m  str "USER" }
        tcp-request content reject if { req.payload(0,4) -m  str "user" }
        default_backend ftp_backend
backend ftp_backend
        mode tcp
        server ftp_server 10.10.20.3:21
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.14-1ppa1~focal 2023/06/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.14.html
Running on: Linux 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64
```

**Comment by capflam** [comment]
Looking at your frontend/backend naming, it seems you are dealing with FTP client and server. The FTP protocol is a banner protocol. It means the server speaks first. Thus, you won't receive anything from the client before the connection establishment to the server. You will reach the inspect-delay timeout and no reject rules won't match. 

If I'm right, there is no bug here. It works as expected from HAProxy point of view. You just try to do something that cannot be achieved with HAProxy.
