### ISSUE TITLE
Risk of overflow in int tick_add(int now, int timeout) ?

### ISSUE THREAD

**Issue by Tony-X** [haproxy/haproxy#2232]
### Detailed Description of the Problem

During investigation of an issue that HAProxy returns http 408 for perfectly fine request, I noticed that timeout calculation code could potentially overflow

https://github.com/haproxy/haproxy/blob/master/include/haproxy/ticks.h#L78-L84

```
static inline int tick_add(int now, int timeout)
{
	now += timeout;
	if (unlikely(!now))
		now++;    /* unfortunate value */
	return now;
}
```

there are multiple calls to `tick_add` to calculate various kinds of timeouts. 

Here is one example from [http-ana.c](https://github.com/haproxy/haproxy/blob/master/src/http_ana.c#L4103)

```
chn->analyse_exp = tick_add_ifset(now_ms, time);
```

I noted now_ms is maintained in clock.c and it is an `uint` but here the code is performing arithmetic on signed integer. 

### Expected Behavior

N/A

### Steps to Reproduce the Behavior

This godbolt snippet grabs the relevant functions from ticks.h. 

https://godbolt.org/z/obq81sTGT

you can switch the compiler between `x86-64-gcc-12.1` and `x86-64-gcc-9.5` to explore the differences interactively. 
Notably, gcc9.5's output is expected (179 false followed by 2 true), gcc 12.1 breaks the loop early and no `false` is printed.

### Do you have any idea what may have caused this?

[signed integer overflow is UB](https://en.cppreference.com/w/c/language/behavior).

### Do you have an idea how to solve the issue?

We could use a larger type (e.g. `long`) to compute and  store the timeout. 

### What is your configuration?
We use the client timeout setting. The rest doesn't matter much.

```haproxy
defaults
    mode        http
    timeout client 180s
    timeout server 30s
```

### Output of `haproxy -vv`
It doesn't matter.

**Comment by Tony-X** [comment]
Closing for now. I'll recreate one if I have a precise repro

**Comment by Tony-X** [comment]
Reopened as I figured out a repro

**Comment by TimWolla** [comment]
> [signed integer overflow is UB](https://en.cppreference.com/w/c/language/behavior).

HAProxy sets `-fwrapv`:

https://github.com/haproxy/haproxy/blob/c156c5bda6d51c743b2f4af9ee87f53f38a946bd/Makefile#L182-L184

Is this an issue you encountered in the wild or is this issue based on reading the code?

**Comment by Tony-X** [comment]
Thanks @TimWolla! I did encounter issues in the wild. We build HAProxy by ourselves so it is very likely we missed this flag.
