### ISSUE TITLE
SSL_CTX_set_keylog_callback: permit to log all key used in EDH or ECDH tls

### ISSUE THREAD

**Issue by laurentL** [haproxy/haproxy#224]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.19-1~bpo9+1 2019/02/12
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-1.8.19=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.0f  25 May 2017
Running on OpenSSL version : OpenSSL 1.1.0k  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE2 version : 10.22 2016-07-29
PCRE2 library supports JIT : yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace


4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux
```

## What should haproxy do differently? Which functionality do you think we should add?
Like a lot of software using openssl, could you add a callback to log all key used during handcheck?
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_keylog_callback.html

## What are you trying to do?

I am trying to decode all request, but it's not possible without this key :
http://ssldump.sourceforge.net/TROUBLESHOOTING Case3
Case 3: Ephemeral keying
If SSL is using one of the ephemeral keying modes then ssldump cannot
decrypt the data. These modes include essentially all of the DH cipher
suites as well as the RSA_EXPORT cipher suites (though not the
RSA_EXPORT1024) cipher suites. A sure sign of this case is when
the server is sending the ServerKeyExchange message. 

If you want to decrypt the connection, you'll have to turn off these
cipher suites on the client or server. If you're getting EXPORT cipher
suites, this probably means you have only an export client and it's
time to upgrade.

**Comment by lukastribus** [comment]
We already have this in 2.0 (introduced in commit 65674662b4b950c7f5fb7572859b98ef8c9a8767), see [ssl_fc_client_random](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#7.3.4-ssl_fc_client_random).

**Comment by laurentL** [comment]
Thanks a lot
