### ISSUE TITLE
src/quic_tx.c: build failed on m68k

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2261]
### Tool Name and Version

gcc / m68k

### Code Report

```plain
CC      src/quic_rx.o
  CC      src/quic_tx.o
In file included from include/haproxy/quic_tx.h:26,
                 from src/quic_tx.c:15:
src/quic_tx.c: In function ‘qc_prep_app_pkts’:
include/haproxy/quic_conn-t.h:241:17: error: comparison of distinct pointer types lacks a cast [-Werror]
  241 |     (void) (&_a == &_b);  \
      |                 ^~
src/quic_tx.c:507:37: note: in expansion of macro ‘QUIC_MIN’
  507 |                         end = pos + QUIC_MIN((uint64_t)qc->path->mtu, quic_may_send_bytes(qc));
      |                                     ^~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
The problem is the `(uint64_t)` cast on the left side while the right side is `size_t`. I'm wondering why it's not complaining on other 32-bit archs such as i386 and ARM though.

**Comment by wtarreau** [comment]
CC @haproxyFred

**Comment by chipitsine** [comment]
We stop on the first failure

**Comment by wtarreau** [comment]
Ah that's a good reason :-)

**Comment by haproxyFred** [comment]
Ok. I have just pushed a fix here:
https://github.com/haproxytech/quic-dev/commit/80c71c44190a696ce23d657b3ab80f742419d940

**Comment by haproxyFred** [comment]
@wtarreau I have pushed again this commit here https://github.com/haproxytech/quic-dev/commit/57b656e68b51822df83e1f62c86408be3108ae7b . It seems it has been removed from its original branch.
It can be merged. Thank you.

**Comment by chipitsine** [comment]
fixed in https://github.com/haproxy/haproxy/commit/3afe54ed5b78646a5bcbda17ac8475031578a806
