### ISSUE TITLE
SSL session cache with wolfSSL

### ISSUE THREAD

**Issue by hpn0t0ad** [haproxy/haproxy#2263]
### Detailed Description of the Problem

Hi, I have a question and possible bug report about different SSL session cache behaviour between OpenSSL and wolfSSL. Just for some context I need HTTP/3 support so I've previously compiled haproxy myself with various versions of the quictls fork and I've also used pre-build docker images from `haproxytech/haproxy-alpine-quic`. Each of them seem to have some sort of memory leak which leads to haproxy crashing and the docker container restarting at various intervals related to user traffic.
Since you recently added support for wolfSSL I tried building haproxy accordingly (wolfSSL: `--enable-haproxy --enable-quic`, haproxy: `USE_QUIC=1 USE_OPENSSL_WOLFSSL=1`). While that build has not crashed on me yet, I'm confused by the prometheus metrics `haproxy_process_ssl_cache_lookups_total` and `haproxy_process_ssl_cache_misses_total`.
See this Grafana screenshot:
<img width="1657" alt="Screenshot 2023-08-23 at 10 22 23" src="https://github.com/haproxy/haproxy/assets/48860505/635b3925-575b-499c-b3e0-2d580be99b24">

It seems to me that the number of session cache lookups is greatly increased while the number of non-misses is very low since switching to wolfSSL (since 08/23).
Is that behaviour expected?
Does caching work ('better'/differently) with OpenSSL?
What are the implications (performance, stability)? 

### Expected Behavior

SSL session cache should work when using wolfSSL.

### Steps to Reproduce the Behavior

Build haproxy with wolfSSL and check the SSL cache prometheus metrics.

### What is your configuration?

```haproxy
-
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.2-61a0f57 2023/08/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.2.html
Running on: Linux 4.15.0-208-generic #220-Ubuntu SMP Mon Mar 20 14:27:01 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL_WOLFSSL=1 USE_LUA=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL +OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=120).
Built with OpenSSL version : wolfSSL 5.6.3
Running on OpenSSL version : wolfSSL 5.6.3
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wlallemand** [comment]
WolfSSL support is still experimental for now. There were indeed issues with the session and tickets callback, which were fixed in WolfSSL with PR https://github.com/wolfSSL/wolfssl/pull/6329 . I don't think it was release in a new version yet. Also even with these fixes, the implementation is different than the one of OpenSSL, and cache lookups are expected even in case of stateless TLS tickets where openssl does not lookup in this case.

**Comment by hpn0t0ad** [comment]
Ok, thanks for the clarification!
