### ISSUE TITLE
Objects in cache with diffrent headers

### ISSUE THREAD

**Issue by xanaxalan** [haproxy/haproxy#2264]
### Detailed Description of the Problem

I was looking into how cache objects are generated and noticed that regardless of headers values there is only one object created. I would expect that different headers should produce different objects for the same url. 

### Expected Behavior

More than one object in cache when headers are different.

### Steps to Reproduce the Behavior

curl -v --http1.1  -H 'accept-encoding: deflate'   -H 'referer: https://example.com1'  --resolve example.com:443:127.0.0.1 https://example.com/staticfile.svg
This generates in cache: (show cache )
hash:4090443040 vary:0x0001000000000000 size:11890 (12 blocks), refcount:0, expire:100
When running while first object is in cache.
curl -v --http1.1  -H 'accept-encoding: gzip' -H 'referer: https://example.com2'  --resolve example.com:443:127.0.0.1 https://example.com/staticfile.svg
This is not producing any new cached objects.

### What is your configuration?

```haproxy
cache static_cache
  total-max-size 128
  process-vary on
  max-age 120

backend some_backend
  http-request cache-use static_cache
  http-response cache-store static_cache
```

### Output of `haproxy -vv`

```plain
checked on 2.7.6 and 2.8.2
haproxy -vv
HAProxy version 2.8.2-61a0f57 2023/08/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.2.html
Running on: Linux 6.1.11-1.el8.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb  8 17:46:25 EST 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1 USE_OT=1 USE_PROMEX=1 USE_PCRE=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL +OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1v  1 Aug 2023
Running on OpenSSL version : OpenSSL 1.1.1v  1 Aug 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-18)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [  OT] opentracing
        [SPOE] spoe
        [TRACE] trace
```

**Comment by rlebreton** [comment]
If your server were to have a "Vary: accept-encoding" header in its response, we would have different entries stored in the cache. But if you only have one entry registered, it might be that your server does not have this header and that it sends the same response to your request, regardless of your "Accept-encoding" value.

The vary part of the cache only supports the "Accept-encoding" and "Referer" as headers out of which a specific secondary hash can be calculated but it does not mean that any request that has either one of those headers will receive a different response from the server and will have a dedicated cache entry created.

**Comment by xanaxalan** [comment]
Thank you for the quick response :) I can see that haproxy responses to my curl have
vary: accept-encoding 
additionally backend web server is responding to the same curl differently for deflate and gzip.
for gzip I can see (directly from backend web server):
< Vary: Accept-Encoding
< Content-Encoding: gzip
With deflate, there is no  Content-Encoding header in response only vary.
< Vary: Accept-Encoding

**Comment by xanaxalan** [comment]
Ok now if I request via hap, with accept-encoding deflate it's getting cached and if I do another one  as long as the cache object is not expired I am  getting object from the cache which is not compressed....
Request with deflate::
> Accept-Encoding: deflate
< content-length: 67438
< vary: accept-encoding

Now immediate request with gzip and response is the same:
> Accept-Encoding: gzip
< content-length: 67438
< vary: accept-encoding

Now we wait for cache to expire and repeat request with gzip and in response:
> Accept-Encoding: gzip
< content-encoding: gzip
< content-length: 12709
< vary: accept-encoding

**Comment by rlebreton** [comment]
That's weird, it should work fine. 
If you have time, could you check that the caching does happen in haproxy and not somewhere else along the line (which seems unlikely but we would be sure that way). The way it's checked in the reg-tests is by using the res.cache-hit variable like so:
    http-response set-header X-Cache-Hit %[res.cache_hit]

**Comment by xanaxalan** [comment]
First request:
> Accept-Encoding: deflate
< content-length: 67438
< vary: Accept-Encoding
< x-cache-hit: 0

Second:

> Accept-Encoding: deflate
< content-length: 67438
< vary: Accept-Encoding
< x-cache-hit: 1

Third:
> Accept-Encoding: gzip
< content-length: 67438
< vary: Accept-Encoding
< x-cache-hit: 1

After cache expired:
> Accept-Encoding: gzip
< vary: Accept-Encoding
< content-encoding: gzip
< content-length: 12709
< x-cache-hit: 0

Second:
> Accept-Encoding: gzip
< vary: Accept-Encoding
< content-encoding: gzip
< content-length: 12709
< x-cache-hit: 1

But even if compressed object is in cache:
> Accept-Encoding: deflate
< content-length: 67438
< vary: Accept-Encoding
< x-cache-hit: 0

**Comment by xanaxalan** [comment]
What do you do when web server sets
vary: Accept-Encoding
but at the same time Accept-Encoding is not set in the response. I think this gets cached and then it's used as valid cache to any value set in Accept-Encoding

**Comment by rlebreton** [comment]
I think I finally understood what happens. What's causing your issue seems to be the lack of `content-encoding` header in your response when you ask for a `deflate` encoding.
In the RFC for content-encoding header, they specify some specific encodings that behave differently than regular content encoding, and namely the `identity` one (see https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.4).

Since your first response does not have a `content-encoding`, it is seen as having the `identity` encoding which is always implicitly approved even when other encodings are explicitly asked. 
When your other request with an explicit `accept-encoding: gzip` arrives, we look in the cache for a match and happen to find the previous entry which was stored with an `identity` encoding. And since the request is treated the same way as if you had an `accept-encoding: gzip, identity` header, we consider that the cached entry can be reused.

In your second test case, the first request has an `accept-encoding: gzip` header and receives a `content-encoding: gzip` response. this information is stored in the cached entry. So the next request that presents an `accept-encoding: deflate` header (which is treated as an `accept-encoding: deflate, identity` header) does NOT match this time and is then forwarded to the server.

**Comment by xanaxalan** [comment]
Thank you for detailed explanation. Should it work like that from cache perspective? If lack of `content-encoding` is treated as `identity` or even if there is valid request which will get identity in the response it's poisoning the cache.

**Comment by rlebreton** [comment]
The cache's main objective is to avoid unnecessary requests to the server so in that regard, sending any response with an accepted content-encoding to a client is valid. If a client really wanted only gzipped responses, he could still reject `identity` responses via `accept-encodin: gzip, identity;q=0`.
The cache still should provide valid responses, which is the case in your tests so there is no poisoning. If your server had actually sent a deflated response to a client having an `accept-encoding: deflate` header, then you would have had two entries in the cache, one deflated and one gzipped.

**Comment by xanaxalan** [comment]
Thank you for explanation. I got around the problem by creating separate caches and using them for specific header combination.
