### ISSUE TITLE
Prometheus metric to determine active/backup state per server

### ISSUE THREAD

**Issue by paurkedal** [haproxy/haproxy#2271]
### Your Feature Request

The `ST_F_BCK` stats field is currently only exported as `haproxy_backend_backup_servers`.  I would like for the metric also to be added for servers to make it possible to determine whether it is active or backup.  Or have I missed another metric which would determine this?

I can see at least `stats.c` uses `ST_F_BCK` for servers for this purpose, so maybe it's a matter of adding the `PROMEX_FL_SRV_METRIC` flag to the `*backup_servers` metric in `addons/promex/service-prometheus.c`?

### What are you trying to do?

Including the active/backup state of servers in Prometheus-based monitoring.

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.0.31-0ubuntu0.2 2023/08/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-OmFwdF/haproxy-2.0.31=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : -51DEGREES +ACCEPT4 -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL +EPOLL -EVPORTS +FUTEX +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MY_ACCEPT4 -MY_EPOLL -MY_SPLICE +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PRIVATE_CACHE -PTHREAD_PSHARED +REGPARM +RT -SLZ -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -VSYSCALL -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```
```

**Comment by capflam** [comment]
It is annoying because, indeed, the metric is available for the servers. I mean, it is exposed by the stats. However, on the prometheus exporter, there is a problem because the metric names must for now be the same for the frontends, backends and servers. Here `_active_servers` and `_backup_servers` are not suitable for servers.

I will specialized metric names per scope. But I don't know if it will be backported. And for sure not as far as 2.0.

**Comment by paurkedal** [comment]
Yes, I noticed the issue with the naming.  I would have gone for `haproxy_server_active_servers` (and `haproxy_server_backup_servers`) for consistency, anyway.  I mean, it's not wrong to say that "the number of active servers among that server is 0 or 1", although it is admittedly an rather odd way of putting it when seen out of this context of consistency.  I don't have strong opinions on the names, though.

**Comment by paurkedal** [comment]
And thanks for looking into it. (We'll have to see what we can do ourselves about backporting the solution or a workaround.)

**Comment by capflam** [comment]
Well, It just demonstrates we should split metric names by scope. It is not really hard to do and more maintainable.

**Comment by capflam** [comment]
FYI, it is planned for the 3.0 (already in the 2.9-next). It was not pushed in the 2.9 because it is freezed. The 2.9.0 is planned for tomorrow.

**Comment by capflam** [comment]
Fixed now.

**Comment by paurkedal** [comment]
Thanks!
