### ISSUE TITLE
src/quic_tx.c: regression caught by quic interop

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2282]
### Detailed Description of the Problem

server: [haproxy](https://github.com/haproxy/haproxy/commit/fb4294be55d372a20aee0c0f430c508a20bfb020) - libressl
client: quic-go
testcase: longrtt

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==28==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000098 (pc 0x5610a52ef9d1 bp 0x7fe9659f3f40 sp 0x7fe9659f3ab0 T2)
==28==The signal is caused by a READ memory access.
==28==Hint: address points to the zero page.
    #0 0x5610a52ef9d0 in qc_dgrams_retransmit src/quic_tx.c:1360
    #1 0x5610a52103de in quic_conn_io_cb src/quic_conn.c:913
    #2 0x5610a58c9038 in run_tasks_from_lists src/task.c:596
    #3 0x5610a58cae33 in process_runnable_tasks src/task.c:876
    #4 0x5610a57bcc64 in run_poll_loop src/haproxy.c:2981
    #5 0x5610a57bdafe in run_thread_poll_loop src/haproxy.c:3180
    #6 0x7fe969529608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8608)
    #7 0x7fe968f2d162 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x11f162)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/quic_tx.c:1360 in qc_dgrams_retransmit
Thread T2 created by T0 here:
    #0 0x7fe96983a815 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:208
    #1 0x5610a5a185b6 in setup_extra_threads src/thread.c:252 
    #2 0x5610a57c0b7c in main src/haproxy.c:3864
    #3 0x7fe968e320b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)

==28==ABORTING
```

### Expected Behavior

hmm

### Steps to Reproduce the Behavior

run quic interop tests against asan enabled haproxy + libressl

### What is your configuration?

```haproxy
no idea
```

### Output of `haproxy -vv`

```plain
mo idea
```

**Comment by haproxyFred** [comment]
Well, I should have checked all the cases where some NULL pointers could be dereferenced. That said, I do not understand why such bug arrives only with libressl :astonished: 
I have just pushed a fix for this issue in **gh2282** branch here:
https://github.com/haproxytech/quic-dev/commit/b5bcc27feef93341bb01928327316b47d62bbe54
Except if I am not totally awaken, I hope this is the last one @wtarreau

**Comment by wtarreau** [comment]
Now merged, thanks to you both.

**Comment by chipitsine** [comment]
I also wonder why only libressl is affected.
chances are that I built quictls without asan
