### ISSUE TITLE
Backend SRV discovered and created via server-template disregards "check port" setting

### ISSUE THREAD

**Issue by kovaxur** [haproxy/haproxy#2287]
### Detailed Description of the Problem

We are using HAProxy on Kubernetes and discover backend pods via SRV records managed by Kubernetes services. Our application (tcp) has a monitoring port for load-balancers, so we would like to set the "check port" configuration in the server-template part, but it seems, that after configuring the port, HAProxy still sends TCP connections to our pods.

Configuration:
```
resolvers kubernetes
  nameserver k8s kube-dns.kube-system.svc.cluster.local:53
  accepted_payload_size 8192

frontend data-main
  mode tcp
  bind :12345
  default_backend data-main

backend data-main
  mode tcp
  balance leastconn
  server-template data-main _data-main._tcp.<service-name>.<namespace>.svc.cluster.local resolvers kubernetes init-addr none resolve-opts allow-dup-ip resolve-prefer ipv4 **check port 12346** observe layer4
```

With these settings, we see connections opened and closed coming from HAProxy.

### Expected Behavior

We think, that check connections should only be opened on the specified port **12346**

### Steps to Reproduce the Behavior

* HAProxy installed via helm, helm version: 1.19.2, HAProxy container image: haproxytech/haproxy-alpine:2.8.1
* Start HAProxy with the supplied configuration

We see the following error on the pods:

`{"message":"Error: socket hang up","timestamp":"2023-09-11T08:09:29.721Z","hostname":"XXX","pid":1,"stack":"Error: socket hang up\n    at connResetException (node:internal/errors:720:14)\n    at TLSSocket.onSocketClose (node:_tls_wrap:1103:23)\n    at TLSSocket.emit (node:events:526:35)\n    at node:net:323:12\n    at Socket.done (node:_tls_wrap:588:7)\n    at Object.onceWrapper (node:events:629:26)\n    at Socket.emit (node:events:514:28)\n    at TCP.<anonymous> (node:net:323:12)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)","error":{"code":"ECONNRESET"},"level":"error"}`

### Do you have any idea what may have caused this?

Maybe this is undocumented and the feature is not supported when SRV discovery happend, however in the documentation it says, that all the server-template settings are supported.

### What is your configuration?

```haproxy
resolvers kubernetes
  nameserver k8s kube-dns.kube-system.svc.cluster.local:53
  accepted_payload_size 8192

frontend data-main
  mode tcp
  bind :12345
  default_backend data-main

backend data-main
  mode tcp
  balance leastconn
  server-template data-main _data-main._tcp.<service-name>.<namespace>.svc.cluster.local resolvers kubernetes init-addr none resolve-opts allow-dup-ip resolve-prefer ipv4 **check port 12346** observe layer4
```
```


### Output of `haproxy -vv`

```plain
We use the following image: haproxytech/haproxy-alpine:2.8.1
```

**Comment by kovaxur** [comment]
It seems, that the issue is not with HAProxy, we have AWS loadbalancers in front of the HAProxy and those are sending the checks to the wrong ports.

**Comment by Darlelet** [comment]
alright, thanks for the update @kovaxur :)
