### ISSUE TITLE
[2.0.4] Gzip compression does not work with header request "Expect: 100-continue".

### ISSUE THREAD

**Issue by pronikell** [haproxy/haproxy#229]
Hello.
###  Build options :
Linux p-proxy1 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Built with zlib version : 1.2.8
Running on zlib version : 1.2.8

### Configuration in backend : 

```
        compression algo gzip
        compression type application/x-hessian text/html
```

### Steps to reproduce :

1. Work:
```
$ curl -X GET http://host:8080/status -H "accept-encoding: gzip deflate"
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

2. If the request has a header "Expect: 100-continue" it does not work:
```
$ curl -X GET -I http://host:8080/status -H "accept-encoding: gzip deflate" -H "Expect: 100-continue"
HTTP/1.1 100 

HTTP/1.1 200 
vary: accept-encoding
Content-Type: text/html;charset=ISO-8859-1
Content-Language: en-US
Transfer-Encoding: chunked
Date: Wed, 21 Aug 2019 22:29:09 GMT

```
3. Workaround:
`no option http-use-htx` for backend

**Comment by wtarreau** [comment]
This looks like a real bug, probably that a compression analyser is not properly reinitialized when dealing with a 1xx status code in HTX mode. We'll have to wait for Christopher to have a look at this when he's back.  Just a hint though, you're missing the comma between "gzip" and "deflate" in your accept-encoding header, I'm even very surprised it works despite this!

**Comment by capflam** [comment]
This issue should be fixed now. The patch was backported to 2.0.
