### ISSUE TITLE
Cookie Persistence in single h2 connection with multiple requests in it

### ISSUE THREAD

**Issue by thyn** [haproxy/haproxy#2295]
### Detailed Description of the Problem

I have one h2 connection . Inside that connection I have multiple requests with different headers. Haproxy has session cookie persistence. When I run parallel multiple requests I have some requests to different endpoints and Set-Cookie in response. After some requests I don't have Set-Cookie for new requests.

How h2 works with concurrent requests with persistence?

### Expected Behavior

Each request should get it's own Set-Cookie response and have different backend servers to serve

### Steps to Reproduce the Behavior

1. create backend configuration on haproxy 2.3.19
 backend tests-haproxy-tests-responder_haproxy-tests-responder_80
 mode http
 balance hdr(x-test)
 cookie QSID insert indirect nocache httponly dynamic 
 dynamic-cookie-key "Ingress" 
 server srv001 10.12.15.129:80 weight 1 maxconn 500 maxqueue 50 check inter 2s 
 server srv002 10.12.15.165:80 weight 1 maxconn 500 maxqueue 50 check inter 2s 

2. create one h2 connection with multiple http requests with different x-test header without cookies
3. Most responses will not have Set-Cookie 

### What is your configuration?

```haproxy
https://haproxy-ingress.github.io/
v 0.13
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.3.19-0647791 2022/03/14 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.19.html
Running on: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=12).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.3.1 20211027

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment]
Please check your logs, I bet that you're using the same client and it learns the first cookies seen, then reuses that cookie for all subsequent requests. Your config rightfully has the "indirect" keyword which means that cookies will only be delivered in response to requests that didn't have one, that's why I'm pretty sure that your client is learning them. In the logs you should see "NI--" for all requests with no cookie leading to a cookie insertion in response, and "VN" for requests with a valid cookie leading to no cookie insertion in response. Of course, as soon as your client learns the cookie, the same server will be used for all subsequent requests.

**Comment by capflam** [comment]
The issue seems to be inactive, I'm closing.
