### ISSUE TITLE
Haproxy logs 200 status code but real response is error code

### ISSUE THREAD

**Issue by max-frai** [haproxy/haproxy#2311]
### Detailed Description of the Problem

```
global
    lua-load /etc/haproxy/notify.lua

defaults
    log global
    mode http

frontend http-in
    option httplog
    bind *:80
    timeout client 30s
    default_backend proxies

backend proxies
    timeout connect 5s
    timeout server 30s
    balance roundrobin

    http-after-response lua.notify

    server node-0 node-0:8080 check
    server node-1 node-1:8080 check
```

I have this simple HAProxy (2.8). Now I open with proxy my custom page where nginx returns 403 error code. So in Postman I see this 403 error code.

But in haproxy log I see:

172.19.0.1:42278 [10/Oct/2023:10:16:07.990] http-in proxies/node-0 0/0/1/47/381 **200** 5878 - - ---- 1/1/0/0/0 0/0 "CONNECT ****.io:443 HTTP/1.1"

So it logs status code 200. Also when I try to get this status code in lua script, it gives me 200:

`local status_code = tonumber(txn.f:status())`

Why it's 200? How to get real returned status code from server and not from my backend.

### Expected Behavior

Status code should be 403

### Steps to Reproduce the Behavior

See my config

### What is your configuration?

```haproxy
Ubuntu
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.3-1~bpo12+1 2023/09/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.3.html
Running on: Linux 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_OT=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL +OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=5).
Built with OpenSSL version : OpenSSL 3.0.9 30 May 2023
Running on OpenSSL version : OpenSSL 3.0.9 30 May 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [  OT] opentracing
        [SPOE] spoe
        [TRACE] trace
```

**Comment by Darlelet** [comment]
Hello,

You seem to be relying on the "tunnel" mode from haproxy, here is what the documentation states about this mode:
```
HAProxy supports 4 connection modes :
  - keep alive    : all requests and responses are processed (default)
  - tunnel        : only the first request and response are processed,
                    everything else is forwarded with no analysis (deprecated).
  - server close  : the server-facing connection is closed after the response.
  - close         : the connection is actively closed after end of response.
 ```

The logged request seems to be the first `CONNECT` instruction which seems to be successful, thus nginx returns 200 response and haproxy logs it, but it seems that subsequent requests in the tunnel, including the one which ends up returning the 403 response are simply forwarded and not processed by haproxy anymore.

Is HTTP tunneling required/expected in your setup?

**Comment by max-frai** [comment]
@Darlelet Hello, thank you for the response. It's strange because I didn't change it to tunnel and in your quote the default mode is keep alive. Maybe the problem is in my backend logic? But if postman shows correct page code, backend logic should work correctly.

**Comment by Darlelet** [comment]
haproxy automatically switches to the tunnel mode when `CONNECT` method is encountered in an HTTP request, thus in this case haproxy behaves as expected since it logs the status of the `CONNECT` request but not subsequent exchanges within the tunnel.

This also means that the backend server you're using (nginx ?) has been configured to support HTTP tunneling, which is often disabled by default, so you must be sure that this was intentional.
HTTP tunneling is often found in older setups to allow clients to indirectly connect to SSL endpoints through an intermediate proxy.

If you don't expect haproxy to allow this kind of requests to pass through (which makes haproxy blind in some ways once the tunnel is established), then you could check the `METH_CONNECT` acl to handle this case specifically within your frontend rules, just like you would normally do for other "special" HTTP methods such as `DELETE`, `OPTIONS`..

Note that haproxy may also be configured as an SSL endpoint, and supports both client-side and server-side SSL.

**Comment by max-frai** [comment]
On backends I use this: https://github.com/xnuter/http-tunnel
It states as "An implementation HTTP Tunnel of in Rust, which can also function as a TCP proxy."

From haproxy I needed load balancing between a few backend which just directs traffic to a few physical servers. So everything worked great until I needed to catch http errors. Do I understand correctly, when I use tunnel with http connect I'm not able to see response status because it's returned directly to caller (Postman in my case where I run the request).

So advice me, please, what's better to do. Replace my "proxy" implementation and use something without tunneling? Or I can handle tunnel manually with haproxy? 

I'm a bit new to this subject, maybe you can forward me in some direction or examples. Thank you

**Comment by capflam** [comment]
From the moment an HTTP tunnel is established, everything that is exchanged between the client and the server are raw data not HTTP data. You can see the connection as a simple TCP connection at this stage.

**Comment by max-frai** [comment]
@capflam So I should change my backend library to work not as tunnel, correct? Maybe you know some good library so I just run it on server and use as backend for haproxy ?

**Comment by lukastribus** [comment]
Please use the mailing list or discourse forum for generic support issues.

Yes, you should not use a tunnel if you need normal HTTP forwarding.
