### ISSUE TITLE
Client Authentication works with LibreSSL but doesn't work with WolfSSL

### ISSUE THREAD

**Issue by vifino** [haproxy/haproxy#2320]
### Detailed Description of the Problem

I love HAProxy.

I've been trying different SSL implementations (and making them easily selectable in NixOS) mostly to get QUIC working and it seems that with WolfSSL Client Certificate auth is broken.

Instead of accepting the Certificate, I get a `ERR_BAD_SSL_CLIENT_AUTH_CERT` back, even though the certificate is valid.

### Expected Behavior

The Client's Certificate's CN gets accepted and validated against `trusted_users.txt`.

### Steps to Reproduce the Behavior

1. Compile HAProxy with WolfSSL
2. Generate required Certificates for HTTPS, Root/Intermediary and Client.
3. Run (modified) example config.
4. Test with Chrome having the Client Certificate loaded

### Do you have any idea what may have caused this?

I'm guessing it is either WolfSSL, the compat layer or how it's used in HAProxy.

With LibreSSL, this did not happen.

### What is your configuration?

```haproxy
frontend fe_https
  bind 1.2.3.4:443 ssl strict-sni crt /path/to/server.pem verify optional ca-file /path/to/clientroot.pem alpn h2,http1/1

  # Broken because of a different issue? Doesn't seem to do certificate auth at all, even with QuicTLS/LibreSSL.
  #bind quic4@1.2.3.4:443 ssl strict-sni crt /path/to/server.pem verify optional ca-file /path/to/clientroot.pem alpn h3
  #http-after-response set-header alt-svc 'h3=":443"; quic=":443"; ma=60'

  acl is_trusted ssl_c_s_dn(CN) -m str -f /etc/haproxy/trusted_users.txt
  use_backend be_trusted if is_trusted

  default_backend be_untrusted
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.3-86e043a 2023/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.3.html
Running on: Linux 6.1.58 #1-NixOS SMP PREEMPT_DYNAMIC Sun Oct 15 16:32:41 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_OPENSSL_WOLFSSL=1 USE_LUA=yes USE_ZLIB=1 USE_SYSTEMD=yes USE_QUIC=1 USE_PCRE2=yes USE_PCRE2_JIT=yes
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL +OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION +QUIC +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : wolfSSL 5.6.3
Running on OpenSSL version : wolfSSL 5.6.3
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.6
Built with network namespace support.
Built with zlib version : 1.3
Running on zlib version : 1.3
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : none

Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

Both HAProxy and WolfSSL are packaged/built under NixOS.

WolfSSL was configured with:
 ```
        "--enable-reproducible-build"
        "--enable-haproxy"
        "--enable-quic"
        "--enable-intelasm"
        "--enable-aesni"
        "--enable-bigcache"
        "--enable-sp=yes,asm"
        "--enable-sp-math-all"
        "--enable-harden"
```

In addition, `-DHAVE_SSL_CTX_SET_CIPHERSUITES -DHAVE_ASN1_TIME_TO_TM` was added to CFLAGS of HAProxy as d75bc06bdc8585112b4c9b231e0a42de4065de96 doing the same was not in the packaged version.

The certificates client root and intermediate are SHA256 RSA 4096  certs.
The Client cert is only 2048 bit.

**Comment by wlallemand** [comment]
WolfSSL is not completely supported yet,

**Comment by wlallemand** [comment]
Hi @vifino,

WolfSSL is not completely supported yet, some issues were fixed in WolfSSL thought, and the fixes are not yet in a released version. I suggest that you test with the latest git commit first.

We successfully tested the client authentication with HAProxy 2.9-dev8 and the WolfSSL from the master branch d83f2fa.

There is a reg-test which is available in `reg-tests/ssl/ssl_client_auth.vtc` which is passing currently.  You can try to launch it with: 
```
make reg-tests reg-tests/ssl/ssl_client_auth.vtc -- --debug
```
 but you need to install VTest first ( https://github.com/vtest/VTest ). If this work you could modify the configuration to use your certificates.

**Comment by vifino** [comment]
Hey @wlallemand!

Thank you so much for your answer!
I tried the latest Git Commit of WolfSSL and it does indeed work now!

Knowing that's the case, I'm guessing it's not a small commit I can apply from the 800+ since 5.6.3.
I suppose proposing WolfSSL as the default in NixOS won't happen until a the next release. 

Besides the now solved problem (thanks again!!), do you happen to know anything about Client Certificate Auth with QUIC?
It doesn't seem to work with any implementation I tried, at least not in Chrome.
Should I make a new issue?

**Comment by wlallemand** [comment]
@vifino please create a new issue so the right people could help you.

**Comment by vifino** [comment]
I will, thank you!
