### ISSUE TITLE
Client Certificate Authentication does not work with QUIC

### ISSUE THREAD

**Issue by vifino** [haproxy/haproxy#2322]
### Detailed Description of the Problem

When configuring a QUIC/H3 listener with Client Certificate Authentication, authentication does not work.

With `verify optional` in the provided example, the first requests are properly authenticated H2 requests and get correctly passed to `be_trusted`.
After the Browser (Chrome) switches to QUIC/H3, `be_untrusted` is always used. 

When switching the QUIC/H3 listener to `verify required`, no QUIC/H3 request are successfully used to deliver the site, with the browser falling back to H2.

### Expected Behavior

QUIC/H3 requests behaves the same as the regular H2/HTTP1.1 requests.
The client is authenticated and hits `be_trusted`.

### Steps to Reproduce the Behavior

1. Generate required Certificates for HTTPS, Root/Intermediary and Client.
2. Add `CN` of Client Certificate to `trusted_users.txt`.
3. Run the (modified) example config.
4. Use Chrome with DevTools open to open the Site.
5. Refresh a few times to see H2 switch to H3.
6. After H3 upgrade, watch requests hit other backend.

### What is your configuration?

```haproxy
frontend fe_https
  bind 1.2.3.4:443 ssl strict-sni crt /path/to/server.pem verify optional ca-file /path/to/clientroot.pem alpn h2,http/1.1
  bind quic4@1.2.3.4:443 ssl strict-sni crt /path/to/server.pem verify optional ca-file /path/to/clientroot.pem alpn h3

  http-after-response set-header alt-svc 'h3=":443"; quic=":443"; ma=60'

  acl is_trusted ssl_c_s_dn(CN) -m str -f /etc/haproxy/trusted_users.txt
  use_backend be_trusted if is_trusted

  default_backend be_untrusted
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.3-86e043a 2023/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.3.html
Running on: Linux 6.1.58 #1-NixOS SMP PREEMPT_DYNAMIC Sun Oct 15 16:32:41 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_OPENSSL_WOLFSSL=1 USE_LUA=yes USE_ZLIB=1 USE_SYSTEMD=yes USE_QUIC=1 USE_PCRE2=yes USE_PCRE2_JIT=yes
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL +OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION +QUIC +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : wolfSSL 5.6.3
Running on OpenSSL version : wolfSSL 5.6.3
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.6
Built with network namespace support.
Built with zlib version : 1.3
Running on zlib version : 1.3
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : none

Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace

```

### Additional Information

The certificates client root and intermediate are SHA256 RSA 4096 certs.
The Client cert is only 2048 bit.

This takes place with all the QUIC implementations I tried: LibreSSL, QuicTLS and WolfSSL.
The WolfSSL in the version output is compiled from todays Git, [`1de048826e43e634e59a756a65535d657a2047a4`.](https://github.com/wolfSSL/wolfssl/commit/1de048826e43e634e59a756a65535d657a2047a4)

**Comment by haproxyFred** [comment]
I am not sure that all the TLS features are supported by WolfSSL QUIC stack. Perhaps you could give a try to quictls or build haproxy against OpenSSL with USE_QUIC_OPENSSL_COMPAT. In this latter case, have a look to "limited-quic" configuration keyword.

**Comment by haproxyFred** [comment]
Another test could be to check that the authentication works without QUIC (TCP).

**Comment by haproxyFred** [comment]
that said, as I have been told by @wlallemand we have regression tests which demonstrate that the client authentication works with WolfSSL. Will try to reproduce this issue asap.

**Comment by chipitsine** [comment]
I'm afraid that regression tests check only h2.

**Comment by haproxyFred** [comment]
I should have written : that said, as I have been told by @wlallemand we have regression tests which demonstrate that the client authentication works with WolfSSL (TCP).

**Comment by vifino** [comment]
Thanks for your swift replies!

> I am not sure that all the TLS features are supported by WolfSSL QUIC stack. Perhaps you could give a try to quictls or build haproxy against OpenSSL with USE_QUIC_OPENSSL_COMPAT. In this latter case, have a look to "limited-quic" configuration keyword.

I tried LibreSSL 3.7.3, QuicTLS 3.1.2-quic1 and WolfSSL nightly, all of which don't seem to support QUIC with cert auth.
So I think this might be a HAProxy patch that is required (or patches to all three if they end up being the broken pieces...)

> Another test could be to check that the authentication works without QUIC (TCP).

It does with all three implementations, WolfSSL requiring the nightly instead of the latest release (5.6.3) which I found out thanks to @wlallemand in #2320.

I am using that nightly WolfSSL here, but I can switch to QuicTLS or LibreSSL again to test patches.

Thank you!

**Comment by haproxyFred** [comment]
I have checked  that the client authentication works with curl which can connect directly to the QUIC listener with such a haproxy conf. It is correctly redirected to "be_trusted" backend:

```
global
    tune.ssl.default-dh-param 2048

defaults
    mode http
    option httplog
    log stderr local0 debug err
    option logasap
    timeout connect 5s
    timeout client 5s
    timeout server 5s

backend be_trusted
    server s1 127.0.0.1:80

backend be_untrusted
    server s2 127.0.0.1:80

listen ssl-lst
    # TCP
    #bind 127.0.0.1:4443 alpn h2 ssl crt reg-tests/ssl/common.pem ca-file reg-tests/ssl/ca-auth.crt verify optional crt-ignore-err X509_V_ERR_CERT_REVOKED,X509_V_ERR_CERT_HAS_EXPIRED crl-file reg-tests/ssl/crl-auth.pem
    
    #QUIC
    bind quic4@127.0.0.1:4443 alpn h3 ssl crt reg-tests/ssl/common.pem ca-file reg-tests/ssl/ca-auth.crt verify optional crt-ignore-err X509_V_ERR_CERT_REVOKED,X509_V_ERR_CERT_HAS_EXPIRED crl-file reg-tests/ssl/crl-auth.pem
    http-response add-header X-SSL %[ssl_c_verify,x509_v_err_str]

    acl is_trusted ssl_c_s_dn(CN) -m str -f trusted_users.txt
    use_backend be_trusted if is_trusted
    default_backend be_untrusted
```
I do not know what a browser like Chrome does when it switches to h3. Does it resend its certificate?

**Comment by vifino** [comment]
Hey @haproxyFred, thank you for your testing!

It took me a while to actually test it with curl as I don't have direct access to any of the certificates used there.

I built a test setup, but QUIC didn't want to work at all.
Turns out if you don't set a client timeout, QUIC doesn't work.
After setting them, QUIC works just fine.

Yes, HAProxy properly does Cert Auth with curl and `--http3-only`!
So again this is not a fault of HAProxy, but rather rather Chrome not sending the certificate.

I dug around in their Issue tracker and yep: It's Chrome's fault!
https://bugs.chromium.org/p/chromium/issues/detail?id=1396207
I'll try to bump this and hope it eventually gets fixed in Chrome.
Guess no H3 for the foreseeable future. :(

Sorry to waste your time like this!
I love HAProxy and it is doing a lovely job.

BTW: Is there a regression test in HAProxy for QUIC? Might be nice to have.

**Comment by wlallemand** [comment]
@vifino Unfortunately we don't have regressions tests for QUIC, because the regression tests uses haproxy as an SSL client as well as an SSL server. And we don't have the client part yet. However we discussed several times to add reg-tests with an external client but we didn't explore the solution yet!

**Comment by haproxyFred** [comment]
Thank you for this information. About the regression test suite, unfortunately there is no test for QUIC. To do so, we could only proceed as this is done for the TCP/TLS tests (reg-test/ssl/*.vtc): chaining two listeners, the first one (clear mode) would have servers which would connect to the second listener (which is a QUIC listener). This is what we do not support at this time in our QUIC stack: QUIC clients (or haproxy QUIC servers).

**Comment by a-denoyelle** [comment]
@vifino interesting coincidence I just discovered by accident that QUIC is not behaving as expected if no timeout client is set. A fix should be merged soon. However, I suggest you to try to always set timeouts for connect/client/server as we consider that haproxy behavior may be unexpected without them.

**Comment by vifino** [comment]
@a-denoyelle Yeah, when I figured out that the missing timeout caused my QUIC failures in my test setup, I was quite frustrated.

Glad to know it's getting fixed though!
Thanks!
