### ISSUE TITLE
haproxy service restarting intermittently with message --> systemd[1]: Stopped SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments

### ISSUE THREAD

**Issue by kishoreuppala** [haproxy/haproxy#2333]
Greetings Team!

### We have noticed haproxy service is intermittently restarting on Prod VMs. Please find the below logs.
Could you kindly help us why it is getting restarted automatically?

Oct 13 03:52:31 hostname1 haproxy[22439]: [WARNING]  (22449) : config : log format ignored for proxy 'replicas' since it has no log address.
Oct 13 03:52:31 hostname1 haproxy[22439]: [  OK  ]
Oct 13 03:52:31 hostname1 systemd[1]: Started SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..

<hr> 
Oct 13 04:46:42 hostname1 systemd[1]: Stopping SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Oct 13 04:46:42 hostname1 haproxy[11618]: Shutting down haproxy: [  OK  ]
Oct 13 04:46:42 hostname1 systemd[1]: Stopped SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments.. 
<hr>
Oct 13 04:46:42 hostname1 systemd[1]: Starting SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Oct 13 04:46:42 hostname1 haproxy[11628]: Starting haproxy: [NOTICE]   (11638) : haproxy version is 2.5.0-f2e0833
Oct 13 04:46:42 hostname1 haproxy[11628]: [NOTICE]   (11638) : path to executable is /usr/sbin/haproxy
Oct 13 04:46:42 hostname1 haproxy[11628]: [WARNING]  (11638) : config : log format ignored for proxy 'master' since it has no log address.
Oct 13 04:46:42 hostname1 haproxy[11628]: [WARNING]  (11638) : config : log format ignored for proxy 'replicas' since it has no log address.
Oct 13 04:46:42 hostname1 haproxy[11628]: [  OK  ]
Oct 13 04:46:42 hostname1 systemd[1]: Started SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..

-----------------####-----------------
Oct 31 21:16:11 hostname1 systemd[1]: Stopping SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Oct 31 21:16:11 hostname1 haproxy[19279]: Shutting down haproxy: [  OK  ]
Oct 31 21:16:11 hostname1 systemd[1]: Stopped SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..
-----------------####-----------------

Oct 31 21:16:11 hostname1 systemd[1]: Starting SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Oct 31 21:16:11 hostname1 haproxy[19291]: Starting haproxy: [NOTICE]   (19301) : haproxy version is 2.5.0-f2e0833
Oct 31 21:16:11 hostname1 haproxy[19291]: [NOTICE]   (19301) : path to executable is /usr/sbin/haproxy
Oct 31 21:16:11 hostname1 haproxy[19291]: [WARNING]  (19301) : config : log format ignored for proxy 'master' since it has no log address.
Oct 31 21:16:11 hostname1 haproxy[19291]: [WARNING]  (19301) : config : log format ignored for proxy 'replicas' since it has no log address.
Oct 31 21:16:11 hostname1 haproxy[19291]: [  OK  ]
Oct 31 21:16:11 hostname1 systemd[1]: Started SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..
Oct 31 21:16:23 hostname1 systemd[1]: Stopping SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Oct 31 21:16:23 hostname1 haproxy[19465]: Shutting down haproxy: [  OK  ]
Oct 31 21:16:23 hostname1 systemd[1]: Stopped SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..
Oct 31 21:16:23 hostname1 systemd[1]: Starting SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Oct 31 21:16:23 hostname1 haproxy[19476]: Starting haproxy: [NOTICE]   (19486) : haproxy version is 2.5.0-f2e0833
Oct 31 21:16:23 hostname1 haproxy[19476]: [NOTICE]   (19486) : path to executable is /usr/sbin/haproxy
Oct 31 21:16:23 hostname1 haproxy[19476]: [WARNING]  (19486) : config : log format ignored for proxy 'master' since it has no log address.
Oct 31 21:16:23 hostname1 haproxy[19476]: [WARNING]  (19486) : config : log format ignored for proxy 'replicas' since it has no log address.
Oct 31 21:16:23 hostname1 haproxy[19476]: [  OK  ]
Oct 31 21:16:23 hostname1 systemd[1]: Started SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..
Nov 01 20:19:47 hostname1 systemd[1]: Stopping SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Nov 01 20:19:47 hostname1 haproxy[14198]: Shutting down haproxy: [  OK  ]
Nov 01 20:19:47 hostname1 systemd[1]: Stopped SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..
Nov 01 20:19:47 hostname1 systemd[1]: Starting SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Nov 01 20:19:47 hostname1 haproxy[14211]: Starting haproxy: [NOTICE]   (14220) : haproxy version is 2.5.0-f2e0833
Nov 01 20:19:47 hostname1 haproxy[14211]: [NOTICE]   (14220) : path to executable is /usr/sbin/haproxy
Nov 01 20:19:47 hostname1 haproxy[14211]: [WARNING]  (14220) : config : log format ignored for proxy 'master' since it has no log address.
Nov 01 20:19:47 hostname1 haproxy[14211]: [WARNING]  (14220) : config : log format ignored for proxy 'replicas' since it has no log address.
Nov 01 20:19:47 hostname1 haproxy[14211]: [  OK  ]
Nov 01 20:19:47 hostname1 systemd[1]: Started SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..

-----------------####-----------------
Nov 01 20:19:55 hostname1 systemd[1]: Stopping SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Nov 01 20:19:55 hostname1 haproxy[14288]: Shutting down haproxy: [  OK  ]
Nov 01 20:19:55 hostname1 systemd[1]: Stopped SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..
-----------------####-----------------

Nov 01 20:19:55 hostname1 systemd[1]: Starting SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments....
Nov 01 20:19:55 hostname1 haproxy[14297]: Starting haproxy: [NOTICE]   (14306) : haproxy version is 2.5.0-f2e0833
Nov 01 20:19:55 hostname1 haproxy[14297]: [NOTICE]   (14306) : path to executable is /usr/sbin/haproxy
Nov 01 20:19:55 hostname1 haproxy[14297]: [WARNING]  (14306) : config : log format ignored for proxy 'master' since it has no log address.
Nov 01 20:19:55 hostname1 haproxy[14297]: [WARNING]  (14306) : config : log format ignored for proxy 'replicas' since it has no log address.
Nov 01 20:19:55 hostname1 haproxy[14297]: [  OK  ]
Nov 01 20:19:55 hostname1 systemd[1]: Started SYSV: HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments..

### Haproxy version:

> haproxy -v
> HAProxy version 2.5.0-f2e0833 2021/11/23 - https://haproxy.org/
> Status: stable branch - will stop receiving fixes around Q1 2023.
> Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
> Running on: Linux 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64

### HAProxy Config file: 

> global
>     maxconn 100000
>     user haproxy
>     group haproxy
> 
> defaults
>     mode               tcp
>     log                global
>     retries            2
>     timeout queue      5s
>     timeout connect    5s
>     timeout client     60m
>     timeout server     60m
>     timeout check      15s
> 
> listen stats
>     mode http
>     bind 192.168.0.100:7000
>     stats enable
>     stats uri /
> 
> listen master
>     bind *:5000
>     maxconn 10000
>     option tcplog
>     option httpchk OPTIONS /master
>     http-check expect status 200
>     default-server inter 3s fastinter 1s fall 3 rise 4 on-marked-down shutdown-sessions
>  
>  server 192.168.0.100 192.168.0.100:5432 check port 8008
>  server 192.168.0.101 192.168.0.101:5432 check port 8008
>  
> listen replicas
>     bind *:5005
>     maxconn 10000
>     option tcplog
>     option httpchk OPTIONS /replica
>     balance roundrobin
>     http-check expect status 200
>     default-server inter 3s fastinter 1s fall 3 rise 2 on-marked-down shutdown-sessions
>   
>  server 192.168.0.100 192.168.0.100:5432 check port 8008
>  server 192.168.0.101 192.168.0.101:5432 check port 8008

--## Above listed IPs are masked due to security concern ##--

**Comment by wlallemand** [comment]
This is not a bug in haproxy. you have something on your system that is restarting haproxy.
Please use the discourse https://discourse.haproxy.org/ or the mailing-list https://www.haproxy.org/#tact to ask for help.
Github is dedicated to bugs and features requests for haproxy!

Thanks,

**Comment by kishoreuppala** [comment]
In my scenario, this behavior is due to the template rendering utility consul-template, which is doing these restarts whenever it finds any config changes as per the code.

There is no issue/bug from the HAPxory end.

Thank you @wlallemand  and Team for your response.
