### ISSUE TITLE
Logging issue when capturing POST payloads to logs

### ISSUE THREAD

**Issue by dragosrp** [haproxy/haproxy#2336]
### Detailed Description of the Problem

This logging configuration produces more log entries with garbled data from body content besides the correct log entry:
global
   log 127.0.0.1  len 32000   local0
   log /dev/log  len 32000   local1 notice

   tune.http.logurilen 20480

   chroot /var/lib/haproxy
   stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
   stats timeout 30s
   user haproxy
   group haproxy
   daemon
   maxconn 500000
   tune.ssl.cachesize 500000
   tune.ssl.capture-buffer-size 800

   ssl-default-bind-options ssl-min-ver TLSv1.2
   ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
   ssl-default-bind-options prefer-client-ciphers ssl-min-ver TLSv1.2 no-tls-tickets
   ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
   ssl-default-server-options no-tls-tickets ssl-min-ver TLSv1.2

defaults
   log     global
   mode    http
   option  dontlognull
   timeout connect 5000
   timeout client  50000
   timeout server  50000
   errorfile 400 /etc/haproxy/errors/400.http
   errorfile 403 /etc/haproxy/errors/403.http
   errorfile 408 /etc/haproxy/errors/408.http
   errorfile 500 /etc/haproxy/errors/500.http
   errorfile 502 /etc/haproxy/errors/502.http
   errorfile 503 /etc/haproxy/errors/503.http
   errorfile 504 /etc/haproxy/errors/504.http
   timeout http-request 30s
   option http-buffer-request

 log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %[fc_err]/%[ssl_fc_err,hex]/%[ssl_c_err]/\%[ssl_c_ca_err]/%[ssl_fc_is_resumed] %[ssl_fc_sni]/%sslv/%sslc FUll URL: %HU Body: %{+Q}[capture.req.hdr(0)]"

frontend https-in
   bind *:443 ssl crt /certs/ alpn h2,http/1.1
   bind [::]:443 ssl crt /certs/ alpn h2,http/1.1

   # Capture payload in logs
   declare capture request len 5000
   http-request capture req.body id 0

   mode http
   log 127.0.0.1 local0 info
...

Note: I enabled 32k logs in rsyslog.

Excuse my boring long URL, I am not sure if its happening with shorter ones but here its one that's causing this behavior:
This URL: https://a.b.com/kdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadf

with POST body:
{"user_id": 12345, "name": "John Doetest11", "email": "johndoe@example.com", "roles": ["admin", "user"], "active": true}

Produces logs of this nature:
Nov  8 17:22:27 localhost haproxy[2775558]: 139.59.147.204:55714 [08/Nov/2023:17:22:27.149] https-in~ something/somethingelse1-5 0/0/1/11/12 404 192 - - ---- 17/17/0/0/0 0/0 {#7B#22user_id#22: 12345, #22name#22: #22John Doetest11#22, #22
email#22: #22johndoe@example.com#22, #22roles#22: [#22admin#22, #22user#22], #22active#22: true#7D#0A|a.b.com} "POST /kdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdka
sjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasf
hjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfh
jkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfad
fkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhsl
fkasjfhkjsfadf HTTP/1.1" 0/0000000000000000/0/\0/0 a.b.com/TLSv1.3/TLS_AES_256_GCM_SHA384 FUll URL: /kdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhk
jsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhf
ldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjad
hfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjksh
fdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadf Body: "{"user_id": 12345, "name": "John Doetest11", "email": "johndoe@example.com", "roles": ["admin", "user"], "active": true}#012"
Nov  8 17:22:27 localhost haproxy[2775558]: 139.59.147.204:55714 [08/Nov/2023:17:22:27.149] https-in~ something/somethingleseT1-5 0/0/1/11/12 404 192 - - ---- 17/17/0/0/0 0/0 {#7B#22user_id#22: 12345, #22name#22: #22John Doetest11#22, #22
email#22: #22johndoe@example.com#22, #22roles#22: [#22admin#22, #22user#22], #22active#22: true#7D#0A|a.b.com} "POST /kdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdka
sjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasf
hjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfh
jkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhk

See the issue? At least %{+Q}r is overwritten completely, not to mention the other text transforms.

### Expected Behavior

Correct logs entries, without:
1. overwritten variables
2. multiple log entries for same request
3. Not garbled/transformed data with #

### Steps to Reproduce the Behavior

1. Use my haproxy configuration and configure rsylog to accept up to 32k logs and $ActionFileDefaultTemplate RSYSLOG_SyslogProtocol23Format
2. Use this POST payload: {"user_id": 12345, "name": "John Doetest11", "email": "johndoe@example.com", "roles": ["admin", "user"], "active": true}
3. Use this URL:
https://a.b.com/kdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadfkdjhfjkasdfhjkshfdkfkjasfhjadhfklhkdkasjhfldhslfkasjfhkjsfadf

### Do you have an idea how to solve the issue?

No. What is even weird is that if I put
declare capture request len 100
http-request capture req.body id 0

after
mode http
it stops logging the body content completely. In my example above its before and its producing the mentioned output. But this might be an unexpected behavior, I am not sure, I will focus only on the first bug here.

### What is your configuration?

```haproxy
global
   lua-load /a/a1.lua
   lua-load /a/a2.lua

   log 127.0.0.1  len 32000   local0
   log /dev/log  len 32000   local1 notice

   tune.http.logurilen 20480

   chroot /var/lib/haproxy
   stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
   stats timeout 30s
   user haproxy
   group haproxy
   daemon
   maxconn 500000
   tune.ssl.cachesize 1000000
   tune.ssl.capture-buffer-size 800

   ssl-default-bind-options ssl-min-ver TLSv1.2

   ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
   ssl-default-bind-options prefer-client-ciphers ssl-min-ver TLSv1.2 no-tls-tickets
   ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
   ssl-default-server-options no-tls-tickets ssl-min-ver TLSv1.2

defaults
   log     global
   mode    http
   option  dontlognull
   timeout connect 5000
   timeout client  50000
   timeout server  50000
   errorfile 400 /etc/haproxy/errors/400.http
   errorfile 403 /etc/haproxy/errors/403.http
   errorfile 408 /etc/haproxy/errors/408.http
   errorfile 500 /etc/haproxy/errors/500.http
   errorfile 502 /etc/haproxy/errors/502.http
   errorfile 503 /etc/haproxy/errors/503.http
   errorfile 504 /etc/haproxy/errors/504.http
   timeout http-request 30s
   option http-buffer-request
#   log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %[fc_err]/%[ssl_fc_err,hex]/%[ssl_c_err]/\%[ssl_c_ca_err]/%[ssl_fc_is_resumed] %[ssl_fc_sni]/%sslv/%sslc FUll URL: %HU"
   log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %[fc_err]/%[ssl_fc_err,hex]/%[ssl_c_err]/\%[ssl_c_ca_err]/%[ssl_fc_is_resumed] %[ssl_fc_sni]/%sslv/%sslc FUll URL: %HU Body: %{+Q}[capture.req.hdr(0)]"

backend per_ip_rates
stick-table type ipv6 size 1m expire 10m store http_req_rate(10s)

backend bma2_rate
stick-table type ip size 100k expire 30m store http_req_rate(30m)

frontend https-in

   bind *:443 ssl crt /certs/ alpn h2,http/1.1
   bind [::]:443 ssl crt /certs/ alpn h2,http/1.1

   # Capture payload in logs, use carefully!
   #option http-buffer-request
   declare capture request len 100
   http-request capture req.body id 0

   mode http
   log 127.0.0.1 local0 info

   maxconn 100000

   capture request header Host len 50

   stick-table type ipv6 size 1m expire 24h store gpc0_rate(72h)

   http-request track-sc0 src table per_ip_rates
   http-request deny deny_status 429 if { sc_http_req_rate(0) gt 1000000 }

   timeout tarpit 5s
   http-request tarpit if { sc_http_req_rate(0) gt 1000000 }

   http-request deny if { req.hdr(user-agent) -i -m sub phantomjs slimerjs }

   http-request silent-drop if { sc_http_req_rate(0) gt 1400000 }

   http-request track-sc0 src
   http-response sc-inc-gpc0(0) if { status 400 }
   http-response sc-inc-gpc0(0) if { status 404 }
...
backend aaa1
balance roundrobin
server server1     127.0.0.1:82 check weight 100

listen  stats
bind :1936
mode            http
log             global

maxconn 10

timeout client      100s
timeout server      100s
timeout connect     100s
timeout queue   100s

stats enable
stats hide-version
stats refresh 30s
stats show-node
stats auth admin:admin
stats uri  /haproxy?stats
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.15-446b02c 2023/08/09 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.15.html
Running on: Linux 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -QUIC +RT +SLZ -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
1. Last from haproxy-admin.log
<132>1 2023-11-08T17:29:11+00:00 localhost haproxy 2777260 - -  Proxy <HTTPCLIENT> stopped (cumulated conns: FE: 0, BE: 0).
<129>1 2023-11-08T17:29:13+00:00 localhost haproxy 2777283 - -  Server api/server1 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
<128>1 2023-11-08T17:29:13+00:00 localhost haproxy 2777283 - -  backend api has no server available!
2. There are no core dumps
```

### Additional Information

Ubuntu 22.04 with Ubuntu Pro Livepatch.
uname -a
Linux LB1 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Darlelet** [comment]
Hi @dragosrp,

>multiple log entries for same request

The reason why you're getting the same request logged twice is because your `https-in` frontend proxy is first inheriting from defaults proxy section which states:
```
   log     global
```

Which means it will produce logs according to your global configuration which states:
```
   log 127.0.0.1  len 32000   local0
   log /dev/log  len 32000   local1 notice
```

Then in your `https-in` frontend you manually stated:
```
   log 127.0.0.1 local0 info
```

What this means, is that for each request, 3 logs will be produced:
- the first one will be sent to 127.0.0.1:514 and will be truncated after 32000 bytes
- the second one will be sent to /dev/log and will be truncated after 32000 bytes
- the third one will be sent to 127.0.0.1:514 (probably duplicate) AND will be trunctated after 1024 bytes

I suspect the third one is not what you expected since you'll end up having a duplicate log which is truncated after 1024 bytes since `len` was not specified, so the log entry will obviously be incomplete given that your URL already is more than 1024 bytes long.

Now for the other issues I must check first, but it would be nice if you could try to better describe your issue (considering my first remark) and cleaning your issue description a bit because it's pretty hard to spot errors in such description.

Thanks!

**Comment by Darlelet** [comment]
>Not garbled/transformed data with #

These `#char` escapes come from the `%hr` format string which automatically encodes the capture (note that this is not the case with `%{+Q}[capture.req.hdr(0)]`). I don't think that this behavior could be configured, but I might be wrong:
https://github.com/haproxy/haproxy/blob/84d26bcf3fd74e153dea98ad7d612373ea5c30ae/src/log.c#L3173-L3175

-----
>overwritten variables

What do you mean by this, could you please be more specific? (With an example of what you expect vs what you're seeing)

**Comment by Darlelet** [comment]
Now for the last point (I hope I don't forget anything):

```
No. What is even weird is that if I put
declare capture request len 100
http-request capture req.body id 0

after
mode http
it stops logging the body content completely. In my example above its before and its producing the mentioned output. But this might be an unexpected behavior, I am not sure, I will focus only on the first bug here.
```
Your request body in itself is already more than 100 bytes long, so the expected behavior should be that haproxy truncates the body after capture slot length is reached, so there could be something wrong indeed.
However I can't seem to reproduce using your example (having an empty body when length is exceeded), at least on haproxy end the capture is simply truncated but not empty?

**Comment by dragosrp** [comment]
> > Not garbled/transformed data with #
> 
> These `#char` escapes come from the `%hr` format string which automatically encodes the capture (note that this is not the case with `%{+Q}[capture.req.hdr(0)]`). I don't think that this behavior could be configured, but I might be wrong:
> 
> https://github.com/haproxy/haproxy/blob/84d26bcf3fd74e153dea98ad7d612373ea5c30ae/src/log.c#L3173-L3175
> 
> > overwritten variables
> 
> What do you mean by this, could you please be more specific? (With an example of what you expect vs what you're seeing)

Instead of %{+Q}r there is the body encoded with #char escapes, see?
Nov 8 17:22:27 localhost haproxy[2775558]: 139.59.147.204:55714 [08/Nov/2023:17:22:27.149] https-in~ something/somethingelse1-5 0/0/1/11/12 404 192 - - ---- 17/17/0/0/0 0/0 {#7Bhttps://github.com/haproxy/haproxy/issues/22user_id#22: 12345, #22name#22: #22John Doetest11#22, #22.....

**Comment by dragosrp** [comment]
> Now for the last point (I hope I don't forget anything):
> 
> ```
> No. What is even weird is that if I put
> declare capture request len 100
> http-request capture req.body id 0
> 
> after
> mode http
> it stops logging the body content completely. In my example above its before and its producing the mentioned output. But this might be an unexpected behavior, I am not sure, I will focus only on the first bug here.
> ```
> 
> Your request body in itself is already more than 100 bytes long, so the expected behavior should be that haproxy truncates the body after capture slot length is reached, so there could be something wrong indeed. However I can't seem to reproduce using your example (having an empty body when length is exceeded), at least on haproxy end the capture is simply truncated but not empty?

After removing all additional logging and keeping only log 127.0.0.1 len 32000 local0 and removing %hr and %hs, this issue does not reproduce anymore.

Maybe the previous post "issue" is somehow expected with %hr and %hs to be # escaped?

**Comment by Darlelet** [comment]
> Instead of %{+Q}r there is the body encoded with #char escapes, see?
> Nov 8 17:22:27 localhost haproxy[2775558]: 139.59.147.204:55714 [08/Nov/2023:17:22:27.149] https-in~ something/somethingelse1-5 0/0/1/11/12 404 192 - - ---- 17/17/0/0/0 0/0 {#7Bhttps://github.com/haproxy/haproxy/issues/22user_idhttps://github.com/haproxy/haproxy/issues/22: 12345, #22name#22: #22John Doetest11#22, #22.....

So both `1. overwritten variables` and `3. Not garbled/transformed data with #` from your bullet list both refer to the same issue, right? (capture data being escaped with `#` chars)

In which case there doesn't seem to be a bug here: this is automatically produced by `%hr` format string in your log format.
If you don't expect that, I think you should drop the `%hr` and only keep the `%{+Q}[capture.req.hdr(0)]` to get raw output for the captured data.

> After removing all additional logging and keeping only log 127.0.0.1 len 32000 local0 and removing %hr and %hs, this issue does not reproduce anymore.
> 
> Maybe the previous post "issue" is somehow expected with %hr and %hs to be # escaped?

I'm not sure to properly understand you on that point, maybe you were previously hitting the 1024 bytes log truncation from your duplicate log directive (without `len` set) which resulted in incomplete log messages? Because both `%hs` and `%{+Q}[capture.req.hdr(0)]` should keep printing the captured data even if it was truncated due to lack of space in the capture slot.

**Comment by dragosrp** [comment]
> > Instead of %{+Q}r there is the body encoded with #char escapes, see?
> > Nov 8 17:22:27 localhost haproxy[2775558]: 139.59.147.204:55714 [08/Nov/2023:17:22:27.149] https-in~ something/somethingelse1-5 0/0/1/11/12 404 192 - - ---- 17/17/0/0/0 0/0 {#7Bhttps://github.com/haproxy/haproxy/issues/22user_idhttps://github.com/[/issues/22](https://github.com/haproxy/haproxy/issues/22): 12345, #22name#22: #22John Doetest11#22, #22.....
> 
> So both `1. overwritten variables` and `3. Not garbled/transformed data with #` from your bullet list both refer to the same issue, right? (capture data being escaped with `#` chars)
Yes.
> 
> In which case there doesn't seem to be a bug here: this is automatically produced by `%hr` format string in your log format. If you don't expect that, I think you should drop the `%hr` and only keep the `%{+Q}[capture.req.hdr(0)]` to get raw output for the captured data.
Ok.
> 
> > After removing all additional logging and keeping only log 127.0.0.1 len 32000 local0 and removing %hr and %hs, this issue does not reproduce anymore.
> > Maybe the previous post "issue" is somehow expected with %hr and %hs to be # escaped?
> 
> I'm not sure to properly understand you on that point, maybe you were previously hitting the 1024 bytes log truncation from your duplicate log directive (without `len` set) which resulted in incomplete log messages? Because both `%hs` and `%{+Q}[capture.req.hdr(0)]` should keep printing the captured data even if it was truncated due to lack of space in the capture slot.

Maybe.. for now it seems to be capturing data at full length specified without %HU and %hr or %hs.

**Comment by capflam** [comment]
What is the status of this issue ?

**Comment by capflam** [comment]
For now, I'm closing the issue because it seems inactive. If there is still an issue, feel free to reopen it with more info. Thanks.
