### ISSUE TITLE
haproxy not detecting disconnected client if entire request read immediately after accept

### ISSUE THREAD

**Issue by robmueller** [haproxy/haproxy#2340]
### Detailed Description of the Problem

I have an haproxy setup for local routing of http 1.1 (not https) requests. I noticed though that if the client connection is dropped, then haproxy did not detect this and would not close the corresponding backend connection.

After some strace work, I'm pretty sure problem is that if the entire request can be read in the `recvfrom()` call after the `accept()` completes (e.g. a fast client on localhost), then the fd is not added to the epoll set, so if the client drops the connection that's not detected. If the entire request is not receivable immediately however, then the fd will be added to the epoll set and any connection close will be detected.

Here's some example strace output of each case.

```
[pid 822991] 06:52:03.470596 <... accept4 resumed>{sa_family=AF_INET, sin_port=htons(46460), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_NONBLOCK) = 44
...
[pid 822993] 06:52:03.470986 setsockopt(44, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid 822993] 06:52:03.471021 recvfrom(44, "POST ./"..., 15360, 0, NULL, NULL) = 1529
[pid 822993] 06:52:03.471108 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 45
[pid 822993] 06:52:03.471139 fcntl(45, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
[pid 822993] 06:52:03.471187 setsockopt(45, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid 822993] 06:52:03.471214 connect(45, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("10.37.129.192")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid 822993] 06:52:03.471294 epoll_ctl(33, EPOLL_CTL_ADD, 45, {EPOLLIN|EPOLLOUT|EPOLLRDHUP, {u32=45, u64=45}}) = 0
[pid 822993] 06:52:03.471325 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=10306686}) = 0
[pid 822993] 06:52:03.471352 epoll_wait(33, [{EPOLLOUT, {u32=45, u64=45}}], 200, 5001) = 1
[pid 822993] 06:52:03.471381 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=10315317}) = 0
[pid 822993] 06:52:03.471408 recvfrom(45, 0x7fdd0c036e10, 15360, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 822993] 06:52:03.471445 sendto(45, "POST /"..., 1551, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 1551
[pid 822993] 06:52:03.473475 epoll_ctl(33, EPOLL_CTL_MOD, 45, {EPOLLIN|EPOLLRDHUP, {u32=45, u64=45}}) = 0
[pid 822993] 06:52:03.473587 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=10412206}) = 0
```

What we see here is we accept the new client connection on fd 44 and immediately do a `recvfrom()` call on it. That call actually has the entire http request in it. At that point haproxy opens a new backend connection on fd 45 and calls `sentto()` to forward the entire request.

We note that at no point does it add fd 44 to it's epoll set. If you close the client connection, it's not detected by haproxy at all. The backend request continues until it completes or a timeout occurs.

Now if we connect and delay sending the request even a bit...

```
[pid 822992] 06:57:55.341242 <... accept4 resumed>{sa_family=AF_INET, sin_port=htons(53782), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_NONBLOCK) = 40
...
[pid 822993] 06:57:55.341544 recvfrom(40,  <unfinished ...>
[pid 822993] 06:57:55.341610 <... recvfrom resumed>0x7fdd0c040110, 15360, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 822993] 06:57:55.341641 epoll_ctl(33, EPOLL_CTL_ADD, 40, {EPOLLIN|EPOLLRDHUP, {u32=40, u64=40}} <unfinished ...>
...
[pid 822993] 06:57:55.341785 epoll_wait(33, [{EPOLLIN, {u32=40, u64=40}}], 200, 60000) = 1
[pid 822993] 06:57:57.504681 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=11535309}) = 0
[pid 822993] 06:57:57.504752 recvfrom(40, "POST /", 15360, 0, NULL, NULL) = 45
[pid 822993] 06:57:57.504833 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=11574497}) = 0
[pid 822993] 06:57:57.504869 epoll_wait(33, [{EPOLLIN, {u32=40, u64=40}}], 200, 60000) = 1
[pid 822993] 06:57:57.545584 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=11600926}) = 0
[pid 822993] 06:57:57.545627 recvfrom(40, "......, 16275, 0, NULL, NULL) = 632
[pid 822993] 06:57:57.545698 setsockopt(40, SOL_TCP, TCP_QUICKACK, [1], 4) = 0
[pid 822993] 06:57:57.545736 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 45
[pid 822993] 06:57:57.545765 fcntl(45, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
[pid 822993] 06:57:57.545787 setsockopt(45, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid 822993] 06:57:57.545810 connect(45, {sa_family=AF_INET, sin_port=htons(8080), sin_addr=inet_addr("10.37.129.192")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid 822993] 06:57:57.545882 epoll_ctl(33, EPOLL_CTL_ADD, 45, {EPOLLIN|EPOLLOUT|EPOLLRDHUP, {u32=45, u64=45}}) = 0
[pid 822993] 06:57:57.545911 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=11718553}) = 0
[pid 822993] 06:57:57.545931 epoll_wait(33, [{EPOLLOUT, {u32=45, u64=45}}], 200, 5001) = 1
[pid 822993] 06:57:57.545956 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=11727319}) = 0
[pid 822993] 06:57:57.545978 recvfrom(45, 0x7fdd0c040110, 15360, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 822993] 06:57:57.546004 sendto(45, "POST/"..., 701, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 701
...
[pid 822993] 06:57:57.602783 epoll_wait(33, [{EPOLLIN|EPOLLRDHUP, {u32=40, u64=40}}], 200, 4944) = 1
[pid 822993] 06:57:59.651764 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=11886695}) = 0
[pid 822993] 06:57:59.651828 recvfrom(40, "", 16320, 0, NULL, NULL) = 0
...
[pid 822993] 06:57:59.652287 setsockopt(45, SOL_SOCKET, SO_LINGER, {l_onoff=1, l_linger=0}, 8) = 0
[pid 822993] 06:57:59.652331 close(45)  = 0
[pid 822993] 06:57:59.652394 close(40)  = 0
```

What we see here is we accept the new client connection on fd 40 and immediately do a `recvfrom()` call on it. However that call returns `EAGAIN`, so we immediately add fd 40 to the epoll set. At a later point, we read enough of the request to open a new backend connection on fd 45 and call `sentto()` to forward the request (well, actually several separate calls in this case, but elided because that's not what we're interested in here)

A few seconds later we close the client connection, and this is immediately detected as `epoll_wait()` returns that fd 40 is available for reading. haproxy tries to `recvfrom()` fd 40, gets 0 length (e.g. EOF condition), and then immediately closes both the backend connection (fd 45) and the client connection (fd 40).

### Expected Behavior

A client disconnect should always be detected and the corresponding backend connection closed, regardless of how fast/slow the client sending the request is.

### Steps to Reproduce the Behavior

1. Setup haproxy with any frontend/backend setup, http 1.0 or 1.1 is easiest
2. Have some backend that just sleeps and holds a request open for a while
3. Compare sending a request to haproxy very quickly vs slightly slowly

I found that generally using curl to request to localhost was "quick" (e.g. the first strace above). For the slow path, I'd just use socat + copy & paste the request, this always triggered the second path.

Really it appears the main issue is just if after an accept() returns a new fd, the next recvfrom() call returns an entire request or not.

### Do you have an idea how to solve the issue?

Even if haproxy can read the entire request immediately after accepting the connection, it should still be adding the fd to the epoll set so it can detect if the client drops the connection, and close the corresponding backend connection in that case.

### What is your configuration?

```haproxy
I first noticed this on a relatively old 2.0.30 version, but even upgrading to 2.8.3 the problem exists.
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.3-86e043a 2023/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.3.html
Running on: Linux 5.10.0-24-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_ZLIB=1 USE_PCRE=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by git001** [comment]
As you have not shared the config, do you have setuped any check for the backend?

**Comment by wtarreau** [comment]
You said in the first capture that the request was complete, then you said that the "_backend request continues until it completes or a timeout occurs_", but there's no trace of such a timeout there. I find this a bit confusing. Do you mean that when the server responded, the client's closure was not noticed and it caused a timeout ?

Regarding what you wrote in the expected behaviour: "_A client disconnect should always be detected and the corresponding backend connection closed, regardless of how fast/slow the client sending the request is_" there is an option to do exactly that, it's "option abortonclose". It does exactly what it says, i.e. it continues to actively try to read the client connection, and will either abort an ongoing connection, or if the request was already sent, will a shutdown to the server so that the server itself decides whether it wants to immediately close or continue.

It's not very clear to me why you think this is the expected behaviour, as doing this breaks some monitoring scripts and hand-crafted tools that build their requests themselves based on netcat/socat and so on.

**Comment by robmueller** [comment]
Ok I'm sorry.

I spent some time creating a minimal config and trying to reproduce this. I was completely wrong about what's happening here. I had jumped to a conclusion too early. Although there is a difference in whether the client fd is added to the epoll set depending on how quickly the request is read, it doesn't change how the client connection is handled.

In the end I discovered that the underlying problem I was detecting was actually something completely different related to `option abortonclose`. I'll close this issue.

**Comment by wtarreau** [comment]
Don't be sorry, and thanks for your honest feedback! It's always difficult to figure all the details of complex protocol handling like this, and it's always better to report what you think is an issue as you did, than leave it open and face problems in field later.
