### ISSUE TITLE
possible leak found by coverity scan

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#237]
** CID 1404569:  Resource leaks  (RESOURCE_LEAK)
/src/ring.c: 85 in ring_resize()

________________________________________________________________________________________________________

*** CID 1404569:  Resource leaks  (RESOURCE_LEAK)
/src/ring.c: 85 in ring_resize()
```
79      HA_RWLOCK_WRLOCK(LOGSRV_LOCK, &ring->lock);
80     
81      /* recheck the buffer's size, it may have changed during the malloc */
82      if (b_size(&ring->buf) < size) {
83              /* copy old contents */
84              b_getblk(&ring->buf, area, ring->buf.data, 0);
>>>     CID 1404569:  Resource leaks  (RESOURCE_LEAK)
>>>     Overwriting "area" in "area = __atomic_exchange_n (&ring->buf.area, 5, area)" leaks the storage that "area" points to.
85              area = HA_ATOMIC_XCHG(&ring->buf.area, area);
86              ring->buf.size = size;
87              ring->buf.head = 0;
88      }
89     
90      HA_RWLOCK_WRUNLOCK(LOGSRV_LOCK, &ring->lock);
```

**Comment by wtarreau** [comment]
No, coverity is (as usual) wrong here. The operation replaces buf.area with area and the previous buf.area is returned in area, which is freed later. On the opposite, this construct is designed to be 100% safe.
