### ISSUE TITLE
Can I get key name if map file matching 

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#2431]
### Your Feature Request

Currently, only matched "value" can be saved as variables, but is there a way to save the matched key as a variable when map matching.

**like key of get map** 
^/test/[^/]+/aaa
type=reg, case=sensitive, found=yes, idx=list, key="^/test/[^/]+/aaa", value="10", type="str"

### What are you trying to do?

I want to save matching key as variable and use it in various ways.

I can save matching key at logging file or use tracking key of stick-tables

example)
It would be nice to add a method to get the key value as below.
map_regk, map_key, map_begk 

example)
http-request set-var(txn.aclkey) path,map_regk(acl.map)
http-request deny deny_status 403 string "blocked reason: var(txn.aclkey)"

rate.map
/aaa/[^/]+/bbb 30
/ccc/[^/]+/bbb 30

http-request set-var(txn.key) path,map_regk(rates.map)
http-request set-var(txn.rate_limit) path,map_reg(rates.map)
http-request track-sc0 var(txn.key) table 

http-request set-var(txn.http_rate) sc_http_req_rate(0)
acl over_rate var(txn.ip_limit),sub(txn.http_rate) -m int le 0

I can sum count multiple path blow
/aaa/123/bbb
/aaa/222/bbb
/aaa/123123/bbb

### Output of `haproxy -vv`

```plain
it is not neccesary
```

**Comment by Darlelet** [comment]
This should already be addressed in 3.0 thanks to ca4758378788ee6a9b774590badbaa12d356e186 (See GH #1446)

**Comment by zino7825** [comment]
@Darlelet  Thanks for your sharing!
