### ISSUE TITLE
Self-signed cert causes OCSP error message

### ISSUE THREAD

**Issue by fraenki** [haproxy/haproxy#2432]
### Detailed Description of the Problem

When using an arbitrary self-signed certificate, HAProxy syntax check will fail:

```
$ /usr/local/sbin/haproxy -c -f /usr/local/etc/haproxy.conf.staging
[NOTICE]   (3554) : haproxy version is 2.8.5-aaba8d0
[NOTICE]   (3554) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (3554) : config : parsing [/usr/local/etc/haproxy.conf.staging:110] : 'bind localhost:8443' in section 'frontend' : 'crt-list' : error processing line 1 in file '/tmp/haproxy/ssl/588bc089e07b30.07907702.certlist' :  '/tmp/haproxy/ssl/65bac40f582f0.pem' has an OCSP URI and OCSP auto-update is set to 'on' but an error occurred (maybe the issuer could not be found)'.
[ALERT]    (3554) : config : Error(s) found in configuration file : /usr/local/etc/haproxy.conf.staging
[ALERT]    (3554) : config : Fatal errors found in configuration.
```

Note that I have `[ocsp-update on]` set for _all_ certificates, because HAProxy should use it when it's available:

```
$ cat /tmp/haproxy/ssl/588bc089e07b30.07907702.certlist
/tmp/haproxy/ssl/65bac40f582f0.pem [ocsp-update on]
/tmp/haproxy/ssl/61d6efdcc4738.pem [ocsp-update on]
/tmp/haproxy/ssl/61d6ecb905c1f.pem [ocsp-update on]
```

Note that HAProxy's error message clearly states:
```
'/tmp/haproxy/ssl/65bac40f582f0.pem' has an OCSP URI and OCSP auto-update is set to 'on' but an error occurred (maybe the issuer could not be found
```

However, this self-signed certificate does not have an OCSP URI configured:

```
$ openssl x509 -noout -ocsp_uri -in /tmp/haproxy/ssl/65bac40f582f0.pem
(no output)

$ openssl x509 -noout -text -in /tmp/haproxy/ssl/65bac40f582f0.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            20:19:15:86:6b:37:e6:c9:eb:ff:ab:bd:11:d4:c8:0e:cc:af:fe:a9
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = XX, ST = StateName, L = CityName, O = CompanyName, OU = CompanySectionName, CN = CommonNameOrHostname
        Validity
            Not Before: Jan 31 22:04:15 2024 GMT
            Not After : Mar  3 22:04:15 2025 GMT
        Subject: C = XX, ST = StateName, L = CityName, O = CompanyName, OU = CompanySectionName, CN = CommonNameOrHostname
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)
                Modulus:
                    00:ca:e2:ed:bd:a3:21:c7:5a:47:24:da:f3:24:ee:
                    54:5b:2c:a1:17:ed:07:f7:7e:74:8e:12:e8:e4:46:
                    44:cf:6b:67:d9:cc:01:7d:79:33:2b:dc:b1:34:b7:
                    be:7a:9a:d1:e5:8a:ad:c6:5a:85:0b:ea:2c:5c:c7:
                    4f:5f:e5:1b:f6:68:b5:e1:e5:d4:55:fd:7f:72:90:
                    77:be:70:df:1c:7d:27:9c:90:10:98:a7:b3:92:38:
                    8c:b8:44:ae:9c:fb:c1:c9:cb:fd:75:de:41:ac:90:
                    67:6f:ec:29:f3:02:16:f6:8f:96:fe:97:cc:87:e2:
                    31:d2:5d:bc:a6:c3:64:49:37:be:4f:21:91:f9:6f:
                    3c:a8:a7:b4:b8:4a:15:53:7b:ce:d6:62:22:c2:37:
                    7c:fb:07:0b:5a:80:5f:d9:f9:f6:4f:82:71:2a:9a:
                    d8:d9:82:cd:13:d4:e1:fd:a2:60:91:ce:fe:1e:4f:
                    9e:ec:19:40:57:57:49:ee:00:4b:e0:ce:65:15:c2:
                    e4:fd:66:c7:87:98:a3:f4:56:0c:bd:e0:f0:67:89:
                    a2:a4:bf:7d:c6:9a:f4:db:92:e1:80:8a:ef:21:5f:
                    71:08:f4:e1:c5:3c:0e:b7:78:d6:4e:7e:8b:1d:dd:
                    20:90:41:d0:4f:ba:b7:71:d7:15:7e:c4:7f:5c:12:
                    f7:68:a2:95:e6:35:24:cc:fa:89:d2:4d:21:66:a9:
                    2c:e5:ae:35:af:86:b2:98:60:cb:c3:2f:18:bf:cc:
                    70:db:6e:6a:43:eb:49:01:9e:a3:77:eb:8c:d3:a9:
                    a7:55:f9:6e:f6:b8:44:e9:cc:6e:d5:1c:a4:7c:4e:
                    a8:67:07:4c:d1:59:81:f0:4a:7d:12:b6:86:70:c0:
                    2f:8d:be:df:84:e0:73:66:43:b8:aa:4b:41:52:2b:
                    32:be:d8:9d:76:f9:f0:1e:7b:1d:03:2f:da:6d:73:
                    89:a4:c8:05:28:30:54:61:e6:a6:0a:90:d5:2a:b6:
                    a4:b3:ae:6c:7a:21:b2:e6:49:3e:83:44:3e:60:21:
                    30:29:5e:92:20:82:eb:6f:4b:ed:6d:3c:95:44:37:
                    4e:6f:02:de:0f:59:26:d2:7c:10:c3:4d:c8:3e:c7:
                    dc:52:25:c8:ca:a4:e3:bb:c9:6a:00:d3:48:3c:44:
                    3f:33:7e:7b:5b:f4:3f:5d:f2:f3:de:d7:5f:b7:47:
                    00:90:68:33:3e:00:81:6d:99:f3:1d:7b:71:5c:ab:
                    61:ce:73:61:fc:3f:7d:b3:9b:a8:3e:83:dd:a2:97:
                    00:79:e0:ed:d2:c8:27:f9:8f:b5:6e:42:04:d3:59:
                    af:90:84:a5:32:2f:ec:53:0a:53:5e:c1:be:94:4b:
                    93:37:89
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                61:6E:54:1B:C9:13:C5:B1:D6:22:68:15:D4:94:0F:BB:BD:F1:C1:7A
            X509v3 Authority Key Identifier: 
                keyid:61:6E:54:1B:C9:13:C5:B1:D6:22:68:15:D4:94:0F:BB:BD:F1:C1:7A

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         92:1f:ff:07:fd:ad:b1:a6:a2:7c:3d:2c:bd:a9:53:d7:4a:e5:
         35:49:30:6d:c3:48:1d:81:d6:1b:11:8e:33:82:f0:ac:6a:bd:
         df:01:37:e2:f6:37:87:72:33:9c:8f:42:0b:59:f5:00:e3:8c:
         22:b2:09:02:f1:52:e8:d8:01:53:ce:45:ee:81:43:6f:32:d9:
         71:92:a6:a2:fb:40:8a:ea:fe:3e:38:e0:36:e5:51:7b:56:f7:
         96:fa:7e:fc:46:07:8e:c1:f5:3d:29:49:83:c0:6f:63:43:12:
         26:d0:89:c8:80:66:33:2b:2d:8c:6f:52:c5:ad:2c:55:ff:0b:
         cf:32:c5:7f:e3:8c:7b:5a:c2:80:dc:a6:fe:1f:d2:b6:23:92:
         14:90:f5:01:23:c6:8a:b3:68:94:70:3d:be:a5:48:a3:0f:49:
         3b:f1:ee:a1:f7:30:87:93:b3:8c:ee:ad:49:4f:2b:98:d8:b0:
         61:51:98:dc:f9:72:ef:da:b1:f3:7b:f2:ee:4c:4e:ea:4e:34:
         bb:14:38:ce:1b:f2:c8:4d:df:ff:2d:44:7c:e3:a9:f4:d1:b9:
         47:6e:27:25:0d:4e:4c:94:c8:a2:dd:94:0f:8a:b8:2e:bc:03:
         58:8f:e2:d2:90:76:0b:43:c9:5a:13:60:6f:4c:b4:45:ed:67:
         51:57:93:fa:77:2e:75:38:4c:eb:7d:c4:39:dd:3c:28:c4:c1:
         eb:ba:c5:ad:0d:0a:6a:d3:aa:9d:27:a6:4c:e8:a7:d2:39:bc:
         fc:74:1a:46:55:d7:23:da:33:5f:9a:7b:70:b8:4e:82:68:89:
         9d:b1:e6:e5:b4:81:f6:56:1c:a7:60:78:45:c2:91:45:ae:cd:
         a8:d8:a2:af:45:fe:4f:c7:88:e7:ad:54:57:8d:ee:1d:48:67:
         8f:a1:dc:c5:f5:fc:29:2f:b2:b4:b1:f4:e0:a9:1f:62:96:43:
         d8:bd:a6:e7:b1:a1:ac:e9:8c:8b:28:9d:bf:de:88:35:5c:dc:
         9f:33:9e:66:b2:e6:f7:75:ac:73:42:56:be:1c:90:60:3e:2d:
         3c:af:0a:8e:6c:a9:44:30:46:d5:8c:71:8c:f6:69:ad:43:66:
         a2:7e:98:d9:86:41:7f:f7:26:96:85:c0:5b:f6:0e:09:54:a1:
         0f:b6:e9:42:d6:c4:27:a2:3b:da:f7:c8:da:54:17:3e:0c:10:
         e6:41:fa:6d:dd:db:10:51:7f:3e:75:53:92:9d:2b:62:7a:8b:
         27:46:e9:b0:9d:e3:5c:d6:0c:0c:76:f8:dd:2f:78:9f:e5:85:
         b4:7c:bd:2f:eb:98:6e:d2:68:36:86:84:ae:d3:9b:83:47:49:
         9f:98:e3:63:e6:62:d8:f5
```

### Expected Behavior

The self-signed certificate does not contain an OCSP URI, so HAProxy should not try to enable OCSP updates for this certificate. HAProxy should disable OCSP updates for this certificate.  I'd like to rely on HAProxy's ability to properly detect OCSP support in all provided certificates. :)

### Steps to Reproduce the Behavior

1. create a self-signed certificate like this: `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 397 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"`
2. add it to a cert-list and set `[ocsp-update on]` for this certificate
3. syntax check will fail: `...has an OCSP URI and OCSP auto-update is set to 'on' but an error occurred (maybe the issuer could not be found)`

### Do you have an idea how to solve the issue?

A _workaround_ would be to remove `[ocsp-update on]` from the self-signed certificate. However, this is pretty cumbersome in environments with a lot automation and many certificates.

### What is your configuration?

```haproxy
# NOTE: This is from a HAProxy test node and some options will probably not make any sense. ;-)

global
    uid                         80
    gid                         80
    chroot                      /var/haproxy
    daemon
    stats                       socket /var/run/haproxy.socket group proxy mode 775 level admin expose-fd listeners
    nbthread                    3
    cpu-map                     1/1 0
    cpu-map                     1/all 0 1 2 3
    cpu-map                     1/2 8
    hard-stop-after             17s
    no strict-limits
    maxconn                     555555
    tune.ssl.ocsp-update.mindelay 300
    tune.ssl.ocsp-update.maxdelay 3600
    httpclient.resolvers.prefer   ipv4
    tune.ssl.default-dh-param   1024
    spread-checks               0
    pp2-never-send-local
    tune.bufsize                16384
    tune.lua.maxmem             0
    log                         /var/run/log local0 debug
    lua-prepend-path            /tmp/haproxy/lua/?.lua
    lua-load                    /tmp/haproxy/lua/617f0378a3e2d8.61814401.lua
    ssl-default-bind-options prefer-client-ciphers ssl-min-ver TLSv1.1
    ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256

defaults
    log     global
    option redispatch -1
    maxconn 1717
    timeout client 33s
    timeout connect 31s
    timeout server 37s
    retries 3
    default-server init-addr last,libc
    default-server maxconn 25

frontend www_frontend
    bind localhost:8443 name localhost:8443 ssl ssl-min-ver TLSv1.1 ssl-max-ver TLSv1.3 ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256 ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/588bc089e07b30.07907702.certlist  thread 1 thread all shards 2 
    mode http
    option http-keep-alive
    default_backend www_backend
    http-request use-service prometheus-exporter if { path /metrics }
    maxconn 444444
    timeout client 10s
    timeout http-request 15s
    timeout http-keep-alive 2s
    stick-table type ip size 50k expire 30m store conn_cnt,conn_cur,conn_rate(10s),sess_cnt,sess_rate(10s),http_req_cnt,http_req_rate(10s) peers opnsense-haproxy-peers
    tcp-request connection track-sc0 src
    option log-separate-errors
    option httplog
    acl acl_5cc7506c6c5bd6.86431523 path_beg -i /.well-known/acme-challenge/
    acl acl_5f1d9e780d9c30.33792935 http_auth(acl_5f1d9e780d9c30.33792935)
    acl acl_63454e8fa72b86.41691541 req.ssl_hello_type 1
    use_backend acme_challenge_backend if acl_5cc7506c6c5bd6.86431523
    http-request set-var(txn.user) http_auth_group(grouptest2a) if acl_5f1d9e780d9c30.33792935
    tcp-request content accept if acl_63454e8fa72b86.41691541
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.5-aaba8d0 2023/12/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.5.html
Running on: FreeBSD 13.2-RELEASE-p9 FreeBSD 13.2-RELEASE-p9 stable/24.1-n254969-8659880248c SMP amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DFREEBSD_PORTS
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 -BACKTRACE +CLOSEFROM +CPU_AFFINITY -CRYPT_H -DEVICEATLAS -DL -ENGINE -EPOLL -EVPORTS +GETADDRINFO +KQUEUE -LIBATOMIC +LIBCRYPT -LINUX_CAP -LINUX_SPLICE -LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING -NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL -PRCTL +PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT -RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD -TFO +THREAD -THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.12 24 Oct 2023
Running on OpenSSL version : OpenSSL 3.0.12 24 Oct 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wlallemand** [comment]
Hello, thanks for your report.

Indeed we should at least fix the error message. 

But what you are requesting is a change of behavior, you are setting explicitly the ocsp-update for this certificate line, so it seems normal to emit an error if it wasn't initialized correctly.

Maybe we could just disable the ocsp-update and emit a warning instead of an error for that kind of cases.

**Comment by fraenki** [comment]
> Maybe we could just disable the ocsp-update and emit a warning instead of an error for that kind of cases.

That would be great! :+1: Thanks for considering this change.

**Comment by rlebreton** [comment]
The error message is indeed wrong and should be changed. I did not think about using the option on certificates that don't have OCSP URIs. The attached patch fixes the error message only.
[0001-BUG-MINOR-ssl-Fix-error-message-after-ssl_sock_load_.patch.txt](https://github.com/haproxy/haproxy/files/14124351/0001-BUG-MINOR-ssl-Fix-error-message-after-ssl_sock_load_.patch.txt)

As for not raising an error when ocsp-update is enabled on a certificate that does not have an ocsp uri I'm a bit more torn. The proper way to answer to your need might rather be to add a global option that enables ocsp-update by default (whenever possible) rather than allow an explicit ocsp update activation that has no chance of succeeding.

**Comment by wlallemand** [comment]
I just pushed the fix, letting the ticket open until we find a more elegant solution.

**Comment by frunkAF** [comment]
I'm seeing this exact behavior using a Cloudflare Origin cert on OPNsense...

[NOTICE] (62651) : haproxy version is 2.8.5-aaba8d0
[NOTICE] (62651) : path to executable is /usr/local/sbin/haproxy
[ALERT] (62651) : config : parsing [/usr/local/etc/haproxy.conf.staging:73] : 'bind 127.4.4.3:443' in section 'frontend' : 'crt-list' : error processing line 1 in file '/tmp/haproxy/ssl/659dc76096fe83.76462299.certlist' : **'/tmp/haproxy/ssl/65c3b55f42923.pem' has an OCSP URI and OCSP auto-update is set to 'on' but an error occurred (maybe the issuer could not be found)'.**
[ALERT] (62651) : config : Error(s) found in configuration file : /usr/local/etc/haproxy.conf.staging
[ALERT] (62651) : config : Fatal errors found in configuration.

I inspect the pem file and it looks like the URIs are correct...

root@OPNsense:~ # openssl x509 -noout -text -in /tmp/haproxy/ssl/65c3b55f42923.pem | grep URI
                OCSP - URI:http://ocsp.cloudflare.com/origin_ecc_ca
                  URI:http://crl.cloudflare.com/origin_ecc_ca.crl

I can workaround this by disabling 'Automatic OCSP updates' under Settings > Global Parameters > SSL settings

It looks like the haproxy plugin was just updated yesterday on OPNsense...
https://github.com/opnsense/plugins/blob/stable/24.1/net/haproxy/pkg-descr

root@OPNsense:~ # haproxy -vv
HAProxy version 2.8.5-aaba8d0 2023/12/07

**Comment by rlebreton** [comment]
@frunkAF You might actually be in a case where the error message was right. In order to validate OCSP responses sent by cloudflare, we need to have a valid certificate against which they can be verified. You could try providing the .issuer file that corresponds to your certificate and see if the error is still there or not. Likewise, if you were to provide an OCSP response alongside your certificate during init, you would be expected to provide the issuer as well and the same error message would be raised (if that is indeed your problem and not an actual bug).

**Comment by frunkAF** [comment]
I reverted the haproxy plugin to 24.1's version...

`opnsense-revert -r 24.1 os-haproxy`

...and it's been working just fine since. I have the Origin Cert with automatic OCSP turned on.

It looks like the version is the exact same?

root@OPNsense:~ # haproxy -vv
HAProxy version 2.8.5-aaba8d0 2023/12/07

The only delta I see is the certlist file doesn't have the brackets anymore.

/tmp/haproxy/ssl/65c3e946c3ef1.pem ocsp-update on

OPNsense performs a syntax check before accepting the change but is it possible that this parameter is incorrectly configured and the haproxy engine just ignores it (ocsp-update off)? So maybe OPNsense updated their plugin to add the brackets and do a proper syntax check and it's now finding out that there's an issue?

> You could try providing the .issuer file that corresponds to your certificate and see if the error is still there or not.

How do I provide an .issuer file?

**Comment by fraenki** [comment]
> The only delta I see is the certlist file doesn't have the brackets anymore.

@frunkAF Although this is pretty off topic, I feel obliged to chime in: a bug in OPNsense 24.1 introduced this syntax error (missing brackets) in the cert lists used by HAProxy. This bug was fixed in OPNsense 24.1.1.

> How do I provide an .issuer file?

Since you're using HAProxy on OPNsense, it should already exist. Search for `/tmp/haproxy/ssl/*.issuer` in the filesystem and verify whether or not it contains the correct issuer information.

**Comment by frunkAF** [comment]
There's no .issuer file in that directory...

root@OPNsense:~ # ls -l /tmp/haproxy/ssl/
total 14
-rw-------  1 www  www  5277 Feb  8 00:00 659db9d938963.pem
-rw-------  1 www  www    50 Feb  8 00:00 659dc2e32786c9.59920524.certlist
-rw-------  1 www  www    50 Feb  8 00:00 659dc76096fe83.76462299.certlist
-rw-------  1 www  www  1389 Feb  8 00:00 65c3e946c3ef1.pem

I tried updating the plugin and still no issuer file exists. Bingo?

**Comment by frunkAF** [comment]
I figured it out!

I uploaded the origin_ca_ecc_root CA to the opnsense Trust Store. Applied the configuration and an issuer file appeared in the directory.

**Comment by rlebreton** [comment]
> The only delta I see is the certlist file doesn't have the brackets anymore.
> 
> /tmp/haproxy/ssl/65c3e946c3ef1.pem ocsp-update on
> 
> OPNsense performs a syntax check before accepting the change but is it possible that this parameter is incorrectly configured and the haproxy engine just ignores it (ocsp-update off)? So maybe OPNsense updated their plugin to add the brackets and do a proper syntax check and it's now finding out that there's an issue?

You a right, the ocsp-update was indeed not enabled in this case. This line actually meant that for hostnames 'ocsp-update' and 'on' the specified certificate would be used.
Glad that everything seems to work for you now.

**Comment by wlallemand** [comment]
Closing this, this has been resolved.

**Comment by PantACRO4life** [comment]
In OPN Sense I wipe all my Cloudflare cert generated by letsencrypt, wipe and redone my ACME challenge types config.  Re-created my certs. No matter what I do I am unable to turn on Automatic OCSP updates.

**Comment by wlallemand** [comment]
@PantACRO4life please open another issue with the relevant details, answering to an unrelated issue which is already closed won't help.

**Comment by fraenki** [comment]
@PantACRO4life You may want to report this issue on the [OPNsense issue tracker](https://github.com/opnsense/plugins/issues). Keep in mind that Let's Encrypt has [ended support for OCSP](https://letsencrypt.org/2024/12/05/ending-ocsp) several months ago.
