### ISSUE TITLE
include/haproxy/sock.h: checked return is suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2439]
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1534012:  Error handling issues  (CHECKED_RETURN)
/include/haproxy/sock.h: 76 in sock_set_mark()
70     }
71     
72     /* Sets mark sockopt on socket */
73     static inline void sock_set_mark(int fd, int mark)
74     {
75     #if defined(SO_MARK)
>>>     CID 1534012:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "setsockopt(fd, 1, 36, &mark, 4U)" without checking return value. This library function may fail and return an error code.
76      setsockopt(fd, SOL_SOCKET, SO_MARK, &mark, sizeof(mark));
77     #elif defined(SO_USER_COOKIE)
78      setsockopt(fd, SOL_SOCKET, SO_USER_COOKIE, &mark, sizeof(mark));
79     #elif defined(SO_RTABLE)
80      setsockopt(fd, SOL_SOCKET, SO_RTABLE, &mark, sizeof(mark));
81     #endif
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment]
Code was recycled from `conn_set_mark()` as found prior to 42a97d9feb5e7eb46c5807b0ef41757728c7eae1

I guess this was previously flagged as false positive, but as the logic was moved, Coverity lost the track of it.

We could make it explicit that we don't check the return value if it was intended (ie: best-effort) though. Else we could try to propagate the error to the caller...

**Comment by chipitsine** [comment]
please, let me know if I should mark it as "intended" on coverity side (or it will be suppressed in some way in code)

**Comment by Darlelet** [comment]
You're right, sorry

Considering this is historical behavior (first found in 51347ed94c54297c0b69954e4fc9c6b7cd4cc4ed), and that it's far from being the only place in the codebase where `setsockopt()` is used without checking the return value (e.g.: tcp quickack), I think we should mark it as intended for now.

Thanks
