### ISSUE TITLE
2.9.x: missing git tags

### ISSUE THREAD

**Issue by kloczek** [haproxy/haproxy#2446]
### Detailed Description of the Problem

Looks like in git repo are missimg git tags from 2.9.1 to 2.9.4.

### Expected Behavior

Release version tags should be present in git repo.

### Steps to Reproduce the Behavior

N/A

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by chipitsine** [comment]
looks duplicate  of

https://github.com/haproxy/haproxy/issues/2303
https://github.com/haproxy/haproxy/issues/1318

**Comment by kloczek** [comment]
Without those tags is not possible to track new releases using gt repo content.

BTW it would be nice if you would start create gh releases to make that easier.
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by chipitsine** [comment]
comment from 

https://github.com/haproxy/haproxy/issues/1318#issuecomment-878547857

describes current release scheme used

**Comment by capflam** [comment]
It is the 4th issue you open on the same subject (this one, #2303, #1318 and #2239). Same question,  same response. We are only using GH as an issue tracker. The DEV repo is mirrored to ease issue tracking in commit messages.

**Comment by git001** [comment]
The funny part is that the same user @kloczek have also raised the other issues before. :man_facepalming:

**Comment by kloczek** [comment]
> The funny part is that the same user @kloczek have also raised the other issues before. 🤦‍♂️

Hmm .. but what is so funny in not tagging repo after release new version? 🤔 
As I wrote before without those tags is not possible to detect that new version has been released.

**Comment by git001** [comment]
That people does not accept how a open source project handles GH. As in the last issues mentioned GH is only used for Issues. The answer [here](https://github.com/haproxy/haproxy/issues/49#issuecomment-467222505) show a valid option to recognize new versions.  Why isn't that an option for you to get informed about new versions?

**Comment by lukastribus** [comment]
We have discussed this over and over again, git stable trees are openely accessible with git tags marking bugfixes release, so there is nothing else to do here. I'm locking this issue now.
