### ISSUE TITLE
GPL 2.0 License does not align with the the GPL 2.1 License stated in src/event_hdl.c

### ISSUE THREAD

**Issue by songliumeng** [haproxy/haproxy#2463]
https://github.com/haproxy/haproxy/blob/4895fdac5a1da1b4d554791780ed1fb522b1a5cd/LICENSE#L3

Upstream repository [src/event_hdl.c](https://github.com/haproxy/haproxy/blob/master/src/event_hdl.c#L9) stated that "either version * **2.1** of the License, or (at your option) any later version.". However, the main LICENSE only mentioned "Historically, haproxy has been covered by GPL version **2**."

Is it possible to update the GPL description here to be "GPL version 2.1 , or (at your option) any later version" that aligns with the upstream repository?

**Comment by wtarreau** [comment]
Hi,

thanks for the report. It seems there was a mixup of GPL and LGPL text in that file, I don't know why. v2.1 is LGPL, GPL is v2. I'll see with Aurélien to fix this. Sometimes I think we should get rid of all this and switch to SPDX tags, but that's a huge work to do and the time spent on this will not be spent adding value to the product :-/

**Comment by Darlelet** [comment]
Ah yes my bad indeed, both `src/http_ext.c` and `src/event_hdl.c` are affected.

I don't remember exactly why, but I think Willy got it right, for those 2 I probably first started by creating the header files which uses LGPL v2.1 (by duplicating them from an existing header file in the repo), and when I created the corresponding source files (by duplicating from another source file), I must have thought there was a mismatch between licenses in header and source file and probably ended up by appending ".1" after the GPL version in the source files without noticing that header files are LGPL and source files are GPL.

How should we proceed for the fix?

**Comment by wtarreau** [comment]
Yes please Aurélien. Please make sure to use the original banner so as to avoid any wording issue for example.

**Comment by Darlelet** [comment]
Now fixed with e9261ff and 60edfab, thanks guys!

**Comment by songliumeng** [comment]
Tons of thanks everyone!!
