### ISSUE TITLE
issue with openssl initialisation order prevent use of security framework configuration for DH-related part

### ISSUE THREAD

**Issue by bplessis** [haproxy/haproxy#2468]
### Detailed Description of the Problem

Due to some clients issue and unknown i was in need to enable DHE-* ciphers with a 1024bits dhparam on a haproxy 2.8 built with openssl 3.x

I quickly discovered (because i also had to enable TLS 1.0/1.1) that with openssl 3.x a security restrictions where increased, including deprecating ciphers, transports mode and, as it seems, dhparam minimum size.

Lowering (or increase) the openssl Security framework leve via the use of `@SECLEVEL=xx` in the ciphers string usually get around thoses limitations, and while that does work for most of the ciphers/transport part, this doesn't work on DHParam processing for haproxy.

However with haproxy, trying to setup a 1024 bit dhparam result in the following message (with the sample :
```
[WARNING]  (154553) : config : parsing [./haproxy.cfg:13] : 'bind 127.0.0.1:44300' in section 'frontend' : 
  unable to load default 1024 bits DH parameter for certificate 'haproxy.pem'.
  , DH ciphers won't be available.
Warnings were found.
```

And there is indeed no possibility to connect with the DHE-RSA-AES128-SHA cipher:

```
$ openssl s_client -CAfile ./dhparam-tests/ca.pem -no_tls1_3 -cipher DHE-RSA-AES128-SHA@SECLEVEL=0 -port 44300
CONNECTED(00000003)
40F7F371FD7E0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1590:SSL alert number 40
```

### Expected Behavior

Setting @SECLEVEL=0 should allow use of a 1024 dhparam key like it's doable using the openssl s_client/s_server tools:

```
$ openssl s_server -cert cert.pem -cert_chain chain.pem -key privkey.pem -dhparam dhparam-1024.pem -cipher DHE:@SECLEVEL=0 -www -no_tls1_3 &
$ openssl s_client -CAfile ca.pem -no_tls1_3 -cipher DHE-RSA-AES128-SHA@SECLEVEL=0
CONNECTED(00000003)
[...]
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: DH, 1024 bits
---
SSL handshake has read 3465 bytes and written 354 bytes
Verification: OK
---
New, SSLv3, Cipher is DHE-RSA-AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DHE-RSA-AES128-SHA
[...]
    Start Time: 1709156194
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```

### Steps to Reproduce the Behavior

1. setup a haproxy instance with the test configuration
2. attempt to connect to it using one of the DHE cipher like DHE-RSA-AES128-SHA

### Do you have any idea what may have caused this?

I tracked the initialisation of the cipher list to `ssl_sock_prepare_bind_conf` use as part of the ssl_sock struct/object called during proxy setup of the `config_validity` function.

While the DH param is installed during `ssl_sock_load_cert` which is called during the parsing of the 'crt' keyword via `bind_parse_crt` if i understand correctly.

Adding a few debug message quickly confirm the intuition that the DHParam was attempted to be loaded even before the ciphersuite was parsed into the openssl ctx, rendering the @SECLEVEL moot for this use.

### Do you have an idea how to solve the issue?

Note: There is usually a way to overcome software not allowing full openssl configuration by passing a custom `openssl.conf` via an environment variable, but even that doesn't work, for i suspect similar reasons (that the code path don't allow dh initialisation after the initial failure)

Full of hope i tried something else: forcing haproxy to re-load the certificate with a dhparam associate via the control socket but it didn't seem to make any difference:

```plain
$ echo -e "set ssl cert haproxy.pem <<\n$(cat ./haproxy.pem ./dhparam-1024.pem)\n" | socat UNIX-CONNECT:/tmp/test-haproxy.sock -
Transaction created for certificate haproxy.pem!

$ echo -e "commit ssl cert haproxy.pem" | socat UNIX-CONNECT:/tmp/test-haproxy.sock -
Committing haproxy.pem.
Success!
```

However haproxy logs didn't show any dhparam related message and the DHE cipher was still unavailable

I did a sanity check hack by just adding a call to `ssl_sock_load_dh_params` in `ssl_sock_prepare_ctx()` and while it didn't get rid of the warning during parsing it did enable the DHE cipher back with the 1024 DH param:

```c
diff --git a/src/ssl_sock.c b/src/ssl_sock.c
index 307f18945..6273455ee 100644
--- a/src/ssl_sock.c
+++ b/src/ssl_sock.c
@@ -3137,14 +3137,15 @@ struct eb_root crtlists_tree = EB_ROOT_UNIQUE;
 static int ssl_sock_load_dh_params(SSL_CTX *ctx, const struct ckch_data *data,
                                    const char *path, char **err)
 {
-	int ret = 0;
+	int ret = 0, sslret;
 	HASSL_DH *dh = NULL;
 
 	if (data && data->dh) {
 		dh = data->dh;
 		if (!ssl_sock_set_tmp_dh(ctx, dh)) {
-			memprintf(err, "%sunable to load the DH parameter specified in '%s'",
-				  err && *err ? *err : "", path);
+                        sslret = ERR_get_error();
+			memprintf(err, "%sunable to load the DH parameter specified in '%s': %s",
+				  err && *err ? *err : "", path, ERR_reason_error_string(sslret));
 			memprintf(err, "%s, DH ciphers won't be available.\n",
 				  err && *err ? *err : "");
 			ret |= ERR_WARN;
@@ -3159,8 +3160,9 @@ static int ssl_sock_load_dh_params(SSL_CTX *ctx, const struct ckch_data *data,
 	}
 	else if (global_dh) {
 		if (!ssl_sock_set_tmp_dh(ctx, global_dh)) {
-			memprintf(err, "%sunable to use the global DH parameter for certificate '%s'",
-				  err && *err ? *err : "", path);
+                        sslret = ERR_get_error();
+			memprintf(err, "%sunable to use the global DH parameter for certificate '%s': %s",
+				  err && *err ? *err : "", path, ERR_reason_error_string(sslret));
 			memprintf(err, "%s, DH ciphers won't be available.\n",
 				  err && *err ? *err : "");
 			ret |= ERR_WARN;
@@ -3188,8 +3190,9 @@ static int ssl_sock_load_dh_params(SSL_CTX *ctx, const struct ckch_data *data,
 				}
 
 				if (!ssl_sock_set_tmp_dh(ctx, local_dh_1024)) {
-					memprintf(err, "%sunable to load default 1024 bits DH parameter for certificate '%s'.\n",
-						  err && *err ? *err : "", path);
+                                        sslret = ERR_get_error();
+					memprintf(err, "%sunable to load default 1024 bits DH parameter for certificate '%s': %s",
+						  err && *err ? *err : "", path, ERR_reason_error_string(sslret));
 					memprintf(err, "%s, DH ciphers won't be available.\n",
 						  err && *err ? *err : "");
 					ret |= ERR_WARN;
@@ -4631,6 +4634,11 @@ static int ssl_sock_prepare_ctx(struct bind_conf *bind_conf, struct ssl_bind_con
 		local_dh_2048 = ssl_get_dh_2048();
 	if (!local_dh_4096)
 		local_dh_4096 = ssl_get_dh_4096();
+
+	if (ssl_sock_load_dh_params(ctx, NULL, NULL, err) & ERR_CODE) {
+		memprintf(err, "%sunable to set default DH parameters.\n",
+		          err && *err ? *err : "");
+	}
 #endif /* OPENSSL_NO_DH */
 
 	SSL_CTX_set_info_callback(ctx, ssl_sock_infocbk);
```

### What is your configuration?

```haproxy
global
         log stdout format raw local0
        stats socket /tmp/test-haproxy.sock mode 600 level admin expose-fd listeners  
        ssl-default-bind-ciphers RSA:DHE@SECLEVEL=0
        tune.ssl.default-dh-param 1024        
        #tune.ssl.default-dh-param 2048

frontend test-ssl
	bind		127.0.0.1:44300 ssl crt haproxy.pem
        mode            http
        log             global
        option          httplog
        option          dontlognull
        maxconn         8000
        timeout client  30s

        http-response return status 404 default-errorfiles

http-errors myerrors
    errorfile 404 errors/404.http
```

### Output of `haproxy -vv`

```plain
Initial issue found on haproxy 2.8.3 packaged for AmazonLinux 2023, i also tested on debian/sid 2.9.5 build and on latest git master.

HAProxy version 2.9.5-1 2024/02/15 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.5.html
Running on: Linux 6.6.13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1 (2024-01-20) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_OT=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL +OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.1.5 30 Jan 2024
Running on OpenSSL version : OpenSSL 3.1.5 30 Jan 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[  OT] opentracing
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wlallemand** [comment]
> Note: There is usually a way to overcome software not allowing full openssl configuration by passing a custom openssl.conf via an environment variable, but even that doesn't work, for i suspect similar reasons (that the code path don't allow dh initialisation after the initial failure)

In fact I just tried this by allowing `CipherString = DEFAULT:@SECLEVEL=1` in a openssl.cnf file and it seems to work by launching it this way:  `OPENSSL_CONF=./openssl.cnf ./haproxy -f bug-2468.cfg`.

Usually you don't need a dhparam.pem but setting `tune.ssl.default-dh-param 1024` will use one generated by openssl. 

I'm not sure what is the best way to fix this, people never reported this because they change it directly the seclevel in openssl.cnf. 
We can't do this because of the initialisation order indeed. Maybe a solution could be to set the security level directly with SSL_CTX_set_security_level() with a global option in haproxy.conf. But I don't see any simple way to do it as a 'bugfix' as you tried, without breaking things.

**Comment by bplessis** [comment]
Hum, i'll test again as i have lost the previous attempt.
However "DEFAULT@SECLEVEL=1" with openssl 3.x isn't enough to enable 1024bits dhparams, you need SECLEVEL=0, are you testing with an openssl 1.1.1 ?

Ok, so for further reference, this openssl.cnf file seem to work:
```
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT@SECLEVEL=0
```

**Comment by wlallemand** [comment]
`Running on OpenSSL version : OpenSSL 3.0.10 1 Aug 2023` w/ Ubuntu 23.10, no problem with SECLEVEL=1.

**Comment by bplessis** [comment]
Huh, ok then i must have mixed the requirements for TLS 1.0/1.1 then
anyway this will get me out of the current jam that's great.

**Comment by wlallemand** [comment]
As far as I know the security level numbers has the same behavior with every OpenSSL version, however starting with OpenSSL 3.0, they enforced the default level to 2.  So according to this document: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_security_level.html "level 1: As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited".

I made a new global option which is named [ssl-security-level](http://docs.haproxy.org/dev/configuration.html#ssl-security-level) which allows to set the security level without doing it in the ciphers, that would be more consistent and won't depend of the setting order.  Hope that helps.

I'm closing the issue.

**Comment by bplessis-swi** [comment]
> As far as I know the security level numbers has the same behavior with every OpenSSL version, however starting with OpenSSL 3.0, they enforced the default level to 2. So according to this document: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_security_level.html "level 1: As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited".

There was another change in OpenSSL 3.0.1: TLS 1.0 and 1.1 were downgraded to security level 0 (https://www.openssl.org/news/openssl-3.0-notes.html)

> I made a new global option which is named [ssl-security-level](http://docs.haproxy.org/dev/configuration.html#ssl-security-level) which allows to set the security level without doing it in the ciphers, that would be more consistent and won't depend of the setting order. Hope that helps.

Thanks, it seem to be working indeed !

**Comment by chipitsine** [comment]
what I particularly like in nginx is the following https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_conf_command

i.e. you can specify virtually any openssl.conf option, including security level.


can we consider something like that for haproxy ?

**Comment by wlallemand** [comment]
@chipitsine I don't think that's a good idea. First it won't be portable and second we will have wild SSL configurations splitted between the haproxy configuration and the openssl one. And as said by the nginx documentation "Note that configuring OpenSSL directly might result in unexpected behavior."

**Comment by chipitsine** [comment]
Well, one can still achieve the same using openssl.cnf, so maybe it's ok
