### ISSUE TITLE
OCSP Stapling fails when server resolves to IPv6 but only IPv4 connectivity available

### ISSUE THREAD

**Issue by chrisstaite-menlo** [haproxy/haproxy#2472]
### Detailed Description of the Problem

Enable OCSP stapling for a certificate where the OCSP server for the certificate resolves to both an IPv4 and IPv6 address, for example Sectigo with ocsp.sectigo.com.  Then disable IPv6 connectivity.  Notice that the stapling is not performed and the error message "Connect() failed for backend <OCSP-UPDATE>: no free ports." is shown in the logs.

I attempted to resolve this with `default-server resolve-prefer ipv4` but this directive was ignored for the <OCSP-UPDATE> backend.

### Expected Behavior

IPv4 is used when IPv6 is unavailable.

### Steps to Reproduce the Behavior

1. Enable OCSP stapling for a certificate with a AAAA record for its OCSP server
2. Disable IPv6 on the HAProxy server
3. Observe that stapling is not performed

### Do you have any idea what may have caused this?

The DNS resolution does not validate available connectivity and does not fall back to IPv4 on IPv6 failure.

### Do you have an idea how to solve the issue?

Either allow this to be configured, utilise the resolve-prefer setting or have IPv6 connection failures fall back to IPv4.

### What is your configuration?

```haproxy
haproxy.conf:
frontend f
  bind 0.0.0.0:443 ssl crt-list haproxy_crt.list alpn h2,http/1.1


haproxy_crt.list:
domain.crt [ocsp-update on]
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.3-86e043a 2023/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.3.html
```

**Comment by wlallemand** [comment]
the `ocsp-update` is using the httpclient which is configurable with `httpclient.resolvers.prefer` in the global section.

**Comment by chrisstaite-menlo** [comment]
Oh, perfect.  Thanks.  Hopefully this ticket can serve to help someone else having this issue.
