### ISSUE TITLE
Allow preserving abstract namespace sockets address length

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#2479]
### Your Feature Request

When connecting to an abstract namespace socket with haproxy, eg with:
```haproxy
server foo abns@bar
```

HAProxy suffix-pads `bar` up to "sun_path" length with NUL bytes, according to the documentation and as pointed out in issue https://github.com/haproxy/haproxy/issues/977

This seems like fairly undesirable behaviour to me.

While I can see that it is not a bug, and rather as-designed, I'd really prefer for HAProxy to offer an option to behave like other tools [1] in that regard.

Additionally, I find it unsettling for my configuration to silently be edited this way [2].

I'm sure there's a historical reason (maybe I'd even find it reasonable!), for why things are this way. But notwithstanding:
- this automatic behaviour is surprising
- appears *less* interoperable with other software nowadays

Finally, what a "sun_path" is should at least be documented, as I don't think it's very common knowledge.
Seems like it's a 108-elements C char array (from https://www.man7.org/linux/man-pages/man7/unix.7.html), which is fine and all if it was mandatory to fill but clearly it is not otherwise this would not cause an interoperability issue...? ~~or am I missing something here?~~

Actually, it's very unclear to me how other tools could possibly pass an array of 108-length but not pad anywhere in it. And lsof and friends don't seem to be able to show what the actual full length name is in the end either.

---

[1]: At the very least cURL, socat, and the Go runtime all seem to not suffix paths

[2]: To me, it seems similar to if `http-request set-header Foo ""` was equivalent to `http-request del-header Foo`. ie questionable convenience benefit but a very good way to shoot yourself in the foot eventually because the semantics are not quite the same before and after.

### What are you trying to do?

Using HAProxy to connect to another program's abns. The latter which doesn't automatically suffix-pad.

### Output of `haproxy -vv`

```plain
HAProxy version 3.0-dev4-7151076+mangadex-73c78ef 2024-03-02T09:44+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 6.2.16-12-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-12 (2023-09-04T13:21Z) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -ggdb3 -gdwarf-4 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=5
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1w+quic-mangadex-73c78ef  2 Mar 2024
Running on OpenSSL version : OpenSSL 1.1.1w+quic-mangadex-73c78ef  2 Mar 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 17.0.6 (++20231208085813+6009708b4367-1~exp1~20231208085906.81)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by Tristan971** [comment]
Digging a bit more, this seems like it's also been reported a long time ago here (in 1.5) https://haproxy.formilux.narkive.com/WkdV7fGj/abstract-namespace-sockets-handling

**Comment by wtarreau** [comment]
I think I'd be OK with changing the default at least because as you say it looks like the rest of the ecosystem has chosen that option, but we need to be sure not to break the old one. If some users have already padded their addresses in their servers to receive connections, or have passed the option to socat, it will suddenly stop working. Or maybe we should just create a new family that is not padded (e.g. abns2) ? After all that's the point of using different address families, we're in some sort changing the address family here. BTW, I was also concerned with the risk that some older kernels might possibly not support this, but I checked, and in kernel 2.1.131 it already used the advertised size so from this point that's OK.

**Comment by Tristan971** [comment]
Agreed on both points; as you'll see on the ML, I took a tunable approach as I'm sure some people manually tweaked their other programs already.

As for changing the default, I'd certainly not complain either :)

> Or maybe we should just create a new family that is not padded (e.g. abns2)

I considered that too, but in the end I figured that it's a bit overkill for a niche-enough feature vs a tunable that changes the default value, especially with how many bind families already exist

**Comment by lukastribus** [comment]
I agree with the non-invasive patch on the ML.


Changing the default on the other hand will break old configurations, configurations that have been in active use, otherwise those previous conversations wouldn't have come up on the issues tracker and mailing list in the first place.

So yes, I'd say changing the default behavior of the abns@ address family prefix is not possible.

If the goal is to end up with a abstract namespace address family that doesn't default to zero padding, then we will have to deprecated the abns@ address family entirely for one LTS cycle or two along with the introduction of new address family prefix.

**Comment by Tristan971** [comment]
> So yes, I'd say changing the default behavior of the abns@ address family prefix is not possible.

While I don’t think it’s mandatory, I don’t agree that it’s impossible or even undesirable.

It’d be reasonable enough to add a notice, which is then increased to a warning in a subsequent release, until a changing-default release.

That said, no matter the default, HAProxy will have to support changing behavior in perpetuity, like socat does and the proposed patch enables.

As for the default, I’m honestly neutral in the way to go because I think it’s advanced and niche enough that:
- no change: requiring a flag forever for « new » behavior is an okay cost
- change: requiring a flag be added to revert to « old » behavior not changed for 10 years is *also* ok

In both cases, the specifically affected crowd can honestly just « deal with it ». And that includes me if it doesn’t change.

But I don’t like the idea that known-suboptimal defaults are to be kept in software for BC alone.

They accumulate over the years, and then you end up with something like MySQL, where you absolutely need 30 lines of boilerplate config to get to a not-insane set of defaults.

That said, I don’t think the default value here is particularly good or particularly bad, and both seem acceptable to me. So this is more philosophical than on-topic… :)
