### ISSUE TITLE
QUIC Interop "resumption" testcase failure when run with LibreSSL

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2480]
### Detailed Description of the Problem

running "resumption" testcase with quic-go client shown that

1) testcase passed on QuicTLS
2) testcase failed on LibreSSL

(logs archive attached)

### Expected Behavior

pour me coffee maybe. not sure.

### Steps to Reproduce the Behavior

run quic interop on the following image

https://github.com/haproxytech/haproxy-qns/tree/libressl

### What is your configuration?

```haproxy
default provided by quic interop image
```

### Output of `haproxy -vv`

```plain
not sure
```

**Comment by chipitsine** [comment]
[logs-resumption.zip](https://github.com/haproxy/haproxy/files/14511283/logs-resumption.zip)

**Comment by haproxyFred** [comment]
checking... thx !

**Comment by haproxyFred** [comment]
In fact for quic-go even the handshake test does not pass for an unknown reason at this time (No ALPN).
Regarding the resumption, it does not pass for any client. According to the interop runner, the server(haproxy) would have sent a certificate in the second handshake.

**Comment by chipitsine** [comment]
at least of the time of writing, I was right. please find [attached logs](https://github.com/haproxy/haproxy/files/14511283/logs-resumption.zip)

1) haproxy is "b0dd4810e748b300482b4610cd904a42e429d91f" (which is current master)
2) quic-go is a bit outdated. cached one from 3 days ago "martenseemann/quic-go-interop                   latest    395f47e956f3"


I didn't attach handshake logs, they pass for both quictls and libressl.
as for "resumption" testcase ...

```
ilia@fedora:~/gh860/quic-interop-runner$ cat logs_2024-03-06T13\:01\:24-libressl/haproxy_quic-go/resumption/output.txt | tail -10
client          | Test case: resumption
client          | Downloading files failed: expected to receive a session ticket within 10 seconds
client exited with code 1
Stopping server   ... 
Stopping sim      ... 
Stopping server   ... done
Stopping sim      ... done
1
Aborting on container exit...

ilia@fedora:~/gh860/quic-interop-runner$ cat logs_2024-03-06T13\:57\:27-quictls/haproxy_quic-go/resumption/output.txt  | tail -1
2024-03-06 13:59:31,489 Check of downloaded files succeeded.
ilia@fedora:~/gh860/quic-interop-runner$ 

```

**Comment by chipitsine** [comment]
I updated quic-go to `99943e33278b`, the same results, "resumption" fails for LibreSSL and passes for QuicTLS

**Comment by haproxyFred** [comment]
Argh! My quic-go image is outdated (6month). Sorry for the noise. So I guess the handshake interop test should pass also for quic-go.

**Comment by chipitsine** [comment]
what else comes to mind that usually quic interop images are built from https://github.com/haproxytech/quic-dev/tree/qns (while I built images from https://github.com/haproxy/haproxy). Sometimes those branches differ

**Comment by chipitsine** [comment]
Resumption not supposed to work on LibreSSL
