### ISSUE TITLE
2.9.6: A bogus APPCTX [0x56295e8a5a70] is spinning at 9291217 calls per second and refuses to die, aborting now!

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#2490]
### Detailed Description of the Problem

The problem here on my side is, we don't have the logs from that day/moment anymore so we only have the ones from the backtrace. Sorry :/
It (seems) first appeared as of 2.9.6 fyi.

### Expected Behavior

No crash

### Steps to Reproduce the Behavior

N/A

### Do you have any idea what may have caused this?

SPOE

### What is your configuration?

```haproxy
I can share specific parts if required
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.6-9eafce5 2024/02/26 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.6.html
Running on: Linux 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB= USE_SLZ=1 USE_NS= USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE= USE_PCRE_JIT= USE_PCRE2=1 USE_PCRE2_JIT=
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=48).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

https://gist.github.com/idl0r/ee83781539827c9a5c8179279eacfec9

**Comment by capflam** [comment]
Thanks @idl0r, I'm investigating.

**Comment by capflam** [comment]
In the trace, it seems some data are blocked in the response channel and the SPOE applet seems to wait for more data. In this case, there is probably some conditions to fall into a wakeup loop.

Could you print the response channel content using following GDB command: `p /x *(char *)(0x7fbb10489470+216)@175` ?

**Comment by idl0r** [comment]
Sure:
```
(gdb) p /x *(char *)(0x7fbb10489470+216)@175
$1 = {0xff, 0x0, 0x12, 0x70, 0xad, 0x50, 0xdf, 0xf8, 0x1b, 0x32, 0xd0, 0xba, 0x68, 0x32, 0xff, 0x0, 0x57, 0xa8, 0x6b, 0x29, 0xc7, 0xe8, 0x9a, 0xca, 0xd0, 0x6f, 0x16, 0x3e, 0x3f, 0x32, 0x34, 0x88, 0x0, 0x37, 0xb2, 0xec, 0xa, 0xc2, 0xc7, 0x1, 0x94, 0x5a, 
  0xe0, 0x40, 0xd4, 0x1e, 0xea, 0xed, 0xd3, 0x6a, 0x5e, 0x71, 0xa8, 0x4f, 0xba, 0xe7, 0xd0, 0x69, 0xe8, 0x60, 0x38, 0x52, 0xc2, 0xad, 0x7e, 0x5a, 0xaf, 0xe, 0xc2, 0x71, 0x6e, 0x91, 0x8c, 0x2b, 0x83, 0x61, 0x79, 0x51, 0x75, 0x7a, 0x77, 0x8b, 0xba, 0x7d, 
  0x93, 0x6c, 0xd, 0x89, 0xf2, 0xeb, 0x84, 0x4b, 0xfe, 0x2a, 0x83, 0x69, 0x89, 0x8a, 0x7a, 0xac, 0x34, 0xd2, 0x71, 0x24, 0xcc, 0xf4, 0x3f, 0xc0, 0x25, 0xdd, 0x23, 0xa8, 0xae, 0x91, 0x21, 0x4b, 0xe, 0xd9, 0x8, 0xb0, 0x1f, 0xb3, 0x74, 0x78, 0xb9, 0x77, 
  0xb8, 0x47, 0xaa, 0xf3, 0xb9, 0x65, 0xd5, 0x8, 0x1f, 0x93, 0x25, 0x5a, 0xdc, 0x7b, 0xea, 0xaa, 0x77, 0x69, 0xe, 0x59, 0xe1, 0x4a, 0xc, 0x3b, 0x98, 0x80, 0x3e, 0xc8, 0xd4, 0xa2, 0xd0, 0xe6, 0xc, 0x96, 0x6e, 0x3d, 0x95, 0x4e, 0x6c, 0xb9, 0xad, 0xf2, 
  0xb6, 0x62, 0x56, 0x29, 0xf, 0xdc, 0xaf}
```

**Comment by capflam** [comment]
Thanks, I will decode it now

**Comment by capflam** [comment]
Hum, it is not a SPOE frame, it corresponds to nothing. I don't know if it comes from the command that prints junk data or if there is indeed an issue with data in the response channel.

**Comment by capflam** [comment]
I'm starting to understand. In some cases, an invalid frame may lead to this behavior. I'm able to reproduce this behavior with a frame of size 0. And I understand my error with the command I sent you. It was indeed wrong. Just to be sure, could you retry with the following command :  `p /x *(char *)(0x7fbb10489470+81)@175`
It should be the offending frame. And to avoid another round-trip, could you also emit `p /x *(char *)(0x7fbb10489470)@81` ?

In any case, I will fix the bug. But it is useful to validate my theory and it may help you to find an issue in the agent too.

**Comment by capflam** [comment]
@idl0r, I pushed a patch that may fix your issue. Without info about the offending frame, it is hard to be categorical. But if you are able to reproduce the issue,  you may test it.

**Comment by idl0r** [comment]
Hi Christopher,

sorry for the delay:
```
(gdb) p /x *(char *)(0x7fbb10489470+81)@175
$1 = {0x6f, 0x77, 0x65, 0x64, 0x11, 0x0, 0x0, 0x0, 0x15, 0x67, 0x0, 0x0, 0x0, 0x1, 0xf3, 0xbc, 0x78, 0x1, 0x1, 0x3, 0x2, 0x7, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x11, 0x0, 0x0, 0x0, 0x15, 0x67, 0x0, 0x0, 0x0, 0x1, 0xf3, 0xbb, 0x78, 0x1, 0x1, 0x3, 
  0x2, 0x7, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x11, 0x0, 0x0, 0x0, 0x15, 0x67, 0x0, 0x0, 0x0, 0x1, 0xf0, 0xbc, 0x78, 0x1, 0x1, 0x3, 0x2, 0x7, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x11, 0x0, 0x0, 0x0, 0x15, 0x67, 0x0, 0x0, 0x0, 0x1, 0xf4, 
  0xbb, 0x78, 0x1, 0x1, 0x3, 0x2, 0x7, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x11, 0xb, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2d, 0x63, 0x6f, 0x64, 0x65, 0x4, 0x0, 0x7, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x8, 0x6, 0x6e, 0x6f, 0x72, 0x6d, 
  0x61, 0x6c, 0xff, 0x0, 0x12, 0x70, 0xad, 0x50, 0xdf, 0xf8, 0x1b, 0x32, 0xd0, 0xba, 0x68, 0x32, 0xff, 0x0, 0x57, 0xa8, 0x6b, 0x29, 0xc7, 0xe8, 0x9a, 0xca, 0xd0, 0x6f, 0x16, 0x3e, 0x3f, 0x32, 0x34, 0x88, 0x0, 0x37, 0xb2, 0xec, 0xa, 0xc2, 0xc7, 0x1}
(gdb) p /x *(char *)(0x7fbb10489470)@81
$2 = {0x0, 0x0, 0x0, 0x25, 0x66, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15, 0x67, 0x0, 0x0, 0x0, 0x1, 0xfc, 0xbb, 0x78, 0x1, 0x1, 0x3, 0x2, 0x7, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x11, 0x0, 0x0, 0x0, 0x15, 0x67, 0x0, 0x0, 0x0, 0x1, 0xf2, 
  0xbc, 0x78, 0x1, 0x1, 0x3, 0x2, 0x7, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x11, 0x0, 0x0, 0x0, 0x15, 0x67, 0x0, 0x0, 0x0, 0x1, 0xf6, 0xbb, 0x78, 0x1, 0x1, 0x3, 0x2, 0x7, 0x61, 0x6c, 0x6c}
```

Let me know if you need anything else.

Will apply / test your patch. Thank! :)

**Comment by capflam** [comment]
no problem @idl0r, I understand you have also something else to do than replying to GH issues :) 

Thanks for the info.

**Comment by wtarreau** [comment]
FWIW this one starts with "owed" and repeats the word "allowed" at plenty of places. The fact that it starts with the end of a word might indicate something maybe (truncation, overflow, bad offset) ?

**Comment by idl0r** [comment]
Let me know if you want me to share those specific parts of the config, in case it helps.

**Comment by capflam** [comment]
I was obviously tired because offsets of the commands were wrong. Fortunately, combining all info, I was able to reconstitue the response buffer. However It seems mangled. There are 7 ACK frames in a middle of a DISCONNECTING frame. My patch should fix the issue by detecting properly the "invalid" DISCONNECTING frame. However that puzzles me. It may be an issue with the agent. But it may also be an issue with HAProxy. In this case, I doubt it only affects the SPOE. Because here, data in the channel's buffer are mangled. It would be a serious issue ! 

Do you know if this is a bug specific to 2.9.6 ?

**Comment by idl0r** [comment]
It was the first and as of now the only crash so far and it was on 2.9.6. We don't have 2.9.6 for that long yet tho.

**Comment by capflam** [comment]
What was the previous version ?

**Comment by idl0r** [comment]
Then deployments started (they may take up to some days to roll out completely)
2.9.6 - Feb. 29
2.9.4 - Feb. 15
2.9.3 - Jan. 22

They all (up to 2.9.6? had some of your special H2 mux patches. I can name the exact ones if necessary.

**Comment by capflam** [comment]
Ok thanks, I will check changes between 2.9.3 and 2.9.6.

**Comment by capflam** [comment]
There is nothing obvious. So if the issue is on haproxy side, the 2.9.3 is probably affected too. Your crash happen on stop/reload. It is at least by interpretation. But I don't know if it is a coincidence or not. Do you have any other backtraces by any chance ?

Is there any chance the issue is on the agent side ?

**Comment by idl0r** [comment]
That's the only crash that happened. There is otherwise just the peers one #2470
So no other backtraces so far.

For the agent question I have to pass that one to @mxey

**Comment by capflam** [comment]
Ok. That's not the best solution but I suggest to wait a bit then.

**Comment by mxey** [comment]
I think this could be bug in the Go library we use for SPOE. AFAICT:

[It usually sends the frames one after the other, reading them from a channel](https://github.com/babiel/haproxy-spoe-go/blob/9119f3323ea82264ef32ba4353555e353077bb95/conn.go#L113). [But on shutdown, it will send a disconnect frame directly, ignoring the channel/queue](https://github.com/babiel/haproxy-spoe-go/blob/9119f3323ea82264ef32ba4353555e353077bb95/conn.go#L60).

**Comment by capflam** [comment]
Thanks @mxey. So it explains the frames in the response channel are mixed up. And my patch should avoid loops in that case by properly reporting an invalid frame. I'm marking the issue as fixed. Thanks guys !
