### ISSUE TITLE
How to change backend use environment variable

### ISSUE THREAD

**Issue by aka-ao** [haproxy/haproxy#250]
When maintenance I need to respond 503, but only health check request  respond 200.
I set as follows and chenge mentenance mode into management page but response is 503.
![screen](https://user-images.githubusercontent.com/15647199/64144288-c20e5180-ce4e-11e9-8f8b-111cc81bedd4.png)

Please tell me How to change backend use environment variable.
 
- haproxy.cfg
```
frontend http-in-app
    ~~~

frontend http-in-${local.ip[count.index]}
      bind ipv4@${local.ip[count.index]}:80
      http-request set-log-level debug if { path_beg /health }
      acl health_check path_beg /health
      acl maintenance env(MAINT_FLG) -m bool true
      use_backend maintenance_mode if health_check maintenance
      default_backend app-management

frontend http-in
      stats enable
      stats uri /admin?stats
      stats admin if TRUE
      bind *:${local.maintenance_port}

backend maintenance_mode
    mode http
    errorfile 503 /etc/haproxy/errors/200.http

backend maintenance_mode
~~~

default_backend app-management
~~~
```

I am sorry that my English is so bad.

**Comment by wtarreau** [comment]
You cannot change environment variables after startup. We initially
thought we would allow this but it would result in a huge confusion
given that for most users it would not be trivial to differenciate
those resolved at boot time and those resolved at run time (i.e. only
the ones in the env() sample fetch).

I wanted to add the possibility to show/set process-wide variables from
the CLI exactly for your purpose (maintenance), but this was never done.
I don't think it's particularly difficult to implement though.

**Comment by aka-ao** [comment]
I'm sorry I didn't explain it enough.
Restart haproxy after changed environment variables from false to true, but response is 503.

**Comment by wtarreau** [comment]
Then it depends how you restart. If you're using systemd, you're screwed
unfortunately, as the variables from your shell are ignored, it uses its
own variables instead.

Also if you perform a reload in master-worker mode, similarly you have no
way to change your variables, you'll keep those that were present when the
master was started. In this mode, environment variables should probably be
limited to host-level configuration only (host name, paths, etc).

**Comment by lukastribus** [comment]
Even if you pass the environment variable correctly, it's not a bool, but a string, so a string match is what your ACL needs to do:

`acl maintenance env(MAINT_FLG) -i true`

Also, as you should have seen when opening this issue, we don't use the tracker on github for support requests, so please use the mailing list or the discourse forum next time.

**Comment by aka-ao** [comment]
> `acl maintenance env(MAINT_FLG) -i true`

thanks this answer.
