### ISSUE TITLE
Can't compile 2.9.6 with openssl 3.2.1

### ISSUE THREAD

**Issue by nneil** [haproxy/haproxy#2501]
### Detailed Description of the Problem

Compilation error

```
[haproxy-2.9.6]$ make USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ZLIB=1 USE_PCRE=1 TARGET=linux-glibc -j 8
  CC      src/ev_poll.o
  CC      src/ev_epoll.o
  CC      src/cpuset.o
  CC      src/ssl_sock.o
  CC      src/ssl_ckch.o
  CC      src/ssl_sample.o
  CC      src/ssl_crtlist.o
  CC      src/cfgparse-ssl.o
  CC      src/ssl_utils.o
  CC      src/jwt.o
  CC      src/ssl_ocsp.o
  CC      src/namespace.o
src/ssl_sample.c: In function ‘smp_fetch_ssl_fc_ec’:
src/ssl_sample.c:1350:15: error: ‘for’ loop initial declarations are only allowed in C99 mode
               for (int i = 0; curve_name[i]; i++)
               ^
compilation terminated due to -Wfatal-errors.
make: *** [src/ssl_sample.o] Error 1
make: *** Waiting for unfinished jobs....
```

### Expected Behavior

Compilation completes

### Steps to Reproduce the Behavior

Extract from source and compile

### Do you have any idea what may have caused this?

Openssl 3.2.1 triggers a different code branch to be compiled

### Do you have an idea how to solve the issue?

Enable C99 for that file?

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
Can't compile
```

**Comment by git001** [comment]
please can you describe your build environment like OS, Compiler.

**Comment by wtarreau** [comment]
It was brought by this one: 25da2174c6 ("MINOR: ssl: Update ssl_fc_curve/ssl_bc_curve to use SSL_get0_group_name"), the code was apparently built with warnings disabled, and since it's only enabled with openssl 3.2, it was not noticed. We'll fix it. Thanks!

In the mean time you can fix it if you want, by adding "int i;" after the line "char *curvvename;" a few lines above, and removing "int" in "int i" from the "for (int i = 0; ..." statement at line 1350 in src/ssl_sample.c.

**Comment by wtarreau** [comment]
Actually the author is not even the culprit in that there's no specific warning to report that one.

**Comment by nneil** [comment]
> Actually the author is not even the culprit in that there's no specific warning to report that one.

Thank you for fixing this. But I don't understand what the sentence above means.

**Comment by wtarreau** [comment]
I meant that there's no compiler warning that can be enabled to detect this portability issue. I found one way to reliably trigger it at build time but I noticed it triggers other unrelated parts (that possibly nede to be fixed as well). I've pushed the fix in the latest master, it will be backported to 2.9 soonish.

Just for our info, what OS type/version and compiler type/version are you using ?

**Comment by nneil** [comment]
I am sad to say I am using Centos 7.0, gcc 4.8.5

**Comment by wtarreau** [comment]
No need to be sad for this :-)  As long as systems and compilers work without causing too many difficulties, we continue to support them. This week-end for example I gave up on Solaris 8 (25 yr old), and this morning we fixed the build for gcc-4.2, so no worries.

**Comment by nneil** [comment]
Thank you for your understanding.

**Comment by wtarreau** [comment]
Let's not close it until backported.

**Comment by capflam** [comment]
Backported now
