### ISSUE TITLE
haproxy 是否存在过滤功能？

### ISSUE THREAD

**Issue by F-0x57** [haproxy/haproxy#2507]
### Detailed Description of the Problem

![图片](https://github.com/haproxy/haproxy/assets/83194919/f1ee8d56-12e6-48d0-bc58-9eda5b3addb2)

### Expected Behavior

-1' UNION select 1,schema_name,3 from INFORMATION_SCHEMA.SCHEMATA;（被 500 内部错误）

-1' UNION select 1,schema_name,3 from INFORMATIONSCHEMA.SCHEMATA;（通过访问）
![图片](https://github.com/haproxy/haproxy/assets/83194919/75f59ba9-d016-411e-a115-b5f804c57bfa)

### Steps to Reproduce the Behavior

我将2个容器绑定到宿主机的一个端口，进行轮询的均衡负载，但是我感觉有过滤，-1' UNION select 1,schema_name,3 from INFORMATION_SCHEMA.SCHEMATA;（被 500 内部错误）。

### What is your configuration?

```haproxy
`global
    log stdout format raw local0

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:8080
    stats uri /haproxy?stats
    default_backend lamp_backends

backend lamp_backends
    balance roundrobin
    server lamp1 lamp1:80 check
    server lamp2 lamp2:80 check`
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.6-9eafce5 2024/02/26 - https://haproxy.org/
```

**Comment by wlallemand** [comment]
@brookeses69 could you please interact in english? We won't be able to help you otherwise. thanks.

**Comment by F-0x57** [comment]
Ok, I used 3 browsers to test and found that only Microsoft Edge returned normally, the other browsers were reset connection
![图片](https://github.com/haproxy/haproxy/assets/83194919/7be920b8-daef-4c1f-ac4c-a703953ae21b)
![图片](https://github.com/haproxy/haproxy/assets/83194919/b60335a8-b9cd-41d5-bc7e-b70d15194514)
![图片](https://github.com/haproxy/haproxy/assets/83194919/8fcbfa47-71ec-4ce5-a43a-23ba93def7c7)
![图片](https://github.com/haproxy/haproxy/assets/83194919/802a7633-490a-431f-87e8-14f8781051ce)
![图片](https://github.com/haproxy/haproxy/assets/83194919/d2b5f518-afa5-4b79-8514-cd60becfa328)

**Comment by brookeses69** [comment]
Ok, I used 3 browsers to test and found that only Microsoft Edge returned normally, the other browsers were reset connection
