### ISSUE TITLE
Weird behaviour with websockets

### ISSUE THREAD

**Issue by sammy007** [haproxy/haproxy#2514]
### Detailed Description of the Problem

I have configured 2 backends, same service endpoint underneath. Getting 503 on the FAILS one and it works on WORKS backend when I put FAILS on maintenance.

### Expected Behavior

It just should work. it should rewrite path and serve.

### Steps to Reproduce the Behavior

```
backend FAILS
        mode http
        option http-server-close
        timeout tunnel 1h

        http-request replace-header Host .* service.domain.tld
        http-request replace-path .* /ws/AUTH-UUID

        server s1 service.domain.tld:443 ssl verify none no-check
```

```
backend WORKS
        mode http
        option http-server-close
        timeout tunnel 1h
    
        option httpchk GET /ws/AUTH-UUID HTTP/1.1
        http-check connect port 443 ssl sni service.domain.tld
        http-check send hdr Host service.domain.tld hdr Connection Upgrade hdr Upgrade websocket hdr Sec-WebSocket-Key haproxy hdr Sec-WebSocket-Version 13
        http-check expect status 101
        
        http-request replace-header Host .* service.domain.tld
        http-request replace-path .* /ws/AUTH-UUID

        server s1 service.domain.tld:443 ssl verify none check-sni service.domain.tld observe layer4 error-limit 10 on-error mark-down check
```

### Do you have any idea what may have caused this?

I have no idea, if I set http-check like in WORKS backend it serves requests. But does not on LTS. If there is no http-check like this it does not serve requests.

### What is your configuration?

```haproxy
FAILS backend fails on 2.9.x and WORKS just works.
**Both backends fails on LTS.**
```

### Output of `haproxy -vv`

```plain
FAILS backend fails on 2.9.x, Both backends fails on LTS (lts-bookworm).
haproxy:2.9.6-alpine3.19 and many other versions.
```

**Comment by capflam** [comment]
At first glance, it is a configuration issue and not a bug. And it is related to SSL not Websocket. You are using a SNI for your HTTP health-check and it works. But there is no SNI defined for the regular traffic. It may be the issue. Try to set `sni` parameter on your server line.

**Comment by capflam** [comment]
@sammy007, what is the status of this issue ? Is the problem fixed on your side ?

**Comment by sammy007** [comment]
For now I give up, I've added layer7 checks and it works, I have no idea why it does not work when there is no checks. Maybe I misunderstand the internals of how haproxy works. So `WORKS/BROKEN` still persist, but maybe it's a feature despite it does not make any sense to me. I will reopen it when I find a time to play further.

**Comment by capflam** [comment]
It is hard to know what happens, we have not enough info. But its seems unrelated to haproxy internals. It is most probably a configuration issue. But if you have a workaround and no time to provide info for now, it is not a problem. The issue is still there and may be reopen indeed.
