### ISSUE TITLE
Trying to insert a string in response body using custom filter causes no response to client.

### ISSUE THREAD

**Issue by anandcta123** [haproxy/haproxy#2517]
### Detailed Description of the Problem

I have a scenario, where I need to inject some js script  into the response body. For this, I have written a custom filter, which inserts the script into the response. 

My filter code is as below.
```
`MyFilter = {}
MyFilter.id = "My Lua filter"
MyFilter.flags = filter.FLT_CFG_FL_HTX
MyFilter.__index = MyFilter

function MyFilter:new()
    flt = {}
    setmetatable(flt, MyFilter)
    return flt
 end

function MyFilter:start_analyze(txn, chn)
    filter.register_data_filter(self, chn) -- mandatory to call http_payload()
end

function MyFilter:end_analyze(txn, chn)
   --filter.unregister_data_filter(self, chn)
end

function MyFilter:http_headers(txn, http_msg)
	core.log(core.notice, "MyFilter:http_headers")
end

local head_end_pattern_size = string.len("</head>")
local js_pattern_end = "</head>"

local function find_head_endtag_in_body(response_body)
    local be, ee = string.find(response_body, js_pattern_end)
    return be, ee
end

function MyFilter:http_payload(txn, http_msg)
    if http_msg:is_resp() then
        local replace = '<script>var __uzdbm_1 = "b47136c0-0246-46ee-94a6-39c2dbb75865";var __uzdbm_2 = "NDczM2Y2MzktYnNmZi00MzAxLWIyYTgtOWQ1NWNjNTQyOTI5JDEyMi4xNzEuMTcuMTQ=";var __uzdbm_3 = "7f6000341fc59e-9533-478a-88aa-b16f4b230e9217121878127494882611-be7e25c77a0735e716";var __uzdbm_4 = "false";var __uzdbm_5 = "uzmx";var __uzdbm_6 = "7f9000751985d1-c080-4205-bbc9-61500909df622-17121878127494882611-4473716d45414ed016";var __uzdbm_7 = "radware.com";</script> <script> (function(w, d, e, u, c, g, a, b){ w["SSJSConnectorObj"] = w["SSJSConnectorObj"] || {ss_cid : c, domain_info: "auto"}; w[g] = function(i, j){w["SSJSConnectorObj"][i] = j}; a = d.createElement(e); a.async = true; if(navigator.userAgent.indexOf(\'MSIE\')!==-1 || navigator.appVersion.indexOf(\'Trident/\') > -1){ u = u.replace("/advanced/", "/advanced/ie/");} a.src = u; b = d.getElementsByTagName(e)[0]; b.parentNode.insertBefore(a, b); })(window,document,"script","https://www.radware.com/18f5227b-e27b-445a-a53f-f845fbe69b40/stormcaster.js","bsfh","ssConf"); ssConf("c1" , "https://www.radware.com"); ssConf("c3", "c99a4269-161c-4242-a3f0-28d44fa6ce24");ssConf("au", "radware.com"); ssConf("cu", "validate.perfdrive.com, ssc"); </script>'	
	
	core.log(core.notice, string.format("resp body --> %s", http_msg:body()))

	be, ee = find_head_endtag_in_body(http_msg:body())
	if be ~= nil and be < ee then
		--	http_msg:insert(replace, (be-1))
	end
    else
        core.log(core.notice, "<HTTP:Request>")
    end
end

core.register_filter("jsinjection-filter", MyFilter, function(flt, args)
    return flt
end)`
```

haproxy.cfg is as below. calling filter in frontend.

```
frontend fe_main
    mode http
    bind *:80 v4v6
    bind *:443 ssl crt /etc/ssl/private/mydomain.pem

    filter lua.jsinjection-filter

    http-request wait-for-body time 1s at-least 10420 
    http-request lua.rdwrHttpClientConnector
   
    use_backend be_servers
	
backend be_servers
    #filter compression
    #compression algo-res gzip

    balance roundrobin
    server server1 127.0.0.1:8081 check
```

My problem, when I call http_msg:insert to insert the script and without enabling the compression filter in backend, the client will not receive the response with an error "could not get response".

If I enable the `filter compression` and `compression algo-res gzip` in only backend section, everything works fine and the script inserted into the response.

### Expected Behavior

Without "filter compression", it is not working. What if, I don't use any compression. This should still work without specifying "filter compression". 

### Steps to Reproduce the Behavior

1. Register a custom filter.
2. restart haproxy.
3. send a request to haproxy. 

### What is your configuration?

```haproxy
global
	log /dev/log	local0	info
	lua-prepend-path /etc/haproxy/utils/?.lua
	lua-load-per-thread /etc/haproxy/rdwr_httpclient_connector.lua
	chroot /var/lib/haproxy
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	httpclient.ssl.verify none

defaults
	log global
	mode	http
	option	httplog
	option logasap
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	option http-keep-alive

frontend fe_main
    mode http
    bind *:80 v4v6

    filter lua.jsinjection-filter

    http-request wait-for-body time 1s at-least 10420 
    http-request lua.rdwrHttpClientConnector
   
    use_backend be_servers
	
backend be_servers
    #filter compression
    #compression algo-res gzip

    balance roundrobin
    server server1 127.0.0.1:8081 check
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.7-1ppa1~focal 2024/03/02 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.7.html
Running on: Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-A73k7e/haproxy-2.8.7=. -fstack-protector-strong -Wformat -Werror=format-securi                                                                             ty -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-va                                                                             lue -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -                                                                             Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT                                                                             =1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -                                                                             KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSS                                                                             L -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +R                                                                             T +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
Not seeing any log information for this error.
```

**Comment by capflam** [comment]
It does not work because you don't change the announced `content-length` when the payload is modified. Thus the response appears as invalid. I guess you have `ID--` termination state in your haproxy logs. And it works with the compression filter by side effect because when the response payload is compressed, it is chunked. So `content-length` header is replaced by `transfer-encoding; chunked` header.

In your case, you should only remove the `content-length` header from the response in `MyFilter:http_headers()` lua function. The response will be automatically chunked. For instance:

```
function MyFilter:http_headers(txn, http_msg)
        if http_msg:is_resp() then
           http_msg:del_header("content-length")
        end
	core.log(core.notice, "MyFilter:http_headers")
end
```

**Comment by anandcta123** [comment]
Thanks for your clarification. I got my mistake. I need few clarifications.
1. Using filter to modify the response content, is it the go to solution? or we need to follow any different approach.
2. If filter is allowed to use, as stated, will updating content-length will solve the issue.
3. If the response from backend server is compressed. Is the Haproxy does decompression before passing to the filter.

**Comment by capflam** [comment]
1. Yes, it is a good solution to use a lua filter for this purpose if the CPU is not an issue. But there is no other solution, so...
3. You can update the content-length if you are sure to update the payload too. Unfortunately, it cannot be performed when the payload is modified because at this step, the headers are no longer available. I guess the API may be improved. But for now, it is not possible.
4. If the response is compressed first, the payload will be seen compressed by your lua filters. In your case, your lua filter is declared before the HTTP compression filter. So it is executed first and then the payload is compressed.

As a side note, it could be a good idea to unregister your filter from data filtering once the payload was rewritten or when you are sure it will never be rewritten. For big object, the data filter may be expensive.

EDIT: If the response is compressed by the server itself, it will not be possible to modify the payload as you want. HAProxy does not uncompress objects. However, you can offload the gzip compression by using `compression offload` directive. This way, the compression will always be performed by HAProxy itself.

**Comment by anandcta123** [comment]
For point 2 of above. 
I am updating the content-length header as below. In http_headers, I will read the content-length header value and I will compute my JS script length. I will update the total length in content-length header as below. After that in http_payload, I will insert the JS script. Is this fine to do like this?

Also will it require to do any special handling, if the response is chunked.

```
function MyFilter:http_headers(txn, http_msg)
        core.log(core.notice, "MyFilter:http_headers")

        if http_msg:is_resp() then
                headers = http_msg:get_headers()
                if headers["content-length"] ~= nil then
                        content_len = headers["content-length"][0] + #rdwr_js_inject
                        core.log(core.notice, string.format("header %d %d", headers["content-length"][0], content_len))
                        http_msg:set_header("content-length", string.format("%d", content_len))
                end
        end
end
```

**Comment by capflam** [comment]
At first glance, it seems good. But in this case, you must be sure to update the payload accordingly. For chunked response, no headers modification is required. But if clients are able to process chunked responses, I suggest to only remove the content-length header. This way, the response will be automatically chunked, independently of the payload update. In all case, this will be valid. And for HTTP/1.0 clients, if any, the close mode will be used instead and this will be good too.

**Comment by anandcta123** [comment]
another important question, will the filter receives complete body of the response by the time http_payload is called or is there any chance, if the response is too big, it will receive parts of response, in that case will it call the filter repeatedly.

**Comment by capflam** [comment]
`http_payload` callback may be called several time, first time after the headers analysis and then every time part of the message body is received. If the payload is small and if you add a `wait-for-body` action, it will be called only once. To do so, the message must fit in a buffer of course.

By default data in the buffer are fully forwarded. The tricky part with lua filters is when you want to bufferize some data to not send them ASAP.

**Comment by anandcta123** [comment]
Thanks for your kind information. Really helpful.

I am testing one more scenario, the backend server sending compressed response using gzip, but if I try to get the body in http_payload of the filter, I am not getting data and printing "..." in log. Will you please let me know, if anything I am missing or it's the behavior of HaProxy.

**Comment by capflam** [comment]
For HAProxy, there is no difference if the response payload is gzip by the backend server or not. However, gzip data are binaries and Lua is probably unable to print it.

**Comment by anandcta123** [comment]
@capflam thanks for the info.

As you mentioned earlier, HaProxy will not do any decompression. I am planning to use "zlib" to decompress payload received from backend server and modify the response body and perform compression on new data. But for me challenging is, how to set again the content-length header with new compressed data. But http_payload will not have access to headers. Is there any better way to solve this problem?

**Comment by capflam** [comment]
About the `content-length` update, the best is to remove it and let HAProxy adds a `transfer-encoding: chunked` header before sending the message. In fact, it is the only solution if the payload is (re)compressed because you cannot know in advance the payload size once compressed.

But, IMHO, you should consider to offload the compression on HAProxy. I don't see any advantage to compress a payload on the server to decompress and recompress it on HAProxy.

**Comment by anandcta123** [comment]
While sending, large response, it will be sent in multiple buffers. Buffer will be full always(~15KB). In this case, the insert method to modify the response is failing, as no space is available in buffer. Is there any way to insert some data, if the buffer is full?

**Comment by capflam** [comment]
Indeed, to rewrite a message the best, if it is possible, is to properly set ` tune.maxrewrite` parameter. By default it is 1024. But if the part you should insert is too big, you must use a temporary buffer to act as a communicating vase. It is doable of course, but it is not so simple.

**Comment by anandcta123** [comment]
Thanks for your valuable feedback. I have a JS script of 1.3kb and after increasing the tune.maxrewrite to 2kb, looks working fine and I am able to insert the JS script.
But need few clarifications.
1. will changing this value, has any impact on performance or any side effects on the functionality of HaProxy.
2. Actually I need to change this value dynamically whenever my JS script available and I will reset to the default value. Is it possible to change this parameter dynamically in lua.

Regarding compression.
1. If the server response is wholly compressed and it's huge in size, which may be received as multiple buffers. Is it possible to buffer the full response  and perform a decompression on complete response (This is not recommended by you, in previous comments, but in case if customer doesn't want to offload compression, we don't have chance.) Is this possible to achieve in filter or any other technique we should use.
2. If the response is chunked, will the compression happens for each chunk or whole response will be compressed and sent in chunks.

**Comment by capflam** [comment]
>     1. will changing this value, has any impact on performance or any side effects on the functionality of HaProxy.
 
Changing from 1kB to 2kB is not a big deal. It fact, this parameter will reserve some space in the buffer to allow in-place rewrites. In your case, once the rewrite is performed, you can unregistered the filter to speed up transfer, calling `filter:unregister_data_filter()` function in lua. And from this time, the payload will be forwarded regardless the maxrewrite parameter. Of course, it is only applicable if you should not filter the whole payload.

>     2. Actually I need to change this value dynamically whenever my JS script available and I will reset to the default value. Is it possible to change this parameter dynamically in lua.

Unfortunately, it is not possible.

> Regarding compression.
> 
>     1. If the server response is wholly compressed and it's huge in size, which may be received as multiple buffers. Is it possible to buffer the full response  and perform a decompression on complete response (This is not recommended by you, in previous comments, but in case if customer doesn't want to offload compression, we don't have chance.) Is this possible to achieve in filter or any other technique we should use.

In this case, I recommend to bufferize the payload in a lua buffer, draining the HAProxy buffer and re-injecting the uncompressed one at the end. Of course, headers must be updated accordingly first. Technically speaking, it is possible. The API is not truly easy to use to do so, but it is possible. However, it is pretty dangerous. This will consume memory and CPU. The decompression must be interruptible otherwise this will block all other processings on the same thread and at the end the HAProxy watchdog would be triggered, crashing HAProxy itself.

So, to be short, it is possible. The lua filter API may be used to achieve this kind of processing. But you must be extremely careful and aware of limitations. And IMHO, except if you are planning to process only few messages per second, it is a dead end. And I also insist, the decompression must not be a blocking task.
 
Note that the servers will compress a response only if  the `Accept-Encoding` header is passed on the request. Removing it disables the compression on server side. It is exactly what `compression offload` directive do. If it is only a matter of bandwidth for your customers, it is probably easier to convince them this will be the only viable solution. Just my 2 cents

>     2. If the response is chunked, will the compression happens for each chunk or whole response will be compressed and sent in chunks.

The chunking is independent on the compression. The payload is compressed then chunked. The compression is performed on the content. The chunking is just about the transport.

**Comment by anandcta123** [comment]
Thanks for your inputs. 

Changing tune.maxrewrite solved my issue and also I am doing unregister_data_filter after the JS injection. So it is working fine now.

Regarding compression, one thing, I am very much curious to know is, how the HaProxy provided compression filter addresses handling large responses. As per my understanding, compression will be done for whole payload, will this filter also buffers whole response payload and then does a compression?. If so, will the above mention problem, will it not occur with haproxy inbuilt compressor.

**Comment by capflam** [comment]
The compression works in stream mode. Thus, at the end, the whole body is compressed, but it is a continuous process, we just compress data as received and deliver only the compressed part.

**Comment by anandcta123** [comment]
I tried in lua as follows.
1. Collect all the compressed buffer data in a lua buffer,
2. Clear the content of the buffer, till reaching the end of the stream.
3. Decompress lua buffer and compress again.
4. Trying to append the data which is more than 15kb to current buffer.

But this is not working, the response is not sent properly. 

Will you please let me know, how to solve this problem in lua.

As you mentioned, it may be dangerous, but curious to understand the way to do.

**Comment by capflam** [comment]
Well, I'm annoyed because it seems there is flaw in the API. Functions to inject data unconditionally fail if there is not enough free space in the buffer to proceed. However, there is no way to check the free space. So it is not really usable. So I must add a function to do so.
