### ISSUE TITLE
if there are any issues with the code here?

### ISSUE THREAD

**Issue by evan199-9** [haproxy/haproxy#2533]
### Tool Name and Version

None

### Code Report

```plain
When I was reading the code, I found some doubts here. Is the logic here correct?
```

### Additional Information

![1CC042C2-0310-437c-9DF6-84E39E86AF5C](https://github.com/haproxy/haproxy/assets/64507283/f2714189-4dc6-4b78-87d2-7096ecc489c3)
![D0189147-161F-4071-93B4-29C298E05234](https://github.com/haproxy/haproxy/assets/64507283/afd19dab-6675-4cef-a51d-961797c2eee3)

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.0-fdd8154 2023/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.0.html
Running on: Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=24).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by einval22** [comment]
Hi  yeyicong !

Thanks for your report !

For `pat_idx_list_str`  logic seems correct, as  it's a dedicated indexation function for string type ACL patterns like:

```
acl is_match_path -i /first/second/content.html
  use backend  ... if is_match_path
acl is_match_reg path_reg -i .*/updated.*
  use backend  ... if is_match_reg
acl app_front1 hdr_dom(host) -i loadbalancer1.fr
  use_backend ... if app_front1
```

```
int (*const pat_index_fcts[PAT_MATCH_NUM])(struct pattern_expr *, struct pattern *, char **) = {
        ....
	[PAT_MATCH_STR]   = pat_idx_tree_str,
        ....
	[PAT_MATCH_SUB]   = pat_idx_list_str,
	[PAT_MATCH_DIR]   = pat_idx_list_str,
	[PAT_MATCH_DOM]   = pat_idx_list_str,
	[PAT_MATCH_END]   = pat_idx_list_str,
```

As you can see from the code of pattern.c and [pattern.h](https://github.com/haproxy/haproxy/blob/master/include/haproxy/pattern.h#L71) struct pattern is associated with indexation functions. These functions permit to index data according to the type of  pattern and also according to the type of match.

`pat_idx_list_str` obviously is dedicated for strings, => when it takes a `struct pattern` argument  and duplicates it, it allocates a `struct pattern_expr`, that will keep a string, so that is why here:  

patl->pat.ptr.str = malloc(patl->pat.len + 1);

`struct pattern` that describes ACL pattern in its turn contains a union `ptr` to represent patterns of different types: https://github.com/haproxy/haproxy/blob/master/include/haproxy/pattern-t.h#L173

To compare: in `pat_idx_list_ptr`, which is dedicated to index  ACL patterns for binary match (match over raw hex string, PAT_MATCH_BIN) we do:
[patl->pat.ptr.ptr = malloc(patl->pat.len);](https://github.com/haproxy/haproxy/blob/master/src/pattern.c#L1190)

**Comment by einval22** [comment]
I can't see any problems in `pat_prune_gen` as well as it is generic for all pattern types

```
void (*const pat_prune_fcts[PAT_MATCH_NUM])(struct pattern_expr *) = {
	[PAT_MATCH_FOUND] = pat_prune_gen,
	[PAT_MATCH_BOOL]  = pat_prune_gen,
	[PAT_MATCH_INT]   = pat_prune_gen,
	[PAT_MATCH_IP]    = pat_prune_gen,
	[PAT_MATCH_BIN]   = pat_prune_gen,
	[PAT_MATCH_LEN]   = pat_prune_gen,
	[PAT_MATCH_STR]   = pat_prune_gen,
	[PAT_MATCH_BEG]   = pat_prune_gen,
	[PAT_MATCH_SUB]   = pat_prune_gen,
	[PAT_MATCH_DIR]   = pat_prune_gen,
	[PAT_MATCH_DOM]   = pat_prune_gen,
	[PAT_MATCH_END]   = pat_prune_gen,
	[PAT_MATCH_REG]   = pat_prune_gen,
	[PAT_MATCH_REGM]  = pat_prune_gen,
```
As it was mentioned above `struct pattern` that describes ACL pattern contains a union [ptr](https://github.com/haproxy/haproxy/blob/master/include/haproxy/pattern-t.h#L173), that keeps pointers to different types.  Passing `void *ptr` to `free` or `regex_free`  is save enough, as `pat_idx_list_ptr`, `pat_idx_list_str` checks the return of malloc:
https://github.com/haproxy/haproxy/blob/master/src/pattern.c#L1191
https://github.com/haproxy/haproxy/blob/master/src/pattern.c#L1225

Regards,

**Comment by evan199-9** [comment]
Thank you for your reply
In the pat_idx_list_str function, memory was allocated to str, but the content was copied to ptr. We usually assign addresses to whom and copy the content to it. I just found out that the addresses of str and ptr are the same, so this is my problem that I didn't notice before.

**Comment by einval22** [comment]
Hi yeyicong !

Ok, fine! I'm closing this one now.
If you have another questions feel free to ask it in the new issue here.
