### ISSUE TITLE
quic http/3 limited-quic version 2.9.7

### ISSUE THREAD

**Issue by xkid1** [haproxy/haproxy#2544]
### Detailed Description of the Problem

I just want to add quic/http3 version 2.9.7 but still fallback into http/2

### Expected Behavior

should be the protocol  h3 http/3

### Steps to Reproduce the Behavior

1. # apt-get install --no-install-recommends software-properties-common # add-apt-repository ppa:vbernat/haproxy-2.9  # apt-get install haproxy=2.9.\*
2. Enable limited-quic in the global section.
3. Create a QUIC H3 l

### What is your configuration?

```haproxy
global    
   limited-quic


defaults    
    mode http
    log global
    option http-keep-alive    

  
           
frontend all
    bind *:80  
    bind *:443 ssl strict-sni crt /etc/ssl/combined_cert.pem alpn h2
    # Enable HTTP/3
    bind quic4@:443 ssl strict-sni crt /etc/ssl/combined_cert.pem alpn h3 
    http-request redirect scheme https unless { ssl_fc }
    http-after-response add-header alt-svc 'h3=":443"; ma=60'
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.7-1ppa1~jammy 2024/04/06 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.7.html
Running on: Linux 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_OT=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL +OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[  OT] opentracing
	[SPOE] spoe
	[TRACE] trace
```

**Comment by einval22** [comment]
Hi Elmer !

Thanks for reporting this !

Do you see some errors in haproxy logs ?
With which client do you check QUIC connection establishment ? 
Many clients as curl and h2load does not support QUIC out of the box, thus needed to be recompiled with explicit settings for this.
Could you please try to do your test without `strict-sni` settings in your bind lines, please ?

I've just done a quick test with HAProxy version 2.9.7  from haproxy_2.9.7-1ppa1~jammy_amd64.deb + h2load and config settings below: H2 and QUIC protocol support works as expected:

```
global
 ...
 limited-quic
 ...
listen test2
  mode http
  ....
  bind quic4@:443 name quic ssl crt /etc/ssl/frontend/combined.pem alpn h3
  bind *:443 name https ssl crt /etc/ssl/frontend/combined.pem alpn h2
  ...
```

haproxy@lg31:/home/haproxy$ h2load/h2load  https://198.19.0.33:443/?s=4M -t 1 -c 1 -m 1 --npn-list=h3 -n 1
starting benchmark...
spawning thread #0: 1 total client(s). 1 total requests
TLS Protocol: TLSv1.3
Cipher: TLS_AES_256_GCM_SHA384
Server Temp Key: X25519 253 bits
Application protocol: h3
progress: 100% done

finished in 28.01ms, 35.70 req/s, 142.94MB/s
requests: 1 total, 1 started, 1 done, 1 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 4.00MB (4198191) total, 120B (120) headers (space savings 0.00%), 4.00MB (4194304) data
UDP datagram: 222 sent, 3675 received
                     min         max         mean         sd        +/- sd
time for request:    22.56ms     22.56ms     22.56ms         0us   100.00%
time for connect:     5.23ms      5.23ms      5.23ms         0us   100.00%
time to 1st byte:     7.49ms      7.49ms      7.49ms         0us   100.00%
req/s           :      35.91       35.91       35.91        0.00   100.00%

haproxy@lg31:/home/haproxy$ h2load/h2load  https://198.19.0.33:443/?s=4M -t 1 -c 1 -m 1 --npn-list=h2 -n 1
starting benchmark...
spawning thread #0: 1 total client(s). 1 total requests
TLS Protocol: TLSv1.3
Cipher: TLS_AES_256_GCM_SHA384
Server Temp Key: X25519 253 bits
Application protocol: h2
progress: 100% done

finished in 26.49ms, 37.75 req/s, 151.14MB/s
requests: 1 total, 1 started, 1 done, 1 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 4.00MB (4197613) total, 105B (105) headers (space savings 12.50%), 4.00MB (4194304) data
                     min         max         mean         sd        +/- sd
time for request:    21.54ms     21.54ms     21.54ms         0us   100.00%
time for connect:     4.72ms      4.72ms      4.72ms         0us   100.00%
time to 1st byte:     6.54ms      6.54ms      6.54ms         0us   100.00%
req/s           :      38.00       38.00       38.00        0.00   100.00%

Many thanks in advance,
Kind regards,

**Comment by xkid1** [comment]
hello valentine,

Yes, Permission error on QUIC socket binding for proxy all. Consider using setcap cap_net_bind_service (Linux only) or running as root. But I already fixed.

sudo setcap cap_net_bind_service=+ep /path/to/haproxy
sudo systemctl restart haproxy


then from iptables i open the port 443 from udp
