### ISSUE TITLE
add `cap_sys_admin` to setcap supported caps

### ISSUE THREAD

**Issue by sigint2** [haproxy/haproxy#2546]
### Your Feature Request

add `cap_sys_admin` to `setcap` supported caps. This is necessary to support `namespace` on a server socket ( which uses the `setns()` syscall, which requires `cap_sys_admin`.

### What are you trying to do?

Use the new `setcap` feature while supporting `namespace` on a server socket ( which uses the `setns()` syscall at runtime, which requires `cap_sys_admin`. Example:

```
[root@fedora ~]# ip netns add foonet
[root@fedora ~]# ip netns exec foonet ip l set dev lo up
```

haproxy config:

```
frontend foo
	bind 127.0.0.1:1234
	use_backend bar

backend bar
	server test 127.0.0.1:9999 namespace foonet
```

Without `cap_sys_admin` set, you'll get this in the haproxy logs:

```
Cannot get a server socket.
```

With `cap_sys_admin` set, the socket connection works as expected.

### Output of `haproxy -vv`

```plain
HAProxy version 3.0-dev7-0046922 2024/04/06 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 6.5.6-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_PCRE2=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=1).
Built with OpenSSL version : OpenSSL 3.1.1 30 May 2023
Running on OpenSSL version : OpenSSL 3.1.1 30 May 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with network namespace support.
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.1 20240316 (Red Hat 13.2.1-7)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by git001** [comment]
Have you tried to use `setcap cap_sys_admin` in `global` which was added in commit https://github.com/haproxy/haproxy/commit/f0b6436f57db5014eecb5ef365bf278119711e02

**Comment by einval22** [comment]
Hi Noah ! 

Thanks a lot for your report ! 

Yes, we extended a bit Linux capabilities support, as Aleks mentioned above.  Extended in the scope, that now haproxy can also take in account capabilities, put in binary's Permitted set via setcap util. Here is more details about [it](https://github.com/haproxy/haproxy/blob/master/doc/management.txt#L4569), and  also [here](https://github.com/haproxy/haproxy/blob/master/doc/configuration.txt#L2282).  

But for the moment we support only: 
- cap_net_admin
- cap_net_raw (subset of cap_net_admin)
- cap_net_bind_service

So, if in your global section you set `setcap cap_sys_admin` like below, this will not work, as we promote into the process Effective set only capabilities from the our supported list .  Same, if you will start as root and then change the user, while keeping the same setcap setting. Support of the last was added in this [commit](https://github.com/haproxy/haproxy/commit/bd84387beb26591e4dd4b77ecf970a584244973b).   

```
global
  ...
  user sgr
  group sgr
  setcap cap_sys_admin
  ...
```

So, as possible workarounds for the moment:

1. grant a user under which you want to  run haproxy cap_sys_admin capability via /etc/security/capability.conf provided by pam_cap module. More details how this works are [here](https://manpages.ubuntu.com/manpages/bionic/man5/capability.conf.5.html). Then start and run as this user,  no any `setcap` or `user` keywords are not needed in the global section.

2. start and run as root, if you may start haproxy container as a privileged user :-|

I'm looking on cap_sys_admin, as it is the powerful one.  
I'll keep you updated if we will add it in our supported capabilities list.

Kind regards,

**Comment by sigint2** [comment]
I've been using systemd to set the caps as a workaround, but thanks for the other suggestions!

I've tried to think through some potential solutions so that you don't need the `cap_sys_admin` if you have a server namespace, but I'm not sure there is an easy one :-( this mailing thread from a few years ago has some good details on it https://www.mail-archive.com/haproxy@formilux.org/msg40946.html , linking for future reference.

**Comment by einval22** [comment]
Hi Noah !

The support for `cap_sys_admin ` capability was merged in the master branch [here](https://github.com/haproxy/haproxy/commit/5cbb278faed4f40bd84e8e79e414eb6ac474dc8b).  Could you, please, try this branch, if this is possible for you, and provide us a feedback.

You could use it as followed:

```
global
    daemon
    maxconn 65536
    stats socket /tmp/haproxy.sock mode 600 level admin
    user haproxy
    group haproxy
    setcap cap_sys_admin,cap_net_bind_service
    ...

frontend fe_foo
    mode http
    option httplog
    log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
    option logasap
    ....
   
    bind 198.19.0.212:443 namespace front ssl crt /etc/ssl/frontend/combined.pem alpn h2
    ...

backend be_bar
    server node 127.0.0.1:6666 namespace foonet ...
    ....
```
Thanks in advance !
Kind regards,

**Comment by wtarreau** [comment]
And it's now part of 3.0-dev10, which should ease your testing.

**Comment by sigint2** [comment]
This looks great, thanks so much for the quick patch! Tested and confirming everything works as expected. Looking forward to using this.

I think these were nice additions, by the way:
- this is a fatal config parsing error now if you're using `user/group` and drop privileges.
- commit https://github.com/haproxy/haproxy/commit/13ef5524888faf47936ce54a0164dac2689ff7b5 handles `EPERM` and prints a helpful log message.

**Comment by wtarreau** [comment]
Thanks for your test!

You're right regarding the config error, that could be a concern. Ideally we should handle it as we did for the transparent mode, issuing a warning only for the backend side, because it might happen for only one specific backend out of the regular production traffic. Also, the config error will make sure we never meet the EPERM case. Normally haproxy takes great care about allowing to start for the most common case, provided that it manages to bind everything, i.e. if a listener is missing permissions, you should get a hard error, but if a server cannot be reached, it should be a soft error. In any case it's no big deal but I'm concerned about the risk of complicating upgrades.
