### ISSUE TITLE
I am using haproxy service port 3108. How should I use it to send to a different IP band?

### ISSUE THREAD

**Issue by rurusungoa** [haproxy/haproxy#2553]
### Your Feature Request

haproxy - port

### What are you trying to do?

I'm planning to use it with haproxy.
3108 is being used at 172.24.xxx.xxx.
How can I use 3108 with a different IP band?

The incoming IP is the same IP, but I plan to use a different outgoing IP band.

I am using an IP like below.. If I try to use 3108 as a different band IP, how can I use 3108 repeatedly?

frontend out-bof2lfpc-send
    bind :3108
    mode tcp
    option tcplog
    default_backend out-bof2lfpc-send

backend out-bof2lfpc-send
    balance source
    mode tcp
    server     bof2pc 172.24.9x.xxx:3108 check

### Output of `haproxy -vv`

```plain
Currently unable to check.
```

**Comment by wlallemand** [comment]
Please use the discourse https://discourse.haproxy.org/ or the mailing-list https://www.haproxy.org/#tact to ask for help.
Github is dedicated to bugs and features requests for haproxy!

Thanks,

**Comment by rurusungoa** [comment]
After checking, I will upload it to https://discourse.haproxy.org/.

Thanks,
