### ISSUE TITLE
`allow-dup-ip` is ignored if server has `resolvers` and backend has `default-server`

### ISSUE THREAD

**Issue by sigint2** [haproxy/haproxy#2559]
### Detailed Description of the Problem

Hi -- I noticed that `allow-dup-ip` is ignored when:

- a server has a `resolvers` associated with it ( either explicitly, or via a default ), AND
- the backend that the server belongs to has a `default-server` line in it.

### Expected Behavior

That the global `default-server resolve-opts` are not reset by a `default-server` in a backend.

### Steps to Reproduce the Behavior

The following config should illustrate the behavior:

- the backend level `default-server backup` is applied to all servers
- the global `defaults` weight `42` is applied to all servers.
- the global `defaults` field `resolve-opts allow-dup-ip` is not applied ( stats page shows server `app2` in maintenance mode )

```
resolvers test
    parse-resolv-conf

defaults
    mode tcp
    default-server resolvers test resolve-opts allow-dup-ip weight 42

frontend foo
    bind 127.0.0.1:9999
    use_backend bar

backend bar
    default-server backup
    server app1 localhost:9999 no-check
    server app2 localhost:9990 no-check
```

the weight of the servers is overridden with `42` 

### Do you have any idea what may have caused this?

In `src/server.c` the resolve opts seem to get reset to hard-coded values when the above conditions are met, the other option that is reset is `resolve-prefer` .

```
    else {
        *srv = newsrv = &curproxy->defsrv;
        *cur_arg = 1;
        newsrv->resolv_opts.family_prio = AF_INET6;
        newsrv->resolv_opts.accept_duplicate_ip = 0;
    }
```

### What is your configuration?

```haproxy
resolvers test
    parse-resolv-conf

defaults
    mode tcp
    default-server resolvers test resolve-opts allow-dup-ip weight 42

frontend foo
    bind 127.0.0.1:9999
    use_backend bar

backend bar
    default-server backup
    server app1 localhost:9999 no-check
    server app2 localhost:9990 no-check
```

### Output of `haproxy -vv`

```plain
( cannot paste ) -- tested on standard builds of 2.6.15, and 3.0-dev10
```

**Comment by capflam** [comment]
Indeed, it seems you're right. There is no reason to reset resolve options when a `default-server` line is parsed.

**Comment by capflam** [comment]
Fixed now, thanks !

**Comment by capflam** [comment]
Not applicable to 2.2 and 2.0. I'm closing now.
