### ISSUE TITLE
HAProxy forwards authority format URI with differences HTTP Method, in violation of RFC 9110

### ISSUE THREAD

**Issue by vtgsxx** [haproxy/haproxy#2565]
### Detailed Description of the Problem

RFC 9110 defines a method-specific URI form for CONNECT:

Section 9.3.6

> CONNECT uses a special form of request target, unique to this method, consisting of only the host and port number of the tunnel destination, separated by a colon. There is no default port; a client MUST send the port number even if the CONNECT request is based on a URI reference that contains an authority component with an elided port

e.g.

```
CONNECT server.example.com:80 HTTP/1.1
Host: server.example.com
```

Also, it says in Section 7.1:

> ...These forms MUST NOT be used with other methods.

So, HAProxy is obligated to reject requests that do not match that definition

However, HAProxy currently forwards authority format URI with differences HTTP Method when Host header is missing or match the URI, which is a violation of RFC 9110.

### Expected Behavior

HAProxy must reject requests with authority-form URI with HTTP Methods other than CONNECT, also it should reject requests that missing Host header

### Steps to Reproduce the Behavior

1. Build and run HAProxy.
2. Send it the following requests:

```
GET example.com:80 HTTP/1.1\r\n
\r\n
```
or
```
GET example.com:80 HTTP/1.1\r\n
Host: example.com:80\r\n
\r\n
```
or in these requests, the URI not even respect authority format `host:port`
```
GET example.com HTTP/1.1\r\n
\r\n
```
```
GET random HTTP/1.1\r\n
\r\n
```
```
GET random/anything?a=a&b=b HTTP/1.1
\r\n
```
(any HTTP method can be used)

3. Observe that those requests is forwarded verbatim to backend

### Do you have any idea what may have caused this?

HAProxy doesn't check whether current HTTP method is CONNECT when `http_parse_path` in `src/http.c` detect URI is in authority format

### Do you have an idea how to solve the issue?

Accept authority format URI with CONNECT only

### What is your configuration?

```haproxy
global
  log stdout format raw local0
  maxconn 4096

defaults
  mode http
  log global
  timeout connect 5000
  timeout client 10000
  timeout server 10000

frontend front1
  bind *:8080
  default_backend back1

backend back1
  server s1 127.0.0.1:1337 # any address should do
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.7-5742051 2024/04/05 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.7.html
Running on: Linux 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
Running on OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.1 20231014

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

This behavior will cause critical security impact if backend's HTTP parser works inconsistently with HAProxy

For example, some Python server will convert and detect the authority-form URI as path, which will lead to ACL bypass of path rule (tested with Werkzeug, Gunicorn)

app.py
```python
from flask import Flask, request

app = Flask(__name__)

@app.route("/")
def index():
  return "index", 200

@app.route("/admin", methods = ["GET", "POST"])
def admin():
  return request.method + " to " + request.path, 200

@app.route("/admin/secret", methods = ["GET", "POST"])
def secret():
  return request.method + " to " + request.path \
  + " with " + " ".join(k + "=" + v for k,v in request.args.items()), 200

if __name__ == "__main__":
  app.run("127.0.0.1", 1337)

```

haproxy.conf
```
global
  log stdout format raw local0
  maxconn 4096

defaults
  mode http
  log global
  timeout connect 5000
  timeout client 10000
  timeout server 10000

frontend front1
  bind *:8080
  default_backend back1

backend back1
  http-request deny if { path,url_dec -i -m sub admin }
  server s1 127.0.0.1:1337
```

```
$ printf "GET /admin HTTP/1.1\r\n\r\n" | ncat 127.0.0.1 8080
HTTP/1.1 403 Forbidden
content-length: 93
cache-control: no-cache
content-type: text/html

<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```
```
$ printf "GET admin HTTP/1.1\r\n\r\n" | ncat 127.0.0.1 8080 
HTTP/1.1 200 OK
server: Werkzeug/2.2.2 Python/3.11.6
date: REDACTED
content-type: text/html; charset=utf-8
content-length: 13

GET to /admin                                                                                                                    
```
```
$ printf "POST admin HTTP/1.1\r\n\r\n" | ncat 127.0.0.1 8080
HTTP/1.1 200 OK
server: Werkzeug/2.2.2 Python/3.11.6
date: REDACTED
content-type: text/html; charset=utf-8
content-length: 14

POST to /admin
```
```
$ printf "GET /admin/secret?a=a&b=b HTTP/1.1\r\n\r\n" | ncat 127.0.0.1 8080
HTTP/1.1 403 Forbidden
content-length: 93
cache-control: no-cache
content-type: text/html

<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```
```
$ printf "GET admin/secret?a=a&b=b HTTP/1.1\r\n\r\n" | ncat 127.0.0.1 8080
HTTP/1.1 200 OK
server: Werkzeug/2.2.2 Python/3.11.6
date: REDACTED
content-type: text/html; charset=utf-8
content-length: 33

GET to /admin/secret with a=a b=b
```

**Comment by wtarreau** [comment]
Thanks for your report. I'm wondering when we broke that, we'll have a look.

**Comment by wtarreau** [comment]
So we had a look and actually it's not an authority that is passed, it's the path, and it's not modified along the path. If you replace the server behind with a standard netcat, you'll see that "GET admin" is sent as-is, there's no transformation such as prepending a slash. It's basically as if you were passing through a TCP proxy. It's still supported for historical/legacy reasons (normally paths should either begin with '/' or be exactly '*' but only for the OPTIONS method).

One could argue that this could expose vulnerable servers, such as the one you're showing that is incorrectly prepending a '/' in front of the requests it receives, but one could also argue that the goal of a reverse proxy is to be the most transparent possible and not necessarily to try to plug all possible holes of servers behind.

We've discussed about possibly enforcing '/' or '*' by default for paths in 3.1, that could be an acceptable breaking change I think, given that broken applications relying on paths not starting with '/' should not exist anymore.

**Comment by vtgsxx** [comment]
> So we had a look and actually it's not an authority that is passed, it's the path, and it's not modified along the path. If you replace the server behind with a standard netcat, you'll see that "GET admin" is sent as-is, there's no transformation such as prepending a slash. It's basically as if you were passing through a TCP proxy. It's still supported for historical/legacy reasons (normally paths should either begin with '/' or be exactly '*' but only for the OPTIONS method).
> 
> One could argue that this could expose vulnerable servers, such as the one you're showing that is incorrectly prepending a '/' in front of the requests it receives, but one could also argue that the goal of a reverse proxy is to be the most transparent possible and not necessarily to try to plug all possible holes of servers behind.
> 
> We've discussed about possibly enforcing '/' or '*' by default for paths in 3.1, that could be an acceptable breaking change I think, given that broken applications relying on paths not starting with '/' should not exist anymore.

I see that in `include/haproxy/http.h`, the [http_uri_parser_init](https://git.haproxy.org/?p=haproxy-2.9.git;a=blob;f=include/haproxy/http.h;h=299264051d28e4bcace2c07e98df276123c8c3b3;hb=HEAD#l141) will set `parser.format` to `URI_PARSER_FORMAT_ABSURI_OR_AUTHORITY` if first character of URI not start with `*` or `/`

Latterly, in `src/http.c` if the [http_parse_path](https://git.haproxy.org/?p=haproxy-2.9.git;a=blob;f=src/http.c;h=9599e0eb586ab2527ec4b59dcfbde024f3b05244;hb=HEAD#l635) doesn't found a scheme (using [http_parse_scheme](https://git.haproxy.org/?p=haproxy-2.9.git;a=blob;f=src/http.c;h=9599e0eb586ab2527ec4b59dcfbde024f3b05244;hb=HEAD#l543) ), then it indicates that the URI is in authority format and the path won't be present

So with "GET admin", HAProxy currently doesn't see "admin" as path (this is why ACL path rule will not detect "admin" to reject the request), or am I in a mistaken way?
![image](https://github.com/haproxy/haproxy/assets/63993564/837ea7f8-fce4-4510-a943-40b5eab45ce3)

**Comment by wtarreau** [comment]
These tests are more surface tests than anything else. Internally the whole URI is conveyed along the path, and it is analyzed by the various parts that need it (e.g. path() sample fetch function, etc). If, for example, you observe the same request received over H1 and forwarded over H2, you'll see it split this way (and rejected by the next hop since the path does not start with / and is not *):
```
[00|h2|1|mux_h2.c:5308] h2c_dec_hdrs(): h2c=0x122a2d0(F,FRP) dsi=1 rcvh :method: GET
[00|h2|1|mux_h2.c:5308] h2c_dec_hdrs(): h2c=0x122a2d0(F,FRP) dsi=1 rcvh :scheme: https
[00|h2|1|mux_h2.c:5308] h2c_dec_hdrs(): h2c=0x122a2d0(F,FRP) dsi=1 rcvh :path: admin
```
We've seen what can be cleaned up, but again, it really has no impact beyond not being pretty.

**Comment by vtgsxx** [comment]
I see your point. Thanks.

**Comment by capflam** [comment]
Some patches were pushed to fix this issue. With Willy, we decided to be stricter on the target request parsing. So, it should be good now. However, the main fix will not be backported because it is a breaking change. And it is still annoying to perform this kind of changes in stable versions. Thanks !

**Comment by t101804** [comment]
> > So we had a look and actually it's not an authority that is passed, it's the path, and it's not modified along the path. If you replace the server behind with a standard netcat, you'll see that "GET admin" is sent as-is, there's no transformation such as prepending a slash. It's basically as if you were passing through a TCP proxy. It's still supported for historical/legacy reasons (normally paths should either begin with '/' or be exactly '*' but only for the OPTIONS method).
> > 
> > One could argue that this could expose vulnerable servers, such as the one you're showing that is incorrectly prepending a '/' in front of the requests it receives, but one could also argue that the goal of a reverse proxy is to be the most transparent possible and not necessarily to try to plug all possible holes of servers behind.
> > 
> > We've discussed about possibly enforcing '/' or '*' by default for paths in 3.1, that could be an acceptable breaking change I think, given that broken applications relying on paths not starting with '/' should not exist anymore.
> 
> I see that in `include/haproxy/http.h`, the [http_uri_parser_init](https://git.haproxy.org/?p=haproxy-2.9.git;a=blob;f=include/haproxy/http.h;h=299264051d28e4bcace2c07e98df276123c8c3b3;hb=HEAD#l141) will set `parser.format` to `URI_PARSER_FORMAT_ABSURI_OR_AUTHORITY` if first character of URI not start with `*` or `/`
> 
> Latterly, in `src/http.c` if the [http_parse_path](https://git.haproxy.org/?p=haproxy-2.9.git;a=blob;f=src/http.c;h=9599e0eb586ab2527ec4b59dcfbde024f3b05244;hb=HEAD#l635) doesn't found a scheme (using [http_parse_scheme](https://git.haproxy.org/?p=haproxy-2.9.git;a=blob;f=src/http.c;h=9599e0eb586ab2527ec4b59dcfbde024f3b05244;hb=HEAD#l543) ), then it indicates that the URI is in authority format and the path won't be present
> 
> So with "GET admin", HAProxy currently doesn't see "admin" as path (this is why ACL path rule will not detect "admin" to reject the request), or am I in a mistaken way?
> ![image](https://github.com/haproxy/haproxy/assets/63993564/837ea7f8-fce4-4510-a943-40b5eab45ce3)
> 

just asking, what IDE are you using

**Comment by vtgsxx** [comment]
> just asking, what IDE are you using

@t101804 it's CLion
