### ISSUE TITLE
DOC: aes_gcm_enc should describe "encrypt" instead of "decrypt"

### ISSUE THREAD

**Issue by NickMRamirez** [haproxy/haproxy#2577]
### Detailed Description of the Problem

The fetch `aes_gcm_enc` describes "Decrypt", but should describe "Encrypt". 

> Decrypts the raw byte input using the AES128-GCM, AES192-GCM or AES256-GCM algorithm, depending on the <bits> parameter. <nonce> and <key> parameters must be base64 encoded. Last parameter, <aead_tag>, must be a variable. The AEAD tag will be stored base64 encoded into that variable. The returned result is in raw byte format. The <nonce> and <key> can either be strings or variables. This converter requires at least OpenSSL 1.0.1.
>
> ```
>http-response set-header X-Encrypted-Text %[var(txn.plain),\
>  aes_gcm_enc(128,txn.nonce,Zm9vb2Zvb29mb29wZm9vbw==,txn.aead_tag)]
>```

https://docs.haproxy.org/dev/configuration.html#aes_gcm_enc

### Expected Behavior

The reason I believe it should describe "Encrypt" is that the function name ends with `enc`, and the example shows `X-Encrypted-Text` as the output.

### Steps to Reproduce the Behavior

n/a

### What is your configuration?

```haproxy
n/a
```

### Output of `haproxy -vv`

```plain
n/a
```

**Comment by wtarreau** [comment]
Thanks for the report, Nick! Now fixed, thank you!
