### ISSUE TITLE
version 2.4  use_promex compatibility issue with RHEL8 

### ISSUE THREAD

**Issue by sdpdb** [haproxy/haproxy#2580]
### Detailed Description of the Problem

Version 2.4 is not compatible with RHEL8

### Expected Behavior

Hi Team, 

we are trying to upgrade HaProxy version 2.4 or above on RHEL8 system, as it is support inbuild Prometheus Exporter.
we have successfully installed 2.4 version but after adding "Enable Prometheus Exporter" configuration in haproxy.cfg file haproxy service not running healthy. 

### Steps to Reproduce the Behavior

Install 2.4 on RHEL8 and try to enable Prometheus Exporter

### Do you have any idea what may have caused this?

no

### Do you have an idea how to solve the issue?

no

### What is your configuration?

```haproxy
its simple standard, below things we have added in lister part of haproxy config:

#frontend stats
    bind *:8404
# Enable Prometheus Exporter
    http-request use-service prometheus-exporter if { path /metrics }
    stats enable
    stats uri /stats
    stats refresh 10s
```

### Output of `haproxy -vv`

```plain
haproxy -vv
HAProxy version 2.4.0-6cbbecf 2021/05/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.0.html
Running on: Linux 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Thu Feb 2 13:01:45 EST 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.1 20191121 (Red Hat 8.3.1-5)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by sdpdb** [comment]
-- Subject: Unit haproxy.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit haproxy.service has begun starting up.
May 28 07:42:15 hostname haproxy[219915]: [ALERT]    (219915) : parsing [/etc/haproxy/haproxy.cfg:46] : error detected in proxy 'stats' while parsing 'http-request use-service' rule : 'prometheus-exporter' unknown service name..
May 28 07:42:15 hostname haproxy[219915]: [ALERT]    (219915) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
May 28 07:42:15 hostname systemd[1]: haproxy.service: Control process exited, code=exited status=1
May 28 07:42:15 hostname systemd[1]: haproxy.service: Failed with result 'exit-code'.

**Comment by git001** [comment]
Well first of all please update to the latest 2.4 or better 2.8!

From http://www.haproxy.org/bugs/bugs-2.4.0.html
> HAProxy known bugs for version v2.4.0 (maintenance branch 2.4) :  635

Second prometheus is not in the haproxy build https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint

From the output of `haproxy -vv`
> -PROMEX

The solution is to use a recent HAProxy version with promtheus service  in HAProxy :smiley:

**Comment by sdpdb** [comment]
Thanks for the immediate update,  

let me go through with your comment and try to understand it.

Meanwhile can you please to get the latest Haproxy 2.8 version rpm which is compatible with RHEL8. 

Thanks !

**Comment by git001** [comment]
> Meanwhile can you please to get the latest Haproxy 2.8 version rpm which is compatible with RHEL8.

As I don't use rpm based system I can't suggest anything.  
Maybe there is a 2.8 rpm in the current repo which you already use. :shrug:

**Comment by capflam** [comment]
I'm closing this issue because we don't maintain HAProxy's RPMs and there is no bug with HAProxy here. However, you can request some help on the mailing list :  [haproxy@formilux.org](mailto:haproxy@formilux.org). Thanks !
