### ISSUE TITLE
[arm64,musl,docker] Kernel warning: `haproxy' uses 32-bit capabilities (legacy support in use)

### ISSUE THREAD

**Issue by krezovic** [haproxy/haproxy#2590]
### Detailed Description of the Problem

When running latest haproxy lts branch (3.0 according to version), kernel will output a warning in dmesg

```
[1710243.523230] capability: warning: `haproxy' uses 32-bit capabilities (legacy support in use)
```

I assume it is harmless, but a clarification in the docs would be nice. An example on how ISC handled similar warning in "bind9" may be seen at the [ISC KB entry](https://kb.isc.org/docs/aa-00823)

### Expected Behavior

Before switching to lts 3.0 branch, I saw no such message. I'd expect to:

- not see it at all
- find a relevant entry in haproxy documentation that explains the issue is harmless

### Steps to Reproduce the Behavior

I run haproxy:lts-alpine docker image on arm64 machine. I assume similar behavior will occur on x86_64 machine. Please note that warning will only be printed once per kernel boot. You'd have to reboot the machine when debugging.

```
docker run --rm -v ./sample-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg haproxy:lts-alpine
```

### What is your configuration?

```haproxy
global
  log stdout format raw local0 info
  maxconn 50

defaults
  mode http
  timeout client 10s
  timeout connect 5s
  timeout server 10s
  timeout http-request 10s
  log global

frontend prometheus
  bind *:443
  option httplog
  http-request set-log-level silent if TRUE
  http-request use-service prometheus-exporter
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.0-5590ada 2024/05/29 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.0.html
Running on: Linux 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64
Build options :
  TARGET  = linux-musl
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.3.0 9 Apr 2024
Running on OpenSSL version : OpenSSL 3.3.0 9 Apr 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.43 2024-02-16
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.1 20240309

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by einval22** [comment]
Hello Armin !

Thanks for reporting this !

Yes, this kernel warning is harmless. I will add some notes about it in our Management guide [here](https://docs.haproxy.org/dev/management.html#13.1).

Linux capabilities was added since the 29 of August 2023, and now all `linux-*` targets from our Makefile automatically enable this support at compile time, see more details in this initial [commit](https://github.com/haproxy/haproxy/commit/bd84387beb26591e4dd4b) and [here](https://github.com/haproxy/haproxy/blob/master/Makefile#L397).

We are using `_LINUX_CAPABILITY_VERSION_1` for  compatibility reasons and it is more easy to parse, than the 64-bit `_LINUX_CAPABILITY_VERSION_3`.

Hope this clarifies a bit.

Kind regards,

**Comment by einval22** [comment]
> Before switching to lts 3.0 branch, I saw no such message.

BTW, which version did you use before the upgrade ?

BR,

**Comment by ZIRAKrezovic** [comment]
> > Before switching to lts 3.0 branch, I saw no such message.
> 
> BTW, which version did you use before the upgrade ?
> 
> BR,

Hi. I was using previous LTS branch, I believe it was 2.8 ?

**Comment by Darlelet** [comment]
After quick bisect (thanks @krezovic for the easy reproducer), first "bad" commit seems to be: f0b6436f5
(first commit where the warning is emitted by the kernel when haproxy is started)

**Comment by einval22** [comment]
> > > Before switching to lts 3.0 branch, I saw no such message.
> > 
> > 
> > BTW, which version did you use before the upgrade ?
> > BR,
> 
> Hi. I was using previous LTS branch, I believe it was 2.8 ?

Yes 2.8 LTS does not contain this feature.

**Comment by einval22** [comment]
Hello Armin !

We've started to use LINUX_CAPABILITIES_VERSION3, which does not trigger any warning, more details are available  [here](https://github.com/haproxy/haproxy/commit/fba9ade8910510151b5d6141c6594da789d6a71b)

So, you will get rid of this warning in the next  release, or you may try now the latest dev version ( use with caution in production env ).

Kind regards,

**Comment by einval22** [comment]
I think we can close this.
Please, feel free to reopen if some more questions.

**Comment by krezovic** [comment]
Thanks for the fix. I have not yet had the time to try it out but will do so probably over the weekend.
