### ISSUE TITLE
Add io_uring to haproxy

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#2591]
### Your Feature Request

Check if io_uring could be a benefit for haproxy [an extensive guide to the io_uring API](https://nick-black.com/dankwiki/index.php/Io_uring)

### What are you trying to do?

Improve performance of haproxy.

### Output of `haproxy -vv`

```plain
Future version
```

**Comment by wlallemand** [comment]
We already look at this in the past, I can't really say if that would be useful to haproxy or not, but this would require a lot of rework, I won't expect it to be done in a while given the unknown benefits.

**Comment by git001** [comment]
Okay, thanks for answer.
