### ISSUE TITLE
Layer4 connection problem, info: "Connection refused"

### ISSUE THREAD

**Issue by zhaochunxue** [haproxy/haproxy#2593]
I want to use haproxy as redis proxy
backend redis is ok
![image](https://github.com/haproxy/haproxy/assets/64675999/fb642f22-bb1d-47ea-8f23-b6a8045c293f)
but front port 16379 is unsable
![image](https://github.com/haproxy/haproxy/assets/64675999/8dfa111a-e146-49b6-aeac-d8d348b85130)

### this is my log
2024-06-05 17:38:09 [NOTICE]   (1) : haproxy version is 2.9.7-5742051
2024-06-05 17:38:09 [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
2024-06-05 17:38:09 [WARNING]  (1) : Exiting Master process...
2024-06-05 17:38:09 [WARNING]  (10) : Proxy http stopped (cumulated conns: FE: 0, BE: 0).
2024-06-05 17:38:09 [WARNING]  (10) : Proxy redis-read stopped (cumulated conns: FE: 0, BE: 0).
2024-06-05 17:38:09 [WARNING]  (10) : Proxy stats stopped (cumulated conns: FE: 0, BE: 0).
2024-06-05 17:38:09 [WARNING]  (10) : Proxy redis-online stopped (cumulated conns: FE: 0, BE: 0).
2024-06-05 17:38:09 [WARNING]  (1) : Current worker (10) exited with code 0 (Exit)
2024-06-05 17:38:09 [WARNING]  (1) : All workers exited. Exiting... (0)
2024-06-05 17:38:10 [NOTICE]   (1) : New worker (10) forked
2024-06-05 17:38:10 [NOTICE]   (1) : Loading success.
2024-06-05 17:38:10 [WARNING]  (10) : Server redis-online/redis-1 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 5ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
2024-06-05 17:38:11 [WARNING]  (10) : Server redis-online/redis-2 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 4ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
2024-06-05 17:38:11 [ALERT]    (10) : backend 'redis-online' has no server available!

### tihis is my configuration
global
    daemon
    maxconn 5000

defaults
    mode tcp
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms
frontend http
    bind :8080
    default_backend stats

backend stats
    mode http
    stats enable
    stats enable
    stats uri /
    stats refresh 1s
    stats show-legends
    stats admin if TRUE

frontend redis-read
  bind *:16379
  mode tcp
  default_backend redis-online

backend redis-online
  mode tcp
  balance roundrobin
  server redis-1 127.0.0.1:6379 check port 6379 maxconn 5000 check inter 2s
  server redis-2 127.0.0.1:6380 check port 6380 maxconn 5000 check inter 2s

### this is my version
haproxy -vv
HAProxy version 2.9.7-5742051 2024/04/05 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.7.html
Running on: Linux 6.4.16-linuxkit #1 SMP PREEMPT Wed Oct 25 16:32:24 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.0.11 19 Sep 2023
Running on OpenSSL version : OpenSSL 3.0.11 19 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace

**Comment by wlallemand** [comment]
For configuration assistance please use the discourse https://discourse.haproxy.org/ or the mailing-list https://www.haproxy.org/#tact.
Github is dedicated to bugs and features requests for haproxy!

Thanks,
