### ISSUE TITLE
DOC: In doc/configuration.txt, entries in "5.1 Bind options" are out of order.

### ISSUE THREAD

**Issue by ldurway24** [haproxy/haproxy#2594]
### Detailed Description of the Problem

DOC: In version 3.0 doc/configuration.txt, these entries in "5.1 Bind options" are out of alphabetical order: 

- curves
- ecdhe
- severity-output
- v4v6
- v6only

### Expected Behavior

Bind options should be in alpha order.

### Steps to Reproduce the Behavior

Display doc/configuration.txt.

### What is your configuration?

```haproxy
No config. Just looking at text file.
```

### Output of `haproxy -vv`

```plain
3.0
```

**Comment by wlallemand** [comment]
Thanks, fixed !
