### ISSUE TITLE
dns resolver fails to resolve 1 of 2 servers in the same backend

### ISSUE THREAD

**Issue by oovs** [haproxy/haproxy#26]
## Output of `haproxy -vv` and `uname -a`
```
HA-Proxy version 1.8.12-1~jessie 2018/06/27
Copyright 2000-2018 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.1t  3 May 2016
Running on OpenSSL version : OpenSSL 1.0.2l  25 May 2017 (VERSIONS DIFFER!)
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.35 2014-04-04
Running on PCRE version : 8.35 2014-04-04
PCRE library supports JIT : yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
```
```
Linux haproxy33 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux
```

## What's the configuration?
```
resolvers localdns
    nameserver local01 127.0.0.1:53
...
backend test_dns
    default-server init-addr none resolvers localdns
    server foo-bar-01-13653  foo-bar-01.domain:13653 check
    server  foo-bar-01-52393  foo-bar-01.domain:52393 check
```

## Steps to reproduce the behavior
1. Add 2 servers with the same fqdn to the single backend with run time dns resolver configured
2. Restart `haproxy`
3. Check if both servers' fqdns being resolved and available: `show servers state`

## Actual behavior
One of servers is in failed state due to resolution error (`srv_op_state`: 32):
```
$ socat haproxy.sock - <<< "show servers state" | grep foo-bar
10 test_dns 1 foo-bar-01-13653 10.10.10.10 2 0 1 1 685 15 3 4 6 0 0 0 foo-bar-01.domain 13653
10 test_dns 2 foo-bar-01-52393 - 0 32 1 1 685 1 0 0 14 0 0 0 foo-bar-01.domain 52393
```

Also, half dns requests marked as failed:
```
Resolvers section localdns
 nameserver local01:
  sent:        270
  snd_error:   0
  valid:       135
  update:      1
  cname:       0
  cname_error: 0
  any_err:     135
  nx:          0
  timeout:     0
  refused:     0
  other:       0
  invalid:     0
  too_big:     0
  truncated:   0
  outdated:    0
```
According to tcpdump `haproxy` tries to make AAAA request mark response as failed (`any_err`) and only then performs failback to the A request.

## Expected behavior
Both declared servers' fqdns being successfully resolved in runtime.

**Comment by wtarreau** [comment]
Konstantin, your version is affected by numerous DNS bugs as well as two important security issues, as reported here : http://www.haproxy.org/bugs/bugs-1.8.12.html

Please first update it to latest 1.8 and check again.

**Comment by git001** [comment]
@o0st you can use this repo link for your debian to install the latest 1.8 stable version.

https://haproxy.debian.net/#?distribution=Debian&release=jessie&version=1.8

**Comment by oovs** [comment]
Thanks for hints, I've tried to upgrade but behavior is the same.

## Output of `haproxy -vv`
```
HA-Proxy version 1.8.17-1~bpo8+1 2019/01/17
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2l  25 May 2017
Running on OpenSSL version : OpenSSL 1.0.2l  25 May 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.35 2014-04-04
Running on PCRE version : 8.35 2014-04-04
PCRE library supports JIT : yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
```

**Comment by bedis** [comment]
Hi,

What does a "dig foo-bar-01.domain @127.0.0.1:53" returns?

**Comment by bedis** [comment]
About the AAAA tried first, this is expected behavior. HAProxy picks up IPv6 first.
If your network uses only IPv4, then you can add the following parameter on the server line: "resolve-prefer ipv4"
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-resolve-prefer

**Comment by bedis** [comment]
Last, if your DNS server returns 1 record, HAProxy will apply it to one server only.
HAProxy, by default, prevent duplication of the records. This is to match the scale out environments such as kubernetes: we do pre-provision servers in a backend but don't give them an IP address at start up.

Now, if your server returns a single IP address, you can enable this configuration option: "resolve-opts allow-dup-ip", and then, HAProxy will allow itself to reuse the same IP address on multiple servers.
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-resolve-opts

Note that later, the resolve-prefer would be deprecated and should move into the resolve-opts, to make it cleaner. 

Given 1 record for the hostname used in my configuration:
* When I start your HAProxy config without the option above, I can see your behavior:
[WARNING] 030/083248 (20646) : test_dns/foo-bar-01-13653 changed its IP from  to 10.42.3.1 by localdns/local01.
[WARNING] 030/083248 (20646) : Server test_dns/foo-bar-01-13653 administratively READY thanks to valid DNS answer.

* when I enable the option, I can see the following:
[WARNING] 030/083317 (20719) : test_dns/foo-bar-01-13653 changed its IP from  to 10.42.3.1 by localdns/local01.
[WARNING] 030/083317 (20719) : Server test_dns/foo-bar-01-13653 administratively READY thanks to valid DNS answer.
[WARNING] 030/083317 (20719) : test_dns/foo-bar-01-52393 changed its IP from  to 10.42.3.1 by DNS cache.
[WARNING] 030/083317 (20719) : Server test_dns/foo-bar-01-52393 administratively READY thanks to valid DNS answer.

**Comment by oovs** [comment]
@bedis yes, DNS returns single A record.
`resolve-prefer ipv4` removed the `any_err` errors from resolver status.
`resolve-opts allow-dup-ip` fixed dns resolution issue.
I'm closing issue since it's not a bug.
Thank you for help.
