### ISSUE TITLE
Backporting "map_*_key Converters" for Version 2.8.x

### ISSUE THREAD

**Issue by ygkat** [haproxy/haproxy#2610]
### Your Feature Request

ref : https://github.com/haproxy/haproxy/commit/ca4758378788ee6a9b774590badbaa12d356e186

### What are you trying to do?

We are currently using version 2.8.x, and since the feature has not been backported, I have been creating separate patch files and applying them manually every time the version is updated.

Please review whether official backporting to version 2.8.x is possible.

### Output of `haproxy -vv`

```plain
not neccesary
```

**Comment by wlallemand** [comment]
We don't backport features in stable branches. Stable branches are meant for maintenance, so only bugs are fixed there. People that want stable branches with backported features could consider HAProxy Enterprise, though.
