### ISSUE TITLE
Using rfc5424 log format leads to incomplete/merged log lines

### ISSUE THREAD

**Issue by fabfurnari** [haproxy/haproxy#2612]
### Detailed Description of the Problem

When using the rfc5424 log format with a `log-format-sd %{+E}o ...` directive sometimes two different log lines are "joined" together, probably due to an unescaped character that breaks the rest of the log line.

### Expected Behavior

Each log line should be correctly terminated

### Steps to Reproduce the Behavior

Unfortunately it's not possible for me to exactly replicate the request that triggers this behavior, but see logs below for an example

### Do you have any idea what may have caused this?

Don't know if this could be related to these 2 bug (already fixed):

* https://git.haproxy.org/?p=haproxy-2.6.git;a=commitdiff;h=bb8b763
* https://git.haproxy.org/?p=haproxy-2.6.git;a=commitdiff;h=52d92de

### What is your configuration?

```haproxy
global
    user haproxy
    group haproxy
    log 127.0.0.1:1221 len 16384 format rfc5424 local0 info
    # do not keep old processes longer than 5m after a reload
    hard-stop-after 5m
    set-dumpable
    nbthread 48

defaults
    mode       http
    log-format "%rt %Tr %Tw %Tc %ST {%[capture.req.hdr(0)]} {%[capture.res.hdr(0)]} %ts"
    log-format-sd %{+E}o\ [customlog\ haproxy_pid=\"%pid\"\ ip=\"%ci\"\ sequence=\"%ID\"\ accept_date=\"%tr\"\ time_backend_response=\"%Tr\"\ http_status=\"%ST\"\ response_size=\"%B\"\ termination_state=\"%ts\"\ uri_host=\"%[capture.req.hdr(0)]\"\ referer=\"%[capture.req.hdr(1)]\"\ user_agent=\"%[capture.req.hdr(2)]\"\ accept_language=\"%[capture.req.hdr(3)]\"\ range=\"%[capture.req.hdr(4)]\"\ accept=\"%[capture.req.hdr(5)]\"\ tls=\"%[capture.req.hdr(6)]\"\ cache_status=\"%[capture.res.hdr(0)]\"\ content_type=\"%[capture.res.hdr(1)]\"\ x_analytics=\"%[capture.res.hdr(2)]\"\ x_cache=\"%[capture.res.hdr(3)]\"\ backend=\"%[capture.res.hdr(4)]\"\ http_method=\"%HM\"\ uri_path=\"%HPO\"\ uri_query=\"%HQ\"]
    option     dontlognull
    option     accept-invalid-http-request
    option     accept-invalid-http-response
    option     http-ignore-probes
    retries    1
    timeout    connect 50000
    timeout    client 500000
    timeout    server 500000

```
```


### Output of `haproxy -vv`

```plain
HAProxy version 2.8.10-1~bpo11+1 2024/06/16 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.10.html
Running on: Linux 5.10.0-30-amd64 #1 SMP Debian 5.10.218-1 (2024-06-01) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=96).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110


Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

An example log line that should be splitted (notice the abrupt truncation in the `query_string` field `...versio<134>...`:

```
<134>1 2024-06-19T15:42:31.440224+00:00 - haproxy 1227962 - [customlog haproxy_pid="1227962" ip="<REDACTED>" sequence="1582219" accept_date="19/Jun/2024:15:42:30.993" time_backend_response="287" http_status="200" response_size="301073" termination_state="--" uri_host="be-tarask.wikipedia.org" referer="https://be-tarask.wikipedia.org/wiki/%D0%92%D1%96%D0%BA%D1%96%D0%BF%D1%8D%D0%B4%D1%8B%D1%8F:%D0%9F%D1%80%D0%B0%D0%B5%D0%BA%D1%82:%D0%A2%D1%8D%D0%BC%D0%B0%D1%82%D1%8B%D1%87%D0%BD%D1%8B_%D1%82%D1%8B%D0%B4%D0%B7%D0%B5%D0%BD%D1%8C/%D0%90%D1%80%D1%88%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%B1%D1%96%D1%82%D0%B2%D0%B0" user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15 (Applebot/0.1; +http://www.apple.com/go/applebot)" accept_language="en-US" range="-" accept="*/*" tls="vers=TLSv1.3;keyx=UNKNOWN;auth=ECDSA;ciph=AES-256-GCM-SHA384;prot=h1;sess=new" cache_status="miss" content_type="text/javascript; charset=" x_analytics="WMF-Last-Access=19-Jun-2024;WMF-Last-Access-Global=19-Jun-2024;https=1;client_port=35204" x_cache="cp4044 miss, cp4044 miss" backend="mw-web.codfw.main-7666f67487-nw9fq" http_method="GET" uri_path="/w/load.php" uri_query="?lang=be-tarask&modules=ext.categoryTree%2CeventLogging%2CnavigationTiming%2Cpopups%2CwikimediaEvents%7Cext.centralNotice.choiceData%2Cdisplay%2CgeoIP%2CimpressionDiet%2CkvStore%2CstartUp%7Cext.centralauth.centralautologin%7Cext.checkUser.clientHints%7Cext.cx.eventlogging.campaigns%7Cext.discussionTools.init%2Cminervaicons%7Cext.echo.centralauth%7Cext.uls.interface%2Cpreferences%2Cwebfonts%7Cext.urlShortener.toolbar%7Cjquery%2Cmoment%2Coojs%2Coojs-ui-core%2Coojs-ui-windows%2Crangefix%2Csite%7Cjquery.client%2CtextSelection%7Cmediawiki.String%2CTitle%2CUri%2Capi%2Cbase%2Ccldr%2Ccookie%2Cexperiments%2CjqueryMsg%2Clanguage%2Crouter%2Cstorage%2Ctoc%2Cuser%2Cutil%2CvisibleTimeout%7Cmediawiki.editfont.styles%7Cmediawiki.libs.pluralruleparser%7Cmediawiki.page.media%2Cready%7Cmediawiki.page.watch.ajax%7Cmmv.bootstrap%2Ccodex%2Chead%7Cmmv.bootstrap.autostart%7Coojs-ui-windows.icons%7Cskins.vector.clientPreferences%2Cjs%7Cskins.vector.icons.js&skin=vector-2022&versio<134>1 2024-06-19T15:42:31.441664+00:00 - haproxy 1227962 - [customlog haproxy_pid="1227962" ip="<REDACTED>" sequence="1582448" accept_date="19/Jun/2024:15:42:31.440" time_backend_response="1" http_status="200" response_size="17243" termination_state="--" uri_host="en.m.wikipedia.org" referer="https://en.m.wikipedia.org/wiki/13th_Amendment_to_the_United_States_Constitution" user_agent="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36" accept_language="en-US,en;q=0.9" range="-" accept="text/css,*/*;q=0.1" tls="vers=TLSv1.3;keyx=UNKNOWN;auth=ECDSA;ciph=AES-256-GCM-SHA384;prot=h2;sess=new" cache_status="hit-front" content_type="text/css; charset=utf-8" x_analytics="WMF-Last-Access=19-Jun-2024;WMF-Last-Access-Global=19-Jun-2024;https=1;client_port=39466" x_cache="cp4044 hit, cp4044 hit/1766" backend="ATS/9.1.4" http_method="GET" uri_path="/w/load.php" uri_query="?lang=en&modules=ext.cite.styles%7Cext.relatedArticles.styles%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cmediawiki.hlist%7Cmobile.init.styles%7Cskins.minerva.amc.styles%7Cskins.minerva.base.styles%7Cskins.minerva.codex.styles%7Cskins.minerva.content.styles.images%7Cskins.minerva.icons.wikimedia%7Cskins.minerva.mainMenu.icons%2Cstyles%7Cwikibase.client.init&only=styles&skin=minerva"] 1582448 1 0 0 200 {en.m.wikipedia.org} {hit-front} -
```

We've observed this behavior in query strings or referrer fields, as they are more prone than other headers to include "problematic" characters.

**Comment by Darlelet** [comment]
Did you face this behavior when upgrading from a previous working version regarding this issue?

I took a look at the commits you've mentioned, but unfortunately I don't see a relationship with the issue you're describing. They should not affect how invalid characters are encoded. (e.g.: non printable chars should be properly escaped)

However, looking a the log example you provided, it looks like you're dealing with very large URIs:
```bash
echo -ne '?lang=be-tarask&modules=ext.categoryTree%2CeventLogging%2CnavigationTiming%2Cpopups%2CwikimediaEvents%7Cext.centralNotice.choiceData%2Cdisplay%2CgeoIP%2CimpressionDiet%2CkvStore%2CstartUp%7Cext.centralauth.centralautologin%7Cext.checkUser.clientHints%7Cext.cx.eventlogging.campaigns%7Cext.discussionTools.init%2Cminervaicons%7Cext.echo.centralauth%7Cext.uls.interface%2Cpreferences%2Cwebfonts%7Cext.urlShortener.toolbar%7Cjquery%2Cmoment%2Coojs%2Coojs-ui-core%2Coojs-ui-windows%2Crangefix%2Csite%7Cjquery.client%2CtextSelection%7Cmediawiki.String%2CTitle%2CUri%2Capi%2Cbase%2Ccldr%2Ccookie%2Cexperiments%2CjqueryMsg%2Clanguage%2Crouter%2Cstorage%2Ctoc%2Cuser%2Cutil%2CvisibleTimeout%7Cmediawiki.editfont.styles%7Cmediawiki.libs.pluralruleparser%7Cmediawiki.page.media%2Cready%7Cmediawiki.page.watch.ajax%7Cmmv.bootstrap%2Ccodex%2Chead%7Cmmv.bootstrap.autostart%7Coojs-ui-windows.icons%7Cskins.vector.clientPreferences%2Cjs%7Cskins.vector.icons.js&skin=vector-2022&versio' | wc -c
970
```
(see how the query part in itself almost hits 1k)

I see that you increased default `len` for your log directive up to 16384, which should allow haproxy to overcome the 1024 (default) log length truncation.

However, I don't see in your config if you also adjusted the `tune.http.logurilen` tunable (https://docs.haproxy.org/dev/configuration.html#3.2-tune.http.logurilen), which also defaults to 1024.

Unless you're pretty confident that the problematic behavior you're facing is "new" and couldn't be triggered in older versions, I would suggest to try to increase this value and see if it helps.

Note however that when hitting `tune.http.logurilen`, it is not expected that the whole log payload gets interrupted abrubtly: only the current log item (here `%HQ`) making use of the request URI should be truncated, and the remaining log items shouldn't be affected (ie: log structure shouldn't be affected).

Thus for now I'm failing to understand why in the example log line you provided the `log-format` part (which normally comes right after `log-format-sd` one) doesn't even show up. Same thing goes for the terminating LF (`\n`), which should always be inserted by haproxy even in case of log truncation.
Could it be that your log collecting device gets upset if the `%HQ` is incomplete? If not, would you mind sharing a bit more context regarding how you're collecting the logs like the example you provided? (is it raw log messages directly sent by haproxy, or is it processed log messages?)

Thanks

**Comment by fabfurnari** [comment]
Thanks for your quick answer

> Did you face this behavior when upgrading from a previous working version regarding this issue?
> 

The bug was present also in 2.6.17. We upgraded from that version to 2.8.10 to figure out if it was dependent on that version but without luck.

> I took a look at the commits you've mentioned, but unfortunately I don't see a relationship with the issue you're describing. They should not affect how invalid characters are encoded. (e.g.: non printable chars should be properly escaped)
> 
> However, looking a the log example you provided, it looks like you're dealing with very large URIs:
> 
> ```shell
> echo -ne '?lang=be-tarask&modules=ext.categoryTree%2CeventLogging%2CnavigationTiming%2Cpopups%2CwikimediaEvents%7Cext.centralNotice.choiceData%2Cdisplay%2CgeoIP%2CimpressionDiet%2CkvStore%2CstartUp%7Cext.centralauth.centralautologin%7Cext.checkUser.clientHints%7Cext.cx.eventlogging.campaigns%7Cext.discussionTools.init%2Cminervaicons%7Cext.echo.centralauth%7Cext.uls.interface%2Cpreferences%2Cwebfonts%7Cext.urlShortener.toolbar%7Cjquery%2Cmoment%2Coojs%2Coojs-ui-core%2Coojs-ui-windows%2Crangefix%2Csite%7Cjquery.client%2CtextSelection%7Cmediawiki.String%2CTitle%2CUri%2Capi%2Cbase%2Ccldr%2Ccookie%2Cexperiments%2CjqueryMsg%2Clanguage%2Crouter%2Cstorage%2Ctoc%2Cuser%2Cutil%2CvisibleTimeout%7Cmediawiki.editfont.styles%7Cmediawiki.libs.pluralruleparser%7Cmediawiki.page.media%2Cready%7Cmediawiki.page.watch.ajax%7Cmmv.bootstrap%2Ccodex%2Chead%7Cmmv.bootstrap.autostart%7Coojs-ui-windows.icons%7Cskins.vector.clientPreferences%2Cjs%7Cskins.vector.icons.js&skin=vector-2022&versio' | wc -c
> 970
> ```
> 
> (see how the query part in itself almost hits 1k)
> 
> I see that you increased default `len` for your log directive up to 16384, which should allow haproxy to overcome the 1024 (default) log length truncation.
> 
> However, I don't see in your config if you also adjusted the `tune.http.logurilen` tunable (https://docs.haproxy.org/dev/configuration.html#3.2-tune.http.logurilen), which also defaults to 1024.
> 
> Unless you're pretty confident that the problematic behavior you're facing is "new" and couldn't be triggered in older versions, I would suggest to try to increase this value and see if it helps.

I will definitely try to tune this, thanks a lot for the hint!

> 
> Note however that when hitting `tune.http.logurilen`, it is not expected that the whole log payload gets interrupted abrubtly: only the current log item (here `%HQ`) making use of the request URI should be truncated, and the remaining log items shouldn't be affected (ie: log structure shouldn't be affected).
> 
> Thus for now I'm failing to understand why in the example log line you provided the `log-format` part (which normally comes right after `log-format-sd` one) doesn't even show up. Same thing goes for the terminating LF (`\n`), which should always be inserted by haproxy even in case of log truncation. Could it be that your log collecting device gets upset if the `%HQ` is incomplete? If not, would you mind sharing a bit more context regarding how you're collecting the logs like the example you provided? (is it raw log messages directly sent by haproxy, or is it processed log messages?)
> 
> Thanks

Our current setup is HAProxy sending logs in rfc5424 format to a standard UDP socket on localhost where Benthos (now RedPanda Connect) is listening and parsing these logs first decoding the syslog format and then working on the various fields to extract the needed information.

This could be definitely due to the ingesting software but it's not easy to isolate that due to the high number of requests, and as I said, the fact that we still can't reproduce the exact request that triggers this behavior. 

Now I'll try to narrow down this and try to exclude the various paths, thanks again for your precious help!

**Comment by Darlelet** [comment]
You're welcome!
Thanks for mentioning that you were already facing this odd behavior with 2.6.17 and for your setup description, it is helpful :)

>This could be definitely due to the ingesting software but it's not easy to isolate that due to the high number of requests, and as I said, the fact that we still can't reproduce the exact request that triggers this behavior.

Yes I understand, no problem

>Now I'll try to narrow down this and try to exclude the various paths, thanks again for your precious help!

Sounds good, let us know how it goes :+1:

**Comment by fabfurnari** [comment]
Hi, just to keep you updated on this task: we're investigating eventual transport issues between HAProxy and the log parser that could result in incomplete/malformed syslog frames.

First investigations suggests that HAProxy is sending the correct syslog payload so I don't think this is really related to how HAProxy crafts the message, anyway we discovered another possible bug in character encoding (but we'll report that separately from this).

Considering the problem is most likely on the log processing side, I would close this and eventually re-open if subsequent tests will show the opposite.

Thanks again for your help and sorry for the non-bug report!

**Comment by kroomagnon** [comment]
Hi,

I think the problem above is indeed in HAProxy. I can replicate a very similar results using a configuration like this:

```
global
    log-send-hostname "logtester"
    log udp@10.150.12.2:5141 local0
    log udp@10.150.12.2:5141 format rfc5424 local0

defaults
    timeout connect 5000
    timeout client 50000
    timeout server 50000
    log global
    mode http
    log-format "===log-format==="
    log-format-sd "===LOG-FORMAT-SD==="

frontend test-front
    bind *:80
    default_backend test-backend

backend test-backend
    server node-1 whoami:80 check
```

After starting HAProxy and making a request, I can see the network traffik using ngrep:

```
U 10.101.0.122:42597 -> 10.150.12.2:5141 #1
  <134>Mar 26 12:55:05 logtester haproxy[7]: ===log-format===.                                                                                                                                                    
#
U 10.101.0.122:42597 -> 10.150.12.2:5141 #2
  <134>1 2025-03-26T12:55:05.635227+01:00 logtester haproxy 7 - ===LOG-FORMAT-SD=== ===log-format===.                                                                                                             
```

Here you can see two syslog messages sent to the log server. The first with the defined `log-format`, the second with the `log-format-sd` and the `log-format` concatenated.

I have tried this with HAProxy 3.0 and 3.1.

I hope this helps.

**Comment by Darlelet** [comment]
@kroomagnon since you appear to have two `log` directives defined in your configuration, it is expected to see 2 logs being by haproxy (one with log-format-sd since it is explicitly formatted for rfc5424 compliancy, and the other one using rfc3164 which is the default in your case and ignores structured data)

If you still think you are facing an issue in haproxy you may want to open a different ticket and provide as much details as possible.

Thanks
