### ISSUE TITLE
redirect not work with path_reg matched variable value

### ISSUE THREAD

**Issue by daddyauden** [haproxy/haproxy#2616]
### Detailed Description of the Problem

    acl acl_domain hdr(host) -i abc.domain.com
    acl acl_path path_reg ^/cat/([^/]+)
    http-request redirect code 301 location https://www.domain.com/cat/subcat/\1 if acl_domain acl_path

### Expected Behavior

for now, the old url https://www.domain.com/cat/abc  just rediect to https://www.domain.com/cat/subcat/cat/abc

the expected should be redirect to https://www.domain.com/cat/subcat/abc

### Steps to Reproduce the Behavior

for the senario, can not reproduce the behavior

### What is your configuration?

```haproxy
acl acl_domain hdr(host) -i abc.domain.com
acl acl_path path_reg ^/cat/([^/]+)
http-request redirect code 301 location https://www.domain.com/cat/subcat/\1 if acl_domain acl_path
```

### Output of `haproxy -vv`

```plain
2.8.5-aaba8d0
```

**Comment by capflam** [comment]
In your exemple, the Host header value does not match `acl_domain` ACL. So the redirect rule is not applied. And fixing the matching on the Host header, the redirect will not handle `\1` as a placeholder. The request will redirected to `https://www.domain.com/cat/subcat/\1`. There is no capture when a regular expression is execute from an ACL. However, the value used as location is a redirect rule is a log-format string. It means you can use the sample fetches to format your URL. For instance:

```
    http-request redirect code 301 location https://www.domain.com/cat/subcat/%[path,word(2,/)] if acl_domain acl_path
```
