### ISSUE TITLE
HAProxy 3.0 doesn't load .key file if certificate specified in crt-store

### ISSUE THREAD

**Issue by chrisstaite-menlo** [haproxy/haproxy#2618]
### Detailed Description of the Problem

If you specify a certificate on a bind line using the crt option then the key is read from the certificate name followed by .key by default.  However, if you specify that certificate in a crt-store then the key is no longer read.

This is contrary to the documentation here: https://github.com/haproxy/haproxy/blob/master/doc/configuration.txt#L15947C1-L15957C49
It is not mentioned as a change of behaviour for crt-store here: https://github.com/haproxy/haproxy/blob/master/doc/configuration.txt#L4850

### Expected Behavior

Specifying a certificate in a load line of a crt-store without a key explicitly stated should load the key file from the certificate filename with .key added as a suffix, like it does if the certificate is not specified in the crt-store.

### Steps to Reproduce the Behavior

1. Create a certificate file called cert.pem with its key in cert.pem.key
2. Add a bind line to a frontend with ssl enabled a `crt cert.pem`
3. Note that HAProxy is able to start
4. Now add a crt-store section to the configuration and `load crt cert.pem`
5. Note that HAProxy is unable to start

### Do you have any idea what may have caused this?

Undocumented change of behaviour with the new crt-store feature.

### Do you have an idea how to solve the issue?

Either make crt-store load the key file from the .key file by default like the bind line, or document the change in behaviour.

### What is your configuration?

```haproxy
global
   maxconn 500000
   daemon
   user haproxy
   group haproxy

defaults
   retries 3
   log global
   mode http

crt-store
   load crt cert.pem ocsp-update on

frontend osh
   maxconn 10000
   bind 127.0.0.1:443 ssl crt cert.pem
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.2-a45a8e6 2024/06/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.2.html
Running on: Linux 5.15.0-101-generic #111~20.04.1-Ubuntu SMP Mon Mar 11 15:44:43 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_OPENSSL=1 USE_SYSTEMD=1 USE_STATIC_PCRE=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL +STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Running with a replaced memory allocator (e.g. via LD_PRELOAD).
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by chrisstaite-menlo** [comment]
It might be helpful for the error message:
```
[ALERT]    (42325) : config : parsing [haproxy.conf] : 'bind 127.0.0.1:443' in section 'frontend' : unable to load SSL private key into SSL Context 'cert.pem': passed a null parameter.
```

**Comment by chrisstaite-menlo** [comment]
I have been on the hunt and I think that this comment indicates that this is a documentation issue, but the function is working as designed?  I'm not entirely sure though:

https://github.com/haproxy/haproxy/blob/a14c7d194ad27f9f84c9d42aab953a162999252a/src/ssl_ckch.c#L4056C1-L4056C72
```
/* crt-store does not try to find files, but use the stored filename */
```

**Comment by wlallemand** [comment]
Hello, the crt-store works in a declarative mode, and does not try to autodetect files. This does not work like the "crt" keyword alone. This is explained in the crt-store part of the documentation: http://docs.haproxy.org/3.0/configuration.html#3.12.1-crt but I can update the documentation of the "crt" keyword of bind lines.

In my opinion this is not a "change of behavior" since the crt-store is a new feature, but just a different behavior !

You can indeed start with an incomplete crt-store load line until it's not associated with anything, like it would be possible with `set ssl cert` on the CLI. In fact a crt-store load line is the configuration equivalent of a `set ssl cert`

**Comment by chrisstaite-menlo** [comment]
After doing some research, it is now clear to me what is going on, but it was a surprise that I don't think is obvious from the crt-store documentation.  I think that updating the docs of the `crt` to say that it will not auto-detect key files if they exist in the `crt-store` would be the best outcome here.

Thanks.

**Comment by chrisstaite-menlo** [comment]
Thank you!
