### ISSUE TITLE
Crashing for different GitHub's subdomains because of using the same TCP connection

### ISSUE THREAD

**Issue by Sharker5854** [haproxy/haproxy#2636]
### Detailed Description of the Problem

Hey
We've configured Haproxy in reverse-proxy mode to provide access for external resources from our organization's closed internal network. And our settings looks to work fine for almost all domains, except `github.com` and it's subdomains.

We get the following error while switching between different GitHub's subdomains:
```
Fastly error: unknown domain: github.com. Please check that this domain has been added to a service.
Details: cache-bma1663-BMA
```

### Expected Behavior

Freely switch between subdomains, without getting this error.
It implies opening new TCP connection for every subdomain.

### Steps to Reproduce the Behavior

1. Run Haproxy in reverse-proxy mode using config below
2. Open `docs.github.com` in one tab
3. Then try to request `api.github.com` in another tab
4. You will have to see our error
5. After waiting until TCP connection is dropped, you will be able to get `api.github.com`
6. Then cycles repeats...

### Do you have any idea what may have caused this?

After long researching, we've come to conclusion that web-browsers try to use the **same TCP connection** even for different GitHub's subdomains (e.g. `api.github.com` and `docs.github.com`), because:

1. GitHub uses wildcart TLS certificate for it's subdomains
2. Web-browser see the same destination IP of our reverse-proxy all the time

That's why it doesn't want to reopen TCP connection and uses **connection coalescing** feature, that causes crash on another subdomain request. It happens until the current connection is dropped by timeout.

Proxying works fine with `curl`, because it drops connection immediately.
Using the same TCP connection is the feature of HTTP/2 protocol, HTTP/1.1 doesn't use this optimization.

### Do you have an idea how to solve the issue?

Hence, this problem can be solved by switching off HTTP/2 in web-browser's settings, but it looks like a bad idea since other sites work correctly with these settings.
Adding  `alpn http/1.1`  in configuration below doesn't fix the problem too.
So do you have any another ideas how to solve it? May be on Haproxy's layer?

### What is your configuration?

```haproxy
global
    daemon
    maxconn 2560
    log stdout format raw local0

defaults
    mode tcp
    timeout connect 5s
    timeout client 3600s
    timeout server 3600s
    log global

frontend http_in
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

frontend https_in
    bind *:443 alpn http/1.1
    mode tcp
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }
    use_backend %[req_ssl_sni]

backend github.com
    server github_com_server github.com:443

backend api.github.com
    server api_github_com_server api.github.com:443

backend docs.github.com
    server docs_github_com_server docs.github.com:443
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.2-a45a8e6 2024/06/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.2.html
Running on: Linux 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
Running on OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by fionera** [comment]
This looks like a similar issue to https://github.com/haproxy/haproxy/issues/947 . By forcing the connection to close it should be fixed

**Comment by wtarreau** [comment]
Hello,

first, please use proper wording. You're speaking about "crash" (even in the title) yet I see no mention of such a crash of the process, only issues apparently reported in the browser.

Second, what I don't get is that if the browser reuses the same connection to haproxy, when used directly it should do the same as well, so that means that the connection from haproxy to github ought to be shared without problems. Hence I conclude that in a normal case (no haproxy), the browser wouldn't reuse the same connection for both domains because both have different addresses. Then it raises a question: how did you arrange for your browser to pass through haproxy ? Are you using transparent proxying to redirect traffic on the fly so that the browser believes it's talking to the real site, or did you just play games with dns or /etc/hosts ? I'm suspecting the latter, and that you're advertising a single address for all sites. **This**, combined with the wildcard certificate, can make the browser confident it can reuse the same connection. So if that's the case, you just need to configure several addresses on your machine and distribute the various different host names across them so that the browser knows they're different hosts.
