### ISSUE TITLE
Haproxy 2.8.4: Sporadic backend UP/DOWN status and CPU fluctuations "Bad EL0 synchronous exception detected... UNRECOGNIZED EC"

### ISSUE THREAD

**Issue by lallish** [haproxy/haproxy#2640]
### Detailed Description of the Problem

We use an AWS Network Load Balancer pointing at our 3 horizontally peered HAProxies, running on Amazon Linux 2, arm64. 

We tried to do a rolling restart of the HAProxies to update the configuration of a backend. When reloading each of the haproxy the system tend to output this message:

`Bad EL0 synchronous exception detected on {cpu}, code 0x66000000 -- UNRECOGNIZED EC`

And after reloading the backends goes from status UP to DOWN sporadically. The healthchecks times out at 2s in which the backend is flagged as DOWN.

But the backends haven't been touched in this period.

Once we've reloaded all 3 haproxies the sporadic healthcheck timeout goes on for about 2 hours and the CPU is fluctuating a lot on the haproxy servers. So in below pictures you can see the haproxy CPU graph, and the backend response times from healthchecks.

![Screenshot 2024-07-15 at 11 20 09](https://github.com/user-attachments/assets/ce0af9c3-36f2-4832-bfb8-166ec87f932d)

![Screenshot 2024-07-15 at 11 20 48](https://github.com/user-attachments/assets/080b6281-3ac6-41cf-a8d5-61107deff0c0)

### Expected Behavior

Drainage of the HAProxy traffic and proper reloading of config.

### Steps to Reproduce the Behavior

Have not been able to reproduce locally. The case have been for production traffic at around 10k queries per seconds.

### Do you have any idea what may have caused this?

No.

### Do you have an idea how to solve the issue?

Nope

### What is your configuration?

```haproxy
global
        pidfile     /var/run/haproxy.pid
        maxconn     22000
        nbthread    4
        cpu-map     auto:1/1-4   0-3
        tune.bufsize 65536
        tune.maxrewrite 4096
        stats socket /run/haproxy_stats.sock mode 600 level admin
        set-var proc.maintenance int(0)
        ssl-default-bind-options ssl-min-ver TLSv1.0
        ssl-default-bind-ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256
        ssl-default-server-ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256
        spread-checks 5
        lua-load /etc/haproxy/stickiness.lua

    defaults
        mode                    http
        log                     global
        option                  httplog
        option                  dontlognull
        option forwardfor       except 127.0.0.0/8
        option                  redispatch
        option                  http-keep-alive
        retries                 3
        timeout http-request    10s
        timeout queue           2500  # Limit time spent in request queue, less than connectors 3s timeout
        timeout connect         3500
        timeout client          28s
        timeout server          10m
        timeout http-keep-alive 35s
        timeout check           10s
        maxconn                 20000
        http-reuse              safe

    http-errors custom_errors
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 401 /etc/haproxy/errors/401.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 404 /etc/haproxy/errors/404.http
        errorfile 405 /etc/haproxy/errors/405.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 410 /etc/haproxy/errors/410.http
        errorfile 413 /etc/haproxy/errors/413.http
        errorfile 425 /etc/haproxy/errors/425.http
        errorfile 429 /etc/haproxy/errors/429.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 501 /etc/haproxy/errors/501.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

    listen stats
        bind 127.0.0.1:1936
        stats enable
        stats realm Haproxy\ Statistics
        stats uri /
        stats auth admin:admin
        stats admin if TRUE
    
    resolvers public_dns
        nameserver dns1 1.1.1.1:53
        nameserver dns2 1.0.0.1:53
        accepted_payload_size 8192 # allow larger DNS payloads
    
    peers default
        peer hap1 2.2.2.1:1050
        peer hap2 2.2.2.2:1050
        peer hap3 2.2.2.3:1050
        peer hap4 2.2.2.4:1050
        peer hap5 2.2.2.5:1050
        peer hap6 2.2.2.6:1050

    frontend shared
        mode http
        errorfiles custom_errors
        bind :443 ssl  crt /etc/haproxy/certificates/cert1.pem ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:AES128-SHA:DHE-RSA-AES128-SHA alpn h2,http/1.1

        tcp-request connection expect-proxy layer4 if { src 1.2.3.4 1.2.3.5 1.2.3.6 }

        monitor-uri /haproxy_status
        monitor fail if { var(proc.maintenance) -m int eq 1 }

        acl is_host_webapi req.hdr(host) -i api.example.com

        http-request set-var(txn.backend) req.hdr(host),field(1,"."),lower,map(/etc/haproxy/api-id.map,no-match)

        acl is-old-tls ssl_fc_protocol TLSv1 or ssl_fc_protocol TLSv1.1
        http-request track-sc0 var(txn.backend) table st_old_tls_backend if is-old-tls
        http-request sc-inc-gpc0 if is-old-tls
        use_backend %[var(txn.backend)] if is_host_webapi
        default_backend no-match

    frontend http
        mode http
        bind 0.0.0.0:80
        monitor-uri /haproxy_status
        monitor fail if { var(proc.maintenance) -m int eq 1 }
        use_backend no-match

    # We have around 50 backends here, just servers that are varying
    backend api-1
        mode http
        balance roundrobin
        option http-buffer-request # lua.parseSessionKey requires this to function correctly
        option forwardfor

        acl is-v1 path_beg -i /api/v1
        acl is-reload path_beg -i /api/reload

        stick-table type string len 36 size 62k expire 2h peers default
        stick on str("reloads") if is-reload
        stick on "lua.parseSessionKey" if is-v1
        stick on url_param(sessionKey) if { url_param(sessionKey) -m found }

        option httpchk
        http-check send meth HEAD uri /healthcheck ver HTTP/1.0 hdr User-Agent HAProxy
        http-check expect status 200
        default-server ssl ca-file /etc/haproxy/ca-bundle.crt check inter 2000 fastinter 250
        server test1.example.com 3.3.3.1:222 verifyhost test1.example.com weight 64 maxconn 128
        server test2.example.com 3.3.3.2:211 verifyhost test2.example.com weight 64 maxconn 128

    backend no-match
        mode http
        http-request deny deny_status 400


This is the stick-table configuration that exist for all backends:
        stick-table type string len 36 size 1m expire 1d store gpc0
        stick-table type string len 36 size 62k expire 2h peers default
        stick-table type string len 36 size 251k expire 2h peers default
        stick-table type string len 36 size 15k expire 2h peers default
        stick-table type string len 36 size 235k expire 2h peers default
        stick-table type string len 36 size 314k expire 2h peers default
        stick-table type string len 36 size 125k expire 2h peers default
        stick-table type string len 36 size 15k expire 2h peers default
        stick-table type string len 36 size 267k expire 2h peers default
        stick-table type string len 36 size 377k expire 2h peers default
        stick-table type string len 36 size 188k expire 2h peers default
        stick-table type string len 36 size 47k expire 2h peers default
        stick-table type string len 36 size 1384k expire 2h peers default
        stick-table type string len 36 size 110k expire 2h peers default
        stick-table type string len 36 size 31k expire 2h peers default
        stick-table type string len 36 size 880k expire 2h peers default
        stick-table type string len 36 size 165k expire 2h peers default
        stick-table type string len 36 size 31k expire 2h peers default
        stick-table type string len 36 size 314k expire 2h peers default
        stick-table type string len 36 size 1698k expire 2h peers default
        stick-table type string len 36 size 78k expire 2h peers default
        stick-table type string len 36 size 23k expire 2h peers default
        stick-table type string len 36 size 1572k expire 2h peers default
        stick-table type string len 36 size 173k expire 2h peers default
        stick-table type string len 36 size 31k expire 2h peers default
        stick-table type string len 36 size 62k expire 2h peers default
        stick-table type string len 36 size 587k expire 2h peers default
        stick-table type string len 36 size 587k expire 2h peers default
        stick-table type string len 36 size 188k expire 2h peers default
        stick-table type string len 36 size 1572k expire 2h peers default
        stick-table type string len 36 size 78k expire 2h peers default
        stick-table type string len 36 size 23k expire 2h peers default
        stick-table type string len 36 size 31k expire 2h peers default
        stick-table type string len 36 size 251k expire 2h peers default
        stick-table type string len 36 size 335k expire 2h peers default
        stick-table type string len 36 size 188k expire 2h peers default
        stick-table type string len 36 size 1761k expire 2h peers default
        stick-table type string len 36 size 39k expire 2h peers default
        stick-table type string len 36 size 15k expire 2h peers default
        stick-table type string len 36 size 1195k expire 2h peers default
        stick-table type string len 36 size 196k expire 2h peers default
        stick-table type string len 36 size 157k expire 2h peers default
        stick-table type string len 36 size 188k expire 2h peers default
        stick-table type string len 36 size 293k expire 2h peers default
        stick-table type string len 36 size 188k expire 2h peers default
        stick-table type string len 36 size 23k expire 2h peers default
        stick-table type string len 36 size 235k expire 2h peers default
        stick-table type string len 36 size 335k expire 2h peers default
        stick-table type string len 36 size 220k expire 2h peers default
        stick-table type string len 36 size 15k expire 2h peers default
        stick-table type string len 36 size 141k expire 2h peers default
        stick-table type string len 36 size 209k expire 2h peers default
        stick-table type string len 36 size 94k expire 2h peers default
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.4-a4ebf9d 2023/11/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.4.html
Running on: Linux 4.14.348-265.562.amzn2.aarch64 #1 SMP Fri Jun 14 09:53:25 UTC 2024 aarch64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
Running on OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.1 20220924

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
Bad EL0 synchronous exception detected on {cpu}, code 0x66000000 -- UNRECOGNIZED EC
```

**Comment by einval22** [comment]
Hi Lalle !

Thanks a lot for reporting this !

As for the  message, which is seen in the  console, it is `bad_el0_sync` kernel trap which prints it, sets `info.si_signo = SIGILL`  and then try to send this SIGILL to haproxy process via  `force_sig_info`():

```
asmlinkage void bad_el0_sync(struct pt_regs *regs, int reason, unsigned int esr)
{
	siginfo_t info;
	void __user *pc = (void __user *)instruction_pointer(regs);
	console_verbose();

	pr_crit("Bad EL0 synchronous exception detected on CPU%d, code 0x%08x -- %s\n",
		smp_processor_id(), esr, esr_get_class_string(esr));
	__show_regs(regs);

	info.si_signo = SIGILL;
	info.si_errno = 0;
	info.si_code  = ILL_ILLOPC;
	info.si_addr  = pc;

	current->thread.fault_address = 0;
	current->thread.fault_code = 0;

	force_sig_info(info.si_signo, &info, current);
}
```

That is strange, that process does not crash, because  `force_sig_info` call [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/signal.c?h=v4.14-rc8#n1180)  should deliver SIGILL. We do not block it in master-worker mode (-W) and in mono-process mode  in the time of reload ( master and worker processes actually do reexec ).

So, assuming this. 
1. Could you please, at first confirm that you start haproxy via systemd service file ? (means in master-worker mode)  
2. Would you please, provide logs of haproxy during restart ?

As the first hypothesis, is that some worker process catches SIGILL during reload, so we should see at least some messages about  this in the haproxy logs.

3. Could you please, explain in more details, what do you mean by  "update the configuration of a backend". Are you  trying to apply the new config for haproxy via reload, in this case the diff between the old and the new  will be very helpful for us. 
Or you have added/removed some backend servers and its settings via CLI before reload ? 

Many thanks in advance,
Kind regards,

**Comment by einval22** [comment]
Could you also, please check if there are some core files created by the process ?

`cat /proc/sys/kernel/core_pattern ` will help to find it.

And could you, please share here `dmesg` output that corresponds to this reload period ?
From your flame graphs, I have the impression (but I may mistake here) that  process is about to start, say with a new config,  and it is killed  each time with SIGILL, which corresponds to BUGON in some places in the code. 
So, if there are some coredumps, it will be very helpful to understand quickly,  in which part of code we trigger this and what is happening.
 
I've also noticed, that you are using `linux-musl`.  Do you have any node in your production environment, where haproxy is compiled with another target, say `linux-glibc` for example ? Just to compare,  if there are the same behavior on reload and it is not because of some issues in musl libc.

**Comment by lukastribus** [comment]
Linux 4.14 does not have ARM SVE support, it was first introduced in 4.15.
Haproxy 2.8.3 updates xxhash to 0.8.2 (vendored) which supports ARM SVE.

Perhaps `__ARM_FEATURE_SVE` was defined during the build?

How was haproxy build exactly, was it build on a different, more modern OS/kernel?

Also see:
https://www.mail-archive.com/gem5-users@gem5.org/msg17303.html

**Comment by wtarreau** [comment]
Super interesting indeed! I'm seeing from the AL2 description page here: https://aws.amazon.com/amazon-linux-2/faqs/ that the distro ships with gcc-7.3. Here the code was built with gcc-12.2. It's very possible that this compiler was optimized for native builds on this platform and always enables SVE since the CPU supports it. The fact that it's running on an outdated 4.14 kernel is not really the compiler's concern, it cannot really guess much (except if the flags don't appear when using -march=native). They also mention that they provide a more up to date 5.10 kernel, maybe a good test would be to boot the instance on such an up-to-date kernel and confirm that it fixes the problem ?

**Comment by lallish** [comment]
> Hi Lalle !
> 
> Thanks a lot for reporting this !
> 
> As for the message, which is seen in the console, it is `bad_el0_sync` kernel trap which prints it, sets `info.si_signo = SIGILL` and then try to send this SIGILL to haproxy process via `force_sig_info`():
> 
> ```
> asmlinkage void bad_el0_sync(struct pt_regs *regs, int reason, unsigned int esr)
> {
> 	siginfo_t info;
> 	void __user *pc = (void __user *)instruction_pointer(regs);
> 	console_verbose();
> 
> 	pr_crit("Bad EL0 synchronous exception detected on CPU%d, code 0x%08x -- %s\n",
> 		smp_processor_id(), esr, esr_get_class_string(esr));
> 	__show_regs(regs);
> 
> 	info.si_signo = SIGILL;
> 	info.si_errno = 0;
> 	info.si_code  = ILL_ILLOPC;
> 	info.si_addr  = pc;
> 
> 	current->thread.fault_address = 0;
> 	current->thread.fault_code = 0;
> 
> 	force_sig_info(info.si_signo, &info, current);
> }
> ```
> 
> That is strange, that process does not crash, because `force_sig_info` call [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/signal.c?h=v4.14-rc8#n1180) should deliver SIGILL. We do not block it in master-worker mode (-W) and in mono-process mode in the time of reload ( master and worker processes actually do reexec ).
> 
> So, assuming this.
> 
>     1. Could you please, at first confirm that you start haproxy via systemd service file ? (means in master-worker mode)
> 
>     2. Would you please, provide logs of haproxy during restart ?
> 
> 
> As the first hypothesis, is that some worker process catches SIGILL during reload, so we should see at least some messages about this in the haproxy logs.
> 
>     3. Could you please, explain in more details, what do you mean by  "update the configuration of a backend". Are you  trying to apply the new config for haproxy via reload, in this case the diff between the old and the new  will be very helpful for us.
>        Or you have added/removed some backend servers and its settings via CLI before reload ?
> 
> 
> Many thanks in advance, Kind regards,

1. Yes the haproxy is a systemd service starting/stopping a the docker container. The docker is fetched from the official registry: https://hub.docker.com/_/haproxy
Here is the systemd unit file:
```
cat /etc/systemd/system/haproxy.service
[Unit]
Description=Docker Container Haproxy
Requires=docker.service
After=docker.service

[Service]
Type=simple
TimeoutStartSec=0
Restart=always
ExecReload=/usr/bin/docker kill --signal=HUP haproxy-container
ExecStart=/usr/bin/docker start -a haproxy-container
ExecStop=/usr/bin/docker stop -t 2 haproxy-container

[Install]
WantedBy=default.target
```

2. Here is the journal log of the service also containing the docker logs:
[logs.txt](https://github.com/user-attachments/files/16451840/logs.txt)

3. The haproxy config is templated to a certain path with eventual changes in it, then we reload the systemd service. The diff in this case was to a backend in the config, the stick table size increased (we use stick tables for some API calls), and another backend server was added:
```

-    stick-table type string len 36 size 78k expire 2h peers default
+    stick-table type string len 36 size 104k expire 2h peers default

     server server2 1.2.3.5:27000 verifyhost server2 weight 64 maxconn 128
+    server server1 1.2.3.4:27000 verifyhost server1 weight 64 maxconn 128


```



> Could you also, please check if there are some core files created by the process ?
> 
> `cat /proc/sys/kernel/core_pattern ` will help to find it.
> 
> And could you, please share here `dmesg` output that corresponds to this reload period ? From your flame graphs, I have the impression (but I may mistake here) that process is about to start, say with a new config, and it is killed each time with SIGILL, which corresponds to BUGON in some places in the code. So, if there are some coredumps, it will be very helpful to understand quickly, in which part of code we trigger this and what is happening.
> 
> I've also noticed, that you are using `linux-musl`. Do you have any node in your production environment, where haproxy is compiled with another target, say `linux-glibc` for example ? Just to compare, if there are the same behavior on reload and it is not because of some issues in musl libc.

No core files.

Here is dmesg, this text looks particularly interesting:
```
Bad EL0 synchronous exception detected on CPU3, code 0x66000000 -- UNRECOGNIZED EC
[ 8243.134577] CPU: 3 PID: 1517 Comm: haproxy Not tainted 4.14.348-265.565.amzn2.aarch64 #1
```
[dmesg.txt](https://github.com/user-attachments/files/16452150/dmesg.txt)

No coredumps either.
The config is just updated with another server added to a backend and stick table size update. Then the systemd is reloaded in a rolling manner over 3 peer haproxies each located on an EC2 arm64 instance.

Can't answer for what the haproxy is compiled with. We use this image from dockerhub: https://hub.docker.com/layers/library/haproxy/2.8.4-alpine/images/sha256-92efb1931de04b3445b1ffe75cdaff3c0d92dbb6fcecb5daef4de108601f4a83?context=explore

 


> Linux 4.14 does not have ARM SVE support, it was first introduced in 4.15. Haproxy 2.8.3 updates xxhash to 0.8.2 (vendored) which supports ARM SVE.
> 
> Perhaps `__ARM_FEATURE_SVE` was defined during the build?
> 
> How was haproxy build exactly, was it build on a different, more modern OS/kernel?
> 
> Also see: https://www.mail-archive.com/gem5-users@gem5.org/msg17303.html

Can I check somehow how the haproxy was built? We're using as mentioned above the haproxy 2.8.4 image from dockerhub.



> Super interesting indeed! I'm seeing from the AL2 description page here: https://aws.amazon.com/amazon-linux-2/faqs/ that the distro ships with gcc-7.3. Here the code was built with gcc-12.2. It's very possible that this compiler was optimized for native builds on this platform and always enables SVE since the CPU supports it. The fact that it's running on an outdated 4.14 kernel is not really the compiler's concern, it cannot really guess much (except if the flags don't appear when using -march=native). They also mention that they provide a more up to date 5.10 kernel, maybe a good test would be to boot the instance on such an up-to-date kernel and confirm that it fixes the problem ?

The EC2 machines are updated about once every month. But there are no updates for this distribution recently, last one is from June 28th, the 4.14.348-265.565.amzn2.aarch64. But the issue is also on that kernel version.

**Comment by lukastribus** [comment]
> Can I check somehow how the haproxy was built? We're using as mentioned above the haproxy 2.8.4 image from dockerhub.

You confirmed that you are not building haproxy on your own, but using a docker build. So we already know that haproxy is build on a more modern systems, and in this particular case enables features that your kernel does not support.

AL2 is really close to EOL (less than 11 months), current is AL2023 (kernel 6.10).

Whether you should upgrade your AL2 kernel to 5.10 or start the migration to AL2023 and how to do that is really out of scope for this bug tracker.

I don't see any way around though.

**Comment by wtarreau** [comment]
Agreed. This is the limit of containers, Mixing possibly modern userspace with older kernel doesn't always work well, andthe incompatibilities are rare enough that they are often hard to spot.

It's possible to see what options haproxy was built with, you already did it with "haproxy -vv". We know its gcc-12.2.1, and that no arch-specific option was passed. In theory the compiler should not emit instructions for non-generic CPUs in this case. But maybe the init code it places to decide on the extensions to use is not sufficiently finegrained, and it uses extensions not available on your system.

**Comment by lallish** [comment]
Thanks for all the input. We will attempt to upgrade all of our systems to amazon linux 2023. I will give an update whether the problem still exists after that.

**Comment by lallish** [comment]
We upgraded to amazon linux 2023 on all haproxies but the problem still persists. 

To be noted this problem only occurs in one of our peered haproxy setups where we have 447 backends in the configuration.

The other peered haproxy setups we have less than 100.

**Comment by lukastribus** [comment]
Do you still see the kernel message:

    Bad EL0 synchronous exception detected on {cpu}, code 0x66000000 -- UNRECOGNIZED EC

or "only" the CPU fluctuations?

Please provide again the output of `haproxy -vv` and all other information, including exact dmesg output if any.

**Comment by lallish** [comment]
No the error message is gone which is good but the CPU fluctuations are still there.

```
HAProxy version 2.8.4-a4ebf9d 2023/11/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.4.html
Running on: Linux 6.1.106-116.188.amzn2023.aarch64 #1 SMP Tue Aug 27 07:00:04 UTC 2024 aarch64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
Running on OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.1 20220924

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wtarreau** [comment]
OK if it's only CPU fluctuations that's already a nice progress which confirms the incompatibilities between gcc's optimizations and the lack of support for them on the older kernel.

Regarding CPU fluctuations, well, as can be seen [here](https://www.haproxy.org/bugs/bugs-2.8.4.html), no less than 265 bugs were fixed in the 2.8 branch since 2.8.4 over the last 10 months. A number of them mention excessive wakeups, ignored events etc and would very likely have such effects. So at this point we're back to the usual "this is probably already fixed" status since nobody else reports such trouble. I don't know if Amazon Linux is based on another distro and if you could simply install any pre-packaged haproxy version provided for that distro. For example if it relies on debian/ubuntu, you could probably install Vincent Bernat's packages from https://haproxy.debian.net/ .

Otherwise, either you'll need to ask them to use up-to-date packages, or you'll need to build your own packages.

**Comment by lukastribus** [comment]
Docker is used here, not OS repositories, so this is a non-issue. 2.8.11 was just released so I guess the docker image should be available soon.

**Comment by wtarreau** [comment]
OK thanks for explaining, but then why was this image running 2.8.4 and not 2.8.10 if it's supposed to be up to date ?

**Comment by lukastribus** [comment]
I'm assuming it is a conscious decision to run a specific, tested release, as opposed to running the latest bugfix version (see #2353 - in fact in this bug we even mention that #2373 may also relevant in this configuration and that 2.8.5 would fix that).

**Comment by einval22** [comment]
﻿We might consider the idea to provide along with containers our own HAProxy VM minimalistic image ( concept inspired from our well tested commercial albva ) for Public Cloud users. 

Image should be very basic, just the version of the kernel, with which we are sure. Then it could be the distro from ALOHA (Formilux) or Ubuntu LTE  + latest stable non-commercial version of haproxy. 

Like this we could deliver the latest stable versions compiled with the "right" kernel, which we know, with the versions of crypto libs, that we know, etc.

This allows for some cloud users to avoid such kind of incompatibility issues, i.e., be run on the old kernel in the container compiled with the latest GCC, same problems with cryptolibs, etc. This concept may also help to eliminate problems with badly configured userland, resolvers, etc, for some, who are not sysadmins.

So, cloud users would have a facility just to pick a fresh image from some repo (or Marketplace), do some tests and deploy it in their infra, instead of deploying only containers, that they are tested before, etc.

Those who want to deploy containers in VMs will continue to use containers.

Those who want to test and to deploy faster in the public cloud, without having many troubles, may prefer an image.

**Comment by lallish** [comment]
As always with production environments, we can't update spontaneously to the latest without having tested it thoroughly. Is 3.0.5 a good target version for us do you think? It's the latest I can find. I'll just have to go through all the eventual breaking changes.

Particularly this breaking changes that I'm skeptic about how it would impact us:

> Stricter parsing of non-standard URIs: Parsing is now more strict during HTTP/1 processing for request target validation. This means that where previously, for compatibility, non-standard-compliant URIs were forwarded as-is for HTTP/1, now some invalid request targets are rejected with a 400-Bad-Request error.

**Comment by lukastribus** [comment]
> We might consider the idea to provide along with containers our own HAProxy VM minimalistic image ( concept inspired from our well tested commercial albva ) for Public Cloud users.
> 
> Image should be very basic, just the version of the kernel, with which we are sure. Then it could be the distro from ALOHA (Formilux) or Ubuntu LTE + latest stable non-commercial version of haproxy.
> 
> Like this we could deliver the latest stable versions compiled with the "right" kernel, which we know, with the versions of crypto libs, that we know, etc.

I don't think this is worth the effort.

The amount of work is high, usage will be low, all this to fix a problem that happens three times a decade to people who would not use this VM image in the first place.

And then we also become a OS vendor and need to support that as well. This is perfect for the commercial distribution. For the OSS project, I'd rather you don't provide this.



> As always with production environments, we can't update spontaneously to the latest without having tested it thoroughly.

That is why we are suggesting you DO NOT change the major release, but stay on 2.8 using the latest available bug fix release.

**Comment by lallish** [comment]
2.8.11 seems to have fixed the issues with latency fluctuations. Thanks for everything.

**Comment by lukastribus** [comment]
Ok, good, thanks for the confirmation.
