### ISSUE TITLE
tcp-request substitute for h3/quic (quic-request)

### ISSUE THREAD

**Issue by amsnek** [haproxy/haproxy#2641]
### Your Feature Request

Using http1 or http2 it is currently possible to reject or drop a tcp connection with haproxy tools very early, before things like a TLS handshake occured (`tcp-request connection reject`). 
This can be useful to drop for example connections from ip-adresses that are identified as attackers based on rate limiting rules / stick tables. For http3 however there currently seems to be no substitute (?). `http-request reject` can be used, but this is already after a tls handshake occured and thus more ressources were consumed. Unless I am missing something, should there not be a "udp-request" or "quic-request connection" function?

### What are you trying to do?

dropping/rejecting a h3/quic request as early as possible based on rules, anologous to the possibilities from `tcp-request connection` 

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.3-95a607c 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Tue May 21 03:13:04 EDT 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Werror=format-security
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.3.1 4 Jun 2024
Running on OpenSSL version : OpenSSL 3.3.1 4 Jun 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.7
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.44 2024-06-07
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-22)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by a-denoyelle** [comment]
FYI, `tcp-request` rules are also processed for QUIC connections. However, this occurs after QUIC handshake too.

**Comment by amsnek** [comment]
Then I may be hitting some bug it seems. 
I just re-tested and while I can indeed drop a QUIC request by specifying a src ip directly like this:
`tcp-request connection reject if { src <ip> }`

This does not work when combined with a stick table for a QUIC request, while the exact same rule works for a H2 (tcp) request?
`tcp-request connection reject if { src_get_gpc0(table-ip) ge 10 }`
-> and the gcp0 value in that table being greater then 10 
Since this worked with a non QUIC request it led me to the conclusion that it differs in case of QUIC in regard to "tcp"-request

The key in the table-ip is a an ip, the gpc0 counter gets increased by other rules. 
Will investigate this further now but either I am doing something wrong or missing something obvious or there is some bug at play?

**Comment by amsnek** [comment]
after further investigation, I think this is a bug -> will open one. 

regarding the feature request, since `tcp-connection reject` does happen before the TLS handshake -> having an option for QUIC to accomplish the same or changing the behaviour to drop before the handshake occurs could be useful. Aligning the function to behave the same no matter if h1/h2 or h3 is used would make sense in any case imo?

**Comment by a-denoyelle** [comment]
Willy and I had some discussions this morning about your feature request for QUIC rules. This is definitely something interesting for us and I'll try to provide a solution for this.

**Comment by a-denoyelle** [comment]
FYI, I just merged a set of patches to implement new "quic-initial" rules. As expected, this allows to filter QUIC connections prior to their allocation and the startup of SSL handshake.

I'm closing this feature request as I considered it as now implemented. Feel free to test this new feature and report anything if you miss something.

**Comment by amsnek** [comment]
Thank you very much, I will look into this asap!

**Comment by amsnek** [comment]
Works as expected, thank you very much! 
There is one thing of note however, a http-client implementation can still "ssl_resume" (ssl_fc_is_resumed) which doesnt create a new handshake but still might spam logs (unless set silent) or worse, possibly still cost a low amount of haproxy ressources?
It could make sense to have the option to disallow ssl resumption for "quic-initial dgram-drop" requests?
If there is no benefit haproxy ressource wise todo this, please ignore.

**Comment by amsnek** [comment]
Addendum: please ignore my previous post, it seems I was hitting older haproxy processes in my initial tests -> I cannot reproduce the ssl_resumption 🙈. Dropping works exactly as intended 👍

**Comment by a-denoyelle** [comment]
Great, thanks for your feedback !

**Comment by amsnek** [comment]
Sorry, one more question. Will this feature make its way into the next 3.0.x release or is this for >=3.1 only?

**Comment by a-denoyelle** [comment]
For the moment, I prefer to not backport this so it will be a 3.1+ only.
