### ISSUE TITLE
tcp-connection reject in conjunction with stick tables behaves differently on QUIC vs HTTP1/HTTP2 requests

### ISSUE THREAD

**Issue by amsnek** [haproxy/haproxy#2644]
### Detailed Description of the Problem

When using stick tables for rate limiting I noticed that a QUIC request does not behave the same as a H1 or H2 TCP request. 
While it is possible to drop a QUIC request by specifying the ip directly like this:
`tcp-request connection reject if { src <ip> }` 

The same does not work for a QUIC request when combined with a stick table while this rule does work for a H2 (tcp) request
example: `tcp-request connection reject if { src_get_gpc0(table-ratelimit) ge 10 }`

Using http-request reject instead of tcp-request works but the intention is to drop as early as possible, ideally *before* a TLS handshake is possible. 

PS: This Bug report stems from an initial feature request (https://github.com/haproxy/haproxy/issues/2641) since I initially thought that the "tcp-request" is not applicable for quic (udp) requests. 

### Expected Behavior

Since tcp-request rules are also processed for QUIC connections -> they should behave in the same way. (ideally they would drop the request before a TLS Handshake occurs, similiar to what happens with a H1/H2 request)

### Steps to Reproduce the Behavior

1. setup a frontend with h2 + quic (see example config below)
2. add stick tables to increase for example the gpc0 counter to react on this in the frontend  
3. use tcp-request connection to reject a request if counter is greater then x 
4. access using quic (e.g browser) hitting the rate limit / tcp-connection reject rule -> gpc0 counter will be increased but has no effect (connection is accepted -> http 429 will continue to show instead the connection being rejected)
5. access using h2 (e.g curl with h2 or disable quic in browser) hitting the rate limit / tcp-connection reject rule -> gpc0 counter will be increased and be effective (connection is rejected)

QUIC can also be disabled in the browser after the gpc0 counter is increased (ip is banned) -> connection will be rejected 
re-enabling QUIC in browser -> connection will succeed again

### What is your configuration?

```haproxy
global
        log 127.0.0.1 len 65535 local0 info
        chroot          /var/lib/haproxy
        pidfile         /var/run/haproxy.pid
        maxconn         80000
        daemon
        user            haproxy
        group           haproxy

        stats socket /var/run/haproxy.sock mode 0660 user root level admin expose-fd listeners
        stats timeout 30s

        ssl-default-bind-ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-server-ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
        ssl-default-server-options ssl-min-ver TLSv1.2 no-tls-tickets
        ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

        ssl-mode-async
        tune.listener.default-shards by-thread
        tune.http.logurilen 4096
        httpclient.resolvers.prefer ipv4
        tune.ssl.cachesize 100000
        limited-quic
        harden.reject-privileged-ports.tcp  on
        harden.reject-privileged-ports.quic on
        setcap cap_net_bind_service
        tune.quic.reorder-ratio 50
        tune.quic.cc-hystart on


defaults
         mode http
         log  global
         balance leastconn
         option  redispatch
         option  abortonclose
         option  tcp-smart-connect
         http-reuse safe

         timeout http-request    15s
         timeout http-keep-alive 30s
         timeout connect         30s
         timeout check           5s
         timeout queue           1m
         timeout server          1m
         timeout client          1m
         timeout client-fin      15s


frontend ratelimit
         bind <ip>:80
         bind <ip>:443       ssl crt <certificate.pem>
         bind quic4@<ip>:443 ssl crt <certificate.pem> alpn h3

         acl mark src_inc_gpc0(table-ratelimit) -m bool
         tcp-request connection track-sc0 src table table-ip
         tcp-request connection reject if { src_get_gpc0(table-ratelimit) ge 3 }
         http-request deny deny_status 429 if { sc0_http_req_rate(table-ip) gt 5 } mark

         http-after-response add-header alt-svc 'h3=":443"; ma=86400'
         redirect scheme https if !{ ssl_fc }

backend table-ip
        stick-table type ip size 50k expire 30s store conn_rate(30s),conn_cur,gpc0,http_req_rate(30s),http_err_rate(30s)

backend table-ratelimit
        stick-table type ip size 10k expire 1h store gpc0
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.3-95a607c 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Tue May 21 03:13:04 EDT 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Werror=format-security
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.3.1 4 Jun 2024
Running on OpenSSL version : OpenSSL 3.3.1 4 Jun 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.7
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.44 2024-06-07
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-22)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by a-denoyelle** [comment]
I have done several experiment but did not find any difference between TCP and QUIC usage regarding your tcp-request rules. However, it is difficult to test with browsers as their behavior may be surprising. It could be useful if you're able to provide me a faulty scenario using CLI tools such as curl.

**Comment by amsnek** [comment]
sadly, the curl version I currently have availiable does not support H3 -> but I will look into compiling one with H3 support. 
Regarding browsers, I tried with latest FF and Chrome -> as long as protocol H3 appeared in network console (f12) the described behaviour happened. 
do you happen to have access to a curl with h3 support?

**Comment by a-denoyelle** [comment]
I have recompiled curl with ngtcp2 as backend for HTTP/3 support. Maybe it's possible to find docker images as an alternative.

**Comment by amsnek** [comment]
Thank you! After looking a bit more into it, I agree something is very fishy when testing this with Browsers. 
When I am repeatedly pressing F5 -> I am continuing to get the "http 429" displayed in the Browser -> even though it should be dropped already. However, if I then create an incognito tab -> I get the reject "website not reachable" instantly (as would be expected) -> and if I then switch back to the main tab -> I get the same error there. The behaviour differs a bit in browsers when using h2/h3 it seems. 

PS: Due to my simplifcations for the test setup, I also had a logic error in my mark acl -> I corrected it to "-m bool". 

Will do some more testing in the next days but it seems my conclusions were flawed based on observations from Browser behaviour. 
One thing that is maybe worth mentioning, when repeatedly press f5 in the browser haproxy does continue to log "connect from ..." even though it should already be in the reject phase (where it doesnt log anymore). I assume this may be because the browser re-uses the same connection (?) wheras curl creates a new one for every request (and nothing gets logged then once "banned"). I suppose it may be wise to set log-level silent if one wants to avoid excessive logging in this case. 

Should/can I close this issue or should this be closed by a developer?

**Comment by a-denoyelle** [comment]
> Thank you! After looking a bit more into it, I agree something is very fishy when testing this with Browsers. When I am repeatedly pressing F5 -> I am continuing to get the "http 429" displayed in the Browser -> even though it should be dropped already. However, if I then create an incognito tab -> I get the reject "website not reachable" instantly (as would be expected) -> and if I then switch back to the main tab -> I get the same error there. The behaviour differs a bit in browsers when using h2/h3 it seems.

Indeed this is exactly why I though. It's difficult to know when the browser will open a new connection or reuse a new one. And there is also the browser cache which add another layer. With CLI tools it is much more easier to debug such issues.
 
> PS: Due to my simplifcations for the test setup, I also had a logic error in my mark acl -> I corrected it to "-m bool".
> 
> Will do some more testing in the next days but it seems my conclusions were flawed based on observations from Browser behaviour. One thing that is maybe worth mentioning, when repeatedly press f5 in the browser haproxy does continue to log "connect from ..." even though it should already be in the reject phase (where it doesnt log anymore). I assume this may be because the browser re-uses the same connection (?) wheras curl creates a new one for every request (and nothing gets logged then once "banned"). I suppose it may be wise to set log-level silent if one wants to avoid excessive logging in this case.
> 
> Should/can I close this issue or should this be closed by a developer?

I'm closing this issue for now, feel free to reopen it if you have new observations to share.
