### ISSUE TITLE
Resolving bind options from environment variables works incorrectly in HAProxy 3.0.3

### ISSUE THREAD

**Issue by timbi88** [haproxy/haproxy#2651]
### Detailed Description of the Problem

Hello,

I'm using values from environment variables for HAProxy initial config, which was working fine on 2.8.X, but does not work in 3.0.3.

Related part of the config file:
frontend ldap_service_front
  mode                      tcp
  bind                      "${BIND_OPTIONS_LDAP}"
  description               LDAP Service
  timeout client            1800s
  default_backend           ldap_service_back

backend ldap_service_back
  server                    ldap-0 "${LDAP_SERVER_IP}:1389" check inter 5s
  mode                      tcp
  timeout server            1800s
  timeout connect           6s

Environment variable is set to ":::1389 v6only"

The error message during the startup says:
bash-4.4$ /home/bodnartibi/haproxy3.0.3/haproxy -f /home/bodnartibi/haproxy3.0.3/proxy.cfg 
[NOTICE]   (16155) : haproxy version is 3.0.3-95a607c
[NOTICE]   (16155) : path to executable is /home/bodnartibi/haproxy3.0.3/haproxy
[ALERT]    (16155) : config : parsing [/home/bodnartibi/haproxy3.0.3/proxy.cfg :13]  :  'bind' : invalid character  '  '  in port number '1389 v6only' in ':::1389 v6only'
[ALERT]    (16155) : config : Error(s) found in configuration file : /home/bodnartibi/haproxy3.0.3/proxy.cfg 
[ALERT]    (16155) : config : Fatal errors found in configuration.

This was worked fine with haproxy 2.8.9 and it also works if I'm adding ":::1389 v6only" bind options to the config file, without using the environment variable, so I guess it is an issue with the envvar handling (but only for bind options, because resolving LDAP_SERVER_IP works as expected still.

### Expected Behavior

Settings in envvar should work fine still as it worked before in 2.8.X.

### Steps to Reproduce the Behavior

Using values from envvar for bind options in the config, which contains space as delimeter between port number and args.

### Do you have any idea what may have caused this?

-

### Do you have an idea how to solve the issue?

-

### What is your configuration?

```haproxy
frontend ldap_service_front
  mode                      tcp
  bind                      "${BIND_OPTIONS_LDAP}"
  description               LDAP Service
  timeout client            1800s
  default_backend           ldap_service_back

backend ldap_service_back
  server                    ldap-0 "${LDAP_SERVER_IP}:1389" check inter 5s
  mode                      tcp
  timeout server            1800s
  timeout connect           6s
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.3-95a607c 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 5.3.18-57-default #1 SMP Wed Apr 28 10:54:41 UTC 2021 (ba3c2e9) x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_OPENSSL=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with OpenSSL version : OpenSSL 1.1.1l-fips  24 Aug 2021 SUSE release SUSE_OPENSSL_RELEASE
Running on OpenSSL version : OpenSSL 1.1.1l-fips  24 Aug 2021 SUSE release 150500.17.31.1
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by Darlelet** [comment]
Thanks for notifying us

First bad commit seems to be: 65f18d65a3822acaa39418d8e919e9afe1f5e781

**Comment by Darlelet** [comment]
> it also works if I'm adding ":::1389 v6only" bind options to the config file, without using the environment variable

On my side I also have the parsing error with this minimal conf starting with 65f18d6:
```haproxy
frontend ldap_service_front
mode tcp
#bind "${BIND_OPTIONS_LDAP}"
bind ":::1389 v6only"
```

**Comment by timbi88** [comment]
Hi @Darlelet,

Thanks for the quick reply. I tried without double quotes when I added the bind options into the config file directly, maybe that is the reason why it worked to me.

**Comment by Darlelet** [comment]
@timbi88 ok that's it then! thanks for the additional input

When doing with way with the env variable for bind options, previously v6only keyword was in fact handled by the "port" parser, but it was ignored..
But now since 65f18d65a3822acaa39418d8e919e9afe1f5e781 with the port parser being stricter, it is rejected

But the configuration is invalid in the first place, because v6only should be parsed as a separate keyword, not as the port

**Comment by Darlelet** [comment]
Try inputting some garbage keyword instead of `v6only` on 2.8, like `test` (haproxy should start, whereas if you put it directly in the conf, it should reject it)

**Comment by Darlelet** [comment]
So in the end this is a configuration issue, not a bug

For this to work, you need to use a specific syntax to tell haproxy your env variable contains multiple keywords separated by spaces:
```haproxy
frontend ldap_service_front
mode tcp
bind "${BIND_OPTIONS_LDAP[*]}"
```
(`[*]` was appended at the end of the variable name)

This is available starting with 2.3 (see fa41cb6792)

**Comment by timbi88** [comment]
Seems to be working fine with the corrected config. Thank you so much!

**Comment by Darlelet** [comment]
Thanks for confirming! :smile:
I'm closing then

**Comment by timbi88** [comment]
Hi @Darlelet,

Another question which I'm struggling with since I modified the config you suggested. If I'm starting the frontend on both IPv4 and IPv6, then I'm having the following issue:
[ALERT]    (20234) : config : parsing [/home/bodnartibi/haproxy3.0.3/proxy.cfg:13] : 'bind :::1389' in section 'frontend': unknown keyword 'v6only,0.0.0.0:1389'.

BIND_OPTIONS_LDAP is set to ":::1389 v6only, 0.0.0.0:1389"

**Comment by Darlelet** [comment]
Why do you need `v6only` if you want to bind on both v4 and v6?
Try this: `BIND_OPTIONS_LDAP=":::1389 v4v6"`

**Comment by Darlelet** [comment]
or this if you want explicit ipv4 listener:
`BIND_OPTIONS_LDAP=":1389,:::1389 v6only"`
