### ISSUE TITLE
build haproxy with lua undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by jiayjlr** [haproxy/haproxy#2655]
### Detailed Description of the Problem

os： centos7.9
kernel:Linux test 3.10.0-1160.105.1.el7.x86_64 #1 SMP Thu Dec 7 15:39:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

build haproxy 2.9.9 with lua 5.4, exec make error 
make -j $(nproc) TARGET=generic -ljemalloc -lpthread -ldl USE_LIBCRYPT=1 USE_CRYPT_H=1 USE_OPENSSL=1 USE_LUA=1 LUA_INC=/root/jiayj/lua536/include LUA_LIB=/root/jiayj/lua536/lib USE_PCRE=1 USE_ZLIB=1 USE_SYSTEMD=1
......
  LD      dev/flags/flags
/usr/bin/ld: /root/jiayj/lua536/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

### Expected Behavior

/usr/bin/ld: /root/jiayj/lua536/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

### Steps to Reproduce the Behavior

1、install lua
curl -L -R -O https://www.lua.org/ftp/lua-5.4.7.tar.gz
tar zxf lua-5.4.7.tar.gz
cd lua-5.4.7
make all test
2、install haproxy dependent
yum groupinstall "Development Tools"   pcre* pcre2* systemd-devel -y
3、install haproxy
make -j $(nproc) TARGET=generic -ljemalloc -lpthread -ldl USE_LIBCRYPT=1 USE_CRYPT_H=1 USE_OPENSSL=1 USE_LUA=1 LUA_INC=/root/jiayj/lua536/include LUA_LIB=/root/jiayj/lua536/lib USE_PCRE=1 USE_ZLIB=1 USE_SYSTEMD=1

### What is your configuration?

```haproxy
haproxy 2.9.9
```

### Output of `haproxy -vv`

```plain
2.9.9
```

**Comment by Darlelet** [comment]
Since you're building with the generic target, try adding `USE_DL=1` to your build line
(This is required for `-ldl` to be passed to the linker, as `dlclose()` function is provided by libdl)

**Comment by jiayjlr** [comment]
> Since you're building with the generic target, try adding `USE_DL=1` to your build line (This is required for `-ldl` to be passed to the linker, as `dlclose()` function is provided by libdl)

thanks

**Comment by jiayjlr** [comment]
> Since you're building with the generic target, try adding `USE_DL=1` to your build line (This is required for `-ldl` to be passed to the linker, as `dlclose()` function is provided by libdl)

use USE_DL=1,this problem resloved
