### ISSUE TITLE
Crashes since 3.0.3 - A bogus APPCTX

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#2656]
### Detailed Description of the Problem

Crashes since 3.0.3, none before so far

### Expected Behavior

No crashes

### Steps to Reproduce the Behavior

N/A

### Do you have any idea what may have caused this?

peers it seems?

### What is your configuration?

```haproxy
N/A / on request
~54 peers
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.3-95a607c 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 5.10.0-31-amd64 #1 SMP Debian 5.10.221-1 (2024-07-14) x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB= USE_SLZ=1 USE_NS= USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE= USE_PCRE_JIT= USE_PCRE2=1 USE_PCRE2_JIT=
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=48).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by idl0r** [comment]
Please let me know, whom I can send the full gdb backtrace, because it contains some more or less sensitive info, that I might not be able to redact / anonymize properly or it would cause some confusion otherwise. So I'll forward it via mail instead.
I have two crashes / coredumps / backtraces and both *might* belong together.

**Comment by capflam** [comment]
Thanks @idl0r, you can send it to me.

**Comment by idl0r** [comment]
Sent :)

**Comment by capflam** [comment]
@idl0r, sorry for the delay, I was quite busy on other bugs... Here is a first patch that should solve the spinning APPCTX. It may be applied on the 3.0.

[0001-BUG-MEDIUM-peer-Notify-the-applet-won-t-consume-data.patch.txt](https://github.com/user-attachments/files/16458705/0001-BUG-MEDIUM-peer-Notify-the-applet-won-t-consume-data.patch.txt)

For the other coredump, about the segfault in the PT multiplexer, I'm still digging. For me, it is not the same bug.

**Comment by idl0r** [comment]
No problem at all! Thanks for fixing it so quickly!
I'll probably apply that on Monday on the first production nodes.

**Comment by capflam** [comment]
FYI, I pushed the patch above. We will wait a bit for your feedback to backport it. I'm sill on the other crash. But I'm going to be on vacations for 3 weeks. If I'm unable to fix it, I will send info to the other guys :)

**Comment by idl0r** [comment]
Thanks and enjoy your vacation! :)

**Comment by wtarreau** [comment]
No no no, do not encourage him, he must find a fix otherwise he will not be able to relax during his vacation :-)

**Comment by capflam** [comment]
So unfortunately, no fixes... @wtarreau , as crazy as it sounds, I will try hard to not think to haproxy for 3 weeks. But I guess, as usual, you will find a critical bug because of one of my changes. So you will probably think to me :kiss:

**Comment by wtarreau** [comment]
Good point, I had not thought about this :-)

**Comment by idl0r** [comment]
Sorry for the delay but I didn't get to it on Monday. I'll try to get to it tomorrow or otherwise next week.

**Comment by idl0r** [comment]
For the record: Patch applied and rolling out patched versions very slowly. But there have been no more crashes since I filed this issue anyway so hard to tell whether it's fixed or not I guess.

**Comment by wtarreau** [comment]
OK, thanks Christian for letting us know!

**Comment by idl0r** [comment]
Sorry for the delay. There has been one more crash and I already sent the backtrace to @capflam. So we'll see how and were it is related. Otherwise the first fix seems to be ok.

**Comment by capflam** [comment]
Thanks, it is indeed the same than your second crash. This confirms it is unrelated to the peers crash. I will investigate.

**Comment by idl0r** [comment]
Thanks! So I'd consider the first issue to be fixed be the mentioned patch then :)

**Comment by capflam** [comment]
@idl0r, Good news. I finally pushed a patch that should fix your second issue. I'm still unable to reproduce it but I can find a foggy scenario by reading the code that may lead to a crash in the PT multiplexer. It is a bit hard to explain. But you may try with the 2 following commits: 

* 76fa71f7a ("BUG/MEDIUM: mux-pt: Never fully close the connection on shutdown")
* d4781bd5e ("BUG/MEDIUM: cli: Always release back endpoint between two commands on the mcli")

The first one should fix your issue. The second one is mandatory to fix a bug in the master CLI revealed by the first commit... We will emit a 3.0.4 tomorrow.  So you may wait a bit if it is easier for you. Thanks for your help, as usual !

**Comment by idl0r** [comment]
Thanks a lot! :)
Yeah, will wait and upgrade to 3.0.4 tomorrow then.

**Comment by capflam** [comment]
I guess the issue is fixed :) I'm closing

**Comment by idl0r** [comment]
Yeah, look good. Thanks! :)
