### ISSUE TITLE
Broken pipe when sending large sets of commands through the socket on version 3.0.3

### ISSUE THREAD

**Issue by Wahnes** [haproxy/haproxy#2658]
### Detailed Description of the Problem

I'm using a script to update HAproxy's maps via socket commands, using a not so small set of data. This has been working with HAproxy versions 2.4 and 2.8, but is no longer working with version 3.0.

The script uses the threefold approach of `prepare map`, then lots of `add map` with a version number, and finally `commit map`.
The `add map` commands are split into several chunks, each one containing a limited number of entries. Earlier version of HAproxy guided me to do it this way.

With HAproxy 3.0.3, this approch fails with `socat` complaining about `Broken pipe`. The actual `socat` message looks like this:

```
E write(5, 0x5635879cf000, 8192): Broken pipe
```

No further output by HAproxy is generated and the map cannot be updated successfully.

In contrast, when I try to feed a very large list of commands (not broken up into chunks), HAproxy will rightfully complain:

```
The command is too big for the buffer size. Please change tune.bufsize in the configuration to use a bigger command.
```

But like I mentioned, the bug I am seeing is different. This is about a set of commands, where each command is smaller than `tune.bufsize`, but the overall size of these commands is somewhat large when grouped together.

I will try to further explain the problem by giving an example, see below.

### Expected Behavior

HAProxy should process each socket command on its own. There should be no broken pipe.

### Steps to Reproduce the Behavior

1. Use the sample HAproxy config file as given below.
2. Run `touch /etc/haproxy/mytest.map` to create an empty map file (or use `@opt` in the config if you like).
3. Create a running instance of Haproxy 3.0.3 with this sample config.
4. Try to update the example map file through socket commands. Below is an example, using `bash` commands to create a set of socket commands that will cause the issue to appear.

### Example with socket commands not working

```
MAPFILE=/etc/haproxy/mytest.map
# as given in the example HAproxy config file
SOCKET=/var/lib/haproxy/stats3
# as given in the example HAproxy config file

versioninfo=$( /usr/bin/socat $SOCKET stdio <<< "prepare map ${MAPFILE}" | /usr/bin/head -1 )
VERSION=$( /bin/cut -d: -f2 <<< $versioninfo | /usr/bin/grep -o -P '\d+(?=\s|$)' )
COMMANDFILE=/tmp/haproxy.socket.commands

HEADER="add map @${VERSION} $MAPFILE <<"
echo "$HEADER" > $COMMANDFILE
for number in $( seq 1 1000 )
do
  echo "$number onelonglineblahblahblah0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789" >> $COMMANDFILE
  [ $(( number % 101 )) -eq 100 ] && echo >> $COMMANDFILE && echo "$HEADER" >> $COMMANDFILE
done
echo >> $COMMANDFILE

/usr/bin/socat -t2 $SOCKET stdio < $COMMANDFILE

[ $? -eq 0 ] && printf "commit map @%i %s\n" ${VERSION} ${MAPFILE} | /usr/bin/socat $SOCKET stdio
```

On the second but last line, the `broken pipe` error will manifest itself.

### Other example where a proper error message is generated

```
COMMANDFILE=/tmp/haproxy.socket.commands.2
/usr/bin/socat -t2 /var/lib/haproxy/stats stdio <<< "prepare map $MAPFILE"
HEADER="add map @${VERSION} $MAPFILE <<"
echo "$HEADER" > $COMMANDFILE
for number in $( seq 1 1000 )
do
  echo "$number onelonglineblahblahblah0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789" >> $COMMANDFILE
done
echo >> $COMMANDFILE
/usr/bin/socat -t2 $SOCKET stdio < $COMMANDFILE
```

This second example generates one big file with lots of commands. HAProxy will reject this and generate an error message. Contrast this with the first example, that does not generate an error message, but fails instead.

### Do you have an idea how to solve the issue?

I verified that the same example config runs fine with older versions of HAproxy.
Specifically, the following versions to **not** exhibit the issue:

- 2.4.27
- 2.8.10

I was able to verify the map is actually updated in these older versions memory by running
```
/usr/bin/socat $SOCKET stdio <<< "show map ${MAPFILE}"
```
before and after the socket commands. The `show map` gives an empty output (when run before the map update, as the file on disk is empty) and a long list, when invoked after the socket update commands have successfully run.

So I assume the issue has been introduced in versions 2.9 or 3.0.

### What is your configuration?

```haproxy
global
    log         127.0.0.1 local6
    stats socket /var/lib/haproxy/stats3 mode 600 expose-fd listeners level admin
    chroot      /var/lib/haproxy
    user        haproxy
    group       haproxy
    daemon

defaults
    mode                    http
    log                     global
    timeout connect          5s
    timeout client          10s
    timeout server          12s

frontend test
    bind ::1:18080
    acl specialnumber req.hdr(X-Number),map(/etc/haproxy/mytest.map) -m found
    http-request set-var(txn.number) str("special") if specialnumber
    default_backend foo

backend foo
   http-request deny status 404
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.3-95a607c 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 4.18.0-553.8.1.el8_10.x86_64 #1 SMP Tue Jul 2 17:10:26 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA= USE_TFO=1 USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE2_JIT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_
TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION
 -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-22)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

The same thing with the broken pipe also happens when trying to send other larger sets of commands through the socket, e.g. updating a few OCSP responses in a row. (I know that newer HAproxy versions can generate and manage OCSP responses themselves, but I still need the ability to update OCSP responses through socket commands for backward compatibility.)

By this, I mean to say that the issue is not specific to updating maps, but concerns socket commands with larger amounts of data in general.

**Comment by einval22** [comment]
Hi Wahnes !

Thanks a lot for reporting this regression and for the reproduction steps.
Trying to reproduce this one with 3.0.3 and 2.9.

I'll keep you updated.

**Comment by einval22** [comment]
Can not reproduce this with upstream of  haproxy-2.9 branch, so this release apparently  does not contain this issue.

But yes, can simply  reproduce with 3.0-dev9, even when number of key value pairs is  ~600, when it's lower, say 550, all pairs are committed.

**Comment by capflam** [comment]
At first glance, it is an expected change of the 3.0. See 3d93ecc132c591598f8ab6db971845aee0385b82. On 2.8 you should have this warning:

```
[WARNING]  (3107949) : Commands sent to the CLI were chained using a new line character while in non-interactive mode. This is not reliable, not officially supported and will not be supported anymore in future versions. Please use ';' to delimit commands instead.
```

So, it is not possible to chain commands separated by a newline character.  A side effect of this fix is that a command with a payload must be the last command, if chained. Because it is necessarily finished by a newline character.

So, you may switch to interactive mode by prepending a `prompt` command to your commands file. Or you can execute each commands separately.

**Comment by Wahnes** [comment]
Thank you for your eye-opening comment. I must have missed that part about command chaining with newer versions.

So to sum up: using a semicolon does **not** help when trying to use multiple commands to update large map files. This is because the `add map` command needs to be stand-alone due to its own syntax, where an empty line signals the end of the "here document".

The key is to use interactive mode when actually doing non-interactive work, which seems a bit odd, but does the trick.

In case anyone with the same problem is reading this later, I'd like to include one way to generate the required syntax, using the example from above. This works with all versions I tried (2.4, 2.8, and 3.0).

```
MAPFILE=/etc/haproxy/mytest.map
# as given in the example HAproxy config file
SOCKET=/var/lib/haproxy/stats3
# as given in the example HAproxy config file

versioninfo=$( /usr/bin/socat $SOCKET stdio <<< "prepare map ${MAPFILE}" | /usr/bin/head -1 )
VERSION=$( /bin/cut -d: -f2 <<< $versioninfo | /usr/bin/grep -o -P '\d+(?=\s|$)' )
COMMANDFILE=/tmp/haproxy.socket.commands
TMPFILE="${COMMANDFILE}.out"

> $COMMANDFILE
FIRSTLINE="prompt"
HEADER="add map @${VERSION} $MAPFILE <<"
echo "$FIRSTLINE" >> $COMMANDFILE
echo "$HEADER" >> $COMMANDFILE
for number in $( seq 1 1000 )
do
  echo "$number onelonglineblahblahblah0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789" >> $COMMANDFILE
  [ $(( number % 101 )) -eq 100 ] && echo >> $COMMANDFILE && echo "$HEADER" >> $COMMANDFILE
done
echo >> $COMMANDFILE

/usr/bin/socat -t2 $SOCKET stdio < $COMMANDFILE > $TMPFILE
code=$?
/usr/bin/grep -v -P '^(?:>[ +]*|)$' $TMPFILE
# output any non-empty messages from running these commands.
# This allows one to spot errors, but not be bothered by routine output that stems from using interactive mode.

[ $code -eq 0 ] && printf "commit map @%i %s\n" ${VERSION} ${MAPFILE} | /usr/bin/socat $SOCKET stdio
```

**Comment by capflam** [comment]
Well indeed, using interactive mode in this case is not really natural. It is a workaround. I guess the right way to do is to execute one command at a time. It is a limitation of all commands with a payload. chained commands must be separated with a semicolon. Commands with a payload must be finished by the payload pattern, which must be finished by a newline. So it is not possible to chained another command after the payload.

In your case, you can probably execute one `add map` command at a time instead of concatenating them in a file.
