### ISSUE TITLE
DNS timeout and established DNS connection again with lot of backends doesn't resolve all servers (same fqdn)

### ISSUE THREAD

**Issue by pa77777** [haproxy/haproxy#2666]
### Detailed Description of the Problem

So there is problem, lets have 1000 backends with 1 server with same fqdn with `resolvers` on server line
Now drop connection to dns server defined in `resolvers`
Wait when `hold timeout` expire dns ip address and all backends go down
Now establish connection to dns server again
DNS starting to get ip addresses and backends are going UP
Check all backends, ALMOST, not ALL are UP, 982/1000 backends are UP in my case, it' problem
Sometime backends have servers resolved ip but they are in state MAINTENANCE, sometime there is not even resolved ip in server

### Expected Behavior

all backends/servers are UP after DNS server is up again

### Steps to Reproduce the Behavior

1. So there is problem, lets have 1000 backends with 1 server with same fqdn with `resolvers` on server line
2. Now drop connection to dns server defined in `resolvers`
3. Wait when `hold timeout` expire dns ip address and all backends go down
4. Now establish connection to dns server again
5. DNS starting to get ip addresses and backends are going UP
6. Check all backends, ALMOST, not ALL are UP, 982/1000 backends are UP in my case, it' problem !!!
7. Sometime backends have servers resolved but in state MAINTENANCE, sometime there is not even resolved ip in server

### Do you have any idea what may have caused this?

no

### Do you have an idea how to solve the issue?

no

### What is your configuration?

```haproxy
resolvers my_resolver
  nameserver ns1 8.8.8.8:53
  hold nx 30s
  hold obsolete 30s
  hold other 30s
  hold refused 30s
  hold timeout 30s
  hold valid 10s
  timeout resolve 1s
  timeout retry 1s
  accepted_payload_size 512
  resolve_retries 3

backend server_1
  server server.xx.xx server.xx.xx:443 check no-check-ssl ssl resolve-prefer ipv4 resolvers my_resolver ssl sni ssl_fc_sni verify none

backend server_2
  server server.xx.xx server.xx.xx:443 check no-check-ssl ssl resolve-prefer ipv4 resolvers my_resolver ssl sni ssl_fc_sni verify none

.
.
.
# lets have them about 1000
#for i in $(seq 1 1000);do echo "backend server_$i\n  server server server.xx.xx server.xx.xx:443 check no-check-ssl ssl resolve-prefer ipv4 resolvers my_resolver ssl sni ssl_fc_sni verify none";done
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.3-95a607c 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 5.14.0-427.28.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 31 15:28:35 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 1.1.1w+quic  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w+quic  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.4.1 20231218 (Red Hat 11.4.1-3)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by Darlelet** [comment]
I'm not sure to properly understand you're issue. But if multiple servers are expected to share the same IP address (from same FQDN), then you may want to set the `allow-dup-ip` resolver option on server lines:
```haproxy
  server s1 myapp.example.com:80 check resolve-opts allow-dup-ip
```

```
* allow-dup-ip
  By default, HAProxy prevents IP address duplication in a backend when DNS
  resolution at runtime is in operation.
  That said, for some cases, it makes sense that two servers (in the same
  backend, being resolved by the same FQDN) have the same IP address.
  For such case, simply enable this option.
  This is the opposite of prevent-dup-ip.
```
Source: https://docs.haproxy.org/dev/configuration.html#5.2-resolve-opts


On the other hand, if your DNS server answers multiple IP addresses for a given FQDN, since you have 1k servers you may be reaching UDP's payload limitation, preventing you from retrieving all IP addresses. You may want to adjust `accepted_payload_size` for UDP, but depending on your network topology you may not want to do that, plus you won't be able to overcome max UDP payload protocol limitation (65k) anyway. Another option could be to switch to TCP for DNS resolutions (if the DNS server supports it):

```haproxy
resolvers mydns
  nameserver mytcpdns tcp@10.0.0.3:53
```

**Comment by pa77777** [comment]
same with `resolve-opts allow-dup-ip` (I think it's not my case)
same with `accepted_payload_size 65535`

as I said, sometimes server gets ip adress but his `srv_op_state` is 0 forever, until I start haproxy reload, so I think it's something inside haproxy dns/health check

**Comment by Darlelet** [comment]
Oh ok my bad, didn't see that you have 10k backends with 1 server each (and not 10k servers in 1 backend)

I'm checking

**Comment by pa77777** [comment]
now i made 200 servers on `google.com`
```
backend server_1
  server google.com google.com:443 check no-check-ssl ssl resolve-prefer ipv4 resolvers my_resolver ssl sni ssl_fc_sni verify none
backend server_2
  server google.com google.com:443 check no-check-ssl ssl resolve-prefer ipv4 resolvers my_resolver ssl sni ssl_fc_sni verify none
  .
  .
  .
  ```
  ```
  % echo "show servers state"|socat stdio unix-connect:/run/haproxy-master.sock|grep google.com|awk '{ if ( $6 == 2 ) print $0 }'|wc -l
  200
  % iptables -I INPUT -s 8.8.8.8 -j DROP
  % echo "show servers state"|socat stdio unix-connect:/run/haproxy-master.sock|grep google.com|awk '{ if ( $6 == 2 ) print $0 }'|wc -l
  % 0
  % iptables -D INPUT -s 8.8.8.8 -j DROP
   % echo "show servers state"|socat stdio unix-connect:/run/haproxy-master.sock|grep google.com|awk '{ if ( $6 == 2 ) print $0 }'|wc -l
199
  ```
  this is weird ... server has his ip but he is DOWN but he got ipv6 address as only 1 server ... so ipv4 had to fail but he got ipv6 after maybe some error from dns but why is he still DOWN ?
  ```
  % echo "show servers state"|socat stdio unix-connect:/run/haproxy-master.sock|grep google.com|awk '{ if ( $6 != 2 ) print $0 }'
108 server_101 1 google.com 2a00:1450:4014:80a::200e 0 32 1 1 32 6 3 0 14 0 0 0 google.com 443 - 1 0 - - 0
```
in haproxy stats he is in maintenance mode forever

![image](https://github.com/user-attachments/assets/736ff6d1-011f-417b-85e9-9a715a9ff9da)

**Comment by Darlelet** [comment]
Ok, I'm able to reproduce indeed, thanks for your inputs

I'm investigating

**Comment by Darlelet** [comment]
Ok.. so again my bad, regression has been introduced with cd994407a9545a8d84e410dc0cc18c30966b70d8 (this commit is starting to become my nemesis!)

Each time the loop of pending events is interrupted ([tune.events.max-events-at-once](https://docs.haproxy.org/dev/configuration.html#tune.events.max-events-at-once) which defaults to 100), one event is consumed but not acknowledged because the check is done after the event is removed, but before the event is accounted for. It is clearly a bug, likely introduced during commit rebase / cleanup prior to merging.

Another side effect of this bug is memory leak! Because we break from the loop prior to freeing the missed event, which is wrong.

So there it means that over the time the situation will keep degrading (with each DNS flap you may loose 1/100th of your server fleet), plus a small memory leak will occur. While waiting for the fix, a workaround could be to increase max-events-at-once to make sure no servers updates are missed, but this is not suitable above 10 000 because it could trigger the watchdog.

The fix should look like this:
```diff
diff --git a/src/server.c b/src/server.c
index 05f72fffa..0753dce4e 100644
--- a/src/server.c
+++ b/src/server.c
@@ -237,20 +237,6 @@ static struct task *server_atomic_sync(struct task *task, void *context, unsigne
 			break;
 		}
 
-		if (!remain) {
-			/* STOP: we've already spent all our budget here, and
-			 * considering we possibly are under isolation, we cannot
-		         * keep blocking other threads any longer.
-			 *
-			 * Reschedule the task to finish where we left off if
-			 * there are remaining events in the queue.
-			 */
-			if (!event_hdl_async_equeue_isempty(&server_atomic_sync_queue))
-				task_wakeup(task, TASK_WOKEN_OTHER);
-			break;
-		}
-		remain--;
-
 		/* new event to process */
 		if (event_hdl_sub_type_equal(event->type, EVENT_HDL_SUB_SERVER_INETADDR)) {
 			struct sockaddr_storage new_addr;
@@ -327,6 +313,20 @@ static struct task *server_atomic_sync(struct task *task, void *context, unsigne
 			srv_set_addr_desc(srv, 1);
 		}
 		event_hdl_async_free_event(event);
+
+		if (!remain) {
+			/* STOP: we've already spent all our budget here, and
+			 * considering we possibly are under isolation, we cannot
+		         * keep blocking other threads any longer.
+			 *
+			 * Reschedule the task to finish where we left off if
+			 * there are remaining events in the queue.
+			 */
+			if (!event_hdl_async_equeue_isempty(&server_atomic_sync_queue))
+				task_wakeup(task, TASK_WOKEN_OTHER);
+			break;
+		}
+		remain--;
 	}
 
 	/* some events possibly required thread_isolation:
```

**Comment by Darlelet** [comment]
It should be fixed now (available in master, and will end up in 3.0 and 2.9 for upcoming releases)

**Comment by Darlelet** [comment]
Thanks for filing a bug report, as always :)

**Comment by pa77777** [comment]
thank you for fast fix

**Comment by Darlelet** [comment]
You're welcome

We'll keep the issue open for tracking until the fix is backported to relevant versions

**Comment by pa77777** [comment]
it's not fixed in new LTS 3.0.4

**Comment by capflam** [comment]
Indeed. Unfortunately several fixes were not backported by mistake. They will be shipped with the 3.0.5.  Sorry for the delay.

**Comment by capflam** [comment]
The commit was backported to 3.0 and 2.9. Thus I'm closing.

**Comment by pa77777** [comment]
in 3.0.5 fixed
