### ISSUE TITLE
Request to Support for HTTP 429 Response Code in retry-on Directive

### ISSUE THREAD

**Issue by ronyrv13** [haproxy/haproxy#2687]
### Your Feature Request

I would like to request the addition of support for the HTTP 429 response code (Too Many Requests) in the `retry-on` directive within HAProxy. 
Currently, the retry-on directive supports the following status codes:

- 404
- 408
- 425
- 500
- 501
- 502
- 503
- 504

### What are you trying to do?

As the usage of services like OpenAI grows, the occurrence of HTTP 429 responses has become increasingly common. In particular, when working with Azure OpenAI backend pools, the ability to handle these 429 responses gracefully by retrying the request would be immensely beneficial.

Currently, users are opting for alternative solutions such as Azure API Management (APIM), which allows for a custom fallback on 429 responses using C# patches. 
However, if HAProxy could natively support retrying on 429, it would greatly enhance its utility in environments where rate limiting and throttling are prevalent.

Implementing this feature would align HAProxy with the needs of modern applications that frequently encounter rate limiting, providing a more streamlined and powerful solution for managing traffic under such conditions. 

Thank you for considering this request.

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.0
```

**Comment by ronyrv13** [comment]
@capflam - I hope you're doing well! If possible, could you please take a look at this feature request? 
Your insights would be greatly appreciated.
implementing this feature would greatly benefit users managing OpenAI backend pools, where HTTP 429 responses are increasingly common.

**Comment by capflam** [comment]
Indeed, It seems reasonable and not too hard to implement.

**Comment by capflam** [comment]
I added 429 support for retry-on directive. It is pretty simple so I guess we can backport it to 3.0.

**Comment by ronyrv13** [comment]
Thanks, @capflam !. That was some seriously low-latency response time! 🔥 
Any word on when the 3.0.4 release will drop? Can't wait to see that fix for [issues/2643](https://github.com/haproxy/haproxy/issues/2643)

**Comment by capflam** [comment]
Well, we should emit the 3.0.4 soon Maybe before the end of the week but more probably the next week.

**Comment by ronyrv13** [comment]
Hello @capflam 
I performed a Test with the commit you made for the feature request - 
```
RUN git clone https://github.com/haproxy/haproxy.git && \
    cd haproxy && \
    git checkout v3.0.0 && \
    git config user.email "build@example.com" && \
    git config user.name "Build Process" && \
    git cherry-pick 0d142e0756986b56819ecb2d131a0c4b30ae899f
```

But unfortunately the retry-on 429 is not working !!!.. The Proxy is not performing the retry !

With retry-on 429 -

172.17.0.1:39612 [30/Aug/2024:08:15:57.408] main_ingress_fe~ gpt35_backend/aoai_gpt35_01 0/0/0/341/341 429 471 - - ---- 2/1/0/0/0 0/0

With retry-on 503 -

172.17.0.1:45184 [30/Aug/2024:09:26:14.868] main_ingress_fe~ gpt35_backend/aoai_gpt35_01 0/391/0/6093/6484 200 2890 - - ---- 5/1/0/0/+1 
So here with retry-on 503 we can see that +1 where it retried but with 429 it didn't not sure why !!..

My Config -

```haproxy.cfg
frontend main_ingress_fe
    bind :8443 ssl crt server.pem alpn h2,http/1.1 tls-ticket-keys /usr/local/etc/haproxy/tls-ticket-keys.txt

    # Define Header Changes
    http-request del-header api-key

    http-request capture ssl_fc_cipher len 64
    http-request capture ssl_c_s_dn(CN) len 64
    http-request capture ssl_fc_protocol len 64
    http-request capture req.hdr(host) len 64
    http-request set-var(txn.llm_host) req.hdr(host)

    # Define ACLs to match the paths
    acl path_gpt35  path_beg /openai0125
    acl path_gpt4   path_beg /openaigpt4


    use_backend gpt35_backend if path_gpt35
    use_backend gpt4_backend if path_gpt4

backend gpt35_backend
   mode http
   http-request set-path %[path,regsub(^/openai0125,)]
   balance roundrobin
   option redispatch 1 # Redispatch on every retry
   retry-on 429 all-retryable-errors
   retries 3
   server aoai_gpt35_01 unix@/run/haproxy/chatpro-aoai-gpt35-dev-usnc-01.sock weight 10
   server aoai_gpt35_02 unix@/run/haproxy/chatpro-aoai-gpt35-dev-usnc-02.sock weight 10
   # Here i have up to 10 servers


listen aoai_gpt35_01
   mode http
   no log
   bind unix@/run/haproxy/chatpro-aoai-gpt4-dev-use-01.sock
   use_backend chatpro-aoai-gpt4-dev-use-01

backend chatpro-aoai-gpt4-dev-use-01
    mode http
    http-reuse always
    http-request set-header Authorization 'Bearer '%[lua.fetch_token]

    default-server ca-file /etc/ssl/certs/ca-certificates.crt alpn h2,http/1.1 resolvers mydns "${BACKEND_OPTIONS[*]}" pool-purge-delay 30s
    http-request set-header host aoai_gpt35_01.openai.azure.com
    server chatpro-aoai-gpt4-dev-use-01 aoai_gpt35_01.openai.azure.com:443
    http-response lua.handle_429 if { status 429 }


```

Could you please review this? It seems there might have been an oversight in the retry or redispatch code. I’m just speculating, but your input would be appreciated.

**Comment by capflam** [comment]
Damned, you're right. I forgot to update the switch statement in `l7_status_match()` function to handle 429 status ! It should be fixed now.

**Comment by ronyrv13** [comment]
Build failed - https://github.com/haproxy/haproxy/actions/runs/10630924123/job/29470819259

My Local Build Output -

```
0.952 include/haproxy/proxy.h: In function 'l7_status_match':
0.952 include/haproxy/proxy.h:210:41: error: 'PR_RE_429' undeclared (first use in this function); did you mean 'PR_RE_425'?
0.952   210 |                 return (p->retry_type & PR_RE_429);
0.952       |                                         ^~~~~~~~~
0.952       |                                         PR_RE_425
0.952 include/haproxy/proxy.h:210:41: note: each undeclared identifier is reported only once for each function it appears in
1.167 At top level:
1.167 cc1: note: unrecognized command-line option '-Wno-atomic-alignment' may have been intended to silence earlier diagnostics
1.167 cc1: note: unrecognized command-line option '-Wno-string-plus-int' may have been intended to silence earlier diagnostics
1.172 make: *** [Makefile:1041: src/ssl_sock.o] Error 1
1.172 make: *** Waiting for unfinished jobs....
1.210 In file included from src/ssl_ocsp.c:55:
1.210 include/haproxy/proxy.h: In function 'l7_status_match':
1.210 include/haproxy/proxy.h:210:41: error: 'PR_RE_429' undeclared (first use in this function); did you mean 'PR_RE_425'?
1.210   210 |                 return (p->retry_type & PR_RE_429);
1.210       |                                         ^~~~~~~~~
1.210       |                                         PR_RE_425
1.210 include/haproxy/proxy.h:210:41: note: each undeclared identifier is reported only once for each function it appears in
1.270 At top level:
1.270 cc1: note: unrecognized command-line option '-Wno-atomic-alignment' may have been intended to silence earlier diagnostics
1.270 cc1: note: unrecognized command-line option '-Wno-string-plus-int' may have been intended to silence earlier diagnostics
1.274 make: *** [Makefile:1041: src/ssl_ocsp.o] Error 1
```

**Comment by capflam** [comment]
Hum, Have you build the 3.1-HEAD (62c9d51ca) ? You must be sure have the following commits:

* 62c9d51ca ("BUG/MINIR: proxy: Match on 429 status when trying to perform a L7 retry")
* 0d142e075 ("MINOR: proxy: Add support of 429-Too-Many-Requests in retry-on status")

**Comment by ronyrv13** [comment]
Yeah, my bad. I have included both commits, and the build passed. I tested it with retry-on 429, and it's working as expected 👍. 
Thank you so much for the support!

**Comment by capflam** [comment]
FYI, the 3.0.4 was released with the commits above.
