### ISSUE TITLE
haproxy  2.9.x - 3.0.x scrambled data returned with h1.1

### ISSUE THREAD

**Issue by awlx** [haproxy/haproxy#2696]
### Detailed Description of the Problem

Sometimes a request gets back some scrambled data like a server line looks like this:
```
MOt3server: nginx/1.27.1
```

It seems to particularly happen when apt downloads something via haproxy with Range requests or long Content-lengths. But only to a sub section of many many requests.

### Expected Behavior

Don't scramble the reply

### Steps to Reproduce the Behavior

Sadly I didn't find a way yet to reproduce it.

### What is your configuration?

Just a standard h1.1 backend and frontend, with zero-copy-forwarding enabled, not sure if this plays a role here as disabling doesn't seem to make a difference.

### Output of `haproxy -vv`

We saw that behavior also with 2.9 and up to 3.0

```
HAProxy version 3.0.3 2024/07/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.3.html
Running on: Linux 5.15.0-119-generic #129~20.04.1-Ubuntu SMP Wed Aug 7 13:07:13 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fwrapv -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fPIC -fwrapv -DMAX_SYSLOG_LEN=2048
  OPTIONS = USE_THREAD=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1 USE_STATIC_PCRE2=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=64).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by capflam** [comment]
That smells bad. You may indeed try to disable the zero-copy forwarding. For now, I have no idea. Are the scrambled data  in response payload or in the headers part ?

**Comment by awlx** [comment]
It's in the header data, I tried disabling zero-copy it didn't make a difference.

**Comment by capflam** [comment]
Ok, I'm not surprised. Zero-copy only concerns the payload transfer. Do you have any http rules manipulating the headers ? 

You have changed the issue title to specify all 3.0/2.9 releases seem to be affected. Have you in mind a version not affected by the bug ?

**Comment by awlx** [comment]
2.8.10 and lower seems not affected, when we downgrade to this it just works :).

**Comment by awlx** [comment]
```
#15 5.866 Answer for: https://haproxy/focal/pool/main/c/curl/curl_7.74.0-1.3ubuntu2.2+_amd64.deb
#15 5.866 ��Nt6server: nginx/1.27.1
#15 5.866 date: Wed, 28 Aug 2024 17:23:32 GMT
#15 5.866 content-type: application/octet-stream
#15 5.866 content-length: 270344
#15 5.866 last-modified: Thu, 02 Jun 2022 18:45:34 GMT
#15 5.866 etag: "6299054e-42008"
#15 5.866 vary: Accept-Encoding
#15 5.866 accept-ranges: bytes



#15 5.727 Answer for: https://haproxy/focal/pool/main/o/openldap/libldap-common_2.6.7+dfsg-1~exp1+1_all.deb
#15 5.727 HTTP/1.1 200 OK
#15 5.727 server: nginx/1.27.1
#15 5.727 date: Wed, 28 Aug 2024 17:23:32 GMT
#15 5.727 content-type: application/octet-stream
#15 5.727 content-length: 73964
#15 5.727 last-modified: Wed, 13 Mar 2024 20:31:41 GMT
#15 5.727 etag: "65f20d2d-120ec"
#15 5.727 vary: Accept-Encoding
#15 5.727 accept-ranges: bytes

```

Another example of a working and a failing answer.  It looks like the "Statuscode" gets mangled into the Server field somehow. Notice apt is requesting with "HTTP/1.0".

**Comment by capflam** [comment]
There is no obvious change on this area between 2.9 and 2.8 that may explain this bug. At least, at first glance. So, it may a side effect of something unrelated. However it is pretty localized. Is there any processing on the response in your configuration ?

**Comment by capflam** [comment]
Just something strange, if the request is perform in HTTP/1.0, a "Connection" header should be added by Haproxy in the response with "close" or "keep-alive" value depending on the request. This header is not present.

**Comment by awlx** [comment]
This is indeed interesting. So this is all we do to the response header `http-response set-header X-Backend Kubernetes`

**Comment by capflam** [comment]
Hum nothing fancy ...

**Comment by capflam** [comment]
Could you confirm it still happens on 3.0.4/2.9.10 ?

**Comment by capflam** [comment]
@awlx, Have you had the opportunity to test the 3.0.4 or better, the 3.0-HEAD, to check if the issue is still there ?

**Comment by jmdelafe** [comment]
We will test it on 3.0.4 today @capflam. Follow up will come later today or early next week.

**Comment by capflam** [comment]
Following the @awlx's comment on #2749, is the bug still there on the 3.0.4/3.0.5 ?

**Comment by awlx** [comment]
@capflam it existed on 3.0.4 as well, we test 3.0.5 next but we are quite busy atm with Universe upcoming :D.

**Comment by capflam** [comment]
The issue is fixed. But because of a typo the issue was not properly mentioned in the commit message. For records, here is the commit:  b150ae46dd97caa5050d8abefc1d9b619ab5ab9a

Finally this issue is a duplicate of #2779. So I'm closing this one. There are more details on the other one. Thanks !
