### ISSUE TITLE
Socket/Session Leak in HAProxy 2.9.9

### ISSUE THREAD

**Issue by lholder-tl** [haproxy/haproxy#2697]
### Detailed Description of the Problem

We have a few regional clusters of HAProxy servers are all hosted in AWS EC2, running c6/7gn.8xl instance types.  We are generally only seeing this issue in one region, but previously have seen it in all regions.  The cluster currently experiencing this issue is 45 nodes, with a backend count of 700-800 nodes and about 1-1.5mil req/min at peak traffic. We're running AmazonLinux 2023 6.1.87-99.174.amzn2023.aarch64.

We have some tuning for TCP sessions on the instances as well:
```
net.ipv4.tcp_keepalive_time: 600
net.ipv4.tcp_keepalive_intvl: 15
net.ipv4.tcp_keepalive_probes: 6
```

Periodically an instance or 2 ends up with a huge spike in throughput and sessions, however the number of connections to the instance remain steady.  The last time this happened, we've managed to preserve an instance, and there's some discrepancies we're seeing.  After removing the node from the load balancer, it is still holding onto about 67k sessions with ages between 1.5 and 2 days old, when running the srcIP through netstat, the socket has long since been closed by the kernel.  At the peak of the issue, we're seeing `too many orphaned sockets` in the kernel ring buffer:
```
[1123338.372320] TCP: too many orphaned sockets
[1123338.372319] TCP: too many orphaned sockets
[1123338.372320] TCP: too many orphaned sockets
```
We also see an increase in TcpSynRetrans as the issue goes on. 
![image](https://github.com/user-attachments/assets/050ba8ad-8348-47f3-a245-ed5451590175)
Raw sockets:
![image](https://github.com/user-attachments/assets/7a88aab9-86c7-44ea-816c-3e4ee2e0a901)

### Expected Behavior

Sessions to be closed down when sockets are closed on the OS.

### Steps to Reproduce the Behavior

Unsure, we haven't been able to ascertain exactly what causes instances to get into this state.  Until this increase in sessions and traffic all system metrics, haproxy metrics, and backend application performance seems to be in trend.

### What is your configuration?

```haproxy
global
  daemon
  user haproxy
  group haproxy
  master-worker
  nbthread 26
  maxconn 750000
  stats socket /tmp/haproxy.sock mode 666 level admin
  tune.bufsize 32768
  tune.listener.default-shards by-thread
  tune.maxpollevents 190
  tune.maxrewrite 4096
  tune.ssl.default-dh-param 2048
  hard-stop-after 360s
  log stderr format raw local0 err
  server-state-file /etc/haproxy/server-state
  setcap cap_net_raw

defaults redacted_defaults
  mode http
  balance random
  log global
  option redispatch
  option dontlognull
  option http-keep-alive
  option http-no-delay
  option tcpka
  option clitcpka
  option srvtcpka
  option splice-auto
  option forwardfor
  no option idle-close-on-response
  option dontlog-normal
  timeout http-request 25s
  timeout connect 1000ms
  timeout client 330s
  timeout client-fin 10s
  timeout server 240s
  timeout server-fin 10s
  timeout http-keep-alive 320s
  load-server-state-from-file global
  option forwarded

frontend app from redacted_defaults
  bind :8081 accept-proxy
  acl url_status path /status
  no log
  filter compression
  compression algo-res gzip
  stats enable
  stats uri /admin?stats
  stats auth :redacted:
  stats refresh 30s
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
  http-request return status 404 if { path /metrics }
  use_backend app_uptime_backend if url_status
  default_backend backend-localhost-8500-app
  compression direction response

frontend app_http from redacted_defaults
  bind :8480 accept-proxy
  acl url_status path /status
  no log
  filter compression
  compression algo-res gzip
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
  http-request return status 404 if { path /metrics }
  use_backend app_uptime_backend if url_status
  default_backend backend-localhost-8500-app
  compression direction response

frontend healthcheck from redacted_defaults
  bind *:9000 accept-proxy
  acl url_healthcheck path_beg /healthcheck
  no log
  # Return 404 for any other requests
  http-request deny deny_status 404 unless url_healthcheck
  use_backend healthcheck if url_healthcheck

frontend metrics from redacted_defaults
  mode http
  bind :8080
  no log
  http-request use-service prometheus-exporter if { path /metrics }
  http-request return status 200 content-type text/plain string "OK" if { path / }

backend backend-localhost-8500-app from redacted_defaults
  mode http
  option allbackups
  option httpchk GET /status
  http-check expect status 200
  no log 
  default-server check observe layer7 error-limit 250 on-error mark-down inter 3s rise 8 fall 3 fastinter 1s downinter 30s agent-check agent-port 9801 agent-inter 10s slowstart 15s
  http-reuse always
  server SRV_GlnBL <serverIp:port> backup check weight 32
  retries 3
  retry-on all-retryable-errors

backend app_uptime_backend from redacted_defaults
  mode http
  no log
  http-request return status 200 content-type text/plain string "OK" if { nbsrv(backend-localhost-8500-app) gt 0 }
  http-request return status 503 content-type text/plain string "Service Unavailable" unless { nbsrv(backend-localhost-8500-app) gt 0 }

backend healthcheck from redacted_defaults
  mode http
  no log
  http-request return status 200 content-type text/plain string "OK" if { path /healthcheck }

program api
  command /usr/bin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/bin/haproxy -f /etc/haproxy/dataplaneapi.yml --config-file /etc/haproxy/haproxy.cfg --pid-file /run/haproxy/dataplaneapi.pid -r "systemctl reload haproxy" -s "systemctl restart haproxy" --master-worker-mode
  no option start-on-reload
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.9-ad75c48 2024/06/14 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.9.html
Running on: Linux 6.1.87-99.174.amzn2023.aarch64 #1 SMP Tue Apr 23 00:06:47 UTC 2024 aarch64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_THREAD=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT +PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL +STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=32).
Built with OpenSSL version : OpenSSL 3.0.8 7 Feb 2023
Running on OpenSSL version : OpenSSL 3.0.8 7 Feb 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.4.1 20230605 (Red Hat 11.4.1-2)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by capflam** [comment]
There are some issue around the zero-copy forwarding. You may try to disable it by adding `tune.disable-zero-copy-forwarding` in your global section. But otherwise, it could be useful to share output of `show sess all` and a `show fd` CLI commands.

**Comment by dclaisse** [comment]
Hi @capflam, as we might encounter a similare issue as discussed in #2665, I've dumped output of `show sess all `and `show fd`, in case it could help. You may for instance have a look at session `0x7f2fc00bbe00` which seems to be problematic as connection to the backend server 10.168.202.6:21000 is blocked in a CLOSE_WAIT state. There are a lot of other sessions in the same sate, see close_wait.txt for the list.
Tested version here is 2.9.9, with the additional patch that fixes #2665.

[close_wait.txt](https://github.com/user-attachments/files/16814442/close_wait.txt)
[sess_all.txt](https://github.com/user-attachments/files/16814339/sess_all.txt)
[fd.txt](https://github.com/user-attachments/files/16814340/fd.txt)

**Comment by capflam** [comment]
Thanks ! I will take a look.

**Comment by seankumar-tl** [comment]
@capflam - Attaching `show sess all` and `show fd`

[haproxy-session-all.txt](https://github.com/user-attachments/files/16818532/haproxy-session-all.txt)
[haproxy-show-fd.txt.zip](https://github.com/user-attachments/files/16818537/haproxy-show-fd.txt.zip)

We're seeing the issue again on another node, similar pattern as what @lholder-tl mentioned. 

![Screenshot 2024-08-30 at 10 33 15 AM](https://github.com/user-attachments/assets/dd77f62a-8b31-422b-a657-9051521c62d8)

**Comment by capflam** [comment]
@seankumar-tl, can you share your `haproxy -vv` ?

**Comment by seankumar-tl** [comment]
> @seankumar-tl, can you share your `haproxy -vv` ?

It's the same as the one posted in the initial post; see below. 

**HAProxy -vv**

```
[root@ip-10-202-205-206 bin]# haproxy -vv
HAProxy version 2.9.9-ad75c48 2024/06/14 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.9.html
Running on: Linux 6.1.87-99.174.amzn2023.aarch64 #1 SMP Tue Apr 23 00:06:47 UTC 2024 aarch64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_THREAD=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT +PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL +STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=32).
Built with OpenSSL version : OpenSSL 3.0.8 7 Feb 2023
Running on OpenSSL version : OpenSSL 3.0.8 7 Feb 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.4.1 20230605 (Red Hat 11.4.1-2)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by capflam** [comment]
@seankumar-tl, checking your sessions dump, it seems the bug is already fixed in 3.1-DEV (0ba6202796fe24099aeff89a5a4b83af99fc027b) but the commit has not been backported yet. A 3.0.4 and most probably a 2.9.10 should be emitted today, shipping the fix.

@lholder-tl, it could be good to share info about sessions and fds to be sure it is the same issue.

@dclaisse there is nothing strange in your dump. You have several tunneled connections with the server side closed for reads. At this stage client and server timeouts (eventually the tunnel timeout) are armed. However, it seems there is an issue with `client-fin` and `server-fin` timeouts in this case.

**Comment by dclaisse** [comment]
Hi @capflam, the issue I observe is that the haproxy at the other end of the tunnel sent a FIN+ACK to signal it wants to end the connection, but the "client" side here seems to ignore that event, as a consequence its network socket is ending in close-wait state waiting for timeouts to fire whereas it should close the connection immediately. At least this immediate close is what I experience when disabling zerocopy or rolling back to 2.8.10. It seems to me that something is lost in the zerocopy mode.
Can I provide anything to help you move forward on this?

**Comment by capflam** [comment]
FYI, the 3.0.4 and 2.9.10 were released. 

@dclaisse, sorry, but I don't understand what the "client" side and the haproxy at the other end of the tunnel are.  In your dump, it is not obvious there is a problem. I will try to compare with the 2.8.10.

**Comment by lholder-tl** [comment]
@capflam the sessions and fds @seankumar-tl has provided will be from the same infrastructure and instances.

We've also checked the changelog for 2.9.10, but don't see the http-ana bugfix in there.  Can you confirm if it made the cut?

**Comment by seankumar-tl** [comment]
@capflam - Are we sure the bug fix referenced https://github.com/haproxy/haproxy/commit/0ba6202796fe24099aeff89a5a4b83af99fc027b was backported to v2.9.10; looking through the changelog I'm not seeing it, but maybe I'm just missing the proper reference/bug. 

Thank you!

**Comment by capflam** [comment]
@lholder-tl copy that. Thanks for the info.
@seankumar-tl, indeed ! Damned that's unfortunate because it was also missing in the 3.0.4. I'm checking with Willy. Stay tuned.

**Comment by capflam** [comment]
So the commit was backported. Have you any a way to compile HAProxy by hand against the 2.9-§HEAD to test it ?

**Comment by capflam** [comment]
@dclaisse , I performed some tests by creating an HTTP tunnel, on the 3.1-dev, 3.0, 2.9 and 2.8. With or without the zero-copy forwarding on newer versions. I didn't observe any difference. So I guess I'm not doing the right test. What I'm doing:

1. A client sends a CONNECT to a server through haproxy
2.  The server replies with a 200-OK and the tunnel is established.
3.  I can exchange raw data between the client and the server
4. The server closes the connection. At this stage HAProxy is waiting for the client closure

On the other side, if the client closes its connection first, the event is forwarded to the server. At this stage, there is nothing strange, it is exactly the same for TCP connections.  So I guess I'm missing something.

**Comment by seankumar-tl** [comment]
@capflam, we were able to pull the latest HEAD from the 2.9.10 branch, validated the bugfix https://github.com/haproxy/haproxy/commit/0ba6202796fe24099aeff89a5a4b83af99fc027b is in place. We're deploying to our environment now and will report back once we have a few hours of data.

**Comment by dclaisse** [comment]
Hi @capflam, I see _some_ sockets ending in close-wait state, but not all. I'm trying to build a reproducer on my side to get the right trigger. Main driver seems the passive close, i.e. backend server (Squid in the following example) originates session closure.

Our setup schematically looks like this:
Client application -> HAProxy A === mTLS tunnel === HAProxy Z -> Squid -> Internet

Note that if it could matter, client application and HAProxy instance A are running on the same host, and HAProxy instance Z and Squid as well (but on another host).

The issue here is observed on HAProxy instance  A when upgrading to 2.9+. Please have a look at network capture attached for the low level things observed, displayed time is time from last displayed packet, host A is 10.168.197.6 and host Z is 10.168.151.23. I observe that (following the fact that Squid initiated the closure of the connection), HAProxy Z sends a FIN/ACK to HAProxy A, but HAProxy A takes 60s to close the connection waiting for a timeout firing instead of immediately acknowledging the closure, so the connection is blocked in close-wait state during this time. I'd expect packets 4677 and 4678 to be sent immediately, as I observe with 2.8.10.

While HAProxy A -> HAProxy Z socket on host A is in close-wait state, the one on host B is in fin-wait-2 state, which is expected. We could think that HAProxy A is waiting from client application on frontend side to close its socket, but on host A, client application -> HAProxy A socket is closed normally and immediately ends in time-wait state (and to confirm this we don't observe dangling sessions on frontend side in the `show sess all` dumps).

![Capture d’écran 2024-09-04 à 17 16 55](https://github.com/user-attachments/assets/a21c41c9-c8d3-4ae2-aedd-205f02b14944)

**Comment by capflam** [comment]
@dclaisse, I'm back on this issue. So there is still something I don't understand. I trust your analysis, especially because you observed a different behavior  with and without the zero-copy forwarding. But I'm still unable to find a way to reproduce the issue. I guess it could be useful to share the configuration of your haproxy instances. I tried to setup a similar config:  

```
Client <=> HAProxy A === HAProxy B <=> Server
```

The client sends a CONNECT request to the server which replies with a 200-OK. Once the tunnel Established, the server sends data to the client and closes the connection. The event is forwarded to the client. If the client closes the connection on its side, everything is closed on both HAproxy. In my tests, everything is on the same host. 

So, please share configuration of your both haproxy. In addition, it may be useful to have a capture on Haproxy A including the client and another one on HAproxy Z including squid. Ideally, the same without zero-copy forwarding may help. 

Another solution is to enable H1 traces, but only if you have a platform to perform some tests because it is pretty verbose.

**Comment by seankumar-tl** [comment]
@capflam - Regarding the initial issue in this thread, I can confirm we might have a resolution. We've been running our full production workload of over 200MM req/min and have not seen a reoccurrence of stuck sessions/sockets at the moment. We'll continue monitoring this through next week to confirm this is actually fully resolved and not just due to new/fresh instances running the HAProxy cluster. 

Thank you

**Comment by capflam** [comment]
@seankumar-tl , copy that. Thanks for the update. I guess new 3.0/2.9 releases will be emitted soon. And this time, the fix will be shipped with these releases ...

**Comment by dclaisse** [comment]
Hi @capflam, I have managed to enable h1 tracing and capture events on a test platform using HAProxy 3.0.4.
Please find attached haproxy configuration, h1 traces and output of ss listing connections blocked in close-wait state. Let me know if you need anything else.
[h1_traces_2697.txt.gz](https://github.com/user-attachments/files/16931250/h1_traces_2697.txt.gz)
[close_wait_2697.txt](https://github.com/user-attachments/files/16931251/close_wait_2697.txt)
[haproxy_2697.txt](https://github.com/user-attachments/files/16931253/haproxy_2697.txt)

**Comment by capflam** [comment]
Many thanks @dclaisse ! I'm now able to reproduce the issue quite easily. I pushed the fix but you may want to try it. In this case, you can apply the following patch on top of your 3.0/2.9.

[0001-BUG-MAJOR-mux-h1-Wake-SC-to-perform-0-copy-forwardin.patch.txt](https://github.com/user-attachments/files/16934003/0001-BUG-MAJOR-mux-h1-Wake-SC-to-perform-0-copy-forwardin.patch.txt)

A said, a 3.0.5/2.9.11 should be emitted soon.

**Comment by dclaisse** [comment]
Many thanks @capflam, I tested a 3.0.4 with this patch on our test environment, no more leaked connections!

**Comment by capflam** [comment]
The fix was backported to all affected version. I'm closing now. Thanks !
