### ISSUE TITLE
HAProxy configure OpenSSL version

### ISSUE THREAD

**Issue by fwh-dc** [haproxy/haproxy#2699]
### Your Feature Request

I'd like to be able to select the OpenSSL version that HAProxy loads.

### What are you trying to do?

Our system has several versions of OpenSSL installed e.g. 1.1.1 and 3.0. We want to use providers which is a OpenSSL 3.0+ feature only.
But HAProxy picks up 1.1.1 instead of 3.0 at startup.

I asked if it was possible to configure HAProxy at https://discourse.haproxy.org/t/haproxy-configure-openssl-version/10165/
The only solution posted yet is to compile our own version strictly against the OpenSSL version which is not what we want.

### Output of `haproxy -vv`

```plain
HAProxy 2.6
```

**Comment by wlallemand** [comment]
You can't configure the OpenSSL version, you have to build HAProxy and link it with the library you want, or use a package which is linked with it.  Take a look at the install file for build instructions: https://github.com/haproxy/haproxy/blob/master/INSTALL
