### ISSUE TITLE
The problem with updating repositories

### ISSUE THREAD

**Issue by egzhe** [haproxy/haproxy#2705]
### Detailed Description of the Problem

When trying to execute a command `apt update` this error appears
`Игн:1 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main 1.7_x86-64 InRelease
Игн:2 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-update 1.7_x86-64 InRelease
Игн:3 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-base 1.7_x86-64 InRelease
Игн:4 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-extended 1.7_x86-64 InRelease
Игн:1 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main 1.7_x86-64 InRelease
Игн:2 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-update 1.7_x86-64 InRelease
Игн:3 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-base 1.7_x86-64 InRelease
Игн:4 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-extended 1.7_x86-64 InRelease
Игн:1 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main 1.7_x86-64 InRelease
Игн:2 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-update 1.7_x86-64 InRelease
Игн:3 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-base 1.7_x86-64 InRelease
Игн:4 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-extended 1.7_x86-64 InRelease
Ошб:1 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main 1.7_x86-64 InRelease
  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13 8090]
Ошб:2 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-update 1.7_x86-64 InRelease
  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13 8090]
Ошб:3 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-base 1.7_x86-64 InRelease
  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13 8090]
Ошб:4 https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-extended 1.7_x86-64 InRelease
  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13 8090]
Чтение списков пакетов… Готово
Построение дерева зависимостей
Чтение информации о состоянии… Готово
Может быть обновлено 215 пакетов. Запустите «apt list --upgradable» для их показа.
W: Не удалось получить https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-main/dists/1.7_x86-64/InRelease  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13 8090]
W: Не удалось получить https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-update/dists/1.7_x86-64/InRelease  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13 8090]
W: Не удалось получить https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-base/dists/1.7_x86-64/InRelease  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13 8090]
W: Не удалось получить https://dl.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/dists/1.7_x86-64/InRelease  Reading from proxy failed - read (115: Операция выполняется в данный момент) [IP: 192.168.65.13  8090]
W: Некоторые индексные файлы скачать не удалось. Они были проигнорированы, или вместо них были использованы старые версии.`
When you change the repository address in the sources list from https to http, everything starts working.
The Astra Linux 1.7 operating system is used.

### Expected Behavior

When using repositories with https protocol, the `apt update` command should work.

### Steps to Reproduce the Behavior

Run the `apt update` command via proxy on Astra Linux.

### What is your configuration?

```haproxy
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon


        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-R>
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  200000
        timeout server  200000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http


frontend proxy_8090
        mode http
        option httpclose
        bind 192.168.65.13:8090 interface eth0

        use_backend proxy_test if { src -f /etc/haproxy/acl/proxytestusers.acl }
	default_backend proxy_main

backend proxy_main
        balance roundrobin
        server KASPER 192.168.65.7:3128 check send-proxy-v2
        server KASPERSECOND 192.168.65.10:3128 check send-proxy-v2
        server UG 192.168.65.15:8090 backup check


backend proxy_test
        mode http
        option forwardfor header X-Forwarded-For
        server SolarWebProxy 192.168.65.5:2270 check
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.10-1ppa1~jammy 2024/06/16 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.10.html
Running on: Linux 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_OT=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL +OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [  OT] opentracing
        [SPOE] spoe
        [TRACE] trace
```

### Additional Information

Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37230 [04/Sep/2024:05:57:05.686] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2520/2517/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.90/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37242 [04/Sep/2024:05:57:05.693] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2519/2516/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37252 [04/Sep/2024:05:57:05.700] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2520/2517/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37264 [04/Sep/2024:05:57:05.711] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2523/2520/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37276 [04/Sep/2024:05:57:05.713] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2525/2522/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37292 [04/Sep/2024:05:57:05.716] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2524/2521/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37306 [04/Sep/2024:05:57:05.719] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2523/2520/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37320 [04/Sep/2024:05:57:05.724] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2522/2519/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37324 [04/Sep/2024:05:57:05.727] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2521/2518/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37334 [04/Sep/2024:05:57:05.731] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2522/2519/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37340 [04/Sep/2024:05:57:05.738] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2520/2517/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37342 [04/Sep/2024:05:57:05.742] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2521/2518/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37348 [04/Sep/2024:05:57:05.748] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2520/2517/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37362 [04/Sep/2024:05:57:05.750] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2522/2519/0/0/0 0/0 "<BADREQ>"
Sep  4 05:57:05 haproxykaspersky haproxy[538585]: 192.168.56.9:37370 [04/Sep/2024:05:57:05.755] proxy_8090 proxy_8090/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 2523/2520/0/0/0 0/0 "<BADREQ>"

**Comment by wlallemand** [comment]
It looks you didn't configure any ssl on your proxy_8090 frontend, so https can't work.

For configuration assistance please use the discourse https://discourse.haproxy.org/ or the mailing-list https://www.haproxy.org/#tact.
Github is dedicated to bugs and features requests for haproxy!

Thanks,

**Comment by egzhe** [comment]
All https requests work. The problem is with updating repositories over https via a proxy.

**Comment by capflam** [comment]
As @wlallemand said, there is no SSL configured on your proxy. It is a configuration issue not a bug. I'm closing.

**Comment by capflam** [comment]
Talking about it with @wlallemand, it is possible we are misunderstood the issue. I'm reopening

**Comment by capflam** [comment]
you can try to get info about the errors on the CLI via `show errors` command.

**Comment by egzhe** [comment]
We have already solved the problem with the following line:
`option accept-invalid-http-request`

**Comment by capflam** [comment]
Ok, thanks for the update. I'm closing the issue.
