### ISSUE TITLE
QUIC Interop: AWS-LC failed on 0-rtt test, quic-go client

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2718]
### Detailed Description of the Problem

https://github.com/haproxy/haproxy/actions/runs/10894153448

[logs-quic-go.zip](https://github.com/user-attachments/files/17023693/logs-quic-go.zip)

### Expected Behavior

not sure

### Steps to Reproduce the Behavior

run QUIC Interop suite on HAProxy built with aws-lc, quic-go client, 0-rtt test

### What is your configuration?

```haproxy
default QUIC Interop
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by chipitsine** [comment]
I see the same behaviour for official QUIC Interop (which uses QuicTLS)

<img width="704" alt="image" src="https://github.com/user-attachments/assets/4d8e7ced-8fb8-4f93-af14-3938d91855fc">

**Comment by haproxyFred** [comment]
So, if you see the same behavior for the official QUIC interop test runner, there is no need to open a ticket here.
