### ISSUE TITLE
Output Tt-max in Prometheus Interface

### ISSUE THREAD

**Issue by kaizen1** [haproxy/haproxy#272]
-->

HAProxy 2.0.5

## What should haproxy do differently? Which functionality do you think we should add?

One of the most insightful data from HAProxy debug log is transaction by transaction time Tc, Tq, Tr, Tt, which are Time to connect, Time in queue, Time for response and Total Time respectively. 

But unfortunately the 2.0.5 Prometheus implementation, these times are AVERAGED over the prior 1,024 requests. This averaging masks problem transactions. 

My suggestion is to add Tt-max to the HAProxy-Prometheus output. This would tell us how badly we're ACTUALLY doing. Users never see averages, they see ACTUALS, that's why Tt-max would be so valuable. We can track Tt-max over time and then fully understand our "worst case" performance. 

This seems like low hanging fruit with a big payoff in observability. 

## What are you trying to do?

Trying to understand worst case performance times which is available in debug log but not in Prometheus interface.

**Comment by capflam** [comment]
I implemented this feature. Counters to store maximum observed values for Tc, Tq, Tr and Tt have been added. These counters are now reported in the stats and in the prometheus exporter.

**Comment by kaizen1** [comment]
That's excellent! Looking forward to using this information.

**Comment by kaizen1** [comment]
Any idea when this will get into HAProxy 2.x? 
It's a great feature to have.

**Comment by lukastribus** [comment]
Features are not generally backported.

I suggest you use `2.1.0` instead.

**Comment by capflam** [comment]
This is already in all 2.x (2.2-dev, 2.1.0 and 2.0.10). I agree with @lukastribus, most of time, features are not backported, except when the scope it limited and well defined.

@kaizen1, take a look at following metrics:
* `haproxy_backend_max_*_time_seconds`
* `haproxy_server_max_*_time_seconds`

**Comment by lukastribus** [comment]
Ah right, this was actually backported to 2.0. I didn't check the 2.0 tree because a backport was not mentioned in the commits.

**Comment by kaizen1** [comment]
> This is already in all 2.x (2.2-dev, 2.1.0 and 2.0.10). I agree with @lukastribus, most of time, features are not backported, except when the scope it limited and well defined.
> 
> @kaizen1, take a look at following metrics:
> 
> * `haproxy_backend_max_*_time_seconds`
> * `haproxy_server_max_*_time_seconds`

@capflam thanks. I need to update my version.
