### ISSUE TITLE
Backup server used even though non-backup servers are up and OK

### ISSUE THREAD

**Issue by brenc** [haproxy/haproxy#2729]
### Detailed Description of the Problem

Sometime in the last six months or so I noticed a strange issue: sometimes after haproxy is restarted it will route traffic to a backup server even when the non-backup servers report as being OK. Please consider the following config:

```
backend be-radio-api                                                                 
  fullconn 1000
  http-check send meth GET uri / ver HTTP/1.1 hdr host api.foo.com
  http-check expect status 200
  option httpchk

  # Don't rate limit our own IPs.
  acl gateway_ips src [IP]

  stick-table type ipv6 size 1k expire 1m store conn_cur,http_req_rate(1m),http_err_rate(1m) peers local                                                                                                                                                      
  acl limit_exceeded src,table_conn_cur() gt 5                                       
  acl limit_exceeded src,table_http_req_rate() gt 80                                  
  acl limit_exceeded src,table_http_err_rate() gt 80                                                                                                                      
  
  http-request deny deny_status 429 if limit_exceeded !gateway_ips                    
  http-request track-sc0 src
                                                                                      
  stick match src table local/sticky-sessions                                         
  stick store-request src table local/sticky-sessions
  
  server-template radio-api 3 _radio-api._tcp.foo.lan resolvers internal_dns check init-addr none maxconn 100                                                      
  server maintenance-mode localhost:8502 maxconn 200 disabled                        
  server down-mode localhost:8501 maxconn 200 backup
```

"Down mode" serves a nice down page when all servers are unavailable using a local nginx instance. We've used this setup for years in multiple backends without issue. This is how it appears in the admin UI:

![Screenshot 2024-09-25 at 2 58 42 PM](https://github.com/user-attachments/assets/0a9bac59-2c6c-4a09-b7f6-2268c69f6988)

Yet when I query the affected proxy server I get a 503 and down-mode page. The workaround for this is to put down-mode into maint then the backend responds as expected. Putting down-mode back to ready right away brings back the 503 yet puzzlingly if I leave down-mode in maint for a while and switch the state back to ready, that seems to correct the issue permanently.

I've tried to reload haproxy and a few other things but nothing seems to correct this other than the above and a hard restart of the process.

Also, this only seems to happen on this particular backend as far as I know.

### Expected Behavior

Backup servers should only receive traffic when non-backup servers are down.

### Steps to Reproduce the Behavior

This seems random. I rebooted all four proxy servers today after running updates (only OS, not haproxy) and 2/4 of them had this issue and only on this one backend afaik.

### Do you have any idea what may have caused this?

I only started seeing this in maybe the past six months or so.

### Do you have an idea how to solve the issue?

Put the backup server in maint, wait a bit, then put it back to ready. Or just fully restart the process.

### What is your configuration?

```haproxy
global
  crt-base /etc/haproxy/certs

  chroot /var/lib/haproxy

  group haproxy

  log /dev/log len 65535 local1

  lua-prepend-path /opt/haproxy-config/lua/?/init.lua
  lua-prepend-path /opt/haproxy-config/lua/?.lua
  lua-load-per-thread /opt/haproxy-config/lua/delay_request.lua
  lua-load-per-thread /opt/haproxy-config/lua/get_ip_info.lua

  maxconn 50000

  server-state-file /var/lib/haproxy/server_state

  set-dumpable

  # https://mozilla.github.io/server-side-tls/ssl-config-generator/
  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

  ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

  ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

  ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

  ssl-dh-param-file /etc/haproxy/dhparam

  stats socket /run/haproxy/admin.sock user haproxy group haproxy mode 660 level admin
  stats socket localhost:81 level admin

  stats timeout 4h

  tune.h2.initial-window-size 1048576

  user haproxy


defaults
  balance roundrobin
  load-server-state-from-file global
  log global
  mode http
  option contstats
  option dontlog-normal
  option httplog
  option http-buffer-request
  option log-separate-errors
  option redispatch -1
  timeout client 30s
  timeout client-fin 30s
  timeout connect 5s
  timeout queue 10s
  timeout http-keep-alive 5s
  timeout http-request 5s
  timeout server 30s
  timeout tarpit 5s
  timeout tunnel 30s

  errorfile 400 /etc/haproxy/errorfiles/400.http
  errorfile 403 /etc/haproxy/errorfiles/403.http
  errorfile 408 /etc/haproxy/errorfiles/408.http
  errorfile 500 /etc/haproxy/errorfiles/500.http
  errorfile 502 /etc/haproxy/errorfiles/502.http
  errorfile 503 /etc/haproxy/errorfiles/503.http
  errorfile 504 /etc/haproxy/errorfiles/504.http

peers local
  peer {{ ansible_hostname }} 127.0.0.1:10000
  table sticky-sessions type ipv6 size 1k

resolvers internal_dns
  accepted_payload_size 8192 
  parse-resolv-conf

frontend fe-main
  bind {{ ansible_default_ipv4.address }}:80
  bind {{ ansible_default_ipv4.address }}:443 ssl crt /etc/haproxy/certs alpn h2,http/1.1

  bind {{ ansible_default_ipv6.address }}:80
  bind {{ ansible_default_ipv6.address }}:443 ssl crt /etc/haproxy/certs alpn h2,http/1.1

  maxconn 50000 
  no option dontlog-normal
  option forwardfor
  tcp-request inspect-delay 10s

  capture request header Host len 1000
  capture request header X-Forwarded-For len 1000
  capture request header Referer len 1000
  capture request header User-Agent len 1000

  acl host_radio_api hdr_dom(host) -i api.foo.com

  use_backend be-radio-api if host_radio_api

backend be-radio-api                                                                 
  fullconn 1000
  http-check send meth GET uri / ver HTTP/1.1 hdr host api.foo.com
  http-check expect status 200
  option httpchk

  acl gateway_ips src [IP]

  stick-table type ipv6 size 1k expire 1m store conn_cur,http_req_rate(1m),http_err_rate(1m) peers local                                                                                                                                                      
  acl limit_exceeded src,table_conn_cur() gt 5                                       
  acl limit_exceeded src,table_http_req_rate() gt 80                                  
  acl limit_exceeded src,table_http_err_rate() gt 80                                                                                                                      
  
  http-request deny deny_status 429 if limit_exceeded !gateway_ips                    
  http-request track-sc0 src
                                                                                      
  stick match src table local/sticky-sessions                                         
  stick store-request src table local/sticky-sessions
  
  server-template radio-api 3 _radio-api._tcp.foo.lan resolvers internal_dns check init-addr none maxconn 100                                                      
  server maintenance-mode localhost:8502 maxconn 200 disabled                        
  server down-mode localhost:8501 maxconn 200 backup
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.5-8e879a5 2024/09/19 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.5.html
Running on: Linux 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26
) x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_P
ROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS -DDEBUG_DONT_SHARE_POOLS -DDEBUG_POO
L_INTEGRITY

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEV
ICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINU
X_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOL
ETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCR
E_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +R
T +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP
+TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
Running on OpenSSL version : OpenSSL 3.0.14 4 Jun 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by Darlelet** [comment]
I'm wondering if the server-state file could have an impact upon reload (ie: primary servers actually UP, but saved as DOWN in the statefile thus restored as DOWN)

Also if the DNS resolution takes some time after reload (DNS server not yet available, or missing entry), it could explain that the primary servers are temporarily seen as MAINT on haproxy side ("resolving" state) given that you specified `init-addr none`.

When the issue happened, were radio* servers (primary servers) flagged as UP or DOWN/MAINT on the stats page?
Does the issue self-corrects itself after some time (do primary servers end up taking traffic?) or does it always require manual operation to get it to work as expected?

**Comment by Darlelet** [comment]
>I only started seeing this in maybe the past six months or so.

Do you think we can we correlate that with a specific haproxy upgrade?

**Comment by brenc** [comment]
> I'm wondering if the server-state file could have an impact upon reload (ie: primary servers actually UP, but saved as DOWN in the statefile thus restored as DOWN)

I don't think this is the case, but here is the section of the state file for those servers after haproxy is stopped in case I've missed something:
```
40:20 be-radio-api 1 radio-api1 10.10.1.58 2 0 1 1 623 15 3 4 6 0 0 0 docker05.newgrounds.lan 7007 _radio-api._tcp.newgrounds.lan 0 0 - - 0
41:20 be-radio-api 2 radio-api2 10.10.1.57 2 0 1 1 623 15 3 4 6 0 0 0 docker04.newgrounds.lan 7007 _radio-api._tcp.newgrounds.lan 0 0 - - 0
42:20 be-radio-api 3 radio-api3 10.10.1.59 2 0 1 1 623 15 3 4 6 0 0 0 docker06.newgrounds.lan 7007 _radio-api._tcp.newgrounds.lan 0 0 - - 0
43:20 be-radio-api 4 maintenance-mode 127.0.0.1 0 5 1 1 2761488 1 0 0 8 0 0 0 localhost 8502 - 0 0 - - 0
44:20 be-radio-api 5 down-mode 127.0.0.1 2 0 1 1 2761488 1 0 4 0 0 0 0 localhost 8501 - 0 0 - - 0
```
As far as I can tell they are being saved correctly.

> Also if the DNS resolution takes some time after reload (DNS server not yet available, or missing entry), it could explain that the primary servers are temporarily seen as MAINT on haproxy side ("resolving" state) given that you specified `init-addr none`.

Local DNS servers are always available and fast, so I doubt this is the case. Double checked the SRV records, all good.

> When the issue happened, were radio* servers (primary servers) flagged as UP or DOWN/MAINT on the stats page? Does the issue self-corrects itself after some time (do primary servers end up taking traffic?) or does it always require manual operation to get it to work as expected?

UP as I showed in the ticket. It never self-corrects. That's what's puzzling about this. They show up but traffic still gets routed to the backup until I set the backup to maint.

> Do you think we can we correlate that with a specific haproxy upgrade?

Hard to say but I did upgrade to 3.x within the past few months. It's possible it started then.

**Comment by Govind10g** [comment]
I have one question - 

Is this fine with one peers only  -

peers local
  peer {{ ansible_hostname }} 127.0.0.1:10000
  table sticky-sessions type ipv6 size 1k
  
 What is the use case of the peer here as I don't see the another peer so wondering how it will do the peering ?

**Comment by brenc** [comment]
> What is the use case of the peer here as I don't see the another peer so wondering how it will do the peering ?

https://www.haproxy.com/documentation/haproxy-configuration-tutorials/core-concepts/stick-tables/#persist-data-at-reload

**Comment by brenc** [comment]
I fully restarted haproxy on one of our staging servers a couple of times to gather some info and that triggered this issue again. Here's the current state file entries for these servers (same config as above just staging):
```
82:40 be-staging-radio-api 1 staging-radio-api1 10.10.1.60 2 0 1 1 2372 15 3 4 6 0 0 0 staging-docker01.newgrounds.lan 7007 _staging-radio-api._tcp.newgrounds.lan 0 0 - - 0
83:40 be-staging-radio-api 2 staging-radio-api2 10.10.1.62 2 0 1 1 2372 15 3 4 6 0 0 0 staging-docker03.newgrounds.lan 7007 _staging-radio-api._tcp.newgrounds.lan 0 0 - - 0
84:40 be-staging-radio-api 3 staging-radio-api3 10.10.1.61 2 0 1 1 2372 15 3 4 6 0 0 0 staging-docker02.newgrounds.lan 7007 _staging-radio-api._tcp.newgrounds.lan 0 0 - - 0
85:40 be-staging-radio-api 4 maintenance-mode 127.0.0.1 0 5 1 1 2766733 1 0 0 8 0 0 0 localhost 8502 - 0 0 - - 0
86:40 be-staging-radio-api 5 down-mode 127.0.0.1 2 0 1 1 2766733 1 0 4 0 0 0 0 localhost 8501 - 0 0 - - 0
```

UI reports UP/L7OK:
![image](https://github.com/user-attachments/assets/fdc67fa4-e377-4998-ad12-3601c04020ec)

Restarting haproxy seems to only correct this issue sometimes. Here are the log entries from a restart where this issue continues to occur:
```
2024-09-26T14:33:35.280251-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : be-staging-radio-api/staging-radio-api1: IP changed from '(none)' to '10.10.1.60' by 'DNS cache'.
2024-09-26T14:33:35.280812-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : be-staging-radio-api/staging-radio-api2: IP changed from '(none)' to '10.10.1.62' by 'DNS cache'.
2024-09-26T14:33:35.283032-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : be-staging-radio-api/staging-radio-api3: IP changed from '(none)' to '10.10.1.61' by 'DNS cache'.
2024-09-26T14:33:35.283687-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : Server be-staging-radio-api/staging-radio-api1 ('staging-docker01.newgrounds.lan') is UP/READY (resolves again).
2024-09-26T14:33:35.283766-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : Server be-staging-radio-api/staging-radio-api1 administratively READY thanks to valid DNS answer.
2024-09-26T14:33:35.284658-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : Server be-staging-radio-api/staging-radio-api2 ('staging-docker03.newgrounds.lan') is UP/READY (resolves again).
2024-09-26T14:33:35.284717-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : Server be-staging-radio-api/staging-radio-api2 administratively READY thanks to valid DNS answer.
2024-09-26T14:33:35.287705-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : Server be-staging-radio-api/staging-radio-api3 ('staging-docker02.newgrounds.lan') is UP/READY (resolves again).
2024-09-26T14:33:35.287780-04:00 staging-proxy01 haproxy[1838187]: [WARNING]  (1838187) : Server be-staging-radio-api/staging-radio-api3 administratively READY thanks to valid DNS answer.
```
Nothing looks out of the ordinary to me. Traffic should not be getting routed to the backup server.

It looks like setting down-mode (the backup) to maint and then back to ready is the only thing that corrects this issue (until the next restart/reload).

**Comment by Darlelet** [comment]
Thanks for the last inputs

I do suspect something timing related: what if shortly after starting haproxy radio servers are DOWN (waiting for IP resolution), and the backup server is immediately available?

Some client requests could then be served by backup server. Only then radio servers switch to UP state (IP resolution succeeds).. unfortunately, as long as the backup server is online, existing sessions will keep hitting the backup server because of your stick `match+store` directive combination. Session persistence would only be reset if the client doesn't perform any request during 1min which is your expire duration set on the table.. or if the server stored in the stick table entry comes offline.

In your case, it looks like this is what's happening, because as you mentioned, the only way to correct the behavior is to temporarily set the backup server in DOWN state to force existing sessions on the backup server to be recreated on active servers. Reloading haproxy isn't sufficient to correct the issue, because stick table entries are teached by the old process to the new one (sessions persist across reload).. and upon actual restart (stick-table data is reset) the issue may exhibit itself again as it is timing dependent (ie: if some requests land to backup server while the primary servers are about transition from MAINT/resolve to UP state)

Now to explain why this behavior didn't seem to occur prior to 3.0, I may have an explanation: since cd994407a9545a8d84e410dc0cc18c30966b70d8, server addr changes are not instantaneously applied anymore, they are scheduled to be picked by a dedicated task. Thus it may have increased the tiny window between the time the server transitions from MAINT/resolve to UP state during startup (because the server is declared with `init-addr none`, it must resolves first before becoming usable, so it is less likely to be available before the backup one whose IP:port is hardcoded in config).

A possible workaround would be to initialize the primary servers with an IP address with `init-addr`. But since you seem to be relying on DNS discovery it may not be a viable option in your case. Perhaps setting `init-addr last` could help if server's IP address is not expected to change upon reload (this way server's will quickly come back online after restart/reload thanks to the last known address in the state file). Another option could be to start with the backup server in `disabled` state, and only enable it after some time when at least one primary server resolves.. but in the end the backup server was properly doing its job as it was serving early requests while primary servers weren't available yet.

**Comment by Darlelet** [comment]
Another thought: maybe you could condition the stick `store-request` operation to only trigger when there are some active servers, this way session will not persist for backup servers.. meaning that as soon as a primary server comes back online sessions will be recreated on one of the primary servers

**Comment by Darlelet** [comment]
Oh wait, looks like there is already something made for this specific purpose:
https://docs.haproxy.org/dev/configuration.html#5.2-non-stick

**Comment by brenc** [comment]
> I do suspect something timing related:

I think you're right! This is probably exactly what's happening. I suppose there isn't anything in the stick table logic either to know when a backup server has become inactive. This makes sense.

I've added `non-stick` to my down and maintenance mode servers. Over the years I've probably gone through the haproxy config manual many times but I have never seen this option before. I don't know that I would have discovered this myself so I really appreciate your help!

Closing as this is not a bug.
