### ISSUE TITLE
Add sample fetch for HTTP/2 stream ID

### ISSUE THREAD

**Issue by phemmer** [haproxy/haproxy#273]
## What should haproxy do differently? Which functionality do you think we should add?

Add a sample fetch for HTTP/2 stream ID

## What are you trying to do?

For better visibility, reporting, & troubleshooting, we would like to add the HTTP/2 stream ID to our logs.

**Comment by wtarreau** [comment]
I've been missing it as well sometimes. At this point we're facing an API
limitation: the muxes are so much modular that their internals are invisible
from outside and we have no way to extract this stream id. We've identified
we'd need a "getinfo" method on a conn_stream to report some info, but this
will require that we define a list of request types and a portable format
for the response. I tend to think that matching what getsockopt() does is
probably the best approach. We should have classes of requests that are
common between all muxes, and others which are private to certain muxes.

**Comment by capflam** [comment]
This was added by 24059615a7a in 3.0. I'm closing now.
