### ISSUE TITLE
Keepalived + HAproxy FTP with session persistant 

### ISSUE THREAD

**Issue by Azgar1998** [haproxy/haproxy#2737]
### Detailed Description of the Problem

I set up a keppalived load-balancer with haproxy with a virtual IP. In my backend, I only have an FTP server at the moment. However, I have two frontend server with a virtual ip address. My problem is when I'm in the process of copying and I switch my loadbalancer to the front, on the client, it tells me "the session has been finished" and therefore cancels the copy in progress
I read topics concerning sticky tables and their synchronization between load-balancer but it does not seem to work.

Do you have any idea why this is not working without interruption? 

Thanks for your help

### Expected Behavior

I expect the copy to freeze and resume once switched to the second load-balancer

### Steps to Reproduce the Behavior

1 - connection to the FTP client via virtual IP
2 - start a copy
3 - switch the load balancer to the second (disable the haproxy service. keepelived switches if the haproxy service is disabled)

### Do you have any idea what may have caused this?

I read somewhere that the FTP service was not made for transparent failover without service interruption

### What is your configuration?

```haproxy
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:D>
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 50000
        timeout client  500000
        timeout server  500000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

listen stats # Define a listen section called "stats"
  bind *:9000 # Listen on port 9000
  mode http
  stats enable  # Enable stats page
  stats hide-version  # Hide HAProxy version
  stats realm Haproxy\ Statistics  # Title text for popup window
  stats uri /haproxy_stats  # Stats URI
  stats auth Username:Password  # Authentication credentials


peers mycluster
  # local host, active node
   peer local_server ip_local_server:10000

  # standby node
  peer name_standby_server ip_standby_server:10000

#table sticky-sessions type ip size 1m


#FRONTEND CONFIG
frontend fe_ftp
bind virtual_ip:21 transparent
option tcplog
mode tcp

#ACL Lists
#FTP ACL
#acl ftp-test.xyz.com 9 req.ssl_sni -i ftp-test.xyz.com 9
#use_backend be_ftp if ftp-test.xyz.com 9

default_backend be_ftp1



frontend ftp_data
bind 0.0.0.0:40000-65535 transparent
option tcplog
mode tcp

#ACL Lists
#FTP ACL
#acl ftp-test.xyz.com 9 req.ssl_sni -i ftp-test.xyz.com 9
#use_backend be_ftp if ftp-test.xyz.com 9

default_backend be_ftp

#BACKEND CONFIG
backend be_ftp
mode tcp
balance source
#hash-type consistent
stick on src
stick-table type ip size 10240k expire 30m peers mycluster
#tcp-request content track-sc0 src
#stick match src table sticktables/sticky-sessions
#stick store-request src table sticktables/sticky-sessions
server server_name "real_ip_ftp_server" check port 20 source "virtual_ip" inter 1s rise 2 fall 2


backend be_ftp1
mode tcp
balance source
#hash-type consistent
stick on src
stick-table type ip size 10240k expire 30m peers mycluster
tcp-request content track-sc0 src
#stick match src table sticktables/sticky-sessions
#stick store-request src table sticktables/sticky-sessions
server server_name real_ip:20 check port 20 source virtual_ip inter 1s rise 2 fall 2
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.5-1ubuntu3 2024/04/01 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.5.html
Running on: Linux 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/haproxy-k5bseW/haproxy-2.8.5=/usr/src/haproxy-2.8.5-1ubuntu3 -Wdate-time -D_FORTIFY_SOURCE=3 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
Running on OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by einval22** [comment]
Hi Azgar !

Just to confirm, if I've got it well:  you are switching the peer at the moment, when the FTP session to the active node  was opened and some data were copying to/from the backend ?

In that case, yes FTP session will be interrupted and the current connection will be closed. So basically, it is usually a client who should do the reconnect and should restart its upload/download session.

Peers  don't support  the behavior, which you've expected for the FTP sessions:
"I expect the copy to freeze and resume once switched to the second load-balancer".

In general we don't pause the connections established to the node, which is about going down and we don't synchronize them at the moment with  another peer nodes. 

What peers are doing in two words, is the stick-tables synchronization. In case, when you have 2 FTP servers and the client was connected to the first one via haproxy node 1 and then the haproxy node 1 goes down. The next time, when this client will connect to haproxy node 2 (peer of node 1), his request will be still served on the first FTP server. There is no any established connection transfer between nodes.

**Comment by Azgar1998** [comment]
Hello,

Thank you for your response.

That's right. If I understand correctly, state synchronization is not possible between several HA proxy front ends for FTP. but does it work with other protocols (HTTP, SQL, etc.)?

I know that with keepalived this is possible but it requires NAT on the front end. this is not what I want as the type of operation, that's why I use keepalive just for the virtual IP part

Do you know any other way to synchronize connection states between front end servers?

**Comment by einval22** [comment]
> Hello,
> 
> Thank you for your response.
> 
> That's right. If I understand correctly, state synchronization is not possible between several HA proxy front ends for FTP. 

Yes, correct.

> but does it work with other protocols (HTTP, SQL, etc.)?
> 
No, HTTP1/1, HTTPv2 and SQL sessions (TDS) are using TCP as a transport . HAProxy peers synchronization serves only to synchronize stick-tables between peers, not TCP connections states. For this we have the conntrack in kernel and netfilter hooks, but need to dig in its documentation in order to check, that this could be achieved with netfilter between distant hosts. I'm not sure at all here.

Peers stick-tables synchronization will  guarantee, that some SQL client  served by the server X, will continue to be served by this server X, when the frontend, to each it was connected before, goes down. So, the client in this case must reconnect again to the VIP: there will be another peer frontend behind, which will serve its connection and which  will "send"  its connection (in simple words ) again to the server X.

Same for HTTP,  HTTP request is inspected in terms of validity of headers and its content.  But if your POST request was interrupted when the client has start sending data, because some frontend A behind the VIP has gone down, it means that you TCP connection will be closed. So, the client should reconnect again, send the headers and data again.

> I know that with keepalived this is possible but it requires NAT on the front end. this is not what I want as the type of operation, that's why I use keepalive just for the virtual IP part
> 
> Do you know any other way to synchronize connection states between front end servers?

If you need to glue the clients to servers, stick tables is the most reliable way. Peers constantly  exchanging the updates for stick tables, thus each node has the latest updates. 
Idle TCP connections to servers from backend can be reused, but it's only to gain a performance. If server will go down or will encounter an error => connection will be closed.

Hope this responds to your question,
Kind regards

**Comment by einval22** [comment]
Hi Azgar, I suppose we can close this one now.
Feel free to reopen, if there are some more questions.
