### ISSUE TITLE
HaProxy round robin is not working 

### ISSUE THREAD

**Issue by adnanhamdussalam** [haproxy/haproxy#2747]
Hi,
I have configured HAproxy but when I add multiple nodes using round robin it is not working.
I have tested the haproxy (# Backend for read operations) when I set one entry for a single server the haproxy  is connecting but when I set two servers entry and want it to connect to the server in round robin fashion it always connects to one server.

PFA the HAproxy conf settings 
[ha_proxy.txt](https://github.com/user-attachments/files/17280645/ha_proxy.txt)

 Any idea ?

**Comment by wtarreau** [comment]
I'm sorry but there's a form to fill for issue reports, which asks for a certain number of info, precisely to avoid empty questions like this one. Please fill the requested info (version, observations etc). Also, basically everyone is using roundrobin (the default algo), so there is necessarily something wrong with your setup, so you need to provide as many details as you can to be helped. Don't forget to also look at the logs, It's possible for example that one of your server doesn't pass the health checks.

**Comment by adnanhamdussalam** [comment]
Yes you right sorry for not provide the complete details.
The issue has been resolved actually in my haproxy configuration I have added two nodes for read operations and set balance round robin but while connecting to the server using below command it connects to only one server:

[postgres@testbed01 rpm]$ psql -h 10.114.16.50 -p 5001 -U myuser -d ctafiniti
Password for user adnan:
psql (16.4)
Type "help" for help.

ctafiniti=# SELECT inet_server_addr() AS hostname;
   hostname
--------------
 10.114.16.30
(1 row)

ctafiniti=# \q
[postgres@testbed01 rpm]$ psql -h 10.114.16.50 -p 5001 -U myuser -d ctafiniti
Password for user adnan:
psql (16.4)
Type "help" for help.

ctafiniti=# SELECT inet_server_addr() AS hostname;
   hostname
--------------
 10.114.16.30
(1 row)

ctafiniti=# \q

But after adding -W in the command it starts connecting to both servers in round robin fashion as given below:

ctafiniti=# \q
[postgres@testbed01 rpm]$ psql -h 10.114.16.50 -p 5001 -U myuser -W -d ctafiniti
Password:
psql (16.4)
Type "help" for help.

ctafiniti=# SELECT inet_server_addr() AS hostname;
   hostname
--------------
 10.114.16.29
(1 row)

ctafiniti=# \q
[postgres@testbed01 rpm]$ psql -h 10.114.16.50 -p 5001 -U myuser -W -d ctafiniti
Password:
psql (16.4)
Type "help" for help.

ctafiniti=# SELECT inet_server_addr() AS hostname;
   hostname
--------------
 10.114.16.30
(1 row)

ctafiniti=# \q

**Comment by Darlelet** [comment]
From `psql` man page:
```
If the server requires password authentication and a password is not available from other sources such as a .pgpass file, psql will prompt for a password in any case. However, psql will waste a connection attempt finding out that the server wants a password. In some cases it is worth typing -W to avoid the extra connection attempt.
```

Since you only have 2 servers in your backend pool, looks like you always ended on the same node because the first connection was wasted trying to figure out if auth was required.

-> auth attempt -> s1
-> select query -> s2
-> auth attempt -> s1
-> select query -> s2

and so on...

Thus it looks like the issue wasn't related to haproxy after all, thanks for the feedback
