### ISSUE TITLE
Listen to UDP on TCP Mode

### ISSUE THREAD

**Issue by fodhelper** [haproxy/haproxy#2748]
### Your Feature Request

Currently i have this config
```
frontend https_front
  mode tcp
  bind ipv4@:443 alpn h2,http/1.1
  tcp-request inspect-delay 5s
  tcp-request content accept if { req_ssl_hello_type 1 }
  use_backend backend_1 if { req.ssl_sni -m str -i 1.example.com }
  use_backend backend_2 if { req.ssl_sni -m str -i 2.example.com }
```

When i add udp or quic to it `bind quic4@:443 alpn h3` or `bind udp4@:443 alpn h3`, HAProxy gives me errors that i can't use udp for bind
then how can i use different backends for each different h3 sni?

### What are you trying to do?

...

### Output of `haproxy -vv`

```plain
I tested docker official haproxy images and haproxytech/haproxy-docker-ubuntu-quic
no difference
```

**Comment by a-denoyelle** [comment]
You have to use `mode http` for QUIC listeners. Also do not forget to add required ssl parameters.

**Comment by fodhelper** [comment]
So it's not possible to route UDP H3 based on SNI (using req.ssl_sni at layer 4)
Is it possible for you to add this feature to HAProxy or it's impossible?

**Comment by a-denoyelle** [comment]
No currently haproxy only supports HTTP/3 in mode HTTP with SSL termination. There is no plan for now to implement L4 load-balancing for QUIC.
