### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [haproxy/haproxy#2750]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing HAProxy application as shown [here](https://elest.io/open-source/haproxy). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/haproxy)

**Comment by wtarreau** [comment]
Hi!

Sorry but it's unclear to me how this is related to the community project. It seems to me you're looking for placing back links to advertise your products but we don't do such a thing (it would be awkward, we'd advertise tons of products and companies and that would make no sense).

However, if you're looking for a commercial partnership with haproxytech, I invite you to contact haproxy.com instead. Hoping this helps.
