### ISSUE TITLE
2.6.2-16a3646  segfault at 1 ip 000000000053faad

### ISSUE THREAD

**Issue by Bowen-Tang** [haproxy/haproxy#2755]
### Detailed Description of the Problem

Is a Bug?

Syslog:
Oct 14 21:52:48 host-q04 kernel: haproxy[49767]: segfault at 1 ip 000000000053faad sp 00007fbb02fdac10 error 6 in haproxy[4000
00+226000]
Oct 14 21:52:48 host-q04 systemd: haproxy-3390.service: main process exited, code=killed, status=11/SEGV
Oct 14 21:52:48 host-q04 systemd: Unit haproxy-3390.service entered failed state.
Oct 14 21:52:48 host-q04 systemd: haproxy-3390.service failed.
Oct 14 21:52:50 host-q04 systemd: haproxy-3390.service holdoff time over, scheduling restart.
Oct 14 21:52:50 host-q04 systemd: Stopped HAProxy 3390 Load Balancer.
Oct 14 21:52:50 host-q04 systemd: Starting HAProxy 3390 Load Balancer...
Oct 14 21:52:50 host-q04 systemd: Started HAProxy 3390 Load Balancer.
Oct 14 22:10:06 host-q04 kernel: haproxy[50663]: segfault at 1 ip 000000000053faad sp 00007fbd1e7c9c10 error 6 in haproxy[4000
00+226000]
Oct 14 22:10:06 host-q04 systemd: haproxy-3390.service: main process exited, code=killed, status=11/SEGV
Oct 14 22:10:06 host-q04 systemd: Unit haproxy-3390.service entered failed state.
Oct 14 22:10:06 host-q04 systemd: haproxy-3390.service failed.
Oct 14 22:10:08 host-q04 systemd: haproxy-3390.service holdoff time over, scheduling restart.
Oct 14 22:10:08 host-q04 systemd: Stopped HAProxy 3390 Load Balancer.
Oct 14 22:10:08 host-q04 systemd: Starting HAProxy 3390 Load Balancer...
Oct 14 22:10:08 host-q04 systemd: Started HAProxy 3390 Load Balancer.
Oct 14 22:26:51 host-q04 kernel: haproxy[53263]: segfault at 1 ip 000000000053faad sp 00007efe49fc0c10 error 6 in haproxy[4000
00+226000]
Oct 14 22:26:51 host-q04 systemd: haproxy-3390.service: main process exited, code=killed, status=11/SEGV
Oct 14 22:26:51 host-q04 systemd: Unit haproxy-3390.service entered failed state.
Oct 14 22:26:51 host-q04 systemd: haproxy-3390.service failed.
Oct 14 22:26:53 host-q04 systemd: haproxy-3390.service holdoff time over, scheduling restart.
Oct 14 22:26:53 host-q04 systemd: Stopped HAProxy 3390 Load Balancer.
Oct 14 22:26:53 host-q04 systemd: Starting HAProxy 3390 Load Balancer...
Oct 14 22:26:53 host-q04 systemd: Started HAProxy 3390 Load Balancer.
Oct 14 23:12:43 host-q04 kernel: haproxy[55559]: segfault at 1 ip 000000000053faad sp 00007fed5d7c7c10 error 6 in haproxy[4000
00+226000]
Oct 14 23:12:43 host-q04 systemd: haproxy-3390.service: main process exited, code=killed, status=11/SEGV
Oct 14 23:12:43 host-q04 systemd: Unit haproxy-3390.service entered failed state.
Oct 14 23:12:43 host-q04 systemd: haproxy-3390.service failed.
Oct 14 23:12:45 host-q04 systemd: haproxy-3390.service holdoff time over, scheduling restart.
Oct 14 23:12:45 host-q04 systemd: Stopped HAProxy 3390 Load Balancer.
Oct 14 23:12:45 host-q04 systemd: Starting HAProxy 3390 Load Balancer...
Oct 14 23:12:45 host-q04 systemd: Started HAProxy 3390 Load Balancer.
Oct 14 23:15:33 host-q04 kernel: haproxy[61962]: segfault at 1 ip 000000000053faad sp 00007f03e150cc10 error 6 in haproxy[4000
[root@host-q04 ~]# vi /var/log/messages^C
[root@host-q04 ~]# vi /var/log/messages

Haproxy Version
[root@host-q04 ~]# haproxy -v
HAProxy version 2.6.2-16a3646 2022/07/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.2.html
Running on: Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64

OS Info
[root@host-q04 ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@host-q04 ~]# uname -a
Linux host-q04 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@host-q04 ~]# 

### Expected Behavior

Always online

### Steps to Reproduce the Behavior

Always Restart

### What is your configuration?

```haproxy
example:
global                                     # 全局配置。
   log         127.0.0.1 local2            # 定义全局的 syslog 服务器，最多可以定义两个。
   chroot      /var/lib/haproxy            # 更改当前目录并为启动进程设置超级用户权限，从而提高安全性。
   pidfile     /var/run/haproxy.pid        # 将 HAProxy 进程的 PID 写入 pidfile。
   maxconn     4096                        # 单个 HAProxy 进程可接受的最大并发连接数，等价于命令行参数 "-n"。
   nbthread    48                          # 最大线程数。线程数的上限与 CPU 数量相同。
   user        haproxy                     # 同 UID 参数。
   group       haproxy                     # 同 GID 参数，建议使用专用用户组。
   daemon                                  # 让 HAProxy 以守护进程的方式工作于后台，等同于命令行参数“-D”的功能。当然，也可以在命令行中用“-db”参数将其禁用。
   stats socket /var/lib/haproxy/stats     # 统计信息保存位置。

defaults                                   # 默认配置。
   log global                              # 日志继承全局配置段的设置。
   retries 2                               # 向上游服务器尝试连接的最大次数，超过此值便认为后端服务器不可用。
   timeout connect  2s                     # HAProxy 与后端服务器连接超时时间。如果在同一个局域网内，可设置成较短的时间。
   timeout client 30000s                   # 客户端与 HAProxy 连接后，数据传输完毕，即非活动连接的超时时间。
   timeout server 30000s                   # 服务器端非活动连接的超时时间。

listen admin_stats                         # frontend 和 backend 的组合体，此监控组的名称可按需进行自定义。
   bind 0.0.0.0:8080                       # 监听端口。
   mode http                               # 监控运行的模式，此处为 `http` 模式。
   option httplog                          # 开始启用记录 HTTP 请求的日志功能。
   maxconn 10                              # 最大并发连接数。
   stats refresh 30s                       # 每隔 30 秒自动刷新监控页面。
   stats uri /haproxy                      # 监控页面的 URL。
   stats realm HAProxy                     # 监控页面的提示信息。
   stats auth admin:pingcap123             # 监控页面的用户和密码，可设置多个用户名。
   stats hide-version                      # 隐藏监控页面上的 HAProxy 版本信息。
   stats  admin if TRUE                    # 手工启用或禁用后端服务器（HAProxy 1.4.9 及之后版本开始支持）。

listen tidb-cluster                        # 配置 database 负载均衡。
   bind 0.0.0.0:3390                       # 浮动 IP 和 监听端口。
   mode tcp                                # HAProxy 要使用第 4 层的传输层。
   balance leastconn                       # 连接数最少的服务器优先接收连接。`leastconn` 建议用于长会话服务，例如 LDAP、SQL、TSE 等，而不是短会话协议，如 HTTP。该算法是动态的，对于启动慢的服务器，服务器权重会在运行中作调整。
   server tidb-1 10.9.18.229:4000 check inter 2000 rise 2 fall 3       # 检测 4000 端口，检测频率为每 2000 毫秒一次。如果 2 次检测为成功，则认为服务器可用；如果 3 次检测为失败，则认为服务器不可用。
   server tidb-2 10.9.39.208:4000 check inter 2000 rise 2 fall 3
   server tidb-3 10.9.64.166:4000 check inter 2000 rise 2 fall 3
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.2-16a3646 2022/07/22 - https://haproxy.org/
```

**Comment by Darlelet** [comment]
Please update your haproxy version, you are missing a LOT of bugfixes and security fixes.

http://www.haproxy.org/bugs/bugs-2.6.2.html

If the problem persists using latest 2.6, please report back to us
Thanks!

**Comment by Bowen-Tang** [comment]
Thanks.
