### ISSUE TITLE
[runtime-api] Backlash ignored in `add map`/`del map` regex key

### ISSUE THREAD

**Issue by costinsin** [haproxy/haproxy#2756]
### Detailed Description of the Problem

I am using a map file that has a regex key and some value. When I load the entry from the map file, the backslashes (`\`) are kept in the regex key, but when I want to add new keys at runtime, the backstash (`\`) is ignored.

Here is a demo:
```sh
$ echo "show map #1" | socat stdio tcp4-connect:127.0.0.1:8023
0x7f2c1d1026d0 ^file\.loaded\.entry$

$ echo "add map #1 ^tcp\.loaded\.entry$ not-working1" | socat stdio tcp4-connect:127.0.0.1:8023
$ echo "add map #1 ^tcp\\.loaded\\.entry$ not-working2" | socat stdio tcp4-connect:127.0.0.1:8023
$ echo "add map #1 ^tcp\\\.loaded\\\.entry$ not-working3" | socat stdio tcp4-connect:127.0.0.1:8023
$ echo "add map #1 ^tcp\\\\.loaded\\\\.entry$ not-working4" | socat stdio tcp4-connect:127.0.0.1:8023

$ echo "show map #1" | socat stdio tcp4-connect:127.0.0.1:8023
0x7f2c1d1026d0 ^file\.loaded\.entry$
0x7f2c12601010 ^tcp.loaded.entry$ not-working1
0x7f2c12601290 ^tcp.loaded.entry$ not-working2
0x7f2c12601490 ^tcp.loaded.entry$ not-working3
0x7f2c12601710 ^tcp.loaded.entry$ not-working4
```

### Expected Behavior

I would expect the backslash (`\`) not to be ignored. In my situation, the backslash inside the regex changes the behavior of the proxy because unescaped `.` means any character instead of just plain `.`.

Also, I am not able to delete entries that were loaded from a file, because no key is found when the backslashes are dropped.

```sh
$ echo "show map #1" | socat stdio tcp4-connect:127.0.0.1:8023
0x7f2c1d1026d0 ^file\.loaded\.entry$

$ echo "del map #1 ^file\.loaded\.entry$" | socat stdio tcp4-connect:127.0.0.1:8023
Key not found.

$ echo "show map #1" | socat stdio tcp4-connect:127.0.0.1:8023
0x7f2c1d1026d0 ^file\.loaded\.entry$
```

### Steps to Reproduce the Behavior

1. Load a map file from disk at startup that contains regexes as keys. The keys should contain backslashes (`\`), for example `^file\.loaded\.entry$`.
2. Try to delete this entry through the Runtime API
3. Try to add a new entry that also contains backslashes (`\`) through the Runtime API

### What is your configuration?

```haproxy
global
    stats socket ipv4@*:8023 level admin expose-fd listeners

backend test
    balance roundrobin
    mode http

    http-request set-var(txn.value) req.hdr(host),map_reg(/maps/test.map)
    http-response set-header Value %[var(txn.value)] if { var(txn.value) -m found }

    server test test.com

frontend healthcheck
    bind *:8080
    mode http

    default_backend test
```

### Output of `haproxy -vv`

```plain
$ haproxy --vv
HAProxy version 3.0.5-8e879a5 2024/09/19 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.5.html
Running on: Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64
```

**Comment by Darlelet** [comment]
Bash is probably eating them, because I don't see anything in the code that prevents such chars.
Try using single quotes instead of double quotes to send the command to the runtime API:
```bash
echo 'add map #1 ^tcp\\\.loaded\\\.entry$ not-working3' | socat stdio tcp4-connect:127.0.0.1:8023
```

**Comment by costinsin** [comment]
You are right! This is a very weird behavior because initially I have encountered this bug while writing directly on the socket in Golang. Bash was actually a way for you guys to easily reproduce. Now I also fixed it in go by escaping every `\`.

```go
key = strings.ReplaceAll(key, "\\", "\\\\")
```

Thanks for helping me out with this!
