### ISSUE TITLE
Closing a gRPC client connection is not propagated to the gRPC server

### ISSUE THREAD

**Issue by inicula** [haproxy/haproxy#2764]
### Detailed Description of the Problem

I've written a minimal example which mimics my actual setup (where I originally observed this problem). The code for reproducing the issue: https://github.com/inicula/haproxy-grpc-issue:
* `server.go` is a gRPC server that listens on port 50052. It only has a unary method, which loops and prints the status of the context/connection (e.g. closed or not), until the context is closed.
* `client.go` is a gRPC client that connects to the server on 50052 directly, or via a HAProxy instance on 50053 when the `--proxy` flag is given. The client just waits for 3 seconds, after which it cleanly closes the connection (the client will always have time to do this since the server loops until the connection is closed).

Now, my problem is that when I do:

```sh
go run server.go # in terminal 1
go run client.go # in terminal 2
```

After 3 seconds, the context/connection is correctly reported server-side as having been closed by the client. For my use-case, this is the expected behavior.

But when I use HAProxy, as follows:

```sh
cd haproxy # in terminal 1, fresh clone from latest master @ https://github.com/haproxy/haproxy.git
make -j4 TARGET=linux-glibc
./haproxy -f /path/to/haproxy.cfg # see https://github.com/inicula/haproxy-grpc-issue/blob/main/haproxy.cfg
go run server.go # in terminal 2
go run client.go --proxy # in terminal 3
```

Then, after 3 seconds pass, the gRPC client closes the connection, but the connection from the proxy to the server is kept alive (the context keeps being reported as open). For my usecase, this behavior is unexpected.

What I'm trying to do is make the HAProxy scenario behave the same as the no-HAProxy scenario. Meaning that when I close the `client<->proxy` connection, I want the `proxy<->server` connection to be closed too.

I've browsed through a few issues on github and it seems like `option abortonclose` should grant me the behavior I'm looking for, but it doesn't work. Either I don't understand the option correctly, or the option doesn't work as intended.

### Expected Behavior

I would expect that when the `client<->proxy` connection is closed, and `option abortonclose` is set, then the `proxy<->server` connection should be closed too.

### Steps to Reproduce the Behavior

See the first section.

### What is your configuration?

```haproxy
frontend grpc_service
    mode http
    bind :50053 proto h2
    default_backend grpc_servers

backend grpc_servers
    mode http
    option abortonclose
    server s1 127.0.0.1:50052 check proto h2
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.1-dev10-278b96-29 2024/10/19 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = 
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER -OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ -SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG
       spop : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace

Linux zinc 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
```

**Comment by capflam** [comment]
I confirm the issue. The `abortonclose` is broken since bca5e142350db02be91c294c92d738a4d767810e

**Comment by capflam** [comment]
It should be fixed now. Thanks

**Comment by susspectsoftware-dev** [comment]
I tried latest dev. Does not work still disconnects.

**Comment by capflam** [comment]
Sorry, but it is quite light... if there is a real issue, could open a new issue filling the template ? This one is closed since almost 1 year and AFAIK, it was fixed.

**Comment by susspectsoftware-dev** [comment]
thanks for the response. So what happens is after say 2-3 minutes the connection between the client and the proxy resets. Running on: HAProxy version 3.2.4-98813a1

global
    log /dev/log local0
    maxconn 20000
    daemon

defaults
    log global
    maxconn 3000
    mode http
    timeout connect 10s
    timeout client 30s
    timeout server 100s
    option httplog
    #option logasap

# Frontend for gRPC over TLS
frontend grpc_front
    bind *:443 ssl crt deploy/yaml/env/files/haproxy.pem alpn h2
    mode tcp
    default_backend grpc_back

# Backend gRPC servers
backend grpc_back
    mode tcp
    balance roundrobin
    server grpc1 127.0.0.1:3030 check inter 5s fall 3 rise 2


I can't work out why it resets, if I go direct without the proxy all is fine.

**Comment by capflam** [comment]
It seems unrelated to this issue. Maybe the connection timed out. Could you share your log please ?

**Comment by susspectsoftware-dev** [comment]
`[NOTICE]   (79089) : haproxy version is 3.2.4-98813a1
[WARNING]  (79089) : parsing [deploy/yaml/env/files/haproxy.cfg.new:13] : 'option httplog' not usable with frontend 'grpc_front' (needs 'mode http'). Falling back to 'option tcplog'.
Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use kqueue.

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
Using kqueue() as the polling mechanism.
[WARNING]  (79089) : Server grpc_back/grpc1 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT]    (79089) : sendmsg()/writev() failed in logger #1: No such file or directory (errno=2)
[ALERT]    (79089) : backend 'grpc_back' has no server available!
[WARNING]  (79089) : Server grpc_back/grpc1 is UP, reason: Layer4 check passed, check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
00000000:grpc_front.accept(0004)=001e from [127.0.0.1:64905] ALPN=h2
00000001:grpc_front.accept(0004)=0020 from [127.0.0.1:64920] ALPN=h2
00000002:grpc_front.accept(0004)=0022 from [127.0.0.1:64926] ALPN=h2
00000003:grpc_front.accept(0004)=0024 from [127.0.0.1:64928] ALPN=h2
00000004:grpc_front.accept(0004)=0027 from [127.0.0.1:64931] ALPN=h2
00000005:grpc_front.accept(0004)=0026 from [127.0.0.1:64930] ALPN=h2
00000006:grpc_front.accept(0004)=002a from [127.0.0.1:64935] ALPN=h2
00000007:grpc_front.accept(0004)=002c from [127.0.0.1:64939] ALPN=h2
00000008:grpc_front.accept(0004)=002d from [127.0.0.1:64940] ALPN=h2
00000009:grpc_front.accept(0004)=0031 from [127.0.0.1:64948] ALPN=h2
0000000a:grpc_front.accept(0004)=0030 from [127.0.0.1:64947] ALPN=h2
0000000b:grpc_front.accept(0004)=0033 from [127.0.0.1:64950] ALPN=h2
0000000c:grpc_front.accept(0004)=0032 from [127.0.0.1:64949] ALPN=h2
0000000d:grpc_front.accept(0004)=0034 from [127.0.0.1:64951] ALPN=h2
0000000e:grpc_front.accept(0004)=0035 from [127.0.0.1:64952] ALPN=h2
0000000f:grpc_front.accept(0004)=0036 from [127.0.0.1:64953] ALPN=h2
00000010:grpc_front.accept(0004)=0037 from [127.0.0.1:64954] ALPN=h2
00000011:grpc_front.accept(0004)=003b from [127.0.0.1:64958] ALPN=h2
00000012:grpc_front.accept(0004)=0046 from [127.0.0.1:64973] ALPN=h2
00000013:grpc_front.accept(0004)=0048 from [127.0.0.1:64978] ALPN=h2
00000014:grpc_front.accept(0004)=0049 from [127.0.0.1:64979] ALPN=h2
00000015:grpc_front.accept(0004)=004c from [127.0.0.1:64987] ALPN=h2
00000016:grpc_front.accept(0004)=004e from [127.0.0.1:64990] ALPN=h2
00000017:grpc_front.accept(0004)=0050 from [127.0.0.1:64992] ALPN=h2
00000018:grpc_front.accept(0004)=0052 from [127.0.0.1:64996] ALPN=h2
00000019:grpc_front.accept(0004)=0054 from [127.0.0.1:64998] ALPN=h2
0000001a:grpc_front.accept(0004)=0055 from [127.0.0.1:64999] ALPN=h2
0000001b:grpc_front.accept(0004)=0056 from [127.0.0.1:65000] ALPN=h2
0000001c:grpc_front.accept(0004)=0058 from [127.0.0.1:65002] ALPN=h2
0000001d:grpc_front.accept(0004)=0057 from [127.0.0.1:65001] ALPN=h2
0000001e:grpc_front.accept(0004)=0065 from [127.0.0.1:65017] ALPN=h2
0000001f:grpc_front.accept(0004)=0061 from [127.0.0.1:65013] ALPN=h2
00000020:grpc_front.accept(0004)=0062 from [127.0.0.1:65014] ALPN=h2
00000021:grpc_front.accept(0004)=0063 from [127.0.0.1:65015] ALPN=h2
00000022:grpc_front.accept(0004)=0064 from [127.0.0.1:65016] ALPN=h2
00000023:grpc_front.accept(0004)=0066 from [127.0.0.1:65018] ALPN=h2
00000024:grpc_front.accept(0004)=005e from [127.0.0.1:65010] ALPN=h2
00000025:grpc_front.accept(0004)=005f from [127.0.0.1:65011] ALPN=h2
00000026:grpc_front.accept(0004)=0060 from [127.0.0.1:65012] ALPN=h2
00000027:grpc_front.accept(0004)=0070 from [127.0.0.1:65028] ALPN=h2
00000028:grpc_front.accept(0004)=0072 from [127.0.0.1:65030] ALPN=h2
00000029:grpc_front.accept(0004)=0074 from [127.0.0.1:65032] ALPN=h2
0000002a:grpc_front.accept(0004)=0076 from [127.0.0.1:65038] ALPN=h2
0000002b:grpc_front.accept(0004)=0078 from [127.0.0.1:65040] ALPN=h2
0000002c:grpc_front.accept(0004)=007a from [127.0.0.1:65043] ALPN=h2
00000000:grpc_back.srvcls[001e:001f]
00000000:grpc_back.clicls[001e:001f]
00000000:grpc_back.closed[001e:001f]
0000002d:grpc_front.accept(0004)=001e from [127.0.0.1:65048] ALPN=h2
00000001:grpc_back.srvcls[0020:0021]
00000001:grpc_back.clicls[0020:0021]
00000001:grpc_back.closed[0020:0021]
00000002:grpc_back.srvcls[0022:0023]
00000002:grpc_back.clicls[0022:0023]
00000002:grpc_back.closed[0022:0023]
00000003:grpc_back.srvcls[0024:0025]
00000003:grpc_back.clicls[0024:0025]
00000003:grpc_back.closed[0024:0025]
00000004:grpc_back.clicls[0027:0028]
00000004:grpc_back.srvcls[0027:0028]
00000004:grpc_back.closed[0027:0028]
00000005:grpc_back.clicls[0026:0029]
00000005:grpc_back.srvcls[0026:0029]
00000005:grpc_back.closed[0026:0029]
00000006:grpc_back.srvcls[002a:002b]
00000006:grpc_back.clicls[002a:002b]
00000006:grpc_back.closed[002a:002b]
00000008:grpc_back.srvcls[002d:002f]
00000008:grpc_back.clicls[002d:002f]
00000008:grpc_back.closed[002d:002f]
00000007:grpc_back.srvcls[002c:002e]
00000007:grpc_back.clicls[002c:002e]
00000007:grpc_back.closed[002c:002e]
00000009:grpc_back.srvcls[0031:0038]
00000009:grpc_back.clicls[0031:0038]
00000009:grpc_back.closed[0031:0038]
0000000e:grpc_back.srvcls[0035:0042]
0000000e:grpc_back.clicls[0035:0042]
0000000e:grpc_back.closed[0035:0042]
0000000d:grpc_back.srvcls[0034:0041]
0000000d:grpc_back.clicls[0034:0041]
0000000d:grpc_back.closed[0034:0041]
0000000a:grpc_back.srvcls[0030:0039]
0000000a:grpc_back.clicls[0030:0039]
0000000a:grpc_back.closed[0030:0039]
00000011:grpc_back.srvcls[003b:0045]
00000011:grpc_back.clicls[003b:0045]
00000011:grpc_back.closed[003b:0045]
00000010:grpc_back.srvcls[0037:0044]
00000010:grpc_back.clicls[0037:0044]
00000010:grpc_back.closed[0037:0044]
0000000f:grpc_back.srvcls[0036:0043]
0000000f:grpc_back.clicls[0036:0043]
0000000f:grpc_back.closed[0036:0043]
0000000b:grpc_back.srvcls[0033:003a]
0000000b:grpc_back.clicls[0033:003a]
0000000b:grpc_back.closed[0033:003a]
0000000c:grpc_back.srvcls[0032:003c]
0000000c:grpc_back.clicls[0032:003c]
0000000c:grpc_back.closed[0032:003c]
00000012:grpc_back.srvcls[0046:0047]
00000012:grpc_back.clicls[0046:0047]
00000012:grpc_back.closed[0046:0047]
00000014:grpc_back.srvcls[0049:004b]
00000014:grpc_back.clicls[0049:004b]
00000014:grpc_back.closed[0049:004b]
00000013:grpc_back.srvcls[0048:004a]
00000013:grpc_back.clicls[0048:004a]
00000013:grpc_back.closed[0048:004a]
00000015:grpc_back.srvcls[004c:004d]
00000015:grpc_back.clicls[004c:004d]
00000015:grpc_back.closed[004c:004d]
00000016:grpc_back.srvcls[004e:004f]
00000016:grpc_back.clicls[004e:004f]
00000016:grpc_back.closed[004e:004f]
00000017:grpc_back.srvcls[0050:0051]
00000017:grpc_back.clicls[0050:0051]
00000017:grpc_back.closed[0050:0051]
00000018:grpc_back.srvcls[0052:0053]
00000018:grpc_back.clicls[0052:0053]
00000018:grpc_back.closed[0052:0053]
0000001b:grpc_back.srvcls[0056:005b]
0000001b:grpc_back.clicls[0056:005b]
0000001b:grpc_back.closed[0056:005b]
0000001a:grpc_back.srvcls[0055:005a]
0000001a:grpc_back.clicls[0055:005a]
0000001a:grpc_back.closed[0055:005a]
0000001d:grpc_back.srvcls[0057:005d]
0000001d:grpc_back.clicls[0057:005d]
0000001d:grpc_back.closed[0057:005d]
00000019:grpc_back.srvcls[0054:0059]
00000019:grpc_back.clicls[0054:0059]
00000019:grpc_back.closed[0054:0059]
0000001c:grpc_back.srvcls[0058:005c]
0000001c:grpc_back.clicls[0058:005c]
0000001c:grpc_back.closed[0058:005c]
00000022:grpc_back.srvcls[0064:006b]
00000022:grpc_back.clicls[0064:006b]
00000022:grpc_back.closed[0064:006b]
00000020:grpc_back.srvcls[0062:0069]
00000020:grpc_back.clicls[0062:0069]
00000020:grpc_back.closed[0062:0069]
00000025:grpc_back.srvcls[005f:006e]
00000025:grpc_back.clicls[005f:006e]
00000025:grpc_back.closed[005f:006e]
0000001f:grpc_back.srvcls[0061:0068]
0000001f:grpc_back.clicls[0061:0068]
0000001f:grpc_back.closed[0061:0068]
0000001e:grpc_back.srvcls[0065:0067]
0000001e:grpc_back.clicls[0065:0067]
0000001e:grpc_back.closed[0065:0067]
00000023:grpc_back.srvcls[0066:006c]
00000023:grpc_back.clicls[0066:006c]
00000023:grpc_back.closed[0066:006c]
00000021:grpc_back.srvcls[0063:006a]
00000021:grpc_back.clicls[0063:006a]
00000021:grpc_back.closed[0063:006a]
00000026:grpc_back.srvcls[0060:006f]
00000026:grpc_back.clicls[0060:006f]
00000026:grpc_back.closed[0060:006f]
00000024:grpc_back.srvcls[005e:006d]
00000024:grpc_back.clicls[005e:006d]
00000024:grpc_back.closed[005e:006d]
00000027:grpc_back.srvcls[0070:0071]
00000027:grpc_back.clicls[0070:0071]
00000027:grpc_back.closed[0070:0071]
00000028:grpc_back.srvcls[0072:0073]
00000028:grpc_back.clicls[0072:0073]
00000028:grpc_back.closed[0072:0073]
00000029:grpc_back.srvcls[0074:0075]
00000029:grpc_back.clicls[0074:0075]
00000029:grpc_back.closed[0074:0075]
0000002a:grpc_back.srvcls[0076:0077]
0000002a:grpc_back.clicls[0076:0077]
0000002a:grpc_back.closed[0076:0077]
0000002b:grpc_back.srvcls[0078:0079]
0000002b:grpc_back.clicls[0078:0079]
0000002b:grpc_back.closed[0078:0079]
0000002c:grpc_back.srvcls[007a:007b]
0000002c:grpc_back.clicls[007a:007b]
0000002c:grpc_back.closed[007a:007b]`

**Comment by capflam** [comment]
There is no log messages here.

**Comment by capflam** [comment]
Looking at your config, I tempted to say you have some configuration issues. Your frontend and backend are configured as TCP proxies. But your default section lets think you want to configure them as HTTP ones.
So, I suggest you to request some help on the mailing list ( [haproxy@formilux.org](mailto:haproxy@formilux.org)) or the forum (https://discourse.haproxy.org/).

**Comment by susspectsoftware-dev** [comment]
sorry that was me trying to do tcp rather than setting them both to http. I think it is def config but can't seem to work it out.
