### ISSUE TITLE
httpclient in lua library sends to wrong frontend when sending via unix socket

### ISSUE THREAD

**Issue by christopherhibbert** [haproxy/haproxy#2765]
### Detailed Description of the Problem

I'm using HAProxy with some LUA code which performs body rewrites on HTML, I'm following the pattern described here which uses httpclient to send to a frontend bound to a unix socket:

I have a simple test case, attached to the repro steps which recreates the problem.

In it there is a main frontend which traffic arrives at, is then sent to a LUA service which depending on the path in the url sends to frontend 1 or 2 via a call to httpclient.get etc via a unix socket.

If I send two http gets in fairly quick succession, one which has path "/1" and the other "/2", the first reqest is correctly send to frontend1, but the second is incorrectly send to frontend1 too!

I have tested with docker versions:
ghcr.io/haproxytech/haproxy-docker-ubuntu:3.0.3
ghcr.io/haproxytech/haproxy-docker-ubuntu:3.0.5

and both have the same incorrect behaviour.

If I change from using unix sockets to ipv4 to send from the LUA to the frontend (and update the frontend1+2 binds accordingly) then the behaviour is correct. It only seems to be a problem with unix sockets.

Also, if I reduce the "timeout client" in the defaults section, and wait longer than timeout client ms between sending to "/1" and sending to "/2" path then I get correct behaviour.

### Expected Behavior

I expect traffic to be sent to the correct frontent by httpclient in LUA code when using unix sockets 

### Steps to Reproduce the Behavior

Attached zip with bash script to docker run appropriate version of haproxy with LUA code and haproxy.cfg file.
[reacreate_wrong_frontend_chosen.zip](https://github.com/user-attachments/files/17472768/reacreate_wrong_frontend_chosen.zip)

Start haproxy:
`./recreate_wrong_frontend_chosen.sh`

Start python http server 1:
`python3 -m http.server 49001`

Start python http server 2:
`python3 -m http.server 49002`

Curl from two urls which should each go to a different python http server:
`while true; do curl localhost:49000/1; curl localhost:49000/2; sleep 1; done`

There is commented out code in lua file and cfg file to which will demonstrate correct behaviour using ipv4 if you edit each and restart haproxy.

### What is your configuration?

```haproxy
See files attached in repo steps for LUA and bash script. cfg file below:

global
  maxconn 16384
  stats socket /run/haproxy.sock mode 660 level admin expose-fd listeners
  tune.maxrewrite 4096
  log stdout format raw daemon debug
  lua-load /tmp/haproxy-files/haproxy-test-lua.lua

defaults unnamed_defaults_1
  mode http
  log global
  log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
  option http-keep-alive
  http-reuse safe
  timeout connect 50000ms
  timeout client 50000ms
  timeout server 50000ms

userlist haproxy-dataplaneapi
  user admin insecure-password mypassword

frontend device-remote-access
  bind :49000
  http-request use-service lua.test-lua

frontend frontend1
  mode http
  bind unix@/tmp/frontend-socket-1.sock
  #bind abns@frontend-socket-1
  bind ipv4@127.0.0.1:50001

  use_backend backend1

frontend frontend2
  mode http
  bind unix@/tmp/frontend-socket-2.sock
  #bind abns@frontend-socket-2
  #bind ipv4@127.0.0.1:50002

  use_backend backend2

backend backend1
  server server1 127.0.0.1:49001

backend backend2
  server server2 127.0.0.1:49002
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.5-8e879a5 2024/09/19 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.5.html
Running on: Linux 5.15.0-1074-azure #83~20.04.1-Ubuntu SMP Fri Oct 4 21:49:59 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_PTHREAD_EMULATION=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX +PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
Running on OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by Darlelet** [comment]
Thanks for sharing and for the repro, I managed to reproduce the issue up to 2.6

It looks like server connection is reused between multiple requests (while requests should be independent as 2 httpclient requests may point to different endpoints)

**Comment by Darlelet** [comment]
I think I managed to "fix" the issue by ensuring REUSE is explicitly disabled on the httpclient proxy:
```c
diff --git a/src/http_client.c b/src/http_client.c
index a1b976ca0..f16e74492 100644
--- a/src/http_client.c
+++ b/src/http_client.c
@@ -1219,6 +1219,7 @@ struct proxy *httpclient_create_proxy(const char *id)
 		goto err;
 	}
 
+	px->options &= ~PR_O_REUSE_MASK; // ensure REUSE isn't set, because it defaults to PR_O_REUSE_SAFE when creating proxy
 	px->options |= PR_O_WREQ_BODY;
 	px->retry_type |= PR_RE_CONN_FAILED | PR_RE_DISCONNECTED | PR_RE_TIMEOUT;
 	px->options2 |= PR_O2_INDEPSTR;
```

However, we must check if there is no bug related to UNIX sockets in http reuse logic, because it seems weird that the same connection is reused despite the socket path isn't the same between the 2 requests.

**Comment by Darlelet** [comment]
>However, we must check if there is no bug related to UNIX sockets in http reuse logic, because it seems weird that the same connection is reused despite the socket path isn't the same between the 2 requests.

Ok so indeed.. in `conn_calculate_hash_sockaddr()`, nothing is done if sockaddr is not ipv4 nor ipv6. So this means 2 requests with different UNIX socket path may result in the same conn hash, which could result in connection reuse as mentioned above.

I don't know if it was intentional or not to overlook the `AF_UNIX` case in `conn_calculate_hash_sockaddr()`.
Something like this could help:
```c
diff --git a/src/connection.c b/src/connection.c
index 668e626f5..460b43785 100644
--- a/src/connection.c
+++ b/src/connection.c
@@ -2644,6 +2644,7 @@ static void conn_calculate_hash_sockaddr(const struct sockaddr_storage *ss,
 {
 	struct sockaddr_in *addr;
 	struct sockaddr_in6 *addr6;
+	struct sockaddr_un *un;
 
 	switch (ss->ss_family) {
 	case AF_INET:
@@ -2675,6 +2676,14 @@ static void conn_calculate_hash_sockaddr(const struct sockaddr_storage *ss,
 		}
 
 		break;
+
+	case AF_UNIX:
+		un = (struct sockaddr_un *)ss;
+
+		conn_hash_update(hash,
+		                 &un->sun_path, sizeof(un->sun_path),
+		                 hash_flags, param_type_addr);
+		break;
 	}
 }
```
Although I'm not 100% convinced, because we should properly check if the unix socket is ABNS or not to perform the check more efficiently.

**Comment by Darlelet** [comment]
Note: this bug may also affect AF_CUST_SOCKPAIR family since it is not handled in `conn_calculate_hash_sockaddr()`

**Comment by Darlelet** [comment]
Ok so since the underlying issue is not httpclient related, I added the `2.4` flag as well (all stable versions affected), as mentioned in the fix

**Comment by Darlelet** [comment]
Unfortunately, while waiting for the fix I don't see any workaround for the httpclient since reuse policy defaults to SAFE and cannot be modified from config (for the httpclient proxy) :/ I mean, you already found it but the only viable workaround I can come with would be to not using UNIX sockets until the fix is backported..

**Comment by Darlelet** [comment]
Closing as the fix was backported to all stable versions.
