### ISSUE TITLE
updating Docker image(s) for AWS-LC, LibreSSL QUIC testing

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2769]
### Detailed Description of the Problem

sorry for being annoying.

can we please go forward with https://github.com/haproxytech/haproxy-qns/issues/3 ?

### Expected Behavior

passing QUIC Interop tests

### Steps to Reproduce the Behavior

try to run QUIC Interop with AWS-LC or LibreSSL image

### What is your configuration?

```haproxy
default one
```

### Output of `haproxy -vv`

```plain
do not have ((
```

**Comment by a-denoyelle** [comment]
Thanks, I wasn't notified about the issue on haproxy-qns repo. I have replied there, I'm closing the current issue.
