### ISSUE TITLE
merge AWS-LC, LibreSSL QUIC Interop definition into single Dockerfile

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2772]
### Your Feature Request

sorry for being annoying.....
can we please merge https://github.com/haproxytech/haproxy-qns/pull/2 ?

### What are you trying to do?

reduce support efforts

### Output of `haproxy -vv`

```plain
no
```

**Comment by a-denoyelle** [comment]
Done, many thanks for your work.
