### ISSUE TITLE
ASAN enabled qns image

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2777]
### Your Feature Request

please have a look: https://github.com/haproxytech/haproxy-qns/pull/4

### What are you trying to do?

improve QUIC Interop tests

### Output of `haproxy -vv`

```plain
no
```

**Comment by a-denoyelle** [comment]
Thanks, I have replied on the pull request.

**Comment by a-denoyelle** [comment]
BTW, I have activated notification for haproxy-qns repositoty, so it should be not necessary anymore to open issues here.
