### ISSUE TITLE
HAProxy 3.x LTS: H1 corruption noticed

### ISSUE THREAD

**Issue by avachette** [haproxy/haproxy#2779]
### Detailed Description of the Problem

We have upgraded from 2.8.11 LTS to 3.0.5 LTS version of HAProxy.

I noticed some strange behavior on H1 frontend using apt-get on our client nodes toward our Debian repository local endpoint.

When we switch to H2, we don't see the issue anymore.

### Expected Behavior

Having the same behavior than 2.8.11 LTS version.

### Steps to Reproduce the Behavior

1. Bootstrap a docker image
2. Run `apt-get update && apt-get install -y jq curl zip make g++`
3. We see those kind of error messages

E: Failed to fetch http://deb.local/ubuntu/pool/main/g/gcc-11/g%2b%2b-11_11.4.0-1ubuntu1%7e22.04_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:dd83655e38c8ea424397defcbe8c54140571de9d3d3b2cdc5a9e1c5bf0f6ef0675612708bdd33d68f0a8323af374765be6576c4018f48a8be1e146b037532cc8
    - SHA256:b9fe023f121bd9c0400d3938db352385b1fbe186592b2fc639148fad1937101d
    - SHA1:24739f6e336d11059fcd2e7430da3ad5736bf1b6 [weak]
    - MD5Sum:d3e774b5b3c890ee54f327ae69e87595 [weak]
    - Filesize:11423434 [weak]
   Hashes of received file:
    - SHA512:9e6356fafcca53f585abf5b9e6746ab279f00514d732e0fd045bde97f9fab46750dccae076cb3a910b4d405328947ad42cda436be527bb8451d1bee8939b5a23
    - SHA256:e9dbbc10565b08aedf6a402b4f72616eed805da4e87a3c6ad799db8388d5d844
    - SHA1:77ba2e8b80737019e06756c7fcf09348b0f30050 [weak]
    - MD5Sum:c730d13118904a74dd060505d7b169b0 [weak]
    - Filesize:11423434 [weak]
   Last modification reported: Thu, 29 Jun 2023 14:06:44 +0000

### Do you have any idea what may have caused this?

We don't see issues when NAT isn't involved in the network path but reverting from 3.x to 2.8.x version fix our issue.

### Do you have an idea how to solve the issue?

At this moment no because the file size and the HTTP code is 200 when we check HAProxy logs

### What is your configuration?

```haproxy
global
  log /dev/log  local0 info info
  log /dev/log  local6 notice
  chroot /var/lib/haproxy
  stats socket /var/lib/haproxy/admin.sock mode 660 expose-fd listeners level admin
  stats timeout 30s
  user haproxy
  group haproxy
  daemon
  maxconn 2000000
  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
  ssl-default-bind-options no-sslv3 no-tls-tickets
  ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
  ssl-default-server-options no-sslv3 no-tls-tickets
  nbthread 28
  cpu-map 1/1 8
  cpu-map 1/2 9
  cpu-map 1/3 10
  cpu-map 1/4 11
  cpu-map 1/5 12
  cpu-map 1/6 13
  cpu-map 1/7 14
  cpu-map 1/8 15
  cpu-map 1/9 16
  cpu-map 1/10 17
  cpu-map 1/11 18
  cpu-map 1/12 19
  cpu-map 1/13 20
  cpu-map 1/14 21
  cpu-map 1/15 32
  cpu-map 1/16 33
  cpu-map 1/17 34
  cpu-map 1/18 35
  cpu-map 1/19 36
  cpu-map 1/20 37
  cpu-map 1/21 38
  cpu-map 1/22 39
  cpu-map 1/23 40
  cpu-map 1/24 41
  cpu-map 1/25 42
  cpu-map 1/26 43
  cpu-map 1/27 44
  cpu-map 1/28 45
  tune.ssl.default-dh-param 2048
  tune.bufsize 32768
  hard-stop-after 24h

defaults
  log global
  mode tcp
  option httplog
  timeout connect 5000
  timeout client 130000
  timeout server 130000
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

listen stats
  description Global statistics
  bind 10.0.0.1:1936
  mode http
  stats enable
  stats uri /
  stats refresh 10s
  stats hide-version
  stats show-node
  http-request use-service prometheus-exporter if { path /metrics }

frontend http_frontend
  bind 10.0.0.1:80
  mode http
  maxconn 10000
  log-format '{"host":"%H","ident":"haproxy","pid":%pid,"ts":"%Ts","haproxy":{"conn":{"act":%ac,"fe":%fc,"be":%bc,"srv":%sc},"queue":{"backend":%bq,"srv":%sq},"time":{"tq":%TR,"tw":%Tw,"tc":%Tc,"tr":%Tr,"tt":%Tu},"termination_state":"%tsc","retries":%rc,"network":{"client_ip":"%ci","client_port":%cp,"frontend_ip":"%fi","frontend_port":%fp},"ssl":{"version":"%sslv","ciphers":"%sslc"},"request":{"method":"%HM","uri":"%HP","protocol":"%HV","header":{"host":"%[capture.req.hdr(0),json(utf8s)]"}},"name":{"backend":"%b","frontend":"%ft","server":"%s"},"response":{"status_code":%ST},"bytes":{"uploaded":%U,"read":%B}}}'
  option clitcpka
  capture request header Host len 30
  http-request add-header X-Forwarded-Proto https
  http-request add-header X-SSL 1
  http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains"
  use_backend debian_repository_backend

backend debian_repository_backend
  description Back-end for our Debian repository
  mode http
  balance roundrobin
  fullconn 5000
  server mirror-01 10.0.0.10:80 check inter 1s rise 3
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.5-1ppa2~focal 2024/09/24 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.5.html
Running on: Linux 5.4.0-200-generic #220-Ubuntu SMP Fri Sep 27 13:19:16 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv -g -O2 -fdebug-prefix-map=/build/haproxy-yeIe2q/haproxy-3.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=64).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
{"host":"dev-lb-01","ident":"haproxy","pid":944174,"ts":"1730984777","haproxy":{"conn":{"act":642,"fe":381,"be":0,"srv":0},"queue":{"backend":0,"srv":0},"time":{"tq":0,"tw":0,"tc":0,"tr":0,"tt":2},"termination_state":"----","retries":0,"network":{"client_ip":"172.16.0.1","client_port":49735,"frontend_ip":"10.0.0.1","frontend_port":80},"ssl":{"version":"-","ciphers":"-"},"request":{"method":"GET","uri":"/ubuntu/pool/main/libt/libtirpc/libtirpc-dev_1.3.2-2ubuntu0.1_amd64.deb","protocol":"HTTP/1.1","header":{"host":"deb.local"}},"name":{"backend":"debian_repository_backend","frontend":"http_frontend","server":"mirror-01"},"response":{"status_code":200},"bytes":{"uploaded":156,"read":192370}}}
```

**Comment by capflam** [comment]
At first glance, I don't know why this happens. But the 3.0.6 was just released. Could you check it first, to be sure ?

**Comment by avachette** [comment]
Hi Christopher,

I will try it when Vincent will release Debian/Ubuntu packages.

Regards,

**Comment by capflam** [comment]
Copy that, Thanks !

**Comment by avachette** [comment]
Hi Christopher,

I still have the issue with version 3.0.6

Regards,

**Comment by capflam** [comment]
Ok, thanks for the test. For now, I have now idea. Especially if no error is returned in logs and if the file size is good. Have you a way to verify the difference between the two files, the good one and the corrupted one. The diff itself is not essential, the idea is to know where it is placed in the file. At the beginning, at the end or random ?

**Comment by avachette** [comment]
I will try to take a look

**Comment by awlx** [comment]
This is actually the same issue we see here:
https://github.com/haproxy/haproxy/issues/2696

It's also apt which has the issue, we don't see it with other clients.

**Comment by capflam** [comment]
@awlx, but in #2696, the issue also affect the headers. Here, at first glance, only the payload is affected. But it is indeed good to note it only affects apt. I don't know how this could affect the response. But I will keep that in mind. Thanks !

**Comment by avachette** [comment]
We indeed use also nginx on our setup to publish our Debian repositories, thanks @awlx for pointing that out.

For the header part, I can try to do a plain curl!

**Comment by awlx** [comment]
We actually witness both after looking into it deeper. Sorry, was so busy with the other topics to not come back.

But everything which is in common is `apt` is the client and nginx after haproxy. I tried to look at the H1.1 of apt and it seems like it's workaround hell for things :D. But I have no idea how that would affect the responses.

**Comment by avachette** [comment]
Good thing I witness your issue also:

```
Answer for: http://deb.local/ubuntu/pool/main/g/gcc-11/g%2b%2b-11_11.4.0-1ubuntu1%7e22.04_amd64.deb
+*}GZIybserver: nginx
date: Thu, 21 Nov 2024 09:28:20 GMT
content-type: application/octet-stream
content-length: 11423434
last-modified: Thu, 29 Jun 2023 14:06:44 GMT
etag: "649d8ff4-ae4eca"
accept-ranges: bytes
strict-transport-security: max-age=31536000; includeSubDomains
```

**Comment by capflam** [comment]
Ok so, it is indeed the same issue. That really bad. @avachette, have you a way to reproduce it quite easily ? It could be pretty useful to have traces.

**Comment by awlx** [comment]
I looked closer at our internal case and a teammate noted the following, the interesting thing is we see 416 happening with 3.x versions of haproxy:

>  It looks like the requests that gets the HTTP 416 response aren't the issue on their own, but rather the original request that get's a HTTP 200.
> 
> We conclude this due to the fact that we don't see any requests containing the Range HTTP header when we downgrade haproxy to 2.8.9.
> 
> If we run eg. 3.0.3 on the internal proxies, we see requests with Range headers. If we downgrade to 2.8.9 we don't see these requests at all.
> 
> To verify this we ran the tcpdump for 10 minutes on all internal proxies on 2.8.9 without seeing any requests that included the Range option.

So something triggers `apt` to do range-requests with 3.x which tells us not all bytes are correctly transferred and the response to the range-request is a 416.

Sadly it's hard to trigger that case in our environment and capture it with tracing, I never fully managed to reproduce it with VMs. So hopefully @avachette can trace it better :D.

**Comment by avachette** [comment]
On the workflow part:
1. `docker run --platform=linux/amd64 -it ubuntu:jammy /bin/bash`
2. `apt-get update && apt-get -o Debug::Acquire::http=True install g++ -y`

But it's also pretty hard to trigger because I have reports also of working workflow depending on the environment.

I can enable more tracing if you want, it's an HAProxy stack without much load since I deployed it on development.

Anyway locally even if the issue is random on downloaded files by apt, it's always ending in error so if I can enable more traces on HAProxy.

I think we will be able to rule out why things are going crazy hopefully.

**Comment by capflam** [comment]
Ok, so to enable traces on 3.0.x, you should add the following in your config:
```
    ring buf1
        size 104857600 # 10MB
        format timed
        backing-file /tmp/blah

    global
        expose-experimental-directives
        trace h1 sink buf1
        trace h1 level devloper
        trace h1 verbosity complete
        trace h1 start now
```

This will write the H1 traces in /tmp/blah file. You can show the traces by running:
```
  strings /tmp/blah | less
```

If it does not work, you may use haring tool from HAProxy sources. To do so, you should compile it (make dev/haring/haring). Then run
```
  ./dev/haring/haring -f /tmp/blah | less
```

Traces may be disable with `trace 0` CLI command.

**Comment by avachette** [comment]
Seems the global section details are missing

**Comment by capflam** [comment]
Sorry, just a big fingers issue :)

**Comment by avachette** [comment]
Thanks, I will isolate the workflow completely to have the best trace without live development trafic and get back to you.

**Comment by avachette** [comment]
I have a trace, where can I share it to you?

Because it's 111 Megabytes

**Comment by capflam** [comment]
compressed by email it should be good

**Comment by avachette** [comment]
Sent to christopher.faulet@capflam.org

**Comment by capflam** [comment]
Thanks ! I will investigate

**Comment by capflam** [comment]
@avachette based on the traces you sent me, have you any idea which response is corrupted ? Because at first glance, I cannot find any corrupted headers.

**Comment by avachette** [comment]
I did a whole capture unfortunately, I will do an another one and try to isolate one specific package until I have a corruption

**Comment by avachette** [comment]
Shared by e-mail the detail with the new trace.

I will copy it here for the record:

A new capture, on apt side I did see the 30th and 47th request in failure.

```
Err:30 http://deb.deez.re/ubuntu jammy-updates/main amd64 liblsan0 amd64 12.3.0-1ubuntu1~22.04
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:8a6dfb5c47bfed088a480eafa96a24bd878eeac2d35be23bfda65f96c0381525344c894dc40b1aab0b08f8c37babe2525ed7468452e1affae7ccd3cf57edaa7b
   - SHA256:606e212c3cbc8fb622313fdb32f78a024b4b5b9fe54b1cc5a8f731297023b899
   - SHA1:706f66564653d5086e2cbc6b43c7bb0f795b1381 [weak]
   - MD5Sum:609ca6f3e5aca703aa86dab89e80e2a4 [weak]
   - Filesize:1069044 [weak]
  Hashes of received file:
   - SHA512:6af309f25d0295b21d110285b38827de424ab528ae245896e7541a430a65b0ec8a578c16905f69cdb9a5f3e7ec895bd5f73967fe1917d49e7e0a55a086f019c5
   - SHA256:f0f28c9f17a726946b5063bed4bc5c7694d07ab29e8fec72e31095461fbcb7ec
   - SHA1:fd192586dd98754d60dd55475239d424165e8aa4 [weak]
   - MD5Sum:f8c1b02cf1759f2b52b433a9b4f91201 [weak]
   - Filesize:1069044 [weak]
  Last modification reported: Thu, 29 Jun 2023 14:09:25 +0000
```

```
Err:47 http://deb.deez.re/ubuntu jammy-updates/main amd64 libfreetype6 amd64 2.11.1+dfsg-1ubuntu0.2
  Hash Sum mismatch
  Hashes of expected file:
   - SHA512:888b706cd852029a1ecb59937dd9d9ae615baa3a1044c4e4aa5f696400ed34bd5d0c63b5a12e6fa20afe329591e4c902b0ff05b8a7b614dc20eb86cb37a45c2d
   - SHA256:8a5ea24cb79eb6955fe5f48f9f1a5ccf89227b8f559357686071956fd403f37c
   - SHA1:15463a70a30b4633a0c672db10a0cb6075253e20 [weak]
   - MD5Sum:e64a7c5ea2ef02fd6c77009cfcfb3490 [weak]
   - Filesize:388826 [weak]
  Hashes of received file:
   - SHA512:f4b467bab80a8635b0c28056a3d10b65892a5e5594e164ace35412c635d4c5621abd39a757387d542309d5a00b53e394b8e53347d89f7b611763821674e911c6
   - SHA256:e2932044e0aa5927d1fd5e200d61216b750dcb2fad327693b86f013bac9ec03c
   - SHA1:cebd013cd448588b79daa09c37885cb6b6ffe11e [weak]
   - MD5Sum:257a9e73afcd7b2c9c1b74a3be6efa79 [weak]
   - Filesize:388826 [weak]
  Last modification reported: Tue, 09 May 2023 11:58:43 +0000
```

And I did see something which wasn't highly spotable before on the 4th call:

```
Err:4 http://deb.deez.re/ubuntu jammy/main amd64 libpng16-16 amd64 1.6.37-3build5
  Bad header line Bad header data [IP: 10.66.120.6 80]
```

**Comment by capflam** [comment]
Thanks, I checked and there is nothing wrong in the trace. For the payload it is not surprising because the content itself is not displayed. But for the header issue, the responses are valid in traces. So, the issue is in the formatting, just before sending the data. I will review the code.

**Comment by avachette** [comment]
Thanks for your detailed explanation.

One mystery then is that header corruption occurs but it's not the calls which are talking about `Hash Sum mismatch`.

But maybe the two issues relies in the formatting part?

**Comment by capflam** [comment]
It is my guess too. Sometimes this happens on headers part and it is immediately visible. On the payload, because it is binary, the only way to observe the corruption is to compare the checksum. At least, this match the observation. So I try to found the issue for the header case because it should be easier to spot.

**Comment by capflam** [comment]
I have a good news and a bad news ... I'm unable to find anything by reading the code for now. It is the bad news. But I'm able to reproduce the issue inside a container. That's a good news ! Now it will be far easier to found the issue.

**Comment by avachette** [comment]
We make progress that's the only thing to keep in mind.

Thanks for investing time on the issue we raised with @awlx 

Let me know if you need more information on my end or trying a patch when you have strong lead on the issue!

**Comment by capflam** [comment]
I finally found and fixed the issue. I will backport the fix very soon. Many thanks for you help !

**Comment by awlx** [comment]
Awesome work as always @capflam. 🚀

**Comment by capflam** [comment]
The fix was backported. I guess new releases will be emitted next week. I'm closing. Thanks !
