### ISSUE TITLE
Issue with checks after 2.0.6

### ISSUE THREAD

**Issue by mildis** [haproxy/haproxy#278]
Since 2.0.6, checks fail and set the server in `DOWN` status.
Removing the checks from the server line allows traffic to flow correctly.

## Output of `haproxy -vv` and `uname -a`

```
Linux haproxy-1 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux

HA-Proxy version 2.0.6-1~bpo9+1 2019/09/14 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.0.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.0k  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.0k  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.22 2016-07-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

## What's the configuration?

```
global
        log /dev/log        local0 info
        log /dev/log        local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # Default ciphers to use on SSL-enabled listening sockets.
        # For more information, see ciphers(1SSL). This list is from:
        #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
        ssl-default-bind-ciphers EECDH+AES:+AES128:+AES256:+SHAHE-RSA-AES256-SHAHE-RSA-AES128-SHA
        ssl-default-bind-options no-sslv3
        tune.ssl.default-dh-param 2048

defaults
        log        global
        mode        http
        option        httplog
        option        dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

        option forwardfor       except 127.0.0.1/8
        option                  redispatch
        option http-keep-alive
        no option http-use-htx

frontend ssl
    bind ${HAPROXY_VRRP}:443 ssl crt tad-2019-chain.crt
    bind ${HAPROXY_IPV4}:443 ssl crt tad-2019-chain.crt
    bind ${HAPROXY_IPV6}:443 ssl crt tad-2019-chain.crt

#    capture request  header Host len 50
#    capture response header Location len 50
#    capture request header User-Agent len 50

    http-request set-header X-Forwarded-Proto https
    http-request set-header X-Forwarded-Port 443
    http-request set-header X-Forwarded-Host %[ssl_fc_sni]

    http-response set-header Strict-Transport-Security max-age=31536000;\ includeSubDomains

    acl secured_cookie res.hdr(Set-Cookie),lower -m sub secure
    rspirep ^(Set-Cookie:.*) \1;\ Secure unless secured_cookie

    acl host-tools        hdr(host) tools.example.com

    acl to-etap                path_beg /etap

    use_backend bck-etap if host-tools to-etap

backend bck-etap
    server etap 192.168.1.69:8080 check
```

## Steps to reproduce the behavior

1. upgrade from 2.0.5 to 2.0.6 under Debian 9.
2. servers with checks are failing
3. must remove checks for servers to be considered `UP` and accessible

## Actual behavior
Server is place in status `DOWN`.
hatop shows `L4TOUT`
From the logs 
```
Sep 14 13:57:35 haproxy-1 haproxy[9978]: Server bck-etap/etap is DOWN, reason: Layer4 timeout, check duration: 2001ms. 0 active and 0 backup servers left. 0 sessions active, 0 dequeued, 0 remaining in queue.
Sep 14 13:57:35 haproxy-1 haproxy[9976]: [WARNING] 256/135735 (9978) : Server bck-etap/etap is DOWN, reason: Layer4 timeout, check duration: 2001ms. 0 active and 0 backup servers left. 0 sessions active, 0 dequeued, 0 remaining in queue.
Sep 14 13:57:35 haproxy-1 haproxy[9978]: Server bck-etap/etap is DOWN, reason: Layer4 timeout, check duration: 2001ms. 0 active and 0 backup servers left. 0 sessions active, 0 dequeued, 0 remaining in queue.
Sep 14 13:57:35 haproxy-1 haproxy[9978]: backend bck-etap has no server available!
Sep 14 13:57:35 haproxy-1 haproxy[9978]: backend bck-etap has no server available!
Sep 14 13:57:35 haproxy-1 haproxy[9976]: [ALERT] 256/135735 (9978) : backend 'bck-etap' has no server available!


Sep 14 13:58:16 haproxy-1 haproxy[9978]: 172.17.10.1:51523 [14/Sep/2019:13:58:16.024] ssl~ bck-etap/<NOSRV> 0/-1/-1/-1/0 503 213 - - SC-- 16/15/0/0/0 0/0 "GET /etap/ HTTP/1.1"
```

## Expected behavior

Checks should behave like under 2.0.5.

## Do you have any idea what may have caused this?
From git bisect :
```
ab160a47acde9dc9c341b328c8716a721a389ab4 is the first bad commit
commit ab160a47acde9dc9c341b328c8716a721a389ab4
Author: Willy Tarreau <w@1wt.eu>
Date:   Thu Sep 5 17:38:40 2019 +0200

    BUG/MINOR: checks: do not uselessly poll for reads before the connection is up
    
    It's pointless to start to perform a recv() call on a connection that is
    not yet established. The only purpose used to be to subscribe but that
    causes many extra syscalls when we know we can do it later.
    
    This patch only attempts a read if the connection is established or if
    there is no write planed, since we want to be certain to be called. And
    in wake_srv_chk() we continue to attempt to read if the reader was not
    subscribed, so as to perform the first read attempt. In case a first
    result is provided, __event_srv_chk_r() will not do anything anyway so
    this is totally harmless in this case.
    
    This fix requires that commit "BUG/MINOR: checks: make __event_chk_srv_r()
    report success before closing" is applied before, otherwise it will break
    some checks (notably SSL) by doing them again after the connection is shut
    down. This completes the fixes on the checks described in issue #253 by
    roughly cutting the number of syscalls in half. It must be backported to
    2.0.
    
    (cherry picked from commit c5940392255e5a5a7eb0d27be62e155f1aec26c6)
    Signed-off-by: Christopher Faulet <cfaulet@haproxy.com>

:040000 040000 4cd93f8ab452b7092e56620c4a9f7672a3f9cd85 cc618d82eea0b8e421274410c61dc579a68cf7ce M        src
```

Bisect script used (with checks enabled in the configuration file)
```
#!/bin/bash

ISBAD=1

make -s -j4 TARGET=linux-glibc USE_ZLIB=1 USE_PCRE=1 USE_OPENSSL=1  USE_WURFL=1 WURFL_INC=contrib/wurfl WURFL_LIB=contrib/wurfl USE_DEVICEATLAS=1 DEVICEATLAS_SRC=contrib/deviceatlas USE_NS=

./haproxy -f ./haproxy.cfg > /tmp/haplog 2>&1 &
HAPID=$!

sleep 10 

if [ $(grep -c DOWN /tmp/haplog) -eq 0 ]; then
	ISBAD=0
fi

kill ${HAPID}

exit ${ISBAD}
```

## Do you have an idea how to solve the issue?
Absolutely not.

**Comment by waja** [comment]
Having the same issue since 2.0.6 with the following config:

```
global
	log 127.0.0.1	local0
	log 127.0.0.1	daemon notice
	maxconn 6000
	stats	socket	/var/run/haproxy-admin.sock mode 700 level admin
	stats	socket	/var/run/haproxy.sock mode 777 level user
	user	haproxy
	group	haproxy
	daemon
	nbproc 1
	nbthread 12
	cpu-map auto:1/1-12 0-11
	spread-checks 10
	tune.ssl.default-dh-param 2048
	ssl-default-bind-options no-tls-tickets ssl-min-ver TLSv1.0

defaults
	mode	http
	log	global
	option	httplog
	option	tcplog
	option	dontlog-normal
	option	dontlognull
	option	contstats
	option	splice-auto

backend backend
balance roundrobin
#option httpchk HEAD /index.php HTTP/1.1\r\nHost:\ www.test.org\r\n
  option forwardfor except 127.0.0.1
  option abortonclose
  option httpclose
  option forceclose
  option http-server-close
  option redispatch

server webserver1 10.10.66.1:80 weight 150 check inter 10000 rise 1 fall 3 minconn 96 maxconn 300
```

In my logfile:
```
Server backend/webserver1 is DOWN, reason: Layer4 timeout, check duration: 10000ms. 0 active and 1 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
```

Other backends (using `httpchk`) are working as expected.

**Comment by lukastribus** [comment]
To confirm the bisect, please revert the bisected commit on top of 2.0.6 by applying to following patch:

https://pastebin.com/raw/bSKFDmj5

**Comment by mildis** [comment]
@lukastribus No more issue after ab160a47acde9dc9c341b328c8716a721a389ab4 is rollbacked

**Comment by nbari** [comment]
having same issue using the [FreeBSD port version  2.0.6](https://www.freshports.org/net/haproxy)

Just in case to revert to `2.0.5`:

    pkg remove haproxy

Then change to `/var/cache/pkg` (in the hope old package still there) and then:

    pkg add haproxy-2.0.5.txz

**UPDATE**: fixed port with version [2.0.6_1](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240627)

**Comment by deepika-maj** [comment]
having same issue on Ubuntu 18.04 and can't revert to 2.0.5

**Comment by kaizen1** [comment]
Having same issue with 2.0.6 on Ubuntu 18.04. Option httpchk worked in 1.8.8. 
I had to remove http-check expect rstring and go with a tcp-check. Then it worked. But not a great workaround. I also turned off htx on the frontend and backend, but that did not help.

For some reason 2.0.6 does not evaluate the regex correctly.


The

**Comment by fraenki** [comment]
>To confirm the bisect, please revert the bisected commit on top of 2.0.6 by applying to following patch:

I can confirm that applying the patch fixed the issue for me. On HAProxy 2.0.6 three backends were completely dead due to failed checks, now they are all up again. :+1:

**Comment by wtarreau** [comment]
On Tue, Sep 17, 2019 at 03:12:17PM -0700, Frank Wall wrote:
> >To confirm the bisect, please revert the bisected commit on top of 2.0.6 by applying to following patch:
> 
> I can confirm that applying the patch fixed the issue for me. On HAProxy
> 2.0.6 three backends were completely dead due to failed checks, now they are
> all up again. :+1: 

Thank you for testing. I'd be all for reverting the patch in the short
term, but the risk of reintroducing the issue by accident while fixing
another check is quite high. Instead I'd like to get a chance to find
a way to fix it. That's why I'd rather not revert it yet.

Willy

**Comment by josephapg** [comment]
> 
> 
> having same issue on Ubuntu 18.04 and can't revert to 2.0.5

@deepika-maj,
If you're using vbernat's ppa, then you can revert to 2.0.5 by following this instruction:
1. `curl -O https://launchpadlibrarian.net/437628444/haproxy_2.0.5-1ppa1~bionic_amd64.deb`<br>(I obtained the file from [vbernat's HAProxy build log](https://launchpad.net/~vbernat/+archive/ubuntu/haproxy-2.0/+build/17428091).
2. `sudo apt install -f ./haproxy_2.0.5-1ppa1~bionic_amd64.deb`
3. Type `Y` when this question appear: `Do you want to continue? [Y/n]`
4. Restart HAProxy

**Comment by josephapg** [comment]
> 
> 
> having same issue on Ubuntu 18.04 and can't revert to 2.0.5

@deepika-maj
If you're using vbernat's ppa, then you can revert to 2.0.5 by following this instruction:
1. `curl -O https://launchpadlibrarian.net/437628444/haproxy_2.0.5-1ppa1~bionic_amd64.deb`<br>(I obtained the file from [vbernat's HAProxy build log](https://launchpad.net/~vbernat/+archive/ubuntu/haproxy-2.0/+build/17428091)).
2. `sudo apt install -f ./haproxy_2.0.5-1ppa1~bionic_amd64.deb`
3. Type `Y` when this question appear: `Do you want to continue? [Y/n]`
4. Restart HAProxy

**Comment by jeroenvermeulen** [comment]
@deepika-maj 
Vincent Bernat has applied [the patch](https://launchpadlibrarian.net/443099949/haproxy_2.0.6-2ppa1~bionic_source.changes) and updated [the package](https://launchpad.net/~vbernat/+archive/ubuntu/haproxy-2.0/+packages).
Now you can just do

    apt-get upgrade
    apt-get install haproxy

You should then have:

    # haproxy -v
    HA-Proxy version 2.0.6-2ppa1~bionic 2019/09/18 - https://haproxy.org/

Mind the `-2` after `2.0.6`

**Comment by lukastribus** [comment]
> Thank you for testing. I'd be all for reverting the patch in the short term, but the risk of reintroducing the issue by accident while fixing another check is quite high. Instead I'd like to get a chance to find a way to fix it. That's why I'd rather not revert it yet. Willy

Absolutely. I only suggested a local revert to confirm the bisect and to allow testing 2.0.6 in #277.

Maintainers including the revert in the package will have to rollback once we actually fix this; but of course for now it works around the problem, which is important.

**Comment by jeroenvermeulen** [comment]
@vincentbernat Thanks for taking care

**Comment by kornaz** [comment]
As a workaround, you can add `option tcp-check` or `option httpchk` in your listener/backend - checks will work fine if check type is explicitly set. I tcpdump'ed both cases (with and without check type set) and I noticed that if the check type is not set, haproxy sends SYN, gets the SYN,ACK and then just sends RST (without ACK!) and marks the server as DOWN. If the check type is set, haproxy sends RST,ACK once it gets SYN,ACK and marks the server correctly as UP.

**Comment by gzalo** [comment]
As another workaround, you can add
`		option httpchk HEAD / HTTP/1.0`
or	
`		option httpchk OPTIONS / HTTP/1.0`
and they seem to work fine

**Comment by wtarreau** [comment]
@kornaz this observation is extremely useful. We're still having different code paths for "option tcp-check" and no option and I suspect that we fail to properly report the success when the option is missing then. I'm currently trying to reproduce. Thank you!

**Comment by wtarreau** [comment]
Now confirmed, with @waja 's config, and I also confirm @kornaz 's observation. Now I have what I need to try to figure what is happening. Thank you guys!

**Comment by wtarreau** [comment]
Some progress on this: I suspect it's affected by the FD cache because in 2.1 it doesn't happen with the same commit, it only affects 2.0 and earlier. So actually we could be facing one of the corner cases where the check results depends on the scheduling. Still digging.

**Comment by wtarreau** [comment]
OK guys I found it. It's really a pain resulting from the very old construct of this code. To make a long story short, the rx code didn't expect to be called with incomplete connections and didn't wait for the end before leaving a verdict. So basically it works most often on the loopback but that's all. It only affected the default checks. It doesn't affect 2.1 in a visible way though I'm pretty sure that certain conditions can triggerr it. I've now fixed it and backported the fix to latest 2.0. Please simply apply commit 0f0393f to your local tree if 
you don't want to rebuild with latest git.

I'm leaving the issue open a little bit in case someone wants to add something or report some feedback but i'll be closed quickly.

Thanks to all who provided extremely valuable information!

**Comment by mildis** [comment]
@wtarreau commit `489bbd3` on 2.0 is ok for me

**Comment by wtarreau** [comment]
@mildis great, thank you for confirming! Since you were the one opening the issue, I'm now closing it! We're still dealing with a few other issues but I think we're not far from issuing 2.0.7 to fix this regression now.
