### ISSUE TITLE
Wrong chroot makes stopping HAProxy worker unexpectedly

### ISSUE THREAD

**Issue by alexandret-ik** [haproxy/haproxy#2784]
### Detailed Description of the Problem

HAProxy is crashing when the chroot is not correct.

### Expected Behavior

HAProxy should not died unexpectedly but stops correctly.

Ideally, I think that configuration checks should warn it as well. (haproxy -c)

### Steps to Reproduce the Behavior

1. Add a chroot directive with a non existing directory
2. Start HAProxy and see it crashing
3. Modify the chroot directive to make it pointing to an existing directory
4. Start HAProxy and see it working

### Do you have any idea what may have caused this?

chroot directive pointing to a non existing directory.

### Do you have an idea how to solve the issue?

Checking that the directory in the chroot directive is existing before to start haproxy workers. 

### What is your configuration?

```haproxy
For the sake of confidentiality, I crafted a dummy configuration file which looks like mine and making crash haproxy.


global
    log /dev/log daemon
    log-tag haproxy
    chroot /dummydir
    stats socket /run/haproxy/haproxy.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    uid "$USER_ID"
    gid "$GROUP_ID"
    daemon
    maxconn 30000

defaults
    log global
    mode http
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000
    timeout http-request 5s
    retries 3
    retry-on conn-failure
    option redispatch
    log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %ID"

frontend stats
    bind 192.168.1.1:9000
    # Enable Prometheus Exporter
    http-request use-service prometheus-exporter if { path /metrics }
    stats enable
    stats uri /stats
    stats refresh 30s
    stats admin if TRUE

frontend health_check
    bind 192.168.1.1:8081
    mode http
    timeout client 5s
    monitor-uri /
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.6-c2c0090 2024/11/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.6.html
Running on: Linux 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_PTHREAD_EMULATION=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX +PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with OpenSSL version : OpenSSL 3.0.14 4 Jun 2024
Running on OpenSSL version : OpenSSL 3.0.14 4 Jun 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
[NOTICE]   (1) : New worker (8) forked
[NOTICE]   (1) : Loading success.
[NOTICE]   (8) : haproxy version is 3.0.6-c2c0090
[NOTICE]   (8) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (8) : [haproxy.main()] Cannot chroot(/dummydir).
HAProxy version 3.0.6-c2c0090 2024/11/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.6.html
Running on: Linux 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64
[NOTICE]   (1) : haproxy version is 3.0.6-c2c0090
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[WARNING]  (1) : Current worker (8) exited with code 1 (Exit)
[WARNING]  (1) : A worker process unexpectedly died and this can only be explained by a bug in haproxy or its dependencies.
Please check that you are running an up to date and maintained version of haproxy and open a bug report.
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING]  (1) : All workers exited. Exiting... (1)
```

### Additional Information

We are using the official haproxy docker image. (haproxytech/haproxy-debian:3.0.6)

I know that it is not critical at all as we have an ALERT in the logs but I made this bug report just because the output was asking me to open a bug report. ;)

**Comment by einval22** [comment]
Hi Alexandret ! 

Thanks for reporting this ! I'm reproduced same output and looking on it. 

Just to precise this output below is produced in case, when worker is exiting due to error, as chroot folder does not exist, so  there is no crash, worker process just existed here with error code (1) [here](http://git.haproxy.org/?p=haproxy-3.0.git;a=blob;f=src/haproxy.c;h=80fd0e846a4b49d23624037ccf749849c0b4d378;hb=HEAD#l3896):


[NOTICE]   (1) : haproxy version is 3.0.6-c2c0090
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[WARNING]  (1) : Current worker (8) exited with code 1 (Exit)
[WARNING]  (1) : A worker process unexpectedly died and this can only be explained by a bug in haproxy or its dependencies.
Please check that you are running an up to date and maintained version of haproxy and open a bug report.
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING]  (1) : All workers exited. Exiting... (1)

"All workers exited. Exiting... (1)" => all other workers if exist will be terminated in this case with SIGTERM.

It seems, that we have to stop early  before forking the worker,  as we also check early in the code ([here](http://git.haproxy.org/?p=haproxy-3.0.git;a=blob;f=src/haproxy.c;h=80fd0e846a4b49d23624037ccf749849c0b4d378;hb=HEAD#l3632)), if we can chroot. But we don't, and this is suspicious.

And yes, we report nothing if launched with -c in this case, which might be also improved.
$ ./haproxy -c -f env4.cfg
$ echo $?
0

**Comment by einval22** [comment]
I've rechecked how chroot logic is applied. There is no error here.  

The problem, is that we report that haproxy can't chroot  in the late initialization stage, when the process tries to perform the chroot() command. It fails, in case of master-worker it 's already forked worker who fails, and then it exits with error code 1.  
In master-worker mode, in 3.0 version, master process performs some clean up, up  on worker's failure. So, we see at the end  this long error message from master:

```
WARNING]  (1) : A worker process unexpectedly died and this can only be explained by a bug in haproxy or its dependencies.
Please check that you are running an up to date and maintained version of haproxy and open a bug report.
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING]  (1) : All workers exited. Exiting... (1)
```

In 3.1 dev versions, master-worker architecture was  changed and the error message  is not confusing, when worker during the start can't apply its config  and exits.  So, I advise to try the latest 3.1-dev version.

```
[NOTICE]   (350223) : Initializing new worker (350225)
[NOTICE]   (350225) : haproxy version is 3.1-dev13-a919d4-72
[NOTICE]   (350225) : path to executable is ./haproxy
[ALERT]    (350225) : [./haproxy.main()] Cannot chroot(/root/tmp).
[NOTICE]   (350223) : haproxy version is 3.1-dev13-a919d4-72
[NOTICE]   (350223) : path to executable is ./haproxy
[WARNING]  (350223) : Failed to load worker!
```

We could check the validity of chroot directory at the configuration parsing stage with stat(), but we can't reported it, when haproxy is started  with '-c' option. There were some cases in the past, when people started `haproxy -c -f ...` in some restricted environments, where they  haven't had enough rights to create all necessary directories and constantly failed `haproxy -c -f ...`  has blocked their validation procedure.

But it's handy to spot chroot-related errors as early as possible without binding process to sockets.
So, in the next dev version it will be possible to start haproxy with `-dD -dW`  and if there will be some warnings, process will exit with an error.  For this case with chroot dir,  `-dD -dW` may be an equivalent of  `haproxy -c -f ...`  mode.

Here are some examples:

```
$ ./haproxy -f env4.cfg -dD -dW -W -S /tmp/xxx
[NOTICE]   (350479) : Initializing new worker (350481)
[NOTICE]   (350481) : haproxy version is 3.1-dev13-a919d4-72
[NOTICE]   (350481) : path to executable is ./haproxy
[DIAG]     (350481) : config : parsing [env4.cfg:15] : 'chroot': '/root/tmp': Permission denied (process is need to be started with root priviledges to be able to chroot).
[ALERT]    (350481) : Some warnings were found and 'zero-warning' is set. Aborting.
[NOTICE]   (350479) : haproxy version is 3.1-dev13-a919d4-72
[NOTICE]   (350479) : path to executable is ./haproxy
[WARNING]  (350479) : Failed to load worker!
$ echo $?
1
```

```
$ ./haproxy -f env4.cfg -dD -dW -W -S /tmp/xxx
[NOTICE]   (350549) : Initializing new worker (350551)
[NOTICE]   (350551) : haproxy version is 3.1-dev13-a919d4-72
[NOTICE]   (350551) : path to executable is ./haproxy
[DIAG]     (350551) : config : parsing [env4.cfg:16]: 'chroot': '/etc/ch' is not a directory.
[ALERT]    (350551) : Some warnings were found and 'zero-warning
[NOTICE]   (350549) : haproxy version is 3.1-dev13-a919d4-72
[NOTICE]   (350549) : path to executable is ./haproxy
[WARNING]  (350549) : Failed to load worker!
$ echo $?
1
```

Kind regards

**Comment by alexandret-ik** [comment]
I will not have the time to test the dev version but for sure, the `-dD` and `-dW` will be useful for this kind of case

Thank you very much for your time and I think that we can close this case now.
