### ISSUE TITLE
broken download link on website

### ISSUE THREAD

**Issue by qeepcologne** [haproxy/haproxy#2800]
### Detailed Description of the Problem

https://www.haproxy.org/download/3.1/src/devel/haproxy-3.1.0.tar.gz
=>
https://www.haproxy.org/download/3.1/src/haproxy-3.1.0.tar.gz

### Expected Behavior

working download link

### Steps to Reproduce the Behavior

visit https://www.haproxy.org/
click on table [latest version][3.1]

### What is your configuration?

```haproxy
not relevant
```

### Output of `haproxy -vv`

```plain
not relevant
```

**Comment by wtarreau** [comment]
Now fixed, thanks a lot! I think I have released 3.1 using the development script instead of the other one :-/
