### ISSUE TITLE
Regression on accept-invalid-http-response in 3.1.0

### ISSUE THREAD

**Issue by zt4** [haproxy/haproxy#2806]
### Detailed Description of the Problem

On version 3.0.6, I am using this option to support a backend that includes spaces in the response header names, which is invalid. This allows haproxy to see the server as "UP" and work.

`option accept-invalid-http-response`

After the upgrade from 3.0.6 to 3.1.0, that server is no longer seen as "UP". In looking at the logs, I get the following warning when starting/reloading haproxy.
`
'accept-invalid-http-response' ignored because backend 'xxxx' has no frontend capability.`

I tried option 'accept-invalid-http-request' as well, and it writes the same error, as expected, as it isn't a frontend.

### Expected Behavior

It worked in 3.0.6 and the option should work in a backend, which it is.

### Steps to Reproduce the Behavior

Include option accept-invalid-http-response in a backend that sends invalid http headers (a space in the name).

### What is your configuration?

```haproxy
backend yyyy
mode http

option httpchk HEAD /

option accept-invalid-http-response

http-response del-header invalidxxx -m beg

server zzzz 1.1.1.1:80 check
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.1.0-2~bpo12+1 2024/12/01 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-3.1.0.html
Running on: Linux 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64
Build options :
  TARGET  = linux-glibc
  CC      = x86_64-linux-gnu-gcc
  CFLAGS  = -O2 -g -fwrapv -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_OT=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL +OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.15 3 Sep 2024
Running on OpenSSL version : OpenSSL 3.0.15 3 Sep 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG
       spop : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [  OT] opentracing
        [SPOE] spoe
        [TRACE] trace
```

**Comment by git001** [comment]
With 3.1 are the config checks more strict, which means that a keywords which are not allowed in backend will now raise this warnings. I suggest to take a look into the [[ANNOUNCE] haproxy-3.1.0](https://www.mail-archive.com/haproxy@formilux.org/msg45435.html)

Anyhow you should switch to [accept-unsafe-violations-in-http-request](http://docs.haproxy.org/3.1/configuration.html#4.2-option%20accept-unsafe-violations-in-http-request) as the [accept-invalid-http-response](http://docs.haproxy.org/3.1/configuration.html#4.2-option%20accept-invalid-http-response) be become deprecated.

As the GH Issues are for bugs please contact the [ML](haproxy@formilux.org) for configuration issues.

**Comment by zt4** [comment]
Thanks, I switched to

`option accept-unsafe-violations-in-http-request`

and it works as-before.

However if the old option is still valid (although deprecated), it should still work and not say that it is not in a frontend, shouldn't it? It only is supposed to work in a listen/backend in version 3.0, so shouldn't it still work in 3.1, although deprecated?

**Comment by capflam** [comment]
Indeed, there is an issue in the parsing of these options. I will fix it. Thanks
