### ISSUE TITLE
HAProxy configuration issue with DNS replacement leading to 401 Unauthorized error from Azure IoT Hub

### ISSUE THREAD

**Issue by sharmilamuthukrishnan** [haproxy/haproxy#2809]
### Detailed Description of the Problem

I 'm using HAProxy to forward requests to Azure IoT Hub, but I'm encountering an issue where the incoming request's DNS is being replaced, leading to a 401 Unauthorized error with the IoT Hub. The error response includes the iothu-errorcode as IoTHubNotFound. I am able to ping and do nslookup from the server successfully, only with haproxy I am  getting error 

### Expected Behavior

HAProxy should forward the request correctly to the IoT Hub with the proper host header and IoT Hub should authenticate the request successfully without returning the IoTHubNotFound error.

### Steps to Reproduce the Behavior

When made a request using https protocol from the postman got the 401 unauthorized error and iothub-errorcode as IoTHubNotFound

### What is your configuration?

```haproxy
frontend iothub_frontend
  bind *:443
  mode tcp
  default_backend iothub_backend
backend iothub_backend
  mode tcp
  server iothub <<iothub-name>>.azure-devices.net:443
  http-request set-header Host <<iothub-name>>.azure-devices.net
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.5-1ubuntu3.2 2024/12/02 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.5.html
Running on: Linux 6.8.0-1017-azure #20-Ubuntu SMP Tue Oct 22 03:43:13 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/haproxy-c5klSH/haproxy-2.8.5=/usr/src/haproxy-2.8.5-1ubuntu3.2 -Wdate-time -D_FORTIFY_SOURCE=3 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=1).
Built with OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
Running on OpenSSL version : OpenSSL 3.0.13 30 Jan 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by git001** [comment]
any chance to update to the latest 2.8 release or to 3.0?

**Comment by einval22** [comment]
Hi sharmilamuthukrishnan,

Thanks for your report !

Your backend and frontend should be in http mode, as you do in your backend `http-request set-header`

Normally, with  you actual configuration you should see this warning, when haproxy starts:

[NOTICE]   (10413) : haproxy version is 2.8.5
[NOTICE]   (10413) : path to executable is ./haproxy
[WARNING]  (10413) : config : 'http-request' rules ignored for backend 'iothub_backend' as they require HTTP mode.

**Comment by sharmilamuthukrishnan** [comment]
Hi @vkssv ,
Thank you for the reply.
I am trying to create a reverse proxy for the Azure IoT Hub using the HA proxy. Azure IoT Hub allows the client to communicate using following protocols:
- MQTT
- MQTT over WebSockets (443)
- Advanced Message Queuing Protocol (AMQP)
- AMQP over WebSockets (443)
- HTTPS (443)
And http mode will not be suitable for all above protocols. So, created the config with tcp mode.
Please let me know whether HAProxy supports this?

**Comment by einval22** [comment]
Yes it supports.

I would suggest to have a dedicated couples frontend + backend for each group of protocols like below:

```
defaults
        mode http
        ...

# websockets traffic + https
frontend websocket_and_https_traffic
        bind :443
        ...

        default_backend web_bck

backend web_bck
        server srv1 azure-devices.net:443
        server srv2 ...
        ...

# TCP "tunnels" to forward MQTT and AMPQ
frontend mqtt_frt
        mode tcp
        bind *:1883
        default_backend mqtt_bck

backend mqtt_bck
        mode tcp
        ...
        server mqtt_hub server_FQDN:1883

frontend ampq_frt
        mode tcp
        bind *:5671
        default_backend ampq_bck

backend ampq_bck
        mode tcp
        ...
        server ampq_hub server_FQDN:5672
```

If there are different server names, which serve HTTPS and websockets traffic within the Azure IoT Hub farm, one may also suggest to add a dedicated frontend+backend for pure HTTPS requests and a dedicated frontend+backend for the servers, which run websocket apps.   This will give more "cleaner" traffic statistics, which could be obtained via stats socket.

Here are more detailed explanations and config examples:

https://www.haproxy.com/blog/websockets-load-balancing-with-haproxy
https://www.haproxy.com/documentation/haproxy-configuration-tutorials/load-balancing/websocket/

https://www.haproxy.com/blog/layer-4-and-layer-7-proxy-mode
https://www.haproxy.com/blog/layer-4-load-balancing-tunnel-mode

And you also can find many more examples and some advises about the configuration at the Discours channel here:
https://discourse.haproxy.org/t/welcome-to-discourse-haproxy-org/8

**Comment by sharmilamuthukrishnan** [comment]
Thank you so much for the support. Its working now..
