### ISSUE TITLE
Connection Establishment Issue with Concurrent Clients

### ISSUE THREAD

**Issue by Jazkiel** [haproxy/haproxy#2823]
### Detailed Description of the Problem

Hello,

I am trying to connect haproxy QUIC docker image with 5 quic-go clinets all at once. But the server just keeps logging

AddressSanitizer:DEADLYSIGNAL

and does not serve any client requests. Any help on this would be appreciated.

### Expected Behavior

It should be able to serve all requests

### Steps to Reproduce the Behavior

Follow this repo https://github.com/JorisHerbots/vegvisir to use it for HAS with haproxy docker image.

### What is your configuration?

```haproxy
I am using an ubuntu 22.04 machine with 64 cores.
```

### Output of `haproxy -vv`

```plain
NA
```

**Comment by a-denoyelle** [comment]
What images of haproxy did you use ? I do not know vegvisir, but at first glance it seems based on quic-interop, which would explain 'AddressSanitizer:DEADLYSIGNAL' trace which reveals that haproxy is compiled with ASAN which should be limited to testing purpose.

You should use the following image https://hub.docker.com/r/haproxytech/haproxy-alpine-quic or an equivalent.

**Comment by Jazkiel** [comment]
I see, I made use of this image: https://github.com/haproxytech/haproxy-qns

**Comment by a-denoyelle** [comment]
This image is only reserved for haproxy QUIC interop purpose. It has no need outside of this particular test suite. Switching to the proposed image should give you better results. I'm closing this issue.
