### ISSUE TITLE
Allow to get the X509 certificate chain of the peer

### ISSUE THREAD

**Issue by pboguslawski** [haproxy/haproxy#297]
Hello,

Please consider fetching all intermediate CA certs sent by TLS client 

https://www.openssl.org/docs/man1.1.1/man3/SSL_get_peer_cert_chain.html

to separate variable similar to ssl_c_der (which hold only peers certificate without intermediates). 

Without intermediate CA certs one cannot do extra client certificate validations i.e. using custom LUA+OCSP checks which require access to intermediates also (managing local intermediate CA repository may be not practical in case of frequently changed intermediates).

Regards,
Paweł

**Comment by wlallemand** [comment]
@pboguslawski does that patch meet your expectations? It wasn't merge since I don't remember any discussion around it. It could be merged for 2.2 though.

**Comment by pboguslawski** [comment]
> does that patch meet your expectations? 

We use older haproxy 1.8 from Debian for devel and this mod cannot be applied easily to this version so we didn't test it.

However allowing one to extract whole client cert chain in LUA after verification seems to be sufficient to do extra checks like OCSP without managing all intermediates locally.

Thank you!

Regards,
Paweł

**Comment by wlallemand** [comment]
I'm closing this as it was implemented in commit a598b50.
