### ISSUE TITLE
Add Fast CGI as proto for servers

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#3]
## Output of `haproxy -vv` and `uname -a`

```
Future version
```

## Which functionality do you think we should add?

I would like to have the possibility to use php-fpm or any other fast-cgi appserver directly as backend servers.

The mailing list discussion started at haproxy 1.9.2 announcement

https://www.mail-archive.com/haproxy@formilux.org/msg32461.html

The Idea is like this.

```
haproxy -> *.php           => php-fpm
        -> *.static-files  => webserver, cache
```
## What are you trying to do?

I want to reduce the hops from the app to the client.
Currently is the only possible solution this flow.

```
Client -> haproxy -> webserver -> fast-cgi app ( e. g. php-fpm)
```

My whish is like this

```
Client -> haproxy -> fast-cgi app ( e. g. php-fpm)
```

**Comment by 1ma** [comment]
Would it be feasible to prototype FastCGI support as a Lua module?

**Comment by git001** [comment]
to be honest it would be much better to have it native in HAProxy. With the new muxer should it be much better to implement a new proxy but I'm not as deep in the code to be able to add it.

**Comment by haproxy-mirror** [comment]
Something tells me that we should soon see some news on this front ;-)

**Comment by git001** [comment]
cool with commit 63bbf284a131de362ad5b60d64ff3b1eff830553 and the follow up commits looks like that that feature are now part of haproxy. great thanks to @capflam and the haproxy Team. :tada:

**Comment by capflam** [comment]
Thanks @git001 to have updated this old issue :) 

Indeed, I've pushed the support of the FCGI on the server side. It is part of HAProxy 2.1 and it won't be backported to 2.0. Feel free to report any problem or any though about its design. If there are some things not really convenient in its configuration or if you experience strange behaviors with a specific FCGI application, it may be adapted. The current implementation is a bit theoretical. I'm glad to close this issue now !
