### ISSUE TITLE
could not forward ipv6 (range port)

### ISSUE THREAD

**Issue by wpzzz** [haproxy/haproxy#307]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.7-1ppa1~xenial 2019/09/28 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g-fips  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.21 2016-01-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace


Linux YgeCloud-190920-ZWO5 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

## What's the configuration?

```
frontend ss-in
bind *:10000-50000
default_backend ss-out

backend ss-out
server server1  2001:470:c:f56::2 maxconn 20480
```

## Steps to reproduce the behavior

1. run haproxy
2. 
3. 

## Actual behavior

 haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/lib/systemd/system/haproxy.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2019-09-30 00:21:19 EDT; 9s ago
     Docs: man:haproxy(1)
           file:/usr/share/doc/haproxy/configuration.txt.gz
  Process: 1410 ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS (code=exited, status=0/SUCCESS)
  Process: 1476 ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=1/FAILURE)
 Main PID: 1410 (code=exited, status=0/SUCCESS)

Sep 30 00:21:19 YgeCloud-190920-ZWO5 systemd[1]: Failed to start HAProxy Load Balancer.
Sep 30 00:21:19 YgeCloud-190920-ZWO5 systemd[1]: haproxy.service: Unit entered failed state.
Sep 30 00:21:19 YgeCloud-190920-ZWO5 systemd[1]: haproxy.service: Failed with result 'exit-code'.
Sep 30 00:21:19 YgeCloud-190920-ZWO5 systemd[1]: haproxy.service: Service hold-off time over, scheduling restart.
Sep 30 00:21:19 YgeCloud-190920-ZWO5 systemd[1]: Stopped HAProxy Load Balancer.
Sep 30 00:21:19 YgeCloud-190920-ZWO5 systemd[1]: haproxy.service: Start request repeated too quickly.
Sep 30 00:21:19 YgeCloud-190920-ZWO5 systemd[1]: Failed to start HAProxy Load Balancer.

## Do you have any idea what may have caused this?

 if  forward a ipv6 single port ,working fine,like this

 frontend ss-in
bind *:25684
default_backend ss-out

backend ss-out
server server1  2001:470:c:f56::2:25684  maxconn 20480

 if  forward  ipv4 range port ,working fine,like this

 frontend ss-in
bind *:10000-50000
default_backend ss-out

backend ss-out
server server1  8.8.8.8  maxconn 20480

but  ipv6 range port fail

**Comment by capflam** [comment]
It is not a problem to forward a range port or a single port with IPv6. It is a parsing problem. The address parser will search the last colon to split the ip and the port. Of course with IPv6,  things get complicated. Here are rules to follow:

> IPv6 addresses can be declared with or without square brackets. When using square brackets for  IPv6 addresses, the port separator (colon) is optional. if not using square brackets, and in order to avoid any ambiguity with IPv6 addresses, the last colon ':' is mandatory even when no port is specified.

So you must write 
```
  server server1  [2001:470:c:f56::2] maxconn 20480
```
or
``` 
  server server1  2001:470:c:f56::2: maxconn 20480
```

**Comment by capflam** [comment]
I'm closing this issue now and marking it as "Works as designed". Reopen it if I missed something.
