### ISSUE TITLE
Add CASPer (cache-aware server-push)

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#31]
## Output of `haproxy -vv` and `uname -a`

```
Future Version
```

## What should haproxy do differently? Which functionality do you think we should add?

It would be nice to have a similar feature as h2o for CASPer (cache-aware server-push).

Description:
* https://h2o.examp1e.net/configure/http2_directives.html#http2-casper

Source:
* https://github.com/h2o/h2o/blob/master/lib/http2/casper.c
* https://github.com/h2o/h2o/blob/master/include/h2o/http2_casper.h

**Comment by TimWolla** [comment]
see: https://news.ycombinator.com/item?id=25064855 "Blink: Intent to Remove: HTTP/2 and gQUIC server push"

**Comment by git001** [comment]
Let's close this issue because it looks like it's not necessary anymore.
