### ISSUE TITLE
Exchange TCP Load Balance NOSRV issue

### ISSUE THREAD

**Issue by CChristensen-SBT** [haproxy/haproxy#311]
#71  Output of `haproxy -vv` and `uname -a`
haproxy -vv
``` HA-Proxy version 2.0.7-1ppa1~bionic 2019/09/28 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-TXZjzi/haproxy-2.0.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

```
Uname -a
```Linux haproxy1.sbt.local 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

## What's the configuration?

```
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
        nbproc 1
        nbthread 8
        cpu-map auto:1/1-8 0-7

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermedi$
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-EC$
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_PO$
        ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

        #Variables for servers
        setenv exchange1 10.x.x.x
        setenv exchange2 10.x.x.x
        setenv timeplus 10.x.x.x
        setenv internalweb 10.x.x.x

defaults
        log     global
        option  httplog
        option  dontlognull
        option tcp-check
#        timeout connect 5000
#        timeout client  50000
#        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http
        option dontlognull # Do not log connections with no requests
        option redispatch # Try another server in case of connection failure
        option contstats # Enable continuous traffic statistics updates
        retries 3 # Try to connect up to 3 times in case of failure
        timeout connect s # 5 seconds max to connect or to stay in queue
        timeout http-keep-alive 1s # 1 second max for the client to post next request
        timeout http-request 15s # 15 seconds max for the client to send a request
        timeout queue 30s # 30 seconds max queued on load balancer
        timeout tarpit 1m # tarpit hold tim
        backlog 10000 # Size of SYN backlog queue
        balance roundrobin #alctl: load balancing algorithm
        mode tcp #alctl: protocol analyser
        option tcplog #alctl: log format
        log global #alctl: log activation
        timeout client 1000s #alctl: client inactivity timeout
        timeout server 1000s #alctl: server inactivity timeout
        default-server inter 3s rise 2 fall 3 #alctl: default check parameters

#Stats Page
frontend stats
        bind *:8888
        stats enable
        mode http
        stats refresh 15s
        stats show-node
#        stats auth admin:xxxxxx
#        stats hide-version
        stats uri  /
#Exchange

frontend ft_exchange_HTTP
        bind 10.x.x.x:80 name exchange80
        maxconn 10000
        default_backend bk_exchange_HTTP

backend bk_exchange_HTTP
        server mail4 $exchange1:80 check
        server mail5 $exchange2:80 check

frontend ft_exchange_SSL
#       http-response set-header X-Frame-Options SAMEORIGIN
#       http-response set-header X-Content-Type-Options nosniff
        bind 10.x.x.x:443 name exchange443
        maxconn 10000 #alctl: connection max (depends on capacity)
        default_backend bk_exchange_SSL #alctl: default farm to use

backend bk_exchange_SSL
        balance source
        server mail4 $exchange1:443 check
        server mail5 $exchange2:443 check

frontend ft_exchange_SMTP

        bind 10.x.x.x:25 name smtp
        maxconn 10000
        acl anon_allowed src 10.x.x.x 10.x.x.x 10.x.x.x
        use_backend bk_exchange_SMTP_anon if anon_allowed
        default_backend bk_exchange_SMTP

backend bk_exchange_SMTP
        option smtpchk
        server mail4 $exchange1:25 check
        server mail5 $exchange2:25 check

backend bk_exchange_SMTP_anon
        option smtpchk
        server mail4 $exchange1:5525 check
        server mail5 $exchange2:5525 check

frontend ft_exchange_SMTP_Secure
        bind 10.x.x.x:587 name smtpssl
        maxconn 10000
        default_backend bk_exchange_SMTP_Secure

backend bk_exchange_SMTP_Secure
        server mail4 $exchange1:587 check
        server mail5 $exchange2:587 check

frontend ft_exchange_IMAP
        bind 10.x.x.x:143 name imap
        maxconn 10000
        default_backend bk_exchange_IMAP

backend bk_exchange_IMAP
        tcp-check expect string "* OK The Microsoft Exchange IMAP4 service is ready."
        server mail4 $exchange1:143 check
        server mail5 $exchange2:143 check

frontend ft_exchange_IMAP_Secure
        bind 10.x.x.x:993 name imapssl
        maxconn 10000
        default_backend bk_exchange_IMAP_Secure

backend bk_exchange_IMAP_Secure
        option tcp-check
#        tcp-check expect string "* OK The Microsoft Exchange IMAP4 service is ready."
        server mail4 $exchange1:993 check
        server mail5 $exchange2:993 check

defaults
        mode http

#Internal Web
frontend HTTPS_Websites
        bind 10.y.y.y:443 ssl crt /etc/ssl/REDACTED/wild-REDACTED-com.pem
        bind 10.y.y.y:80
        redirect scheme https code 301 if !{ ssl_fc }   # redirect 80 -> 443
        acl internalweb hdr(host) -i internalweb.DOMAIN.COM
        acl timeplus hdr(host) -i timeclock.DOMAIN.com
        acl timeplus hdr(host) -i timeplus.DOMAIN.com
        use_backend internalweb_be if internalweb
        use_backend timeplus_be if timeplus
        default_backend internalweb_be

backend internalweb_be
        option httpchk
        server server1 $internalweb:80 check

backend timeplus_be
        option httpchk
        option httpchk GET /app/webclock/#/EmployeeLogOn
        server server1 $timeplus:81 check

```

## Steps to reproduce the behavior

1. Configure HAProxy 2.0.x to act as a L4 load balancer in front of an exchange 2016 environment
2. Change DNS records for autodiscover.domain to point to the proxy instead of directly to an exchange server
3. Wait for several hundred users to connect to the proxy

(Tested 2.0.6 and 2.0.7)
## Actual behavior

--Users experience disconnects, unreliable access (timeouts, connection resets, etc) and slow performance. 
--Haproxy.log gets flooded with entries that look like the following
`Oct  2 15:20:47 haproxy1 haproxy[12836]: 10.x.x.123:56542 [02/Oct/2019:15:20:47.749] ft_exchange_SSL bk_exchange_SSL/<NOSRV> -1/-1/0 0 SC 8/7/6/0/0 0/0
Oct  2 15:20:55 haproxy1 haproxy[12836]: 10.x.x.249:62325 [02/Oct/2019:15:20:55.797] ft_exchange_SSL bk_exchange_SSL/<NOSRV> -1/-1/0 0 SC 8/7/6/0/0 0/0
`
--CPU usage on the haproxy box spikes to 100% utilization

Issue was not present during testing or with a small load of users. It begins only when deployed to production and hundreds of exchange users (Outlook & Mobile Clients mostly) connect through the proxy. I couldn't find a hard line in the sand, but it seemed to begin happening with around 450 current sessions on the exchange SSL backend (The vast majority of exchange traffic goes through the 443 front/backend). I never saw more than about 450-500 current sessions on the stats page on version 2.0

## Expected behavior

Users should not receive timeouts & disconnects. CPU load should stay low.

## Do you have any idea what may have caused this?

At first I thought it was some sort of resource exhaustion issue, but 400-500 L4 connections is a tiny load compared to what other users are running through haProxy. Additionally, allocating more CPU did not fix the issue. (Tested with 2 ,4, & 8 vCPUs)

## Do you have an idea how to solve the issue?
 Uninstall 2.0.x and install 1.9.x
To test I cloned the Virtual machine and gave the clone a different IP address. I utilized the exact same configuration (other than changing Bind IP addresses to the new address). I uninstalled 2.0 (apt remove haproxy) and installed 1.9. After letting the DNS propagate to direct users at the 1.9 haproxy, the issue appears to be completely gone. I currently have between 800-1000 current sessions on the exchange_SSL backend. CPU load on the box is 1-2% and not a single NOSRV error in the log. With 2.0 I never saw more than 400-500 current sessions on the SSL backend. At that point it would fall on it's face, the log would begin to be filled with the NOSRV CR errors and users began complaining.

**Comment by bedis** [comment]
Hi,

You might have a too short global maxconn. Default is set to 2000.
To check this, maybe you can issue a "show stat" on the stats socket and report here the result.

Note that Microsoft recommends 10 connections per users. In practice, I used to see each outlook opening from 3 to 5 connections, which matches your 400 or 500 users to the default global maxconn limit

**Comment by bedis** [comment]
I removed te bug flag for now, cause it's not yet proven this is a bug :)

**Comment by CChristensen-SBT** [comment]
So the global maxconn on 2.0 is set to 2000. Is that a change from 1.9? If so what is the default maxconn on 1.9?

**Comment by wtarreau** [comment]
If it is not set in your config, it is automatically calculated from
your process' "ulimit -n" setting. In 1.9 and older by default it was
limited to 1024 FDs, resulting in ~500 connections max.

**Comment by CChristensen-SBT** [comment]
@bedis One other thing I should clarify. When looking at the stats page, it would start to fall apart at about 400-500 *current sessions*.
@wtarreau 
You can see my config above, there is no entry for maxconn in the global section. What you're saying about 1.9 defaulting to ~500 connections is completely opposite from my experience.
On 2.0 it fell apart at ~500 connections, however as soon as I rolled back to 1.9 with the **exact** same config. The problem went away entirely and now it's running stable with around 800-1100 sessions on the Exchange_SSL backend.

**Comment by wtarreau** [comment]
You're getting connection failures. Do you know if you're seeing a moderately high request rate ? I'm interested in figuring if it could be related to a very low socket limit that is hit once we add the few idle connections. On your default-server line you could add "pool-max-conn 0" to see if that changes anything.

Also when you start haproxy it would be useful to emit "show info" on the CLI to see the relevant settings of both versions.

Oh I think I understand. You're starting it as root with your ulimit limited to 1024. That allows haproxy to override your ulimit and increase it to accomodate the maxconn setting, while in 2.0 you're remaining limited to 1024 (fd limit) roughly divided by two to get the maxconn value. Could you please check "ulimit -n" before starting it ? Or if you're running it under systemd, you have to set the limit in the systemd service for this. I think it's done with LimitNOFILE as explained here, though not being a systemd user I don't know for sure : https://medium.com/@pawilon/tuning-your-linux-kernel-and-haproxy-instance-for-high-loads-1a2105ea553e

**Comment by lukastribus** [comment]
I suggest you look at the stats page, it shows both the actual ulimit as well as the global maxconn used.

**Comment by wtarreau** [comment]
Good idea!

**Comment by CChristensen-SBT** [comment]
My request rate is not high. Looking at the stats page right now ~5 and that the max session rate (since the most recent reload which was earlier this morning) is 43 (on the SSL backend which has 99% of the traffic)

It is running on ubuntu 18.04 which means that I am running Systemd. I am using the pre-built packages from Vincent's PPA.

This is my stats page on 1.9. Unfortunately I don't have a good way of testing the issue on 2.0 now as The only way to reproduce the issue was to push it to my production environment and get the connections up and then it was service impacting. 
![image](https://user-images.githubusercontent.com/56084618/66335910-38dcb580-e8f9-11e9-9cc2-59ae5b8d0697.png)

**Comment by lukastribus** [comment]
You just have to start 2.0 in staging and take a look at the stats page, to understand the ulimit and maxconn values it uses in your environment.

**Comment by alexanderharm** [comment]
I recently had similar problems and was able to fix them by adding

```
tcp-request inspect-delay 5s
tcp-request content accept if { req_ssl_hello_type 1 }
```

to the tcp front ends.

**Comment by wtarreau** [comment]
Here it must be different as there is no TCP frontend doing SSL analysis. However the version is now old and given the bug has not evolved, I think we should possibly close it if there's no more activity.
