### ISSUE TITLE
Improve documentation of configuration items values "types" (especially for strings)

### ISSUE THREAD

**Issue by mjf** [haproxy/haproxy#313]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.7 2019/09/27 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -m64 -march=x86-64 -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DTCP_USER_TIMEOUT=18 -DMAX_SESS_STKCTR=12
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.4
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

## What should haproxy do differently? Which functionality do you think we should add?

Be consistent in configuration string behaviour, at least. Sometimes quoting become part of a configuration item value!
Documentation does not suggest much. People who tend to be strict on quoting then
end up in sort of more or less serious troubles and it also parses wrong in the `dataplaneapi` JSON output of services etc. For instance, consider this configuration snippet:

```
global
    user  'haproxy'
    group 'haproxy'
```

This is just fine and works as expected (or, at least, it seems to work). But consider this snipet:

```
userlist 'api'
    user 'user' insecure-password 'password'
```

This time you end up with user literaly called `'user'` and password `'password'` which is
obviously not the thing you intended to achieve. There are more issues with the quoting
that I consider quite inconsistent. For instant, when I write `0600` for file mode in the
the configuration somewhere, does it really mean that it parses as octal numerical expression?

```
... mode 0600 ...
```

What happens now?

```
... mode '0600' ...
```

It seems to work either! So, it's a quotable string, in fact, right? Or is it not? It's highly confusing... but it actually works as expected with the hard quoting applied...

I would like to, at least, see hints where quoting is available, parsed or even interpreted (double-quoted). I suggest to distinquish the variants (or "types") of configuration item values in the documentation, mainly

- strong quoted strings
- weak quoted strings
- quoted strings (both variants possible at once)
- literals (no quoting expected)
- octal / decimal / heximal / ... numbers

and maybe more (IPv4 address, IPv6, special names with special rules such as backend names etc...)

So that the the section on `userlist`s in the documentation may, for example, look like this:

```
userlist <literal listname>
    user <literal username> [password|insecure-password <literal password>]
                ...
```

instead of just

```
userlist <listname>
```

and nobody would try to put quotes there.

There is also a benefit from documenting the configuration types - you will see where you
can use for instance environment variables at glance if you knew that this or that configuration
item value is weak quotable, right?

Thanks for your attention.

**Comment by capflam** [comment]
You probably made a mistake on the way the user and password parameters are evaluated in the userlist section. Quotes are not part of the parameters, except if you explicitly escape it. See section 2 of the configuration manual. It explains how parameters are parsed in the configuration file. Quotes and escape sequences are only useful during the very first stage of the configuration parsing, when lines are split into arguments.

If you really have a parameter parsed in a way that contradicts the section 2 of the configuration manual, it is a bug. If so, you may open an issue to report it.
