### ISSUE TITLE
Implement a "strict-mode" or "lazy-mode" http-request directive

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#317]
After a discussion with Christopher regarding how to deal with HTTP rewrite errors (headers, URI, ...), it appeared that being able to turn on/off a strict or lazy rewrite mode using an http-request directive would fit every purpose.

The main issue is that a non-negligible number of configurations do rely on the current "lazy" mode by which if a add-header rule fails, we don't care, and such configurations often have their rules sorted by order of importance (particularly cookies). So it would break some setups to enforce a strict mode that cannot be disabled. But with a directive, we could start processing in strict mode, then decide that past a certain point the rules are not important and disable the strict mode before the subsequent add-header/set-header rules. This allows us to turn on the strict mode by default, which is what most users expect.

We could for example have this in a response path:
```
 http-response add-header Strict-Transport-Security max-age=31536000
 http-response add-header Set-Cookie login_status=logged_in
 http-response strict-mode off   # from now on, silently ignore failed header additions.
 http-response set-header Server "my lovely server"
 http-response add-header Set-Cookie profile=gold
```

**Comment by capflam** [comment]
Implemented now in 2.2-dev
