### ISSUE TITLE
HAProxy 2.0.7 - websockets don't works

### ISSUE THREAD

**Issue by maniac1978** [haproxy/haproxy#323]
We using haproxy 1.5.18. And want to upgrade to version 2.0. I installed haproxy 2.0.7 on the new server. And I found a problem with websockets.
This is the configration of haproxy:

```
defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend www
        bind *:80

redirect scheme https if { hdr(Host) -i i.api.mydomain.com } !{ ssl_fc }

frontend https_frontend
        bind *:443 ssl crt /etc/haproxy/haproxysslapi.pem crt /etc/haproxy/haproxyssl.pem alpn http/1.1
        mode http

use_backend bk_mapp-app if { ssl_fc_sni i.api.mydomain.com }

backend bk_mapp-app

mode http
balance roundrobin
option forwardfor
option http-server-close
option forceclose
no option httpclose
        balance roundrobin
        server mapp-app1        192.168.200.66:80 maxconn 10000 weight 10 cookie mapp-app1 check
        server mapp-app2        192.168.200.67:80 maxconn 10000 weight 10 cookie mapp-app2 check
        server mapp-app3        192.168.200.68:80 maxconn 10000 weight 10 cookie mapp-app3 check
```
And this works fine on haproxy version 1.5.18. Here is the result of successfully getting the file via websockets:

`Oct 14 16:23:59 localhost haproxy[25864]: 10.20.216.202:58282 [14/Oct/2019:16:23:33.181] https_frontend~ bk_mapp-app/mapp-app3 157/0/1/6/26431 200 38781954 - - ---- 1/1/1/0/0 0/0 "POST /market/apk/62bd718e-3381-4f42-b614-fddf915f6c22/download HTTP/1.1"
`

And this is the result of working with the same configuration via haproxy 2.0.7:

`Oct 14 13:53:20 tank haproxy[18764]: 10.20.216.202:42288 [14/Oct/2019:13:52:27.521] https_frontend~ bk_mapp-app/mapp-app3 0/0/38/44/52757 200 739177 - - cD-- 2/2/1/0/0 0/0 "POST /market/apk/62bd718e-3381-4f42-b614-fddf915f6c22/download HTTP/1.1"
`

What is wrong?

Output haproxy -vv from both servers:

```
[root@NLB3 haproxy]# haproxy -vv
HA-Proxy version 1.5.18 2016/05/10
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 8192, maxpollevents = 200

Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.7
Compression algorithms supported : identity, deflate, gzip
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
Built with PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
```

```
root@tank:/home/maniac# haproxy -vv
HA-Proxy version 2.0.7-1ppa1~bionic 2019/09/28 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-TXZjzi/haproxy-2.0.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

**Comment by capflam** [comment]
Looking at your log lines, it seems you've hit the client timeout for the second one, and not for the first. So from the log point of view, everything seems to be ok. But the total number of bytes sent to the client is significantly different ( 38781954 vs. 739177). I don't know if it is the expected behavior of you application. From the client or the server point of view, Did you observe any freeze of the connection ?

We need more info to said if it is a bug from HAProxy or not. Could you try to disable the HTX mode adding `no option http-use-htx` in your default section ? And a network capture before and after HAProxy may help to diagnose problems. In addition, if it is reproducible, could you share the output of the cli commands `show sess all` and `show fd`  before the timeout ?

Note: if any, sent me these infos privately and be careful to remove all sensitive information.

**Comment by maniac1978** [comment]
Thanks for a response !
I emailed you the necessary files.

About server and application behavior.
It seems that neither understands what 's going on. The server does not react, the application endlessly shows “Downloading file”.

I may have mentioned "websockets" incorrectly.
I specified with the developers, they write on node.js and use the streams described here: https://nodejs.org/api/stream.html

About `no option http-use-htx`. 
The first time we tested haproxy 2.0.7, we had a problem downloading files from another application.
That problem was manifested as follows.
At haproxy 1.5.18, the download of the ~ 200Mb file took 5 minutes:
`Oct  4 11:14:13 localhost haproxy[11041]: 10.20.216.130:36160 [04/Oct/2019:11:09:11.284] https_frontend~ bk_fdev3/fdev2 42/0/2/104/302141 200 198792117 - - ---- 1279/1279/11/5/0 0/0 "GET /ecommerce/goods/offline/articuls?store=a6487039-4769-4897-b975-d100d3b911e5 HTTP/1.1"`

And on haproxy 2.0.7 it took 55 minutes:
`Oct 10 08:32:04 nlb5 haproxy[10891]: 10.20.216.130:47314 [10/Oct/2019:07:36:27.406] https_frontend~ bk_fdev3/fdev2 1/0/1/146/3336967 200 198727101 - - ---- 1794/1794/13/6/0 0/0 "GET /ecommerce/goods/offline/articuls?store=a6487039-4769-4897-b975-d100d3b911e5 HTTP/1.1"`

I added `no option http-use-htx` in default section in configuration of haproxy 2.0.7 and it took less than 4 minutes to download the file:
`Oct 11 06:45:31 nlb5 haproxy[25401]: 10.20.216.130:49812 [11/Oct/2019:06:41:43.918] https_frontend~ bk_fdev3/fdev2 0/0/1/77/227871 200 199603507 - - ---- 1691/1689/10/4/0 0/0 "GET /ecommerce/goods/offline/articuls?store=a6487039-4769-4897-b975-d100d3b911e5 HTTP/1.1"`

But with the current problem turning off HTX mode doesn't help, I've tried before.

**Comment by wtarreau** [comment]
I'm wondering how the following lines in h1_send() could affect the transfer:

	if (h1c->flags & H1C_F_OUT_FULL)
		flags |= CO_SFL_MSG_MORE;

It seems to me that this results in MSG_MORE being always set on tunnel transfers (and we have the same in mux_h2). In legacy mode we were using a much more complex rule taking into account the tunnel mode, dontwait and so on that are known at the stream level:

		if ((!(oc->flags & (CF_NEVER_WAIT|CF_SEND_DONTWAIT)) &&
		     ((oc->to_forward && oc->to_forward != CHN_INFINITE_FORWARD) ||
		      (oc->flags & CF_EXPECT_MORE))) ||
		    ((oc->flags & CF_ISRESP) &&
		     ((oc->flags & (CF_AUTO_CLOSE|CF_SHUTW_NOW)) == (CF_AUTO_CLOSE|CF_SHUTW_NOW))))
			send_flag |= CO_SFL_MSG_MORE;

Thus I suspect that tunnelled data are simply transferred at a rate of 16kB buffer every 200ms in the worst case if waiting for application level ACKs to come from the other side. The last test suggests 59kB/s on average which roughly is 12kB/200ms so we're not far form this.

I suspect we'll finally have to pass that CS_FL_SND_MORE flag to the muxes to address this.

**Comment by capflam** [comment]
Thanks Willy.  That explains the very slow throughput with the HTX.

BTW, @maniac1978, I took a look at the network capture you sent me. The client side is encrypted. So this part is unusable. But the server side is and  I found a problem with the response sent by your server. Both `Content-Length` and `Transfer-encoding` headers are present and  there is a typo in the encoding: `chuncked` instead of `chunked`. Note also the payload is not chunked.

The parsing with the HTX mode is more strict than with the legacy HTTP mode. So here, in HTX, the `Content-Length` header is removed because there is a `Transfer-Encoding`. And because of  the typo on `chunked`, end of the payload is only reached when the server closes the connection (see RFC7230#3.3.3 for details). Because it never happens, we hit the server timeout. Note with the 2.0.7 and the legacy HTTP mode, you should observe the same behaviour. In 1.5, because some backports are missing, the `Content-Length` header is not removed and the payload is parsed using the specified size.

So, given the response received by HAProxy, it works as expected.

**Comment by capflam** [comment]
@wtarreau, I quickly reviewed this issue again this morning. I realized the request are done on a SSL frontend. So the flag `CO_SFL_MSG_MORE` is ignored both in the HTX mode and in the legacy HTTP mode. The only flag handled by the SSL layer is `CO_SFL_STREAMER`. This one is passed in the legacy HTTP mode but ignored in HTX. But it seems to be used only when the maximum SSL records size is tuned.

@maniac1978, Did you tune this parameter (`tune.ssl.maxrecord <number>` defined in your global section) ?

**Comment by maniac1978** [comment]
@capflam, No, I did not apply this setting in the configuration.

**Comment by maniac1978** [comment]
@capflam, Thank you, problem solved !
At first, the developers removed the `Transfer-Encoding` header, but this did not help.
They then deleted the `accept-ranges (bytes)` and `Connection (keep-alive)` headers. And everything worked.

**Comment by wtarreau** [comment]
Great, closing now.
