### ISSUE TITLE
Allow http2 over plain text connections to the backend

### ISSUE THREAD

**Issue by darix** [haproxy/haproxy#326]
nginx allows you to declare plain http listen statements as http2.

```
listen 127.0.0.1:85 http2;
```

you can use the following curl cmdline to talk to such a backend:

```
curl -vsS -o /dev/null --http2-prior-knowledge http://127.0.0.1:85/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 85 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56356ff28ed0)
> GET / HTTP/2
> Host: 127.0.0.1:85
> User-Agent: curl/7.60.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx/1.17.3
< date: Mon, 14 Oct 2019 16:40:30 GMT
< content-type: text/html
< content-length: 260
< last-modified: Mon, 06 Apr 2015 03:21:35 GMT
< etag: "5521fbbf-104"
< accept-ranges: bytes
< 
{ [260 bytes data]
* Connection #0 to host 127.0.0.1 left intact
```

Adding the usual ```h2``` to the server line doesnt work without ```ssl``` at the moment. but given nginx supports plain text http2 it would be nice to be able to use it with haproxy.

**Comment by daniel-corbett** [comment]
I believe that you are looking for `proto h2`

**Comment by wtarreau** [comment]
It already works, please have a look at the "proto" server directive. You
just need to add "proto h2" to force the protocol to be h2 (technically
speaking it forces to select the same mux as normally used when negociating
the "h2" ALPN).

**Comment by darix** [comment]
confirmed! :D

**Comment by darix** [comment]
how would a valid ```option httpchk``` line look in this case? would I just keep using the http/1.0 format and haproxy will convert it automatically? (to answer myself: using the http/1.0 format doesnt work)

**Comment by darix** [comment]
and where can I read up on the behavior I will see then? will one frontend h2 connection be mapped to 1 backend h2 connection? will you combine multiple frontend h1 connections to a single h2 connection to the backend host if they e.g. come from the same remote IP?

**Comment by wtarreau** [comment]
On Mon, Oct 14, 2019 at 11:35:03AM -0700, darix wrote:
> how would a valid ```option httpchk``` line look in this case? would I just
> keep using the http/1.0 format and haproxy will convert it automatically?

Checks currently cannot use muxes, which is why we want to rework them
to support HTX, hence being able to use H1/H2/FCGI/etc.

**Comment by wtarreau** [comment]
On Mon, Oct 14, 2019 at 11:42:34AM -0700, darix wrote:
> and where can I read up on the behavior I will see then? will one frontend h2
> connection be mapped to 1 backend h2 connection? will you combine multiple
> frontend h1 connections to a single h2 connection to the backend host if they
> e.g. come from the same remote IP?

Each side uses its own protocol version, thus you have :

   (h1,h2) ---> (h1,h2,fcgi)

It is possible to reuse idle backend connections depending on the
"http-reuse" directive. It defaults to "safe" which means for H1
that once it's certain the client may be able to retry in case of
a close race, connections my be reused, and for H2 that a connection
may be reused. Idle connections are attached to the client's session
in order to maximize the likelihood that the same connection is
reused by the same client (to improve server logs processing). If
anything makes the connection private (401/407) or if reuse id
disabled, then the connection will not be shared.

**Comment by darix** [comment]
Thank you for the explanation and keep up the good work! :)
Always fun to discover new things.
