### ISSUE TITLE
proto/connection.h: conn_(sock|xprt)_polling_changes: function mismatch documetation, possible bug

### ISSUE THREAD

**Issue by vpodobaev** [haproxy/haproxy#34]
In file include/proto/connection.h: Functions conn_sock_polling_changes and conn_sock_polling_changes:
In comments for these functions it is written:

> Additionally non-zero is also returned if an error was reported on the connection.

But the code is the following:

	f &= CO_FL_XPRT_WR_ENA | CO_FL_XPRT_RD_ENA | CO_FL_CURR_WR_ENA |
	     CO_FL_CURR_RD_ENA | CO_FL_ERROR;

	f = (f ^ (f << 1)) & (CO_FL_CURR_WR_ENA|CO_FL_CURR_RD_ENA);    /* test C ^ D */
	return f & (CO_FL_CURR_WR_ENA | CO_FL_CURR_RD_ENA | CO_FL_ERROR);

In the line with XOR (^) the CO_FL_ERROR is definitely cleared (only CO_FL_CURR_WR_ENA CO_FL_CURR_RD_ENA are allowed). So, the next statement (f & ...) will not be true if only one CO_FL_ERROR is set (without WR|RD_ENA). So, the functions mismatch the documentation. Is it ok? Maybe it's a bug?

**Comment by wtarreau** [comment]
Good observation. This got "damaged" in 1.5-dev22 by this commit :

    310987a03 MAJOR: connection: remove the CO_FL_WAIT_{RD,WR} flags

The test doesn't need to check for CO_FL_ERROR however, so in practice it could very wel do "return f;" and be done with it.

**Comment by capflam** [comment]
Old enough to be closed. These functions were removed in 2.2.
