### ISSUE TITLE
backend (ELB) IPs scale beyond DNS UDP payload size => TC flag kills backend

### ISSUE THREAD

**Issue by jfree-fs** [haproxy/haproxy#341]
### version/system :
```
# haproxy -vv
HA-Proxy version 1.8.19-1~bpo9+1 2019/02/12
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-1.8.19=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.0f  25 May 2017
Running on OpenSSL version : OpenSSL 1.1.0l  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE2 version : 10.22 2016-07-29
PCRE2 library supports JIT : yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace

# uname -a
Linux ip-10-36-212-54 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
```
### haproxy cfg:
```
global
	daemon
	cpu-map all 1	# 0-based
	log-send-hostname
	user	haproxy
	group	haproxy
	maxconn	65000
	stats socket /run/haproxy/stats.sock mode 600 level operator
	stats timeout 2m
	server-state-base /etc/haproxy/states
	server-state-file global

defaults
	mode	http
	option	redispatch
	option	allbackups
	option	dontlognull
	option	log-health-checks
	retries	3
	maxconn	65000
	timeout	client	300000
	timeout	server	300000
	timeout	connect	5000
	log-format	±{\"date\":\"%t\",\"lbtype\":\"dtm\",\"lbname\":\"%H\",\"cip\":\"%ci\",\"pid\":\"%pid\",\"name_f\":\"%f\",\"name_b\":\"%b\",\"name_s\":\"%s\",\"Tw\":\"%Tw\",\"Tc\":\"%Tc\",\"Tr\":\"%Tr\",\"Ta\":\"%Ta\",\"Td\":\"%Td\",\"Th\":\"%Th\",\"Ti\":\"%Ti\",\"Tq\":\"%Tq\",\"TR\":\"%TR\",\"Tt\":\"%Tt\",\"scode\":\"%ST\",\"bytes_c\":\"%U\",\"bytes_s\":\"%B\",\"termstat\":\"%ts\",\"con_act\":\"%ac\",\"con_frnt\":\"%fc\",\"con_back\":\"%bc\",\"con_srv\":\"%sc\",\"rtry\":\"%rc\",\"queue_s\":\"%sq\",\"queue_b\":\"%bq\",\"rqst\":\"%r\",\"cookies\":\"%CC\",\"Origin\":\"%[capture.req.hdr(0)]\",\"X-F-F\":\"%[capture.req.hdr(1)]\",\"X-F-Proto\":\"%[capture.req.hdr(2)]\",\"X-F-Port\":\"%[capture.req.hdr(3)]\",\"Host\":\"%[capture.req.hdr(4)]\",\"User-Agent\":\"%[capture.req.hdr(5)]\",\"Accept-Lang\":\"%[capture.req.hdr(6)]\",\"Accept\":\"%[capture.req.hdr(7)]\",\"Referer\":\"%[capture.req.hdr(8)]\",\"srv_ip\":\"%si\"}
	load-server-state-from-file global
	default-server init-addr last,libc,none

resolvers vpc_resolver
  nameserver ns1 10.7.7.2:53
  hold valid 60s

frontend ft
  bind	:10009
  log	127.0.0.1	len 2048	local2	debug info

  capture request header Origin             len 128
  capture request header X-Forwarded-For    len 64
  capture request header X-Forwarded-Proto  len 5
  capture request header X-Forwarded-Port   len 6
  capture request header Host               len 64
  capture request header User-Agent         len 96
  capture request header Accept-Language    len 64
  capture request header Accept             len 64
  capture request header Referer            len 96

 acl MATCH_ft path_reg -i ^/ft($|/)
 use_backend ft if MATCH_ft

backend ft
	log 127.0.0.1:514 local3 notice emerg
	balance roundrobin
	http-request set-header X-Orig-Base /ft
	acl missing_slash path_reg -i ^/ft$
	http-request redirect code 301 prefix / drop-query append-slash if missing_slash
	reqrep ^([^\ ]*)\ /ft/(.*) \1\ /\2

	server-template elbIPs 26 long_elb_name:80 resolvers vpc_resolver resolve-prefer ipv4
```

### Trigger :
1. Traffic causes ELB IPs to scale until TC (truncated) bit set in DNS response flags
    (# RRs too great to fit in one UDP response packet)

### Currrent Behavior:
src/dns.c::dns_validate_dns_response() then skips handling ANY of the response because DNS_RESP_TRUNCATED
 => TTLs of ALL endpoints in server-template expire, so  ALL endpoints get marked DOWN, e.g. :

   Server www26 is going DOWN for maintenance (unspecified DNS error)

and ALL subsequent requests get 503 (SC) => system is down.

### Expected behavior
Parse TC response to keep valid endpoints in the backend, while issuing a critical syslog entry.

### Notes:
Our haproxy cfg is auto-generated frequently, in part to track AWS ELB scaling events. 

As a stop-gap measure, we'll investigate using accepted_payload_size > the default 512 if/as we can.

But killing the whole backend because of a TC response was catastrophic to our service.

https://www.mail-archive.com/haproxy@formilux.org/msg35180.html

**Comment by wtarreau** [comment]
Let @bedis have a look at this. It could be as simple a fix as ignoring the TC flag, or it could be more complex for example if the info is missing from the packet for the server in question, in which case I don't see what could be done.

**Comment by lukastribus** [comment]
It is my understanding that the TC flag was set here, yes.

My proposal is that when the TC flag is set:
- we keep parsing as much from the response as possible instead of rejecting it entirely
- we log a critical error, indicating that the response has been truncated, and that payload_size tuning is probably necessary

**Comment by jfree-fs** [comment]
Sense of test in src/dns.c::dns_validate_dns_response()  seems opposite to comment preceding it ?
  ... dns_query->type != DNS_RTYPE_SRV ...
wants (per comment) to be
  ... dns_query->type == DNS_RTYPE_SRV ...
??

**Comment by bedis** [comment]
Weird, I thought I ignored the TC flag and keep on parsing.
I'll check tonight this part of the code.

@jfree-fs can you share privately with me a terraform code to generate the AWS minimum thing to trigger this issue?

**Comment by lukastribus** [comment]
I think that is the case for srv records, but not other records?

**Comment by jfree-fs** [comment]
We don't use terraform, but I'll look into working up a cfg if that makes it more workable for you.

The crux of this was a highly-scaled ELB name as \<fqdn\> (and IP count as \<num\>) argument(s) to server-template.  As the ELB scaled to 24+ IP addresses, the # of ELB IP addresses overwhelmed the capability of a DNS response UDP pkt to enumerate sans TC.

We're suspicious (case pending) as to why the ELB was scaled to such an extent, but that inquiry is an issue apart from haproxy's handling of it.

**Comment by bedis** [comment]
@jfree-fs if providing me a diagram with the different AWS component in place and their minimal config is better for you, let's do that. Then I'll do the terrafrom myself.

I now remember I tested many DNS servers and I observed different type of behavior with TC.
Some servers return no record with TC, some did return some records (and then you want to enable 'hold obsolete' in your config).

Saying that, you can use the 'accepted_payload_size' parameter to enable EDNS and announce to the server that HAProxy can accept payloads bigger that 512 bytes.
It's not enabled by default because I don't know if all servers support it, how to detect a server does not support it and what would be the mechanism to disable it on the fly.

**Comment by jfree-fs** [comment]
Thanks much for this insight.  We've kludged up a set of DNS that imitates this scenario, and found that AWS's DNS does in fact set TC, then enumerates no servers (sent .pcap to @bedis ).  We'll set accepted_payload_size (probably to 1472 - safest/biggest we feel comfortable with for now), and continue investigating with the provider why the ELB had scaled to so many entries (makes no sense).

**Comment by jfree-fs** [comment]
We found out from our provider that this happened when they were performing maintenance on their load balancers, which caused them to temporarily scale.

Just so happened they scaled to a number of IPs/LB_instances that would overrun haproxy's default 512-byte UDP DNS response accepted_payload_size, and the provider's DNS service set the TC in flags, but enumerated no 'A' records for the query.  I'd convinced myself the TC response enumerated what records it could fit, but tcpdump proved me stupid.

https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#accepted_payload_size
https://serverfault.com/questions/422158/what-is-the-in-the-wire-size-of-a-ethernet-frame-1518-or-1542
 - 1472 payload size for non-Jumbo ethernet UDP pkt
 - safe max value a bit tricky to ascertain in our case - ICMP not enabled 'twixt haproxy and DNS
