### ISSUE TITLE
Local Ubuntu Repository HAProxy public key

### ISSUE THREAD

**Issue by gbryant200** [haproxy/haproxy#344]
I'm using apt-mirror for a local repository for all my servers behind our firewall/proxy.

I've setup apt-mirror to download the `deb http://ppa.launchpad.net/vbernat/haproxy-2.0/ubuntu bionic main` repository.

When I add the repository to the servers inside our company in /etc/apt/sources.list.d/haproxy.list:
`deb ftp://mw-umirror/haproxy/ubuntu bionic main` and I try to apt update I get a warning that the public key isn't available; NO_PUBKEY 505D97A41C61B9CD

Is there a way to manually download this key to my local mirror so I can then add it to my servers inside our network?

Thanks

**Comment by lukastribus** [comment]
Probably something like:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 505D97A41C61B9CD`


However this is not the right place for this question. We are using github issues for haproxy bugs and features requests, while you need help with Ubuntu. Please consider using the Ubuntu support channels instead.
