### ISSUE TITLE
DNS resolution failure behaviour

### ISSUE THREAD

**Issue by hamshiva** [haproxy/haproxy#345]
## Output of `haproxy -vv` and `uname -a`

```
root@hostname:/etc/haproxy# haproxy -v
HA-Proxy version 1.8.22-1~bpo9+1 2019/10/26
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

root@hostname:/etc/haproxy# uname -a
Linux hostname 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
```

## What's the configuration?

```
resolvers test_resolvers
  nameserver dns1 192.168.1.1:53
  hold valid 1m
  hold nx 5s
  hold refused 5s
  hold obsolete 30m
  accepted_payload_size 8192

backend test_web_back
  balance roundrobin
  mode http
  option forwardfor
  option redispatch
  option abortonclose
  option http-server-close
  option tcp-smart-connect
  server-template web 200 _httpvip._tcp.localdomain resolvers test_resolvers check agent-check agent-port 9100
  timeout server 10s
```

## Steps to reproduce the behavior

1. Add a iptables rule to reject or drop DNS request from haproxy server on the DNS resolver or even stop the DNS daemon
2. Watch the backend servers status changes

## Actual behavior
The backend servers states change to maintenance after more or less 1 minute (hold valid timeout).

## Expected behavior
While the documentation state that a resolution is considered as invalid (NX, timeout, refused), when all the servers return an error, the backend servers states should remain unchanged until the obsolete timeout is reached or a valid DNS resolution occurs.

## Do you have any idea what may have caused this?
No

## Do you have an idea how to solve the issue?
No

Regards,

**Comment by bedis** [comment]
Hi Hamshiva,

This is the correct behavior. Timeout obsolete is enabled only when HAProxy does not receive a record for said server for this amount of time. (which implies that the DNS server is operating properly, of course).

This could happen when the number of DNS server returns only a subset of records compared to the real number of servers configured behind this resolution.

**Comment by wtarreau** [comment]
Thus to be clear, what's the correct knob to tune here before we can close this issue ? "hold valid" maybe ?

**Comment by bedis** [comment]
Well, I think the documentation is clear about "hold obsolete":

> As a DNS server may not answer all the IPs in one DNS request, haproxy keeps
> a cache of previous answers, an answer will be considered obsolete after
> <hold obsolete> seconds without the IP returned.

I think I understand what @hamshiva wants.
Basically, we keep a valid answer for 'hold valid' period and then we trigger a new DNS resolution after this period.
So we could enforce 'hold valid' to 1h to workaround this, but then HAProxy won't detect new changes too for this 1h period.
I think what @hamshiva wants is that we ignore any kind of errors for 1h (but we carry on triggering quite frequently DNS queries).

@hamshiva can you confirm my assumption is correct?
if yes, we'll discuss about possible workarounds, first of them would to have a reliable DNS server... Not really acceptable that DNS service is not reliable on your infra :p

**Comment by wtarreau** [comment]
I think this makes sense indeed. There is a difference between no information about error and information about no error. I tend to think one hold setting should make sure we can keep an old working value. We should probably have "hold stale" or something like this. But maybe it could be fused with one of the existing ones. The obsolete one is not far from this from the users' perspective ("no more info about this server").

**Comment by bedis** [comment]
You got me :)
I wanted to re-use 'hold obsolete' for such use case, but I am waiting for @hamshiva to confirm that we well spotted his issue.

**Comment by hamshiva** [comment]
Hi,

You are completely right about having reliable DNS servers. But shit always happens.
My point is that, if the DNS are for whatever reason unavailable then the last valid resolution should be used until the next valid resolution or a certain timeout is reached (hold obsolete as I understood the doc but it seems I am wrong).

Let me give you a simple example. One haproxy using DNS-SD for backend servers provisionning, resolution done locally via consul daemon, I would much prefer haproxy to keep last good resolution instead of removing all servers if the consul daemon was to hang/crash/be retarted at the wrong time/killed/whatever.

Even if you are using external reliable resolvers it could happen that this one is in an other subnet behind a FW and we all know that messing with FW rules is far too easy, thus you could temporarily loose DNS resolution and it should not "avoid" haproxy to fullfil his duty (which it does very well btw).

While I read the documentation https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.3.1 and 5.3.2 I understand that an invalid resolution should not be processed but instead should lead to using an other valid resolution or trigger a resolution retry. Is my understanding wrong ?

Regards,

**Comment by bedis** [comment]
I spent some time re-reading the doc, the code and some old commit messages and it seems we already have a "timeout resolve" which is supposed to trigger the resolution after this timeout.
It is clearly not used for now, so we have a bug here.

What will happen is that HAProxy will trigger a dns resolution after 'timeout resolve' and keep the resolution as valid for 'hold valid' period of time.
This means that even if timeout or NX are errors are encountered, they will be ignored for 'hold valid' period.

**Comment by hamshiva** [comment]
Sounds good to me :)

**Comment by bedis** [comment]
Hi @hamshiva 
I fixed the wrong behavior, so you can now retry and confirm this would work as expected.
Please close this issue once done.

**Comment by lukastribus** [comment]
This bug fix is in:

```
2.1: 2.1.0 (first release)
2.0: 2.0.9
1.9: 1.9.13
1.8: 1.8.23
```

**Comment by ishergin** [comment]
> What will happen is that HAProxy will trigger a dns resolution after 'timeout resolve' and keep the resolution as valid for 'hold valid' period of time.
> This means that even if timeout or NX are errors are encountered, they will be ignored for 'hold valid' period.
Hi!

I have to use short 'timeout resolve' (1s for example), because haproxy doesn't support DNS TTL.
But I want to have protection against DNS failure for several hours/days and is it impossible in the current configuration? 

I checked behavior with version 2.0.16-1ppa1~xenial and got 'DOWN for maintenance (DNS timeout status)' in few seconds in spite of settings 'hold valid 24h'

**Comment by ivasilyev-servicetitan-com** [comment]
> > What will happen is that HAProxy will trigger a dns resolution after 'timeout resolve' and keep the resolution as valid for 'hold valid' period of time.
> > This means that even if timeout or NX are errors are encountered, they will be ignored for 'hold valid' period.
> > Hi!
> 
> I have to use short 'timeout resolve' (1s for example), because haproxy doesn't support DNS TTL. But I want to have protection against DNS failure for several hours/days and is it impossible in the current configuration?
> 
> I checked behavior with version 2.0.16-1ppa1~xenial and got 'DOWN for maintenance (DNS timeout status)' in few seconds in spite of settings 'hold valid 24h'

@ishergin you need to use 'hold timeout 24h' if you want protection for `DNS timeout` response
