### ISSUE TITLE
src/dns.c: logically dead code found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#349]
```
1580                /* known query id means a resolution in prgress */
    assignment: Assigning: res = (struct dns_resolution *)((void *)eb - 60L).
1581                res = eb32_entry(eb, struct dns_resolution, qid);
    notnull: At condition res, the value of res cannot be NULL.
    dead_error_condition: The condition !res cannot be true.
1582                if (!res) {
    CID 1399778: Logically dead code (DEADCODE)dead_error_begin: Execution cannot reach this statement: ns->counters.outdated++;.
1583                        ns->counters.outdated++;
1584                        continue;
1585                }
```

**Comment by wtarreau** [comment]
Agreed, should be "if (!eb)". @bedis care to check this ? I suspect it can lead to bad behavior when getting late replies if QID is not found.

**Comment by bedis** [comment]
Yep, I saw this report but I was not sure how to address it. Now I know, I'll have a look at it.

**Comment by wdauchy** [comment]
I've sent a proposal here https://www.mail-archive.com/haproxy@formilux.org/msg35548.html

**Comment by chipitsine** [comment]
thank you @wdauchy 

```
   Your request for analysis of Haproxy has been completed successfully.
    The results are available at https://u2389337.ct.sendgrid.net/wf/click?upn=08onrYu34A-2BWcWUl-2F-2BfV0V05UPxvVjWch-2Bd2MGckcRZSimvEwL5B1ViGlrRm8Kbput-2FpqBXksiDyxbrfzJm20g-3D-3D_Xj92pbuVUtYzUgAvpgFpalDO5omG8Nmis06qm2RYPydv60-2Fba3tSCgI0P-2Fag5SAsfbqGpkrhd0WU0o6HaR3BLxiOC4PASvazr4EmaMPvuJLGbgcgE7wNe3R6of3esR1JAl3que576Ong1s2svmu5rBxM94N8lOGXzOoQI40yKKYUFH249aKApGTgUbkGY3pA5e4f0QY0LKq1VyEvZ5QUeoNC8IrIIyfVFilf36v3Cqk-3D

    Build ID: 283381

    Analysis Summary:
       New defects found: 0
       Defects eliminated: 1
```

**Comment by TimWolla** [comment]
I notice that this bug is tagged with versions to backport to. I believe CLEANUP patches are usually not backported and indeed I cannot find anything in 2.1. Should those version labels be removed and this issue closed?

**Comment by wtarreau** [comment]
In fact "BUILD" is often more appropriate for such fixes when they address a build warning, but I tend to do the same mistake very 50% of the time because these are not real changes. We occasionally backport them when they help distro maintainers get rid of warnings. If they're just made to shut up coverity, we don't need to backport them. I'm closing now.
