### ISSUE TITLE
bind-process does not work with threads

### ISSUE THREAD

**Issue by ehocdet** [haproxy/haproxy#36]
With this configuration: (haproxy 1.9.2 and  with fresh dev branch), 
bind-process with threads is accepted but do nothing: all threads is used for one frontend.
```
  nbthread 2

frontend one
   bind-process 1/1
   [...]
frontend two
   bind-process 1/2
   [...]
```

This configuration is also accepted without warning:
```
  nbthread 2

frontend one
   bind-process 1/45

```

expected:
. bind-process works with threads
or
. haproxy does not accept threads with bind-process  (warning/error)

**Comment by capflam** [comment]
Hi,

Indeed it is a bug. `bind-process` directive does not support threads. But an error must be triggered if any invalid character is detected. It is also true for `cpu-map` and `process` directives. For instance, following declaration passes:
```
bind *:80 ... process 1a
```

**Comment by wtarreau** [comment]
Funny, I also fixed it separately because I was fed up with "bind-process 1,3,5" silently ignoring "3,5"... Dropped my patch now.

**Comment by TimWolla** [comment]
@wtarreau Is there a reason this was not backported to 1.8?

The #40 issue is already backported to 1.8 and 1.9 and newer than this one.

**Comment by wtarreau** [comment]
On Sun, Feb 10, 2019 at 03:55:06PM -0800, Tim Düsterhus wrote:
> @wtarreau Is there a reason this was not backported to 1.8?

Simply lost during a cherry-pick --abort after I already merged it. Now merged again.

**Comment by TimWolla** [comment]
> Simply lost during a cherry-pick --abort after I already merged it. Now merged again.

Perfect. Fully backported then, closing.
