### ISSUE TITLE
Set the weights  without percentatge in haproxy-agent

### ISSUE THREAD

**Issue by mcortinas** [haproxy/haproxy#360]
Hello, 
I'm using haproxy-agent in order to set the weights for each server. Let me share the doc: 
- [haproxy doc](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-agent-check)
> n ASCII representation of a positive integer percentage, e.g. "75%".
  Values in this format will set the weight proportional to the initial
  weight of a server as configured when haproxy starts.

My real issue is I'm using ingress-haproxy and these ingress-controller set the initial value to 0
I opened an issue to ingress-hproxy in https://github.com/jcmoraisjr/haproxy-ingress/issues/442 
The main issue if the initial value is alweays 0 and haproxy-agent don't let us change the weight for my backend, this always will be 0.

¿Could you add some logic in haproxy-agent in order to send a static weight? Maybe I could send "weight: 255"?

**Comment by wtarreau** [comment]
Interesting, I was absolutely certain we had it and no, we do not. The
reason is that the weight was the first thing the agent would support
and it doesn't take any prefix so it remains quite strict on its format.
Temporarily you can simply remove the "&& strchr(cmd, '%')" in checks.c
and it will support this. But I'd rather do it by supporting a new
"weight:<value>[%]" format that is less ambiguous and will not change
weights to 1 when some older agents return "0"/"1" depending on OK/KO
for example. Please have a look 2 lines below how maxconn is handled
and do the same with the "ps" variable. I'm willing to take such a
patch if you do it. Just have a look at CONTRIBUTING to check a few
coding style and message formating rules and that's all.

**Comment by capflam** [comment]
Better late than never, this was implemented. An agent can now return `weight:<value>[%]` as suggested by Willy. An absolute value must be between 0 and 256. Thanks !
