### ISSUE TITLE
SPOA examples improvement

### ISSUE THREAD

**Issue by rikatz** [haproxy/haproxy#362]
## Output of `haproxy -vv` and `uname -a`

```
./haproxy -vv
HA-Proxy version 2.1-dev4-7031e3-19 2019/11/09 - https://haproxy.org/
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = 

Feature list : -EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE -NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE -THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -VSYSCALL -GETADDRINFO -OPENSSL -LUA -FUTEX -ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built without multi-threading support (USE_THREAD not set).

Available polling systems :
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 2 (2 usable), will use poll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS
            fcgi : mode=HTTP       side=BE        mux=FCGI

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
	[FCGI] fcgi-app

$ uname -a
Linux compiler01 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

## What should haproxy do differently? Which functionality do you think we should add?

Hi there,

First of all, thanks for the amazing work.

I've been trying to port the spoe-modsecurity to other "easier" language than C, to generate some improvements as Rules ignoring, logging improvements and so on.

The problem is that the Python and Lua examples only support setting values, but not getting them. So, in Python I get a lot of issues with the ``args`` parsing.

I was originally trying to use the Golang library (https://github.com/negasus/haproxy-spoe-go) but it panics when You use binary args.

I've figured out how to deal with binary fields and buffer lens, but I'm still not able to get them from the messages, as the Python and Lua examples doesn't have any function/method to retrieve them from the PyObject generated.

As I'm no C developer (sorry!!) I would like to check if someone is willing to implement methods to also retrieve the args passed from HAProxy to SPOA.

I might also try to hack/change into the Golang library, but would be great if Python and Lua also support this.

Thank you very much!

**Comment by rikatz** [comment]
@jcmoraisjr marking You here, so You can also follow this one.

**Comment by bedis** [comment]
Hi,
Can you try this library: https://github.com/criteo/haproxy-spoe-go ?

**Comment by rikatz** [comment]
Hi @bedis thanks for the answer :)

Negasus corrected his lib also, so as I started with his lib I'll follow it :) But thank you for the follow up, I'll also test the criteo lib to make some benchmarks and so on ! :)
