### ISSUE TITLE
Layer4 timeout when use check. without checking ,it works

### ISSUE THREAD

**Issue by AI-T** [haproxy/haproxy#363]
haproxy Server XXXXX is DOWN, reason: Layer4 timeout check duration: 10001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
haproxy服务器 启动失败

Here is my config #这是我的配置信息
backend node-backend
   balance roundrobin
   mode tcp
   server server-a 172.19.0.2:8080 check
   server server-b 172.19.0.3:8080 check

**Comment by bedis** [comment]
Can you do curl / telnet from the HAProxy machine to the <server ip>:<port> ?

**Comment by wtarreau** [comment]
Note: I'm closing this. This is neither a bug report nor a feature. If you require any help, please check on the mailing list or on the forum that were mentioned on the new issue page.

**Comment by AI-T** [comment]
> Can you do curl / telnet from the HAProxy machine to the : ?

yes. without check configure (server server-a 172.19.0.2:8080), it works.
