### ISSUE TITLE
Socket bind name as sample / log format option

### ISSUE THREAD

**Issue by mhofman** [haproxy/haproxy#37]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.14-52e4d43 2018/09/20
Copyright 2000-2018 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -fno-strict-overflow -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_ZLIB=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.0f  25 May 2017
Running on OpenSSL version : OpenSSL 1.1.0f  25 May 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace

Linux haproxy 3.10.102 #15284 SMP Thu Jun 21 00:42:18 CST 2018 x86_64 GNU/Linux
```

## What should haproxy do differently? Which functionality do you think we should add? 

I'd like to use the socket bind name in custom log formats.
Currently no log format options include socket information. The hard-coded error logs do however include the socket name if defined.

There is the `so_id` sample allowing to discriminate on binding socket, but that's an integer and not very readable in logs.
The only workaround I've found is to conditionally set a session variable based on the `so_id` sample value.

E.g.:
```
        tcp-request content set-var(sess.source_type) str(wan) if { so_id 1:2 }
        tcp-request content set-var(sess.source_type) str(lan) if { so_id 3:4 }
```
## What are you trying to do?

There should either be a way to access the socket bind name as a log format, and / or as a sample.

E.g. `%fsn` for `frontend_socket_name` in log formats or the `so_name` sample that could then be accessed as `%[so_name]`

```
    bind "${WAN_IP}:80" name wan
    bind "${WAN_IPv6}:80" name wan
    bind "${LAN_IP}:80" name lan
    bind "${LAN_IPv6}:80" name lan

    log-format "%ci:%cp [%t] %f/%fsn %b/%s %Tw/%Tc/%Tt %B %ts \
                %ac/%fc/%bc/%sc/%rc %sq/%bq"

    # or

    log-format "%ci:%cp [%t] %f/%[so_name] %b/%s %Tw/%Tc/%Tt %B %ts \
                %ac/%fc/%bc/%sc/%rc %sq/%bq"
```

[Discourse topic](https://discourse.haproxy.org/t/custom-log-socket-bind-name/3466) where I suggested the feature.

**Comment by jazzl0ver** [comment]
I need this log option too

**Comment by mhzgh** [comment]
Yes, would be great. Still the same with v2.2 and v2.3. Just recognized that it is not listed in the custom-format table in docs/configuration.txt - but is used to generate the error log messages. Would be a nice, uniform addition to have it configurable via custom format at some point in the future.

My frontends contain multiple bind directives and its useful to know the original target of the request. As a workaround I currently use custom-format fields for frontend_ip and frontend_port, so it can be matched that way.

**Comment by capflam** [comment]
`so_name` sample fetch is already available. It was introduced in the 2.2 and backported as far as the 2.0. This also means this issue may be closed.
