### ISSUE TITLE
HTTPS connection reuse with SNI

### ISSUE THREAD

**Issue by bobvanderlinden** [haproxy/haproxy#371]
Currently haproxy supports HTTP connection reuse using the `http-resuse` option:

https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-http-reuse

However, the documentation also states that:

>  - connections sent to a server with a TLS SNI extension are marked private
>    and are never shared;

This is indeed correct as outgoing connections toward backends that have the sni option defined are closed immediately after the HTTP request has been handled. This even happens when the sni option has a literal string defined, like:

```
sni str(literal.domain.com)
```

The result is that SSL handshaking needs to happen for each HTTP request.

Are there plans to add HTTP connection reuse for SNI-enabled backends?

**Comment by ehocdet** [comment]
In the general case, I think a session could be reused if authority (sni) is taken into consideration in the selection criteria.

**Comment by capflam** [comment]
Now implemented in the 2.3.
