### ISSUE TITLE
src/cli.c: out of bound write found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#377]
```
2542        }
2543
    22. incr: Incrementing arg. The value of arg is now 65.
    CID 1399794 (#1 of 1): Out-of-bounds write (OVERRUN)23. overrun-local: Overrunning array args of 65 8-byte elements at element index 65 (byte offset 527) using index ++arg (which evaluates to 65).
2544        args[++arg] = "\0";
2545
2546        bind_conf = bind_conf_alloc(mworker_proxy, "master-socket", 0, "", xprt_get(XPRT_RAW));
2547        if (!bind_conf)
2548                goto err;
```

**Comment by wlallemand** [comment]
Thanks, fixed.

**Comment by chipitsine** [comment]
@wlallemand , there are about 5 similar "out of bound read/write"
should we review them before 2.1 is out ?

**Comment by wlallemand** [comment]
You can post them, yes.

**Comment by TimWolla** [comment]
@wlallemand Small note: The version labels are used to track which branches a fix still needs to be backported to (i.e. which branches still are affected). So if a fix is commited and fully backported no more of them should remain.

**Comment by wlallemand** [comment]
Seems logical, thanks for the explanation.

**Comment by chipitsine** [comment]
tadam ))

https://github.com/haproxy/haproxy/issues/378
https://github.com/haproxy/haproxy/issues/379
