### ISSUE TITLE
dns_hostname_validation doesn't allow a hostname with exactly 63 characters

### ISSUE THREAD

**Issue by alisson276** [haproxy/haproxy#387]
## Steps to reproduce the behavior

1. Define a backend server hostname with 63 characters on backend, for example: 012345678901234567890123456789012345678901234567890123456789aaa.mydomain.com
2. Run `haproxy -c -f /etc/haproxy/haproxy.cfg`
3. You will see an error related to resolve hostname.

## Actual behavior

The HAProxy fail with `could not resolve address`

## Expected behavior

Must be allowed exactly 63 characters on labels, as defined by RFC1035.

## Do you have any idea what may have caused this?
This code just allow 62 characters:
```
if ((i >= DNS_MAX_LABEL_SIZE) && (d[i] != '.')) {
```

## Do you have an idea how to solve the issue?
To solve, just remove the equal from `i >= DNS_MAX_LABEL_SIZE`

**Comment by bedis** [comment]
Hi @alisson276 ,
Nice catch!
I'll fix this asap today.

**Comment by TimWolla** [comment]
>  I'll fix this asap today.

@bedis “Today” already passed since a few days and I see that there's no fix yet. So here's a reminder.

**Comment by wdauchy** [comment]
Oh this one looks very easy to fix, I will send a patch as Baptiste seems busy ;)

**Comment by TimWolla** [comment]
@wtarreau aecd5dcac2cd4cd87639596980c449f887b2ca26 did not contain any backport information, so I guess that's why it has not been backported at all (I'm not seeing it in 2.1). When labeling this issue I verified that HAProxy 1.6+ is affected.

Either the labels should be removed or that patch backported.

**Comment by wtarreau** [comment]
Ah good catch Tim. Now backported as far as 1.6, closing. Thanks!
