### ISSUE TITLE
PVS-Studio analysis results

### ISSUE THREAD

**Issue by pavel-pimenov** [haproxy/haproxy#39]
Total Warnings:  696
http://www.fly-server.ru/pvs-studio/haproxy/

**Comment by wtarreau** [comment]
Well, I looked at something like 30 of the first "High" ones, and they were all pure garbage. I have no intent to read them further nor to have a look at the supposedly "medium" ones. As most of the time, such automated tools seem to be having difficulties with the C language and can only report style issues.
