### ISSUE TITLE
Idle pool usage is ineffective with multithreaded instances

### ISSUE THREAD

**Issue by max2k1** [haproxy/haproxy#393]
Hi!

I want to talk about effectiveness of idle pool usage. For example, I have haproxy instance with http-proxy section that receives about 2K requests per second and have 48 backend servers. All requests have keep-alive option turned on and haproxy has `nbthread 32` option.

I've started collecting `connect` and `reuse` metrics from this section and made a simple calculation on reusage percentage: `reuse` / (`reuse` + `connect`). I've got only 48%. I tried to play with `http-reuse` parameter, `timeout http-keep-alive` – nothing helped much.

But then I've read the code of connect-function (https://github.com/haproxy/haproxy/blob/eea8fc737b37ca2d61cef6f35e29d990656c10d4/src/backend.c#L1217) and found out that idle pool is in practice thread-bounded. So I've changed my config to `nbthread 8` and got 95% of connection reusage.

So I wanna ask if there are any plans for improvements in cross-thread idle-pool usage? 

##  Output of `haproxy -vv` and `uname -a`
```
$ uname -r
4.19.86-20

$ haproxy -vv 
HA-Proxy version 2.1.0-1 2019/12/01 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.0.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=56).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.21 2016-01-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
```

**Comment by wtarreau** [comment]
Yes there are plans to do this. We even tried to address it for 2.1 and
were reasonably confident it could be done but in the end, after spending
a few months working 100% on bugs and not developing at all, in the time
left we figured that the task was way more difficult than initially expected.
At least we know that for H2 and FCGI it will take time. For H1 Olivier had
an idea how to proceed to transfer totally idle connections between threads,
but it remains technically difficult as we have to synchronize the operation
at the stream level and at the connection level (i.e. stealing another thread's
connection while the other thread is processing I/O on it is not a good idea).
But we still want to address this, as IMHO it's the last point making
multi-threading less interesting than single-threading, and in addition it
does have a considerable impact on FD count when dealing with large thread
numbers, even under moderate loads.

**Comment by max2k1** [comment]
Thank you for clarification, Willy!

I wish a process of connection reusage is better documented :)

And one more question since this ticket is a kind of "feature request". Just a kind of idea. What if haproxy doesn't need to steal another's threads connection and deal with its complexity? What if it could create'em by itself for each server in each thread? For example: one can ask haproxy for specific backend section to keep 5 idle connections for each server in each thread and set a GET-statement to use for it. So haproxy could execute these GET-requests periodically from each thread and keep connections in idle pool.

**Comment by wtarreau** [comment]
Regarding the doc, I too wish it's better documented.

Otherwise the behaviour you're explaining is the one we currently have.
But we also have to ensure to keep limits. Port it to 48 threads and you'll
see that you keep 240 connections on the server when you only need 5, so
that's how you end up with a reuse rate of only 2%. If you keep them long
enough (pool-purge-delay) and in large enough quantity (pool-max-conn),
you'll get your increased reuse rate, but the cost in terms of number of
FD and source ports will be high. Multiply this by 100 servers and that's
24000 FDs and source ports!

**Comment by lukastribus** [comment]
Please retry 2.2.

**Comment by wtarreau** [comment]
By the way, if you retry on 2.2, you can also try adding "pool-low-conn XXX" on your servers line, where XXX is approximately twice the number of threads. Experiments have shown that this optimizes *both* the reuse rate *and* the number of FDs. The idea is that we refrain from keeping an idle connection for a thread if the server already has enough. This causes the few extra connections to instantly be evenly distributed across all active threads and the takeover operations become quite rare, with a high reuse rate within threads. This will likely become a new default for 2.3.

**Comment by wtarreau** [comment]
closing now.
