### ISSUE TITLE
After haproxy "Soft reset" operation haproxy services shows inactive

### ISSUE THREAD

**Issue by kirangavali** [haproxy/haproxy#397]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.5.18 2016/05/10
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 8192, maxpollevents = 200

Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.7
Compression algorithms supported : identity, deflate, gzip
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
Built with PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

uname -a
-----------
Linux oss-gitlab-k.novalocal 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
#---------------------------------------------------------------------
# Example configuration for a possible web application.  See the
# full configuration options online.
#
#   http://haproxy.1wt.eu/download/1.4/doc/configuration.txt
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #
    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend  main *:5000
    acl url_static       path_beg       -i /static /images /javascript /stylesheets
    acl url_static       path_end       -i .jpg .gif .png .css .js

    use_backend static          if url_static
    default_backend             app

#---------------------------------------------------------------------
# static backend for serving up images, stylesheets and such
#---------------------------------------------------------------------
backend static
    balance     roundrobin
    server      static 127.0.0.1:4331 check

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend app
    balance     roundrobin
    server  app1 127.0.0.1:5001 check
    server  app2 127.0.0.1:5002 check
    server  app3 127.0.0.1:5003 check
    server  app4 127.0.0.1:5004 check


```

## Steps to reproduce the behavior

1. Start the haproxy service #systemctl start haproxy
2. Now, perform the soft-reset. # haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)
3. check haproxy status #systemctl status haproxy .

## Actual behavior

If HAProxy service is already started with command: #systemctl start haproxy and soft reset of haproxy with "-sf" option is performed, it is observed that the haproxy service status goes to the  inactive (dead) state.

## Expected behavior
haproxy status should not be in inactive (dead) when load balancing is being performed on its haproxy process. 

## Do you have any idea what may have caused this?

This bug is not reproduced while haproxy is build using source code , this bug is reproduced only on haproxy installation using RHEL packages.

**Comment by wlallemand** [comment]
I'm not sure what you are trying to do, with systemd, a reload will launch a soft restart by doing a kill -USR2 on the master process, or the systemd-wrapper with your version. You are not supposed to launch the haproxy command to do that, only do a "systemctl reload haproxy". 

I don't know which package you are using but you should check in the systemd unit file what it does.

Also, the 1.5 branch will probably die soon, I strongly advise you to update to a more recent branch.

**Comment by kirangavali** [comment]
Hi @wlallemand ,

Thank you for quick response on my query.

> I'm not sure what you are trying to do, with systemd, a reload will launch a soft restart by doing a kill -USR2 on the master process, or the systemd-wrapper with your version. **You are not supposed to launch the haproxy command to do that, only do a "systemctl reload haproxy".**

As you said We do not launch the haproxy command then why haproxy community provided the soft reset command on haproxy community and what is the use of "haproxy -sf" command ?

I got reference from below haproxy community
 [https://cbonte.github.io/haproxy-dconv/2.2/management.html](https://cbonte.github.io/haproxy-dconv/2.2/management.html)

```
A safe way to start HAProxy from an init file consists in forcing the daemon
mode, storing existing pids to a pid file and using this pid file to notify
older processes to finish before leaving :

   haproxy -f /etc/haproxy.cfg \
           -D -p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)

![Capture](https://user-images.githubusercontent.com/36035109/70306987-2c5bd700-182e-11ea-8f5c-3cfcf989c540.JPG)

```
> 
> I don't know which package you are using but you should check in the systemd unit file what it does.
> 
> Also, the 1.5 branch will probably die soon, I strongly advise you to update to a more recent branch.

**Comment by wlallemand** [comment]
The `haproxy -sf` command ask the previous process to exit softly once it started HAProxy. The problem there is that you will start HAProxy outside the context of systemd by doing that so systemd won't be able to see the process.

In fact `haproxy -sf` is not a command to ask an old process to launch a new process, the new process is the actual process of this command. So the process will be started where you executed this command.

This command is supposed to be used in a init script if you launched HAProxy with a init script, but with systemd you don't need it, you just need the systemd-wrapper or the master worker mode.
This master process will launch a haproxy -sf for you when it receives a kill -USR2.
