### ISSUE TITLE
Intermediate CA for client auth does not work

### ISSUE THREAD

**Issue by pboguslawski** [haproxy/haproxy#404]
Hello,

haproxy does no allow one to specify only intermediate CA as allowed to verify client certificates. 

If you put only intermediate cert in file specified in frontends ca-file, server sends to client correct list of allowed CAs for client certs but after client sends correct cert, haproxy throws error "SSL client CA chain cannot be verified" and connection is aborted (haproxy does not know root CA which is not present in ca-file).

If you put root CA and intermediate CA in ca-file, sever sends to client both CAs and client cert is accepted successfully, but this is too much in scenario when you want to trust _only_one_ intermediate_ and not _other_ intermediate CAs signed by the same root CA.

Checked in haproxy v1.8 and 2.0 from debian buster/buster-backports; other reports of this problem:

https://serverfault.com/questions/953679/openssl-haproxy-verify-client-certificates-using-a-non-ca-certificate
https://discourse.haproxy.org/t/intermediate-client-ca/1695

haproxy should allow one to specify separate cert files for:
- client certificate selection (to generate required CA list for client certs; this should allow one to put here only intermediate CA cert)
- client certificate verification (this one may contain additional certs, like root + intermediate CAs)

Apache allows this using SSLCADNRequestFile or SSLCADNRequestPath:

https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcadnrequestfile

Regards,
Paweł

**Comment by ehocdet** [comment]
Hi Pawel

I made a quick patch (on dev branch) to address that with new parameter "ca-names-file" : 
https://github.com/ehocdet/haproxy/commit/bd661e34beac0681e33b89e55d3b0e268340643c
If you can test it it will be great.

**Comment by ehocdet** [comment]
expected final version: https://github.com/ehocdet/haproxy/commit/41cccd0674becb213dc2b46e260674cb3c004f49

**Comment by pboguslawski** [comment]
Hi,

Please note that some PKIs may use only 1 level of CAs (root only without intermediates) and other may use more (3, 4, etc.) levels of intermediates; more: one may need to allow certs signed with some roots and some intermediates of other roots.

Param name ca-root-file introduced in

https://github.com/ehocdet/haproxy/commit/41cccd0674becb213dc2b46e260674cb3c004f49

may be misleading in such scenarios (sometimes will have to contain intermediates also) and ca-file may contain roots and intermediates.

Consider solution similar to apache - one file for certs used for names only (i.e. ca-names) and one file for complete chains used for client cert verification (root+all reqiured intermediates; may or must contain duplicated certs from ca-names). Params proposed in

https://github.com/ehocdet/haproxy/commit/bd661e34beac0681e33b89e55d3b0e268340643c

look better for me.

Regards,
Paweł

**Comment by ehocdet** [comment]
Hi Pawel,

What I understand is that ca-root-file is misnamed: ca-for-no-names-file, ca-end-file, ... could be a better name.
Target is also to minimize changes for back compatibility, not to mimic  other software.

**Comment by pboguslawski** [comment]
(1)
For names presented to client: consider adding new optional parameter ca-names-file; if ca-names-file is defined - all names from certs from this file only will be presented to client. If ca-names-file is not defined - all certs from ca-file will be presented to client (backward compatibility).

(2)
For client cert verification: use certs from ca-file only (backward compatibility). I think ca-names-file should not be used for client cert verification (admin must take care to include in ca-file certs from ca-names-file also if ca-names-file will be used).

(1) + (2) gives solution similar to apache's way (I didn't see better solution to configuring this):

https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcadnrequestfile

**Comment by ehocdet** [comment]
Many thanks to develop your point of view.

My point of view is that it would better to not duplicate CA in files for two distinguishes things (verify and ca-names generation). It's error prone and avoid easiest way to upgrade facility: add a certificate to ca-file for new client.
In 2.1, HAproxy introduced live update for certificates: with 'CA-file' and 'CA-end-file', user could update CA-file (and ca-names) in one command, and not touch CA-end-file who should be more stable.

**Comment by pboguslawski** [comment]
Hi,

We use haproxy 1.8. I don't know live update function so consider implementing CA names feature:
* compatible with haproxy master,
* which allows admin to specify accepted CA names which is subset of certs used for client certificate verification,
* compatible with different PKI scenarios described above,
* easy to understood and without misleading param names because config errors in this area may be dangerous.

Thank you!

Regards,
Paweł

**Comment by pboguslawski** [comment]
We've adapted patches

https://github.com/haproxy/haproxy/commit/d4f9a60ee2648c9552503d7742530e64d28ab027
https://github.com/ehocdet/haproxy/commit/41cccd0674becb213dc2b46e260674cb3c004f49

to haproxy 1.8.19-1+deb10u1 sources (debian 10) and checked that client receives only subjects of certs from ca-file and not from ca-root-file so mod seems to work ok. Thank you!

Regards,
Paweł

**Comment by ehocdet** [comment]
Happy to help,

I have submitted the "ca-no-names-file" https://github.com/ehocdet/haproxy/commit/58c447327933567443a6f685084efd989537bee2  instead the misnamed "ca-root-file" patch.
Perhaps it will be integrated into haproxy-dev branch.

**Comment by wlallemand** [comment]
Hello Manu!

I find the "ca-no-names-file" name not that obvious to understand. Don't you think ca-verify-file is more suited?

**Comment by ehocdet** [comment]
Hi William,
Really more suited. I update the patch.

**Comment by kinvaris** [comment]
Hi,

I just had the same problem that @pboguslawski was describing on pfsense. The installed HAproxy version is: 1.8.27-493ce0b

I first setup the haproxy with client certs via a intermediate CA but I was getting the following errors:
```
Mar  4 16:51:31 pfsense haproxy[18938]: <internal_ipv4_address>:<port> [04/Mar/2021:16:51:31.758] https_shared-merged/<public_ipv4>:<port>: SSL client CA chain cannot be verified 
```

I setup a new root CA and generated a client cert from it, put the root CA on the HAproxy instance and it started working.

Gr,

Jonas Libbrecht
