### ISSUE TITLE
Architecture Document is missing for HA Proxy 2.1

### ISSUE THREAD

**Issue by krtkvrm** [haproxy/haproxy#405]
HAProxy Starter Guide lists `architecture.txt` as `the architecture manual explains how to best architect a load-balanced infrastructure and how to interact with third party products.`.
`architecture.txt` is missing in http://www.haproxy.org/download/2.1/doc/

**Comment by lukastribus** [comment]
Not sure how the site extracts this files, but the tarball and the git tree do contain `doc/architecture.txt`:

https://github.com/haproxy/haproxy/blob/master/doc/architecture.txt

Please note that the architecture has not been updated in a long time and it is definitely not up to date. Please take any statements with a grain of salt.


@wtarreau can you clarify how the `www.haproxy.org/download/2.1/doc/` is generated?

**Comment by chipitsine** [comment]
Hi,  should we use github wiki for such documents?

**Comment by git001** [comment]
I would prefer to keep it in the source doc trees to have it offline available. Jm2c

**Comment by wtarreau** [comment]
We should definitely move this to the wiki, that was the exact purpose
of opening it. The problem with the outdated architecture manual is that
nobody has all the required knowledge anymore nor enough time to maintain
it, while a wiki is accessible by way more people.

@Lukas, regarding the build process, it's the "create-release" script
that explicitly drops this outdated file, and "publish-release" which
is used to publish it, which drops it for any version after 1.3. So I'm
surprised that we're receiving the question now, considering it has been
removed 8 versions ago :-)

**Comment by wtarreau** [comment]
OK I've now updated the intro.txt file in 2.2->1.6 not to mention architecture.txt anymore since it's not packaged.
Thanks!
