### ISSUE TITLE
Upgrading TCP connections to HTTP.

### ISSUE THREAD

**Issue by Mo3m3n** [haproxy/haproxy#406]
## What should haproxy do differently? Which functionality do you think we should add?
Ability to choose to upgrade a TCP connection to a HTTP connection based on information available at layers 4/5/6

## What are you trying to do?
I am trying to choose to offload ssl connections or not to do it, based on the SNI.
For some SNIs I'd like to offload SSL and for others just do ssl-passthrough. 
Currently,imo, the only way to do it is to use "proxy chaining" which means having a frontend listening for SSL traffic in mode TCP (ssl-passthrough) followed by a dummy frontend  in mode HTTP (ssl-offload).

**Comment by bedis** [comment]
Would be cool to be able to configure this in crt-list too :)

**Comment by capflam** [comment]
There is nothing related to the HTTP here. The feature is to choose to offload or not a SSL connection based on the connection information (for instance the SNI). Once offloaded, if you route the request to an HTTP backend, it will be handled as an HTTP connection. Otherwise, it remains a raw TCP connection. This part already work.

**Comment by Mo3m3n** [comment]
> Once offloaded, if you route the request to an HTTP backend, it will be handled as an HTTP connection. Otherwise, it remains a raw TCP connection. 

I was rather thinking about a solution where I can use information in HTTP layer (once SSL offloaded) to make a decision about which backend to choose. Like with a 
So you're suggestion is not going to work in this case.
That being said, the ability to "to choose to offload or not a SSL connection" in the same frontend is already a good thing and I understand that transforming a raw TCP connection to an HTTP one in the same proxy may not play well with the current design (a proxy is statically defined as either HTTP or TCP)

**Comment by capflam** [comment]
It is already how it works. In a TCP frontend, you may use any http sample fetches from `tcp-request content` rules. In [the configuration manual](https://cbonte.github.io/haproxy-dconv/2.1/configuration.html#tcp-request%20content), there are some examples using them from a tcp context.

**Comment by bedis** [comment]
well, keep in mind to add a first `tcp-request content accept if HTTP` first.
Maybe adding a second ACLs to match the SNI list where the traffic is supposedly in clear would do the trick

**Comment by capflam** [comment]
Re-reading this issue, it seems that this feature is already implemented. HAProxy is already capable to upgrade TCP connections to HTTP. And it is possible to choose between SSL offload or not by redirecting the traffic that should be offloaded to a second/internal frontend. I'm closing the issue now.

**Comment by Mo3m3n** [comment]
>And it is possible to choose between SSL offload or not by redirecting the traffic that should be offloaded to a second/internal frontend.

Actually, that was part of the request: Offloading SSL connections conditionally on the same frontend and not resorting to proxy chaining (creating dummy backend, doubling the number of fd, etc)
