### ISSUE TITLE
net:ERR_HTTP2_PROTOCOL_ERROR when sending a 409 to Chrome

### ISSUE THREAD

**Issue by nono** [haproxy/haproxy#410]
Hi,

## Output of `haproxy -vv` and `uname -a`

<details>

```
$ ./haproxy -vv
HA-Proxy version 2.1.1 2019/12/11 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.1.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1b  26 Feb 2019
Running on OpenSSL version : OpenSSL 1.1.1b  26 Feb 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression

$ uname -a
Linux lechat 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

## What's the configuration?

```
global
	maxconn 256

defaults
	mode http
	option httplog
	option dontlognull
	timeout connect 5000ms
	timeout client 50000ms
	timeout server 50000ms

listen http-in
	bind *:1443 ssl crt ssl/bug.localhost/bug.localhost.pem alpn h2
	server server1 127.0.0.1:7000 maxconn 32
	log stderr daemon
```

## Steps to reproduce the behavior

1. Upload a big file from Chrome to haproxy in HTTP/2 (via the JS fetch method)
2. haproxy proxies the request to the backend in HTTP/1.1
3. the backend send a 409 response before the end of the upload

I've made a repository with code and instructions to reproduce the behavior in local: https://github.com/nono/bug-haproxy-chrome

## Actual behavior

- the fetch call fails with an error `net:ERR_HTTP2_PROTOCOL_ERROR`
- in the devtools, we don't see the 409 response
- the other streams of HTTP/2 connection are also lost (not visible in the reproduction code, but observed in production)

## Expected behavior

- the fetch call fails with a response that has the 409 code

## Do you have any idea what may have caused this?

I don't know if it is a bug in Chrome or in haproxy, or just me that have done something I shouldn't.

## Do you have an idea how to solve the issue?

No, I don't know.

**Comment by wtarreau** [comment]
Hi Bruno!

Thanks a lot for your report and particularly for the detailed reproducer, it worked out of the box!
I could enable traces and saw this on the backend side:

[00|h1|0|mux_h1.c:1397] rcvd H1 response headers : [B] [MSG_DATA, MSG_DATA] - VAL=141 - "HTTP/1.1 409 Conflict" - h1c=0x1985cb0(0x00000002) h1s=0x1985610(0x000040
40) ibuf=150@0x1994c00+48/16384 obuf=16384@0x1998c10+13898/16384
         htx=0x1990bf0(size=16336,data=129,used=5,wrap=NO,flags=0x00000000,extra=9,first=0,head=0,tail=4,tail_addr=129,head_addr=0,end_addr=0)
                [0] type=HTX_BLK_RES_SL    - size=43     - addr=0       HTTP/1.1 409 Conflict
                [1] type=HTX_BLK_HDR       - size=33     - addr=43      date: Fri, 13 Dec 2019 14:52:38 GMT
                [2] type=HTX_BLK_HDR       - size=15     - addr=76      content-length: 9
                [3] type=HTX_BLK_HDR       - size=37     - addr=91      content-type: text/plain; charset=utf-8
                [4] type=HTX_BLK_EOH       - size=1      - addr=128     <empty>

Thus it's the server that aborts in the middle of the transfer. A bit later this I'm seeing this on the frontend side:

[00|h2|4|mux_h2.c:2767] h2_frame_check_vs_state(): entering : h2c=0x1e769c0(F,FRP) dft=DATA/00 dsi=17 h2s=0x5cea80(0,CLO)

Thus chrome sent a DATA frame in a state where haproxy considered the stream in a closed state. An RST stream was indeed emitted. I'll have a deeper look at that trace, because for now I'm not yet sure why this stream is supposed to be closed, in my opinion it should be "half-closed(local)". Or maybe it's in fact just because due to the server's early response we're passing the RST_STREAM to the client to cancel the upload. But we should normally see the response headers frame sent there and I don't see it in the trace. I've also tested with an earlier version (2.0.11) without HTX and it's the same.

Were you aware of a previously working version or is it the first time you meed this bug ?

Thanks,
Willy

**Comment by wtarreau** [comment]
Wait a minute, no, I simply missed that line. The response was apparently sent:
```
[00|h1|2|mux_h1.c:1440] switch h1c in busy mode : [B] [MSG_DATA, MSG_DONE] - h1c=0x1985cb0(0x00000042) h1s=0x1985610(0x00004040) ibuf=0@(nil)+0/0 obuf=16384@0x19>
[00|h1|4|mux_h1.c:1494] h1_process_input(): leaving : [B] [MSG_DATA, MSG_DONE] - VAL=0 - "HTTP/1.1 409 Conflict" - h1c=0x1985cb0(0x00000042) h1s=0x1985610(0x0000>
         htx=0x1990bf0(size=16336,data=139,used=7,wrap=NO,flags=0x00000000,extra=0,first=0,head=0,tail=6,tail_addr=139,head_addr=0,end_addr=0)
                [0] type=HTX_BLK_RES_SL    - size=43     - addr=0       HTTP/1.1 409 Conflict
                [1] type=HTX_BLK_HDR       - size=33     - addr=43      date: Fri, 13 Dec 2019 14:52:38 GMT
                [2] type=HTX_BLK_HDR       - size=15     - addr=76      content-length: 9
                [3] type=HTX_BLK_HDR       - size=37     - addr=91      content-type: text/plain; charset=utf-8
                [4] type=HTX_BLK_EOH       - size=1      - addr=128     <empty>
                [5] type=HTX_BLK_DATA      - size=9      - addr=129   
                [6] type=HTX_BLK_EOM       - size=1      - addr=138     <empty>

[00|h1|4|mux_h1.c:2634] h1_rcv_buf(): leaving : [B] [MSG_DATA, MSG_DONE] - VAL=0 - h1c=0x1985cb0(0x00000042) h1s=0x1985610(0x00004040) ibuf=0@(nil)+0/0 obuf=1638>
[00|h1|4|mux_h1.c:2574] h1_subscribe(): subscribe(recv) : [B] [MSG_DATA, MSG_DONE] - h1c=0x1985cb0(0x00000042) h1s=0x1985610(0x00004040) ibuf=0@(nil)+0/0 obuf=16>
[00|h2|4|mux_h2.c:5830] h2_snd_buf(): entering : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,OPN)
[00|h2|4|mux_h2.c:4618] h2s_frt_make_resp_headers(): entering : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,OPN)
[00|h2|0|mux_h2.c:4771] sent H2 response : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,OPN) : [15] H2 RES: HTTP/1.1 409 Conflict
[00|h2|4|mux_h2.c:4809] h2s_frt_make_resp_headers(): leaving : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,OPN)
[00|h2|4|mux_h2.c:5189] h2s_frt_make_resp_data(): entering : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,OPN)
[00|h2|4|mux_h2.c:5427] h2s_frt_make_resp_data(): more data available, trying to send another frame : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,OPN)
[00|h2|1|mux_h2.c:5442] ES flag set on outgoing frame : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,HCL)
[00|h2|4|mux_h2.c:5446] h2s_frt_make_resp_data(): leaving : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,HCL)
[00|h2|4|mux_h2.c:5976] h2_snd_buf(): data queued, waking up h2c sender : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,HCL)
[00|h2|4|mux_h2.c:5999] h2_snd_buf(): leaving : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,HCL)
[00|h2|4|mux_h2.c:3562] h2_io_cb(): entering : h2c=0x198a9c0(F,FRP)
[00|h2|4|mux_h2.c:3433] h2_send(): entering : h2c=0x198a9c0(F,FRP)
[00|h2|4|mux_h2.c:3261] h2_process_mux(): entering : h2c=0x198a9c0(F,FRP)
[00|h2|4|mux_h2.c:3348] h2_process_mux(): leaving : h2c=0x198a9c0(F,FRP)
[00|h2|3|mux_h2.c:3491] sent data : h2c=0x198a9c0(F,FRP)
[00|h2|4|mux_h2.c:3543] h2_send(): leaving with everything sent : h2c=0x198a9c0(F,FRP)
```

Then later when the server closes and is not willing to receive the data anymore, we appropriately send an RST_STREAM(CANCEL):
```
[00|h2|4|mux_h2.c:1722] h2s_send_rst_stream(): entering : h2c=0x198a9c0(F,FRP) h2s=0x19080f0(15,ERR) err=CANCEL/08
```
So I don't see why Chrome wouldn't get the response, especially given that we continue to receive data over that connection. Maybe it's just seeing the cancel and dropping the response ?

**Comment by nono** [comment]
Hi Willy,

> Were you aware of a previously working version or is it the first time you meed this bug ?

I think we have this bug since we have activated HTTP/2, but we thought it was caused by unstable connections on mobile (3G). I'm pretty sure the bug was here with haproxy 1.8, as we had a debug session with it: we identified the bug and were able to reproduce it on our production environment, even if we didn't really why and how it happens. But, it was enough to implement a work-around in the JavaScript.

**Comment by wtarreau** [comment]
By the way I'm not seeing any trace of protocol error here. It would be interesting to see what traces you get on your side, since you're on 2.1. In order to enable them, just add a stats socket to your config:
```
stats socket /tmp/sock1 level admin mode 666
```

Then from a shell, enable H1 and H2 traces and redirect the output to a file:
```
(echo "trace h1 sink buf0; trace h1 level developer; trace h1 verbosity complete; trace h2 sink buf0; trace h2 level developer; trace h2 verbosity complete; trace h1 start now; trace h2 start now;show events buf0 -w -n" ; cat ) | socat - /tmp/sock1
```
You can look for "h2s_send_rst_stream" in the output.

**Comment by nono** [comment]
I've added this line in the global section of the config and restarted haproxy: there is a `/tmp/sock1` socket. But, when I execute `(echo "trace h1 sink buf0; trace h1 level developer; trace h1 verbosity complete; trace h2 sink buf0; trace h2 level developer; trace h2 verbosity complete; trace h1 start now; trace h2 start now;show events buf0 -w -n" ; cat ) | socat - /tmp/sock1
`, I get only a few blank lines, nothing more. I should have missed something, but I don't see what.

I have a log file from Chrome (from `chrome://net-export/`). Can it be useful?

**Comment by nono** [comment]
Oh, it works with a space between `;` and `show events`!

```
$ grep -A10 -B10 h2s_send_rst_stream haproxy.log 
<0>2019-12-13T16:36:42.434258 [01|h1|4|mux_h1.c:2464] h1_shutr(): entering : [B] [MSG_DATA, MSG_DONE] - h1c=0x7f6b28028bb0(0x00004042) h1s=0x7f6b2801de20(0x000040c8) ibuf=0@(nil)+0/0 obuf=0@(nil)+0/0
<0>2019-12-13T16:36:42.434261 [01|h1|2|mux_h1.c:2471] shutdown on connection (error|rd_sh|wr_sh) : [B] [MSG_DATA, MSG_DONE] - h1c=0x7f6b28028bb0(0x00004042) h1s=0x7f6b2801de20(0x000040c8) ibuf=0@(nil)+0/0 obuf=0@(nil)+0/0
<0>2019-12-13T16:36:42.434264 [01|h1|4|mux_h1.c:2488] h1_shutr(): leaving : [B] [MSG_DATA, MSG_DONE] - h1c=0x7f6b28028bb0(0x00004042) h1s=0x7f6b2801de20(0x000040c8) ibuf=0@(nil)+0/0 obuf=0@(nil)+0/0
<0>2019-12-13T16:36:42.434274 [01|h2|4|mux_h2.c:4190] h2_shutw(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,HCL)
<0>2019-12-13T16:36:42.434276 [01|h2|4|mux_h2.c:4195] h2_shutw(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,HCL)
<0>2019-12-13T16:36:42.434277 [01|h2|4|mux_h2.c:4190] h2_shutw(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,HCL)
<0>2019-12-13T16:36:42.434279 [01|h2|4|mux_h2.c:4195] h2_shutw(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,HCL)
<0>2019-12-13T16:36:42.434280 [01|h2|4|mux_h2.c:4175] h2_shutr(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,HCL)
<0>2019-12-13T16:36:42.434282 [01|h2|4|mux_h2.c:4003] h2_do_shutr(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,HCL)
<0>2019-12-13T16:36:42.434284 [01|h2|4|mux_h2.c:1031] h2s_error(): in : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,HCL)
<0>2019-12-13T16:36:42.434287 [01|h2|4|mux_h2.c:1722] h2s_send_rst_stream(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,ERR) err=CANCEL/08
<0>2019-12-13T16:36:42.434289 [01|h2|4|mux_h2.c:1236] h2s_close(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,ERR) err=CANCEL/08
<0>2019-12-13T16:36:42.434291 [01|h2|4|mux_h2.c:1244] h2s_close(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,ERR) err=CANCEL/08
<0>2019-12-13T16:36:42.434293 [01|h2|4|mux_h2.c:1775] h2s_send_rst_stream(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434295 [01|h2|4|mux_h2.c:4042] h2_do_shutr(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434297 [01|h2|4|mux_h2.c:4182] h2_shutr(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434344 [01|h2|4|mux_h2.c:4190] h2_shutw(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434346 [01|h2|4|mux_h2.c:4195] h2_shutw(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434348 [01|h2|4|mux_h2.c:4175] h2_shutr(): entering : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434350 [01|h2|4|mux_h2.c:4042] h2_do_shutr(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434351 [01|h2|4|mux_h2.c:4182] h2_shutr(): leaving : h2c=0x7f6b28026d40(F,FRP) h2s=0x7f6b280210a0(9,CLO) err=CANCEL/08
<0>2019-12-13T16:36:42.434356 [01|h1|4|mux_h1.c:2554] h1_unsubscribe(): unsubscribe(send) : [B] [MSG_DATA, MSG_DONE] - h1c=0x7f6b28028bb0(0x00004042) h1s=0x7f6b2801de20(0x000040c8) ibuf=0@(nil)+0/0 obuf=0@(nil)+0/0
<0>2019-12-13T16:36:42.434359 [01|h1|4|mux_h1.c:2347] h1_detach(): entering : [B] [MSG_DATA, MSG_DONE] - h1c=0x7f6b28028bb0(0x00004042) h1s=0x7f6b2801de20(0x000040c8) ibuf=0@(nil)+0/0 obuf=0@(nil)+0/0
<0>2019-12-13T16:36:42.434362 [01|h1|4|/mux_h1.c:599] h1s_destroy(): in : [B] [MSG_DATA, MSG_DONE] - h1c=0x7f6b28028bb0(0x00004042) h1s=0x7f6b2801de20(0x000040c8) ibuf=0@(nil)+0/0 obuf=0@(nil)+0/0
```

**Comment by wtarreau** [comment]
So you're having a CANCEL as well. It's rather strange that Chrome thinks it sees a PROTOCOL_ERROR then. Does it only happen with Chrome or with other browsers as well ? It could be either a bug there in the stack or an interoperability issue between Chrome and haproxy on a corner case. Chrome devs are quite responsive on interoperability issues so may be we should bring them in the loop ?

**Comment by nono** [comment]
> Does it only happen with Chrome or with other browsers as well ?

I've seen it with chrome, chromium, electron and nodejs. But not with Firefox.

> Chrome devs are quite responsive on interoperability issues so may be we should bring them in the loop ?

Sure, what is the best way to contact them? An issue on https://bugs.chromium.org/p/chromium/issues/list?

**Comment by nono** [comment]
I have created an issue on chromium bugtracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1033945

**Comment by wtarreau** [comment]
I'm currently turning it to "invalid" in that for now the issue seems to be more on the Chrome side according to the discussion in the bug tracker above, but I'm not closing it so that we don't forget to regularly check, and we can easier interact if we need to adjust anything.

**Comment by wtarreau** [comment]
@nono it seems the Chromium team has fixed the issue on their side a while ago: https://bugs.chromium.org/p/chromium/issues/detail?id=1020233. Shall we close it now, or do you want to rerun some tests first ?

**Comment by nono** [comment]
@wtarreau well, I still have an error (`net::ERR_HTTP2_PROTOCOL_ERROR`), and not a 409 when I tries on my repro repository with Chrome 80.0.3987.87. So, I don't think we can tell it is fixed.

**Comment by wtarreau** [comment]
OK thanks for the quick feedback!

**Comment by TimWolla** [comment]
@wtarreau I believe you mixed up the Chrome issue numbers:

From the reporter: https://bugs.chromium.org/p/chromium/issues/detail?id=1033945
The one you linked 2 days ago: https://bugs.chromium.org/p/chromium/issues/detail?id=1020233

**Comment by wtarreau** [comment]
Strange, I found it linked in the discussion. Anyway I agree that yours
indeed clearly says it's not finished.

thanks,
Willy

**Comment by switch1280** [comment]
Would this error 409 occurring when attempting to upload a 20k file across HAProxy be the same issue, even though this is with curl? It works directly to a backend host, but not through the loadbalancer.

Here's the version we're using:
HA-Proxy version 1.7.9-1ppa1~trusty 2017/08/19

Here's the command we're running:
curl -vku USER:PASS https://${SERVER}:/${URL} -X POST -F "name=@/private/tmp/512x512bb.jpg"

Here's the verbose output:
*   Trying 192.168.0.30...
* TCP_NODELAY set
* Connected to server.domain.com (192.168.0.30) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* SSL certificate verify ok.
* Server auth using Basic with user 'USER'
> POST /Resource/fileuploads/mobiledeviceapplicationsicon/id/169 HTTP/1.1
> Host: server.domain.com:443
> Authorization: Basic SlNZQVBJOkoyMkFQMQ==
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 19754
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------bc2bec11f0d983dd
> 
< HTTP/1.1 100 
< HTTP/1.1 409 
< X-FRAME-OPTIONS: DENY
< Cache-Control: no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0
< Date: Tue, 31 Mar 2020 21:10:54 GMT
< Accept-Ranges: bytes
< Server: Restlet-Framework/2.3.12
< Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< Content-Type: text/html;charset=UTF-8
< Content-Length: 443
< Set-Cookie: SRVSTICKY=srv05; path=/
* HTTP error before end of send, stop sending
< 
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>
<p>Unable to complete file upload.  No file found for the upload.</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):

**Comment by capflam** [comment]
I'm closing this issue now. Thanks !  @switch1280 it is not related to this issue. Feel free to open a new issue if necessary.
