### ISSUE TITLE
src/server.c: resource leak found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#417]
```
    10. Condition fgets(mybuf, 512, f), taking true branch.
    16. Condition fgets(mybuf, 512, f), taking true branch.
3609                while (fgets(mybuf, SRV_STATE_LINE_MAXLEN, f)) {
    CID 1402197 (#1 of 1): Resource leak (RESOURCE_LEAK)17. overwrite_var: Overwriting line in line = NULL leaks the storage that line points to.
3610                        line = NULL;
3611
    11. alloc_fn: Storage is returned from allocation function strdup.
    12. var_assign: Assigning: line = storage returned from strdup(mybuf).
3612                        line = strdup(mybuf);
    13. Condition line == NULL, taking false branch.
```

**Comment by bedis** [comment]
I'll have a look :)

**Comment by wtarreau** [comment]
I think the right fix is this as it's the only place where we leave line copied nowhere before freeing it:
```
diff --git a/src/server.c b/src/server.c
index 3465db97c3..1f9fe19397 100644
--- a/src/server.c
+++ b/src/server.c
@@ -3616,7 +3616,7 @@ void apply_server_state(void)
 
                        srv_state_parse_line(mybuf, global_file_version, params, srv_params);
                        if (params[0] == NULL)
-                               continue;
+                               goto nextline;
 
                        /* bkname */
                        bkname = params[1];

```

In addition I'm seeing quite an expensive operation that very likely slows down the state file parsing significantly and uses tremendous amounts of RAM:

			st = calloc(1, sizeof(*st) + trash.size);
                        (...)
			memcpy(st->name_name.key, trash.area, trash.size);

So for each backend+server name string (~20 chars typicaly) we allocate and memcpy a whole 16kB buffer. So if you have 100k servers this will allocate and copy 1.6GB of RAM. You need to replace trash.size with "trash.data + 1" here. Just let me know if you want to handle it right now, or I can do it now before the release.

**Comment by wtarreau** [comment]
OK finally I've done these and also addressed a 3rd issue with duplicate entries also eating memory. I'm closing the issue now as that was backported to 2.1.
