### ISSUE TITLE
Function url_enc similar to url_dec

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#425]
## Output of `haproxy -vv` and `uname -a`

Future version.

## What should haproxy do differently? Which functionality do you think we should add?

add a function to encode none ASCII url parts into ASCII.  
see ML for discussion.  
https://www.mail-archive.com/haproxy@formilux.org/msg35783.html

**Comment by wdauchy** [comment]
reading the thread, it is not very clear whether it is really needed. It seems to be more an application side issue.
However if the need is confirmed, I can work on the patch.

**Comment by git001** [comment]
Let's close this issue until we have a better usecase.

**Comment by KlavsKlavsen** [comment]
I have a usecase for you - I hope you like :)
We require JWT login for multiple services - also several which actually does not support it - so we decode the JWT in haproxy (lua) to verify it, before even forwarding the request. All this works great.
But - if the visitor does not have a valid JWT (or its too old) - we'd today redirect them to the login page (on a diff. central domain) - and we'd really like to pass along the url they were trying to visit, so they can be redirected back by after login.
That requires us to take the url and url enc it in the Location we're sending.. haproxy needs this function to do that.

**Comment by wdauchy** [comment]
I might have a closer look in the following weeks if it is ok

**Comment by TimWolla** [comment]
Duplicate of #941
