### ISSUE TITLE
New checks feature collection

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#426]
Let's try to collect most of the wishes for the new check setup.

## Output of `haproxy -vv` and `uname -a`
Future version

## What should haproxy do differently? Which functionality do you think we should add?

* better usability for checks.
  ```
  option check_url URL OR %[URL,enc_url]
  option check_host %[host]
  ```
* Maybe it could be considered to use a applet for checks.
  ```
  check-app http-1
    mode http
    host %[host] or %[host,punycode] or %[str('host'),punycode]
    url URL or %[URL,url_enc]
    header ...
    header ....
    param ....
    auth ...

    check-app tcp-1
    mode tcp
    tcp-payload ...

    check-app udp-1
    mode udp
    udp-payload ...

  backend YYY
    check-app http-1
  ```
The functions punycode and url_enc are not yet part of haproxy

**Comment by grivet** [comment]
Hi,

Checks were due for some work recently, I have started implementing something similar to the applet you are  describing (not using applets however). This takes the form of templates of tcp-checks, defined once and re-used in several backends.

My feature is however limited to tcp-checks. There might be plan to extend it to other types if it is useful, but this is not currently planned, http-check in particular (need some cleanup before). There are no UDP checks AFAIK.

It might be worthwhile to clear up the design if we want to add other types of challenge / responses (H2 support in particular). This will the subject of another dev after this one. No current plan to add UDP support however, if that is of interest to some users please shout.

**Comment by wtarreau** [comment]
IMHO UDP checks are totally pointless since there's no definition of what behavior to expect (typically a successful UDP check would be one which doesn't provide an ICMP unreachable in return in a finite duration). More useful would be specific checks on UDP-based services. But since we only support proxying TCP-based protocols, I'd say that relying on side signals to declare a server up or down remains a very bad solution, so this can remain pretty low on the priority list.

**Comment by git001** [comment]
With release of 2.2-dev7 are the checks now completely overwritten. Looks like with this release is this issue done.

https://github.com/haproxy/haproxy/commit/fc0b8f39a6497f89cab338fc515f4a922cadecc2

**Comment by TimWolla** [comment]
> Looks like with this release is this issue done.

Labeled 'fixed', thanks.
