### ISSUE TITLE
Outdated documentation on Cache Limitations in 1.9+

### ISSUE THREAD

**Issue by amit777** [haproxy/haproxy#43]
In the Limitations section (10.1) here:
https://github.com/haproxy/haproxy/blob/master/doc/configuration.txt

> The cache won't store and won't deliver objects in these cases:
> - If the response is not a 200

However, in the 1.9 news release it says the following at https://www.haproxy.com/blog/haproxy-1-9-has-arrived/

> HAProxy can now cache the responses of the following status codes: 204, 404, 405, 414, and 501. 

Is the documentation out of date?

**Comment by lukastribus** [comment]
The blog post talks about the change in c55ddce65c6d727da3587074caea4733c6a91f96 (which btw is also in `1.8.2`), but this commit does not affect the object cache.

As the commit says:

> For now this it only checked by the checkcache option to detect cacheable cookies.

Object cache only works with 200 responses, the documentation is correct.

@dcorbett-haproxy maybe you want to fix that blog post.
