### ISSUE TITLE
HA Proxy h2 idle connection closing logic seems to have issues

### ISSUE THREAD

**Issue by phaze-debug** [haproxy/haproxy#431]
This is related to the bug report that I had initially logged and was fixed. https://github.com/haproxy/haproxy/issues/373 1
I am reopening the issue because seems like although the original issue was fixed, there might be issues with the way the connections are being closed. We are seeing a new issue with the requests timing out (usually starts to appear as the load increases). To reiterate our system landscape, HA Proxy is balancing the traffic between multiple Java backend processes running Tomcat. Upon enabling the tomcat container logs, this is what we could see. Both exceptions show up at the same time. Suspecting this has something to do with the way ha proxy is closing the connections. I haven’t posted the entire stack trace, but if it helps, please let me know. -

org.apache.catalina.connector.ClientAbortException: org.apache.coyote.CloseNowException: Connection [8], Stream [299], This stream is not writable

java.io.IOException: HTTP/2 Stream reset at org.apache.coyote.http2.Stream$StreamInputBuffer.doRead

**Comment by wtarreau** [comment]
It would be useful to see haproxy logs as well to figure why it decided to close the connection.
Also, last time you were on 2.0.10, so I guess you're now on 2.0.12, could you please confirm ?

**Comment by phaze-debug** [comment]
Thanks for getting back, @wtarreau - We are still on 2.0.10 but can upgrade to 2.0.12, if it helps. I wish I could share the ha proxy logs but have to check on confidentiality agreement. Meanwhile, I am trying to enable tomcat's fine-grained http/2 logging to capture the stream information. I did come across this in tomcat archives which might be what is happening - 

https://www.mail-archive.com/dev@tomcat.apache.org/msg125313.html,

**Comment by wtarreau** [comment]
Regarding the logs we don't need any private information. What's useful is to see the termination state (the 4 chars usually "----" or "SD--" or so), the status code, the timers+retry count. You can grep for some of the failed connections by yourself and just report these parts.

Yes it sounds like haproxy sent an RST there, what we need to figure is why. Also, if it happens often enough, yes you'd better first upgrade to 2.0.12, though I'm seeing that fixes related to shutdowns/aborts seem related to H1 and not H2 (but maybe the abort is detected on an H1 client and forwarded).

**Comment by phaze-debug** [comment]
So, this might not be of much help but after enabling tomcat h2 logs, can confirm that haproxy is sending RST. This is what I see in the logs before tomcat throws out ClientAbortException - 

Connection [3], Stream [5,297], State changed from [HALF_CLOSED_REMOTE] to [CLOSED_RST_RX]. 

I am still trying to figure out a way to get the logs for failed connections. I could not see any connection failure logs without enabling trace, After enabling trace on the backend, the throughput drops drastically (strangely, this issue does not show up under low load or when the throughput drops). We are using Marathon LB which is running on top of HA Proxy and cannot define any custom trace. Would really help if you can let me know if there's any other way to get the logs you'd need. We are still working on upgrading to 2.12

**Comment by wtarreau** [comment]
OK so this at least confirms this is an RST_STREAM. Thus it doesn't close the connection but the stream. This is not necessarily a problem, it could be as simple as a client clicking "STOP" during the download, or an http-response rule blocking a response.

Regarding the logs, you just need to add "option httplog" to your frontend, with a "log global" directive so that logs for this frontend are sent to the same place as the rest of the logs. If you only want to log errors (that's a bad idea, you should always log the traffic unless you're not interested in performance), you can add "option dontlog-normal" to the frontend.

You're speaking about enabling traces, I'm not sure which ones you're speaking about considering that traces were introduced in 2.1.

**Comment by phaze-debug** [comment]
Thanks, will try with the httplog option and let you know. I had added the trace directive to the backend like this and I could see the trace logs - 
backend process_12345
  balance roundrobin
  mode http
  option http-use-htx
  server xxx_xxx_xx_xxx_12345 xxx_xxx_xx_xxx_12345 proto h2
 filter trace name h2trace

As for our scenario, it is a plain app-to-app GET request without any manual intervention, and is being run through a load runner script (the script invokes a REST endpoint. The service that serves the endpoint internally calls another service. It is the service-service communication that's happening over h2c). We don't have any http-response rule defined, either.

We are using Java 8, which doesn’t have native support for h2. The external library we use for h2 is okhttp. To rule it if it is an issue with the client library, I tried with haproxy as passthrough (set the mode to tcp and ran the same test). The load, as expected was not balanced but did not face this issue in pass through mode

**Comment by wtarreau** [comment]
OK then indeed the trace filter can be extremely expensive, it's mainly aimed at developers.
Thanks for the background on the use case and your other tests.

**Comment by phaze-debug** [comment]
Tried with option httplog but could not see anything getting logged when the stream is getting closed. Will see if I am missing anything and try again. Meanwhile, just wanted to let you know the same ha proxy instance is also used to balance traffic to other backend processes that use http 1.1. Sharing the HAProxy config defaults since I hadn't shared before (want to make sure none of the default settings could be causing this issue) - 

defaults
  load-server-state-from-file global
  log               global
  retries                   3
  backlog               10000
  maxconn               10000
  timeout connect         60s
  timeout client          60s
  timeout server          60s
  timeout tunnel        3600s
  timeout http-keep-alive  20s
  timeout http-request    60s
  timeout queue           30s
  timeout tarpit          60s
  option            dontlognull
  option            redispatch

This is the frontend config of the h2 backend process - 

frontend process_12345
 bind *:12345 proto h2
 mode http
 option httplog
  use_backend process_12345

**Comment by wtarreau** [comment]
Do you have any "log" statement in your global section ? I assumed you did but maybe you never log at all ?
If you don't have any log, and are running under systemd or docker, probably the easiest for you will be to set "log stdout daemon" instead of "log global". This will send the logs to stdout which will be archived where your service manager puts it. You'd rather enable "option dontlog-normal" to avoid getting too much traffic though.

**Comment by phaze-debug** [comment]
Thanks, @wtarreau - We tried with log stdout format raw daemon as we are running under docker but haproxy failed to start with this error - the default HAPROXY_HEAD section changed, please make the following changes to your custom template: Remove "daemon", Add "stats socket /var/run/haproxy/socket expose-fd listeners"

We are running a customized version of HA Proxy with the way it has been provided by our vendor. Will work with them to figure out if it is their custom template that's causing this issue. Will get back as soon as I have an update

**Comment by TimWolla** [comment]
> We are running a customized version of HA Proxy with the way it has been provided by our vendor. Will work with them to figure out if it is their custom template that's causing this issue. Will get back as soon as I have an update

A Google search for the error message pointed me to the product in question. It uses an extraordinarily dumb config “parser” that will reject the start whenever it finds the word `daemon` within your configuration. Probably in an attempt to be helpful in case the user configured the [`daemon`](http://cbonte.github.io/haproxy-dconv/2.1/configuration.html#daemon) option. You might want to point them to the `-db` command line argument which will take precedence over the `daemon` option and prevent daemonization.

**Comment by wtarreau** [comment]
Ah that's almost funny, thanks Tim for spotting this one :-)
Well, you can use "local0" instead of daemon if you want, it will be the same.

**Comment by wtarreau** [comment]
So what's the status here, after a month of idling ? Did you try again with Tim's suggestion ?

**Comment by capflam** [comment]
It seems to be a dead issue. May be closed now.
