### ISSUE TITLE
Return last error on L7 retries

### ISSUE THREAD

**Issue by Elufimov** [haproxy/haproxy#439]
This is a followup of this https://discourse.haproxy.org/t/502-as-result-of-unsuccessful-retries/4651 question.

## What should haproxy do differently? Which functionality do you think we should add?
Forward to a client the last server response if L7 retry is enable and request exceeds all retries. Right now haproxy return blank 502 in this situation.

## What are you trying to do?
We are trying to adopt retries in our frontend proxy (for especially 50x) and our application react differently on different backed errors but haproxy return 502 if retry exceeds all attempts.

**Comment by wtarreau** [comment]
I think this indeed makes sense. I don't know what it involves to do
it though but it's worth having a look at it.

**Comment by capflam** [comment]
@wtarreau, we should probably don't try to trigger an l7 retry at the stream-interface level when the maximum connection retries is reached, in si_cs_recv().  Something like that:

```diff
diff --git a/src/stream_interface.c b/src/stream_interface.c
index 1d84ca9ad..214b73858 100644
--- a/src/stream_interface.c
+++ b/src/stream_interface.c
@@ -1372,7 +1372,7 @@ int si_cs_recv(struct conn_stream *cs)
                        break;
                }
 
-               if (si->flags & SI_FL_L7_RETRY) {
+               if ((si->flags & SI_FL_L7_RETRY) && si->conn_retries) {
                        struct htx *htx;
                        struct htx_sl *sl;
```

**Comment by wtarreau** [comment]
I think it's the best approach, yes.

**Comment by capflam** [comment]
Ok, so I'll handle this issue. I update the labels because it is a bug not a feature.

**Comment by capflam** [comment]
It should be fixed in upstream now.

**Comment by Elufimov** [comment]
It was so quick! Thx @capflam @wtarreau !
