### ISSUE TITLE
maxconn is 40000, but max connection is only 500

### ISSUE THREAD

**Issue by hezhiqiang** [haproxy/haproxy#440]
i use haproxy 2.1.0, my config is below:

vi /etc/haproxy.cfg
global
    daemon

defaults
    timeout connect 5s
    timeout client  50s
    timeout server  50s

listen keydb 
    bind *:6379
    maxconn 40000 
    mode tcp
    balance first
    option tcp-check
    tcp-check send AUTH\ 密码\r\n
    tcp-check expect string +OK
    tcp-check send PING\r\n
    tcp-check expect string +PONG
    tcp-check send QUIT\r\n
    tcp-check expect string +OK
    server keydb1 ip1:6380 maxconn 20000 check inter 1s
    server keydb2 ip2:6379 maxconn 20000 check inter 1s

**Comment by wtarreau** [comment]
Your global maxconn is 500 because it's not set and your process is started with the default per-process FD limit of 1024. You either have to add a maxconn value in the global section or to set your FD limit with ulimit -n before starting it.

**Comment by hezhiqiang** [comment]
@wtarreau thanks very much, solved, ^_^
