### ISSUE TITLE
"select" method does not work (current master branch)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#442]
reproduced on travis-ci

`./haproxy -vv` ("select" is available)

https://travis-ci.com/haproxy/haproxy/jobs/269501267#L467-L471

```
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
```

actual run ("select" is not available):
https://travis-ci.com/haproxy/haproxy/jobs/269501267#L774-L775

```
***  h1   debug|Available polling systems :
***  h1   debug|      epoll : pref=300, 
***  h1   debug| test result OK
***  h1   debug|
***  h1   debug|       poll : 
***  h1   debug|pref=200,  test result OK
***  h1   debug|     select : pref=150, 
***  h1   debug| test result FAILED
***  h1   debug|Total: 3 (2 usable), will use epoll.
```

**Comment by chipitsine** [comment]
same is reproduced by me on CentOS 7.7.1908

**Comment by lukastribus** [comment]
I assume your have maxconn > 500 so you are probably hitting this expected behavior:
https://github.com/haproxy/haproxy/commit/8274e105b752f70c41e49aa21c3f50531e986639

https://github.com/haproxy/haproxy/commit/3fa87b1db95bc4d6640999462bdae620bff147c6


Which is explained in the error message as you noticed in the other thread:

> indeed, after adding noepoll, nopoll
> 
> ```
> Available polling systems :
>      select : pref=150,  test result FAILED
>        poll : disabled,  test result OK
>       epoll : disabled,  test result OK
> Total: 3 (0 usable), will use poll.
> 
> Available filters :
> 	[SPOE] spoe
> 	[CACHE] cache
> 	[FCGI] fcgi-app
> 	[TRACE] trace
> 	[COMP] compression
> [ALERT] 010/183238 (1577) : No polling mechanism available.
>   It is likely that haproxy was built with TARGET=generic and that FD_SETSIZE
>   is too low on this platform to support maxconn and the number of listeners
>   and servers. You should rebuild haproxy specifying your system using TARGET=
>   in order to support other polling systems (poll, epoll, kqueue) or reduce the
>   global maxconn setting to accommodate the system's limitation. For reference,
>   FD_SETSIZE=1024 on this system, global.maxconn=4096 resulting in a maximum of
>   8221 file descriptors. You should thus reduce global.maxconn by 3599. Also,
>   check build settings using 'haproxy -vv'.
> ```

**Comment by chipitsine** [comment]
yep. I missed that.
