### ISSUE TITLE
HAProxy management documentation render issue 

### ISSUE THREAD

**Issue by niktwenty3** [haproxy/haproxy#445]
## Issue details

Line 794 of /doc/management.txt renders as a function instead of plain text. 
https://github.com/haproxy/haproxy/blob/f31af9367ed7e381e34716c0df53b6a1c0a0c405/doc/management.txt#L794

![image](https://user-images.githubusercontent.com/10053187/72341875-ad2eae00-36cb-11ea-9846-ebd372d9a4ea.png)

## Steps to reproduce the behavior

1. Parse management.txt using dconv

## Steps to fix

1. Wrap `/proc/irq` in quotes `'/proc/irq'`

**Comment by lukastribus** [comment]
@cbonte is that your suggestion?

**Comment by cbonte** [comment]
Hi all, sorry for the late answer.
First, I thought I already fixed that specific rendering issue a long time a ago. It appears it's not the case.

In my opinion, wrapping the text is not the best fix. It definitely should be properly detected in the documentation converter.

Ideally, I should validate the arguments syntax during the conversion to prevent false positives. But that may require some extra work and in the short term I won't be able to find that time. I'm adding it to my TODO list.
But for now, a quick fix may be to limit the number of words evalutated to consider it's really a keyword. Arbitrarily, I set this value to 5 words, but it seems we never have more than 3 words to define a haproxy keyword. I try to apply this quick fix in the next 24h.

**Comment by cbonte** [comment]
Oh and I forgot the specific case of a keyord detected with an argument beginning with a /.
This happens only once in the whole documentation, for the bind keyword. Maybe we can also rework this part of the documentation.
For example :
```
bind <path>
bind </path>
...
```
instead of :
```
bind /<path>
```

That way, I can safely remove the / from the regex used to detect keywords.

**Comment by wtarreau** [comment]
On Mon, Jan 20, 2020 at 03:05:31PM -0800, Cyril Bonté wrote:
> Oh and I forgot the specific case of a keyord detected with an argument beginning with a /.
> This happens only once in the whole documentation, for the bind keyword. Maybe we can also rework this part of the documentation.
> For example :
> ```
> bind <path>
> bind </path>
> ...
> ```
> instead of :
> ```
> bind /<path>
> ```
> 
> That way, I can safely remove the / from the regex used to detect keywords.

In fact we only need "bind <path>" because "/<path>" is wrong, as the doc
later says that <path> must begin with a "/", thus the "/" is part of <path>.

Willy

**Comment by wtarreau** [comment]
This problem doesn't exist anymore in the latest version of the doc, closing.
