### ISSUE TITLE
src/backend.c: null pointer dereference found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#454]
```
*** CID 1412593:  Null pointer dereferences  (NULL_RETURNS)
/src/backend.c: 1975 in back_handle_st_con()
1969                    /* Note: state = SI_ST_DIS now */
1970                    DBG_TRACE_STATE("client abort during connection attempt", STRM_EV_STRM_PROC|STRM_EV_SI_ST|STRM_EV_STRM_ERR, s);
1971                    goto end;
1972            }
1973     
1974            /* first, let's see if we've made any progress on this connection */
>>>     CID 1412593:  Null pointer dereferences  (NULL_RETURNS)
>>>     Dereferencing "conn", which is known to be "NULL".
1975            if (!conn->mux && (conn->flags & CO_FL_CONNECTED)) {
1976                    /* connection finished to set up */
1977                    struct server *srv;
1978     
1979                    if (conn->flags & CO_FL_ERROR)
1980                            goto fail;
```

**Comment by wdauchy** [comment]
not sure to understand the issue here, I don't see when conn can be null; or maybe this is just because it's not written ```!(conn->mux)``` ?

**Comment by TimWolla** [comment]
> not sure to understand the issue here, I don't see when conn can be null;

These static analyzer work on a bunch of assumptions which are missing from the issues @chipitsine creates. My educated guess would be that coverity noticed that `objt_conn` (i.e. the second part of the ternary conditional) could return `NULL` if the passed parameter is not `OBJ_TYPE_CONN` and then `back_handle_st_con` would dereference a null pointer.

If it's guaranteed that all the state is good whenever `back_handle_st_con` is called then this is a false positive, but coverity can't know this. I am a fan of `assert`s / `BUG_ON` to clarify this guarantee and as a by-product help the static analyzers, but @wtarreau disagrees there :smile:

**Comment by chipitsine** [comment]
if you guys tell me to mark it as "intentional", I'll do so.

also, I mark as "modelling required" (models is coverity way to skip some cases: https://scan.coverity.com/tune#writing-model

**Comment by TimWolla** [comment]
> if you guys tell me to mark it as "intentional", I'll do so.

I am not qualified to make that decision.



> also, I mark as "modelling required" (models is coverity way to skip some cases: https://scan.coverity.com/tune#writing-model

That link is only available for logged in users.

**Comment by wtarreau** [comment]
OK it's a false alarm, it believes it can be null due to objt_conn() which may return a NULL if passed a null but that cannot happen here, so I replaced it with __objt_conn().
