### ISSUE TITLE
with http 1.0 backend servers we need to default to httpclose

### ISSUE THREAD

**Issue by bjacke** [haproxy/haproxy#458]
I have a tiny python BaseHTTPServer server which support http 1.0 only. While the backend returns some valid status code like 200, haproxy returns HTTP/1.0 502 Bad Gateway.

#### backend response:
# curl  http://10.11.0.3:8000/ -D - 
HTTP/1.0 200 OK
Server: HookHandler/0.1 Python/2.7.16
Date: Tue, 21 Jan 2020 14:42:33 GMT

#### haproxy response with http2 broken:
curl: (92) HTTP/2 stream 1 was not closed cleanly: REFUSED_STREAM (err 7)

#### haproxy response with http 1.1:
# curl -D - --no-apln https://...
HTTP/1.0 502 Bad Gateway
cache-control: no-cache
content-type: text/html

 <html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>

adding option httpclose to the backend makes this work (curl -v against the backed server mentioned "* HTTP 1.0, assume close after body" and pointed me in the right direction).

**Comment by lukastribus** [comment]
Please reopen once you fill out the issue template completely.
