### ISSUE TITLE
haproxy unhappy with empty (missing) http bodies

### ISSUE THREAD

**Issue by bjacke** [haproxy/haproxy#459]
I have a python based http 1.0 backend server which can send empty http bodies:

# curl  http://10.11.0.3:8000/ -v
* Expire in 0 ms for 6 (transfer 0x55aec790ff50)
*   Trying 10.11.0.3...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55aec790ff50)
* Connected to 10.11.0.3 (10.11.0.3) port 8000 (#0)
> GET / HTTP/1.1
> Host: 10.11.0.3:8000
> User-Agent: curl/7.64.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: HookHandler/0.1 Python/2.7.16
< Date: Tue, 21 Jan 2020 15:01:30 GMT
* Closing connection 0

This also makes haproxy unhappy and return a 502 Bad Gateway. As soon as I send an empty line as an "empty" body, haproxy is happy.

**Comment by lukastribus** [comment]
Please reopen once you fill out the issue template completely.

**Comment by capflam** [comment]
Just to be sure you will not create new issues for nothing. Be careful to have a valid response first, with a last CRLF at the end, marking the end of headers.

**Comment by bjacke** [comment]
Thanks for replying, in fact http requires CRLF at after headers, even with empty bodies. Many well known client implementations don't mind about the missing CRLF though. If haproxy will stay stricter with for backend servers than clients like curl, then at least this bug report helps people solve their issue if they hit the same problem.
