### ISSUE TITLE
src/standard.c: structurally dead code found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#463]
```
145                case 1000000000000000000ULL ... 9999999999999999999ULL:
   CID 1403869 (#1 of 1): Structurally dead code (UNREACHABLE)unreachable: This code cannot be reached: i = 18;.
146                        i = 18;
147                        break;
148
149                case 10000000000000000000ULL ... ULLONG_MAX:
150                        i = 19;
151                        break;
```

```
255                case 1000000000000000000ULL ... 9999999999999999999UL:
   CID 1403839 (#1 of 1): Structurally dead code (UNREACHABLE)unreachable: This code cannot be reached: i = 18;.
256                        i = 18;
257                        break;
258
259                case 10000000000000000000ULL ... ULONG_MAX:
260                        i = 19;
261                        break;
```

**Comment by wtarreau** [comment]
This one really makes no sense. Why only this specific line ? If it had complained much earlier I could I imagined coverity only knew about 32-bit integers, but here in the middle of nowhere, it really makes no sense at all. I'm even wondering if it's not a bug in coverity's integer parser!

**Comment by chipitsine** [comment]
I think, coverity does not like `ULL` <--> `UL`  comparision

**Comment by wtarreau** [comment]
On Thu, Jan 23, 2020 at 08:25:25AM -0800, Ilya Shipitsin wrote:
> I think, coverity does not like `ULL` <--> `UL`  comparision

I thought about this as well, except that it's not present in the first
report. Also this one is only on the 64-bit part so it shouldn't harm.

Willy

**Comment by wtarreau** [comment]
Let's mark this one as a false positive, it's just adding noise to the bug tracker.

**Comment by chipitsine** [comment]
done
