### ISSUE TITLE
htx_manage_server_side_cookies: is_cookie2 is uninitialised

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#47]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0-dev0-8861e1-296 2019/02/12 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O0 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_OPENSSL=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE
              h2 : mode=HTX        side=FE|BE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

## What's the configuration?

```
defaults
	option http-use-htx

listen http
	mode http
	bind *:8080

	cookie foo insert

	# Pretend example.com send a `Set-Cookie` header
	http-request set-header Host example.com
	server example1 example.com:443 ssl verify none sni req.hdr(host) cookie bar
	server example2 example.com:443 ssl verify none sni req.hdr(host) cookie baz
```

## Steps to reproduce the behavior

Apply the following patch:

```diff
diff --git i/src/proto_htx.c w/src/proto_htx.c
index 9e285f21..9eb7b911 100644
--- i/src/proto_htx.c
+++ w/src/proto_htx.c
@@ -4288,7 +4288,7 @@ static void htx_manage_client_side_cookies(struct stream *s, struct channel *req
                }
        } /* for each "Cookie header */
 }
-
+#include<assert.h>
 /*
  * Manage server-side cookies. It can impact performance by about 2% so it is
  * desirable to call it only when needed. This function is also used when we
@@ -4309,6 +4309,7 @@ static void htx_manage_server_side_cookies(struct stream *s, struct channel *res
 
        ctx.blk = NULL;
        while (1) {
+               assert(is_cookie2 == 1);
                if (!http_find_header(htx, ist("Set-Cookie"), &ctx, 1)) {
                        if (!http_find_header(htx, ist("Set-Cookie2"), &ctx, 1))
                                break;
```

## Actual behavior

The assert passes.

## Expected behavior

The assert does not pass.

## Do you have any idea what may have caused this?

I suspect the following:

gcc detects that `is_cookie2` is only ever assigned the value `1` and therefore pretends the unintialized value is always `1` and optimizes it away. With `-O0` the `assert` fails as expected.

## Do you have an idea how to solve the issue?

Initialize `is_cookie2` to `0`. But then there is another issue in the function (I did not verify, this is deduced from reading the code):

The `Set-Cookie2` header is only ever looked at when no `Set-Cookie` headers can be found any more. Thus in the following list of headers HAProxy fails to check the `Set-Cookie2` header:

```
HTTP/1.1 200 OK
Set-Cookie2: …
…
Set-Cookie: …
```

because the `ctx` has already been advanced past the `Set-Cookie2` header when finding the `Set-Cookie` header.

(if you'd ask me I'd just remove support for Set-Cookie2 in HTX :wink:)

**Comment by wtarreau** [comment]
While I don't know about the bug (I've not read the surrounding code yet), I tend to agree that we could use the transition to HTX to remove support for Set-Cookie2. Nobody uses it, it was a failure. It's not even documented in the config manual, so it will not come as a big surprise!

**Comment by TimWolla** [comment]
@wtarreau Is this resolved with 6f7a02a381339d48a6e5f1430ad87c7dccfb0054 or do you want to re-visit this ("But then there is another issue in the function ...")?

**Comment by wtarreau** [comment]
On Mon, Apr 15, 2019 at 03:39:27PM -0700, Tim Düsterhus wrote:
> @wtarreau Is this resolved with 6f7a02a381339d48a6e5f1430ad87c7dccfb0054 or
> do you want to re-visit this ("But then there is another issue in the
> function ...")?

I completely forgot about this one, thanks for the reminder. I've just
checked and legacy mode only ever checked set-cookie2 when set-cookie
was absent. I suspect that RFC2965 recommended not to mix the two but
I could be wrong. Set-Cookie2 was used to set multiple cookies at once
so there was no point in mixing the two.

We could get rid of set-cookie2 anyway since it was obsoleted years
ago given that nobody implements it. I think haproxy was about the only
one to modify (thus emit) it, and Opera was the only one to parse it...

I guess we can close this issue and mark it as fixed once the fix is
backported.

Thanks,
Willy

**Comment by TimWolla** [comment]
> I guess we can close this issue and mark it as fixed once the fix is backported.

Fair enough. It's backported now, thus closing.

**Comment by TimWolla** [comment]
> (if you'd ask me I'd just remove support for Set-Cookie2 in HTX wink)

I almost predicted it was going to cause issues down the road :sweat_smile:

bfb15ab34ead85f64cd6da0e9fb418c9cd14cee8

**Comment by wtarreau** [comment]
Too bad we didn't notice the root of the bug by then!

**Comment by wtarreau** [comment]
We forgot to drop it in the past, I don't want breakage between 2.5 and 2.6 so we must keep a note somewhere that this must be removed after 2.6.

**Comment by wtarreau** [comment]
With that said, the reporter probably met it for real in field :-/

**Comment by TimWolla** [comment]
> so we must keep a note somewhere that this must be removed after 2.6.

a) We could commit a patch into the 'next' branch.
b) We could create a separate tracking issue that references this one and we both try to remember about that after 2.6 was released.

**Comment by wtarreau** [comment]
While a) tends to be the most common, I like b) as it allows such changes to be more visible to everyone. Maybe we should have a "next" tag in the issues just for this.

**Comment by TimWolla** [comment]
> b) as it allows such changes to be more visible to everyone. Maybe we should have a "next" tag in the issues just for this.

Okay, for now I've just filed it #1551. Feel free additional labels as desired.
