### ISSUE TITLE
Unable to clone haproxy 1.0 or 1.1 trees

### ISSUE THREAD

**Issue by FireBurn** [haproxy/haproxy#470]
Hi

When I try and clone haproxy 1.0 or 1.1 I get the following error

git clone http://git.haproxy.org/git/haproxy-1.0.git/
Cloning into 'haproxy-1.0'...
fatal: repository 'http://git.haproxy.org/git/haproxy-1.0.git/' not found

git clone http://git.haproxy.org/git/haproxy-1.1.git/
Cloning into 'haproxy-1.1'...
fatal: repository 'http://git.haproxy.org/git/haproxy-1.1.git/' not found

The rest clone correctly

I've created a unified repo at https://github.com/FireBurn/haproxy with all the other branches and tags but until I can clone 1.0 & 1.1 it won't be complete

**Comment by wtarreau** [comment]
Thank you for the report, this is now fixed. The hooks on the server were still using the old (and absent) "git-update-server-info" command to generate the info/refs file, and it didn't fail for recent repositories just because these are also refreshed during the regeneration of the bugs matrix.

**Comment by FireBurn** [comment]
I've just noticed that when I push to my repo notifications pop up in your repo :(

Would you be interested in doing what I've done and using this mirror to add in all your branches of haproxy?

**Comment by TimWolla** [comment]
> I've just noticed that when I push to my repo notifications pop up in your repo :(

It does not actually send notifications, it just creates references within the issues. I would assume that this stops happening if you “de-fork” your repository (i.e. delete and re-create as standalone), because GitHub then doesn't know what repository the issue numbers should refer to.
