### ISSUE TITLE
openssl-1.1.0, libressl builds fail on current master

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#480]
https://travis-ci.com/haproxy/haproxy/builds/147080448

**Comment by wtarreau** [comment]
Strange, as far as I remember, the abns test doesn't depend on the openssl
version. We might have broken something else, but why it doesn't affect
1.1.1 is a mistery :-/

**Comment by chipitsine** [comment]
cron builds are green
seems https://github.com/haproxy/haproxy/commit/1c7c0d6b97513e79c304aaf834f83843f32a674d fixed this issue

**Comment by wtarreau** [comment]
It should not as this one seems to only concern the cases of lack of memory, but I may be wrong. Given that we cannot give a clearer verdict here, we can hardly take any action. Let's close this one and reopen it if the issue surfaces again.

**Comment by wlallemand** [comment]
This bug was preventing the previous HAProxy process to leave by being locked up in the pool deinit. Since the abns test does a seamless reload that could be the explanation.
