### ISSUE TITLE
Github releases

### ISSUE THREAD

**Issue by publicarray** [haproxy/haproxy#49]
First off thanks for developing haproxy!

Since 1.9 releases the releases on githup are no longer synced with the releases on the website. Could this be fixed? I use the new Github watch feature to only notify me of new releases so that I can update my docker images accordingly.

**Comment by lukastribus** [comment]
This is a mirror of the development tree, therefor you will see only development tags like `v1.9-dev5` or `v2.0-dev0`, but not stable release tags, which are in the stable git branches that are currently not mirrored on github.

However, those are git tags, not Github releases, and Github notifies on new releases, it does not notify on new git tags. The Github UI is very confusing as tags are actually shown as releases, but they really aren't. Therefor, the "release-only" notification would not work anyway with tags. I have discussed the confusing UI with Github staff, they agree and have filed my feedback.

So to get the notifications working on new stable releases, we would have to:
- mirror stable tree's on github
- manually make mark certain tags as releases here on github

While the former may be possible, the latter is an additional step in the release process, which I'm not sure should be any longer or more complicated than it already is.

Tagging @TimWolla @wtarreau for additional feedback.

**Comment by wtarreau** [comment]
I don't really understand the issue to be honest. We've never had releases here, there's nothing related to 1.9 at all, and as you say we only have the development tree here. At the moment I'm not particularly fond of further complicating the stable release process by adding new stuff to take care of.

Also this made me discover that the tarballs on github are wrong, they don't respect the git-archive attributes and the SUBVERS and VERDATE entries were not expanded. We'd rather need to remove these tarballs from github, I don't know if we can prevent it from emitting such bogus tarballs.

**Comment by wtarreau** [comment]
In fact the attributes for SUBVERS and VERDATE are in .git/info/attributes which are the old way to store them and cannot be pushed. Nowadays it's possible to move them to .gitattributes which can be pushed an apparently github would respect them.

**Comment by publicarray** [comment]
Thank you for the thoughtful responses!

I made a few wrong assumptions, but yea the fact that github does not give notification on tags is odd. Thanks for letting me know.  It looks like I'm going back to use the atom feeds for other repos with ifttt.com. Is there a way to inform package managers or users of new releases from haproxy other than visiting the website?

**Comment by TimWolla** [comment]
> Is there a way to inform package managers or users of new releases from haproxy other than visiting the website?

The mailing list is the canonical place to get notified about new releases. You can also [scrape the website like Docker does](https://github.com/docker-library/haproxy/blob/master/update.sh) using a cronjob (or scrape that repository itself).

**Comment by dellelce** [comment]
@TimWolla my travis [job](https://travis-ci.org/github/dellelce/mkit/jobs/690685103) that use the scraping method is timing out.... while from other points in the network the website is working fine. 

Was travis blocked? Is the "scraping" method still allowed?

Though if all tags were pushed to github I could scrape github (or use its unauthenticated API).

**Comment by TimWolla** [comment]
@dellelce I do not run the instrastructure and thus can't answer your question, but please see this email: https://www.mail-archive.com/haproxy@formilux.org/msg37405.html
