### ISSUE TITLE
Please change this unofficial project's misleading description

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#49]
The project's description says "Mirror of haproxy repository...". This is misleading, please change it to something more accurate like "Unofficial fork of haproxy repository ...", as the project contains commits that are *not* in the official repositories, and people get confused and post pull requests here that nobody processes nor reads.

This repository is causing more harm to the HAProxy project than it helps due to its misleading nature. Please do something about this quickly.

**Comment by jbuchbinder** [comment]
Sorry about that -- theoretically the only changes are Travis CI integration for automated testing of the builds, but I'll adjust the name for you (as well as giving you admin access).

**Comment by wtarreau** [comment]
Hi Jeff,

On Mon, Nov 02, 2015 at 05:51:01AM -0800, Jeff Buchbinder wrote:
> Sorry about that -- theoretically the only changes are Travis CI integration
> for automated testing of the builds, but I'll adjust the name for you (as
> well as giving you admin access).

I think its preferable to call it "fork" rather than "mirror" since a
mirror is supposed to be the same. Here, it's not always up to date, and
there are merge commits that don't exist in mainline. If someone builds
haproxy from there and shows something like "1.7-dev0-2065ffc-16", we cannot
match this against any official commit, which is problematic.

Maybe also discouraging people from sending pull requests could help,
something like "pull requests will be ignored" may be enough for them
to ask on other channels.

Thanks,
Willy

**Comment by jbuchbinder** [comment]
I sent you an invite to admin the mirrors, so you're more than welcome to change any of the verbiage in whichever ways work best. I originally set these "mirrors" up to allow digging through git history whenever the main git repo wasn't functional, and tacked on travis CI builds later. If there's a better way to maintain the mirrors other than me manually syncing them, I'd be more than happy to remove and recreate them in a way that would more properly mirror your repo.

**Comment by jbuchbinder** [comment]
We can actually turn off "issues" to disallow pull requests, etc, but I wanted to wait until after we had closed this thread, since I'm pretty sure it would destroy all of this if I would flip that switch.

**Comment by wtarreau** [comment]
So probably this will require some inspection before it's turned off, because some of them might possibly be real bugs. I've e-mailed you on your work address (hoping it's still the right one), it will be easier to discuss than via this interface!
