### ISSUE TITLE
REGEX in ACL Hangs Client

### ISSUE THREAD

**Issue by kaizen1** [haproxy/haproxy#498]
```
Linux haproxy-z-a 5.0.0-1029-gcp #30~18.04.1-Ubuntu SMP Mon Jan 13 05:40:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

HA-Proxy version 2.0.12-1ppa1~bionic 2019/12/21 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-N7m_4z/haproxy-2.0.12=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

```

## What's the configuration?

```
frontend stats

	maxconn 15
        bind *:8450 ssl crt /etc/haproxy/certs/mysite.pem alpn h2,http/1.1
        log /dev/log local0 debug
	
	stats enable

	acl invalid_host hdr(host) -m reg -i \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
	http-request deny if invalid_host
etc. etc.
```

## Actual behavior

Browser hangs and eventually times out when this URL is opened https://xx.yy.zz.aa/stats where xx.yyy.zz.aaa is an IP4 address (my real users will never use this). Using the FQDN opens the URL without a problem.

This is not a terrible result because it blocks the request that has a Host as IP address, but I think it should fail fast. 

## Expected behavior

I think it should fail fast on the client. 

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

Leave it as is.

**Comment by wtarreau** [comment]
I suspect this is related to the recent fix on truncated responses. Do you want to give a try to latest 2.0 snapshot ? Note that if you want to block your users you can use the "silent-drop" action which is even better: it silently kills the connection on haproxy's side after acking the contents, so that the browser waits forever without eating any resource on your side.

**Comment by kaizen1** [comment]
I'm only able to test from deb http://ppa.launchpad.net/vbernat/haproxy-2.0/ubuntu bionic main, and that's still on 2.0.12 (same as issue report version)

Thanks for the silent-drop tip.

**Comment by wtarreau** [comment]
I've just pushed 2.0.13 which clears a bunch of other bugs, better test on this one then.

**Comment by kaizen1** [comment]
Tried do an update from deb http://ppa.launchpad.net/vbernat/haproxy-2.0/ubuntu bionic main, but it's still on 2.0.12

**Comment by wtarreau** [comment]
On Thu, Feb 13, 2020 at 07:48:29AM -0800, kaizen1 wrote:
> Tried do an update from deb http://ppa.launchpad.net/vbernat/haproxy-2.0/ubuntu bionic main, but it's still on 2.0.12

Please grant the distro maintainers some time to see the announce
and take the time to update, build and publish their packages :-)
They're doing this on their spare time, and since this update has
nothing critical it can take a few days.

Thanks!

**Comment by kaizen1** [comment]
Got it. I wasn't familiar with the build process :) 
Thank you!

**Comment by TimWolla** [comment]
@kaizen1 FYI: HAProxy 2.0.13 appears to be available now.

**Comment by capflam** [comment]
No feedback since a while. May be closed now.
