### ISSUE TITLE
Haproxy can bind multiple frontends to the same port without warning the end user

### ISSUE THREAD

**Issue by phattrent** [haproxy/haproxy#51]
I saw this on haproxy-1.6.1 and haproxy 1.5.1, I assume I should get a warning or error when attempting to bind multiple frontends to the same port.  Instead the /haproxy check feature returns valid configuration and round robins TCP requests between the frontends.  

Example configuration:

global
    pidfile     /var/run/haproxy.pid
    user        haproxy
    group       haproxy
    daemon

defaults
    mode                    http
    timeout http-request    15m
    timeout queue           1m
    timeout connect         10s
    timeout client          5m
    timeout server          5m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 15000

frontend main
    bind *:80
    acl foo hdr_dom(host) -i drpepper.example.com
    use_backend platform-backend-foo if foo

frontend platform-frontend-foo *:8084
    default_backend             platform-backend-foo
backend platform-backend-foo
    balance     roundrobin
    server  foo 172.28.15.60:80 cookie foo check inter 3000

frontend platform-frontend-bar *:8084
    default_backend             platform-backend-bar
backend platform-backend-bar
    balance     roundrobin
    server  bar 172.28.15.4:80 cookie bar check inter 3000

**Comment by wtarreau** [comment]
This is a valid config and some people use this, so there is no reason at all
for reporting an error on a valid configuration. It's not haproxy which performs
the round robin, it's the kernel since it sees two listeners for the same
destination. And to be precise, it doesn't perform a round robin but a hash
on (ip, ports) to pick the correct socket queue.

**Comment by phattrent** [comment]
I couldn't find the documentation with examples for this section, can you point me to it? I saw bind uses a unique port in the doc so I assumed frontend did the same.

**Comment by wtarreau** [comment]
The most common case is simply when you use nbproc > 1 to let the kernel
perform clean load balancing between the listening sockets. For example :

global
	nbproc 4

listen foo
	bind :1234
	bind :1234
	bind :1234
	bind :1234
	server bar 1.2.3.4:80

You can then improve such a configuration by limiting each bind line to
a given process :

listen foo
	bind :1234 process 1
	bind :1234 process 2
	bind :1234 process 3
	bind :1234 process 4
	server bar 1.2.3.4:80

**Comment by phattrent** [comment]
thanks

**Comment by mfischer-zd** [comment]
Willy, do you have an example of where such a configuration would be not just valid, but also useful, such that this "feature" is worth keeping?

**Comment by cbonte** [comment]
As an example, via the global stats socket, this allows to enable/disable different frontends with similar behaviour but with a slightly different configuration :
- enable temporarily the stats page publicly
- enable a frontend with stronger limits in case of DoS attempts
- activate temporarily a new version of a service
...

**Comment by mfischer-zd** [comment]
Those are good examples, @cbonte, but do they all need to be enabled simultaneously?

**Comment by cbonte** [comment]
They don't need, they can. You don't have the need, I sometimes have.

**Comment by mfischer-zd** [comment]
When would it be useful for them to be enabled *simultaneously*?  That's the answer I'm looking for.

**Comment by cbonte** [comment]
random part of customers going to the next (un)stable release of a service

**Comment by mfischer-zd** [comment]
But that can also be accomplished by configuring the backends such that one or more is a server providing the unstable release, no?

**Comment by cbonte** [comment]
It depends on what you want to test, here it allows to validate 2 (or even more) frontends configurations at runtime, including the client connection. This is still one of numerous examples users can have.

**Comment by cbonte** [comment]
But I understand that if doesn't fit with your needs, it may be suitable to find a solution.
Does a global option like "noreuseport" would do the trick ? The purpose would be to not set the SO_REUSEPORT socket option, resulting in a fatal error (cannot bind socket)

**Comment by mfischer-zd** [comment]
Sure, that'd be a great workaround.  It'd be nice if that were the default because I think most users probably don't benefit from this feature.

**Comment by wtarreau** [comment]
It's not the default for several reasons :
- it allows seamless config reloads ; without SO_REUSEPORT the old process
  is forced to stop listening before the new one takes over ;
- it supports a scalable multi-process model for high loads

We've already considered having such an option a few times for config
validation but each time it did not appear very useful compared to the
loss of the features above.

Also please note that you can already shoot yourself in the foot without
SO_REUSEPORT if one frontend listens to 0.0.0.0:80 and another one to
1.2.3.4:80.

In my opinion such cases would be better dealt with using a diagnostic
mode that we still don't have. This mode would allow haproxy to run more
advanced strange patterns detection and report warnings (eg: two servers
having the same cookie value in a farm, two listeners with overlapping
ip:port:interface:process, multiple stats sockets in the same process,
unbound stats socket in multi-process mode, etc).

**Comment by lukastribus** [comment]
That is all correct and I agree with Willy, but to respond to Cyril's proposal:

I do believe that a "noreuseport" keyword (and command line argument) could be useful. There are situations when we want to make sure that the haproxy instance about to start is exclusively bound to those ports. Troubleshooting/debugging are one of those situations.

We allow people to manually tune a lot of things, we should also allow them to disable reuseport, to restore the behavior as it was for a really long time on Linux (< 3.9).

This doesn't fix the core issue here, and I agree with Willy that we need something more; but making reuseport configurable is a very good idea.

**Comment by zpeterg** [comment]
Is there any progress in implementing a no-reuseport setting?

**Comment by wtarreau** [comment]
I'm not aware of anyone having volunteered to working on it yet :-/
