### ISSUE TITLE
Allow private keys from OpenSSL ENGINE

### ISSUE THREAD

**Issue by space88man** [haproxy/haproxy#518]
## Output of `haproxy -vv` and `uname -a`

```
HAProxy version:  haproxy >= 2.2
OS version: ANY
```

## What should haproxy do differently? Which functionality do you think we should add?

Allow HAProxy to use private keys from OpenSSL ENGINE if supported: e.g. using engine pkcs11 + PKCS#11 module

## What are you trying to do?

Do TLS + HSM termination with HAProxy

Currently HAProxy has OpenSSL ENGINE support for algorithms but in the bind statement for a listener or outgoing connection to backend there does not seem to be a way to specify that the private key should be from the engine.

The crt option parses the PEM file for key and cert. It would be useful to enhance it like nginx 

```
http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate_key
ssl_certificate_key:  The value engine:name:id can be specified
    instead of the file (1.7.9), which loads a secret key with a 
    specified id from the OpenSSL engine name. 
```

Additonal considerations: some OpenSSL ENGINEs wrap PKCS#11 modules, in which case, it would be necessary to defer loading such keys using ENGINE_load_private_key until after the fork() (in multiprocess mode). The reason for this is  PKCS#11 modules do behave well after fork()-ing and consumers are required to call `C_Initialize)` and reload all resources in the child process.. However this is an implementation detail not available to HAProxy (we do not know if the backing ENGINE is actually using PKCS#11).

**Comment by wlallemand** [comment]
I'll look into this to see if that's easily doable, but I don't think it will be available before 2.3 if it's implemented.

**Comment by githubMichaelYang** [comment]
@wlallemand , 
any updates?

**Comment by hsmguy** [comment]
@wlallemand 
@space88man 
@markun 
@tmm1 

couldnt get this working on pkcs11 engine for the ca bind.

got it working on chil engine however :p with a fake pem pointer file to hsm key using the ca bind.... (this works).

suggest you implement a method to allow a pkcs11 URI for pkcs11 engine for the private key.

i work for an HSM company, we would like to see this functionality :-)

thank you,

**Comment by freedge** [comment]
I am interested in this feature for TPM2 engines (https://github.com/tpm2-software/tpm2-tss-engine/, https://github.com/tpm2-software/tpm2-openssl for OpenSSL 3). At the moment the engine generates a private key file (that starts with ```-----BEGIN TSS2 PRIVATE KEY```) that could be used as private key, but a handle of the tpm2 could be referenced as well.

**Comment by wlallemand** [comment]
No progress on this for now. Also this is a duplicate of #71. Please comment on this one. I'm closing the issue.
