### ISSUE TITLE
Select a new server to reforward based on specific errors

### ISSUE THREAD

**Issue by wangao1236** [haproxy/haproxy#523]
Hello, I am a beginner of haproxy, and I am trying to deploy haproxy to realize the load balancing of a kubernetes cluster. 
I would like to ask a question whether haproxy has the ability to select a new server to retransmit after timeout or a specific status code appears?
I know there is a configuration item called option redispatch, but from the documentation, it only works when the server is down. 
However, the problem I ask is that I want to retransmit a specific error code after it has occurred, and the machine with the error code or timeout may return to normal within a certain period of time.
Thank you very much for answering my question~~

**Comment by wtarreau** [comment]
What you're asking for are layer-7 retries. Please have a look at the "retry-on" directive in the documentation. For more help you can ask on the mailing list, but I'm closing this issue since it cannot qualify as a feature request, being already implemented.
