### ISSUE TITLE
SPOA traffic mirroring

### ISSUE THREAD

**Issue by silviubajenaru** [haproxy/haproxy#529]
## Output of `haproxy -vv`

```
HA-Proxy version 2.0.10-1ppa1~bionic 2019/11/26 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-M3LRQ8/haproxy-2.0.10=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=40).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

```

# Output of uname -a
````
Linux HAProxy1-wbidder 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
````

## What's the configuration?

```
global
#        log /dev/log    local0 info
#        log /dev/log    local1 notice
        log /dev/null    local0
        # Get Core Dumps
        set-dumpable

        stats socket /var/run/haproxy/admin.sock mode 660 level admin
        stats socket /var/run/haproxy/info.sock mode 666 level user
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
        master-worker

        # Performance tunning
        maxconn 2000000

        # Use multiple cores
        nbproc 1
        nbthread 38
        cpu-map auto:1/1-38 0-37

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private
        tune.ssl.default-dh-param 2048
        tune.ssl.cachesize 1000000
        tune.ssl.lifetime 3600
        tune.ssl.maxrecord 1460
        stats bind-process 1
        # Default ciphers to use on SSL-enabled listening sockets.
        # For more information, see ciphers(1SSL). This list is from:
        #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
        # An alternative list with additional directives can be obtained from
        #  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!a
        ssl-default-bind-options force-tlsv12

program mirror
    command spoa-mirror --runtime 0 --mirror-url http://<remote test machine:port/

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option log-health-checks
        # Protect against Slowloris
        #timeout http-request 20s
        #timeout connect 10s
        #timeout client  20s
        #timeout server 25s
        timeout http-request 15s
        timeout connect 15s
        timeout client  15s
        timeout server 15s
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http


frontend http
    bind 0.0.0.0:80
    mode http
    http-request add-header X-Forwarded-Proto http
    redirect scheme https if !{ ssl_fc }

frontend www-https
    bind 0.0.0.0:443 ssl crt /etc/haproxy/bundle.pem

    option http-buffer-request
    filter spoe  engine mirror  config /etc/haproxy/mirror.conf

    http-request add-header X-Forwarded-Proto https
    default_backend pool0
    mode http
    maxconn 350000

backend pool0
    mode http
    fullconn 200000
    option http-server-close
    option httpchk
    # Delete the X-Forwarded-For header. Useful when the user's behind a proxy server.
    http-request del-header X-Forwarded-For
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    balance leastconn
    timeout connect 15s
    timeout check 15s
    # Backend servers down below
    [...]
   server server77 <ip>:<port> check weight 220 maxconn 11000

backend test
    mode tcp
    balance roundrobin
    timeout connect 5s
    timeout server 5s
    server test1 <ip>:<port>

```

## Steps to reproduce the behavior
Use the config file. Please see the behavior described below.

## Actual behavior

I expected HAProxy to mirror the requests to the test server, based on the mirror.conf file. I followed the https://www.haproxy.com/blog/haproxy-2-0-and-beyond/ and https://www.haproxy.com/blog/haproxy-traffic-mirroring-for-real-world-testing/ tutorial to set this up. Still, the issue is that the test server is getting something from the haproxy but tcpdump reports:
    <test_server_ip>.<port> > <haproxy's IP>.54970: Flags [P.], cksum 0x5b19 (incorrect -> 0xeeb4), seq 1:146, ack 134, win 235, options [nop,nop,TS val 3633271597 ecr 1543946716], length 145: HTTP, length: 145
        HTTP/1.1 400 Bad Request
        Content-Length: 65
        Content-Type: application/json
        {"error":"Bad Request","message":"Client Error","statusCode":400}[!http]

## Expected behavior

Properly "clone" the requests it gets. If I set the test server as a backend server, everything works fine...

## Do you have any idea what may have caused this?
None.

## Do you have an idea how to solve the issue?
No.

**Comment by capflam** [comment]
Could you share your spoa-mirror configuration and tell us the version you use ? Then it may be useful to give more info about the request itself.

**Comment by silviubajenaru** [comment]
Hello,

As I said, I followed the articles from those two webpages. The mirror.conf file looks like thsi now:
````
[traffic-mirror]
spoe-agent spoe-traffic-mirror
    log global
    messages mirror
    option set-on-error err
    option set-process-time ptime
    option set-total-time ttime
    option var-prefix spoe
    timeout hello 500ms
    timeout idle 10s
    timeout processing 100ms
    use-backend test

spoe-message mirror
    args arg_method=method arg_path=url arg_ver=req.ver arg_hdrs=req.hdrs_bin arg_body=req.body
    event on-frontend-http-request if { rand(10000) le 1 }
````
As for the version:
````
# spoa-mirror -V
spoa-mirror v1.2.6 [build 2388] by Miroslav Zagorac <mzagorac@haproxy.com>, Mar  2 2020
````

**Comment by capflam** [comment]
Thanks for the config. And about the failing request ? If you have a tcpdump with the test server response, I guess it is easy to have the request too. You can also try to run the spoa-mirror in debug mode (--debug 511).

**Comment by silviubajenaru** [comment]
While playing with it I said that I should take a look at tcpflow and found something interesting:
````
<proxy IP>.64878-<mirror server IP>.<app port>: /status-codemessageframe is too big
<proxy IP>.05688-<mirror server IP>.<app port>: supported-versions2.0max-frame-sizecapabilitiespipelining,asyncengine-id$3851b06e-2ae4-4f99-a20a-c7a6a731347e
<mirror server IP>.<app port>-<proxy IP>.05688: HTTP/1.1 400 Bad Request
Content-Length: 65
Content-Type: application/json

{"error":"Bad Request","message":"Client Error","statusCode":400}
````
````
<proxy IP>.05688-<mirror server IP>.<app port>: supported-versions2.0max-frame-sizecapabilitiespipelining,asyncengine-id$3851b06e-2ae4-4f99-a20a-c7a6a731347e
````
 is what caught my eye.... Supported-versions2.0max-frame-sizecap[..] .....?

Also, as something that I didn't quite understand, what is the -u <link> in the spoa-mirror do? I've set it to -u 'http://<mirror server IP>:<port>/' but I'm not sure it's right....?

As for the requests, they are usually long URLs. I can't say now, but they're generally /offer?ID=<long string>
Trying to run spoa-mirror in debug now.

Can't seem to find a way to run spoa-mirror in debug mode.....?

**Comment by capflam** [comment]
the `-u` option must be used to specify the url of the http server where to send the mirrored request. So `http://IP:PORT` is valid.

I'm not an spoa-mirror expert. But during compilation step, I followed the README and passed '--enable-debug' option to the configure script.

**Comment by capflam** [comment]
About the "strange" packet exchanged between HAProxy and the spoa-mirror, it is part of the SPOE protocol. There is an hello handshake when a new connection is established. But the previous packet, "frame is too big" is not welcome at all. I really need to have the request dump (anonymized if necessary). I'm asking because I suspect the request is too big to be fully sent to the spoa-mirror (A request with a huge payload for instance). Or it may have a problem with the Host header.

But in the end, to know if there is a bug in HAProxy or not, get a tcpdump between HAProxy and the spoa-mirror.

**Comment by silviubajenaru** [comment]
Hello,

I tried to compile spoa with --enable-debug and run it manually but nothing shows up in the console... 
Also, because I forgot to turn on spoa manually once, it seems that even without spoa-mirror running, traffic is being sent to the target machine....? I commented the program spoa-mirror line that was starting spoa when haproxy started in order to start it manually. I forgot to start it before restarting haproxy and traffic just started to flow from haproxy to the target machine...? Looks like the spoa-mirror process is bypassed somehow....?

> About the "strange" packet exchanged between HAProxy and the spoa-mirror, it is part of the SPOE protocol. There is an hello handshake when a new connection is established. But the previous packet, "frame is too big" is not welcome at all. I really need to have the request dump (anonymized if necessary). I'm asking because I suspect the request is too big to be fully sent to the spoa-mirror (A request with a huge payload for instance). Or it may have a problem with the Host header.

This was between the haproxy machine and the mirror machine, not between haproxy and spoa-mirror process.
As for the request, Here is one of the requests: ````/offer?affid=null&subid=null&count=1````
Another request goes like this: ````/?id=2Fc%3Fpv%3D2%26v%3D0%7C0%7C0%7CvQ7sz52vdHoFPh7j-oWYyX0VQI4-oluDSUMK8veQ7NZlL-PDaEFkz73tXFLLkAAb%26cid%3D721394%26f%3D1%26h2%3Dh6Cjt7-SKwNai_zVWzMBBWmQxV2Yf0rUxqfPrlk_5TM*%26rid%3Da12dbb86-5d6b-11ea-91c7-e4434b151302%26psid%3Dbid_5555%26cp%3D153%26iub%3DaHR0cHM6Ly9zLWltZy5hZHNrZWVwZXIuY28udWsvZy81MDQ5ODUxLzMyOHgzMjgvLTB4LTB4NDkyeDMyOC9hSFIwY0RvdkwybHRaMmh2YzNSekxtTnZiUzkwTHpJd01Ua3RNVEV2TWpRM016RTVMek5sWkdWbU5qVXpabVpoTkdRMVlqbGhOekk1TkRkak5tTTFPRGs1TjJWbExtcHdadyoqLndlYnA%3D&s=1060&a=bid_5555&sub=1234&d=8&ic=0````

> But in the end, to know if there is a bug in HAProxy or not, get a tcpdump between HAProxy and the spoa-mirror.

How can I provide a tcpdump?

**Comment by capflam** [comment]
> I tried to compile spoa with --enable-debug and run it manually but nothing shows up in the console...
> Also, because I forgot to turn on spoa manually once, it seems that even without spoa-mirror running, traffic is being sent to the target machine....? I commented the program spoa-mirror line that was starting spoa when haproxy started in order to start it manually. I forgot to start it before restarting haproxy and traffic just started to flow from haproxy to the target machine...? Looks like the spoa-mirror process is bypassed somehow....?

Be careful to kill all remaining spoa-mirror instances before doing your tests. You have probably one of them running in background. 

> 
> This was between the haproxy machine and the mirror machine, not between haproxy and spoa-mirror process.

Wait a minute. What you say is that some SPOE packets are sent to your http test server ? In your HAProxy configuration, the `test` backend must point on the spoa-mirror. By default `127.0.0.1:12345`. Only the spoa-mirror knows the address of your http test server (via -u parameter).

**Comment by silviubajenaru** [comment]
Ok, this isn't a bug then. My bad.
From what I understood, I got the picture that the haproxy would send the traffic to the mirror server directly, not via the SPOA, but the SPOA would somehow mangle with the traffic before it leaves the haproxy.
So, now everything's clear. You have to create a backend using the SPOA-mirror as a backend server which then forwards the traffic to the actual mirror server using the -u <url> parameter.

And, of course, it works.

Seems to have been an issue from the admin.
Thank you for your time.
