### ISSUE TITLE
Invalid warning shown at startup

### ISSUE THREAD

**Issue by rmillet-rs** [haproxy/haproxy#54]
Hello, this is a really minor issue because a warning is display when it should not and the functionality used still works.

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.19 2019/02/11
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -ggdb3 -O0
  OPTIONS = USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with PCRE version : 7.8 2008-09-05
Running on PCRE version : 7.8 2008-09-05
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with multi-threading support.
Encrypted password support via crypt(3): yes
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with OpenSSL version : OpenSSL 1.1.1b  26 Feb 2019
Running on OpenSSL version : OpenSSL 1.1.1b  26 Feb 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[TRACE] trace
	[COMP] compression
	[SPOE] spoe


Linux 6197e6339bc2 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

Extract from haproxy.cfg:
```
frontend myfront
    bind 172.29.43.2:443 name default ssl ssl-max-ver TLSv1.2 ssl-min-ver TLSv1.0 crt /etc/ssl/certs/haproxy.default.crt crt-list /etc/haproxy/crt-list.cfg ecdhe prime256v1 ciphers ECDHE-ECDSA-CHACHA20-POLY1305:*redacted*:!3DES
```

Extract from crt-list.cfg:
```
/etc/haproxy/cert_2147483651 [ssl-min-ver TLSv1.0 ssl-max-ver TLSv1.2 ciphers ECDHE-ECDSA-CHACHA20-POLY1305:*redacted*:!3DES] example.com
```

## Steps to reproduce the behavior

1. Use ssl-min-ver and/or ssl-max-ver in a crt-list file configuration
2. Start haproxy

## Actual behavior

The warning  is shown:
> crt-list: ssl-min-ver and ssl-max-ver are not supported with this Openssl version (skipped).

But the directives still work correctly

## Expected behavior

No warning is shown because it works.

## Do you have any idea what may have caused this?

Condition here is wrong (I have OpenSSL >= 1.1.1, but not boringSSl):
https://github.com/haproxy/haproxy/blob/8e5e1e7bf000f2603a085c76be118214d22c55b4/src/ssl_sock.c#L7657

## Do you have an idea how to solve the issue?

Change the condition linked above (I don't know if it should work with boringSSL))

**Comment by lukastribus** [comment]
Thanks for the precise report!

A patch has been posted for review:
https://www.mail-archive.com/haproxy@formilux.org/msg32972.html
