### ISSUE TITLE
Add DEBUG_STRICT=1 to CI

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#546]
## What should haproxy do differently? Which functionality do you think we should add?

We should add `DEBUG_STRICT=1` to ensure Travis / Cirrus / GitHub Actions run with `BUG_ON` enabled.

see: https://www.mail-archive.com/haproxy@formilux.org/msg36621.html

## What are you trying to do?

Improve the quality of the CI.

**Comment by chipitsine** [comment]
yep. I noticed some recent commit regarding to BUG_ON.

do we need to run two flavour of builds - with DEBUG_STRICT=1 and without ?
or DEBUG_STRICT=1 is enough ?

**Comment by TimWolla** [comment]
> or DEBUG_STRICT=1 is enough ?

That should be enough. It just enables `BUG_ON` which crashes the process if the condition is violated, no other behavior is modified. If such a condition is violated it indicates a bug that must be fixed (either within the condition or within the surrounding code). In CI we want to catch those bugs.

**Comment by chipitsine** [comment]
I've found it

https://github.com/haproxy/haproxy/commit/f4629a5346ea341026e908792a6b31e98022faa1

**Comment by chipitsine** [comment]
@TimWolla , I'll play with DEBUG_STRICT in my fork and send a PR.
seem to be simple

**Comment by chipitsine** [comment]
it is implemented in https://github.com/haproxy/haproxy/commit/2f9802b24be0aef3689a1cd06fd166383a936118
