### ISSUE TITLE
Peers Protocol: Decouple on-the-wire table key from SMP_T_*

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#548]
This is a tracking issue for what was [discussed on the list](https://www.mail-archive.com/haproxy@formilux.org/msg36650.html):

From @wtarreau:
> No we shouldn't rely on this and we should instead change the peers code
> to remap SMP_T_* to the on-wire value. I think this got broken a long
> time ago when extending the sample types to support the ADDR type which
> carries both IPv4 and IPv6, and nobody noticed that these types were
> transported directly over the wire :-(  Bingo, that was this patch
> between 1.5 and 1.6 that merged the two:
> […]
> So now from what I'm seeing, we should document that on the wire we
> have this:
>
>   2 = signed int
>   4 = IPv4
>   5 = IPv6
>   6 = string
>   7 = binary

**Comment by TimWolla** [comment]
@wtarreau I'd like to bump this, because I'm not sure whether this should go into 2.2 or not.

**Comment by wtarreau** [comment]
Indeed it would definitely be better if it was done before 2.2 but I'm afraid it's too much for my own todo list :-( If someone wants to work on it I'll really appreciate it. Otherwise we can get it done later as a cleanup.

**Comment by TimWolla** [comment]
Resolved as of: 530ba38a706ed640e43eb44abe5578c7a5826d5d
