### ISSUE TITLE
Add path option to the cookie keyword

### ISSUE THREAD

**Issue by jcmoraisjr** [haproxy/haproxy#550]
## What should haproxy do differently? Which functionality do you think we should add?

Add `path` option into the `cookie` keyword. Currently haproxy uses the root path `/` hardcoded.

## What are you trying to do?

I'm trying to configure a cookie to be visible only on a subpath of a domain - [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1)

**Comment by TimWolla** [comment]
Can you use the `attr` directive? It has been backported to 1.8+: 2f5339079b884ac8bdde166add1879ebfd9e433b

**Comment by jcmoraisjr** [comment]
Hi, yup, I'm currently using `attr`, my concern is regarding the duplicated attribute and some broken http client. A new `path` directive or remove the hardcoded `path=` if I'm declaring one from `attr` is fine for me.

**Comment by lukastribus** [comment]
Haproxy cookies are only used for stickiness. Are you saying you need per path stickiness? I don't really understand the use-case.

**Comment by jcmoraisjr** [comment]
Yes. The use-case is stickiness that need to be configured on backends due to one of its functionality. It'd be an improvement if the sticky session could be configured only on that path, other paths would benefit from the current lb algorithm. An acl would also be welcome here.

**Comment by wtarreau** [comment]
It's a real pain to deal with path-based cookies. For example you'll have a hard time purging them. You'd rather let the client send the cookie all the time and have haproxy ignore it on selected paths. Usually it's done like this:
```
       ignore-persist unless { path_beg /foo }
```
or:
```
       ignore-persist if { path_beg /img /css /static }
```

**Comment by jcmoraisjr** [comment]
Hi Willy, thanks for the helpful hint. No matter how much of haproxy I think I know, every now and then I'm discovering a new nice keyword. This doesn't work how I'd expect but for sure it'll do the job. Closing this FR.
