### ISSUE TITLE
Make socket hard closure configurable for health check

### ISSUE THREAD

**Issue by keliss** [haproxy/haproxy#560]
Hello everyone.
I'd like to suggest making RST termination of http health check requests optional.
I'm running a pretty old version of HAProxy (1.5.18) but tcpdump output tells me that this behaviour is the same even for newer ones (tried on 1.8.8).
The issue here is that this behaviour causes a lot of "connection reset by peer" exceptions in my app, which leads to performance drop and is definitely not what this optimization was introduced for. So it would be really great to see a new option that allows to disable it.

**Comment by chipitsine** [comment]
RST termination saves ephemeral ports.

if connection is terminated using FIN, it is FIN_WAIT for some time
if connection is terminated using RST, port is free immediately

**Comment by keliss** [comment]
I understand. But this is not a problem usually, because number of "useful" connections is always much greater than number of health check connections. And there is even a possibility to control that time to wait after FIN. In fact, this optimization leaves user no choice, because HAProxy doesn't support any kind of alternative health check over http (like some custom check that would be independent of the usual one)

**Comment by chipitsine** [comment]
You are right.

Except "configurable" FIN_WAIT. It is not. You will run into big mess if you try.

**Comment by keliss** [comment]
Hm, played around with HAProxy 1.8.8 a bit and noticed that it also uses RST to terminate server worker connections, while client connection are terminated gracefully, using FINs. Is this expected? If yes, then is there a way to disable it? Seems really weird that it closes connections this way even though http keep-alive is on and timeout is set to a big enough value. Now I'm starting to think that the root cause of the app level exceptions is actually not only health checks...

**Comment by keliss** [comment]
Here is my config if it helps somehow:
```global
	log 127.0.0.1:514	local0 notice emerg
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	# An alternative list with additional directives can be obtained from
	#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3
	nbproc 1
	cpu-map 1 4

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 1m
        timeout client  1m
        timeout server  1m
	timeout http-keep-alive 1m
	retries 3
	option redispatch
	option forwardfor
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend http
	bind :1078
	default_backend ssp

backend ssp
	option srvtcpka
	option http-keep-alive
	maxconn 5000
	#http-check expect status 200
	#option httpchk GET /status
	#option tcp-check
	server s1 localhost:8123
	default-server inter 1s rise 3 fall 5

listen stats
	bind :1111
	stats enable
        stats uri /stats
        stats auth blabla:blabla```

**Comment by keliss** [comment]
Here is my config if it helps somehow:
```
global
	log 127.0.0.1:514	local0 notice emerg
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	# An alternative list with additional directives can be obtained from
	#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3
	nbproc 1
	cpu-map 1 4

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect  1m
        timeout client  1m
        timeout server  1m
	timeout http-keep-alive 1m
	retries 3
	option redispatch
	option forwardfor
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend http
	bind :1078
	default_backend serv

backend serv
	option srvtcpka
	option http-keep-alive
	maxconn 5000
	#http-check expect status 200
	#option httpchk GET /status
	#option tcp-check
	server s1 localhost:5555
	default-server inter 1s rise 3 fall 5

listen stats
	bind :1111
	stats enable
        stats uri /stats
        stats auth blabla:blabla
```

**Comment by wtarreau** [comment]
It's not weird, it's the ONLY way to do it properly. And this requires some non-trivial stuff! If it was using a FIN to close to the server, as it used to be the case 19 years ago in version 1.0, it would represent a huge security issue as anyone could trivially and instantly DoS it by turning all backend ports to TIME_WAIT for one minute. Haproxy tries hard to make sure the server closes first, but if it needs to unexpectedly close by itself, then it can only use an RST. If that's a problem in your case, better upgrade to 2.0 which reuses connections more extensively, and you will almost never observe this.

**Comment by keliss** [comment]
I see, thank you for clarifying

**Comment by capflam** [comment]
This one can be closed, tagging it as "invalid".
