### ISSUE TITLE
Inconsistent handling of local peer definition in a peers section

### ISSUE THREAD

**Issue by jmagnin** [haproxy/haproxy#565]
## Output of `haproxy -vv` and `uname -a`

```
Linux lhotse 5.5.13-arch1-1 #1 SMP PREEMPT Wed, 25 Mar 2020 16:04:40 +0000 x86_64 GNU/Linux
HA-Proxy version 2.2-dev5-167397-12 2020/03/26 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O0 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1e  17 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1e  17 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression

```

## What's the configuration?

```
peers foopeers
  peer foo 127.0.0.1:12345
  
peers barpeers
  bind *:12346
  server bar

```
neither foo nor bar is the hostname of the machine where haproxy is executed.

## Steps to reproduce the behavior

1. haproxy -c -f ./sample_config.cfg
2. haproxy -db -f ./sample_config.cfg -L bar
3. haproxy -db -f ./sample_config.cfg -L foo

## Actual behavior

1. config check fails to parse the server line in the peers section barpeers.

```
[ALERT] 090/094134 (15692) : parsing [./local_peer.cfg:6] : 'server' expects <name> and <addr>[:<port>] as arguments.
[ALERT] 090/094134 (15692) : Error(s) found in configuration file : ./local_peer.cfg
[ALERT] 090/094134 (15692) : Fatal errors found in configuration.
```
2. config check removes foopeers because we gave -L bar. 
```                                                                                                                                                                                        
[WARNING] 090/094356 (15715) : Removing incomplete section 'peers foopeers' (no peer named 'bar').
Configuration file is valid
```

3. config checks fails to parse the server line in the barpeers peers section. just like in step 1.
## Expected behavior
I would expect haproxy to warn about ignoring both peers sections in 1. and warn that either foopeers or barpeers is invalid in 2. and 3.

## Do you have any idea what may have caused this?
This was introduced with the new peers section syntax around commit c06b5d4f7

## Do you have an idea how to solve the issue?
Not at the moment.

**Comment by wtarreau** [comment]
@haproxyFred you might also be interested by this one :-)

**Comment by haproxyFred** [comment]
In fact the "server" keyword has not the same syntax, depending on the section it is in.
As documented, the address and port are optional for "server" lines in "peers" sections (we must not provide the address and port for the local peer) :

server <peername> [<ip>:<port>] [param*]
  As previously mentioned, "peer" keyword may be replaced by "server" keyword
  with a support for all "server" parameters found in 5.2 paragraph.
  If the underlying peer is local, <ip>:<port> parameters must not be present.
  These parameters must  be provided on a "bind" line (see "bind" keyword
  of this "peers" section).
  Some of these parameters are irrelevant for "peers" sections.

So, the configuration is invalid because of the "server" syntax in "peers" section.

Now if we want to modify this behavior to validate such configurations, what I can do is ignoring the "server" lines without any address and port, in "peers" section, if they are not local, emitting a warning.

**Comment by jmagnin** [comment]
8ba10fea6 fixes the issue. thank you Fred.

**Comment by TimWolla** [comment]
Thanks. I've adjusted the labels.
