### ISSUE TITLE
DNS Resolver and different case in response answer section

### ISSUE THREAD

**Issue by pkxyz** [haproxy/haproxy#566]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.13-1ppa1~xenial 2020/02/15 - https://haproxy.org/
Build options :
TARGET = linux-glibc
CPU = generic
CC = gcc
CFLAGS = -O2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.0.2g 1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g 1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.21 2016-01-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
epoll : pref=300, test result OK
poll : pref=200, test result OK
select : pref=150, test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
h2 : mode=HTX side=FE|BE mux=H2
h2 : mode=HTTP side=FE mux=H2
<default> : mode=HTX side=FE|BE mux=H1
<default> : mode=TCP|HTTP side=FE|BE mux=PASS

Available services :
prometheus-exporter

Available filters :
[SPOE] spoe
[COMP] compression
[CACHE] cache
[TRACE] trace

uname -a
Linux ip-10-202-9-95 4.4.0-1104-aws #115-Ubuntu SMP Mon Mar 2 06:35:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linu
```

## What's the configuration?

```
resolvers bridgedns
parse-resolv-conf
hold valid 10s

listen mqtt_aws
maxconn 40100
bind 127.0.0.1:2884
mode tcp
option srvtcpka
server aws redacted.ats.iot.cn-north-1.amazonaws.com.cn:8883 resolvers bridgedns resolve-prefer ipv4 ssl verify required crt /opt/app/certs/aws-client.pem ca-file /opt/app/certs/aws-ats-ca1.pem
```

## Steps to reproduce the behavior

Use lowercase server host name in conjunction with a BIND DNS server (or use some form of DNS emulator to modify response's answer section). When connections are made and DNS queried, BIND will cache the lowercase host name. Update haproxy config to use uppercase hostname. When connections are made, BIND will use cache entry (case insensitive match) and return the lower case host name in the answer. This will then be handled as if the DNS query failed to resolve host as case of requested hostname and returned hostname do not match producing log warnings.

## Actual behavior

Server host is failed to be resolved and connections fail. Example log entries:

Server mqtt_aws/aws is going DOWN for maintenance (unspecified DNS error). 0 active and 0 backup servers left. 8 sessions active, 0 requeued, 0 remaining in queue.
haproxy[23580]: Server mqtt_aws/aws is going DOWN for maintenance (unspecified DNS error). 0 active and 0 backup servers left. 8 sessions active, 0 requeued, 0 remaining in queue.
haproxy[23577]: [ALERT] 061/144455 (23580) : proxy 'mqtt_aws' has no server available!
haproxy[23580]: Server mqtt_aws/aws is going DOWN for maintenance (unspecified DNS error). 0 active and 0 backup servers left. 8 sessions active, 0 requeued, 0 remaining in queue.

In the below example from tcpdump, the actual names are redacted in the case UPPER (REDACTED-VALUE) or lower (redacted-value) as they appeared in the tested scenario. The IPs used have also been changed.

Can see Request (Frame=29) sent with a Name in uppercase i.e. REDACTED-VALUE.ats.iot.cn-north-1.amazonaws.com.cn
However, Response (Grame=31) is sent with Name in Answer section in lower case i.e.
Answers
redacted.ats.iot.cn-north-1.amazonaws.com.cn: type CNAME, class IN, cname iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn
Name: redacted.ats.iot.cn-north-1.amazonaws.com.cn

HAProxy does not accept this and the following HAProxy trace is seen:

Server mqtt_aws/aws is going DOWN for maintenance (unspecified DNS error). 0 active and 0 backup servers left. 8 sessions active, 0 requeued, 0 remaining in queue.
haproxy[23580]: Server mqtt_aws/aws is going DOWN for maintenance (unspecified DNS error). 0 active and 0 backup servers left. 8 sessions active, 0 requeued, 0 remaining in queue.
haproxy[23577]: [ALERT] 061/144455 (23580) : proxy 'mqtt_aws' has no server available!
haproxy[23580]: Server mqtt_aws/aws is going DOWN for maintenance (unspecified DNS error). 0 active and 0 backup servers left. 8 sessions active, 0 requeued, 0 remaining in queue.

The Request/Response handshake then continues until a timer expiry two seconds later eg Frames: 34/35 to 74/75.

No Time. Source IP. Src Port. Dest IP Dst Port Protocol Length Info
29 14:20:47.584127 1.2.3.4 53766 5.6.7.8 53 DNS 121 Standard query 0xcc5d A REDACTED-VALUE.ats.iot.cn-north-1.amazonaws.com.cn OPT

Frame 29: 121 bytes on wire (968 bits), 121 bytes captured (968 bits)
... ... ... ...
... ... .... ...
... ... .... ...

Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 1.2.3.4, Dst: 5.6.7.8
0100 .... = Version: 4
.... 0101 = Header Length: 20 bytes
Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
0000 00.. = Differentiated Services Codepoint: Default (0)
.... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
Total Length: 107
Identification: 0xe395 (58261)
Flags: 0x02 (Don't Fragment)
0... .... = Reserved bit: Not set
.1.. .... = Don't fragment: Set
..0. .... = More fragments: Not set
Fragment offset: 0
Time to live: 64
Protocol: UDP (17)
Header checksum: 0x1d0a [validation disabled]
[Good: False]
[Bad: False]
Source: 1.2.3.4
Destination: 5.6.7.8
[Source GeoIP: Unknown]
[Destination GeoIP: Unknown]
User Datagram Protocol, Src Port: 53766 (53766), Dst Port: 53 (53)
Source Port: 53766
Destination Port: 53
Length: 87
Checksum: 0x3a4b [validation disabled]
[Good Checksum: False]
[Bad Checksum: False]
[Stream index: 0]
Domain Name System (query)
[Response In: 31]
Transaction ID: 0xcc5d
Flags: 0x0100 Standard query
0... .... .... .... = Response: Message is a query
.000 0... .... .... = Opcode: Standard query (0)
.... ..0. .... .... = Truncated: Message is not truncated
.... ...1 .... .... = Recursion desired: Do query recursively
.... .... .0.. .... = Z: reserved (0)
.... .... ...0 .... = Non-authenticated data: Unacceptable
Questions: 1
Answer RRs: 0
Authority RRs: 0
Additional RRs: 1
Queries
REDACTED-VALUE.ats.iot.cn-north-1.amazonaws.com.cn: type A, class IN
Name: REDACTED-VALUE.ats.iot.cn-north-1.amazonaws.com.cn
[Name Length: 50]
[Label Count: 7]
Type: A (Host Address) (1)
Class: IN (0x0001)
Additional records
<Root>: type OPT
Name: <Root>
Type: OPT (41)
UDP payload size: 512
Higher bits in extended RCODE: 0x00
EDNS0 version: 0
Z: 0x0000
0... .... .... .... = DO bit: Cannot handle DNSSEC security RRs
.000 0000 0000 0000 = Reserved: 0x0000
Data length: 0

No Time. Source IP. Src Port. Dest IP Dst Port Protocol Length Info
31 14:20:47.584588 5.6.7.8 53 1.2.3.4 53766 DNS 240 Standard query response 0xcc5d A REDACTED.ats.iot.cn-north-1.amazonaws.com.cn CNAME iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn A 11.33.55.77 A 22.44.66.88 OPT

Frame 31: 240 bytes on wire (1920 bits), 240 bytes captured (1920 bits)
... ... ... ...
... ... .... ...
... ... .... ...
Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 5.6.7.8, Dst: 1.2.3.4
0100 .... = Version: 4
.... 0101 = Header Length: 20 bytes
Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
0000 00.. = Differentiated Services Codepoint: Default (0)
.... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
Total Length: 226
Identification: 0x5268 (21096)
Flags: 0x00
0... .... = Reserved bit: Not set
.0.. .... = Don't fragment: Not set
..0. .... = More fragments: Not set
Fragment offset: 0
Time to live: 64
Protocol: UDP (17)
Header checksum: 0xedc0 [validation disabled]
[Good: False]
[Bad: False]
Source: 5.6.7.8
Destination: 1.2.3.4
[Source GeoIP: Unknown]
[Destination GeoIP: Unknown]
User Datagram Protocol, Src Port: 53 (53), Dst Port: 53766 (53766)
Source Port: 53
Destination Port: 53766
Length: 206
Checksum: 0x0f63 [validation disabled]
[Good Checksum: False]
[Bad Checksum: False]
[Stream index: 0]
Domain Name System (response)
[Request In: 29]
[Time: 0.000461000 seconds]
Transaction ID: 0xcc5d
Flags: 0x8180 Standard query response, No error
1... .... .... .... = Response: Message is a response
.000 0... .... .... = Opcode: Standard query (0)
.... .0.. .... .... = Authoritative: Server is not an authority for domain
.... ..0. .... .... = Truncated: Message is not truncated
.... ...1 .... .... = Recursion desired: Do query recursively
.... .... 1... .... = Recursion available: Server can do recursive queries
.... .... .0.. .... = Z: reserved (0)
.... .... ..0. .... = Answer authenticated: Answer/authority portion was not authenticated by the server
.... .... ...0 .... = Non-authenticated data: Unacceptable
.... .... .... 0000 = Reply code: No error (0)
Questions: 1
Answer RRs: 3
Authority RRs: 0
Additional RRs: 1
Queries
REDACTED.ats.iot.cn-north-1.amazonaws.com.cn: type A, class IN
Name: REDACTED.ats.iot.cn-north-1.amazonaws.com.cn
[Name Length: 50]
[Label Count: 7]
Type: A (Host Address) (1)
Class: IN (0x0001)
Answers
redacted.ats.iot.cn-north-1.amazonaws.com.cn: type CNAME, class IN, cname iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn
Name: redacted.ats.iot.cn-north-1.amazonaws.com.cn
Type: CNAME (Canonical NAME for an alias) (5)
Class: IN (0x0001)
Time to live: 4
Data length: 60
CNAME: iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn
iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn: type A, class IN, addr 11.33.55.77
Name: iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn
Type: A (Host Address) (1)
Class: IN (0x0001)
Time to live: 53
Data length: 4
Address: 11.33.55.77
iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn: type A, class IN, addr 22.44.66.88
Name: iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn
Type: A (Host Address) (1)
Class: IN (0x0001)
Time to live: 53
Data length: 4
Address: 22.44.66.88
Additional records
<Root>: type OPT
Name: <Root>
Type: OPT (41)
UDP payload size: 4096
Higher bits in extended RCODE: 0x00
EDNS0 version: 0
Z: 0x0000
0... .... .... .... = DO bit: Cannot handle DNSSEC security RRs
.000 0000 0000 0000 = Reserved: 0x0000
Data length: 0

No Time. Source IP. Src Port. Dest IP Dst Port Protocol Length Info
34 14:20:47.585410 1.2.3.4 53766 5.6.7.8 53 DNS 121 Standard query 0xcc5d A REDACTED-VALUE.ats.iot.cn-north-1.amazonaws.com.cn OPT

No Time. Source IP. Src Port. Dest IP Dst Port Protocol Length Info
35 14:20:47.585799 5.6.7.8 53 1.2.3.4 53766 DNS 240 Standard query response 0xcc5d A REDACTED.ats.iot.cn-north-1.amazonaws.com.cn CNAME iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn A 11.33.55.77 A 22.44.66.88 OPT

... ... ... ...
... ... ... ...
... ... ... ...

No Time. Source IP. Src Port. Dest IP Dst Port Protocol Length Info
74 14:20:49.588521 1.2.3.4 53766 5.6.7.8 53 DNS 121 Standard query 0xcc5d A REDACTED-VALUE.ats.iot.cn-north-1.amazonaws.com.cn OPT

No Time. Source IP. Src Port. Dest IP Dst Port Protocol Length Info
75 14:20:49.585906 5.6.7.8 53 1.2.3.4 53766 DNS 240 Standard query response 0xcc5d A REDACTED.ats.iot.cn-north-1.amazonaws.com.cn CNAME iotmoonraker-c-elb-also-redacted.cn-north-1.elb.amazonaws.com.cn A 11.33.55.77 A 22.44.66.88 OPT

## Expected behavior

Based on RFC 2035 (https://tools.ietf.org/html/rfc1035) section 2.3.3, a different case is allowable in the response's answer section (but has to be same case as original in question section) and therefore the IP should be resolved.

## Do you have any idea what may have caused this?

BIND DNS can return a different case host name in response's answer section e.g. if uses cache entry for same host but different case:

https://indico.dns-oarc.net/event/20/contributions/265/attachments/254/471/ISC-case-sensitivity.pdf

## Do you have an idea how to solve the issue?
Allow different case for hostname in DNS query response's answer section.

**Comment by wtarreau** [comment]
Thanks for your detailed report. I suspect the code lies in one of the few strcmp() calls in dns.c though I don't know this code enough to have an authoritative opinion. @bedis what do you think ? I'll attempt some maintenance releases for tomorrow, if you think you can have a trivial fix by then we might merge it in time.

**Comment by cognet** [comment]
I think my commit should fix it.

**Comment by TimWolla** [comment]
@cognet Please see this mailing list response from Baptiste: https://www.mail-archive.com/haproxy@formilux.org/msg29529.html `Message-ID: <CAODHi7pJy0taFyavSXYeMOU-hvnhZwFdMJPzAdekdm2K-KvuVw@mail.gmail.com>`

**Comment by cognet** [comment]
I'm not sure I agree with that, and since it's so easy to support it, why not ?

**Comment by wtarreau** [comment]
Interesting. I didn't remember about that thread. However I'm seeing that participants were talking past each other. The response from the (apparently authoritative) guy was that the QUESTION must match but the response doesn't need to, and this didn't seem to be reflected in the conversation linked to above where it went simplified as "OK we must match". I'd argue that someone needs to read the RFC (1035 IIRC but I'm getting old and could be wrong) carefully and do at least what is documented as MUST and make sure we are compatible with others' MAY. Imitating others is not sufficient for interoperability.

**Comment by TimWolla** [comment]
> I'm not sure I agree with that, and since it's so easy to support it, why not ?

Baptiste is listed as the DNS maintainer in MAINTAINERS and my understanding is that he explicitely refused changing this back then.

On the why not: [draft-vixie-dnsext-dns0x20-00](https://tools.ietf.org/html/draft-vixie-dnsext-dns0x20-00#section-2.2). Verifying the case is intended as a security feature against DNS response spoofing, because it increases the entropy of the responses.

**Comment by wtarreau** [comment]
This is exactly what I was talking about: here it mentions the QUESTION section, not the ANSWER. And my lecture of the thread above indicates there seems to be a confusion between the two. The problem reported here in this issue is about the answer's case not matching the question's. So I think this needs to be carefully rechecked. And it's likely that Olivier's patch is a bit too lax on this. Let's wait for Baptiste to have a look, carefully considering the difference between these two parts (something that was overlooked in the old thread two years ago).

**Comment by bedis** [comment]
Hi there,

so RFC1035 is a bit outdated and there is a new RFC dedicated to character case in DNS: https://tools.ietf.org/html/rfc4343

It clearly states that the case matching should be insensitive but that the server should also try to match the QUERY part.
Quick try:
```
host WwW.HaPrOxY.oRg
WwW.HaPrOxY.oRg has address 51.15.8.218
```

Before relaxing this, @pkxyz , can you tell me how you managed to arrive in a situation where HAProxy could not match queries or records because of case issue?
Seams like usually, everyone uses lowercase in DNS.

**Comment by pkxyz** [comment]
Hi @bedis - we believe this situation occurred when the dns entry for the host was entered incorrectly by the host service provider (e.g. upper case for one or more characters). This was then cached by the BIND server, so even gave us HAProxy connection errors even though we believe the DNS entry error was spotted and corrected, until we cleared the BIND cache.

Thanks all for looking at this.

**Comment by wtarreau** [comment]
@bedis what's the status of this one ? Can we close it or is there anything left to be done ?

**Comment by capflam** [comment]
The provided fix was never backported anywhere while it is marked to be backported as far as 1.8. @bedis, should we close the issue and leave old versions intact or should we backport the fix ?

**Comment by capflam** [comment]
@bedis ping ?

**Comment by capflam** [comment]
Finally backported as far as 1.8. I'm closing this issue now.
