### ISSUE TITLE
h2spec fails on current master

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#569]
run test many times on my local computer

```
Hypertext Transfer Protocol Version 2 (HTTP/2)
  7. Error Codes
    × 1: Sends a GOAWAY frame with unknown error code
      -> The endpoint MUST NOT trigger any special behavior.
         Expected: Connection closed
                   PING Frame (length:8, flags:0x01, stream_id:0, opaque_data:h2spec)
           Actual: Error: read tcp 127.0.0.1:48674->127.0.0.1:8443: read: connection reset by peer

Finished in 0.5491 seconds
```

**Comment by wtarreau** [comment]
I can't seem to reproduce it, here's what I'm getting for this one:

willy@wtap:haproxy$ h2/tools/h2spec -Svtk -h 127.0.0.1 -p 4443 http2/7
Hypertext Transfer Protocol Version 2 (HTTP/2)
  7. Error Codes
         [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
         [recv] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
         [send] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
         [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
         [send] GOAWAY Frame (length:8, flags:0x00, stream_id:0)
         [recv] Connection closed
    â 1: Sends a GOAWAY frame with unknown error code
         [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
         [recv] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
         [send] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
         [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
         [send] HEADERS Frame (length:15, flags:0x04, stream_id:1)
         [send] RST_STREAM Frame (length:4, flags:0x00, stream_id:1)
         [send] PING Frame (length:8, flags:0x00, stream_id:0)
         [recv] PING Frame (length:8, flags:0x01, stream_id:0)
    â 2: Sends a RST_STREAM frame with unknown error code

Tried in clear and TLS. It's probably another corner case depending on a minor config option or race condition :-/

**Comment by chipitsine** [comment]
I use steps and config from here https://github.com/haproxy/haproxy/blob/master/.github/workflows/h2spec.yml

**Comment by wtarreau** [comment]
Thanks, the difference is the h2spec version. I've updated it and get the same as yours now. However I'm suspecting the issue is in h2spec, which sends a PING *after* we've closed, so the TCP stack responds with a reset and it doesn't expect this one as part of a valid close.

**Comment by wtarreau** [comment]
And that's it indeed. Just running haproxy through strace adds enough latency to make the issue disappear :-/

**Comment by chipitsine** [comment]
I do not understand what do you mean, but my experience says that if it depends on latency, it looks like race condition :)


I will try to figure out if I will have time

**Comment by chipitsine** [comment]
I started this investigation because of https://github.com/haproxy/haproxy/runs/550469707?check_suite_focus=true

however, on my local run I see another failures than in github CI

**Comment by wtarreau** [comment]
The problem is that h2spec expects a close but sends data (PING) after the operation which is supposed to provoke this close. The close indeed happened, but the fact that it sent extra data after the close caused the TCP stack to produce a reset, which is detected as "connection reset by peer".
