### ISSUE TITLE
HAproxy LB to NGINX Ingress - SSL not working?

### ISSUE THREAD

**Issue by robotica72** [haproxy/haproxy#571]
HAproxy -vv Output:
HA-Proxy version 2.1.4 2020/04/02 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.33 2019-04-16
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [TRACE] trace
        [COMP] compression

## What's the configuration?

HAproxy is the front end LB to a K8s cluster using NGINX Ingress.  NGINX works fine by itself, working on both 80 and 443.  When I use the HAproxy IP, HTTP works but all HTTPS attempts fail.  A Curl replies with : curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.

NGINX is using the self-generated fake certificate.  (This is the only thing I can think of causing the issue??)

The NGINX log has odd error logs from the attempt:
172.17.0.9 - - [04/Apr/2020:02:29:24 +0000] "\x16\x03\x01\x00\xF2\x01\x00\x00\xEE\x03\x03^\x87\xF1\xDE\x0E!\xCF\xF3\xA3\x5C\xF6eT=#~\xA5\x0BX%z1\xB2\xB8\xAF\xA1\xA4!\xA5b{\xFE\x00\x00l\xC0+\xC0,\xC0\x86\xC0\x87\xC0\x09\xC0#\xC0" 400 157 "-" "-" 0 0.010 [] [] - - - - 3ceb9ac31d0d3f11bdc2087a5966b77a

## Steps to reproduce the behavior
Run an HAproxy using the config file below to a base NGINX Ingress controller.

haproxy.cfg:
global
  log /dev/log local0
  log /dev/log local1 notice
  daemon

defaults
  log global
  mode tcp
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000

frontend workers-https
  bind *:443
  default_backend ingress-nodes-https
  bind *:80
  default_backend ingress-nodes-http

backend ingress-nodes-http
  option httpchk GET /healthz
  server cluster01-worker worker1:80 check verify none
  server cluster01-worker2 worker2:80 check verify none
  server cluster01-worker3 worker3:80 check verify none

backend ingress-nodes-https
  option httpchk GET /healthz
  server cluster01-worker worker1:443 check ssl verify none
  server cluster01-worker2 worker2:443 check ssl verify none
  server cluster01-worker3 worker3:443 check ssl verify none

Describe what you would like HAProxy to do differently.

LB HTTPS traffic to NGINX Ingress

## Do you have any idea what may have caused this?

Only idea is the NGINX Fake certificate?

Any ideas on how I can get this config to run correctly?

**Comment by jmagnin** [comment]
This is a configuration issue. You should use the mailing list, discourse, or other documented support channels for such things.

Please do not use the issue tracker for support questions. This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.
