### ISSUE TITLE
src/h2.c: null pointer dereference found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#572]
```
682        if (!(*msgf & H2_MSGF_BODY) || ((*msgf & H2_MSGF_BODY_CL) && *body_len == 0))
683                sl_flags |= HTX_SL_F_BODYLESS;
684
685        /* update the start line with last detected header info */
   CID 1399818 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)26. var_deref_op: Dereferencing null pointer sl.
686        sl->flags |= sl_flags;
687
688        if ((*msgf & (H2_MSGF_BODY|H2_MSGF_BODY_TUNNEL|H2_MSGF_BODY_CL)) == H2_MSGF_BODY) {
689                /* FIXME: Do we need to signal anything when we have a body and
690                 * no content-length, to have the equivalent of H1's chunked
691                 * encoding?
692                 */
693        }
```

**Comment by chipitsine** [comment]
another finding in the same file

```
448        /* update the start line with last detected header info */
   CID 1399804 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)26. var_deref_op: Dereferencing null pointer sl.
449        sl->flags |= sl_flags;
450
451        /* complete with missing Host if needed */
452        if ((fields & (H2_PHDR_FND_HOST|H2_PHDR_FND_AUTH)) == H2_PHDR_FND_AUTH) {
453                /* missing Host field, use :authority instead */
454                if (!htx_add_header(htx, ist("host"), phdr_val[H2_PHDR_IDX_AUTH]))
455                        goto fail;
456        }
```

**Comment by chipitsine** [comment]
what if put comparision out of "if"


```diff
--- a/src/h2.c
+++ b/src/h2.c
@@ -675,10 +675,11 @@ int h2_make_htx_response(struct http_hdr *list, struct htx *htx, unsigned int *m
        /* Let's dump the request now if not yet emitted. */
        if (!(fields & H2_PHDR_FND_NONE)) {
                sl = h2_prepare_htx_stsline(fields, phdr_val, htx, msgf);
-               if (!sl)
-                       goto fail;
        }
 
+       if (!sl)
+               goto fail;
+
        if (!(*msgf & H2_MSGF_BODY) || ((*msgf & H2_MSGF_BODY_CL) && *body_len == 0))
                sl_flags |= HTX_SL_F_BODYLESS;

```

**Comment by wtarreau** [comment]
On this one Coverity is wrong. I'm a bit surprised since it seems to correctly figure some trickier ones.

- <tt>fields</tt> starts at zero
- when reaching this line, if <tt>fields</tt> doesn't have  <tt>H2_PHDR_FND_NONE</tt>, <tt>sl</tt> is set and checked
- the flag above is only set after assigning <tt>sl</tt> and testing it to be valid.
=> there's no single case where we can reach the next line after that "if" block with a NULL <tt>sl</tt>.

Thus for me it's a false-positive.

**Comment by chipitsine** [comment]
I will mark as false positive

**Comment by chipitsine** [comment]
@wtarreau , do you mind to have a look at clang scan-build report ?

it looks similar to coverity, and it provides possible flow when `sl` is null derefenced

http://chipitsine.github.io/haproxy/report-2f0083.html#EndPath

**Comment by wtarreau** [comment]
Well, it's totally amazing:
  - at step 9 it assumes that FND_NONE is NOT present,
  - at step 10 it continues with this flag not set,
  - at 11 & 12 is breaks out of the loop,
  - and at step 15 it suddently changed its mind and decided that
    the flag is now set.

This even made me recheck the constants to be sure there wasn't
an error with the flags, but on, H2_PHDR_FNX_NONE is defined as
(1 << 0) so the code is right and *both* checkers are utterly
wrong.

It looks as if they didn't retain the assumptions they make all
along the code, that's quite strange :-/

Willy

**Comment by wtarreau** [comment]
Note, when closing such bugs it would be nice to tag them as invalid,
because if the authors of these checkers are ever interested in seeing
cases where their tools fail, it would help us extract these examples
to help them improve.

**Comment by chipitsine** [comment]
I hope that coverity learns issues marked ad false positive.


Thank you!
