### ISSUE TITLE
server-state application failed for server 'x/y', invalid srv_admin_state value '32'

### ISSUE THREAD

**Issue by PiBa-NL** [haproxy/haproxy#576]
## Output of `haproxy -vv` and `uname -a`

```
haproxy -vv
HA-Proxy version 2.2-dev5-c3500c3 2020/03/25 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -pipe -g -fstack-protector -fno-strict-aliasing -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -fno-strict-overflow -Wno-null-dereference -Wno-unused-label -Wno-unused-parameter -Wno-sign-compare -Wno-ignored-qualifiers -Wno-unused-command-line-argument -Wno-missing-field-initializers -Wno-address-of-packed-member -DFREEBSD_PORTS -DFREEBSD_PORTS
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_STATIC_PCRE=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ACCEPT4=1 USE_ZLIB=1

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE +STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H +GETADDRINFO +OPENSSL +LUA -FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-freebsd  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2o-freebsd  27 Mar 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.4
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE version : 8.40 2017-01-11
Running on PCRE version : 8.40 2017-01-11
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [TRACE] trace
        [COMP] compression

uname -a
FreeBSD pfsense_3.itm.local 11.2-RELEASE-p6 FreeBSD 11.2-RELEASE-p6 #3 518496b29ae(RELENG_2_4_4): Wed Dec 12 07:41:44 EST 2018     root@buildbot2.nyi.netgate.com:/build/ce-crossbuild-244/obj/amd64/ZfGpH5cd/build/ce-crossbuild-244/pfSense/tmp/FreeBSD-src/sys/pfSense  amd64

```

## What's the configuration?

```
## a cut down config snippet (i hope still works..):
global
	stats socket /tmp/haproxy.socket level admin  expose-fd listeners
	server-state-file /tmp/haproxy_server_state
defaults	
	load-server-state-from-file global
resolvers globalresolvers
	nameserver localdns 127.0.0.1:53
	resolve_retries 3
	timeout retry 1s
	hold valid 10s
frontend website
	bind			:80 
	use_backend x if FALSE
	use_backend x2 if FALSE
backend x
	server            y AppSrv:8084 id 161 check inter 10000  weight 1 resolvers globalresolvers
backend x2
	server-template    z 3 smtp.company.tld:25 id 167 check inter 10000  weight 10 resolvers globalresolvers 
```

## Steps to reproduce the behavior

1. make sure haproxy is running and marking the server and 3rd servertemplate as 'down' due to failed resolution
2. save state-file of the socket command "show servers state"
3. perform a 'seamless reload' of haproxy

## Actual behavior

Using 2.2-dev5-c3500c3, I've got both a server and a servertemplate/server that are marked 'down' due to dns not replying with (enough) records. That by itself is alright..
But when i perform a 'seemless reload' with a serverstates file it causes the warnings below for both server and template.: 
```
[WARNING] 095/150909 (74796) : server-state application failed for server 'x/y', invalid srv_admin_state value '32'
[WARNING] 095/150909 (74796) : server-state application failed for server 'x2/z3', invalid srv_admin_state value '32' 
```

## Expected behavior
no warnings should be logged about invalid states in the state-file, either the value 32 should not be written there, or when reading the file back it should get processed as a valid state.

## Do you have any idea what may have caused this?
nope.

## Do you have an idea how to solve the issue?
nope.

## Other known affected versions:
@bedis could reproduce the issue on haproxy 1.8(.25?) as well.

## Link to discourse/mailthread where the issue was discussed:
https://www.mail-archive.com/haproxy@formilux.org/msg36916.html

**Comment by gabrieltz** [comment]
I am having the same issue with 2.0.20 . 
This also occurs with 1.9.2, 2.0.8, 2.0.9, 2.0.15 ( i had old compiled binaries to test against )
The reason is that when using `server-template srvname 10 .....resolvers ... ` in a backend and the resolver ( consul for us )
returns less than 10 SRV records due to autoscaling, some of the automatically generated server entries have no ip address
therefore the srv_admin_state is 32  ( or 0x20 = SRV_ADMF_RMAINT  as stated in https://cbonte.github.io/haproxy-dconv/2.0/management.html ) . 
Of course you have to be using the load-server-state-from-file and server-state-file as indicated above by @PiBa-NL .
I have worked around this issue by adding `load-server-state-from-file none` in the backend section of non-critical backends

**Comment by capflam** [comment]
When a server-state is loaded, some "inherited" statues are removed from `srv_admin_state` parameter. `SRV_ADMF_IDRAIN`, `SRV_ADMF_IMAINT` and `SRV_ADMF_HMAINT` are thus removed. In fact the last one is not inherited but set from the CLI. So I guess we should also remove `SRV_ADMF_RMAINT`. This means we only consider `SRV_ADMF_FMAINT`, `SRV_ADMF_CMAINT` and `SRV_ADMF_FDRAIN` as valid states, i.e. the "static" states.

You may try to apply this quick patch on top of the 2.0.20 to confirm it works as you expected:

```diff
diff --git a/src/server.c b/src/server.c
index 1b123fb22..1e04e63ca 100644
--- a/src/server.c
+++ b/src/server.c
@@ -2918,7 +2918,7 @@ static void srv_update_state(struct server *srv, int version, char **params)
                        /* inherited statuses will be recomputed later.
                         * Also disable SRV_ADMF_HMAINT flag (set from stats socket fqdn).
                         */
-                       srv_admin_state &= ~SRV_ADMF_IDRAIN & ~SRV_ADMF_IMAINT & ~SRV_ADMF_HMAINT;
+                       srv_admin_state &= ~SRV_ADMF_IDRAIN & ~SRV_ADMF_IMAINT & ~SRV_ADMF_HMAINT & ~SRV_ADMF_RMAINT;
 
                        if ((p == params[2]) || errno == EINVAL || errno == ERANGE ||
                            (srv_admin_state != 0 &&
```
[0001-BUG-MINOR-server-Remove-RMAINT-from-admin-state-when.patch-v2.0.txt](https://github.com/haproxy/haproxy/files/5973117/0001-BUG-MINOR-server-Remove-RMAINT-from-admin-state-when.patch-v2.0.txt)

**Comment by gabrieltz** [comment]
thank you @capflam , the patch worked as expected. 
Instead of getting 
`[WARNING] 045/092901 (3209) : server-state application failed for server 'backend/srv4', invalid srv_admin_state value '32'`
I'm getting
`[WARNING] 045/093025 (3915) : Server backend/srv4 is DOWN, changed from server-state after a reload. 10 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.`

**Comment by capflam** [comment]
Thanks @gabrieltz. This last message is indeed expected because the server is reported as down in the server-state file. I will push the fix soon.

**Comment by gabrieltz** [comment]
@capflam , I'm sorry to bother you again,  I have a strange behaviour i didn't have before this patch.
Something appears to be broken when i try to reload haproxy through systemctl reload haproxy.

While running haproxy -f /etc/haproxy/haproxy.cfg -c produces no errors , when i reload however, the configuration does not change and there is the following line in journalctl -u haproxy
```
[ALERT] 052/155024 (29036) : config: backend 'rpc-proxy-blue-bk-end': server 'rpcproxybluesrv5' has neither service port nor check port nor tcp_check rule 'connect'  with port information.
```

backend configuration: 
```
backend rpc-proxy-blue-bk-end
        mode http
        option httpclose
        option httpchk GET /status HTTP/1.0\r\n
        server-template rpcproxybluesrv 5 _rpc-proxy-blue._tcp.service.heraklion.consul resolvers consul check observe layer4 maxconn 50
```

consul resolver returns 4 active SRV entries but the server-state-file has the normal 4 lines for each, but the fifth is entry
is wrong having the same ip as the fourth server but no hostname.

server-state-file:
```
33 rpc-proxy-blue-bk-end 1 rpcproxybluesrv1 10.5.5.112 2 0 1 1 886530 15 3 4 6 0 0 0 0a050570.addr.heraklion.consul 8701 _rpc-proxy-blue._tcp.service.heraklion.consul
33 rpc-proxy-blue-bk-end 2 rpcproxybluesrv2 10.5.5.111 2 0 1 1 2002821 15 3 4 6 0 0 0 0a05056f.addr.heraklion.consul 8701 _rpc-proxy-blue._tcp.service.heraklion.consul
33 rpc-proxy-blue-bk-end 3 rpcproxybluesrv3 10.5.5.96 2 0 1 1 2341910 15 3 4 6 0 0 0 0a050560.addr.heraklion.consul 8701 _rpc-proxy-blue._tcp.service.heraklion.consul
33 rpc-proxy-blue-bk-end 4 rpcproxybluesrv4 10.5.5.99 2 64 1 1 707 15 3 4 6 0 0 0 0a050563.addr.heraklion.consul 8701 _rpc-proxy-blue._tcp.service.heraklion.consul
33 rpc-proxy-blue-bk-end 5 rpcproxybluesrv5 10.5.5.99 2 0 1 1 962 15 3 4 6 0 0 0 - 8701 _rpc-proxy-blue._tcp.service.heraklion.consul
```

here is an entry from a non-patched haproxy running an old 2.0.8 version with almost the same configuration. You'll nbtice there is no ip address as it should.
```
14 rpc-proxy-blue 5 rpcproxybluesrv5 - 0 0 1 1 9490554 5 2 0 6 0 0 0 - 8701 _rpc-proxy-blue._tcp.service.consul
```

my systemd service file is identical to the one in contrib/systemd/ with the addition of 
`ExecReload=/bin/bash -c "/usr/bin/socat /run/haproxy/admin.sock - <<< 'show servers state' > /etc/haproxy/state/current"`
before the other two ExecReload entries

Update: I forgot to add that this does not happen to every backend using server-template

**Comment by capflam** [comment]
I'm able to reproduce the bug. For me, there is a problem with the resolvers here. But I must check this point with @bedis first. I'm just surprised to see the 5th server has still an IP address and a port while it does not resolve.

**Comment by gabrieltz** [comment]
I was unable to reproduce using a fraction of my configs on a small server , but this occured on 3 out of my 6 haproxy servers 
which led me to revert to the original 2.0.20 version. i had to remove the state file and start clean to resolve the issue.
I think it's impossible for consul to return a duplicate IP since all my services run on distinct hosts.

and by the way , thank you all for this awesome balancer :)

**Comment by capflam** [comment]
I pushed some fixes that should solve this issue. Not backported yet however. Here is the list. Only the last 3 patches are applicable to the 2.0.

* a331a1e8e BUG/MINOR: resolvers: Only renew TTL for SRV records with an additional record
* b4badf720 BUG/MINOR: resolvers: new callback to properly handle SRV record errors
* 52d4d3010 BUG/MEDIUM: resolvers: Reset server address and port for obselete SRV records
* d127ffa9f BUG/MEDIUM: resolvers: Reset address for unresolved servers

**Comment by gabrieltz** [comment]
thank you @capflam i'll patch one node tomorrow, test the patches out, and report back

**Comment by gabrieltz** [comment]
I'm sorry, I know i promised to test today but the first 3 patches refer to files that don't exist in haproxy 2.0.20 and the fourth is off by ~150 lines and i may break something :) . I would rather test when they're backported since i'm testing in production environment.
Thank you again

**Comment by capflam** [comment]
Don't be sorry, it is really not obvious to backport patches. Here is the 4 patches adapted to the 2.0 (including the patch about RMAINT):

[0001-BUG-MINOR-server-Remove-RMAINT-from-admin-state-when.patch.txt](https://github.com/haproxy/haproxy/files/6048892/0001-BUG-MINOR-server-Remove-RMAINT-from-admin-state-when.patch.txt)
[0002-BUG-MINOR-resolvers-new-callback-to-properly-handle-.patch.txt](https://github.com/haproxy/haproxy/files/6048893/0002-BUG-MINOR-resolvers-new-callback-to-properly-handle-.patch.txt)
[0003-BUG-MEDIUM-resolvers-Reset-server-address-and-port-f.patch.txt](https://github.com/haproxy/haproxy/files/6048895/0003-BUG-MEDIUM-resolvers-Reset-server-address-and-port-f.patch.txt)
[0004-BUG-MEDIUM-resolvers-Reset-address-for-unresolved-se.patch.txt](https://github.com/haproxy/haproxy/files/6048896/0004-BUG-MEDIUM-resolvers-Reset-address-for-unresolved-se.patch.txt)

**Comment by capflam** [comment]
Now backported as far as 2.0.

**Comment by gabrieltz** [comment]
hello @capflam, i patched my main 3 balancers with all 4 patches you sent me , it's been 3 days since and I had no issues with either the server state file or the dns entries when dynamic scaling with server templates. 

thank you

**Comment by capflam** [comment]
Good ! Thanks for the feedback !
