### ISSUE TITLE
Url decode function bug 

### ISSUE THREAD

**Issue by senioi** [haproxy/haproxy#585]
test haproxy version: 1.8 1.9 2.0 .21

test URL:
http://www.test.com/testing!%20Just.%20Testpicking.%20[41.34+].zip

haproxy url_dec function:
http://www.test.com/testing! Just. Testpicking. **[41.34 ]**.zip

correct:
http://www.test.com/testing! Just. testpicking. **[41.34+]**.zip

> System: ubuntu 18

> ------------------------------------------------------------------------------

> HA-Proxy version 2.1.4-e3d2d4f 2020/04/09 - https://haproxy.org/
> Status: stable branch - will stop receiving fixes around Q1 2021.
> Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html
> Build options :
>   TARGET  = linux-glibc
>   CPU     = native
>   CC      = gcc
>   CFLAGS  = -m64 -march=x86-64 -O2 -march=native -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
>   OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_REGPARM=1 USE_STATIC_PCRE=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ACCEPT4=1
> USE_TFO=1 USE_SYSTEMD=1
> 
> Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM +STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS
> 
> Default settings :
>   bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
> 
> Built with multi-threading support (MAX_THREADS=64, default=1).
> Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
> Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
> OpenSSL library supports TLS extensions : yes
> OpenSSL library supports SNI : yes
> OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
> Built with Lua version : Lua 5.3.5
> Built with network namespace support.
> Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
> Built with PCRE version : 8.44 2020-02-12
> Running on PCRE version : 8.44 2020-02-12
> PCRE library supports JIT : yes
> Encrypted password support via crypt(3): yes
> Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
> Compression algorithms supported : identity("identity")
> 
> Available polling systems :
>       epoll : pref=300,  test result OK
>        poll : pref=200,  test result OK
>      select : pref=150,  test result OK
> Total: 3 (3 usable), will use epoll.
> 
> Available multiplexer protocols :
> (protocols marked as <default> cannot be specified using 'proto' keyword)
>               h2 : mode=HTTP       side=FE|BE     mux=H2
>             fcgi : mode=HTTP       side=BE        mux=FCGI
>        <default> : mode=HTTP       side=FE|BE     mux=H1
>        <default> : mode=TCP        side=FE|BE     mux=PASS
> 
> Available services : none
> 
> Available filters :
>         [SPOE] spoe
>         [CACHE] cache
>         [FCGI] fcgi-app
>         [TRACE] trace
>         [COMP] compression

**Comment by lukastribus** [comment]
You are supposed to fill out the template, not ignore everything there. Please go back to the template and fill it out completely.

**Comment by wtarreau** [comment]
@lukastribus I think the reporter here wanted to mention that we ought not to transcode the '+' into a space in the path part of the URL. I've done this in the commit above. I'm marking it for backport now.

**Comment by capflam** [comment]
No critical enough to be backported to 1.7 and 1.6. I close the issue keeping labels for the reference.
