### ISSUE TITLE
HAPRoxy fails to resolve servers - DNS resolution failure behaviour

### ISSUE THREAD

**Issue by guptajiten** [haproxy/haproxy#591]
We did some chaos monkey tests in our kubernetes environment:
1. delete the existing haproxy pods and see if its still connecting back to servers.
what we have observed that sometimes haproxy fails to find the servers but sometimes it resolves correctly.
- we have taken a tcp dump, and it looks like haproxy is sending dns queries but in bad case from localhost.
- what we have observed in bad case is - the DNS lookup requests are coming from the localhost/loopback interface (NIC) instead of the connected interface (NIC).  This means the requests may never make it to the DNS server.

below are some information
==================BAD CASE=============================
Resolvers section k8s
 nameserver dns1:
  sent:        51
  snd_error:   0
  valid:       0
  update:      0
  cname:       0
  cname_error: 0
  any_err:     0
  nx:          0
  timeout:     0
  refused:     0
  other:       0
  invalid:     0
  too_big:     0
  truncated:   0
  outdated:    0
Nbthread: 64
Nbproc: 1
Process_num: 1
Pid: 6
Uptime: 0d 0h01m18s
Uptime_sec: 78
Memmax_MB: 0
PoolAlloc_MB: 2
PoolUsed_MB: 2
PoolFailed: 0
Ulimit-n: 1048575
Maxsock: 1048575
Maxconn: 524169
Hard_maxconn: 524169
CurrConns: 98
CumConns: 211
CumReq: 19
MaxSslConns: 0
CurrSslConns: 0
CumSslConns: 0
Maxpipes: 0
PipesUsed: 0
PipesFree: 0
ConnRate: 83
ConnRateLimit: 0
MaxConnRate: 51
SessRate: 83
SessRateLimit: 0
MaxSessRate: 51
SslRate: 0
SslRateLimit: 0
MaxSslRate: 0
SslFrontendKeyRate: 0
SslFrontendMaxKeyRate: 0
SslFrontendSessionReuse_pct: 0
SslBackendKeyRate: 0
SslBackendMaxKeyRate: 0
SslCacheLookups: 0
SslCacheMisses: 0
CompressBpsIn: 0
CompressBpsOut: 0
CompressBpsRateLim: 0
ZlibMemUsage: 0
MaxZlibMemUsage: 0
Tasks: 320
Run_queue: 1
Idle_pct: 100
node: haproxy-grpc-xxxxxx
Stopping: 0
Jobs: 104
Unstoppable Jobs: 0
Listeners: 5
ActivePeers: 0
ConnectedPeers: 0
DroppedLogs: 0
BusyPolling: 0
FailedResolutions: 0
TotalBytesOut: 9695

=============GOOD CASE================
Resolvers section k8s
 nameserver dns1:
  sent:        302
  snd_error:   0
  valid:       301
  update:      5
  cname:       0
  cname_error: 0
  any_err:     0
  nx:          0
  timeout:     0
  refused:     0
  other:       0
  invalid:     0
  too_big:     0
  truncated:   0
  outdated:    1
Nbthread: 64
Nbproc: 1
Process_num: 1
Pid: 6
Uptime: 0d 0h00m58s
Uptime_sec: 58
Memmax_MB: 0
PoolAlloc_MB: 2
PoolUsed_MB: 2
PoolFailed: 0
Ulimit-n: 1048575
Maxsock: 1048575
Maxconn: 524169
Hard_maxconn: 524169
CurrConns: 97
CumConns: 110
CumReq: 14
MaxSslConns: 0
CurrSslConns: 0
CumSslConns: 0
Maxpipes: 0
PipesUsed: 0
PipesFree: 0
ConnRate: 1
ConnRateLimit: 0
MaxConnRate: 62
SessRate: 1
SessRateLimit: 0
MaxSessRate: 62
SslRate: 0
SslRateLimit: 0
MaxSslRate: 0
SslFrontendKeyRate: 0
SslFrontendMaxKeyRate: 0
SslFrontendSessionReuse_pct: 0
SslBackendKeyRate: 0
SslBackendMaxKeyRate: 0
SslCacheLookups: 0
SslCacheMisses: 0
CompressBpsIn: 0
CompressBpsOut: 0
CompressBpsRateLim: 0
ZlibMemUsage: 0
MaxZlibMemUsage: 0
Tasks: 321
Run_queue: 1
Idle_pct: 100
node: haproxy-grpc-xxxxxx
Stopping: 0
Jobs: 103
Unstoppable Jobs: 0
Listeners: 5
ActivePeers: 0
ConnectedPeers: 0
DroppedLogs: 0
BusyPolling: 0
FailedResolutions: 0
TotalBytesOut: 736969

The issue is intermittent, if we try deleting haproxy pod again, we may find dns resolution works and haproxy gets proper response and it may work.

Any help would really be appreciated or any kind of troubleshooting steps?

**Comment by guptajiten** [comment]
Is it related to HAProxy not able to resolve its own address and using localhost instead?

**Comment by TimWolla** [comment]
If you want to report a bug, then [select “Bug Report”](https://github.com/haproxy/haproxy/issues/new?labels=type%3A+bug%2C+status%3A+needs-triage&template=Bug.md) on the issue creation screen, then carefully read and fill in the template. Make sure to use code fences to improve the readability of large copy and paste sections from your configuration / status pages.

If you don't think this is a bug and you want help with your configuration then either ask on the mailing list (haproxy@formilux.org) or [in the forum](https://discourse.haproxy.org).

You have selected none of the predefined options of the issue selection screen. To start with a blank issue needs a *very good* reason.
