### ISSUE TITLE
Http2. Backend

### ISSUE THREAD

**Issue by waytoharish** [haproxy/haproxy#592]
HA proxy 
1. We are trying to enable HTTP2 for Frontend as well backend but backend still on http1
2. Front End `alpn h2,http/1.1`
3. Backend 'alpn h2,http/1.1`
Defaault -option http-use-htx

## Actual behavior

localhost haproxy[123]: 192.168.37.1:41974 [20/Apr/2020:21:47:50.029] http-in~ backend_default/default_backend20 0/0/3/2/5 200 120 - - ---- 2/1/0/0/0 0/0 {} "GET /ReadResponseCode.v1 HTTP/1.1"

## Expected behavior

Should be HTTP2

**Comment by capflam** [comment]
Please provide all information requested by the issue template. Then the request line in the log message is the one received by HAProxy (eventually rewritten internally, depending on your configuration),  not the one sent to the server. So here, it means your HAProxy received an H1 request.

**Comment by wtarreau** [comment]
I think it was in fact a help request given that there was no info and there's no more feedback, so I assume the issue was found. I'm closing it now.
