### ISSUE TITLE
[x86 assembly] div return both the quotient AND the remainder

### ISSUE THREAD

**Issue by recoules** [haproxy/haproxy#596]
According to https://c9x.me/x86/html/file_module_x86_id_72.html, the ```divl``` instruction return the quotient in ```eax``` and the remainder in ```edx```.

In the following code, the compiler ignores that the value of ```edx``` is clobbered and this could lead it to perform undue optimization on this wrong basis.

https://github.com/haproxy/haproxy/blob/b203ff6e20bc80363ebfc7204e7fdd1ae656e046/include/common/standard.h#L835-L850

The solution is to declare a dummy output that will inform the compiler that the register value actually changes:
```c
unsigned int dummy;
asm("divl %3" 
    : "=a" (result), "=d" (dummy) 
    : "A"(o1), "rm"(o2))
```

**Comment by wtarreau** [comment]
You're absolutely right! I'm goign to fix it befor forgetting! Thanks!

**Comment by wtarreau** [comment]
Now fixed slightly differently ("=A" with a long long result) after analysing output code. Thanks!

**Comment by recoules** [comment]
Glad to hear that :)
