### ISSUE TITLE
X-Forwarded-Client-Cert header dropped for POST requests with payload > buff size

### ISSUE THREAD

**Issue by Soha-Albaghdady** [haproxy/haproxy#598]
We have noticed that haproxy fails to forward the X-Forwarded-Client-Cert header to the server for Post requests with large payloads (payloads greater than the tuned bufsize). The issue is only visible in load tests (load >5 req/s) and only happens to one fifth of the requests.

## Output of `haproxy -vv` and `uname -a`

```
#haproxy -vv
HA-Proxy version 1.9.15 2020/04/02 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_ZLIB=1 USE_OPENSSL=1 USE_LUA=1 USE_STATIC_PCRE2=1 USE_PCRE2_JIT=yes

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.5
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : no (libpcre2 build without JIT?)
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

#uname -a 
Linux dc770ce1-e241-46a3-871e-67a9509fddcb 4.15.0-91-generic #92~16.04.1-Ubuntu SMP Fri Feb 28 14:57:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
## What's the configuration?

```
lobal
    tune.ssl.default-dh-param 2048
    tune.bufsize 32768
 
 
defaults
    log global
    option log-separate-errors
    option http-server-close
    option forwardfor
 
# HTTPS Frontend {{{
frontend https-in
    mode http
    bind :443  ssl crt-list /var/vcap/jobs/haproxy/config/ssl/crt-list  ca-file /etc/ssl/certs/ca-certificates.crt verify optional
no option http-server-close
    http-request del-header X-Forwarded-Client-Cert
    http-request set-header X-Forwarded-Client-Cert %[ssl_c_der,base64] if { ssl_c_used }
    capture request header Host len 256
    default_backend http-routers
# }}}

```

## Steps to reproduce the behavior

1- Deploy an app which returns the received headers
2- run the load tests against the app while checking if the header was received. We are using K6 load testing tool
 
Test script: k6.js
```
mport http from 'k6/http';
import { Counter } from 'k6/metrics';
 
export let options = {
    vus: 1, // 1 virtual user
    duration: ‘30s',
    tlsAuth: [
        {
          domains: [“app-domain”],
          cert: open(“/path/to/cert”),
          key: open(“/path/to/key”)
        }
    ]
};
 
let errorCounter = new Counter('status_code_errors');
let headerTransmittedCounter = new Counter('header_transmitted');
let headerNotTransmittedCounter = new Counter('header_not_transmitted');
 
export default function() {
    const res = http.post(‘app-url’,
        '0'.repeat(1024 * 60.5) // all headers will be there if set to 30
    );
    if (res.status === 200) {
            if (res.body.includes('X-Forwarded-Client-Cert')) {
                headerTransmittedCounter.add(1)
            } else {
                headerNotTransmittedCounter.add(1);
            }
    } else {
        errorCounter.add(1);
        console.error(res.body);
    }
}
```

## Actual behavior

The X-Forwarded-Client-Cert header is silently dropped for a subset of the requests.
 
Load test output:
```
duration: 30s, iterations: -
         vus: 1,   max: 1
 
    done [==========================================================] 30s / 30s
 
    data_received..............: 17 MB  565 kB/s
    data_sent..................: 671 MB 22 MB/s
    header_not_transmitted.....: 1478   49.266446/s
    header_transmitted.........: 9237   307.898622/s
    http_req_blocked...........: avg=7.22µs   min=4.41µs   med=5.25µs   max=18.15ms  p(90)=5.95µs   p(95)=6.37µs
    http_req_connecting........: avg=78ns     min=0s       med=0s       max=840.62µs p(90)=0s       p(95)=0s
    http_req_duration..........: avg=2.48ms   min=1.38ms   med=1.95ms   max=1.4s     p(90)=2.67ms   p(95)=3.55ms
    http_req_receiving.........: avg=54.97µs  min=29.13µs  med=53.86µs  max=1.52ms   p(90)=64.16µs  p(95)=68.48µs
    http_req_sending...........: avg=258.67µs min=197.17µs med=254.92µs max=9.23ms   p(90)=283.99µs p(95)=293.39µs
    http_req_tls_handshaking...: avg=1.43µs   min=0s       med=0s       max=15.33ms  p(90)=0s       p(95)=0s
    http_req_waiting...........: avg=2.16ms   min=744.35µs med=1.64ms   max=1.4s     p(90)=2.36ms   p(95)=3.22ms
    http_reqs..................: 10716  357.198401/s
    iteration_duration.........: avg=2.78ms   min=1.66ms   med=2.23ms   max=1.4s     p(90)=3.05ms   p(95)=4.01ms
    iterations.................: 10715  357.165068/s
    vus........................: 1      min=1 max=1
    vus_max....................: 1      min=1 max=1
```
## Expected behavior
Haproxy logs an error/ warning . The header would be dropped for all or none of the requests.

## Do you have any idea what may have caused this?
We suspect that the issue has to do with the maxrewrite buffer being too small. We haven’t tuned the maxrewrite so it defaults to 1KB. The client certificate sent with the request is 5KB

## Do you have an idea how to solve the issue?
We have increased the maxrewrite buffer to 2K and we no longer see the issue. However, we don’t understand how large should the buffer be in comparison to the request size and the header size? Also, why does this happen to only a subset of the request?

**Comment by wtarreau** [comment]
I was exactly about asking you if the cert could be larger than maxrewrite. Yes indeed this is the problem. 1 kB is far more than enough for most static additions as well as x-forwarded-for. But for certificates and such large elements you definitely need to increase this reserve. If you see your header can technically reach 5kB, better set your maxrewrite to 5kB.

The reason it only happens to a subset of the request is as usual, purely timing-dependent. Some of them have the time to receive enough payload in a single recvfrom() while others don't. Buffering in the kernel, scheduling, network pacing and TCP congestion control all count here.

I think this type of issue is extremely rare and quite not easy to diagnose for most users, so I think it could make sense to add a note to the ssl_c_der section warning explicitly about this use case and suggesting to increase the reserve. Do you think it could have helped in your case ?

**Comment by wtarreau** [comment]
I'm classifying it as "works as designed" as it's indeed the case, but keeping it open as a bug until we figure how to improve the situation so that others don't get hit by this in the future (likely just by documentation).

**Comment by TimWolla** [comment]
@wtarreau Shouldn't this warning have triggered: https://github.com/haproxy/haproxy/commit/3fd1973d373363123ee25b995416643fb3a4446b?

**Comment by wtarreau** [comment]
Good point, being so much used to silent failures, I forgot about this one! However not everyone looks at the logs to figure if there were runtime warnings! Now we have the "strict-mode" which by default causes a hard failure when such a rewrite fails. But if we can warn users in the doc of a few rare sample-fetch functions which we know are almost only used like this and are likely to cause such trouble, it would be nicer.

**Comment by capflam** [comment]
And with the HTX, we can probably add an option to do the opposite of the http-buffer-request option. Because the mux copy data from an internal buffer to the channel's one, it is possible to only copy the headers. It is in fact an old discussion we already had: Have a way from the stream to tell to the mux what we want to retrieve for analysis.

**Comment by wtarreau** [comment]
Sure! But it also comes with other problems (e.g not being able to
extract POST data during header processing anymore). There's no
one-size-fits-all anyway.

**Comment by TimWolla** [comment]
> I forgot about this one! However not everyone looks at the logs to figure if there were runtime warnings!

However @Soha-Albaghdady stated that a warning was expected within the "Expected behavior" section. That implies to me that the logs were looked at and no warning was to be found.

**Comment by capflam** [comment]
Of course, it is a matter of compromise. If you need to analyse POST data and add a huge header, the only solution is to increase the buffer size and the maxrewrite value. So a warning in the doc is also required.

**Comment by capflam** [comment]
@TimWolla, in the provided configuration, there is no logger.

**Comment by wtarreau** [comment]
On Fri, Apr 24, 2020 at 09:49:08AM -0700, Christopher Faulet wrote:
> Of course, it is a matter of compromise. If you need to analyse POST data and
> add a huge header, the only solution is to increase the buffer size and the
> maxrewrite value.

On this point anyway it already isn't reliable without buffer-request,
so we could indeed have the mux always return only headers on first
read. http-buffer-request will provoke the second read that will
collect the requested data if needed. So yes, technically that could
be a nice solution.

**Comment by Soha-Albaghdady** [comment]
@wtarreau thanks alot for your reply. Yes adding a note to the ssl_c_der section would have helped as we weren't aware of such a buffer when we set the header config. 

You do use logging and have looked into the logs and found neither errors nor warnings. Here is our logging config.

```
global
    log /run/log-haproxy len 4096 format rfc3164 syslog info
defaults
    log global
    option log-health-checks
    option log-separate-errors
    option httplog 

frontend https-in
    log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslc %sslv"

```

**Comment by marcelo-devsres** [comment]
Hello folks!

Sorry for necro'ing an issue, but I decided to investigate one random problem on my production environment and came to realize that I'm having this exact problem for at least **a couple years** without knowing (around 10% of the requests that should pass certificates to the backend fail with 500 and state PR). Now I'm trying to "raise awareness" of everybody to it.

On this issue, it was mentioned:

> I think this type of issue is extremely rare and quite not easy to diagnose for most users, so I think it could make sense to add a note to the ssl_c_der section warning explicitly about this use case and suggesting to increase the reserve. Do you think it could have helped in your case ?

Was this ever added anywhere so I can point people to the docs instead of this issue? I couldn't find this on the ssl_c_der session:

* https://docs.haproxy.org/dev/configuration.html#7.3.4-ssl_c_der

**Comment by wtarreau** [comment]
I don't think any such part was added for ssl_c_der particularly but the "PR" termination code
was slightly completed:

     PR   The proxy blocked the client's HTTP request, either because of an
          invalid HTTP syntax, in which case it returned an HTTP 400 error to
          the client, or because a deny filter matched, in which case it
          returned an HTTP 403 error.  It may also be due to an HTTP header
          rewrite failure on the request. In this case, an HTTP 500 error is
          sent (see "tune.maxrewrite" and "http-request strict-mode" for more
          inforomation).

(with a typo at the end BTW). Maybe "rewrite failure on the request" should be reworded like this:

   It may also be due to the failure to rewrite or append an HTTP request header that was
   larger than the space left in the buffer, which is always at least <tune.maxrewrite>
   bytes long, but may not always be sufficient if many headers are added or if a header
   is appended from a very large string (e.g. ssl_c_der, user-agent etc).

Please do not hesitate to propose sometihng (and better, please just propose a patch, it
will save us time). Thanks!
