### ISSUE TITLE
haproxy/hapee cache bug

### ISSUE THREAD

**Issue by senioi** [haproxy/haproxy#611]
system:

> Linux UB-Dev 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

haproxy version:

> HA-Proxy version 2.1.4-e3d2d4f 2020/04/09 - https://haproxy.org/
> Status: stable branch - will stop receiving fixes around Q1 2021.
> Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html
> Build options :
> TARGET = linux-glibc
> CPU = native
> CC = gcc
> CFLAGS = -m64 -march=x86-64 -O2 -march=native -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
> OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_REGPARM=1 USE_STATIC_PCRE=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ACCEPT4=1 USE_TFO=1 USE_SYSTEMD=1
> Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM +STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS
> Default settings :
> bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
> Built with multi-threading support (MAX_THREADS=64, default=4).
> Built with OpenSSL version : OpenSSL 1.1.1d 10 Sep 2019
> Running on OpenSSL version : OpenSSL 1.1.1 11 Sep 2018
> OpenSSL library supports TLS extensions : yes
> OpenSSL library supports SNI : yes
> OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
> Built with Lua version : Lua 5.3.5
> Built with network namespace support.
> Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
> Built with PCRE version : 8.44 2020-02-12
> Running on PCRE version : 8.44 2020-02-12
> PCRE library supports JIT : yes
> Encrypted password support via crypt(3): yes
> Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
> Compression algorithms supported : identity("identity")
> Available polling systems :
> epoll : pref=300, test result OK
> poll : pref=200, test result OK
> select : pref=150, test result OK
> Total: 3 (3 usable), will use epoll.
> Available multiplexer protocols :
> (protocols marked as cannot be specified using 'proto' keyword)
> h2 : mode=HTTP side=FE|BE mux=H2
> fcgi : mode=HTTP side=BE mux=FCGI
> : mode=HTTP side=FE|BE mux=H1
> : mode=TCP side=FE|BE mux=PASS
> Available services : none
> Available filters :
> [SPOE] spoe
> [CACHE] cache
> [FCGI] fcgi-app
> [TRACE] trace
> [COMP] compressio

##What's the configuration?

> #https://www.haproxy.com/documentation/hapee/1-7r2/traffic-management/caching-small-objects/

```
cache test
total-max-size 4
max-age 240
frontend fe_main
bind *:80
http-request cache-use test
http-response cache-store test
default_backend be_main
```

##Steps to reproduce the behavior
ISSUE:
Browsers that based on Chromium or Firefox or WebKit framework you use to access any static resource less than 16KB(haproxy **tune.bufsize 262144**) will not hit the haproxy cache.
Steps to reproduce:
It will send a header: **accept-encoding: gzip, deflate, br** when I check those browsers.
Haproxy will not properly handle this resource-change request.

> Use Microsoft edge InPrivate mode to test
DEBUG LOG:
First request:
![image](https://user-images.githubusercontent.com/42415346/80898752-b22a7280-8d39-11ea-84c9-f0e6fb79379a.png)

Haproxy cache function did not hit any cache the second request:

![image](https://user-images.githubusercontent.com/42415346/80898765-eb62e280-8d39-11ea-8c91-18736a821cfc.png)

> If I don't set the  **accept-encoding: gzip, deflate, br** , haproxy will hit the cache.

Use the request tool to test:
First request:
![image](https://user-images.githubusercontent.com/42415346/80898973-c1f78600-8d3c-11ea-9ed7-9d8ade289a89.png)

haproxy cache hit the second request:

![image](https://user-images.githubusercontent.com/42415346/80898978-ccb21b00-8d3c-11ea-86e5-8df3810887e2.png)

## Do you have an idea on how to solve the issue?:
Haproxy will not cache if you set any value to the header: "accept-encoding".

**Comment by senioi** [comment]
Update:
**test version:**
haproxy 1.8 1.9 2.1 
HAPEE  1.9r* 2.1r*

**a Simple configuration sample:**
```
global
    maxconn            17024
    log                127.0.0.1 local0
    #chroot             /var/empty
    stats timeout      10m
    tune.bufsize 262144

defaults
    log global
    maxconn 16384
    mode http
    option dontlognull
    option forwardfor except 127.0.0.0/8
    option http-server-close
   
cache static-assets
   total-max-size 256
   max-age 23333

frontend fe_main
bind *:80
http-request cache-use static-assets
http-response cache-store static-assets
default_backend be_master


#---------------------------------------------------------------------
# .com backend nodes.
#---------------------------------------------------------------------
backend be_master
    balance uri
    http-request del-header X-Forwarded-For
    http-request add-header VTUN-FORWARDED-PROTO SSL
    http-request add-header VTUN-FORWARDED-HOST %[hdr(host)]
    server vTun-1 xxx.xxx.xxx.xxx:80

```

I hope to improve Haproxy's cache functions , and the cache plays a big role in the Layer-7 front-end.

**Comment by wtarreau** [comment]
This is not a bug and works as documented:
```
6.1. Limitation
----------------

The cache won't store and won't deliver objects in these cases:
(...)
- If the response contains a Vary header
```
The server saw an opportunity to compress the content on the fly before returning it, and presented a Vary header to inform caches on the way that if they want to cache, they must use the value of the headers in the list (Accept-Encoding here) as a secondary caching key and never return this content to other values (since a client might not be able to parse a response compressed differently).

Haproxy's cache uses only a primary key and currently cannot derive a secondary key from the headers mentioned in Vary since it doesn't have the request anymore. Some future work on this has been considered though, maybe just to a limited extent (e.g. only support it on accept-encoding, and/or just a few values of accept-encoding).
