### ISSUE TITLE
stick-table expiration inconsistency

### ISSUE THREAD

**Issue by celesteking** [haproxy/haproxy#615]
I've chosen the "feature request", but this is really more like a bug in design.
Searching the Internet, it seems like I'm among the few who have come across this nasty behavior -- and the number of the people realizing this is way lower than the number of people who wrongly think it works as they think. I'd say almost every article using sticky tables out there is wrong on assumptions of expiry behavior.

Main issue is that most people would think that expiry won't be reset when the entry is matched. They incorrectly assume that `expiry` would expire the entry from the time it's been set (some assume since the entry initial creation) and they lay out their rules according to this assumption. 

My proposal is not to change this behavior, but to introduce another option that would allow checking the value out without resetting the expiry counter.  i.e. ,instead of `sc_get_gpc0(<ctr>[,<table>]) : integer`, you'd have `sc_get_gpc0(<ctr>[,<table>][,<skip_expiry_reset>]) : integer`, where skip_expiry_reset is a bool. Or maybe even come up with new getter methods, like `sc_probe_gpc0(<ctr>[,<table>]) : integer`, which is quite nice, actually.

Another possibility would be just setting the counter expiry behavior explicitly via new `expire_absolute` param:
`stick-table type ip size 1m expire_absolute 5m store gpc0,conn_rate(30s)`

<expire_absolute>   defines the maximum duration of an entry in the table since it was last created. Not updated when entry is refreshed or matched.

**Comment by jmagnin** [comment]
I think your problem is that you use sc_get_gpc0 so you need a track-sc rule, and that refreshes expire.
Converters such as [table_gpc0](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#table_gpc0), and all the other table_ converters can be used for table lookups, and that won't touch expire.

I think this is more of a configuration/misunderstanding issue than a bug. Feel free to post your problem and your configuration on the mailing list or the project discourse.

**Comment by celesteking** [comment]
There's a big documentation deficiency out there. Nowhere in the documentation it says that using special type of converters would not update the entry expiration time or differ from normal behavior in any way. Even if you'd look the documentation up on `table_gpc0(<table>)`, you won't find that it has special/differing meaning vs. `sc_get_gpc`, and  you'd assume it refers to a "table" , and the "table" doc leads you to `table` and `stick-table` sections, which in their turn contain `expiry` param description, which is, again:

    <expire>   defines the maximum duration of an entry in the table since it
            was last created, **refreshed or matched**.

**Comment by TimWolla** [comment]
Retagging as “type:doc” and re-opening. @celesteking Feel free to propose improved phrasing that would have helped you.

**Comment by wtarreau** [comment]
fixed a few months ago, now closing.
