### ISSUE TITLE
Haproxy does not link dns resolution to servers when restoring from state

### ISSUE THREAD

**Issue by byronwolfman** [haproxy/haproxy#621]
## Output of `haproxy -vv` and `uname -a`

```
$ uname -a
Linux <host redacted> 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ haproxy -vv
HA-Proxy version 2.1.3 2020/02/12 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.3.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
```

## What's the configuration?

```
global
    maxconn           65536
    stats socket      /var/run/haproxy.stat mode 600 level admin expose-fd listeners
    log               /dev/haproxy-log.sock local6 debug
    pidfile           /var/run/haproxy.pid
    server-state-file /tmp/haproxy.state
    daemon

    tune.ssl.default-dh-param 2048

    hard-stop-after 180s

    # Multi-thread
    nbproc            1
    nbthread          2
    cpu-map           auto:1/1-2 0-1

# Consul DNS resolver
resolvers consul
  nameserver          consul 127.0.0.1:8600
  accepted_payload_size 8192
  resolve_retries     1000
  timeout resolve     3s
  timeout retry       2s
  hold nx             5s  # hold record this long after being unable to resolve to IP addresses
  hold obsolete       5s  # hold record this long until after it no longer appears in DNS
  hold other          5s  # safety valve, if result is not one of [valid, nx, timeout, refused]
  hold refused        90s # hold this long after dnsmasq/consul refuses to answer
  hold timeout        90s # hold this long after dnsmasq/consul times out (e.g. consul agent is unavailable)
  hold valid          5s  # trigger re-resolution after this long

# Stats dashboard
listen haproxy_stats
  bind                *:8118
  mode                http
  maxconn             256
  no log

  stats               refresh 5s
  stats uri           /haproxy-stats

  timeout client      180s
  timeout connect     5s
  timeout http-keep-alive 10s
  timeout server      180s

# HTTP Defaults
defaults
  balance             random(2)
  default-server      init-addr last,libc,none inter 2s rise 1 fall 5
  load-server-state-from-file global
  log                 global
  mode                http

  compression algo    gzip
  compression type    application/javascript application/json application/manifest+json application/pdf application/rss+xml application/x-font-ttf application/xml image/svg+xml text/css text/html text/javascript text/plain text/xml

  option              dontlognull
  option              forwardfor
  option              http-keep-alive
  option              httplog
  option              socket-stats

  timeout client      180s
  timeout connect     5s
  timeout http-keep-alive 10s
  timeout server      180s

# HTTP frontend
frontend http-in
  bind                *:80
  bind                *:443 ssl crt /etc/pki/tls/private/backend.pem  ssl-min-ver TLSv1.2 alpn h2,http/1.1
  http-request        add-header X-Forwarded-Proto https if { ssl_fc }
  maxconn             65536
  use_backend         b_%[req.hdr(Host),lower,word(1,:)]

# HTTP backends


backend b_some-app.example.com
  server-template     some-app 4 _some-app._tcp.service.consul resolvers consul resolve-prefer ipv4 check observe layer4 resolve-opts allow-dup-ip
```
Init:

```
$ cat /etc/sysconfig/haproxy
# -x option tells the worker to connect to the unix socket of the old to inherit its listening sockets
RELOADOPTS="-x /var/run/haproxy.stat"
```

```
[Unit]
Description=HAProxy Load Balancer
Documentation=man:haproxy(1)
After=syslog.target network.target

[Service]
EnvironmentFile=-/etc/sysconfig/haproxy
EnvironmentFile=-/etc/sysconfig/haproxy
Environment="CONFIG=/etc/haproxy/haproxy.cfg" "PIDFILE=/run/haproxy.pid" "EXTRAOPTS=-S /run/haproxy-master.sock"
ExecStartPre=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS
ExecStart=/usr/sbin/haproxy -Ws -f $CONFIG -p $PIDFILE $EXTRAOPTS
ExecReload=/usr/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS
ExecReload=/bin/kill -USR2 $MAINPID
KillMode=mixed
Restart=always
SuccessExitStatus=143
Type=notify
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

## Steps to reproduce the behavior

1. Launch haproxy with no state file
2. Launch two apps which register with consul, such that they appear in the `some-app.service.consul` SRV record, such that some-app1 and some-app2 are configured via DNS at startup, and some-app3 and some-app4 do nothing yet (because no records).
3. Dump state and reload from state file via `socat /var/run/haproxy.stat - <<< "show servers state" > /tmp/haproxy.state` and then `systemctl reload haproxy`

## Actual behavior

DNS prior to reload:

Haproxy stops performing DNS resolution on some-app1 and some-app2, when the DNS response changes however it will continue to perform resolution against some-app3 and some-app4 when the DNS response changes.

e.g.:

```
# before:
dig some-app.service.consul +short srv
1 1 28693 ansible.node.vagrant.consul.
1 1 29039 ansible.node.vagrant.consul.

# after:
dig some-app.service.consul +short srv
1 1 28693 ansible.node.vagrant.consul.
```

Haproxy is not performing dns resolution for some-app2, so it doesn't notice the DNS change, and the backend server goes unhealthy due to healthcheck rather than DNS.

A different example:

```
# before:
dig some-app.service.consul +short srv
1 1 28693 ansible.node.vagrant.consul.
1 1 29039 ansible.node.vagrant.consul.

# after:
dig some-app.service.consul +short srv
1 1 28693 ansible.node.vagrant.consul.
1 1 29039 ansible.node.vagrant.consul.
1 1 27702 ansible.node.vagrant.consul.
```

DNS resolution is being performed on some-app3, so it comes up as normal. If the third record is removed, it goes down as normal due to DNS resolution.

The reason that these behave differently it seems is that some-app1 and some-app2 had state reloaded from the global state file.

## Expected behavior

some-app1 and some-app2 should be performing DNS resolution; they are not. This can be confirmed via tcpdump, and by crudely littering the code with lots of print statements. In particular, I've been watching `snr_resolution_cb` in server.c. I found that the callback returns early for some-app1 and some-app2 due to `s = objt_server(requester->owner);` evaluated to NULL.

The backend servers not loaded from the state file (some-app3 and some-app4) continue to perform normally, and I see the callback function being fully executed for them.

## What next

I've not touched C in forever and I'm way out of my depth. As far as I can tell though, something about loading from the state file either overwrites the linked DNS resolution, or prevents it from being linked in the first place.

I managed to "fix" this (heavy air-quoting) with the following diff:

```diff
diff --git a/src/server.c b/src/server.c
index ac7ea37f2..370cb4a0c 100644
--- a/src/server.c
+++ b/src/server.c
@@ -3354,12 +3354,13 @@ static void srv_update_state(struct server *srv, int version, char **params)
                                res = srv_prepare_for_resolution(srv, fqdn);
                                if (res == -1) {
                                        chunk_appendf(msg, ", can't allocate memory for DNS resolution for server '%s'", srv->id);
                                        HA_SPIN_UNLOCK(SERVER_LOCK, &srv->lock);
                                        goto out;
                                }
+                               dns_link_resolution(srv, OBJ_TYPE_SERVER, 1);

                                /* configure check.port accordingly */
                                if ((srv->check.state & CHK_ST_CONFIGURED) &&
                                    !(srv->flags & SRV_F_CHECKPORT))
                                        srv->check.port = port;
```

(Note this is against the v2.1.0 tag.)

This ensured that DNS resolution was linked after loading from the state file. With this change, some-app1 and some-app2 made attempts to resolve DNS, and completed the callback routine. Changes to DNS were respected by all backend servers.

Anyway I'm pretty sure there is a horrible drawback to this approach so I'm hoping someone who knows the code better can come up with a more "correct" solution. The effect this is having on our environment is that Haproxy does not always follow DNS changes, meaning it sometimes tries to send traffic to applications that have already been shutoff.

**Comment by byronwolfman** [comment]
Looks like I need to get better at searching. https://github.com/haproxy/haproxy/issues/620 appears to be describing very nearly the same thing.

**Comment by byronwolfman** [comment]
Hey friends -- sorry to pester. Is there somewhere else I should be drawing attention to the issue report? I'm pretty sure we've found a reproducible bug but I'm definitely not smart enough to fix it without breaking the code.

**Comment by bedis** [comment]
You're at the right place, it's just a matter of finding some time to work on this one.

**Comment by byronwolfman** [comment]
Thanks! I wasn't sure if it had been noticed. As long as it has been noticed though, I won't pester any further. :)

**Comment by wtarreau** [comment]
Any news on this ?

**Comment by byronwolfman** [comment]
Hey! We're also curious about the status of this. We decided to try my dangerous patch in a test environment, and it turns out it is very memory-unsafe. Don't do it.

We're back on the official code, but that leaves us in a situation where haproxy is not always tracking DNS changes after reloading dumped state. We've gotten pretty good at recreating the issue if you need any additional details.

**Comment by capflam** [comment]
Thanks for your feedback. @bedis, any way to give us some hints on this ?

**Comment by byronwolfman** [comment]
Hey friends, if anyone is into trying incredibly dangerous things, our team is currently soaking the following patch in a test environment, built against haproxy 2.1.3:

```diff
--- server.c
+++ server.c
@@ -3358,6 +3358,7 @@
 					HA_SPIN_UNLOCK(SERVER_LOCK, &srv->lock);
 					goto out;
 				}
+				srv_set_fqdn(srv, fqdn, 0);

 				/* configure check.port accordingly */
 				if ((srv->check.state & CHK_ST_CONFIGURED) &&
```

This is similar to the diff I posted in the initial issue, but without causing an infinite loop on exit. It seems that using `dns_link_resolution` directly in that context is unsafe or otherwise dirtying things that prevent haproxy from shutting down. Using `srv_set_fqdn` instead seems to be a safer/more robust way to accomplish the same outcome, without the death spiral.

The tipoff came from the following comment which is made earlier in server.c:

```
          /* If the FDQN has been changed from stats socket,
           * apply fqdn state file value (which is the value set
           * from stats socket).
           */
          if (fqdn_set_by_cli) {
            srv_set_fqdn(srv, fqdn, 0);
            srv->next_admin |= SRV_ADMF_HMAINT;
          }
```

So if the fqdn has _changed_ via the stats socket, re-assert it. Dynamic DNS sounds like something else that would cause drift, and wouldn't you know it, `srv_set_fqdn` relinks DNS. It's possible that this patch should also be setting `srv->next_admin |= SRV_ADMF_HMAINT;` but currently it is not.

So far this patch has corrected the behaviour we were seeing previously. The patched binary correctly follows DNS changes even after reloading with state. I don't think that the patch is the correct way to fix the bug as-is since there are probably cases where executing `srv_set_fqdn` is unnecessary (which is why it's tucked away in a few conditions, by default). Regardless, I hope it will point the way to a solution that is actually correct and to the high standard of the project.

Couple of warnings for other sysadmins shooting from the hip:

1. This is showing positive results in our environment but that doesn't mean it will work for anyone else, so this is very use-at-your-own-risk.
1. We patched against 2.1.3 since this version is otherwise stable for our config. I've not tried other versions of 2.1.x and for reasons unrelated to this issue we're not ready to move to 2.2.x.

**Comment by TimWolla** [comment]
>     2\. We patched against 2.1.3 since this version is otherwise stable for our config.

You should upgrade to the most recent 2.1.x if only to fix a CRITICAL vulnerability in the HTTP/2 implementation:

- http://www.haproxy.org/bugs/bugs-2.1.3.html
- http://git.haproxy.org/?p=haproxy-2.1.git;a=commitdiff;h=f17f863

**Comment by byronwolfman** [comment]
Thanks Tim, excellent advice. Our shop uses haproxy as a backend east-to-west loadbalancer which is not internet exposed. It doesn't excuse not patching, but hopefully forgives the pace. Either way, I appreciate the your pointing this out!

I'll attempt our hacky patch against 2.1.4 or later.

**Comment by TimWolla** [comment]
> I'll attempt our hacky patch against 2.1.4 or later.

FWIW: I don't expect you seeing any issues with going straight to 2.1.7 with that single line change. From my experience you can mindlessly upgrade HAProxy to the latest release within a given branch. These releases are expected to only fix bugs and not change anything else. Regressions that make it into a release are pretty rare and usually quickly fixed.

**Comment by byronwolfman** [comment]
Sounds good to me -- it's straight to 2.1.7 then! Thanks again Tim.

To perhaps nobody's surprise, the only difference for the 2.1.7 patchfile is the line numbers. Our team is currently soaking this against 2.1.7 in a test environment:

```diff
--- server.c
+++ server.c
@@ -3222,6 +3222,7 @@
 					HA_SPIN_UNLOCK(SERVER_LOCK, &srv->lock);
 					goto out;
 				}
+				srv_set_fqdn(srv, fqdn, 0);

 				/* configure check.port accordingly */
 				if ((srv->check.state & CHK_ST_CONFIGURED) &&
```

(The usual disclaimer about applying a random stranger's patch production systems still applies!)

**Comment by capflam** [comment]
FYI, recent fixes were pushed that may solve this issue. Backported to 2.3 only for now.

* a331a1e BUG/MINOR: resolvers: Only renew TTL for SRV records with an additional record
* b4badf7 BUG/MINOR: resolvers: new callback to properly handle SRV record errors
* 52d4d30 BUG/MEDIUM: resolvers: Reset server address and port for obselete SRV records
* d127ffa BUG/MEDIUM: resolvers: Reset address for unresolved servers

**Comment by capflam** [comment]
Now backported as far as 2.0.

**Comment by capflam** [comment]
I'm closing this issue. Feel free to reopen it if necessary. Thanks !
