### ISSUE TITLE
boringssl builds are broken

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#633]
https://travis-ci.com/github/haproxy/haproxy/jobs/335953354

hmm, I used to think that boringssl supports async mode. @ehocdet  ?

```
src/cfgparse-ssl.c:1804:35: error: use of undeclared identifier 'ssl_parse_global_ssl_async'

        { CFG_GLOBAL, "ssl-mode-async",  ssl_parse_global_ssl_async },

                                         ^

1 error generated.

Makefile:877: recipe for target 'src/cfgparse-ssl.o' failed

make: *** [src/cfgparse-ssl.o] Error 1

make: *** Waiting for unfinished jobs....
```

**Comment by wlallemand** [comment]
The #ifdef was misplaced during the split of the file.

**Comment by wlallemand** [comment]
Is there a reason why I don't see the boringssl build on our github? Did we disabled it in the CI? I don't get where I'm suppose to see this one, the github shows everything in green.

**Comment by wlallemand** [comment]
Is there a reason why I don't see the boringssl build on our github? Did we disabled it in the CI? I don't get where I'm suppose to see this one, the github shows everything in green.

**Comment by chipitsine** [comment]
BoringSSL build is about 10 min, so we decided to run it daily, to keep developer velocity by using other fast builds.

when building BoringSSL we have 2 bad choices

1. cache it (it help very rare)
2. clone it

any of choices takes about 10 minutes

**Comment by wlallemand** [comment]
Why is it a problem? is it blocking the next builds?

**Comment by chipitsine** [comment]
it is not a problem by itself. travis-ci allows 4 builds in parallel. 

we discussed in mailing list that we want high developer velocity and thus fast tests. BoringSSL is not considered widely used, build takes 10 min, so we decided to run several build daily, including BoringSSL.


anyway we can switch "daily" <--> "push" behaviour for BoringSSL

**Comment by wlallemand** [comment]
Let's keep it this way, I just wanted to know the reason behind this. Thanks!

**Comment by chipitsine** [comment]
nevermind, I will add that to travis-ci.yml next time
