### ISSUE TITLE
src/cache.c: null pointer dereference suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#634]
```
1434                cconf = f->conf;
    CID 1399771 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)8. var_deref_model: Passing null pointer name to strcmp, which dereferences it.
1435                if (strcmp(name, cconf->c.name)) {
1436                        cconf = NULL;
1437                        continue;
1438                }
```

**Comment by chipitsine** [comment]
coverity confirmed issue is fixed.

@lukastribus , can you please tag the issue for backporting to 1.9, 2.0, 2.1 ?
I'm not closing issue yet (for backporting)

**Comment by TimWolla** [comment]
I don't think there is a need for backporting (the commit message only says “may”), because the patch does not result in a user-visible change.

**Comment by chipitsine** [comment]
I do not mind. 

so, I just close this issue ?

**Comment by chipitsine** [comment]
I thought that "CLEANUP" commits are not backported, but "BUG" are usually backported
