### ISSUE TITLE
Balance based on vars or tcp payload

### ISSUE THREAD

**Issue by git001** [haproxy/haproxy#638]
## Output of `haproxy -vv` and `uname -a`

```
Future Version
```

## What should haproxy do differently? Which functionality do you think we should add?

There are some user request do be able to balance based on tcp payload  
https://stackoverflow.com/questions/61838813/consistent-hashing-to-a-dynamic-set-of-servers-based-on-tcp-payload/61880749  
https://stackoverflow.com/questions/30304124/unexpected-haproxy-acl-behaviour-tcp-payload-routing   
It would be nice to have a balance method `vars` similar to `uri` or `hdr()` which uses a variable capture by `req.payload()`

**Comment by wtarreau** [comment]
I've though about making balance support an expression, but maybe having just a variable could be a nice option.

**Comment by wtarreau** [comment]
No done as a consequence of 7c9a0fe2a ("MEDIUM: backend: add new "balance hash <expr>" algorithm").
Let's mark as fixed and close.
