### ISSUE TITLE
haproxy 2.2 adds extra root cert to the Certificate Chain

### ISSUE THREAD

**Issue by phaleth** [haproxy/haproxy#655]
The issue is reproducible using any of the following docker images:
haproxy:2.2-dev6
haproxy:2.2-dev7
haproxy:2.2-dev8

Setup a domain pointing to the server, TLS termination on the server and then run the following command against the haproxy server instance:

> echo QUIT | openssl s_client -connect yourdomain.com:443 -tlsextdebug -status

In case where Let's Encrypt cert is used portion of the output will contain the following:
```
---
Certificate chain
 0 s:CN = yourdomain.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
 2 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```

While that specific portion should contain the following instead:
```
---
Certificate chain
 0 s:CN = yourdomain.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
```

**Comment by TimWolla** [comment]
Please fill in the issue template, specifically the (SSL) configuration.

**Comment by phaleth** [comment]
Bellow is a haproxy.cfg suitable for a dockerized haproxy instance with all the relevant parts to reproduce the issue:
```
global
    log stdout local0
    maxconn 4096

    ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-CCM8:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA
    ssl-default-bind-ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

    ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-CCM8:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA
    ssl-default-server-ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256
    ssl-default-server-options ssl-min-ver TLSv1.2 no-tls-tickets

    ssl-dh-param-file /etc/haproxy/certs/dhparam4096.pem

defaults
    log global
    option httplog
    option dontlognull
    option http-pretend-keepalive
    retries 3
    option redispatch
    timeout connect 5000
    timeout check 5000
    timeout client 149500
    timeout server 150000
    timeout http-request 145000

frontend web-https
    mode http
    http-request del-header X-Forwarded-For
    option forwardfor
    bind *:80
    bind *:443 ssl crt /etc/haproxy/certs/yourdomain.com.pem alpn h2,http/1.1 npn h2,http/1.1 curves P-384:X448:P-521
    http-request set-header X-Forwarded-Proto https if { ssl_fc }
    http-response del-header Server
    http-response del-header X-Powered-By
    acl host_base hdr(host) -i yourdomain.com
    acl host_www hdr(host) -i www.yourdomain.com
    http-request set-header Host yourdomain.com if host_www
    http-request redirect scheme https if !{ ssl_fc }
    use_backend yourdomain-com-backend if host_base || host_www
    default_backend yourdomain-com-backend

backend yourdomain-com-backend
    mode http
    compression algo gzip
    compression type image/svg+xml text/plain text/html text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript font/woff font/woff2
    http-response set-header Strict-Transport-Security max-age=31536000;includeSubDomains;preload
    http-response set-header X-Frame-Options SAMEORIGIN
    http-response set-header X-Content-Type-Options nosniff
    http-response set-header X-XSS-Protection "1; mode=block"
    http-response set-header Content-Security-Policy "upgrade-insecure-requests; object-src 'none'"
    http-response set-header Referrer-Policy no-referrer
    http-response set-header Feature-Policy "geolocation 'none'; camera 'none'; speaker 'none'"
    server node1 172.21.0.5:80
```

**Comment by lukastribus** [comment]
Haproxy doesn't add or remove any certificates, but uses exactly what is provided in the file. Remove the unneeded certificate from `/etc/haproxy/certs/yourdomain.com.pem` to avoid sending it to the client.

**Comment by phaleth** [comment]
There is no unneeded certificate in `/etc/haproxy/certs/yourdomain.com.pem`, haproxy:2.1, 2.0 and 1.9 work fine with the above setup as far as the resulting Certificate Chain is concerned.

**Comment by wlallemand** [comment]
HAProxy can't make up certificates that are not mentionned in your PEM file.

Please check with `openssl crl2pkcs7 -nocrl -certfile  /etc/haproxy/certs/yourdomain.com.pem | openssl pkcs7 -print_certs -text -noout`

**Comment by phaleth** [comment]
Actually, there are two PEM files, `/etc/haproxy/certs/yourdomain.com.pem.ecdsa` and `/etc/haproxy/certs/yourdomain.com.pem.rsa`. Only `/etc/haproxy/certs/yourdomain.com.pem` is mentioned in the `haproxy.cfg` and that way haproxy serves both ECC and then RSA cert. In each of those PEM files only two certificates are mentioned. There is no reason why would the root cert be there twice.

I could provide the somewhat full TLS cert setup, which is done using `acme.sh` in a separate docker container, but that has nothing to do with the issue.

Originally I thought this might be easy to reproduce. Right now it seems like it's related to those specific docker containers.

Please if you require any more input let me know. I'm unsure if the output of the command mentioned by @wlallemand is safe to post publicly, but that one also outputs only two certificates for any of those two above mentioned PEM files.

**Comment by lukastribus** [comment]
Note that the output doesn't look like the root CA cert is included, but it looks more like the intermediate certificate is sent twice or something like that.

**Comment by wlallemand** [comment]
Okay, so you use multi-certificate bundling, do you have the same problem when specifying directly "crt /etc/haproxy/certs/yourdomain.com.pem.rsa crt /etc/haproxy/certs/yourdomain.com.pem.ecdsa" ?

The output of `openssl crl2pkcs7 -nocrl -certfile YOURPEM | openssl pkcs7 -print_certs -text -noout | grep -E 'Subject:|Issuer:' ` should return you the same things as your openssl s_client output, if you only have 2 certificates in each files, there is indeed a bug.

Also could you provide the output of `haproxy -vv` as asked in the github template.

**Comment by lukastribus** [comment]
I can reproduce with multi-cert bundle and with both openssl 1.0.2 and 1.1.1:

4fed93eb725b513dd3b2029daa888311db110851 is the first bad commit


```
lukas@dev:~/haproxy$ ./haproxy -vv
HA-Proxy version 2.2-dev5-4fed93-3 2020/03/24 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [TRACE] trace
        [COMP] compression

lukas@dev:~/haproxy$
lukas@dev:~/haproxy$ openssl crl2pkcs7 -nocrl -certfile /home/lukas/cert/certdir/dev.lan.ltri.eu.pem.ecdsa | openssl pkcs7 -print_certs -text -noout | grep -E 'Subject:|Issuer:'
        Issuer: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
        Subject: CN=dev.lan.ltri.eu
        Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
        Subject: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
lukas@dev:~/haproxy$ openssl crl2pkcs7 -nocrl -certfile /home/lukas/cert/certdir/dev.lan.ltri.eu.pem.rsa | openssl pkcs7 -print_certs -text -noout | grep -E 'Subject:|Issuer:'
        Issuer: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
        Subject: CN=dev.lan.ltri.eu
        Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
        Subject: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
lukas@dev:~/haproxy$

```

**Comment by phaleth** [comment]
@wlallemand I've just tried putting `/etc/haproxy/certs/yourdomain.com.pem.ecdsa` and then also `/etc/haproxy/certs/yourdomain.com.pem.rsa` into `haproxy.cfg` on the bind line and that indeed solves the issue. The thing is I'd like to be able to use dual certs and let haproxy negotiate ECC first with the client, which works in haproxy:2.1 when specifying `/etc/haproxy/certs/yourdomain.com.pem` on the bind line.

@lukastribus Seems like the issue can be reproduced on haproxy:2.2-dev5 as well. I didn't test that one. Thanks.

**Comment by wlallemand** [comment]
@phaleth declaring both certificates separately does this, the only requirement is to have an openssl version which is at least 1.1.1 or boringssl, the multi-cert bundle technique was implemented because of the limitation of previous OpenSSL versions. However this is not normal and this is indeed a bug.

@lukastribus thanks a lot, that helps, I'll take a look at this tomorrow.

**Comment by wlallemand** [comment]
My understanding is that SSL_CTX_add_extra_chain_cert() is not able to create different chains for all the certificate types. So the new chain is added at the end of the previous one, which means that it would concatenate the chain of the .rsa with the chain of the .ecdsa.

So we still need the previous code, which handles bundles for >= 1.0.2. I'm reverting this commit.
