### ISSUE TITLE
HAProxy does not advertise "fragmentation" as an SPOE capability

### ISSUE THREAD

**Issue by NickMRamirez** [haproxy/haproxy#659]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.1.4 2020/04/02 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.33 2019-04-16
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [TRACE] trace
        [COMP] compression
```

## What's the configuration?

*haproxy.cfg*:
```
global
  log stdout format raw local0

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client  50000
  timeout server  50000

frontend web
   bind :80
   filter spoe engine my-spoa config /etc/haproxy/spoa.conf
   http-request set-header "ip_score" %[var(sess.myspoe.ip_score)]
   default_backend servers

backend servers
   balance roundrobin
   server web1 web:8080 check

backend be_agents
   mode tcp
   balance roundrobin
   option spop-check
   server agent1 agent:12345 check  inter 10s  maxconn 30
```

*spoa.conf*:

```
[my-spoa]
spoe-agent my-agent
   messages           my-message-name
   option var-prefix  myspoe
   option send-frag-payload
   log                global
   use-backend        be_agents
   timeout hello      10s
   timeout idle       10s
   timeout processing 10s

spoe-message my-message-name
   args ip=src anotherarg=str(abc)
   event on-frontend-http-request if { path / }
```

## Steps to reproduce the behavior

1. Clone the "integration_tests" branch from [the .NET Core SPOA library](https://github.com/haproxytech/haproxy-spoa-dotnet/tree/integration_tests/IntegrationTests)
2. Run `docker-compose up`
3. Make a web request to the HAProxy frontend: *localhost:8000*
4. The SPOA reports its log output in the window where Docker Compose is running

## Actual behavior

The .NET Core SPOA reports the HAProxy Hello message. Note that "capabilities" reports "pipelining" and "async", but not "fragmentation".

```
agent      | Type: HaproxyHello
agent      | Length: 129
agent      | Flags - Fin: True
agent      | Flags - Abort: False
agent      | StreamID: 0
agent      | FrameID: 0
agent      | supported-versions = 2.0
agent      | max-frame-size = 16380
agent      | capabilities = pipelining,async
agent      | engine-id = e0fb9a42-8ea4-402f-aed3-291cab570c8e
```

## Expected behavior

The spec is not clear whether HAProxy supports receiving fragmented frames. If it does, then it should advertise "fragmentation" as a capability. If it does not, then could this be documented somewhere?

## Do you have any idea what may have caused this?

n/a

## Do you have an idea how to solve the issue?

If HAProxy can receive fragmented frames from a SPOA, it should be listed as a capability advertised to the SPOA.

**Comment by capflam** [comment]
The "fragmentation" capability is announced to indicate the sender is able to receive fragmented frames. HAProxy does not support yet fragmented frames in receipt. But your right, it is not mentioned in the SPOE documentation.

**Comment by NickMRamirez** [comment]
Okay, thanks for clarifying. If it does not list it as a capability, so that could be discovered by checking the capabilities field, but I had a doubt and so opened the ticket. That answers my question, though, and I will leave it up to you whether or not it should be documented further.

**Comment by capflam** [comment]
I'm adding the label "Work as designed" but I'm keeping it open as a reminder.

**Comment by cortex93** [comment]
> The "fragmentation" capability is announced to indicate the sender is able to receive fragmented frames. HAProxy does not support yet fragmented frames in receipt. But your right, it is not mentioned in the SPOE documentation.

When fragmentation is supported by the receiver, does it means that the sender MUST or MAY send fragmented frames ? Documentation says "This is the responsibility to the other peer to use it or not", but it's not clear for me.

If the answer is MUST, for spoa implementation, it could be a breaking change when HAProxy will support fragmentation if they do not handle it.

**Comment by NickMRamirez** [comment]
@cortex93 The sender *may* send fragments if the receiver supports it. Section 3.2.1 "Frame capabilities" says:

> fragmentation: This is the ability for a peer to support fragmented  payload in received frames. This is an **asymmectical capability**, it only concerns the peer that announces it. This is the **responsibility to the other peer to use it or not**.

I understand this to mean that when HAProxy begins supporting receiving fragmented frames, then the sender can send them if they are capable. In that case, the sender would support sending UNSET frames and HAProxy would support receiving them.

**Comment by capflam** [comment]
Finally, the limitation was documented. I'm closing the issue now. Thanks !
