### ISSUE TITLE
Domain .ie on file not being accepted on acl statement

### ISSUE THREAD

**Issue by rmsmatos** [haproxy/haproxy#66]
When entering a domain ending in .ie on a file and using it on a acl rule returns the error:
 [ALERT] 078/130409 (31480) : parsing [/etc/haproxy/haproxy.cfg:93] : error detected while parsing ACL 'WWWDomainRedirect' : 'somedomain.ie' is not a valid IPv4 or IPv6 address at line 12 of file '/etc/haproxy/wwwdomainredirect.cfg'.

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.8-1ubuntu0.4 2019/01/24
Copyright 2000-2018 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -g -O2 -fdebug-prefix-map=/build/haproxy-Mxbbv4/haproxy-1.8.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.0g  2 Nov 2017
Running on OpenSSL version : OpenSSL 1.1.0g  2 Nov 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace

Linux Obfuscated 4.15.0-1037-azure #39-Ubuntu SMP Tue Jan 15 10:24:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
        acl WWWDomainRedirect src -f /etc/haproxy/wwwdomainredirect.cfg

```

## Steps to reproduce the behavior

1. Create a file named /etc/haproxy/wwwdomainredirect.cfg and add some entries for domains and include one ending in .ie
2. Name an acl rule and state the file as the source: acl WWWDomainRedirect src -f /etc/haproxy/wwwdomainredirect.cfg
3. Issue a service haproxy reload

## Actual behavior
After reload haproxy retunrs this error.

HAproxy retunrs the 
 [ALERT] 078/130409 (31480) : parsing [/etc/haproxy/haproxy.cfg:93] : error detected while parsing ACL 'WWWDomainRedirect' : '360print.ie' is not a valid IPv4 or IPv6 address at line 12 of file '/etc/haproxy/wwwdomainredirect.cfg'.

**Comment by TimWolla** [comment]
You forgot to redact the domain in one place and I looked it up: It does not have any DNS records defined.

In any case your ACL does not look right to me. You are attempting to match the client `src` IP address against some domains. While this would work if the domain would resolve I still believe that it is not what you intended.

I guess you are searching for `acl WWWDomainRedirect hdr(host) -f /etc/haproxy/wwwdomainredirect.cfg`.

**Comment by rmsmatos** [comment]
Tim, you're absolutely right, the acl rule is constructed as you indicate: acl WWWDomainRedirect hdr(host) -f /etc/haproxy/wwwdomainredirect.cfg

The domain is in fact 360onlineprint.ie, I've redacted because it wasn't meant to be public yet but I guess I must be as accurate as possible, sorry for that. So, in this case because HAProxy can't resolve the domain it reports that error? I've made some changes on the used DNS servers and must wait for DNS propagation and hopefully tomorrow they are effective. I'll try again tomorrow and let you know if problem remains after DNS records are valid.

Thanks for you help.

**Comment by TimWolla** [comment]
> I must be as accurate as possible, sorry for that.

For reliable answers this would be helpful. Either clearly mark it as redacted or use the originals. In your case there was a `360print.ie` (without the “online”).

> So, in this case because HAProxy can't resolve the domain it reports that error?

Yes. The `src` fetch tries to match an IP address and thus HAProxy tries to resolve the domain for you:

> The "-n" flag forbids the dns resolutions. It is used with the load of ip files.
> By default, if the parser cannot parse ip address it considers that the parsed
> string is maybe a domain name and try dns resolution. The flag "-n" disable this
> resolution. It is useful for detecting malformed ip lists. Note that if the DNS
> server is not reachable, the haproxy configuration parsing may last many minutes
> waiting fir the timeout. During this time no error messages are displayed. The
> flag "-n" disable this behavior. Note also that during the runtime, this
> function is disabled for the dynamic acl modifications.

(it's in section 7.1 ACL basics: https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#7.1

> I'll try again tomorrow and let you know if problem remains after DNS records are valid.

If you use the (assumed) correct `hdr(host)` fetch instead of `src` it should already work. But I'm only guessing here what you intended to do.
