### ISSUE TITLE
A bogus STREAM is spinning

### ISSUE THREAD

**Issue by StanleyP** [haproxy/haproxy#661]
## Output of `haproxy -vv` and `uname -a`

Using HAProxyTech docker image haproxytech/haproxy-debian:2.0
Same behavior occured on latest docker image haproxytech/haproxy-debian:2.1 (version 2.1.4).

```
$ uname -a
Linux dih-uat-vmss-fe-000001 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ haproxy -vv
HA-Proxy version 2.0.14 2020/04/02 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-
clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wn
ull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX
_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBS
OLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

## What's the configuration?

```
global
	master-worker
	nbthread 1

	stats socket /var/run/haproxy.sock mode 600 expose-fd listeners level user

	log stdout format raw local0
	log 127.0.0.1:25224 len 4096 format rfc3164 local0 info info

	tune.ssl.default-dh-param 2048

	lua-load /src/main.lua
	crt-base /usr/local/etc/haproxy/pem

defaults
	timeout connect 10s
	timeout client  60s
	timeout server  60s

	log global

	mode http
	log-format "$logfmt_http"
	option dontlognull

peers all
	peer dih-uat-vmss-fe-000001 10.48.115.101:1024
	peer dih-uat-vmss-fe-000003 10.48.115.103:1024
	peer dih-uat-vmss-fe-000004 10.48.115.104:1024

backend __dns__
        disabled
	server https-login.microsoftonline.com login.microsoftonline.com:443

program danted
  command danted -f /usr/local/etc/danted.conf
  no option start-on-reload

frontend https
	bind :443 ssl crt web.pem crt api.pem

	log-format "$logfmt_https"

	http-request set-header X-Forwarded-Proto https
	option forwardfor if-none

	acl is_healthcheck path /healthcheck/ping
	http-request set-log-level silent if is_healthcheck
	http-request use-service lua.ping if is_healthcheck

	http-request redirect location /grafana/ if { hdr(host) -i hub-uat.mycompany.local } { path / }
	use_backend api if { hdr(host) -i api-uat.mycompany.local } { ssl_fc_sni -i api-uat.mycompany.local }
	use_backend grafana_int if { hdr(host) -i hub-uat.mycompany.local } { path_beg /grafana }
	use_backend login if { hdr(x-original-host) -i login-uat.mycompany.com }
	use_backend fuel_transaction if { path_beg /sdc/fuel-transaction/ }
	use_backend geo_location if { path_beg /sdc/geo-location/ }
	use_backend transactions if { path_beg /sdc/transactions/ }

backend http-nomatch
        http-request deny if { ssl_fc }
	redirect scheme https code 301 if !{ ssl_fc }

frontend http
	bind :80

	option forwardfor if-none

	default_backend http-nomatch

	acl is_healthcheck path /healthcheck/ping
	http-request set-log-level silent if is_healthcheck
	http-request use-service lua.ping if is_healthcheck

	http-request use-service prometheus-exporter if { path /metrics }
	use_backend api if { hdr(host) -i api-uat.mycompany.local }

backend api
	http-request set-log-level silent
	server api unix@/tmp/api.sock send-proxy

backend api-nomatch
	http-response lua.cors "GET,PUT,POST,DELETE,OPTIONS,HEAD,PATCH,TRACE" "*"
	http-request use-service lua.options if { method OPTIONS }
	http-request deny

frontend api
	bind unix@/tmp/api.sock accept-proxy

	http-request redirect location /swagger/ if { path / }

	default_backend api-nomatch

	http-request lua.cors
	http-request lua.apiroute

	unique-id-format %[var(txn.api_unique_id)]
	unique-id-header X-TrackingId
	http-response set-header X-TrackingId %[var(txn.api_unique_id)]

	use_backend rapidoc if { path_beg -i /swagger/ }
	use_backend swagger-ui if { path_beg -i /swagger-ui/ }
	use_backend %[var(txn.api_backend)] if { var(txn.api_match) -m bool }
	use_backend document_cache_fulfilment if { path_beg /soap/document/setDocument }
	use_backend individual_bank_account if { path_beg /soap/ewallet/individual-bank-account/ }
	use_backend smsgw if { path_beg /soap/smsgw/ }

backend com
	balance roundrobin

	http-request lua.apiauthn
	http-request use-service lua.apiauthndeny if ! { var(txn.api_authenticated) -m bool }
	http-request lua.apiauthz
	http-request use-service lua.apiauthzdeny if ! { var(txn.api_authorized) -m bool }
	http-request lua.apithrottle
	http-request use-service lua.apirldeny if { var(txn.api_throttle) -m bool }
	http-response lua.apirlhdrs


	http-request lua.aadauth com
	http-request set-header Host om-uat.mycompany.local

	server com om-uat.mycompany.local:443 ssl verify none
```

## Steps to reproduce the behavior

So far I was able to reproduce the issue in my local dev environment by:

    1. Running haproxy container locally
    2. Connecting to remote redis and OAuth2 provider via VPN
    3. Make HTTP request to haproxy to populate redis connection pool
    4. Disconnect VPN
    5. Make HTTP request
    6. HAProxy crashes with "bogus STREAM error"

When I restarted redis server(s) cleanly to invalidate connection in redis connection pool the problem did not manifest and HAProxy reconnected to redis cleanly.

## Actual behavior

HAProxy crashes and is restarted.

`A bogus STREAM [0x558f4ecaf4b0] is spinning at 172103 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x558f4ecaf4b0 src=10.48.144.4 fe=api be=com dst=unknown rqf=44080000 rqa=900 rpf=80000000 rpa=0 sif=EST,200008 sib=INI,10 af=(nil),0 csf=0x558f4ec94400,4000 ab=(nil),0 csb=(nil),0 cof=0x558f4ed795a0,a0203300:H1(0x558f4ecd74d0)/RAW((nil))/unix_stream(133) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]`

## Expected behavior

HAProxy does not crash:)

**Comment by TimWolla** [comment]
> HAProxy crashes and is restarted.

Can you provide the error message and stack trace, please?

**Comment by StanleyP** [comment]
I'm sorry, I forgot to include the error message:

`A bogus STREAM [0x558f4ecaf4b0] is spinning at 172103 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x558f4ecaf4b0 src=10.48.144.4 fe=api be=com dst=unknown rqf=44080000 rqa=900 rpf=80000000 rpa=0 sif=EST,200008 sib=INI,10 af=(nil),0 csf=0x558f4ec94400,4000 ab=(nil),0 csb=(nil),0 cof=0x558f4ed795a0,a0203300:H1(0x558f4ecd74d0)/RAW((nil))/unix_stream(133) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]`

**Comment by wtarreau** [comment]
Thanks, the error is extremely useful. So you've received a valid request, there's no error, backend HTTP rules were still being evaluated and it was not yet completed. Given that you have Lua actions there, it's pretty certain that it's related to this, however I don't see how Lua could cause an issue forcing the stream to spin :-/

In case your Lua code is not too big, it would be useful to share it.

**Comment by StanleyP** [comment]
I'm afraid I'm not allowed to share the lua code:(
It is part of integration platform we are building for our customer.
What exactly in the lua code would cause haproxy to crash? 

Do you think downgrading to 1.9 or even 1.8 might help?

**Comment by TimWolla** [comment]
I'm not sure whether it would be helpful, but do you happen to have received a core dump?

**Comment by StanleyP** [comment]
Unfortunately I have no core dump. I'm running haproxy in docker container and I dont know how to get core dump from it.
Yesterday our haproxy crashed many times, but today only two times yet.

In order to obtain core dump, is it sufficient to set set-dumpable in global config section and point core file location to some writable directory mapped to host filesystem?

**Comment by wtarreau** [comment]
It might suffice, but honestly without a hint about what the Lua code does, it will be hard to guess from the core because the core happens far away from the problem. There is something there that makes haproxy believe there is constant activity on this stream, it might be something related with direct channel manipulation maybe, or maybe you're draining data or rewriting part of a request or response. It's hard to guess. At least if you can reproduce it easily and can fiddle a bit with the code there, you might be able to figure what triggers the problem. The Lua code is not necessarily wrong, it might be hitting a corner case, a situation that was not expected to be supported and which makes the Lua state and the core of haproxy permanently disagree on something.

**Comment by StanleyP** [comment]
The lua code makes http request via https://github.com/haproxytech/haproxy-lua-http to obtain oauth2 token and then stores it in redis via https://blog.arpalert.org/2018/02/haproxy-lua-redis-connection-pool.html then sets the token in authorization header. We've been using this same exact auth code for some time and yesterday was the first time we experienced this crash (and first haproxy crash at all!). We ran on haproxy 2.1.4, so I switched to 2.0 LTS, but the crash occured again.

**Comment by wtarreau** [comment]
OK. Did you ever update the version of this Lua code that you were using ? I'm seeing a recent bug having been fixed a few days ago there. Maybe you automatically updated it and this fix caused a regression, which could explain why it only recently started to appear ?

**Comment by StanleyP** [comment]
No, this code hasn't been touched for several months (I checked our git repo and last change in lua auth code was 5 months ago) and we haven't had any problems with it till yesterday. It is really confusing. Perhaps some latest change in haproxytech/haproxy-debian:2.1 and 2.0 triggers it.
I will do my best and try to reproduce it. Today crash occured 6 times so far:/
Monday I will try to downgrade to 1.9 and see if it still occurs.

**Comment by wtarreau** [comment]
OK. 2.1.5 was just issued with some fixes. While I can't think of any of them that could be related, it might be worth giving it a try, especially if it could save you 6 crashes a day!

**Comment by StanleyP** [comment]
Thanks for info. I'll give 2.1.5 chance and definitely report back.
I will also try to stress test our auth code and see if I will be able to crash it on purpose.
Thanks a lot for your feedback!!

**Comment by StanleyP** [comment]
When can I expect that 2.1.5 will appear on hub.docker.com?
FYI, so far it seems that it has something to do with idle/stalled/dead connections in redis connection pool. I was able to crash it several times since friday during my experiments, but I dont have definitive test-case that crashes every time.
Do you have any idea how to check if socket (created by haproxy lua api) in connection pool is still ok to use?

**Comment by StanleyP** [comment]
So far I was able to reproduce the issue in my local dev environment by:

1. Running haproxy container locally
2. Connecting to remote redis and OAuth2 provider via VPN
3. Make HTTP request to haproxy to populate redis connection pool
4. Disconnect VPN
5. Make HTTP request
6. HAProxy crashes with "bogus STREAM error"

When I restarted redis server(s) cleanly to invalidate connection in redis connection pool the problem did not manifest and HAProxy reconnected to redis cleanly.

Yesterday I discovered that I did not set timeout on some of the core.tcp() sockets via https://www.arpalert.org/src/haproxy-lua-api/2.0/index.html#Socket.settimeout When I fixed that, it appeared that the problem is fixed as well, but it reoccured later again :/

Is settimeout really necessary for all sockets created by lua API? I'm really running out of the ideas now. Do you have any suggestions? I dont do anything special in my lua code, no direct request/response manipulation or rewriting etc. Just http and redis calls.

BTW, is SPOE and spoa_server (in contrib) production ready? I had an idea to move auth code to spoa_server to isolate lua auth code to avoid HAProxy crash.

Thanks for any help!

**Comment by TimWolla** [comment]
> When can I expect that 2.1.5 will appear on hub.docker.com?

Once this PR is merged: docker-library/official-images#8105

**Comment by StanleyP** [comment]
My latest finding regarding this issue is that I finally managed to isolate the problem into the minimal lua code + haproxy.cfg + official haproxytech/haproxy-debian:2.0 image (will post it after some further experiments). I created docker-compose.yml to easily start haproxy instance that crashes after single http request. I am testing this on Ubuntu Server 18.04 and it crashes every time.
What REALLY surprised me that I tested this same setup on Centos7 and IT DOES NOT CRASH, on Centos7 everything works OK.

Do you have any hints what Ubuntu 18.04 OS settings might cause this issue? Do you have any other reports of HAProxy crashing on Ubuntu 18.04?

Thanks for any help!

**Comment by StanleyP** [comment]
[crash.zip](https://github.com/haproxy/haproxy/files/4718094/crash.zip)
Attached is file `crash.zip` with docker-compose.yml, lua code and haproxy.cfg that after it starts can be crashed by simple curl http://localhost.

The crash only occurs on Ubuntu Server 18.04-LTS and 19.10 both on my local laptop (X1 Carbon 6th gen) and in Azure.

Works OK on Centos7 and Debian-10-buster.

To start please have docker and docker-compose installed. Unpack crash.tgz into any directory and from this directory run `docker-compose up`.

```
$ docker-compose up
Starting haproxy ... done
Attaching to haproxy
haproxy    | [WARNING] 153/143907 (1) : config : log format ignored for proxy 'default' since it has no log address.
haproxy    | [NOTICE] 153/143907 (1) : New worker #1 (6) forked
```

After that make HTTP request to haproxy by `curl http://localhost` and you'll see the crash:

```
haproxy    | [debug] 153/143917 (6) : loop
haproxy    | [debug] 153/143917 (6) : pool empty
haproxy    | [debug] 153/143917 (6) : going to new_conn
haproxy    | [debug] 153/143922 (6) : redis_pool: sentinel connection failed
haproxy    | [debug] 153/143922 (6) : going to sleep
haproxy    | [debug] 153/143922 (6) : loop
haproxy    | [debug] 153/143922 (6) : pool empty
haproxy    | [debug] 153/143922 (6) : going to new_conn
haproxy    | [ALERT] 153/143923 (6) : A bogus STREAM [0x563137ca39e0] is spinning at 279034 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x563137ca39e0 src=127.0.0.1 fe=default be=default dst=unknown rqf=40080000 rqa=30 rpf=80000000 rpa=0 sif=EST,200008 sib=INI,10 af=(nil),0 csf=0x563137ca7aa0,4000 ab=(nil),0 csb=(nil),0 cof=0x563137ca6ff0,80201306:H1(0x563137ca71a0)/RAW((nil))/tcpv4(12) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) ]
haproxy    | [ALERT] 153/143923 (1) : Current worker #1 (6) exited with code 134 (Aborted)
haproxy    | [ALERT] 153/143923 (1) : exit-on-failure: killing every processes with SIGTERM
haproxy    | [WARNING] 153/143923 (1) : All workers exited. Exiting... (134)
haproxy exited with code 134
```

Any ideas?

**Comment by TimWolla** [comment]
I was able to further trim down your example to the following:

```
[timwolla@/s/haproxy (master) [134]]./haproxy -vv                                                                                                                                                           17:44:30
HA-Proxy version 2.2-dev8-975564-40 2020/05/31 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.4.0-179-generic #209-Ubuntu SMP Fri Apr 24 17:48:44 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_LUA=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL +LUA +FUTEX +ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with gcc compiler version 5.4.0 20160609
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
```

```
global
	lua-prepend-path /tmp/crasher/?.lua
	lua-load /tmp/crasher/main.lua

listen default
	mode http
	bind :8080
	http-request lua.crash
```

main.lua
```
local function crash(txn)
  local my_pool = require "redis_pool".new(
    "10.100.100.100",
    6379,
    "redis123",
    20
  )
  local conn
  conn = my_pool:get(1000)
end

core.register_action('crash', {'http-req'}, crash, 0)
```

redis_pool.lua
```
-- vim: tabstop=2 shiftwidth=2 expandtab

-- redis_pool : Add connection pool to the Lua Redis library
-- 
-- Copyright 2018 Thierry Fournier 
--
-- This lib is compliant with HAProxy cosockets
--

local redis_pool = {}

redis_pool.new = function(sentinel_ip, sentinel_port, master_auth, pool_sz, master_group)
  local r = {}
  r.sentinel_ip = sentinel_ip
  r.sentinel_port = sentinel_port
  r.nb_max = pool_sz
  r.nb_cur = 0
  setmetatable(r, redis_pool.meta);
  return r
end

redis_pool.meta = {}
redis_pool.meta.__index = {}
redis_pool.meta.__index.new_conn = function(r)
  local sock = core.tcp()
  sock:settimeout(5)
  if sock:connect(r.sentinel_ip, r.sentinel_port) == nil then
    sock:close()
    core.Debug("redis_pool: sentinel connection failed")
    return nil
  end
end

redis_pool.meta.__index.get = function(r, wait)
  local tspent = 0
  local conn
  while true do
    core.Debug("loop")

    -- Slot available: create new connection
    if r.nb_cur < r.nb_max then
      core.Debug("going to new_conn")
      conn = r:new_conn()
      if conn ~= nil then
        return conn
      end
    end

    core.Debug("going to sleep")
    -- no slot available wait a while
    core.msleep(50)
    tspent = tspent + 50
    if tspent >= wait then
      return nil
    end
  end
end

return redis_pool
```

```
$ ./haproxy -f /tmp/crasher/haproxy.cfg -d
[WARNING] 153/174655 (23936) : config : missing timeouts for proxy 'default'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
Note: setting global.maxconn to 524276.
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
Using epoll() as the polling mechanism.
00000000:default.accept(0004)=0010 from [127.0.0.1:58348] ALPN=<none>
00000000:default.clireq[0010:ffffffff]: GET / HTTP/1.1
00000000:default.clihdr[0010:ffffffff]: host: localhost:8080
00000000:default.clihdr[0010:ffffffff]: user-agent: curl/7.47.0
00000000:default.clihdr[0010:ffffffff]: accept: */*
[debug] 153/174658 (23936) : loop
[debug] 153/174658 (23936) : going to new_conn
00000001:LUA-SOCKET.clicls[ffffffff:0011]
00000001:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174658 (23936) : redis_pool: sentinel connection failed
[debug] 153/174658 (23936) : going to sleep
[debug] 153/174658 (23936) : loop
[debug] 153/174658 (23936) : going to new_conn
00000002:LUA-SOCKET.clicls[ffffffff:0011]
00000002:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174658 (23936) : redis_pool: sentinel connection failed
[debug] 153/174658 (23936) : going to sleep
[debug] 153/174658 (23936) : loop
[debug] 153/174658 (23936) : going to new_conn
00000003:LUA-SOCKET.clicls[ffffffff:0011]
00000003:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174658 (23936) : redis_pool: sentinel connection failed
[debug] 153/174658 (23936) : going to sleep
[debug] 153/174658 (23936) : loop
[debug] 153/174658 (23936) : going to new_conn
00000004:LUA-SOCKET.clicls[ffffffff:0011]
00000004:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174658 (23936) : redis_pool: sentinel connection failed
[debug] 153/174658 (23936) : going to sleep
[debug] 153/174658 (23936) : loop
[debug] 153/174658 (23936) : going to new_conn
00000005:LUA-SOCKET.clicls[ffffffff:0011]
00000005:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174658 (23936) : redis_pool: sentinel connection failed
[debug] 153/174658 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
00000006:LUA-SOCKET.clicls[ffffffff:0011]
00000006:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174659 (23936) : redis_pool: sentinel connection failed
[debug] 153/174659 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
00000007:LUA-SOCKET.clicls[ffffffff:0011]
00000007:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174659 (23936) : redis_pool: sentinel connection failed
[debug] 153/174659 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
00000008:LUA-SOCKET.clicls[ffffffff:0011]
00000008:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174659 (23936) : redis_pool: sentinel connection failed
[debug] 153/174659 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
00000009:LUA-SOCKET.clicls[ffffffff:0011]
00000009:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174659 (23936) : redis_pool: sentinel connection failed
[debug] 153/174659 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
0000000a:LUA-SOCKET.clicls[ffffffff:0011]
0000000a:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174659 (23936) : redis_pool: sentinel connection failed
[debug] 153/174659 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
0000000b:LUA-SOCKET.clicls[ffffffff:0011]
0000000b:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174659 (23936) : redis_pool: sentinel connection failed
[debug] 153/174659 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
0000000c:LUA-SOCKET.clicls[ffffffff:0011]
0000000c:LUA-SOCKET.closed[ffffffff:0011]
[debug] 153/174659 (23936) : redis_pool: sentinel connection failed
[debug] 153/174659 (23936) : going to sleep
[debug] 153/174659 (23936) : loop
[debug] 153/174659 (23936) : going to new_conn
[NOTICE] 153/174659 (23936) : haproxy version is 2.2-dev8-975564-40
[NOTICE] 153/174659 (23936) : path to executable is ./haproxy
[ALERT] 153/174659 (23936) : A bogus STREAM [0x16f0010] is spinning at 101019 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x16f0010 src=127.0.0.1 fe=default be=default dst=unknown rqf=40080000 rqa=30 rpf=80000000 rpa=0 sif=EST,200008 sib=INI,10 af=(nil),0 csf=0x1688410,c000 ab=(nil),0 csb=(nil),0 cof=0x1688060,1300:H1(0x1688290)/RAW((nil))/tcpv4(16) cob=(nil),0:NONE((nil))/NONE((nil))/NONE(0) filters={}]
fish: Job 1, './haproxy -f /tmp/crasher/hapro…' terminated by signal SIGABRT (Abort)
```

**Comment by capflam** [comment]
Thanks @wdauchy, it is really useful ! I'm able to reproduce the bug now. The request's analyse expiration timeout (`req.analyse_exp`) is never reset by the lua. So it is set by the call to `core.msleep()` when the first connect fails. Then the second connect yields. At this step, because `req.analyse_exp` was not reset, the task timeout is set in past. This induces a loop.

**Comment by wtarreau** [comment]
@capflam you're dealing with too many issues at once, wdauchy is in another one (closely related but without Lua) :-)  I'd love it if his also hits analyse_exp though!

**Comment by capflam** [comment]
@wtarreau, I don't think so,  `analyse_exp` is set to 0, both for the request and the response...

BTW, here is a quick patch. It should fix the bug : [0001-BUG-MEDIUM-lua-Reset-analyse-expiration-timeout-befo.patch.txt](https://github.com/haproxy/haproxy/files/4718602/0001-BUG-MEDIUM-lua-Reset-analyse-expiration-timeout-befo.patch.txt)

@wtarreau, I also noticed the channel flag CF_ANA_TIMEOUT is never removed. I guess is should be, probably at the same place. Because today, this flag is set after the first expiration and never removed. It seems to have no impact, but it is confusing. I must check, but it may be true for the inspect delay too.

**Comment by StanleyP** [comment]
Thanks for the patch! It applies cleanly to 2.2 branch, but unfortunately does not apply neither to 2.0 nor to 2.1 :( Any hope/chance to get patch for stable branch (2.0 or 2.1)? We have big release coming in couple days and I dont want to use unstable branch for production.

I modified the lua code to avoid multiple connection attempts that triggered the bug. So far the crash did not occur so maybe this is sufficient for now, but definitely looking for proper fix in 2.0 or 2.1.

**Comment by capflam** [comment]
Here is the patch for the 2.1. It should apply cleanly to 2.0 too.

[0001-BUG-MEDIUM-lua-Reset-analyse-expiration-timeout-befo-V2.1.patch.txt](https://github.com/haproxy/haproxy/files/4721295/0001-BUG-MEDIUM-lua-Reset-analyse-expiration-timeout-befo-V2.1.patch.txt)

**Comment by StanleyP** [comment]
Thanks a lot for help, you guys are the best!
I patched 2.0.14 a rolled it to DEV, TEST and UAT.
So far it works flawlessly!

Do you have any estimation when the official patch will be done and in what haproxy stable release will this fix appear?

**Comment by capflam** [comment]
Ok, Thanks. I'll push the patch this morning and backport it to 2.1 at least. It will be shipped with the next stable release (2.1 or 2.0) because before a release all pending backports are performed. But I don't know when we will do it.

**Comment by StanleyP** [comment]
Great news, thanks again! Will be looking forward for the next stable release then.

**Comment by wtarreau** [comment]
I'd like to diagnose wdauchy's report of looping streams in 2.2-dev to see if it's an older bug that's triggered in 2.2 or just a new regression, and after that it would be worth issuing a new set of stable versions to celebrate the death of these annoying bugs.
