### ISSUE TITLE
"show map" command return wrong value on haproxy 1.9.x

### ISSUE THREAD

**Issue by tasavi** [haproxy/haproxy#664]
## Output of `haproxy -vv` and `uname -a`

```
haproxy -vv
HA-Proxy version 1.9.15 2020/04/02 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_DL=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with PCRE version : 7.8 2008-09-05
Running on PCRE version : 7.8 2008-09-05
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

uname -a
Linux SI8221-130 2.6.32-754.17.1.el6.x86_64 #1 SMP Tue Jul 2 12:42:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

## What's the configuration?

```
haproxy.cfg

global

    log             127.0.0.1    local2    info
    pidfile         /var/run/haproxy.pid
    maxconn         500000
    tune.bufsize    16384
    user            haproxy
    group           haproxy
    daemon
    unix-bind       prefix /var/run/    mode 660    user haproxy group haproxy
    spread-checks   5s

    nbproc          2
    nbthread        20

    cpu-map         1/all   0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38
    cpu-map         2/all   1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39

    stats socket        /var/run/haproxy.stat1  process 1       level admin
    stats socket        /var/run/haproxy.stat2  process 2       level admin

    server-state-file   /etc/haproxy/server_state

    # LUA_load
    lua-load            /etc/haproxy/lua-LiveTsCounter.lua

...
skip
...
    http-response   lua.LiveTsCounter               if      { capture.req.uri -m sub .ts } { status 200 } { var(txn.req_host),lower,map_beg(/etc/haproxy/LiveTsCountDomain.map) -m found }
...
skip
...


/etc/haproxy/lua-LiveTsCounter.lua

data_map = "/etc/haproxy/LiveTsCounter.map"
ts_count_data = Map.new(data_map, Map.str);
...
skip
...

local channel_count = ts_count_data:lookup(channel_key)

		if channel_count == nil then
			core.log(core.debug,"[debug]Domain: "..host..", Channel: "..channel..", Count: not found")
			channel_count = 0
		else
			core.log(core.debug,"[debug]Domain: "..host..", Channel: "..channel..", Count: "..channel_count)
		end

		channel_count = tonumber(channel_count) + 1
		if channel_count > max_count then
			channel_count = 1
		end
		channel_count = tostring(channel_count)

		core.set_map(data_map, channel_key, channel_count)	
		core.log(core.info,"[debug]TS Data Update - Domain: "..host..", Channel: "..channel..", Count: "..channel_count)
...

```

## Steps to reproduce the behavior

1. request .ts file continually to work lua get and set data fo map
2. run "show map" to get map data (echo "show map /etc/haproxy/LiveTsCounter.map")
3. check returned key and value are correct

## Actual behavior

# case1

"show map" command returns an unexpected string instead of a number.

> 0x7f63ba6da4b0 hls-m.example.com/ad1 À<91>^\ºc^?
> 0x7f63b1094480 hls-m.example.com/ad1/ad1.smil 27956
> 0x7f63cdf5c0e0 hls-m.example.com/ad1/ad1.smil/b496000 1358
> 0x7f63b10a2500 hls-m.example.com/ad1/ad1.smil/b1328000 3632
> 0x7f63b10937a0 hls-m.example.com/ad1/ad1.smil/b2692000 22966
> 0x7f63ba6ea960 hls-m.example.com/ad1/ad1_300.stream 8774
> 0x7f63b0ed1010 hls-m.example.com/ad1/ad1_800.stream 197021
> 0x7f63ba6d0780 hls-m.example.com/ad1/ad1_2000.stream 60520

### bug
> 0x7f63ba6da4b0 hls-m.example.com/ad1 À<91>^\ºc^?

### the value must be a number in my map data.
---
# case2.
"show map" command returns a key without a value.

example

>     0x1cafa70 hls-m.example.com/ad5 370954
>     0x7f23f8f48150 hls-m.example.com/ad5/ad5.smil 44122
>     0x7f23f8f48480 hls-m.example.com/ad5/ad5.smil/b496000 1152
>     0x1cae3e0 hls-m.example.com/ad5/ad5.smil/b1328000 11444
>     0x1cafc70 hls-m.example.com/ad5/ad5.smil/b2692000 31526
>     0x7f23f8f245d0 hls-m.example.com/ad5/ad5_300.stream 8230
>     0x7f23f8f4c3d0 hls-m.example.com/ad5/ad5_800.stream 229211
>     0x1ca19a0 hls-m.example.com/ad5/ad5_2000.stream 89391
>     0x1c9cf80 hls.example.com/ad5
>     0x1ca8520 hls.example.com/ad5/ad5_800.stream 115320
>     0x7f23f92ea300 hls.example.com/ad5/ad5_5000.stream 5005

### bug
0x1c9cf80 key "hls.example.com/ad5" exist, but no value.
>     0x1c9cf80 hls.example.com/ad5
If I run "show map" command once more, I can get correct value
>     0x1c9cf80 hls.example.com/ad5 120325

---
# case3.
"show map" command returns a value that looks like stripped from the origin.

example

> 0x22de590 hls-m.example.com/ad5 398640
> 0x7f0bb8bd79d0 hls-m.example.com/ad5/ad5.smil 48757
> 0x7f0bb8bd7c90 hls-m.example.com/ad5/ad5.smil/b496000 9070
> 0x7f0bb8bbcb10 hls-m.example.com/ad5/ad5.smil/b1328000 8868
> 0x7f0bd473dd30 hls-m.example.com/ad5/ad5.smil/b2692000 30819
> 0x22db280 hls-m.example.com/ad5/ad5_300.stream 9633
> 0x22de760 hls-m.example.com/ad5/ad5_800.stream 253635
> 0x7f0bb8bd7120 hls-m.example.com/ad5/ad5_2000.stream 86615
> 0x7f0bbd51d7f0 hls.example.com/ad5 1744
> 0x7f0bbd4e9ed0 hls.example.com/ad5/ad5_800.stream 163192
> 0x7f0bbd5b9970 hls.example.com/ad5/ad5_2000.stream 61
> 0x7f0bbd4eb310 hls.example.com/ad5/ad5_5000.stream 11147
> 0x186ad50 hls.example.com/ch4/ch4_800.stream 9643

### bug
0x7f0bbd51d7f0 key "hls.example.com/ad5" exist, but the value (1744) is striped from 174400.
163192 + 61 + 11147 = 174400
> 0x7f0bbd51d7f0 hls.example.com/ad5 1744

If I run "show map" command once more, I can get correct value
> 0x22de590 hls-m.example.com/ad5 398640
> 0x7f0bb8bd79d0 hls-m.example.com/ad5/ad5.smil 48757
> 0x7f0bb8bd7c90 hls-m.example.com/ad5/ad5.smil/b496000 9070
> 0x7f0bb8bbcb10 hls-m.example.com/ad5/ad5.smil/b1328000 8868
> 0x7f0bd473dd30 hls-m.example.com/ad5/ad5.smil/b2692000 30819
> 0x22db280 hls-m.example.com/ad5/ad5_300.stream 9633
> 0x22de760 hls-m.example.com/ad5/ad5_800.stream 253635
> 0x7f0bb8bd7120 hls-m.example.com/ad5/ad5_2000.stream 86615
> 0x7f0bbd51d7f0 hls.example.com/ad5 174400
> 0x7f0bbd4e9ed0 hls.example.com/ad5/ad5_800.stream 163192
> 0x7f0bbd5b9970 hls.example.com/ad5/ad5_2000.stream 61
> 0x7f0bbd4eb310 hls.example.com/ad5/ad5_5000.stream 11147
> 0x186ad50 hls.example.com/ch4/ch4_800.stream 9643

## Expected behavior

haproxy must return the correct value of map data when running the "show map" command.

## Do you have any idea what may have caused this?
"get map" and "set map" command work correct, but "show map" command has a bug.
## Do you have an idea how to solve the issue?
no.

**Comment by capflam** [comment]
Could you test the attached patch please ? I'm pretty sure it fixes the issue but a confirmation is still good. The patch is for HAProxy 1.9. But the bug exists on all versions supporting threads.

[0001-WIP-BUG-MEDIUM-hlua-Lock-pattern-reference-to-perfor.patch.txt](https://github.com/haproxy/haproxy/files/4724786/0001-WIP-BUG-MEDIUM-hlua-Lock-pattern-reference-to-perfor.patch.txt)

**Comment by tasavis** [comment]
hi. I applied the attached patch to one of the three haproxy servers. I'm running a test to see if the issue is occurring by making the same request on each haproxy. I'll check it out for a day and let you know.

**Comment by tasavis** [comment]
I tested it all day and had no problems with the patched haproxy server. I am sure the problem has been solved correctly.

**Comment by capflam** [comment]
Thanks, I'll push the patch.

**Comment by tasavis** [comment]
Thanks, Christopher.
