### ISSUE TITLE
Support for tcp_keepalive_{intvl,probes,time} parameters customization

### ISSUE THREAD

**Issue by miztake** [haproxy/haproxy#670]
## What should haproxy do differently? Which functionality do you think we should add?

haproxy can enable TCP keepalive with srvtcpka, clitcpka, or tcpka.
However, various parameters of TCP keepalive cannot be customized.

## What are you trying to do?

The default TCP keepalive parameter is too long.
Changing kernel parameters (net.ipv4.tcp_keepalive_*) affects other programs.
Therefore, haproxy should be able to customize the TCP keepalive parameters.

**Comment by wtarreau** [comment]
Do you think it would be enough to set them globally, just as is done for TCP buffers in the global section ? Because making it configurable per-proxy or even worse, per-listener and per-server would become a real pain to use for the vast majority of users.

**Comment by miztake** [comment]
@wtarreau,

I apologize for the late reply.

> Do you think it would be enough to set them globally, just as is done for TCP buffers in the global section ?

tcpka, clitcpka, and srvtcpka are all configurable not only in the defaults section but also in the frontend, backend, and listen sections.
Similarly, tcp_keepalive_{intvl,probes,time} parameters should be configurable in the defaults, frontend, backend and listen sections.
In addition, if there are 3 patterns of client side, server side, client + server side like tcpka, the specifications of all keepalive parameters can be unified.

Is there any problem with the following specifications?

  Parameter corresponding to tcp_keepalive_time.
  
   - tcpkatime    : configurable in the defaults, frontend, backend and listen sections
   - clitcpkatime : configurable in the defaults, frontend and listen sections
   - srvtcpkatime : configurable in the defaults, backend  and listen sections

  Parameter corresponding to tcp_keepalive_probes.

   - tcpkaprobes    : configurable in the defaults, frontend, backend and listen sections
   - clitcpkaprobes : configurable in the defaults, frontend and listen sections
   - srvtcpkaprobes : configurable in the defaults, backend  and listen sections

  Parameter corresponding to tcp_keepalive_intvl.

   - tcpkaintvl    : configurable in the defaults, frontend, backend and listen sections
   - clitcpkaintvl : configurable in the defaults, frontend and listen sections
   - srvtcpkaintvl : configurable in the defaults, backend  and listen sections

**Comment by miztake** [comment]
This prototype patch seems to work fine.

https://github.com/miztake/haproxy/commit/230d3413a354f8d5e85b8ab771b2b00ba38b9444

**Comment by git001** [comment]
@miztake 
Just a small suggestion for usability. Please can you use `parse_time_err()` so that the user can set the time with the common post-fixes as described in the doc.
[Time format](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#2.4)

for example, random example: https://github.com/haproxy/haproxy/blob/master/src/proto_tcp.c#L1785

**Comment by miztake** [comment]
@git001,

Thank you for your suggestion.
I rewrote the patch using parse_time_err().

https://github.com/miztake/haproxy/commit/4189f3f3319f3685ce2eda92654c5cd07b08ae46

Please comment if you have any problems with this patch.
If there are no other comments, I would proceed with writing the test code and modifying the documentation.

**Comment by wtarreau** [comment]
OK I think this looks reasonable.

I'd rather avoid the "-intvl" suffix as we're trying hard to avoid abbreviations which are harder to remember than complete names. Better use "-interval" for this. And "-time" is ambiguous. Maybe use "-start" or "-delay" ?

I'm OK in principle for merging this. Please add some doc and have a look at CONTRIBUTING to see how to properly format your patch so that it's seamlessly integrated. Thanks!

**Comment by miztake** [comment]
@wtarreau,

> I'd rather avoid the "-intvl" suffix as we're trying hard to avoid abbreviations which are harder to remember than complete names. Better use "-interval" for this. And "-time" is ambiguous. Maybe use "-start" or "-delay" ?

Thank you for your comment.
I will explain the background of naming these keywords:

I named these keywords to associate the kernel parameters below.
(See man 7 tcp)
 - net.ipv4.tcp_keepalive_intvl  --> tcpka-intvl
 - net.ipv4.tcp_keepalive_probes --> tcpka-probes
 - net.ipv4.tcp_keepalive_time   --> tcpka-time

I also considered following keywords to associate setsockopt(2) options below.
(See man 7 tcp)
 - TCP_KEEPINTVL --> tcpka-intvl
 - TCP_KEEPCNT   --> tcpka-cnt
 - TCP_KEEPIDLE  --> tcpka-idle

I think these names are user-oriented to make it easier for users to associate keywords with functionality.

If these names are still not suitable, I will accept your suggestion.

**Comment by wtarreau** [comment]
This was merged, closing now.
