### ISSUE TITLE
In multi-process modes, connections is unbalanced sometime.

### ISSUE THREAD

**Issue by lonnywong** [haproxy/haproxy#684]
## Output of `haproxy -vv` and `uname -a`

```
$ ./haproxy -vv
HA-Proxy version 2.0.14 2020/04/02 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_THREAD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

$ uname -a
Linux VM_1_162_centos 5.6.2-1.el7.elrepo.x86_64 #1 SMP Thu Apr 2 10:55:54 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
    daemon
    nbproc 4
    tune.maxaccept 1

defaults
    timeout client 10s
    timeout server 10s
    timeout connect 10s

listen test
    mode tcp
    bind *:6000
    server test 127.0.0.1:6001
```

## Steps to reproduce the behavior

1. start server
```
$ cat server.go
package main

import (
	"fmt"
	"net"
)

var connections = make(chan net.Conn, 65536)

func acceptConn(listener net.Listener) {
	for {
		conn, err := listener.Accept()
		if err != nil {
			fmt.Println(err)
			return
		}
		connections <- conn
	}
}

func closeAll() int {
	count := 0
	for {
		select {
		case conn := <-connections:
			conn.Close()
			count++
		default:
			return count
		}
	}
}

func main() {
	listener, err := net.Listen("tcp", "127.0.0.1:6001")
	if err != nil {
		fmt.Println(err)
		return
	}

	defer listener.Close()

	go acceptConn(listener)

	for {
		fmt.Print("enter to close all connections ...")
		fmt.Scanln()

		count := closeAll()
		fmt.Printf("%d connections has been closed\n", count)
	}
}

$ go run server.go
```

2. start haproxy
```
$ cat haproxy.cfg
global
    daemon
    nbproc 4
    tune.maxaccept 1

defaults
    timeout client 10s
    timeout server 10s
    timeout connect 10s

listen test
    mode tcp
    bind *:6000
    server test 127.0.0.1:6001

$ ./haproxy -f haproxy.cfg
```

3. start client
```
cat client.go
package main

import (
	"fmt"
	"net"
	"os/exec"
)

func main() {
	var connections []net.Conn

	for i := 0; i < 1000; i++ {
		conn, err := net.Dial("tcp", "127.0.0.1:6000")
		if err != nil {
			fmt.Println(err)
			return
		}
		connections = append(connections, conn)
	}

	cmd := exec.Command("sh", "-c", "netstat -tnap | grep haproxy | grep ESTABLISHED | awk '{print $7}' | sort | uniq -c")
	output, err := cmd.Output()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(output))

	fmt.Print("enter to close all connections ...")
	fmt.Scanln()

	for _, conn := range connections {
		conn.Close()
	}
}

$ go run client.go
```

## Actual behavior

```
     62 20887/./haproxy
      4 20888/./haproxy
   1148 20889/./haproxy
    786 20890/./haproxy
```

## Expected behavior

```
    500 20887/./haproxy
    500 20888/./haproxy
    500 20889/./haproxy
    500 20890/./haproxy
```

## Do you have any idea what may have caused this?
A process accept too many connections, while other processes have no chance to accept?

## Do you have an idea how to solve the issue?
In multi-process modes, is there a way to accept connections in turn?

**Comment by wtarreau** [comment]
This is totally expected and is a well-known limitation of any system where multiple processes are listening to the same socket. The right way to use multi-process is to create one socket per process, by duplicating the "bind" line for each process and appending "process X" at the end of the line so that the kernel will load-balance incoming connections.

The best way is to disable multi-process mode and use multi-threading instead (nbthread 4), which will allow haproxy to perform the internal load-balancing itself.

**Comment by lonnywong** [comment]
> This is totally expected and is a well-known limitation of any system where multiple processes are listening to the same socket. The right way to use multi-process is to create one socket per process, by duplicating the "bind" line for each process and appending "process X" at the end of the line so that the kernel will load-balance incoming connections.
> 
> The best way is to disable multi-process mode and use multi-threading instead (nbthread 4), which will allow haproxy to perform the internal load-balancing itself.

I test multi-process mode, it's not so bad.

```c
// myproxy.c
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>
#include <arpa/inet.h>
#include <sys/epoll.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>

#define MAX_EVENTS 1024

int loop(int server_fd) {
    struct sockaddr_in client_addr;
    socklen_t client_len = sizeof(client_addr);

    char buf[20];
    int len = snprintf(buf, sizeof(buf), "%d", getpid());

    int epoll_fd = epoll_create1(0);
    if (epoll_fd < 0) {
        perror("epoll_create1");
        return 101;
    }

    struct epoll_event ev, events[MAX_EVENTS];
    ev.events = EPOLLIN | EPOLLET;
    ev.data.fd = server_fd;
    if (epoll_ctl(epoll_fd, EPOLL_CTL_ADD, server_fd, &ev) < 0) {
        perror("epoll_ctl");
        return 102;
    }

    while (1) {
        int nfds = epoll_wait(epoll_fd, events, MAX_EVENTS, -1);
        if (nfds < 0) {
            perror("epoll_wait");
            return 103;
        }

        for (int i = 0; i < nfds; i++) {
            if (events[i].data.fd == server_fd) {
                while (1) {
                    int client_fd = accept(server_fd, (struct sockaddr *) &client_addr, &client_len);
                    if (client_fd < 0) {
                        if (errno == EAGAIN) {
                            break;
                        } else {
                            perror("accept");
                            return 104;
                        }
                    }
                    ssize_t n = write(client_fd, buf, len);
                    if (n != len) {
                        perror("write");
                        return 105;
                    }
                    close(client_fd);
                }
            }
        }
    }

    return 0;
}

int main() {
    int server_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0) {
        perror("socket");
        return 1;
    }

    struct sockaddr_in server_addr;
    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = htonl(INADDR_ANY);
    server_addr.sin_port = htons(7000);

    if (bind(server_fd, (struct sockaddr *) &server_addr, sizeof(server_addr)) < 0) {
        perror("bind");
        return 3;
    }

    if (listen(server_fd, 1024) < 0) {
        perror("listen");
        return 4;
    }

    for (int i = 0; i < 4; i++) {
        pid_t pid = fork();
        if (pid == 0) {
            return loop(server_fd);
        }
    }

    return 0;
}
```

```go
// myclient.go
package main

import (
	"bufio"
	"fmt"
	"io/ioutil"
	"net"
)

func main() {
	var connections []net.Conn

	for i := 0; i < 1000; i++ {
		conn, err := net.Dial("tcp", "127.0.0.1:7000")
		if err != nil {
			fmt.Println(err)
			return
		}
		connections = append(connections, conn)
	}

	for _, conn := range connections {
		pid, err := ioutil.ReadAll(bufio.NewReader(conn))
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(string(pid))
		conn.Close()
	}
}
```

```sh
$ gcc -o myproxy myproxy.c
$ ./myproxy
$ go run myclient.go | sort | uniq -c
    252 22900
    240 22901
    251 22902
    257 22903
```

**Comment by lonnywong** [comment]
> This is totally expected and is a well-known limitation of any system where multiple processes are listening to the same socket. The right way to use multi-process is to create one socket per process, by duplicating the "bind" line for each process and appending "process X" at the end of the line so that the kernel will load-balance incoming connections.
> 
> The best way is to disable multi-process mode and use multi-threading instead (nbthread 4), which will allow haproxy to perform the internal load-balancing itself.

One process got 948 connections, while another process only got 2 connections. It's not work as as designed. 

I test 5 times, and I got this:
```sh
$ go run client.go
      5 20887/./haproxy
      2 20888/./haproxy
     45 20889/./haproxy
    948 20890/./haproxy

$ go run client.go
      2 20887/./haproxy
     54 20889/./haproxy
    944 20890/./haproxy

$ go run client.go
     17 20887/./haproxy
     15 20888/./haproxy
     22 20889/./haproxy
    946 20890/./haproxy

$ go run client.go
     22 20887/./haproxy
     12 20888/./haproxy
    312 20889/./haproxy
    654 20890/./haproxy

$ go run client.go
    120 20887/./haproxy
     51 20888/./haproxy
    282 20889/./haproxy
    547 20890/./haproxy
```

**Comment by lonnywong** [comment]
> > This is totally expected and is a well-known limitation of any system where multiple processes are listening to the same socket. The right way to use multi-process is to create one socket per process, by duplicating the "bind" line for each process and appending "process X" at the end of the line so that the kernel will load-balance incoming connections.
> > The best way is to disable multi-process mode and use multi-threading instead (nbthread 4), which will allow haproxy to perform the internal load-balancing itself.
> 
> One process got 948 connections, while another process only got 2 connections. It's not work as as designed.
> 
> I test 5 times, and I got this:
> 
> ```shell
> $ go run client.go
>       5 20887/./haproxy
>       2 20888/./haproxy
>      45 20889/./haproxy
>     948 20890/./haproxy
> 
> $ go run client.go
>       2 20887/./haproxy
>      54 20889/./haproxy
>     944 20890/./haproxy
> 
> $ go run client.go
>      17 20887/./haproxy
>      15 20888/./haproxy
>      22 20889/./haproxy
>     946 20890/./haproxy
> 
> $ go run client.go
>      22 20887/./haproxy
>      12 20888/./haproxy
>     312 20889/./haproxy
>     654 20890/./haproxy
> 
> $ go run client.go
>     120 20887/./haproxy
>      51 20888/./haproxy
>     282 20889/./haproxy
>     547 20890/./haproxy
> ```

I forgot to run the server.go , so It's not add up to 2000 connections as my first post.
```
     62 20887/./haproxy
      4 20888/./haproxy
   1148 20889/./haproxy
    786 20890/./haproxy
```

**Comment by wtarreau** [comment]
Your example is doing nothing between accept, proceeding like this doesn't scale well with connection rate. It is mandatory to run multiple accept() in batches for a single wakeup, which is what also causes the imbalance. In multi-process haproxy already reduces the batch lengths to force fairness. You can force haproxy to run into your single-accept mode by setting "tune.maxaccept 1". But I prefer to warn you that it's not efficient. Regardless you should really run in thread mode. Multi-process mode was created to address per-process FD limitations that affect some older systems.

**Comment by lonnywong** [comment]
> Your example is doing nothing between accept, proceeding like this doesn't scale well with connection rate. It is mandatory to run multiple accept() in batches for a single wakeup, which is what also causes the imbalance. In multi-process haproxy already reduces the batch lengths to force fairness. You can force haproxy to run into your single-accept mode by setting "tune.maxaccept 1". But I prefer to warn you that it's not efficient. Regardless you should really run in thread mode. Multi-process mode was created to address per-process FD limitations that affect some older systems.

Yes, I agree with you, the best way is run in thread mode. 

In my case, I only need to create thousands connections on the client startup, there is no more connections except that the client restart. I don't care about the efficient, and I am setting the "tune.maxaccept 1", but it seems not working. That's why I post this issue.

**Comment by Lix900** [comment]
We observed same behaviors in our system, often one process uses no CPU while other worker processes use >90% CPU.

**Comment by wtarreau** [comment]
OK. Anyway, while maxaccept 1 expects to significantly improve things, it
cannot fix the fundamental issue which is that if one process is working
while another one is idle, the idle one will easily have time to suck all
pending connections while the other one is busy. This is why having multiple
processes on a *single* socket is bad by design.

But if you really want to keep your nbproc for whatever reason, please at
least duplicate the bind lines to reserve one per process. This will work
because each process will only see the sockets that the kernel delivered
to it and cannot suck the ones delivered to other processes.

**Comment by lonnywong** [comment]
> OK. Anyway, while maxaccept 1 expects to significantly improve things, it cannot fix the fundamental issue which is that if one process is working while another one is idle, the idle one will easily have time to suck all pending connections while the other one is busy. This is why having multiple processes on a *single* socket is bad by design. But if you really want to keep your nbproc for whatever reason, please at least duplicate the bind lines to reserve one per process. This will work because each process will only see the sockets that the kernel delivered to it and cannot suck the ones delivered to other processes.

Do you mean duplicate the bind lines like this ?
```
global
    daemon
    nbproc 4
    tune.maxaccept 1

defaults
    timeout client 10s
    timeout server 10s
    timeout connect 10s

listen test
    mode tcp
    bind *:6000
    bind *:6000
    bind *:6000
    bind *:6000
    server test 127.0.0.1:6001
```

```sh
$ lsof -i:6000 -P
COMMAND   PID      USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
haproxy 22363 lonnywang    4u  IPv4 159540472      0t0  TCP *:6000 (LISTEN)
haproxy 22363 lonnywang    5u  IPv4 159540473      0t0  TCP *:6000 (LISTEN)
haproxy 22363 lonnywang    6u  IPv4 159540474      0t0  TCP *:6000 (LISTEN)
haproxy 22363 lonnywang    7u  IPv4 159540475      0t0  TCP *:6000 (LISTEN)
haproxy 22364 lonnywang    4u  IPv4 159540472      0t0  TCP *:6000 (LISTEN)
haproxy 22364 lonnywang    5u  IPv4 159540473      0t0  TCP *:6000 (LISTEN)
haproxy 22364 lonnywang    6u  IPv4 159540474      0t0  TCP *:6000 (LISTEN)
haproxy 22364 lonnywang    7u  IPv4 159540475      0t0  TCP *:6000 (LISTEN)
haproxy 22365 lonnywang    4u  IPv4 159540472      0t0  TCP *:6000 (LISTEN)
haproxy 22365 lonnywang    5u  IPv4 159540473      0t0  TCP *:6000 (LISTEN)
haproxy 22365 lonnywang    6u  IPv4 159540474      0t0  TCP *:6000 (LISTEN)
haproxy 22365 lonnywang    7u  IPv4 159540475      0t0  TCP *:6000 (LISTEN)
haproxy 22366 lonnywang    4u  IPv4 159540472      0t0  TCP *:6000 (LISTEN)
haproxy 22366 lonnywang    5u  IPv4 159540473      0t0  TCP *:6000 (LISTEN)
haproxy 22366 lonnywang    6u  IPv4 159540474      0t0  TCP *:6000 (LISTEN)
haproxy 22366 lonnywang    7u  IPv4 159540475      0t0  TCP *:6000 (LISTEN)
```

Seems not working :
```sh
$ go run client.go
   1908 22363/./haproxy
     30 22364/./haproxy
     58 22365/./haproxy
      4 22366/./haproxy

$ go run client.go
    618 22363/./haproxy
    206 22364/./haproxy
    626 22365/./haproxy
    550 22366/./haproxy

$ go run client.go
   1406 22363/./haproxy
    128 22364/./haproxy
    446 22365/./haproxy
     20 22366/./haproxy

$ go run client.go
   1096 22363/./haproxy
    240 22364/./haproxy
    416 22365/./haproxy
    248 22366/./haproxy

$ go run client.go
    566 22363/./haproxy
    258 22364/./haproxy
   1140 22365/./haproxy
     36 22366/./haproxy
```

**Comment by TimWolla** [comment]
> Do you mean duplicate the bind lines like this ?

You need to specify the [`process`](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#5.1-process) keyword.

**Comment by lonnywong** [comment]
> > Do you mean duplicate the bind lines like this ?
> 
> You need to specify the [`process`](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#5.1-process) keyword.

Thanks. It works.

```
$ cat haproxy.cfg
global
    daemon
    nbproc 4
    tune.maxaccept 1

defaults
    timeout client 10s
    timeout server 10s
    timeout connect 10s

listen test
    mode tcp
    bind *:6000 process 1
    bind *:6000 process 2
    bind *:6000 process 3
    bind *:6000 process 4
    server test 127.0.0.1:6001
```

```
$ lsof -i:6000 -P
COMMAND  PID      USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
haproxy 8245 lonnywang    4u  IPv4 159832757      0t0  TCP *:6000 (LISTEN)
haproxy 8246 lonnywang    5u  IPv4 159832758      0t0  TCP *:6000 (LISTEN)
haproxy 8247 lonnywang    6u  IPv4 159832759      0t0  TCP *:6000 (LISTEN)
haproxy 8248 lonnywang    7u  IPv4 159832760      0t0  TCP *:6000 (LISTEN)
```

```
$ go run client.go
    464 8245/./haproxy
    474 8246/./haproxy
    476 8247/./haproxy
    586 8248/./haproxy

$ go run client.go
    488 8245/./haproxy
    516 8246/./haproxy
    498 8247/./haproxy
    498 8248/./haproxy

$ go run client.go
    528 8245/./haproxy
    504 8246/./haproxy
    458 8247/./haproxy
    510 8248/./haproxy

$ go run client.go
    466 8245/./haproxy
    500 8246/./haproxy
    528 8247/./haproxy
    506 8248/./haproxy

$ go run client.go
    474 8245/./haproxy
    488 8246/./haproxy
    482 8247/./haproxy
    556 8248/./haproxy
```

**Comment by Lix900** [comment]
Can we make this default? we have 24 cores in one of out systems.

```
  bind *:6000 process 1
    bind *:6000 process 2
    bind *:6000 process 3
    bind *:6000 process 4
```

or is there some option like 

```
    bind *:6000 process ALL
```
to achieve the same purpose?

**Comment by wtarreau** [comment]
No there is no such option. I started to work on something like this during 2.0 development and figured that it was not worth pursuing that direction given that we now have the multi-thread load balancing now that provides a smoother load balancing without the extra cost of having many listening sockets. Also, for those using tens of thousands of certificates, this method used to significantly increase the memory usage. I haven't completely given up o this approach but for now I don't see any benefit in it anymore. If we find a compelling reason later, I might revive this work.
