### ISSUE TITLE
Allow detailed SSL/TLS handshake error reporting

### ISSUE THREAD

**Issue by rustyx** [haproxy/haproxy#693]
From the documentation section **8.2.5, Error log format**, it seems the error log format is fixed (HAProxy version 2.1.0).

That complicates TLS client certificate errors logging and debugging, because in case of any error it does not log any details about the client certificate.

For example:

    10.2.0.41:56102 [14/Jun/2020:20:13:28.293] grpc_bk/1: SSL client certificate not trusted

What I would like to know:

* Which certificate was used (DN, SHA-1, serial, issuer)?
* Other handshake details such as the TLS version, key exchange, cipher, etc.

Hence hereby a feature request to either make error log format configurable or add the above mentioned details to the TLS error messages.

**Comment by wtarreau** [comment]
Making error log format configurable is close to impossible because the error log format is highly context-dependent and very often deeply technical. However I totally agree that the TLS error messages should be more detailed. I think there's already an issue about this.

Sadly, sometimes TLS errors are captured inside callbacks and can only be reported once the code returns. This complicates the retrieval of contextual information. But that's definitely something that needs to be improved anyway.

**Comment by 0x1a0b** [comment]
This please. 👍 

It's a pain to take a packet capture just to know the tls alarm id

**Comment by rongshengfang** [comment]
I would love to see this implemented as well 👍

**Comment by domdom82** [comment]
This! Would be great to have better logs in cases of TLS errors. Especially in mTLS cases where a client certificate might be bad, which we don't have control over on the proxy.

**Comment by wtarreau** [comment]
Rest assured that this pain is shared and several of us have already started looking closer into this. There are already some stats about TLS errors, but that's still insufficient :-/

**Comment by ionescurobert** [comment]
I have a fork where you will get client certificate details in case of tls errors.

For now following client certificate information were logged:

- SHA1
- Serial
- Issuer
- DN

Find it here: https://github.com/ionescurobert/haproxy

**Comment by wtarreau** [comment]
Thank you Robert. Sorry for not responding to your recent messages but we're all busy finalizing the current 2.4 release and it's quite hard to work both on polishing and review new features. Will get back to you soon.

**Comment by domdom82** [comment]
I think probably one of the lowest hanging fruits would be to include the verify code in the log message like so:
```
10.2.0.41:56102 [14/Jun/2020:20:13:28.293] grpc_bk/1: SSL client certificate not trusted (10)
```

Then I could go ahead and look it up at https://github.com/openssl/openssl/blob/master/include/openssl/x509_vfy.h.in#L206
to find out that it's `X509_V_ERR_CERT_HAS_EXPIRED` which would already be super helpful.

Meanwhile I will try to work around the issue by putting `crt-ignore-err all ca-ignore-err all` to my bind line and maybe call a lua script if `ssl_c_verify` is not `0`. Hope this helps.

**Comment by wlallemand** [comment]
Hello,

Some patches were merged today about this, 2 options are now useful to debug this:
- the `option httpslog` default log format https://github.com/haproxy/haproxy/commit/98b930d04329ccedbd85b1862f24e52933ba45e5
- the `option dontloglegacyconnerr` which use the log-format for error logs https://github.com/haproxy/haproxy/commit/4a6328f0666d6ab0739a819867f41896fdfb28cc

Don't hesitate to test them and to report your problems.

**Comment by ionescurobert** [comment]
Hello,

Most probably someone could review my changes
https://github.com/ionescurobert/haproxy

Maybe this could be also created as a patch somehow?

BR

William Lallemand ***@***.***> schrieb am Do., 29. Juli 2021,
16:58:

**Comment by wlallemand** [comment]
Sorry @ionescurobert, I thought someone already replied to you but that wasn't the case, your implementation does not meet our requirements, there were already ways to get the information you wanted with the SSL fetches. So we just needed to use theses ways. What was implemented is a way to emit a error log using the log-format, this way you could use the fetches already existing (ssl_fc_*, ssl_c_*) in your log-format. The fetches for the frontend connection should be working fine, we are still looking for a way of doing it for the backend connection. Please try the "option dontloglegacyconnerr" keyword with a customized log-format, it should meet your needs. Thanks!

**Comment by rustyx** [comment]
Just ran a quick test and don't fully understand the new log output.

Before:

`192.168.1.9:63889 [31/Jul/2021:18:00:16.283] test-fe/1: SSL client certificate not trusted`

After (with `option dontloglegacyconnerr`):

`192.168.1.9:49771 [31/Jul/2021:18:01:51.906] test-fe~ test-fe/<NOSRV> -1/-1/-1/-1/0 0 0 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>" 31/000000001417C086/20/0 TLSv1.3/TLS_AES_256_GCM_SHA384`

Now it's not even clear that the error was "SSL client certificate not trusted" :)

What does `31/000000001417C086/20/0` mean? It doesn't seem to match the client certificate hash, nor the serial...

**Comment by wlallemand** [comment]
@rustyx The configuration.txt documentation file was edited to explain the fields https://github.com/haproxy/haproxy/commit/98b930d04329ccedbd85b1862f24e52933ba45e5.

The following fields were added in the `option httpslog`:

```
17   conn_status '/' ssl_fc_hsk_err '/' ssl_c_err '/' ssl_c_ca_err  0/0/0/0
18   ssl_version '/' ssl_ciphers             TLSv1.3/TLS_AES_256_GCM_SHA384

```

You can then referer to the documentation of the mentionned sample fetches, some are new:

The conn_status fetch is https://github.com/haproxy/haproxy/commit/3d2093af9bec2b73ed285b967f434f6bc3b7af9b
The ssl_fc_hsk_err fetch is https://github.com/haproxy/haproxy/commit/7c6898ee4907e66c000a77ec32effd5acf1b99d8

So in your case:
``` 
31 | "SSL client certificate not trusted"
$ openssl errstr 000000001417C086
error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed
20 is the verify return code but I can't find a reliable documentation which is not the openssl sourcecode

```

**Comment by wlallemand** [comment]
FIY I just renamed `option dontloglegacyconnerr` to `option log-error-via-logformat` in 56f1f75.

**Comment by rustyx** [comment]
Ok thanks.

Wouldn't it be nice to log more human-readable errors so as to not have to decode them? I believe [`ERR_error_string`](https://www.openssl.org/docs/man1.1.1/man3/ERR_error_string.html) can help with that.

Also, it seems my primary question, *which* client certificate wasn't trusted (hash, CN or serial), remains unanswered?

**Comment by wlallemand** [comment]
> Wouldn't it be nice to log more human-readable errors so as to not have to decode them? I believe [`ERR_error_string`](https://www.openssl.org/docs/man1.1.1/man3/ERR_error_string.html) can help with that.

Sure, there is already the `ssl_fc_hsk_err_str` fetch for that https://github.com/haproxy/haproxy/commit/7c6898ee4907e66c000a77ec32effd5acf1b99d8. But we can't really put this by default.

 > Also, it seems my primary question, _which_ client certificate wasn't trusted (hash, CN or serial), remains unanswered?

Since you have the `option log-error-via-logformat` available, you can customize your log-format using the fetches for the client certificates (ssl_c_*) : https://cbonte.github.io/haproxy-dconv/2.5/configuration.html#ssl_c_serial

**Comment by rustyx** [comment]
> Since you have the option log-error-via-logformat available, you can customize your log-format using the fetches for the client certificates (ssl_c_*)

But `ssl_c_*` are all empty in case of an error.

Config:

`log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %[fc_conn_err_str]/%[ssl_fc_hsk_err_str]/%[ssl_c_err]/%[ssl_c_ca_err] CN=%{+Q}[ssl_c_s_dn],serial=%[ssl_c_serial,hex],hash=%[ssl_c_sha1,hex] %sslv/%sslc"`

Result:

`192.168.1.9:65118 [02/Aug/2021:12:47:46.468] test-fe~ test-fe/<NOSRV> -1/-1/-1/-1/0 0 0 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>" SSL client certificate not trusted/error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed/20/0 CN="",serial=-,hash=- TLSv1.3/TLS_AES_256_GCM_SHA384`

**Comment by wlallemand** [comment]
It's possible that the data is freed upon error for these fetches, this is still a work in progress and your configuration is something that should be working in the end, we'll take a look at this, thanks!

**Comment by wlallemand** [comment]
@rustyx the latest patch from @rlebreton should allow to log with your configuration

**Comment by rustyx** [comment]
@wlallemand cool, now indeed I can see which certificate failed validation.

`127.0.0.1:51060 [22/Aug/2021:15:41:34.047] test-fe~ test-fe/<NOSRV> -1/-1/-1/-1/0 0 0 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>" SSL client certificate not trusted/error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed/18/0 CN="/O=db2/CN=db2/C=XX",serial=91C3EE27912A6247,hash=52D2276FE35632F523922F155B1ECA77878A3890 TLSv1.3/TLS_AES_256_GCM_SHA384`

Just one query - there's still no way to define a custom TLS error log format, correct? `%[fc_conn_err_str]` is returning `"Success"` when there's no error, and also all the other TLS details are a bit verbose for the success log.

`127.0.0.1:51040 [22/Aug/2021:15:39:53.638] test-fe~ test-be/1 0/0/-1/-1/3007 503 217 - - SC-- 1/1/0/0/3 0/0 "GET /test HTTP/1.1" Success/-/0/0 CN="/CN=db1",serial=91EDEB8FBCC5C0F5,hash=9FBDCDEB7891BCBA7C4D4E1D7B5919CC6E37F33A TLSv1.3/TLS_AES_256_GCM_SHA384`

**Comment by wlallemand** [comment]
> Just one query - there's still no way to define a custom TLS error log format, correct? `%[fc_conn_err_str]` is returning `"Success"` when there's no error, and also all the other TLS details are a bit verbose for the success log.
> 
> `127.0.0.1:51040 [22/Aug/2021:15:39:53.638] test-fe~ test-be/1 0/0/-1/-1/3007 503 217 - - SC-- 1/1/0/0/3 0/0 "GET /test HTTP/1.1" Success/-/0/0 CN="/CN=db1",serial=91EDEB8FBCC5C0F5,hash=9FBDCDEB7891BCBA7C4D4E1D7B5919CC6E37F33A TLSv1.3/TLS_AES_256_GCM_SHA384`

There is no log-format for errors only, you could use  %[ssl_fc_hsk_err] instead of the str version, which will return a 0 in case of success. The errors strings are all the same anyway, and you can use `openssl errstr` to decode the one you don't know. Same for the errors in %[fc_conn_err] they are documented in configuration.txt

**Comment by wlallemand** [comment]
We could have a `log-format-error` keyword to set a log-format which will only be used in case of errors, I don't know if the architecture is suitable right now to achieve this, I should discuss this with the team.

**Comment by rlebreton** [comment]
You could also set the "dontlog-normal' option if you don't want success logs to be emitted. This way only the error logs will be sent. And they could be made much smaller by removing the ssl_fc_hsk_err_str fetch as @wlallemand suggested.

**Comment by wlallemand** [comment]
After discussing this with the team, we concluded that the proper way would be to remove the `option log-error-via-logformat` and replace it by a directive `error-log-format` which would take a log format in parameter.So we are going to implement this.

**Comment by rustyx** [comment]
I think the complexity here is that there are different "sources" of errors - TLS handshake with frontend, connection with the backend, TLS handshake with backend, etc., potentially requiring different formats. I wouldn't consider an HTTP 503 response due to a backend being unreachable as an error that should log all TLS details, for example.
If I look at the TLS error reporting as it previously was, it was just `"SSL client certificate not trusted"`, so there must have been this special format hardcoded for TLS errors. So a single `error-log-format` might be insufficient IMO.
Anyway for now we can even live with the current implementation, logging everything all the time.

**Comment by wlallemand** [comment]
This `error-log-format` will help to use a custom log format for what was described by **8.2.5, Error log format** in the documentation, it's an intermediate step which does not require to change the entire log architecture so it could be released with haproxy 2.5.

Using the same log-format for the frontend connection error and the traffic is quite confusing because most of the fields will be the same upon errors, you will have `<BADREQ>`, `<NOSRV>`,  0 and -1 everywhere... 

Having multiple log-format (and default ones)  per type of errors could be something we could have in the future, but we can't define a log-format per class of error currently.

> If I look at the TLS error reporting as it previously was, it was just `"SSL client certificate not trusted"`, so there must have been this special format hardcoded for TLS errors. So a single `error-log-format` might be insufficient IMO.

In fact there are hard-coded strings for each connection errors, not only SSL, but everything related to the handshake, it's now available in the `fc_conn_err` and `fc_conn_err_str` sample fetches, you can have the list of errors and the related strings in doc/configuration.txt.

**Comment by carlosjpr-collab** [comment]
> Hello,
> 
> Some patches were merged today about this, 2 options are now useful to debug this:
> 
> * the `option httpslog` default log format [98b930d](https://github.com/haproxy/haproxy/commit/98b930d04329ccedbd85b1862f24e52933ba45e5)
> * the `option dontloglegacyconnerr` which use the log-format for error logs [4a6328f](https://github.com/haproxy/haproxy/commit/4a6328f0666d6ab0739a819867f41896fdfb28cc)
> 
> Don't hesitate to test them and to report your problems.

where we can add in  these options. which section of haproxy config ? 

we added it in front and I see 
`unknown option 'httpslog'; did you mean 'httplog' maybe`
docker image used `2.5-dev13-bullseye`

**Comment by rlebreton** [comment]
I just tried it and did not have any problem defining an "option httpslog" in a frontend. Could you share the part of your configuration that raises the error please ?

To answer your first question, this option can be specified in a frontend, a listener or a defaults section. It should work the same way as the other log options (httplog and tcplog).

**Comment by wlallemand** [comment]
I'm closing this since the feature is now implemented:
- `option httpslog` allows more details on HTTPS requests logs
- `error-log-format` allows to customize the error logs, giving you the opportunity to log SSL errors here
