### ISSUE TITLE
Documentation (v1.9+) needs to be updated

### ISSUE THREAD

**Issue by monteiz** [haproxy/haproxy#697]
Hi everybody,
the [first chapter of the official documentation](https://cbonte.github.io/haproxy-dconv/2.1/configuration.html#1.1) needs to be updated, as from HAProxy v.1.9 it became possible to forward HTTP/2 requests to other servers.

Specifically, as @lukastribus [confirms](https://discourse.haproxy.org/t/doubt-about-the-2-1-documentation-http-2/5281/2?u=monteiz), this is the paragraph that should be updated:

> For HTTP/2, the connection mode resembles more the "server close" mode : given
> the independence of all streams, there is currently no place to hook the idle
> server connection after a response, so it is closed after the response. HTTP/2
> is only supported for incoming connections, not on connections going to
> servers.

**Comment by wtarreau** [comment]
Yes, and I have in my todo list to finish to lift up such docs for the 2.2 release. We've been significantly delayed by painful bugs, and I think some docs will be updated post-release and backported. But this example is a perfect one and it must be fixed.

Thanks for spotting it!

**Comment by monteiz** [comment]
@wtarreau Very glad to contribute to this fantastic project!

If I may give a suggestion, I would migrate the documentation from `.txt` files to markdown format (`.md` files). That would incredibly improve the readability of the documents.

**Comment by wtarreau** [comment]
Doc was updated in 2.2 and now backported as far as 1.9. Closing.
