### ISSUE TITLE
acl ... path_beg,url_dec doesn't do a prefix match

### ISSUE THREAD

**Issue by ghost** [haproxy/haproxy#698]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.19-1+deb10u2 2020/04/01
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-ap5Gic/haproxy-1.8.19=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_NS=1                                                                                                             

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
```

```
Linux vent 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```

## What's the configuration?

```
global
        log /dev/log daemon
defaults
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http
        log global
        mode http
        option dontlognull
        option forwardfor
        option httplog
        timeout client  50000
        timeout connect 5000
        timeout server  50000
backend varnish
        server localhost pawan:6081
frontend frontend
        bind *:8000
        default_backend varnish
        acl mailing_lists path_beg,url_dec /mailing_lists
        http-request deny if mailing_lists
```

## Steps to reproduce the behavior

1. curl http://localhost:8000/mailing_lists/anything

## Actual behavior

The request is allowed.

## Expected behavior

The request should be denied.

The request is denied, as expected, if you replace the acl with the following perfectly suitable work-around:
```
acl mailing_lists path,url_dec -m beg /mailing_lists
```
I also verified that request is denied, as expected, if the converter url_dec is removed so it's the combination that triggers the defect:
```
acl mailing_lists path_beg /mailing_lists
``` 
## Do you have any idea what may have caused this? 

path_beg,url_dec seems to be doing an exact string match instead of a prefix match.

## Do you have an idea how to solve the issue?

No.

**Comment by wtarreau** [comment]
It's not a bug and I'm pretty sure it's already documented as working like this. The thing is that all the `_beg`, `_reg` etc variants of a sample fetch only exist to ease ACL declaration, but are in fact just a default matching method applied to a common sample fetch method. Thus when you write `path_beg` it implements `path -m beg`. But when you modify the output and write `path_beg,url_dec`, you're in fact applying the `url_dec` converter onto the `path` output and uses that last expression element's default matching method. `url_dec` returns a string so it applies `-m str`. And it couldn't be differently, think about it, some converters will even change the output type (for example you wouldn't want a regex match to apply to an IP address nor a netmask to apply to an integer).

**Comment by wtarreau** [comment]
What could possibly be done however, would be to detect such expressions and to emit a warning suggesting how to fix them. This could be helpful I think, but it's not certain everyone would figure what to add instead.

**Comment by ghost** [comment]
Thanks for the detailed response.  I am sorry to waste your time.

The configuration guide (1.8) doesn't discuss any caveats in the path & url_dec sections.  It very well may be documented however I did not find it when I reviewed what seemed the relevant sections of the (excellent) documentation.  The ACL basic section says the following but seems different than you explained above:

> The default test method is implied by the output type of this sample fetch method. The ACL declinations can describe alternate matching methods of a same sample fetch method. 

Ideas are cheap so here are a few (I only wrote these as assertions to clearly communicate the ideas, they may very well all be bad):

1. (Some?) converters should not have a default match type but instead use the match type from the previous fetch method (source of data) not the last sub-condition.
2. Match type should be an artifact of the (whole) condition instead of sub-conditions.  This would be in line with the -m syntax.
3. Depreciate/remove the short cuts as they couple two unrelated concepts of fetch method and match type.  The way to roll this out would be to make -m a mandatory so configurations break instead of silently changing behavior.  Arguments that are mandatory would usually not be - options.

**Comment by TimWolla** [comment]
> What could possibly be done however, would be to detect such expressions and to emit a warning suggesting how to fix them. This could be helpful I think, but it's not certain everyone would figure what to add instead.

I'll relabel this issue 'type:doc' instead of bug + works as designed, because I agree that a warning could be helpful here.

**Comment by ghost** [comment]
From an end-user perspective (a) I am clearly asking for a prefix match when using path_beg (otherwise I would have used path), and (b) I cannot think of a valid use case where don't want to combine it with url_dec.  This may be the normal case and it was surprising to me.  With some help I figured how to capture the data but I didn't see a way to dump the match type when trying to figure out what was going on.

Updating the documentation is welcome.  I would argue that it makes it a known design defect.

The work-around is perfectly acceptable so this is not important in the scheme of things.

Thanks again.  I hope it helps.

**Comment by mr-manuel** [comment]
@allanwind can you maybe please also post how you solved it? I have the same issue and this is the first link on Google :)

**Comment by wtarreau** [comment]
I've finally added a small paragraph in the doc for this, we can now close.
