### ISSUE TITLE
Expose histogram metrics for response , total, connect and queue times rather than averages

### ISSUE THREAD

**Issue by primeroz** [haproxy/haproxy#699]
## What should haproxy do differently? Which functionality do you think we should add?

Haproxy prometheus metrics ( in 2.0+ ) seem to be a direct mapping of what the stats page always exposed. 

The following metrics, exposed as averages over 1024 requests, are not very useful as such in prometheus and instead a an [histogram](https://prometheus.io/docs/concepts/metric_types/#histogram) type metric would be ideal so to be able to calculate quantiles and such , this would also provide average 

This is one of my biggest reasons to be looking into replacing haproxy as our ingress controller in kubernetes because parsing the logs to expose this values as prometheus metrics is just too tedious and fragile.

This apply to the following metrics
```
| haproxy_backend_queue_time_average_seconds          | Avg. queue time for last 1024 successful connections.                    |
| haproxy_backend_connect_time_average_seconds        | Avg. connect time for last 1024 successful connections.                  |
| haproxy_backend_response_time_average_seconds       | Avg. response time for last 1024 successful connections. (0 for TCP)     |
| haproxy_backend_total_time_average_seconds          | Avg. total time for last 1024 successful connections.
| haproxy_server_queue_time_average_seconds          | Avg. queue time for last 1024 successful connections.                     |
| haproxy_server_connect_time_average_seconds        | Avg. connect time for last 1024 successful connections.                   |
| haproxy_server_response_time_average_seconds       | Avg. response time for last 1024 successful connections. (0 for TCP)      |
| haproxy_server_total_time_average_seconds          | Avg. total time for last 1024 successful connections. 
```
## What are you trying to do?

Be able to calculate response time percentiles on my backends.

**Comment by capflam** [comment]
See #398. Especially the comments.

**Comment by primeroz** [comment]
Closing this as #398 is already addressing it
