### ISSUE TITLE
1.8 and earlier: bo_putblk() miscounts the buffer's position

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#7]
This is an already diagnosed bug. It only affects 1.8 and earlier and *apparently* has no impact there, though the risk of misuse consecutive to the backport of a fix exists.

The function bo_putblk() does this at the end : 

```
        memcpy(b->p, blk, half);
        b->p = b_ptr(b, half);
        if (len > half) {
                memcpy(b->p, blk + half, len - half);
                b->p = b_ptr(b, half);
        }
```

This results in half (the wrapping point) being counted twice. The second one should have been : 

```
b->p = b_ptr(b, len - half)
```

Only checks use this function at the moment and these ones do not wrap so they are safe. 1.9 and later are not affected thanks to the buffer API changes. It's unknown if versions prior to 1.8 use this function in a more sensitive context.

**Comment by capflam** [comment]
I guess this will never be fixed. I'm closing now.
