### ISSUE TITLE
http-request return log-format file evaluation altering spacing of ASCII output/art

### ISSUE THREAD

**Issue by daniel-corbett** [haproxy/haproxy#701]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2-dev10 2020/06/19 - https://haproxy.org/
Status: development branch - not safe for use in production.

uname -a
Linux test #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

## What's the configuration?

```
global
    master-worker

listen custom
    bind :20200
    mode http
    http-request return status 200 content-type "text/html; charset=utf-8" lf-file test.txt if { path /bad }
    http-request return status 200 content-type "text/html; charset=utf-8" file test.txt if { path /good }

```

## Steps to reproduce the behavior

1. Add test.txt in current directory (attached)
2. Run haproxy `./haproxy -f haproxy.cfg -d`
3. `curl localhost:20200/good`
4. `curl localhost:20200/bad`

## Actual behavior
When requesting the path /good we see ASCII art is not displayed appropriately.
When requesting the path /bad we see that there are some spacing issues that cause the ASCII art to not display appropriately.

## Expected behavior
Requesting a file that is used within lf-file should preserve spacing.

## Do you have any idea what may have caused this?
Assuming some type of spacing manipulation

## Do you have an idea how to solve the issue?
Commenting out  this line:
https://github.com/haproxy/haproxy/blob/dc0936c2557b23adad140760d87d5c47ad203be9/src/log.c#L702

seems to fix the issue for me. Although, I'm not sure whether that is an appropriate fix.

Required test.txt attached below
[test.txt](https://github.com/haproxy/haproxy/files/4808150/test.txt)

**Comment by wtarreau** [comment]
I don't think we'd want to backport this, so let's close it now. If anyone disagrees we can reopen it.
