### ISSUE TITLE
contrib/spoa_server: fails to build with python2 libraries.

### ISSUE THREAD

**Issue by mjbnz** [haproxy/haproxy#702]
Granted, python2.7 is EOL, but the build system for spoa_server supports it. I've since moved to python3, but for the sake of completeness, I'll report the bug anyway.

Fix is very simple - adjust printf format specifier from `%d` to `%ld` [on this line of ps_python.c](https://github.com/haproxy/haproxy/blob/dc0936c2557b23adad140760d87d5c47ad203be9/contrib/spoa_server/ps_python.c#L69)

**Comment by wdauchy** [comment]
@mjbnz it should be fixed in the next v2.2 release. Otherwise you may test from HEAD of the repo.

Thanks for the report!

**Comment by capflam** [comment]
The fix has been backported to 2.2
