### ISSUE TITLE
could not configure HAProxy to connect to _nomad._http.service.consul 

### ISSUE THREAD

**Issue by maxadamo** [haproxy/haproxy#709]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.24-2ppa1~bionic 2020/04/02
Copyright 2000-2020 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-6UyvXR/haproxy-1.8.24=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-null-dereference -Wno-unused-label -Wno-stringop-overflow
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace

```
```
Linux prod-haproxy01 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
backend nomad
  mode http
  option httpchk GET /ui/servers
  http-check expect status 307
  timeout connect 10s
  timeout server 1m
  balance source
  server-template nomad 3 _nomad._http.service.<MY-DOMAIN> check inter 10s resolvers consul
```

the name resolution works as expected:

```
host -t SRV _nomad._http.service.<MY-DOMAIN>
_nomad._http.service.<MY-DOMAIN> has SRV record 1 1 4646 prod-nomad01.<MY-DOMAIN>.
_nomad._http.service.<MY-DOMAIN> has SRV record 1 1 4646 prod-nomad03.<MY-DOMAIN>.
_nomad._http.service.<MY-DOMAIN> has SRV record 1 1 4646 prod-nomad02.<MY-DOMAIN>.
```

## Actual behavior

backend is Down and in the logs I see either this:

```
Server nomad/nomad1 is DOWN, reason: Socket error, check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
```

or this:

```
Server nomad/nomad1 was DOWN and now enters maintenance (unspecified DNS error).
```

## Expected behavior

backend working, as in other stanzas where I am using server-template and SRV records

## Do you have any idea what may have caused this?

is the tag `_http` set in the SRV record by Nomad supposed to work with HAProxy `server-template`, or does it only work with `_tcp`? 

## Do you have an idea how to solve the issue?

n/a

**Comment by maxadamo** [comment]
see issue => https://github.com/hashicorp/nomad/issues/8250

**Comment by wdauchy** [comment]
@maxadamo what is present is your `resolvers consul` section? it can be useful for us to see the full config

**Comment by maxadamo** [comment]
hello @wdauchy 
below the content of consul section:
```
resolvers consul
  nameserver prod-consul <IPV4_ADDRESS_HERE>:8600
  resolve_retries 3
  timeout retry 1s
  hold nx 30s
  hold valid 5
  accepted_payload_size 512
```

**Comment by wdauchy** [comment]
thanks @maxadamo 
What is the answer of the following command:
```
dig @<IPV4_ADDRESS_HERE>:8600 srv _nomad._http.service.<MY-DOMAIN>
```
I'm wondering about the final size, does it go beyond 512 limit?

**Comment by maxadamo** [comment]
hi @wdauchy 
the option was `-p 8600`... below the result:

```
# dig @prod-consul01.<DOMAIN_HERE> -p 8600 srv _nomad._http.service.<DOMAIN_HERE>

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> @prod-consul01.<DOMAIN_HERE> -p 8600 srv _nomad._http.service.<DOMAIN_HERE>
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50949
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 4
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_nomad._http.service.<DOMAIN_HERE>. IN	SRV

;; ANSWER SECTION:
_nomad._http.service.<DOMAIN_HERE>. 5 IN	SRV	1 1 4646 prod-nomad03.<DOMAIN_HERE>.
_nomad._http.service.<DOMAIN_HERE>. 5 IN	SRV	1 1 4646 prod-nomad01.<DOMAIN_HERE>.
_nomad._http.service.<DOMAIN_HERE>. 5 IN	SRV	1 1 4646 prod-nomad02.<DOMAIN_HERE>.

;; ADDITIONAL SECTION:
prod-nomad03.node.<DOMAIN_HERE>. 5	IN TXT	"consul-network-segment="
prod-nomad01.node.<DOMAIN_HERE>. 5	IN TXT	"consul-network-segment="
prod-nomad02.node.<DOMAIN_HERE>. 5	IN TXT	"consul-network-segment="

;; Query time: 19 msec
;; SERVER: 2001:798:3::63#8600(2001:798:3::63)
;; WHEN: Sun Aug 09 21:14:26 UTC 2020
;; MSG SIZE  rcvd: 346
```

**Comment by wdauchy** [comment]
@bedis any idea regarding this v1.8 issue? From my point of view there is no known issue on v1.8 apart from this bugfix not yet released http://git.haproxy.org/?p=haproxy-1.8.git;a=commit;h=de06fc4c15f31777bba0b4414d9dde3911ab2615 but it less likely to be the issue here.

I might try to do a similar setup later this week to try to reproduce

**Comment by bedis** [comment]
There is something weird in the DNS response which might trigger a "DNS response error":
  `;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 4`
While I only see 3 records printed by dig on the output.

@maxadamo could you send me privately (bedis9 at gmail.com) a pcap of the DNS exchange between HAProxy and Consul?
I would also need you to:
- run HAProxy in debug mode from a cli and copy/paste me the messages displayed (can also be sent over my email)
- on a running process, execute the following command on the stats socket (runtime API): "show resolvers" and send me the output too

**Comment by bedis** [comment]
So it seems there is an OPT record in the additional section. Checking this right now :)

**Comment by bedis** [comment]
So, the DNS response is all valid and HAProxy parses it properly.
I need the debug messages and maybe the ouptut of a "show stats" too.

I'd like to know the consul + nomad versions too so I can try to reproduce the same setup in-house

**Comment by maxadamo** [comment]
@bedis 
Nomad version is: `0.11.3`
Consul version is: `1.8.0`
I'm sorry, how can I produce the debug messages? I also don't know what `show stats` is (where I can run this command)?

**Comment by bedis** [comment]
Bascically, HAProxy comes with a "runtime api" called "stats socket" in the configuration. If you don't have it, it would be good to enable it.
Then, you can issue commands against running HAProxy using `socat` tool, such as: `echo "show stat" | socat /var/run/haproxy.socket -`

**Comment by maxadamo** [comment]
@bedis I have sent both files to your email address

**Comment by bedis** [comment]
ok cool thx. I will process this asap

**Comment by bedis** [comment]
I have a nomad cluster and I am trying to reproduce this issue.

**Comment by bedis** [comment]
@maxadamo here is the output of my SRV response for my nomad UI:
I do have a single Nomad server in my cluster, but this should work the same. I did not see the address records (A/AAAA) in the additional section in your output.

    dig -p 8600 @nomad1.h.lo _nomad._http.service.dc1.consul -t srv
    ;; ANSWER SECTION:
    _nomad._http.service.dc1.consul. 0 IN   SRV     1 1 4646 0a2a0147.addr.dc1.consul.

    ;; ADDITIONAL SECTION:
    0a2a0147.addr.dc1.consul. 0     IN      A       10.42.1.71

**Comment by bedis** [comment]
Now, I created a frontend / backend for the nomad UI:

    frontend fe_nomad_ui
     bind 127.0.0.1:4646
     default_backend be_nomad_ui

    backend be_nomad_ui
     server-template nomad 5 _nomad._http.service.dc1.consul check resolvers consul

HAProxy can resolve this server:

    [WARNING] 337/152919 (4077310) : be_nomad_ui/nomad1 changed its IP from  to 10.42.1.71 by consul/consul.
    [WARNING] 337/152919 (4077310) : Server be_nomad_ui/nomad1 administratively READY thanks to valid DNS answer.
    [WARNING] 337/152919 (4077310) : Server be_nomad_ui/nomad1 ('0a2a0147.addr.dc1.consul') is UP/READY (resolves again).

**Comment by capflam** [comment]
I'm closing this issue. Feel free to reopen it if necessary. Thanks !

**Comment by maxadamo** [comment]
I can confirm that it's working with haproxy 2.4
