### ISSUE TITLE
Add BNF of config syntax to documentation

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#712]
Also I intend to add a section to the config documentation with a BNF of the config syntax, that would clearly help there! It'll just take quite some extra time.

_Originally posted by @wtarreau in https://github.com/haproxy/haproxy/issues/200#issuecomment-586405684_

**Comment by wtarreau** [comment]
Now done, closing. This will likely be backported to some stable branches as part of the usual doc backports.
