### ISSUE TITLE
HTTP Date field not present in http response from HAproxy

### ISSUE THREAD

**Issue by xcorp** [haproxy/haproxy#731]
## Output of `haproxy -vv` and `uname -a`

```
root@haproxy-test:/etc/haproxy# haproxy -vv
HA-Proxy version 2.0.13-2 2020/04/01 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-f5gtLl/haproxy-2.0.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

```

```
Linux haproxy-test 5.0.21-5-pve #1 SMP PVE 5.0.21-10 (Wed, 13 Nov 2019 08:27:10 +0100) x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http


frontend http_in
	bind *:80


	acl host_haproxy-test.lan  hdr(host) haproxy-test.lan

	redirect scheme https code 301 if !{ ssl_fc } host_haproxy-test.lan`

```

## Steps to reproduce the behavior

Haproxy config that returns a redirect to https

Have tested on stats backend with both http and https as well, none returned date header

## Actual behavior
HTTP response does not contain a date header

## Expected behavior
HTTP response MUST contain a date header according to https://tools.ietf.org/html/rfc2616#section-14.18

**Comment by git001** [comment]
2616 is obsolete.
[RFC 7231 7.1.1.2.  Date](https://tools.ietf.org/html/rfc7231#section-7.1.1.2) have also a MUST but only if a capable clock is available. Jm2c

```
   An origin server MUST NOT send a Date header field if it does not
   have a clock capable of providing a reasonable approximation of the
   current instance in Coordinated Universal Time.  An origin server MAY
   send a Date header field if the response is in the 1xx
   (Informational) or 5xx (Server Error) class of status codes.  An
   origin server MUST send a Date header field in all other cases.
```

**Comment by xcorp** [comment]
> 2616 is obsolete.
> [RFC 7231 7.1.1.2. Date](https://tools.ietf.org/html/rfc7231#section-7.1.1.2) have also a MUST but only if a capable clock is available. Jm2c
> 
> ```
>    An origin server MUST NOT send a Date header field if it does not
>    have a clock capable of providing a reasonable approximation of the
>    current instance in Coordinated Universal Time.  An origin server MAY
>    send a Date header field if the response is in the 1xx
>    (Informational) or 5xx (Server Error) class of status codes.  An
>    origin server MUST send a Date header field in all other cases.
> ```

In principle I can agree with you, but since HAProxy also does SSL client verification, which requires a clock afaik that argument is kinda moot.

**Comment by lukastribus** [comment]
Haproxy is not an origin server, the requirement therefor does not apply.

Other than RFC compliance, what is the actual problem you are trying to solve? Does this cause any interoperability issues anywhere? What is the real world impact?

**Comment by xcorp** [comment]
> Haproxy is not an origin server, the requirement therefor does not apply.
> 
> Other than RFC compliance, what is the actual problem you are trying to solve? Does this cause any interoperability issues anywhere? What is the real world impact?

Of course it's an origin server when doing redirects or serving the stats backend, who else would be?

The company where I work have a big fleet of embedded units without any battery due to regulations, and therefor have no persistent clock. They then piggy back on the date field to set the time. This worked fine before we switched over a clustered environment and Haproxy.

**Comment by lukastribus** [comment]
You are right, in corner cases like redirects, error pages or stats/admin backend, haproxy actually is the origin server. But that's not really the primary use-case of haproxy and your use-case is extremely niche, which is why this is the first time this comes up.

I will let @wtarreau comment on whether we treat this as a bug.

**Comment by capflam** [comment]
I don't know if we want to have by default dynamic messages for responses generated by HAProxy. I guess the vast majority of users don't care to have the Date header or not and prefer to not spend CPU for this.

Note that on the 2.2 (released today), it is possible to add headers in responses, including those generated by HAProxy, using http-after-response ruleset.

**Comment by wtarreau** [comment]
There are plenty of clock-less devices where haproxy is deployed and which, according to RFC7231, must not emit any date. Actually it's fun to see that the reason you want haproxy to send a date is to work abuse it to deliver a date to devices which don't have date and on which haproxy would be forbidden from sending a date if it were to run there.

I agree with @capflam above. Instead of making haproxy violate the standards for *every* user, you can have it emit a date for your non-standard purpose. I think it will look like:
`http-after-response add-header date %[date,http_date] if { status 300:399 } !{ res.hdr(date) -m found }`

**Comment by xcorp** [comment]
The solution proposed by @capflam is completely fine by me, I looked for something like that before opening this issue, but couldn't find it since the feature didn't exist. Thanks :)
