### ISSUE TITLE
haproxy 2.0.14 occasionally sends an empty http2 data frame with ES set which causes grpc failure at client side (rpc error: code = Internal desc = server closed the stream without sending trailers) 

### ISSUE THREAD

**Issue by xin-hedera** [haproxy/haproxy#736]
## Output of `haproxy -vv` and `uname -a`

```
root@483d9a2215ca:/# haproxy -vv
HA-Proxy version 2.0.14 2020/04/02 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

root@483d9a2215ca:/# uname -a
Linux 483d9a2215ca 5.3.0-1023-aws #25~18.04.1-Ubuntu SMP Fri Jun 5 15:18:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
    log 127.0.0.1 local0 err
    log stdout local0 warning
    maxconn 50000
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options ssl-min-ver TLSv1.1

defaults
    log global
    maxconn 3000
    mode http
    timeout connect 10s
    timeout client 30s
    timeout server 30s
    option httplog
    option http-use-htx
    option logasap

frontend fe_proxy
    mode http
    bind :3001 proto h2
    default_backend be_servers

backend be_servers
    mode http
    option http-use-htx
    server server1 "${HAPROXY_TARGET_IP}":50211 proto h2 check inter 10s downinter 10s observe layer4 error-limit 5 on-error mark-down
```

## Steps to reproduce the behavior

1. Run the benchmark client with high target tps (transaction per second) and large payload size, for instance, 2000 tps and 5k byte
2. At the same time, use tcpdump to capture traffic between the client and haproxy, as well as the traffic between haproxy and the backend server
3. After a while, usually around 5 minutes, the client will begin to report grpc code 13 error (rpc error: code = Internal desc = server closed the stream without sending trailers). It's occasional, for a long run, the stats is about 35 out of 4 million grpc calls.

## Actual behavior

I have uploaded two pcap files ([pcap.gz](https://github.com/haproxy/haproxy/files/4893915/pcap.gz)).

The problematic empty data frame is packet 177059 in client_proxy.pcap, which has 3 frames:

* HEADERS with http status 200 OK
* DATA which contains a grpc response message
* empty DATA with ES

File proxy_backend.pcap is the traffic between haproxy and the backend server. The corresponding stream between haproxy and the backend server is stream 3069 of the connection 172.20.0.2:43386 and 35.196.144.134:50211. The way to correlate the two streams is the grpc data sent by the client has a crypto signature, the first couple of bytes is "f7:da:f6:56:7b:82:a1:aa:cb:e1:e4:3c:59:eb:9a".

Stream 3069 is properly closed in packet 114863 with the following 3 frames:

* HEADERS with http status 200 OK
* DATA which contains a grpc response message
* HEADERS with ES set and grpc-status trailer

One thing to note is the backend server sent a GOAWAY with Promised Stream ID == 3069 in packet 114858, before closing stream 3069.

## Expected behavior

haproxy sends a HEADERS frame with the grpc-status trailer to properly close the http2 stream.
 

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

No.

**Comment by wtarreau** [comment]
An empty DATA frame with ES is perfectly normal and valid, it indicates that we've reached the end of the stream. It can for example correspond to the receipt of the zero-length chunk received over HTTP/1.1 on the other side, or the end of receipt of an H2 response.

What we need to figure is why the response was apparently truncated. It might be possible that the GOAWAY you captured caused the server-side H2 client to close its side for whatever reason and that this would have resulted in a truncated response.

**Comment by xin-hedera** [comment]
HTTP2 allows empty DATA frame with ES. However, grpc over http2 protocol mandates that for grpc response, empty DATA frame with ES is not allowed and it should end with a HEADERS frame with ES and the HEADERS frame should have the grpc-status header.

In addition to the GOAWAY, the TCP connection is reset by the backend server soon after it sent the HEADERS (http status 200) + DATA + HEADERS with ES and grpc-status header. This may be worth analyzing too.

**Comment by wtarreau** [comment]
Actually I'm looking at your trace, and there is a problem in the server's behavior: it closes with a TCP reset. One must never ever close a transfer with an RST after sending data because that destroys the data in the peer's socket buffers. So what happens here is logical and purely a timing issue: the server responds with the data and immediately sends an RST. Haproxy is woken up by the system when the first data get buffered, has a chance to read some of them, and on the subsequent recv() attempts it gets -1 ECONNRESET because the remaining ones were destroyed in the system, so all it gets is there. Now, it's important to note that we always deploy a lot of efforts to try to read as far as possible when facing such conditions because there are bogus servers here and there, and being able to try to catch the maximum is important.

Here what I *suspect* is that we performed a first recv() which collected the whole data (3 frames in 113 bytes at once), that the socket status already reported POLLERR or that the second recv() attempt returned -1 ECONNRESET so that we had to mark the error on the connection, that we went back into H2 to process what we had but that before processing the next frame we detected the error flag on the connection and aborted. If this is the case I suspect we could manage to go a bit further. But really, it's extremely difficult to continue while errors are present because at some point, errors really require to stop processing, and here the server definitely closes in error.

What I suspect based on your trace (very useful by the way) is that the server didn't read the WINDOW_UPDATE for stream 3067 that was sent immediately after the data for 3069, and that it didn't perform a shutdown() before closing, resulting in a close() causing the local TCP stack to emit an RST to reject the pending 8 unread bytes. With a normal shutdown(), a FIN would have been sent before the RST and haproxy wouldn't have received a socket error.

**Comment by wtarreau** [comment]
Note, if you want to try something absolutely ugly, you could try to hack the server to forcefully perform a shutdown() before each close(). Assuming the server is not run with a setuid/setgid and is not statically linked, you could try to achieve this using LD_PRELOAD like this:
```
// gcc -fPIC -shared -O2 -o shutclose.so shutclose.c
// LD_PRELOAD=$PWD/shutclose.so command args...

#include <asm/unistd.h>
#include <sys/socket.h>
#include <unistd.h>

int close(int fd)
{
        shutdown(fd, SHUT_WR);
        return syscall(__NR_close, fd);
}
```
Then once built, you start your server with it. With a bit of luck (i.e. if it accepts its calls being remapped by preloaded libs), you should see a FIN flag before seeing the RST and that should definitely help.

**Comment by xin-hedera** [comment]
Thank you Willy. We will look into our server config & implementation and change it to gracefully shutdown and retest it.

**Comment by bobymicroby** [comment]
@xin-hedera I am having exactly the same issues, did you manage to solve your problems somehow ?
