### ISSUE TITLE
enhance stats collection after a reload

### ISSUE THREAD

**Issue by wdauchy** [haproxy/haproxy#740]
Hello,

We have a recurrent issue with the usage of reload along with stats collection. We are collecting them through the builtin prometheus plugin. However, when you reload, haproxy waits for the end of long running connections, until `hard-stop-after` parameter if set. In our case `hard-stop-after` is set to a few minutes because we have long running connections using pipelining, which can be around for one hour. In the meantime, requests continues to flow in the older processes, but stats are collected only on the new process. It creates some confusion where you may sometimes feel you are treating less traffic than usual, particularly visible on the number of requests treated.

Maybe master process could play a role here, but I'm not even sure of this. It looks complicated enough to start a wider discussion about it. We are hoping this could be addressed in v2.3

**Comment by wlallemand** [comment]
I remember having this discussion at HAProxytech regarding the stats socket. Once a proxy is stopped we can't access the stats anymore, I think we could easily give access to the stats of a stopping process from the master CLI by changing a few things. However I have no idea how work the prometheus plugin, @capflam probably has a better understanding of the subject :-)

**Comment by wdauchy** [comment]
any thoughts @capflam ?

**Comment by wdauchy** [comment]
#954 will probably addressing that
cc @wtarreau
