### ISSUE TITLE
Build warning on Rpi4 for cfgparse.c

### ISSUE THREAD

**Issue by nrapopor** [haproxy/haproxy#747]
## Short preamble:

Trying to create a octoprint rpi4 with camera and supporting two printers... (this is where haproxy comes in) running two instances of octoprint and rerouting based on url prefix ...

I do not wish to build or use older versions -- no beading edge -- just latest stable.

* ubuntu 20.04 server:
  -  octoprint -- no problem
  -  haproxy -- no problem
  -  rpi camera -- big problem (no mmal library -- cant find the source to build )
* raspbian (10 == Debian buster)
  - octoprint -- no problem
  - haproxy -- Must build from source (the latest build I can find (armhf) is 1.9.x)
  - rpi camera -- no problem
              
So I grabbed the latest (stable) 2.2.0 and I'm not sure that this is an issue -- but I do not know your code so I'm bringing this to your attention.

Form filled in below

I did run validate a bunch of times.  

## Output of `haproxy -vv` and `uname -a`

uname -a
```
Linux octoprint 5.4.50-v7l+ #1324 SMP Wed Jul 1 17:06:14 BST 2020 armv7l GNU/Linux
```
haproxy -vv
```
HA-Proxy version 2.2.0 2020/07/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.0.html
Running on: Linux 5.4.50-v7l+ #1324 SMP Wed Jul 1 17:06:14 BST 2020 armv7l
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=32, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

```

## What's the configuration?

```
not relevant -- this is a build issue
```

## Steps to reproduce the behavior

1.  Download and unzip v2.2.0
2.  run: `make -j $(nproc) TARGET=linux-glibc USE_OPENSSL=1 USE_ZLIB=1 USE_LUA=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_SYSTEMD=1 LUA_LIB_NAME=lua5.3 LUA_INC=/usr/include/lua5.3` in the folder.
3.  Get the following:

```
...
 CC      src/backend.o
  CC      src/cfgparse.o
  CC      src/cli.o
src/cfgparse.c: In function 'check_config_validity':
src/cfgparse.c:3584:26: warning: argument 1 range [2147483648, 4294967295] exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
     newsrv->idle_conns = calloc((unsigned)global.nbthread, sizeof(*newsrv->idle_conns));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/cfgparse.c:24:
/usr/include/stdlib.h:541:14: note: in a call to allocation function 'calloc' declared here
 extern void *calloc (size_t __nmemb, size_t __size)
              ^~~~~~
  CC      src/cfgparse-listen.o
  CC      src/stats.o
  CC      src/http_ana.o
...

```

## Actual behavior

Build warning for an out of range argument 

## Expected behavior

Clean build

Please modify the code to prevent passing invalid `size_t` issue (I don't know why Rpi foundation insists on 32-bit OS when the world moved on but it is what it is)

## Do you have any idea what may have caused this?

lack of testing on armhf 

## Do you have an idea how to solve the issue?

Yes please fix the code -- perhaps casting as `unsigned` where `size_t` is expected not a good idea ... just saying ;-)

**Comment by wtarreau** [comment]
This one is extremely annoying because it's a gcc extremism with values domains. We actually had to put a few of these unsigned casts to shut it up, but it seems that since that it became even smarter and figured that some other values might be possible there! This is becoming totally ridiculous as the initial value is 1 to 32 or 1 to 64...

By the way we *do* test on armv7 (was tested with gcc 6.5 here, which doesn't seem to report this one). Also note that on 32-bits, size_t and unsigned are the same. Apparently the other call places without the cast are happy so we could simply drop it for this one. Could you please check ?

**Comment by wtarreau** [comment]
I just did that now and backported it to 2.2, hoping it does the job.

**Comment by TimWolla** [comment]
It looks like this broke stuff on amd64 (I was seeing this warning while building a Debian package for #758 using 2.2.0-18-g395b930f1):

```
src/cfgparse.c: In function 'check_config_validity':
src/cfgparse.c:3584:26: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
     newsrv->idle_conns = calloc(global.nbthread, sizeof(*newsrv->idle_conns));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/cfgparse.c:24:
/usr/include/stdlib.h:541:14: note: in a call to allocation function 'calloc' declared here
 extern void *calloc (size_t __nmemb, size_t __size)
              ^~~~~~
```

**Comment by wtarreau** [comment]
Yep sorry you met this one, I had it as well on gcc 7.3.0 (8.2.0 is fine). The rpi one is the most bogus one of all, so I turned the cast back but to an unsigned short to help it being less stupid. It's still amazing the compiler didn't complain about the previous and next assignments which are exactly the same!

**Comment by nrapopor** [comment]
Hi -- Yeah, you are right -- I've not built on 32-bit in some time. (why are we having this discussion at all -- why 32 bit, if I could find mmal library for arm64 for ubuntu ... I would have never known ... :-)  ).  -- will try to strip the cast on pi (gcc is 8.3.0) to test ...

**Comment by nrapopor** [comment]
yep took care of things for pi4 with gcc 8.3.0 ....
Thanks guys!

**Comment by nrapopor** [comment]
sorry for being imprecise --by strip the cast I mean changed it to unsigned short ....
