### ISSUE TITLE
Sample init.d script fails on network up check 

### ISSUE THREAD

**Issue by davesargrad** [haproxy/haproxy#748]
The provided sample init.d script fails in centos 7 at line 26.

![image](https://user-images.githubusercontent.com/48793689/87299870-d4c7cd00-c4da-11ea-83a5-3d32cc20eb44.png)

![image](https://user-images.githubusercontent.com/48793689/87299903-e315e900-c4da-11ea-9909-0dbab4335e96.png)

I see [this syntax](https://stackoverflow.com/a/13618376/2025407) referenced on stack. Is this actually a bug in the script, or is the script expected to work in certain environments?

**Comment by lukastribus** [comment]
You are not supposed to use the init.d script in the first place. CentOs 7 uses systemd, you are supposed to use the systemd unit file that ships with haproxy.

Also see:
https://discourse.haproxy.org/t/failing-to-start-with-systemd-and-unexplained-issues/849/4
