### ISSUE TITLE
verify host not working in peers section

### ISSUE THREAD

**Issue by ylafon** [haproxy/haproxy#753]
## Output of `haproxy -vv` and `uname -a`

```
haproxy -vv
HA-Proxy version 2.0.15-4f39279 2020/06/12 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = gcc
  CFLAGS  = -O2 -march=native -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_REGPARM=1 USE_OPENSSL=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

```
Linux sherri 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```
## What's the configuration?

```
peers ssopeers
	bind :1234 ssl crt /etc/ssl/private/wildcard-example.org-chain.pem
	default-server ssl force-tlsv13 verify required ca-file /etc/ssl/certs/example_ca_full.pem

	table sample type string len 128 size 100k expire 7d store gpc0,http_req_rate(1d),http_req_cnt,http_err_cnt

        server atlas 192.168.0.41:1234 verifyhost atlas.example.org 
        server circinus 192.168.0.13:1234 verifyhost circus.example.org 
        server gor 192.168.0.197:1234 verifyhost gor.invalid.invalid
        server sherri
        server terri 192.168.0.112:1234 verifyhost terri.example.org
```

## Steps to reproduce the behavior

All the peers share a wildcard cert for `example.org`, setting the `verifyhost` value to the `invalid.invalid` domain leads to
```
  0x5558be1d9f30: id=gor(remote) addr=192.168.0.197:1234 status=ESTA reconnect=3s confirm=0 tx_hbt=196 rx_hbt=194 no_hbt=1 new_conn=4 proto_err=0
        flags=0x20000000 appctx:0x7f2734016990 st0=7 st1=0 task_calls=390 state=EST
        xprt=SSL src=192.168.0.197:46642 addr=192.168.0.111:1234
```

## Actual behavior

See above, actual behaviour is connecting while `verifyhost` requirement is not met.

## Expected behavior

The connection should fail, as the name is not the right one.

**Comment by wtarreau** [comment]
Thanks Yves! Adding @haproxyFred and @EmericBr as they're probably the most likely ones to quickly figure what is missing there :-)

**Comment by haproxyFred** [comment]
Hello Yves,

I am not a TLS expert. But according to me, it is possible that the TLS session might be established between gor and sherri: this is when gor connects to sherri as it verifies a correst server name I guess: sherri.example.org. On the contrary, if sherri connects to gor before gor connects to sherri the TLS session cannot be established. I have checked this on my side. This is easy to reproduce starting sherri after gor has started.

**Comment by haproxyFred** [comment]
I should have mentionned that the TLS session finally always manages to be established because gor finally always manages to connect to sherri before sherri connects to gor.

**Comment by EmericBr** [comment]
I agree with Fred, if on one side the verifyhost match, the connection will converge to established. This is also the same for the cert authentication, the exposed configuration is incomplete, you will have to add the crt also on server lines, and the verify+ca-file on the bind line.

**Comment by ylafon** [comment]
> I should have mentionned that the TLS session finally always manages to be established because gor finally always manages to connect to sherri before sherri connects to gor.

Ah yes, my bad for not spotting that when I did my tests, setting an invalid domain on both side leads to 
`  0x55bff9932f30: id=gor(remote) addr=192.168.0.197:1024 status=CONN reconnect=2s confirm=0 tx_hbt=0 rx_hbt=0 no_hbt=0 new_conn=151 proto_err=0`
which is what should happen. So you can close this as invalid, sorry about that!
In that case I will have to use multiple ca-file to check `verifyhost` and client certs.

**Comment by wtarreau** [comment]
With this said, it's easy to get trapped and I think that a small amendment
to the doc on this subject could be useful.
