### ISSUE TITLE
Performance Regression with FastCGI since haproxy 2.2

### ISSUE THREAD

**Issue by kamulos** [haproxy/haproxy#756]
This is a weird problem: starting with haproxy 2.2 some requests in my setup take a bit more than 200ms even tough everything is on localhost. This problem did not occur with haproxy 2.1 . I am using the FastCGI backend and an application using the libfcgi. This is what I could find out until now:

- This occurs mostly with small FastCGI answers
- This occurs only if I use the libfcgi function fflush(stdout). Probably it depends on the order in which the FastCGI records of the answer arrive at the haproxy
- Slow requests consistently take a few ms more than 200ms . In some configurations I caught with `strace` that some `epoll_wait` take 200ms while under constant load, but with everything on localhost I don't see those anymore
- If I fire requests directly after starting the haproxy, there is no performance problem. I can send thousands of requests with a client and this problem only occurs if I restart the client. So I guess the requests without issues use the same http connection and only when a new connection is opened this problem occurs.

## What's the configuration?

Haproxy config:

```
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms


backend cloud1
    server server0 127.0.0.1:9002 proto fcgi
    use-fcgi-app cloud-app

fcgi-app cloud-app
    docroot /
    no option keep-conn

frontend web
    bind *:8080
    default_backend cloud1
```

FastCGI application:

```
#include <fcgi_stdio.h>

void main(void)
{
  while (FCGI_Accept() >= 0)   {
    printf("\r\n.");
    fflush(stdout);
  }
}
```

Compile and start with:

```
cc app.c -lfcgi -o app
spawn-fcgi -n -p 9002 -- ./app
```

## Steps to reproduce the behavior

1. Compile and start the FastCGI application as described above
2. Start haproxy (dev or 2.2) with above config
3. Send HTTP requests to localhost:8080 (can be done with a browser)
4. If the problem does not occur, make sure that a new http connection is used (restart client, press ctrl-f5 in browser)
5. Most requests should now take around 205ms

As a comparison you can disable the fflush in the source file. The problem should now cease to exist.

## haproxy -vv

```
HA-Proxy version 2.3-dev0-2d067f-56 2020/07/16 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.1.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

**Comment by kamulos** [comment]
I built haproxy `2.1` and `dev` with the following params: `make TARGET=linux-glibc V=1 USE_OBSOLETE_LINKER=1 CFLAGS="-g3 -O1"`

Then I ran it with: `perf record ./haproxy -f test.cfg`

2.1:
```
  26.27%  haproxy  haproxy             [.] fcgi_encode_param
   7.62%  haproxy  haproxy             [.] ist2bin_lc
   4.33%  haproxy  haproxy             [.] process_stream
   2.19%  haproxy  haproxy             [.] process_runnable_tasks
   2.00%  haproxy  haproxy             [.] si_cs_recv
   1.87%  haproxy  haproxy             [.] _do_poll
   1.38%  haproxy  haproxy             [.] h1_snd_buf
   1.24%  haproxy  haproxy             [.] isteqi
   1.21%  haproxy  haproxy             [.] h1_headers_to_hdr_list
   1.17%  haproxy  libc-2.31.so        [.] __strftime_internal
   1.16%  haproxy  haproxy             [.] __pool_put_to_cache
   1.04%  haproxy  haproxy             [.] fcgi_flt_http_headers
   1.03%  haproxy  haproxy             [.] fcgi_process
```

dev:
```
  17.30%  haproxy  haproxy             [.] fcgi_encode_param
   9.72%  haproxy  haproxy             [.] updt_fd_polling
   4.40%  haproxy  haproxy             [.] process_stream
   4.16%  haproxy  haproxy             [.] ist2bin_lc
   2.04%  haproxy  haproxy             [.] _do_poll
   1.75%  haproxy  haproxy             [.] process_runnable_tasks
   1.69%  haproxy  libc-2.31.so        [.] __strftime_internal
   1.68%  haproxy  haproxy             [.] run_tasks_from_lists
   1.44%  haproxy  haproxy             [.] si_cs_recv
   1.37%  haproxy  haproxy             [.] h1_snd_buf
   1.19%  haproxy  haproxy             [.] h1_headers_to_hdr_list
   1.14%  haproxy  haproxy             [.] fcgi_flt_http_headers
   1.08%  haproxy  haproxy             [.] fcgi_rcv_buf
```

I am not sure if this is helpful. My intuition would be that this is a concurrency issue with locking but I don't know enough about haproxy to judge it.

Slightly off topic: My app is not using the fcgi params, so I am a bit uncomfortable with this much time being spent to encode them. I'd like to save this processing power.

**Comment by kamulos** [comment]
As an addition: during the perf runs the `2.1` processed ~200000 requests, while the `dev` processed ~2000 . It really does not make a lot of sense that a similar time is spent in `fcgi_encode_param`. Maybe the `perf report` is just wrong?

**Comment by wtarreau** [comment]
That's not good but hopefully it's not a big problem. 200ms makes me think we're sending an MSG_MORE flag when we shouldn't, and that should not be too hard to address once we can reproduce it.

**Comment by wtarreau** [comment]
Oh and regarding the time spent in the supposedly almost unused function, let's retry once the bug is addressed. It's indeed extremely possible that due to the unexpected wait time, there are too few samples to report an accurate measurement.

**Comment by kamulos** [comment]
I just remembered this is the perfect thing for `git bisect`:

```
46230363af6cb9332580ce9a8594251f1aa365b5 is the first bad commit
commit 46230363af6cb9332580ce9a8594251f1aa365b5
Author: Christopher Faulet <cfaulet@haproxy.com>
Date:   Thu Oct 17 16:04:20 2019 +0200

    MINOR: mux-h1: Inherit send flags from the upper layer

    Send flags (CO_SFL_*) used when xprt->snd_buf() is called, in h1_send(), are now
    inherited from the upper layer, when h1_snd_buf() is called. First, the flag
    CO_SFL_MSG_MORE is no more set if the output buffer is full, but only if the
    stream-interface decides to set it. It has more info to do it than the
    mux. Then, the flag CO_SFL_STREAMER is now also handled this way. It was just
    ignored till now.

 src/mux_h1.c | 14 +++++++++++++-
 1 file changed, 13 insertions(+), 1 deletion(-)
```

**Comment by capflam** [comment]
As Willy said, it is because the `CO_SFL_MSG_MORE` flag is set on the last send while no more data are expected. It is set because the `CF_EXPECT_MORE` flag is not removed on the response channel before this last send. So now, I must found the right place to remove this flag.

**Comment by wtarreau** [comment]
So ideally we should just compute it on the fly when doing the si_cs_send() call (i.e. we shouldn't need to store it) but I remember that there were areas where we couldn't completely infer it and needed to use the flag instead. Maybe that's finished and could be done entirely on the fly by now thanks to HTX.
