### ISSUE TITLE
haproxy invoked oom-killer

### ISSUE THREAD

**Issue by XityZhang** [haproxy/haproxy#764]
## Output of `haproxy -vv` and `uname -a`
```
HA-Proxy version 2.1.7 2020/06/09 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.7.html
Running on: Linux 2.6.32-642.6.3.el6.x86_64 #1 SMP Fri Nov 11 11:33:08 CST 2016 x86_64
Build options :
  TARGET  = linux263
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_RT=1

Feature list : -EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE -THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 -TPROXY +LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -VSYSCALL -BACKTRACE -GETADDRINFO +OPENSSL +LUA -FUTEX -ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.1e-fips 11 Feb 2013
Running on OpenSSL version : OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without multi-threading support (USE_THREAD not set).
Built with PCRE version : 7.8 2008-09-05
Running on PCRE version : 7.8 2008-09-05
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.3
Running on zlib version : 1.2.3
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 2 (2 usable), will use poll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression

Linux hostname 2.6.32-642.6.3.el6.x86_64 #1 SMP Fri Nov 11 11:33:08 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```

global
    log         127.0.0.1 local2
    pidfile     /var/run/haproxy.pid
    maxconn     8000
    user        root
    group       root
    daemon

    lua-load    /opt/soft/haproxy/conf/auth.lua

    ssl-server-verify none
    tune.ssl.default-dh-param 2048
    ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
    ssl-default-bind-options no-sslv3 no-tls-tickets
    ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
    ssl-default-server-options no-sslv3 no-tls-tickets

    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 8000


frontend ft_exchange2013_https
    bind *:80 name INT_http
    bind *:443 name INT_https ssl crt crtpath
    mode http
    option http-keep-alive
    # disable me? or enable me? FIXME
    #option prefer-last-server
    no option httpclose
    no option http-server-close
    no option forceclose
    no option http-tunnel
    timeout client 600s
    log global
    capture request header Host len 32
    capture request header User-Agent len 64
    capture response header Content-Length len 10
    # log-format directive must br written on a single line
    # it is splitted for documentation convnience
    log-format "%ci:%cp [%t] %ft %b/%s %Tq/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs {%sslv/%sslc/%[ssl_fc_sni]/%[ssl_fc_session_id]} %[capture.req.method] %[capture.req.hdr(0)]%[capture.req.uri] HTTP/1.1"
    maxconn 6000
    acl aclname path_beg -i target_path
    acl ssl_connection ssl_fc
    http-request redirect scheme https code 302 unless ssl_connection

    use_backendone if target_path
#All
backend backendname
    balance roundrobin
    option http-keep-alive
    option prefer-last-server
    no option httpclose
    no option http-server-close
    no option forceclose
    no option http-tunnel
    mode http
    # if risky, 403
    http-request lua.risk_assessment
    http-response lua.risk_assessment_cb
    log global
    option httplog
    option forwardfor
    #option httpchk GET /Autodiscover/HealthCheck.html
    #http-check expect string 200\ OK
    timeout server 60s
    server realbackend domain:port ssl maxconn 4000 weight 10 check



```

## Steps to reproduce the behavior

1. No external access or action has been found to trigger this BUG. Haproxy only runs for a period of time and will automatically restart, and observing that dmesg found that the triggering of the oom-killer, at this time haproxy load is very low. TOP view haproxy occupies less than 100MB of memory.Our machine has 12G of available memory.

## Actual behavior

[ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
[ 9576]     0  9576    26528      299   1       0             0 sh
[ 9577]     0  9577    26527      325   1       0             0 30_process_dete
[ 9612]     0  9612    26593      414   3       0             0 service
[ 9619]     0  9619    27152      453   3       0             0 haproxy
[ 9711]     0  9711    27053      320   2       0             0 bash
[ 9712]     0  9712    17453     2735   0       0             0 haproxy
[10137]     0 10137    17490     2141   0       0             0 haproxy
Memory cgroup out of memory: Kill process 9576 (sh) score 1 or sacrifice child
Killed process 9577, UID 0, (30_process_dete) total-vm:106108kB, anon-rss:180kB, file-rss:1120kB
## Expected behavior

We believe that haproxy should not trigger OOM at such a low load, it should be able to work steadily.
## Do you have any idea what may have caused this?
Maybe the socket overflows?
## Do you have an idea how to solve the issue?
We looked at resource usage, memory stacks, and so on, and found no possible cause.

**Comment by wtarreau** [comment]
Sadly, haproxy is only a victim here. You never decide to get killed by the kernel's OOM killer. It sounds extremely surprising that with 12GB memory a process taking less than 1% of that got killed! Do you have some swap on this machine ? In the past, with older kernels like this, I used to meet the OOM killer from time to time when memory was highly fragmented, and apparently swapping pages out and in was the only way to defragment it.

Also, do you have any info about the 99% of the remaining memory ? Where is it ? Did you change your TCP memory sysctls maybe ? There are some wrong settings on the net where tcp_mem is incorrectly configured in bytes instead of pages, leading the TCP stack to be allowed to use 4096 times the amount of memory... this can surely trigger the OOM killer.

**Comment by XityZhang** [comment]
> Sadly, haproxy is only a victim here. You never decide to get killed by the kernel's OOM killer. It sounds extremely surprising that with 12GB memory a process taking less than 1% of that got killed! Do you have some swap on this machine ? In the past, with older kernels like this, I used to meet the OOM killer from time to time when memory was highly fragmented, and apparently swapping pages out and in was the only way to defragment it.
> 
> Also, do you have any info about the 99% of the remaining memory ? Where is it ? Did you change your TCP memory sysctls maybe ? There are some wrong settings on the net where tcp_mem is incorrectly configured in bytes instead of pages, leading the TCP stack to be allowed to use 4096 times the amount of memory... this can surely trigger the OOM killer.

Thank you for your reply. I haven't adjusted the tcp_mem, and its values are automatically configured by the system. dmesg shows Memory cgroup out of memory instead of socket OOM, i don't think it's a TCP-related issue. But as you said, haproxy is not a problem, and some other services are also on our machines, perhaps for these reasons. I looked for one of the machines to run the vmstat information, as follows.
```
vmstat -s

32883360  total memory
28183200  used memory
25237296  active memory
1546836  inactive memory
4700160  free memory
123732  buffer memory
24931712  swap cache
0  total swap
0  used swap
0  free swap
89865412 non-nice user cpu ticks
92965362 nice user cpu ticks
141536087 system cpu ticks
21944514282 idle cpu ticks
206635813 IO-wait cpu ticks
9592 IRQ cpu ticks
4235352 softirq cpu ticks
1314656 stolen cpu ticks
64190064 pages paged in
2751192816 pages paged out
0 pages swapped in
0 pages swapped out
228757519 interrupts
4175673471 CPU context switches
566984098 boot time
646782517 forks
```

**Comment by XityZhang** [comment]
I will close this issue and open another haproxy crash issue, hoping to get more help, thank you!
[https://github.com/haproxy/haproxy/issues/765](url)

**Comment by wtarreau** [comment]
```
> 566984098 boot time
> 646782517 forks
```

While certainly unrelated, I've never seen that high a fork count,
it's even higher than the number of uptime ticks! It looks like you're
facing something looping on forks, like a script executing itself in
loops or funny stuff like this:

```
    while (fork() > 0)
	wait(NULL);
    exit(0);
```

So there's definitely something unusual going on there.

**Comment by XityZhang** [comment]
> ```
> 566984098 boot time 646782517 forks
> ``` While certainly unrelated, I've never seen that high a fork count, it's even higher than the number of uptime ticks! It looks like you're facing something looping on forks, like a script executing itself in loops or funny stuff like this: ``` while (fork() > 0) wait(NULL); exit(0); ``` So there's definitely something unusual going on there.

Oh yeah, I recently started managing the system, there are a lot of things to optimize.

**Comment by TimWolla** [comment]
>  Memory cgroup out of memory: Kill process 9576 (sh) score 1 or sacrifice child

I'd like to point out this line, specifically the 'cgroup' part in there. It looks like HAProxy specifically is somehow memory limited e.g. by using a Docker Container or by using `MemoryMax=` with systemd. So even if the whole system has still free memory the process tree containing HAProxy might not.

**Comment by XityZhang** [comment]
> > Memory cgroup out of memory: Kill process 9576 (sh) score 1 or sacrifice child
> 
> I'd like to point out this line, specifically the 'cgroup' part in there. It looks like HAProxy specifically is somehow memory limited e.g. by using a Docker Container or by using `MemoryMax=` with systemd. So even if the whole system has still free memory the process tree containing HAProxy might not.

yeah I check about cgroup limits like ```/cgroup/memory``` and ```/etc/cgrule.conf```  but cant find anything. Now I set ```oom_kill_disable 0``` in ```memory.oom_control``` for turning off oom_killier and run the auto-detection script to detect memory  status. It will record memory status and do some protection measures when memory is not safe.
And I need to analysis syslog ```/var/log/messages/``` to know what happend when oom_killer kill the haproxy process such as dump_stack or Mem-Info
I would reply u guys if something been found. Thank u.
