### ISSUE TITLE
Metrics: prometheus exporter: filter by metrics names

### ISSUE THREAD

**Issue by aidofitz** [haproxy/haproxy#770]
Hi,

As I understand it, the prometheus exporter offers basic filtering as outlined here:

https://github.com/haproxy/haproxy/tree/master/contrib/prometheus-exporter

e.g. /metrics?scope=backend

we've got a very large config and it takes a long time to return all the metrics, but we're not interested in most of them. Might it make sense to extend the metrics filtering to allow for selection (include and/or exclude) of specific metrics, something along the lines of:

/metrics?scope=backend&include_metrics=haproxy_backend_current_sessions,haproxy_backend_max_sessions

possibly even allowing for regex in the metrics name?

My primary concern is the impact on HAProxy itself in regularly producing a lot of metrics for prometheus that we are never going to use. If the filtering would be more intensive than just returning them all, then that probably dilutes the value of such a feature. 

~~A secondary concern is that it is taking HAProxy so long (>30s) to respond with the full set of metrics, we can't poll for the metrics as frequently as we would like. More frequenent polling on a much smaller data set would be better for us.~~
Correction to above - the metrics file is about 9Mb total but only takes a few second to d/l when using cURL. Super long times were only when using Chrome, for some reason. 

Appreciate your views!

Regards,

Adrian

**Comment by Lusitaniae** [comment]
Somewhat also related to: https://github.com/haproxy/haproxy/issues/1312

Currently having a few 100 servers running a few dozen service _each_ via server-template/consul implementation

`haproxy_server_check_status` metric is 90% of cardinality in my prometheus database

Having the option to simply exclude it from the output `?exclude=haproxy_server_check_status` would probably be useful to lower bandwidth requirements and load on the scraping side

(i already updated Prometheus config to drop the metric, as described in the issue)


From one server alone, I see 50k lines ~ 5MB response from that metric alone
```
curl 127.0.0.1:9102/metrics -s | grep haproxy_server_check_status | wc -l
52434

curl 127.0.0.1:9102/metrics -s | grep haproxy_server_check_status | wc -c
5167627
```

**Comment by capflam** [comment]
I'm currently working on the exporter to improve it. It is not pushed yet but I've added a way to filter the metrics on their name, to list explicitly metrics to dump or on the opposite to exclude only some metrics from the dump. To do so, a comma-separated list of metrics must be specified. If a name is preceded by a minus (`-`), the metric is excluded from the dump. If at least one metric is specified to be explicitly dumped, all metrics are no longer dumped, but only those explicitly listed.

Here are examples:

```
  # Dumped all metrics, except "haproxy_server_check_status"
  /metrics?metrics=-haproxy_server_check_status

  # Only dump frontends, backends and servers status
  /metrics?metrics=haproxy_frontend_status,haproxy_backend_status,haproxy_server_status
```

Several `metrics` parameters may be used. Included and Excluded metrics can be mixed. Only the intersection will be dumped. Mixed with `scope` parameters, this should be good enough. The purpose of this feature is not to list hundreds of metrics.

Note that I've excluded the regex filtering from the scope of the feature. This would be too expensive. Also note the change is not trivial and will probably not be backported.

**Comment by capflam** [comment]
FYI, the feature was pushed to 3.0.
