### ISSUE TITLE
Headers space allocated, but not flushed with correct data when htx support is enabled

### ISSUE THREAD

**Issue by shamsimam** [haproxy/haproxy#78]
## Output of `haproxy -vv` and `uname -a`

```
$ haproxy -vv
HA-Proxy version 1.9.6 2019/03/29 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-omit-frame-pointer -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2o  27 Mar 2018
Running on OpenSSL version : OpenSSL 1.0.2o  27 Mar 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with PCRE version : 8.30 2012-02-04
Running on PCRE version : 8.30 2012-02-04
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE
              h2 : mode=HTX        side=FE|BE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

$ uname -a
Linux XXX YYY #1 SMP Mon Dec 5 21:15:47 GMT 2016 x86_64 GNU/Linux
```

## What's the configuration?

```
global
   maxconn 10000
   nbproc 1
   nbthread 1
   tune.maxrewrite 32768
   tune.bufsize 65536
   tune.ssl.default-dh-param 2048
   daemon
   user some_account

defaults
   mode http
   log   global
   option http-use-htx
   timeout connect 10s
   timeout client 30s
   timeout server 30s

frontend frontend_node
    bind *:8082 proto h2
    bind *:8083 ssl crt-list /path/to/crt-list alpn h2,http1.1
    option forward-for
    
    acl is-ssl-acl dst_port 8083
    http-request set-header X-Forwarded-Proto http if !is-ssl-acl
    http-request set-header X-Forwarded-Proto https if is-ssl-acl
    acl is-http2 fc_http_major 2
    http-request set-header X-Forwarded-Proto-Version HTTP/2.0 if is-http2
    http-request set-header X-Forwarded-Proto-Version %[capture.req.ver] if !is-http2
    
    usebackend backend_node_h2 if is-http2
    default_backend backend_node_h1

backend backend_node_h1
    server host-1 host-1:9092
    server host-2 host-2:9092

backend backend_node_h2
    server host-1 host-1:9093 check ssl verify none alpn h2
    server host-2 host-2:9093 check ssl verify none alpn h2
```

## Steps to reproduce the behavior

Stream lots of HTTP/1.1 requests with large bodies (my example content length is 690606)  through HA-Proxy.
Some requests (non-deterministic) will fail with a 400 response since the backend server will be unable to parse the incoming HTTP request.
I have been able to reproduce this at a rate of 1 in 50 concurrent requests.
The actual test I am running is in [another codebase](https://github.com/twosigma/waiter/blob/master/waiter/integration/waiter/streaming_test.clj#L22).

## Actual behavior

While space for writing the headers is allocated, the actual header name and value pairs are not flushed into the buffer.
In the example below, the error region allocates exact amount of space it needs to write the new headers, but it did not 'flush' the data to include the x-forwarded headers in the string (in the `sendto` segment). Please see the `sendto` segment in the Expected behavior section to compare with the actual expected output.

_Actual_ [strace](https://linux.die.net/man/1/strace) output from the runnign HA-Proxy process:
```
 30595 21:17:50.403618 recvfrom(43, "
POST /endpoint HTTP/1.1\r\n
Accept-Encoding: gzip\r\n
User-Agent: foo/bar\r\n
Content-Type: application/octet-stream\r\n
x-cid: parallelrequest-iter26\r\n
...
Host: waiter.localtest.me:8082\r\n
Content-Length: 690606\r\n
\r\n
Lorem ipsum dolor sit amet, consectetur adipiscing elit....Morbi lacus tortor, fringilla a facilisis at, fermentum vel orci.\n", 
65480, 0, NULL, NULL) = 14480
...
30595 21:17:50.406799 sendto(36, "
POST /endpoint HTTP/1.1\r\n
accept-encoding: gzip\r\n
user-agent: foo/bar\r\n
content-type: application/octet-stream\r\n
x-cid: parallelrequest-iter26\r\n
...
host: waiter.localtest.me:8082\r\n
content-length: 690606\r\n
Lorem ipsum dolor:  sit\r\n 
amet, consectetur adipis: cing eli\r\n
t. Curabitur ul: lamcorper faci\r\n
\r\n
Lorem ipsum dolor sit amet, consectetur adipiscing elit...Quisque dapibus interdum nisl nec lacinia.", 
32593, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 32593
```

## Expected behavior

Headers should be written and passed along successfully without issues:

_Expected_ [strace](https://linux.die.net/man/1/strace) output from the runnign HA-Proxy process:
```
 30595 21:17:50.403618 recvfrom(43, "
POST /endpoint HTTP/1.1\r\n
Accept-Encoding: gzip\r\n
User-Agent: foo/bar\r\n
Content-Type: application/octet-stream\r\n
x-cid: parallelrequest-iter26\r\n
...
Host: waiter.localtest.me:8082\r\n
Content-Length: 690606\r\n
\r\n
Lorem ipsum dolor sit amet, consectetur adipiscing elit....Morbi lacus tortor, fringilla a facilisis at, fermentum vel orci.\n", 
65480, 0, NULL, NULL) = 14480
...
30595 21:17:50.406799 sendto(36, "
POST /endpoint HTTP/1.1\r\n
accept-encoding: gzip\r\n
user-agent: foo/bar\r\n
content-type: application/octet-stream\r\n
x-cid: parallelrequest-iter26\r\n
...
host: waiter.localtest.me:8082\r\n
content-length: 690606\r\n
x-forwarded-proto: http\r\n
x-forwarded-proto-version: HTTP/1.1\r\n
x-forwarded-for: 123.45.678.123\r\n
\r\n
Lorem ipsum dolor sit amet, consectetur adipiscing elit...Quisque dapibus interdum nisl nec lacinia.", 
32593, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 32593
```

## Do you have any idea what may have caused this?

I do not. However, I have been unable to reproduce the behavior using the following configuration:

```
backend backend_node_h1
    server localhost localhost:9092

backend backend_node_h2
    server localhost localhost:9093 check ssl verify none alpn h2
```

Disabling `htx` mode (and http/2 support) also causes the error to go away.

## Do you have an idea how to solve the issue?

I do not.

**Comment by wtarreau** [comment]
I have no idea what you are talking about. There is no such "space allocation for headers" or whatever. It is very possible that we have an issue one way or another in HTX mode (or in the H2 to backend code maybe), but your description is extremely confusing as it's discussing about possible causes which are not part of haproxy.

Do you have a valid stream of requests that can be sent to haproxy to reproduce the issue ? Maybe simply send your utility to netcat and capture the output ? I'm asking because at first glance the strace output looks fine and one possible reason for getting a 400 could be that the test stream is not correctly delimited (i.e. slightly invalid content-length for example). It's unlikely to be the cause if it works fine without HTX, but on the other hand such tests work perfectly for tens of millions or requests with standard tools like h2load, which adds to the confusion.

Thanks,
Willy

**Comment by wtarreau** [comment]
So I finally managed to run your test file with an H1 client and H1 server over HTX. I could send 61000 requests over a single connection (42 GB total) after which I decided to stop it. Thus if you can clarify what conditions exactly are required to face the problem you're facing, it would help. Thanks!

**Comment by wtarreau** [comment]
So for complete coverage I also tested with H1->H2 chained to H2->H1, both with two servers, and so far the behaviour looks OK to me at 40k requests.

**Comment by capflam** [comment]
Just to let you know I reproduced the bug. I need more time to find the right way to fix it. But I'm on it.

**Comment by shamsimam** [comment]
Hi @wtarreau

Thank you for taking the time and looking into this.

>  There is no such "space allocation for headers" or whatever... your description is extremely confusing as it's discussing about possible causes which are not part of haproxy.

Sorry for the confusion, I was guessing as to what is happening based on what I was seeing in the outputs.

> Maybe simply send your utility to netcat and capture the output ? 

The input stream is valid (as confirmed by the `strace` `recvfrom` output).
I confirmed that the backend server is receiving incorrect data by running it through `strace` too.
Using `netcat` should give similar results.

> I'm asking because at first glance the strace output looks fine and one possible reason for getting a 400 could be that the test stream is not correctly delimited

The `strace` output for `sendto` is _not correct_ and is the reason for getting the 400.
In particular, the error is in this region:

```
content-length: 690606\r\n
Lorem ipsum dolor:  sit\r\n 
amet, consectetur adipis: cing eli\r\n
t. Curabitur ul: lamcorper faci\r\n
\r\n
Lorem ipsum dolor sit amet, consectetur adipiscing elit...
```

The content after the content-length header is also being interpreted as headers (as there is no blank newline) and leads to the 400.
The body of the request (as you can see from the `recvfrom` log) starts at `Lorem ipsum dolor sit amet, consectetur adipiscing elit...` after the blank newline.

So, this content is incorrect on two counts: 

1. It is not the start of the body of the request that was sent (`Lorem ipsum dolor sit amet, consectetur adipiscing elit...`):
```
Lorem ipsum dolor:  sit\r\n
amet, consectetur adipis: cing eli\r\n
t. Curabitur ul: lamcorper faci\r\n
```

2. The output does not include the `x-forwarded-*` headers that HA-Proxy should have generated.
If we count the bytes (97), it is the exact number that would be there if the content had the right headers (that are generated in HA-Proxy):
```
x-forwarded-proto: http\r\n
x-forwarded-proto-version: HTTP/1.1\r\n
x-forwarded-for: 123.45.678.12\r\n
```

> I could send 61000 requests over a single connection (42 GB total) after which I decided to stop it. 
> Thus if you can clarify what conditions exactly are required to face the problem you're facing, it would help. 

In your tests, was HA-Proxy receiving other requests concurrently?
This issue surfaced for us when we ran our integration test suite which runs multiple tests in parallel.
Maybe that is an angle we are missing.

As mentioned in the issue report above, I was unable to reproduce this issue with a single localhost backend.
But it surfaces consistently around every 50 streaming requests (while HA-proxy is accepting other concurrent requests) with multiple remote backends.

Regards,
Shams.

**Comment by shamsimam** [comment]
@capflam thank you very much for confirming the issue (and beginning working on the fix :) ).

**Comment by wtarreau** [comment]
On Tue, Apr 09, 2019 at 07:22:29AM -0700, Shams wrote:
> The content after the content-length header is also being interpreted as
> headers (as there is no blank newline) and leads to the 400.

You're right, I overlooked the missing CRLF there in the trace (which
is fairly long).

> > I could send 61000 requests over a single connection (42 GB total) after which I decided to stop it. 
> > Thus if you can clarify what conditions exactly are required to face the problem you're facing, it would help. 
> 
> In your tests, was HA-Proxy receiving other requests concurrently?

I tested both cases, single connection and multiple. But as you've
seen, Christopher finally managed to reproduce it.

> This issue surfaced for us when we ran our integration test suite which runs
> multiple tests in parallel.
> Maybe that is an angle we are missing.

The most difficult is always to manage to transpose a reproducer in another
environment where anything (including timing or single-byte difference in
host name or anything) sometimes enables or hides the problem :-)

Thanks!
Willy

**Comment by lukastribus** [comment]
Also see:
https://www.mail-archive.com/haproxy@formilux.org/msg33202.html

**Comment by capflam** [comment]
I pushed a fix. See commit f1449b78. It should be ok.

**Comment by shamsimam** [comment]
Wow, that was fast! I will test this weekend.

**Comment by shamsimam** [comment]
@capflam I ran the code from [master](https://github.com/haproxy/haproxy/commit/8ef706502aa2000531d36e4ac56dbdc7c30f718d) against our integration tests and was unable to reproduce this issue.

Do you know when this will be backported to 1.9 and a release made available?

**Comment by wtarreau** [comment]
On Mon, Apr 15, 2019 at 12:56:26PM -0700, Shams wrote:
> @capflam I ran the code from
> [master](https://github.com/haproxy/haproxy/commit/8ef706502aa2000531d36e4ac56dbdc7c30f718d)
> against our integration tests and was unable to reproduce this issue.

Thanks for confirming!

> Do you know when this will be backported to 1.9 and a release made available?

William already backported it this afternoon. A new 1.9.7 should be emitted
relatively soon given that we managed to address a number of interesting
bugs. We'll recheck tomorrow if everything is OK.

Willy

**Comment by shamsimam** [comment]
Any update on when 1.9.7 will be available?

**Comment by shamsimam** [comment]
Just noticed that 1.9.7 was released, thank you!

<img width="874" alt="Screen Shot 2019-04-25 at 2 39 09 PM" src="https://user-images.githubusercontent.com/6611249/56763393-ed2db980-6767-11e9-9ea3-7a38d0186d87.png">

**Comment by capflam** [comment]
You're welcome. Thank you for your help.
