### ISSUE TITLE
HAProxy: Lua: Socket.connect_ssl(socket, address, port) SNI support

### ISSUE THREAD

**Issue by StanleyP** [haproxy/haproxy#780]
## Output of `haproxy -vv` and `uname -a`

Using official haproxytech/haproxy-debian images from hub.docker.com

## What should haproxy do differently? Which functionality do you think we should add?

HAProxy Lua API Socket.connect_ssl(socket, address, port) should provide a way to specify Hostname and/or SNI (https://cs.wikipedia.org/wiki/Server_Name_Indication) value for SSL/TLS handshake.

## What are you trying to do?

I'm trying to connect to SSL/TLS enabled web service using

https://github.com/TimWolla/haproxy-auth-request

The service drops connection when SNI is not present in SSL/TLS handshake.
Currently I have no way to connect to the service from HAProxy/Lua code.

Any suggestions/workarounds very welcome!

**Comment by StanleyP** [comment]
For anyone interested:

I managed to workaround this Socket.connect_ssl limitation by introducing following listen proxy:

```haproxy
listen private-auth
  bind unix@/tmp/private-auth.sock
  http-request set-header Host <FQDN>
  server <FQDN> <FQDN>:443 ssl ca-file /etc/ssl/certs/ca-certificates.crt sni req.hdr(host)
```
  
and from lua I use normal connect to the local socket:

```lua
local socket = core.tcp()
socket:settimeout(5)
if socket:connect("unix@/tmp/private-auth.sock") then
  ...
end
```

**Comment by TimWolla** [comment]
> I managed to workaround this Socket.connect_ssl limitation by introducing following listen proxy:

As you specifically mentioned haproxy-auth-request: That's the workaround I recommend for SSL. See also: https://github.com/TimWolla/haproxy-auth-request/issues/12
