### ISSUE TITLE
 parsing [/etc/haproxy/haproxy.cfg:14] : unknown keyword 'ca-file' in 'global' section

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxy/haproxy#784]
parsing [/etc/haproxy/haproxy.cfg:14] : unknown keyword 'ca-file' in 'global' section, should be supported not in 2.2? Afaik in the manual of 2.2

running haproxy 2.2

docker haproxy:2.2-alpine

**Comment by wlallemand** [comment]
I'm not sure what you are trying to do, but "ca-file" is a keyword of the server and bind line, which must be in a proxy section, it has nothing to do in the global section.
