### ISSUE TITLE
ssl sni on frontend with acls

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxy/haproxy#786]
I hope, nobody minds me asking here. I do not seem to get the discourse email. But maybe this is also a nice feature request if this is not supported. 

I am currently having two different frontends, both I want to offer on ssl 443. However each front end has different acls, http-response set-headers. I think the default[1] to redirect to backends is somethink like this.

```
frontend env_ssl_frontend
  bind *:443
  mode tcp
  option tcplog
  tcp-request inspect-delay 10s
  tcp-request content accept if { req_ssl_hello_type 1 }
  use_backend bk_app1 if { req.ssl_sni -m end app1.domain.com }
  use_backend bk_app2 if { req.ssl_sni -m end app2.domain.com }
  use_backend bk_app3 if { req.ssl_sni -m end app3.domain.com }
```

```
frontend http
  bind *:443 ssl crt /etc/ssl/certs/mycert.pem
  mode tcp
  acl backend1 ssl_fc_sni backed1.domain.com
  acl backend2 ssl_fc_sni backed2.domain.com
  tcp-request inspect-delay 5s
  use_backend backend1 if backend1
  use_backend backend2 if backend2
```

But I think this would mean I cannot separate acl's for different backends, or am I mistaken here? Or is there another way to configure this? I was thinking of doing maybe an port redirection, but that does not really look nice on the client side.

Feature request would be then something like 

* adding a 'use_frontend' that processes rules from another frontend
* or just do in the background tls sni filtering, and just select the correct frontend with correct certificate.

[1]
https://dev.to/dviejopomata/haproxy-multiple-certificates-over-single-ip-using-sni-29ka
https://marcelog.github.io/articles/haproxy_acl_backend_ssl_sni.html

PS. I am not getting the email from the forum to the email address of this account here on github.
https://discourse.haproxy.org/u/account-created/resent

discourse also gives popup about 'You are not permitted to view the requested resource.' while clicking resend

**Comment by lukastribus** [comment]
I've activated your discourse account manually, looks like previous emails bounced back.

Lets proceed there or on the mailing list.

**Comment by f1-outsourcing** [comment]
Thanks Lukas!
