### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#788]
https://www.mail-archive.com/haproxy@formilux.org/msg38032.html

- [ ] using clang-9 (instead of default clang-7) ?
- [ ] using address sanitizer
- [ ] do we need static linking ?
- [ ] caching build artifacts between builds
- [ ] how to get proper checkout ?
- [ ] ...

**Comment by TimWolla** [comment]
>     * using clang-9 (instead of default clang-7) ?

In my test branch this is already the case: Built with clang compiler version 9.0.0 (tags/RELEASE_900/final)

>     * using address sanitizer

Please only within a single, all-features-enabled, entry in the matrix, not everywhere. A single all-features build should be sufficient to detect memory unsafety. It is more important to test configurations that can be seen in the wild (i.e. ASAN disabled).

**Comment by chipitsine** [comment]
closing this issue
