### ISSUE TITLE
JWT Token Query Support In Core Product

### ISSUE THREAD

**Issue by RisingPhorce** [haproxy/haproxy#79]
I would like to request a feature in the core product to to be able reference arbitrary fields of a JWT sent in the standard "Authorization: Bearer ..." header in haproxy configurations.  I anticipate using this with acls.

Today this can, of course, be done with Lua scripts as noted in the [haproxy api gateway part 2 blog entry](https://www.haproxy.com/blog/using-haproxy-as-an-api-gateway-part-2-authentication/).  The downside of this approach is managing the lua scripts to do base64 decoding and spliting the JWT header, payload and signature and then interpreting the payload it as JSON and creating fields as a map/dictionary data structure.  

There are a couple design/implementation decisions on what happens when the signature is invalid, or the token is un-parseable.  

Ultimately having high-quality code in the core product for interpreting jwt tokens would be great for us.

I have discussed this with a representative from HAProxy.  He stated:

> So yes, definitively, it would make sense to have such "converters" to
> validate and extract data from a JWT token.
> It does not look so complicated, we just need to extract data which we
> can do and apply some openssl functions exposed by the linked library.
> I have this on my TODO for some time to do it :)

Thanks for your consideration.

**Comment by wtarreau** [comment]
Do you have any pointers to this JWT thing specification so that we
can estimate the impacts ? I have no idea what this is.

Thanks,
Willy

**Comment by git001** [comment]
It's a huge beast this jwt. I use https://jwt.io/ for debugging.

There is a RFC for that https://tools.ietf.org/html/rfc7519 but as for my experience it's mostly usable with a oauth2 backend to verify if the given values are valid.

For easy usage and implementation a map can be used to verify some `JWT Claims`.

There is a lib for jwt ;-) https://github.com/benmcollins/libjwt

Jm2c

**Comment by bedis** [comment]
I think we "just" need to be able to access some functions from the openssl library to validate the token, then, extracting content may be straight forward through a few fetches / converters: jwt token is encoded in base 64.

great idea by the way :)

**Comment by git001** [comment]
Well it also requires to parse JSON . I know it's "just" a parser but as we know from the http example it's not an easy task to create a parser. There are also some additional RFCs which are included in the rfc7519

The Wikipedia article explains it in a high level way.  
https://en.wikipedia.org/wiki/JSON_Web_Token

**Comment by mfechner** [comment]
@RisingPhorce I do not really understand, why a load balancer has to work with data that belongs to the application server. JWT is used to be completely stateless, so it does not matter which application server works on the request.
If you put this work load to the load balancer, it will get a bottle neck. Why not do all the required checks on the appliation server, this is much more secure and you can scale it without any problems.

**Comment by RisingPhorce** [comment]
@mfechner Hi Matthias, I should have been a little more clear.  The use case that I support today (using Lua scripting) is that our JWT tokens contain a field that indicates a security scope or realm for which the token was issued.  We use this information to route a single frontend to the backend that corresponds to the security realm.  The backends are not multi-tenant.  In short, I wish to use JWT token fields for smart routing.

**Comment by bedis** [comment]
Well, the reverse proxy is also a security endpoint nowadays, and checking if a token is "valid"  still makes sense from my point of view. The soonest in your infra you block an abuser, the best.

**Comment by mfechner** [comment]
@RisingPhorce thanks for clarification, I agree in this case it would be valuable to have such a feature in haproxy even if this is maybe not that simple to implement as you have different possibilities to generate a JWT. With a secret or with RSA public/private key-pair. The public key can be retrieved using a REST based endpoint (jwks) or can be found in a local file.
I did a sample implementation with nestjs (https://github.com/mfechner/nest-graphql-apollo-auth-passport) but this will not have much to do with an implementation you will have to do for haproxy which is maybe completely in C.

**Comment by mfechner** [comment]
@RisingPhorce thanks for clarification, I agree in this case it would be valuable to have such a feature in haproxy even if this is maybe not that simple to implement as you have different possibilities to generate a JWT. With a secret or with RSA public/private key-pair. The public key can be retrieved using a REST based endpoint (jwks) or can be found in a local file.
I did a sample implementation with nestjs (https://github.com/mfechner/nest-graphql-apollo-auth-passport) but this will not have much to do with an implementation you will have to do for haproxy which is maybe completely in C.

**Comment by sodabrew** [comment]
I would actually have a use case for this feature in the load balancer - Cloudflare Access: https://developers.cloudflare.com/access/setting-up-access/validate-jwt-tokens/

End-users connect to Cloudflare per the DNS record for the hostname, and then Cloudflare uses its Access rules to require the user to log in to an identity provider. Cloudflare then signs a JWT and passes it in a header to the backend server if the user was authorized.

The backend validates this JWT to prove that the client came through the Cloudflare Access rules. By making this validation available in the load balancer, it is a bit easier to protect an otherwise brainless intranet application in a zero-trust style remote access scenario.

**Comment by TimWolla** [comment]
I believe this is resolved now: https://github.com/haproxy/haproxy/blob/master/src/jwt.c

/cc @rlebreton Shall we close this as "Fixed"?

**Comment by rlebreton** [comment]
@TimWolla Indeed the first batch of JWT patches should answer to this need (through the jwt_header_query, jwt_payload_query and jwt_verify converters). We can probably close this issue.
