### ISSUE TITLE
Make it more prominent that the hdr fetch splits header at commas

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#796]
Many administrators appear to trip over the fact that the `hdr` fetch splits the header value at commas. While this is documented it is buried deep within a long paragraph. It should be investigated whether the documentation can be rephrased to improve the visibility of that “gotcha”.

**Comment by lukastribus** [comment]
Also hdr clones, like `capture.req.hdr` and `capture.res.hdr` keywords do not mention this at all.

**Comment by TimWolla** [comment]
> Also hdr clones, like `capture.req.hdr` and `capture.res.hdr` keywords do not mention this at all.

Because they are not affected, they pull the raw values out of the capture slot which contains the full header of used with `capture request header …`.
