### ISSUE TITLE
using a large number of slots for server-template results in very high CPU load

### ISSUE THREAD

**Issue by ngrigoriev** [haproxy/haproxy#797]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.5 2019/08/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno
-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-t
ype -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE
 -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TF
O +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=3).
Built with OpenSSL version : OpenSSL 1.1.1c  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.33 2019-04-16
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace


Linux haproxy-7765fdd6c4-j4lhd 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 Linux
```

## What's the configuration?

```
backend demo-api-service
  log global
  mode http
  option log-health-checks
  option httpchk GET /isready
  dynamic-cookie-key XYZ
  cookie MY_SESSION_COOKIE indirect nocache dynamic preserve
  balance roundrobin
  option httpclose
  server-template srv-ws 1000 _http-api-port._tcp.demo-api-service.default.svc.cluster.local resolvers k8s check resolve-opts allow-dup-ip resolve-prefer ipv4
...
```

## Steps to reproduce the behavior

1. Run HAproxy with the configuration like above
2. Try with 10 slots
3. Try with 1000 slots

## Actual behavior

HAProxy consumes lots of CPU time even if there are few (like 1-2) backend servers available from the SRV record and zero traffic.

strace shows lots of actions:

```
9     <... clock_gettime resumed> {tv_sec=7, tv_nsec=498290642}) = 0
8     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
9     epoll_pwait(12,  <unfinished ...>
8     <... clock_gettime resumed> {tv_sec=7, tv_nsec=554516854}) = 0
7     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
8     clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=7, tv_nsec=554553410}) = 0
7     <... clock_gettime resumed> {tv_sec=7, tv_nsec=593258373}) = 0
8     epoll_pwait(15,  <unfinished ...>
7     epoll_pwait(5,  <unfinished ...>
9     <... epoll_pwait resumed> [], 200, 2, NULL, 8) = 0
9     clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=7, tv_nsec=498464176}) = 0
9     clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=7, tv_nsec=498572891}) = 0
9     epoll_pwait(12, [], 200, 0, NULL, 8) = 0
9     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
7     <... epoll_pwait resumed> [], 200, 3, NULL, 8) = 0
9     <... clock_gettime resumed> {tv_sec=7, tv_nsec=498793617}) = 0
8     <... epoll_pwait resumed> [], 200, 3, NULL, 8) = 0
9     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
7     clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=7, tv_nsec=593308543}) = 0
9     <... clock_gettime resumed> {tv_sec=7, tv_nsec=498839317}) = 0
8     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
9     epoll_pwait(12,  <unfinished ...>
7     clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=7, tv_nsec=593324034}) = 0
9     <... epoll_pwait resumed> [], 200, 0, NULL, 8) = 0
8     <... clock_gettime resumed> {tv_sec=7, tv_nsec=554629189}) = 0
9     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
8     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
9     <... clock_gettime resumed> {tv_sec=7, tv_nsec=498899603}) = 0
8     <... clock_gettime resumed> {tv_sec=7, tv_nsec=554652745}) = 0
9     clock_gettime(CLOCK_THREAD_CPUTIME_ID,  <unfinished ...>
7     epoll_pwait(5,  <unfinished ...>
9     <... clock_gettime resumed> {tv_sec=7, tv_nsec=498917734}) = 0
8     epoll_pwait(15,  <unfinished ...>
9     epoll_pwait(12,  <unfinished ...>
```

## Expected behavior

HAProxy consumes reasonable amount of CPU when idle

## Do you have any idea what may have caused this?

There must be some kind of linear operation that iterates over the list of slots and does something inefficiently, I suppose.

## Do you have an idea how to solve the issue?

No

**Comment by ngrigoriev** [comment]
I am wondering about the number of threads. Our cluster nodes are 16-core machines but we give HAProxy a limit of 1 CPU or sometimes even less (in dev/test systems). If I understand the documentation correctly, the default "nbthread" value is the number of CPUs? I am going to try to force it to 1 and see if it makes a difference.

**Comment by TimWolla** [comment]
Can you please upgrade your HAProxy to the latest version in the 2.0.x branch? Quite a few bugs have been fixed since then (including a CRITICAL vulnerability in the HTTP/2 implementation): https://www.haproxy.org/bugs/bugs-2.0.5.html

**Comment by ngrigoriev** [comment]
@TimWolla  I have tested 2.0.16 in my environment and the results were similar.

However, lowering the "nbthread" to 1 did seem to help. Could it be possible that giving HAProxy a fraction of a single CPU (Kubernetes resource limits -> cgroups) while it thinks that we have multiple CPUs results in that kind of behavior? If I understand correctly that by default nbthread is equal to the number of CPUs (/proc/cpu ?). On my laptop it shows "Built with multi-threading support (MAX_THREADS=64, default=3)", on the actual cluster it shows default=16. Maybe the way to reproduce it would be to run it in a single-core environment with 16 threads. Or in 4-cpu environment with 64 threads? ;)

**Comment by wtarreau** [comment]
What bothers me is that it looks like there is nothing done between your calls in your trace.

I don't know how filling the templates from the DNS works, so I have no idea what could be done between these steps. Maybe these are related to DNS responses not yet being ready and the requester thinking it has something to do, I honestly don't know.

Regarding your question about the number of CPUs, it precisely uses by default the number of CPUs *exposed* to haproxy, i.e. the ones the process is allowed to bind to (using taskset or sched_setaffinity()). So you'll never have more threads than CPUs allowed to run on.

**Comment by ngrigoriev** [comment]
@wtarreau It is because I picked a very small fragment of the trace. In fact, there is DNS and healthcheck traffic in betwee, for sure. The trace fragment covers only a small fraction of a second. 

I have compared this trace with the trace I get when using fewer slots (same configuration) and it appears that there is much more epoll/clock_gettime "noise" in case of 1000 slots than in case of 10.

Anyway, it has been confirmed by our testers that, indeed, setting nbthread to 1 does address the issue. So, I guess, the issue is really about the mismatch between the number of CPUs detected by HAProxy vs the actual amount of CPU resources made available by the container framework (technically, kernel via cgroups). In our case particularly, with 0.5 CPU core available and 16 CPUs "visible" (via /proc/cpu), the results were catastrophic once we've increased the number of server-termplate "slots" from 10 to 1000.

Maybe the solution for HAProxy is to try to detect if it is running under any kind of CGROUP limitations. And if so, probably it is wise to either use these limitations (if possible) to initialize nbthread or simply set nbthread to 1 in this case and have a point about it in the docs - e.g. if you externally restrict the amount of CPU resources to HAProxy, please set nbthread to the appropriate value.

**Comment by wtarreau** [comment]
On Thu, Aug 06, 2020 at 06:58:24AM -0700, Nikolai Grigoriev wrote:
> @wtarreau It is because I picked a very small fragment of the trace. In fact,
> there is DNS and healthcheck traffic in betwee, for sure. The trace fragment
> covers only a small fraction of a second. 

OK but even then, there definitely is a problem as there are wakeups without
I/O in between and that's absolutely not expected.

> I have compared this trace with the trace I get when using fewer slots (same
> configuration) and it appears that there is much more epoll/clock_gettime
> "noise" in case of 1000 slots than in case of 10.

This may possibly indicate that unconfigured servers get requests regardless
of their state. But I have no idea how servers are "discovered" in this mode.

> So, I guess, the issue is really about the mismatch between the number of
> CPUs detected by HAProxy vs the actual amount of CPU resources made available
> by the container framework (technically, kernel via cgroups).

There shouldn't be any reason for this at all. It wouldn't cause spurious
wakeups with no I/O. And it would not just affect this very particular use
case.

> In our case
> particularly, with 0.5 CPU core available and 16 CPUs "visible" (via
> /proc/cpu),

When you presend 16 CPUs to the VM, they'll still be mapped to 16
individual CPUs which are just available to you for small portions
of time. Otherwise this would be catastrophic for *any* threaded
workload, as CPUs would be scheduled out holding a lock while
others would be scheduled in just to loop on that lock.

Willy

**Comment by wtarreau** [comment]
Hi again,

so I tried to reproduce something with your config excerpt by completing is with a dummy frontend and a resolvers section, but I'm unable to see anything wrong. I'm seeing SRV requests being sent once a second, to which the local DNS server doesn't respond. I suspect there's something wrong in the SRV record processing code but I don't even know how to produce SRV records, so I'll leave it to someone more knowledgeable on this. @bedis any ideas ?

**Comment by bedis** [comment]
Hi there,

The option `allow-dup-ip` is enable which means the 1000 servers should be used at the same time. That said, I am not sure what this option implies with SRV records. I'll check this and come back to you.
That said, I think CPU usage might be related to the "On" parsing of IP addresses and fqdns associated to the servers in the backend.

**Comment by capflam** [comment]
The resolver part was improved over the versions. We tried to backport as much fixes as possible. The 2.0 is not the best one on this part, far from there. Please try 2.4 or 2.5 instead. I'm closing this issue now. Thanks !
