### ISSUE TITLE
Cosmetic issue: HAProxy -vv prints that encrypted passwords are supported even if disabled during compile-time

### ISSUE THREAD

**Issue by vityank** [haproxy/haproxy#799]
Cosmetic issue.
Hi, I've built static version of HAProxy w/o crypt support(Due to Mozilla NSS not supporting static libraries) using "USE_LIBCRYPT=" and other changes.
The binary always prints that encrypted passwords are supported, which is incorrect:
Encrypted password support via crypt(3): no

src/auth.c:
I found in the end of file(HAProxy src v2.2.2) this line with fixed output:
REGISTER_BUILD_OPTS("Encrypted password support via crypt(3): yes");

I changed it like written below and now it seems to print it's crypto compile-in state properly:

#ifdef USE_LIBCRYPT
REGISTER_BUILD_OPTS("Encrypted password support via crypt(3): yes");
#else
REGISTER_BUILD_OPTS("Encrypted password support via crypt(3): no");
#endif

**Comment by lukastribus** [comment]
Agreed, we should not end up in situations like this:

```
lukas@dev:~/haproxy-2.2$ ./haproxy -vv | grep crypted
Encrypted password support via crypt(3): yes
lukas@dev:~/haproxy-2.2$ ./haproxy -f ../cert/haproxy.cfg -c
[WARNING] 218/081327 (32364) : parsing [../cert/haproxy.cfg:48]: no crypt(3) support compiled, encrypted passwords will not work.
Warnings were found.
Configuration file is valid
lukas@dev:~/haproxy-2.2$
```

**Comment by wtarreau** [comment]
Oh I understand the mess. It might have happened when cleaning up the file to reduce the scope of the horrible ifdefs :-( 

@vityank I agree with your change, it's even better than just not listing the entry as it makes it obvious these are not supported. Could you please propose a patch ? Please have a look at CONTRIBUTING to get it right on the first time. Thanks!

**Comment by vityank** [comment]
Hi. Can I paste regular patch in comment, as i have the release tarball tree(Not from git), or you need git's format-patch with commit description?

Btw,I revised the change a little using preprocessor definition, as shown below:

--- src/auth.c.orig     2020-07-31 12:54:32.000000000 +0300
+++ src/auth.c  2020-08-06 13:35:19.067718090 +0300
@@ -36,6 +36,7 @@
 struct userlist *userlist = NULL;    /* list of all existing userlists */

 #ifdef USE_LIBCRYPT
+#define CRYPT_STATE_MSG "yes"
 #ifdef HA_HAVE_CRYPT_R
 /* context for crypt_r() */
 static THREAD_LOCAL struct crypt_data crypt_data = { .initialized = 0 };
@@ -43,6 +44,8 @@
 /* lock for crypt() */
 __decl_thread(static HA_SPINLOCK_T auth_lock);
 #endif
+#else /* USE_LIBCRYPT */
+#define CRYPT_STATE_MSG "no"
 #endif

 /* find targets for selected groups. The function returns pointer to
@@ -310,4 +313,4 @@
        return NULL;
 }

-REGISTER_BUILD_OPTS("Encrypted password support via crypt(3): yes");
+REGISTER_BUILD_OPTS("Encrypted password support via crypt(3): "CRYPT_STATE_MSG);

**Comment by wtarreau** [comment]
Please do the entire thing with the commit description and git-format-patch. It may be cumbersome for you the first time if you're not used to doing this but it's even more for someone else to have to describe what you faced and were trying to do. You may also want to mention this issue ID in the commit message; if you prefix it by a '#' it will be recognized. Don't worry too much about cosmetic details, we can slightly adjust the message if needed. Usually we prefer the patches to be posted to the mailing list, but if it's easier to you, just attach it here. In any case, your participation is much appreciated. Thank you!

**Comment by vityank** [comment]
[0001-Version-info-page-Print-valid-crypto-3-support-state.zip](https://github.com/haproxy/haproxy/files/5036331/0001-Version-info-page-Print-valid-crypto-3-support-state.zip)

It's ok. I just used to PR's on github(But saw in CONTRIBUTING, that you prefer raw patches, just not so raw :) ).
I'll clone the repo and will make commit+format patch on it, then attach the patch file to this message.

Update: Patch file attached.

**Comment by wtarreau** [comment]
Thank you Victor, I've just taken it after adding a more suitable commit message. But your solution was OK to me. PS: next time, please don't zip the file, just call it .txt :-)

**Comment by vityank** [comment]
Ok, thanks. I've just got used to zipping to overcome googles's
restrictions of file types.:)

вт, 8 сент. 2020 г., 3:37 PM Willy Tarreau <notifications@github.com>:
