### ISSUE TITLE
h2: incorrect sign extension in h2_peek_frame_hdr()

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#8]
This problem was already diagnosed. In 1.8 (and only this version), h2_peek_frame_hdr() computes the frame length using an incorrect shift : 
```
h->len = *b->p << 16;
```
Here, b->p is a (char*) thus we have a large negative value when chars are signed, resulting in a negative length. Fortunately the length is always checked later so this bug has no impact. The required fix is trivial : 
```
h->len = *(uint8_t *)b->p << 16;
```
1.9 is safe thanks to the buffer API changes.

**Comment by capflam** [comment]
I guess this will never be fixed. I'm closing now.
