### ISSUE TITLE
ssl-skip-self-issued-ca option does not work

### ISSUE THREAD

**Issue by wlallemand** [haproxy/haproxy#804]
Following https://www.mail-archive.com/haproxy@formilux.org/msg37936.html

## Actual behavior

It doesn't do anything.

## Expected behavior

Should skip the self-issued CA in the SSL_CTX.

## Do you have any idea what may have caused this?

Commit f187ce6 reverted the feature because it was breaking the multi-cert bundles.

## Do you have an idea how to solve the issue?

Probably by moving the self-issued CA from the chain storage to the issuer storage before doing a SSL_CTX_set1_chain()

**Comment by serimin** [comment]
@wlallemand 
This works well.

Thanks!!
Seri

**Comment by wtarreau** [comment]
Thanks for checking, now closing since backported.
