### ISSUE TITLE
crt-list negative filters don't work

### ISSUE THREAD

**Issue by wlallemand** [haproxy/haproxy#818]
## Output of `haproxy -vv` and `uname -a`

All supported versions of HAProxy.

## What's the configuration?

config:

     bind :4443 ssl strict-sni crt-list bug.crt-list

crt-list:

    domain.tld.pem.ecdsa  *.subdomain.domain.tld !record.subdomain.domain.tld

## Steps to reproduce the behavior

    echo QUIT | openssl s_client -connect localhost:4443 -servername record.subdomain.domain.tld 

## Actual behavior

HAProxy replies with the domain.tld.pem.ecdsa certificate when it should close the connection.

## Expected behavior

It must refuse the connection.

According to the documentation:

> Wildcards are supported in the SNI filter. Negative filter are also supported,
> only useful in combination with a wildcard filter to exclude a particular SNI.

The example in the documentation works because the single name filters have a highest priority over the wildcard ones

      certW.pem                   *.domain.tld !secure.domain.tld
      certS.pem [curves X25519:P-256 ciphers ECDHE-ECDSA-AES256-GCM-SHA384] secure.domain.tld

## Do you have any idea what may have caused this?

The negative filters are skipped in the configuration and not used actively.

## Do you have an idea how to solve the issue?

The negative filter must be used in combination with a wildcard, if a wildcard is matched, we must look for a negative filter which is on a same line. So we need to add a pointer in struct sni_ctx to a list of filters which are on the same crt-list line.

**Comment by wlallemand** [comment]
I'm interested in feedback and tests for this bugfix, this is unlikely to be backported in version older than 2.1 though. Let me know if you have any problem with it.

**Comment by wlallemand** [comment]
Backported in 2.2 and 2.1. Still need to fix the doc in older versions.

**Comment by wlallemand** [comment]
The documentation was fixed in b0b703f starting from the 2.0 branch.

**Comment by TimWolla** [comment]
This can be closed then?

**Comment by wlallemand** [comment]
I just backported it in 1.8. Can be closed now.
