### ISSUE TITLE
Upstream socks proxy support

### ISSUE THREAD

**Issue by alec-liu** [haproxy/haproxy#82]
## What should haproxy do differently? Which functionality do you think we should add?

HAProxy is a TCP based load balancer means all backend connections will be TCP, in some network environment we can use socks4/5 proxy only, if the backend connections able to link via different socks proxy will be great.

## What are you trying to do?

Try to make the HAProxy fit into different kind of network environments, like the one supporting socks proxy only.

**Comment by wtarreau** [comment]
Well, socks is never ever used in load balancing environments nor web applications. I understand how it can be useful to complete the collection of nice stuff that makes haproxy the Swiss Army Knife of proxying, and I wouldn't be opposed to merging patches that would implement this if that doesn't affect how the rest works. But I'm not aware of anyone willing to spend time on this.

**Comment by alec-liu** [comment]
Good to know you guys are open to this. 

Understand that in a normal load balancing environment or web application, socks won’t be used. Base on my understanding, that’s because for most of time the backend service should be within the same internal network or LAN as HAProxy. But if we are trying to use the HAProxy as TCP relay load balancer to some service over WAN, then we might have to go over the internal firewall before able to reach the service on WAN. That is where the socks proxy get into the picture. Of course, we have some other methods to get HAProxy hooked to socks proxy without changing any code of HAProxy, but from better control and easy to use point of view , if we can have the HAProxy supporting upstream socks proxy will be useful.

I will try to build some patches for it, and I hope you guys can help to do some code review to make sure not breaking anything.

Thank you!

**Comment by wtarreau** [comment]
On Mon, Apr 15, 2019 at 09:50:43PM -0700, alec-liu wrote:
> I will try to build some patches for it, and I hope you guys can help to do
> some code review to make sure not breaking anything.

OK. Please have a look at how muxes are implemented. They're definitely
where protocol translations happen (mux-h1, mux-h2). I don't even know
if SOCKS supports multiplexing but even without if you just need to
prepend a connection header, perform a handshake with the server, or
encapsulate data into frames, you'll have good examples there. mux-h1
is the simplest one, doesn't require double-buffering, performs the
changes on the fly and supports one stream per connection. H2 does the
connection handshakes, has more than one stream per connection (hence
a send list) and uses double buffering. In your case you may need to
declare a new mux protocol ("SOCKS" ?) working only in TCP I guess.

Willy

**Comment by git001** [comment]
Well the socks protocol is not only TCP it have also some UDP parts.  
https://en.wikipedia.org/wiki/SOCKS

@alec-liu I assume you will need to route based on destination ip with SOCKS5, right?

If my assumption is right can this could end in such a pseudo config.

```
frontend generic

   ... 
  # https://www.haproxy.com/blog/introduction-to-haproxy-maps/
   use_backend %[str(src),map(ips.map)]

backend xxx
  mode socks5
  server dest-srv xxx.....

```

**Comment by alec-liu** [comment]
@git001 Yes, you are right SOCKS can be used for UDP, but of course we can use the TCP part only for HAProxy. I am not trying to turn the HAProxy into some kind of SOCKS proxy or load balancer to balance multi SOCKS proxies. What I am trying do is, to let the HAProxy able to use SOCKS for upstream.

In my mind, the config might end up like this:

`server srv1 123.123.123.123:8080 socks4 192.168.1.100:1080`

And I am planning to support SOCKS4 only at very beginning which is TCP only.

If you want to know more about SOCKS protocol detail, you can try to read the RFC 1928.

**Comment by alec-liu** [comment]
@wtarreau I have a socks4 version patch ready, can you help to review it? And where should I send the patch to? 
Thank you.

**Comment by TimWolla** [comment]
Note to people reading this issue: Alec sent the patch to the list by now (that's where patches go!). You can follow the thread here: https://www.mail-archive.com/haproxy@formilux.org/msg33430.html

**Comment by alec-liu** [comment]
Hi Tim, Willy,

Here is the updated patch for review.

There is a sample configuration in the patch.
If you want to give it a try, you can use "ssh -D 1080 user@xxx.xxx.xxx.xxx"
to setup a quick socks4 proxy tunnel.

Thank you.

Regards,
Alexander Liu

**Comment by cipriancraciun** [comment]
**EDIT:  I just realized that what I'm speaking about is a little different than this issue / pull request.**  However it is still strictly related, as it is about an orthogonal feature:  having SOCKS4 as an alternative to the PROXY protocol header.

---

Would it be feasible to also add support for SOCKS4 to the backend and frontend as an alternative to the PROXY protocol?  (I think it's simpler than implementing the actual tunneling part.)

The use case I have in mid is something like:

* SOCKS4 in the backend, would allow HAProxy to route all backend
traffic through a proper SOCKS4 proxy;  this might be used as a
poor-man variant of a tunnel, like for example via SSH;  (if one makes
HAProxy into a transparent proxy, it could even serve as a layer-7
firewall;)

* SOCKS4 in the frontend, would allow HAProxy to act like a SOCKS4
proxy, and apply for example HTTP routing and filtering;  (for example
one configures HAProxy as a SOCKS4 proxy in a browser;)

**Comment by nutinshell** [comment]
@alec-liu if come this far, will you make it support both socks4/5 ?

**Comment by alec-liu** [comment]
@nutinshell Yes, that's the plan, SOCKS4 first, then SOCKS5 with
authentication, domain name destination, and IPV6 support later.
I will try to use a different way to implement it, compare to the
SOCKS4 one, so it won't be ready in short.

**Comment by alec-liu** [comment]
@Ciprian-Dorin-Craciun
Base on my understanding, the PROXY protocol was used to pass over the
source address.
How are you going to use the SOCKS4 proxy as an alternative to the
PROXY protocol?

For the use case you have mentioned, why don't you just use the HTTP
Proxy in browser?

**Comment by cipriancraciun** [comment]
@alec-liu 
> For the use case you have mentioned, why don't you just use the HTTP Proxy in browser?

First I'll tackle the HTTP-proxy support in the browser:  HAProxy doesn't support (out of the box) the HTTP-proxy protocol.  One could perhaps use various ACL's and HTTP mangling to make it work, but I think it's sub-optimal.  (Moreover, TLS man-in-the-middle is not possible, at least not without extra work.)

Moreover, not all tools support HTTP-proxy, and it can't be easily used for non-HTTP.  Also the Tor proxy (from my knowledge) supports only SOCKS.

----

Now to move to my use-case for SOCKS4 as (HA)PROXY header replacement (as a feature in the `frontend` section):  one could easily configure a browser (or other tool) to use SOCKS4 and point it to a HAProxy instance.  In doing so then HAProxy can not only be used to filter and route the requests, but (if the proper CA certificates are installed) also handle HTTPS requests.  (One could use such a setup mainly for development or debugging purposes, but also for "sandboxing", etc.)

A second use-case is a little bit different (as a feature in the `server` section for `backend`s):  HAProxy can be targeted as a transparent proxy (for example in Linux I can forward through `iptables` any port 80/443 connection to a HAProxy instance);  there I can apply the same filtering / routing as before, but in the end I could forward the requests through a real SOCKS4 proxy (like Tor or SSH).  Thus one could sandbox certain containers / VM's.

----

My proposal differs from the current feature in the fact that it only provides an alternative to the (HA)PROXY protocol header, it doesn't interfere with the actual connections and I/O.  (I.e. the `server` address remains constant, etc.)

**Comment by nutinshell** [comment]
@alec-liu  I think @cipriancraciun wants to redirect incoming tcp to socks4 server, like `client tcp -> linux iptable redirect -> haproxy transparent frontend -> backend socks4 servers` 

it should be a very useful feature to do client traffic LB.

**Comment by cipriancraciun** [comment]
@nutinshell Exactly!  In the use-case I envisage HAProxy doesn't act as a reverse proxy, but instead as a "normal" forwarding proxy.  (I'ts main usage is the powerful ACL and routing capability.)

So as you've summarized it, there are a couple of use-cases:
* client with explicit SOCKS support -> HAProxy SOCKS frontend -> normal backend / servers -- useful for routing only specific domains through HAProxy (perhaps with browser PAC support);
* client without SOCKS support -> HAProxy transparent frontend -> normal backend / servers -- useful to sandbox certain clients, or to debug various setups;
* client (with / without) SOCKS support -> HAProxy frontend -> SOCKS enabled server -- useful for traffic filtering, and redirection to a proper SOCKS proxy;

**Comment by git001** [comment]
@cipriancraciun 

> @nutinshell Exactly! In the use-case I envisage HAProxy doesn't act as a reverse proxy, but instead as a "normal" forwarding proxy. (I'ts main usage is the powerful ACL and routing capability.)

 I think it's a huge amount of work to add this feature to HAProxy which looks like squid. What's wrong with squid?

> So as you've summarized it, there are a couple of use-cases:
> 
>     * client with explicit SOCKS support -> HAProxy SOCKS frontend -> normal backend / servers -- useful for routing only specific domains through HAProxy (perhaps with browser PAC support);

This requires that haproxy have the `mode socks(4|5)` and a PAC parser, IMHO. Both parts are complete different levels of network layer and not easy to implement. You can use SS5 with http/s fixup for such a solution. http://ss5.sourceforge.net/features.htm => **Traffic filtering**

>     * client without SOCKS support -> HAProxy transparent frontend -> normal backend / servers -- useful to sandbox certain clients, or to debug various setups;

This is already possible, isn't it?

>     * client (with / without) SOCKS support -> HAProxy frontend -> SOCKS enabled server -- useful for traffic filtering, and redirection to a proper SOCKS proxy;

This is the patch from @alec-liu for the socks4 backend?

As I have mentioned in https://github.com/haproxy/haproxy/issues/82#issuecomment-483669353 `mode socks(4|5)` would be nice but it's not easy to write a robust and compliant socks server. Patches are welcome.

**Comment by cipriancraciun** [comment]
@git001 

> I think it's a huge amount of work to add this feature to HAProxy which looks like squid. What's wrong with squid?

At one time I've looked through the HAProxy code where the `PROXY` feature was implemented, and it didn't seem to be too involved.  (As said the feature I propose is just an alternative to the `PROXY` header, nothing more;  it doesn't impact the connection and I/O code.)

https://www.mail-archive.com/haproxy@formilux.org/msg27549.html

(There is nothing wrong with Squid, however if one needs only the filtering, and one already knows how to configure HAProxy, I think it becomes a better and stronger alternative.  For example I don't have extensive knowledge of Squid, but I do somewhat for Varnish, and although Varnish and HAProxy are on-par feature wise when it comes to HTTP "mangling", I would say HAProxy is a lot better in terms of configuration and flexibility.)

---

> > * client with explicit SOCKS support -> HAProxy SOCKS frontend -> normal backend / servers -- useful for routing only specific domains through HAProxy (perhaps with browser PAC support);
> 
> This requires that haproxy have the `mode socks(4|5)` and a PAC parser, IMHO.

No, the PAC metioned is configured in the browser, HAProxy has nothing to do with it.  (I just mentioned it as away to configure HAProxy as the SOCKS4 proxy for selected domains.)


> > * client without SOCKS support -> HAProxy transparent frontend -> normal backend / servers -- useful to sandbox certain clients, or to debug various setups;
> 
> This is already possible, isn't it?

Yes it is, however it "fits" into the larger use-case family of HAProxy as an "forwarding" filtering / HTTP mangling tool.


> > * client (with / without) SOCKS support -> HAProxy frontend -> SOCKS enabled server -- useful for traffic filtering, and redirection to a proper SOCKS proxy;
> 
> This is the patch from @alec-liu for the socks4 backend?

Not quite.  From what I read @alec-liu implemented SOCKS4 in the backend only as a way to submit requests for to a "fixed" server IP through a "fixed" SOCKS4 proxy server.

My proposal is somewhat different, as in the `PROXY` case, HAProxy just adds the `SOCKS4` header and sends the rest of the communication unmodified to the IP mentioned on the server line.  (Unfortunately as opposed to the `PROXY` header, in case of `SOCKS4`, the server also replies with a header which has to be read and handled.)

---

> As I have mentioned in [#82 (comment)](https://github.com/haproxy/haproxy/issues/82#issuecomment-483669353) `mode socks(4|5)` would be nice but it's not easy to write a robust and compliant socks server. Patches are welcome.

Once more, I underline that my proposal doesn't require HAProxy to become a fully compliant `SOCKS` server, just that it handles the header as an alternative to the `PROXY` header.

**Comment by nutinshell** [comment]
@git001 no needed to do so much in Haproxy,  Haproxy only to do tcp to socks4 server like this:

```
bind :2000 transparent
server s1 10.0.0.1:3000 socks4-redirect #10.0.0.1:3000 is socks4
```
 @alec-liu 's patch is let the tcp go servers via socks, and here we want tcp go directly to socks.

**Comment by git001** [comment]
@cipriancraciun 

> At one time I've looked through the HAProxy code where the `PROXY` feature was implemented, and it didn't seem to be too involved. (As said the feature I propose is just an alternative to the `PROXY` header, nothing more; it doesn't impact the connection and I/O code.)
> 
> https://www.mail-archive.com/haproxy@formilux.org/msg27549.html

I see we have discussed this topic in the past ;-)

> My proposal is somewhat different, as in the `PROXY` case, HAProxy just adds the `SOCKS4` header and sends the rest of the communication unmodified to the IP mentioned on the server line. (Unfortunately as opposed to the `PROXY` header, in case of `SOCKS4`, the server also replies with a header which has to be read and handled.)

Yes  and that's the point. HAProxy need to understand what the reply is.

> Once more, I underline that my proposal doesn't require HAProxy to become a fully compliant `SOCKS` server, just that it handles the header as an alternative to the `PROXY` header.

From my opinion it isn't that such simple.
Socks4a have the option to let the proxy resolve the ip, so this must also be implemented. I assume that we talk here about the **CONNECT** command not the **BIND** right.

Don't get me wrong I would like to see this feature in HAProxy but I know how difficult it is to build a socks-server and therefore I would not underestimate the amount of work for such a feature.

But I strongly suggest to move this discussion to the mailing list as the developer are all there.

**Comment by git001** [comment]
@nutinshell 
> @git001 no needed to do so much in Haproxy, Haproxy only to do tcp to socks4 server like this:
> 
> ```
> bind :2000 transparent
> server s1 10.0.0.1:3000 socks4-redirect #10.0.0.1:3000 is socks4
> ```
> @alec-liu 's patch is let the tcp go servers via socks, and here we want tcp go directly to socks.

I think this is a different use case then @cipriancraciun have.

**Comment by nutinshell** [comment]
@git001 I think that's the same way, but minimal work to do in haproxy.

**Comment by git001** [comment]
@nutinshell 
> @git001 I think that's the same way, but minimal work to do in haproxy.

As far as I have understood the socks4-redirect is it a tcp redirect. I haven't used such a case before. How do you use it today? Do you have a example about the workflow or a setup from a used program?

When I look into redsock2 it looks like the program uses some ip tools on different platforms.

https://github.com/semigodking/redsocks/blob/master/base.c#L306-L318

Maybe this could be solved with a `redirect` action in https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#4.2-tcp-request%20content independently of socksX, what do you think?

**Comment by nutinshell** [comment]
> As far as I have understood the socks4-redirect is it a tcp redirect. I haven't used such a case before. How do you use it today? Do you have a example about the workflow or a setup from a used program?

Yes, we use the below redsocks to redirect tcp to socks server, but it's no LB, and performance not good.

> Maybe this could be solved with a `redirect` action in https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#4.2-tcp-request%20content independently of socksX, what do you think?

It should be cool :) But how could it redirect users' tcp traffic to the remote server in a good way?

**Comment by git001** [comment]
@cipriancraciun & @nutinshell 
I have created a summery in the ML and invite you to discuss this further on the list.

https://www.mail-archive.com/haproxy@formilux.org/msg33989.html

**Comment by wtarreau** [comment]
Given that the feature was merged and the discussion moved to the list, I'm now closing this issue.

**Comment by alirezadigi** [comment]
@wtarreau can you please explain more? ... (on how?)

**Comment by git001** [comment]
@alirezadigi this is the mail thread. https://www.mail-archive.com/haproxy@formilux.org/msg33989.html
