### ISSUE TITLE
Add support for HTTP 304 Not Modified to HAProxy's cache

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#821]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.1-1~bpo10+1 2020/07/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.1.html
Running on: Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.2.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

## What should haproxy do differently? Which functionality do you think we should add?

It would be useful if HAProxy was capable of generating a 304 Not Modified responses for cached objects.

## What are you trying to do?

I'm attempting to cache objects in HAProxy to avoid a round trip to the configured backend (nginx). Unfortunately HAProxy is not capable of responding with 304 Not Modified to requests having an `if-none-match` header containing an ETag, while my backend is. While I can reduce the number of backend requests by caching in HAProxy I need to pay with increased response sizes for revalidation requests (an unchanged resource is fully delivered from the cache) which makes the cache not *that* interesting.

**Comment by wlallemand** [comment]
This was mentionned in issue #214. Your patch is in my backlog I'm reviewing it soon.

**Comment by TimWolla** [comment]
@wlallemand Thanks. I've edited the initial message of #214 to insert the number of this issue in the appropriate locations.

**Comment by TimWolla** [comment]
@wlallemand Did you get around to taking a look, yet?

**Comment by TimWolla** [comment]
Proposal thread: https://www.mail-archive.com/haproxy@formilux.org/msg38202.html

My latest series before passing this to someone else: https://www.mail-archive.com/haproxy@formilux.org/msg38296.html

Useful remarks from William: https://www.mail-archive.com/haproxy@formilux.org/msg38326.html

**Comment by TimWolla** [comment]
Marking as fixed and closing. Thanks @rlebreton!

**Comment by uasan** [comment]
I noticed that the 304 status is only possible if the ETag header value was enclosed in double quotes, is this intended?

There seems to be no requirement in the HTTP protocol that the ETag header value must be enclosed in double quotes in order to be revalidated and respond with the 304 status

**Comment by capflam** [comment]
Well in fact, it is a requirement of the RFC 9110 (https://datatracker.ietf.org/doc/html/rfc9110#name-etag)

>   An entity tag consists of an opaque quoted string, possibly prefixed by a weakness indicator.

**Comment by uasan** [comment]
Yes, indeed you are right, these browsers support any format without quotes, ok, it is not a problem for me, thank you
