### ISSUE TITLE
Can't compile haproxy-2.0-dev2 from source

### ISSUE THREAD

**Issue by nrcmn** [haproxy/haproxy#83]
I'm trying to compile haproxy with minimum option and getting error:

make TARGET=linux2628
  CC      src/ev_poll.o
In file included from include/common/chunk.h:30,
                 from include/common/standard.h:36,
                 from include/common/ticks.h:56,
                 from src/ev_poll.c:23:
include/common/memory.h: In function ‘__pool_get_first’:
include/common/memory.h:234: warning: implicit declaration of function ‘__atomic_add_fetch’
include/common/memory.h:234: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/common/memory.h:234: error: (Each undeclared identifier is reported only once
include/common/memory.h:234: error: for each function it appears in.)
include/common/memory.h: In function ‘__pool_free’:
include/common/memory.h:292: warning: implicit declaration of function ‘__atomic_compare_exchange_n’
include/common/memory.h:292: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/common/memory.h:294: warning: implicit declaration of function ‘__atomic_sub_fetch’
In file included from include/proto/activity.h:29,
                 from src/ev_poll.c:28:
include/proto/freq_ctr.h: In function ‘update_freq_ctr’:
include/proto/freq_ctr.h:45: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/freq_ctr.h:63: warning: implicit declaration of function ‘__atomic_store_n’
include/proto/freq_ctr.h: In function ‘update_freq_ctr_period’:
include/proto/freq_ctr.h:83: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
In file included from src/ev_poll.c:29:
include/proto/fd.h: In function ‘updt_fd_polling’:
include/proto/fd.h:125: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘done_update_polling’:
include/proto/fd.h:147: warning: implicit declaration of function ‘__atomic_and_fetch’
include/proto/fd.h:147: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_alloc_cache_entry’:
include/proto/fd.h:173: warning: implicit declaration of function ‘__atomic_or_fetch’
include/proto/fd.h:173: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_stop_recv’:
include/proto/fd.h:291: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_stop_send’:
include/proto/fd.h:316: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_stop_both’:
include/proto/fd.h:341: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_cant_recv’:
include/proto/fd.h:367: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_may_recv’:
include/proto/fd.h:386: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_done_recv’:
include/proto/fd.h:413: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_cant_send’:
include/proto/fd.h:439: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_may_send’:
include/proto/fd.h:458: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_want_recv’:
include/proto/fd.h:481: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘fd_want_send’:
include/proto/fd.h:507: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘hap_fd_set’:
include/proto/fd.h:587: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
include/proto/fd.h: In function ‘hap_fd_clr’:
include/proto/fd.h:592: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
src/ev_poll.c: In function ‘_update_fd’:
src/ev_poll.c:68: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
src/ev_poll.c: In function ‘_do_poll’:
src/ev_poll.c:109: error: ‘__ATOMIC_RELAXED’ undeclared (first use in this function)
make: *** [src/ev_poll.o] Error 1

**cat /etc/issue**
CentOS release 6.10 (Final)
**uname -r**
2.6.32-573.22.1.el6.x86_64

In docs:

HAProxy requires a working GCC or Clang toolchain and GNU make :

  - GNU make >= 3.80. Note that neither Solaris nor OpenBSD's make work with
    the GNU Makefile. If you get many syntax errors when running "make", you
    may want to retry with "gmake" which is the name commonly used for GNU make
    on BSD systems.

  - GCC >= 3.4 (up to 8.1 tested). Older versions can be made to work with a
    few minor adaptations if really needed. Newer versions may sometimes break
    due to compiler regressions or behaviour changes. The version shipped with
    your operating system is very likely to work with no trouble. Clang >= 3.0
    is also known to work as an alternative solution. Recent versions may emit
    a bit more warnings that are worth reporting.

  - GNU ld (binutils package), with no particular version. Other linkers might
    work but were not tested.

I have:

**yum info gcc**
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-mirror.rbc.ru
 * extras: dedic.sh
 * updates: centos-mirror.rbc.ru
Installed Packages
Name        : gcc
Arch        : x86_64
Version     : 4.4.7
Release     : 23.el6
Size        : 19 M
Repo        : installed
From repo   : base
Summary     : Various compilers (C, C++, Objective-C, Java, ...)
URL         : http://gcc.gnu.org
License     : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions
Description : The gcc package contains the GNU Compiler Collection version 4.4.
            : You'll need this package in order to compile C code.

**yum info make**
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-mirror.rbc.ru
 * extras: dedic.sh
 * updates: centos-mirror.rbc.ru
Installed Packages
Name        : make
Arch        : x86_64
Epoch       : 1
Version     : 3.81
Release     : 23.el6
Size        : 1.0 M
Repo        : installed
From repo   : base
Summary     : A GNU tool which simplifies the build process for users
URL         : http://www.gnu.org/software/make/
License     : GPLv2+
Description : A GNU tool for controlling the generation of executables and other
            : non-source files of a program from the program's source files. Make
            : allows users to build and install packages without any significant
            : knowledge about the details of the build process. The details about
            : how the program should be built are provided for make in the program's
            : makefile.

**yum info binutils**
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-mirror.rbc.ru
 * extras: dedic.sh
 * updates: centos-mirror.rbc.ru
Installed Packages
Name        : binutils
Arch        : x86_64
Version     : 2.20.51.0.2
Release     : 5.48.el6_10.1
Size        : 9.4 M
Repo        : installed
From repo   : updates
Summary     : A GNU collection of binary utilities
URL         : http://sources.redhat.com/binutils
License     : GPLv3+
Description : Binutils is a collection of binary utilities, including ar (for
            : creating, modifying and extracting from archives), as (a family of GNU
            : assemblers), gprof (for displaying call graph profile data), ld (the
            : GNU linker), nm (for listing symbols from object files), objcopy (for
            : copying and translating object files), objdump (for displaying
            : information from object files), ranlib (for generating an index for
            : the contents of an archive), readelf (for displaying detailed
            : information about binary files), size (for listing the section sizes
            : of an object or archive file), strings (for listing printable strings
            : from files), strip (for discarding symbols), and addr2line (for
            : converting addresses to file and line).

**Comment by lukastribus** [comment]
@cognet the new `_HA_ATOMIC_*` macros break the build in CentOs 6 (gcc 4.4.7) again. Can we do something to make this work with those ancient gcc releases, just like we did in commit 1a69af6d3892 ?

**Comment by cognet** [comment]
Ooops, sorry about that, I took great care of supporting both newer and older gcc versions, but I defined the >= 4.7 gcc just after the relevant #ifdef, so of course it wouldn't work so well on older gcc versions.
It should be much better now :)

**Comment by lukastribus** [comment]
Confirmed, fixed in 3212a2c43 (`BUG/MEDIUM: Threads: Only use the gcc >= 4.7 builtins when using gcc >= 4.7`).
