### ISSUE TITLE
Add support for `cookie <name> prefix nocache httponly secure attr "SameSite=None"`

### ISSUE THREAD

**Issue by mbattista** [haproxy/haproxy#831]
## What should haproxy do differently? Which functionality do you think we should add? What are you trying to do?

We have haproxy in front of multiple backend webserver. The loadbalancing needs to happen based on a cookie (because we do not know how long the user needs to land on the same backend webserver). As of writing haproxy's prefix option manipulates the cookie by dropping existing `Secure; HttpOnly; SameSite=None`. Thus we are trying to re-add the before mentioned cookie attributes. This seems not to be supported.

An alternative to this feature request could be to make haproxys feature option to not drop existing cookie attributes to be future-proof.

haproxy configuration extract:
```
backend backend_http
    balance roundrobin
[...]
    cookie PHPSESSID prefix nocache httponly secure attr "SameSite=None"
    server web-01 10.0.0.1:443 check port 80 cookie w01 ssl verify none
    server web-02 10.0.0.2:443 check port 80 cookie w02 ssl verify none
    server web-03 10.0.0.3:443 check port 80 cookie w03 ssl verify none
[...]
```

Current result from `curl` request:
```
[...]
set-cookie: PHPSESSID=w03~8779f98473ae67738a47889d968a1264; path=/
[...]
```

Desired result from `curl` request:
```
[...]
set-cookie: PHPSESSID=w03~8779f98473ae67738a47889d968a1264; path=/; Secure; HttpOnly; SameSite=None
[...]
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.13-1~bpo9+1 2020/02/15 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.0.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.0l  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.0l  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.22 2016-07-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

```

```
Linux tux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
```

**Comment by lukastribus** [comment]
You should really use a dedicated cookie, as opposed to reuse application cookies.

Prefixing existing application cookies is a ugly workaround for a specific client issue and probably irrelevant since a decade or two.

I'd actually suggest we contemplate deprecating `cookie ... prefix` functionality.

**Comment by robert-scheck** [comment]
> I'd actually suggest we contemplate deprecating `cookie ... prefix` functionality.

Honestly, I would prefer that haproxy does not simply remove things like `Secure; HttpOnly; SameSite=None` when it manipulates a cookie using `prefix`, that would make its behaviour at least more transparent. It also hopefully reduces the implementation amount?

**Comment by wtarreau** [comment]
Well, as Lukas mentioned, `prefix` is extremely old. However I'm quite surprised that it results in dropping attributes. I suspect that when it was designed, attributes didn't even exist and that we might have gone through various simplifications!
I don't really want to deprecate this feature because it does have some value in certain environments where many layers are stacked; in this case instead of having one cookie for each layer, you can just prefix the existing one and each layer will have its own prefix. But I agree it's not the most common usage.

**Comment by lukastribus** [comment]
I cannot reproduce your claim that haproxy is dropping those attributes.

This is haproxy 2.0.13 with a similar config:

```
backend my-backend
 balance roundrobin
 http-request set-header Host www.lan.ltri.eu
 cookie APPSESSID prefix nocache httponly secure attr "SameSite=None"
 server s3 10.0.0.31:80 cookie server3
```


The server emits a cookie with those attributes:

```
lukas@www:~$ curl -v www.lan.ltri.eu/cookie-attr.php
*   Trying 10.0.0.31...
* TCP_NODELAY set
* Connected to www.lan.ltri.eu (10.0.0.31) port 80 (#0)
> GET /cookie-attr.php HTTP/1.1
> Host: www.lan.ltri.eu
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.14.0 (Ubuntu)
< Date: Sat, 29 Aug 2020 07:20:51 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: APPSESSID=123456789; expires=Sat, 29-Aug-2020 08:11:14 GMT; Max-Age=3600; path=/; HttpOnly; SameSite=None
<
* Connection #0 to host www.lan.ltri.eu left intact
```


And haproxy, although rewriting the cookie and adding the server prefix, does not drop the attributes:

```
lukas@www:~$ curl -v dev.lan.ltri.eu/cookie-attr.php
*   Trying 10.0.0.33...
* TCP_NODELAY set
* Connected to dev.lan.ltri.eu (10.0.0.33) port 80 (#0)
> GET /cookie-attr.php HTTP/1.1
> Host: dev.lan.ltri.eu
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< server: nginx/1.14.0 (Ubuntu)
< date: Sat, 29 Aug 2020 07:20:55 GMT
< content-type: text/plain; charset=utf-8
< transfer-encoding: chunked
< set-cookie: APPSESSID=server3~123456789; expires=Sat, 29-Aug-2020 08:11:14 GMT; Max-Age=3600; path=/; HttpOnly; SameSite=None
<
* Connection #0 to host dev.lan.ltri.eu left intact
lukas@www:~$
```

It's not going to add those attributes to the application cookies that don't have them, because all those `httponly`, `secure `and `attr` keywords work for cookie insertion only, as documented. But haproxy is not removing attributes.

**Comment by lukastribus** [comment]
If on the other hand your application cannot emit the cookie with those attributes, but you need them, just use normal header rewriting as suggested in the other githubt issue:

https://github.com/haproxy/haproxy/issues/361#issuecomment-581644718

Even you if *also* use cookie persistence in prefix mode, http-header rewriting still works fine and does it's job:

```
lukas@www:~$ curl -v www.lan.ltri.eu/cookie-attr.php
*   Trying 10.0.0.31...
* TCP_NODELAY set
* Connected to www.lan.ltri.eu (10.0.0.31) port 80 (#0)
> GET /cookie-attr.php HTTP/1.1
> Host: www.lan.ltri.eu
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.14.0 (Ubuntu)
< Date: Sat, 29 Aug 2020 07:30:25 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: APPSESSID=123456789
<
* Connection #0 to host www.lan.ltri.eu left intact
lukas@www:~$
lukas@www:~$
lukas@www:~$ curl -v dev.lan.ltri.eu/cookie-attr.php
*   Trying 10.0.0.33...
* TCP_NODELAY set
* Connected to dev.lan.ltri.eu (10.0.0.33) port 80 (#0)
> GET /cookie-attr.php HTTP/1.1
> Host: dev.lan.ltri.eu
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< server: nginx/1.14.0 (Ubuntu)
< date: Sat, 29 Aug 2020 07:30:27 GMT
< content-type: text/plain; charset=utf-8
< transfer-encoding: chunked
< set-cookie: APPSESSID=server3~123456789; SameSite=None
<
* Connection #0 to host dev.lan.ltri.eu left intact
lukas@www:~$

```

**Comment by wtarreau** [comment]
Thanks Lukas for testing. I was a bit surprised that we could have written extra code to suppress such attributes, so I'd rather imagine an error in the analysis.

**Comment by mbattista** [comment]
I am very sorry.

It seems that the application did in fact not set the header in the first place. It worked on a dev enviroment which lead me to believe that haproxy dropped the header attributes.

I will close the issue since there were a lot of good advices that helped to fix the problem.

**Comment by lukastribus** [comment]
Thanks for the feedback, no need to be sorry!

**Comment by wtarreau** [comment]
On Tue, Sep 01, 2020 at 11:35:19AM -0700, Lukas Tribus wrote:
> Thanks for the feedback, no need to be sorry!

Seconded!
