### ISSUE TITLE
src/sock.c: coverity suspects unchecked return value

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#834]
```
   CID 1432232 (#1 of 1): Unchecked return value from library (CHECKED_RETURN)4. check_return: Calling setsockopt(sock, 1, 20, (void *)&tv, 16U) without checking return value. This library function may fail and return an error code.
131        setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, (void *)&tv, sizeof(tv));
```

**Comment by wtarreau** [comment]
It was previously in cli.c and I think it was marked as ignored as we don't care much. I'm still working in this area so it's possible I'll come back to this function soon anyway, I may add a test just to shut it up.

**Comment by chipitsine** [comment]
Adding disguise is bad idea?

**Comment by chipitsine** [comment]
I will mark ignored today

**Comment by wtarreau** [comment]
It's not a bad idea, it's just inelegant. We should use it when we have no other easy choice. But in this function there are already plenty of error checks so it'd be cleaner to add a check for this one as well.
