### ISSUE TITLE
Wrong value of http mode frontend conn_rate

### ISSUE THREAD

**Issue by pboguslawski** [haproxy/haproxy#836]
Hello,

Seems there is a bug in conn_rate counting for http mode frontends.

Using config like...

> backend st-ip
>     stick-table type ip size 1m expire 10s store conn_cur,conn_rate(10s),http_req_rate(10s)
> 
> frontend https
>     bind *:1443 ssl crt /etc/ssl/key-crt-ca.pem ca-file /etc/ssl/intermediate.pem ca-verify-file /etc/ssl/root.pem verify required
>     tcp-request inspect-delay 10s
>     id 1200
>     mode http
>     http-request capture req.fhdr(Host) len 64
>     http-request capture req.fhdr(User-Agent) len 256
>     http-request track-sc0 src table st-ip
> [...]

...we have such stats before test...

> \# echo 'show stat https -1 -1 typed' | socat unix:/run/haproxy.sock - | grep -P 'conn_|req_'
> F.1200.0.46.req_rate.1:MRP:u32:0
> F.1200.0.47.req_rate_max.1:MMP:u32:0
> F.1200.0.48.req_tot.1:MCP:u64:0
> F.1200.0.77.conn_rate.1:MRP:u32:0
> F.1200.0.78.conn_rate_max.1:MMP:u32:0
> F.1200.0.79.conn_tot.1:MCP:u64:0
> 
> echo 'show table st-ip' | socat unix:/run/haproxy.sock -
> \# table: st-ip, type: ip, size:1048576, used:0

...and then we refresh page in Firefox (limit of 6 connections per server) which need 30 HTTP requests to be refreshed; w few seconds after this reload haproxy data shows conn_rate = 30 in stick table equal to http_req_rate = 30...

> echo 'show table st-ip' | socat unix:/run/haproxy.sock -
> \# table: st-ip, type: ip, size:1048576, used:1
> 0x55a9622dbc20: key=client.ip.here use=0 exp=8778 conn_rate(10000)=30 conn_cur=0 http_req_rate(10000)=30

...but its wrong because Firefox used max 6 connections and web application uses keepalives so connections are reused - checked with tcpdump; also frontend stats show correct conn_tot and conn_max_rate:

> echo 'show stat https -1 -1 typed' | socat unix:/run/haproxy.sock - | grep -P 'conn_|req_'
> F.1200.0.46.req_rate.1:MRP:u32:0
> F.1200.0.47.req_rate_max.1:MMP:u32:29
> F.1200.0.48.req_tot.1:MCP:u64:30
> F.1200.0.77.conn_rate.1:MRP:u32:0
> F.1200.0.78.conn_rate_max.1:MMP:u32:5
> F.1200.0.79.conn_tot.1:MCP:u64:6

It seems that in http mode haproxy increases conn_rate in stick table on every new http request not on every new connection and one cannot control rate of connections for such http mode frontend nor for mix of tcp frontends and such http mode frontend (to limit all tcp conns per src ip for example regardless of frontend).

No such problem when tcp mode frontends use such stick table.

Problem checked on Debian, in haproxy 2.2.2-1 and 1.8.19-1+deb10u2 from experimental and buster:

https://packages.debian.org/experimental/haproxy
https://packages.debian.org/buster/haproxy

No issue/bugfix found on Github so probably problem exists in master also.

Regards,
Paweł

**Comment by wtarreau** [comment]
Even though it's not obvious, it's expected: the `track-sc` directives have a scope limited to the same class they're tracking. This means that here if you're tracking using http-request, the tracking will not survive longer than a request-response cycle, and the next request will lead to a new tracking, resulting in a new counter increase. The right way to count connections is to track them at the TCP level, using `tcp-request connection track-sc0 src` for example.

**Comment by pboguslawski** [comment]
Thank you for response.

`tcp-request connection` and `tcp-request content` variants were checked also without success during out tests in http mode frontend.

Just checked this scenario again in haproxy 1.8.19-1+deb10u2  from buster...

```
backend st1
    stick-table type ip size 1m expire 10s store conn_cur,conn_rate(10s)

frontend https
    id 1200
    mode http
    [...] 
    tcp-request connection track-sc0 src table st1
```
  
...but `tcp-request connection` doesn't even update st1; when using...

`     tcp-request content track-sc0 src table st1`

...st1 is updated but the same problem occurs - conn_rate is higher than should be (probably still every http request updates it):
```
# echo 'show table st1' | socat unix:/run/haproxy.sock -
# table: st1, type: ip, size:1048576, used:1
0x55e62ca2c690: key=client.ip.here use=6 exp=94 conn_rate(10000)=30 conn_cur=6

# echo 'show stat 1200 -1 -1 typed' | socat unix:/run/haproxy.sock - | grep -P 'conn_|req_'
F.1200.0.46.req_rate.1:MRP:u32:0
F.1200.0.47.req_rate_max.1:MMP:u32:16
F.1200.0.48.req_tot.1:MCP:u64:30
F.1200.0.77.conn_rate.1:MRP:u32:0
F.1200.0.78.conn_rate_max.1:MMP:u32:5
F.1200.0.79.conn_tot.1:MCP:u64:6
```
BTW: if `http-request` cannot be used for `conn_rate` checking we would like to use `tcp-request content` because at `tcp-request connection` stage there is no access for client certificate details and we would like to limit connection rate per `ssl_c_serial` for example not per `src`.

**Comment by wtarreau** [comment]
I don't know why it doesn't work at the connection level but I trust you. Regarding tcp-content, it's the same problem as with HTTP, as due to the fact that people used to employ "tcp-request content" a lot with HTTP stuff, when keep-alive was implemented it was decided that the tcp-content context is reset after each request.

For your use case you also have `tcp-request session` which happens after the handshakes are complete, thus the ssl_c_serial will be available. I'm obviously interested in knowing if it works for you!

**Comment by pboguslawski** [comment]
`tcp-request session` works ok for limiting conn_rate (based on ip or ssl data) - thank you!

Is it possible to use the same stick table for limiting conn_curr, conn_rate and http_req_rate like this?

```
backend st-ip
    stick-table type ip size 1m expire 10s store conn_cur,conn_rate(10s),http_req_rate(10s)

frontend smtp
[...]
    mode tcp
    tcp-request inspect-delay 10s
    tcp-request session track-sc0 src table st-ip
    tcp-request session reject if { sc_conn_cur(0) gt 100 }
    tcp-request session reject if { sc_conn_rate(0) gt 100 }


frontend http
[...]
    mode http
    tcp-request inspect-delay 10s
    tcp-request session track-sc0 src table st-ip
    tcp-request session reject if { sc_conn_cur(0) gt 20 }
    tcp-request session reject if { sc_conn_rate(0) gt 100 }
    http-request reject if { sc_http_req_rate(0) gt 500 }
```
It seems to work ok during tests but not sure if http_req_rate in stick-table tracked in `tcp-request session` will be updated correctly for `http-request reject`  and no other "suprises" occur during tcp/http request life.

Regards,
Paweł

**Comment by wtarreau** [comment]
Yes normally it should work, as the tracking is set up upon session creation.

**Comment by pboguslawski** [comment]
Thank you for help. Closing this issue.
