### ISSUE TITLE
Exposed prometheus metrics jumping all over the place

### ISSUE THREAD

**Issue by uselessjargon** [haproxy/haproxy#843]
I am testing out using the built-in prometheus metrics for haproxy 2 and I am finding the counter haproxy_frontend_http_responses_total jumping up and down 100K+ increments. The same counters from the haproxy_exporter are incrementing as they should on the same node.

**In haproxy.cfg:**
frontend stats
  bind *:8404
  stats enable
  stats uri /stats
  stats refresh 10s
  http-request use-service prometheus-exporter if { path /metrics }
  option http-use-htx

**Haproxy version:**
[root@s311XX ~]# haproxy -v
HA-Proxy version 2.0.15-4f39279 2020/06/12 - https://haproxy.org/

**Haproxy exposed prometheus metrics:**
```
while :;do curl -s s311XX:8404/metrics | grep haproxy_frontend_http_responses_total | grep -i "dbg-drupal-render-ssl:443" | grep 2xx;sleep 1;done
haproxy_frontend_http_responses_total{proxy="dbg-drupal-render-ssl:443",code="2xx"} 229685
haproxy_frontend_http_responses_total{proxy="dbg-drupal-render-ssl:443",code="2xx"} 337434
haproxy_frontend_http_responses_total{proxy="dbg-drupal-render-ssl:443",code="2xx"} 229686
haproxy_frontend_http_responses_total{proxy="dbg-drupal-render-ssl:443",code="2xx"} 156366
haproxy_frontend_http_responses_total{proxy="dbg-drupal-render-ssl:443",code="2xx"} 337435
haproxy_frontend_http_responses_total{proxy="dbg-drupal-render-ssl:443",code="2xx"} 172701
```

**Haproxy metrics from prometheus haproxy_exporter:**
```
while :;do curl -s s311XX:9101/metrics | grep haproxy_frontend_http_responses_total | grep -i "dbg-drupal-render-ssl:443" | grep 2xx;sleep 1;done
haproxy_frontend_http_responses_total{code="2xx",frontend="dbg-drupal-render-ssl:443"} 337474
haproxy_frontend_http_responses_total{code="2xx",frontend="dbg-drupal-render-ssl:443"} 337476
haproxy_frontend_http_responses_total{code="2xx",frontend="dbg-drupal-render-ssl:443"} 337476
haproxy_frontend_http_responses_total{code="2xx",frontend="dbg-drupal-render-ssl:443"} 337476
haproxy_frontend_http_responses_total{code="2xx",frontend="dbg-drupal-render-ssl:443"} 337481
haproxy_frontend_http_responses_total{code="2xx",frontend="dbg-drupal-render-ssl:443"} 337481
haproxy_frontend_http_responses_total{code="2xx",frontend="dbg-drupal-render-ssl:443"} 337485
```

**Comment by wtarreau** [comment]
Given that the exposed counters are monotonous, the only explanation I can find is that you're hitting different processes. So either you have an old process still present that coexists with the new one, or you have the global `nbproc` directive in your config.

**Comment by uselessjargon** [comment]
Thanks for the response. We do have the `nbproc` directive in our config. In some of our implementations where we are not doing ssl termination we can switch to using `nbthread`. However, for those that do need `nbproc` it sounds like the built-in prometheus stats are useless?

**Comment by wtarreau** [comment]
Then you could have different ports for each process so that you collect each of them separately. Just out of curiosity, what justifies keeping nbproc in your case (aside the need to change a running config, of course) ?

**Comment by uselessjargon** [comment]
Probably nothing justifies it at this point. Right now nbproc seems to be the standard configuration in our chef cookbooks though I don't have a history of why it's that way. I have read that nbproc helps with scaling setups doing ssl termination. In those cases where we might need nbproc we can just go back to using haproxy_exporter. Thanks for your help and time.

**Comment by uselessjargon** [comment]
I'm closing this issue.

**Comment by wtarreau** [comment]
Then it was probably added before we had threads as the only way to scale.
You should probably try to remove it from your configs and benefit from an
even higher scalability without the downsides that come with nbproc. I
don't know what versions you have in your production, but as a rule of
thumb, I'd suggest using threads starting from 2.0 and to keep using
nbproc on 1.8 and earlier.

**Comment by uselessjargon** [comment]
Ah ok.That makes sense. We had just updated our cookbooks from version 1.8 to 2.0 haproxy so the nbproc is a left over from that version. I appreciate all the input here!
