### ISSUE TITLE
Haproxy stucks with sched_yield

### ISSUE THREAD

**Issue by VipulsSharma** [haproxy/haproxy#858]
## Detailed description of the problem

Haproxy Version Info : 
HA-Proxy version 1.8.25-1ppa1~bionic 2020/04/19
Copyright 2000-2020 Willy Tarreau <willy@haproxy.org>

Running with nbproc set as 1 while nbthread as 16.
On a 8 core server.

All the threads go into a wait4(-1, state while one of the thread among the same is in give state : 

[pid xxx] sched_yield( <unfinished ...>
[pid xxx] <... sched_yield resumed> ) = 0
[pid xxx] <... sched_yield resumed> ) = 0

All the new upcoming requests land in Rec-Q for haproxy , even the stats page and no requests is served by haproxy during this time.

Restarting the process seems to resolve the issue.

## Expected behavior

The bug appears to be in earlier versions of haproxy 
http://git.haproxy.org/?p=haproxy-1.8.git;a=commitdiff;h=3aa7e5a

Also the CPU core utilisation for this duration is high.

## Steps to reproduce the behavior

Running haproxy version HA-Proxy version 1.8.25-1ppa1~bionic 2020/04/19.
Ubuntu OS
nbproc as 1 and nbthread as 16 on a 8 core system.

Produces the bug.

## Do you have any idea what may have caused this?
No

## Do you have an idea how to solve the issue?
I think lowering the number of threads.

## What is your configuration?

```
Basic config haproxy with some frontend and backend , no specific parameters set.
```

## Output of `haproxy version`

```
HA-Proxy version 1.8.25-1ppa1~bionic 2020/04/19
Copyright 2000-2020 Willy Tarreau <willy@haproxy.org>

Ubuntu Bionic OS
```

**Comment by capflam** [comment]
Sorry, no one answered to you. Is it still a problem for you or not ?

**Comment by capflam** [comment]
I'm closing this issue now. Feel free to reopen it if necessary.
