### ISSUE TITLE
Configuration allows two frontends to bind to the same IP and port

### ISSUE THREAD

**Issue by NickMRamirez** [haproxy/haproxy#868]
## Detailed description of the problem

Given a configuration where two `frontend` sections bind to the same IP address and port, there is currently no error and HAProxy starts up without any issue. However, the second `frontend` recives no requests. It should be considered an invalid configuration to have two frontends that bind to the same address and port.

Example:

```
frontend fe1
    bind :80
    default_backend servers1

# this frontend will never be called
frontend fe2
  bind :80
  default_backend servers2
```

Validation has no issue with this:

```
$ haproxy -c -f /etc/haproxy/haproxy.cfg 
Configuration file is valid
```

## Expected behavior

I believe that the validator should throw at least a warning about this, to indicate that the user has most likely, unintentionally, added two frontends that bind to the same address, but only one of them will be used. This is a more likely scenario when the configuration is created through automated processes, such as via the Data Plane API, where multiple users and teams may be creating frontends independently, through separate CI/CD pipelines. 

Without a warning, it sets up a "whoever got there first" scenario, where the one who got there first gets the binding, while the one who got there second believes their frontend should work, but does not.

## Steps to reproduce the behavior

1. Update haproxy.cfg to have two frontends that are bound to the same IP and port (or no IP and just port)
2. Validate that the configuration is valid
3. Start HAProxy and receive no error or warning

## Do you have any idea what may have caused this?

no

## Do you have an idea how to solve the issue?

Create a warning or error in the validator

## What is your configuration?

```
frontend fe1
    bind :80
    default_backend servers1

frontend fe2
  bind :80
  default_backend servers2

backend servers1
   server server1 127.0.0.1:8080

backend servers2
  server server1 127.0.0.1:8081
```

## Output of `haproxy -vv` and `uname -a`

```
 haproxy -vv
HA-Proxy version 2.2.1-1ppa1~bionic 2020/07/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.1.html
Running on: Linux 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-Z1CobD/haproxy-2.2.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app


$ uname -a
Linux server1 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by roidelapluie** [comment]
I am not sure whether it is a bug or not, but it is possible because HAPROXY is using SO_REUSEPORT.

You can even launch 2 haproxy at the same time as long as they use the same unix user.

**Comment by lukastribus** [comment]
This is expected behavior and can be disabled with the [noreuseport](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#3.2-noreuseport) directive.

There is a feature request  #629 about implementing additional safe guards against this misconfiguration.

**Comment by NickMRamirez** [comment]
It seems strange that the default behavior is to allow multiple bindings on the same address, which I can only think is a misconfiguration, since it results in one frontend being unreachable, and that there is then a directive to disable this (`noreuseport`). I'd expect it would have been the reverse: The default behavior is to _not_ allow multiple bindings on the same address, but you can enable it if you wanted (like `allowreuseport`).

**Comment by roidelapluie** [comment]
The default behaviour is needed to have multiple processes (`nproc` > 1 ) and handle reloads, I think.

**Comment by lukastribus** [comment]
Correct, there are a number of technical reasons why reuseport is the default.

Now configuration error checking on the other hand, that is what the feature request in the other issue is about.

**Comment by NickMRamirez** [comment]
Thanks @lukastribus and @roidelapluie. I think this issue could probably be closed now, since there is already a feature request covering this suggested functionality (displaying an error or warning).
