### ISSUE TITLE
Allow HAProxy to overwrite server errors with custom error pages

### ISSUE THREAD

**Issue by NickMRamirez** [haproxy/haproxy#869]
## What should haproxy do differently? Which functionality do you think we should add?

As a feature request, it would be good if HAProxy could intercept errors from the backend servers (404, 500, etc.) and replace them with custom error pages. Currently, HAProxy supports displaying custom error pages only for errors that it generates, but in order to overwrite server errors, a hack is required: You must use `http-response deny` to deny the response with the same error code as the server (e.g. 404, 500). Then, HAProxy can use its own error file. 

Having the option to store all custom error pages in HAProxy means that a user can guarantee custom error pages are shown, regardless of which backend web server technology is used and regardless of whether the backend servers are up or down.

There was a new directive introduced: `http-error status`, but so far, it does not seem very useful, since it does not support intercepting and overwriting server errors.

## What are you trying to do?

Create branded custom error pages and have HAProxy be the single place to manage them. This functionality is there for errors originating from HAProxy, but so far, it can not overwrite errors from the servers, which severely limits its real-world applications.

## Output of `haproxy -vv` and `uname -a`

```
$ haproxy -vv
HA-Proxy version 2.2.1-1ppa1~bionic 2020/07/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.1.html
Running on: Linux 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-Z1CobD/haproxy-2.2.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app

$ uname -a
Linux server1 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jmagnin** [comment]
Hi,

Haproxy 2.2 introduced  [http-response return](https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#4.2-http-response%20return) for that. See the example, it details how to respond based on status.

**Comment by NickMRamirez** [comment]
@jmagnin Interesting! Yes, this works.

I wonder then, what is the purpose of `http-error status`?

**Comment by jmagnin** [comment]
if I were to take a wild guess, it gives errorfiles the flexibility of the return rules, such as adding headers, generated content, etc.., as opposed to a single static file with headers and body.

    listen foo
      bind :8080
      http-error status 403 content-type text/plain lf-string "you shall not %[path]"
      http-request deny

**Comment by NickMRamirez** [comment]
It looks like `http-response return` does what I wanted, and it looks less hacky than my original idea of using `http-request deny` to intercept server errors. The `http-response return` directive can also return `lf-file` and `lf-string`, if I want to inject some variables, and it supports adding headers. So, it seems to have it all! 

This feature request could probably be closed. Thank you @jmagnin for pointing out the solution!
