### ISSUE TITLE
inconsistent behaviour for ssl crt directory and ssl runtime API 

### ISSUE THREAD

**Issue by wdauchy** [haproxy/haproxy#872]
On haproxy v2.2, we are loading our certs this way:
```
bind x.x.x.x:443 name https_ip4 process 1/all ssl crt /etc/haproxy/tls/fe_foo alpn h2,http/1.1 tfo allow-0rtt namespace haproxy
```
The directory contains certificate as a bundle, i.e.:
```
_.foo.com.pem.ecdsa
_.foo.com.pem.rsa
```
So that certificate are loaded as bundle:
```
# echo -e "show ssl crt-list /etc/haproxy/tls/fe_foo.com" | socat stdio /var/lib/haproxy/stats
# /etc/haproxy/tls/fe_foo.com
/etc/haproxy/tls/fe_foo.com/_.foo.com.pem
```
We are then using `set ssl cert` runtime API to update the certs as follow:
```
# echo -e "set ssl cert /etc/haproxy/tls/fe_foo.com/_.foo.com.pem.ecdsa <<\n$(cat /etc/haproxy/tls/fe_foo.com/_.foo.com.pem.ecdsa)\n" | socat stdio /var/lib/haproxy/stats 
Transaction created for certificate /etc/haproxy/tls/fe_foo.com/_.foo.com.pem!
# echo -e "commit ssl cert /etc/haproxy/tls/fe_foo.com/_.foo.com.pem" | socat stdio /var/lib/haproxy/stats
Committing /etc/haproxy/tls/fe_foo.com/_.foo.com.pem
Success!
```
Notice that the existing bundle is auto detected, despite we do a `set ssl cert` on a `.ecdsa` file.

We recently started to have a closer look at `new ssl cert <filename>` command in runtime API, so we can add new ones:
```
# echo -e "new ssl cert /etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa" | socat stdio /var/lib/haproxy/stats
New empty certificate store '/etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa'!
# echo -e "set ssl cert /etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa <<\n$(cat /etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa)\n" | socat stdio /var/lib/haproxy/stats 
Transaction created for certificate /etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa!
# echo -e "commit ssl cert /etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa" | socat stdio /var/lib/haproxy/stats
Committing /etc/haproxy/tls/fe_foo.com/_.bar.pem.ecdsa
Success!
# echo "add ssl crt-list /etc/haproxy/tls/fe_foo.com /etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa" | socat stdio /var/lib/haproxy/stats
Inserting certificate '/etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa' in crt-list '/etc/haproxy/tls/fe_foo.com'..
Success!
```
So my new cert is not added as a bundle. I also tried to add it as `new ssl cert /etc/haproxy/tls/fe_foo.com/_.bar.com.pem` and then `set ssl cert /etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa` but it is refused.

```
# echo "show ssl crt-list /etc/haproxy/tls/fe_foo.com" | socat stdio /var/lib/haproxy/stats
# /etc/haproxy/tls/fe_foo.com
/etc/haproxy/tls/fe_foo.com/_.foo.com.pem
/etc/haproxy/tls/fe_foo.com/_.bar.com.pem.ecdsa
``` 

It creates an inconsistent state as when it comes to update `_.bar.com.pem.ecdsa` the commit command is different, because this is not a bundle. So along the life of a process I first need to do a show on the certs, to make sure I use the proper update commands.

Did I miss something in the process? Or should we move to another way to load our cert in our config file?

Thanks,

**Comment by wlallemand** [comment]
Hello William,

I responded to your mail this morning about this, maybe you didn't get it, but I'll resume it here so we can share this with people interested.

The bundle is the deprecated way of using multiple certificates type, with OpenSSL 1.0.2 it was only possible to use multiple certificate types only by putting them in the same SSL_CTX structure, so OpenSSL was handling this by itself. It is not convenient to do this from a software architecture point of view, but this was the only way then. With recent version of OpenSSL an clienthello callback was implemented so the software can chose itself which certificate it want.

So this was a will to remove the OpenSSL bundle in HAProxy, so we decided to stop supporting them for the new CLI features.

You can load directly each certificates with the "crt" keyword, with OpenSSL 1.1.1, HAProxy will be able to use them without the bundles.

In HAProxy 2.3, the OpenSSL bundle support was removed but it is emulated by loading separately the certificates which were loaded the bundle way, so the configuration is still compatible, but you'll see separate certificates on the CLI.

**Comment by wlallemand** [comment]
I replied too fast, you need to customize the "[ssl-load-extra-files](https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#ssl-load-extra-files)" directive, without the bundle support, so the certificates in the directories will be loaded separately.

**Comment by wdauchy** [comment]
Thank you very much @wlallemand for your complete answer.

- we might have an issue between us around emails, because this is not the first time I see I don't receive emails from you, but find them in the mailing list by chance :) I saw this issue with both my pro and perso email. anyway, lets try to find out in private.
- in fact yesterday, I was a bit lost around cert bundle. Because I found your commits stating bundle were deprecated, but could not understand how I had to migrate, as we are using directories, I did not wanted to specify the many certificates we have. The missing key was in fact `ssl-load-extra-files`, I completely missed that. Thank you. I will give another try :)
- there might be some documentation to improve in v2.2 for crt config, so that users starts to move away from bundle. Maybe adding a link towards ssl-load-extra-files.

Sorry for the noise

**Comment by wlallemand** [comment]
No problem, let's keep the ticket open so we can address the documentation issue.

**Comment by wdauchy** [comment]
@wlallemand I've sent a proposition in the mailing list

**Comment by wlallemand** [comment]
Hello William,

By reading your patch I think we made the mistake of calling "bundle" the SSL_CTX and the HAProxy configuration, it creates a confusion everywhere and I made this mistake again by explaining the situation here.

So I'll try to clarify again:

With HAProxy <= 2.2 and OpenSSL >= 1.0.2, an HAProxy multi-certificates bundle (cert bundle) is the autodiscovery of certificate files (.rsa, .ecdsa, .dsa) when you set a non-existing file in your configuration. This autodiscovery loads each certificate in the certificates store of the SSL_CTX(3 types: ecdsa, rsa, dsa). This was the only way then to do an "hybrid" ECC/RSA bind on the same SNI.

With HAProxy >= 1.8 and <= 2.2 and OpenSSL  >= 1.1.1, cert bundle still loads the certificates in the same SSL_CTX store. But you can also do an hybrid ECC/RSA bind by loading separately the files in the configuration.

With HAProxy >= 2.3, the cert bundle does not load the certificates in the same SSL_CTX anymore, but loads one certificate type per SSL_CTX. At least OpenSSL 1.1.1 is required to do this, the bundles won't work anymore with previous version of OpenSSL.

The "new ssl cert" CLI command can only be used to create a SSL_CTX with a single certificate, so if you load the files with the bundle in HAProxy 2.2 you will have an inconsistency on the CLI. With HAProxy 2.3 you won't have this problem and you will see all the files separately on the CLI.

Regarding  your patch:

> this should probably be backported in >= v2.2 in order to encourage
people to move away from bundle certificates loading.

I think you meant <= v2.2, not >= v2.2. In my opinion this is not relevant for HAProxy 2.3, but I will review the documentation to see if there are still places where this is confusing.

**Comment by wdauchy** [comment]
@wlallemand thanks for the clarification, it is limpid now.
I think I previously understood correctly apart from the last changes made in v2.3; but I confirm the bundle wording is confusing in doc as it mixes haproxy specific with openssl specific.
For the patch, at the end, I think it should be backported in v2.2 only as `ssl-load-extra-files` does not exist < v2.2, right?

**Comment by wlallemand** [comment]
> but I confirm the bundle wording is confusing in doc as it mixes haproxy specific with openssl specific.

I'll made some clarification in 2.3.

> For the patch, at the end, I think it should be backported in v2.2 only as ssl-load-extra-files does not exist < v2.2, right?

I agree.

**Comment by wdauchy** [comment]
thanks @wlallemand. looks better now! one remaining typo is:
```
diff --git a/doc/configuration.txt b/doc/configuration.txt
index b01129f8f..a98284da3 100644
--- a/doc/configuration.txt
+++ b/doc/configuration.txt
@@ -1423,7 +1423,7 @@ ssl-load-extra-files <none|all|bundle|sctl|ocsp|issuer|key>*
   On the CLI, bundles are seen as separate files, and the bundle extension is
   required to commit them.
 
-  OSCP files (.ocsp), issuer files (.issuer), Certificate Transparency (.sctl)
+  OCSP files (.ocsp), issuer files (.issuer), Certificate Transparency (.sctl)
   as well as private keys (.key) are supported with multi-cert bundling.
 
   "sctl": Try to load "<basename>.sctl" for each crt keyword.
```
Should we send a patch for that?

**Comment by wlallemand** [comment]
sure @wdauchy
