### ISSUE TITLE
Typo in agent-check documentation

### ISSUE THREAD

**Issue by brenc** [haproxy/haproxy#876]
Just noting that there's a typo in the [`agent-check` documentation](http://cbonte.github.io/haproxy-dconv/2.1/configuration.html#5.2-agent-check):

> The words "down", "failed", or "stopped", optionally followed by a description string after a sharp ('#').

"Failed" should actually be "fail".

**Comment by wdauchy** [comment]
Thanks, I will fix this one

**Comment by capflam** [comment]
This issue is far from critical, so I close it, keeping 1.6 and 1.7 tags
