### ISSUE TITLE
docker/lua limiting log level does not work

### ISSUE THREAD

**Issue by sdahlbac** [haproxy/haproxy#879]
## Detailed description of the problem

When running haproxy docker container, with lua code containing `core.Debug` statements, the log messages are emitted even though log level is set to info.

## Expected behavior

No [debug] lines should be seen.

## Steps to reproduce the behavior

1. `wget https://raw.githubusercontent.com/haproxytech/haproxy-lua-cors/master/lib/cors.lua`
2. Dockerfile
```
FROM haproxy:2.3-dev-alpine

COPY haproxy.cfg cors.lua /usr/local/etc/haproxy/

EXPOSE 8002
```
3.  haproxy.cfg
```
global
    log stdout  format raw  local0  info
    lua-load /usr/local/etc/haproxy/cors.lua

defaults
    mode http
    log global
    option httplog

frontend http-in
    bind *:8002
    use_backend foo

backend foo
    http-request lua.cors "GET, PUT, POST, HEAD, DELETE" "localhost:8002"
    http-response lua.cors
```
4. `docker build --tag haproxy-log-test .`
5. `docker run -it -p8002:8002 --rm --name haproxy-log-test haproxy-log-test:latest haproxy -f /usr/local/etc/haproxy/haproxy.cfg`
6. In another terminal: `curl -X OPTIONS localhost:8002 -H Origin:'localhost:8002'`

7. See unexpected [debug] log output
```

[WARNING] 271/141112 (1) : config : missing timeouts for frontend 'http-in'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
Proxy http-in started.
Proxy foo started.
[NOTICE] 271/141112 (1) : New worker #1 (7) forked
[debug] 271/141123 (7) : CORS: Got 'Origin' header: localhost:8002
[debug] 271/141123 (7) : CORS: preflight request received
[debug] 271/141123 (7) : CORS: localhost:8002 not allowed
[debug] 271/141123 (7) : CORS: Returning reply to preflight request
172.17.0.1:56544 [28/Sep/2020:14:11:23.770] http-in foo/<NOSRV> 0/-1/-1/-1/0 204 164 - - LR-- 1/1/0/0/3 0/0 "OPTIONS / HTTP/1.1"
```
## What is your configuration?

```
(paste your output here)
```

## Output of `haproxy -vv` and `uname -a`

```
uname -a
Darwin myhostname.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

docker -v
Docker version 19.03.12, build 48a66213fe
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

**Comment by capflam** [comment]
In fact, it is not a log issue. The log messages are really skipped. It is related to informational messages displayed on the standard output. I guess, in this case, these messages should only be displayed in debug mode. It is true for the lua. But it may also concerns other kind of messages. I'll try to get an eye on it. Thanks

**Comment by capflam** [comment]
I pushed a fix to remove debug messages emitted by lua scripts, except if the debug mode is enabled.

**Comment by capflam** [comment]
I'm closing the issue now because it is more a improvement than a bug fix. I guess it will be backported but it is optional.
