### ISSUE TITLE
HAProxy 1.8 release for fix to http/2 connections terminated - ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by if-kenn** [haproxy/haproxy#884]
I am not filling out the form due to the fact that there are already multiple issues covering this, but they have been closed. 

- https://github.com/haproxy/haproxy/issues/768
- https://github.com/haproxy/haproxy/issues/798

The issue I am having is that there has not been a 1.8 release since the fix was added to 1.8.

I see recent releases for 2.0, 2.1, 2.2 & 2.3. However, it appears that 1.8 has not had a release since before the fix was added. 

- https://github.com/haproxy/haproxy/issues/798#issuecomment-669501946
- https://github.com/haproxy/haproxy/issues/768#issuecomment-669501543

Any information would be greatly appreciated. Thank you!

**Comment by wtarreau** [comment]
We'll issue another 1.8 soon. Older releases are emitted less often since their users upgrade less often and want proven fixes that have been cooking for some time in more recent branches. We'll try to make one next week as time permits.

**Comment by phlbrz** [comment]
Hi,

It really bring down my apps, I had to do disable HTTP2, as mentioned here https://github.com/haproxy/haproxy/issues/798#issuecomment-669142531
I'm using Openshift 3.11.317.
It uses haproxy version `HA-Proxy version 1.8.26 2020/08/03`
Also same haproxy version is in Openshift 3.11.318 and 3.11.346

**Comment by lukastribus** [comment]
Haproxy 1.8.27 has been released more than a month ago with this fix.

**Comment by phlbrz** [comment]
@lukastribus Thank you.
I couldn't find it in changelogs.
I'll wait for a new release with this fix in Openshift.

**Comment by frobware** [comment]
> I'll wait for a new release with this fix in Openshift.

Cross referencing the bugzilla tracking the openshift issue: https://bugzilla.redhat.com/show_bug.cgi?id=1918392#c4
