### ISSUE TITLE
Client-facing connection keep-alive after backend timeout or backend connection failure

### ISSUE THREAD

**Issue by jaroslawr** [haproxy/haproxy#889]
It would be nice to be able to use a fixed response AND keep the client connection intact in case of backend timeout or backend connection failure.

While it is possible in those cases to emit a given response body and response headers via the `errorfile` directive, it still forces the client to disconnect - HAProxy seems to force a 'Connection: close' header in the response regardless of the contents of the file provided as argument to `errorfile`. I am trying to provide a fixed HTTP response as fallback when our backend cluster is overloaded, but the reconnections that result from loss of keepalive then make the HAProxy cluster overloaded too.

**Comment by capflam** [comment]
I guess you are using a pre-HTX version (i.e < 1.9) or a version where it is possible to disable the HTX (1.9 and 2.0). Because, with the HTX (the new HTTP implementation since the 1.9, enabled by default in the 2.0), it is possible to keep the client connection alive independently of the server one. Thus, if you have an HTTP/1.1 errorfile without the "Connection: close" header, the client connection will be kept alive as expected.

Note also than since the 2.2, most of the default HTTP errors don't force the client connection closure. Only default 400 and 408 HTTP errors includes the "Connection: close" header.

**Comment by capflam** [comment]
I close the issue because the feature already exists. If you observe another behaviour with the HTX enabled (on 2.1 and above, it is the only HTTP implementation), it means it is a bug. In this case, re-open and relabel the issue, filling the "Bug Report" template to provide all requested information.

**Comment by jaroslawr** [comment]
@capflam Here is a test on haproxy 2.2.x:

```
HA-Proxy version 2.2.3-6a551a-16 2020/09/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.3.html
Running on: Linux 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64
```

My haproxy.cfg:

```
defaults
        mode http
        timeout client 10000
        timeout connect 100
        timeout server 5000

frontend lolcathost
        default_backend jetty
        bind localhost:8080

backend jetty
        errorfile 503 204.http
        errorfile 504 204.http
        server localhost_8082 localhost:8082
```

204.http is this:

```
HTTP/1.1 204 No Content
Cache-Control: no-cache

```

If the server defined in jetty backend is up the connection is reused correctly:

```
curl -v -v localhost:8080 localhost:8080
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Wed, 07 Oct 2020 19:18:27 GMT
< content-type: text/html;charset=utf-8
< content-length: 21
<
<h1>Hello World</h1>
* Connection #0 to host localhost left intact
* Found bundle for host localhost: 0x55c920fd7330 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Wed, 07 Oct 2020 19:18:27 GMT
< content-type: text/html;charset=utf-8
< content-length: 21
<
<h1>Hello World</h1>
* Connection #0 to host localhost left intact
```

If you bring up haproxy but the backend server is not up, haproxy will use 204.http but "connection: close" is added:

```
curl -v -v localhost:8080 localhost:8080
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< cache-control: no-cache
< connection: close
<
* Closing connection 0
* Hostname localhost was found in DNS cache
*   Trying ::1:8080...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#1)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< cache-control: no-cache
< connection: close
<
* Closing connection 1
```

Same thing happens when the jetty backend takes above `timeout server` to respond.

**Comment by jaroslawr** [comment]
@capflam Sorry, I first thought I could turn this issue here into a bug report. I opened a new issue instead: https://github.com/haproxy/haproxy/issues/891

**Comment by capflam** [comment]
No problem. Thanks for the report. I will investigate.
