### ISSUE TITLE
Unable to install on Ubuntu 18.04.02 LTS

### ISSUE THREAD

**Issue by oragain** [haproxy/haproxy#89]
## Output of `haproxy -vv` and `uname -a`

```
Linux a-sv-prd-bal-02 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

```

## What's the configuration?

```
No configuration - This is a setup and install issue
```

## Steps to reproduce the behavior

1. Install a fresh Ubuntu 18.04 install
2. Add the repository: add-apt-repository ppa:vbernat/haproxy-1.9
3. apt-get install haproxy

## Do you have any idea what may have caused this?

The following packages have unmet dependencies:
 haproxy : Depends: libpcre2-8-0 (>= 10.31) but it is not installable

## Do you have an idea how to solve the issue?
Allow HAProxy to use updated versions of the library

**Comment by lukastribus** [comment]
This is not a haproxy issue.

You have to check why `libpcre2-8-0` is not installable. I suggest Ubuntu support channels. You may just missing an `apt-get update` here before installing it.

**Comment by gravcat** [comment]
For anyone coming across this in the future, you'll need to enable the `universe` repo for your Ubuntu distribution. In my case, `bionic`.

references:
* https://help.ubuntu.com/community/Repositories/Ubuntu
* https://packages.ubuntu.com/bionic/libpcre2-8-0
