### ISSUE TITLE
ebtree: alignment issues on Sparc

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#9]
It was reported here about version 1.7 on Solaris/Sparc64 : 

   https://www.mail-archive.com/haproxy@formilux.org/msg25937.html

The problem is caused by the presence of `__attribute__((packed))` on the ebtree definition. Indeed, ((packed)) automatically disables alignment. Here we only want it so that eb32_nodes are not needlessly inflated twice and that the uint32 immediately follows the eb_node. But it also causes eb_nodes to be misaligned when the struct is placed anywhere within another struct, and its pointers cannot be accessed on some 64-bit platforms which don't support unaligned accesses.

A short-term solution would possibly consist in disabling the `__attribute__((packed))` on unsafe platforms (possibly only Sparc64 and MIPS64 by now). 

Other long-term solution should be studied to force alignment of the beginning of the struct even when the end is not filled with holes. Among the potential solutions, probably that placing this struct into a transparent union containing a single pointer would work.

This issue is tagged minor because apparently there are almost no more users of such platforms and the option of building for 32 bits often remains a valid workaround.

**Comment by TimWolla** [comment]
Hint: The `__attribute__((packed))` is being misrendered, because underscores have a special meaning in markdown. Use backticks to mark it as code.

**Comment by wtarreau** [comment]
Edited, thanks! I'd also love to disable the shitty pop-up that appears to propose icons every time we type the colon character which is quite highly needed in an issue tracker!

**Comment by capflam** [comment]
I consider this issue as fixed and I close it because a patch fixed this issue.
