### ISSUE TITLE
gRPC via HTTP/2 proxy unable to reconnect after server restart, error 503

### ISSUE THREAD

**Issue by rustyx** [haproxy/haproxy#914]
## Detailed description of the problem

It seems that gRPC can't handle stream reconnections in combination with haproxy and kubernetes.

When the grpc pod is restarted, the client keeps on getting HTTP 503 Service Unavailable error even after the service is back up.

Keepalives on both server and client side are enabled, to no avail.

Restarting the haproxy pod "solves" the problem.

## Expected behavior

After the grpc service is restarted, the client should be able to reconnect normally.

## Steps to reproduce the behavior

My config file:

    global
        maxconn 4000
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
        ssl-default-bind-ciphers TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:EECDH+AESGCM:EDH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!DSS:!AESCCM
        tune.ssl.default-dh-param 2048
        tune.ssl.maxrecord 1460

    defaults
        timeout connect 5s
        timeout client 10m
        timeout server 10m
        timeout tunnel 15m
        default-server init-addr last,libc,none
        option dontlognull

    frontend grpc
        mode http
        bind *:9000 ssl crt mydomain.pem ca-file cacert.crt verify required alpn h2
        default_backend grpc-be

    backend grpc-be
        mode http
        server myservice myservice:9001 check proto h2

Test client (C#):

    class Program
    {
        static void Main(string[] args)
        {
            System.Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "info");
            System.Environment.SetEnvironmentVariable("GRPC_TRACE", "http,api");
            var ch = CreateChannel("mydomain.com:9000", "client.crt", "client.key");
            var client = new TestService.TestServiceClient(ch);
            Run(client);
            Console.WriteLine("press Enter to exit");
            Console.ReadLine();
        }

        private static Channel CreateChannel(string grpcUrl, string grpcCertFile, string nopGrpcKeyFile)
        {
            string grpcCert = File.ReadAllText(grpcCertFile);
            string grpcKey = File.ReadAllText(nopGrpcKeyFile);
            KeyCertificatePair keyCertificatePair = new KeyCertificatePair(grpcCert, grpcKey);
            var channelCredentials = new SslCredentials(null, keyCertificatePair);
            ChannelOption[] channelOptions = new[] {
                    new ChannelOption("grpc.keepalive_time_ms", 30000),
                    new ChannelOption("grpc.keepalive_timeout_ms", 10000),
                };
            return new Channel(grpcUrl, channelCredentials, channelOptions);
        }

        static async void Run(TestService.TestServiceClient client)
        {
            while (true)
            {
                try
                {
                    using (var call = client.StreamUpdates(new StreamUpdatesRequest()))
                    {
                        var responseStream = call.ResponseStream;
                        while (await responseStream.MoveNext())
                        {
                            Console.WriteLine(responseStream.Current);
                        }
                    }
                    Console.WriteLine(DateTime.Now.ToLongTimeString() + "  StreamUpdates done");
                }
                catch (Exception e)
                {
                    Console.WriteLine(DateTime.Now.ToLongTimeString() + "  Exception: " + e);
                }
                await Task.Delay(5_000);
            }
        }
		
    }

## Do you have any idea what may have caused this?

It seems like when the grpc service pod is restarted, haproxy keeps the underlying HTTP/2 connection open. And since the client keeps on trying to open a subchannel inside the same connection, the connection never times out, resulting in a perpetual 503 error.

## Do you have an idea how to solve the issue?

For now we switched to `mode tcp` in both frontend and backend and it is working fine.
But we also need some `mode http` features like ACL's and routing based on URL.

## What is your configuration?

Just the `haproxy:2.1-alpine` standard Docker image running in Google Kubernetes Engine with a `LoadBalancer` (fixed IP) service type.

```
# haproxy -vv
HA-Proxy version 2.1.4 2020/04/02 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [TRACE] trace
        [COMP] compression

# uname -a
Linux haproxy-5f46f9747d-s558w 4.14.91+ #1 SMP Wed Jan 23 21:34:58 PST 2019 x86_64 Linux
# 
```

**Comment by wtarreau** [comment]
This sounds odd, it sounds like a failure to signal the end of the front H2 connection after the last stream when stopping, and failure to process new connections on the backend. Have you tried with an up to date version ? Yours is 7 months old and is affected by 171 known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html

**Comment by rustyx** [comment]
Version 2.2.4 seems to be working better indeed. Thanks
