### ISSUE TITLE
SPOA-SERVER: http-request/http-response send-spoe-group: errors / missing messages when used multiple times

### ISSUE THREAD

**Issue by StanleyP** [haproxy/haproxy#927]
## Detailed description of the problem

I am using SPOE to offload some processing from main HAProxy process. In my scenario I need to call SPOA multiple times during request/response processing, exactly 2x during request processing and 2x during response processing.

But only first occurence of http-request/http-response send-spoe-group is called as seen from SPOA logs. After couple of seconds, 2 errors "Failed to write Agent frame" are seen in HAProxy logs.

```
...
spoa       | 1603786859.880451 [01] Notify frame received: stream-id=15 - frame-id=1
spoa       | 1603786859.880465 [01]   Message 'spoadebug-req' received
spoa       | 1603786859.880502 [01] Ack frame sent: stream-id=15 - frame-id=1
haproxy    | 127.0.0.1:38238 [27/Oct/2020:08:20:59.880] api local/local 16/0/0/0/16 200 110 - - ---- 4/1/0/0/0 0/0 "GET / HTTP/1.1"
spoa       | 1603786859.897278 [01] Notify frame received: stream-id=15 - frame-id=2
spoa       | 1603786859.897286 [01]   Message 'spoadebug-res' received
spoa       | 1603786859.897312 [01] Ack frame sent: stream-id=15 - frame-id=2
spoa       | 1603786889.898889 [01] Disconnect frame received: reason=normal
spoa       | 1603786889.899114 [01] Disconnect frame sent: reason=normal
spoa       | 1603786889.899193 [01] New connection from HAProxy accepted
spoa       | 1603786889.899298 [01] Failed to write Agent frame
spoa       | 1603786889.899343 [01] Close the client socket because of I/O errors
spoa       | 1603786889.899386 [01] New connection from HAProxy accepted
spoa       | 1603786889.899427 [01] Failed to write Agent frame
spoa       | 1603786889.899456 [01] Close the client socket because of I/O errors
...
```

## Expected behavior

All 4 http-request/http-response send-spoe-group are passed to SPOA.

## Steps to reproduce the behavior

1. Please download and unzip attached spoadebug.zip archive to some directory and cd to this directory.
2. Start haproxy and spoa using docker-compose up
3. Call curl http://localhost and see the logs

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

No.

### haproxy.cfg

```
global
  description HAProxy API Gateway (internal)

  master-worker
  nbthread 1

  log stdout format raw local1 info info

  tune.ssl.default-dh-param 2048

  lua-load /main.lua

defaults
  timeout connect 10s
  timeout client  60s
  timeout server  60s

  log global

  mode http
  option dontlognull
  option httplog

frontend ping
  bind :8080

  http-request set-log-level silent
  http-request use-service lua.ping

frontend http
  bind :80

  option http-buffer-request
  filter spoe engine spoadebug config /spoadebug.spoe.conf
  http-request send-spoe-group spoadebug spoadebug-req
  http-response send-spoe-group spoadebug spoadebug-res

  use_backend api

backend api
  http-request set-log-level silent

  server api unix@/tmp/api.sock send-proxy

frontend api
  bind unix@/tmp/api.sock accept-proxy

  http-request set-header x-my-header my-val

  use_backend local

backend local
  server local 127.0.0.1:8080
  filter spoe engine spoadebug config /spoadebug.spoe.conf
  http-request send-spoe-group spoadebug spoadebug-req2
  http-response send-spoe-group spoadebug spoadebug-res2

backend spoadebug-spoe
  mode tcp
  balance roundrobin
  timeout connect 5s
  timeout server  3m
  server spoe-server 127.0.0.1:12345

```

### spoadebug.spoe.conf

```
[spoadebug]
  
spoe-agent spoadebug
  groups spoadebug-req spoadebug-req2 spoadebug-res2 spoadebug-res
  option var-prefix  tfl
  timeout hello      100ms
  timeout idle       30s
  timeout processing 15ms
  use-backend spoadebug-spoe
                       
spoe-group spoadebug-req
  messages spoadebug-req 
                         
spoe-message spoadebug-req
  args method=capture.req.method url=url ver=capture.req.ver hdrs=req.hdrs body_len=req.body_len body=req.body
                       
spoe-group spoadebug-res
  messages spoadebug-res 
                         
spoe-message spoadebug-res
  args hdrs=res.hdrs   
                       
spoe-group spoadebug-req2
  messages spoadebug-req2
                         
spoe-message spoadebug-req2
  args hdrs=req.hdrs 

spoe-group spoadebug-res2
  messages spoadebug-res2

spoe-message spoadebug-res2
  args hdrs=res.hdrs body_len=res.body_len body=res.body
```

### haproxy -vv (Official haproxytech/haproxy-debian:2.2 docker image)

```
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

### uname -a`

```
Linux ubuntu 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

`N/A`

## Additional information (if helpful)

[spoadebug.zip](https://github.com/haproxy/haproxy/files/5444109/spoadebug.zip)

**Comment by capflam** [comment]
It is an issue with the spoa_server. Please see https://www.mail-archive.com/haproxy@formilux.org/msg38484.html and #705.

Here you have 2 agents, not sharing their connections. In debug mode, the spoa_server does not create workers. Thus the connection opened by the first engine, in `http` frontend, will block any new connection attempts from the second engine, in `local` backend.

It is a design issue with the spoa_server.

**Comment by StanleyP** [comment]
Thanks a lot for explanation/clarification.

So if I understand the issue correctly, even turning off debug mode on spoa_server and setting nbthread to 1 thread does not guarantee correct processing? Or am I safe with nbthread 1? What is recommended setting of spoa_server in regard to haproxy configuration then?

Does this mean that the whole SPOP/SPOE/SPOA mechanism is still not quite production ready? This is really important to me, because at the moment I am in the development phase with this feature, but definitely am/was planning to deploy the feature to production.

What I am trying to achieve with SPOP/SPOE/SPOA is kind of traffic monitoring/inspection. Are there any alternative solutions with haproxy or some other complementary software for this? Implement own filter in C? Or use some MITM proxy server before haproxy?

Thanks again for any help.

**Comment by StanleyP** [comment]
I have additional question: You wrote "Here you have 2 agents, not sharing their connections." - Does it mean that both `filter spoe ...` commands create separate connections to SPOA? Is there a way to share single connection to SPOA? In my use case I have potentially many backends that need to talk to the same SPOA so connection sharing could be useful.

**Comment by capflam** [comment]
> So if I understand the issue correctly, even turning off debug mode on spoa_server and setting nbthread to 1 thread does not guarantee correct processing? Or am I safe with nbthread 1? What is recommended setting of spoa_server in regard to haproxy configuration then?

It really depends on your traffic and the number of spoa_server workers. But because each worker accepts only one connection and processes only one message at a time, you may easily hit the spoe processing timeout because messages are queued waiting to be processed. The spoa_server processes messages synchronously. Thus N spoa_server workers will only be able to process N messages at a time. It is clearly a bottleneck. And with several engines, the connection attempts may also be queued waiting a slot.

> Does this mean that the whole SPOP/SPOE/SPOA mechanism is still not quite production ready? This is really important to me, because at the moment I am in the development phase with this feature, but definitely am/was planning to deploy the feature to production.

It is only a spoa_server issue. The current design of the spoa_server is probably limited by the lua. It is hard to execute concurrently several lua scripts using the same stack. In HAProxy, we use a big lock to ensure only one script is executed at a time. The execution is interruptible however.

> 
> What I am trying to achieve with SPOP/SPOE/SPOA is kind of traffic monitoring/inspection. Are there any alternative solutions with haproxy or some other complementary software for this? Implement own filter in C? Or use some MITM proxy server before haproxy?

You may try to evaluate the spoa-exemple, written in C. If you plan to write a filter in C, you may try to extent/fork the spoa-exemple. But definitely, the spoa_server is limited.

> I have additional question: You wrote "Here you have 2 agents, not sharing their connections." - Does it mean that both `filter spoe ...` commands create separate connections to SPOA? Is there a way to share single connection to SPOA? In my use case I have potentially many backends that need to talk to the same SPOA so connection sharing could be useful.

With the current design, all spoe filters are independent and don't share their connections. If you plan to have many engines, you will not be able to use the spoa_server.

**Comment by StanleyP** [comment]
Thanks again for the your answers and clarifications!
If I understand correctly the spoa_example supports all advanced features like async processing, pipelining so it won't be subject to the limitation of spoa_server.
I will try to write new spoa based on spoa_example as you suggested.
We can close this issue or I can report my progress with spoa_example and close later.
Take care.

**Comment by capflam** [comment]
Ok, I close it. About the spoa-exemple, even in sync mode, there is no such issue because it is event driven and a worker is able to handle several connections concurrently. The only problem with the sync mode is it requires much more connections than pipelining/async mode. But it is easier to implement.
