### ISSUE TITLE
Websockets disconnect on lightweight config changes

### ISSUE THREAD

**Issue by robin-anil** [haproxy/haproxy#93]
I don't think this is a version specific bug. Please let me know if it is and you need more details, But I have noticed that when we make any config change, for example, Lets, say we have backend A which is connected to web-sockets, 

Scenario 1: switching backend B or C which are unrelated to A, all the connected WebSockets on A disconnects. 

Scenario 2: when we switch new clusters A to A`, the same thing happens

Questions:
1) How can we avoid the disconnection in Scenario 1?
2) Is there a way of doing Scenarios 2, where we can control the number of reconnects at a steady rate. Right now due to the issue identified in 1, incremental server adds and deletions all cause all connections to disconnect.

Websockets are configured as follows and routed based on path `/ws`

Relevant sections from the config
```
defaults
    log global
    mode http
    compression algo gzip
    compression type text/html text/plain text/css application/javascript application/octet-stream application/json
    option httplog
    option dontlognull
    option redispatch
    option tcp-smart-accept
    option tcp-smart-connect
    option forwardfor if-none
    option splice-auto
    option socket-stats
    option http-buffer-request
    timeout check 5s
    timeout client 300s
    timeout tunnel 60000s
    timeout connect 20s
    timeout http-keep-alive 300s
    timeout http-request 30s
    timeout queue 20s
    timeout server 50s
    hash-balance-factor 125
    balance hdr(Cookie)
    hash-type consistent djb2
    default-server inter 5s fall 3 rise 1

backend ws
    reqidel ^.*x-webkit-deflate-frame.*
    timeout server 60000s
    option http-server-close
    # Health check path.
    option httpchk GET /monitorz/healthcheck?pretty=true
    http-response set-header X-backends api-server-ws
    #enter the IP of your application here
    server node-1 ws-server-1:80 maxconn 500 check
    server node-2 ws-server-1:80 maxconn 500 check
    server node-3 ws-server-1:80 maxconn 500 check

```

**Comment by lukastribus** [comment]
> switching backend B or C

I don't know what "switching a backend" means.


> switch new clusters A to A

Same here.


Please elaborate what the trigger is and what you are actually doing (changing the configuration file on the disk has no effect on haproxy) - are you reloading or restarting haproxy? If so, how?

**Comment by robin-anil** [comment]
Clarification: With switching I mean, making a change to Backend B by adding or removing nodes and doing a seamless config reload as mentioned here.

https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/

**Comment by lukastribus** [comment]
No reload (seamless or otherwise) will ever disconnect existing sessions in flight, only a restart does that.

I suggest you use the support channels to troubleshoot this, as this is not a bug report.

**Comment by robin-anil** [comment]
Thanks for that, I will re-open this if I have better proof of this happening.
