### ISSUE TITLE
Possible isolated peers sending malformed messages

### ISSUE THREAD

**Issue by haproxyFred** [haproxy/haproxy#939]
## Detailed description of the problem

I am reporting this issue on behalf of a haproxy user who cannot provide very much information for security reasons. This is at least to keep traces about this information, for sharing, and to be able to easily update them.

This user has noticed that under heavy load a haproxy peer  could be isolated, possibly sending  data which could not be decoded by several others remote peers. According to "show peers" command output on these remote peers, there are possibly very much protocol errors detected by these remote peers. This leads the remote peers to be disconnected from the peer which seems to send garbage data. I suppose this latter tries to send again and again the same data the remote peers cannot decode.

I have provided the user with several patches so that to have more information about the root cause of this issue, especially one which enable us to store the code line number where the protocol errors are detected. This information has been added to "show peers" command.

## Expected behavior

Any peer should be able to synchronize with any other peer belonging to the same group ("peers" section).

## Steps to reproduce the behavior

I could not reproduce such an issue.

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

No.

## What is your configuration?

Only the stick-table configuration is provided:

```
table cookie type string len 128 size 100k expire 7d store gpc0,http_req_rate(1d),http_req_cnt,http_err_cnt
```
All the peers have this rule configured:
```
http-request track-sc1 req.cook(sesscookie) table cookiepeers/cookie if cookie_sess_present
```
Only the peer which seems to send garbage data is configured with this stickiness rule:

```
stick store-response res.cook(sesscookie) table cookiepeers/cookie if set_cookie_sess status_REDIR
```

## Additional information (if helpful)
Sometimes there is no protocol error detection but some stick-table entries are corrupted, perhaps because the peers managed to decode data which are wrong with malformed stick-table entry keys and irrelevant counter values (unexpected gpc0, http_err_cnt counter values).
The peers data stream is unfortunately ciphered (SSL configuration).

**Comment by wtarreau** [comment]
Merci Fred!

**Comment by wtarreau** [comment]
I've added the relevant tags based on the info you currently have.

**Comment by wtarreau** [comment]
Adding a reference to issue #938 that could possibly be related.

**Comment by wlallemand** [comment]
Hello, I suppose it was fixed with 1dfd4f1. Can we close this now?

**Comment by haproxyFred** [comment]
We hope so. But we are waiting for the client feedback.

**Comment by haproxyFred** [comment]
https://github.com/haproxy/haproxy/commit/1dfd4f106f15bc4e6e992f8babbc863c12975b5a definitively fixed some weird issues but it seems there is possibly at least a remaining one. Waiting for more information.

**Comment by wtarreau** [comment]
So the reporter finally confirmed that one node missed the upgrade and that with all nodes up to date, the bug is definitely gone. Closing now. The backport to 2.2 was already done.
