### ISSUE TITLE
data race found by thread sanitizer

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#95]
here's full build log (too big to copy here)

https://travis-ci.com/chipitsine/haproxy-1/jobs/198820896

**Comment by wtarreau** [comment]
At first glance it seems to be enumerating all variables that are used by multiple threads, which is a bit the purpose of a multi-threaded program :-)  Unless there's something easy to work around, I guess you'll have to disable this test.

**Comment by wtarreau** [comment]
I'm tagging it as invalid for now since it's essentially an issue with the sanitizer (or the way to use it), and closing. Feel free to reference this one later if needed.
