### ISSUE TITLE
memory leak detected by address sanitizer

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#96]
full log:

https://travis-ci.com/chipitsine/haproxy-1/jobs/198816193

leak

```
***  h1    0.1 debug|=================================================================
***  h1    0.1 debug|==5924==ERROR: LeakSanitizer: detected memory leaks
***  h1    0.1 debug|
***  h1    0.1 debug|Direct leak of 1 byte(s) in 1 object(s) allocated from:
***  h1    0.1 debug|    #0 0x4c74dd in __strdup /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:463:3
***  h1    0.1 debug|    #1 0x91fb22 in mworker_env_to_proc_list /home/travis/build/chipitsine/haproxy-1/src/mworker.c:179:17
***  h1    0.1 debug|
***  h1    0.1 debug|SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).
```

**Comment by TimWolla** [comment]
I proposed a patch for this on the list: https://www.mail-archive.com/haproxy@formilux.org/msg33745.html

**Comment by chipitsine** [comment]
I'll run tests with sanitizer soon

**Comment by chipitsine** [comment]
I tested, everything is ok

**Comment by chipitsine** [comment]
I've rebased to current master, enabled address sanitizer and built:

https://travis-ci.org/chipitsine/haproxy-1/jobs/532472001#L2448-L2454

https://travis-ci.org/chipitsine/haproxy-1/builds/532471995

still leaks

**Comment by TimWolla** [comment]
> still leaks

Yes, because my memory-leak patch has not yet been applied.

**Comment by chipitsine** [comment]
Sorry, I saw some discussion on mailing list. I thought similar patch was applied, but I was wrong
