### ISSUE TITLE
Haproxy configuration manual references a no longer existing function

### ISSUE THREAD

**Issue by throwaway8787** [haproxy/haproxy#966]
http://cbonte.github.io/haproxy-dconv/2.2/configuration.html has four examples referencing `reqrep`, but this function actually doesn't exist in 2.2 anymore.

**Comment by wtarreau** [comment]
Shame on me for not having noticed it when I added a few examples for quotes. This part needs to be rewritten to explain the top-down parser anyway. Thanks for the tip!

**Comment by capflam** [comment]
Now backported to 2.3 and 2.2.
