### ISSUE TITLE
Stats page occasionally renders corrupted

### ISSUE THREAD

**Issue by jaroslawr** [haproxy/haproxy#972]
## Detailed description of the problem

Occasionally stats page renders as if it was based on some inconsistent snapshot of the underlying data - some backends instead of being rendered as a green backend row instead render as a "frontend" row, some other backends render blue despite being in completely normal operational state etc. I attach a screen shot that shows the fragment of a stats page that normally is just a list of consecutive backends: w101.foo.com, w102.foo.com, ... They are all healthy, serving traffic normally etc. I blurred the text to anonymise the data. The gray row has "Frontend" written on it although it represents a backend. 

![stats](https://user-images.githubusercontent.com/26233/99809299-62c75a80-2b42-11eb-9f87-7bd3ea173a97.png)

I also see weird peaks in collected stats where e.g. the number of 2xx responses/s occasionally (5 readings per day) comes out as 5 million/s, where the real number is orders of magnitude lower, which I suspect might be related. That goes through some of our custom scripting though and I haven't look at the raw numbers coming out of the stats socket etc.

## Expected behavior

Stats page renders backends as backends.

## Steps to reproduce the behavior

Refresh the stats page until problem occurs.

## What is your configuration?

```
global
        user haproxy
        group haproxy

        nbthread 38
        maxconn 120000
        hard-stop-after 10s

        tune.bufsize 32768
        tune.ssl.default-dh-param 2048
        tune.ssl.cachesize 10000000
        tune.ssl.lifetime 3600

        log /dev/log local0 info info
        log /dev/log local1 notice

        stats socket /run/haproxy/haproxy-node1.sock mode 660 level admin

defaults
        mode http
        option httplog
        option dontlognull
        option forwardfor
        option http-buffer-request

        maxconn 110000

        retries 0
        no option redispatch

        # time client can be idle
        # on timeout: client connection is closed
        timeout client 50000

        # time backend server can be idle
        # on timeout: 504 Gateway Timeout response, client connection is not closed
        timeout server 500

        # time to connect to backend server
        # on timeout: 503 Service Unavailable response, client connection is not closed
        timeout connect 5

        # time to wait in queue for an available backend server
        # on timeout: 503 Service Unavailable response, client connection is not closed
        timeout queue 5

frontend xyz.com
        bind *:80
        bind *:443 ssl crt /etc/haproxy/xyz.com.pem alpn h2,http/1.1
        default_backend workers

        log global
        http-request set-log-level silent unless { rand(5000) lt 5 }

backend workers
        balance leastconn
        option httpchk
        http-check send meth HEAD uri /worker/healthcheck
        default-server check inter 1000 maxqueue 1

        server w101.xyz.net_8082 w101.xyz.net:8082 weight 6 maxconn 64
        server w102.xyz.net_8082 w102.xyz.net:8082 weight 64 maxconn 64
        server w103.xyz.net_8082 w103.xyz.net:8082 weight 64 maxconn 64
        server w104.xyz.net_8082 w104.xyz.net:8082 weight 64 maxconn 64
        server w105.xyz.net_8082 w105.xyz.net:8082 weight 32 maxconn 32
        server w106.xyz.net_8082 w106.xyz.net:8082 weight 64 maxconn 64
        server w107.xyz.net_8082 w107.xyz.net:8082 weight 64 maxconn 64
        server w108.xyz.net_8082 w108.xyz.net:8082 weight 80 maxconn 80
        server w109.xyz.net_8082 w109.xyz.net:8082 weight 128 maxconn 128
        server w110.xyz.net_8082 w110.xyz.net:8082 weight 80 maxconn 80
        ...
        server w567.xyz.net_8082 w567.xyz.net:8082 weight 128 maxconn 128
        server w568.xyz.net_8082 w568.xyz.net:8082 weight 128 maxconn 128
        server w999.xyz.net_8082 w999.xyz.net:8082 weight 60 maxconn 60

listen stats
        bind *:7655
        log global
        stats enable
        stats uri /
        stats refresh 5s
        acl valid_src src 10.0.0.0/8 172.16.0.0/12 127.0.0.0/8 5.135.236.132
        http-request deny if ! valid_src
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3.0-1c0a722 2020/11/05 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.0.html
Running on: Linux 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=38).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

**Comment by a-denoyelle** [comment]
I have tried to reproduce the issue but to no avail. Do you observe this frequently ?

**Comment by jaroslawr** [comment]
@a-denoyelle Its definitely rare and hard to reproduce manually.

**Comment by wtarreau** [comment]
I don't even see how it is technically possible at all. @jaroslawr could you send me privately a dump of such a stats page ? (not the screenshot, the HTML output by pressing Ctrl-S in the browser) ? I want to see there if we spot any pattern in the output code that could indicate that some entries maybe couldn't be added or something like this.

The reason why it shouldn't happen is that there are two embedded loops, one used to dump proxies and one for servers. If you're seeing non-servers in the middle of servers, it would imply getting out of the loop, but then it cannot go on inside the loop again. However if some entries failed to be dumped for whatever reason and were not detected as a failure, they could possibly be missed. It would just be extremely strange that the next header line would be skipped as well :-/

**Comment by jaroslawr** [comment]
@wtarreau I didn't preserve the HTML source and it is hard to reproduce this, so I sent you the best I've got so far - the uncensored screenshot.

**Comment by wtarreau** [comment]
Thanks @jaroslawr it was helpful. For others, it's visible in the capture that what is reported as a frontend actually is not a frontend but a regular server in the middle of all other ones, because all the numbers, byte counts, limits etc match. In addition, where it happens it looks like it punches a hole in the numbering (for example we could have servers 240-245 then a frontend then it goes on with 249). Given that frontends and listeners use the fe_counters struct and that backends and servers use the be_counters struct, my first estimate is that the numbers are properly extracted from the server struct (and the be_counters), are placed in the stats fields, but later are possibly corrupted and the object type is turned to a frontend, causing the HTML output driver to report them wrong. But that's still something totally new to me and I'm still in lack of imagination to understand what's happening there :-/

**Comment by capflam** [comment]
A push a patch that should hopefully fix this issue. For me, it is a thread-safety issue, when several stats page are requested concurrently.

**Comment by capflam** [comment]
Just a note, because it is a bit hard to observe on the html page (but easier on the cvs output, see #992), I'll mark it as fixed. If I'm wrong, feel free to reopen the issue.
