### ISSUE TITLE
cpu usage is high after Haproxy version upgrade (  2.2.5 )

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#974]
## Detailed description of the problem

We are using cpu pinning and assigning cores by http bind and ssl bind.
We experienced high cpu usage in http bind assigned cores after version upgrade ( 2.2.5 )
We fixed high cpu usage after downgrade to 2.2.4 

## Steps to reproduce the behavior
1. use thread mode
2. cpu pinning by http and ssl
3. use 2.2.5 version

## Do you have an idea how to solve the issue?
I suspect part of http bind because  assigned cores for http bind are high usage.

## What is your configuration?
Below is a summarized configuration.
```
global 
nbthread 21

cpu-map 1-15 0-11 x x x 
cpu-map 16-21 12-17

frontend http
bind :80 process 1/16-21

frontend https
bind unix@https tfo accept-proxy process 1/16-21

listen ssl
mod tcp
bind :443 ssl curves xxxx process 1/1-15
server https unix@/var/run/https send-proxy-v2 maxconn 500000
```

**16-21 cores are high cpu usage**

## Output of `haproxy -vv` and `uname -a`

I already mentioned that we changed version ( 2.2.5 -> 2.2.4) and problem was fixed.

```
HA-Proxy version 2.2.4-de45672 2020/01/21 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.4.html
Running on: Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = gcc
  CFLAGS  = -O2 -march=native -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DTLS_TICKETS_NO=4
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATL
AS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=20).
Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-11)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

## Additional information (if helpful)
os : centos 7

**Comment by wtarreau** [comment]
Could you please also post the output of haproxy -v on the faulty one, just in case we can spot something ?

**Comment by wtarreau** [comment]
Also running "perf top" a few seconds and showing the first lines may help: it could indicate roughly where something is getting weird.

**Comment by zino7825** [comment]
@wtarreau okey i will add what you requested after re-upgrading

I wonder that is it spec in Haproxy 2.2.x ??

This graph is RPS chart.
  - high graph : 2.2.x version server
  - low graph : 2.1.x version server

if method:POST AND protocol: http/1.1
![image](https://user-images.githubusercontent.com/5656233/100352449-56ef0300-3030-11eb-9f04-b2b6afd33094.png)

if method: POST AND protocol: http/2.0
![image](https://user-images.githubusercontent.com/5656233/100352666-ad5c4180-3030-11eb-82cb-9019b786004c.png)

if method GET is same balance.

There is no problem if we apply 2.2.x version to entire servers.

**Comment by wtarreau** [comment]
We faced this already in the past, I don't remember what issue it was, I think it was @wdauchy who encountered the exact same situation, but I could be wrong. I seem to remember that we noticed that 2.2 was able to absorb requests and responses much faster than 2.1 and took a higher share of the load, resulting in a higher CPU usage there and lower one on the other nodes.

BTW if you're about to upgrade, we're going to issue 2.2.6 and 2.3.2 probably tomorrow or early next week, after having fixed quite a number of annoying bugs. If you delay your upgrade by a day or two you may save yet another one later. Just my two cents :-)

**Comment by zino7825** [comment]
* `haproxy -v` 
```
[root@xxx ~]# ha version
HA-Proxy version 2.2.5-34b2b10 2020/01/21 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.5.html
Running on: Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64
```
* perf top 
![image](https://user-images.githubusercontent.com/5656233/100417737-e8a85000-30c4-11eb-977c-3c701e31a329.png)

* Same role server group 
* version : 2.2.5
![image](https://user-images.githubusercontent.com/5656233/100417835-1392a400-30c5-11eb-8c9a-63c2377672dc.png)
* version : 2.2.4
![image](https://user-images.githubusercontent.com/5656233/100417852-19888500-30c5-11eb-9a35-de50cbd616ad.png)

**Comment by zino7825** [comment]
> We faced this already in the past, I don't remember what issue it was, I think it was @wdauchy who encountered the exact same situation, but I could be wrong. I seem to remember that we noticed that 2.2 was able to absorb requests and responses much faster than 2.1 and took a higher share of the load, resulting in a higher CPU usage there and lower one on the other nodes.
> 

if i use same version 2.2.x to same service group, there is no balance problem. 
but 2.2.5 version server has been used high cpu usage if i use mixed version 2.2.4 and 2.2.5.
> BTW if you're about to upgrade, we're going to issue 2.2.6 and 2.3.2 probably tomorrow or early next week, after having fixed quite a number of annoying bugs. If you delay your upgrade by a day or two you may save yet another one later. Just my two cents :-)

**Comment by wtarreau** [comment]
This fix in 2.2.5 addressed a bug in the scheduler that was introduced in 2.0: `563eede24 ("BUG/MEDIUM: task: bound the number of tasks picked from the wait queue at once")`

A potential problem was that the scheduler would process an unlimited number of tasks under load and create a big unfairness resulting in some threads possibly staying stuck processing plenty of tasks and not doing I/O, then catching up with I/Os. I really think this could produce the effect you observed on the older versions whose load drops when shared with a more fair process.

**Comment by wdauchy** [comment]
> We faced this already in the past, I don't remember what issue it was, I think it was @wdauchy who encountered the exact same situation, but I could be wrong. I seem to remember that we noticed that 2.2 was able to absorb requests and responses much faster than 2.1 and took a higher share of the load, resulting in a higher CPU usage there and lower one on the other nodes.

yes, it looks very similar to what we saw as well, at least while speaking about v2.1 to v2.2 migration: higher cpu usage (between 5 and 10% depending on cases) but much better QPS capacity. and the graph above seems to confirm that.

the number I remember were up to x3 in qps capacity in some ideal cases (http1 pipelining) from 2.1 and 2.2.

**Comment by zino7825** [comment]
This problem does not occur in version 2.2.13.
Connection stuck and unbalanced CPU usage.

**Comment by wtarreau** [comment]
Great, thanks for confirming. By the way if you're looking for high RPS rates, you may want to upgrade to 2.3 (which improved scalability) or even 2.4 (warning, still in development).

**Comment by wtarreau** [comment]
By the way, could we close this issue then if it's fixed ?

**Comment by zino7825** [comment]
@wdauchy I will monitor for another week. 
I'll share it again. how about close the issue after then?

**Comment by wtarreau** [comment]
Fine by me, thank you!

**Comment by wtarreau** [comment]
Ah, maybe you meant "then" in the meaning of "after another week", reopening :-)

**Comment by capflam** [comment]
@zino7825, can we close this issue now ? Does it work as expected now ?

**Comment by zino7825** [comment]
@capflam yes. you can close it.

**Comment by capflam** [comment]
Thanks
