### ISSUE TITLE
Abstract Unix sockets need to preserve address length

### ISSUE THREAD

**Issue by tmccombs** [haproxy/haproxy#977]
## Detailed description of the problem

Using an abstract unix socket does not work as expected. From the man page for the unix address family:

>an abstract socket address is distinguished (from a pathname socket) by the fact that sun_path[0] is a null byte ('\0').  The socket's address in this namespace is given by the additional bytes  in  sun_path that *are covered by the specified length of the address structure.  (Null bytes in the name have no special significance.)*
(emphasis mine)

However, the code for parsing a `abns@` address does not have any method of preserving the length of the socket name. So if, for example the address was given as `abns@test`, then instead of using the abstract unix socket "test" it will use the abstract unix socket of "test" followed by 103 NUL bytes, which is almost certainly not what the user wanted.

## Expected behavior

If you use a server line like 
```
server t1 abns@test
```
It should forward to the abstract unix socket named "test", instead of `"test\0\0\0\0\0..."`. 

## Steps to reproduce the behavior

1. Create haproxy configuration with something like the following:
    ```
    listen test
      bind :9000
      mode tcp
      server t1 abns@test
    ```
2. Listen on the "test" abstract unix socket, with something like: `socat abstract-listen:test,fork exec:cat`
3. Notice that it doesn't foward to the unix socket listener

## Do you have any idea what may have caused this?

The code in `str2sa_range` for abstract unix sockets (https://github.com/haproxy/haproxy/blob/a9ffc416377e0df9859526dc3c1d769c6a68636f/src/tools.c#L1031) doesn't preserve the length of the socket name, and the server struct doesn't preserve the address length, so ultimately when `connect` is called, it is passed with the wrong address length.

## Do you have an idea how to solve the issue?

`str2sa_range` would need to return the final length of the address structure, `struct server` would need to preserve that result, and calls such as `connect` would need to use that length rather than relying on the result of `get_addr_len`.

Alternatively, stop supporting  abstract unix sockets.  Given that it is currently almost completely broken, it seems likely this feature is not actually used in practice.

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.19-aceb6cb 2020/11/06 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2_JIT=1 USE_REGPARM=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=12).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

Although I discovered this while reading the source code on master.

**Comment by lukastribus** [comment]
This is expected behavior, as documented:

```
 Note: regarding Linux's abstract namespace sockets, HAProxy uses the whole
       sun_path length is used for the address length. Some other programs
       such as socat use the string length only by default. Pass the option
       ",unix-tightsocklen=0" to any abstract socket definition in socat to
       make it compatible with HAProxy's.
```


> Alternatively, stop supporting abstract unix sockets. Given that it is currently almost completely broken, it seems likely this feature is not actually used in practice.

That's just not true, it works completely fine and used very often.

**Comment by tmccombs** [comment]
Ah, I see. I missed that in the documentation. I'm fine with closing this then.
