### ISSUE TITLE
timeout http-keep-alive doesn't work after upgrade to 2.2.5

### ISSUE THREAD

**Issue by axel7born** [haproxy/haproxy#984]
## Detailed description of the problem
After updating haproxy from version 1.9.15 to version 2.2.5, we see that connections are not closed after `timeout http-keep-alive`.
With version 1.9.15. a tcp connection is closed, if the client doesn't send a new request for a longer time than specified by timeout http-keep-alive.
With version 2.2.5 this doesn't happen.
We also tested with 2.3 and it doesn't work here either.

## Expected behavior
The tcp connection should be closed by haproxy after the timeout as explained in the documentation.

## Steps to reproduce the behavior

1.  Open a tcp connection vie netcat or openssl s_client.
```
openssl s_client -connect host.example.com:https
``` 
2. Send a request 
```
GET / HTTP/1.1
HOST:host.example.com.com

```
3. Wait for the time specified by `timeout http-keep-alive`

## Do you have any idea what may have caused this?
No.
## Do you have an idea how to solve the issue?
No.
## What is your configuration?

```
global
    log /run/log-haproxy len 4096 format rfc3164 syslog info
    daemon
    nbthread 4
    user vcap
    group vcap
    maxconn 512000
    spread-checks 4
    tune.ssl.default-dh-param 2048
    tune.bufsize 35840
    tune.maxrewrite 4096
    stats socket /var/vcap/sys/run/haproxy/stats.sock mode 600 expose-fd listeners level admin
    stats timeout 2m
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11
    ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:AES128-SHA256:AES128-SHA
    ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11
    ssl-default-server-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:AES128-SHA256:AES128-SHA

defaults
    log global
    option log-health-checks
    option log-separate-errors
    maxconn 512000
    option http-server-close
    option httplog
    option forwardfor
    option contstats
    timeout connect         30000ms
    timeout client          960000ms
    timeout server          960000ms
    timeout tunnel          3600000ms
    timeout http-keep-alive 60000ms
    timeout http-request    90000ms
    timeout queue           30000ms

frontend http-in
    mode http
      grace 15000
    bind :80
log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslc %sslv"
capture request header User-agent len 256
no option http-server-close

frontend https-in
    mode http
      grace 15000
    bind :443  ssl crt-list /var/vcap/jobs/haproxy/config/ssl/crt-list  ca-file /etc/ssl/certs/ca-certificates.crt verify optional
    option tcpka
log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslc %sslv"
capture request header User-agent len 256
no option http-server-close

# Default Backend {{{
backend http-routers

# Default Backend {{{
backend http-routers
    mode http
    balance roundrobin
    no option http-server-close
http-reuse safe
option prefer-last-server

        errorfile 503 /var/vcap/jobs/haproxy/errorfiles/custom503.http
        option httpchk GET /health

  server node0 10.1.1.8:443 check inter 10  00 port 8080 ssl verify required ca-file /var/vcap/jobs/haproxy/config/backend-ca-certs.pem verifyhost <host>
# }}}

```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.5-34b2b10 2020/11/05 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.5.html
Running on: Linux 4.15.0-122-generic #124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=yes USE_STATIC_PCRE2=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE +STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.4.1
Built with network namespace support.
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : no (libpcre2 build without JIT?)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 5.4.0 20160609

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

uname -a
Linux d005cd55-92ff-4fd9-a01e-a574ae6c4683 4.15.0-122-generic #124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces
No crash.

```
(paste your output here)
```

**Comment by a-denoyelle** [comment]
It seems the issue is triggered when using the ssl on the bind directive. I'm investigating on it.

**Comment by haproxyFred** [comment]
I have "git bisected" 2.2 branch. The result would be that this commit has broken something:

commit 2c1f37d3537c725e87c728bd2c5e7d3b380cdd37 (HEAD)
Author: Willy Tarreau <w@1wt.eu>
Date:   Wed Mar 4 17:50:02 2020 +0100

    OPTIM: mux-h1: subscribe rather than waking up at a few other places
    
    This is another round of conversion from a blind tasklet_wakeup() to
    a more careful subscribe(). It has significantly improved the number
    of function calls per HTTP request (/?s=1k/t=20) :

**Comment by haproxyFred** [comment]
This issue is reproducible with such a configuration file:
``
defaults
    log global
    timeout connect         30000ms
    timeout client          960000ms
    timeout server          960000ms
    timeout http-keep-alive 5s

frontend https-in
    mode http
    bind 127.0.0.1:8080
    default_backend http-routers

backend http-routers
    mode http
    server node0 127.0.0.1:1080
``

**Comment by haproxyFred** [comment]
@a-denoyelle I have removed my previous comments which were due to wrong testing on my side.

**Comment by a-denoyelle** [comment]
My initial assumption is also wrong, the bug can be triggered with a plain connection.

**Comment by capflam** [comment]
I'm able to reproduce the bug and indeed the http-keep-alive timeout is no more considered. I'm on a fix.

**Comment by capflam** [comment]
@axel7born, could you test the following patch please ? I'm pretty sure it works but a confirmation is still good.

[0001-BUG-MINOR-mux-h1-Handle-keep-alive-timeout-for-idle-.patch.txt](https://github.com/haproxy/haproxy/files/5622158/0001-BUG-MINOR-mux-h1-Handle-keep-alive-timeout-for-idle-.patch.txt)

**Comment by axel7born** [comment]
Hi @capflam, I tested your patch and can confirm that it works.
Thanks a lot for this fast fix!
:thumbsup:

**Comment by capflam** [comment]
Thanks for the quick feedback

**Comment by wdauchy** [comment]
ah interesting, I was looking for an-already-made report, and I see there is also already a fix
thanks @capflam

**Comment by wdauchy** [comment]
@capflam was it introduced by 
commit 69f2cb8df386cc5eee19f7d51da32570cbc1efe8 ("BUG/MINOR: mux-h1: Be sure to only set CO_RFL_READ_ONCE for the first read") ? Because it seems like I did not had this issue in v2.2.3 (to be confirmed though) and this commit was introduced in v2.2.5

**Comment by capflam** [comment]
Hum, I don't know. I was too lazy to bisect :) But I don't think so. For me, the commit 2c1f37d353, first pointed by @haproxyFred, is a better candidate. However the commit ca39747dcf is required to observe the bug I guess. Otherwise you will just have no timeout at all...

**Comment by wdauchy** [comment]
ah thanks, interesting pointer

**Comment by capflam** [comment]
FYI, I pushed the patch in the 2.4-dev.
