### ISSUE TITLE
2.4: Vary handling of cache affected by hash collisions

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#988]
## Detailed description of the problem

It is possible to make HAProxy deliver unacceptable cached responses to a client.

## Expected behavior

HAProxy must never send unacceptable responses.

## Steps to reproduce the behavior

```
[timwolla@~]curl -v -o /dev/null 'http://localhost:8080'  -H 'accept-encoding: br,gzip,xxx,jdcqiab' 2>&1 |grep content-encoding
< content-encoding: br
[timwolla@~]curl -v -o /dev/null 'http://localhost:8080'  -H 'accept-encoding: gzip' 2>&1 |grep content-encoding
< content-encoding: br
```

## Do you have any idea what may have caused this?

`crc32(gzip) ^ crc32(br) ^ crc32(xxx) ^ crc32(jdcqiab)` is equal to `crc32(gzip)`

## Do you have an idea how to solve the issue?

The best solution probably would be that `accept_encoding_normalizer` only handles known encodings and returns `1` on unknown encodings, causing such requests to not be cached. The resulting hash could be an 8-bit integer with one bit for each:

1. gzip
2. br
3. deflate
4. compress
5. identity

It would require an HAProxy update in case a new common encoding method is deployed, but such a patch should be safe to backport.

## What is your configuration?

(same as in #987)

```
frontend fe
	mode http
	bind *:8080

	use_backend http

backend http
	mode http

	http-request set-header host www.youtube.com
	http-request cache-use my_cache
	
	# Force the response to be cacheable
	http-response set-header cache-control "public, max-age=600"
	http-response del-header pragma
	http-response del-header expires
	http-response set-header vary accept-encoding

	http-response cache-store my_cache
	
	server youtube www.youtube.com:443 ssl verify none sni str(www.youtube.com)

cache my_cache
	total-max-size 50
	max-age 30
	process-vary 1
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.4-dev2-324344-15 2020/12/02 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.4.0-194-generic #226-Ubuntu SMP Wed Oct 21 10:19:36 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_OPENSSL=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 5.4.0 20160609

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

## If HAProxy crashed: Last outputs and backtraces

n/a

**Comment by wlallemand** [comment]
Thanks for the report, @rlebreton is working on it!

**Comment by TimWolla** [comment]
Awesome!

Note: This probably also affects the `Referer` response header. I did not test that, because I have no need for varying on the Referer. I'm not even sure how useful a vary on the `Referer` is, I expect it to contain too many possible values to be useful.

Anyway: A simple solution to make that one more resilient against cache poisoning might be seeding the hash used for the `Referer` with some random bytes coming from a CSPRNG when HAProxy starts up. Then an attacker needs to find out the seed before they are able to intentionally create hash collisions.

**Comment by rlebreton** [comment]
Unlike with the accept-encoding header, where you could prevent a client from getting the resources he's looking for (as you showed), a hash collision on the referer part seems less dangerous. The Referer support in the Vary came from a Fastly blog post where they described a case in which a server might want to vary on the referer. It would be a server that wants to display a welcome banner to clients that come from another website than their own.
This use case is probably rare and I'll focus more on the accept-encoding normalizer for now. We will probably end up supporting an explicit subset of accepted encodings as you suggested, so the hash related risks will be removed.

**Comment by TimWolla** [comment]
This is not actually fixed yet. I'll send a patch.
