### ISSUE TITLE
A lot of warnings

### ISSUE THREAD

**Issue by icebluey** [haproxy/haproxy#997]
\# GCC Version:
gcc version 10.2.0 (GCC) 
\# Haproxy Version:
haproxy 2.3.2

`for contrib in halog ip6range; do`
 `    make -C contrib/$contrib SBINDIR=/usr/bin OPTIMIZE= CFLAGS="-O2 -g" LDFLAGS="-Wl,-z,relro -Wl,-z,now"`
`done`
# output:

make: Entering directory '/tmp/haproxy-2.3.2/contrib/halog'
gcc   -o halog -I../../include ../../src/ebtree.c ../../src/eb32tree.c ../../src/eb64tree.c ../../src/ebmbtree.c ../../src/ebsttree.c ../../src/ebistree.c ../../src/ebimtree.c halog.c fgets2.c
In file included from ../../src/ebtree.c:21:
../../include/import/ebtree.h: In function ‘__eb_insert_dup’:
../../include/import/ebtree.h:471:34: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  471 |  eb_troot_t *new_left = eb_dotag(&new->branches, EB_LEFT);
      |                                  ^~~~~~~~~~~~~~
../../include/import/ebtree.h:472:34: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  472 |  eb_troot_t *new_rght = eb_dotag(&new->branches, EB_RGHT);
      |                                  ^~~~~~~~~~~~~~
../../include/import/ebtree.h:473:34: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  473 |  eb_troot_t *new_leaf = eb_dotag(&new->branches, EB_LEAF);
      |                                  ^~~~~~~~~~~~~~
../../include/import/ebtree.h:490:40: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  490 |   head->branches.b[EB_RGHT] = eb_dotag(&new->branches, EB_NODE);
      |                                        ^~~~~~~~~~~~~~
../../include/import/ebtree.h:495:39: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  495 |   new->branches.b[EB_LEFT] = eb_dotag(&sub->branches, EB_LEAF);
      |                                       ^~~~~~~~~~~~~~
../../include/import/ebtree.h:508:37: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  508 |   head->branches.b[side] = eb_dotag(&new->branches, EB_NODE);
      |                                     ^~~~~~~~~~~~~~
../../include/import/ebtree.h:513:39: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  513 |   new->branches.b[EB_LEFT] = eb_dotag(&sub->branches, EB_NODE);
      |                                       ^~~~~~~~~~~~~~
../../include/import/ebtree.h: In function ‘__eb_delete’:
../../include/import/ebtree.h:761:32: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  761 |  gparent->b[gpside] = eb_dotag(&parent->branches, EB_NODE);
      |                                ^~~~~~~~~~~~~~~~~
../../include/import/ebtree.h:767:14: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  767 |     eb_dotag(&parent->branches, pside);
      |              ^~~~~~~~~~~~~~~~~
../../include/import/ebtree.h:770:14: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  770 |     eb_dotag(&parent->branches, pside);
      |              ^~~~~~~~~~~~~~~~~
In file included from ../../include/import/eb32tree.h:24,
                 from ../../src/eb32tree.c:23:

\.
\.
\.

In file included from halog.c:26:
../../include/import/ebsttree.h:278:24: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  278 |    new_left = eb_dotag(&new->node.branches, EB_LEFT);
      |                        ^~~~~~~~~~~~~~~~~~~
../../include/import/ebsttree.h:279:24: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  279 |    new_rght = eb_dotag(&new->node.branches, EB_RGHT);
      |                        ^~~~~~~~~~~~~~~~~~~
../../include/import/ebsttree.h:280:24: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  280 |    new_leaf = eb_dotag(&new->node.branches, EB_LEAF);
      |                        ^~~~~~~~~~~~~~~~~~~
../../include/import/ebsttree.h:281:24: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  281 |    old_node = eb_dotag(&old->node.branches, EB_NODE);
      |                        ^~~~~~~~~~~~~~~~~~~
../../include/import/ebsttree.h:303:10: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  303 |   root = &old->node.branches;
      |          ^~~~~~~~~~~~~~~~~~~
../../include/import/ebsttree.h:319:27: warning: taking address of packed member of ‘struct eb_node’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  319 |  root->b[side] = eb_dotag(&new->node.branches, EB_NODE);
      |                           ^~~~~~~~~~~~~~~~~~~
In file included from ../../include/import/eb32tree.h:24,
                 from halog.c:23:
halog.c: In function ‘main’:
halog.c:1255:39: warning: converting a packed ‘struct eb_node’ pointer (alignment 1) to a ‘struct url_stat’ pointer (alignment 8) may result in an unaligned pointer value [-Waddress-of-packed-member]
 1255 |     ustat = container_of(node, struct url_stat, node.url.node);
      |                                       ^~~~~~~~
../../include/import/ebtree.h:321:77: note: in definition of macro ‘container_of’
  321 | #define container_of(ptr, type, name) ((type *)(((void *)(ptr)) - ((long)&((type *)0)->name)))
      |                                                                             ^~~~
../../include/import/ebtree.h:376:8: note: defined here
  376 | struct eb_node {
      |        ^~~~~~~
halog.c:64:8: note: defined here
   64 | struct url_stat {
      |        ^~~~~~~~
In file included from ../../include/import/eb32tree.h:24,
                 from halog.c:23:
halog.c:1290:38: warning: converting a packed ‘struct eb_node’ pointer (alignment 1) to a ‘struct url_stat’ pointer (alignment 8) may result in an unaligned pointer value [-Waddress-of-packed-member]
 1290 |    ustat = container_of(node, struct url_stat, node.url.node);
      |                                      ^~~~~~~~
../../include/import/ebtree.h:321:77: note: in definition of macro ‘container_of’
  321 | #define container_of(ptr, type, name) ((type *)(((void *)(ptr)) - ((long)&((type *)0)->name)))
      |                                                                             ^~~~
../../include/import/ebtree.h:376:8: note: defined here
  376 | struct eb_node {
      |        ^~~~~~~
halog.c:64:8: note: defined here
   64 | struct url_stat {
      |        ^~~~~~~~
make: Leaving directory '/tmp/haproxy-2.3.2/contrib/halog'

make: Entering directory '/tmp/haproxy-2.3.2/contrib/ip6range'
gcc -Wl,-z,relro -Wl,-z,now  -o ip6range ip6range.c
ip6range.c:317:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
  317 | main(int argc, char **argv)
      | ^~~~
make: Leaving directory '/tmp/haproxy-2.3.2/contrib/ip6range'

**Comment by wtarreau** [comment]
This is known, these warnings are bogus but addressing them in auxiliary tools will be a pain until we change their build process. Thus I suggest that we postpone this fix.

**Comment by wtarreau** [comment]
This was addressed as part of the contrib reorganization in 2.4 and the makefiles now pass the appropriate build options for the compiler. No issues here even with gcc 11 thus I'm closing.
